### ISSUE TITLE
Suddenly not in party anymore.

### ISSUE THREAD

**Issue by JebusAlmighty** [HabitRPG/habitica#2659] opened 2014-01-30 19:18 UTC
I'm suddenly not a member in The Determined Ones party anymore.

**Comment by JebusAlmighty** [comment] 2014-01-30 19:21
For some reason, I'm only having this problem on Google Chrome, but not Firefox.

**Comment by Rahenna** [comment] 2014-01-31 16:57
Same here - no party in Chrome, all okay in Firefox.

**Comment by lefnire** [comment] 2014-01-31 16:59
Sounds like y'all might be part of multiple parties, and one (or more) are empty. When you see the blank party session, go to your party page and see if there's a "create party" dialog, or an empty (but existing) party. If No. 2, leave that party and refresh. Repeat until you see your real party

**Comment by Rahenna** [comment] 2014-01-31 17:03
On the party page, it says:

You are not in a party. You can either create one and invite friends, or if you want to join an existing party, have them enter: (code)

But this is ONLY in Chrome.  In Firefox, my party is there as normal/expected.  Weird.

**Comment by sonoftheking** [comment] 2014-02-05 04:39
I can confirm problem, and might know why it's happened...

How to reproduce [I think]:
i. [I was L1/2] Got invited to join party [a L50+ friend created & invited me]
ii. I entered the party code, and joined the party. I could see it and who's in it etc.
iii. I went to tasks and back to Party page, and then I couldn't see the party any more. Got the same "You are not in a party. You can either create one and invite friends, or if you want to join an existing party, have them enter: (code)" message

It resolved it self when I levelled up to L3 [gotten the "hey you can join a party" dialogue / hint] and now I can see the party again.

Potential Solution:
I think the fix for this is to hide [or grey out] the Party tab until you reach L3 [maybe include a tool tip when hovering over Party tab.

**Comment by deilann** [comment] 2014-02-05 04:43
No, you should be able to be in a party until level 3... Jason the Guide is
just letting you know they exist.

**Comment by SabreCat** [comment] 2014-02-05 04:50
Sometimes the Party page falls behind the times, and says you're not in a party when you in fact are. A refresh clears it up. The question becomes, why does it do that and how can we fix it?

**Comment by deilann** [comment] 2014-02-05 04:51
Is it that it falls behind the times or that it renders a default and the
party page overlays that if you're in one?

**Comment by SabreCat** [comment] 2014-02-05 04:54
@deilann: You're probably right. I know I've seen the "you're not in a party" appear during loading times as well.

**Comment by colegleason** [comment] 2014-02-05 05:33
I think the problem is that fetching the party can be a long request. Right?

On Tue, Feb 4, 2014 at 10:54 PM, Sabe Jones notifications@github.comwrote:

> @deilann https://github.com/deilann: You're probably right. I know I've
> seen the "you're not in a party" appear during loading times as well.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/HabitRPG/habitrpg/issues/2659#issuecomment-34137711
> .

## 

Cole Gleason
Student, University of Illinois at Urbana-Champaign
Computer Science, Class of 2015
cg@colegleason.com | colegleason.com

**Comment by SabreCat** [comment] 2014-02-06 00:34
@colegleason: Could well be. Misleading users about their status seems problematic even if we can't shorten the turnaround time, though.

**Comment by deilann** [comment] 2014-02-11 10:29
Put in a PR to let people know about this on the Create a Party page.

**Closed as completed by deilann** 2014-02-11 10:29 UTC

**Comment by sonoftheking** [comment] 2014-02-12 02:36
May I ask what a PR is?

**Comment by sonoftheking** [comment] 2014-02-12 02:42
I think I found it, guessing it's a Pull Request?

So may I rather ask what a LFG link is?

**Comment by deilann** [comment] 2014-02-13 01:28
@sonoftheking LFG = Looking for Group. That part is unrelated to this ticket. The related part is in the shared PR, talking about how your party may just be taking a long while to fetch.

**Comment by sonoftheking** [comment] 2014-02-13 01:42
@deilann Thanks for the clarification
