### ISSUE TITLE
Custuom Day Reset leads to issues: unable to create new dailies at certain day of the week & weekly dailies show up on the wrong day.

### ISSUE THREAD

**Issue by fghber** [HabitRPG/habitica#8833] opened 2017-06-22 23:04 UTC
[//]: # (Fill out relevant information - UUID is found in Settings -> API)
### General Info
  * UUID: 2379dd46-aaf9-4b95-80fe-cd89f62e5864
  * Browser: Microsoft Edge 40.15063.0.0/Chrome
  * OS: Windows 10

### Description
A while ago on a Sunday I have changed my day reset time to one hour earlier the midnight (PST). First, I did not notice any issue. But the next week I noticed some of my weekly tasks scheduled for Sunday/Monday did not show up on the correct day. This this was a minor issue for me I ignored it for a while. But later, I learned I was unable to create new dailies on Sunday. I tried to reload the browser (without Cache, etc.), use a different browser, etc. - without success.
Since I was suspicious about the custom day reset I set switched back to regular value and all the sudden I could create new dailies and all my tasks showed up at the right day again.
I guess the offset is not taken into consideration on all relevant places in the code.

Could be related to #8182 

#### Console Errors
None.

**Comment by majestic-owl448** [comment] 2017-06-23 06:57
This is not a bug... it's the behaviour for setting a custom day start time before midnight, look here: http://habitica.wikia.com/wiki/Custom_Day_Start#Examples_and_a_Warning_about_Late_Custom_Day_Start_Times

Also, now the best place to report a bug is the Report a Bug guild inside Habitica

**Comment by fghber** [comment] 2017-06-23 14:58
Okay, wrong show up on wrong day may be not a bug, but a feature.
What about the problem to create dailies?

**Comment by Alys** [comment] 2017-06-23 15:00
@fghber As @Ieahleen says, that behaviour is intentional, and bugs should be reported in the Report a Bug guild (from the Guilds or Help menu on the website, and from Guilds on the app). It's rare that a bug needs to be reported in GitHub and if it does, a moderator would notify you of that. The problem with creating a Daily on Sunday is probably this issue: https://github.com/HabitRPG/habitica/issues/5525

**Comment by fghber** [comment] 2017-06-23 15:00
I have reported the bug in the bug guild before and was told to report it here!

**Comment by fghber** [comment] 2017-06-23 15:02
Thanks for closing! 👍

**Comment by Alys** [comment] 2017-06-23 15:03
Ah, sorry, I've been offline for a couple of days and haven't checked the bug guild. I'm reopening since another admin must have wanted to investigate further.

**Comment by Alys** [comment] 2017-06-24 12:10
@fghber I've caught up with everything in the Report a Bug guild and I can't see an admin requesting this to be in GitHub, so I'm going to close this again.

You might have been thinking about this conversation in the Bug guild starting on 2017-06-04:

You posted:
"I have 2 problems: I cannot create new **active** dailies. When I create a random daily it is always **grayed-out** no matter whether it is set to repeat every day, on each day of the week or what ever.  The other problem is that since I have moved my **day reset** to a custom time to 1 hour earlier than the normal day break, some of my **dailies do not show on the correct day**. I notices this mostly with dailies set to show up on Sundays (other days me be affected as well)."

@TheHollidayInn replied:
"I am seeing your CDS set to 0. Is that correct? Also, did you refresh the page after setting the CDS and can you send me the name of one of your tasks having issues."

Then I replied:
"When you set your Custom Day Start time to 23 (11pm), you're saying that each day in Habitica should not start until 11pm is reached in the real world. It's therefore correct that Dailies will appear on the 'wrong' days until 11pm is reached. For more information about that, see the wiki's [Custom Day Start](http://habitica.wikia.com/wiki/Custom_Day_Start) page, especially the section 'Examples and a Warning about Late Custom Day Start Times'."


If you're still having trouble with Dailies when you have your Custom Day Start time set to midnight or to the early hours of the morning (i.e., between midnight and the earliest time you'd expect to use Habitica each day), then please post to the Report a Bug guild to tell us which Dailies have the problem.

**Closed as completed by Alys** 2017-06-24 12:10 UTC

**Comment by fghber** [comment] 2017-06-24 16:08
@Alys I was requested via a private message by 
@TheHollidayInn  Can you post in report a bug guild how to recreate the issue you are having and post how you changed the CDS to fix it? -16 days ago         
 TheHollidayInn 
PN: Regarding my bug report: I have restored my CDS to the regular time. This fixed all my problems. I have refreshed the page many times before (also with Ctrl+F5/without cache). The problems described were persistent over a couple of weeks limited to weekly tasks set to Sunday - the day I had changed my CDS before. Sorry, for the late reply. Should I report this somewhere on git? -16 days ago

But do as you desire... why does this rhymes with liar? You might have had that on your mind. *SCNR*
