### ISSUE TITLE
Tiny visual glitch when combining yellow clothing & second helm

### ISSUE THREAD

**Issue by krivers** [HabitRPG/habitica#738] opened 2013-03-28 00:06 UTC
When my female character has both yellow clothing and the second helm upgrade (I think the chain helmet?), the helmet only shows up halfway. The same helmet works fine when pink clothing is chosen instead. Here are example pics for both yellow and pink to demonstrate the problem:
![Screen shot 2013-03-27 at 8 00 17 PM](https://f.cloud.github.com/assets/699757/311322/00cc9f46-973b-11e2-9c0b-8d1cc8547dc6.png) ![Screen shot 2013-03-27 at 8 00 37 PM](https://f.cloud.github.com/assets/699757/311324/03406690-973b-11e2-8dc6-ee53942978c9.png)

Obviously this is not a high-priority bug, but it might be related to other potential problems with the sprite construction.

**Comment by lefnire** [comment] 2013-03-28 00:09
Actually by design but not obviously so. It's really armor sets 1 and 2,
though we're showing it as pink and yellow shirts. We should change the
selector in the settings

**Comment by caycefischer** [comment] 2013-03-28 18:25
I thought we were getting rid of the yellow and pink "default bodies" and just going with a white shirt as per the ol' gender equality discussion?

**Comment by lefnire** [comment] 2013-03-28 18:29
I'm down with that. Sad to see made armor go by the way side, b t seems to
confuse more people than please, so we can remove

**Comment by wc8** [comment] 2013-03-28 18:43
I guess I'm behind the times but I thought the solution was more options, rather than less, i.e., white, yellow or pink. 
- How about white or pink, or white or yellow? Then those who would want long hair can still have a white shirt and you can still do the armor options. Mouseover on white/alternate could explain the armor set 1 and armor set 2. 
- Alternatively, with/without colored shirts, another box, when helmet/armor is bought, allowing helmet 1, helmet 2.

**Comment by caycefischer** [comment] 2013-03-28 19:02
Oh, yeah of course more options are better, for both default body types. We just gotta make those sprites.

**Comment by lemoness** [comment] 2013-03-31 23:52
Hm. What modifications are needed? We already seem to have all of the colors for both body types in the master sprite sheet....

**Comment by lefnire** [comment] 2013-04-01 01:36
Here are my thoughts:
We have the art designed, let's keep it. I'll make it bit more obvious about "armor set 1" v "armor set 2" (a la recommendations above). We can possibly add a mechanic in the future for set 2, maybe tokens, maybe earned. This may really get me in trouble, but here goes: guys get less up-in-arms about this stuff, so I don't think this setup needs be "equality or nothing" - we can probably just keep it as is until we add that mechanic, but make things more obvious. If I'm wrong, speak now or forever hold your peace?

**Comment by Pandoro** [comment] 2013-04-01 11:31
While I don't mind the idea of not doing the whole gender thing. However, the sprite version I did a while back kind of relies on not having it, as it fused both sprites into  one larger sprite, containing 1 character, with different visual looks for whatever kind of customization you want. In the end it became clear that the skin model can be the same for both genders so you just should pick the hair you want and the armor you think fits yourself best, small shields, big shields, long shoulder plates or small ones etc. 

I think there are different advantages, such as fewer different sprites and especially no need to actually make two versions for new armors. So I think we should move there eventually. Especially with the stuff @lemoness presented lately, it will probably be cool if we can fit stuff to 1 sprite instead of worry about two versions every time.

**Comment by lefnire** [comment] 2013-04-01 18:03
@Pandoro So is the suggestion nix the second armor set?

**Comment by Pandoro** [comment] 2013-04-01 18:36
No exactly the opposite ;) Add additional support for different versions of
1 item and remove the whole gender thing. You just buy for example the 1
helmet and then you can pick 1 out of several different looks. Same goes
for most armors, as many have a female and male look. You can thus exactly
reproduce your current look, but without choosing your gender.

The advantage is that if a guy likes a ponytail, he can get one, without
needing the flower, or if a girl likes the male hairstyle, but wants the
flower helmet that is possible too. Or the pink shirt, or the blue shirt
etc.  If each armor piece can have several looks, you can fully customize
your character. IT shouldn't be TOO hard, since the basic idea is there
already, we would just have do display the actual different versions. And
if there is only one version, well no problem either, then we also need to
just send 1 version, instead of sending it twice in both the male and
female sprite.

This will also tie in nicely with enchantments. Maybe your sword will
become pink, but you don't like that, so you can choose just to keep the
original look, while still playing with the added effect.

Plus if we start adding more hairstyles, we do not need to limit them to a
gender or explicitly say they are there for both. You know I am not feeling
strongly about removing the genders, but from a pixel art kind of look, it
might make a bit more sense in the end I think. Plus if people can fine
tune their character, they can build up a bigger bond with them, so they
might be more tempted to buy custom armor (just for the looks of it) for
tokens.

**Comment by lefnire** [comment] 2013-04-01 18:47
Just read that comment a couple times, but I'm having a hard time following how that's not going to add a bunch of extra work for us? We'd have to add multiple versions of every helmet piece, weapon colors, etc? It sounds great, and extra customization is always :+1:  - but we may have to postpone that?

Edit: I mean, I defer to you, @Shaners & @lemoness - since y'all are the pixelists anyway, but just thinking out loud

**Comment by Pandoro** [comment] 2013-04-01 18:57
Sorry, I figured it might not have been my best written post :x

Well not for everything, just what is there already. It is in the sprite
sheet I uploaded a while back. Pretty much it gives both the male and
female version to every player, which sometimes is the same, but sometimes
the girl had 2 and the male had 1 giving 3 already. So art wise this is
good to role already. Especially for the starter set I created like 6
different color versions.

I would guess coding wise it doesn't need to much code, as you can already
change for example your skin color, if you reuse that code, you should be
able to make such a change framework for each piece. The main work will be
the migration from what there is now to such a new system. But you could
just default everyone to version 1 of the current item, and tell them to
play around with the different versions.

If you then keep in mind that more might be added with further versions, we
can easily bit by bit create different color variations, different sizes
and what not for all the items over time, thus extending the whole version
system over time.

**Comment by lemoness** [comment] 2013-04-01 23:10
I'm all for using what we've already got, and new customization options are
great, but let's definitely hold off on making new versions of armor for
now.  Otherwise, I think your ideas sound great!!

I think a good way to distinguish our two body types would be "slim" and
"stocky", what do you guys think?

Regarding hairstyles, since I am hoping to get to them as soon as I finish
some NPC stuff and the final mage - is it possible for us to separate the
bangs from the rest of the hair, coding wise? My reasoning is twofold.
1. More customization, which is of course nice.
2. If the longer part of the hairstyle goes BEHIND the clothes, it's much
   much much easier to design something uniform that will work no matter what
   the costume is.

**Comment by Pandoro** [comment] 2013-04-02 00:20
Yes, I think creating new stuff right now isn't needed. But for future
iterations it might be possible to add additional versions for armor sets
if someone has a nice idea, or likes to add a different color. Like a blue
armor instead of a red armor etc.

Slim and stocky, SOUNDS good, but is hard to realize ;) If you succeed in
making the characters look slimmer, that is cool, but it is hard to do, as
everything. Fewer pixels is really hard, and purely using color isn't easy
either. It is well possible when talking about shoulders, or large/small
shields, but the actual body is pretty fixed in my experience. Then again
you can do better stuff than me sooo ;)

The hairstyle is actually already separated in the last version I uploaded.
I am not really sure where it is. The basic idea is that you have 1
hairstyle with outlines, for simply showing the hairstyle and then 1
version without outlines, which is used as hair pixels UNDER the helmet.
The helmet could specify some flag, saying "no ponytail" if it is not
compatible and in such a case it would revert to a basic hairstyle
automatically. (Needs to be implemented of course.) You can look at the
sprite if you find it :x It should be fairly straight forward to understand
if you see it.

Right now the ponytail goes OVER the armor, but this could be changed at
some point I guess. At the cost of course of loosing the ponytail. I think
with more armor, the hairstyle is getting less and less important though.
Unless you choose to not use a helmet, in which case the hair over the
armor might be better? (This could also be another flag for armor, but this
might be getting overly complex :x)

**Comment by lemoness** [comment] 2013-04-02 13:46
AHH no no, I just meant re-labeling the two body types we already have as
"slim" (previously the girl body) and "stocky" (previously the guy body)! I
wasn't talking about changing them any further, just re-labeling them so
that they're gender neutral. I really love the distinction you made, and
definitely couldn't improve on it. Sorry that wasn't clear!!

With mages and also potentially rogues, you can see a variety of
hairstyles... Also for some of the custom outfits. I guess I will just make
the hairstyles separately, and then we can figure out whether or not they
should go over or under. I will try both ways! It's a little in the future
anyway.

**Comment by wildcate** [comment] 2013-04-03 16:33
@Pandoro and @lemoness, that all sounds really, really cool - I'm looking forward to having your hard work available for avatar customisation!

**Closed as completed** 2013-10-25 16:23 UTC
