### ISSUE TITLE
challenges being joined twice simultaneously; challenge tasks duplicated

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#7730] opened 2016-06-26 22:02 UTC
I've seen some reports of players having duplicate challenge tasks and I've also seen challenge IDs appearing twice in users' `challenge` objects. I'm going to start reporting all instances here so that we can track it and work out what's causing it.

This is distressing for the players because it makes their task lists feel out of control, and it can be damaging for them and their party if they think they're not allowed to tick a duplicated Daily.

@paglias @crookedneighbor  Do you have any idea what might be causing this?

Joining challenges doesn't seem to be recorded in Amplitude. Is it worth adding it?

Natusha (0f3823fd-38a4-477a-ad4a-6d0ce458ef6f) in the Report a Bug guild
**When I click in the "Join" on the challenge area, all the quests (daily, to do, etc) appear duplicated, that happened in the 2 challenges I took, and I'm scared of taking more and continuing duplicating things**

```
    "challenges": [
        "63a21fcf-7ab8-4483-a70d-d4fb61d88f6e",
        "63a21fcf-7ab8-4483-a70d-d4fb61d88f6e",
        "2650b24f-7097-4789-adcd-dad9cae5d74b",
        "2650b24f-7097-4789-adcd-dad9cae5d74b",
        "c4004b63-e868-4e6e-a7e4-3cd30d02a3e8"
    ],
```

For challenge [63a21fcf-7ab8-4483-a70d-d4fb61d88f6e](https://habitica.com/#/options/groups/challenges/63a21fcf-7ab8-4483-a70d-d4fb61d88f6e):

```
{
    "_id": "4bb04ea8-2332-4d4f-9aa6-1d60fe6c7315",
    "tags": [],
    "challenge": {
        "taskId": "576cb003-394e-49ad-ae23-e35fe28fb320",
        "id": "63a21fcf-7ab8-4483-a70d-d4fb61d88f6e"
    },
    "createdAt": "2016-06-26T18:20:13.464Z"
}

{
    "_id": "5b25e9bf-55c7-4d1d-bf6e-3886fa61920d",
    "tags": [
        "63a21fcf-7ab8-4483-a70d-d4fb61d88f6e"
    ],
    "challenge": {
        "taskId": "576cb003-394e-49ad-ae23-e35fe28fb320",
        "id": "63a21fcf-7ab8-4483-a70d-d4fb61d88f6e"
    },
    "createdAt": "2016-06-26T18:20:13.491Z"
}

{
    "_id": "513c4947-99d5-4433-8553-9eb4b8d71ad3",
    "tags": [
        "63a21fcf-7ab8-4483-a70d-d4fb61d88f6e"
    ],
    "challenge": {
        "taskId": "69acb6fe-2d2d-4a96-b5d3-847ff17b0e8e",
        "id": "63a21fcf-7ab8-4483-a70d-d4fb61d88f6e"
    },
    "createdAt": "2016-06-18T15:12:21.551Z"
}

{
    "_id": "e58fef95-5dfa-4840-9f28-a6528436cb1a",
    "tags": [
        "63a21fcf-7ab8-4483-a70d-d4fb61d88f6e"
    ],
    "challenge": {
        "taskId": "2231e1e5-ed97-429f-a96e-2e400bd89e4d",
        "id": "63a21fcf-7ab8-4483-a70d-d4fb61d88f6e"
    },
    "createdAt": "2016-06-26T18:20:13.493Z"
}

{
    "_id": "e7eacac8-422e-471c-a8cc-4e6d288cd432",
    "tags": [
        "63a21fcf-7ab8-4483-a70d-d4fb61d88f6e"
    ],
    "challenge": {
        "taskId": "2231e1e5-ed97-429f-a96e-2e400bd89e4d",
        "id": "63a21fcf-7ab8-4483-a70d-d4fb61d88f6e"
    },
    "createdAt": "2016-06-26T18:20:13.465Z"
}

{
    "_id": "e35f5786-4c30-4947-90ba-79597f2af4da",
    "tags": [
        "63a21fcf-7ab8-4483-a70d-d4fb61d88f6e"
    ],
    "challenge": {
        "taskId": "ae9a0b12-810e-4364-8bc5-78aecfa1ce9d",
        "id": "63a21fcf-7ab8-4483-a70d-d4fb61d88f6e"
    },
    "createdAt": "2016-06-18T15:12:21.553Z"
}
```

For challenge [2650b24f-7097-4789-adcd-dad9cae5d74b](https://habitica.com/#/options/groups/challenges/2650b24f-7097-4789-adcd-dad9cae5d74b):

```
{
    "_id": "abc8d9dd-5bae-4f9e-89e4-77287c566a3a",
    "tags": [
        "2650b24f-7097-4789-adcd-dad9cae5d74b"
    ],
    "challenge": {
        "taskId": "a93cd6ef-811d-4c11-9458-ee8341fefff3",
        "id": "2650b24f-7097-4789-adcd-dad9cae5d74b"
    },
    "createdAt": "2016-06-26T20:49:22.113Z"
}

{
    "_id": "64fe1e81-1ad6-4178-87ef-1188ca0666a2",
    "tags": [
        "2650b24f-7097-4789-adcd-dad9cae5d74b"
    ],
    "challenge": {
        "taskId": "a93cd6ef-811d-4c11-9458-ee8341fefff3",
        "id": "2650b24f-7097-4789-adcd-dad9cae5d74b"
    },
    "createdAt": "2016-06-26T20:49:22.111Z"
}


{
    "_id": "1de2604a-3bb0-459b-a89d-33f823d23258",
    "tags": [
        "2650b24f-7097-4789-adcd-dad9cae5d74b"
    ],
    "challenge": {
        "taskId": "1b6fe224-d20b-41f8-a745-70ae3af8f0c1",
        "id": "2650b24f-7097-4789-adcd-dad9cae5d74b"
    },
    "createdAt": "2016-06-26T20:49:22.106Z"
}

{
    "_id": "d7023082-bae6-416b-872b-ac6a07274cd1",
    "tags": [
        "2650b24f-7097-4789-adcd-dad9cae5d74b"
    ],
    "challenge": {
        "taskId": "1b6fe224-d20b-41f8-a745-70ae3af8f0c1",
        "id": "2650b24f-7097-4789-adcd-dad9cae5d74b"
    },
    "createdAt": "2016-06-26T20:49:22.101Z"
}


{
    "_id": "16a27440-8910-4da8-bdcb-810dc2f5f41f",
    "tags": [
        "2650b24f-7097-4789-adcd-dad9cae5d74b"
    ],
    "challenge": {
        "taskId": "2bbf82a9-d080-46ff-8b1a-e16dba03d355",
        "id": "2650b24f-7097-4789-adcd-dad9cae5d74b"
    },
    "createdAt": "2016-06-26T20:49:22.105Z"
}

{
    "_id": "1251dc3c-fa27-4a7d-940e-a8b44821a8e0",
    "tags": [
        "2650b24f-7097-4789-adcd-dad9cae5d74b"
    ],
    "challenge": {
        "taskId": "2bbf82a9-d080-46ff-8b1a-e16dba03d355",
        "id": "2650b24f-7097-4789-adcd-dad9cae5d74b"
    },
    "createdAt": "2016-06-26T20:49:22.099Z"
}


{
    "_id": "fd1e9fb8-5f27-4560-9d5a-74adf9d8a409",
    "tags": [
        "2650b24f-7097-4789-adcd-dad9cae5d74b"
    ],
    "challenge": {
        "taskId": "d83864fd-e442-4a36-86fa-b67b7253cd99",
        "id": "2650b24f-7097-4789-adcd-dad9cae5d74b"
    },
    "createdAt": "2016-06-26T20:49:22.103Z"
}

{
    "_id": "75f339ec-13d5-4a93-a8ee-c923c3c76ec5",
    "tags": [
        "2650b24f-7097-4789-adcd-dad9cae5d74b"
    ],
    "challenge": {
        "taskId": "d83864fd-e442-4a36-86fa-b67b7253cd99",
        "id": "2650b24f-7097-4789-adcd-dad9cae5d74b"
    },
    "createdAt": "2016-06-26T20:49:22.107Z"
}


{
    "_id": "3476d193-d141-4ef5-ba7f-eb2074ffca1b",
    "tags": [
        "2650b24f-7097-4789-adcd-dad9cae5d74b"
    ],
    "challenge": {
        "taskId": "b4fda3e5-b071-4ce4-ac35-8504b0d9c238",
        "id": "2650b24f-7097-4789-adcd-dad9cae5d74b"
    },
    "createdAt": "2016-06-26T20:49:22.108Z"
}

{
    "_id": "b06b8e2c-2bcf-4711-9963-c5f14df29621",
    "tags": [
        "2650b24f-7097-4789-adcd-dad9cae5d74b"
    ],
    "challenge": {
        "taskId": "b4fda3e5-b071-4ce4-ac35-8504b0d9c238",
        "id": "2650b24f-7097-4789-adcd-dad9cae5d74b"
    },
    "createdAt": "2016-06-26T20:49:22.104Z"
}



{
    "_id": "8bc52e97-9708-402c-9aeb-0a9aeca6d198",
    "tags": [
        "2650b24f-7097-4789-adcd-dad9cae5d74b"
    ],
    "challenge": {
        "taskId": "c4628b97-6784-48fb-a263-8edcd79d63a4",
        "id": "2650b24f-7097-4789-adcd-dad9cae5d74b"
    },
    "createdAt": "2016-06-26T20:49:22.105Z"
}

{
    "_id": "d20e577e-785d-497a-ae1f-4f02893d1653",
    "tags": [
        "2650b24f-7097-4789-adcd-dad9cae5d74b"
    ],
    "challenge": {
        "taskId": "c4628b97-6784-48fb-a263-8edcd79d63a4",
        "id": "2650b24f-7097-4789-adcd-dad9cae5d74b"
    },
    "createdAt": "2016-06-26T20:49:22.109Z"
}


{
    "_id": "f6a639a0-ef41-4e9d-83c9-482ae9e047a8",
    "tags": [
        "2650b24f-7097-4789-adcd-dad9cae5d74b"
    ],
    "challenge": {
        "taskId": "07f03a8f-e420-4e00-bfaf-1667d45ff135",
        "id": "2650b24f-7097-4789-adcd-dad9cae5d74b"
    },
    "createdAt": "2016-06-26T20:49:22.110Z"
}

{
    "_id": "dfbbeb23-cd78-4340-89ea-c78c76688ef7",
    "tags": [
        "2650b24f-7097-4789-adcd-dad9cae5d74b"
    ],
    "challenge": {
        "taskId": "07f03a8f-e420-4e00-bfaf-1667d45ff135",
        "id": "2650b24f-7097-4789-adcd-dad9cae5d74b"
    },
    "createdAt": "2016-06-26T20:49:22.106Z"
}


{
    "_id": "e7212581-c400-4978-9622-7e4fc238b1e1",
    "tags": [
        "2650b24f-7097-4789-adcd-dad9cae5d74b"
    ],
    "challenge": {
        "taskId": "221d286c-f496-4ef0-8cf4-0de69d340dac",
        "id": "2650b24f-7097-4789-adcd-dad9cae5d74b"
    },
    "createdAt": "2016-06-26T20:49:22.111Z"
}

{
    "_id": "5f90d4bc-a6c3-421e-aa9b-c5d04e7de02d",
    "tags": [
        "2650b24f-7097-4789-adcd-dad9cae5d74b"
    ],
    "challenge": {
        "taskId": "221d286c-f496-4ef0-8cf4-0de69d340dac",
        "id": "2650b24f-7097-4789-adcd-dad9cae5d74b"
    },
    "createdAt": "2016-06-26T20:49:22.108Z"
}


{
    "_id": "d611e017-e291-4253-9aba-b6e463a8b1b6",
    "tags": [
        "2650b24f-7097-4789-adcd-dad9cae5d74b"
    ],
    "challenge": {
        "taskId": "3d23f8bf-df9d-4feb-a0fb-024a4ab9b88a",
        "id": "2650b24f-7097-4789-adcd-dad9cae5d74b"
    },
    "createdAt": "2016-06-26T20:49:22.112Z"
}

{
    "_id": "0e42003b-a6fd-432b-a809-98f062ffad83",
    "tags": [
        "2650b24f-7097-4789-adcd-dad9cae5d74b"
    ],
    "challenge": {
        "taskId": "3d23f8bf-df9d-4feb-a0fb-024a4ab9b88a",
        "id": "2650b24f-7097-4789-adcd-dad9cae5d74b"
    },
    "createdAt": "2016-06-26T20:49:22.109Z"
}
```

**Comment by paglias** [comment] 2016-06-27 07:19
It's likely that users are clicking more than once on the Join button... the fact is that Mongoose should prevent this from happening (same data added to an array twice) but it doesn't look to be working

**Comment by Alys** [comment] 2016-06-27 07:22
Does bootstrap provide an easy way to make a button unclickable immediately after it's been clicked?

**Comment by paglias** [comment] 2016-06-27 07:23
We can probably make so a request is only sent after the previous one has
ended but then it would resolve the problem on the site only, could still
happen from mobile or API. Anyway better than nothing

2016-06-27 9:22 GMT+02:00 Alys notifications@github.com:

> Does bootstrap provide an easy way to make a button unclickable
> immediately after it's been clicked?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/HabitRPG/habitrpg/issues/7730#issuecomment-228671291,
> or mute the thread
> https://github.com/notifications/unsubscribe/AAkAVxkyD8CV0HcW5I0_bbn1KMarEC5Mks5qP3oxgaJpZM4I-p3V
> .

## 

Matteo Pagliazzi - paglias.net

**Comment by paglias** [comment] 2016-06-27 07:35
Confirmed that clicking very quickly on the Join button causes this

2016-06-27 9:23 GMT+02:00 Matteo Pagliazzi matteopagliazzi@gmail.com:

> We can probably make so a request is only sent after the previous one has
> ended but then it would resolve the problem on the site only, could still
> happen from mobile or API. Anyway better than nothing
> 
> 2016-06-27 9:22 GMT+02:00 Alys notifications@github.com:
> 
> > Does bootstrap provide an easy way to make a button unclickable
> > immediately after it's been clicked?
> > 
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly, view it on GitHub
> > https://github.com/HabitRPG/habitrpg/issues/7730#issuecomment-228671291,
> > or mute the thread
> > https://github.com/notifications/unsubscribe/AAkAVxkyD8CV0HcW5I0_bbn1KMarEC5Mks5qP3oxgaJpZM4I-p3V
> > .
> 
> ## 
> 
> Matteo Pagliazzi - paglias.net

## 

Matteo Pagliazzi - paglias.net

**Comment by khipkin** [comment] 2016-06-27 13:13
http://stackoverflow.com/questions/18130808/preventing-dealing-with-double-button-clicks-in-angular

**Comment by Alys** [comment] 2016-06-29 09:26
FYI, for the TAKE THIS challenge, there are 6817 participants and 5 of them have two sets of the tasks. Not a high proportion.

**Comment by khipkin** [comment] 2016-06-30 13:19
#6961 is also an issue with rapid clicking.

**Comment by Hus274** [comment] 2016-07-13 23:38
I can look into pushing out a fix for this

**Comment by Hus274** [comment] 2016-07-14 02:23
Looks like the deduping function in the syncToUserMethod is working but the duplicate still happens in the database for some reason. 

Log statements:

```
before
["19aac2ee-ca04-4efa-8b0d-53ef8ddddd97","f8e37900-d8ee-424b-a17d-0f77ed834242"]
after
["19aac2ee-ca04-4efa-8b0d-53ef8ddddd97","f8e37900-d8ee-424b-a17d-0f77ed834242","b5b34404-cd55-4088-913e-505dd242e45a"]
POST /api/v3/challenges/b5b34404-cd55-4088-913e-505dd242e45a/join?userV=1319 200 83.190 ms - 710
before
["19aac2ee-ca04-4efa-8b0d-53ef8ddddd97","f8e37900-d8ee-424b-a17d-0f77ed834242"]
after
["19aac2ee-ca04-4efa-8b0d-53ef8ddddd97","f8e37900-d8ee-424b-a17d-0f77ed834242","b5b34404-cd55-4088-913e-505dd242e45a"]
POST /api/v3/challenges/b5b34404-cd55-4088-913e-505dd242e45a/join?userV=1319 200 83.222 ms - 709
```

DB after the parallel posts:

```
  db.users.find({_id: '95ee9d01-e93d-4d33-9ca4-2da8bac1ec86'})[0].challenges
[
    "19aac2ee-ca04-4efa-8b0d-53ef8ddddd97",
    "f8e37900-d8ee-424b-a17d-0f77ed834242",
    "b5b34404-cd55-4088-913e-505dd242e45a",
    "b5b34404-cd55-4088-913e-505dd242e45a"
]
```

I don't know how the two updates get merged as I would think one would just overwrite the other. I'm going to try to dig a little deeper into it to see if I can find the actual root cause

**Comment by Hus274** [comment] 2016-07-14 03:17
I see the duplicated save happening:

```
Saving the following:
["19aac2ee-ca04-4efa-8b0d-53ef8ddddd97","f8e37900-d8ee-424b-a17d-0f77ed834242","b5b34404-cd55-4088-913e-505dd242e45a"]
Loading after the save:
["19aac2ee-ca04-4efa-8b0d-53ef8ddddd97","f8e37900-d8ee-424b-a17d-0f77ed834242","b5b34404-cd55-4088-913e-505dd242e45a"]
POST /api/v3/challenges/b5b34404-cd55-4088-913e-505dd242e45a/join?userV=1580 200 102.331 ms - 710
Saving the following:
["19aac2ee-ca04-4efa-8b0d-53ef8ddddd97","f8e37900-d8ee-424b-a17d-0f77ed834242","b5b34404-cd55-4088-913e-505dd242e45a"]
Loading after the save:
["19aac2ee-ca04-4efa-8b0d-53ef8ddddd97","f8e37900-d8ee-424b-a17d-0f77ed834242","b5b34404-cd55-4088-913e-505dd242e45a","b5b34404-cd55-4088-913e-505dd242e45a"]
```

With the following code:

```
  console.log('Saving the following:');
  console.log(user.challenges);
  toSave.push(user.save());
  await Bluebird.all(toSave);
  console.log('Loading after the save:');
  let newUser = await User.find({_id: user._id});
  console.log(newUser[0].challenges);
```

From my understanding of the mongoose save, a save of the local document should completely overwrite what is currently in the database so I don't see how saving with 3 challenges can result in 4 challenges in the database. Any thoughts on how this could be happening?

**Comment by Hus274** [comment] 2016-07-14 03:25
Looking at the object returned in the callback of the user.save() function, the duplicate isn't seen:

```
Saving the following:
["19aac2ee-ca04-4efa-8b0d-53ef8ddddd97","f8e37900-d8ee-424b-a17d-0f77ed834242","b5b34404-cd55-4088-913e-505dd242e45a"]
Loading after the save:
["19aac2ee-ca04-4efa-8b0d-53ef8ddddd97","f8e37900-d8ee-424b-a17d-0f77ed834242","b5b34404-cd55-4088-913e-505dd242e45a"]
POST /api/v3/challenges/b5b34404-cd55-4088-913e-505dd242e45a/join?userV=1604 200 91.503 ms - 710
Saving the following:
["19aac2ee-ca04-4efa-8b0d-53ef8ddddd97","f8e37900-d8ee-424b-a17d-0f77ed834242","b5b34404-cd55-4088-913e-505dd242e45a"]
Loading after the save:
["19aac2ee-ca04-4efa-8b0d-53ef8ddddd97","f8e37900-d8ee-424b-a17d-0f77ed834242","b5b34404-cd55-4088-913e-505dd242e45a"]
```

**Comment by Hus274** [comment] 2016-07-14 03:30
Potential solution is maybe to do a couple update operations instead of a save `User.update({_id: user._id}, {$addToSet: {challenges: challenge._id}}));`

**Comment by Hus274** [comment] 2016-07-14 04:05
So I think I might have figured out what was happening here. Mongoose treats saves of objects that already exists as inserting a differential between what's there and what's being saved. In this case, I think what would happen is both of the saves are occurring at the same time and both compute a diff against the document without the challenge being added. Both computed differentials then have the diff of something like +newChallenge. At this point they both will then insert the missing challenge into to challenges array leading to the challenge being inserted twice. 

[Mongoose source](https://github.com/Automattic/mongoose/blob/168f516902bf142006581479d58d19867fb844e8/lib/model.js#L146)

**Comment by khipkin** [comment] 2016-09-09 05:34
Suggestion: [help welcome now] --> [in progress]

**Closed as completed** 2016-12-21 01:52 UTC
Labels: priority: important, section: Challenges, status: issue: needs investigation, status: issue: in progress
