### ISSUE TITLE
At least one daily failed to process - death and lost item.

### ISSUE THREAD

**Issue by eiron** [HabitRPG/habitica#4183] opened 2014-10-25 15:33 UTC
A daily I ticked off late last night seems not have synced prior to cron. This means that the damage was just high enough to push to zero. I do not mind dying if it is my fault, but this was not - and the item lost is from another class (my golden staff) meaning I would have to pay six gems (real-world money) to get it back. Any chance of having this put right without having to incur the gem cost? I already put a lot of gems into the site (getting all the class gear in the first place, plus my challenge guild), so would prefer not to throw a bunch away again due to a small glitch.

User ID: 4182cdea-64db-4db4-9713-dc587d86c662

**Comment by lemoness** [comment] 2014-10-25 17:55
There's a fix in the works, I think, to keep people from losing cross-class
items when they die. What's your UUID? I'll give you back your staff.

**Comment by eiron** [comment] 2014-10-25 18:23
UUID is 4182cdea-64db-4db4-9713-dc587d86c662. I actually quite like the cross-class items getting lost in some respects, as it means I know which class to switch to next. But I would like it to be an option. And also for it to be a little easier to fix if it is the result of an error!

**Comment by eiron** [comment] 2014-10-25 18:26
(While we are at it, I never did get my [Find the Cub scroll](https://github.com/HabitRPG/habitrpg/issues/2592#issuecomment-43208653) back.)

**Comment by lemoness** [comment] 2014-10-25 19:32
Okay, refresh - you should have your staff back, and your scroll as well :)

**Comment by Amezuki** [comment] 2014-11-01 17:18
I have noticed this happening several times recently, where dailies that I know for an ironclad fact that I checked off are not getting counted. This has required me to repeatedly fix character values and edit streaks, something I hate doing.

At first I thought maybe I was just forgetting to check them off and forgetting that I'd forgotten, but once it was nearly all the dailies (including one that I virtually never fail to do), and last night it resulted in me losing a perfect day bonus when I very distinctly remember the entire column being gray and checked off.

UID: e702f702-0d01-49d4-9ed6-5003108764b2

**Comment by Alys** [comment] 2014-11-01 18:24
@Amezuki when this happens, is it on days when you have ticked off several Dailies together very quickly one after the other, or does it happen even if you tick off the Dailies slowly at different times throughout the day?

**Comment by Amezuki** [comment] 2014-11-02 05:48
I honestly can't recall, but given my typical workflow of reviewing all of my checklist items at the end of the day, it's entirely possible this was a race condition of some sort. Frustrating, but I'll try to go through the list a bit slower.

**Comment by Alys** [comment] 2014-11-02 06:34
@Amezuki : It sounds very much like it would have been sync errors caused by ticking off the Dailies too quickly. Basically, your browser can't keep up with you and can't send the information to the server quickly enough. For more information see [Sync Errors](http://habitrpg.wikia.com/wiki/Sync_Errors), especially section 3 "How to Minimise Sync Errors" (in brief, wait for the blue bar at the top of the screen  to disappear before ticking off the next Daily, but there's other useful advice there too). If you keep getting sync errors even when ticking off Dailies slowly, tell us.

@Eiron FYI: This is the fix that @lemoness mentioned to keep people from losing cross-class items when they die: https://github.com/HabitRPG/habitrpg-shared/pull/305. It's waiting for input about a failing test that's preventing it being made live. I liked [your idea above](https://github.com/HabitRPG/habitrpg/issues/4183#issuecomment-60492088) about making it an option to loose cross-class items. We could keep that in mind for a future enhancement (maybe for a "make HabitRPG harder" mode).

I'm closing this now but it can be reopened if problems persist.

**Closed as completed by Alys** 2014-11-02 06:34 UTC
