### ISSUE TITLE
Damage from Cron even though all dailies checked (caused by 3rd party programs)

### ISSUE THREAD

**Issue by crookedneighbor** [HabitRPG/habitica#4513] opened 2015-01-13 22:27 UTC
Working with a user that uses the [todoist-habitrpg module](https://github.com/Kusold/todoist-habitrpg) to sync tasks from Todoist to HabitRPG. Some todos got assigned the type of "Daily", so even though they existed in the `user.todos` object, they were being counted as dailies by the cron script because their type was "daily". 

[Here's the point in the Github issue where we start figuring out what is going on](https://github.com/Kusold/todoist-habitrpg/issues/23#issuecomment-69120506)

I think an easy fix would be to make the type value immutable, so that it cannot be changed once created. Another option would be [this gist from lefnire](https://gist.github.com/lefnire/afbcf83f6d1dac6617dd), which would be the start of allowing tasks to be converted to other types.
##

**Comment by Alys** [comment] 2015-01-13 22:37
Note that I do not believe this is a HabitRPG cron bug (although I asked @crookedneighbor to create this issue here so that we would all be aware of it). Instead, it's caused by the todoist-habitrpg module producing corrupted tasks that have attributes that cron considers as Dailies (and hence does damage for) but which the HabitRPG user interface does not consider as Dailies and so doesn't let the user know that they need to be completed.

Ideally, HabitRPG would be able to appropriately handle this sort of corruption, and we'll probably need to do that in time as third-party apps become more prevalent, since we can't control the quality of those apps. But for now this needs to be fixed in the todoist-habitrpg module (the devs there are already aware of that).

**Comment by crookedneighbor** [comment] 2015-01-13 22:55
If we decide to make the type attribute immutable, [this gist from lefnire should do it](https://gist.github.com/lefnire/6b9f183d09d9a391a85b).

Edit: Wrong link, corrected now.

**Comment by crookedneighbor** [comment] 2015-01-13 22:56
When troubleshooting Cron bugs, it would be a good idea to ask about all 3rd party programs that the user has that interact with HabitRPG. Especially ones that can create or modify tasks.

**Comment by paglias** [comment] 2015-01-13 23:50
Why do we store a type property if tasks are already separated in
user.(dailies,todos,habits)?
Il 13/gen/2015 23:56 "Blade Barringer" notifications@github.com ha
scritto:

**Comment by Alys** [comment] 2015-01-13 23:58
Coding convenience. Example: https://github.com/HabitRPG/habitrpg-shared/blob/develop/script/index.coffee#L1448-1460 which treats todos and dailys in the same way (same loop through both types of tasks) but has extra code that's run only if `type` is `daily`. Of course there'd be other ways of doing it, but it would have been simplest and fastest to write it that way.

**Comment by paglias** [comment] 2015-01-14 18:45
@Alys I see, (I also commented here https://github.com/HabitRPG/habitrpg/issues/4514 but the content is the same, so ignore it)

**Comment by Alys** [comment] 2016-05-28 12:31
I believe this issue isn't needed any more because it's no longer possible to relabel tasks of one type as a different type now that API v3 has been released, so I'm closing this. It can be reopened if I'm wrong.

**Closed as completed by Alys** 2016-05-28 12:31 UTC
Labels: priority: important
