### ISSUE TITLE
Repeat every X periodic dailies punish too soon

### ISSUE THREAD

**Issue by battlmonstr** [HabitRPG/habitica#7824] opened 2016-07-25 17:47 UTC
I have a "daily" periodic task called "sport" with Repeat = "Every X days", and "Repeat every" = 7.
Usually the task is grey, but sometimes it is green, yellow or red.
It is very confusing as to when it becomes green, yellow or red, but when that happens, I need to complete (mark) it during the same day, otherwise I get penalties (lose health).

I would like to do this task once a week (once in 7 days), but I don't know on which day. I want to be flexible on that. It can be Friday, or Sunday, or Monday, or whatever.
It happened several times that I had completed and checked a grey task (for example on Monday), but later on the same week (even on Tuesday) it became yellow and punished me.

The desired behavior is that when I complete this periodic task, the whole current period should be safe, and the punishment should be planned at the end of the next period.
For example, if I create a task on Monday (on day N) to "repeat every 7 days", normally I should be punished next Monday (on day N+7). But if I come and complete the task on Wednesday, the punishment should be replanned to the next after the next Monday (day N+14).

To be clear, this is the state right after creating the task in this example:
day 0 - Monday - no punishment
day 1 - Tuesday - no punishment
day 2 - Wednesday - no punishment
day 3 - Thursday - no punishment
day 4 - Friday - no punishment
day 5 - Saturday - no punishment
day 6 - Sunday - last day to avoid punishment
day 7 - Monday - punishment day

And this is the expected state after completing the task on Wednesday:

day 2 - Wednesday - no punishment
day 3 - Thursday - no punishment
day 4 - Friday - no punishment
day 5 - Saturday - no punishment
day 6 - Sunday - no punishment
day 7 - Monday - no punishment
day 8 - Tuesday - no punishment
day 9 - Wednesday - no punishment
day 10 - Thursday - no punishment
day 11 - Friday - no punishment
day 12 - Saturday - no punishment
day 13 - Sunday - last day to avoid punishment
day 14 - Monday - punishment day

So doing the task on any day of the week should clear that week and postpone the punishment to +7 days. On the next week I should be able to come and complete the task on any day again, for example on Friday without being punished. This is because I want to do the task once in 7 days, not more frequently than that.

I'm not sure what is the current strategy, but it's clearly different. I'm completing the tasks on time in advance (when grey), but then still get punished.

This is related to this feature:
https://github.com/HabitRPG/habitrpg/issues/4173

**Comment by Alys** [comment] 2016-07-25 20:34
What you've described is the correct, expected behaviour for Dailies set up with the "Every X Days" feature. In your case where X is 7, that feature is intended to make a Daily due on its 'Start Date", then exactly 7 days from its Start Date, then exactly 7 days after that, and so on.

There is currently no feature to make a Daily due 7 days after you last completed it however there will be in future.

If you'd like to change when it's due, adjusting its Start Date is the best method. For another idea, see "Tracking Weekly Activities" in the wiki's [Checklist](http://habitica.wikia.com/wiki/Checklists#Keeping_Track_of_Dailies) page, and you'll find other information at [Dailies](http://habitica.wikia.com/wiki/Dailies). If you have questions, drop in to Help > Ask a Question from the website's menu.

**Closed as completed by Alys** 2016-07-25 20:34 UTC

**Comment by battlmonstr** [comment] 2016-07-25 22:01
I'm sorry, but I still claim that the current system behaviour is different from what I describe as expected, and different from what you describe as well.

Like I said, I'm getting punished even if I complete a task, and it looks something like this:
If I start a task on Monday (day N) with "repeat every 7 days", and then complete it on Wednesday (same week, day N+2), then I can get punished next Monday (day N+7) or next Wednesday (day N+9). This is wrong!

The most annoying is when I complete a task on Saturday or Sunday, and then get punished on Monday. It feels that according to the system I have to complete it on a CERTAIN DATE, even though it says "repeat every X days".

To me "repeat every X days" means that I need to repeat this task every X days (once a week) at ANY day in the current period. To the system it seems to mean "punish this guy every X days", because it really works in this sense, but not in the normal sense.

I can make more tests, but I think it's pretty clear that it's not behaving as claimed.

In addition it would be nice if colors were changed according to the time left in the period. For example, if >100% of the period time is left - it's grey, >66% - green >33% - yellow , otherwise - red. Or something like this. Right now it's completely different (it's grey all the time, and then on a single day can change all the colors).

**Comment by Alys** [comment] 2016-07-25 22:25
For all Dailies, you do get punished if you don't complete a Daily on the day that it was due, and the current behaviour of "Every X Days" Dailies is that they are due exactly X days after the last time they were due. Because of that, it's expected, and technically correct, that you are getting punished on the days it is due when you have completed it on earlier days but not on the due days themselves. Currently, Dailies are not meant to reschedule themselves based on their date of last completion.

I do understand that it doesn't match the feature that you want, and that feature would definitely be a good thing for Habitica to have. We are intending to add the feature of making a Daily due X days after it was last completed. A project for that has already been started. There is currently no timeframe for when it will be completed.

The colours of all tasks show how well you've done on that task in the past. See [Task Value](http://habitica.wikia.com/wiki/Task_Value) for detailed information about that.

**Comment by battlmonstr** [comment] 2016-07-25 22:34
I understand now.
If the work is started, where is it tracked? Could you link this issue to the issue where the work is ongoing?

Speaking about the colors, I've checked your wiki link. It makes sense for bad habits (with + and -), but 1) it doesn't make sense for a repeating task; 2) The table doesn't explain a grey color which I observe 90% of the time. 3) how "consecutive clicks" can be negative?

**Comment by audiolion** [comment] 2016-07-25 22:38
@battlmonstr I think the thing to consider is a scenario like 'go to gym' with MWF repeat, if you go an extra time on a TH when it is grayed out (because it isnt due on this day) you still get a bonus because hey, going to gym on thursday in addition is great too, but you still need to go on Friday as you usually do.

It makes it a bit complex when the user could want to do something IN ADDITION to the current, e.g. 'go to gym' -> goes an extra day vs. REPLACEMENT e.g. 'go to gym' -> 'went on TH instead of FR this week'.

**Comment by mcooledge** [comment] 2016-07-25 22:41
@battlmonstr, a grey task is one that is not due that day. If it's grey and you do it, you'll get a reward, but you won't get punished for not doing it that day.

**Comment by mcooledge** [comment] 2016-07-25 22:42
Also, my strategy for weekly tasks that don't depend on the day is just to add a new todo every week for the task. It's slightly less elegant and I don't get punished for not doing it, but it works fine for now.

**Comment by battlmonstr** [comment] 2016-07-25 22:46
If I know that I'm going each Friday, there's a special option to check "repeat every Friday",
but IMO "repeat every X days" was meant for something else.
Like if I'm going on Wednesday might mean that on Friday I have something else planned. I don't want to be punished for that.
With habitica I try to find time for all my hobbies. I don't have a schedule for them (can't have or don't want to have). I just want some regularity, and periodic notifications (if done right) should work for that.
I don't see any complexity here. If you want to do it more - it's up to you, but in this case you shouldn't be punished, right?

Yes, adding a TODO might be a workaround, it's a bit of work though for 5-10 tasks.

**Comment by audiolion** [comment] 2016-07-25 22:52
IMO if there is a loose schedule for the activities they should go under the 'habits' section, e.g. 'spend some time with friends', + it when you do, try to keep it green/blue

**Comment by mcooledge** [comment] 2016-07-25 22:55
I agree with audiolion, habits are probably a better option for the use case you described.

"repeat every X days" is good for when you don't need to do something every day but want to do it regularly and on a schedule. Cleaning the cat's litter box, for example, is often something people want to do every other day, so that would be a daily with "repeat every 2 days" selected.

Having weeklies would also work for what you suggested, but at this time isn't supported. I know a lot of people would love it, however, and I believe it's a common feature request.

**Comment by battlmonstr** [comment] 2016-07-25 22:58
Habits are not great. I still want to be punished for lazyness automatically.

Having weeklies sounds great. Actually "weeklies" + "bi-weeklies" + "half-weeklies" would be ideal for me.

**Comment by audiolion** [comment] 2016-07-25 23:15
Yeah, follow https://github.com/HabitRPG/habitrpg/pull/7811 for updates on that functionality and talk to SabreCat if you have any comments or suggestions or see [this trello card](https://trello.com/c/XuVokK2V/108-add-weeklies-monthlies-to-habitica-com)

**Comment by Alys** [comment] 2016-07-26 01:17
@battlmonstr @audiolion Actually comments and suggestions should still go on [that Trello card](https://trello.com/c/XuVokK2V/108-add-weeklies-monthlies-to-habitica-com), not directly to SabreCat and not to the "WIP: Monthlies" pull request. SabreCat will see any comments added to the Trello card, and that's the best place for them to keep all feature suggestions and comments together in one place, for the benefit of both this change and future ones.

**Comment by audiolion** [comment] 2016-07-26 04:48
Apologies! Cant edit anymore
