### ISSUE TITLE
Font rendered e's weirdly

### ISSUE THREAD

**Issue by wysawyg** [HabitRPG/habitica#3900] opened 2014-08-21 18:19 UTC
In the last day I've noticed that the font appears to have changed and all e's are now rendering like c's with a longer top part (see image). I've used Chrome developer tools to inspect the CSS and I can't see anything odd there. Main font applicable css seems to be: font-family: 'Lato,sans serif'; font-size: 14px. Where I applied these to a little test html file, I wasn't getting the same effect!

From the looks of the tavern chat, there is at least one other user having the problem so it's unlikely to be me (though I have tried clearing the cache incase).

![2014-08-21 19_13_47-habitrpg _ your life the role playing game](https://cloud.githubusercontent.com/assets/8496107/4001020/9117b31c-295f-11e4-961f-91dc569da5a4.png)

**Comment by lemoness** [comment] 2014-08-21 18:38
Just a quick note that I am not having this issue in Safari.

**Comment by Holseties** [comment] 2014-08-21 21:11
I'm having the exact same issue and I'm on Chrome as well. The @ symbol also has some bits missing from it.

**Comment by LlamaHobbit** [comment] 2014-08-22 10:40
Having this issue with the lowercase letter 'e' in Chrome as well, but not in Firefox. It actually began immediately after I cleared my cache on 8/21/14, which I don't usually remember to do and it had been awhile.

**Comment by LlamaHobbit** [comment] 2014-08-22 10:46
Hmm, I refreshed one more time to get recent chat, and suddenly the problem is gone. Not sure why that refresh worked and previous ones had not worked, but I assume somebody fixed the problem. Thanks!

**Comment by negue** [comment] 2014-08-27 18:40
So I guess we can close this and #3902

**Closed as completed** 2014-08-27 18:48 UTC

**Comment by Alys** [comment] 2014-08-27 18:50
We believe this has been fixed so I'm closing this issue, however if anyone is still having problems, please say so here and I'll reopen it.
