### ISSUE TITLE
Completed To-Do's won't clear

### ISSUE THREAD

**Issue by GinnyJ** [HabitRPG/habitica#5105] opened 2015-04-30 01:31 UTC
Hi there, I'm user 96718fcb-646c-4602-bd57-2cc55af9c4df 
I'm kind of new to HabitRPG and have recently been having a few issues with the site, including lagging on Chrome and freezing in Firefox until the homepage loads when I first log into Habit, but the most recent and annoying issue is the unresponsive script messages on Firefox that say:
"A script on this page may be busy, or it may have stopped responding. You can stop the script now, open the script in the debugger, or let the script continue.

Script: https://habitrpg.com/app-ad920dd5.js:1" 
I have read on other threads that deleting completed To-Do's will get rid of this issue, but my completed To-Do's won't clear when I delete them. I have quite a lot of completed and uncompleted To-Do's, as well as a bunch of habits and Dailies. How can I fix this?

**Comment by Alys** [comment] 2015-04-30 03:04
The message "A script on this page may be busy, or it may have stopped responding. ..." is a standard browser message that you can see on many sites from time to time. Can be a sign that your browser is overloaded, rather than a problem with the website (although it can be that too). Whenever you see it, click the stop option, and then reload the HabitRPG website.

If you have many tabs open in your browser, try closing as many as you can to improve browser performance. If you don't mind telling us, how many tabs do you usually have open when these problems happen? An estimate is okay of course!

How many tasks of each kind do you have? The easiest way to count them if there's a lot is to go to Data -> Data Display Tool and use the Task Statistics section.

For Firefox, I often notice freezing for a couple to a few seconds when I start or reload HabitRPG, but it unfreezes after that.

When you say that completed To-Dos won't delete, can you give more details? Firstly, are you deleting them with the "Delete" button at the bottom of the Done tab? If not, definitely use that button. When you click on it, do you get any errors? 

Are the only remaining To-Dos from challenges that are still ongoing? If so, that's expected behaviour. They won't be delete until the challenge is over, otherwise your progress in the challenge wouldn't be visible to the challenge creator when they choose a winner.

**Comment by deilann** [comment] 2015-04-30 04:48
They won't delete even when the challenge is over. :) You have to remove
them the same way you remove other challenge tasks.

**Comment by Alys** [comment] 2015-07-26 12:41
I'm closing this since it's been a few months without a response, but @GinnyJ let us know if you are still having this problem and see my questions from my previous comment.

**Closed as completed by Alys** 2015-07-26 12:41 UTC
