### ISSUE TITLE
Tasks reappearing in to-do list - multiple duplicated To-Dos (same ID, etc)

### ISSUE THREAD

**Issue by akwilke** [HabitRPG/habitica#4588] opened 2015-01-28 22:15 UTC
![image](https://cloud.githubusercontent.com/assets/10748453/5948292/643419b2-a709-11e4-8511-f1f863c5fede.png)

Several tasks will not clear from my todo list.  I cannot delete them and if I click that I completed them they reappear as soon as the screen refreshes.  On the attached image the following tasks continue to reappear  "update job description", "enter concerts", "finish real life manual and print", "list of projects-update res life", "notes berenice", "notes murielle"

**Comment by Alys** [comment] 2015-01-28 22:21
If this is still happening in 10 to 12 hours (after I get home from work today), I'll look into your account in the database and fix whatever the problem is.

Please let us know if the problem disappears before then!

BTW, you might like to take another screenshot that shows only your tasks and edit your comment to replace the screenshot that's there now. The current screenshot is showing your emails, meetings, contacts.

**Comment by akwilke** [comment] 2015-01-28 22:23
Ok here is my user id 30fb2640-7121-4968-ace5-f385e60ea6c5  Also a few of the tasks this has been happening for several days in multiple browser types including Chrome, IE, and Firefox.    I think I updated the screen shot.  Thanks.

**Comment by Alys** [comment] 2015-01-29 10:29
@lefnire @paglias FYI an extreme example of duplicated tasks (same text, same id, same creation date for many tasks).

@akwilke Many of your tasks exist multiple times in the database. For example, "notes for tawny" is in there six times (that's the worst one). HabitRPG shows you only one task from each duplicate set at a time, and then when you mark that task completed or when you delete it, it shows you a different one from the same set. So the tasks aren't actually reappearing or refusing to delete; instead, you're seeing duplicated tasks that you hadn't seen before.

For the tasks you listed ("update job description", "enter concerts", "finish real life manual and print", "list of projects-update res life", "notes berenice", "notes murielle"), I believe I have deleted all of them. Let me know if I've missed any! I'll need to know the exact text for a database search.

There are still many other tasks that exist multiple times, and I haven't touched those since you probably haven't completed them. The good news is that most of them have only one duplicate, although some do have up to four, and "notes for tawny" has six. I think, when you go to tick off a task and notice that it has reappeared, then you should be able to delete the new instance of the task. You might need to do this up to five times, but after that, the task should be gone. I would be interested to know if this does actually work. Be sure to tell me if it does not!

I should be able to remove the duplicates for the tasks that you haven't completed, so that you won't have to go through this annoying deletion process, however I will need to think about the most efficient way of doing that, and I'll need to do it on a day when I have sufficient time free to be able to do it slowly and carefully. I'll try to work on it this weekend. I'll be sure to make a backup of your data first, so no matter what happens your tasks will be safe.

I would also like to try work out how this happened. It could be a bug in HabitRPG, or it could be something external. Can you tell me please if you're using any third-party applications that communicate with HabitRPG? For example, do you have programs or apps or websites that add tasks (apart from HabitRPG itself of course)? Or any tools that integrate some other task management application with HabitRPG? Or have you noticed any odd behaviour in HabitRPG apart from these reappearing tasks?

**Comment by akwilke** [comment] 2015-01-29 14:12
Hi Alice,

I am not using a third party application to create tasks.  I do sometimes
have Habit open in both my app and on my desk top and I had wondered if
that could cause issues.  The ways that I access Habit are through the web
on my desk top, the web on my tablet, the app on my phone, and occasionally
the web on my phone when I have trouble getting the app to load (this has
mostly been taken care of since I uninstalled and reinstalled the app).

Autumn

On Thu, Jan 29, 2015 at 4:29 AM, Alice Harris notifications@github.com
wrote:

> @lefnire https://github.com/lefnire @paglias
> https://github.com/paglias FYI an extreme example of duplicated tasks
> (same text, same id, same creation date for many tasks).
> 
> @akwilke https://github.com/akwilke Many of your tasks exist multiple
> times in the database. For example, "notes for tawny" is in there six times
> (that's the worst one). HabitRPG shows you only one task from each
> duplicate set at a time, and then when you mark that task completed or when
> you delete it, it shows you a different one from the same set. So the tasks
> aren't actually reappearing or refusing to delete; instead, you're seeing
> duplicated tasks that you hadn't seen before.
> 
> For the tasks you listed ("update job description", "enter concerts",
> "finish real life manual and print", "list of projects-update res life",
> "notes berenice", "notes murielle"), I believe I have deleted all of them.
> Let me know if I've missed any! I'll need to know the exact text for a
> database search.
> 
> There are still many other tasks that exist multiple times, and I haven't
> touched those since you probably haven't completed them. The good news is
> that most of them have only one duplicate, although some do have up to
> four, and "notes for tawny" has six. I think, when you go to tick off a
> task and notice that it has reappeared, then you should be able to delete
> the new instance of the task. You might need to do this up to five times,
> but after that, the task should be gone. I would be interested to know if
> this does actually work. Be sure to tell me if it does not!
> 
> I should be able to remove the duplicates for the tasks that you haven't
> completed, so that you won't have to go through this annoying deletion
> process, however I will need to think about the most efficient way of doing
> that, and I'll need to do it on a day when I have sufficient time free to
> be able to do it slowly and carefully. I'll try to work on it this weekend.
> I'll be sure to make a backup of your data first, so no matter what happens
> your tasks will be safe.
> 
> I would also like to try work out how this happened. It could be a bug in
> HabitRPG, or it could be something external. Can you tell me please if
> you're using any third-party applications that communicate with HabitRPG?
> For example, do you have programs or apps or websites that add tasks (apart
> from HabitRPG itself of course)? Or any tools that integrate some other
> task management application with HabitRPG? Or have you noticed any odd
> behaviour in HabitRPG apart from these reappearing tasks?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/HabitRPG/habitrpg/issues/4588#issuecomment-72002843.

## 

Autumn Wilke
Residence Life Coordinator
Academic Advisor
Grinnell College

wilkeaut@grinnell.edu
641-269-3761

**Comment by akwilke** [comment] 2015-01-29 14:15
Also, I thought I would mention that "notes for tawny" doesn't show up in
my task list.  I completed that one a few days ago and did not get
duplicates for it.  So it is interesting that there are still duplicates of
it on the server.

On Thu, Jan 29, 2015 at 8:11 AM, Autumn Wilke autumn.k.wilke@gmail.com
wrote:

> Hi Alice,
> 
> I am not using a third party application to create tasks.  I do sometimes
> have Habit open in both my app and on my desk top and I had wondered if
> that could cause issues.  The ways that I access Habit are through the web
> on my desk top, the web on my tablet, the app on my phone, and occasionally
> the web on my phone when I have trouble getting the app to load (this has
> mostly been taken care of since I uninstalled and reinstalled the app).
> 
> Autumn
> 
> On Thu, Jan 29, 2015 at 4:29 AM, Alice Harris notifications@github.com
> wrote:
> 
> > @lefnire https://github.com/lefnire @paglias
> > https://github.com/paglias FYI an extreme example of duplicated tasks
> > (same text, same id, same creation date for many tasks).
> > 
> > @akwilke https://github.com/akwilke Many of your tasks exist multiple
> > times in the database. For example, "notes for tawny" is in there six times
> > (that's the worst one). HabitRPG shows you only one task from each
> > duplicate set at a time, and then when you mark that task completed or when
> > you delete it, it shows you a different one from the same set. So the tasks
> > aren't actually reappearing or refusing to delete; instead, you're seeing
> > duplicated tasks that you hadn't seen before.
> > 
> > For the tasks you listed ("update job description", "enter concerts",
> > "finish real life manual and print", "list of projects-update res life",
> > "notes berenice", "notes murielle"), I believe I have deleted all of them.
> > Let me know if I've missed any! I'll need to know the exact text for a
> > database search.
> > 
> > There are still many other tasks that exist multiple times, and I haven't
> > touched those since you probably haven't completed them. The good news is
> > that most of them have only one duplicate, although some do have up to
> > four, and "notes for tawny" has six. I think, when you go to tick off a
> > task and notice that it has reappeared, then you should be able to delete
> > the new instance of the task. You might need to do this up to five times,
> > but after that, the task should be gone. I would be interested to know if
> > this does actually work. Be sure to tell me if it does not!
> > 
> > I should be able to remove the duplicates for the tasks that you haven't
> > completed, so that you won't have to go through this annoying deletion
> > process, however I will need to think about the most efficient way of doing
> > that, and I'll need to do it on a day when I have sufficient time free to
> > be able to do it slowly and carefully. I'll try to work on it this weekend.
> > I'll be sure to make a backup of your data first, so no matter what happens
> > your tasks will be safe.
> > 
> > I would also like to try work out how this happened. It could be a bug in
> > HabitRPG, or it could be something external. Can you tell me please if
> > you're using any third-party applications that communicate with HabitRPG?
> > For example, do you have programs or apps or websites that add tasks (apart
> > from HabitRPG itself of course)? Or any tools that integrate some other
> > task management application with HabitRPG? Or have you noticed any odd
> > behaviour in HabitRPG apart from these reappearing tasks?
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/HabitRPG/habitrpg/issues/4588#issuecomment-72002843.
> 
> ## 
> 
> Autumn Wilke
> Residence Life Coordinator
> Academic Advisor
> Grinnell College
> 
> wilkeaut@grinnell.edu
> 641-269-3761

## 

Autumn Wilke
Residence Life Coordinator
Academic Advisor
Grinnell College

wilkeaut@grinnell.edu
641-269-3761

**Comment by akwilke** [comment] 2015-01-29 21:02
I have a new task that won't go away.  I tried to "complete" it 6 or 7
times and it keeps coming back.  It is "add people to access-roland, polly,
tawny, anne"

Thanks for your continued help!

A

On Thu, Jan 29, 2015 at 8:14 AM, Autumn Wilke autumn.k.wilke@gmail.com
wrote:

> Also, I thought I would mention that "notes for tawny" doesn't show up in
> my task list.  I completed that one a few days ago and did not get
> duplicates for it.  So it is interesting that there are still duplicates of
> it on the server.
> 
> On Thu, Jan 29, 2015 at 8:11 AM, Autumn Wilke autumn.k.wilke@gmail.com
> wrote:
> 
> > Hi Alice,
> > 
> > I am not using a third party application to create tasks.  I do sometimes
> > have Habit open in both my app and on my desk top and I had wondered if
> > that could cause issues.  The ways that I access Habit are through the web
> > on my desk top, the web on my tablet, the app on my phone, and occasionally
> > the web on my phone when I have trouble getting the app to load (this has
> > mostly been taken care of since I uninstalled and reinstalled the app).
> > 
> > Autumn
> > 
> > On Thu, Jan 29, 2015 at 4:29 AM, Alice Harris notifications@github.com
> > wrote:
> > 
> > > @lefnire https://github.com/lefnire @paglias
> > > https://github.com/paglias FYI an extreme example of duplicated tasks
> > > (same text, same id, same creation date for many tasks).
> > > 
> > > @akwilke https://github.com/akwilke Many of your tasks exist multiple
> > > times in the database. For example, "notes for tawny" is in there six times
> > > (that's the worst one). HabitRPG shows you only one task from each
> > > duplicate set at a time, and then when you mark that task completed or when
> > > you delete it, it shows you a different one from the same set. So the tasks
> > > aren't actually reappearing or refusing to delete; instead, you're seeing
> > > duplicated tasks that you hadn't seen before.
> > > 
> > > For the tasks you listed ("update job description", "enter concerts",
> > > "finish real life manual and print", "list of projects-update res life",
> > > "notes berenice", "notes murielle"), I believe I have deleted all of them.
> > > Let me know if I've missed any! I'll need to know the exact text for a
> > > database search.
> > > 
> > > There are still many other tasks that exist multiple times, and I
> > > haven't touched those since you probably haven't completed them. The good
> > > news is that most of them have only one duplicate, although some do have up
> > > to four, and "notes for tawny" has six. I think, when you go to tick off a
> > > task and notice that it has reappeared, then you should be able to delete
> > > the new instance of the task. You might need to do this up to five times,
> > > but after that, the task should be gone. I would be interested to know if
> > > this does actually work. Be sure to tell me if it does not!
> > > 
> > > I should be able to remove the duplicates for the tasks that you haven't
> > > completed, so that you won't have to go through this annoying deletion
> > > process, however I will need to think about the most efficient way of doing
> > > that, and I'll need to do it on a day when I have sufficient time free to
> > > be able to do it slowly and carefully. I'll try to work on it this weekend.
> > > I'll be sure to make a backup of your data first, so no matter what happens
> > > your tasks will be safe.
> > > 
> > > I would also like to try work out how this happened. It could be a bug
> > > in HabitRPG, or it could be something external. Can you tell me please if
> > > you're using any third-party applications that communicate with HabitRPG?
> > > For example, do you have programs or apps or websites that add tasks (apart
> > > from HabitRPG itself of course)? Or any tools that integrate some other
> > > task management application with HabitRPG? Or have you noticed any odd
> > > behaviour in HabitRPG apart from these reappearing tasks?
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/HabitRPG/habitrpg/issues/4588#issuecomment-72002843
> > > .
> > 
> > ## 
> > 
> > Autumn Wilke
> > Residence Life Coordinator
> > Academic Advisor
> > Grinnell College
> > 
> > wilkeaut@grinnell.edu
> > 641-269-3761
> 
> ## 
> 
> Autumn Wilke
> Residence Life Coordinator
> Academic Advisor
> Grinnell College
> 
> wilkeaut@grinnell.edu
> 641-269-3761

## 

Autumn Wilke
Residence Life Coordinator
Academic Advisor
Grinnell College

wilkeaut@grinnell.edu
641-269-3761

**Comment by Alys** [comment] 2015-02-03 06:44
I'm sorry @akwilke, I've only just noticed your most recent two comments! They didn't get emailed to me the way comments usually do.

I'm not sure that having HabitRPG open in two devices at once would cause duplicates. I usually have it open in at least two browser tabs at once, often two browsers on separate PCs, and sometimes the app as well, and I've never noticed duplicate tasks. However if duplicates keep being a problem for you, it might be worth closing one instance of HabitRPG before you open another, just to see if that makes a difference.

I've looked at the "notes for tawny" tasks more closely and they are all marked as completed, with completion dates more than three days in the past, so none of them will be showing up in the HabitRPG web interface. The duplicates would have been created after you completed it, so you never saw them.

The "add people ..." task has only two duplicates, one completed and one not. I've removed them both. I hope that's okay. I have a backup so I can put the completed one back into your account if you need it for record-keeping.

I wasn't able to spend any time on this over the weekend because I had to deal with another database issue that was affecting many people. I'm still going to work out the most efficient way of deleting all of the duplicates for you, but it might be another few days before I can. Let me know if there are any that are really bothering you right now!

**Comment by Alys** [comment] 2015-02-07 03:26
@akwilke I've gone through your data and removed all tasks that had duplicate "unique" ID numbers, although I believe all of them were now completed, so they were probably not causing you problems any more. There were a lot of tasks that had identical or very similar text, but did not have the same ID numbers, so I think it's likely that they were just similar tasks that you added manually yourself. I haven't removed them.

I'm going to close this issue now, but if you have any more problems with duplicate tasks, or with tasks reappearing after you've ticked them off (which is usually a sign of duplication), let us know! I now have a script that will identify and delete duplicates rapidly, so we should be able to fix this problem much faster next time.

**Comment by akwilke** [comment] 2015-02-25 22:30
Hello Alys, This issue is back :(  I have several tasks that are reappearing and that are actually showing up in my to do list more than once at the same time.  Currently the issues that are reappearing are "scheudle with evan in its". "notes robert." "work on crappy page for website" "notes tolu"  The scheudle with evan in its also appeared multiple times on my to do list but i was able to clear the duplicates but not the reoccurance.

**Comment by Alys** [comment] 2015-02-25 22:56
I'm sorry to hear that @akwilke! We'll get those tasks fixed up for you, although it might take a few hours.

**Comment by Alys** [comment] 2015-02-26 11:14
There were twelve tasks that had been identically duplicated (identical text, and the same "unique" ID number). I have removed the duplicates. 

You have a huge number of To-Dos, many of them completed (over 1400 if my estimate is correct). It's possible that the load from them all is contributing to the duplications (although that's a bit of a wild guess). You might wish to consider deleting all the old To-Dos. The majority of them won't be showing up in the website because they are too old, but they are still part of your account. If you'd like to clear them out, there's instructions on the wiki at [To-Dos -> Clean Up](http://habitrpg.wikia.com/wiki/To-dos#Clean_up), including a link to a page about exporting them if you want to keep a record of them.

**Closed as completed by Alys** 2015-02-26 11:14 UTC
Labels: status: issue: needs investigation

**Comment by Alys** [comment] 2015-02-26 11:34
I forgot to say: Do tell us again if the problem persists! :)

**Comment by akwilke** [comment] 2015-02-26 14:04
Great thanks! I will go in and clean those up.

**Comment by akwilke** [comment] 2015-04-03 14:05
Hi Alice,

I have another new task that is reappearing.  This time it is "email
deparments again"

Thanks for your continued help!

On Thu, Jan 29, 2015 at 3:02 PM, Autumn Wilke autumn.k.wilke@gmail.com
wrote:

> I have a new task that won't go away.  I tried to "complete" it 6 or 7
> times and it keeps coming back.  It is "add people to access-roland, polly,
> tawny, anne"
> 
> Thanks for your continued help!
> 
> A
> 
> On Thu, Jan 29, 2015 at 8:14 AM, Autumn Wilke autumn.k.wilke@gmail.com
> wrote:
> 
> > Also, I thought I would mention that "notes for tawny" doesn't show up in
> > my task list.  I completed that one a few days ago and did not get
> > duplicates for it.  So it is interesting that there are still duplicates of
> > it on the server.
> > 
> > On Thu, Jan 29, 2015 at 8:11 AM, Autumn Wilke autumn.k.wilke@gmail.com
> > wrote:
> > 
> > > Hi Alice,
> > > 
> > > I am not using a third party application to create tasks.  I do
> > > sometimes have Habit open in both my app and on my desk top and I had
> > > wondered if that could cause issues.  The ways that I access Habit are
> > > through the web on my desk top, the web on my tablet, the app on my phone,
> > > and occasionally the web on my phone when I have trouble getting the app to
> > > load (this has mostly been taken care of since I uninstalled and
> > > reinstalled the app).
> > > 
> > > Autumn
> > > 
> > > On Thu, Jan 29, 2015 at 4:29 AM, Alice Harris notifications@github.com
> > > wrote:
> > > 
> > > > @lefnire https://github.com/lefnire @paglias
> > > > https://github.com/paglias FYI an extreme example of duplicated
> > > > tasks (same text, same id, same creation date for many tasks).
> > > > 
> > > > @akwilke https://github.com/akwilke Many of your tasks exist
> > > > multiple times in the database. For example, "notes for tawny" is in there
> > > > six times (that's the worst one). HabitRPG shows you only one task from
> > > > each duplicate set at a time, and then when you mark that task completed or
> > > > when you delete it, it shows you a different one from the same set. So the
> > > > tasks aren't actually reappearing or refusing to delete; instead, you're
> > > > seeing duplicated tasks that you hadn't seen before.
> > > > 
> > > > For the tasks you listed ("update job description", "enter concerts",
> > > > "finish real life manual and print", "list of projects-update res life",
> > > > "notes berenice", "notes murielle"), I believe I have deleted all of them.
> > > > Let me know if I've missed any! I'll need to know the exact text for a
> > > > database search.
> > > > 
> > > > There are still many other tasks that exist multiple times, and I
> > > > haven't touched those since you probably haven't completed them. The good
> > > > news is that most of them have only one duplicate, although some do have up
> > > > to four, and "notes for tawny" has six. I think, when you go to tick off a
> > > > task and notice that it has reappeared, then you should be able to delete
> > > > the new instance of the task. You might need to do this up to five times,
> > > > but after that, the task should be gone. I would be interested to know if
> > > > this does actually work. Be sure to tell me if it does not!
> > > > 
> > > > I should be able to remove the duplicates for the tasks that you
> > > > haven't completed, so that you won't have to go through this annoying
> > > > deletion process, however I will need to think about the most efficient way
> > > > of doing that, and I'll need to do it on a day when I have sufficient time
> > > > free to be able to do it slowly and carefully. I'll try to work on it this
> > > > weekend. I'll be sure to make a backup of your data first, so no matter
> > > > what happens your tasks will be safe.
> > > > 
> > > > I would also like to try work out how this happened. It could be a bug
> > > > in HabitRPG, or it could be something external. Can you tell me please if
> > > > you're using any third-party applications that communicate with HabitRPG?
> > > > For example, do you have programs or apps or websites that add tasks (apart
> > > > from HabitRPG itself of course)? Or any tools that integrate some other
> > > > task management application with HabitRPG? Or have you noticed any odd
> > > > behaviour in HabitRPG apart from these reappearing tasks?
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > https://github.com/HabitRPG/habitrpg/issues/4588#issuecomment-72002843
> > > > .
> > > 
> > > ## 
> > > 
> > > Autumn Wilke
> > > Residence Life Coordinator
> > > Academic Advisor
> > > Grinnell College
> > > 
> > > wilkeaut@grinnell.edu
> > > 641-269-3761
> > 
> > ## 
> > 
> > Autumn Wilke
> > Residence Life Coordinator
> > Academic Advisor
> > Grinnell College
> > 
> > wilkeaut@grinnell.edu
> > 641-269-3761
> 
> ## 
> 
> Autumn Wilke
> Residence Life Coordinator
> Academic Advisor
> Grinnell College
> 
> wilkeaut@grinnell.edu
> 641-269-3761

## 

Autumn Wilke
Residence Life Coordinator
Academic Advisor
Grinnell College

wilkeaut@grinnell.edu
641-269-3761

**Comment by Alys** [comment] 2015-04-03 23:21
We've had a lot of success lately with deleting duplicate tasks starting from the bottom of the list - so, scroll to the bottom and then scroll up slowly, looking for each duplicate and deleting it as you find it. Deleting from the top down often doesn't work.

If the duplicates are To-Dos, then you will probably need to delete all completed To-Dos first.

Please reply if this doesn't fix the problem for you!
