### ISSUE TITLE
When I level up, (lvl40) It tries to give me a scroll but can't. and then the lvl up resets

### ISSUE THREAD

**Issue by Lost--** [HabitRPG/habitica#5102] opened 2015-04-29 04:52 UTC
Please reload, "Error Cannot set property 'drop' of undefined" If the error persists, please report it at Help > Report a Bug. If you're familiar with your browser's console, please include any error messages

**Comment by Lost--** [comment] 2015-04-29 04:53
I keep reloading, but the same thing keeps happening

**Comment by deilann** [comment] 2015-04-29 04:56
Level up without using a skill. You can use fcv to achieve this. If you
search the error you can find the discussion on this bug. I'd point you
there myself but I am on my phone.

**Comment by crookedneighbor** [comment] 2015-04-29 13:52
Duplicate of #4986

**Closed as completed by crookedneighbor** 2015-04-29 13:52 UTC
