### ISSUE TITLE
Inconsistently Aligned Mount Sprites

### ISSUE THREAD

**Issue by beffymaroo** [HabitRPG/habitica#7982] opened 2016-09-08 17:45 UTC
### Description

Some mount sprites (head/body) appear to be aligned inconsistently across mount colors- this is particularly noticeable with magic potion mounts. 

First spotted in the wiki: 

![untitled-1](https://cloud.githubusercontent.com/assets/9218855/18360009/328d44ba-75b1-11e6-8c4a-a19ec190937f.png)
#### Console Errors

n/a

**Comment by delphinium89** [comment] 2016-09-21 17:36
It seems like the PNG images used in the wiki for floral are all cropped differently.

Compare: http://vignette4.wikia.nocookie.net/habitrpg/images/c/cc/Mount_TigerCub-Peppermint.png

To: http://vignette2.wikia.nocookie.net/habitrpg/images/8/88/Mount_TigerCub-Floral.png

**Comment by TheJadeFox** [comment] 2016-10-03 00:25
Hi.  I copy/pasted both images onto a word doc and they appear to be identical.  Maybe I could try taking them apart or layering them, to check the exact measurements but to the naked eye they look the same.
It may possibly be the flowers.  Which in my opinion are one of their best features.

**Comment by SabreCat** [comment] 2016-10-03 14:34
Sounds like the issue is just the wiki page, not the sprites here in the repo, so I'll close this. If there is some misalignment on the actual site, please update with a relevant screenshot and we can reopen the ticket!

**Comment by beffymaroo** [comment] 2016-10-03 18:38
I was told by the guild members in Wizards of the Wiki that they use the sprite images directly from the repository. 

Comparison of Pandas in-game: 
![panda_sprites](https://cloud.githubusercontent.com/assets/9218855/19049106/d8891b0e-895d-11e6-9b6c-9bbd1860cf9e.jpg)

**Comment by TheJadeFox** [comment] 2016-10-04 04:06
Yes. The body of the Pink Panda is shorter.
1.3 cm Orange Panda distance from head edge to tail
just under 1 cm Pink Panda

![orange](https://cloud.githubusercontent.com/assets/19853880/19063422/925ee1e0-89b7-11e6-90a0-da2326d9c77b.jpg)
![pink](https://cloud.githubusercontent.com/assets/19853880/19063427/9f4d24e8-89b7-11e6-8553-47115c8336f6.jpg)

**Comment by SabreCat** [comment] 2016-10-04 14:07
Hmm, so maybe the front and back sprites weren't aligned consistently. But which one is correct? Or maybe they were designed a little differently for variety's sake? ( @lemoness ..?)

**Comment by khipkin** [comment] 2016-10-04 15:15
In my opinion, it doesn't make sense for them to be different, except for coloring obviously.  I would be surprised if it was intentional.

**Comment by beffymaroo** [comment] 2016-10-04 17:16
Right, I think the issue is that artists may have been unclear on how to line up the layers when doing the Magic Potion recolors (myself included, I struggled with this a bit because they didn't align intuitively when the layers were pasted together in Photoshop).

All the original Classic Mount recolors seem to be aligned consistently when equipped.

**Comment by khipkin** [comment] 2016-10-04 23:29
@beffymaroo Would fixing the inconsistencies be a task best handled by an artisan?

**Comment by lemoness** [comment] 2016-10-08 20:04
The panda alignment should match that of the classic colors, so let's use
the Base Mount for comparison.

Khipkin is right that this might be a good task for an artisan. Can I get a
list of all the inconsistent mounts that need to be tweaked? In the
meantime, let's leave the ticket open, since the sprites will need to be
added eventually, and mark it "On hold."

**Comment by Hus274** [comment] 2016-12-07 02:28
### Body Issues
This is a list of the body issues that I was able to find looking through the repository. Still need to look through head files.
* Flying Pig Body
  * Floral
  * Peppermint
  * Spooky
  * Thunderstorm
* Lion Cub Body
  * Etheral
  * Peppermint
  * Spooky
  * Thunderstorm
* Tiger Body
  * Floral
  * Peppermint
  * Spooky
  * Thunderstorm
* Panda Cub
  * Peppermint

**Comment by Hus274** [comment] 2016-12-07 02:44
### Head Issues
* Dragon (covered by #8253)
* Flying Pig Head - Listed ones are moved slightly up and left
  * Floral
  * Peppermint
  * Spooky
  * Thunderstorm
* Fox Head - These are too high
  * Peppermint
  * Spooky
* Lion Cub Head - Ever so slightly too high and to the left. This might not be noticeable really
  * Peppermint
  * Floral
  * Spooky
  * Thunderstorm
* Panda Head
  * Peppermint -> too far right, no legs
  * Spooky -> too far left
* Tiger Cub -> too high and too far left
  * Floral
  * Peppermint
  * Spooky
  * Thunderstorm

**Comment by Hus274** [comment] 2016-12-07 02:45
These are all the ones I could find by just checking all the images in the repository.

**Comment by padm0** [comment] 2016-12-12 00:23
Hello! I've started working on some of these images. What would be the best way to submit the corrections?

**Comment by SabreCat** [comment] 2016-12-12 17:18
@padm0: A pull request would be ideal. I saw you did one already for the cornucopia set, so keep doing that! Let us know if you need any help.

**Closed as completed** 2016-12-17 00:46 UTC
Labels: priority: minor, status: issue: on hold
