### ISSUE TITLE
Deleted Tasks reappear after Sync

### ISSUE THREAD

**Issue by Vorakesh** [HabitRPG/habitica#1730] opened 2013-11-03 11:10 UTC
The "Example Tasks" reappear after I hit the Sync button or just re-login.

In the Android App my tasks appear after a couple of seconds on their own.

The can be edited (eating Junk Food is now a positive habit ;)) but not deleted

**Comment by Verax2** [comment] 2013-11-03 15:40
Same results here.  Example tasks return after re-login or refresh.

If I delete my own stuff it stays gone, but not the original example tasks.

**Comment by lefnire** [comment] 2013-11-04 02:24
this is a critical one, i'm gonna work on this asap. There's a mismatch going on between `task._id` and `task.id` (something to look out for @paglias )

**Comment by lefnire** [comment] 2013-11-04 06:31
dupe of #1741, fixed

**Closed as completed by lefnire** 2013-11-04 06:31 UTC
