### ISSUE TITLE
when buying new equipment, item does not disappear from Market or Seasonal Shop

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#10920] opened 2018-12-26 03:22 UTC
When you go to Shops > Market or Shops > Seasonal Shop to buy an equipment piece that you have not previously owned, the purchase is successful (the item appears in your Inventory immediately) but the bought item does not disappear from the Shop until you sync. I.e., it looks as if you haven't been able to buy the item, which will be confusing and frustrating to anyone attempting to use the Shop for the current Grand Gala gear.

Note that if you are buying an item because you previously owned it and lost it due to death, then it DOES disappear from the Market as soon as you buy it, so this bug only happens if the item was not already stored in your account with a false value.

The bug does not occur if you buy a new item from your Rewards column.

_Thanks to cTheDragons for reporting this._

**Comment by Alys** [comment] 2019-06-19 09:50
Reopening because this is happening again. Confirmed by me, reported by Aerilita (3b724a41-48d3-4048-ae27-70b258cf5a72):

"On the website, the available for me seasonal equipment doesn't disappear from the Market after buying, unless I force sync or reload the page. All four of them did that (so I tried both reload and force-sync)."

**Comment by Alys** [comment] 2019-07-30 09:38
I've just tested and confirmed that this issue is still happening.

**Comment by Xaz16** [comment] 2019-09-06 11:40
Hi folks!
@Alys can I take this one?

**Comment by Alys** [comment] 2019-09-07 08:09
@Xaz16 Sure! Thanks! :)

**Comment by Xaz16** [comment] 2019-09-15 19:41
@Alys, could you check please this issue again? As I can see all items which I can buy/purchase for gold/gems are disappearing immediately.

If you can reproduce it, could you please describe steps for reproduce comprehensively? (which season, which item)

**Comment by Alys** [comment] 2019-09-16 10:40
@Xaz16 I've just tested on habitica.com and it's still happening as described in the first paragraph of this issue.

I haven't tested on a local install because I'm using a new computer and still getting the local install set up. :-/

If you want to test it in production, tell me your Habitica Username or User ID and I'll remove some of the basic class equipment that you own. That will let you replicate the bug.

**Comment by Xaz16** [comment] 2019-09-18 14:46
@Alys no, thanks. Production is production. Can you please just describe step by step what are you doing exactly? Which tab of market do you use (special, equipment, quests)? What item and for what currency do you buy it?

**Comment by Alys** [comment] 2019-09-19 04:06
To replicate this: "When you go to Shops > Market or Shops > Seasonal Shop
to buy an equipment piece that you have not previously owned, the purchase
is successful (the item appears in your Inventory immediately) but the
bought item does not disappear from the Shop until you sync":

1. Go to Shops > Market (or Shops > Seasonal Shop when items are available
there).
2. Pick an equipment piece that you see there that you have not previously
bought. It will be in the Equipment section of the page (the other sections
never have equipment for sale). It needs to be an item that's available for
you to buy (so not a locked item). It doesn't matter what item apart from
that.
3. Buy it with gold. Note that if you're choosing an older item in the
Seasonal Shop, you'd need to buy it for gems, not gold (the currency type
is displayed on the item) however it's possible that the bug doesn't occur
with gem-purchasable items so pick a gold purchasable one if you can.

**Comment by Xaz16** [comment] 2019-09-19 06:43
Thank you @Alys 
For now I can say that on my local machine I use old seasons for enable seasonal shop and buy eqiupment for gems and gold (I changed one if condition to get all equipment for gold) and I can say that all works as expected.

I will try to replicate this one for Market one, but I'm really sure that here we can see the same behavior (I tested it in market before seasonal). I will make a couple of additional attempts.

**Comment by Alys** [comment] 2019-09-25 01:38
@Xaz16 How are you going with this? If you haven't yet had time to set up a test account to replicate it, you can see the bug in production with the new Grand Gala gear if you try to buy it from the Market (not from the Rewards column).

**Comment by Xaz16** [comment] 2019-09-25 06:59
Hi @Alys 
For now I have not so much time for contributing to habitica, but I will try to fix it (not sure that this week).

**Comment by Xaz16** [comment] 2019-10-16 20:08
It is obvious but it looks like this issue can be reproduced only on production, due to we have seasonal event for now and on production I face this issue, but with same config in dev build issue can't be reproduced. 

I will spent a couple of hours on this issue to understand is that uglyfication of sources cause of issue...

**Comment by Xaz16** [comment] 2019-10-16 20:41
I found the way how to reproduce it. It is really simple: you shouldn't have any gear in market except seasonal. Only when you satisfy this condition you can reproduce this one.

**Comment by Xaz16** [comment] 2019-11-19 21:27
PR created: https://github.com/HabitRPG/habitica/pull/11563

**Comment by paglias** [comment] 2020-01-14 12:00
Fixed in #11637

**Closed as completed** 2020-01-14 12:01 UTC
Labels: priority: medium, status: issue: in progress, type: medium level coding, section: Market
