### ISSUE TITLE
Bug Problem

### ISSUE THREAD

**Issue by Vallent** [HabitRPG/habitica#1042] opened 2013-05-25 23:32 UTC
When I´d completed a task, i have received a base potion but instead i received 7 or 8 more or less, it´s a bug or it´s normal?

Thanks for read! ^^

**Comment by lefnire** [comment] 2013-05-26 09:44
duplicate of #901 , let's follow up there. When did this happen last?

**Comment by paglias** [comment] 2013-09-09 17:31
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!

**Closed as completed by paglias** 2013-09-09 17:31 UTC
