### ISSUE TITLE
Dailies not  resetting each day

### ISSUE THREAD

**Issue by Muna526** [HabitRPG/habitica#1107] opened 2013-05-31 12:55 UTC
The dailies haven't been resetted anymore since 2 days. They should be resetted each day. :(

**Comment by jftalarico** [comment] 2013-06-06 03:27
This has happened to me as well two days in a row now. Not only that but after it does reset it drops me back to the previous level and I loose a ton of HP. Frustrating.

**Comment by StanLindsey** [comment] 2013-06-06 09:46
May be a stupid question, but you're not currently checked in the inn are you?

**Comment by jftalarico** [comment] 2013-06-06 13:16
No. Never been to the in. I'm on an iPhone through safari and hit the refresh button to try and clear the screen. When it did clear it dropped me a level and took away a chunk of hp. 

Another time it wouldn't clear and every time I hit refresh my xp and hp would change a few points up or down. That was a couple weeks ago. First paragraph stuff happened twice this week. 

Love the idea though and thanks for looking into this.

**Comment by jftalarico** [comment] 2013-06-06 13:22
Just checked now and it brought me back a level and killed me.

**Comment by AndreCaseyScott** [comment] 2013-06-07 12:21
I believe #587 might be related. They both seem to stem from using Habit via multiple devices.

**Comment by StanLindsey** [comment] 2013-06-07 20:31
Sounds like the possibility that you're pushes aren't sticking. So when the server refreshes it doesn't think you've done your dailies and takes off a bunch of health. (Also you "drop" a level because on the server you may not of leveled up)

@lefnire - can we use the recent change to the drop dialog in this situation? Only keep a task checked if there is a response from the server? (If my hypothesis is correct that is, you maybe have a better idea)

**Comment by jftalarico** [comment] 2013-06-08 05:19
That's about how it feels. I refresh to try and get my dailies and habits to reset for a new day but it resets like I've done nothing from the previous day. All my HP drops and I die. This has been the third day in a row now. I've lost 3 pieces of armor now and all of my money. So I'm camping out in the tavern till I hear otherwise.

**Comment by lefnire** [comment] 2013-06-08 16:47
@SlappyBag nay, checkboxes track the `task.completed` property, which is Racer-managed. The drop thing was somewhat lucky for me since I can say "grant a drop upon successful mongo operation callback", but I can't do the same with updating the html - that's Derby-managed.

this is one of those things that's either multi-computer access or server downtime, so will have to wait till 0.5

**Comment by lsaxton** [comment] 2013-06-13 13:45
I had the same thing happen to me today, and I haven't been using it on multiple devices.

**Comment by kvalle** [comment] 2013-06-14 07:45
Same happened to me today. 

Completed only 1 out of my 3 dailies yesterday. Today the one I completed is still checked. It must have registered that it's a new day, however, as I lost HP for the ones I didn't complete.

I'm using HabitRPG from two different computers, but I am careful not to have it open in both locations at the same time, if that matters.

**Comment by Catmagnet** [comment] 2013-06-14 22:11
Perhaps it's just as well I've never tried to log in to Habit RPG on my phone!  However, I have the "dailies not resetting" problem today.  I've tried both the regular site and the beta, and still no new dailies.  It's sitting right where it was when I went to bed (which admittedly was 6 a.m. my time, but my reset is 8 a.m. my time).

**Comment by nrstarr** [comment] 2013-07-23 21:07
Just happened to me. I have a custom reset time at 5 AM, checked off a bunch of dailies last night past midnight but before 5 AM on my phone. Checked on my computer today, and they still haven't reset, on either beta or the main site. Same on my phone. If it's relevant, I normally use just my phone (iPhone 4) and haven't run into this before.

**Comment by AndreCaseyScott** [comment] 2013-07-23 21:29
It's caused by using multiple devices. Happens to me every time i use the
mobile app. Will probably be fixed by the angular.js rewrite. The only work
around is to only use habit on one device.

**Comment by KookinKeith** [comment] 2013-07-30 15:22
Does anyone know if the issue is due to the fact that we are using multiple devices, or the fact that we are logged in on multiple devices at once?  I'm wondering if it's ok to use multiple computers as long as I make sure to log out of HabitRPG before I decide to use another device.  Has anyone tried this or can confirm this?

**Comment by AndreCaseyScott** [comment] 2013-08-03 00:01
It's worth a try. I haven't tried this myself. I simply try and wait until
I get back to my laptop to report, since I've had problems with my custom
day start time and the mobile app currently available. The web interface is
just not worth it to me to bother with on mobile anymore.

**Comment by Senth** [comment] 2013-08-07 19:19
Today I noticed that my phone didn't reset the dailies, as soon as I logged in via the web the dailies were reset. It seems to me that the webpage has the code for clearing the dailies.

A solution (if you have implemented like I mentioned) could be to instead store a datetime when the daily was last completed. Then both devices will know if the daily is completed or not (just check if it's another date, with regard to when the day begins). Thus no device has to "uncheck" the device as it simply checks the datetime.

**Comment by SecretCheri** [comment] 2013-08-31 16:30
Yeah, it's been happening to me the last couple days. Every time I go up a level the dailies don't reset and are still grey so I can't even use them again. Very frustrating.

**Comment by lefnire** [comment] 2013-09-01 04:47
I'm pretty sure this is fixed in the rewrite API. The current site could is
pretty incompatible with the rewrite, so I'm just gonna wait till we launch
rewrite and we'll check in on this issue again. Don't quote me on it, but
I'm really hoping eta of tomorrow, or at least this week

**Comment by wc8** [comment] 2013-09-07 13:43
Report in Tavern Chat of Dailies not reset.

**Comment by lefnire** [comment] 2013-09-07 14:36
Yeah. I just don't know what to do about this one. It's obviously an extremely critical bug, but I've sunk a solid >72h into it, and it's passing all the tests. It's only an issue for some people, I dare say I'm gonna have to punt to another dev to tackling this one or I'm going to have to revisit in the future. It makes me feel really gross making that decision, but I gotta move on to other things

**Comment by devarops** [comment] 2013-09-07 22:02
I'm experiencing the same problem. Dailies for today are grayed out (not "active").

**Comment by lefnire** [comment] 2013-09-07 22:27
dupe of #1057, follow up there

**Closed as completed by lefnire** 2013-09-07 22:27 UTC

**Comment by sixgunglory** [comment] 2015-01-13 07:44
I've started having the same problem over the last 2 days. Dailies not reseting and it's doubled some tasks that I entered once. I don't use multiple devices, it synched up fine last night and I don't have a custom roll over time.

**Comment by Alys** [comment] 2015-01-13 11:30
@sixgunglory This is a closed issue, so we'll follow up on your problem in another one, but first I need more details so I can work out which issue is best.

When your Dailies do not reset, is it ALL of the ones you have ticked that do not become unticked, or do only SOME of them stay ticked?

Are you in a quest at the moment? If so, does your party chat contain messages about your quest progress from the past two days? Please click "fetch recent messages" in your party chat before you look for quest progress messages.

**Comment by sixgunglory** [comment] 2015-01-13 16:13
Some of them stay ticked, some become unticked. 

I'm not on a quest, though there is the world one at the moment.

I don't run multiple devices - run it on chrome and windows 8.1

**Comment by Alys** [comment] 2015-01-13 21:58
Thanks for the details @sixgunglory ! This is a known issue (https://github.com/HabitRPG/habitrpg/issues/4313) and we are trying to work out what's causing it. If you have any more problems with it, could you please report it there? I've mentioned your latest report there already.

**Comment by Aseelaldallal** [comment] 2015-05-07 17:26
Dailies, habits, not resetting. Not using Multiple devices either. How to fix?

**Comment by Alys** [comment] 2015-05-08 08:56
@Aseelaldallal Are you [Resting in the Inn](http://habitrpg.wikia.com/wiki/Rest_in_the_Inn)? If so, check out of the inn and your Dailies will reset tomorrow. We can't give you any more targeted advice than that without your User ID. I you aren't Resting, go to Help -> Report a Bug and see the instructions in step 6 for how to find your User ID.
