### ISSUE TITLE
Damage from "grey" dailies, dailies aren't reloading for following day, and MP amount loaded incorrectly

### ISSUE THREAD

**Issue by inetjunker** [HabitRPG/habitica#6465] opened 2016-01-05 18:24 UTC
Hello,

My User ID is "abe55da1-22e1-4885-bef3-624e2cd77cbe". (The number "1"s may be letter "l"s. It is hard to say. Please see point 4 below). I have found the issues when using both Chrome and Firefox browsers. I am using Windows 8.1 OS. 

I wanted to report a bug regarding 4 incidents that happened today. To my knowledge this is the first time they have happened. 

1) I am receiving damage from grey/completed dailies. I believe this is compounded by a boss our team is fighting. I had a perfect day yesterday so I should not have received damage. 

2) My dailies for today did not reset. There are some of my dailies shown as "completed", but I did not click them today. 

3) My MP amount loaded incorrectly. Currently my MP amount is full (blue bar is complete) at a value of "0/". See attached image as follows. 

![2016_01_05_habitica issue](https://cloud.githubusercontent.com/assets/16563173/12123213/9681ee4c-b3ad-11e5-9b44-ae64a258e42e.png)

4) API page flashes up quickly (no more than 1 sec) and goes away. It made it difficult to pull my User ID, but I was able to get it via Print Screen. 

I greatly appreciate your help and look forward to hearing from you soon. 

Best Regards,
inetjunker

**Comment by inetjunker** [comment] 2016-01-05 18:30
There is one other issue that I just noticed. Several of the task that I added to my list yesterday are now missing.

**Comment by inetjunker** [comment] 2016-01-05 18:34
Again, I apologize for adding more issues to the list. I am merely reporting them as I find them. I am also not able to remove or change any of my equipment, change my mounts, add any new task, or rest in the tavern. I can, however, still "complete" dailies that were still incomplete on my list.

**Comment by Alys** [comment] 2016-01-05 22:34
I'm sorry about this! You've experienced the bug reported here: https://github.com/HabitRPG/habitrpg/issues/4313

Please see the "Advice" section near the top about how to recover from unfair damage and how to untick your completed Dailies.

This bug is caused by a local storage problem in your browser, and it's probably also causing the issue with not being able to change your avatar or add new tasks. Please go to https://habitica.com/static/clear-browser-data and click the button there (read the text above it first).

Tell us if you still have problems after that.

**Comment by Alys** [comment] 2016-01-06 09:53
I'm closing this, but you're welcome to keep commenting here if you have questions or further problems.

**Closed as completed by Alys** 2016-01-06 09:53 UTC
