### ISSUE TITLE
[API  v3] Blessing costs no mana

### ISSUE THREAD

**Issue by taldin** [HabitRPG/habitica#7223] opened 2016-05-14 05:50 UTC
Casting Blessing deducts 25 mana, but then gives you 25 right back.

**Comment by paglias** [comment] 2016-05-14 18:38
@taldin is blessing applied at all?

**Comment by taldin** [comment] 2016-05-15 00:57
It's being applied, yes, but you wind up getting the 25 mana back (-25, +HP, +25 MP)

**Comment by paglias** [comment] 2016-05-15 19:28
This should be fixed with https://github.com/HabitRPG/habitrpg/commit/52bedc3563f90b089ce5fdb9aad0fe1bb89daf08 that has just been deployed. Reopen if the error persists after reloading the site.

**Comment by ghost** [comment] 2016-05-15 19:55
@paglias. The same issue for the revived Valorous Presence and the Gaze. It seems they give mana back

**Comment by paglias** [comment] 2016-05-15 19:57
@GitHubSphinx if you reload the page the problem persists? it should be fixed now

**Comment by ghost** [comment] 2016-05-15 20:10
I've reloaded the page, cleared browser data from static/clear-browser-data, ctrl+f5'ed, opened in Opera for Android.

Valorous Presence and Intimidating Gaze still return mana for me.

**Comment by paglias** [comment] 2016-05-15 20:23
Confirmed on v3.habitica but can't reproduce locally :(

**Comment by ghost** [comment] 2016-05-15 20:53
It's gone. No more mana refunds for me.

But it's gone alongside with debug menu. And I started to get 502 reds when trying to cast Brutal Smash (

**Comment by paglias** [comment] 2016-05-15 20:54
@GitHubSphinx sorry the app went offline while updating, try reloading now.

**Closed as completed by paglias** 2016-05-15 20:54 UTC

**Comment by ghost** [comment] 2016-05-15 20:55
Great!

Oh @paglias and sorry for taking your time (

**Comment by GitHubSphinx** [comment] 2016-05-15 20:58
Oh @paglias and sorry for taking your time (

**Comment by paglias** [comment] 2016-05-15 20:59
Thank you for reporting bugs!
Il 15 mag 2016 10:58 PM, "Sphinx" notifications@github.com ha scritto:
