### ISSUE TITLE
Avatar missing in Android app

### ISSUE THREAD

**Issue by gileryn** [HabitRPG/habitica#5340] opened 2015-06-03 01:05 UTC
I cannot see my avatar when I view the panel on the left on the HabitRPG app for Android. When I go to "Profile" I can see it, as well as on the website. It is only missing on the left-hand panel in the app. Instead it is an empty, white space.

**Comment by gileryn** [comment] 2015-06-03 01:08
This began immediately after the most recent update.

**Comment by lemoness** [comment] 2015-06-03 21:38
pinging @negue!

**Comment by negue** [comment] 2015-06-04 00:10
Cannot reproduce this on my galaxy s4 :( @gileryn could you please try to un- and  reinstall the App and see if it solves the problem?

**Comment by gileryn** [comment] 2015-06-04 04:54
I un- and reinstalled the app and the problem persists =[

**Comment by hairlessbear** [comment] 2015-06-04 05:53
Have you tried clearing the app's data (settings -> application manager (or possibly "manage applications") -> HabitRPG -> clear data)?

**Comment by gileryn** [comment] 2015-06-04 22:59
Didn't work =[

**Comment by gileryn** [comment] 2015-06-12 23:10
D: still

**Comment by hairlessbear** [comment] 2015-06-13 04:51
@gileryn The app has been updated since you last posted; have you updated to the new version?

**Comment by gileryn** [comment] 2015-06-15 00:28
Yes I have x_x

**Comment by hairlessbear** [comment] 2015-06-15 00:46
@gileryn Have you considered that you may be cursed? Did you anger a witch recently?

Seriously though, sorry this is still causing you grief; I imagine it's really obnoxious! Another idea: I want you to try the following in the exact order it's written. It's an attempt to _completely_ remove the app before reinstalling it. I have no idea if it'll work, but hey, you never know.

1) Go to your application manager
2) Click "Force Stop"
3) Click "Clear Data"
4) Uninstall the app
5) Reinstall the app

**Comment by gileryn** [comment] 2015-06-15 12:03
I followed your instructions, in order
aaannd

No good =[

Yes, it isn't too farfetched of an idea to think I might be cursed... Hahahaha x_x

**Comment by Alys** [comment] 2015-06-15 12:14
Or... it's a new Invisible Man costume and you're our first lucky recipient. :)

But seriously, I'm sorry this is such a persistent bug for you! 

Please tell us what version of Android your phone is running.

Are you using any software that modifies the OS in significant ways (e.g., cyanogenmod)?

Do you have any adblockers or privacy blockers or download limiters or firewall software?

Do you have any software that could be considered not just an ordinary app - anything that might modify the behaviour of other software? I'm sorry, I know this is a rather vague question.

**Comment by gileryn** [comment] 2015-06-15 12:41
Android version 4.4.4
Model number DROID MAXX
Build number SU6-7.2

I don't know if those other two things are important or not...I'm out of my league here, but I'm trying to help you help me! They looked important, anyway.

I don't have any of those types of software/apps you mentioned or anything. The only thing I can think of is Spotify, maybe? I don't think so, though... I can't imagine how.

**Comment by Alys** [comment] 2015-07-26 11:36
@gileryn We were never able to find a cause for this, and it doesn't seem to be reproducible for other accounts, which makes it hard to track down. :(  However we're working on a new, native Android app for HabitRPG which will have better performance and more features. It's not finished yet but it is close. I would expect that this bug will not occur on it. So, I'm closing this issue. I'm very sorry that we weren't able to resolve it for you.

**Closed as completed by Alys** 2015-07-26 11:36 UTC
