### ISSUE TITLE
Quest data carries over

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#9137] opened 2017-10-03 05:15 UTC
A user has reported that when they attempted to invite their party to a quest which was correctly denied due to a level requirement, and they then opened up a new quest to invite their party (the Basi-list), the quest invite button incorrectly remained locked until they refreshed the page.

**Comment by probaton** [comment] 2018-07-10 11:22
This seems like a duplicate of #9701. Or vice versa, I suppose, but the other issue has a more generic description that also covers this use case.

**Closed as completed** 2018-07-21 12:36 UTC
Labels: priority: medium, section: Quest Shop
