### ISSUE TITLE
Unable to accept quest posted by other party member.

### ISSUE THREAD

**Issue by jronath** [HabitRPG/habitica#5533] opened 2015-07-01 06:05 UTC
Pretty much the subject line. I'm reborn and attempting to regain equipment, first quest was no problem, but second one no one accepted after 18 hours.

Not getting the pop up "New Quest" and I don't see the button on the Party page. My party member pulled the quest and tried to repost it and I still couldn't join it. We then tried with a different quest same issue. I'm in the process of confirming that the other party members are having this issue too, but one of them had been on 30 minutes before I realized so they would have accepted if the pop up had appeared.

Tested in:
Chrome OS 43 (Acer c720)
Firefox 38 (Firefox for Ubuntu 1.0) (Crouton - Trusty 14.04)

Only JS error from the Firefox Console is
`<source> element has no "src" attribute. Media resource load failed. habitrpg.com`

`All candidate resources failed to load. Media load paused.`
Chrome OS doesn't even give me that.

User ID: 50739826-fb21-4d73-ba4b-23a52802afaa

Group ID: d40f49bb-4462-4c9a-b12f-63181399da7e

**Comment by Alys** [comment] 2015-07-01 06:44
The quest in that party has already been started by the quest owner. The owner should abort the quest (there's a button at the bottom of the quest box). The scroll will reappear in their inventory (they should reload if they don't see it). They should then click on the scroll to issue the invitation and then should NOT click "begin" in the quest box on the party page.

If they follow this process and you still don't receive an invitation, comment here again and we'll keep helping you. Please also comment if it does work so that we can close the issue.

**Comment by jronath** [comment] 2015-07-01 07:02
Yeah, sorry. The owner got pissed off and activated the quest.  they completed it on their own at midnight.

**Comment by Alys** [comment] 2015-07-01 07:04
Thanks for letting us know!

Comment here again if any future quests have the same problem.

**Comment by jronath** [comment] 2015-07-01 07:05
I am having the same problem. Sorry I didn't mention that in my previous comment.

**Comment by Alys** [comment] 2015-07-01 07:09
Can you please reload the party page and tell me if you see an invitation and/or see accept/reject button on the quest box (they might be at the bottom of one of the two box tabs - please check both tabs and scroll down to the bottom of each).

**Comment by Alys** [comment] 2015-07-01 07:15
Are you or any of your party mates using the "beta" HabitRPG site? If you're not sure what that means, please get each of your party members - especially the person who started the most recent quest (the quest that is still pending) - to check the URL of the website. Please tell me if starts with anything EXCEPT exactly this: **https://habitrpg.com/**

**Comment by jronath** [comment] 2015-07-01 07:20
I do not see the accept/rejection buttons or receiving the Quest pop up.

But that second comment might explain it. I received the email about the Quest. Clicking the link in the email sends me to the beta site which is doesn't have the button on the party page still, but does give me the pop up  (I thought I checked beta yesterday and it didn't work).

The quest owner has been using beta because it was loading better for them.

**Comment by Alys** [comment] 2015-07-01 07:24
That's the cause of the problem. Beta does not have the latest code for quests. Please tell the quest leader to cancel the quest and then move to the normal HabitRPG site at https://habitrpg.com/

The beta site is used by admins for testing new features, often features that have not yet been completed and that contain significant bugs or very different behaviour than you would see on the normal site. It also very often does not contain the newest features that have been released on the normal site and therefore cannot be guaranteed to work correctly. It is strongly recommended that no one uses the beta site unless staff or moderators suggest that they can to assist with testing.

You're welcome to ask more questions about this here and I'll keep replying, but I'm closing this issue now. Because beta is used for testing specific new features, we don't do bug fixes on it for features that are unrelated to our tests.

**Closed as completed by Alys** 2015-07-01 07:24 UTC

**Comment by jronath** [comment] 2015-07-01 07:32
Yup, that worked. Thanks for the assistance. My friend's been using Beta on an Admin's suggestion because they had issues getting the regular site to open with their unusually large number of dailies. They hadn't had any significant problems until now.

**Comment by Alys** [comment] 2015-07-01 07:35
Thanks for telling me. Please let them know that the admin probably meant that advice as a very temporary measure and it's best to not use beta now.

By the way, we recently made a change to the normal site which we think has resolved the server errors that many players were seeing frequently. If your friend had bad performance in the past on the normal site, they might find that it is better now.
