### ISSUE TITLE
Unable to delete completed quest (Basi-List)

### ISSUE THREAD

**Issue by camachoborracho** [HabitRPG/habitica#6339] opened 2015-12-05 21:16 UTC
User ID: 4d6a708d-3434-468d-bfaf-573dd1b04f7b

So I had invited 2 people to join me on a quest (Basi-List) but they never joined, so I began the quest of the Basi-List & completed without them. However, when I look at INVENTORY > QUESTS under YOUR QUESTS: Unlockable Quests (left side) it states Basi-List 3 - which I am told means I have three copies of this quest in my inventory, possibly because I clicked on it 4 times (and did 1) or the inviting 2 others to make a group of 3.

In any case, I can't even repeat the quest to remove it or do the other 3 if it's open, in fact it says "Group not found or you don't have access"

I'm only seeing it as done x1 under USER > STATS but I know we can do it more than once.

Can it either be removed from my inventory as not done, or can the block be cleared? Thank you!
![screen shot 2015-12-05 at 1 13 48 pm](https://cloud.githubusercontent.com/assets/15842968/11610274/577bbcdc-9b52-11e5-9a48-cead292d025d.png)
![screen shot 2015-12-05 at 1 13 55 pm](https://cloud.githubusercontent.com/assets/15842968/11610273/577b2196-9b52-11e5-9c0d-8c1d8797e450.png)

**Comment by Alys** [comment] 2015-12-06 01:20
Every time someone accepts a party invitation from you, you are given a new
copy of  the Basi-List quest scroll. You can use them all to do the quest
multiple times (one time per scroll). A quest scroll is removed from your
inventory only when you've used it.

When you try to start any quest and you see the message, "Group not found
or you don't have access", it means that either you are not in a party, or
the website hasn't loaded properly and it thinks incorrectly that you
aren't in a party. In the latter case, reload the site. In the former case,
join someone else's party or click the blue "Battle Monsters With Friends"
button in the header to start your own party.

**Comment by Alys** [comment] 2015-12-06 09:12
@camachoborracho I'm back at my computer now and I've checked your account. You are not in a party. That's why you're seeing "Group not found or you don't have access" - the group it's referring to is the party. I don't think there's any bugs in what you've described, so I'm closing this now, however if you need more help, comment here and we'll still see it. If you'd like advice about how to create a party, the wiki's party page (http://habitica.wikia.com/wiki/Party ) might help, or you can go to Help -> Ask a Question on the Habitica website. If you're looking for party members or a party to join, go to the Party Wanted guild at https://habitica.com/#/options/groups/guilds/f2db2a7f-13c5-454d-b3ee-ea1f5089e601

**Closed as completed by Alys** 2015-12-06 09:12 UTC

**Comment by camachoborracho** [comment] 2015-12-07 19:59
Well, I reset my browser and deleted history, etc. nothing changed.

I posted on boards saying I was looking for people to join my party, 2 people replied and so I invited 2 people asking to join my party (not me to join theirs) and it said they were in a party already - so I suspect a bug now somewhere.

And now I went to party, saw no one else, then was able to start a quest. I was able to start the Basi-List again, but the 3 beside it has not disappeared (Maybe it will after I defeat it again this time?)

![screen shot 2015-12-07 at 11 55 17 am](https://cloud.githubusercontent.com/assets/15842968/11638047/9bfe775e-9cd9-11e5-94d7-19f7be1bc10c.png)
![screen shot 2015-12-07 at 11 55 24 am](https://cloud.githubusercontent.com/assets/15842968/11638053/a208a804-9cd9-11e5-9866-74145a905d2b.png)
![screen shot 2015-12-07 at 11 55 28 am](https://cloud.githubusercontent.com/assets/15842968/11638067/b2cce2ae-9cd9-11e5-8e5a-7ed7f3320289.png)
![screen shot 2015-12-07 at 11 56 25 am](https://cloud.githubusercontent.com/assets/15842968/11638107/e06e2f7e-9cd9-11e5-82a7-b685a6ae26db.png)
![screen shot 2015-12-07 at 11 56 08 am](https://cloud.githubusercontent.com/assets/15842968/11638108/e08922ca-9cd9-11e5-9a96-520470357736.png)

This is definitely a bug relating to inviting people who don't accept/reply, then canceling, then doing the quest without them. Appears to leave the number of invites/quests in your inventory unchanged.

**Comment by Alys** [comment] 2015-12-07 22:28
_"Well, I reset my browser and deleted history, etc. nothing changed."_

Yes, none of that would have helped. The thing you needed to do was create a party, and I see from your account that you've done that now. That's why you're able to start quests now.

_" posted on boards saying I was looking for people to join my party, 2 people replied and so I invited 2 people asking to join my party (not me to join theirs) and it said they were in a party already - so I suspect a bug now somewhere."_

No, that's not a bug. It just means that before you invited them, someone else already had and the players had accepted that invitation. A player can be in only one party at a time, so if you try to invite someone who is already in a party, you'll get the message telling you that they are in a party.

_"I was able to start the Basi-List again, but the 3 beside it has not disappeared"_

When you first use a quest scroll to start a quest, the number of scrolls owned does not decrease immediately. This is because clicking on a quest scroll doesn't actually start the quest, it just sends quest invitations to the current party members. At that stage, you still own the scroll because the quest has not started. When the quest does start, the scroll is removed. In a one-person party like yours, the invitation phase actually finishes immediately and the quest starts automatically (because there are no other people in the party but you and so there are no invitations that need to be accepted), so if you'd reloaded the quest page as soon as you'd clicked on the scroll, you would have seen the number decrease to 2. If you look now, it will say 2. I've checked your account and you have only two of those scrolls.

**Comment by camachoborracho** [comment] 2015-12-08 00:09
Thank you for clarifying. Odd, when I switch computers it's changed but
perhaps need to reloaded.

Glad it's resolved. Will just burn through these ones and move forward
then, thanks!

Ian Camacho
310 775 3540
http://www.imdb.com/name/nm1907117/
cafepress.com/revengetables
