### ISSUE TITLE
[API v3] Open new tasks in edit mode remain in edit mode after refresh

### ISSUE THREAD

**Issue by Kryzowsky** [HabitRPG/habitica#7237] opened 2016-05-14 11:42 UTC
General Info
- UUID: 432192fb-66ed-413c-88f6-b1ece628d943
- Browser: Google Chrome 50.0.2661.102 m
- OS: Windows 7
### Description

When the "Open new tasks in edit mode" function is checked, tasks remain in edit mode, even after refreshing the page. However, if you cancel/tick the saves, they collapse as normal.

**Comment by paglias** [comment] 2016-05-14 18:34
This is probably due to the task._editing state being saved to localStorage. 

I'm not sure if we should fix it or now @Alys @crookedneighbor

**Comment by keysmashes** [comment] 2016-05-14 20:20
Can't reproduce – after a refresh, tasks left in edit mode appear like that for a second, but then collapse again. Honestly, I think this behaviour (of previously-open tasks staying open after refresh) might be better, or at least no worse.

#2965 may be relevant?

**Comment by Alys** [comment] 2016-05-14 22:11
I don't think we should fix this. If you've chosen to leave a task open, then you'd want it to remain open, especially if the refresh happened because of Habitica's automatic six-hour reload (even if you lost your edits, you'd at least be able to easily find the task you were editing).

**Comment by paglias** [comment] 2016-05-15 09:14
Closing this, we'll probably fix #2965 sometime in future

**Closed as completed by paglias** 2016-05-15 09:14 UTC
