### ISSUE TITLE
"Advanced settings" setting has no apparent effect

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica#10556] opened 2018-07-26 19:50 UTC
From the Bug Guild:

>gust (673c677c-7391-4706-820c-d49f52924624) 
>i just noticed the setting"Advanced Settings in tasks start collapsed", doesnt work. My advanced settings are always collapsed either way the option is checked.

Confirmed by me (Chrome).

**Comment by TheHollidayInn** [comment] 2018-07-27 04:12
Is this a duplicate of: https://github.com/HabitRPG/habitica/issues/9876?

**Comment by Alys** [comment] 2018-07-27 04:36
No, that other issue is for not showing the "Advanced Settings" section in task types where there are no such settings (e.g., To-Dos and Habits have no advanced settings, although personally I'd still like to see https://github.com/HabitRPG/habitica/issues/9902 done, which would add an advanced setting for all task types). 

This new issue is about the User Icon > Settings > "Advanced Settings in tasks start collapsed" preference setting. When that checkbox is not ticked, every time you edit a task, the Advanced Settings section should be open by default.

**Comment by TheHollidayInn** [comment] 2018-07-27 04:49
Ah perfect, thanks.

**Comment by alexfig** [comment] 2018-07-27 23:49
Hi, I'd like to work on this

**Comment by Alys** [comment] 2018-07-28 00:13
@alexfig Great, thank you! Comment here if you have questions!

**Closed as completed** 2018-07-30 13:58 UTC
Labels: priority: medium, status: issue: in progress, type: medium level coding, section: Task Page, section: Equipment
