### ISSUE TITLE
Starting Habit script not responding.

### ISSUE THREAD

**Issue by nikrage** [HabitRPG/habitica#1166] opened 2013-06-12 09:04 UTC
Habit has been very "heavy" since a couple of days. Now Mozilla stops working when I open it and then says script not responding do you wish to let it finish or stop the script, something like that: https://beta.habitrpg.com/gen/0rKymaEwdfx_ZAi5m3xhrw.js:8. This is the scrip. I have a powerful computer but the site acts weird on startup

**Comment by lefnire** [comment] 2013-06-12 19:04
dupe of #745, let's follow up there

**Closed as completed by lefnire** 2013-06-12 19:04 UTC
