### ISSUE TITLE
Cannot remove Challenge tasks from personal task list after leaving Challenge

### ISSUE THREAD

**Issue by kamni** [HabitRPG/habitica#5613] opened 2015-07-14 16:27 UTC
How to reproduce:

1) Join a challenge. Note that there are new challenge tasks in your habits/dailies/todos.
2) Leave the challenge. Opt not to delete the tasks (because you want to use some of them for a little while longer)

There is no direct way to remove the challenge's tasks now that you have opted not to delete the tasks.

One workaround is to re-join the challenge, then leave and opt to delete the tasks; however, this isn't necessarily an obvious workaround, and if you wanted to keep some of the tasks from the challenge, you're out of luck.

**Comment by GitHubSphinx** [comment] 2015-07-14 20:36
@kamni I believe it's documented on the wiki: http://habitrpg.wikia.com/wiki/Challenge#Challenge_Tags_Remaining_after_Leaving_a_Challenge

**Comment by GitHubSphinx** [comment] 2015-07-14 20:39
@kamni I believe it's documented on the wiki
- http://habitrpg.wikia.com/wiki/Challenge#Deleting_a_Challenge_Task
- http://habitrpg.wikia.com/wiki/Challenge#Tasks_Created_by_a_Challenge_Can.27t_Be_Removed_after_It.27s_Been_Closed

*This post is an edit because the first one had the wrong link.*

**Comment by ghost** [comment] 2015-07-14 20:44
@kamni I believe it's documented on the wiki
- http://habitrpg.wikia.com/wiki/Challenge#Deleting_a_Challenge_Task
- http://habitrpg.wikia.com/wiki/Challenge#Tasks_Created_by_a_Challenge_Can.27t_Be_Removed_after_It.27s_Been_Closed

> If the challenge appears to no longer exist but you don't have a broken megaphone yet, try checking off any Habit, Daily, or To-Do that belongs to the challenge, then reload HabitRPG. That should sync your task list with the server and turn the megaphone into the broken megaphone icon.
> 
> In some cases, you might need to repeat those actions a few times, possibly over several hours, before the broken megaphone icon appears (e.g., if your first attempt doesn't work, wait a few hours and try again, then if necessary, try again the next morning, and then a few hours after that).
> 
> You might find that you can delete challenge tasks using the Mobile app even if you can't delete them on the website.
> 
> If the broken megaphone icon has still not appeared after trying these suggestions for two days, report the problem. 

_This post is a third edit because the first two ones got somehow messy_ =(

duplicating #2877 ?

**Comment by Alys** [comment] 2015-07-14 21:37
@kamni We do often have reports of challenge tasks being undeletable when a challenge has ended, but it's rare to see it when a challenge has been left. If the workaround posted by @GitHubSphinx doesn't work, we'd really like more information from you so we can work out what's happening.

Firstly, when you leave the challenge and opt to keep the tasks, the challenge icon (the megaphone) on each task should be removed and replaced by a rubbish bin. Obviously the rubbish bin isn't appearing for you, but is the megaphone being removed? Can you please show us a screenshot of the tasks from a challenge you've left?

When you've left a challenge and chosen to keep the tasks, does the challenge still appear in the list of challenges you are participating in? You can use the controls on the left-hand side of the challenge page to filter challenges. Does the challenge have a leave or join button?

Is this reproducible for every challenge you join then leave?

Which browser or app are you using to leave the challenge, and which OS or mobile device type? 
Which browser or app are you using when you don't see the rubbish bin on the ex-challenge tasks, and which OS or mobile device type?

If you're using Chrome or Firefox (or any other browser that has a javascript console), do any messages appear in the console when you leave a challenge? We can tell you how to find the console if you're not sure.

**Comment by Alys** [comment] 2015-07-17 09:59
@kamni I'm closing this because I'm afraid we can't investigate without further information, but if you still need help with removing challenge tasks, please reply and we'll reopen it.

**Closed as completed by Alys** 2015-07-17 09:59 UTC

**Comment by kamni** [comment] 2015-08-07 12:55
@Alys 

So the workaround posted by @GitHubSphinx did not help. The issue was that when I left the challenge and opted to keep the tasks, the microphone was not changed into a rubbish bin, so I couldn't delete it. I kept the task for several weeks before I got frustrated enough to report it, so it wasn't a refresh or waiting issue. The challenge was not listed as one I was still participating. 

The workaround was to re-join the challenge, then opt to keep none of the tasks (which was a shame, because I wanted to keep some of them, along with the histories), and then manually create the tasks that I wanted to keep

**Comment by crookedneighbor** [comment] 2015-08-07 14:05
@kamni In the future, if you have a problem like this, you can always ask us for help. The more information we have, the easier (and faster) it'll be to track down the bug to resolve it. In the mean time, we can do a manual database edit to remove the task(s) you don't want.
