### ISSUE TITLE
Clear Completed should archive, not delete

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#3062] opened 2014-03-13 01:47 UTC
By the look of things, when I click Clear Completed on my To-Dos, all of my completed To-Dos are deleted entirely from my account. For example, if I later go to Export User Data, none of the completed To-Dos show up in the exported JSON.

This is a bit alarming, especially since the archival of To-Dos that happens automatically after 3 days is supposed to be exportable. Clicking "Clear Completed" once, ever, wiping all that out is rather drastic, and not expected from the end-user side. Double pain: clicking that button is one of the main workarounds for To-Do sorting going wonky...

Since we have the archival feature now, shouldn't Clear Completed archive all completed To-Dos, not erase them?
##

**Comment by jbutz** [comment] 2014-03-27 16:15
It looks like the archive feature is currently being accomplished by filtering out ToDos that were completed 3 or more days ago.

The way I see it there are three ways to do this.
1. Remove the Clear Completed button, so the archive is preserved
2. Warn people that using the button deletes old Todos and doesn't archive them
3. Add a flag to the todos to denote them as archived and adjust everything to go off that

Thoughts from everyone?

**Comment by SabreCat** [comment] 2014-03-27 23:46
My vote's for _3_, but an "are you sure" warning ala _2_ would be a suitable stopgap.

**Comment by deilann** [comment] 2014-03-27 23:51
The problem with 2 is that sometimes you need to press clear completed to
fix the to-do sorting problem...

**Comment by SabreCat** [comment] 2014-03-28 01:52
A-yup. That's what spurred me to write up this ticket in the first place >.<

**Comment by jbutz** [comment] 2014-03-28 13:15
I'm willing to go after number 3 if no one has objections. I've looking into it a bit and this seems to be everything that would need doing more or less in this order.
1. Add flag to todo schema
2. Update cron to flip the flag on completed todos older than 3 days
3. Update the `user.batchUpdate` to filter on the flag and not the completed date
4. Update the button

This could be completed in 3 pull requests that would have to be done sequentially but they wouldn't have to occur at the same time, there could be time between them.

The first pull request would have Item 1 and that would be on the habitrpg repo. The second pull request would have Item 2 and be on habitrpg-shared. The third pull request would have the remaining items on the habitrpg repo.

So, what say you all? My one big question is, what is the issue that necessitates the Clear Completed button as a fix? Because there is a chance this might not continue to work as a fix afterwards depending upon what the problem is.

**Comment by SabreCat** [comment] 2014-03-30 11:49
Yay @jbutz! Go for it!

#2606 is the one. But I haven't had any problem with it messing up on archived To-Dos, so maybe this will still help.

**Comment by jbutz** [comment] 2014-04-18 16:40
I got the repo for number 4 wrong, but I threw that in with number 2. All the pull requests are in.

**Comment by Alys** [comment] 2014-08-10 19:58
@iiku : What language does HabitRPG use for you? I think the translations for that button might be wrong for you. When you put your mouse over the "Delete Completed" button, the pop-up should explain that all completed and archived to-dos will be permanently deleted.

**Comment by Alys** [comment] 2016-04-02 21:40
I'm closing this because we renamed the button to be "delete completed". I believe it always was meant to be a delete button but was just misnamed.

If we decide that we need a button to "archive" To-Dos faster than they normally are, we could open a new issue to avoid confusion from this old one.

The sorting bug mentioned above was fixed too.

**Closed as completed by Alys** 2016-04-02 21:40 UTC
Labels: priority: medium
