### ISSUE TITLE
Invalid Log In/My account is gone

### ISSUE THREAD

**Issue by AnonyMoses** [HabitRPG/habitica#268] opened 2013-01-31 02:42 UTC
So today while using Habit RPG, it went offline for a little bit. After it came back online, all my items added to my account were gone. My to-dos, habits, dailies were all gone. I managed to copy the 3rd party code information if that will help but I would really hate to see that all my info is gone as well. I was well on my way of leveling up and had a huge list of to-to. 

I am using Google Chrome on Windows 7. I tried logging in using Chrome, Chrome's incognito, as well as Firefox.

**Comment by wc8** [comment] 2013-01-31 02:43
Sorry about your trouble. This just happened to me, too, so I really sympathize. Try emailing your user ID to @lefnire

**Comment by wc8** [comment] 2013-01-31 02:45
Is your username showing up when you go to the site?

**Comment by lefnire** [comment] 2013-01-31 02:46
shoot - i'm going to restore to a recent backup, let's try that

**Comment by ghost** [comment] 2013-01-31 02:46
Same here guys

**Comment by AnonyMoses** [comment] 2013-01-31 02:47
It is not. I used LastPass to save my username and password, and that is
showing up as the account never existing when I use my login info.

**Comment by Valence87** [comment] 2013-01-31 03:01
Mine's gone, too. Getting the "Invalid Login" error

**Comment by lefnire** [comment] 2013-01-31 03:05
i'm talking with my sysadmin - i can't get the website to connect, mongo's got thousands requests/second - working on it

**Comment by lefnire** [comment] 2013-01-31 03:17
check

**Comment by ghost** [comment] 2013-01-31 03:17
Everything is gone

**Comment by lefnire** [comment] 2013-01-31 03:21
weird, i haven't deployed anything since female avatars earlier today. the database size shows the same. how's it looking for anyone else now?

**Comment by wc8** [comment] 2013-01-31 03:22
no change

**Comment by lefnire** [comment] 2013-01-31 03:22
wes, try log-in-out?

**Comment by ghost** [comment] 2013-01-31 03:24
Fixed it thanks Tyler

**Comment by lefnire** [comment] 2013-01-31 03:24
shit, i have to step away for a bit. any coders, take a peak at recent master commits that might be shady - i'll be back soon as i can

**Comment by AnonyMoses** [comment] 2013-01-31 03:27
Thanks for the work. I s got nothing on my end of it.

**Comment by FunnySunshine** [comment] 2013-01-31 03:29
I have the same problem too. I reloaded the page since it was once again marked "Offline", but when it refreshed, I couldn't see my avatar nor any dailys, habits, rewards or to-dos. I then decided to log-out, but I couldn't log in afterwards, it said that my account didn't exist.

**Comment by wc8** [comment] 2013-01-31 03:32
That'll teach me to say its getting too easy ;-)
No improvement, but I can wait. I think I had plenty of HP for the night, if need be.

**Comment by lefnire** [comment] 2013-01-31 03:32
well, we have two backups from morning and eventing - i'll figure this out

**Comment by theogeer** [comment] 2013-01-31 04:07
I'm messed up too. Looks like I got reset. I login through facebook. theogeer

**Comment by ianthetechie** [comment] 2013-01-31 04:47
Thanks for looking into this. Same thing happened to me as well :/ my account appears to be no more (and consequently the ads are back).

**Comment by Pandoro** [comment] 2013-01-31 08:05
Could those of you, who had their account "removed" or reset maybe post their timezone? And also whether or not this occurred during the day, or after you tried to login the next morning? 

This might help potential developers to narrow the search for potential bugs. If it happened during the day, then probably it wasn't caused by some timed job, but if it happened after the date changed, maybe it is something caused by the cron job? 

I'm just bringing up some ideas here. I also looked at the last commits and I don't see anything major. Then again I'm not a web developer :( 

I hope this doesn't discourage all of you from playing once this is fixed! :)

**Comment by feliep** [comment] 2013-01-31 08:07
mine's gone too...

there was a box saying something like "cannot reconect" and I lost all my data, then I logged out and when I logged in again it says my login is invalid.

btw, this idea is incredible, keep it up please!

**Comment by AnonyMoses** [comment] 2013-01-31 08:21
I was playing during the daytime. I'm west coast time in USA.

**Comment by lefnire** [comment] 2013-01-31 09:06
tried another backup, check now

**Comment by horusofoz** [comment] 2013-01-31 09:30
Same thing was happening for me up to about 20 mins ago. ACST. (10:30+)

**Comment by StanLindsey** [comment] 2013-01-31 10:35
I'm fine, but then I've been asleep and only woke up a couple hours ago. I've only just checked HabitRPG and it may of been fixed by now.

**Comment by theogeer** [comment] 2013-01-31 12:49
Woke up this morning and everything is back. Looks like a restore of some earlier point in the day worked.

For the record I'm in CST (-600). I'm not certain what time the profile vanished. I'd say it's probably about 8PM. I remember because I had a lot of TODOs yesterday that I was working through. The site went down and gave me the whole "Try again, in the meantime go to kicksterter" page.

When it came back all the images were gone and it wasn't loading. After checking this thread a little later I tried logging out and then logging back in, and then it was working again, but my account had been reset.

**Comment by lefnire** [comment] 2013-01-31 12:49
Is anyone still effect since my last comment? I think I know where something went wrong, but I'm not sure why. Here were my steps yesterday:
1. Deployed female avatar (no data-destructive code here)
2. Started working on Parties on another branch
3. Testing locally, Parties requires `user.preferences.gender` and `user.preferences.armorSet` - so I created a migration to add that in where missing: [migration script](https://github.com/lefnire/habitrpg/blob/parties/migrations/20130129_add_missing_preferences.js). Ran migration locally, ran tests, check. 
4. Made backup of live site, ran migration live - error. Ran a simple `db.users.count()` - error. Ran database repair, all looked in order. Made a second backup. 

However, I think this is where things went wrong - because a few hours later people started reporting issues. I went to look at backups, the second backup (after the migration) was 75.2m (vs 90+m for the other backups) - [see screenshot](http://gyazo.com/34c519c2d7d651860e120806c3f4617a). Sorry this took so long to act on, it took me a bit to figure it out - had to find that strangely small database snapshot and retrace my steps. I restored to the snap before it as of my last comment, which means newcomers between 2013-01-30 23:47 UTC and restoration may have experienced data loss, but everyone else should be fine. 

Strange that migration went awry - I'm going to experiment later on a different db server or running mongod on Liquid Web. I apologize to everyone for this experience! I'll have to come up with some mongo sanity tests for pre/post migrations.

**Comment by Pandoro** [comment] 2013-01-31 12:55
You're the man for figuring this out @lefnire  :+1: I really hope this fixes it for everyone. Considering the kickstarter project, it is a rather critical time for habitrpg to break.

**Comment by Valence87** [comment] 2013-01-31 14:11
My character is back, but I took a big HP hit. I'm EST (-500). I had the same symptoms as funnysunshine:

"I have the same problem too. I reloaded the page since it was once again marked "Offline", but when it refreshed, I couldn't see my avatar nor any dailys, habits, rewards or to-dos. I then decided to log-out, but I couldn't log in afterwards, it said that my account didn't exist."

Everything is back today, though. Thanks!

**Comment by lefnire** [comment] 2013-01-31 14:14
ok phew

**Comment by ghost** [comment] 2013-01-31 16:43
Not sure if this is the same bug but every time I pull up habit in chrome on Android health is nan and all my stuff is gone but when I am on my laptop everything is fine

**Comment by horusofoz** [comment] 2013-02-05 12:37
@Neohuman Is your issue still occurring?

**Comment by ghost** [comment] 2013-02-05 12:41
No I just use Facebook to log in

**Closed as completed** 2013-02-05 12:46 UTC
