### ISSUE TITLE
"Error Cannot set property 'drop' of undefined"

### ISSUE THREAD

**Issue by Solas36** [HabitRPG/habitica#5108] opened 2015-04-30 12:31 UTC
Tried to cast "Burst of Flames" on one of my tasks, and it worked (and dropped a quest), but then I got this error message.  When I reloaded the page as indicated by the error, this action was totally undone.  I tried to reload and cast Burst of Flames again, but the exact same thing happened several times.

User ID: 8404874c-5f92-47ae-a54b-3c07dac203f6
Using Chrome version 41.0.2272.118 m

**Comment by crookedneighbor** [comment] 2015-04-30 12:35
Duplicate of #4986 You can track the progress of the issue by subscribing to that issue.

**Closed as completed by crookedneighbor** 2015-04-30 12:35 UTC
