### ISSUE TITLE
Cannot change password

### ISSUE THREAD

**Issue by HataKare** [HabitRPG/habitica#7465] opened 2016-05-24 02:30 UTC
General Info
- UUID: b8637b91-9d24-4a00-8054-24654a0eae7a
- Browser: Vivaldi and Chrome
- OS: Windows 10 Pro
### Description

When I try to change my password it shows the following message:
![habitica password glitch](https://cloud.githubusercontent.com/assets/2553443/15490319/e2acfdbc-2134-11e6-9a96-d441107cf852.PNG)
This happens in both Chrome and Vivaldi, and I tried different password lengths and character uses, to no avail.

**Comment by crookedneighbor** [comment] 2016-05-24 03:59
Duplicate of https://github.com/HabitRPG/habitrpg/issues/7423

Copying this text over to the other issue.

**Closed as completed by crookedneighbor** 2016-05-24 03:59 UTC
