### ISSUE TITLE
Gold disapeared

### ISSUE THREAD

**Issue by awkwardsoul** [HabitRPG/habitica#763] opened 2013-04-02 19:12 UTC
I had just added a new daily, labelled it not active for today (but accidentally checked it off), and then all my gold/silver vanished! I had about 45g in there.

I didn't spend it or anything. I had a screenshot of early yesterday http://wp.me/a2xq6p-bC

and after the glitch, http://wp.me/a2xq6p-bH (i tested a todo and I got 2 gold)
logging in and out didn't fix it, or refreshing.

**Comment by wc8** [comment] 2013-04-02 19:19
I couldn't replicate it (not saying it didn't happen, just I couldn't reproduce it). What browser are you using?
Meanwhile: Drop-down menu (arrow by your username) > Settings > Reset, correct the gold.

**Comment by awkwardsoul** [comment] 2013-04-02 19:20
Google Chrome Version 25.0.1364.172 m

Cool, I'll fix my gold - TY!

**Comment by robynthegeek** [comment] 2013-06-12 19:33
Reproduced in Chrome Version 27.0.1453.93
All gold disappeared and XP reset to 0
Damage to health was retained though!

**Comment by robynthegeek** [comment] 2013-06-13 00:52
Hmm, just kidding, I can't reproduce this myself so it may have been triggered by another action. 
Other possibilities were logging in from the android client and adding items there and having 2 windows open simultaneously, one in chrome and one in Safari.

**Comment by paglias** [comment] 2013-09-09 17:37
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!

**Closed as completed by paglias** 2013-09-09 17:37 UTC
