### ISSUE TITLE
[Feature? Bug?]

### ISSUE THREAD

**Issue by dbueller** [HabitRPG/habitica#283] opened 2013-02-01 13:14 UTC
I'm not sure if this was the intention or just a bug, but I find myself humming SNES RPG songs as I do my daily tasks.  Anyone experiencing similar issues?

**Comment by StanLindsey** [comment] 2013-02-01 13:15
Totally a feature =P

**Comment by lefnire** [comment] 2013-02-01 21:37
There have been reported Sega hummings , still diagnosing that bug

**Comment by Pandoro** [comment] 2013-02-03 01:02
I've been humming terranigma lately ;) But letś keep the board a little clean. I'll close this for now. If this occurs more often though, we'll call it a feature and not a bug :p

**Closed as completed by Pandoro** 2013-02-03 01:02 UTC
