### ISSUE TITLE
Can't edit "Ghost Ship" guild: permanent "Server currently unreachable" error

### ISSUE THREAD

**Issue by habitrpguser** [HabitRPG/habitica#7200] opened 2016-05-13 09:38 UTC
As guild leader of the "Ghost Ship" (Guild ID: 4b4c7c73-884d-42ea-b2f8-e6be35d28479), I (UUID 1aff9116-34b0-438c-9877-06038bdce161) am currently trying to edit the guild's speech bubble ("Message from group leader") and logo. I always get a "Server currently unreachable" error, and the change isn't saved. (Posting in the guild works fine though.)

I guess (but have no proof) that this is related to the guild's size and the "Entity" error I encountered previously when trying to edit the guild.

It is NOT related to:
- an extremely high server workload (rest of Habitica works fine, and I tried several times during the last 24 hours),
- the guild design (I tried the same text and even longer ones, and the same logo, in a private guild - no problem),
- my account (same reason),
- the browser (tried several, and even tried the Android app, but apparently you can't create or edit guilds with the app at all yet),
- the OS (tried Windows and Android),
- the internet connection or computer speed (everything else loads fast enough, and the Android device I used is a new and fast one).

When I encountered the old "Entitiy" bug last time I edited the guild, I waited a few days and tried again, and then a few more days, and tried again. After a while (and before the "Entity" got debugged), it worked. My guess is: Because the number of guild challenges varies, the size of the guild object varies, and at times when it's small enough, it lets me edit the guild.

I can't use the "wait a few days and try again" approach this time, though, because the changes I want to make are a bit urgent. (Details below.) I would appreciate it if a quick workaround can be found, i.e., if someone with database access can make the changes for me. After that, the actual debugging isn't that urgent anymore.

The changes I'd like to have made are:
- leave the guild description as it is
- remove the guild logo URL entirely
- change the "message from group leader" to:

"
- The guild has its own [wiki page](http://habitrpg.wikia.com/wiki/The_Keep:Ghost_Ship) (which, sadly, is still very much under construction, but already contains some helpful links).
- Big thanks to **@Cantras** who is now in charge of the organ donor challenges - it's a lot of work! Thanks also to **@Horacious Moreau** for coding the "organ donor counter" for the "♡ I am an organ donor! ♡" challenges!
- We are currently looking for a new logo (preferably a picture of a ghost ship). Suggestions (own art or pictures in the public domain or with a license that allows commercial use) are welcome! (The old logo from **Daniel Sinoca** can be admired at [DeviantArt](http://sinoca.deviantart.com/art/Ghost-Ship-182070306). We originally found it as a "free wallpaper" on a website that no longer exists, and thought it has no copyright, but it has.)

"

I'll repeat that in block code here so you have no trouble copying the format:

```
+ The guild has its own [wiki page](http://habitrpg.wikia.com/wiki/The_Keep:Ghost_Ship) (which, sadly, is still very much under construction, but already contains some helpful links).
+ Big thanks to **@Cantras** who is now in charge of the organ donor challenges - it's a lot of work! Thanks also to **@Horacious Moreau** for coding the "organ donor counter" for the "♡ I am an organ donor! ♡" challenges!
+ We are currently looking for a new logo (preferably a picture of a ghost ship). Suggestions (own art or pictures in the public domain or with a license that allows commercial use) are welcome! (The old logo from **Daniel Sinoca** can be admired at [DeviantArt](http://sinoca.deviantart.com/art/Ghost-Ship-182070306). We originally found it as a "free wallpaper" on a website that no longer exists, and thought it has no copyright, but it has.)
```

(In the speech bubble text, only the third list item is different from what it's now.)

As is apparent from the text, the guild will have to be edited again once we find a new guild logo, and then again once the Ghost Ship wiki page isn't "very much under construction" any longer - but that won't be as urgent.

**Why it's urgent:**
You can, at the moment, find a more detailed discussion in guild chat, but this is the summary:

It's not just because of the copyright violation. That's bad enough in itself. But the speech bubble now contains an URL (clickable in most browsers, apparently not in some others) of the old site where that picture was found. Originally it was a website with free wallpapers. Then it vanished and the domain was up for grabs (but looked otherwise harmless). Now the domain redirects to various very aggressive ads (different each time I reload), and some of them trigger my antivirus software, and try to make me click things that pretend to be Windows messages, and don't let me close the browser again without resorting to the task manager, etc., etc. In short, **virus danger**. So the blackdreamer-dot-com URL should vanish from the guild's speech bubble as soon as possible. (At the very least, it shouldn't be clickable.)

Oh, and, of course, the logo violates copyright, and should go, too. (I would like to have the DeviantArt link in the speech bubble for now, though, because that way, people trying to create or search for a new logo know what we're looking for, and can use it as inspiration.) What's more, the picture is now used as cover art of a [remastered heavy metal album](http://www.amazon.com/Kill-Devil-Hills-Killer-Khan/dp/B00X7LWTAI/ref=ntt_mus_ep_dpi_1) released June 2015. (I hope the band actually credited Daniel Sinoca and didn't make the same mistake I made.) So it's probably not a good idea to even think of asking the artist for permission to use the picture.

Meanwhile, I posted a warning about the link in guild chat. Please tell me if I should do anything else.

Would it be ok if I comment on the DeviantArt page and apologize for having used the picture without knowing about the copyright, and thank the artist for having made it and having helped to inspire people to become organ donors? (If your answer is too irrelevant for debugging to go into this github thread, you can tell me via PM in Habitica if you like, or in Ghost Ship guild chat.)

**Comment by Alys** [comment] 2016-05-13 11:06
Guild is https://habitica.com/#/options/groups/guilds/4b4c7c73-884d-42ea-b2f8-e6be35d28479 not a4244022-f517-437e-b038-24fa5fe99c32. :)

I've removed the logo and replaced the leader message. The hearts in the challenge name didn't come across because the editor I use didn't handle them properly, but they can be added later. Tell us here if anything else isn't right.

I don't have any firm opinion about contacting the artist. It's up to you. :)

This error probably was caused by the Entity. We're close to the end of a project to make some large improvements to Habitica's code, which is likely to remove or significantly decreases the instances of the Entity. The new code is expected to go live later this month. If this bug still happens after that, we'll investigate.

If you have other changes before then, you're welcome to post again for us to make them for you. Comment here even though I'm about to close it (we'll still see it), or if you can't easily find this issue, create a new one.

**Comment by habitrpguser** [comment] 2016-05-13 11:24
Ooops yes, I shouldn't have accidentally copied the group id of my private testing guild! :-} I edited my original post here accordingly.

@Alys , thank you for fixing this so fast! (What would we do without you?) I'll report again here after the new code goes live. (Then I'll try to put the hearts back in as a test.)

**Comment by habitrpguser** [comment] 2016-05-22 15:20
Now that the new code is live, I just tried to put the hearts back into the "Ghost Ship" guild as planned, and got a "request entity too large" error. The missing hearts themselves are no problem, and there's nothing urgent that needs to be done. Within the next few weeks I'd like to make a few other small changes - but I'll have to think about them a little first. But basically, I just want to report that the error is still there.

Please don't stress yourself - you don't have to reply immediately, or at all! I'm sure you are all very busy now after the code change. In the long run, if the guild stays uneditable, I'll just continue to post guild description changes here. I'll also try my first approach again, i.e., try changes every few days since the guild size varies over time. If I notice that the guild can be edited, I'll tell you here again.

**Comment by IstraLouise** [comment] 2016-05-25 23:29
Hi, Alys and long-suffering staff.  I hate to bother you but I'm having trouble editing my guild 'Book Lust' (https://habitica.com/#/options/groups/guilds/16b96e1b-0b59-4b49-b9a7-05f20ff760e6) in order to add a survey and change some information from 'a word from the guild leader to guild description' and update the picture.
I am getting something like 'request entity too large' whenever I try to edit the information.

I was able to edit the guild before the update, I think.. we did add some challenges so if challenges are a problem maybe that's where we went wrong.

We had hoped to do the initial survey and then end it on June 10th, and then create a vote based on all the titles gathered from the first survey that weekend.  Nowhere near as dire as copyright infringement, but please help, this is going to really change how we operate day to day if we can't get the announcements changed.  Is there any way you could change them?

**Comment by Alys** [comment] 2016-05-26 00:28
@IstraLouise We can definitely help with this! Let us know what you want changed. It might be a couple of days though.

**Comment by crookedneighbor** [comment] 2016-05-26 00:51
I _think_ this is happening because the update request is sending the entire chat array. Since we're making a copy of the group when editing, I think we could get away with just deleting the chat array from it when we press the edit button

https://github.com/HabitRPG/habitrpg/blob/develop/website/client/js/controllers/groupsCtrl.js#L46

**Comment by crookedneighbor** [comment] 2016-05-26 01:08
Just tested it, that is exactly why that's happening.

**Closed as completed** 2016-05-26 01:19 UTC

**Comment by crookedneighbor** [comment] 2016-05-26 03:17
@IstraLouise Refresh your browser and try again. It should work now.

**Comment by habitrpguser** [comment] 2016-05-26 09:47
Editing works again for the "Ghost Ship" guild now, too! Thank you, that solves some problems (and saves you some extra work)!
