### ISSUE TITLE
`undefined is not a function` (/app/src/controllers/user.js:98:21)

### ISSUE THREAD

**Issue by lefnire** [HabitRPG/habitica#3767] opened 2014-07-21 19:33 UTC
``` shell
TypeError: undefined is not a function
    at Promise.<anonymous> (/app/src/controllers/user.js:98:21)
    at Promise.<anonymous> (/app/node_modules/mongoose/node_modules/mpromise/lib/promise.js:172:8)
    at Promise.emit (events.js:95:17)
    at Promise.emit (/app/node_modules/mongoose/node_modules/mpromise/lib/promise.js:84:38)
    at Promise.reject (/app/node_modules/mongoose/node_modules/mpromise/lib/promise.js:111:15)
    at Promise.error (/app/node_modules/mongoose/lib/promise.js:89:15)
    at handleSave (/app/node_modules/mongoose/lib/model.js:126:17)
    at /app/node_modules/mongoose/lib/utils.js:408:16
    at /app/node_modules/mongoose/node_modules/mongodb/lib/mongodb/collection/core.js:637:9
    at Server.Base._callHandler (/app/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/base.js:442:41)
    at /app/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:485:18
    at MongoReply.parseBody (/app/node_modules/mongoose/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
    at null.<anonymous> (/app/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:443:20)
    at emit (events.js:95:17)
    at null.<anonymous> (/app/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:191:13)
    at emit (events.js:98:17)
    at Socket.<anonymous> (/app/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js:418:22)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:748:14)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:410:10)
    at emitReadable (_stream_readable.js:406:5)
    at readableAddChunk (_stream_readable.js:168:9)
    at Socket.Readable.push (_stream_readable.js:130:10)
    at TCP.onread (net.js:528:21)
    at TCP.onread (/app/node_modules/newrelic/node_modules/continuation-local-storage/node_modules/async-listener/glue.js:177:31)
```

**Comment by thedavemarshall** [comment] 2014-07-21 23:05
What are the reproduction steps for this? I think I have it located to
https://github.com/HabitRPG/habitrpg/blob/develop/src/controllers/user.js#L64 expecting `next` to be a function, and calling it but
https://github.com/HabitRPG/habitrpg/blob/develop/src/routes/apiv1.js#L92 not passing it in. I think that passing in `next` should fix it, but I can't reproduce this issue.

**Comment by SabreCat** [comment] 2014-07-21 23:51
@thedavemarshall: By the look of it, this was pulled from the error logs, so @lefnire may not have steps to reproduce. Some of these things have come via API abuse, server load, or "anyone's guess".

**Comment by lefnire** [comment] 2014-07-22 00:55
Exactly as @SabreCat says.. I _do_ have sample data which was submitted, let me paste here:

```
originalUrl: /api/v1/user/batch-update?date=1405911935440

headers: {"x-request-start":"1405911935549","x-request-id":"REMOVED","x-forwarded-proto":"https","x-forwarded-port":"443","x-forwarded-for":"REMOVED","x-api-user":"REMOVED","x-api-key":"REMOVED","user-agent":"Mozilla/5.0 (iPhone; CPU iPhone OS 7_1 like Mac OS X) AppleWebKit/537.51.2 (KHTML, like Gecko) Version/7.0 Mobile/11D167 Safari/9537.53","origin":"file://","host":"beta.habitrpg.com","cookie":"REMOVED","content-type":"application/json;charset=UTF-8","content-length":"56810","connection":"close","accept-language":"en-us","accept-encoding":"gzip, deflate","accept":"*/*"}

body: {"text":"MFP Log Diner","challenge":{},"attribute":"str","priority":1,"value":83.90006835545906,"tags":{},"notes":"drive","dateCreated":"2014-03-11T19:43:12.725Z","id":"9b9327c8-e15b-4996-9cb5-e05e75a67c70","streak":14,"checklist":[],"collapseChecklist":false,"repeat":{"su":true,"s":true,"f":true,"th":true,"w":true,"t":true,"m":true},"completed":true,"history":[{"date":"2014-03-12T04:00:15.749Z","value":7.690828761342928},{"date":"2014-04-01T04:01:41.621Z","value":26.105983807415967},{"date":"2014-05-01T04:03:51.783Z","value":43.40690970346703},{"date":"2014-06-01T04:01:50.649Z","value":60.80431681946136},{"value":71.1442557916444,"date":1404187206797},{"date":1404273680041,"value":71.72406545363597},{"value":74.62311376359385,"date":1404360100794},{"date":1404446669832,"value":75.20292342558542},{"value":75.782733087577,"date":1404532923231},{"date":1404619220405,"value":76.36254274956858},{"value":75.782733087577,"date":1404705885315},{"date":1404792214597,"value":76.36254274956858},{"value":76.94235241156015,"date":1404878479633},{"date":1404964928314,"value":77.52216207355173},{"value":78.1019717355433,"date":1405051229904},{"date":1405137707022,"value":78.68178139753488},{"value":79.26159105952645,"date":1405224008370},{"date":1405310444394,"value":79.84140072151803},{"value":80.4212103835096,"date":1405396858029},{"date":1405483280156,"value":81.00102004550118},{"value":81.58082970749275,"date":1405569687912},{"date":1405656021115,"value":82.16063936948433},{"value":82.7404490314759,"date":1405742774126},{"date":1405828826793,"value":83.32025869346748}],"type":"daily"}
```

Another:

```

originalUrl: /api/v1/user/batch-update?date=1405911905265

headers: {"x-request-start":"1405911905352","x-request-id":"REMOVED","x-forwarded-proto":"https","x-forwarded-port":"443","x-forwarded-for":"REMOVED","x-api-user":"REMOVED","x-api-key":"REMOVED","user-agent":"Mozilla/5.0 (iPhone; CPU iPhone OS 7_1 like Mac OS X) AppleWebKit/537.51.2 (KHTML, like Gecko) Version/7.0 Mobile/11D167 Safari/9537.53","origin":"file://","host":"beta.habitrpg.com","cookie":"REMOVED","content-type":"application/json;charset=UTF-8","content-length":"3846","connection":"close","accept-language":"en-us","accept-encoding":"gzip, deflate","accept":"*/*"}

body: {"_id":"7c00a402-d1b6-4206-b0be-5128bc569930","down":true,"text":"15 Mins Exercise","up":true,"challenge":{},"attribute":"str","priority":1,"value":108.65498015697608,"tags":{},"notes":"15 Mins Activity","dateCreated":"2014-01-20T02:10:32.560Z","id":"7c00a402-d1b6-4206-b0be-5128bc569930","streak":114,"checklist":[],"collapseChecklist":false,"repeat":{"su":true,"s":true,"f":true,"th":true,"w":true,"t":true,"m":true},"completed":true,"history":[{"date":"2013-09-15T01:34:31.393Z","value":-76.8442627997394},{"date":"2014-01-01T05:13:31.171Z","value":-72.45464952929213},{"date":"2014-02-01T05:16:58.972Z","value":-5.669624542462423},{"date":"2014-03-01T05:00:05.106Z","value":22.878386838104372},{"date":"2014-04-01T04:01:41.651Z","value":43.909567901250405},{"date":"2014-05-01T04:03:51.845Z","value":64.3462998583296},{"date":"2014-06-01T04:01:50.666Z","value":85.21134282378338},{"value":97.05878691714457,"date":1404187206821},{"date":1404273680072,"value":97.63859657913615},{"value":98.7982159031193,"date":1404360100811},{"date":1404446669847,"value":99.37802556511087},{"value":99.95783522710245,"date":1404532923409},{"date":1404619220701,"value":100.53764488909403},{"value":99.95783522710245,"date":1404705886065},{"date":1404792214838,"value":100.53764488909403},{"value":101.69726421307718,"date":1404878479642},{"date":1404964928328,"value":102.27707387506875},{"value":102.85688353706033,"date":1405051229926},{"date":1405137707090,"value":103.4366931990519},{"value":104.01650286104348,"date":1405224008381},{"date":1405310444403,"value":104.59631252303505},{"value":105.17612218502663,"date":1405396858038},{"date":1405483280182,"value":105.7559318470182},{"value":106.33574150900978,"date":1405569687931},{"date":1405656021129,"value":106.91555117100135},{"value":107.49536083299293,"date":1405742774140},{"date":1405828826804,"value":108.0751704949845}],"type":"daily"}
```

**Comment by lefnire** [comment] 2014-07-22 00:58
Seems it could indeed be API "abuse" (or rather, experimenting.. maybe someone's trying to build a client). Reason I say, is they're hitting beta.habitrpg (previously in the API docs) - I've gotten ~20-30 of these emails, they're all using invalid API requests. Batch update expects an array of OPs (`[{op:'addTask',data:{..},{op:'clearCompleted',data:{...}}}]`) (<-- pseudocode). 

Perhapse this isn't so critical after all, it'll just error for those API devs

**Comment by Alys** [comment] 2015-08-15 13:03
This was from api/v1. Closing.

**Closed as completed by Alys** 2015-08-15 13:03 UTC
