### ISSUE TITLE
Unexpected Token Syntax error on main page load.

### ISSUE THREAD

**Issue by starkaudio** [HabitRPG/habitica#6687] opened 2016-02-10 13:50 UTC
Loading the app this morning yields a syntax error followed by several other problems. Services unavailable? See attached screenshot. This has persisted for about 15 minutes.
<img width="781" alt="screen shot 2016-02-10 at 8 49 11 am" src="https://cloud.githubusercontent.com/assets/1504461/12948942/4897a126-cfd3-11e5-8ff9-8267592962e5.png">

**Comment by architech99** [comment] 2016-02-10 13:52
Seeing similar issues.

```
06:49:26.564 Object { data: "<!DOCTYPE html>     <html>     <hea…", status: 503, headers: tc/<(), config: Object, statusText: "Service Unavailable" }1 app-665327ea.js:32:17425
.responseError() app-665327ea.js:32
j() app-665327ea.js:7
k/<() app-665327ea.js:7
wd/this.$get</j.prototype.$eval() app-665327ea.js:7
wd/this.$get</j.prototype.$digest() app-665327ea.js:7
wd/this.$get</j.prototype.$apply() app-665327ea.js:7
s() app-665327ea.js:6
w() app-665327ea.js:6
y() app-665327ea.js:6

06:49:28.406 Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data
na@https://habitica.com/app-665327ea.js:4:28372
a/i<.get.transformResponse@https://habitica.com/app-665327ea.js:32:27764
uc@https://habitica.com/app-665327ea.js:6:9564
n@https://habitica.com/app-665327ea.js:6:11232
j@https://habitica.com/app-665327ea.js:7:9455
k/<@https://habitica.com/app-665327ea.js:7:9652
wd/this.$get</j.prototype.$eval@https://habitica.com/app-665327ea.js:7:16398
wd/this.$get</j.prototype.$digest@https://habitica.com/app-665327ea.js:7:14857
wd/this.$get</j.prototype.$apply@https://habitica.com/app-665327ea.js:7:16676
s@https://habitica.com/app-665327ea.js:6:12595
w@https://habitica.com/app-665327ea.js:6:14213
y@https://habitica.com/app-665327ea.js:6:13875
1 app-665327ea.js:6:24898
e/<() app-665327ea.js:6
kc/this.$get</<() app-665327ea.js:6
j() app-665327ea.js:7
k/<() app-665327ea.js:7
wd/this.$get</j.prototype.$eval() app-665327ea.js:7
wd/this.$get</j.prototype.$digest() app-665327ea.js:7
wd/this.$get</j.prototype.$apply() app-665327ea.js:7
s() app-665327ea.js:6
w() app-665327ea.js:6
y() app-665327ea.js:6

06:49:28.406 Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data
na@https://habitica.com/app-665327ea.js:4:28372
a/i<.get.transformResponse@https://habitica.com/app-665327ea.js:32:27764
uc@https://habitica.com/app-665327ea.js:6:9564
n@https://habitica.com/app-665327ea.js:6:11232
j@https://habitica.com/app-665327ea.js:7:9455
k/<@https://habitica.com/app-665327ea.js:7:9652
wd/this.$get</j.prototype.$eval@https://habitica.com/app-665327ea.js:7:16398
wd/this.$get</j.prototype.$digest@https://habitica.com/app-665327ea.js:7:14857
wd/this.$get</j.prototype.$apply@https://habitica.com/app-665327ea.js:7:16676
s@https://habitica.com/app-665327ea.js:6:12595
w@https://habitica.com/app-665327ea.js:6:14213
y@https://habitica.com/app-665327ea.js:6:13875
1 app-665327ea.js:6:24898
e/<() app-665327ea.js:6
kc/this.$get</<() app-665327ea.js:6
j() app-665327ea.js:7
k/<() app-665327ea.js:7
wd/this.$get</j.prototype.$eval() app-665327ea.js:7
wd/this.$get</j.prototype.$digest() app-665327ea.js:7
wd/this.$get</j.prototype.$apply() app-665327ea.js:7
s() app-665327ea.js:6
w() app-665327ea.js:6
y() app-665327ea.js:6

06:49:28.409 Error: c.data is undefined
.responseError@https://habitica.com/app-665327ea.js:32:16749
j@https://habitica.com/app-665327ea.js:7:9455
k/<@https://habitica.com/app-665327ea.js:7:9652
wd/this.$get</j.prototype.$eval@https://habitica.com/app-665327ea.js:7:16398
wd/this.$get</j.prototype.$digest@https://habitica.com/app-665327ea.js:7:14857
wd/this.$get</j.prototype.$apply@https://habitica.com/app-665327ea.js:7:16676
s@https://habitica.com/app-665327ea.js:6:12595
w@https://habitica.com/app-665327ea.js:6:14213
y@https://habitica.com/app-665327ea.js:6:13875
1 app-665327ea.js:6:24898
e/<() app-665327ea.js:6
kc/this.$get</<() app-665327ea.js:6
j() app-665327ea.js:7
k/<() app-665327ea.js:7
wd/this.$get</j.prototype.$eval() app-665327ea.js:7
wd/this.$get</j.prototype.$digest() app-665327ea.js:7
wd/this.$get</j.prototype.$apply() app-665327ea.js:7
s() app-665327ea.js:6
w() app-665327ea.js:6
y() app-665327ea.js:6

06:49:28.411 Error: a.config is undefined
b</<.responseError@https://habitica.com/app-665327ea.js:11:14484
j@https://habitica.com/app-665327ea.js:7:9455
k/<@https://habitica.com/app-665327ea.js:7:9652
wd/this.$get</j.prototype.$eval@https://habitica.com/app-665327ea.js:7:16398
wd/this.$get</j.prototype.$digest@https://habitica.com/app-665327ea.js:7:14857
wd/this.$get</j.prototype.$apply@https://habitica.com/app-665327ea.js:7:16676
s@https://habitica.com/app-665327ea.js:6:12595
w@https://habitica.com/app-665327ea.js:6:14213
y@https://habitica.com/app-665327ea.js:6:13875
1 app-665327ea.js:6:24898
e/<() app-665327ea.js:6
kc/this.$get</<() app-665327ea.js:6
j() app-665327ea.js:7
k/<() app-665327ea.js:7
wd/this.$get</j.prototype.$eval() app-665327ea.js:7
wd/this.$get</j.prototype.$digest() app-665327ea.js:7
wd/this.$get</j.prototype.$apply() app-665327ea.js:7
s() app-665327ea.js:6
w() app-665327ea.js:6
y() app-665327ea.js:6
```

I'm guessing there's a service down from the first error.

**Comment by anshbansal** [comment] 2016-02-10 13:54
Same here

**Comment by Somariel** [comment] 2016-02-10 19:44
I don't know if this is related, but the Tasks page looks extremely weird and isn't showing any of my tasks and the various menus are showing all options in overlapping lists. I tried to attach a screenshot to this post, but I'm getting a message saying "Something went really wrong, and we can't process that file."

**Comment by Alys** [comment] 2016-02-10 22:24
Everyone, these errors are likely to have been caused by the server overload we've been experiencing recently. We restarted the server not long ago, which should have helped.

@Somariel Does reloading the page help? If not, please go to https://habitica.com/static/clear-browser-data and click the button there. Does that fix it?

**Comment by starkaudio** [comment] 2016-02-11 02:18
I agree that it was server load, but it was _bad_...reloading did NOT help
the page for about 20 minutes. I wasn't upset though, I just wanted to
notify someone. Love the app, love you guys, keep up the good work!

-L

**Comment by scheidm** [comment] 2016-02-11 15:35
still having the issue after the server overload
ErrorEvent {isTrusted: true}
jquery.min.js:2 Uncaught SecurityError: Failed to read the 'contentDocument' property from 'HTMLIFrameElement': Blocked a frame with origin "https://habitica.com" from accessing a frame with origin "https://s7.addthis.com". Protocols, domains, and ports must match.ot.each.contents @ jquery.min.js:2ot.extend.map @ jquery.min.js:1ot.fn.(anonymous function) @ jquery.min.js:2(anonymous function) @ ActivityMonitorOverlayView.js:1ot.extend.each @ jquery.min.js:1ot.fn.ot.each @ jquery.min.js:1n.Class.create.bindActivityDetectors @ ActivityMonitorOverlayView.js:1i.Class.create.init @ ActivityMonitorController.js:1API.Component.load.onLoaded @ content.js:1(anonymous function) @ ComponentFactory.js:1q.execCb @ cajon.js:1b.check @ cajon.js:1(anonymous function) @ cajon.js:1(anonymous function) @ cajon.js:1(anonymous function) @ cajon.js:1each @ cajon.js:1b.emit @ cajon.js:1b.check @ cajon.js:1(anonymous function) @ cajon.js:1(anonymous function) @ cajon.js:1(anonymous function) @ cajon.js:1each @ cajon.js:1b.emit @ cajon.js:1b.check @ cajon.js:1b.enable @ cajon.js:1b.init @ cajon.js:1(anonymous function) @ cajon.js:1(anonymous function) @ cajon.js:1(anonymous function) @ cajon.js:1each @ cajon.js:1b.emit @ cajon.js:1b.check @ cajon.js:1b.enable @ cajon.js:1b.init @ cajon.js:1(anonymous function) @ cajon.js:1(anonymous function) @ cajon.js:1n.finishLoad @ text.js:1(anonymous function) @ text.js:1a.onreadystatechange @ text.js:1
app-c14655c7.js:6 GET https://habitica.com/api/v2/groups/party 503 (Service Unavailable)(anonymous function) @ app-c14655c7.js:6s @ app-c14655c7.js:6f @ app-c14655c7.js:6j @ app-c14655c7.js:7(anonymous function) @ app-c14655c7.js:7j.$eval @ app-c14655c7.js:7j.$digest @ app-c14655c7.js:7j.$apply @ app-c14655c7.js:7g @ app-c14655c7.js:4i @ app-c14655c7.js:5g @ app-c14655c7.js:4xa @ app-c14655c7.js:4wa @ app-c14655c7.js:4(anonymous function) @ app-c14655c7.js:9j @ app-c14655c7.js:1k.fireWith @ app-c14655c7.js:1o.extend.ready @ app-c14655c7.js:1I @ app-c14655c7.js:1
app-c14655c7.js:6 SyntaxError: Unexpected token <
    at Object.parse (native)
    at Object.na [as fromJson](https://habitica.com/app-c14655c7.js:4:28377)
    at b.get.transformResponse (https://habitica.com/app-c14655c7.js:32:27856)
    at uc (https://habitica.com/app-c14655c7.js:6:9564)
    at n (https://habitica.com/app-c14655c7.js:6:11232)
    at j (https://habitica.com/app-c14655c7.js:7:9455)
    at https://habitica.com/app-c14655c7.js:7:9652
    at j.$eval (https://habitica.com/app-c14655c7.js:7:16402)
    at j.$digest (https://habitica.com/app-c14655c7.js:7:14865)
    at j.$apply (https://habitica.com/app-c14655c7.js:7:16678)(anonymous function) @ app-c14655c7.js:6(anonymous function) @ app-c14655c7.js:6j @ app-c14655c7.js:7(anonymous function) @ app-c14655c7.js:7j.$eval @ app-c14655c7.js:7j.$digest @ app-c14655c7.js:7j.$apply @ app-c14655c7.js:7s @ app-c14655c7.js:6w @ app-c14655c7.js:6y @ app-c14655c7.js:6
app-c14655c7.js:6 TypeError: Cannot read property 'code' of undefined
    at responseError (app-c14655c7.js:32)
    at j (app-c14655c7.js:7)
    at app-c14655c7.js:7
    at j.$eval (app-c14655c7.js:7)
    at j.$digest (app-c14655c7.js:7)
    at j.$apply (app-c14655c7.js:7)
    at s (app-c14655c7.js:6)
    at w (app-c14655c7.js:6)
    at XMLHttpRequest.y (app-c14655c7.js:6)(anonymous function) @ app-c14655c7.js:6(anonymous function) @ app-c14655c7.js:6j @ app-c14655c7.js:7(anonymous function) @ app-c14655c7.js:7j.$eval @ app-c14655c7.js:7j.$digest @ app-c14655c7.js:7j.$apply @ app-c14655c7.js:7s @ app-c14655c7.js:6w @ app-c14655c7.js:6y @ app-c14655c7.js:6
app-c14655c7.js:6 TypeError: Cannot read property 'ignoreLoadingBar' of undefined
    at responseError (app-c14655c7.js:11)
    at j (app-c14655c7.js:7)
    at app-c14655c7.js:7
    at j.$eval (app-c14655c7.js:7)
    at j.$digest (app-c14655c7.js:7)
    at j.$apply (app-c14655c7.js:7)
    at s (app-c14655c7.js:6)
    at w (app-c14655c7.js:6)
    at XMLHttpRequest.y (app-c14655c7.js:6)(anonymous function) @ app-c14655c7.js:6(anonymous function) @ app-c14655c7.js:6j @ app-c14655c7.js:7(anonymous function) @ app-c14655c7.js:7j.$eval @ app-c14655c7.js:7j.$digest @ app-c14655c7.js:7j.$apply @ app-c14655c7.js:7s @ app-c14655c7.js:6w @ app-c14655c7.js:6y @ app-c14655c7.js:6

**Comment by Alys** [comment] 2016-02-14 03:27
@scheidm That error is just from an extension or other security feature on your PC blocking access to an optional sharing feature that uses a third-party site. It's not something to worry about. Are you still experiencing errors right now? There were a couple earlier today but we've restarted the server so hopefully things will be better for you now.

@starkaudio Thank you for your lovely message! :) <3

**Comment by Alys** [comment] 2016-03-06 22:48
We're tracking these server errors now at https://github.com/HabitRPG/habitrpg/issues/6700 so I'm closing this one. There's some advice at the top of that issue for anyone who experiences problems like these.

**Closed as completed by Alys** 2016-03-06 22:48 UTC
