### ISSUE TITLE
iOS Safari New User - Login/Register

### ISSUE THREAD

**Issue by dblanken** [HabitRPG/habitica#1088] opened 2013-05-29 14:41 UTC
Hi all:

I recently used HabitRPG on my computer and created an account to become a member.  When I attempt to log in using my iPhone using Safari, the intro bubble (Welcome to HabitRPG) is in front of the links to login/register, and the link to continue the bubble is underneath the header behind the rest of the page, so you cannot continue.  It may be an issue with bootstrap-tour, however, is it possible to allow clicking the bubble div to continue the tour or a query string that would bypass the tour?

![photo](https://f.cloud.github.com/assets/26911/579232/c6dc0e70-c86d-11e2-9087-320a71c2a74e.png)

**Comment by lefnire** [comment] 2013-05-29 14:42
dupe of #995, let's follow up there.

**Closed as completed by lefnire** 2013-05-29 14:42 UTC
