### ISSUE TITLE
Tag icons remain after all tags removed via global deletion

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#1611] opened 2013-10-12 15:58 UTC
Given issues #1403 and #1528, tag filters aren't very useful to me at the moment. Plus I don't have all that many context-sensitive tasks these days anyway, so I decided to wipe out my filters by deleting them all from the main list. The checkboxes are gone from all the tasks, but the tasks still retain the "tags" icon saying they have tags added. Hovering over them doesn't show anything.

UID 7f14ed62-5408-4e1b-be83-ada62d504931

**Comment by paglias** [comment] 2013-10-24 19:47
This is fixed, see #1643, but I still have to write the database migration to fix it for existing tasks, follow-up there

**Comment by SabreCat** [comment] 2013-11-15 12:19
This issue seems to have cropped back up. On beta.habit, I deleted a tag, and the tag icons vanished from everything I expected them to... but the next day, the tag icons had returned, and no way to get rid of them.

**Comment by lefnire** [comment] 2013-11-18 04:42
@paglias did I break this?

**Comment by paglias** [comment] 2013-11-18 16:00
Well it seems that finally client-side UI is updated correctly, but server doesn't work and I don't understand why... The returned user is saved correcly and indeed you see the empty tag icon only after a refresh and I can't understand why...

**Comment by lefnire** [comment] 2013-11-19 03:09
Likely what's going on (this took me a long time to figure out).

When you have a "fuzzy" Schema attribute, like [TaskSchema.history](https://github.com/HabitRPG/habitrpg/blob/develop/src/models/task.js#L18) (`Array`), or in the case of [TaskSchema.tags](https://github.com/HabitRPG/habitrpg/blob/develop/src/models/task.js#L22), `Schema.Types.Mixed`, then Mongoose can't override the setter methods of nested properties, and therefore can't flag when something's been marked as modified. When using `Model.save()`, Mongoose only saves attributes to the database that have been marked modified. So for attributes without a definitive schema (`Array` & `Schema.Types.Mixed` are the only ones I think), you have to explicitly call `Model.markModified('path.to.attr')` before calling save. So for removing tags, we probably need to do:

``` javascript
user.markModified('habits');
user.markModified('dailys');
user.markModified('todos');
user.markModified('rewards');
....
user.save()
```

**Comment by Clariel** [comment] 2014-01-16 00:38
Is this supposed to be fixed? Because I have tasks with tag icons that have no tags assigned.

**Comment by paglias** [comment] 2014-01-16 16:30
I can confirm this is back,  (sometimes) tags are not correctly saved or deleted

**Comment by lefnire** [comment] 2014-01-16 16:48
I'll write up some api.mocha tests for this. Gonna wait will after https://github.com/HabitRPG/habitrpg/pull/2396 is merged so we don't step on the CS => JS conversion toes

**Comment by meganstrickland** [comment] 2014-03-11 04:03
This is happening for me as well. 

I'm afraid I have no idea if the other stuff has been taken care of so this could even potentially be looked at, and it certainly isn't a big deal... but I just noticed this bug myself and went looking for any open threads and here it is. So... Thank you all so much for all that you do!

**Comment by Ulugbeg** [comment] 2014-08-21 12:09
Just to bring this back to attention, #2396 has been merged, and this problem still exists. It's not a bit issue, but a minor annoyance.

**Comment by paglias** [comment] 2014-10-12 11:09
Can't replicate anymoew

**Closed as completed by paglias** 2014-10-12 11:09 UTC
Labels: priority: minor
