### ISSUE TITLE
Dread Drag'on temporarily defeated (Increase in XP/GP; Shrimp Pets, NaN eggs/light crystals, collection quest ending)

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#3712] opened 2014-07-12 08:29 UTC
NOTE: IF YOU RECEIVED XP OR GOLD FOR NO REASON, THIS IS WHY:

Due to an unknown glitch, the Dread Drag'on was accidentally "defeated" much sooner than planned. Users have reported receiving the rewards, including XP, GP, and the Mantis Shrimp pet/mount. 

Potentially related: several users (including me) who were in a party quest have found that the Data Display Tool is now reporting that they are not in a party quest anymore. Another has reported that their damage for the day was suddenly reduced to zero - possibly a large-scale version of https://github.com/HabitRPG/habitrpg/issues/3693?

I'll add to this thread if any other weird quest-related things pop up in the Tavern. 

@lefnire

**Comment by fragmental** [comment] 2014-07-12 08:55
Confirmed.

**Comment by brightbold** [comment] 2014-07-12 15:25
Yes - the Data Display Tool reports that my party is no longer in a quest, while our Party page shows that we are still in the Hedgebeast quest with 101HP remaining. No damage appears to have been done to (or by) the Hedgebeast from yesterday's activities, at least, none is reported in the Party chat. Unfortunately I can't remember how many HP the Beast or I had yesterday, but one of my party members was in the Inn and had just leveled up, and she's still showing 50HP so I'm guessing the quest progress was not processed last night at all.

**Comment by thebat137** [comment] 2014-07-12 16:14
I can confirm that quest progress didn't happen.  I'm in a solo Egg Hunt quest, and I know I had collected 42 eggs before cron.  It was still 42 eggs after, too, even though I should have collected at least a dozen eggs.  When I refreshed after my cron last night, I got some kind of error message about a null quest, and no collection message showed up on my party page, not even a message that I'd collected zero eggs.  However, when I cast Tools of the Trade a couple minutes later, that _did_ show up on the party page.

**Comment by DrewbyPls** [comment] 2014-07-12 16:15
Why was I referenced to this from #3717?  I have no idea what anyone's talking about in this thread.

I have yet to have done any quests or anything like that.

**Comment by thebat137** [comment] 2014-07-12 16:16
DrewbyPls, because the pseudo-defeat of the Dread Drag'on gave _everybody_ a bunch of spurious XP and gold last night, and some people also got the quest pet and mount.

(If you don't know what the Dread Drag'on is, it's a "World Boss" for which quest progress has been tracked in the Tavern.)

**Comment by DrewbyPls** [comment] 2014-07-12 16:17
Oh I see.  Thank you for the info.

**Comment by lemoness** [comment] 2014-07-12 16:24
Edited the ticket to make that redirect more obvious for future people.

**Comment by shanaqui** [comment] 2014-07-12 16:41
I know some people have been having party/quest problems because of this, but I've got an odd variation: my cron was a while before the bug kicked off, and I'd done party damage etc as usual -- I checked both soon after my cron and when I got up in the morning, after the bug occurred. Now that damage has disappeared, but only in the last few hours..

**Comment by CS-Raela** [comment] 2014-07-12 17:07
@shanaqui To me that sounds potentially to do with time zones rather than directly related to this case - assuming that cron is based on one's own time zone, which I recall reading in the FAQ. However that does suggest that when this bug occurred, data pertaining to the previous day regarding quest and party information got corrupted even if it was after cron for certain time zones.

Myself I was accessing habitrpg from app via iPad when I noticed the strange jump. It was definitely before midnight PST. Imagine my confusion going from level 2 to 7 in an instant. I was worried I had glitched the app's syncing to the site (or multi tapped the + somehow...) rather than something like this.

If you put it together, data corruption is likely\* from the on-defeat script/event of the world boss modifying values incorrectly. If the world boss is classified as a boss, but isn't part of a party quest, then perhaps there's null values being passed around somewhere.

My apologies if this is not helpful to the trace of this bug. I just felt like putting in my 2 silver.
- I say likely here, but because I am unfamiliar with the underlying system I may be totally off base with the hypothesis.

**Comment by shanaqui** [comment] 2014-07-12 17:11
My cron is not synchronous with my time zone, it's set to be two hours later. And like I said, the boss damage showed after my chron and before the bug, and also after the bug showed, until the last couple of hours. That may mean it's not related at all, or maybe I had a cached page, but it might be useful info.

**Comment by ArlieS** [comment] 2014-07-12 17:14
I also have nothing happening in my party, much like thebat137 described, except I'm in a kill-the-boss quest rather than a collection quest, and my quest should have terminated overnight - I only needed to do 75 more damage, and my back of the envelope estimate says that I probably did 100-150 points of non-appearing damage.

**Comment by casicastiel** [comment] 2014-07-12 17:50
Another possibly related tidbit: I've been getting more Application Errors today than I have in a long time.

**Comment by lemoness** [comment] 2014-07-12 18:00
I am as well, actually.

**Comment by lefnire** [comment] 2014-07-12 18:01
Drag'on is back on the battle field, I'm running the script to remove MantisShrimp pet & mount from users. I'm investigating the problem

**Comment by lemoness** [comment] 2014-07-12 18:15
Go Tyler go!!! You're a champion :D

**Comment by thebat137** [comment] 2014-07-12 19:30
Just to note one other thing for eventual cleanup --- I and at least some others still have a "The Dread Drag'on of Dilatory x1" quest completion listed in our stats.

**Comment by itokro** [comment] 2014-07-12 19:33
Just a confirmation on this affecting party quests - my party screen is still showing that I'm in the Dilatory Derby Quest, but the User Data Display isn't, and I didn't deal any boss damage in that quest from yesterday's tasks (even though I should have done)

**Comment by deilann** [comment] 2014-07-12 19:35
It may be sadly, that a day of wonkiness is a bit inevitable, and a day of
damage is lost. To kind of get that damage to run again,  your cron would
have to run again, which would... make wonkiness. Wonkiness is a good word.

**Comment by lefnire** [comment] 2014-07-12 19:44
@thebat137 thanks, forgot that one. Running script now.

**Comment by BI0WOLF** [comment] 2014-07-12 19:46
My party's damage was also not calculated into our party quest, and my dailies never reset the day that the Drag'on disappeared.

**Comment by lefnire** [comment] 2014-07-12 20:42
Lost quest progress bug fix:https://github.com/HabitRPG/habitrpg/commit/496618c6658c28caa580b7a0dfa775353082be99

**Comment by thebat137** [comment] 2014-07-12 21:16
@lefnire , just to provide one data point on the results of your work, my spurious Dread Drag'on quest completion is showing up as gone now.  My mantis shrimp pet/mount also got removed as promised.  I did get the Drag'on quest completion message when I refreshed just now, as did many others, but I'm assuming that's just some kind of leftover wonkiness.

However, my user data display still doesn't show me as being on the Egg Hunt quest even though I can see it in my party screen --- is bug fix 496618c supposed to address that issue, or is that still in the works?

**Comment by lefnire** [comment] 2014-07-12 21:17
@thebat137 still in the works. I'm gonna wrap up a few more code bits, then run that migration

**Comment by thebat137** [comment] 2014-07-12 21:18
@lefnire, glad to hear it.  Thanks for all your hard work on this.  I wish I could help.  (Maybe after I graduate!)

**Comment by lefnire** [comment] 2014-07-12 21:19
@lemoness @deilann Ok, most affiliated bugs are now fixed (party quest, etc). I don't know how the boss died early, but I have a hunch. Setting `user.party.quest.progress.*` manually via the API isn't validated, so anyone could have run a `curl` script to do 5m damage. I commited https://github.com/HabitRPG/habitrpg/commit/860b3acc52eb122ca5dd266e219d57bfe9ab7f86, which caps boss dmg by a single user to 300. I moved it to all quest progress in https://github.com/HabitRPG/habitrpg/commit/89369e21a3daf9c6b69e26487b96a4e061d1d09e, figuring it's cleaner and solves the issue of insane mage OP spells. Let me know if (a) 300 sounds right, (b) we should keep it like this or only apply it to world bosses (previous commit)

**Comment by lefnire** [comment] 2014-07-12 21:29
and as many have noticed, I fixed the quest-completion dialog bug. Ha, I should have waited to deploy that fix till tomorrow. _sigh_ well, at least that should cut down on the "unwarranted GP / XP" tickets we keep getting, since they'll know where it came from.

**Comment by lemoness** [comment] 2014-07-12 21:38
I think 300 is fair, as it is the lowest hp of the easy bosses, so hard
bosses like spirit of spring will now take more punches. Drag'on's health
was designed to accommodate the hard-hitting mages, but due to the "spells
don't count if you aren't in a quest" bug it may have been evening out. We
will keep an eye on that!

**Comment by deilann** [comment] 2014-07-12 21:41
Only apply it to world bosses.

Many people enjoy being able to 1 hit kill their bosses. Would make them
very unhappy.

**Comment by deilann** [comment] 2014-07-12 21:45
(Especially solo pet collectors... who would now need at least 4 days to
kill many of the bosses... and as you have to defeat them 7 times... that
would put solo pet collectors on a very tight schedule.)

**Comment by deilann** [comment] 2014-07-12 21:47
It would be really cool though, if party leaders could set the max for the
party...

**Comment by lefnire** [comment] 2014-07-12 21:49
@thebat137 we're gold, can you check DDT now?

**Comment by thebat137** [comment] 2014-07-12 21:53
@lefnire , I see my quest in DDT now.  I don't have any quest progress for the day, and checking off one of my dailies didn't create any.  But since it's a collection quest, the progress is somewhat random, isn't it?

**Comment by lemoness** [comment] 2014-07-12 21:57
@deilann - That is a very valid point - however, to deal more than 300, I
think you usually have to cast a lot of Burst of Flames, which was planned
to have its boss damage sharply nerfed in the future. @lefnire was there
already a cap on damage without spells?

This should probably be a separate discussion, so that we can weigh
opinions from people with a variety of play styles.

**Comment by lefnire** [comment] 2014-07-12 22:03
@lemoness no cap was previously implemented, either spell or non. @thebat137 hmmm, `progress.up` will always increment even if it isn't used. `progress.collect{}` is counted separately. I'll keep an eye out.

@lemoness @deilann I'll leave it to y'all to get the covo separate & opinions weighed, I've no opinion one way or another - @lemoness hit me with the final decision?

**Comment by lemoness** [comment] 2014-07-12 22:08
For now, @lefnire, leave it just a cap for the world boss only if that's an
option (did not see it when skimming this thread on my phone) - people have
been through enough rock-and-roll in the past 24 hours without having their
normal boss damage suddenly reduced.

If it is just world boss, higher than 300 might be good, since we did
originally balance it with mages in mind. Let's say 900 max for world
bosses?

Leave normal quests be, if separating them is an option, and later today I
will start a discussion about boss damage caps as a way to nerf Burst of
Flames.

**Comment by thebat137** [comment] 2014-07-12 22:08
@lefnire, I just checked a couple more dailies and a couple todo checklist items (although no todos) and still nothing.  Then I just sat there and checked and unchecked a daily a couple times and no go.  I've got a moderately high PER (63 base, 154 with class and item bonuses), so I'd think something in there should've found me an egg...

ETA: Some people say in the tavern that they've been able to rack up damage on their boss quests, at least, so perhaps I'm just having a run of bad luck on egg-finding.  I guess I'll keep an eye on it throughout the rest of the day.

**Comment by effpeeks** [comment] 2014-07-13 00:09
I have just experienced a problem that could be related? I was in the middle of the second Vice quest, with 15 out of 45 light crystals collected. I have a solo party, and I've been getting 1-6 crystals a day. About ten minutes before my cron cycle ended (one hour ago) I checked the User Data Display page and had a Quest Progress of 0. Shortly after, I refreshed my HabitRPG page and got a load of gold and XP, so I checked my Party page, and my quest was finished! I found the following note in my chat board: "effpeeks found NaN Light Crystals." According to the User Data Display I am no longer in a quest. I also now have the third Vice quest scroll. Dunno what happened or why, but I thought I'd mention it!

**Comment by lefnire** [comment] 2014-07-13 01:05
@thebat137 could you open up Chrome Console, fiddle around with dailies as you've been, and see if any errors show up on console? What's your UUID?

**Comment by thebat137** [comment] 2014-07-13 01:08
@lefnire, my UserID is dea8a9e8-c084-438a-9a14-7fe96a73fd0a.  Chrome Console is a thing in the Google Chrome browser, right?  (I'm still a Firefox/Iceweasel user, but I can switch over for any testing you need.)

ETA: Assuming I'm looking in the right place, I don't see any actual errors being triggered by clicking on dailies or todo checkboxes or anything.  There are a couple general warnings that came up for the page before I did anything, but they don't seem serious.  Just for completeness, they are:

Consider using 'dppx' units, as in CSS 'dpi' means dots-per-CSS-inch, not dots-per-physical-inch, so does not correspond to the actual 'dpi' of a screen. In media query expression: (-webkit-min-device-pixel-ratio: 1.5), (min-resolution: 144dpi) tweet_button.1404859412.html:1

and:

Given URL is not allowed by the Application configuration.: One or more of the given URLs is not allowed by the App's settings.  It must match the Website URL or Canvas URL, or the domain must be a subdomain of one of the App's domains.

Also, I should mention that using Chrome doesn't seem to affect whether or not I'm getting quest progress in the DDT.  I'm still supposedly doing damage to the Drag'on, though.

**Comment by thirdpolice** [comment] 2014-07-13 05:55
At least two members of my party (myself included) got a popup notification that the Hedgebeast was defeated. The Hedgebeast was actually defeated 8 days ago according to the party chat, and we haven't embarked on a quest since then.

Looks like it was just the notification that was repeated, not the rewards, but I'm not 100% sure of that.

My user ID is 1c6567b4-9226-47e7-b52f-e00aefa8b11e

**Comment by BCarnan** [comment] 2014-07-13 06:58
Please don't take my burst of flames!  Mostly I do very little damage based just on my dailies, so it's very satisfying to occasionally one-hit a boss.  It's the only way I can keep up with the fighter in my group!

**Comment by thebat137** [comment] 2014-07-13 07:14
So I just hit my cron and, as others on collection quests have been commenting, I found NaN plain eggs and got quest completion (having had 42 eggs the day before), including the completion reward.

I had another Egg Hunt quest scroll, so I started it up and checked off a few dailies just to see what would happen, and the DDT is now showing that I'm finding eggs again, so hopefully this will just be a once-off problem.

ETA: This Dread Drag'on glitch sure was a humdinger, wasn't it?  Probably time to start designing next year's Derby Day pet (and perhaps also next year's Derby Day glitch)...  :D

**Comment by Punk-mit-keks** [comment] 2014-07-13 13:27
My party started the egg hunt some days ago and today it suddenly says we finished it. I've never before been in a collecting quest, so I don't know how it is supposed to be working. But I got the feeling it wasn't working correctly from the beginning. in the partys chatroom is a message about that "kAbi found 0 Plain Eggs." 2 days ago, and from today is a message: "kAbi found NaN Plain Eggs. 
All items found! Party has received their rewards."
there stands nothing about the other party members. I'm utterly confused.
In the tavern I got told it may has to do with the glitsch of the drag'on.

**Comment by itokro** [comment] 2014-07-13 13:29
We're getting several reports in the tavern of people on the Egg Hunt quest receiving the message "[name] found NaN Plain Eggs" along with quest completion. I'm assuming this is ongoing glitchiness related to the Drag'on?

**Comment by brightbold** [comment] 2014-07-13 14:40
An interesting thing today - we completed the Hedgebeast quest last night, and today received double rewards for it (6 eggs, 250XP, etc.) Not sure if that was related to this issue or to #2805 - the message only appears in the party chat once, and with the other bug you can always see the damage messages twice. So I'm guessing it's Drag'on-related. Either way, not complaining (6 little hedgehogs!), but thought it was an interesting bug.

**Comment by MDKniese** [comment] 2014-07-13 16:33
Data point for the devs: I just marked off all my dailies, habits and to-do's for the day, and according to DDT did almost 140 damage to the drag'on -and found a grand total of zero magic crystals. Now the drops are random, so I suppose that's possible, but it certainly seems off...

**Comment by Fractionless** [comment] 2014-07-13 16:50
Progress notifications during our Egg quest have become glitchy as well, and it appears to be related to this bug too, because that's when this began happening.

Notifications after the Drag'on bug began appearing like this: "(player) found . "

The last cron notification before quest completion reads "(player) found NaN Plain Eggs," followed by "All items found! Party has received their rewards."

It's sweet to have completed the quest, but there's satisfaction in knowing how much you contributed too!

Let me know what additional information you need (e.g., party ID) to continue.

**Comment by ArlieS** [comment] 2014-07-13 17:00
This morning I did do some damage to my quest - but it's minimal. By the looks of it,  no "Burst of Flames" registered. I presume this is part of the same bug series, so reporting it here rather than as its own thread.

**Comment by lefnire** [comment] 2014-07-13 17:42
Anyone experiencing `NaN` bug, could you post your UUID and/or Group ID?

**Comment by thebat137** [comment] 2014-07-13 17:54
NaN bug data:
UUID: dea8a9e8-c084-438a-9a14-7fe96a73fd0a
Group ID: 33d17c3a-402f-4f29-a7a4-b35925807deb
Quest: Egg Hunt
Party size: 1
Notes: Had collected 42 eggs before the Drag'on glitch, saw no eggs collected after quests were restarted yesterday, collected NaN eggs at cron and got quest completion, started a new Egg Hunt after cron and seem to be collecting eggs normally (according to DDT).

**Comment by lefnire** [comment] 2014-07-13 18:14
'cept for you @thebat137, you fixed yourself :) (thanks for all the help on this ticket btw)

**Comment by thebat137** [comment] 2014-07-13 18:25
Heh, just figured I'd provide a reporting example.

**Comment by effpeeks** [comment] 2014-07-13 18:51
UUID: 3d3cceb3-f448-4820-a99d-65c96b4eb5ed
Group ID: 9e0445a0-963a-4785-a435-25c0020180d8

**Comment by lefnire** [comment] 2014-07-13 19:07
Confusticate. After looking at @effpeeks's data, looks like the `NaN` adding completes the quest, so I probably won't be able to nip this in the bud - as soon as someone sees the issue, it will have "corrected" itself by completing the quest (Schrodinger's Cat? Is that what that concept is?). Anyway, I'll keep digging

**Comment by deilann** [comment] 2014-07-13 19:13
Yeah, I'd guess that NaN + int = NaN and NaN is > target number of eggs?

Maybe solution would be to give folks who felt cheated (wanted to "earn"
it) another scroll to try again, so they can feel productive, if you have
the time? They'd get double rewards, but it might feel more like an
accompishment, and they can just sell the extra plain eggs or keep them as
a trophy.

**Comment by maleamy** [comment] 2014-07-13 19:25
It appears that it's not just eggs but all the collection quests. 
I just received NaN light crystals and completed the "Find the Lair of the Wyrm" quest after receiving the message that "MAL found  ." the day before.
User ID: 1d6ffc04-b404-4bff-96d5-0f83d341cd88
Group ID: 2569ecff-9ec2-4863-b2f4-ccf7b13d820f

@lefnire -- Would it help to solve the Schrodinger's cat issue if I start another collection quest? I have an extra egg hunt scroll right here.

**Comment by Fractionless** [comment] 2014-07-13 22:02
One more data point for the NaN bug, just in case:

User ID: 4fc02125-1cc6-40f0-86a9-fa861af7a9d2 
Group ID: 213a74df-610f-4c3b-ac33-43f8c88b7aec

**Comment by Mousekiro** [comment] 2014-07-14 05:41
My (solo) party got NaNed this morning.
UID: 8adce993-c886-4be2-87bf-34c517e6b316
Group ID: 37ccd16b-bee0-4a07-9ff4-51c8522bb39d

Got the rewards, though I've done nothing with them yet.

**Comment by toyg** [comment] 2014-07-14 07:57
Another NaN here - was at 85 eggs yesterday, and now it's completed. I'm not crying tbh (I hated the quest!) but here's my group ID: 
803d743a-14f8-42a2-8ab1-5c6520f0421d
and User ID:
632c1748-e362-4a8a-b20e-ca6d2dc0be82

**Comment by thebat137** [comment] 2014-07-14 12:48
Just to follow up on the NaN bug, my new Egg Hunt quest seems to be working just fine.  I got my expected number of eggs at cron.

**Comment by deilann** [comment] 2014-07-14 19:56
Updated title to reflect NaN bug.

**Comment by lemoness** [comment] 2014-07-14 19:59
A+

**Comment by seajules** [comment] 2014-07-14 22:50
I lost the damage I dealt yesterday, and my group got hit in our HP by our quest boss.
Group ID: 1c14d480-7c38-4bca-960c-6bfac41fafa6
User ID: f8793188-b734-463c-8eff-087d5dad8c7d

**Comment by Alys** [comment] 2014-07-14 23:04
@seajules:

When your quest boss removes HP from your party, it's always because one or more party members had not completed all of their dailies. HP loss is not caused by the Dread Drag'on nor by the bugs described in this issue. Note that there can be sync errors which make it look as if all your dailies have been ticked off, when really they have not been. For more information about damage caused by dailies and sync errors, see [My character died when it shouldn't have! What do I do?](http://habitrpg.wikia.com/wiki/FAQ#My_character_died_when_it_shouldn.27t_have.21_What_do_I_do.3F) in the FAQ.

You said "I lost the damage I dealt yesterday". Can you please explain that further? Please also include screenshots from your party page that show the problem.

**Comment by epimarti** [comment] 2014-07-20 21:50
Hi,
I was in the Inn the last month and discovered today that I had won at least 90 gold and something like 900 XP, without leveling up....
I can't say if I have got damage during the last month.
And I'm NOT in a party.
I hope it can help you fix the issue.

**Comment by deilann** [comment] 2014-07-21 00:42
Like.everyone else and it's stated here, you can remove.that XP and GP via
fix.character.values.

**Closed as completed** 2014-08-01 21:16 UTC
