### ISSUE TITLE
De-Aryanize default character

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#1529] opened 2013-09-13 01:38 UTC
Whenever a new user registers, their avatar defaults to a white male with blond hair. It'd be much more welcoming to a diverse base of users if the initial avatar were random, making no assumptions about the "typical" player's gender or skin color.

Self-assigning since this is a change hopefully within my coding reach, and which I tend to care about more than most!

**Comment by wc8** [comment] 2013-09-13 02:13
You could randomize it—or use _blue skin and white hair_. The latter option might be more palatable to those who take their character's appearance seriously. (As opposed to users like me who change it every so often.)

**The tour should probably mention the option to change the character's appearance.**. It's been a hot topic in the past.

**Comment by SabreCat** [comment] 2013-09-13 03:07
It would only be random when a new character is first generated--I'm not saying it should randomize your avatar every time you log in, ha. If I can't get it to be random, then we could come up with an iconic character setup that dodges the problematic nature of the white male default: a green-skinned lady, perhaps!

**Comment by lefnire** [comment] 2013-09-13 05:31
Thou shalt all be unto mine own image! But I agree with @wc8, that should probably be the last item of the tour steps. "Finally, click here to customize your avatar". 

One downside I anticipate is that I'm recently very much leaning towards removing habitrpg-shared/helpers:userSchema() and relying entirely on Mongoose default values for the User model. This will make my life a whole lot easier, but it could present quite the technical dilemma for this ticket.

**Comment by lefnire** [comment] 2013-09-20 15:52
Actually, I take that "last step of the tour" bit back. I forgot that there actually is a popover that shows up after a few clicks in the game, it's the first popover after the tour

**Comment by Gaelan** [comment] 2013-09-25 03:29
@lefnire Should I figure out random gear? Or should I wait because of the `habitrpg-shared/helpers:userSchema()` removal?

**Comment by SabreCat** [comment] 2013-09-26 03:17
How would random gear work? At the moment, there's only one set of linearly improving gear, though I get the impression there will be more variety once classes are up and running.

**Comment by lefnire** [comment] 2013-09-26 16:59
I think @Gaelan  means the avatar customizations (pink v yellow shirt might be the "gear" referred to?)

In any case, let's put this tick on hold (@Gaelan don't do anything yet) until I've fully removed helpers:userSchema() in favor of user.js:Schema. I'll ping back here when that's done - or I might just implement it myself at the same time, since once we're using mongoose schema, avatar randomization should be a fairly trivial task.

**Comment by Gaelan** [comment] 2013-09-26 21:52
Yeah, that's what I meant. My bad.

**Comment by lefnire** [comment] 2013-12-06 17:26
The new default character is bald, and there is no longer gender. We could go further to make the default skin some median tone like [c06534](https://github.com/HabitRPG/habitrpg-shared/blob/classes/img/sprites/spritesmith/skin/skin_c06534.png). I'm personally not digging the idea of randomization - new users will end up with an orc head, red mustache, and buns, thinking "wut?" - I think a median blank slate says more obviously "customize me" than a random combo.

**Comment by wc8** [comment] 2013-12-06 17:42
Yeah, that could go badly…It might actually end up upsetting more than it interests. Median tone is fine. 
Another idea: a silhouette with a ? for new characters, _a la_ pet slots in the stable, but instead of a footprint a silhouette.

**Comment by lefnire** [comment] 2013-12-06 17:46
I think the ? might still off-put people. Kinda "how do I unlock my avatar?". I'm thinking:
1. An "agreeable" default avatar, with an explicit callout in the tour
2. **OR** forcing users to customize immediately (a la Skyrim)

Edit: actually, @wc8 I see your idea agrees with #2. Another option is to redirect the user to /#/options/profile/avatar after the tour ends

**Comment by SabreCat** [comment] 2013-12-07 13:59
Okay, I'm convinced against random. I like the idea of having an agreeable default, especially if it's fantastical--a lot of our fan art has featured blue- or green-skinned peoples! Broad body, green skin, long hair perhaps?

Forcing immediate customization could work, but I think it'd be hard to avoid making it feel obtrusive with our UI.

The male/female thing is already being resolved with the customization overhaul.

**Comment by SabreCat** [comment] 2013-12-31 00:03
Our default is now a dark-skinned, bald, broad-shouldered Habiteer, which is not so fantastical as some of the suggestions but still a far sight less problematic than the original default. I'm happy with it; closing.

**Comment by lefnire** [comment] 2013-12-31 00:08
I actually forgot about this, I intended to ask y'all which you'd prefer as the start avatar.

**Comment by SabreCat** [comment] 2013-12-31 00:11
I mean, it'd still be cool to make it a green-skinned slim-bodied figure with white hair or something, but this one feels "generic" without saying "white dudes are the default human beings", heh.

**Comment by meganstrickland** [comment] 2014-03-09 11:01
Just throwing in my vote for green or blue skin for the starting avatar, so that no real-life skin color is privileged, and I think this would have the added bonus of making the baldness seem less "male" because, hey, blue skin.

**Comment by deilann** [comment] 2014-03-09 11:07
I'm not worried about a dark skin tone because as a white person, I know that my skin tone will always be an option in games. Obviously, I can't speak for POC, but I do know that they don't always know their skin tone will be an option, even if blue/green is an option because I've seen this in multiple games. I don't think Habit can suddenly grant privilege to POC by making their skin-tone default, and can only increase visibility that it is, in fact, an option. I would actually argue to make the default character dark skinned with a pony-tail, possibly the orange. Men will always assume they can be male; white people will always assume they can be white. The only time we ever see the gender thing going in the opposite is when male healers and mages are forced to wear dresses and tiaras.

**Comment by meganstrickland** [comment] 2014-03-09 12:41
Forgive me---when I created a dummy character over on cron.habitrpg.com, the default was pale, so I assumed that was still the default starting skin color on the main site. I absolutely agree that dark-skinned by default is better than pale-skinned by default. I still think that using a non-realistic skin color might deflect some of the gender assumptions, though.

**Comment by deilann** [comment] 2014-03-09 12:57
I think that the strongest way to beat off gender assumptions is to male the default avatar as feminine as possible. If it reads as female, people who want a feminine avatar will realize it's possible. People who want a more masculine avatar probably wont be worrying at this point whether or not it's possible because it is 99% of the time. And people who want to go androgynous are the kind of people who I feel are likely to play with the editor anyway, as theyre used to having to do that no matter what.
meganstrickland notifications@github.com wrote:

> Forgive me---when I created a dummy character over on cron.habitrpg.com, the default was pale, so I assumed that was still the default starting skin color on the main site. I absolutely agree that dark-skinned by default is better than pale-skinned by default. I still think that using a non-realistic skin color might deflect some of the gender assumptions, though.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/HabitRPG/habitrpg/issues/1529#issuecomment-37126048

Forgive me---when I created a dummy character over on cron.habitrpg.com, the default was pale, so I assumed that was still the default starting skin color on the main site. I absolutely agree that dark-skinned by default is better than pale-skinned by default. I still think that using a non-realistic skin color might deflect some of the gender assumptions, though.

**Comment by lefnire** [comment] 2014-03-09 17:25
@meganstrickland we selected the HEX directly in the center of our human skin-tone set. Probably looks white because it's not dark (per se), but Shane was pretty meticulous about designing the tone gamut based on real life, with proper stepping, so it should accurately be right in the center. What we were going for with bald: fresh-out-of-the-oven template human tofu :) We tried slim body for some femininity, but that's not speaking it to anyone, so...

So that's why we did what we did. As for what to do next, @lemoness & I were _thinking_ about just making default a WOC. As @deilann mentioned above, white men won't complain. Although, hearing @meganstrickland's arguments, I think I'm leaning towards blue or white (aka, ghost) skin. Blue, they might actually associate with an avatar (like, Avatar the movie)! White seems like a ghost - I know [Habbit](https://www.habbit.me/) actually starts you off as a ghost. Green I'm not so keen on, it speaks more orc or a poisoned player than "change me". Not sure what to do about hair color/length: (a) @deilann mentioned if we go funky-color, then the baldness might be ok; (b) others have mentioned just use a pony-tail. 

Anyway, those are my thoughts - I'm not gonna call any shots on this (as the white guy), so hit me with a PR when y'all have fleshed it out

**Comment by lemoness** [comment] 2014-04-30 01:24
1. How do we feel about having this be the new sample character?
   ![sample character](https://cloud.githubusercontent.com/assets/3494081/2836755/a4193a02-d005-11e3-853d-f659d07ba882.png)
2. After a bunch of conversations with new users (and less enthusiastic conversations with many angry social media messages accusing us of being sexist for requiring people to "pay to be women") I think I've hit on one of the big causes of confusion - the free ponytails are mixed in with the purchasable hairstyles. How hard would it be to rework the page to look like this? If there's a lot of that awful spritesmith renaming required, I volunteer myself to relabel them all.

![sample screen revision](https://cloud.githubusercontent.com/assets/3494081/2836775/082338d6-d006-11e3-8b2f-e87bbdda1321.png)
1. Can we rename the "Head" section to  "Hairstyles and Hair Colors"? I think this will also encourage people to scroll down and explore their options.

**Comment by deilann** [comment] 2014-04-30 01:27
Yes and yes

**Comment by SabreCat** [comment] 2014-04-30 01:46
This all sounds excellent to me.

**Comment by lemoness** [comment] 2014-04-30 02:05
Great! Let me know any and all ways that I can help to make this easier for
the devs :)

**Comment by Alys** [comment] 2014-08-02 05:45
Summary of actions required from the most recent comments:
- [x] rename the "Head" section to "Hairstyles and Hair Colors"
- [x] make default avatar look like [this image](https://cloud.githubusercontent.com/assets/3494081/2836755/a4193a02-d005-11e3-853d-f659d07ba882.png)
  - [x] default shirt: blue
  - [x] default skin: darkest brown
  - [x] default hair colour: orange
  - [x] default hair "base": large, one-sided pigtail
  - [x] default flower: blue
- [x] unmix free ponytails from purchasable hairstyles [like this image](https://cloud.githubusercontent.com/assets/3494081/2836775/082338d6-d006-11e3-8b2f-e87bbdda1321.png)
  - [ ] make Lemoness do any awful spritesmith renaming required ;)

I've just noticed that SabreCat is assigned to this, and here I was getting interested in it... :) @SabreCat did you especially want to work on these changes?

**Comment by lemoness** [comment] 2014-08-02 06:12
_salutes_ Tedious Spritesmith Renamer reporting for duty!

**Comment by Alys** [comment] 2014-08-02 06:26
@SabreCat : I couldn't stop. It was too interesting.

@lemoness : From my local install, <strike>this is what a new default avatar looks like</strike>, and what the new "Head" heading is like. Ok?   EDIT: Default avatar had the wrong body shape. See comment below.
![screen shot 2014-08-02 at 4 21 37 pm](https://cloud.githubusercontent.com/assets/1495809/3787280/66b02dae-1a0d-11e4-806a-dc3c98a7ec01.png)

The unmixing part hasn't been done yet.

**Comment by Alys** [comment] 2014-08-02 06:33
Grr. Sorry, wrong body shape. THIS is what the default avatar looks like:
![screen shot 2014-08-02 at 4 33 12 pm](https://cloud.githubusercontent.com/assets/1495809/3787307/e9484f84-1a0e-11e4-91be-1421973af886.png)

**Comment by lemoness** [comment] 2014-08-03 00:42
These are looking really good! Ahh Alice, you're great :D

**Comment by Alys** [comment] 2014-08-03 04:41
All that's left is "unmix free ponytails from purchasable hairstyles". Lemoness, there won't be any spritesmith renaming to be done.

I know how to do it and have tentative code, but I'm getting odd errors, even when I put my local install back to only approved code. If I can't sort that out soon, I'll upload my code and let someone else test it.

**Comment by lemoness** [comment] 2014-08-03 07:25
I'm secretly relieved.

**Comment by Alys** [comment] 2014-08-03 20:11
The code to make the final change ("unmix free ponytails from purchasable hairstyles") is here, along with a request for someone else to test it:
https://github.com/Alys/habitrpg/commit/e340d584cd3b912636e3898eae4951bf39560062

**Closed as completed** 2014-08-04 22:14 UTC
Labels: status: issue: suggestion-discussion, priority: minor

**Comment by Alys** [comment] 2014-08-04 23:29
Ummm.... @lemoness ... It's possible that my change to add the flower has had unintentional consequences... One user (John Camden - ha!) has reported that a flower has appeared on his head. Thinking about the change I made... I definitely added the flower to the file that defines defaults for new players. However I'm **guessing** now (too late!) that the file might also be applied to all existing players, meaning that any new defaults are applied to all players **unless** those players had already made a settings change that would make the default irrelevant. So in this particular case:
- For any existing player who was already wearing a flower, their flower would **_not**_ have changed. 
- For any existing player who had at some time in the past put on a flower and then taken it off, they would still **_not**_ be wearing a flower.
- But any existing player who had never experimented with flowers would now have been given a blue flower.

If this is correct, I'm sorry. :(  I didn't understand that the defaults would be applied to existing players. It could have been avoided by using a migration script that set flower=none for all existing players that didn't have a flower option, but I fear it might be rather late for that since all players who've used Habit since the change went live might now have the flower. That is, IF my guess is correct. It might just be a coincidence that John put on a flower and then forgot he'd done so.

@lefnire : The file I'm talking about is src/models/user.js - do all new defaults get picked up by existing players? Is it worth reverting the change in production until a migration script is written for the remaining users that haven't been affected yet?

**Comment by lemoness** [comment] 2014-08-04 23:34
Ahhh - well, we'll know if that's the case, because we'll get a flood of
complaints and bug reports.

It only just went live, right? If so, and your guess is correct, it would
be nice to reverse it so that we can minimize the confusion/complaints. If
it's too late, it's too late, but many people will still be at work/away
and not have logged in since the change.

**Comment by Alys** [comment] 2014-08-04 23:37
Reversing it would involve editing src/models/user.js to change this line:

```
flower: {type: Number, 'default': 1}
```

to this:

```
flower: Number
```

I haven't submitted a patch for that because doing so would put it into develop which means that all of develop would have to be pushed to production and I'm guessing that that's something @lefnire wouldn't want to do in a hurry (any other recent changes would get pushed out immediately). @lefnire, what's the best way to revert this? Sorry to create trouble for you.

**Comment by Alys** [comment] 2014-08-04 23:47
@lemoness Do you know if anyone part from Tyler has direct access to production?

**Comment by deilann** [comment] 2014-08-04 23:49
There'd be no way now to separate those who have blue flowers on purpose
from those who don't, that I can think of, though.

**Comment by Alys** [comment] 2014-08-04 23:51
No, we couldn't fix anyone already affected, but we could do a migration for all users who have no value for flower, to give them the zero value. But the fastest thing would be to revert the default flower change until a migration script had been written.

**Comment by deilann** [comment] 2014-08-04 23:52
I'm actually looking at it as a feature. It's easily solved (take the
flower off) and helps users who never noticed the flowers know they're
there.

**Comment by SabreCat** [comment] 2014-08-04 23:59
Best "not a bug, a feature" situation I've met yet! xD

**Comment by lemoness** [comment] 2014-08-05 00:06
@Alys In that case, I wouldn't worry too much about it - as Ryan says, it's
easy to solve. It just means that we'll have to answer the question "why
does my avatar have a flower?" several times. Hardly the most dramatic of
situations. I don't know if I'd call it a feature, but as bugs go, it's
pretty light.

**Comment by Alys** [comment] 2014-08-05 00:15
Damn, I've confirmed that it really is happening. I've just logged in to production with three test users that I created a while back, and they all have blue flowers. I'll create a separate Issue ticket for this so we can direct users to it if we want to. Sorry again.

**Comment by Alys** [comment] 2014-08-05 00:26
https://github.com/HabitRPG/habitrpg/issues/3843  "Blue flower appears on avatar's head"

**Comment by SabreCat** [comment] 2014-08-05 05:16
It sounds like you feel bad about this one, @Alys, but it's really quite
minor (and a little funny, but maybe that's just my bug-lovin' QAer brain).
It's not like you, say, made drops barely ever happen, or something like
that....

**Comment by Gaelan** [comment] 2014-08-05 05:17
Or broke everyone's stats page… :smile:

**Comment by Alys** [comment] 2014-08-05 05:23
Thanks SabreCat and Gaelan. :) But I feel only very slightly bad. I've been in IT long enough to know that glitches happen, sometimes even to me. :)  And I felt even less bad once I looked at the [PR](https://github.com/HabitRPG/habitrpg/pull/3834) and found this:
![screen shot 2014-08-05 at 3 22 18 pm](https://cloud.githubusercontent.com/assets/1495809/3807193/844de644-1c60-11e4-9748-a64fa206e270.png)

I've also been in IT long enough to know when I can escalate blame upwards. ;) :)

**Comment by lemoness** [comment] 2014-08-05 07:12
Hehehe ;)

**Comment by thepeopleseason** [comment] 2014-08-05 18:44
:clap:

**Comment by lefnire** [comment] 2014-08-05 19:12
Or dropped the database on Christmas! (Seriously @Alys, this is small-beans). I'll push the no-default fix for now. How about:

`db.users.update({'preferences.hair.flower':null},{$set:{'preferences.hair.flower':0}},{multi:1})`?

**Comment by Alys** [comment] 2014-08-07 01:01
Thanks @lefnire :)

**Comment by lefnire** [comment] 2014-08-07 03:10
@Alys do you want me to run that migration? Any devs wanna double check it?

**Comment by Alys** [comment] 2014-08-07 03:12
Yes, please. 

Is it possible for people other than you to run migrations?

**Comment by lefnire** [comment] 2014-08-07 03:13
Only Matteo & me. Running now
