### ISSUE TITLE
task boxes SCRAMBLED!

### ISSUE THREAD

**Issue by sgtorange** [HabitRPG/habitica#1027] opened 2013-05-22 18:52 UTC
i just loaded my page and noticed a ton of my tasks were missing! but then scrolled down and they are actually still there but all in random places WITHIN the same column. I logged out then back in and it's still scrambled, so now I have to go through my entire page and reorganize everything. Very annoying, think i'll make it a to do lol

**Comment by lefnire** [comment] 2013-05-22 18:53
dupe of #318, let's follow up there

**Closed as completed by lefnire** 2013-05-22 18:53 UTC
