### ISSUE TITLE
Taking Damage for no apparent reason

### ISSUE THREAD

**Issue by MaggieFero** [HabitRPG/habitica#6861] opened 2016-03-11 01:35 UTC
Today, for the second time, I took damage long after chron (in this case 15 hours) for no apparent reason. The first time this occurred was a few weeks ago. 

Some background information:
- As you can see in the attached screenshot, I do not have an active quest. 
- I leveled up this morning (around chron+8), and should still have 50 health. 
- I do not have any negative habits set up, so I do not ever expect to take damage except at chron. 

My user ID is 7e42d3ac-b053-4d39-b9d0-6dd38934e76d

![image](https://cloud.githubusercontent.com/assets/1719499/13690561/4b002f76-e6e6-11e5-975d-8f8aaeb1925c.png)

**Comment by Alys** [comment] 2016-03-11 23:37
@MaggieFero Thank you for reporting this! We've been looking into it, and into a couple of other reports that might be similar. We don't have anything useful to say yet, but I wanted to let you know that we aren't ignoring this.

If you notice yourself taking damage unexpectedly again, please comment here again.

**Comment by rogue-companion** [comment] 2016-03-12 14:41
I also have received damage for no apparent reason (and I am on a quest). I completed all of my dailies yesterday. I'm using Firefox 44.0.2 and my user id is  bd34e0df-179f-4323-9720-7c3592dd28c4. This isn't the first time I've had problems with Habitica. A few weeks ago I had sync problems between the web version and iPhone app...resulting in me losing a level, equipment, health, gold, and my streak counts (which I couldn't remember to reset manually). I since adjusted those levels and removed the app entirely....but it caused major damage to my party and I'm afraid if I continue to have problems with undeserved damage then my party will want to drop me. I don't know if it's worth mentioning, but I found it odd that I barely had any drops yesterday and I usually have a lot. I love the concept of Habitica and it has made a greatly positive impact on my life since I started a few months ago, but it is unreliable at times.

**Comment by Alys** [comment] 2016-03-13 03:02
@rogue-companion I'm sorry about that! The cause of the problems you described is that your browser wasn't able to sync to Habitica's servers. It was recording all the actions you took but it wasn't sending them to the server for permanent storage. One important consequence of this is that your Dailies weren't saved on the server as having been completed and so when cron ran, you were damaged for them. Also, you weren't receiving drops because the server assigns drops and it only does that when your browser can notify it that you have completed tasks. Please see the "Advice" section near the top of https://github.com/HabitRPG/habitrpg/issues/4313 - it lists ways of noticing when this problem has started and ways of avoid it.

**Comment by Alys** [comment] 2016-03-16 22:15
@MaggieFero You were suffering from a bug in the Android app that we've just found and fixed (fix will be on the Google Play Store soon).

This comment explains it and gives a workaround to use until the new app version is available: https://github.com/HabitRPG/habitrpg/issues/6879#issuecomment-197559252

I believe we don't need more information from you about this bug, but you are welcome to post here again if you have questions, or if anything else seems to be going wrong.

**Comment by MaggieFero** [comment] 2016-03-16 22:32
Hi, Alys!

Sorry, but that really doesn't sound like it applies. This was two weeks
before daylight savings time in my time zone, and I don't use the Android
app. I think that's something else that just manifests similarly.

**Comment by Alys** [comment] 2016-03-16 22:41
Ah, sorry about that! I'm reopening this.

**Comment by MaggieFero** [comment] 2016-03-16 22:44
Thank you!

**Comment by Alys** [comment] 2016-05-28 12:27
Habitica has recently undergone large changes, which means that the code that caused these bugs probably does not exist any more. I'm closing this, but if you notice the same problem happening again, please open a new issue.

**Closed as completed by Alys** 2016-05-28 12:27 UTC
