### ISSUE TITLE
Beast Master illegitimately awarded & Pets disappeared from stable

### ISSUE THREAD

**Issue by roseaboveit** [HabitRPG/habitica#1823] opened 2013-11-15 01:42 UTC
I just got the Beast Master achievement but I don't have all that many pets. I then tried to check how many pets I had in order to make this report and my stable shows NONE of my previous pets

**Comment by lefnire** [comment] 2013-11-15 02:04
dupe of #1818, simply refresh the page

**Closed as completed by lefnire** 2013-11-15 02:04 UTC
