### ISSUE TITLE
No Party Group Leader - 'leader' UUID deleted from party document even though leader is still active and in the party

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#6313] opened 2015-11-29 13:34 UTC
I am the group leader of the party but it is not showing up as me being the group leader and I do not have administrative rights to the party.
![screen shot 2015-11-29 at 9 33 59 pm](https://cloud.githubusercontent.com/assets/16068860/11457325/f399af3c-96e0-11e5-986b-7706aaff4b29.png)

User ID:552cf120-2a6a-4bb9-8942-b683c06f201c
Group ID:cafc4e8e-2681-491f-9a9d-c872e105df07

---

_edit by admin:_

**Comment by Alys** [comment] 2015-11-29 19:47
@fxxry I've set you as leader. (Note for admins: I was able to confirm fxxry should be leader because their user id was first in the members list.)

@fxxry This is the second time I've seen a report of this, so if you don't mind, I'd love it if you could give us some information to help us work out what might have caused this:

Did you create the party on the website or on the iOS mobile app?

Have you ever seen your name listed as group leader? I.e., were you shown as leader when you first created the party but then your name disappeared later, or did it never show that you were leader?

If your name did appear as group leader initially, but then disappeared later, do you have any idea how long it might have been before it disappeared?

**Comment by ghost** [comment] 2015-11-30 00:30
Thank you very much.

I created the party on the website.

I did see my name listed as the group leader but it disappeared later, I think it disappeared around 4-5 hours  after the party has been created.

**Comment by Alys** [comment] 2015-11-30 04:41
@fxxry Thanks very much for the details! I'm leaving this open so that we can track the problem, since this is the second time I've seen it. You can unsubscribe from notifications for this issue, if you wish to, using the button in the right-hand column on this page.

FYI for other admins, the first occurrence was reported in the Tavern a few days ago, and I fixed it there while hoping it was a once-off glitch.

**Comment by M1st3rSam** [comment] 2016-01-04 16:24
I am the group leader of a party and I am having the exact same problem described here.

**Comment by crookedneighbor** [comment] 2016-01-04 18:16
@M1st3rSam 

What's your User ID? You can find it in [Settings > API](https://habitrpg.com/#/options/settings/api). Be sure to only copy the User ID and _not_ your API Token.   

Please also provide the id of the party, if possible.

**Comment by M1st3rSam** [comment] 2016-01-04 18:22
The problem has already been resolved by admin but here is the info.
User ID: 6320a833-6907-4e4c-b3d6-8b711444abff
Group ID: dbac8fdf-6fc4-498b-bbc4-e1461bf11ee0

**Comment by wswld** [comment] 2016-01-17 21:13
Having the same problem over there.

Group ID: `0362556c-3fdf-4e93-8040-a5bac13acbb1`
User ID: `ead43d3b-3279-4d7d-9d2f-bd0f81994edb`

**Comment by Alys** [comment] 2016-01-17 21:20
@wswld I've made that user the leader.

**Comment by wswld** [comment] 2016-01-17 21:21
Thanks. Do you know where the bug is? I mean is there a way I could prevent that?

**Comment by Alys** [comment] 2016-01-17 21:24
@wswld We have no idea at the moment. Sorry!

**Comment by wswld** [comment] 2016-01-17 21:26
That's OK, I'll try to notice some details if it happens again.

**Comment by Alys** [comment] 2016-01-17 21:28
@wswld Thank you!

**Comment by wswld** [comment] 2016-01-17 21:33
I checked some of the stuff I did last time to possibly cause that. When you edit the group the `asign the leader` dropdown is empty. Saving changes with that empty — nothing happens. The moment I deliberately chose _myself_ in that dropdown and saved — voila, here comes the anarchy.

**Comment by wswld** [comment] 2016-01-17 21:35
I have my wife in that group, so I can check assigning leadership to her, if you set me as the leader again. I mean to check whether It's only assigning to myself, or assigning to anyone.

**Comment by wswld** [comment] 2016-01-17 21:55
Sorry, it does seem to be working in both cases (assigning to someone else and to myself in web app) — it's just the field is empty after the save, but it's OK after I press `fetch the new messages button`. So, it's not the culprit here, although empty field after save is misleading. With my original problem it persisted even after refresh.

**Comment by mgpc3** [comment] 2016-02-10 12:53
Hi there, I'm having this issue now as well, I think it might be the second time it happens to me but @Alys fixed it before I even had a chance to report it here the first time. 

UUID: 8f21e403-8e3a-4d75-8824-74fe4712b2ce
Group ID: dbfaff12-f77e-4635-9cab-aad256e616a7

I think I created the party last spring and it was probably done on the website (I don't think you could have done it from a mobile app back then). I haven't been paying very close attention to the page lately so I can't say for sure when my name disappeared, I just noticed it because I wanted to edit my party description and announcement today and then I discovered I couldn't.

**Comment by Alys** [comment] 2016-02-10 21:19
@ptdaisy That should be fixed for you now.

**Comment by mgpc3** [comment] 2016-02-10 21:58
@Alys It is, thanks a lot.

**Comment by wswld** [comment] 2016-02-14 18:13
I'm not a leader of my group again. That's weird because I was offline and in the inn for some time.

**Comment by Alys** [comment] 2016-02-17 21:33
In https://github.com/HabitRPG/habitrpg/issues/6730, it's reported that this happened when editing the party in the iOS app to change the party name.

**Comment by Alys** [comment] 2016-02-18 09:27
Confirmed: this happens when editing the party in the iOS app to change the party name. Logged at https://github.com/HabitRPG/habitrpg-ios/issues/333

**Comment by sm0xe** [comment] 2016-04-17 18:12
Sorry to necro-bump this thread, but it seems that we have the same problem, even though none of us are using the iOS app.
UUID: 64109824-b58b-4e4d-812b-48313aba69ed
GID: 061578da-2ce6-4c62-9597-d3c9bfeef31e

**Comment by Alys** [comment] 2016-04-17 22:27
@gussefant No worries about commenting here - that was the right thing to do!

I have some data from 23 March, from when I was investigating this bug, which shows that you were the leader of the party then, so something has happened since then to remove your leadership status. We might have a different bug that we haven't noticed before. Can you tell me when you first noticed this? Do you use the Android app? Since 23 March (or thereabouts) have you tried to edit the party (e.g., changing it name or description), and if so did you do that on the website or Android app or both?

I've made you leader of the party again. If you reload the party page on the website, you should see yourself as leader now. Tell me if you don't! Please do let us know here if this happens again!

**Comment by sm0xe** [comment] 2016-04-18 06:43
Thanks a lot! I hadn't really noticed until I tried to edit the group, right before reporting it. I'm using the Android app, but haven't edited the group outside the website, and I believe I haven't done so since mid-March.

**Comment by Alys** [comment] 2016-04-18 10:54
There's another fourteen parties that don't have leaders. For at least some of them, I'm completely certain that they did have leaders when I finished fixing leaderless parties in late March (I still have group records from the database back then), so something has caused them to loose their leaders since then. For some it could be that they're using an old version of the iOS app, but gussefant doesn't use iOS.

I've assigned leaders to all of those parties.

**Comment by mgpc3** [comment] 2016-05-01 15:04
I don't think I tried to edit the party details through a mobile app either (I use iOS) but my party seems to be leaderless once again. I'm not sure how long it's been that way, I just noticed today.

UUID: 8f21e403-8e3a-4d75-8824-74fe4712b2ce
Group ID: dbfaff12-f77e-4635-9cab-aad256e616a7

**Comment by Alys** [comment] 2016-05-28 16:13
I've just checked all parties and guilds and they all have leaders so I'm closing this. If the problem reoccurs, it will have a new cause so we can open a new issue.

**Closed as completed by Alys** 2016-05-28 16:13 UTC
Labels: help wanted
