### ISSUE TITLE
Daily Reordering (sort order not maintained)

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#1616] opened 2013-10-13 23:06 UTC
Over the past couple of days, my Dailies keep reordering themselves. It's pretty frustrating. I've added some new Dailies recently - could that be linked?

**Comment by paglias** [comment] 2013-10-14 12:12
By keep reordering what do you mean that if you move them they go back to the old position?

**Comment by lemoness** [comment] 2013-10-14 21:07
No, it appears to be a random position.

**Comment by lemoness** [comment] 2013-10-24 23:32
Having this problem again, and it's driving me insane!! It definitely happens every time I add a new Daily. I'm house-sitting this week, so I had to add a bunch - and now my Dailies list is a nightmare. I've had to reorder EVERYTHING three times already - they keep getting entirely scrambled!!

**Comment by ianoff** [comment] 2013-10-25 03:18
FYI, it's not just dailies. It's been happening to me on To Dos & Habits as well, whenever a new one is added, they get resorted from newest on top, to oldest on the bottom -- custom order is gone.

**Comment by paglias** [comment] 2013-10-25 17:05
Mmmm... I have no clue on this but as soon as we switch to mongodb's subdocs for tasks we'll need to use a specific property to set item's position so we'll need to update the whole code about this feature and probably this issue will be fixed too, right @lefnire ?

**Comment by paglias** [comment] 2013-10-25 19:46
ok I got this too this evening. 

It may, but I'm really not sure that the only way to make order persisting is replacing the whole array of items (https://groups.google.com/forum/#!topic/mongodb-user/HfFlSInmZME) replacing the old one with the new one which has updated ordering.

I don't know if this will work or not and I think the best solution would be to wait for the switch to subdocs.

**Comment by lefnire** [comment] 2013-10-25 23:48
@paglias i'm going to be switching to subdocs on the challenges branch, i'm working on the migration as we speak. If I haven't release challenges within a week, and we need subdocs sooner than later, tell me and I'll re-structure the commits (`git rebase -i`) such that these fixes can be pulled into develop/master - maybe monday/tuesday

**Comment by kriscrat** [comment] 2013-10-29 14:32
I am having similar issues, but I'm noticing it to my To Dos.  I can reorder them while I have one tag open, but when I go back to the website later to check something off they are back in their old order again.

**Comment by paglias** [comment] 2013-10-29 15:30
@kriscrat no it's ok here it's the same problems for todos/dailies/habits... I hope to have it fixed for next week

**Comment by lefnire** [comment] 2013-10-30 01:43
ok, I have (mutually-exclusive) 3 hunches:
1. subdocs will solve the issue, as @paglias mentioned. We'll be releasing ~Sunday, and let's hope for the best. The guess here was that the old schema stored `user.tasks` as an object, and `user[type+'Ids']` separately for sort-order
2. `User.save()` isn't being called after sorting. So `splice` orders the user's tasks for that browsing session, and on the server - but not in localStorage, and - then I don't know what.
3. To-dos `completed=true/false` issues. This hunch would mean the problem should only occur for To-dos (@lemoness you've definitely experienced for Dailies?). The notion here is that Todos have sort order, but now that I think about it it doesn't make much sense since we're storing both completed & non-completed todos on the same array; however, sorting restricts `to` `from` params in `splice()` to the HTML list - which could probably cause some wonkiness. A possible solution is, while migrating to TaskSchema SubDocs, migrate also to user.todos & user.completed. However, this would require a mobile release, and we'd have to wait till iOS hits the market

I'm just spitballing anyway, let's hope we're dealing with #1

**Comment by paglias** [comment] 2013-10-30 15:09
@lefnire I got this for dailies too.

I don't think switching to subdocs will solve the issue.

I was thinking about a "position" field under task schema, it would work also with todos (completed & not) and also when filtering tasks using a tag: when sorting end we should have the old position (absolute not relative to what is shown actually) of the task and the old position of the task "replaced" (the first one that got moved down, if there's one) and then we would be able to calculate everything without problems when some task is not shown since we're relying on the `position` field

**Comment by mutedgrey** [comment] 2013-11-14 09:15
I was looking to see if this had been brought up or not because how frequently my todos get reordered is driving me crazy! I haven't yet experienced dailies or habits reordering though I think rewards did once? It's really just the todos for me.

**Comment by SabreCat** [comment] 2013-11-14 13:05
This happens to me all the time, yeah, on all types of task. If I'm tenacious about it, putting them back in my preferred order every time I see them go off, it seems to stick after a while... at least until I join a Challenge or otherwise alter the list, at which point it's a free-for-all until the glue dries again.

**Comment by skelletime** [comment] 2013-12-09 06:46
Chiming in. Started playing today. Facing this same issue with To-Dos. Inconsistent order, hasn't affected Dailies or Habits. I noticed it initially after adding/editing/reordering Habits.

**Comment by brightbold** [comment] 2013-12-09 13:57
This just happened to me. I added a bunch of new To Dos, which appeared at the top of the list, and then I moved them all to the middle of the list. Realizing I'd forgotten one, I added another and changed its difficulty. When I saved it, the list had reordered so all the new things were back at the top, and all the things that had previously been at the top of my list were now at the bottom. This reinforces my theory (that I probably put in one of those other issues) that when you think you're moving the new tasks you just added, the system things you're moving the task that was previously in that position. When the display refreshes so it matches what the system thinks is going on, you realize you've totally wrecked the order of your tasks.

**Comment by mutedgrey** [comment] 2013-12-09 14:48
This is still happening for me, both for todos and rewards but not yet for dailies or habits.  I gave up on trying to put them back in the right order because it was such a pain. For me, the order seems random and not related to @brightbold's theory, but I could try again and see if that holds true.

**Comment by brightbold** [comment] 2013-12-09 14:57
After I posted the above I refreshed the page, and some items returned to the order that I had originally intended. The number of items out of place was the same as the number of items I had just reordered (although they were different items.) So another theory is that the server has it right but what we're seeing client-side is wrong, so we're rearranging things that are really in the right order because they look wrong to us.

**Comment by SabreCat** [comment] 2013-12-12 02:27
@brightbold, I think you're on to something! I'm gonna try the tactic of refreshing after each sort operation and see if that makes it behave better.

**Comment by lefnire** [comment] 2013-12-12 22:53
huh! I'll take a look too while I'm knee-deep in https://github.com/HabitRPG/habitrpg/issues/1977 . We're moving all operations to be performed both client and server-side with the same code (it was choppy in the past, I've developed a system which enforces unified code). Will keep this thread in mind when porting sortTask

**Comment by lefnire** [comment] 2013-12-13 00:24
sure enough, @brightbold! it's not run on the user object & saved in localstorage, but the op is POST'd to the server. So local browsing is outdated until a refresh, I'll be fixing this with APIv2

**Comment by SabreCat** [comment] 2013-12-18 13:05
I did a bunch of sorting this morning, and it does indeed appear to be fixed! Kudos @lefnire! If anybody spots this happening again, please reopen.

**Closed as completed by SabreCat** 2013-12-18 13:05 UTC
Labels: priority: important, status: issue: needs investigation

**Comment by brightbold** [comment] 2013-12-30 15:37
New craziness in #2180 - I wasn't sure this was the same root cause so didn't reopen this, but we may need to.

**Comment by theglus** [comment] 2014-01-25 10:57
I did a bunch of sorting today of my To-Dos and I seem to be having the same issue. It just started happening on 1/24/14, it was working perfectly fine on 1/23/14 (at least for me).

**Comment by SabreCat** [comment] 2014-01-25 15:47
@theglus: Did you have any tag filters active? That can make a hash of sorting.

**Comment by theglus** [comment] 2014-01-25 19:37
@SabreCat No, I didn't have any tag filters active, but that's good to know. It happening in both Chrome and Firefox on OSX.

**Comment by theglus** [comment] 2014-01-25 20:08
It appears @lorian has experience the issue and has documented it in #2180.

**Comment by lorian** [comment] 2014-01-25 20:49
Yep, it's been happening consistently to my to-dos for over a week now. It was working perfectly before then. I don't use tag filters and I try to keep my completed to-dos to a minimum (although I can't do anything about the challenge to-dos), but everything just bounces around willy-nilly.

**Comment by Hackiisan** [comment] 2014-05-02 07:22
I can cause the bug to occur if I drag the last item to any position that's not the second-last position. A page refresh resets the bug.

**Comment by aeshildr** [comment] 2017-11-17 15:16
Please reopen. I started playing today and have this same issue.
Refreshing after each operation doesn't work 
Moving the daily to a new position doesn't work

**Comment by Alys** [comment] 2017-11-20 13:16
@aeshildr The specific bug that this refers to was fixed. There are other, more recent sorting bugs but they have their own issues so reopening this one isn't needed. Please post to the Report a Bug guild in Habitica to describe the problem you're having (copy your comment from here if you wish) and we'll help you there. You can reach that guild from the Help menu on the website or from Guilds on the mobile app. All bugs are best reported there because we can see your Habitica account there to give you specific advice.
