### ISSUE TITLE
[API v3]Adding multiple tasks at a time causes error

### ISSUE THREAD

**Issue by froggily** [HabitRPG/habitica#7217] opened 2016-05-14 03:31 UTC
General Info
- UUID: 634ef54c-8d52-4293-8adc-f0e810dd85dc
- Browser: Google Chrome Version 50.0.2661.86 (64-bit)
- OS: Mac OS X Yosemite 10.10.5
### Description

When adding multiple tasks at a time, the red "Yikes, an error occurred!" message appears with "Error [object Object]" appears. When you sync, the new ones seem to be placed randomly at the top and/or bottom.
#### Console Errors

Failed to load resource: the server responded with a status of 500 (Internal Server Error)
app-010542b5.js:43 Objectconfig: Objectdata: Objectheaders: (c)status: 500statusText: "Internal Server Error"**proto**: ObjectresponseError @ app-010542b5.js:43

**Comment by paglias** [comment] 2016-05-15 09:16
Note: can't reproduce locally but only on v3.habitica.com

**Comment by paglias** [comment] 2016-05-15 09:28
@TheHollidayInn this happens because instead of a single POST request one is sent for each task being added

**Comment by paglias** [comment] 2016-05-15 09:28
Also, every time you add one or more task there' s a GET call to /user

**Comment by paglias** [comment] 2016-05-15 14:36
I'm fixing this

**Comment by paglias** [comment] 2016-05-15 14:44
Fixed in https://github.com/HabitRPG/habitrpg/commit/b31de3845bfe9b832819105483782f747c24d48c

@froggily it'll go live with the next deploy (later today or tomorrow)

**Closed as completed by paglias** 2016-05-15 14:44 UTC
