### ISSUE TITLE
too many hatching potions

### ISSUE THREAD

**Issue by kriscrat** [HabitRPG/habitica#1034] opened 2013-05-24 06:20 UTC
Sorry if this is a duplicate.

First, I LOVE the random drop.  Very motivating.

I'm not sure if this is really a bug or if I just happen to be unlucky with what drops, but I have nearly 30 hatching potions and no eggs to go with them.  I do have 16 pets, so it seems like I'm getting 2-3 potions for every egg that drops.  Is this what you're going for? Either way, I'm excited to be able to trade with my party members at some point in the future.

**Comment by lefnire** [comment] 2013-05-24 08:26
duplicate of https://github.com/lefnire/habitrpg/issues/901 ? Ie, do you have very many of one hatching potion?

**Comment by baconsaur** [comment] 2013-05-24 18:10
I had this problem as well. I think it's sorted itself out now, so I'm not sure if it was just random luck. Until about a week ago, every single one of my drops was a potion, but it was always just one at a time so it didn't seem to be an obvious bug. I definitely did have a panda egg duplicate once, though. And my boyfriend had the duplication thing happen too, yesterday he got like 20 cotton candy blue potions all at once.

**Comment by lefnire** [comment] 2013-05-24 18:16
let's follow up on #901, we've got duplicate hatching github issues as well

**Closed as completed by lefnire** 2013-05-24 18:16 UTC
