### ISSUE TITLE
Changes to challenges not saving at all

### ISSUE THREAD

**Issue by Dewines** [HabitRPG/habitica#7699] opened 2016-06-20 14:48 UTC
I created an new challenge and the information in the notes fields didn't save in the To-Dos. This was important because they contained links to articles that the person doing the challenge needed to read. I tried re-adding the notes (severaltimes), but they just didn't save.

I therefore deleted the To-Dos and recreated them, including the notes fields. When I'd saved the challenge, all the To-Dos had vanished! It's a complex challenge and I don't have time to keep recreating the whole thing in the hope that this time everything will save. Help!

**Comment by Dewines** [comment] 2016-06-21 09:24
I've now played around with a test challenge and basically you have to get everything perfect first time. The only thing you can change now is the explanatory text. If you make a mistake and need to make any changes to tasks or add any extra tasks, the changes just don't save.

**Comment by ShulamitLH** [comment] 2016-06-29 04:15
That is happening still for me as well. Once a challenge is saved, there's no option to add additional tasks or to change the title or difficulty of a task. I just tried it this morning, and it looked like it would add a task, but on refresh, the new task disappeared.

We really need to be able to edit existing challenges. It's too much work to re-create the challenge each time there is a small change (one new item added, for example).

**Comment by ShulamitLH** [comment] 2016-07-07 14:59
I just tried creating a new challenge with a variety of tasks and difficulties. After saving, I had a different member of our party join the challenge. All of the tasks had randomly organized themselves and had all reset the difficulty to easy, despite that I had set them about 1/3 easy, 1/3 medium and 1/3 hard. I was unable to make any changes on the challenge using edit.

**Comment by cjprieb** [comment] 2016-07-21 22:25
I'd like to attempt to fix this issue. I'm still learning my way around the code base and familiarizing myself with where things are, so I'm not yet sure what changes would need to be made.

**Comment by Alys** [comment] 2016-07-21 22:36
@cjprieb Thank you!! If you have any questions at all or would like any advice, just comment here!

**Comment by Hus274** [comment] 2016-08-07 03:12
Is this a duplicate of #7320?

**Comment by Alys** [comment] 2016-08-07 03:23
Yes, basically. Everyone, this is being tracked in  #7320  and @Hus274 is developing a fix in https://github.com/HabitRPG/habitrpg/pull/7877 so I'm closing this.

**Closed as completed** 2016-08-12 22:31 UTC
Labels: priority: important, section: Challenges, help wanted
