### ISSUE TITLE
Wrong party mate equipment

### ISSUE THREAD

**Issue by moskupols** [HabitRPG/habitica#2323] opened 2014-01-09 15:16 UTC
When I first look at the stats of my party mate A, I see his equipment, it's OK.
Then I look at the stats of another mate, B, and see his traits, but with A's equipment.
Then I look at the stats of mate C, and see B's equipment. If I look at C's stats again, I see C's equipment as it should be.

**Comment by SyntaxPickax** [comment] 2014-01-09 18:17
~~I can't reproduce this. Does this happen often?~~
EDIT: Oh, I see. The sprites are correct, but the listed equipment does belong to the previous member:
![screen shot 2014-01-09 at 10 56 46 am](https://f.cloud.github.com/assets/1245093/1880908/0f9779b2-7960-11e3-92ff-87e8b9457885.png)
Rogue wearing healer's equipment:
![screen shot 2014-01-09 at 10 56 36 am](https://f.cloud.github.com/assets/1245093/1880909/0fabccd2-7960-11e3-93c8-32bd1057aa87.png)

**Comment by colegleason** [comment] 2014-01-09 18:19
Duplicate of #2010

**Comment by lefnire** [comment] 2014-01-09 18:24
Quote from #2010:

> I'm pushing a tentative fix (see two commits above), which wraps the member profiles when you click them. I want to keep an eye out for performance to make sure this doesn't slow things down. Additionally, there's a bug with party-member gear. On first party modal click, it's correct. Second party modal click gives the previous member's gear - it's always one behind. Don't know if it's always been this way, items.gear has nothing to do with the wrap function, so my hunch is it's always been this way

So it's confirmed. Since 2010's original bug wasn't isn't related, I'll close that one and keep this open

**Comment by deilann** [comment] 2014-02-05 21:43
#2010 has been reopened, so I'm gonna close this one.

**Closed as completed by deilann** 2014-02-05 21:43 UTC
