### ISSUE TITLE
Today i got attribute points over lvl 100...

### ISSUE THREAD

**Issue by kawunngg** [HabitRPG/habitica#6434] opened 2015-12-31 13:54 UTC
Hello all,

today i got the notification that i have unallocated attribute points. my character is lvl 141 and i allocated them all some while ago. so i went to the character page and could allocate those points. (141 in total now.) after refreshing they are still there. 

i think i leveled up today, but i'm not sure when the attribute points appeared. 

My user ID is ce935e7f-00e6-44bc-a44a-5280553810f0

Happy New Year to you all!

**Comment by Alys** [comment] 2015-12-31 14:02
Confirmed - see stats below.

@kawunngg Thank you for reporting this!

```
    "stats": {
        "con": 5,
        "int": 30,
        "lvl": 141,
        "per": 100,
        "points": 0,
        "str": 6,
        etc
```

**Comment by crookedneighbor** [comment] 2015-12-31 14:10
Probably related to https://github.com/HabitRPG/habitrpg/pull/6312

@TheHollidayInn Mind investigating?

**Comment by Alys** [comment] 2015-12-31 14:16
In a database backup made on 2015-12-28, kawunngg's stats added up to 97 while the level was 140. That probably indicates three deaths after level 100 was reached and the latest code allows gaining of stats after level 100 if the total stats are less than 100.

**Comment by crookedneighbor** [comment] 2015-12-31 14:35
Probably because it doesn't take into account unallocated stats.

**Comment by crookedneighbor** [comment] 2015-12-31 14:35
My bad, I should have caught that while reviewing the PR.

**Comment by kawunngg** [comment] 2015-12-31 14:51
oh? only three times? i die a lot. :-D

in fact i wasn't sure if i really had 100 points total before i allocated the new ones. but if i had not 100, this means the lost points weren't allocated to me after levelling up if i lost them. well, not before today?
if i only had 97 on 28th then i should have had 3 unallocated points. i'm sure i did not have them in my notifications, but can't say if they were available at my stats page. 

from the maybe related thread i did not understand when this update went live. 
i think it's been a while since my last death, but i don't keep track and because of my party i die from time to time, so it's nothing special and remarkable for me anymore.

**Comment by Alys** [comment] 2015-12-31 20:19
@kawunngg It might have been more than three, but three recently enough to show up in your data. :) There's a relatively new bug that's causing you to be given more attribute points than you should be able to have, but it only happens if you die at least once after passing level 100. We'll get that fixed soon, and then the excess attribute points should disappear the next time you die or rebirth. When the code is working correctly, it will not be possible to have more than 100 points.

**Comment by kawunngg** [comment] 2016-01-01 23:37
thank you all for your efforts for habitica! :)

**Comment by huesitos** [comment] 2016-01-04 20:08
Hello, something kind of similar happened to me today. i leveled up to lvl 28 and when I went to the stats page to allocate my new attribute point, I had 74 new points! I refreshed the page and allocated them, and they remained. Is this normal behavior?

**Comment by Alys** [comment] 2016-01-04 20:21
@huesitos @crookedneighbor I've just confirmed huesitos's comment. I was at level 24, I levelled up, I received 76 points to allocate.

**Comment by Alys** [comment] 2016-01-04 20:26
@huesitos Sorry about that.  If you tell us your User ID, I'll fix your points. You can find your User ID from Settings -> API ( https://habitica.com/#/options/settings/api ). 

What I'll do is unassign all your points since I'm not sure how you'd like them assigned (I can't remove just the most recently assigned ones). But if you tell me how you'd like them split up between the attributes, I can do that for you to save you clicking 28 times. :)

**Comment by TheHollidayInn** [comment] 2016-01-04 20:28
I think I see the issue. I can correct it if @crookedneighbor isn't already working on it. Sorry for the delay, btw.

**Comment by Alys** [comment] 2016-01-04 20:29
It's okay, we're on it, but thank you :)

**Comment by Alys** [comment] 2016-01-04 20:39
fixed in https://github.com/HabitRPG/habitrpg/commit/53e2939ad90123985c61f994ad7eed6e0c66b374

**Comment by Alys** [comment] 2016-01-04 21:21
Both commits had to be reverted. A new fix will be done soon.

https://github.com/HabitRPG/habitrpg/commit/ece0de51cc29d2972a517c7b02c3c3f1dc15f734
https://github.com/HabitRPG/habitrpg/commit/8db492099cf1e6350afe271d1bf7ac1a6d23addb

**Comment by TheHollidayInn** [comment] 2016-01-04 21:27
Sounds good. Let me know if you need any help!

**Comment by huesitos** [comment] 2016-01-04 21:28
Here is my UserID 75ab2897-b05d-4b29-91b1-e7e0749a8c50. You can unassign them all, I'll allocate them :)

**Comment by Alys** [comment] 2016-01-04 21:33
@huesitos Thanks! I've set all your allocated points to 0 and your unallocated points to 28. Let me know if you want me to allocate them for you.

**Comment by huesitos** [comment] 2016-01-04 21:44
No prob! I did it myself. Thanks for the fast fix!

2016-01-04 17:33 GMT-04:00 Alys notifications@github.com:

> @huesitos https://github.com/huesitos Thanks! I've set all your
> allocated points to 0 and your unallocated points to 28. Let me know if you
> want me to allocate them for you.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/HabitRPG/habitrpg/issues/6434#issuecomment-168816368.

## 

Denisse Margarita Lara Martín

**Closed as completed** 2016-01-09 13:00 UTC
