### ISSUE TITLE
The "Leave" button doesn't change to "Join" inside the guild if accessed directly by a link with group id

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#3408] opened 2014-05-04 09:52 UTC
First of all, I know it's not something on the surface, and It's most like connected with private guilds and parties that seem to share the interface with open groups. So please excuse me if it there is a master ticket or if it isn't an issue at all.

Still if you browse the list of open guilds, the button "Join" is interchangeable with "Leave" .

_BTW, I've always considered it to be a drawback that you can not have a look at the guild without joining it - learn what challenges are held and who you can meet in the chat._

Anyways, if you access a guild by a direct link (e.g. [Bermy Bits](https://habitrpg.com/#/options/groups/guilds/4559996d-2100-4fde-bd4c-9b6989d9833f) ) the button in the left column will always be "Leave" no matter if you are a member or not.

So if it's possible to be implemented not interfering with private guilds and parties, it'll be logical to have an opportunity to join an open guild from the inside.

**Comment by wc8** [comment] 2014-05-07 12:36
To-do:
- [ ] guilds list: Preview and Join button
- [ ] set guild membership button to Join if not member. (Currently says, Leave).

---

I lean toward the _Preview_ replacing "Join" on the guilds list page.

**Comment by deilann** [comment] 2014-05-07 12:40
I was actually thinking that I'd like a preview _and_ a join button, at
least for GMs. This would allow GMs to quickly and easily step into guilds
for moderation purposes.

**Comment by ghost** [comment] 2014-05-07 13:32
@wc8 I assume these are from trello, right? Sorry I haven't thought to search for suggestions there.
Should I close the ticket?

**Comment by wc8** [comment] 2014-05-07 18:39
I added the checklists as a way to track work to be done @GitHubSphinx 
@deilann Is join redundant if you can _Preview_ from the guild list and _Join_ from the guild page? Regardless, I updated the to-do.

**Comment by deilann** [comment] 2014-05-07 20:19
No, one may want to join without previewing.

**Comment by ghost** [comment] 2014-05-08 15:01
@wc8 @deilann

> Is join redundant if you can Preview from the guild list and Join from the guild page? 

 I never thought of this option, but actually it may be the best one as it will solve the both to-do's and at the same time keep the list of public guilds neat with a single button for each guild. One may face a question of _Previewers_ participating in the _internal_ guild chat, but it really seems to be a more complex question.

**Comment by wc8** [comment] 2014-05-08 21:47
People can currently participate in a public guild chat if they have or save the direct link.

**Comment by ghost** [comment] 2014-05-09 08:57
@wc8 I know that, but it's not so evident now. If and when everyone sees the Preview button I believe 1. more users will use this opportunity. 2. More guild members might express their disapproval

**Comment by deilann** [comment] 2014-05-09 09:19
I'm not sure what the issue is, if it's a public guild, personally. They
could join, then say something, then leave, if this weren't possible.
What's the difference?

**Comment by ghost** [comment] 2014-05-09 11:49
@deilann thanks for pointing that out. You are right. no issue in previewing at all then.

**Comment by wc8** [comment] 2014-05-22 17:29
Should we close this? 
It's more of an information issue (FAQ?) than an a bug.

**Comment by deilann** [comment] 2014-05-22 17:30
It's something that should possibly change, even though it's expected
behavior. I'd keep it open.

**Comment by Alys** [comment] 2015-02-19 08:19
I would like to see this worked on reasonably soon because it is very common now to put links to guilds in the Tavern and other places. Also, the Newbies guild is linked to from the Help menu. This means many users will be bypassing the Join button on the guild index page.

I would also like to see a predominant Join button at the top of any guild, unless you are already a member (and maybe a Leave button there if you are). I would guess that many new users would not realise they can join a guild to get notifications. Any objections?

**Comment by lemoness** [comment] 2015-02-19 20:44
None! This has bothered me in the past.

**Comment by crookedneighbor** [comment] 2015-02-19 22:02
Something like this?

![screen shot 2015-02-19 at 4 02 07 pm](https://cloud.githubusercontent.com/assets/2916945/6277030/b2ca50e8-b850-11e4-8636-3c872c8333c5.png)

**Comment by Alys** [comment] 2015-02-19 22:05
Mmmmmmm .... very nice! Better than the thovghts I had. I like that location.

**Comment by crookedneighbor** [comment] 2015-02-19 22:59
One hiccup with this position. If the guild has an image, it'll likely push the button down beneath the fold. Is that okay? Or do we want it available without scrolling at all?

**Comment by Alys** [comment] 2015-02-19 23:59
I'd say available without scrolling. 

I suppose the same problem arises with large amounts of text. New users might chose such a guild first, and never know to look downwards for the button.

**Comment by crookedneighbor** [comment] 2015-02-20 03:39
Finding it difficult to determine easily whether a user is part of the guild already or not. There's a function for checking it, but using that in the `ng-if` results in it being called 6-7 times per page load. Seems excessive. 

The list of guilds page has access to a `group._isMember` for the choosing whether to show the join or leave button, but that doesn't seem like it's available in the scope on the guild detail page. 

Won't be able to work on this much over the next couple of days, so other devs feel free to have at it.

**Comment by LlamaHobbit** [comment] 2015-02-25 16:23
Glad someone is working on this! A lot of newbie questions wondering where the guild they thought they joined had gone. Also, and this may be a different issue, on the Public Guilds page all of the guilds have a green Join button - even ones I've been a member of for months. Would be nice to see the appropriate Join and Leave buttons on that page according to which guilds one was already a member of.

**Comment by crookedneighbor** [comment] 2015-02-25 17:09
Ahh, interesting. I didn't realize the `_isMember` thing on the public guilds page was broken. Thanks for pointing it out.

**Comment by crookedneighbor** [comment] 2015-02-25 17:48
Looks like for `_isMember` to work on [this line](https://github.com/HabitRPG/habitrpg/blob/develop/website/src/controllers/groups.js#L88), it must first have the `_isMember` attribute set as a boolean in [the groups model](https://github.com/HabitRPG/habitrpg/blob/develop/website/src/models/group.js#L8).

That doesn't seem like that should be a problem, and the value never actually gets saved, but I'm no Mongoose expert. Can someone verify that it is okay to do that?

**Comment by crookedneighbor** [comment] 2015-02-25 21:08
What do we think of this:

![screen shot 2015-02-25 at 3 07 15 pm](https://cloud.githubusercontent.com/assets/2916945/6380558/29b0175c-bd00-11e4-8590-c900028c64ff.png)

**Comment by Alys** [comment] 2015-02-25 21:13
I like it!

**Comment by lemoness** [comment] 2015-02-25 23:19
I like it too. Looks great!

**Closed as completed** 2015-02-25 23:28 UTC
