### ISSUE TITLE
Cannot add checklist to task in IE 10 - hitting enter redirects to another page or shows recent notifications

### ISSUE THREAD

**Issue by MerelKS** [HabitRPG/habitica#5690] opened 2015-07-29 11:40 UTC
I can only add the first checklist-box. When I hit [enter] to make the next checkbox, I am redirected to the subscription page of habitrpg. 
It sometimes helpes, to save the To Do (without checklist), run a manual sync, then try to add the checklist. Doesn't always work. 
I had the same problemen earlier, but [enter] would show/hide the menu bar at the top of the site. 

My Used ID is e0ddf4e7-19bd-4001-8915-979365d60e92 .
I use Internet Explores in Windows
##

**Comment by Alys** [comment] 2015-07-29 12:07
@MerelKS Can you remember approximately how long this has been happening for for both the redirection to subscription and the show/hide of the menu bar?

**Comment by MerelKS** [comment] 2015-07-29 12:16
@Alys  I remember the show/hide menu bar from two weeks ago. 
The redirection to subscription has happened this week. They seem to be happening one or the other. I haven't had them at the same time. 
Also, this mostly happens on my work-pc wich has IE on it. It has happened on my own pc as well, where I use Chrome.

**Comment by Alys** [comment] 2015-07-29 12:30
We deleted the show/hide menu feature several days back, so that's probably why it switched to redirecting you to the subscription page. Not that that makes it any less weird. :-/

We'd like to know if there's anything in the JavaScript Console in Chrome when this happens, although if it doesn't happen often in Chrome, it could be hard to find any error messages there. However, it's worth trying anyway. When you're next using Chrome, please open the JavaScript Console (probably under View menu -> Developer -> JavaScript Console), and try to add checklist items. Even if the bug doesn't happen, please tell us what is in the console, if anything.

**Comment by crookedneighbor** [comment] 2015-07-29 12:41
@MerelKS Can you tell us which version of Internet Explorer you are using?

**Comment by MerelKS** [comment] 2015-07-29 13:22
@Alys  I wil try to add some checklist-times with the console open in a few hours, when I'm back home. For @crookedneighbor  I am using IE version 10.0.9200.17377 at work.

**Comment by MerelKS** [comment] 2015-07-29 17:38
On my home computer with Chrome, I do not have any problems currently.

**Comment by Alys** [comment] 2015-08-11 23:03
Has it happened again in Chrome since then?

Is it still happening in IE 10?

**Comment by MerelKS** [comment] 2015-08-12 10:41
Yes it still happens in IE, and I will check on my home computer tonight (going to make a To Do now)

**Comment by tomeran** [comment] 2015-08-16 17:13
Yes I have the same problem on IE 10. Can't add more than one checklist item

**Comment by CharityB** [comment] 2015-08-24 19:01
I am having the same issue on IE 10.0.9200.17457. I can only enter 1 checklist item, when I hit enter for the next item I am redirected to the party page.

**Comment by negue** [comment] 2015-08-24 19:25
Can't reproduce on IE 11.

If I set my IE11 on "IE10" Mode the problem exist. Hmmmm

Are you able to upgrade to 11?

**Comment by Alys** [comment] 2015-10-12 22:31
Ugh, I've just realised, based on a comment in the Newbies Guild, that this bug makes it look as if checklists are a subscriber premium feature. When you try to add a new checklist item, you're redirected to the subscription page and that just looks dodgy. :(

**Comment by Alys** [comment] 2015-11-05 22:04
In https://github.com/HabitRPG/habitrpg/issues/6187 there's a report of hitting enter not redirecting to a new page but instead showing all previous XP/GP/MP/drops notifications.

**Comment by Alys** [comment] 2017-06-24 18:20
I'm putting this on hold because we're most of the way through a project to change the website's front-end code and this might no longer happen afterwards, or if it does, there'll be new code that will need to be modified to fix it.

**Comment by lemoness** [comment] 2017-10-17 01:03
Is this still happening?

**Comment by Alys** [comment] 2017-10-21 12:44
I'm closing this but we can reopen if it's still happening.

**Closed as completed by Alys** 2017-10-21 12:44 UTC
Labels: priority: medium, status: issue: on hold
