### ISSUE TITLE
Closing 'edit' doesn't save

### ISSUE THREAD

**Issue by gwillen** [HabitRPG/habitica#1599] opened 2013-10-07 00:36 UTC
When closing 'edit' mode on a task/habit/daily by clicking the 'pencil' icon a second time, it should either save, or revert and warn that it's not saving.

Right now it just closes, leaving the changes unsaved, and then next time the page is refreshed they're lost.

I understand the logic behind this behavior, but if you expect (as I did) that clicking the pencil again will save, it's hard to notice that it's not. Instead I just spent a long time thinking the site was really flaky and often failed to save things for no reason.

(I bet you this is behind a number of the other complaints you get about things randomly reverting to old values.)

**Comment by brightbold** [comment] 2013-10-07 11:43
+1. Back in the Derby days I also thought this action would save and it took me a while to figure out it didn't.

**Comment by paglias** [comment] 2013-10-07 13:22
I sincerely don't understand this, there's a big "Save & Close" button and
the pencil icon is faded unless you hover it with the mouse, there's
nothing suggesting that it should save the edits, or no?

2013/10/7 Kelley Curry notifications@github.com

> +1. Back in the Derby days I also thought this action would save and it
> took me a while to figure out it didn't.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lefnire/habitrpg/issues/1599#issuecomment-25802041
> .

## 

Matteo Pagliazzi - paglias.net

**Comment by brightbold** [comment] 2013-10-07 13:44
The pencil icon is _always_ faded unless you hover over it, so there's nothing about it being faded that suggests that it's not fully functional. Yes there is a big Save & Close button but it's way down the page and you often have to scroll to get to it. So when I first realized that I could toggle the pencil to collapse the task I thought I had discovered a big timesaver - click the pencil, edit, click the pencil, no scrolling required! I was still using the save & close button when I was editing things near the bottom of the task but I was toggling the pencil when I was changing things above the fold. So it took me a while to realize why only some of my changes were being saved.

The vast majority of the time (on my MBP retina) the save button is below the fold. If you are at the top of the Habit screen (showing your avatar etc.), you have to scroll for the save button on every task. If you scroll so that you can only see tasks on the screen, only the first 5 tasks in each column, assuming none of your tasks runs to two lines, have the save button visible without scrolling, compared to 12 tasks lower down where you have to scroll. So it would be nice to also be able to save by clicking the pencil and not having to scroll most of the time.

Like the OP, I think this is a feature request and not a bug. I admit there was nothing suggesting it was going to save, but nor was there anything suggesting that it wouldn't. I just assumed since it had the same visible action as the button - it collapsed the task - that it also had the same invisible action (saving).

**Comment by Shaners** [comment] 2013-10-07 16:10
Maybe something like this would help:
![saveandclose](https://f.cloud.github.com/assets/2374703/1281927/e14f7ecc-2f6a-11e3-988f-4b88b8e09e39.png)

**Comment by brightbold** [comment] 2013-10-07 17:04
Thanks Shaners! Something like that would definitely help. Although we'd need to think both about narrower screens (I tend to keep my browser windows about 75% width so I can look at two things at once) and longer task titles. Here's a screenshot of my first few dailies - if you stuck the button up there I'd have no room for text!
![task-screenshot](https://f.cloud.github.com/assets/405068/1282327/a9dc4536-2f71-11e3-94b2-308c2bdc2f19.png)

I take it it's easier to add a second copy of the button than to modify the pencil so it does the same thing? Because the button is an actual submit button?

**Comment by Shaners** [comment] 2013-10-07 17:53
Well I'm just not sure that it'd be obvious to other people that clicking the pencil icon a second time saves the changes so even if that was in place some might seek out the save button at the bottom. Which is kind of a pain if your changes are in the top 50% of the edit panel. It also would only appear when editing the task since you don't need to save otherwise so longer task names aren't that big of an issue:
![saveandclose002](https://f.cloud.github.com/assets/2374703/1282693/c7cd266c-2f78-11e3-9ff9-d096f9553edd.png)

**Comment by gwillen** [comment] 2013-10-07 17:54
Putting a save button at the top is not a bad idea. But I think the key action item here is a change to the behavior of the pencil icon.

It really violates the principle of least surprise to have a button that hides the edits I just made, but _neither_ saves nor cancels them. I would prefer that it save, because why wouldn't it? But if not, it should cancel, and put up a dialog warning that it will cancel. (As a third option, it could disappear or become disabled when in edit mode. Just so long as it doesn't do what it does now, "close while leaving edits silently pending so they'll be lost later.")

**Comment by Shaners** [comment] 2013-10-07 18:07
Yea good points. It kind of acts like a minimization thingy right now. Maybe it should become an x so you can cancel out the changes you've made (with warning dialog) if you'd made a mistake in your edits.

**Comment by lemoness** [comment] 2013-10-07 20:31
Actually, my biggest issue with this is that when you uncheck a tag, it leaves that tag without automatically saving and closing, and so you have to hunt around for it to click save-and-close. Automatic saving would probably help this.

**Comment by Shaners** [comment] 2013-10-07 21:19
Or halting the filtering until you actually save the changes.

**Comment by lefnire** [comment] 2013-10-08 22:09
I vote just have the edit pencil save, it's simple enough. I understand the
arguments on this thread and agree re: the surprise (I fell victim myself
once or twice, and I created the thing)

**Comment by brightbold** [comment] 2013-10-09 02:53
Haha, Tyler!
Yeah, that would be great.

**Comment by wc8** [comment] 2013-10-09 14:38
Pencil Save: add mouseover "Save" text
or Replace Pencil with Save icon (eg. the little Disk icon)

Either way, I'd vote to also have an X icon to cancel the changes. Sometimes I'm glad I can back away from a change I started.

**Comment by filkaris** [comment] 2013-11-13 20:19
Hey guys, I was thinking that sometimes (when you have a LOT of tags)
the save button is waaaay down, and is not convenient for small changes (let's say in the title of a task).

I have added a button which looks like this.
![screenshot](https://f.cloud.github.com/assets/1624978/1535211/495a1016-4ca0-11e3-952b-f5c3a6c91e1b.png)

It's not functional yet, but the front-end is ready :)
Should I complete it and do a pull request? Or should I check how popular it is somehow?

**Comment by gwillen** [comment] 2013-11-13 20:21
+1 to adding the upper save button; the position can be tweaked later, but it seems like a win to have it in some form regardless. (Keeping in mind that I am not a developer on this project and can't speak for them. :-)

**Comment by lefnire** [comment] 2013-11-13 22:02
what about using that tiny [save icon](http://fontawesome.io/icon/floppy-o/) from FontAwesome? Right up next to the other lil' icons. I've been meaning to introduce FA to habit for an age, all it's icon goodies.

**Comment by brightbold** [comment] 2013-11-13 22:08
Yes! That's an elegant solution.

**Comment by filkaris** [comment] 2013-11-14 12:45
I don't know how to add FA into the habitrpg installation, I'm completely new with node.js :)

What I can do (for now) is use the "check" icon (icon-ok) that is already in the bootstrap.

Also, I noticed that clicking the pencil and the cancel button does the same thing...
It hides/shows the editing area. 
So cancel is NOT really "cancel", since it should Cancel all the changes the user made.

I'm going to try and make it so that cancel really cancels, and the new OK icon saves changes :)

**Comment by paglias** [comment] 2013-11-14 13:51
#1814 for @phil230 pull request which adds the save icon from bootstrap.

@phil230 for the cancel I'll see to fix it in the next few days

**Comment by deilann** [comment] 2014-02-11 08:39
Closing this -- I do believe it's possible to save from the top now.

**Closed as completed by deilann** 2014-02-11 08:39 UTC
Labels: status: issue: suggestion-discussion, priority: minor
