### ISSUE TITLE
Keep getting this error in chrome and safari when "Challenges" is opened

### ISSUE THREAD

**Issue by CarmenLumiere** [HabitRPG/habitica#2906] opened 2014-02-20 07:10 UTC
Please reload, "Error [object Object]" (see Chrome console for more details).

**Comment by quin-jay** [comment] 2014-02-20 07:59
This looks to be a duplicate of #2903. @CarmenLumiere, I suggest you +1 the issue over there as well.

**Closed as completed** 2014-02-20 17:18 UTC
