### ISSUE TITLE
Error when ending challenge, now can't delete tasks

### ISSUE THREAD

**Issue by hattieshoe** [HabitRPG/habitica#2877] opened 2014-02-18 01:44 UTC
I ended the "Read a Tome of Compelling Significance" challenge this morning. I chose a winner and got an error (503?). I refreshed the Challenges page and the challenge is gone. However, the habit associated with the challenge is still on my tasks page, does not show the "challenge has ended" indicator, and cannot be deleted. The 3 to-dos from the challenge are also still in my completed tasks list.

This happened at the end of January with another challenge of mine, but appeared to resolve itself within about an hour. This time it's been about 11.5 hours and I haven't seen it resolve yet, so thought I'd better mention it.

Of most concern to me is that there may now be a high number of users with undeletable tasks from the challenge. If it resolves itself, I'll post a followup.

_edit by admin:_
# What to do if you experience this bug:

Please see the wiki page [Challenges &gt; Deleting a Challenge Task](http://habitrpg.wikia.com/wiki/Challenges#Deleting_a_Challenge_Task) for a sequence of steps you can follow to remove the tasks.
##

**Comment by casicastiel** [comment] 2014-02-18 15:44
I can confirm that the habit and to-dos still act as if the challenge is open. I can't find the challenge on the Challenges page to leave it, though.

**Comment by deilann** [comment] 2014-02-18 15:48
Same. Doesnt seem to be reverting itself this time.
casicastiel notifications@github.com wrote:

> I can confirm that the habit and to-dos still act as if the challenge is open. I can't find the challenge on the Challenges page to leave it, though.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/HabitRPG/habitrpg/issues/2877#issuecomment-35396892

I can confirm that the habit and to-dos still act as if the challenge is open. I can't find the challenge on the Challenges page to leave it, though.

**Comment by hattieshoe** [comment] 2014-02-18 16:26
Could it possibly be related to the large number of people in the challenge? This one had over 1150 participants, and one that I closed at the end of January had around 300. Not sure if that was the one with the problem though, as the issue I made then has been closed.

**Comment by deilann** [comment] 2014-02-18 16:31
You can actually grab closed tickets, @hattieshoe! I may be able to look in
a second.

**Comment by hattieshoe** [comment] 2014-02-18 17:14
Oh yup @deilann, I just searched and found it. And it was indeed the Conquer Your Castle Clutter challenge, with 300+ participants. Two instances does not a pattern make, I know, but it makes me wonder.

**Comment by deilann** [comment] 2014-02-18 17:15
In this case, I think it either makes a pattern of overly large challenges,
or challenges started by hattieshoe.

**Comment by hattieshoe** [comment] 2014-02-18 17:17
I hope it's the former and not the latter! However, I've created and closed at least 8 to 10 challenges besides those, and not had a problem with them.

I guess the only bright side is that there wasn't a daily for this challenge.

**Comment by lefnire** [comment] 2014-02-18 18:47
The size of the challenge will have been the problem, it would have maxed our Dyno's memory and crashed the server. I'm going to work on fixing this before closing our own "Spread the Word Challenge", since we have even more. In the mean time, I have a strange temp fix in where if you score a broken-challenge task (in your tasks) and sync/refresh, it should become deletable. So click + on a broken habit for instance. Let me know if this doesn't work

**Comment by deilann** [comment] 2014-02-18 18:49
Yay it worked! However, naturally, I got a 305% crit bonus on it.

**Comment by hattieshoe** [comment] 2014-02-18 19:26
Thanks, that worked for me as well, and I'll go announce it in the Tavern so others can do it too. One small concern: When the "broken challenge link" came up after refreshing, it said the challenge had been deleted -- no winner was listed. So the winner I picked may not have gotten the gems or an achievement listing. I don't really care about the gems disappearing, but the winner not winning is kind of a bummer (if that person is still using Habit).

**Comment by heyheyitsrey** [comment] 2014-02-19 16:17
#2763 - I had the same issue.

**Comment by marcgenesis** [comment] 2014-02-24 01:19
I'm shooting something on the fly here without looking through the code, but I'm guessing when a challenge is closed, it's automatically looking at every user in the challenge and sending the "end this challenge" flag?

Could this bug be fixed if we checked for ended challenges when a user log in, instead of sending the flags all at once when the challenge ends?

**Comment by lefnire** [comment] 2014-02-24 01:32
@marcgenesis there's a simpler solution, one of two options:
1. Use mongoose query streams + `batchSize`. @colegleason has experience with this, I'm gonna dive in in the near future.
2. Once we move `users.tasks` to objects instead of arrays, we can pull only the necessary objects for update in a query using `$elemMatch`. This will cut back _substantially_ on db-loaded data, such that even 2k users won't be a burden. This is the _real_ solution, but may be a long ways out. 

I'm gonna assign this ticket to me, I know the solution and I just need to do it. Expect a fix by the time we close STWC

**Comment by Sulfirh** [comment] 2014-04-02 06:09
Hi there,
I just had the same problem on the Clean the Dungeon challenge. Clicking the task made "Broken challenge link" appear (so I can remove all the tasks), but I just wonder if the winner got his achievement.

**Comment by veghita** [comment] 2014-06-23 10:54
I'm trying to pick a winner for my challenge All work and no play, but it keeps showing the error that the string is too long, and my challenge still appears.

**Comment by deilann** [comment] 2014-06-23 19:59
You're just going to have to try from time to time. You may still get an
error when the challenge ends, but eventually it will disappear.

**Comment by veghita** [comment] 2014-06-23 20:14
Thanks!

El 23/06/2014 21:59, deilann notifications@github.com escribió:
You're just going to have to try from time to time. You may still get an
error when the challenge ends, but eventually it will disappear.

On Mon, Jun 23, 2014 at 3:55 AM, veghita notifications@github.com wrote:

> I'm trying to pick a winner for my challenge All work and no play, but it
> keeps showing the error that the string is too long, and my challenge still
> appears.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/HabitRPG/habitrpg/issues/2877#issuecomment-46829838.

---

**Comment by lemoness** [comment] 2014-08-05 22:25
I recently attempted to end a large Challenge (over 550 participants). No matter what I tried, clicking "End" and then attempting to award a winner resulted in the following error:
![screen shot 2014-08-04 at 1 39 56 pm](https://cloud.githubusercontent.com/assets/3494081/3819735/3a9e84c0-1cee-11e4-9ba1-c3894769bbf6.png)

I tried multiple times over the course of multiple days, and the Challenge was at no point removed. Eventually, I manually awarded gems to the winner and deleted the Challenge, which produced an application error, but successfully removed the Challenge.

@lefnire reporting here instead of filing a new bug like you asked, since I notice that most of the recent reports are of the can't-pick-winner variety; hope that's okay.

**Comment by FireFoxr479** [comment] 2015-04-04 04:15
Hi, I tried picking a winner for the challenge "Stay Groomed" (260 participants) and ending the challenge, and I got this error: 
![screen shot 2015-04-04 at 12 04 24 am](https://cloud.githubusercontent.com/assets/11793365/6991395/61c79da0-da5f-11e4-9ce1-36846fc62984.png)

**Comment by Alys** [comment] 2015-04-04 04:41
@FireFoxr479  Please tell me who the winner should be. I'll assign the gem(s) to them and delete the challenge. Please also give me the URL you see when you're looking at the challenge (it will have a long string of random letters and numbers in it).

**Comment by FireFoxr479** [comment] 2015-04-04 04:44
Reagan Wolf should be the winner. The challenge url is
https://habitrpg.com/#/options/groups/challenges/eb821673-f44b-4176-aa65-93f1fc039732

​

**Comment by Alys** [comment] 2015-04-04 04:59
@FireFoxr479 :  I have given one gem to Reagan Wolf (cd9a9791-e3b1-4e46-bfa5-f7eba6986bb1) and deleted the challenge. Sorry it caused you trouble!

**Comment by FireFoxr479** [comment] 2015-04-04 05:00
No worries. Thanks so much!

**Comment by MaidM** [comment] 2015-06-12 09:52
Tried to remove habits from a challenge that I can only assume ended, since I can't find it anymore in the challenges list.  Tried the 'solution' (not a very good one) of doing the habit task to see if that 'tricks' the megaphone into showing broken - which it doesn't.  I finally was able to delete the habit by going in via my tablet app and deleting the habit, but please please fix this properly.  Why not just allow users to delete ANY challenge-related tasks, but if they do, ask if they want to be removed from the challenge?

Challenge was tracking trash.

**Comment by Alys** [comment] 2016-01-13 20:19
I'm closing this because we have it reported in https://github.com/HabitRPG/habitrpg/issues/2763

**Closed as completed by Alys** 2016-01-13 20:19 UTC
Labels: section: Challenges
