### ISSUE TITLE
Mouseover popup for eggs remains even when not moused over

### ISSUE THREAD

**Issue by kamni** [HabitRPG/habitica#7521] opened 2016-05-27 15:51 UTC
This may have a similar cause as #7517

General Info
- UUID: fedc44cb-088a-4bc8-8f4f-3e6a1882f042
- Browser: FF
- OS: OS X 10.11.4
### Description

When applying a hatching potion to an egg, the mouseover popup does not go away after the potion has been applied:

<img width="689" alt="screen shot 2016-05-27 at 9 36 18 am" src="https://cloud.githubusercontent.com/assets/101778/15613371/2c6d190e-2401-11e6-9505-844f92c80c25.png">

This does not happen when simply mousing over the egg, and then immediately mousing off. It only stays up when applying a hatching potion.
#### Console Errors

None; unrelated warnings only.

**Comment by JenniferMartin** [comment] 2016-05-28 15:16
Just wanted to note that this is not new behavior with the recent update--it's been occurring for me for as far back as I remember (can't remember if it was from the beginning or not). I use Firefox on Windows 7. It had never occurred to me to bug it, though.

**Comment by keysmashes** [comment] 2016-05-28 23:19
I'm on Ubuntu 14.04 and can reproduce this in Firefox, although not Chrome.

**Comment by hairlessbear** [comment] 2016-05-29 01:48
I've had this issue in Chrome since I started using Habitica a year and a half ago. Happens on Windows and Linux. Usually happens inconsistently; seems to be caused by moving off of the item too quickly to be properly detected, but I'm not sure. 

EDIT: To be clear, this happens with any items (food, eggs, pets etc.), but doesn't happen very often.

**Comment by khipkin** [comment] 2016-08-25 15:28
@Alys I think this can also be closed because of the redesign.

**Comment by Alys** [comment] 2016-08-26 06:50
True. It's low priority and it will be made redundant by the upcoming website improvement project so I'm closing it.

**Closed as completed by Alys** 2016-08-26 06:50 UTC
Labels: priority: minor, help wanted
