### ISSUE TITLE
Tag number 8 and 9 are linked

### ISSUE THREAD

**Issue by ShadowBB** [HabitRPG/habitica#940] opened 2013-05-13 10:35 UTC
I have 9 tags:
Morning Work Evening EvE Heimr Marriage Huis Computer Organisaties

Whenever I click "Computer" it also activates "Organisaties" (and the other way around.)

This happens both when I click on the filter itself and when I go into the tasks to modify the tags that are associated with them.

I use opera 12.15

Thanks.

**Comment by ShadowBB** [comment] 2013-05-14 08:15
My user id is:
d05d5b37-a001-47bf-bf00-c5cafa3cd332

Additional information:

I now have 10 tags (added an "other" tag) the bug persists but the 10th tag is not effected. The bug stays with the 8 and 9th tag.

I also tried Firefox 16.0.1. The bug is present there as well. So it's not the browser I think.

Some additional details:
- When I deactivate one the other deactivates as well.
- It happens consistently every time.
- It filters correctly and only shows objects that have both tags (so it's not just cosmetic.)

**Comment by nchezrony** [comment] 2013-06-07 01:36
This is happening for me as well, but not just for the 8th and 9th tag.

**Comment by paglias** [comment] 2013-09-09 17:41
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!

**Comment by ShadowBB** [comment] 2013-10-23 13:36
Hey, this bug is still occurring. How do I reopen this bug?

**Comment by paglias** [comment] 2013-10-23 13:39
@ShadowBB reopening it, by  saying they are linked do you mean that one tag's tasks are shown when the other one is selected or also that in the site the 9th and 8th tags are highlighted at the same time like if you clicked both?

**Comment by ShadowBB** [comment] 2013-10-23 14:07
The second one

Both tags are highlighted when I click only 1 of them.
Or when they are already highlighted:
Both tags are un-highlighted when I click only 1 of them.

They also actually filter "correctly", so only tasks (Etc.) that have both these tags are shown... however that always happens because I can't give a task only 1 of these tags... if I give a task 1 of these tags he automatically receives the other tag as well.

**Comment by paglias** [comment] 2013-10-23 14:43
Probably you have already tried this but in case you didn't, what happens if you delete and recreate both tags?

**Comment by elendraug** [comment] 2013-12-17 16:30
This just happened to me as well. I added three custom tag categories and went to edit a habit and all three boxes checked. Refreshing the page fixed the problem.

Chrome 31.0.1650.57 m

**Comment by startmyquest** [comment] 2013-12-22 20:24
Yep, getting the same issue for any new tags I create and if immediately open a task to assign them. Will assign and tick all boxes for any recently created ones. Hitting refresh on browser, does seem to fix it.

**Comment by nimbuschick** [comment] 2013-12-31 18:00
Same thing. Any tags I create (meaning not the morning, afternoon, night ones that are default) cannot be selected or deselected without the same happening to each other one.

**Comment by tamiveldura** [comment] 2014-01-02 03:33
Ditto with this issue, only refreshing doesn't do any good.

Any time I create new tags they're linked together, to the point of renaming themselves the most recent tag created after navigating away from the page.

Does not appear to affect tags auto-created by accepting challenges.

**Comment by lefnire** [comment] 2014-01-02 20:31
Confirmed issue, refreshing always fixes in my testing

**Comment by francehopper** [comment] 2014-01-07 23:32
Ditto here as well. I also have a tag that is overwriting the name of another tag. The first tag called "Library" should be called "Kickstarter". Try to rename it and it just goes right back to Library.
![screen shot 2014-01-08 at 10 30 38 am](https://f.cloud.github.com/assets/6091484/1864451/c378d2c8-77f3-11e3-9633-d15525d9a666.png)
![screen shot 2014-01-08 at 10 30 28 am](https://f.cloud.github.com/assets/6091484/1864452/c383aee6-77f3-11e3-9a87-d1be9ed75913.png)

**Comment by lefnire** [comment] 2014-01-08 00:24
https://github.com/HabitRPG/habitrpg-shared/commit/84637ad336eecb4e74ad245438c820270d6d7bc3

**Closed as completed by lefnire** 2014-01-08 00:24 UTC
Labels: status: issue: needs investigation
