### ISSUE TITLE
Instant death mid-day.

### ISSUE THREAD

**Issue by gabichicaloca** [HabitRPG/habitica#3516] opened 2014-05-22 21:42 UTC
Today I logged into my habit account on my computer and was killed. What I found unusual is that I had been logged on for a few minutes and was not killed as soon as I logged. Not that I should have been because I had logged on the night before to check my dailies on my iPhone and then again after midnight to see how much damage had been dealt to the boss in the challenge I am currently in. I am also concerned about the other person in my party who was undoubtedly hit by the same attack that killed me.

**Comment by deilann** [comment] 2014-05-22 21:44
Can you go to your party page, refresh, and verify that you are the one who
dealt the damage?

**Comment by gabichicaloca** [comment] 2014-05-23 02:27
Yes, it was me.

**Comment by gabichicaloca** [comment] 2014-05-23 05:21
The same thing has just happened

**Comment by Alys** [comment] 2015-07-18 22:54
@gabichicaloca I'm sorry we never got back to you with an explanation of this problem. It might have been caused by data not being synced between your browser and the server as soon as it should have been. I'm closing this now since it's an old report, but if it happens again, please tell us.

**Closed as completed by Alys** 2015-07-18 22:54 UTC
