### ISSUE TITLE
Items did not clear from previous day

### ISSUE THREAD

**Issue by marphod** [HabitRPG/habitica#1140] opened 2013-06-05 23:37 UTC
All of my Dailies are marked as 'completed', even though I hadn't logged in for around 26 hours.

**Comment by jftalarico** [comment] 2013-06-06 03:28
This has happened to me as well two days in a row now. Not only that but after it does reset it drops me back to the previous level and I loose a ton of HP. Frustrating.

**Comment by StanLindsey** [comment] 2013-06-06 09:46
Dupe of #1107 - continue conversation there.

**Closed as completed by StanLindsey** 2013-06-06 09:46 UTC
