### ISSUE TITLE
TRex Mount Images Much Wider Than Others

### ISSUE THREAD

**Issue by deilann** [HabitRPG/habitica#4803] opened 2015-03-05 13:14 UTC
![](http://i.snag.gy/v87U0.jpg)

The TRex Mount images are very wide... which causes them to take up two rows in my browser, full screen, at a 1366x768 resolution in Chrome on Windows 7.

**Comment by crookedneighbor** [comment] 2015-03-07 03:22
Related- We discussed reworking the way mounts are displayed on the page to only show the head of the image: #4618

**Comment by SpenserJ** [comment] 2015-07-21 03:09
This can be closed as a duplicate of #4618, and the T-rex specific issue seems to have been fixed in 7c5b2457be111c99259a6f776cda37dea63acc47

**Closed as completed** 2015-07-21 12:53 UTC
Labels: priority: minor
