### ISSUE TITLE
Experience increases too quickly

### ISSUE THREAD

**Issue by tsouthcotte** [HabitRPG/habitica#622] opened 2013-03-08 21:19 UTC
I was level 9 last night, and am about to be level 11. I have only done a few tasks, but my EXP bar is at 260, and even green tasks are netting 25 or more EXP.

Forgive me if this is already a thread. I couldn't find it.

**Comment by wc8** [comment] 2013-03-08 21:26
By tasks do you mean daily tasks? 
This seems related to #598.

**Comment by tsouthcotte** [comment] 2013-03-08 21:44
No, it is every item I click. Daily, to do, habits. Each give 20 or more EXP even when green. Since I only need 280 to level, it is just flying through.

**Comment by tsouthcotte** [comment] 2013-03-08 21:50
The gold seems to be on track. It only goes up by around 1 or 2 gold per daily. Only the experience is out of sync.

Also, i butchered that title, and for that I am ashamed.

**Comment by lefnire** [comment] 2013-03-09 00:07
Actually agree, I'm finding the new system a tad too easy - don't think I'll die unless I step away from Habit for a week. We'll look into this

**Comment by cleave29** [comment] 2013-03-09 08:05
I'm having the same thing happen to me.

**Comment by lefnire** [comment] 2013-03-09 23:41
bumping this up to crit, tons of people reporting via email and KS - new algos too easy

**Comment by wildcate** [comment] 2013-03-11 14:19
I remember reading somewhere that reaching lv. 100 for an average user should take about 400 days... which would mean a new level every 4 days. If the intention is to make leveling progressively harder, that would mean very very fast leveling during the lower levels, maybe that is the cause?
If you are aiming for an average-user-leveling-time, how about going for "current level in days"? Would that work for folks?

**Comment by lefnire** [comment] 2013-03-11 14:26
Naw, don't think we'll be doing level as days - want them to earn it by completing tasks - and be able to earn more points by challenging themselves more. Our algos just need to be tweaked again.

**Comment by wildcate** [comment] 2013-03-11 15:26
I didn't mean to say you should fix the levels to the amount of days spent! They should of course be linked to completed tasks. I had just gotten the impression (from said bit about 400 days for 100 levels) that you were aiming for some sort of "leveling speed" based on the average user when making the algorithms.

**Comment by lefnire** [comment] 2013-03-12 14:08
temp fix: https://github.com/lefnire/habitrpg/commit/bb57eddec136063e5ba12ec1fb8f8c2d163a4c74

**Comment by erreerre** [comment] 2013-03-12 15:55
Hi Tyler, you have closed this issue but it is still leveling way too fast... Maybe you have closed just my comment just to keep open the general issue (perfectly fine with it). I have just gained +24XP for a daily task I do every day. In fact I'm leveling up everyday (yesterday I was level 7, right now I am level 9). I don't think I can die in this game... :/

Thanks a lot for all the effort!!

**Comment by lefnire** [comment] 2013-03-12 16:23
I just closed #641 since it's a duplicate of this ticket, which is still open. Just keeping the convo centralized. I reduced exp gain by 1/2 as a temporary workaround until @MrConcept gets back from holiday, then we'll take another stab at this.

**Comment by erreerre** [comment] 2013-03-12 16:31
Ok! Thank you again!

**Comment by wc8** [comment] 2013-03-12 19:00
On a related note: I'm dying too quickly. I think it should take _at least_ a 3 of days of major failure before I die, not missing half my daily tasks one day to be 1 pt away from death.

**Comment by lefnire** [comment] 2013-03-12 20:00
Hmm, I haven't actually heard that complaint yet. IIRC your daily list was
pretty long, this might be another vote for the normalization convo?

**Comment by wc8** [comment] 2013-03-12 21:25
Maybe it's leftover high settings from the priority multiplier which is now difficulty. If I reduce the difficulty level for some of my tasks, that may straighten it out. 

P.S. For reference: #325 difficulty normalization

**Comment by wildcate** [comment] 2013-03-14 17:11
@wc8 Maybe you had the same effect that I had, the tab refreshed and deducted the hp again? Did something you checked become unchecked again?

**Comment by wc8** [comment] 2013-03-14 20:43
I'm earning 25 XP for completing some of my tasks. I imagine there are tasks with a correspondingly high HP loss. It just takes a few to kill me. So it's more about the value of each task (after multiplying/adding days missed and difficulty) than about an error in the game. [Update: the side note of #651 does seem related to my situation.]

**Comment by wildcate** [comment] 2013-03-21 14:01
Have the algos been changed in the meantime? I still feel that I'm leveling quite fast, even though I only do a few habits and dailies per day (since my to-do items are sorta large-ish and get stalled again and again). I think it took me less than three days to get from level 10 to 11... that seems very fast to me, especially since it feels like the gold gain is not so big in comparison.

**Comment by lefnire** [comment] 2013-04-04 19:57
demoted to `important`, since stopgap is working fine

**Comment by paglias** [comment] 2013-09-09 15:40
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!

**Closed as completed by paglias** 2013-09-09 15:40 UTC
Labels: status: issue: suggestion-discussion, priority: important
