### ISSUE TITLE
Bug: 869/850 XP

### ISSUE THREAD

**Issue by Rosenblad** [HabitRPG/habitica#8654] opened 2017-04-05 14:50 UTC
[//]: # (Before logging this issue, look through common problems at https://github.com/HabitRPG/habitrpg/issues If you find your issue there, read at least the first post to see if there is a workaround for you)

[//]: # (Github is primarily used for reporting bugs. If you have a feature request, use "Help > Request a Feature" so that the feature request can be vetted by the larger Habitica community)

[//]: # (To report a bug in one of the mobile apps, please report it in the correct repository. Android: https://github.com/HabitRPG/habitrpg-android, iOS: https://github.com/HabitRPG/habitrpg-ios)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitrpg/issues/2760)

[//]: # (Fill out relevant information - UUID is found in Settings -> API)
General Info
  * UUID: ce8e50d9-bfc3-4c3e-8451-1e4111a28488
  * Browser: Chrome
  * OS: osx

http://whatsmybrowser.org/b/E9CCSLE

### Description
[//]: # (Describe bug in detail here. Include pictures if helpful.)

https://i.gyazo.com/2434b8f9c2e1c60497535f9981a78406.png

I think the picture explains the problem pretty well. I noticed it after logging in and I'm guessing it has something to do with the fact that my party finished the laundromancer quest while I was offline.

**Comment by SabreCat** [comment] 2017-04-05 14:51
Duplicate of #2433. You'll level up next time you check off a task!

**Closed as completed by SabreCat** 2017-04-05 14:51 UTC

**Comment by SabreCat** [comment] 2017-04-05 14:54
We have a guild within Habitica for faster reporting of problems: [Report a Bug](https://habitica.com/#/options/groups/guilds/a29da26b-37de-4a71-b0c6-48e72a900dac). You can get to it from Help > Report a Bug from the website's menu (or Guilds > Report a Bug from the mobile app). The only time you'd need to log an issue in GitHub is if it's a complex problem, and then a moderator would advise you of that.
