### ISSUE TITLE
Punctuation following an email address in Markdown fields causes it not to be parsed as email

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#12437] opened 2020-08-03 18:42 UTC
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)
### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)

Ordinarily, an email address typed in chat, private messages, etc. is parsed and rendered as a `mailto:` link. However, if you follow it with punctuation, like a period or a hyphen used to make a dash, the email is not understood as such and gets a partial highlight meant to call out usernames:

![image](https://user-images.githubusercontent.com/4501321/89215948-24a42c00-d58f-11ea-8a04-92da0605e5ff.png)

#### Console Errors
[//]: # (Include any JavaScript console errors here.)

None.

**Comment by mbroshi** [comment] 2020-08-19 17:15
I have never contributed before, but I would be interested in taking a crack at this one. My guess is that the issue is a regex gone haywire, which would be good for a first-timer like myself.

**Comment by paglias** [comment] 2020-08-19 17:36
thanks @mbroshi ! I've marked the issue as in progress for you, let us know if you have any question but it's very likely the issue is indeed a regex one

**Comment by mbroshi** [comment] 2020-08-20 04:47
Nothing is ever simple! I've found the root cause in the isLinkOrEmail function in the habitica-markdown project. That function has some surprising behavior:
"www.google.com@user" is considered the URL link http://www.google.com followed by an @user mention
but  
"http://www.google.com@user" is consider the URL link http://www.google.com@user with no @ mention
That behavior is enforced by unit tests, so presumably it's desirable (although, I find it rather confusing). It makes the fix a little tricky.

In any case, how do I navigate closing the issue here and reopening it in the habitica-markdown project? I'm a total noob.

**Comment by paglias** [comment] 2020-08-20 10:24
@mbroshi I'd keep the issue open here but you can open a new one in the habitica-markdown repo here https://github.com/HabitRPG/habitica-markdown/issues/new or if you have a fix ready you can make a pr directly without opening an issue

**Closed as completed** 2020-09-03 15:00 UTC
Labels: priority: minor, status: issue: in progress, section: Tavern Chat, section: Messages
