### ISSUE TITLE
P1 BUG - Bad sync between mobile and Desktop version on EVERYTHING and all aspects 

### ISSUE THREAD

**Issue by hahansen** [HabitRPG/habitica#5498] opened 2015-06-26 16:06 UTC
Okay let me see if I can break this down: this is for my account associated with either hhansen@four-keys.come or hollyahansen@gmail.com - my background is web product management - so feel free to ask me if you need any clarifications.

The problems seemed to originate when I died in a Quest and first found out by looking on my mobile app

For Desktop I use Google Chrome
My Mobile is IOS

The first problems that showed up: ABOUT A WEEK AGO

My avatar:
MOBILE: Is naked, and it looks like I am floating - only the pet showing
DESKTOP: My avatar reflects no changes - I still look the same

My inventory:
MOBILE - I have only basic gear all of my paid for and earned equipment is gone
DESKTOP - All my gear is still intact

My To-Do. Dailies Tasks  - This issue started about 24-48 hours ago
MOBILE : all of my Lists are intact - I can still mark them
DESKTOP - all but one of my dailies and one of my to-dos is GONE  not showing

As you can see there are some serious P1 issues - I say this because I have to use 2 devices to get HABIT RPG to work at all

Please help!

**Comment by Alys** [comment] 2015-06-26 23:14
@hahansen I'm sorry you've had so many problems!

For _"MOBILE: Is naked, and it looks like I am floating - only the pet showing"_ -- Problems like that are typically caused by images not being received from the server and they're usually very temporary. Is that still happening?

_"MOBILE - I have only basic gear all of my paid for and earned equipment is gone"_ -- That might be the same problem or it could be a bug. Is it still happening?

Those two errors are likely to have been caused by some server overload problems we've been having lately. We believe we've fixed them now.

_"DESKTOP - all but one of my dailies and one of my to-dos is GONE not showing"_ -- When that happens while the tasks still exist (as yours do since you can see them in mobile), it's always because a tag or search filter is enabled. Please click on the "clear" button next to your tags, even if it looks like no tags are showing, and also removed all text from the search box (just above the Rewards column). Does that make your tasks appear again?

**Comment by hahansen** [comment] 2015-06-29 04:47
Hi Alys,
Thanks for reaching out - I decided to wait a couple of days

I did the clear filter thing - and that worked so all of my tasks are showing both on my desktop and Mobile (YEAH) 

But UNFORTUNATELY - the other issues are still showing up. 
Is there a way to shadow my account see why these bugs are going on? 

Any help appreciated!
Holly

**Comment by Alys** [comment] 2015-06-29 05:37
When you have bugs that you want help with, please respond promptly to our questions. Sometimes information related to the bugs is only available to us for a limited time.

Please provide screenshots of your avatar and your equipment screens from both desktop and mobile. We need to see which pieces of gear are not available on mobile. Also tell us your user ID. If you don't know how to find it, on the website go to Help -> Report a Bug. Step 6 in the instructions will tell you how.

Note that the latest equipment, pets, mounts, and other images released in HabitRPG do not always show up immediately in the apps because app changes have to be approved by Google or Apple. This can take days or weeks, especially for Apple. If you're aware that the missing equipment and mount have been added to HabitRPG recently (e.g., Armoire equipment or cuttlefish mount), then this would explain what you are seeing and you don't need to supply the screenshots or user ID. Please let us know if that's the case. The items will appear when the app update is approved.

**Comment by hahansen** [comment] 2015-06-29 15:37
Hi Alys, 
I waited based on what you said in your first response. Sorry if I misunderstood.
See Screenshots below 
my user id is cd45b8f9-4a58-4fb7-99c1-3ea4b5edc7bb 

The equipment missing from the mobile view was stuff earned from quests - Not the amoire or cuttle fish  (see screenshots) 
DESKTOP: 
![image](https://cloud.githubusercontent.com/assets/13067133/8411527/36648c54-1e39-11e5-9558-91d1d7524ed8.png)
![image](https://cloud.githubusercontent.com/assets/13067133/8411539/480cf752-1e39-11e5-874a-9044c9b35969.png)
![image](https://cloud.githubusercontent.com/assets/13067133/8411545/5647cd60-1e39-11e5-8c0b-4ec94e444f37.png)
![image](https://cloud.githubusercontent.com/assets/13067133/8411553/68a4f2a8-1e39-11e5-9e56-7cb1386193c9.png)

MOBILE: 
![img_5406](https://cloud.githubusercontent.com/assets/13067133/8411618/d61c99da-1e39-11e5-9036-5b99a4ccaf54.JPG)
![img_5407](https://cloud.githubusercontent.com/assets/13067133/8411623/db30ef70-1e39-11e5-87b7-876dc1ce5def.JPG)
![img_5408](https://cloud.githubusercontent.com/assets/13067133/8411649/f9fefdac-1e39-11e5-80f9-7405a9e75dda.JPG)

**Comment by crookedneighbor** [comment] 2015-06-29 23:05
Thanks for the screenshots @hahansen. I believe the egg basket mount _should_ be on the latest version of the iOS app. The most recent subscriber gear is not, but the green knight stuff should be. 

Can you tell me what version of the app you're using (You can find that by going to the menu and tapping About)? And if there are any updates in the App Store?

**Comment by Alys** [comment] 2015-06-29 23:19
@hahansen That missing equipment problem is reported in https://github.com/HabitRPG/habitrpg/issues/5129 and I've added a comment there about your example of it.

I'm going to close this issue now as a duplicate, but please do give us the information @crookedneighbor asked about, so that we can refer back to it when we're working on the other issue.

Also note that we are currently rewriting the mobile apps from scratch to make them native apps, which should improve performance and remove problems like this. In the meantime, you'll probably find that the website works well on your mobile browser, so you can use that for features that the app doesn't yet have or doesn't implement correctly.

**Closed as completed by Alys** 2015-06-29 23:19 UTC
