### ISSUE TITLE
XML Data export error

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica#12971] opened 2021-01-17 14:55 UTC
Report from Ceran:

> I tried to export my user date with the options in the settings, using the xml version, but it only gave me a white page with the error message
> 
> {"success":false,"error":"InternalServerError","message":"An unexpected error occurred."}
> 
> Checked, exporting the cvs habit history worked, but since I wanted my to-dos, not much use. Exporting the json file works too, but I don't know how to open that file to check contents.

Replicated by me.

Similar to (or the same as) previously fixed #12482 and #10100 

---

EDIT by Alys 2021-04-19

When this issue is fully fixed, the fix must include an update for the apidoc comments for the XML export route. Currently they say:
> `@api {get} /export/userdata.xml Export user data in XML format`
> `@apiName ExportUserDataXml`
> `@apiDescription This XML export feature is not currently working (https://github.com/HabitRPG/habitica/issues/10100).`

**Comment by habitrpguser** [comment] 2021-03-16 23:01
I just want to confirm this error. It is exactly the same for me.

**Comment by Alys** [comment] 2021-04-16 10:29
This happens for me too, and we have a report in RaB today.

**Comment by Helcostr** [comment] 2021-04-16 21:25
I will investigate to see if I can fix this issue.... I am pretty sure I can, but I will double check.

**Comment by Alys** [comment] 2021-04-17 08:58
@Helcostr Thank you!

**Comment by Helcostr** [comment] 2021-04-17 14:30
With a fresh account, XML exporting is fine. And since it's an InternalServerError, I don't have many hints to go off of.

Can anyone narrow this issue down?

I think my contribution here is to wrap this function in an error handler so that the error is more clear.

Edit:

There are tons of warning signs around to not leak stuff... I am not sure how best to handle error returning, and so I decided to kick the key issue down the road and have it always return xml, at the cost of obfuscating the bad key characters. (Assuming the issue is with a "uuid key" issue)

**Comment by Alys** [comment] 2021-04-19 08:59
@Helcostr There's nothing in Habitica's server logs for my failed attempt to export my data, so narrowing it down will be hard. :(

I like this partial fix you've done! That looks promising.

---

As a note for the future when (if) this issue is fully fixed, we should update the apidoc comments for the XML export route. Currently they say:
> `@api {get} /export/userdata.xml Export user data in XML format`
> `@apiName ExportUserDataXml`
> `@apiDescription This XML export feature is not currently working (https://github.com/HabitRPG/habitica/issues/10100).`

I've added a note to the top post about this.

**Comment by Alys** [comment] 2021-04-19 10:21
We're making progress!! There's a staging server that Habitica's staff and moderators have access to. Before I merged @Helcostr's partial fix for this issue (https://github.com/HabitRPG/habitica/pull/13181), the XML export was giving me an error there, just as it was on the production site. Now that the PR's fix has been deployed to staging, the export is working there!

As @Helcostr predicted, the exported file does have some obfuscated XML keys. I've copied the relevant sections below along with the matching json data from my account, straight out of Habitica's database.

From this we can see that the json keys that start with digits are producing invalid XML tags. That's predictable really since the [XML spec](https://www.w3.org/TR/REC-xml/) says "Disallowed initial characters for Names include digits, diacritics, the full stop and the hyphen." Before now we just didn't know where to start looking for the problem. :-/

I guess now we just need to work out how to best adjust those XML tags to make them meaningful. I did a quest internet search for ideas and one suggestion is to start a tag name with an underscore when the first character would otherwise be a digit. E.g., instead of `<1>true</1>` we could use `<_1>true</_1>`

There's other options, such as starting the tag with the parent's name. E.g., `<beard1>true</beard1>` if the offending tag is in the `<beard>` parent tag.

I like the idea of using an underscore though because it could easily be applied to any tag in the export. E.g., have a function that checks each tag name and adds an underscore if it starts with a digit, regardless of where in the xml tree the tag is.

Other opinions welcome of course!

The staff would need to make the final decision (@SabreCat )

@Helcostr Thank you for getting us this far!  I'll leave this issue marked as in progress for you in case you want to keep working on it once the desired fix is chosen.

```
<purchased>
	<hair>
		<base>
			<�>true</�>
			<�>true</�>
			[16 other lines like those]
		</base>

"purchased": {
	"hair": {
		"base": {
			"2": true,
			"4": true,
			"5": true,
			"6": true,
			"7": true,
			"8": true,
			"9": true,
			"10": true,
			"11": true,
			"12": true,
			"13": true,
			"14": true,
			"15": true,
			"16": true,
			"17": true,
			"18": true,
			"19": true,
			"20": true
		},
```


```
<purchased>
	<hair>
		<beard>
			<�>true</�>
			<�>true</�>
			<�>true</�>
		</beard>
		<mustache>
			<�>true</�>
			<�>true</�>
		</mustache>

"purchased": {
	"hair": {
		"beard": {
			"1": true,
			"2": true,
			"3": true
		},
		"mustache": {
			"1": true,
			"2": true
		}
	},
```

```
<purchased>
	<skin>
		<eb052b>true</eb052b>
		<f69922>true</f69922>
		<f5d70f>true</f5d70f>
		<�ff591>true</�ff591>
		<�b43f6>true</�b43f6>
		<d7a9f7>true</d7a9f7>
		<�00ed0>true</�00ed0>
		<rainbow>true</rainbow>
		[other lines that aren't obfuscated]

"purchased": {
	"skin": {
		"eb052b": true,
		"f69922": true,
		"f5d70f": true,
		"0ff591": true,
		"2b43f6": true,
		"d7a9f7": true,
		"800ed0": true,
		"rainbow": true,
		[etc]
```

**Comment by Helcostr** [comment] 2021-04-19 12:40
> As @Helcostr predicted, the exported file does have some obfuscated XML keys. I've copied the relevant sections below along with the matching json data from my account, straight out of Habitica's database.

Thanks to @benkelaar for tipping me off in issue #12482

> I like the idea of using an underscore though because it could easily be applied to any tag in the export. E.g., have a function that checks each tag name and adds an underscore if it starts with a digit, regardless of where in the xml tree the tag is.

I don't like this method, since this is a bandaid fix to the issue. I very much prefer an array export:
```
<purchased>
	<skin>eb052b</skin>
	<skin>f69922</skin>
	<skin>f5d70f</skin>
	<skin>0ff591</skin>
	<skin>2b43f6</skin>
	[etc]
```

is there internal documentation on what the `res.locals.user` object is, and are the skin (before json conversion) an object name/identifier that I can look for that tips me off that what i am looking at can start with a number? (before json conversion). I would like to not define this information in two place (maybe the skin object is full of `new Skin('eb052b')` values) (second place I must define this "pattern" is in the `xmlMarshaller`, and I want to make sure the code is not fixed in two places)

**Comment by Helcostr** [comment] 2021-04-19 15:13
> There's nothing in Habitica's server logs for my failed attempt to export my data, so narrowing it down will be hard.

@Alys currently all errors are being swallowed. is there a suggested way for me to properly handle thrown errors related to this xml export?

I was thinking of spitting the error verbosely at the user. But if there is an error tracking place that I can push the error to, that would be cool as well.

**Comment by Alys** [comment] 2021-04-22 12:48
The issue with changing it to work like this:
```
<purchased>
	<skin>eb052b</skin>
```
is that it would be a breaking change. Anyone who's already able to get an XML file because they don't own any of the offending items may already have code that processes the XML file using the `<skin> <eb052b>true</eb052b> ...` syntax, and their code would break if the XML format broke.

 It would also be inconsistent with how the other purchased items are formatted: 
 ```
    <purchased>
        <background>
            <flying_over_icy_steppes>true</flying_over_icy_steppes>
            <driving_a_sleigh>true</driving_a_sleigh>
        </background>
        <hair>
            <color>
                <candycane>true</candycane>
                <frost>true</frost>
                <winternight>true</winternight>
            </color>
```

Having said that though...
It isn't an especially good format, and XML exports may be still broken for a lot of players, so perhaps a case could be made for changing the format for the entire set of gem-purchased items. It's not something I can decide on though. :)

 @SabreCat what do you think?
 And do you have any preferences for how the XML errors should be handled - https://github.com/HabitRPG/habitica/issues/12971#issuecomment-822548460 ?

**Comment by Helcostr** [comment] 2021-04-22 13:29
I think we can MAYBE do both (lul) 🙃

v1 would use the `_` prefix

v2 would be an "array" export (consistent with other purchased items, no discrimination)

```
<purchased>
	<skin>eb052b</skin>
	<skin>f69922</skin>
	<skin>f5d70f</skin>
	<skin>0ff591</skin>
	<skin>2b43f6</skin>
       <background>flying_over_icy_steppes</background>
       <background>driving_a_sleigh</background>
```

I totally agree with the breaking changes part though XD... and I'm curious why it's in a `key:true` format 🤔

**Comment by Helcostr** [comment] 2021-08-30 05:18
Sure!

**Comment by SabreCat** [comment] 2021-08-31 21:21
Looking this over, I'm OK with making a breaking change here. In the rather unlikely event that somebody's built an application on top of the bad structure, they'll need to make a fix, but that seems like a fair price to pay for correcting this issue and making the structure more futureproof.

**Comment by SabreCat** [comment] 2021-11-09 21:31
@Helcostr is this still on your radar? Let us know how things are going!

**Comment by Helcostr** [comment] 2021-11-12 00:38
@SabreCat Lost the Habitica project from my computer, and I don't feel like starting over from scratch. I'll let someone take over for now.

**Comment by CuriousMagpie** [comment] 2021-11-12 16:13
Thanks for the update @Helcostr! I've opened this back up for someone else to tackle.

**Comment by johnl2102** [comment] 2022-03-23 03:22
Can I pick this up?

**Comment by CuriousMagpie** [comment] 2022-03-28 18:52
@johnl2102 I'm still waiting for your reply on the other issue you wanted--we only allow folks to work on one thing at a time.

**Comment by johnl2102** [comment] 2022-03-29 01:06
Sorry about that, can I take this issue and drop #13891 ? 😄

**Comment by CuriousMagpie** [comment] 2022-03-29 16:31
Sure thing! Let us know if you have any questions! You can also check out the [Aspiring Blacksmiths Guild](https://habitica.com/groups/guild/68d4a01e-db97-4786-8ee3-05d612c5af6f) in game.

**Comment by johnl2102** [comment] 2022-04-13 21:58
I've tried to recreate the issue using usernames with digits and hyphens on a locally built version of Habitica, but was unable to reproduce the error as the XML exports successfully. 

Is the issue fixed?

**Comment by Alys** [comment] 2022-04-14 05:29
@johnl2102 It still has the error described from https://github.com/HabitRPG/habitica/issues/12971#issuecomment-822357432 downwards, so a fix for that is still desired.

To make it easier to focus on the important comments, I've deleted some of the older ones that are no longer needed (confirmations of the original bug, and old posts about claiming and un-claiming this issue).

**Comment by SabreCat** [comment] 2022-05-16 19:13
Should be fixed by the linked PR. Closing until we hear otherwise!

**Closed as completed by SabreCat** 2022-05-16 19:13 UTC
Labels: priority: medium, section: Other
