### ISSUE TITLE
Task or Reward shows up as Habit and cannot be deleted

### ISSUE THREAD

**Issue by jkantz** [HabitRPG/habitica#3441] opened 2014-05-09 22:03 UTC
I added a new reward via the HabitRPG app on an android phone. The reward shows up in the habit list and cannot be deleted.

**Comment by deilann** [comment] 2014-05-09 22:08
Can you get me a screenshot?

**Comment by jkantz** [comment] 2014-05-09 22:12
Here you go.

**Comment by jkantz** [comment] 2014-05-09 22:13
![screenshot 2014-05-09 at 6 11 07 pm](https://cloud.githubusercontent.com/assets/49618/2933958/20a4fe58-d7c7-11e3-990c-1dc2fbf49a38.png)

**Comment by deilann** [comment] 2014-05-09 22:16
What happens if you try to delete it?

**Comment by jkantz** [comment] 2014-05-09 22:33
Nothing happens. The delete operation doesn't show any error so it appears
to succeed, but the reward is still there. I've tried deleting from web and
android. Both are silent fail.

**Comment by deilann** [comment] 2014-05-09 22:40
What happens if you "buy" it?

**Comment by wc8** [comment] 2014-05-10 11:24
@jkantz the database admin might need your User ID.

I've seen a couple github tickets in the past where, when the database admin checks the account, it turns out a task that was deleted wasn't fully cleared out.

**Comment by negue** [comment] 2014-09-05 08:51
Duplicate of #2443 . Or should we use this as "main" ticket?

**Comment by Alys** [comment] 2014-09-05 09:02
Good idea negue. There's lots of detail in this one so to heck with convention, I'll make this the main one. 

Refer to https://github.com/HabitRPG/habitrpg/issues/2443 for another instance of this issue and links to two others. None of those three have any significant extra information in them.

**Comment by Alys** [comment] 2014-09-08 19:40
This is also a duplicate of https://github.com/HabitRPG/habitrpg/issues/2334 and lefnire has assigned tags and commented in that one, so we'd better make that the main one.

**Closed as completed by Alys** 2014-09-08 19:40 UTC
