### ISSUE TITLE
Chrome Extension Syncing

### ISSUE THREAD

**Issue by cmock13** [HabitRPG/habitica#497] opened 2013-02-23 20:34 UTC
I am having issues allowing the Chrome extension to sync with the web app. I have copied my UID and my API token, but the "Browsing Productivity" task never creates itself.

What gives?

**Comment by ruddfawcett** [comment] 2013-02-23 20:35
https://github.com/lefnire/habitrpg-chrome

**Comment by cmock13** [comment] 2013-02-23 21:23
I understand how it works, but I can't get the website to sync.

**Comment by StanLindsey** [comment] 2013-02-23 21:51
Is the extension effecting you? E.g. are you losing health by using bad sites?

**Comment by cmock13** [comment] 2013-02-23 21:56
It's not affecting me at all.

**Comment by StanLindsey** [comment] 2013-02-23 21:59
Alright, can you answer these questions so I can help you =D

So you never get a message when you're on a unproductive website for a while. 

Does the chest icon have in chrome have a + or an ! over it on a vice or productive site?

If you click on the chest icon what is the status of "Work Hours"? 

In the settings menu what are the time & days of work hours set to?

Cheers!

**Comment by cmock13** [comment] 2013-02-23 22:08
No problem!

I don't get the message.

The website is a vice and it has an exclamation mark (!)

Work Hours is ON

Every day, always on.

**Comment by StanLindsey** [comment] 2013-02-23 22:34
Okay. So it means the application is timing you but I have a hunch that the API isn't firing. Go to Settings > Extensions in Chrome and click "developer mode", then click the _generated_background_page.html under HabitRPG extension. 

Now, when you've got 5/10 mins spare could you open up a vice-site and leave Chrome on it (Go do something productive in the real world hehe), and there may be a red-error line showing up in the background.js console window you just opened. Either way could you screenshot the window and upload it here for me to check. =D I've written loads of logs to the console so I should be able to follow the program till where it goes wrong.

**Comment by cmock13** [comment] 2013-02-23 22:41
Okay, I enabled developer mode and the sync started working. What do you think caused the signal failure?

**Comment by cmock13** [comment] 2013-02-23 22:49
I take that back. It updated once, but now it's stopped.

**Comment by Raytray** [comment] 2013-03-04 00:36
"Failed to load resource: the server responded with a status of 401 (Unauthorized) https://habitrpg.com/v1/users/15ac2585-0ac5-42ab-acb0-dac61b7d3399/tasks/productivity/down
"
I'm getting this. It never made the habit itself either, it is finding vice/good sites.

**Comment by a7h13f** [comment] 2013-03-04 07:12
I'm having the same issue.  It started after I installed Chrome on a new PC and let it sync my extensions.  Uninstalling / reinstalling the extension has not helped, nor has clearing my cache/cookies.  I'm getting these errors under the developer console window in Chrome:

Failed to load resource: the server responded with a status of 401 (Unauthorized) 

POST https://habitrpg.com/v1/users/cca33eb5-682f-4ad1-81ea-5a1002760ba8/tasks/productivity/down 401 (Unauthorized) background.js:2
send background.js:2
p.extend.ajax background.js:2
score background.js:252
(anonymous function) background.js:203
(anonymous function) background.js:237
chromeHidden.handleResponse

**Comment by lefnire** [comment] 2013-03-04 20:49
#571

**Comment by rixx** [comment] 2013-04-10 10:32
@cmock13 @a7h13f: Does it work by now? If not, you should maybe consider closing this Issue and opening another one over at https://github.com/lefnire/habitrpg-chrome.

**Comment by a7h13f** [comment] 2013-04-10 19:17
@rixx The issue is resolved, at least for me

**Comment by paglias** [comment] 2013-09-09 15:55
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!

**Closed as completed by paglias** 2013-09-09 15:55 UTC
Labels: priority: minor
