### ISSUE TITLE
Suggestion: add mentoring function 

### ISSUE THREAD

**Issue by Gallenkamp** [HabitRPG/habitica#6045] opened 2015-10-14 15:43 UTC
Hi there,

I a missing a feature I had in another habit RPG I wrote some years before: **mentoring** other people.

**Who is using this anyway?**
Many people that are using those gamified to do lists lack of self organization. That is why they try and use these tools. So its basically people haveing issues to stay organized. Some even need or have help with that.

**Who could need mentoring?**
- Children can learn responsabilty
- creative people can get their boring stuff done
- people with mental issues like ADHD can get guidance and supervision from social workers
- people who have been through or are in a burn out situation can have friends help them

The list goes on and on.

**Who could act as a mentor?**
- social workers
- parents
- friends
- teachers
- your boss?

**What is the benefit?**
It's still a game. People take it easy and dont freak out on overdue tasks. People start working together. Getting more stuff done. Misguided people can have help with priorities.

Although I cant provide any code (apart from php), I am willing to make this feature real.
Let me know what you think about it.

Cheers!

**Comment by hartalex** [comment] 2015-10-16 18:26
I'm thinking that the existing challenge system could be used in this regard.  

The mentor would be the challenge creator, and would be able to access the progress of the tasks of the users they are mentoring, without accessing all of the other users tasks which may be private.

**Comment by Alys** [comment] 2015-10-16 19:34
@Gallenkamp We use GitHub primarily for bug reports. Feature requests are collated in Trello so that all related requests can be easily reviewed together when planning future changes. Could you please go to Help -> Request a Feature (from Habitica's website) to make this suggestion? I'm going to close this issue now since it's not a bug, but I think it would be okay if you wanted to put a descriptive summary in Trello and then a link to this issue for the details.

@Vorgone That's a good point about challenges. Thank you.

**Closed as completed by Alys** 2015-10-16 19:34 UTC
