### ISSUE TITLE
Everything unclickable

### ISSUE THREAD

**Issue by JellyBean22** [HabitRPG/habitica#836] opened 2013-04-18 21:34 UTC
For me, as of the last half hour, everything on both beta and prod (and after multiple refreshes) is unclickable, mouseovers work but I can when I click anything (add new, mark todos done, edit habits, etc.) nothing happens. Also I am able to move them around too.

Chrome 28
Win 7

**Comment by lefnire** [comment] 2013-04-18 21:43
confusticate and bebother - it's definitely 251890f which is committed specifically to fix unclickability (https://github.com/lefnire/habitrpg/issues/769) - ironic. Follow the discussion on the actual commit message if you're interested technically, I'll be working on it in for the next while. Luckily I made a tag I can roll back to worst case scenario. 

Is anyone else experiencing this?

**Comment by savannahcookson** [comment] 2013-04-18 22:09
Not really good at coding but a site lover, I can confirm the problem.

**Comment by storian** [comment] 2013-04-18 22:23
This is affecting me too.  Both Chrome 26.0.1410.65 and FF 17.0.1, mac 10.6.8.

**Comment by octern** [comment] 2013-04-18 23:03
This has been happening to me all day. Mac 10.8.3, tried in Firefox 20.0 and current versions of Chrome and Safari. Tried numerous reloads and logging out and in (via Facebook). I can't complete tasks or habits, access the edit screen, or create new tasks. I can drag things to reorder them, but the new order isn't saved. The "Progress" link next to the "Todos" heading doesn't work, but the "iCal" link does. 

I actually was able to complete a task once today, but no other clicks registered after that. There was nothing obviously different about that time vs. all the other times I've loaded the page today.

**Comment by sgtorange** [comment] 2013-04-18 23:12
I am also experiencing this, unable to click to task options and check mark. the check mark blacks out but gives no exp nor gold and becomes undone when I refresh. it happened about 3 hrs ago for me.

**Comment by bobbyroberts99** [comment] 2013-04-18 23:14
Beta is working for me sporadically on Mac 10.8.2, Safari 6.0.3 but I 
often have to reload several times before a click scores.

Bob

**Comment by lefnire** [comment] 2013-04-18 23:18
Reverting a commit: https://github.com/lefnire/habitrpg/commit/08f7367e17d6f9f7a627b95acc87d76b08bd8c5a and restarting the server (it may take a bit before it's accessible). When it comes back on, can y'all try again?

**Comment by bobbyroberts99** [comment] 2013-04-18 23:44
Seems like its back up...

On beta and production, I can click a habit and have it score. The 
second time I click. Nothing. After I reload, I can click one time then 
nothing.

I can edit the habit (after a reload) but I can't save the changes.

Bob

**Comment by JellyBean22** [comment] 2013-04-18 23:47
Everything is still unclickable for me

**Comment by bobbyroberts99** [comment] 2013-04-18 23:49
Anonymous on beta seems to be working like it should (and quickly).

I cleared my cache and logged back into bobbyroberts99. This time I got 
2 clicks before it stopped working.

Tyler Renelle wrote:

**Comment by lefnire** [comment] 2013-04-18 23:57
@bobbyroberts99 your normal user account on prod?

**Comment by bobbyroberts99** [comment] 2013-04-19 00:03
Yes, but I've been using it on beta too. Is that a no no?

**Comment by lefnire** [comment] 2013-04-19 00:06
no it's fine, just checking to see if the error is still occurring for you on production as well.

**Comment by savannahcookson** [comment] 2013-04-19 00:10
Fwiw mine is not working on iPhone browser prod

Savannah Cookson
CoNTRoL - Cognitive Neuroscience Research at Tech Laboratory
(404) 372-5380
savannah.cookson@gatech.edu

**Comment by wisteriacs** [comment] 2013-04-19 00:17
Mine's not working--occasionally a refresh will allow a single click. Tried on Chrome and Safari Mac 10.7 As far as I know, it's not beta, but I'm not sure.

**Comment by lefnire** [comment] 2013-04-19 00:26
Ok, I've reverted all the culprits. How are things looking now?

**Comment by JellyBean22** [comment] 2013-04-19 00:32
All working as it should now on prod but not beta yet

**Comment by wisteriacs** [comment] 2013-04-19 00:34
Looks good for me!

**Comment by lefnire** [comment] 2013-04-19 00:35
Wahhhh! It's a bummer that was the fix after all, I thought I had solved other bugs with those commits! Back to the drawing board

**Closed as completed by lefnire** 2013-04-19 00:35 UTC

**Comment by bobbyroberts99** [comment] 2013-04-19 00:43
Both beta and prod work like before on my iPhone (well). Can't edit habits in beta though (but have had that problem for a while).
