### ISSUE TITLE
Cron triggering twice a day

### ISSUE THREAD

**Issue by harleyalexander** [HabitRPG/habitica#6922] opened 2016-03-19 00:03 UTC
Hello!
I'm writing because I have the issue posted below. I have posted in the corresponding issue thread and was asked by Alys to report the bug. 

> @Alys 
> Hello!
> I'm having the issue that cron triggers twice a day. It has caused me to die and lose all the things I've worked hard for. The time zone on the website settings tab shows a UTC -4:00 but my computer shows UTC -5:00. I've reloaded the page and restarted my computer but the website does not change. I don't know if this is the issue because cron triggered at 12:00am and then at 7:00am, killing not only me, but injuring my whole party. Is there any way to roll back this issue and get my level, gold, and equipment back?
> Thank you!

Alys' reply:

> @harleyalexander I've updated the first post in this issue to describe how to recover from the unfair damage (see the last paragraph, but in brief, you can use Settings > Site > Fix Character Values). We'll need to talk to you some more about the problem you're having, so please log a new issue as described in the second-last paragraph (in brief, go to Help > Report a Bug and follow the instructions there, especially point 6 about how to find your User ID).

The time previously posted are wrong. Cron first triggered at 03/16/2016 00:18:23  and then again at 03/18/2016 05:03:07.

I'm also running the andriod app, and I can't seem to find a way to check the time settings on that. My phone time and my computer times are both the same.

My user ID is : 0787ac9b-5c80-4286-9db7-c0cc2ab92262

I am using the latest version of Google Chrome running on a Windows 10 OS.

Thank you in advance!

**Comment by Alys** [comment] 2016-03-19 00:37
Thanks for all the details!

It's quite disturbing that Habitica isn't picking up your PC's correct time zone even after a refresh, which is the main reason I wanted this in a new issue because it could be some trouble to sort it out. Although I am wondering if your PC isn't reporting a DST change to you correctly when you look at your PC's own time zone. Can you show me a screenshot of your PC's time zone settings screen? Either drag it into a new comment here (attaching it to an email to github won't work), or if you don't want to release it as public information for privacy reasons, then email the screenshot to admin@habitica.com and mention my name (Alys) in the email.

Please also tell me the local name of the USA time zone you are in. E.g., PDT or EST. In an email is fine if you don't want to release it publicly either.

I've confirmed from your account that Habitica does have UTC -4:00 recorded for you at the moment.

For the Android app, ensure that you're using the latest version, which is 0.0.27. If you see any number less than 27, it's not the latest version and you should avoid using the app until the new version appears in Google Play for you (although it's probably there now). You can see the version number by going to the About screen and scrolling all the way down to the bottom. Old versions had a bug that would have caused at least some of the problems you reported.

Could you please tell me if you have been using an old version in the past couple of days? Knowing that will help me work out what still needs to be fixed here.

Please go to the Settings > Site page on your mobile browser, then reload it, and then tell me what time zone Habitica reports there.

**Comment by Alys** [comment] 2016-04-02 06:13
@harleyalexander I'm closing this now but if you'd like more help, see the questions from my previous post, and let us know if there's any other information you can give us.

**Closed as completed by Alys** 2016-04-02 06:13 UTC
