### ISSUE TITLE
Spooky Sparkles not showing

### ISSUE THREAD

**Issue by mdianes** [HabitRPG/habitica#4145] opened 2014-10-14 09:41 UTC
A teammate and I are using spooky sparkles,but the effects are no longer showing for the spooked teammate.  (The change does show for the person performing the action, and the action is logged in the party information.)  The potion was working correctly when we initially tried it.  We've only run into issues in the past few days.

**Comment by Alys** [comment] 2014-10-14 09:50
For each player who has Spooky Sparkles cast on them, the effect wears off at the start of their new day. The player can also choose to remove the effect by buying an Opaque Potion. 

Also after you cast the sparkles on a party mate, you might need to reload the page to  see their avatar change.

From your description, it sounds like the sparkles are working as intended (just keep in mind the reload trick), so I'm going to close this issue, but if you have any concerns or if this information hasn't helped, comment here and we'll reopen it.

**Comment by mdianes** [comment] 2014-10-14 10:35
The sparkles are not working as intended.  We've tried refreshing, reloading, and the sparkles do not show same day, even within a six hour window of trying all of the things you suggested.  It is also not an opaque potion issue.  We are deliberately coordinating to try to get the effects to show.

**Comment by Alys** [comment] 2014-10-14 10:53
Okay, reopening, and investigating.

Can you please tell us the User IDs of all affected players and the Group ID of the party. To learn how to find those things, go to [Help -> Report a Bug](https://github.com/HabitRPG/habitrpg/issues/2760). 

Please also describe, step by step, the exact process you're following to cast the sparkles, and what happens at each step. Sorry to ask this, but I do need this detailed information from you because I've just tested and I can't replicate the problem you describe.

Also, after casting at least one Sparkle, reload the party page and then take a screenshot of the party page chat showing the message saying that they were cast, and also showing the header with the avatar of the party member they were cast on, with the name of the avatar visible in the header (you might need to hover over the avatar to make the name show).

**Comment by Alys** [comment] 2014-10-14 11:01
In case this helps, this is the step-by-step process that I followed to test:
- On the right-hand side of the [Inventory -> Market page](https://habitrpg.com/#/options/inventory/drops), at the bottom in the "Special" section, I clicked on the Sparkles icon.
- Result: 15 GP was subtracted from my account and one Sparkles appeared in my inventory (i.e. on the left-hand side of that same page).
- I clicked on the Sparkles in my inventory (on the left-hand side of that page).
- Result: My mouse pointer changed to a green plus symbol.
- I clicked on an avatar in the header.
- Result: The avatar changed to a ghost (no reload was necessary).

You might find it helpful to copy these exact steps to the clipboard, paste them into your reply and then edit them as necessary to describe exactly what you did and what happened - especially where the process you followed or the results you found were different than I described.

**Comment by mdianes** [comment] 2014-10-14 13:17
IT seems to be an issue if one of us hasn't refreshed the view since cron.  If we've both refreshed/reloaded after cron, the sparkles take.  If the person it is cast on hasn't refreshed or reloaded since cron and the other party member casts sparkles, the sparkles show only to the caster, even after the castee refreshes/reloads.

---

On Tue, 10/14/14, Alice Harris notifications@github.com wrote:

 Subject: Re: [habitrpg] Spooky Sparkles not showing (#4145)
 To: "HabitRPG/habitrpg" habitrpg@noreply.github.com
 Cc: "mdianes" m_dianes@yahoo.com
 Date: Tuesday, October 14, 2014, 6:56 AM

 Also, after casting at least one
 Sparkle, reload the party page and then take a screenshot of
 the party page chat showing the message saying that they
 were cast, and also showing the header with the avatar of
 the party member they were cast on, with the name of the
 avatar visible in the header (you might need to hover over
 the avatar to make the name show).

 —
 Reply to this email directly or view
 it on GitHub.

**Comment by Alys** [comment] 2014-10-14 19:49
Okay, so if I understand correctly, it is working, you just sometimes need to reload the page to see an avatar change? I'm closing this again but we can reopen it again if my understanding is wrong.

**Closed as completed by Alys** 2014-10-14 19:49 UTC
