### ISSUE TITLE
Dailies only partially resetting

### ISSUE THREAD

**Issue by melsmarsh** [HabitRPG/habitica#4923] opened 2015-03-26 14:34 UTC
This seems to be a new issue, but on cron only half of my dailies reset today and I had a perfect day.  I am not in the inn or anything like that.

Ones that did not reset included all of the ones I put in manually, such as the stuff I absolutely MUST do every day like meds and such.

Ones that did reset included all the ones I was doing for challenges like "do something nice for yourself."

Sometimes the manual ones won't appear but will appear when you refresh (I did, it didn't).  Help?

**Comment by Alys** [comment] 2015-03-26 21:54
This is an example of the bug reported in https://github.com/HabitRPG/habitrpg/issues/4313. I am sorry you were hit by it! If you look in the "Advice" section in the first post on that page, you will see some information about a workaround for today ("How to fix Dailies that should have become unticked"), and what to do if you notice it happening again ("What to do if you experience this bug often").

I'm closing this issue, but you can track the progress of the bug by going to that page and clicking the subscribe button in the right-hand column. If you have questions, you can ask them here and we'll see them and help you.

**Comment by Alys** [comment] 2015-03-30 16:18
I'm reopening this because @melsmarsh says in https://github.com/HabitRPG/habitrpg/issues/4313#issuecomment-86742051 that this can't be that bug. Extra information they provided there:

User: d37b6a7e-8ede-4e78-8924-1598eaffd397
Browser: Firefox (same issue on Chrome)
OS: Win 8.1

melsmarsh commented 9 hours ago:
And today the only ones that reset were the manually entered ones, but the challenges didn't reset. I am quite, quite confused.

melsmarsh commented 2 hours ago
@Alys those steps [_the advice to reload and sync at the end of each day_] do not work to fix this bug. I already tried it multiple times and did before I even reported the bug here. I believe I even mentioned that in the initial bug report. I really think this is a separate bug. It is too unusual to have manually entered dailies and challenge dailies acting differently from each other.

**Comment by Alys** [comment] 2015-03-30 16:45
@melsmarsh According to the history on your Dailies, none of them have been reset since 2015-03-27 or 2015-03-28 (timezones make it fuzzy). The ones that appeared to be resetting might have been not due on recent previous days and so when they became due, they had not been ticked yet.

I know you aren't resting in the inn now, but have you been resting in the inn at any time, even briefly, over the past few days?

Can you confirm, just so that we can be certain, that at the end of each day after you have ticked off all your tasks for that day, you have been reloading using your browser's refresh button?

**Comment by Alys** [comment] 2015-06-26 05:48
I'm closing this, but if you'd like us to keep investigating, please give us answers to the questions above - although it's probably only relevant if the problem is still happening.

**Closed as completed by Alys** 2015-06-26 05:48 UTC
