### ISSUE TITLE
Login button does not work on iPad

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#5702] opened 2015-07-31 00:00 UTC
The new Habitica splash page does not work on my iPad (iOS 8.4, Safari). The login buttons change colour when you tap them but don't do anything else. Pretty sure this was a problem when this splash page first went up on HabitRPG too way back when it was introduced.

**Comment by ghost** [comment] 2015-07-31 00:03
It does, however, work on Chrome on iOS.

**Comment by crookedneighbor** [comment] 2015-07-31 03:45
This is a duplicate of https://github.com/HabitRPG/habitrpg/issues/5111

The weirdest thing is that it's only happening in a production environment. Haven't been able to figure it out yet, but it's next up on my list of things to fix. Thanks for reporting it.

**Closed as completed by crookedneighbor** 2015-07-31 03:45 UTC
