### ISSUE TITLE
Buying Weapons: GP spent, but didn't receive weapon

### ISSUE THREAD

**Issue by coolandsmartrr** [HabitRPG/habitica#233] opened 2013-01-27 06:38 UTC
One incentive to keep playing this game is to accumulate wealth by completing tasks. Yet, when I spent 20 Gold to get sword 2, the money disappeared while I haven't obtained the weapon. Sword 2 is still available for sale, and I still hold the default sword. Could this bug get fixed soon?

**Comment by horusofoz** [comment] 2013-01-27 11:02
Can you log out, clear your browser cache and log back in to confirm the issue persists?

**Comment by rixx** [comment] 2013-01-27 12:10
Same thing happened to me, however a reload of the page fixed it. It becomes more aparent if you buy something that makes you look different – you get the item immediately, but it takes a reload to update the shop.

**Comment by coolandsmartrr** [comment] 2013-01-27 12:34
I reloaded, and sword 2 got replaced by an axe. However, it seems that the graphic hasn't changed at all.

**Comment by horusofoz** [comment] 2013-01-27 12:36
@rixx @coolandsmartrr Can you advise if your using your phone or a computer to access the website? Android, iPhone, Windows, Mac OSX, Ubuntu Linux, etc.

Also what web browser are you using? Firefox, Safari, Chrome, Internet Explorer, etc.

Thank you for taking the time to help us, help you :)

**Comment by rixx** [comment] 2013-01-27 12:37
Sword2 looked pretty much like the first sword for me, too.

**Comment by horusofoz** [comment] 2013-01-27 12:41
The Sword2 graphic is basically a larger sword.Open the website in an alternate browser and compare the sword from the demo page to confirm the graphic has changed.

**Comment by StanLindsey** [comment] 2013-01-27 14:40
The graphic does change, it is just extremely similar, if the item in the shop has then you've upgraded properly. I'm fairly sure the whole character customisation and store items will be rebuild at some stage so this will be fixed.

**Comment by rixx** [comment] 2013-01-27 14:41
Two days ago, it didn't change for me when I bought my axe.

**Comment by horusofoz** [comment] 2013-01-27 14:44
@rixx Can you advise if your using your phone or a computer to access the website? Android, iPhone, Windows, Mac OSX, Ubuntu Linux, etc.

Also what web browser are you using? Firefox, Safari, Chrome, Internet Explorer, etc.

I assure you we will be able to resolve your issue sooner with this info.

**Comment by rixx** [comment] 2013-01-27 14:44
Firefox on Arch Linux.

**Comment by StanLindsey** [comment] 2013-01-27 14:47
(Labled as bug due to either character's weapon not upgrading or character image not representing current weapon)

**Comment by horusofoz** [comment] 2013-01-27 14:55
@rixx Thank you.

@coolandsmartrr Can you provide your OS and browser info? It helps to isolate the issue.

**Comment by coolandsmartrr** [comment] 2013-01-28 14:48
@horusofoz I use the latest version of Chrome on Mac OSX 10.8.2.

**Comment by horusofoz** [comment] 2013-01-29 04:30
Thanks guys. This at least makes evident the issue is not isolated to an OS (Arch Linux/OSX), browser (Firefox or Chrome) or rendering engine (Gecko/WebKit).

My thought is it was an temporary database issue but still requires further investigation.

Could you provide your UUIDs so the devs can have a look at the backend for any unusual activity around the time you guys reported the issue?

**Comment by StanLindsey** [comment] 2013-01-29 10:09
I assume you've all Ctrl-F5ed, the image for the sword might be sitting in the cache or similar. (I'm not sure how the site reloads/changes the images so I think this is a long shot)

**Comment by coolandsmartrr** [comment] 2013-01-29 15:21
@horusofoz I'd like to provide my UUID, but I wonder if it's safe to just post it here. As of now, not many apps utilize the HabitRPG API, but someone can still manipulate my data knowing my UUID. Is there a way to PM you?

**Comment by lefnire** [comment] 2013-01-29 15:27
yeah, [email it](https://github.com/lefnire/habitrpg#email) to me instead.
We're working on getting API tokens in place for external apps so UUIDs
will be safe to publicly use

**Comment by horusofoz** [comment] 2013-01-29 16:05
@coolandsmartrr Just to confirm,  @lefnire is the primary dev. We are all playing with his brainchild. Props be to @lefnire ;)

**Comment by lefnire** [comment] 2013-01-29 16:09
and @horusofoz @SlappyBag @wc8 @hookang are keeping me sane!

**Comment by rixx** [comment] 2013-01-29 16:41
Just an update, it seems the problem is persistent. I bought the Morningstar, which became visible in my avatar nearly immediately, while the Morningstar remained in the Menu.

![habitrpg](https://f.cloud.github.com/assets/2657547/107649/b4b071b2-6a32-11e2-93df-4a94cbb1fc8b.png)

A simple F5 did it for me.

(I don't mean to push since this is a rather minor bug; just wanted to provide an image for reference. You're all doing an awesome job and I'm enjoying this site a lot!)

**Comment by lefnire** [comment] 2013-01-30 18:47
fixed - was a bug where model functions weren't re-constructed on dom reset, see [this code](https://github.com/lefnire/habitrpg/commit/466256f7930b1c885efb9a67a42dd2936940da23#L17R102)

**Comment by lefnire** [comment] 2013-03-23 15:32
reopening due to #709

**Comment by lefnire** [comment] 2013-04-06 18:41
still a problem, upping to critical. users who experience this - [use this](https://github.com/lefnire/habitrpg/wiki/Restoring-Your-Account#restoring-your-avatar-stats-items-accidental-death-etc) to restore your deserved weapon / armor while I work on this ticket

**Comment by lefnire** [comment] 2013-04-08 00:23
that commit should fix it (will deploy with next restart)

**Closed as completed by lefnire** 2013-04-08 00:23 UTC
Labels: priority: important
