### ISSUE TITLE
HabitRPG: My life keeps going down by almost half ...

### ISSUE THREAD

**Issue by jared43** [HabitRPG/habitica#3626] opened 2014-06-19 14:25 UTC
My character Jared43 keeps loosing his life each night by half even though I am completing all my daily tasks, pushing + on my habits and completing items off the to-do list. I thought life was only effected by habits and dailies? I enjoy HabitRPG but it is getting a little out of hand. 

Please help,

Jared

**Comment by paglias** [comment] 2014-06-19 14:28
Are you in a quest?
Il 19/giu/2014 16:25 "jared43" notifications@github.com ha scritto:

**Comment by jared43** [comment] 2014-06-19 14:33
Not to my knowledge. I was waiting for some buddies to get back from Europe before we started doing them together. 

Jared S. Rife

From: Matteo Pagliazzi
Sent: ‎Thursday‎, ‎June‎ ‎19‎, ‎2014 ‎10‎:‎28‎ ‎AM
To: HabitRPG/habitrpg
Cc: jared43

Are you in a quest? 
Il 19/giu/2014 16:25 "jared43" notifications@github.com ha scritto:

**Comment by paglias** [comment] 2014-06-19 14:57
Strange... This evening when you have checked all the dailies try
refreshing the browser and look if they are still checked
Il 19/giu/2014 16:33 "jared43" notifications@github.com ha scritto:

**Comment by jared43** [comment] 2014-06-19 14:57
Ok will do. Thanks.

Jared S. Rife

From: Matteo Pagliazzi
Sent: ‎Thursday‎, ‎June‎ ‎19‎, ‎2014 ‎10‎:‎57‎ ‎AM
To: HabitRPG/habitrpg
Cc: jared43

Strange... This evening when you have checked all the dailies try 
refreshing the browser and look if they are still checked 
Il 19/giu/2014 16:33 "jared43" notifications@github.com ha scritto:

**Comment by lefnire** [comment] 2014-06-19 15:00
Also, any tags activated? [Click clear](https://www.evernote.com/shard/s17/sh/a84b706c-2b0d-4ba3-87a2-aa67e866237f/fdb70f8c3f51c787281ef7d838aaa059) to be sure, they persist across refresh. (aka, you could be not seeing some of your active dailies)

**Comment by jared43** [comment] 2014-06-19 15:04
I checked the tags and I haven't designated any as that. I also just noticed that none of my dailies are showing that they have more then “one” on the streak counter. They all say one (or are still waiting as I have not completed them) but I have been doing them, in some cases for weeks. Would it have something to do with the fact that I am now in a different time zone then the one I registered in?

Jared S. Rife

From: Tyler Renelle
Sent: ‎Thursday‎, ‎June‎ ‎19‎, ‎2014 ‎11‎:‎00‎ ‎AM
To: HabitRPG/habitrpg
Cc: jared43

Also, any tags activated? Click clear to be sure, they persist across refresh. (aka, you could be not seeing some of your active dailies)

**Comment by seajules** [comment] 2014-06-23 12:32
I have this same problem and I am on the Octothulu quest.

**Comment by Alys** [comment] 2014-08-13 08:06
It's likely that these problems were caused by sync errors. To learn about them, see  [Sync Errors](http://habitrpg.wikia.com/wiki/Sync_Errors) on the wiki, in particular the sections titled "How to Minimise Sync Errors" and "Completing most/all Dailies but still losing heath". I'm closing this issue now since it's rather old (I'm sorry we didn't give you this information earlier), but if the problems are still happening and the sync error page doesn't help, comment here and we'll reopen this.

**Closed as completed by Alys** 2014-08-13 08:06 UTC
