### ISSUE TITLE
Deleting food items

### ISSUE THREAD

**Issue by heidihohh** [HabitRPG/habitica#6173] opened 2015-11-03 19:37 UTC
Twice today I have had a food item disappear when I went to/refreshed the Pets page. (not the same food item, either... chocolate and honey today.)

**Comment by Alys** [comment] 2015-11-03 19:50
That will be from one of these causes (the first one is most likely if you've used the Armoire several times today):
1. [Enchanted Armoire drops equipment but no gear or the wrong gear appears in Inventory - Issue #5376](https://github.com/HabitRPG/habitrpg/issues/5376). That can also happen with food - the Armoire gives you food initially but then the bug causes it to be replaced with something else. If you look in your equipment list, you might find new gear there, or you might have been given Experience. The chance of this bug happening can be reduced if you wait for a sync to happen after each time you click on the Armoire.
2. [Sync errors](http://habitica.wikia.com/wiki/Sync_Errors), which can happen if you take several actions on the site too quickly. In brief, your browser processes your actions and shows you results, but the server can't keep up with the pace and doesn't store the results, so when your browser later syncs with the server, the effects of your actions disappear.
3. [Issue 4313](https://github.com/HabitRPG/habitrpg/issues/4313), which can affect things other than tasks, despite the name of the issue. It's similar to point 2 except that it's a problem caused by local storage on your browser holding onto your changes and then, in this case, losing them later. 

If it was caused by 2 or 3, you might find that a couple of Dailies or To-Dos have become unticked.

I'm going to close this now since we're tracking those possible causes elsewhere, but if you have any questions, please do comment here. We'll still see your comments and keep helping you.

**Closed as completed by Alys** 2015-11-03 19:50 UTC

**Comment by heidihohh** [comment] 2015-11-03 20:01
Thank you for the prompt answer... but the second one occurred when I only clicked the enchanted armoire once?
h

Date: Tue, 3 Nov 2015 11:50:15 -0800

**Comment by Alys** [comment] 2015-11-03 22:28
It could have been from one of the other two causes too. I should have mentioned before: if you tell us your User ID, we can give you back the food. See Help -> Report a Bug step 6 for how to find your User ID.

**Comment by heidihohh** [comment] 2015-11-03 23:40
it hasn't happened since; i've been going very slowly! my user id is heidiho.
thank you!
h

Date: Tue, 3 Nov 2015 14:29:06 -0800

**Comment by Alys** [comment] 2015-11-04 10:15
I'm sorry, we can't use your profile name to adjust your account because more than one person can use the same name. Can you please go to Help -> Report a Bug and see step 6? That shows you how to find your User ID, which is unique to your account.

**Comment by heidihohh** [comment] 2015-11-04 13:18
Goddess, I'm such a moron about this!

I'm lazy in bed right now... torn meniscus,7am and all that. I appreciate all the time you've spent while I'm being an idiot. I want so worried about the missing items as I was that I'd goofed it up somehow!

Thank you. I'll figure this out after my MRIs today!

Heidi

On November 4, 2015, at 4:15 AM, Alys notifications@github.com wrote:

I'm sorry, we can't use your profile name to adjust your account because more than one person can use the same name. Can you please go to Help -> Report a Bug and see step 6? That shows you how to find your User ID, which is unique to your account.

---

**Comment by Alys** [comment] 2015-11-04 22:20
You're not being a moron! Take your time, there's no hurry. :)
