### ISSUE TITLE
"Application Error" on page refresh

### ISSUE THREAD

**Issue by VerbingNouns** [HabitRPG/habitica#2638] opened 2014-01-29 19:55 UTC
![screen shot 2014-01-29 at 1 48 27 pm](https://f.cloud.github.com/assets/1964260/2033598/1661f046-891f-11e3-9fbc-308f47c537ab.png)

At first it said something about Error 404 and upgrading my mobile application (I'm on Chrome Version 32.0.1700.102 on a MacBook Pro), but now it only says this.

(iframe https://s3.amazonaws.com/heroku_pages/error.html or something?)

**Comment by colegleason** [comment] 2014-01-29 20:06
This happens when something crashes the server. Dupe of #2554.

**Closed as completed by colegleason** 2014-01-29 20:06 UTC
