### ISSUE TITLE
Warning: Unresponsive script, site crashes

### ISSUE THREAD

**Issue by mellifiedmonkey** [HabitRPG/habitica#1499] opened 2013-09-09 17:30 UTC
I haven't been able to access the site for four days now - basically, ever since the big update. It's crashed on chrome and firefox, and crashed when I tried it on another computer. Can't access it to provide my user ID. username is mellifiedmonkey. It loads my avatar and health/exp bar, and occasionally a bit more, but I can't select anything. Gives me the option to 'kill pages' and even if I click wait, it crashes and shows me the blue 'Something went wrong while displaying this webpage' screen.

**Comment by paglias** [comment] 2013-09-09 17:38
Do you have an old pc?

2013/9/9, mellifiedmonkey notifications@github.com:

> I haven't been able to access the site for four days now - basically, ever
> since the big update. It's crashed on chrome and firefox, and crashed when I
> tried it on another computer. Can't access it to provide my user ID.
> username is mellifiedmonkey. It loads my avatar and health/exp bar, and
> occasionally a bit more, but I can't select anything. Gives me the option to
> 'kill pages' and even if I click wait, it crashes and shows me the blue
> 'Something went wrong while displaying this webpage' screen.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/lefnire/habitrpg/issues/1499

## 

Matteo Pagliazzi - paglias.net

**Comment by wc8** [comment] 2013-09-09 17:41
Same as #1495 ?

**Comment by mellifiedmonkey** [comment] 2013-09-09 18:32
My laptop is a new macbook pro, other computer I tried it on is an old PC. Doing the same thing on both. Sounds similar to 1495 but I'm not getting the 'couldn't find it' error message.

I had a friend look it up and my ID should be a32f7a95-2489-49f8-8793-936af2b59b5e

**Comment by michaelmdf** [comment] 2013-09-09 18:37
@mellifiedmonkey: I think our issues are essentially the same indeed. The 'could not find' message was for 'old.habitrpg.com,' which I was told was taken down.

If that's relevant, I'm also trying it from a MacBook Pro (running Mac OS X 10.7.4).

Unfortunately I do not have access to my ID, since I'm not able to load it. Can you pull it out from any other piece of information?

**Comment by lefnire** [comment] 2013-09-09 18:47
I'm able to replicate with @mellifiedmonkey's account, it's too much to handle. My guess is many non-cleared completed todos - page just crashes from javascript overload. I can't get to this right this minute, we'll obviously need to at least manually clear mell's todos so they can get in for the time being, and do something about performance in the long term. I should be able to get to this tonight or tomorrow

**Comment by michaelmdf** [comment] 2013-09-09 18:53
This seems plausible. I go through a fair amount of todo's and didn't know that they still ate up space/memory/whatever. I don't think I've ever cleared them! Sorry :-(

If my account loads again (as it has once or twice for a little bit) I'll try and clear up my completed todo's and see if I see any improvement.

Thanks!
Michael

**Comment by lefnire** [comment] 2013-09-09 18:56
don't be sorry, it's our own fault for now having a mechanism in place for angular to ignore completed todos. Ok, hit me if you get it solve, and i'll tackle this moment i can otherwise

**Comment by mellifiedmonkey** [comment] 2013-09-09 19:36
I was able to get mine to work on Safari

**Comment by michaelmdf** [comment] 2013-09-09 21:34
Chrome: looks like it's trying to load but doesn't do anything; every now and then the window asking whether I'd like to wait for it or kill the website pops up.

Safari: stops trying to load, but incomplete; seems to be taking up a lot of memory and/or processing power since the whole system slows down severely.

Opera: loads incomplete; reloading doesn't do anything, have to close the tab and open a new one, but it only brings it back up to the same point.

Firefox: Gives me:

Warning: Unresponsive script

A script on this page may be busy, or it may have stopped responding. You can stop the script now, or you can continue to see if the script will complete.

Script: https://habitrpg.com/build/app.js:5

**Comment by michaelmdf** [comment] 2013-09-09 22:08
Managed to load (don't really know how) on Chrome. Yay! This is my User ID: 261555d5-6784-4103-91f9-d881bdc26d67

It seems like I've managed to clear the completed tasks, although clicking on that tab now takes me to a void I can't come back from without refreshing.

I suppose I might still have too many todos in there though? I used the GTD method, so basically every task I have to do is in there. I probably accomplish 5--10 of those a day (sometimes a little more), but I often replace them with a comparable amount. Is there an optimal number of tasks the system would be able to handle, at least at this stage?

Thanks a lot for all the help! Let me know if there's anything else I could do :-)

**Comment by BlackEdder** [comment] 2013-09-10 13:34
@michaelmdf: what I do is only put the tasks I want to accomplish that day on the habitrpg todo list. This is not ideal since you need another separate todo list, although I do find that having less todo items in view is much more motivating, since I have the feeling I can actually finish them.

Of course this only a suggestion while they are trying to optimize the site.

**Comment by michaelmdf** [comment] 2013-09-10 13:39
Crashing update: Yesterday evening I managed to load it and it was quite stable. I don't know if anybody did anything about it, but if they did, it seems like it worked! This morning I was also able to load it and work without any problems.

@BlackEdder: Yes, I'm going to review how I work this out for now. In thinking about this I think it would be nice to have a "bank" of todos where you could keep everything whatsoever you need to do, and then you could check some todos from those every day into your current, or most immediate ones (the ones which you'd actually get points for). But I'll suggest that (or something like it) at the appropriate location as a feature. Thanks for the suggestion!

**Comment by AranelS** [comment] 2013-09-10 13:40
Aha!  

I cleared my looooong list of completed todos and stopped getting the incessant "unresponsive script" warnings in Firefox. I can even load my inventory without freezing the browser first!   YAY!

My current list of todos only has about 10 items in it, which is clearly not enough to cause any problems.

**Comment by paglias** [comment] 2013-09-10 13:42
How many did you have before?

@lefnire we should or delete completed todos after for example 1 week or
when they reach a x number

**Comment by lefnire** [comment] 2013-09-10 16:48
That's a possible solution. A safer bet is create an "archive" page with completed overflow beyond say 10 items. Just static jade-rendered list which allows you to restore to main list, but it's a totally separate page (kinda like how Pandora management pages).

But @paglias your solution is much simpler. Does anyone here object? The downside is you lose data (completed todos), which _could_ have contained useful information. But the upside is, I don't think **anyone** has used that data - most people are even surprised the "completed" tab exists.

**Comment by Shaners** [comment] 2013-09-10 16:54
I'd like to have that data available for possible analysis but in current state I have to remove it anyway to help with using the site. My vote would be go with Paglias solution for now with the archiving as a 'nice to have' feature but not a priority.

**Comment by lefnire** [comment] 2013-09-10 16:58
I'm on board with that

**Comment by paglias** [comment] 2013-09-10 17:04
The archive solution is a lot better but since this is a quite serious bug iw ould go with: move old items deciding if after x numbers by completion (we need completion date field I think) or after x completed items to an archive field then when we will have time add the ability to see the archive.

**Comment by eiron** [comment] 2013-09-10 22:01
I have the problem that I have a large todo list (which has gotten dramatically bigger recently with my lack of time for doing things). The number of items I have is certainly in excess of 1000. Even clearing the completed items, Habit is having a lot to do with me.

**Comment by paglias** [comment] 2013-09-11 13:55
Now how many items do you have completed+todo?

**Comment by eiron** [comment] 2013-09-11 23:18
The completed tasks are now cleared, but that does leave roughly 1000 (or
more) todos still active.

**Comment by paglias** [comment] 2013-09-12 12:56
1000 active todos? that's really a lot and I don't think we can do really
anything about that

2013/9/12 Eiron Page notifications@github.com

> The completed tasks are now cleared, but that does leave roughly 1000 (or
> more) todos still active.
> 
> On 11 September 2013 14:55, Matteo Pagliazzi notifications@github.comwrote:
> 
> > Now how many items do you have completed+todo?
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/lefnire/habitrpg/issues/1499#issuecomment-24241341>
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lefnire/habitrpg/issues/1499#issuecomment-24284081
> .

## 

Matteo Pagliazzi - paglias.net

**Comment by lefnire** [comment] 2013-09-12 15:43
@litenull did some work with [ngInfiniteScroll](http://binarymuse.github.io/ngInfiniteScroll/) on a separate branch for mobile, thinking about toying with that in the near future to see if we could get infinite todo list sizes. Would be a bit down the pike though

**Comment by litenull** [comment] 2013-09-13 20:06
Nice, nice. let the force be with you.

**Comment by lefnire** [comment] 2013-11-06 01:35
I added preen-history to user cron, I want to see if this will fix the issue for some people. Cron (next day roll-over) doesn't happen till the next morning, so y'all won't be able to check until tomorrow. Alternatively, I added a "trigger next day" button in Options > Settings > Restore, but that'll hurt your avatar - so use with digression.

The two next big things that need to happen to improve performance are:
- use `ui-router` **or** `ng-filter` to switch between completed / non-completed TODOs. I realize, we don't need to create a separate page - we just need to filter it or write it to a $state, so that all the bindings aren't wired up for invisible TODOs
- Do something about that `taskClasses()` horrible method, which is causing digest to recalculate for every single action 

These two are listed at https://github.com/HabitRPG/habitrpg/issues/1451, but I'm just thinking out loud.

**Comment by deertheory** [comment] 2013-11-06 06:44
Hi, all,
Apologies for delayed input. I was #1737, thanks for closing & redirecting me to this thread.
My UID is 166219e2-7f70-46cf-869a-cd4990093482. Clearing completed tasks helped, but still I get crashed every now and then, including today when I went to show someone via my own screen where to find their UID.
I am not running an old or unequipped computer. ASUS G53S.
Additionally, an archive sounds great. Also, though, I am a bit of a digital hoarder, so maybe it is a bad pattern behaviour. I agree that it would be interesting for those who wanted to analyse their task management & such.

**Comment by lefnire** [comment] 2013-11-06 19:24
I've started a branch called `remove-task-classes`. First commit there is using a filter instead of taskClasses to show/hide completed todos. Alternatively we could use ui-router, or even break `user.todos` into `user.todos, user.completed`.  That commit above I think might be a bit iffy though, I think {completed: true/false} check won't always give expected results for non-todos. thoughts @paglias ?

Anyway, removing taskClasses bit-by-bit is gonna be a difficult process, important one I think. I'll keep y'all posted

**Comment by ahrisah** [comment] 2013-11-07 21:24
Hi, I've been having this issue for like 3-4 weeks now. I use chrome and I can't get my habit to load for the life of me. I read through this thread and using the mobile iOS app I checked all of my to-dos to see if that would get it working again. alas, there hasn't been much improvement. I've been meaning to go ahead and reset my account and start fresh but haven't been able to do anything. 
 my user id: 4144e778-c263-457c-8e82-c11e79d2cbef

Help!

**Comment by paglias** [comment] 2013-11-07 21:25
You should try deleting all your completed todos
Il 07/nov/2013 22:24 "ahrisah" notifications@github.com ha scritto:

**Comment by lefnire** [comment] 2013-11-10 20:52
I've done some testing around on affected accounts. Preening user history helped substantially, but still not enough. The issue is definitely too many tasks - and probably 95% of the time is completed To-Dos. I tried a few things - removing `taskClassses()` completely, removing `task.history` bindings (since its' the largest task attribute), but nothing seemed to help a whole lot. Adding a filter on To-Dos (above commit) was the thing that helped the most. I'm going to play with that to try to get it solid.

In the mean time, if anyone can't even get into their account to clear todos, here's a workaround. Call the API route for clear-completed directly, you can do so by [going here](https://beta.habitrpg.com/static/api#!/user/user_tasks_clear_completed_post_7), entering your UUID & API Token at the top of the page (just enter it, don't need to click anything), and then clickcking "Try it out!" in the `POST /user/tasks/clear-completed` link I provided.

**Comment by lefnire** [comment] 2013-11-10 20:58
BTW @ahrisah, it's not "checking off To-Dos" that you need to do - it's _clearing completed To-Dos_ ([screenshot](https://www.evernote.com/shard/s17/sh/1a95f9cc-132d-4129-b50e-4ad6fa398414/2ccb06a007ddb91af1d0d63dd77d9b8f))

**Comment by ahrisah** [comment] 2013-11-11 18:24
@lefnire Yeah, I understand about deleting the completed to-dos but I can't access my account to do so. Also, I dl the chrome Advanced Rest Client and its not loading either...why would that be? If I could just get it to load I could follow your screenshot tutorial... :(

**Comment by lefnire** [comment] 2013-11-11 18:25
advanced rest client's not loading? hmm... what's your uuid, i'll give it a shot

**Comment by ahrisah** [comment] 2013-11-11 18:33
@lefnire just kidding- I turned off some extensions on chrome and it launched this time! I followed the screenshot replacing user and api codes with my own and hit send. Bunch of stuff came up in code that I don't quite understand.

**Comment by ahrisah** [comment] 2013-11-11 18:35
@lefnire Habit has loaded! Its a Christmas miracle!! Thanks for the help! Now i'm going to reset my character as planned and be sure to keep to-dos cleaned up. Is having to many uncompleted to-dos a problem at all or just completed ones? Just want to avoid this issue in the future

**Comment by lefnire** [comment] 2013-11-11 18:37
having many tasks in general is the issue. Obviously it _shouldn't_ be an issue, and we're working hard to fix it - but the most common cause of this for everyone is that they have too many **completed** todos (since they don't even know they're there until they click the "completed" tab)

**Comment by lefnire** [comment] 2013-11-23 21:48
@snicker this is the ticket i was talking about. I made some performance headway by (1) using `ng-if` instead of `ng-show` for `task._editing` (so that the edition options aren't bound / listening unless shown), and (2) a partially-functional filter to remove completed todos from the view at https://github.com/HabitRPG/habitrpg/commit/0456b835106b603f748650a34724ae7b03954b93 . Both cause issues: (1) causes strange CSS issues when editing tasks, (2) has filtering issues with habits / dailies / rewards. Anyway, just wanted to point you to the WIPs in case you're exploring that route

**Comment by snicker** [comment] 2013-11-24 00:11
awesome.. I'll make sure to look this over when I get a chance

**Comment by fragmental** [comment] 2013-12-04 02:58
Is there any way we could just tell people to clear their completed todos if they see the script error?  I was looking at the comments for the android client and someone was saying that the website was unusable because of this error.  I was having the same error, though the site was still perfectly usable, and that's why I came here.

**Comment by lefnire** [comment] 2013-12-09 19:12
@fragmental currently if you have >75 todos, a warning div says "please clear your todos for better performance". Nothing on mobile yet though

**Comment by lefnire** [comment] 2013-12-29 07:17
I pushed two big updates, doesn't fix everything but it should help. Can someone who was experiencing the issues try beta.habitrpg.com?

**Comment by eiron** [comment] 2013-12-30 23:04
I have given it a go, but am not seeing results. Obviously, I expect I am
the worst case scenario around here.

**Comment by JasonGross** [comment] 2014-01-28 07:10
I am having this issue too.  I have around 80-90 uncompleted to-dos (I'm using HabitRPG as a long-running to-do list), and clear my completed todos often.  Is 800 MB of RAM typical usage of the site?  It seems extremely excessive.

**Comment by fragmental** [comment] 2014-01-28 08:31
I don't know if 800 MB of ram usage is typical for the site, but I know
that either chrome or firefox will frequently use more than that on my pc,
whether I have habitrpg.com open or not.  I keep windows task manager open
and make sure they are both shut down before I open them back up again.
 That's the only solution I know of.  Which browser do you use?

**Comment by JasonGross** [comment] 2014-01-28 08:52
This is Chrome, and I'm not talking about the entire browser, I'm talking about just HabitRPG.  Chrome's internal task manager says that one HabitRPG tab is using 700MB, gmail is using 405MB, the browser process is 320MB, seven github tabs are collectively using 260MB, another HabitRPG tab (which I haven't done much on yet) is using 180MB, two facebook tabs are collectively using 170MB, the GPU process is using 160MB, two twitter tabs are collectively using 120MB, google calendar is using 70MB, and there a some miscellaneous other tabs using < 150 MB each.

**Comment by fragmental** [comment] 2014-01-28 09:03
Oh.  I forgot about chrome's internal task manager.  I should check mine
more often.

**Comment by JasonGross** [comment] 2014-02-02 12:54
This seems like it might be (at least in Chrome) HabitRPG running into some javascript garbage collecting infelicities of Chrome.  When I reload the page repeatedly (doing nothing but waiting for it to finish loading in between), I get the following sequence of memory consumption:

241 MB
388 MB
521 MB
627 MB
748 MB
874 MB
854 MB
922 MB
(page unresponsive on reload)

I suspect this is because Chrome shares javascript objects between two codebases (Blink and Chromium) and so is really bad at garbage collecting them.  I'd suggest working with the chrome devs to get this fixed, or picking a different UI framework that's better at memory.

**Comment by paglias** [comment] 2014-02-02 13:00
@JasonGross this is surely a problem, probably on the Chrome side, but we also have an enormeous memory usage when switching back and forth from the tasks page to the options pages and browsing the various tabs, I easily got 1.5gb of used memory.

For some reason a lot of objects are not correctly garbaged or destroyed by angular, I hope that upgrading to angular-ui 0.10 will solve a part of that, at least

**Comment by Alys** [comment] 2015-05-17 20:27
I'm closing this because it's very old and many site changes have been made since it was logged, which have probably resolved or improved these problems. This can be reopened if needed, but I suggest that new issues are probably better.

**Closed as completed by Alys** 2015-05-17 20:27 UTC
