### ISSUE TITLE
Facebook login on app doesn't work

### ISSUE THREAD

**Issue by MitjaCernko** [HabitRPG/habitica#6359] opened 2015-12-11 00:32 UTC
As FB is my only login (also on web app), and the loading screen just disappears shortly after pressing the "sign in with Facebook" button, and leaving me on the login page, I can't use the new version of the app...

**Comment by crookedneighbor** [comment] 2015-12-11 00:48
Duplicate of https://github.com/HabitRPG/habitrpg/issues/6358

**Closed as completed by crookedneighbor** 2015-12-11 00:48 UTC
