### ISSUE TITLE
Can't remove tag from a task

### ISSUE THREAD

**Issue by WillyReyno** [HabitRPG/habitica#7508] opened 2016-05-26 20:00 UTC
General Info
- UUID: aa137fd1-9b36-4c2f-ae2b-e651e2b764c5
- Browser: Firefox and Chrome
- OS: Windows 10  and Mac OS X El Capitan
### Description

Since not so long ago, maybe today, I can't remove a tag from my tasks. I added some gifs to show you the problem : 

![habiticabug2](https://cloud.githubusercontent.com/assets/5576482/15588236/276e52f2-238d-11e6-9f4f-a21b75ad907c.gif)
![habiticabug3](https://cloud.githubusercontent.com/assets/5576482/15588237/2774c2f4-238d-11e6-89ff-94f3cd802fd4.gif)

I tried with other tasks, same problem.

**Comment by SabreCat** [comment] 2016-05-26 20:02
Duplicate of #7412. Stay tuned there for our investigations!

**Comment by Alys** [comment] 2016-05-26 22:36
Also note that my first comment in #7412 has a workaround. In brief, double tap the tag's checkbox.

**Closed as completed** 2016-05-27 14:34 UTC
