### ISSUE TITLE
Can't connect to Habitica anymore! (either app or web version) - _cronSignature not reset correctly

### ISSUE THREAD

**Issue by alsombra** [HabitRPG/habitica#7970] opened 2016-09-05 00:44 UTC
General Info

   Device: kltetmo 
   Android Version: 22 
   AppVersion: Version 0.0.33.2 (117) 
   User ID: f24161df-3147-4b19-9b2a-1ae290977923 
- Browser: Chrome, Firefox, Safari
- OS: Mac OS
### Description

I have been getting the same "Connection Error : There seems to be a problem with a server. Try again later" error on the App for about 3 days now and all my friends confirm that the game is up and running normally for them! I can't connect to the web version either - It doesn't go past the loading initial screen (with habitica logo and tip) for any of the 3 Browsers I tested. 
#### Console Errors

---

GET https://habitica.com/api/v3/user/?userV=undefined 500 (Internal Server Error)

(anonymous function) @ app-212ad8bf.js:8s @ app-212ad8bf.js:8f @ app-212ad8bf.js:8j @ app-212ad8bf.js:9(anonymous function) @ app-212ad8bf.js:9$eval @ app-212ad8bf.js:9$digest @ app-212ad8bf.js:9$apply @ app-212ad8bf.js:9a @ app-212ad8bf.js:6i @ app-212ad8bf.js:7g @ app-212ad8bf.js:6xa @ app-212ad8bf.js:6wa @ app-212ad8bf.js:6(anonymous function) @ app-212ad8bf.js:11j @ app-212ad8bf.js:3fireWith @ app-212ad8bf.js:3ready @ app-212ad8bf.js:3I @ app-212ad8bf.js:3
app-212ad8bf.js:45 Object {data: Object, status: 500, config: Object, statusText: "Internal Server Error"}responseError @ app-212ad8bf.js:45j @ app-212ad8bf.js:9(anonymous function) @ app-212ad8bf.js:9$eval @ app-212ad8bf.js:9$digest @ app-212ad8bf.js:9$apply @ app-212ad8bf.js:9s @ app-212ad8bf.js:8v @ app-212ad8bf.js:8a @ app-212ad8bf.js:8

---

app-212ad8bf.js:45 Object {data: Object, status: 500, config: Object, statusText: "Internal Server Error"}config: Objectheaders: ObjectignoreLoadingBar: truemethod: "GET"transformRequest: Array[1]transformResponse: Array[1]url: "/api/v3/user/?userV=undefined"**proto**: Objectdata: Objecterror: "InternalServerError"message: "An unexpected error occurred."success: false__proto__: Objectheaders: (c)arguments: (...)caller: (...)length: 1name: ""prototype: Object__proto__: ()<function scope>status: 500statusText: "Internal Server Error"**proto**: Object__defineGetter__: **defineGetter**()**defineSetter**: **defineSetter**()**lookupGetter**: **lookupGetter**()**lookupSetter**: **lookupSetter**()constructor: Object()hasOwnProperty: hasOwnProperty()isPrototypeOf: isPrototypeOf()propertyIsEnumerable: propertyIsEnumerable()toLocaleString: toLocaleString()toString: toString()valueOf: valueOf()get **proto**: **proto**()set **proto**: **proto**()responseError @ app-212ad8bf.js:45j @ app-212ad8bf.js:9(anonymous function) @ app-212ad8bf.js:9$eval @ app-212ad8bf.js:9$digest @ app-212ad8bf.js:9$apply @ app-212ad8bf.js:9s @ app-212ad8bf.js:8v @ app-212ad8bf.js:8a @ app-212ad8bf.js:8

**Comment by Alys** [comment] 2016-09-05 01:18
Please go to https://habitica.com/static/clear-browser-data and click the red button there, then before you log in again, clear your browser's cookies for habitica.com. 

I think that actually won't help, but it's worth a try. Post again here with the results. If it helps, it will be only for the website.

**Comment by Alys** [comment] 2016-09-05 01:27
Found it! Probably. `"_cronSignature": "c5a4af61-7b89-4607-9a04-25694d902aa6",`  I've changed it to "NOT_RUNNING" which is correct. Don't worry about what it means - that's a note for us admins.

You were also affected by this bug: https://github.com/HabitRPG/habitrpg/issues/7955
but I've just cleared the bad notification. That wasn't be the cause of not being able to log in though.

Please try logging in on both website and app now. Don't bother about doing the instructions in my previous comment.

**Comment by alsombra** [comment] 2016-09-05 02:36
Solved, It's all working again! Thanks a ton, Alys! Really impressed with the efficiency of all Habitica team! =D

**Comment by BlackEdder** [comment] 2017-10-14 11:39
I have a similar problem. 

My User ID:29c6cae1-b18e-472d-97bc-36f3aa7ebc5b
Both the iphone app and on safari.

It started happening after going to colombia for a week (Normally I am based in the UK).

**Comment by BlackEdder** [comment] 2017-10-14 11:56
As an update:

I managed to login on firefox from a linux machine. Now I seem to be able to login on the iphone again, but still not from safari on OSX.

**Comment by Alys** [comment] 2017-10-21 12:16
@BlackEdder  You're not affected by the _cronSIgnature bug if you're able to log in on another platform.

On Safari, go to https://habitica.com/static/clear-browser-data and click the red "Clear Data" button there. If that doesn't make the website work, report the problem in the Report a Bug guild (available from Guilds on the mobile app or from Help on the website) and we'll help you more there.

**Comment by lemoness** [comment] 2017-10-23 21:02
Should these labels be updated?

**Comment by Alys** [comment] 2017-10-31 11:20
I'm closing this because it will be fixed by https://github.com/HabitRPG/habitica/pull/8565 when that's been deployed to production.

**Closed as completed by Alys** 2017-10-31 11:20 UTC
Labels: priority: important, status: issue: needs investigation
