### ISSUE TITLE
Party member did not damage boss

### ISSUE THREAD

**Issue by philips999** [HabitRPG/habitica#4174] opened 2014-10-21 15:29 UTC
Hello,

One of the members of my party should have done a lot of damage to the boss that we are fighting, but no damage was done. My id is eefad08c-4193-42dd-bea8-46b81837cccc, the group id is  d5913e14-ecb9-4cd4-a56a-b5e74a03f7e7, and the party member Natrin whose attack did not happen is d3d82450-a2a8-4040-90c3-d791b5481390.

Thanks!
-Phil

![image](https://cloud.githubusercontent.com/assets/9252665/4721193/0084268e-5937-11e4-9224-d04162029e8a.png)

---

_edit by admin:_
# What to do if you have this bug:

**If you think you should have damaged your quest boss or should have found items for a collection quest, but you don't see any messages in party chat about your quest progress:**
1. Be aware that quest progress is not applied until the day **after** you have ticked off some To-Dos and Dailies. So if the quest started today, you will see quest progress tomorrow, and this is not a bug. You do not need to report anything here.
2. If your quest started yesterday or earlier but you don't see messages in party chat about your quest progress, click the "Fetch Recent Messages" button. If you now see a message about your own quest progress, then everything is working correctly and you can stop reading here.
3. If you still don't see your quest progress message, look at the quest box on the party page. Does your name appear in the list of participants? If it does not, then you are not participating in the quest. This could be because you joined the party after the quest started OR because the quest owner started the quest before you accepted the invitation. If the quest has not progressed very far, the quest owner might want to abort the quest and then restart it (the quest scroll will reappear in their Inventory for re-use). You do **not** need to report this situation here and there is nothing that admins can do to help.
4. If none of those points are applicable to you, please **_add a comment to this issue with your unique user ID (UUID)**_, which you can find on your [Settings -> API](https://habitrpg.com/#/options/settings/api) page. If others of your party members have the same problem, please tell us that too, but you don't need to give us their UUIDs (we can find them in your quest data in the database). We will then be able to fix the problem for you.

If you aren't sure about any of this, ask a question in the Newbies Guild ([Help -> Ask a Question](https://habitrpg.com/#/options/groups/guilds/5481ccf3-5d2d-48a9-a871-70a7380cee5a)) and we'll give you advice there.
##

**Comment by Alys** [comment] 2014-10-21 17:40
@philips999 Please look at the boss's current health and then reload the page and see if the health has changed by about 185 points. Then click the button which is next to the "send chat button") (i.e., the button that displays "fetch recent messages" when you hover over it). Check the boss's health again and also look to see if there are any new damage messages in the party chat. Is there now any evidence of that damage being done?

**Comment by philips999** [comment] 2014-10-21 19:27
Yes, I reloaded the page and also did the fetch recent messages button, and neither worked. Natrin also did these steps and it didn't work.

![image](https://cloud.githubusercontent.com/assets/9252665/4725302/5352c6ba-5958-11e4-9830-8e516ce21b22.png)

**Comment by Alys** [comment] 2014-12-15 20:32
We've been investigating cron failures in https://github.com/HabitRPG/habitrpg/issues/4313

Are these problems still happening for you?

**Comment by seahorsesrule** [comment] 2015-02-26 13:46
Hi, 

A few members of my party are not doing damage to the boss on our quest, despite being on the quest, completing tasks/dailies, and attacking with spells. Our dailies refresh properly at cron, but no quest boss damage is registered for us. I have refreshed, hard refreshed, synced, and hit "fetch recent message" on the party page many times.

This problem is affecting:
me 08ba47b6-7b90-4c42-b112-e5f0558c81f0 ,
30398645-85c9-4c60-8800-a8783cbe5fc0 (quest owner),
and possibly b06c47c6-5ca3-4ad0-8631-7190fa7aa0f1

It seems to have started after the server went down a couple days ago.

Our party # is 8f8081c2-dda6-4b41-9663-ba78913be7a9.

Thank you very much for your help. :)

Donna

**Comment by crookedneighbor** [comment] 2015-02-26 14:19
I've confirmed that all 3 members listed by @seahorsesrule are _not_ sleeping in the inn, but it looks like the key value for the quest is set to `null` for each of those members. The key value for the quest in the group is `ghost_stag`.

@seahorsesrule Could you go to your party page, hover your mouse over the boss and scroll down? It should show a list of participants. Would you mind taking a screenshot and posting it here? I'm curious to see if the three party members you posted are seen as being part of the quest.

The screenshot will have to be attached to a comment, sending it via an email will not work.

**Comment by seahorsesrule** [comment] 2015-02-26 14:43
@crookedneighbor Thanks for your help. It looks as if we are all listed as participants (neuron, caracal, and tucansam are the ones marked as null): 
![screenshot 2015-02-26 09 41 33](https://cloud.githubusercontent.com/assets/7607348/6393893/d497a2a2-bd9b-11e4-8649-bb780649b2e2.png)

**Comment by crookedneighbor** [comment] 2015-02-26 17:14
For the record:

### original quest objects:

``` javascript
// 08ba47b6-7b90-4c42-b112-e5f0558c81f0 
        "quest" : {
            "completed" : "",
            "progress" : {
                "collect" : {},
                "down" : 0,
                "up" : 0
            },
            "key" : null
        },

// 30398645-85c9-4c60-8800-a8783cbe5fc0
        "quest" : {
            "completed" : "",
            "progress" : {
                "collect" : {},
                "down" : 0,
                "up" : 3.455665585469748
            },
            "key" : null
        }

// b06c47c6-5ca3-4ad0-8631-7190fa7aa0f1
        "quest" : {
            "completed" : "",
            "progress" : {
                "collect" : {},
                "down" : 0,
                "up" : 6.789571141921265
            },
            "key" : null
        }
```

I changed `"completed"` to `null` and `"key"` to `"ghost_stag"` to match the quest data on another user in the party. I probably didn't need to change `"completed"`, but did it just in case.

Let us know the results tomorrow.

**Comment by crookedneighbor** [comment] 2015-02-26 17:48
@philips999 Any updates on this for you and your party?

**Comment by seahorsesrule** [comment] 2015-02-26 19:02
Thank you, @crookedneighbor. It looks like damage from one of the afflicted members (b06c47c6-5ca3-4ad0-8631-7190fa7aa0f1) has now shown up. I'll let you know on the other two.

I'm guessing this fix re-enters us into the quest and there is no (easy) way to recoup the damages we afflicted the past 2 nights? No big deal if that's true -- I just want to be able to clarify to my party members.

Thank you again for the very fast response.

**Comment by crookedneighbor** [comment] 2015-02-26 19:14
@seahorsesrule Yeah, unfortunately, it's impossible for me to tell what that damage was, so I can't apply it. If you know, I'll gladly apply it.

**Comment by TheresaVestal** [comment] 2015-02-27 15:23
My party has the exact same problem. In the 3 days since the crash 2 party members have inflicted no damage on the quest boss we are battling. Both have been active every day.

. One of them (me) has for sure completed a lot of dailies and cast at least 4 Brutal Smash spells that should have done a lot of damage. A third party member has been inflicting damage every day.The remaining 2 members have stayed in the inn ever since they were put there after the crash so I don't know if they are affected by this bug. 

Party members affected:
Me (Romi) 62eb37b9-8c8e-47d5-85cf-7b261895c4ee
Elijah Dale 67451853-e6a7-4786-b850-f9803c67f26b

Quest members:
![bug](https://cloud.githubusercontent.com/assets/11231419/6415038/f4de52c6-be50-11e4-8fca-a5bb76301faa.JPG)

Thanks-
Theresa Vestal

**Comment by TheBlueAmazingDragon** [comment] 2015-02-27 16:04
It seems to me that i left a party (in witch i could inflict damage), created a party, and now i cant deal damage anymore

**Comment by seahorsesrule** [comment] 2015-02-27 16:05
@crookedneighbor None of us know what damage we inflicted, but we're fine with it being lost. Thank you so much for all your help! We really appreciate it.

**Comment by JLSC224** [comment] 2015-02-27 19:24
Hello, I'm having this problem with my party as well. When I look at who's in the party, I am among the list, yet even after I've completed my dailies and to-do's for two days straight I have not done any damage while the other party members have. My information is as follows:

Group ID: 0bc49772-8a67-4231-92af-639c253e6f69

User ID: f63cd1e0-6a19-4143-9082-d36ba11c44d2

Thank you!

**Comment by Alys** [comment] 2015-02-28 05:09
@JLSC224 You aren't dealing damage to the boss because you aren't part of the quest. It is possible to be in a party without being a quest participant - this can happen if the quest starts before you joined the party, or if the quest owner chooses to begin the quest early, before you have accepted the invitation. If you look at the list of quest participants, you'll see that you are not included. If you'd like more information, have a look at the wiki's [Quests](http://habitrpg.wikia.com/wiki/Quests) page, and if you have questions, go to Help -> Ask a Question and you'll find a lot of people there who can give you answers, including me. :)

**Comment by JLSC224** [comment] 2015-02-28 05:24
Oh......... I sincerely apologize for wasting your time with such a trivial matter. I guess I looked at party participants rather than the quest participants. Thank you so much for your time!! :)

Jacob

**Comment by Alys** [comment] 2015-02-28 05:34
@JLSC224 No worries at all! :)

@TheresaVestal I've fixed the problem for you and Elijah Dale. You should both deal damage the next time your crons run (probably tomorrow morning). Post again here if that's not the case or if you see anything else wrong.

FYI devs: it was the same problem that @crookedneighbor noticed: the key value for the quest was set to null instead of atom2.

@TheBlueAmazingDragon Please tell us your unique user ID - you can learn how to find it from step 6 in [these instructions](https://github.com/HabitRPG/habitrpg/issues/2760).

**Comment by TheresaVestal** [comment] 2015-02-28 05:35
Thanks so much Alys.

**Comment by TheBlueAmazingDragon** [comment] 2015-02-28 06:15
User ID : 044ddd26-c37b-4cf9-acff-08c2129d6f93
Group ID : 6e296f5f-cbf5-4f7a-931d-e5bdc6617ca4
It also seems that today I did deal damage, but I don't know if its fixed or not

**Comment by Alys** [comment] 2015-02-28 06:19
Since you've dealt damage, then everything is fine and there's nothing I need to do. Thank you for telling me that! You saved me some time! :) You should find that you continue to deal damage from now on, but do tell us if that changes!

FYI, damage is reported in party chat on the day after you accumulate it, so you'll never see any damage on the first day of a quest.

**Comment by Alys** [comment] 2015-02-28 06:22
ATTENTION MODERATORS: There's a new "What to do if you have this bug" section at the top of this issue. Feel free to adjust it as you see fit. Especially if I've made it too complicated. :)

**Comment by TheBlueAmazingDragon** [comment] 2015-02-28 06:41
User ID :
Group ID : 6e296f5f-cbf5-4f7a-931d-e5bdc6617ca4

**Comment by pjay-io** [comment] 2015-02-28 11:05
3bf2bbf4-8ae0-4aa9-9370-bcbcd48c9f5f

My cron runs at 03:00, the other party member' cron runs at 00:00. He did the final blow, I got the xp and gold after 00:00, he did also. Now the damage isn't showing in the party chat and the boss is still alive with the 3hp remaining just like yesterday.

Neither my damage, neither his is showing. We are not in the inn and our tasks are processed.

**Comment by Alys** [comment] 2015-02-28 11:46
@PJay-  I'm sorry about that! I've removed the remnants of the quest. It should now not be showing on your party page, and your party should be able to start another quest - if you have any trouble doing that, comment here and we'll fix that too!

In case you are curious, what happened was this:
One party member did 4.9 damage in the past day or two, but that damage was actually applied twice, which is due to another bug https://github.com/HabitRPG/habitrpg/issues/2805 (not due to anything your party had done wrong). If you look in party chat, you'll see two identical messages for it. If that damage had been applied only once, your party's total damage to the boss would have been 97, leaving 3 HP remaining on the boss's health. But because it was applied twice, it took you over the 100 damage needed to kill the boss. So, when the crons ran, both your accounts were updated as if the boss had been killed. However for the quest itself, which is calculated separately from your accounts, the duplicate 4.9 damage was not counted twice, meaning that the boss was still alive.

I'm sorry it didn't go smoothly for you. It's likely that your future quests will be trouble-free. Although you will see quite a few error reports here about quests going wrong in various ways, HabitRPG has tens of thousands of users, and very many quests are done without any problems. However if anything looks wrong with any future quests, be sure to tell us and we'll help as best we can!

Ping @crookedneighbor  -- FYI in case you ever come across this.

**Comment by pjay-io** [comment] 2015-02-28 12:13
@Alys Thank you for the quick response! Everything is working again.
I didn't notice the duplicate damage. I hope the increased load on the application is managable btw, sometimes I get load times of 3 seconds for one asset!

**Comment by NOMINDTR** [comment] 2015-06-03 19:49
Started the Quest yesterday. I did not damage the boss today, I figured I could have.
I am participating.

User id 70d88957-673a-4edd-b97e-f1ecb018dd89

Group ID: 11a2456c-8b39-438c-82c7-1467e10564a6

Thank you

**Comment by libelt** [comment] 2015-07-27 09:19
Hello! I have the same problem! Me and my friend are fighting the boss since yesterday. 
Today we were to deal the first damage and on the group chat only mine displays. As if my friend did no damage. 
He is a starfish now, due to potion(yesterday 15:22). Do you think thats the case? Also I did read somewhere that the potion should wear off at next Cron(which we are already after, right?)

I clicked "Fetch Recent Messages", does not work. 
We are all on the list of participants.

my friend's ID; c49cbcad-37e2-4ef6-8fb4-14407d021101

It's the frist, Basi-List quest. Thank you for your help!

**Comment by Alys** [comment] 2015-07-27 09:35
@kamykkamyk Has your friend used HabitRPG yet today? It's sounding as if he has not. Cron runs when you use HabitRPG for the first time each day. The starfish always wears off when cron runs (and never stops boss damage being done).

**Comment by libelt** [comment] 2015-07-27 10:17
@Alys Yes, thank you, that was the case. Sorry for the fuss. : )

**Comment by Alys** [comment] 2015-07-27 12:11
@kamykkamyk No worries! :) Cron is often confusing until you're used to it!

**Comment by stonemanm** [comment] 2015-09-24 14:41
Hi! I should have done a LOT of damage to the Laundromancer this morning, but no matter where I open Habitica or how I refresh, it doesn't seem to take effect. I've tried the iPhone app, Chrome, and Safari so far. None of steps 1-3 helped at all. I really appreciate the help!

User ID: 20bd4137-648c-4ad7-a5b2-c0000e61f2da
Group ID: 8f40430f-625d-4b80-aa08-b7bd1f26ffba

EDIT: Another user in my group is also having the same problem. ID: 2a789d36-619d-4131-b8ed-1ab271a92b0e. Two other group members have had no problem, and we haven't tested the fifth yet.

**Comment by Alys** [comment] 2015-09-24 19:35
@stonemanm's report is confirmed. Both players are in the quest, both damaged the boss on their previous cron, but not on their most recent cron. 

@stonemanm We'll try to work this out today but we might not be able to find out what went wrong before tomorrow. Could you please comment again tomorrow to tell us whether your not it happened again?

**Comment by stonemanm** [comment] 2015-09-24 20:22
@Alys Absolutely. If you don't say otherwise by tomorrow, I'll check and let you know then. Thank you!

**Comment by stonemanm** [comment] 2015-09-25 08:11
@Alys For whatever reason, I was able to damage the boss today. Still no clearer on why yesterday's attack failed to materialize, but it's nice to know, at least.

@Alys EDIT: I tried buffing the party today (using Earthquake to boost INT) and as best I can tell, it had no effect. Is it possible that the party is no longer considering me a member?

**Comment by ruby1110** [comment] 2015-10-14 13:59
Hello.  This is my second day of not damaging my party's quest boss.  I'm not in the Inn, and I'm the one who started this quest (Laundromancer), so those aren't the problems.

User ID:  dbe08e20-657d-464c-80d1-7a54369a6774
Group ID:  bc9f45d5-3177-4cd7-82b8-43cb72ff115f

I'm not sure if this has anything to do with the problem, but when I refresh the party page it temporarily believes that I am partyless.

I will also not be using any spells (especially Brutal Smash) today in case that is what is causing the problem.

**Comment by ruby1110** [comment] 2015-10-15 06:06
Cron just happened.  No damage to boss.  Evidently doing spells is not the issue.  I'm still have the party refresh problem (still unsure if that's related/how to fix it).

**Comment by Alys** [comment] 2015-10-15 07:44
@ruby1110 Sorry about that! When the quest started, the correct information hadn't been added to your account, so each time you cronned, your progress couldn't be added to the quest. I've updated your account now so you should start seeing quest progress from yourself from your next cron. Post again here if you don't.

**Comment by ruby1110** [comment] 2015-10-16 13:47
@Alys Everything seems to be working normally now.  Thank you!

**Comment by WanderingPat** [comment] 2015-11-13 13:43
I'm running into the same issue as ruby1110.  I started the basi-list quest with my party.  I did the first damage, but haven't done anything else in the last 2 days.  Since I started this quest, I know I SHOULD be on it.  My ID: d2f54671-fd08-4da4-b3ed-8de3165b768c
![partylog](https://cloud.githubusercontent.com/assets/15042744/11147240/932f27ea-89e2-11e5-9fda-467b03368495.PNG)

**Comment by madisonparklove** [comment] 2015-11-14 12:43
For 3 days in a row now, when my cron resets, I don't show up at all in the quest chat as having done damage or taken damage. I am participant in the quest and I am not resting in the inn. ID: 9d462b64-137a-4a91-800b-02e0bf1cd2ca
![screen shot 2015-11-14 at 7 42 35 am](https://cloud.githubusercontent.com/assets/13150260/11163591/5d4dcffc-8aa3-11e5-8582-745d5ecab670.png)

**Comment by Alys** [comment] 2015-11-14 13:32
@WanderingPat and @madisonparklove You should both find that you do damage to the quest boss on your next cron.

For our reference: Both of your accounts were missing a value for `party.quest.key`, even though you were listed as being in the quest's members object.

**Comment by madisonparklove** [comment] 2015-11-14 14:22
Thank you!

**Comment by luminerium** [comment] 2016-02-20 16:41
I have this problem. I've dealt damage every day since the current quest started but today I just didn't show up in the chat. Cron definitely did happen. UUID: 5d54efc5-2e92-409c-9f4a-361fc59c8273

**Comment by Alys** [comment] 2016-02-21 09:13
@theyliveforever There's nothing wrong in your account (i.e., you aren't suffering from the missing `party.quest.key` data that other players here had). Occasionally it just happens that quest damage messages don't show up and/or quest damage isn't applied on one day, probably if you cron during a period of particularly heavy server load. You should do quest damage tomorrow.

**Comment by luminerium** [comment] 2016-02-21 18:47
@Alys I see, thank you!

**Comment by ditabug** [comment] 2016-03-01 18:12
Hi! the other member in my party was able to do damage but i was not. my ID number is 5240ba4c-aabd-484c-9129-285c77ad196a and the Group ID is: 314e12e7-a5a6-4ef6-9062-b3515f926611

Thanks!

**Comment by Alys** [comment] 2016-03-01 20:30
@ditabug Were you Resting in the Inn (http://habitica.wikia.com/wiki/Rest_in_the_Inn ) over the past day? If so, that's what would have prevented the damage.

If you weren't Resting:
It looks like you've missed only one boss damage event, and occasionally it just happens that quest damage messages don't show up and/or quest damage isn't applied on one day, probably if you cron during a period of particularly heavy server load or server errors (there more more errors than usual a few hours ago). You should do quest damage tomorrow - if you don't, please post here again.

**Comment by vkuehne** [comment] 2016-03-17 13:36
This happened to me today. Checked all other options (fetch recent messages etc.). Cron ran well for my other party member.

My ID: 00df024c-c000-4631-b7a2-62279cc68cee

Thanks for looking into it! :)

**Comment by Alys** [comment] 2016-03-17 13:48
@vkuehne There was a bug today that caused this to happen for some players. We've already fixed it and corrected the affected accounts, including yours, but we didn't get to yours in time for your cron. Sorry about that! You should find it works normally tomorrow - if it doesn't, please post here again. If you can estimate how many items you should have found today, I can add them to your account for tomorrow.

**Comment by vkuehne** [comment] 2016-03-17 15:01
thanks for the quick reply. No idea how many I should have found - haven't done that many collection quests, but I had 117 Perception or so, so should have found quite a lot I guess :D

**Comment by Alys** [comment] 2016-03-18 09:45
@vkuehne You found 5 Fire Coral and 3 Blue Fins today so I've given you that many again for your progress tomorrow (in addition to what you'll earn normally).

**Comment by vkuehne** [comment] 2016-03-19 15:56
thanks, so I got 12+9 today, all good, thanks!

**Comment by Incendiaeternus** [comment] 2016-03-26 16:10
This just happened to our group, I waited a day for the Cron to go past, and nothing. This was after accepting the invite, and when I go back to check on the participants list, it only lists the quest starter, despite having accepted the invite in time. 

ID: 1ff295e0-1f4c-4330-a04c-89e0e4ac1421

**Comment by Alys** [comment] 2016-03-26 23:21
@Incendiaeternus  I've added you to the quest. If it happens again for future quests, the quest owner can abort the quest. The quest scroll will go back into their inventory and then they can use it to resend the quest invitations.

**Comment by wizdave** [comment] 2016-05-04 15:09
This happened to me today as well - I checked all the items listed by admin in the original post, but my cron does not appear to have run today. See additional details below:

I just started using Habitica yesterday (May 3) and completed all of the dailies that I had setup, but the dailies have not reset yet today. Additionally I have not done any damage to the party quest boss that I started yesterday (I am the quest owner). My custom day start is set to 2 AM and my time zone is UTC-5:00, but the daily cron appears to have not run (my user ID is 10d32882-e461-47db-b65d-14c70ef52a8f). How can I force the cron to run for today? I have tried reloading the page, clicking the sync button, and logging out and back in and my dailies still show grey and completed from yesterday.

**Comment by Alys** [comment] 2016-05-04 23:48
@wizdave There can sometimes be a problem with cron not running after the first day on Habitica. We aren't sure why but we're almost at the end of a big project to do some code refactoring, so if that doesn't fix the problem, we'll be in a better place to investigate it after that. Regardless, your Dailies should reset correctly tomorrow. Comment again here if they don't. The damage you've accumulated towards defeating the quest boss should be applied tomorrow, not lost. Sorry about the trouble!

**Comment by Amuchia** [comment] 2016-05-13 14:42
Someone in my party (user id: 4db332ad-a42c-44a0-9d12-7ee8b16b86a6 ) checks off their dailies before cron but doesn't do any damage to the boss even though they're part of the quest (a quest that just ended, so alas I can't screenshot the quest's participants).

**Comment by Alys** [comment] 2016-05-13 22:44
@Amuchia Are they resting in the inn each night? If so, that will stop their quest progress being applied. See http://habitica.wikia.com/wiki/Rest_in_the_Inn for details. If that's not it and if the person continues to not make progress on the next quest, ask them to post here so that we can go through some troubleshooting steps with them.

**Comment by ghost** [comment] 2016-05-31 03:03
Hello!  Since the recent update, I haven't been finding any quest items for the past 9 days.  I first had an issue with not displaying in the party, but after a few days that was fixed (I think it was just a display error).  Now, despite doing Dailies and habits, I've found nothing each day.

my user ID:  09232b39-47ef-4264-8b49-ef4dafeabe67

any help would be appreciated!  Thank you!

**Comment by crookedneighbor** [comment] 2016-05-31 03:10
@AnB749 You did not have the quest key on your user object for some reason. I've added it.

**Comment by ghost** [comment] 2016-06-01 04:14
@crookedneighbor Thanks for that, I will let you know how it works.  So far, there hasn't been anything found, but I will check again tomorrow.  Fingers crossed!

**Comment by SalamandaBlue** [comment] 2016-06-01 15:46
Good mornin', 

I've been apart of the same quest for a few weeks now, but after the big Habitica update online I can't seem to damage the boss my party is fighting. Actions like casting spells for the group still show up, but no damage is done from my dailies, to-do's, or positive habits. I'm the quest owner, I'm not resting at the inn, and another member of my party is damaging the boss just fine. 

My user ID is: a1a7c39a-239d-4b80-8b18-d41013ce3642
And the group ID is: dae66ef-8599-472a-8b4e-eff2a74f20ef

Thanks for the help :)

**Comment by ghost** [comment] 2016-06-02 01:56
@crookedneighbor , it's me again.  So I checked this morning and again I have found no items relating to my quest.  I understand that it's possible to not have found anything, but seeing as I have done all my Dailies, and quite a few good habits, I would think I would at least have found something.  Do you have any more suggestions for things I should do, or should I wait a little longer?

My user ID:  09232b39-47ef-4264-8b49-ef4dafeabe67

Thanks again!

**Comment by crookedneighbor** [comment] 2016-06-02 02:39
@SalamandaBlue @AnB749 you both did not have keys on your party.quest attribute again... something must be removing it on accident. What platforms do you use?

I'm working on a PR that will make all these operations run on the server using the group object instead of relying on the user object, so in any case, this should be fixed soon. https://github.com/HabitRPG/habitrpg/pull/7570

**Comment by ghost** [comment] 2016-06-02 04:09
@crookedneighbor Thanks for the quick response!

I primarily use 3 different systems with Habitica.

I use Google Chrome with Windows 8.1 Pro,  Google Chrome with Windows 7 Home, and the Android App.

**Comment by SalamandaBlue** [comment] 2016-06-02 04:43
@crookedneighbor  Thanks for looking into this. I use the same as @AnB749 , that is the Android app on my phone, and Google Chrome with Windows 8.1 
I actually just switched back to Windows 8 recently, and didn't have this problem on Windows 10.

**Comment by ghost** [comment] 2016-06-04 10:50
Hey @crookedneighbor , the last two days I have been finding items.  Thank you so much!  I hope @SalamandaBlue is doing ok with their boss.

**Closed as completed** 2016-06-05 11:18 UTC
Labels: type: memorable

**Comment by OrangeBoreal** [comment] 2016-07-13 09:14
Hello, 
No damages dealt for me this morning, nothing showing up in the chat even when I click on "Fetch recent messages". 
I'm the quest owner, not resting in the Inn, used the iOS app to connect first this morning. 
My ID: bc612705-7cb4-4f3e-ba39-0871980b1a11
Group ID: f14cdfd7-cc6e-47e9-a5a0-fc38ad140efe

Thanks for the help !

**Comment by Alys** [comment] 2016-07-13 09:20
@OrangeBoreal Sorry about that, and thanks for letting us know! Usually that happens just once so you should be back to normal tomorrow, but please tell us if it happens again on this quest or any future one!

**Comment by lucastanhe** [comment] 2016-10-17 10:15
Hi, it's been 3 days and still no damage dealt for me, I've followed all the steps given in this thread. The damage display states that I should deal 94.7 damage to the boss.

Here is my ID: 94a2a16e-f6f8-4343-9ac7-71427127677b
Group ID: 2a592829-f00a-467e-a5aa-0bff845c0ebf

**Comment by Alys** [comment] 2016-10-17 10:41
@lucastanhe From what I can see in our logs, you've been resting in the inn at night over the past few days. Tell us if that's not the case.

Resting prevents your accumulated boss damage from being applied - if you have questions about that, you can read about it on the wiki at http://habitica.wikia.com/wiki/Rest_in_the_Inn or ask at Help > Ask a Question from the habitica.com website's menu (or Guilds > The Newbies guild on the mobile app, but it's not just for new players).

**Comment by droitducoeur** [comment] 2017-01-17 13:40
9b100a2f-6caa-4c21-bd59-40b361dd2e79
 I have this problem, I cannot fight any bosses, when I am in the group or not

ID van de groep: d5413f93-a81a-43d3-8f0f-dbe5ec36b139

**Comment by Alys** [comment] 2017-01-18 20:58
@droitducoeur I can see an attack from your account in the past day approximately. If you notice not attacking again when you think you should, tell us and we'll look into it again. The best way to report it to use is in the Report a Bug guild, which you can get to from the Help menu in the website or from Guilds in the website and mobile apps.

**Comment by MrFifths** [comment] 2018-02-01 20:10
9b7bc28f-77a2-4e6b-a3e2-9cfd1663f4b8

I have this issue. Not doing any dmg two days in a row now despite casting dmg spells and completing tasks.

I am shown in party list, have refreshed messages, and still nothing. Other party members are doing dmg OK.

**Comment by veddy69** [comment] 2018-04-11 20:07
Im new to the app but my Friend whos Been playing for sine time cant find the problem. It just says "dmg pending" but then it reset the dmg without dealing it.. my number is 427b0585-f863-44e3-8c91-2703ed460668

**Comment by Gimdal** [comment] 2018-10-14 12:59
Same issue; i have lots of pending damage, and using my damage dealing skills eats away my mana, but the damage is never registered.
1ac8b6d8-75bd-499c-a0e0-8f81fac0b758

**Comment by majestic-owl448** [comment] 2018-10-14 18:03
@MrFifths @Gimdal @veddy69 : when you have bug reports like this the best thing you could do is write in the [Report a Bug](https://habitica.com/groups/guild/a29da26b-37de-4a71-b0c6-48e72a900dac) guild - in a closed ticket like this you don't have much chance of receiving an answer
