### ISSUE TITLE
I just 'died' for no reason

### ISSUE THREAD

**Issue by meowcules** [HabitRPG/habitica#5608] opened 2015-07-13 23:20 UTC
When checking off one of my dailies despite having nearly full health and leveling up yesterday.  Using google chrome browser.

**Comment by Alys** [comment] 2015-07-14 10:32
Ticking off the Daily would not have caused your death. Instead, something else happened at the same time, most likely damage from a boss quest caused by one of your party mates not having done all their Dailies. For information about this, please see [Death Mechanics](http://habitrpg.wikia.com/wiki/Death_Mechanics) on the wiki, in particular the section called "Sudden, Unexpected Death", but other sections on the page might be of use to you too. If you have questions about anything you read there, the Help -> Ask a Question menu option in HabitRPG will be the fastest way to get answers - it takes you to a guild where a lot of experienced users help other players with their questions.

If, after reading that, you think that your death was caused by a bug, please comment here with your User ID so that we can investigate. To find your User ID, go to Help -> Report a Bug and see step 6 of the instructions.

**Comment by Alys** [comment] 2015-07-16 04:53
@meowcules I'm closing this on the assumption that the wiki information explained what happened, but we can reopen it if an investigation is needed.

**Closed as completed by Alys** 2015-07-16 04:53 UTC

**Comment by jamesmgg** [comment] 2015-09-07 05:41
Er... I had this same issue when ticking off a daily. I believe I did see a boss/quet thing flash,but it went away immediately. This happened even though I wasn't actively doing the quest and while currently not in a party. user is is 3f2abcfa-d140-4c8f-859e-61ffea50cf4d

**Comment by Alys** [comment] 2015-09-07 17:29
@jamesmgg I've noticed that your account had been inactive for a while until relatively recently which means it might have had a lot of old activity to report to you - that might explain the boss/quest thing. Do you recall if it was about an Abominable Stressbeast?

Could you please tell me when you started using your account again? That might help me work out what caused your death.

Also, are you using Habitica in two or more devices - PC(s), phone(s), tablet(s)?

**Comment by jamesmgg** [comment] 2015-09-22 17:54
I think I just realize what happened.... I had some uncompleted dailies, and it was just after midnight when I was ticking one off, and perhaps that's when the app updated and told me I died because I hadn't completed the dailies and lost health at midnight. 

@Alys my slight annoyance is that I sleep after midnight and I complete a daily after midnight, but it's already too late. Is there any way to adjust this so day ends, say at 2am?

**Comment by Alys** [comment] 2015-09-22 20:57
@jamesmgg Yes, use [Fix Character Values](http://habitica.wikia.com/wiki/Fix_Character_Values). If you have questions about that, either ask here or go to the habitica.com site and click on Help -> Ask a Question. That takes you to a guild with many experienced users who are familiar with all of Habitica's features. You're likely to get answers to questions there faster than on GitHub because there's more players who monitor that guild. :)

**Comment by crookedneighbor** [comment] 2015-09-22 22:49
@jamesmgg Regarding setting it to 2AM, you can do that with the custom date start option in settings.

**Comment by Alys** [comment] 2015-09-22 23:46
`headdesk` Sorry, yes, [Custom Day Start](http://habitica.wikia.com/wiki/Custom_Day_Start) not Fix Character Values @jamesmgg

**Comment by jamesmgg** [comment] 2015-09-25 04:53
You guys rock. Thank you. :)
