### ISSUE TITLE
Level up does not occur when backstabbing

### ISSUE THREAD

**Issue by JasonGross** [HabitRPG/habitica#2611] opened 2014-01-28 10:52 UTC
It is possible to get over the XP required to level up, without leveling up, by using spells.  It seems that level up is not appropriately triggered on spells?

**Comment by deilann** [comment] 2014-01-28 20:32
Correct! Quests do this too. It'll be fixed at some point.

**Comment by colegleason** [comment] 2014-01-29 20:14
dupe of #2598

**Closed as completed by colegleason** 2014-01-29 20:14 UTC
