### ISSUE TITLE
Mount Icons

### ISSUE THREAD

**Issue by k8sullyvan** [HabitRPG/habitica#3651] opened 2014-06-24 12:05 UTC
It looks like the 'Mystery paw' for the mounts and the pets has the same spacing, but while that is fine for the pets, as the mounts are bigger it leads to uneven columns with partially complete collections. I imagine it is a case of adjusting the gaps between the mount 'paws' and that would probably sort out the problem.

![screenshot 2014-06-24 13 01 13](https://cloud.githubusercontent.com/assets/7197274/3370885/763fe5fa-fb97-11e3-8857-5522acc811aa.png)

**Comment by SabreCat** [comment] 2014-06-25 02:19
Duplicate of #2084.

**Closed as completed by SabreCat** 2014-06-25 02:19 UTC
