### ISSUE TITLE
Challenge can't be updated more than twice (without reloading the page)

### ISSUE THREAD

**Issue by HydeHunter2** [HabitRPG/habitica#11141] opened 2019-04-27 10:40 UTC
### General Info
  * UUID: af1477b6-509a-4611-b851-d7a8e3a9c02a
  * Browser: Safari
  * OS: OS X

### Description
Leader of Challenge cannot update it more than twice without reloading the page.
Also, after each update, some interface element disappears(Look at the screenshots)

Initial state | After the first update | After the second update.
------------|----------------------|----------------------
![GitHub](https://user-images.githubusercontent.com/46248839/56848500-9f918800-68f2-11e9-8777-64a2fd169b83.png) | ![GitHub](https://user-images.githubusercontent.com/46248839/56848505-b3d58500-68f2-11e9-97a4-aa136646d249.png) | ![Github](https://user-images.githubusercontent.com/46248839/56848510-c3ed6480-68f2-11e9-81f1-4055b0f3062a.png)
![Github](https://user-images.githubusercontent.com/46248839/56848546-13cc2b80-68f3-11e9-997e-84530d8a2de4.png) | ![Github](https://user-images.githubusercontent.com/46248839/56848546-13cc2b80-68f3-11e9-997e-84530d8a2de4.png) | ![Github](https://user-images.githubusercontent.com/46248839/56848552-1fb7ed80-68f3-11e9-84df-2a6ad5f6117e.png)

That's all. After the second update, You can't press the button `Update Challenge`

Alys asked to create this issue.

#### Console Errors
After several updates of a challenge:
1) `TypeError: undefined is not an object (evaluating 'this.workingChallenge.group._id')`
This error occurs [here](https://github.com/HabitRPG/habitica/blob/d198e23de6801bb9ca97feb0262712b1339e7552/website/client/components/challenges/challengeModal.vue#L347).
2) `TypeError: t.trim is not a function. (In 't.trim()', 't.trim' is undefined)`
This error occurs [here](https://github.com/HabitRPG/habitica/blob/d198e23de6801bb9ca97feb0262712b1339e7552/website/client/components/challenges/challengeModal.vue#L455).

**Comment by gautamz07** [comment] 2019-06-03 20:51
Can confirm this issues exists , 

@HydeHunter2 when the update button jams after a couple of attempts can you confirm that the issue you see in the terminal is::-

> Error in v-on handler: "TypeError: key.trim is not a function

**Comment by HydeHunter2** [comment] 2019-06-04 14:29
@gautamz07 -- Thanks!
Yeah. There is the error in console.
I updated issue

**Comment by gautamz07** [comment] 2019-06-06 19:04
Tested this locally seems to be caused by this line [HERE](https://github.com/HabitRPG/habitica/blob/develop/website/client/components/challenges/challengeModal.vue#L347).

Can somebody elaborate on what exactly is the purpose of the following lines of code ?

`this.workingChallenge.group = this.workingChallenge.group._id;
 this.workingChallenge.categories = [];`

`this.workingChallenge.group` is essentially an object and `this.workingChallenge.group._id` is just a string , this somehow does't make alot of sense .

**Comment by paglias** [comment] 2019-06-06 19:12
`this.workingChallenge.group` seems to be 
a string actually https://github.com/HabitRPG/habitica/blob/develop/website/client/components/challenges/challengeModal.vue#L367

Not very clear, I agree

**Comment by gautamz07** [comment] 2019-06-07 23:38
@paglias  when `challenge` inside `computed()` is console.logged I.E. `console.log(this.$store.state.challengeOptions.workingChallenge);` it gives this value  [see screenshot](https://i.imgur.com/EsmkCrl.jpg).

But if you `console.log(this.challenge)`; inside `setUpWorkingChallenge ()` , it gives this value , [see screenshot](https://i.imgur.com/IEgnrIg.jpg) , where exactly does the value of  `this.challenge` change then ? i have scanned the whole component , but am a bit clueless about this still , can somebody shed some light on this ?

**Comment by paglias** [comment] 2019-06-09 14:38
I think it comes from here https://github.com/HabitRPG/habitica/blob/develop/website/client/components/challenges/challengeModal.vue#L247 ? So from the state

**Comment by gautamz07** [comment] 2019-06-12 21:48
My conclusion is the below line of code needs to be removed completely , it makes no sense. sould i submit a pull with the same ?

`this.workingChallenge.group = this.workingChallenge.group._id;` [this line](https://github.com/HabitRPG/habitica/blob/develop/website/client/components/challenges/challengeModal.vue#L347).

Also `group : '' ;` might need to be changed to `group : {}` , [line here](https://github.com/HabitRPG/habitica/blob/develop/website/client/components/challenges/challengeModal.vue#L216)

taughts ?

**Comment by Xaz16** [comment] 2019-09-14 08:06
Hi folks!
@gautamz07 will you work on that? 
@Alys can I take this one?

**Comment by Alys** [comment] 2019-09-16 10:42
@gautamz07 I'm so sorry we never replied to you back in June! Are you still interested in doing a pull request for this? If so, I'll mark this issue as in progress for you.

(@Xaz16 Sorry about the delay but we'll see what @gautamz07 says first.)

**Comment by SabreCat** [comment] 2019-11-01 17:57
Going to mark this as available for help, but @gautamz07 / @Xaz16 definitely jump in if you're still interested in your prior claim!

**Comment by Xaz16** [comment] 2019-11-01 21:54
@SabreCat sure

**Comment by Xaz16** [comment] 2019-12-29 17:18
About this one: 
It looks like issue is not relevant anymore, I test in on Chrome and Safari on OSX. I edited challenge that not bound to guild or party, bound to guild, bound to party. It I edited in about 5 times without any errors. 
Suggest to close it @paglias @Alys 
One thing that I found: after editing short name it is not updated at all (nor first edit, nor second... etc)

**Comment by Alys** [comment] 2019-12-30 05:05
Darnit, I logged a duplicate bug for this issue: https://github.com/HabitRPG/habitica/issues/11561. That was fixed in https://github.com/HabitRPG/habitica/pull/11591 so yes, this issue is no longer needed. Thanks @Xaz16 !

**Closed as completed by Alys** 2019-12-30 05:05 UTC
Labels: section: Challenges, priority: medium, help wanted
