### ISSUE TITLE
problem with challenges page

### ISSUE THREAD

**Issue by locheed9** [HabitRPG/habitica#5874] opened 2015-09-01 22:01 UTC
Recurring error message from top right of screen, stating: 
Please reload: error runner error: overflow sort stage buffered data usage 33818640

**Comment by locheed9** [comment] 2015-09-01 22:01
PLEASE AND THANK YOU MY SISTER WOULDN'T SAY IT

**Comment by zedutch** [comment] 2015-09-03 21:05
I think this is a duplicate from #5839

**Comment by crookedneighbor** [comment] 2015-09-04 02:02
Yes, this does sound very much like a duplicate of that issue. Closing this one. You can track the progress by clicking the subscribe button on that issue.

**Closed as completed by crookedneighbor** 2015-09-04 02:02 UTC
