### ISSUE TITLE
Damages and death while sleeping in the inn

### ISSUE THREAD

**Issue by snouz** [HabitRPG/habitica#4899] opened 2015-03-21 18:44 UTC
I died while being in the inn. I'm in the inn since wednesday (I was sick) but when I came back, I was dead. Here is a screenshot
http://i.imgur.com/WPga9qL.png

I couldn't find any related issue when typing "death inn"

**Comment by snouz** [comment] 2015-03-21 18:52
I died while being in the inn. I'm in the inn since wednesday (I was sick) but when I came back, I was dead. Here is a screenshot

**Comment by Alys** [comment] 2015-03-21 22:15
Are you participating in a boss quest in a party? If so, damage caused by your party mates can still kill you. For more information about that, go to Social -> Tavern on the website and see the message around the Inn's button. 

You can see damage done from the quest on the Party page - click the Fetch Recent Messages button and then look for red messages.

**Comment by SpenserJ** [comment] 2015-07-21 02:47
This can probably be closed after four months with no reply from @snouz

**Comment by crookedneighbor** [comment] 2015-07-21 12:57
@snouz I'm closing this now, but if you're still having issues, please reopen it.

**Closed as completed by crookedneighbor** 2015-07-21 12:57 UTC
