### ISSUE TITLE
Browser slowdown/crashes

### ISSUE THREAD

**Issue by eiron** [HabitRPG/habitica#1437] opened 2013-09-05 19:58 UTC
Not sure if it is the size of my todo list, but I experience long periods of inactivity in my browser (it being Firefox it locks everything down) and fairly frequent crashes. Running the beta version of the site does not significantly improve things for me.

(Sorry for the vague issue flag, but I am sure by talking we can work it out.)

**Comment by lefnire** [comment] 2013-09-05 20:05
how large is your task list (like, one screenful, 100s, just ballpark)? we're only looking at issues for beta.habit right now, since that's replacing prod in a day or two. I think we're gonna have to do some sort of optimization by rendering anything that won't change via jade rather than angular, but it's gonna be some overhaul - we may have to tackle this a bit down the pike

**Comment by lefnire** [comment] 2013-09-10 20:36
dupe of https://github.com/lefnire/habitrpg/issues/1499, let's follow up there

**Closed as completed by lefnire** 2013-09-10 20:36 UTC
