### ISSUE TITLE
Notifications replay in Firefox mobile

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#4756] opened 2015-02-25 20:17 UTC
Weird issue, I don't know where to start on this one.  
Reproduced on Android 5.0.1 (Nexus 9) and Cyanogenmod 12 (HTC One M8), both on Firefox mobile, on the site (not the app). Couldn't reproduce on Chrome mobile, and a friend couldn't reproduce on her iPhone/Safari, so I guess it's only showing up in Firefox mobile.

When the site is loaded on the browser, there's a unused space on the top right corner. When tapping this space on Firefox mobile, different notifications show up, beginning with "Level Up", then "+/- MP", "+/- XP" and "+/- Gold" (see screenshots below).

Tapping repeatedly make these notifications show up, disappear, and show up again (always with the same values in a same session). I guess that these values are the last loaded by the browser. I also have to say that it doesn't modify in any way my stats, which stay the same (which is why I think it's only a notification replay).  

I can reproduce this weird behavior at will, as long as I'm in portrait mode. I don't reproduce it on landscape mode.
My User-ID, in case it can be helpful to track this behaviour : a75eb6f8-5a29-482f-a971-7aff7438da86

![screenshot_2015-02-25-20-12-29](https://cloud.githubusercontent.com/assets/4882150/6379146/658c9752-bd30-11e4-94b1-10400f60185a.png)
![screenshot_2015-02-25-20-26-31](https://cloud.githubusercontent.com/assets/4882150/6379147/65925b4c-bd30-11e4-9b92-1f2c62778045.png)
##

**Comment by crookedneighbor** [comment] 2015-02-25 22:49
Interesting. Would someone with an android device download firefox mobile and attempt to reproduce this issue?

**Comment by deilann** [comment] 2015-02-26 00:43
This seems to me like it's just the cached local version updating to
changes made... That actually happens on all browsers.

I personally use Firefox mobile on my Android device and it's no different
than using any other browser in this instance. I'd imagine you didn't have
any issue with Safari because you'd never used Safari before, so there was
no cached local version to update!

**Comment by ghost** [comment] 2015-03-01 20:41
I tried again to reproduce it in Chrome for Android, since it was also the first time I loaded the site on this browser. I still can't reproduce this behavior in Chrome on second / third loading. Tried again in Firefox, and it's still there, on both devices.

**Comment by Alys** [comment] 2016-08-06 06:07
I'm going to close this because it's not something we hear about often, isn't critical, and is likely to disappear when we improve the website's front-end code later this year.

**Closed as completed by Alys** 2016-08-06 06:07 UTC
Labels: priority: minor, status: issue: needs investigation
