### ISSUE TITLE
Halloween skins disappeared despite purchase

### ISSUE THREAD

**Issue by breadstrings** [HabitRPG/habitica#1791] opened 2013-11-11 10:39 UTC
Hi, I just discovered that the unlocked Halloween Skins no longer show up in my profile options.

Browser: Google Chrome
UserID: 3b675c0e-d7a6-440c-8687-bc67cd0bf4e9

**Comment by lefnire** [comment] 2013-11-11 16:23
dupe of #1792, fixed

**Closed as completed by lefnire** 2013-11-11 16:23 UTC
