### ISSUE TITLE
Dailies Aren't Resetting

### ISSUE THREAD

**Issue by Babileilei** [HabitRPG/habitica#2566] opened 2014-01-25 20:28 UTC
I had my day set to start over at 5 in the morning.  I've come across the bug that won't let my dailies reset.  Everything else seems to be fine except that I'm not getting anything for my tasks and whatnot. It knows it's the next day since on of my dailies is unclickable at the moment (it's only for MWF), but I've received nothing from my accomplishments.  I've synced, logged out and logged in, tried logging in on different platforms (mobile, app), and changed my day to start at midnight, but nothing has helped so far.  Little help?

**Comment by lefnire** [comment] 2014-01-25 20:29
dupe of #1057, follow there

**Closed as completed by lefnire** 2014-01-25 20:29 UTC
