### ISSUE TITLE
Snowballing a user before they've logged in that day prevents them from seeing it

### ISSUE THREAD

**Issue by Feriority** [HabitRPG/habitica#4507] opened 2015-01-12 01:57 UTC
A friend snowballed me, but when I logged in I couldn't see the effect (and neither could he, any more).  My best theory is that, since the snowball is reset by cron, and I hadn't logged in yet that day, when I did log in, it immediately triggered cron, which cleared my snowball state even though it hadn't been a full 24 hours.

I don't see anything explicitly setting snowball in cron, but we set buffs to an object without snowball.  My proposed change would set snowball (and I guess the ghost equivalent?) explicitly based on whether the user has been snowballed since their last change of day (IE if my day changes at midnight and I was snowballed at 12:01, logging in at 12:02 shouldn't reset it; if I was snowballed at 11:59 the previous night, then logging in after 12 should).  This is made a little more complicated by needing to store the time of the most recent snowball somewhere on the user, so there's a data change involved.

Does that seem reasonable?

**Comment by Alys** [comment] 2015-01-12 02:02
Duplicate of https://github.com/HabitRPG/habitrpg/issues/3071 since snowball etc are buffs. Ideally the same solution would be used for them all.

@Feriority have a look through that issue and see if there's anything there that affects your idea. Your idea so far sounds interesting to me.

**Comment by Alys** [comment] 2015-05-18 04:29
Actually a duplicate of https://github.com/HabitRPG/habitrpg/issues/2523 which has more detail than #3071, and includes the idea of storing the time that the buff was cast. I'm closing this issue, but it's been linked to from #2523 for future reference.

**Closed as completed by Alys** 2015-05-18 04:29 UTC
Labels: priority: minor
