### ISSUE TITLE
Double Cron Issues Probably Associated with Daylight Savings Time - Android app was not picking up new timezone

### ISSUE THREAD

**Issue by pqhunter** [HabitRPG/habitica#6879] opened 2016-03-14 07:00 UTC
Hey,

So I think the problem that the android app has with daylight savings time just caused some real problems with my account.  I lost health for dailies that the app has marked as incomplete, but that I definitely did.  I don't mind that so much. What is annoying is that I lost my perfect day buff which was 20+ days in the making.  I went from 296 MP to 214 MP, if that gives any indication of what my buff was like. I would really like it back if at all possible.  Thank you!

**Comment by pqhunter** [comment] 2016-03-14 07:05
![screenshot 2016-03-14 03 05 07](https://cloud.githubusercontent.com/assets/17100270/13737178/9bb83e2e-e991-11e5-88eb-1f32c3e37083.png)

**Comment by Alys** [comment] 2016-03-14 09:40
@pqhunter Did you recently go through a daylight savings change? If so, was it the USA one on Sunday or a different one? 

Do you think it was that change which caused the problem or was it something else related to daylight savings time?

Can you tell us exactly what you experienced? For example:
- Did your cron run at the normal time (e.g., when you first used Habitica one day) AND did it then run a second time later that day?
- Or did it not run when it was supposed to BUT ran later or earlier than it should have?
- Or did cron run only once, exactly when you were expecting it to, but it behaved in a different way than it should have? There's the problem with Dailies that you reported, but was there anything else?

What date did this problem happen? For example, was it on 13th March (Sunday) in your timezone or was it on 14th March (Monday) or on another day? 
What time of day did you notice it happening?

What is your timezone? Please tell us it in terms of UTC + or - a number of hours, rather than as a local name for the timezone. If your timezone changed because of a daylight savings change, what was your timezone before and after the change?

What is your User ID? See step 6 at Help > Report a Bug if you're not sure how to find it.

If you'd like to gain back the health etc that you lost, you can go to Settings > Site on the Habitica website (Settings is the gear-shaped icon) and click the "Fix Character Values" button. That tool can't restore your buff but you can give yourself extra mana, etc to make up for what you should have gained today. At some future time, it's likely that we'll modify that tool so that you can use it to increase your number of Perfect Day achievements, and then you'll be able to add 1 to the number for the achievement that you should have gained when this bug happened.

**Comment by mandyzhou** [comment] 2016-03-14 13:37
I'm not OP, but I'm experiencing a similar issue. My user ID is 8cce502f-a91c-40c2-b782-687759c6da0a.

My timezone is UTC-4:00 (US East Coast) and I recently went through daylight savings. I've checked my timezone settings through https://habitica.com/#/options/settings/settings on both my laptop browser and my phone browser; both showed that my timezone was set to UTC-4:00. My custom day start is set to 4am.

After completing all my Dailies yesterday (3/13/16), I checked through the Data Display Tool that my Dailies were checked off -- and they were. This morning, the Data Display Tool indicated that I didn't complete any of the Dailies I had due on 3/13/16; my mana was very low; my streaks for Dailies due on 3/13 were set to zero; and I did not get any of the Perfect Day buffs I should have.

My party is also in the middle of a quest. At 04:05:10 on 3/14/16, I was shown to have done 74.0 damage to the boss; the boss did zero damage to the party. However, a little over two hours later, at 06:22:53 on 3/14/16, my damage was calculated again; I did zero damage to the boss, but the boss did 4.3 damage to my party. This does not seem to have happened to anyone else in my party (so far).

Please let me know if I can provide any further information.

**Comment by Alys** [comment] 2016-03-14 13:49
@mandyzhou Thank you very much - that's a very thorough and detailed report! There is clearly something going on here. We don't know what yet but we'll keep at it until we've worked it out. I'm pretty sure that it shouldn't happen again tomorrow. If it does, please do tell us! I'm sorry about the extra damage.

**Comment by pqhunter** [comment] 2016-03-14 13:56
@Alys 
- I did recently go through the USA day light savings time.  I went from UTC -5 to UTC -4  On Sunday I changed the date on most of my dailies so that the start date was post daylight savings time, so that I wouldn't have problems in the app with dailies showing up on the wrong days.
- I've never had a problem before where I Croned while logged into my computer and then when I have gone to check something off in the app I have Croned again.  That appears to be what happened last night
- I Croned exactly at midnight last night (13/3 changing to 14/3) while logged into my computer.  It was ~3:00 am when I logged into the Android app and Croned the second time.  When I logged into the app my drop count was also reset and I think I lost all of the experience and gold that I had gained between 12:00 and 3:00.  The notification in the app was gone too quickly for me to catch all of the numbers.

My ID is 0298735e-b2e1-4720-a605-4f4a00c70338

**Comment by Alys** [comment] 2016-03-14 15:19
**Our latest findings are that for anyone who has gone through a time zone change recently and has experienced two crons on the same day, it's probably because the Habitica website hasn't yet picked up your new time zone but the mobile app has, and the two zones are conflicting and causing double crons. Log out of the website (on ALL browsers that you use it on, including browsers on your mobile devices) and log back in - that will allow the website to pick up your new timezone. You shouldn't need to log out of the mobile app.**

**Comment by mamessner** [comment] 2016-03-14 16:21
Hi all. I just scrolled through the chat a bit and saw people talking about daylight savings and potential effects on cron and health, but I'm not sure what the final solution was. I just logged in and realized that I was hurt pretty badly. I checked the data display tool and saw that it recorded all of my dailies from yesterday as not being done. I was also resting in the inn the day before (Saturday, the day before the time change), so I guess the crons from both days just ran.

My ID is 43e182df-ec31-4b93-9afd-6d8340dd0466

**Comment by mandyzhou** [comment] 2016-03-14 16:25
Should this issue be renamed since it seems to cover double Cron issues due to Daylight Savings more generally? It would make this discussion easier to find for others experiencing this issue.

**Comment by pqhunter** [comment] 2016-03-14 16:27
@mandyzhou Renamed to better reflect the discussion.

**Comment by Alys** [comment] 2016-03-15 00:15
@mamessner I'm sorry about that! It wasn't actually that crons from both days ran. Instead your cron for today ran twice, because of an issue caused by the DST change. See my post above for a longer description (I've just made it all bold to make it easier to find), but in brief, please log out of the website and log back in to make sure it has picked up your new time zone. You can use Settings > Site > Fix Character Values to restore lost health and other stats.

**Comment by pqhunter** [comment] 2016-03-15 06:11
@Alys I logged out of all of my browser's and even uninstalled the app. I
still double croned today and did a lot of damage to my party. I also lost my perfect day bonus again.

**Comment by pqhunter** [comment] 2016-03-15 06:12
Sorry for the double post. This time I did not lose my perfect day buffs

**Comment by Alys** [comment] 2016-03-15 07:00
@pqhunter After you logged out of all your browsers, how many did you log back into? Were they all on the same PC/mobile device or on different PCs / devices?

If they were on different devices, is it at all possible that one of those devices is set to a different time zone than the others? Even if you think that's not possible, I think it would be a good idea to check. The best way to check is to go to https://habitica.com/#/options/settings/settings on each of the devices, then reload that page (even if you've only just loaded it), and then see what it says near the bottom right in the Time Zone section. It will be something like this:
`Habitica uses the time zone set on your PC, which is: UTC+10:00`
Does that page give exactly the same value, after reloading, on all of the browsers you use?

Technical details for devs:

```
"preferences": {
    "dayStart": 0,
    "timezoneOffset": 240
},


{
    "id": "138ceacd-fe5e-4611-82de-890eb361d0c6",
    "text": "`pqhunter attacks The Necromancer for 4.1 damage, The Necromancer attacks party for 12.6 damage.`",
    "timestamp": 1458022041132, [ UTC 2016-03-15 06:07:21 ]
    "flagCount": 0
},
{
    "id": "7a39eb33-7d3d-4910-9e52-298477345740",
    "text": "`pqhunter attacks The Necromancer for 29.4 damage, The Necromancer attacks party for 0.0 damage.`",
    "timestamp": 1458014715777,  [ UTC 2016-03-15 04:05:15 ]
    "flagCount": 0
},
```

**Comment by mandyzhou** [comment] 2016-03-15 13:25
I also experienced a double Cron for the second time. Prior to Croning, I had logged out of and back in to Habitica on all browsers on all my PCs and devices. I'd also verified through https://habitica.com/#/options/settings/settings that Habitica was set to the UTC-4:00 timezone on all my PCs and devices.

Note that I'm still getting Perfect Day achievements, which must have been triggered after the first Cron.

**Comment by Alys** [comment] 2016-03-16 00:11
@mandyzhou Thank you for the extra details, and I'm sorry about that. Can you recall the approximate times of the two crons, or roughly how far apart they were?

From the database, mandyzhou's most recent cron was `"lastCron": "2016-03-15T09:47:32.811Z"`. There's no active quest at the moment so I can't get the previous cron date from the quest progress messages.

**Comment by Alys** [comment] 2016-03-16 00:13
From the database, mandyzhou's most recent cron was `"lastCron": "2016-03-15T09:47:32.811Z"`. There's no active quest at the moment so I can't get the previous cron date from the quest progress messages.

**Comment by mandyzhou** [comment] 2016-03-16 01:44
The first cron happened when my party was still doing a quest -- the
message reporting how much damage I did to the boss appeared at 04:05:03 on
3/15.

**Comment by citrusella** [comment] 2016-03-16 03:59
Was told to report here:

Cron ran normally at midnight last night. Sometime around 5 am or so, I checked off my language hacking daily. After that, I think I dropped in on the Tavern a few times via the site and definitely did so a few times before dinner. I checked the app exactly once before dinner and came back sometime after to all my streaks but the one on the task I checked in the morning unchecked and about 17 health lost (though I don't remember noticing a popup notification for the lost health when I returned to the site, so it's possible the screwup happened earlier? And it might have--perhaps even much earlier since I often miss things right in front of my face--since I just checked the app without getting it to refresh and my health was subtracted there, too.).

Checking the data display tool shows my actual data for yesterday as apparently having never happened (despite me being rather sure it did and this not being, say, a sync issue), because the one task that was checked today is the only one checked for yesterday in my dailies history.

Went through DST spring forward on Sunday; visited the site multiple times since then and pretty sure I visited the app at least once as well. My timezone is Eastern Time US (I believe that's UTC -5, which is what the site displays on my computer, but I'm not sure if it's supposed to be different under DST; haven't run the check on my phone to see if there's a discrepancy because it would take forever to load (I think this slowness is a Firefox issue on my phone--at present it is actually entirely refusing to load the settings page at all), but I'm waiting for it to get through so that I can check).

User ID is 2d6ef231-50b4-4a22-90e7-45eb97147a2c and luckily no heavy harm was done--I didn't die and was able to restore the relevant streaks. I'll try to log in and out of the site on the chance it was a date discrepancy between my phone and PC.

EDIT: Think it may have been a date discrepancy; phone finally loaded and read UTC -4 and upon my just-happened actual cron, the website changed to read as that zone as well. XP

**Comment by EmanonSuomynona** [comment] 2016-03-16 07:47
Hi I'm having the same issue as well, even after logging out and logging back in to Habitica on my PC, my mobile browser, as well as the mobile app.

I am in the UTC-5:00 (previously UTC-6:00) time zone, and my cron is set at midnight. For the past three days, cron ran successfully at midnight, but then it seems to run again at around 2am. I've checked the time zones on the Habitica settings page for all my browsers, and they're all at UTC-5:00.

My User ID is 8cb48592-37f4-4925-a1fd-9b030f6d8619 (EmanonSuomynona).

Thanks.

Edit: I mostly use the new Habitica app on Android. I occasionally use the old Habitica Android app as well if I want to check my inventory or guild messages.

**Comment by Alys** [comment] 2016-03-16 07:55
EVERYONE:

If you've used the Habitica mobile app in the past three days, can you please comment here to say whether it's Android or iOS? No need to comment if you've already mentioned it in this issue.

If you're using the old "HabitRPG" app with the brown chest logo, please tell us that too!

Note that I'm not implying that the problem is on the app, I just want to collect as much information as I can.

**Comment by mandyzhou** [comment] 2016-03-16 09:17
I'm using the (new) Android app.

**Comment by LlamaHobbit** [comment] 2016-03-16 11:59
Not sure if this is the same issue. User ID is b41d86c0-8dce-4d2b-bf2a-c54cffaf1b2b and party ID is ab82c2b2-5f26-4ac2-b7ff-ee940ea050a6 .

 It looks like my cron may have run twice this morning (March 16th, at 5:03am for me.) I'm in UTC-5. And yes, DST happened on Sunday, though I've used the website and both the old and new android apps each day since then without any problems. I first logged in this morning on the old HabitRPG android app, which I don't do all the time (usually log in first on the website on my PC), and immediately saw in Party chat that I'd done double damage. Switched over to the new Habitica android app and saw the same thing. Same thing when I checked on the website, too. 
![double boss damage](https://cloud.githubusercontent.com/assets/7524843/13811482/02b3975a-eb44-11e5-8391-86ecfbd98339.PNG)

I didn't lose any streaks like others have reported or unexpected health. Just did double damage to the boss.

**Comment by Alys** [comment] 2016-03-16 12:08
@LlamaHobbit That's actually a different bug, although I freely admit it's hard to tell. Two identical damages at the same time indicate that it's https://github.com/HabitRPG/habitrpg/issues/2805 in which cron occurs twice at the same time (as opposed to cron re-occurring after a couple of hours have passed). You don't need to comment on that issue. Thank you for letting us know!

**Comment by citrusella** [comment] 2016-03-16 13:05
Double croned again this morning (and for what it's worth, the timezone issues I mentioned last post shouldn't have been at play this time). I use the Android app and accidentally got into the HabitRPG version when I was clearing notifications on my phone last night because I'd started a quest, but I don't normally get on it a ton anymore.

**Comment by mandyzhou** [comment] 2016-03-16 13:41
I _didn't_ double Cron today (or at least I haven't yet; hope I didn't just jinx it!). The only thing I can think of that I did differently today is that my first interaction with Habitica (triggering Cron) was about an hour later than when I did double Cron (i.e., around 5am instead of 4am, both time zone UTC-4:00/US Eastern). Let me know if I can provide any additional information.

**Comment by Alys** [comment] 2016-03-16 20:23
EVERYONE:

@mandyzhou has reported that logging in more than an hour after the Custom Day Start time might have prevented the double cron. If you're still experiencing double crons, I recommend trying that tomorrow. So, for example, if your Custom Day Start time is 6am, don't use Habitica (on website or app) until 7am - alternatively, edit your Custom Day Start time today to be a hour earlier (5am in that example, and then don't use Habitica tomorrow until after 6am). Please tell us whether that seems to help or not!

I think this problem is happening because Habitica has still not picked up the new timezone on one of the devices that it is used on. For a couple of people who've reported this, data that I've been capturing about timezone settings in their Habitica account has been showing the timezone flipping back and forth between the old and new ones, which means that Habitica is repeatedly saving first one zone and then the other. One of those people is mandyzhou who has confirmed that the Habitica **website** has the right zone on both devices (https://github.com/HabitRPG/habitrpg/issues/6879#issuecomment-196815581 ) so this might be a problem in the Android app. I'm hoping to reach mandyzhou through Habitica chat to do some extra testing to confirm this and then I'll report back here (not doing the testing through here because it would spam this issue with multiple messages).

**Comment by Alys** [comment] 2016-03-16 21:38
mandyzhou's testing has confirmed that the Habitica mobile app was not picking up the new time zone correctly and viirus, our mobile dev, has tracked it down to a problem in the Android API. The next release of the Android app will have a fix. It should be out soon. I'll post the version number here when it's released.

Until then, I think you might be able to avoid a double cron by not using Habitica in any way until an hour after your Custom Day Start time. I'm not sure that will work in all cases though, so check back here for updates. If you want to be absolutely sure of not getting double crons, don't use the Habitica mobile app until the next version is released. It's okay to use the Habitica website on a mobile browser.

**Comment by Alys** [comment] 2016-03-17 00:45
The new version of the Android app is out! It's version 0.0.27. I'm not sure if all Google Play accounts get all updates at the same time, so watch out for that version number. You can see it on the Google Play page and on the app's About screen (scroll all the way to the bottom). Once you see 0.0.27 on the About screen, it should be safe to use the Habitica app, and to use Habitica in general at any time even just after you Custom Day Start time, without risk of getting the double cron.

However please do post here if you still experience problems with cron.

**Comment by citrusella** [comment] 2016-03-17 02:25
@Alys Both my cron issues happened far after my day start (then again, mine's not custom? XP).

Though for what it's worth, I finally got around to checking off the tasks I did today and I don't remember doing the ones with streaks still on them, yet I still have the streaks I restored despite every other part of cron definitely having run. 0_o It's not any further of a problem with cron than my comment 13 hours ago, but I felt it important to note. :P

**Comment by mandyzhou** [comment] 2016-03-17 13:22
I installed version 0.0.27 of the Android app, then accessed Habitica shortly after my Custom Day Start time. Good news -- no double Cron! A huge thank you to @Alys and @vIiRuS for looking into this and releasing a fix so quickly. Hope everyone else's double Cron issues are fixed, too!

**Comment by Alys** [comment] 2016-03-17 13:24
@mandyzhou Thank you for letting us know, and for bravely testing! :)

**Comment by Rainechaser** [comment] 2016-03-17 18:44
I have also experienced double cron this week. It appears to only happen when I use the android app. 
I experienced it on Monday which I attributed to DST. All I did today was update and open the app, and it did it to me again. My adjusted cron time is 2 am, both times these second crons happened at around 11 am, usually when I log in to check off things I accomplish in the morning. I keep damaging my party severely. Is the recommendation to just not use the android app until this is resolved?

**Comment by mandyzhou** [comment] 2016-03-17 18:46
@Rainechaser Are you using version 0.0.27 of the app? You can check by going to the About screen and scrolling all the way down. That version should have fixed the problem.

**Comment by Rainechaser** [comment] 2016-03-17 18:52
Yes, I am running 0.0.27.1 
When I open the app it is now giving me a connection error saying that there seems to be a problem with the server.

**Comment by citrusella** [comment] 2016-03-17 20:07
@Rainechaser Clearing the app's data should fix the connection problem. It's not anything on your or Habitica's end with that but something niggly in the data your phone had previously stored that needs to be wiped out. I dunno where the cron issue came from with the new app, though.

**Comment by Rainechaser** [comment] 2016-03-17 20:57
I just uninstalled and reinstalled. Will wait and see what happens tomorrow.

**Comment by Alys** [comment] 2016-04-02 06:19
Closing this because we confirmed that this rash of cron problems was from the Habitica mobile app not picking up the new time zone correctly and viirus, our mobile dev, tracked it down to a problem in the Android API. The app was updated.

**Closed as completed by Alys** 2016-04-02 06:19 UTC

**Comment by chankeypathak** [comment] 2016-09-30 12:42
Facing the same issue. Getting "there seems to be a problem with the server."

**Comment by crookedneighbor** [comment] 2016-09-30 13:02
@chankeypathak  What's your User ID? You can find it in [Settings > API](https://habitrpg.com/#/options/settings/api) on the website. Be sure to only copy the User ID and _not_ your API Token.

**Comment by chankeypathak** [comment] 2016-10-03 05:08
@crookedneighbor It's 507514bf-0939-40b1-a391-e3b89a8c2346

**Comment by Alys** [comment] 2016-10-03 05:49
I'm not seeing any indication that you're getting double crons (i.e., that your Dailies are becoming unticked more than once a day), although recently you've been either resting in the inn or not logging in to Habitica so it's hard to tell. If you're still having trouble, please describe what's going wrong in as much detail as you can in the "Report a Bug" guild. You can get to it through Help > Report a Bug from the website's menu or Guilds > Report a Bug on the mobile app.
