### ISSUE TITLE
I request a warning: "If nothing changes you will die when the day ends."

### ISSUE THREAD

**Issue by ShadowBB** [HabitRPG/habitica#737] opened 2013-03-27 12:50 UTC
I suggest the following:
- A simple red alert warning that is clearly visible if you will die when the day ends when no other dailies are filled in today.

This will prompt you to try and get more dailies filled so you won't die or push to complete some tasks/good habits so you level up and safe yourself that way.

Possible variants:
- Maybe a yellow warning for when you are close to the above mentioned threshold. Something among the lines of "Warning: If nothing changes you will fall below 10 HP when the day ends."
- Or maybe some sort of gradient that is red at 0 HP and green at 20 HP and invisible at a projected 21 HP and above.

**Comment by wc8** [comment] 2013-03-27 16:01
Duplicate of [this](http://community.habitrpg.com/content/warning-if-nothing-changes-you-will-die-when-day-ends), right?

**Comment by ShadowBB** [comment] 2013-03-27 16:12
Yes it is. I posted it here as well because I got a reply stating that it should be posted here. But yesterday they posted a protocol in the forums for feature requests that told me to post it on the forum. I posted a post explaining the double post on the forums but that one isn't up there yet because it needs to be approved by an admin.

**Comment by lefnire** [comment] 2013-03-27 16:31
Ha! Sorry about all that, we're still re-jigging all the community stuff
and workflow. We're almost there, and things will be much less duplicable
in the future.

**Comment by wc8** [comment] 2013-03-27 16:43
Also, @ShadowBB thanks for confirming. 
I wanted to make sure before I closed this for organization, which is [has been] our usual practice once a suggestion is on our Trello feature/suggestion tracker. 
Speaking of which, you can find your suggestion [here](https://trello.com/c/NpknHuDm). The card needs some updating, but it's a start—see also my question in the forum thread.

**Closed as completed** 2013-03-27 16:44 UTC
Labels: status: issue: suggestion-discussion, priority: minor

**Comment by StanLindsey** [comment] 2013-03-27 23:41
On that subject @wc8 or @lefnire could you give me admin rights over on the community.habit site? I'd like to rejig some stuff its that alright. Try and bring this community into unison.

**Comment by lefnire** [comment] 2013-03-27 23:47
@wc8, you wanna give it a shot, Drupal practice? Else I'll do it soon

**Comment by wc8** [comment] 2013-03-28 00:05
@SlappyBag & @lefnire Slappybag is now an admin

**Comment by lefnire** [comment] 2013-03-28 00:06
Ninja!
