### ISSUE TITLE
-9 MP

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#2067] opened 2013-12-20 14:32 UTC
Last night I had 1 MP and it looks like I gained 10 overnight. This morning I had a total of 11MP and I cast a Burst of Flames on a daily. Now it looks like I have -9 MP and the graphic shows the mana bar full. Spells correctly indicate that I do not have enough man.

Browser: Google Chrome Version 31.0.1650.63
OS: Fedora 19
User Id: breezedm

The only thing in the javascript console is 

Given URL is not allowed by the Application configuration.: One or more of the given URLs is not allowed by the App's settings.  It must match the Website URL or Canvas URL, or the domain must be a subdomain of one of the App's domains. ping?client_id=172525162793917&domain=habitrpg.com&origin=1&redirect_uri=https%3A%2F%2Fs-static.ak.…:1 

![screenshot from 2013-12-20 09 24 36](https://f.cloud.github.com/assets/5521453/1790877/a239d60e-6982-11e3-89cb-baec2259e181.png)

**Comment by SabreCat** [comment] 2013-12-20 21:27
Duplicate of #2012. To avoid this, when casting spells click on the body of the task (the name area) instead of the checkbox.

**Closed as completed by SabreCat** 2013-12-20 21:27 UTC
