### ISSUE TITLE
Misspelling in Community Guidelines link

### ISSUE THREAD

**Issue by SHHHHHH** [HabitRPG/habitica#6260] opened 2015-11-17 18:34 UTC
This is nothing major, but there is a missing y in the guilds chat, before I agree to the "terms".
Here is a screenshot: https://www.dropbox.com/s/p8uboetur0w978f/PrtScr%20capture_4.jpg?dl=0

**Comment by SabreCat** [comment] 2015-11-17 20:20
Duplicate of #6254 .

**Closed as completed by SabreCat** 2015-11-17 20:20 UTC

**Comment by Alys** [comment] 2015-11-17 22:08
@SHHHHHH I've seen that you were asking in the Newbies Guild if you reported this correctly. You definitely did! The only reason we closed it is that someone else had reported it first. :) We're tracking the fix in the first issue (the one linked to above).

**Comment by SHHHHHH** [comment] 2015-11-18 17:25
@Alys Thanks for the response :) I checked, but failed to see that there is report about this. Tho I guess I missed it because it's 'closed', and I thought closed issues are resolved too, so I only searched the open ones. 
@SabreCat Sorry for the dupe :)

**Comment by crookedneighbor** [comment] 2015-11-18 18:28
It's closed because I just fixed it :)

**Comment by SHHHHHH** [comment] 2015-11-18 18:39
@crookedneighbor Cool. :+1: :) So issues do remain open until they get resolved.
Then I guess I wasn't looking hard enough. Next time I'll be more thorough. :)
