### ISSUE TITLE
Notifications Clutter the Information Displayed on the Page

### ISSUE THREAD

**Issue by ingomohr** [HabitRPG/habitica#13357] opened 2021-06-22 08:11 UTC
### General Info
  * Browser: Google Chrome 91.0
  * OS: Windows 10

### Description
When I resolve all my dailies (which I do for my daily onboarding), and I switch to the "Party" tab to check my progress on the current boss (in order to post my damage for our daily coordination), all the notifications clutter the page.

Workaround: I have to reload the webpage to get rid of the nofitications (or wait for some time - which is no option for a productivity app ;) ).

#### Console Errors
none

**Comment by ingomohr** [comment] 2021-06-22 08:12
This is what it looks like.
![image](https://user-images.githubusercontent.com/2838592/122888589-4a225b80-d342-11eb-9fec-2c2522a82fa4.png)

**Comment by shanaqui** [comment] 2021-06-24 12:41
Hi! This is not a bug: this is the way it is currently supposed to work. You can click on those notifications in order to dismiss them, or just wait for them to time out.

It's usually a good idea to report bugs to the Report a Bug guild first, so that we can put things on Github if we're sure there's a bug, or direct you to the feedback form in the case of requests. Here's the link to that form: https://docs.google.com/forms/d/e/1FAIpQLScPhrwq_7P1C6PTrI3lbvTsvqGyTNnGzp1ugi1Ml0PFee_p5g/viewform?usp=sf_link

There are changes to this actually being tested at the moment, in any case.

Closing this issue since it isn't a bug! :)

**Closed as completed by shanaqui** 2021-06-24 12:41 UTC
