### ISSUE TITLE
Tasks come back after checking

### ISSUE THREAD

**Issue by pantaz** [HabitRPG/habitica#5012] opened 2015-04-10 17:57 UTC
After I purchased gems, my tasks have not been disappearing after I check them complete.  My user ID is c843d059-c045-496c-b114-42bff54e5589.  I'm using Chrome and there are no console errors.  Thanks for your help!

**Comment by Alys** [comment] 2015-04-11 03:17
I'm sorry about this @pantaz! I know it must be really annoying.

The problem is that some of your To-Dos have become duplicated. What's probably happening is that you are marking those ones as complete, but doing that allows the duplicate to appear in your list of incomplete To-Dos (previously it might have been hidden).

Could you please go to the Completed To-Dos tab and delete all your completed To-Dos using the button at the bottom of the list (not by doing it manually). Then try deleting the duplicate tasks. If you happen to see two identical tasks, delete the one closer to the bottom of the list first.

Please let me know if this doesn't help or if you experience any problems!

**Comment by lemoness** [comment] 2015-04-11 18:28
My roommate is experiencing what I believe to be a variant of this bug, except that her checklists are not behaving as expected. 

She had a checklisted To-Do that she checked off, but it gave her only the rewards for a single task, and then a duplicate version appeared. When she navigated to Completed To-Dos, the completed version of herTo-Do did not have a checklist. She unchecked it, and lost all of the XP that she would have gained had it been counted as a checklist, resulting in negative XP. 

Is this a common variant of the bug, or should I file a separate ticket?

**Comment by Alys** [comment] 2015-04-12 00:16
@lemoness Ouch, that is nasty! But it is just the standard bug, no separate ticket needed. What happens is that there are two (or more) tasks with the same 'unique' ID. After the duplicate is created, it can have different settings than the first task (including a different checklist). The problem is that any action on any one of the duplicates could be applied to any other of the duplicates, as happened in this case. If she can, she should delete the task that has no checklist (she might need to move the other one to the top of the list first) and then she can re-complete the checklisted task.

**Comment by lemoness** [comment] 2015-04-14 01:05
Okay, I will let her know!

**Comment by Alys** [comment] 2015-06-14 06:50
The duplicated tasks issue has also been reported at https://github.com/HabitRPG/habitrpg/issues/4470 and we believe it should have been fixed by https://github.com/HabitRPG/habitrpg/pull/4845 so I'm closing this. If anyone still has problems with duplicated tasks or To-Dos seeming to become unticked after you've ticked them, please comment on #4470.

**Closed as completed by Alys** 2015-06-14 06:50 UTC
