### ISSUE TITLE
bugs in party invitations - sending / cancelling / accepting?

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#8931] opened 2017-08-08 11:45 UTC
I've seen enough reports to be pretty sure that the latest code related to party invitations has bugs in it. Below are some of the reports. I haven't had a chance to investigate in detail or even find out which platforms problems appear in, but I'm dumping all this here now so it doesn't get lost or forgotten about. I'll clean up this issue once I or anyone else has investigated properly.

 
Transurfer (ffe1c057-537c-454d-873f-c590b162ff2c) : _"... I've invited a person to my party and after a day I saw that his pending invitation disappeared, so I assumed he rejected it. I wrote him a letter wishing him great experience with habitica, but he said he didn't reject it. I tried to invite him again but it's says that user has already pending invitation. And he says there is no invitation. He checked everything...  I'm doing the invitation on the pc, on the website. And app.. I was so frustrated that I have uninstalled it. I'll wait till next update and try install again XD"_ [later] _"he was using mobile app and there he just saw the thing with Qr code. But on the website he could do it. Thank you! he's already in the party"_

ste. (ecc71172-583f-49b4-8113-18b0d7969bda) : _"Hello. I can't invite Zipheon (3d687d87-a1dc-4cc3-8496-e2b5cfbe5348) to my party. He does not see my invitation; I don't see him in the place of invited sent; I tried to invite him again, but I received the message that he is already been invited. How can I do?"_
 
The Flawless Swordsman (33ec374b-270b-4530-892e-2d2427131bc0) : _"Hi I am a party leader and I'm having trouble with pending invitations, the party members I invite can't accept the invitations I send and I'm not able to withdraw the invitation or even boot the members in question. Has anyone else experienced this issue?  Thanks!"_

Schiebelini (26e24484-a2ea-4d0c-9edd-0b4ddd735a06) : _"Hey, I am invited to a group for a quest, but I can't see wich group or who sent the invitation. Is this normal?"_

Emily (0d8f2fb1-2ddd-44c7-bd2a-68c01d8fc5d4) : _"Hello! I had sent a party invitation to two members but never got a response. I tried to remove them from the pending list, but the system keeps stating that they can't be found from the group. Is this a bug?"_
This is from the account of one of the people Emily had invited:
```
{
    "_id": "14fd0a49-4c45-4469-a9d9-781fca270a85",
    "invitations": {
        "party": {
            "inviter": "0d8f2fb1-2ddd-44c7-bd2a-68c01d8fc5d4",
            "name": "Imperial Fists",
            "id": "... [ user id was here ]............"
        },
        "guilds": [],
        "parties": []
    }
}
```

**Comment by lynxlynxlynx** [comment] 2017-08-11 12:09
Here's another one:
![spectacle u29152](https://user-images.githubusercontent.com/121515/29212372-95797764-7e9e-11e7-95e8-212d68c83478.png)

It was in a running session. Let me know if you need the inviter's UUID.

**Comment by Alys** [comment] 2017-08-28 11:43
Below is another buggy `invitations` object from the account of a user who had been invited to a party. The party leader says "We have [an] invite that we can't get rid of. We've been trying to get rid of him/her from invites for a month, but it says that there is no one by that user name in our group."

```
    "invitations": {
        "party": {
            "inviter": "ab4bbaed-4d59-4f3c-8eee-e37f3fe2bf7f",
            "name": "Always Be Questing!",
            "id": "24ca2b4b-ad62-41d4-9035-cf23191a1fdb"
        },
        "guilds": []
    },
```

**Comment by PauloDeSouza** [comment] 2017-10-03 19:43
Canceling pending invitation is now broken after the update. A lot of people complaining in the Looking for a Party Guild, as well Group leaders.

**Comment by TheHollidayInn** [comment] 2017-12-05 00:53
Is this still happening?

**Comment by Alys** [comment] 2017-12-07 18:33
Reports today from "Il Mago Grigio (test account 3)" (dd95201f-ac81-48c8-a28a-a8052e151b70) and Il Mago Azzurro (c073342f-4a65-4a13-9ffd-9e7fa5410d6b) (the same person):

_Il Mago Grigio (test account 3)_: "I have invited this account to my main account's party and then rescinded the invite a couple of times, but now this account has one invite in the notifications that shouldn't be there. There is no pending invite or anything (checked with the other account), and reloading doesn't make it go away"

_Alys_: "That's definitely weird because the invitation stored in this test user's account looks normal _[data below]_. Can you please reload the website in which this account is active and also the website that you main account is in and tell me if the invitation then behaves correctly? There should be one invitation available to this test account and it should appear in the party's invitation list."
```
{
    "_id": "dd95201f-ac81-48c8-a28a-a8052e151b70",
    "profile": {
        "name": "Il Mago Grigio (test account 3)"
    },
    "party": {},
    "invitations": {
        "parties": [
            {
                "id": "a1a66032-7339-4871-bd6b-a29edf198ce6",
                "name": "Il Mago Azzurro's Party",
                "inviter": "c073342f-4a65-4a13-9ffd-9e7fa5410d6b",
                "_id": "5a2830cdca78a50018d6040e"
            }
        ],
        "party": {
            "id": "a1a66032-7339-4871-bd6b-a29edf198ce6",
            "name": "Il Mago Azzurro's Party",
            "inviter": "c073342f-4a65-4a13-9ffd-9e7fa5410d6b",
            "_id": "5a2830cdca78a50018d6040e"
        },
        "guilds": []
    }
}
``` 

_Il Mago Azzurro_: "well, when I first opened Il Mago Grigio account there were two invites shown in notifications, and one on this side, from here I was able to see one pending invite and deleted it (and didn't see any other), and in Il Mago Grigio account the invites dropped to one. Now there is an other pending invite shown and I am going to delete that one too...  EDIT to add: but it doesn't go away. I had to remove it a third time for the invite to finally go away."
```
{
    "_id": "dd95201f-ac81-48c8-a28a-a8052e151b70",
    "profile": {
        "name": "Il Mago Grigio (test account 3)"
    },
    "party": {},
    "invitations": {
        "parties": [],
        "party": {},
        "guilds": []
    }
}
```

**Comment by lemoness** [comment] 2018-02-20 01:31
Does this still need investigation, or is it ready to be claimed?

**Comment by Alys** [comment] 2018-02-20 23:53
Last time I checked, the feature to allow multiple party invitations hadn't been implemented on all the code that relates to invitations (e.g., removing invitations). Working out exactly what's needed to fix it is probably a larger than average job but I'm marking this as help wanted.

**Comment by Alys** [comment] 2018-02-20 23:54
Oh, it already was, it was just "needs investigation" as well. Although I don't think those two labels need to be mutually exclusive.

**Comment by paglias** [comment] 2018-05-15 15:05
I've checked the reject invitation code and it's code to handle multiple invitations:

```
    let hasPartyInvitation = removeFromArray(user.invitations.parties, { id: groupId });
    if (hasPartyInvitation) {
      user.invitations.party = user.invitations.parties.length > 0 ? user.invitations.parties[user.invitations.parties.length - 1] : {};
      user.markModified('invitations.party');
      isUserInvited = true;
```

Is there a way to reproduce this bug?

**Comment by TheHollidayInn** [comment] 2018-08-10 13:51
Any recent reports of this?

**Comment by SabreCat** [comment] 2018-08-10 15:01
@TheHollidayInn We've had a ton of trouble with invitations lately, some of which sounds much like the above. But I _think_ it's a mobile app problem; I'm trying to confirm with users that Web-only flows are OK.

**Comment by TheHollidayInn** [comment] 2018-08-12 23:10
Can you post the users' post?

**Comment by shanaqui** [comment] 2018-11-13 12:49
From Report a Bug:

> _Dora (fa5c39c6-10d5-4f8f-ad33-e76b04616d97): "Hi! I can't seem to be able to cancel party invitations. I've read here that it is a known issue - https://github.com/HabitRPG/habitica/issues/8931
> 
> Is there a fix?"_

**Comment by SabreCat** [comment] 2018-11-15 16:55
Nothing unusual in the invitations object for the user affected above, from what I could see:

```
{
        "_id" : "cb5ad5c6-8a1a-4452-a426-90335ffda06d",
        "invitations" : {
                "party" : {
                        "id" : "88a4eb2c-960e-47e7-ad0b-ecf8d87ebb6b",
                        "name" : (redacted)
                        "inviter" : "fa5c39c6-10d5-4f8f-ad33-e76b04616d97"
                },
                "guilds" : [ ],
                "parties" : [
                        {
                                "_id" : ObjectId("5be5696cc17eda001eb54df6"),
                                "id" : "ebcc1371-38a2-4611-864f-abd05be1da9c",
                                "name" : (redacted)
                                "inviter" : "380f07e8-058c-40b7-b60f-09f1bc11bef4"
                        },
                        {
                                "_id" : ObjectId("5be56d12934fcf0023d8c6b7"),
                                "id" : "ab105e25-aae0-49dd-905e-525ad6676ef2",
                                "name" : (redacted)
                                "inviter" : "98248066-2924-4b89-9177-be36d016d273"
                        },
                        {
                                "_id" : ObjectId("5be58be5c61e6d00257f3813"),
                                "id" : "d116b5df-7606-48cb-8b8a-5ae17b92dd69",
                                "name" : (redacted)
                                "inviter" : "e568a84b-4228-4484-b808-cbef6deaf189"
                        },
                        {
                                "_id" : ObjectId("5be5aab65ed740001241666e"),
                                "id" : "f710388e-5423-4893-84af-56f9c00d85ab",
                                "name" : (redacted)
                                "inviter" : "56afbc51-22c1-4c9c-a80c-2ca76c5b67db"
                        },
                        {
                                "_id" : ObjectId("5be611ce85b6b0001860dfdd"),
                                "id" : "45e60c29-f3e6-483d-9b31-1d1fd7878bd5",
                                "name" : (redacted)
                                "inviter" : "80498a0a-ddd5-40ce-85e3-cdf3bf9d78db"
                        },
                        {
                                "_id" : ObjectId("5be6e37f01a9700013fbf916"),
                                "id" : "88a4eb2c-960e-47e7-ad0b-ecf8d87ebb6b",
                                "name" : (redacted)
                                "inviter" : "fa5c39c6-10d5-4f8f-ad33-e76b04616d97"
                        }
                ]
        }
}
```

**Comment by Alys** [comment] 2018-12-13 20:58
I'll work with @shanaqui on testing this on website and Android, then if they don't have the test iOS phone by then, I'll work with Sara for iOS. I'll be sending two or more party invitations to the test accounts, then we'll see if all invitations can be viewed, accepted, rejected correctly on all platforms. I can use database searches to confirm what's happening in the backend as the front-end testing is being done.

**Comment by Alys** [comment] 2018-12-15 03:55
Upon further reflection, I think it's best if the testing waits until shanaqui has been sent the iOS phone. Testing on all platforms at the same time has a lot of benefits for efficiency (and hence speed), and ensuring that the test data is identical for all platforms, and keeping the same test methodology without having to write notes about it or remember / recreate what was done in the past. It will also make it obvious if there's any display or wording inconsistencies across the platforms, which would be less likely to be noticed if testing was done by different people or at different times.

**Comment by Alys** [comment] 2019-04-13 04:14
One of the party invitation bugs is that if a player has an invitation in only this format:
```
"invitations.party": {
	"id": "12345672-8050-4253-85ba-123411234567",
	"name": "Party name",
	"inviter": "d904bd62-da08-416b-a816-ba797c9ee265"
},
```
i.e., if there's no corresponding data in the `invitations.parties`, then when the party leader tries to cancel that invitation, they see the error "User not found among group's members" (that's the `groupMemberNotFound` string from groups.json).
Two problems with that:
+ they can't cancel the invitation (they should be able to)
+ the error message is misleading - even in cases where it's legit to see an error message, the message should explain that the invitation does not exist

This was reported by LillaSmith (b5a69bc4-e325-417f-befe-32e3ce6f0f80) when they were trying to remove old invitations and I've confirmed it with testing in my party.

**Comment by veeeeeee** [comment] 2021-04-20 16:35
Closing due to age of issue and has not been updated with more incidents since 2019. Please open new issue if something like this pops up again.

**Closed as completed by veeeeeee** 2021-04-20 16:35 UTC
Labels: priority: important, status: issue: needs investigation, section: Party Page
