### ISSUE TITLE
Clicking on someone's name at the tavern lists one's own equipment. 

### ISSUE THREAD

**Issue by marcelosizer** [HabitRPG/habitica#2043] opened 2013-12-18 10:38 UTC
When you click on someone's name at the tavern instead of showing their equipment it shows one's own equipment. The equipment is always the same and it's exactly what I'm using. I've just changed Golden to Ruby sword and it changed promptly.
![equip1](https://f.cloud.github.com/assets/6205335/1772359/9db039a2-67cf-11e3-94a4-e1085f9b8eb4.png)

**Comment by SabreCat** [comment] 2013-12-18 12:35
Duplicate of #2010 .

**Closed as completed by SabreCat** 2013-12-18 12:35 UTC
