### ISSUE TITLE
Actions not registering

### ISSUE THREAD

**Issue by inbasso3** [HabitRPG/habitica#619] opened 2013-03-08 07:53 UTC
I had posted about issues with excessive reward points/levels, but now my account seems not to be working correctly at all. The daily tasks I had checked a couple of days ago remain the same (I can uncheck them, but they have not reset, and I have tried reloading the page, restarting my browser, and would sign out, but clicking on the drop-down button at the top right isn't doing anything, either). 
I can click on the Daily & To Do items, but the Daily items are not resetting from what I had already clicked, and no points are being rewarded for doing either of these things. Clicking +/- for Habits also does nothing.

**Comment by wc8** [comment] 2013-03-08 11:23
Possibly related to #614

**Comment by Skater6780** [comment] 2013-03-09 14:54
I also have this problem

**Comment by lefnire** [comment] 2013-04-08 01:00
dupe of #614, and I believe #769 too (at least, I think 769's resolution will solve this)

**Closed as completed by lefnire** 2013-04-08 01:00 UTC

**Comment by lefnire** [comment] 2013-04-10 13:52
@inbasso3 @Skater6780 how are things now?
