### ISSUE TITLE
Removing a tag from a task while filtering the list

### ISSUE THREAD

**Issue by Eusebius** [HabitRPG/habitica#1015] opened 2013-05-22 11:44 UTC
This is a use case working logically, yet strangely:
- Filter the list in order to display only items tagged with X;
- Edit one of those items;
- Uncheck the X tag;
- The item you are editing is hidden before you have a chance to save your changes.

If you later unfilter the list, it is apparently possible to save the changes of an item still open for edition, but I guess you have to do it one item at a time. This behaviour ends up a bit uncomfortable when you need to do some kind of mass edition based on a given tag.

**Comment by paglias** [comment] 2013-09-09 16:17
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!

**Comment by paulstaab** [comment] 2013-12-10 12:33
This issue still occurs on the current version of the site.

**Comment by kibin** [comment] 2014-04-13 19:58
I think it's fixed now, can't reproduce.

**Comment by paulstaab** [comment] 2014-05-26 07:45
Issue still affects me, and I can reproduce it following the description in the initial post. I'm happy to provide clarifications if needed.

**Comment by Alys** [comment] 2014-08-22 16:41
Proposed fix: https://github.com/HabitRPG/habitrpg-shared/pull/280

**Closed as completed** 2014-09-02 04:20 UTC
Labels: status: issue: suggestion-discussion, priority: minor
