### ISSUE TITLE
Incorrect text on CON tooltip

### ISSUE THREAD

**Issue by asbjornsen** [HabitRPG/habitica#2572] opened 2014-01-26 00:10 UTC
Possibly related to https://github.com/HabitRPG/habitrpg/issues/2548 , the Constitution tooltip text is totally wrong for me. Looks like something got copy/pasted incorrectly?

![con tooltip](https://f.cloud.github.com/assets/6503501/2002952/251c7664-861e-11e3-8f35-78d86ef2e2ce.png)

**Comment by deilann** [comment] 2014-01-26 00:31
Oh, looks like it's grabbing the wrong string. I'm not sure which string that is, though. I'll check it in a bit. Thanks!

**Comment by deilann** [comment] 2014-01-26 00:39
Okay, so the problem is that main.json has two strings named "conText," one which refers to the constitution popover and one which refers to the contributor info popover. If someone doesn't get to this first, I'll deal with it when I can go and fix all my pull requests. I suggest renaming the contributor related stuff to "contribText" and so on and so forth.

**Comment by ghost** [comment] 2014-01-26 18:13
I'm not seeing a duplicate key in that file under either `master` or `develop`. What branch are you looking at? Or did someone already fix this issue and commit?

**Comment by deilann** [comment] 2014-01-26 18:15
Here;
https://github.com/HabitRPG/habitrpg-shared/blob/54473b713578e01fc3c860d01d2ba652e81ccc0b/locales/en/main.json

**Comment by ghost** [comment] 2014-01-26 18:42
Oh man. Okay, I see now. I didn't realize that HabitRPG pulled in yet another git repository upon installation.

**Comment by marcelosizer** [comment] 2014-01-26 19:47
Fixed by #2583 and [habitrpg-shared #119](https://github.com/HabitRPG/habitrpg-shared/pull/119).

**Closed as completed** 2014-01-28 18:25 UTC
