### ISSUE TITLE
Prevent accidentally closing tasks in edit mode

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#9262] opened 2017-10-25 00:59 UTC
When tasks are open in edit mode, you shouldn't be able to click out of them and lose changes. Instead, it should trigger the following prompt if they typed anything in the task while it was in edit mode:

"Would you like to stop editing? Any changes made will not be saved."

Note that this prompt shouldn't come up if they didn't enter any text or make any changes.

**Comment by paglias** [comment] 2017-10-25 08:46
We can also prevent the modal from closing at all by clicking outside of it or by pressing ESC if we want

**Comment by Alys** [comment] 2017-10-25 11:12
I'd like to keep being able to use ESC to close the modal - it's a useful for keyboard control of the website. 

I like the idea of the prompt to confirm you want to leave.

**Comment by gitlui** [comment] 2017-11-03 00:03
Hey there I'd like to start contributing to habitica. Would you mind if I try to solve this issue?

**Comment by lemoness** [comment] 2017-11-04 01:13
@gitlui We'd love to have you contribute! Thank you so much. Let us know if you have any questions.

I've updated the labels on this ticket.

**Comment by gitlui** [comment] 2017-11-08 00:15
Hmmm.. as I'am new to Vue.js can someone maybe explain why the properties for b-modal: 
no-close-on-backdrop="true", 
no-close-on-esc="false" aren't working? 

The no-close-on-backdrop works if ESC should be forbidden too.

**Comment by paglias** [comment] 2017-11-08 10:00
> And is there a guideline which forbids the separation of the template/style/script parts into separate files?

you mean the .vue files?

> no-close-on-backdrop="true",
> no-close-on-esc="false" aren't working?

have you tried passing them as props? `:no-close-on-esc="false"` for example? See how they're used here https://github.com/HabitRPG/habitica/blob/develop/website/client/components/yesterdailyModal.vue#L6-L7

**Comment by gitlui** [comment] 2017-11-08 10:09
Yes I mean the .vue files. Couldn't they be organized more in folders like so:
taskModal (folder)
---taskModal.js
---taskModal.scss
---taskModal.html
---taskModal.vue

this would increase the file count but drastically improve readability, mergability and searching in these files.

I haven't tried your :no-close-on-esc="false" variant because my local installation doesn't build right now. I'll try it this evening.

**Comment by paglias** [comment] 2017-11-08 10:16
@gitlui we're going to keep the css/js/html together because it's been really helpful in general to have everything together, especially the js and html that are really coupled with Vue. I do realize, though, that some of them have got really big and we may want to split them into smaller components at least. I'll let you know

**Comment by gitlui** [comment] 2017-11-08 10:35
Ok I can live with that. Just wanted to clear things up. thx so far

**Comment by TheHollidayInn** [comment] 2017-12-01 14:14
@gitlui Are you still wanting to work on this?

**Comment by gitlui** [comment] 2017-12-01 20:57
After the labels were changed and the assignment to me was removed I stopped working on it. The required fix is mentioned in the comments above.

**Comment by Alys** [comment] 2017-12-01 21:01
@gitlui The labels being changed was probably an accident. When something like that happens, you can ask always us about it. Do you want to keep working on it?

**Comment by Alys** [comment] 2019-11-14 21:15
I've deleted some old comments about a potential fix that's no longer relevant because the site's code has changed.

Recently, a similar bug was fixed in the Challenge creation/edit screen and it was a very easy fix so I'm marking this as a good first issue. https://github.com/HabitRPG/habitica/pull/11409
`:no-close-on-backdrop="true"` looks like it's what we need. The task edit modal already has no-close-on-backdrop turned on when the tag selection screen is open (code below) but I think it should be on all the time.
https://github.com/HabitRPG/habitica/blob/99599953f55766fb447707594fe1c66a78d9e89d/website/client/src/components/tasks/taskModal.vue#L5

**Comment by Alys** [comment] 2019-11-14 21:19
Although I notice that the issue is actually for adding a prompt. I don't know if that needs a specific design? @Tressley 

My feeling is it would be good to do a quick fix now to prevent the task edit modal from closing at all when you click outside it, and then if a prompt is desired, it could be added later if design work is needed for it.

**Comment by Tressley** [comment] 2019-11-14 21:39
@Alys -- I agree. For now I think we should just prevent the user from clicking outside of the modal and losing focus. The only way to close the modal should be "Cancel" or "Save."

**Comment by MagicMilly** [comment] 2019-11-20 13:45
@alexthomson1, @laurel-thomson, and I (new Habiticans! 🎉) are going to get together and work on this. Thank you for the `good first issue` tag!

**Comment by Alys** [comment] 2019-11-23 02:53
@MagicMilly @alexthomson1 @laurel-thomson Thanks! I've marked this as in progress for you. Post here if you have questions!

**Comment by MagicMilly** [comment] 2019-12-09 17:26
Update: @alexthomson1 and @laurel-thomson have spun up local copies on their machines (Linux and Windows). Still working on mine (MacOS). But we are making progress! ⭐️

**Closed as completed** 2020-01-11 17:13 UTC
Labels: priority: medium, good first issue, status: issue: in progress, section: Task Page
