### ISSUE TITLE
minor experience/level up bug

### ISSUE THREAD

**Issue by irgendwr** [HabitRPG/habitica#7595] opened 2016-06-03 16:41 UTC
General Info
- UUID: 5ea6bd9e-fb1f-4f18-95d5-d3072355f8c6
- Browser: Google Chrome
- OS: Windows
### Description

Level didn't increase after experience was above limit, even after syncing and refreshing the page. This was also the case on the Android App.
After getting more experience the level increased as it should.
![habitica](https://cloud.githubusercontent.com/assets/17804578/15783614/2ed3379c-29af-11e6-933d-1e3b2f660b07.PNG)
#### Console Errors

none

**Comment by SabreCat** [comment] 2016-06-03 16:58
Duplicate of #2433. We've knocked out a few ways this can happen, but not yet all of them!

**Closed as completed by SabreCat** 2016-06-03 16:58 UTC

**Comment by irgendwr** [comment] 2016-06-03 17:02
@SabreCat okay, thanks and sorry for the duplicate ^^
