### ISSUE TITLE
Level up not being triggered after quest completion

### ISSUE THREAD

**Issue by ltorroba** [HabitRPG/habitica#7153] opened 2016-05-08 13:44 UTC
General Info
- UUID: 8ac1be04-4201-4eed-a2a4-436eada5c0e9
- Browser: Chrome, Safari, Firefox
- OS: Mac OS X
### Description

This morning my party (635ab0d2-a0d1-4660-ab84-a12ea92ed4d1) completed a quest (_Vice, Part 3: Vice Awakens_), granting us 1000 EXP. This took me to 2090 EXP total, above the 1340 EXP threshold for level 52.

![](http://i.imgur.com/DtgjwAD.png)

In an attempt to fix the issue, I attempted the following:
- Refreshing the page - did not trigger level up;
- Tested on Safari, Firefox and Chrome - levelled up still not triggered;
- Checked off a Todo and levelling up was triggered, taking me to halfway through level 53, as expected initially.

The guys that did the quest in my party faced the same problem. Here are their profiles, accessed by me:
##### Profile for _Giovanne Bittar da Costa_ (2f5a7084-ce4c-4978-9a8c-ffeaf9eb7f16)

![](http://i.imgur.com/SZ4TFQC.png)
##### Profile for _Andrômeda_ (7ce8f9d9-b840-47dd-86aa-ec3af18c6c1c)

![](http://i.imgur.com/WDRm3sl.png)
#### Console Errors

None related to this issue.

**Comment by crookedneighbor** [comment] 2016-05-08 14:03
This is a duplicate of https://github.com/HabitRPG/habitrpg/issues/2433

When you check off a task, you'll level up.

**Closed as completed by crookedneighbor** 2016-05-08 14:03 UTC
