### ISSUE TITLE
API should validate and adjust task date format

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#10809] opened 2018-11-04 04:23 UTC
As reported by Zags (5c08b0b0-dfc9-4bdb-b02a-b1d735bab587):

_"If a tasks has a due date (parameter 'date') formatted like '2018-11-23' (which can be done through the API), the due date show up in the web interface but not the Android mobile interface. Only due dates formatted like '2018-11-10T01:00:00.000Z' show up on the Android mobile interface."_

The desired fix is that the API should check the date and if it's not in the '2018-11-10T01:00:00.000Z' format, it should put it into that format. This should occur when creating and editing tasks.

When the API needs to set the time portion of the date itself, it should consider the user's time zone and Custom Day Start time. E.g., if the user supplies 2018-11-10, don't just set the time to 00:00 UTC on that day, because that might actually be 2018-11-09 or 2018-11-11 in the user's zone. The code in https://github.com/HabitRPG/habitica/pull/10783 might give hints about how to do this because it's related to a similar problem.

If the value provided for the due date is unable to be parsed as a date, there's probably already code to handle that, but if not, it would be worth handling it too as part of the fix for this issue.

**Comment by majestic-owl448** [comment] 2018-11-04 09:16
There is not a code to handle that, when you use a value that can't be parsed as a date, the call goes through and it just says "Not valid" on the todo instead of the due date

**Comment by Alys** [comment] 2018-11-04 10:33
@Ieahleen Thanks very much! 

I can think of a couple of alternatives for handling the case where the date can't be parsed:
- Throw an error and not create the To-Do (not my favourite option because the user might not notice the error / the third-party developer might not provide code to display the error).
- Set the To-Do to undated (perhaps not the safest option if it was an urgent To-Do and the user doesn't often look at their undated To-Dos).
- Set the To-Do to have the current date+time as the due date (my favourite option because the To-Do will be immediately obvious in the user's task list and they can change the date manually).

**Comment by paglias** [comment] 2018-11-04 10:47
What's happening here is that the db has some invalid date stored, so the field can't be set to a Date type, see https://github.com/HabitRPG/habitica/blob/develop/website/server/models/task.js#L322-L323

I think there's already an open issue about this, but anyway the things to do are:

1. Write a migration that tries to parse all the stored strings, and convert them to a Date if possible, otherwise remove them
2. Change the field to a date type

@Alys regarding the handling of invalid data we should really throw an error. It's consistent with how other fields are treated and it's the responsability of the API consumer to handle errors (this like all the others we have)

**Comment by paglias** [comment] 2018-11-04 15:49
There's another issue at #8405

**Comment by paglias** [comment] 2018-11-04 15:49
I think this is a duplicate of #8405

**Comment by paglias** [comment] 2018-11-05 13:28
Closing in favor ot #8405

**Closed as completed by paglias** 2018-11-05 13:28 UTC
Labels: priority: minor, help wanted, section: Other
