### ISSUE TITLE
Page unresponsive

### ISSUE THREAD

**Issue by ArgentD** [HabitRPG/habitica#1131] opened 2013-06-04 02:24 UTC
While I can mark tasks complete, I receive no XP or gold/silver for it and upon refresh, the task is back to not being marked complete again.  To keep from losing health because of this, I thought to move myself into the Inn.  However, the page won't switch to the profile side of the page.

I typically use Firefox 11.0 and the beta site, but tried the normal site with no better luck.  I also tried using the beta site and the normal site in Chrome 27.0.1453.94 m.  I only started having this problem in the last hour or two.

**Comment by squirrel7** [comment] 2013-06-04 02:34
Same here - I've tried regular and beta, Firefox and Chrome browsers, and both of my accounts (personal and work) are doing the same thing. It was working fine earlier today but just now when I tried to update things it was doing just as ArgentD described.

**Comment by lefnire** [comment] 2013-06-04 02:39
can you see if it's the same issue as #1130 (via javascript console)?

**Comment by sleepymess** [comment] 2013-06-04 02:39
Complete newbie here. this is what I'm getting when I first load the page: 
"Uncaught TypeError: Cannot set property 'guilds' of undefined"

after that, anything I click on, returns:
"Uncaught Error: Bound function not found:"

**Comment by lefnire** [comment] 2013-06-04 02:42
yeppers, same issue then. closing as dupe of #1130 , check back in 3m - if still an issue, open referenced ticket

**Closed as completed by lefnire** 2013-06-04 02:42 UTC
