### ISSUE TITLE
Hatching the same egg multiple times

### ISSUE THREAD

**Issue by deniz-dee** [HabitRPG/habitica#1258] opened 2013-07-16 13:26 UTC
I hatched 4 eggs in a row and they all appeared correctly in my stable, but the eggs did not disappear from my inventory. 2 of the potions I used are also still there.

I tried hatching one of the eggs I hatched before (Fox) and now I have two foxes from the same egg, one desert (that I wanted) and one white (test). Even after the second hatching, the egg is still in my inventory.

My internet connection is unstable (not an issue of habitrpg), so I suspect a timeout issue preventing the eggs and potions being removed from my inventory after being successfully used. Not sure which of the operations comes first.

This happened when I checked the site again after getting the "server restarting" error.

**Comment by deniz-dee** [comment] 2013-07-17 16:11
Got a new egg today and it worked correctly. The other four are still in my inventory though.

**Comment by lefnire** [comment] 2013-07-17 23:19
I can give you gems to buy back the eggs if you want, provide me with your UUID. Unfortunately we can't fix this issue until we fix #165, which we can only do with a full website rewrite (see the [backstory here](habitrpg.tumblr.com))

**Comment by deniz-dee** [comment] 2013-07-18 15:58
Uhh, I guess I couldn't explain it clearly. I haven't lost the eggs. On the contrary, the eggs remained in my inventory after being used. So I've gained extra eggs I haven't earned. I suppose not many people would be complaining about that, but I don't like cheating. It would be very easy to 'find' all the pets if such an error happened a few more times.

In short, Habit's gifted me 4 eggs.

**Comment by Longformer** [comment] 2013-07-19 10:41
Tyler, I had the opposite problem.  Got two wolf eggs and a lion egg, hatched the lion egg with a red potion, had the potion & egg disappear correctly.  However, then couldn't select the red lion as my pet, but could still switch to other pets.  ended up with an empty pet view while clicking the red lion eventually, but then went back to my previous pet. Unfortunately, this morning my two wolf and one lion eggs were gone.  UUID fdd86072-32c0-43a2-b6ca-41f3f7b06585

**Comment by lefnire** [comment] 2013-07-19 16:54
@Longformer gave you some tokens to buy back your pets. Unfortunately only thing I can do for no until we move off Derby. Follow http://habitrpg.tumblr.com/post/55792029689/bug-workarounds going forward, No. 1 was the cause of that bug

**Comment by paglias** [comment] 2013-09-09 17:51
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!

**Closed as completed by paglias** 2013-09-09 17:51 UTC
