### ISSUE TITLE
Subtracting experience and gold when I feed pets?

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#4202] opened 2014-10-31 21:06 UTC
Hello,

I'm not quite sure if this is a bug, but when I fed my Zombie Dragon a Rotten Candy, it subtracted 88 gold and some experience.

Browser: Chrome version 38.0.2125.104 m (64-bit)
OS: Windows 8.1
User ID: 35755297-ea59-405f-a39a-a70f2e0ccae9

(Sorry I couldn't screenshot)
Thanks!

**Comment by Alys** [comment] 2014-10-31 21:14
The loss of experience and gold would have been coincidental rather than caused by feeding. Something else in HabitRPG recently caused you to lose the XP and gold, and HabitRPG didn't show those messages to you until you fed the pet. The loss could either have been due to [sync errors](http://habitrpg.wikia.com/wiki/Sync_Errors) or by actions taken previously on another device that had not yet been reported to you on the device that you used for feeding your pet.

I'm going to close this now since it isn't a bug, but if I haven't explained this clearly enough, or if you have any questions, or would like more information, comment here and we will definitely reply.

**Closed as completed by Alys** 2014-10-31 21:14 UTC

**Comment by ghost** [comment] 2014-10-31 21:16
Thanks for the reply. I didn't spend anything before, though. I was just checking off tasks and feeding my pet....

**Comment by Alys** [comment] 2014-10-31 21:23
Then it would definitely be from sync errors. Have a look at the "sync error" page that I linked to, especially section 2 and section 4.2, which go into more detail than we can easily put here. The section about how to minimise sync errors might be useful to. If you still have questions afterwards, feel free to ask again. :)
