### ISSUE TITLE
Can't create challenge

### ISSUE THREAD

**Issue by sleepyspider1** [HabitRPG/habitica#3119] opened 2014-03-21 18:13 UTC
When I try to create a challenge, the reward text box complains stating:
It must be greater than or equal to 1.
When I set it to >= 1, it says, it must be less than or equal to zero.
Setting it to zero results in:
"It must be greater than or equal to 1".

Therefore, I can not create a challenge.

**Comment by deilann** [comment] 2014-03-21 18:14
Please search before opening a new ticket. This looks like it's a dupe of https://github.com/HabitRPG/habitrpg/issues/3020

**Closed as completed by deilann** 2014-03-21 18:14 UTC

**Comment by sleepyspider1** [comment] 2014-03-21 21:58
I did search. Nothing came up.

**Comment by deilann** [comment] 2014-03-21 21:59
What did you search? I searched "challenge" and it was maybe the second
ticket?

**Comment by sleepyspider1** [comment] 2014-03-22 01:09
I don't remember, sorry. I just remember that nothing came up. I must have reworded the error message incorrectly.

**Comment by deilann** [comment] 2014-03-22 05:09
Mmm, next time, search something super generic. Like, if it's a challenges
issue "challenges" is more likely to get you what you're looking for than
the actual error message. A lot of times, people don't c/p the error. :)
