### ISSUE TITLE
Attempting to create a Challenge with not enough Gems locks Challenge submission until refresh

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#11765] opened 2020-01-21 12:47 UTC
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)

### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)

If you attempt to create a Challenge with a Gem prize larger than your current available Gems, you get an error that you don't have enough Gems and need to reduce the prize or buy some Gems first. All well and good! But if you then reduce the prize or get Gems, as directed, the Create Challenge button stays disabled. You can't create the Challenge unless you refresh the page first.

#### Console Errors
[//]: # (Include any JavaScript console errors here.)

Unhandled error in Vue.js code. logging.js:30
Error: Error: "Request failed with status code 401"
    createError createError.js:16
    settle settle.js:17
    handleLoad xhr.js:59

**Comment by aristizabal95** [comment] 2020-01-26 04:39
The reason why the button is disabled is because the `loading` property inside the `challengeModal` is not being set to false after sending a `createChallenge` request to the server. The only instance of resetting the `loading` property to false is on `challengeModal.vue:540` where client-side errors have been identified. this property should be set to false after completing a request, no matter if it was successful or not.

I propose adding a `this.loading = false;` after completing a `createChallenge` request.

/website/client/src/components/challenges/challengeModal.vue:565
```javascript
} else {
  challenge = await this.$store.dispatch('challenges:createChallenge', {challenge: challengeDetails });
}
this.loading = false; // Server has responded
```

On the other hand, it would be great if the app could check this possible error from the client-side. I'm not sure if there's a way that the `challengeModal` could be aware of the amount of gems the user has beforehand (not a vue developer).

**Comment by aristizabal95** [comment] 2020-01-26 19:39
I'm interested on working on this issue

**Comment by Alys** [comment] 2020-01-27 01:35
@aristizabal95 Thanks! I've marked it as in progress for you.

**Comment by citrusella** [comment] 2020-01-27 03:06
Curiosity question rather than anything super specific, because it's been gnawing at me: Does #11545 have the same root cause as this (the loading property thing keeping the button disabled, and thus the this.loading addition would in theory fix it) or no?

**Comment by aristizabal95** [comment] 2020-01-27 03:26
@citrusella I believe it is. As of right now, the loading property of this module will only reenable itself if a clientside error was found. Since the loading property is the one that disables the button, then any server-side error will not reenable the button until refreshing.

Now, I made some tests before adding clientside validation on this specific issue, and seems like serverside exceptions are not being handled correctly. this means that if there's an error the creation script will stop before reaching the `this.loading = false` line (making it somewhat useless atm). 

I also wanted to add some exception handling in this section to avoid this, but node and vue are unfamiliar territory to me.I'm pretty sure if you manage to handle the exceptions, and reset the loading property, the bug should be fixed.

**Comment by aristizabal95** [comment] 2020-01-27 03:46
@citrusella Nevermind, gave it a try (pun intended) and adding a basic exception handling wasn't as difficult as I thought. I'm going to update my PR. If you want, give it a try and see if that resolves your problem!

**Closed as completed** 2020-02-18 16:06 UTC
Labels: priority: minor, section: Challenges, status: issue: in progress
