### ISSUE TITLE
Attributes display a wrong class bonus on friends

### ISSUE THREAD

**Issue by Peldor** [HabitRPG/habitica#5623] opened 2015-07-15 11:46 UTC
If one clicks on a party member to see his attributes, for instance, a class bonus of 45 is reported on perception, while the person actually has a 15 class bonus

**Comment by crookedneighbor** [comment] 2015-07-15 13:08
@Peldor Can you provide screenshots and user ids?

**Comment by hairlessbear** [comment] 2015-07-15 14:25
I believe this is a duplicate of [#5135](https://github.com/HabitRPG/habitrpg/issues/5135#issuecomment-100303275) (specifically the last couple comments)

**Comment by Peldor** [comment] 2015-07-15 15:06
I did a good search on attributes, but did not see this post.
What i gather from the text is that that is 0.5 class bonus. 
But what i see is the 0.5 class bonus+ the original item stat= equals 3 times class bonus.
I asked others and they see the same

**Comment by hairlessbear** [comment] 2015-07-15 15:15
The last few comments in the linked issue are what I'm referring to; I apologize for not being more specific.

Here's what's happening: for each attribute, there are five bonuses that can display: level, equipment, class bonus, allocated, and buffs. Unfortunately, the code that calculates the equipment bonus isn't working properly, and isn't returning any value. 

This has two side effects:
1) No equipment bonus is displayed, even when it should be
2) The bonus that should go to equipment is lumped into "Class Bonus"

So the reason you're seeing such large class bonuses is because each displayed class bonus is a combination of the actual class bonus and the equipment buffs for that attribute. Does that make sense?

**Comment by hairlessbear** [comment] 2015-07-15 15:21
Here's an example from my profile.

This is a screenshot from my avatar page (where the stats display properly):
![selection_036](https://cloud.githubusercontent.com/assets/7059890/8702062/5e79bc26-2ae3-11e5-846a-dec3ce628010.jpg)

This is a screenshot from my member popup:
![selection_037](https://cloud.githubusercontent.com/assets/7059890/8702068/6c12988a-2ae3-11e5-835d-fd4566ad3f44.jpg)

As you can see, the class bonuses in my member popup are a combination of my actual class bonus and the equipment bonus.

**Comment by hairlessbear** [comment] 2015-07-15 15:40
@crookedneighbor I just fiddled with [the code ](https://github.com/HabitRPG/habitrpg/blob/develop/website/views/shared/profiles/stats.jade#L46-48) a bit, and replacing the instances of `e` with `profile.items.gear.equipped` makes everything work properly. So something weird is happening in the `ng-init` to cause `e` to not properly be set or something.

**Comment by crookedneighbor** [comment] 2015-07-15 15:55
Well, the first problem is that we're using ng-init in a non ng-repeat context :disappointed:

**Comment by hairlessbear** [comment] 2015-07-15 16:02
Very true. I just don't understand why it works properly on the profile page, but not with the member modal. Either way, it definitely needs to be reworked.

In the meantime, #5626 fixes this issue in a hacky way, and might be worth implementing until we get around to refactoring the code.

**Comment by SabreCat** [comment] 2015-07-15 16:35
Closing this ticket as a duplicate of #5135.

**Closed as completed by SabreCat** 2015-07-15 16:35 UTC
