### ISSUE TITLE
Trapper Santa Regains Health 

### ISSUE THREAD

**Issue by wecansexy** [HabitRPG/habitica#2388] opened 2014-01-13 15:43 UTC
After one day of the boss battle, the boss's HP reset to 300/300. We have a somewhat large party and had it down to about half, and then it went back to full health out of nowhere. Very confusing!

**Comment by lefnire** [comment] 2014-01-13 16:18
dupe of #2389, let's follow up there

**Closed as completed by lefnire** 2014-01-13 16:18 UTC
Labels: priority: important
