### ISSUE TITLE
Entire rewards column missing

### ISSUE THREAD

**Issue by khipkin** [HabitRPG/habitica#10134] opened 2018-03-14 02:31 UTC
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)
### General Info
  * UUID: 
  * Browser: Chrome Version 64.0.3282.186 (Official Build) (64-bit)
  * OS: Windows 10 Home (Version 1709) (OS Build 16299.309)

### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)

Relaunched the website after restarting my computer, and the entire rewards column failed to appear.

![image](https://user-images.githubusercontent.com/5641207/37380176-a137a9fa-26f4-11e8-8a1f-487f6e9b4ee2.png)

#### Console Errors
[//]: # (Include any JavaScript console errors here.)

![image](https://user-images.githubusercontent.com/5641207/37380231-edd8ce9c-26f4-11e8-9911-7a4fced9a9b4.png)

The problem seems to be this error:

    vue.runtime.esm.js:1713 TypeError: Cannot read property 'key' of undefined
    at e.exports (app.78dc0f64afd5fc1a7fd8.js:1)
    at app.78dc0f64afd5fc1a7fd8.js:1
    at Array.map (<anonymous>)
    at e.exports (app.78dc0f64afd5fc1a7fd8.js:1)
    at a.inAppRewards (8.ea5e7c1a746c2218feac.js:1)
    at Ci.get (vue.runtime.esm.js:3111)
    at Ci.evaluate (vue.runtime.esm.js:3218)
    at a.inAppRewards (vue.runtime.esm.js:3470)
    at a.initialColumnDescription (8.ea5e7c1a746c2218feac.js:1)
    at Ci.get (vue.runtime.esm.js:3111)

**Comment by paglias** [comment] 2018-03-14 16:53
I'm not able to replicate this myself on habitica.com @khipkin can you click on the line that says `at e.exports (app.....)` in the console and post a screenshot of the code that appears?

Is this happening to you @TheHollidayInn @SabreCat @Alys ?

**Comment by Alys** [comment] 2018-03-14 22:18
It's not happening for me.

In the past when the Rewards column has had problems, it's been because of pinned items, but when I replicate kippikoo's pinned items in my account I don't get this problem. @khipkin This is for your kippikoo (f9c89bba-abf8-4f20-a974-cf1550ff603f) account?

**Comment by khipkin** [comment] 2018-03-15 17:29
@paglias I no longer have the console available. @Alys yes.

**Comment by paglias** [comment] 2018-03-15 18:25
@khipkin what do you mean the console is no longer available?

**Comment by paglias** [comment] 2018-03-15 18:25
Can you try to clear local storage and login again?

**Comment by negue** [comment] 2018-03-16 20:30
@khipkin could you get your anonymized data, check it if there are still any data left (if so, open a different issue for that too^^) and post that data on a gist, that way we or you could use the data on our local dev-mode 

https://habitica.com/api/v3/user/anonymized


While writing this I forgot that our new api-doc doesn't have a execute button for the various apis, could you write a simple api call with the user/key data ?

**Comment by khipkin** [comment] 2018-03-17 02:15
@paglias Sorry, I meant the console from that session, containing the error message.

How do you clear local storage? I can't remember the URL.

**Comment by Alys** [comment] 2018-03-17 02:27
@khipkin https://habitica.com/static/clear-browser-data

**Comment by paglias** [comment] 2018-03-17 11:27
@khipkin so you haven't been able to reproduce the error anymore?

**Comment by khipkin** [comment] 2018-04-30 23:57
This has not happened again.

**Comment by TheHollidayInn** [comment] 2018-05-01 00:27
Closing. Feel free to reopen if it happens again.

**Comment by SabreCat** [comment] 2018-10-11 19:30
Had what sounds like a fresh report of this today:

>**Agent-Y** (d44a19fd-012b-495f-bd63-b8f830f9870c)
>Hey. Using habitica on the computer, sometimes when I switch to tasks the rewards tab disappears. Switching back and forth made it re-appear (also did a sync, but didn't restore the tab). Just thought i'd report this since it was 3 minutes to midnight and I desperately needed to buy a health potion hahaha.

Will try to get more info on the user's browser/OS.

**Comment by paglias** [comment] 2018-10-14 10:46
It'd be useful to get the console output here

**Comment by Alys** [comment] 2019-02-26 08:03
From @ravenlune (9272ab2c-4b66-4b74-aebd-799725885d1c):

"My rewards column disappeared twice today. Seems to be the same as this issue on GitHub. I can't remember when it first happened (it fixed itself on refresh), but sometime this afternoon. Second time was around 12 am EST. I believe I unpinned the 3rd Dilatory Distress quest (yesterday, possibly day before that) and the shield-hand Scimitar was pinned to my rewards because I died (yesterday). And by yesterday, I mean February 24. Using Chrome on Windows 10. [Below] are some screenshots I took of the console errors and what shows up when I click on at inAppRewards.js:44, which the GitHub issues mentioned. I can't fit all of it on my screen at once, so some parts are duplicated, but I hope it helps."

![rlune-1](https://user-images.githubusercontent.com/1495809/53396508-54d9b980-39f0-11e9-8a61-b307a7bdab18.jpg)

Here's ravenlune's pinnedItems at the time that I saw their report:

```
{
    "_id": "9272ab2c-4b66-4b74-aebd-799725885d1c",
    "pinnedItems": [
        {
            "type": "potion",
            "path": "potion"
        },
        {
            "type": "armoire",
            "path": "armoire"
        },
        {
            "path": "cardTypes.valentine",
            "type": "card"
        },
        {
            "type": "marketGear",
            "path": "gear.flat.shield_rogue_2"
        }
    ],
    "unpinnedItems": []
}
```

**Comment by paglias** [comment] 2019-02-26 09:37
@negue looks like (from the last screenshots) that some pinned items are undefined?

**Comment by negue** [comment] 2019-02-26 20:14
I checked all possible methods where the pinnedItems is modified, couldn't find any line which could insert an undefined/null entry.

But I added some more checks and cleanups (if the `user.pinnedItems` still manages to get an undefined entry, that those entries get removed, when getting the rewards)

**Comment by saraolson** [comment] 2019-03-15 16:02
not sure if this is the exact same issue but i was able to reproduce my rewards column disappearing by buying a health potion > navigating to a diff section of the site (party/shops) > back to task board. Refreshing gets it back.

**Comment by Alys** [comment] 2019-03-15 22:36
> i was able to reproduce my rewards column disappearing by buying a health potion > navigating to a diff section of the site (party/shops) > back to task board. Refreshing gets it back.

Confirmed on my account. Good catch!

While testing that, I watched my `pinnedItems` array in the database. At no time did it have any inappropriate or empty entries. It stayed like this the whole time:
```
    "pinnedItems": [
        {
            "type": "armoire",
            "path": "armoire"
        },
        {
            "type": "potion",
            "path": "potion"
        },
        {
            "path": "cardTypes.valentine",
            "type": "card"
        }
    ],
```

When I bought the health potion, this appeared in the Console:
```
TypeError: "a is undefined"

    n inAppRewards.js:44
	exports inAppRewards.js:44
	inAppRewards column.vue:374
	get 3 VueJS
	initialColumnDescription column.vue:403
	get 3 VueJS
	a column.vue:1
	_render 7 VueJS
    I es6.promise.js:75
	I es6.promise.js:60
	l _microtask.js:18 
	vue.runtime.esm.js:1878
    ut 10 VueJS
	I es6.promise.js:75
	I es6.promise.js:60
	l _microtask.js:18
```

When I moved to another page (Shops), nothing else appeared in the console.

When I moved back to Tasks, that same console message appeared again:
```
TypeError: "a is undefined"

    n inAppRewards.js:44
	exports inAppRewards.js:44
	inAppRewards column.vue:374
	get 3 VueJS
	[etc]
```

> not sure if this is the exact same issue

I think it's worth assuming that it is the same issue. Once we fix this, if we see any more reports of the Rewards column going missing, then we can go looking for other causes.

**Comment by shanaqui** [comment] 2019-03-15 23:12
Report today: 

> _@JSn1nj4 (b1781515-6c3f-4314-a126-705b1e8390e8): "So... My "rewards" section disappeared when the Pi Day announcement hit. It came back after refresh with the new merch, but just wanted to share.
> 
> [Screenshot](https://pasteboard.co/I5oeeL6.png)"_

**Comment by Alys** [comment] 2019-03-16 13:03
On my local install, I added `console.log(JSON.stringify(user)); // eslint-disable-line no-console` at the start of this function in `website/common/script/libs/inAppRewards.js`
```
module.exports = function getPinnedItems (user) {
```

Then I reloaded the tasks page and confirmed that the `user` object contained the expected `pinnedItems` array:
```
"pinnedItems":[{"type":"potion","path":"potion"},{"type":"armoire","path":"armoire"},{"path":"quests.taskwoodsTerror3","type":"quests"}],
```

Then I bought a health potion and examined the console again. The `user` object no longer contained the `pinnedItems` array (not an empty array - simply not there at all), and these errors appeared in the console:
```
[Vue warn]: Error in render: "TypeError: _ref is undefined"

found in

---> <TaskColumn> at website/client/components/tasks/column.vue
       <User> at website/client/components/tasks/user.vue
         <App> at website/client/app.vue
           <Root> vue.runtime.esm.js:619

    warn 11 VueJS
    run es6.promise.js:75
 	notify es6.promise.js:92
 	flush _microtask.js:18 

TypeError: "_ref is undefined"

    items inAppRewards.js:45
	getPinnedItems inAppRewards.js:45
	[etc - see screenshot below]
```
![image](https://user-images.githubusercontent.com/1495809/54475625-1f7dfa00-483f-11e9-98c8-8ad2b1022c68.png)

So something goes wrong during or just after the buying of the health potion (or possibly buying of any item from the Rewards column).

**Comment by negue** [comment] 2019-03-16 19:13
thanks for the steps to reproduce this, it was a line that reset the pinnedItems back then, but the "buy operation" doesn't return the pinnedItems anymore and so the items at the user were reset to undefined ..., gonna add this to my open PR

**Comment by Alys** [comment] 2019-03-19 23:19
@negue Awesome!
@saraolson excellent find!

**Closed as completed** 2019-03-31 18:41 UTC
Labels: status: issue: needs investigation, status: issue: in progress, section: Task Page
