### ISSUE TITLE
All tasks reset to Easy with class system update

### ISSUE THREAD

**Issue by dfjkla** [HabitRPG/habitica#2015] opened 2013-12-17 18:24 UTC
All my tasks reset to easy, most likely during the class system update. I've set them again - quite a task given the # of items I have - and they seem to stick now, but I'm sure not everyone notices. And perhaps worth checking to see if it can/will re-occur in certain circumstances.

**Comment by brightbold** [comment] 2013-12-17 21:08
Confirmed. Since I had to go through every task to assign attributes anyway it wasn't much extra work for me, but people who aren't using auto-allocation (or people who don't notice) will be inconvenienced.

**Comment by lefnire** [comment] 2013-12-17 21:11
Yeah, confirmed. I'll see what I can do, it's gonna be tough to fix since
many users will have updated their difficulty since, and I won't be able to
tell which is the "correct" version.

**Comment by dfjkla** [comment] 2013-12-17 21:32
I'm no UI or usability expert - far from it - but I wouldn't worry about fixing the result of the bug due to reasons you mention - and this is not a gamebreaking bug -, only checking to see it doesn't happen again. And making a note on a blog post would be a good heads up so people who have set custom difficulty levels know to fix them manually.

**Comment by SabreCat** [comment] 2013-12-18 01:08
Oh, wow. It would have taken me a while to notice that, since with all the PER bonuses, critical hits, etc., I've been raking in gold and XP with every click anyway. Thanks for the find @dfjkla .

**Comment by wc8** [comment] 2013-12-18 14:40
I agree on don’t try to guess at correct version. 

In fact, I’d say if developers have time for that it’d probably be better spent to moving [multiple item edit](https://trello.com/c/pL4QIDbO) forward. That would give users an easier time fixing any similar issues in the future. 
Of course, we don’t want repeats, but there’s always a chance that an upgrade could cause a reset. (Challenges > Tags). In some cases, it might even be necessary to improve a feature. A way to mass edit items would help with get users back on track.

**Comment by brightbold** [comment] 2013-12-18 15:31
Agreed. Just tell people it's an issue and they can fix it. I think everyone understands that bugs happen.

**Comment by lefnire** [comment] 2013-12-18 15:47
Ok, https://www.facebook.com/Habitrpg/posts/549706751780371 and https://twitter.com/habitrpg/status/413334325510172673 . I'll start mulling on a multi-select batch-op feature (a la @wc8)... unfortunately, it could take some time to flesh out :( I'll keep you posted if any developments

**Comment by deilann** [comment] 2014-02-10 12:59
I'm going to assume this is no longer really an issue? Re-poen if I'm wrong. :P

**Closed as completed by deilann** 2014-02-10 12:59 UTC
