### ISSUE TITLE
Viewing challenges gives: Overflow sort stage

### ISSUE THREAD

**Issue by ahains** [HabitRPG/habitica#5200] opened 2015-05-14 04:32 UTC
Url: https://habitrpg.com/#/options/groups/challenges
My user id is: bee41965-72e4-49ff-a814-96f629c97967
I'm running Chrome version 42.0.2311.135 on osx.

Before I saw this error I had just viewed a "Family Activities" challenge at https://habitrpg.com/#/options/groups/challenges/8fc23e97-2281-439b-9d79-7550f80e3636
This is in the Newbies group (5481ccf3-5d2d-48a9-a871-70a7380cee5a).
The bug seems to repro if I view that Family Activities challenge and then click on "Back to all challenges"

I have been working with MongoDB at work lately and have seen similar errors, so I believe this is likely coming from Mongo. You might need to add an index.

The full error displayed is as follows:Please reload, "Error Runner error: Overflow sort stage buffered data usage of 33911511 bytes exceeds internal limit of 33554432 bytes" If the error persists, please report it at Help > Report a Bug. If you're familiar with your browser's console, please include any error messages.

**Comment by SabreCat** [comment] 2015-05-14 23:04
Duplicate of #4132; please follow that issue and add your advice there!

**Closed as completed by SabreCat** 2015-05-14 23:04 UTC
