### ISSUE TITLE
PM / private message entry box cannot be expanded

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica#11950] opened 2020-03-07 23:20 UTC
AnneLine reported:

> Hi, Bug zappers. Not sure if this is a bug, or a design issue or.... ? Here's a photo
> I think a change may have been made to the combox system for PMs on line, and I can't tell if it is a glitch or intended behavior. I'm using Chrome if that is any help.
> We now have a large box of the message that was sent to us (that moves up and down, which is nice), but just 4 lines to type in for our message. Theoretically, we can make the com box larger, but THAT is not working... nothing happens when you try to enlarge the box. 

Enlarging the box is working in Firefox, but I've confirmed the same issue happens for me in Google Chrome.

**Comment by ajeffrey** [comment] 2020-05-05 10:03
this is caused by the following line of CSS:
`max-height: var(--textarea-auto-height,40px)`

if you change it to `height: var(--textarea-auto-height,40px)` you can resize the textarea, though the height jumps rather dramatically when you resize. I'll see about putting in a PR.

**Comment by Alys** [comment] 2020-05-07 09:56
@ajeffrey Thank you! I've marked this as in progress for you.

**Comment by Alys** [comment] 2020-05-26 00:48
Same thing also happens on Firefox on Windows 10 (reported by @PixelStormArt 100fadc6-0b54-4329-8dc3-d96b5e482399) and Firefox on Ubuntu (me). I'm about to change the title to remove mention of Chrome.

@ajeffrey How are you going with this? Did you need any advice about creating a PR? If real-life has got in the way and you no longer have free time for it, just let us know! We understand what that's like. :)

**Comment by Tressley** [comment] 2020-05-26 14:23
Bringing @negue into this discussion He was the lead on the most recent PM enhancements.

**Comment by negue** [comment] 2020-05-26 15:10
`min-/max-height` of `--textarea-auto-height` is there:
- to be small 40px, when no text is in it
- to be "bigger" 80px, when text is inside the area

it could be set to `height` instead of `min/max` , to re-enable the resizing. 

But due to the space between the textarea and the page-bottom - the resizing is hard to get it right (either it shrinks down OR jumps to the full height).

Maybe we should rather add a `height` / `size` selection to increase to 120px / 160px

**Comment by ajeffrey** [comment] 2020-05-27 00:00
@Alys no problems here! Just slipped my mind, I've made a note to create a PR tomorrow :)

@negue When I was playing around in the dev console, switching it to height seemed to provide the same user experience without the bug, but of course I'll have to have a play around to make sure it works consistently and across browsers. Once I've got something together I'll ping you and if you could let me know if you think it's still good, that would be fantastic! Thanks

**Comment by ajeffrey** [comment] 2020-05-28 17:20
I've just added a PR @negue @Alys, I've tried it with just the max-height => height change and it seems to work as intended in Chrome and Firefox. I've just tested it now in Safari too and you can resize, but it does tend to increase in size rather quickly!

**Closed as completed** 2020-06-07 10:53 UTC
Labels: priority: medium, status: issue: in progress, type: medium level coding, section: Messages
