### ISSUE TITLE
Losing subscription items?

### ISSUE THREAD

**Issue by Keovar** [HabitRPG/habitica#3035] opened 2014-03-08 21:05 UTC
How do I replace an item that came from a subscription box? Someone in my party quest apparently took a day off and caused the entire party over 100 damage, killing everyone. The equipment I lost was the robe from the February subscription box. If this is unfixable, then I see no reason to keep the subscription.  
It's bad enough to lose a level and all gold, and even an item that could be purchased again is recoverable, but permanently losing irreplaceable items is not acceptable, as the only way to be sure of protecting myself is to quit the party and play alone.  I don't think encouraging isolation fits the purpose of HabitRPG.

**Comment by snicker** [comment] 2014-03-08 21:09
I agree... certain items should probably be marked as indestructible.

**Comment by lefnire** [comment] 2014-03-08 21:32
The intent is that _no_ item is permanently destructible. If you earn something once, you can earn it forever more from the item store. Dupe of https://github.com/HabitRPG/habitrpg/issues/2999

**Closed as completed by lefnire** 2014-03-08 21:32 UTC
