### ISSUE TITLE
Cannot see tasks (To-Dos or Habits or Dailies) or add new ones on website

### ISSUE THREAD

**Issue by annaiguana** [HabitRPG/habitica#4060] opened 2014-09-22 01:46 UTC
All of my to-do items have disappeared when I logged in today, 9/21/14. Also, I cannot add a new to-do item. Every time I enter one, nothing appears. Nothing shows up under the completed to-do items tab, either. This happens whether I log in using Chrome or Firefox. I'm using Windows 8.

My UUID is a51997e1-01d4-4594-b583-1f229e42501d

**Comment by deilann** [comment] 2014-09-22 01:46
Press "clear" on your tag filters, and tell me if this fixes your problem.

**Comment by annaiguana** [comment] 2014-09-22 01:49
it did not fix the problem.

**Comment by pastles** [comment] 2014-09-22 03:49
Hello! My Habits are all gone. My tags have been cleared (a few times), and I've logged in and out. I also can't add any new Habits currently. I am currently using Firefox 32.0.2. Funnily enough, I still see my Habits on the HabitRPG app (v0.0.35) on my Android.

Everything else is okay though.

My UUID: 172de083-73bc-42a5-855f-3e7d2d6acc0e

**Comment by Alys** [comment] 2014-09-22 04:10
@annaiguana and @pastles (or anyone else with this issue): If you know how to open the JavaScript console in Chrome, please do so, and then reload the tasks page. Do any errors appear in the console? If so, can you please paste them into this issue?

@annaiguana, note that if you have one of the HabitRPG mobile apps, you might be able to access your tasks using it.

**Comment by pastles** [comment] 2014-09-22 04:13
@Alys Is this what you were looking for?

"Error: [ngRepeat:dupes] Duplicates in a repeater are not allowed. Use 'track by' expression to specify unique keys. Repeater: task in obj[list.type+"s"] track by task.id, Duplicate key: 7bfe0551-51c4-475c-90a9-7140cb6631fa
http://errors.angularjs.org/1.3.0-beta.11/ngRepeat/dupes?p0=task%20in%20obj%5Blist.type%2B%22s%22%5D%20track%20by%20task.id&p1=7bfe0551-51c4-475c-90a9-7140cb6631fa
d/<@https://habitrpg.com/app-99623818.js:4:21997
C@https://habitrpg.com/app-99623818.js:8:4878
q@https://habitrpg.com/app-99623818.js:7:3119
Md/this.$get</i.prototype.$digest@https://habitrpg.com/app-99623818.js:7:3754
Md/this.$get</i.prototype.$apply@https://habitrpg.com/app-99623818.js:7:5500
wb/g/<@https://habitrpg.com/app-99623818.js:4:30316
i@https://habitrpg.com/app-99623818.js:5:15034
wb/g@https://habitrpg.com/app-99623818.js:4:30298
wb@https://habitrpg.com/app-99623818.js:4:30433
vb@https://habitrpg.com/app-99623818.js:4:29907
@https://habitrpg.com/app-99623818.js:8:12435
n.Callbacks/j@https://habitrpg.com/app-99623818.js:1:26852
n.Callbacks/k.fireWith@https://habitrpg.com/app-99623818.js:1:27661
.ready@https://habitrpg.com/app-99623818.js:1:29482
I@https://habitrpg.com/app-99623818.js:1:29656
" app-99623818.js:6

"Error: [ngRepeat:dupes] Duplicates in a repeater are not allowed. Use 'track by' expression to specify unique keys. Repeater: task in obj[list.type+"s"] track by task.id, Duplicate key: 7bfe0551-51c4-475c-90a9-7140cb6631fa
http://errors.angularjs.org/1.3.0-beta.11/ngRepeat/dupes?p0=task%20in%20obj%5Blist.type%2B%22s%22%5D%20track%20by%20task.id&p1=7bfe0551-51c4-475c-90a9-7140cb6631fa
d/<@https://habitrpg.com/app-99623818.js:4:21997
C@https://habitrpg.com/app-99623818.js:8:4878
q@https://habitrpg.com/app-99623818.js:7:3133
Md/this.$get</i.prototype.$digest@https://habitrpg.com/app-99623818.js:7:3754
Md/this.$get</i.prototype.$apply@https://habitrpg.com/app-99623818.js:7:5500
o@https://habitrpg.com/app-99623818.js:6:5428
x@https://habitrpg.com/app-99623818.js:6:7190
_c/</s.onreadystatechange@https://habitrpg.com/app-99623818.js:6:6839
" app-99623818.js:6

"Given URL is not permitted by the application configuration.: One or more of the given URLs is not allowed by the App's settings.  It must match the Website URL or Canvas URL, or the domain must be a subdomain of one of the App's domains."

**Comment by Alys** [comment] 2014-09-22 04:18
@pastles That's extremely interesting. It looks like it's saying that you have two tasks with the same "unique" ID, although I could be misreading it.

@annaiguana and @pastles : If you don't mind, would you be able to tell me which Challenges you are participating in, if any? If you'd rather not for privacy, that's okay, but one possible source of this is a problem with one of the Challenges.

**Comment by pastles** [comment] 2014-09-22 04:27
@Alys I'm participating in 1 challenge from my party: 

Group ID: 0f80ecef-e9db-45ec-9d61-411539b19734
1. 毎日ちょっと練習しましょう

Previously, I created a challenge for my party, but the task still remained on my Habits list after I deleted the challenge. And then I created a duplicate challenge... I think I joined it, then I left it, but the tasks were still in my Habits list as the challenge is still on-going. Might that have been the cause of this issue? Sorry if that was confusing. 

Challenge: ファイト!

**Comment by helenl7** [comment] 2014-09-22 04:38
Hi, My todos are also all gone!  Maybe this was the only way they were gonna get all checked off... 747817a9-5968-4dc2-b125-c4323d528ef2.  I've cleared tags and no dice.

**Comment by Alys** [comment] 2014-09-22 05:01
@pastles : That might have been the cause, or might not have. :) Sorry, I'm a bit limited as to what I can tell because I don't have admin access. However that might be useful information for our database admin.

@helenl7, do you know how to open the JavaScript console in Chrome? If so, please do so, and then reload the tasks page. If any errors appear in the console, please paste them into this issue.
Note that if you have one of the HabitRPG mobile apps, you might be able to access your tasks using it.

**Comment by helenl7** [comment] 2014-09-22 05:06
Alys, i will do my best!

**Comment by helenl7** [comment] 2014-09-22 05:10
Is this right?
The page at 'https://habitrpg.com/#/tasks' was loaded over HTTPS, but displayed insecure content from 'http://i.minus.com/i8HG8cVnlfi3R.gif': this content should also be loaded over HTTPS.
 app-99623818.js:2
Error: [ngRepeat:dupes] Duplicates in a repeater are not allowed. Use 'track by' expression to specify unique keys. Repeater: task in obj[list.type+"s"] track by task.id, Duplicate key: b96c5d55-1ffa-4de4-b480-db20b821c7a0
http://errors.angularjs.org/1.3.0-beta.11/ngRepeat/dupes?p0=task%20in%20obj…B%22s%22%5D%20track%20by%20task.id&p1=b96c5d55-1ffa-4de4-b480-db20b821c7a0
    at https://habitrpg.com/app-99623818.js:4:22004
    at C (https://habitrpg.com/app-99623818.js:8:4884)
    at Object.q [as fn](https://habitrpg.com/app-99623818.js:7:3119)
    at i.$digest (https://habitrpg.com/app-99623818.js:7:3756)
    at i.$apply (https://habitrpg.com/app-99623818.js:7:5502)
    at https://habitrpg.com/app-99623818.js:4:30318
    at Object.i [as invoke](https://habitrpg.com/app-99623818.js:5:15043)
    at g (https://habitrpg.com/app-99623818.js:4:30239)
    at wb (https://habitrpg.com/app-99623818.js:4:30440)
    at vb (https://habitrpg.com/app-99623818.js:4:29900) 
Uncaught SecurityError: Blocked a frame with origin "https://googleads.g.doubleclick.net" from accessing a frame with origin "https://habitrpg.com". Protocols, domains, and ports must match. Keyboard.js:238
requested layout set: all Layout.js:39
Uncaught SecurityError: Blocked a frame with origin "https://googleads.g.doubleclick.net" from accessing a frame with origin "https://habitrpg.com". Protocols, domains, and ports must match. Keyboard.js:238
requested layout set: all Layout.js:39
Uncaught SecurityError: Blocked a frame with origin "https://googleads.g.doubleclick.net" from accessing a frame with origin "https://habitrpg.com". Protocols, domains, and ports must match. Keyboard.js:238
requested layout set: all Layout.js:39
Uncaught SecurityError: Blocked a frame with origin "https://googleads.g.doubleclick.net" from accessing a frame with origin "https://habitrpg.com". Protocols, domains, and ports must match. Keyboard.js:238
Consider using 'dppx' units, as in CSS 'dpi' means dots-per-CSS-inch, not dots-per-physical-inch, so does not correspond to the actual 'dpi' of a screen. In media query expression: (-webkit-min-device-pixel-ratio: 1.5), (min-resolution: 144dpi) tweet_button.1410989646.html:1
requested layout set: all Layout.js:39
Uncaught SecurityError: Blocked a frame with origin "https://ct1.addthis.com" from accessing a frame with origin "https://habitrpg.com". Protocols, domains, and ports must match. Keyboard.js:238
requested layout set: all Layout.js:39
Uncaught SecurityError: Blocked a frame with origin "https://platform.twitter.com" from accessing a frame with origin "https://habitrpg.com". The frame requesting access set "document.domain" to "twitter.com", but the frame being accessed did not. Both must set "document.domain" to the same value to allow access. Keyboard.js:238
requested layout set: all

**Comment by Alys** [comment] 2014-09-22 05:13
Perfect! Thank you @helenl7 

(Another error possibly indicating tasks with the same "unique" ID.)

**Comment by helenl7** [comment] 2014-09-22 05:17
this wasn't all of it because I didn't want to bog down this page, but I can get all of it if you like.  Thanks so much for helping, Alys!

**Comment by Alys** [comment] 2014-09-22 05:20
@helenl7 Yes, please, if there's more, paste it in. For this sort of thing, bogging down the page doesn't matter -- but thank you for considering it, and especially for providing this information! It's much easier to troubleshoot when we can see errors like this. :)

**Comment by paglias** [comment] 2014-09-22 05:20
Pinging @negue @lefnire
Il 22/set/2014 07:17 "helenl7" notifications@github.com ha scritto:

**Comment by negue** [comment] 2014-09-22 05:50
If I am reading correctly, a habit of a challenge has the same ID as a normal Habit has? Seems that these "unique" IDs not that unique at all.. :(

We really should check them IDs if they already exists , if they do, generate a new ID..

Till that happens each "track by" useless.

I may have a workaround for this:
- once Tasks loaded in the website, go through all of em and generate a "task.trackById" which is "c_h_ID": "c_" if it is from a challenge, "h_" each Task Type, this one would be habit, at the end, the ID.

With this, the IDs would be more "unique".

Altough I could only start a "fix" in about 7-8 hours.

**Comment by helenl7** [comment] 2014-09-22 05:51
The page at 'https://habitrpg.com/#/tasks' was loaded over HTTPS, but displayed insecure content from 'http://i.minus.com/i8HG8cVnlfi3R.gif': this content should also be loaded over HTTPS.
 app-99623818.js:2
Error: [ngRepeat:dupes] Duplicates in a repeater are not allowed. Use 'track by' expression to specify unique keys. Repeater: task in obj[list.type+"s"] track by task.id, Duplicate key: b96c5d55-1ffa-4de4-b480-db20b821c7a0
http://errors.angularjs.org/1.3.0-beta.11/ngRepeat/dupes?p0=task%20in%20obj…B%22s%22%5D%20track%20by%20task.id&p1=b96c5d55-1ffa-4de4-b480-db20b821c7a0
    at https://habitrpg.com/app-99623818.js:4:22004
    at C (https://habitrpg.com/app-99623818.js:8:4884)
    at Object.q [as fn](https://habitrpg.com/app-99623818.js:7:3119)
    at i.$digest (https://habitrpg.com/app-99623818.js:7:3756)
    at i.$apply (https://habitrpg.com/app-99623818.js:7:5502)
    at https://habitrpg.com/app-99623818.js:4:30318
    at Object.i [as invoke](https://habitrpg.com/app-99623818.js:5:15043)
    at g (https://habitrpg.com/app-99623818.js:4:30239)
    at wb (https://habitrpg.com/app-99623818.js:4:30440)
    at vb (https://habitrpg.com/app-99623818.js:4:29900) app-99623818.js:6
Error: [ngRepeat:dupes] Duplicates in a repeater are not allowed. Use 'track by' expression to specify unique keys. Repeater: task in obj[list.type+"s"] track by task.id, Duplicate key: b96c5d55-1ffa-4de4-b480-db20b821c7a0
http://errors.angularjs.org/1.3.0-beta.11/ngRepeat/dupes?p0=task%20in%20obj…B%22s%22%5D%20track%20by%20task.id&p1=b96c5d55-1ffa-4de4-b480-db20b821c7a0
    at https://habitrpg.com/app-99623818.js:4:22004
    at C (https://habitrpg.com/app-99623818.js:8:4884)
    at Object.q [as fn](https://habitrpg.com/app-99623818.js:7:3133)
    at i.$digest (https://habitrpg.com/app-99623818.js:7:3756)
    at i.$apply (https://habitrpg.com/app-99623818.js:7:5502)
    at o (https://habitrpg.com/app-99623818.js:6:5430)
    at x (https://habitrpg.com/app-99623818.js:6:7190)
    at XMLHttpRequest.s.onreadystatechange (https://habitrpg.com/app-99623818.js:6:6839) app-99623818.js:6
'Attr.nodeValue' is deprecated. Please use 'value' instead. adsbygoogle.js?_=1411364973010:32
requested layout set: all Layout.js:39
requested layout set: all Layout.js:39
requested layout set: all Layout.js:39
Uncaught SecurityError: Blocked a frame with origin "https://googleads.g.doubleclick.net" from accessing a frame with origin "https://habitrpg.com". Protocols, domains, and ports must match. Keyboard.js:238
requested layout set: all Layout.js:39
Uncaught SecurityError: Blocked a frame with origin "https://googleads.g.doubleclick.net" from accessing a frame with origin "https://habitrpg.com". Protocols, domains, and ports must match. Keyboard.js:238
requested layout set: all Layout.js:39
Uncaught SecurityError: Blocked a frame with origin "https://googleads.g.doubleclick.net" from accessing a frame with origin "https://habitrpg.com". Protocols, domains, and ports must match. Keyboard.js:238
requested layout set: all Layout.js:39
Uncaught SecurityError: Blocked a frame with origin "https://googleads.g.doubleclick.net" from accessing a frame with origin "https://habitrpg.com". Protocols, domains, and ports must match. Keyboard.js:238
Consider using 'dppx' units, as in CSS 'dpi' means dots-per-CSS-inch, not dots-per-physical-inch, so does not correspond to the actual 'dpi' of a screen. In media query expression: (-webkit-min-device-pixel-ratio: 1.5), (min-resolution: 144dpi) tweet_button.1410989646.html:1
requested layout set: all Layout.js:39
Uncaught SecurityError: Blocked a frame with origin "https://ct1.addthis.com" from accessing a frame with origin "https://habitrpg.com". Protocols, domains, and ports must match. Keyboard.js:238
requested layout set: all Layout.js:39
Uncaught SecurityError: Blocked a frame with origin "https://apis.google.com" from accessing a frame with origin "https://habitrpg.com". Protocols, domains, and ports must match. Keyboard.js:238
requested layout set: all Layout.js:39
Uncaught SecurityError: Blocked a frame with origin "https://platform.twitter.com" from accessing a frame with origin "https://habitrpg.com". The frame requesting access set "document.domain" to "twitter.com", but the frame being accessed did not. Both must set "document.domain" to the same value to allow access. Keyboard.js:238
Given URL is not allowed by the Application configuration.: One or more of the given URLs is not allowed by the App's settings.  It must match the Website URL or Canvas URL, or the domain must be a subdomain of one of the App's domains. ping?client_id=172525162793917&domain=habitrpg.com&origin=1&redirect_uri=https%3A%2F%2Fs-static.ak.…:1
requested layout set: all Uncaught SecurityError: Blocked a frame with origin "https://s-static.ak.facebook.com" from accessing a frame with origin "https://habitrpg.com". The frame requesting access set "document.domain" to "facebook.com", but the frame being accessed did not. Both must set "document.domain" to the same value to allow access. Keyboard.js:238
requested layout set: all Layout.js:39
Uncaught SecurityError: Blocked a frame with origin "https://www.facebook.com" from accessing a frame with origin "https://habitrpg.com". Protocols, domains, and ports must match. Keyboard.js:238
requested layout set: all Layout.js:39
Uncaught SecurityError: Blocked a frame with origin "https://accounts.google.com" from accessing a frame with origin "https://habitrpg.com". Protocols, domains, and ports must match. Keyboard.js:238
requested layout set: all Layout.js:39
Uncaught SecurityError: Blocked a frame with origin "https://www.facebook.com" from accessing a frame with origin "https://habitrpg.com". The frame requesting access set "document.domain" to "facebook.com", but the frame being accessed did not. Both must set "document.domain" to the same value to allow access. Keyboard.js:238
requested layout set: all Layout.js:39
Uncaught SecurityError: Blocked a frame with origin "https://platform.twitter.com" from accessing a frame with origin "https://habitrpg.com". The frame requesting access set "document.domain" to "twitter.com", but the frame being accessed did not. Both must set "document.domain" to the same value to allow access. Keyboard.js:238

**Comment by helenl7** [comment] 2014-09-22 05:52
i think that's all of it!

**Comment by Alys** [comment] 2014-09-22 05:57
Thanks @helenl7 !

@negue It might have nothing to do with challenges. That was just one idea I had; if everyone was in the same challenge, then maybe there were duplicate IDs. But now that's clearly not the case.

**Comment by pastles** [comment] 2014-09-22 06:11
Just an additional note, I tried creating new Habits on the website, but they didn't appear. However, they appeared in the app. And just to confirm, anything done in the app is updated on the webpage (ie: XP increased, HP decreased etc)

**Comment by negue** [comment] 2014-09-22 06:46
Current workaround would be remove and re-add your habits, you would loose the current "Level" / the Habits Color.

OR if you can read the json output using https://habitrpg.com/static/api you could see which habit you need to re-add.

**Comment by annaiguana** [comment] 2014-09-22 07:39
hi- thank you so much!! i could see that I had duplicate tasks in my android app. i deleted them both, to be safe, then synced the app and refreshed in Chrome. it is fixed, and everything else wasn't lost.

**Comment by negue** [comment] 2014-09-22 08:04
I'm glad that it worked on your side. :) 

Did they were "exactly" the same? Also the same Name?

**Comment by Alys** [comment] 2014-09-22 09:49
Clella (a9963baa-c9fe-436a-a464-6306c03738cc) writes in the Newbies Guild:
"I have the same problem. Since 1 hour I am not able to see my todos. I try to add a new one and I don't see it also. I ckech on my iPhone and every thing is ok on it included the task I add as a test."

I think we need to modify the code as soon as we can to stop this happening. It could be affecting an unknown number of people and not all of them will know that they can ask for help here or in the Tavern/Newbies. Also, some of them might not have phones that they can use to access their tasks (e.g. phones that are too old to run the apps). @negue, can the "track by" code be removed relatively quickly? At least as a temporary measure until you have time to try the workaround you suggested above?

**Comment by negue** [comment] 2014-09-22 09:59
@Alys yes, just remove the "track by task.id" at https://github.com/HabitRPG/habitrpg/blob/develop/views/shared/tasks/task.jade#L1

The other track by are working. (till now)

**Comment by Alys** [comment] 2014-09-22 10:26
@negue, thanks! Just like this? https://github.com/HabitRPG/habitrpg/pull/4061

@lefnire or @paglias, is it possible for this to be pushed to production soon?

**Comment by paglias** [comment] 2014-09-22 10:37
Merged but I can't push to production, only Tyler does

**Comment by negue** [comment] 2014-09-22 10:48
@Alys Yes, Exactly like this.

**Comment by draky177** [comment] 2014-09-22 10:51
Hi, I'm having the same problem as listed above. All of my To-Dos vanished overnight. I tried to do the fix described above - I've seen two identical tasks (identical in name, even with the same typo) in my android app so I deleted both of them. However, it didn't affect To-Dos in my Chrome browser. I can work with the app for some time, I'm just really happy I've found this thread and got reassured all my To-Dos (about 150 of them, my whole life) are not gone

My user ID 7d609a55-9799-4b6d-9139-df81790092ff

**Comment by negue** [comment] 2014-09-22 10:59
@draky177 This is "just" a viewing Issue on the Website. All data is still on the server.

Also thanks for your Informations, that 2 Tasks with the Name are existing are the bigger issue^^.

Once the new version of the website is pushed, you should be able to see your tasks again :)

**Comment by Alys** [comment] 2014-09-22 16:32
Reopened (it was closed automatically when the fix was committed) and assigned to @lefnire for him to make this commit live: https://github.com/HabitRPG/habitrpg/commit/73f7f6605e0c4ea34ba87c6b5a2f213858e796a0

**Comment by ladybesu** [comment] 2014-09-22 18:15
I encountered the same problem. My to do list is gone in Windows but is visible in the iPad app. To note, over the past few days I also had problems with duplicate items on my to do list (i.e. I add one and two appeared) and was just renaming one and moving onward. This happened several times.

My user ID is 9ce807c5-1ce6-4a1e-a69d-cd4b0b67dbe2

When will a new version of the website go live? I can make do by checking off items on the app, but it's not as convenient. Thanks so much for your help!

**Comment by Alienor77310** [comment] 2014-09-22 18:43
Same problem as above, to-dos don't appear on the web page (firefox and chrome), but show on the app.
UUID: 778106ba-4217-40fc-a61c-9cb3bf5d06b4

**Comment by crochet0721** [comment] 2014-09-22 19:15
Hello,

I am sorry if this is the wrong area, I am not technologically savvy and had trouble following the conversation. I would like to report that my tasks have completely vanished on Safari desktop browser (and it is not related to tags.) I use the iPhone app, and tasks are showing up there. I tried to make a new task on the website using Safari, it disappeared, but shows up on my iPhone app. Is this just a matter of waiting for a fix, or is there something I can do? Thank you~!

**Comment by lefnire** [comment] 2014-09-22 19:32
pushing recent changes to production now

**Comment by lemoness** [comment] 2014-09-22 20:34
@lefnire Site crashed just about this time - is it the typical Challenges bug, or did something in this push break things?

**Closed as completed** 2014-09-22 21:53 UTC

**Comment by helenl7** [comment] 2014-09-22 23:39
i got my todos back!  thank you habitlords!

**Comment by draky177** [comment] 2014-09-23 09:52
My To-Dos are back too! :) Thank you so much for a such quick response! Love you and HabitRPG! :)

**Comment by sej3506** [comment] 2014-12-11 21:44
This is slightly unrelated in the sense that it is affecting me on my mobile device, but here goes.

I cannot see any of my habits, to-dos, dailies, or custom rewards on the Internet Explorer app on my Windows Phone.

User ID: 5700df36-0f57-4d6c-9089-c2293568a583
Phone info: Windows Phone 8 using the Windows Phone 8.1 Update (OS Version 8.10.14141.167)

Clearing the cache on the phone did not work. Neither restarting the phone browser or turning my phone on/off worked. I still see all my tasks on PC browsers correctly.

Let me know what more information I can provide. This has been going on for at least 3 days, but I haven't checked consistently because I knew it wasn't working properly on my phone.

**Comment by Alys** [comment] 2014-12-11 22:17
@sej3506 On Internet Explorer, click the "clear" button next to the tags, even if it looks as if no tags are selected. Does that help?

**Comment by sej3506** [comment] 2014-12-12 15:20
@Alys I feel silly for not doing this first. But yes, this solved the problem. Thank you!
