### ISSUE TITLE
Task creation dailies glitch

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#891] opened 2013-05-04 14:11 UTC
I can't create more than one new daily anymore. Creation of goal A is normal. After I create goal B though, the name of A changes to B immediately. Also, if I open the settings of any one of them, it opens the settings of the top one. If I refresh, only one goal remains. If I delete one of them, all of them will be gone after a refresh.

Here are the error messages I have in the Chrome Console. They are there after loading the page, I don't get any new ones while creating the new dailies.
GET https://www.assoc-amazon.com/e/ir?t=ha0d2-20&l=as2&o=1&a=1400069289  /:21
GET https://www.assoc-amazon.com/e/ir?t=ha0d2-20&l=as2&o=1&a=0142000280  beta.habitrpg.com:21
GET https://www.assoc-amazon.com/e/ir?t=ha0d2-20&l=as2&o=1&a=0312430000  beta.habitrpg.com:21
GET https://www.assoc-amazon.com/e/ir?t=ha0d2-20&l=as2&o=1&a=1594484805  beta.habitrpg.com:21
GET https://www.assoc-amazon.com/e/ir?t=ha0d2-20&l=as2&o=1&a=1400069289  4qVIbo2pENG5kFIVkcFXJw.js:6
GET https://www.assoc-amazon.com/e/ir?t=ha0d2-20&l=as2&o=1&a=0142000280  4qVIbo2pENG5kFIVkcFXJw.js:6
GET https://www.assoc-amazon.com/e/ir?t=ha0d2-20&l=as2&o=1&a=0312430000  4qVIbo2pENG5kFIVkcFXJw.js:6
GET https://www.assoc-amazon.com/e/ir?t=ha0d2-20&l=as2&o=1&a=1594484805  4qVIbo2pENG5kFIVkcFXJw.js:6
GET https://wms.assoc-amazon.com/20070822/US/js/link-enhancer-common.js?tag=ha0d2-20&_=1367676606496  4qVIbo2pENG5kFIVkcFXJw.js:16

**Comment by themenniss** [comment] 2013-05-04 20:43
I'm also experiencing this. The behaviour is the same with habits and todos as well. For example, if I create a habit "A" and then create a daily "B" then "A"'s name will immediately be changed to B. Deleting B will leave a blank habit where the "A" was.

**Comment by ghost** [comment] 2013-05-04 20:54
Getting the same problem here, doesn't matter which browser I use. This also seems to occur: If I create "A" under Dailies, it'll also be created under Habits. (It disappears upon refreshing the page.)

**Comment by octern** [comment] 2013-05-04 22:14
Confirming that the bug in the original post is occurring on Windows 7 and MacOS 10.8, both using Chrome. Bad timing, too... I'd just talked my wife into trying it. 

Reloading appears to get rid of the duplicate task, but it doesn't restore the task that was overwritten.

**Comment by justdiver** [comment] 2013-05-04 23:21
I can also confirm I'm experiencing this bug.  I can reproduce this using a different computer and browser.  That is, Chrome on computer A, Internet Explorer on computer B.

**Comment by fawques** [comment] 2013-05-05 00:59
Firefox in ubuntu happening here too. In my case I created a Todo and it created a copy in Habits. Creating another Todo changed the fake Habit text to the new one, and created the other Todo. Refreshing made everything disappear, leaving these 2 errors:

20a7ce0f-5c50-4b01-bcec-36e9dab0d3b1's habits were corrupt.
20a7ce0f-5c50-4b01-bcec-36e9dab0d3b1's todos were corrupt.

**Comment by heyimzsa** [comment] 2013-05-05 04:59
I'm experiencing this issue as well in Windows Chrome just like @themenniss except after refreshing a few times, my GP went from 113 to 0.

Edit: I also wanted to add that when I tried to attempt making a new habit, something happened to my avatar. She's missing her face! Attached is the ghost avy and the habit I made
![capture](https://f.cloud.github.com/assets/4038162/463239/9567d268-b542-11e2-953b-62353b96d045.png)

**Comment by Eusebius** [comment] 2013-05-05 07:08
I confirm the issue... I am now unable (since May 4th) to create any new habit, daily, todo or reward.

**Comment by lefnire** [comment] 2013-05-05 09:18
confirmed, fixing

**Comment by lefnire** [comment] 2013-05-05 10:45
Having a helluva time with this one. Did an `npm update` locally and started getting the bug. Did `git bisect` on my code to be sure it was an npm module that introduced the bug, sure enough the bisecting back a month or two and it still shows up - so definitely an npm module. Looked through the top level dependencies, nothing's changed in the last few days - so it's gotta be a submodule, which makes this really hard to hunt. 

@switz any thoughts? The bug is you `modul.unshift('_habitList',...)` and `model.unshift('_dailyList',...)`, etc, and some blanks appear in the other lists as well. i'm gonna keep hunting

**Comment by Lukking** [comment] 2013-05-05 10:46
Thanks. I will definately show this my friends, if it works properly. This is amazing!!!

**Comment by lefnire** [comment] 2013-05-05 11:00
don't show till we get this fixed :)

**Comment by Lukking** [comment] 2013-05-05 11:02
of course :D

**Comment by Nolori** [comment] 2013-05-05 18:27
This is an issue for me too, however the only thing on my console is "Unknown RPC service: widget-interactive-I0_1367778253468 cb=gapi.loaded_0:116"

I'm using Chrome on Win 7

**Comment by lefnire** [comment] 2013-05-05 20:37
wooaa! `model.id()` returns gibberish, which is non-unique `"NaN-undefinedundefined-40undefined-80undefined-undefinedundefinedundefinedundefinedundefinedundefined"` - so new tasks are getting the same id. But I'm not seeing `node-uuid` as having been updated recently... digging more

**Comment by switz** [comment] 2013-05-05 20:43
Wow, that's totally weird - happening for me too. I'll look into it.

**Comment by switz** [comment] 2013-05-05 20:46
I'm fairly certain Derby uses this to generate uuids https://github.com/broofa/node-uuid - Tried `DERBY.app.model.id()` on unroll.me (slaks) and it returns a normal id as well as PhishVids.

**Comment by lefnire** [comment] 2013-05-05 20:50
Yeah, it does use node-uuid. But that hasn't been updated recently, I'm
step-debugging node-uuid

**Comment by lefnire** [comment] 2013-05-05 21:40
testing on phishvids live, √ . download to local, npm install, test on phishvids local - corrupt id. something in node-uuid, gotta be a crypto module update or some such

**Comment by switz** [comment] 2013-05-05 22:25
Weird as node-uuid doesn't depend on anything. Must be a Racer bug...

**Comment by lefnire** [comment] 2013-05-05 22:40
well, lefnire/racer#habitrpg patches it now, so we can close this in hopes i can find a real fix soon. added more info at https://github.com/SLaks/racer/issues/12 .

**Closed as completed by lefnire** 2013-05-05 22:40 UTC

**Comment by lefnire** [comment] 2013-05-05 22:41
@Chaudie click the female head option in the profile tab, see if that sorts out the ghost bit.

**Comment by heyimzsa** [comment] 2013-05-06 00:24
Alright I fixed it. I just needed to reselect my options. Thanks!
—
