### ISSUE TITLE
Odd Pet Feeding Behavior

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#9368] opened 2017-11-02 04:52 UTC
We've received some reports that sometimes when a user quick-hatches a pet where they already have the mount (not sure if it happens other times), the greyed-out don't-have-this-pet-but-do-have-the-mount icon doesn't update to a regular colored have-this-pet icon until a refresh. This means that, until I reload, they can still click on the greyed-out icon and get the dialogue for hatching the pet again, except that the buttons don't do anything any more. This seems to be a similar problem to the one that people sometimes report when they tame a pet into a mount where the feeding bar disappears, but the pet icon doesn't grey out until they reload the page, preventing them from hatching a new one.

We've also had a follow-up report: "The thing I discovered today when hatching pets (in cases where I already have the mount) was that the bug only seemed to affect pets hatched after the first. So if i hatch just one pet for which I have the mount, the new pet's full-color icon will show up. But the second, third, and presumably etc. pets I hatch in that situation don't get their full-color icons until I reload the page. I can't test other pet growth stages right now, but hopefully this is at least another data point for those working to resolve the issue."

Beth has added: "When I raise a pet to a mount, the pet icon does grey out. But, when I hatch the pet to replace the mount, 1) there does not seem to be any obvious indicator that I can or cannot hatch the pet 2) when I hatch the new pet the icon stays greyed out until I do a full refresh (but not always- weirdly this issue seems to happen with the classic pet set but maybe not with quest ones?)

I've also had a couple where it seems like it auto-hatched the new pet after I raised the mount. I raised a Zombie seahorse, but due to sync errors clicked it maybe an extra time? Then all of a sudden I had the pet without seeing the hatching popup at all. But then on refresh I had to hatch it again."

We should definitely investigate these.

**Comment by TheHollidayInn** [comment] 2017-11-27 18:45
This issue doesn't seem to be happening for me. I'd suggest we close unless someone else can recreate or we get more reports.

**Comment by Alys** [comment] 2018-02-12 21:49
A related problem was just posted by NoCyg (154802ac-9567-4916-ac66-79ea5ba81ec7) in the Report a Bug guild:

"In Chrome, I discovered that when you raise a pet to a mount, the pet icon does not automatically switch to grayed out (indicating that you hatched the pet but do not currently have one). This led to a weird instance where I'd raised the pet to a mount, then clicked on its icon to try to re-hatch it, but instead ended up setting the pet (which I didn't actually have) as my avatar pet. This did resolve on a refresh (although I did have to re-select the avatar pet I actually wanted)."

I've seen similar behaviour to this and some of the comments above although I've never bothered to report them - sorry, I should have (too used to seeing minor glitches like this to really pay attention each time). It doesn't seem to happen all the time but there can definitely be a delay in the Stable updating itself when a pet's status changes.

**Comment by Alys** [comment] 2018-04-21 23:01
I'm reopening this because I've seen one report that it's still happening and I don't think  #10243 could fix it. That PR adjusts which icon is shown when you are able to re-hatch a pet but it doesn't have any code for making sure the icon does get updated at the time that you re-hatch the pet.

**Comment by Alys** [comment] 2018-04-22 03:07
Here's an example of this bug for the case where I did not already have the mount. The screenshot below was taken immediately after I had used a Saddle to turn the Base Wolf Pet into a Mount. This was my `items.pets` and `items.mounts` data at the same time the screenshot was taken:
```
    "items": {
        "mounts": {
            "Wolf-Base": true
        },
        "pets": {
            "Wolf-Base": -1
        }
    },
```

![image](https://user-images.githubusercontent.com/1495809/39090930-d7332c98-462d-11e8-96c0-f197cf58a18d.png)

Syncing did not fix the problem. Reloading did.

**Comment by kirsty-tortoise** [comment] 2018-09-24 21:21
Is this still happening? This used to happen to me a lot but hasn't recently and I haven't been able to reproduce it, and I'd be interested in what is / was causing it.

**Comment by Alys** [comment] 2018-11-21 07:31
There's been several changes to the code responsible for this feature since this was logged so any remaining problems are likely to be (slightly?) different to the ones reported here and/or be caused by different code. I'm closing this but if we get more reports of incorrect behaviour, we will log a new issue with specific details of the current problems.

**Closed as completed by Alys** 2018-11-21 07:31 UTC
Labels: priority: medium, help wanted, section: Stable
