### ISSUE TITLE
Disallow line breaks in display names

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica#11946] opened 2020-03-04 23:04 UTC
A user managed to put a line break in their display name:

![image](https://user-images.githubusercontent.com/8144640/75931194-48dad000-5e6c-11ea-8656-60a4be4328ef.png)

This seems like a bad idea, so the desired fix is to disallow any linebreaks in users' display names.

**Comment by Alys** [comment] 2020-03-05 01:37
The line breaks were inserted by typing `\n` into the profile name.

We'd want to be cautious that any change that prevented this didn't prevent legitimate uses of backslashes. For example, maybe backslashes are used when entering characters in some languages that don't use the Latin alphabet.

**Comment by paglias** [comment] 2020-03-05 10:37
I think `\n` is the universal way to input line breaks so it should be fine to block exactly that behavior

**Comment by kareenf** [comment] 2020-04-02 21:11
I'm interested in working on this!

Edit: My colleague (@nathanzhu144) and I will be working on this together

**Comment by Alys** [comment] 2020-04-03 00:01
@kareenf Thank you! Please go ahead and post here if you have questions or run into trouble!

**Comment by nathanzhu144** [comment] 2020-04-09 20:00
@shanaqui 
@Alys 
I'm having trouble reproducing this problem.

I am adding \n to the display name, like 
![Screenshot from 2020-04-09 15-58-11](https://user-images.githubusercontent.com/26507505/78935635-1af43700-7a7b-11ea-8f68-94f2f464532d.png)

However, this only shows up as \n.  Is there anything else special that needs to be done?

I noticed that in validation.js, there are some additional checks for validity in the username that is not done in display name.  For example, in the verifyUsername function, there is a "invalidCharsRegex" that is checked against, but this is not called in the verifyDisplayName function.  Is this intentional?
![Screenshot from 2020-04-09 16-07-34](https://user-images.githubusercontent.com/26507505/78936293-4f1c2780-7a7c-11ea-80bc-525667070fed.png)

**Comment by Alys** [comment] 2020-04-10 04:21
@nathanzhu144 I'm very sorry, my comment about them typing \n into their profile name didn't give enough information. I shouldn't have been that brief. :-/

I've just done some testing and the website's edit form for the Display Name will correctly convert `\n` to `\\n` (i.e., it escapes the backslash so that that `\n` no longer has special meaning).

However the API doesn't do that escaping. You can put two `\n` line breaks into your Display Name using a command like the one below. Two are needed to get the full blank line effect.

`curl -X PUT -H "Content-Type: application/json" -d "{ \"profile.name\": \"A Little\\n\\nYellow Spider\" }" -H "x-api-user: $USERID" -H "x-api-key: $APITOKEN" https://habitica.com/api/v3/user`

Note that that command itself escapes the backslashes by putting another backslash in front of each (`\\n\\n`) but that's to prevent `\n` having special meaning in my Linux shell.

When the API receives that command, it sees this new text for the Display Name: `A Little\n\nYellow Spider`
I.e., the backslashes are not escaped in the command that the API receives.

The API does not do its own escaping of the backslashes and so the Display Name is stored in Habitica's database as `A Little\n\nYellow Spider`

Please tell me if any of that doesn't make sense or if you'd like more information!

**Comment by Alys** [comment] 2020-04-10 04:24
I think it would be sufficient for the API to escape backslashes before it inserts them into the database.

That won't fix any existing instances where a user has already inserted \n (or any other backslashed character) into their name but admins can do a database migration to fix them, or probably better a manual search and fix since there's likely to be hardly any accounts that do this. (Or we could even just leave the existing cases unchanged. If the display name bothers the party members, they can ask the person to change it.)

**Comment by nathanzhu144** [comment] 2020-04-10 21:29
@Alys 
Thanks for the comprehensive reply!  I'm currently getting these error messages when doing the curl command that you posted.  I am substituting the API name and the key variables, so I don't think that is the issue?

curl: (6) Could not resolve host: LittlennYellow
curl: (3) [globbing] unmatched close brace/bracket in column 8
{"success":false,"error":"SyntaxError","message":"Unexpected token p in JSON at position 2"}

Do you know what might cause this?

**Comment by Alys** [comment] 2020-04-11 03:09
@nathanzhu144 Ah sorry. :( Some essential backslashes weren't being displayed. I've wrapped it in backticks and it's working for me now. Post again if it's still not good for you.

**Comment by nathanzhu144** [comment] 2020-04-12 22:24
@Alys 
Thank you so much for all the detailed help! :)
I've managed to somewhat reproduce the problem.  I was not able to see the effect of the /n on the display name, but after trying other escape characters like /t, I was able to get effects on the display name.

Here's after inserting tabs.  Note the tabs in between the chars.
![Screenshot from 2020-04-12 18-18-42](https://user-images.githubusercontent.com/26507505/79081331-80019400-7cea-11ea-842b-b7fe4909de49.png)

Here's after inserting newlines.  The lack of space in between the two words is where the newlines should've appeared.
![Screenshot from 2020-04-12 18-21-05](https://user-images.githubusercontent.com/26507505/79081337-842db180-7cea-11ea-8672-d781af567cd4.png)

Is there a way to see the newlines being a problem?

**Comment by Alys** [comment] 2020-04-13 00:17
Try making a post in the Tavern or other chat space. Two \n in the name should show up as a line break there. Tell us if it doesn't.

**Comment by nathanzhu144** [comment] 2020-04-13 21:42
@Alys 
![Screenshot from 2020-04-13 17-40-35](https://user-images.githubusercontent.com/26507505/79163926-fadfb300-7dad-11ea-9a0b-c4da3daf4abd.png)

When I post in the Tavern, I don't see a linebreak in my name.

![Screenshot from 2020-04-13 17-41-48](https://user-images.githubusercontent.com/26507505/79163971-12b73700-7dae-11ea-8572-be31d8e2d426.png)

I don't see it in my display name, either, just like yesterday.  Maybe I am posting in the wrong place?

From what I can see, there is some kind of parser than sees the newline, and even though the display name viewer in "settings" doesn't add a space, in the Tavern, a space is added where the newlines were.

**Comment by Alys** [comment] 2020-04-14 08:39
Hmm, sorry, I thought I had tested a while back with a Tavern or guild post and the line break did appear in the name but I might be misremembering.

Anyway, it's not really important to see the line break effect. The important thing is that if you enter a backslash in the name when you use that API command, the data stored in the database should have two backslashes. And if you enter two backslashes, the data stored should have four, and so on. I.e., every backslash you enter should be escaped by a backslash being placed in front of it.

On your local install you can confirm that by doing the API command to edit the profile name, then a mongodb "find" command to show you the stored data (there's info about mongodb commands in the wiki docs, but post here if you need help with that).

You can also use what you've found about `\t` for testing visually. When backslashes are escaped properly, you'll stop seeing the tab space in the Display Name field in settings and start seeing a literal `\t` instead.

**Comment by shanaqui** [comment] 2020-04-30 12:38
I just thought I'd add in case there's any confusion about how to reproduce: the post where it was seen was a system message, showing the user's progress on a quest. The person reporting didn't state having seen it anywhere else.

**Comment by shanaqui** [comment] 2020-04-30 12:39
@kareenf, @nathanzhu144 Are you still working on this one? If not, I'll add the help wanted label back so other folks can take a look.

**Comment by kareenf** [comment] 2020-05-03 21:52
@shanaqui hey, sorry for the late response! I just got done with all my finals so I wasn't able to respond until now. At the moment, I think it'd be best to put the help wanted label back. Thanks!

**Comment by shanaqui** [comment] 2020-05-05 19:51
@kareenf No worries, I'll do that now. :) You can always let us know if you want to pick it up again later.

**Comment by Amberlisi** [comment] 2020-05-30 23:48
Hi, I'd like to pick this up if that's alright. I was able to reproduce this error using the API

![image](https://user-images.githubusercontent.com/43859793/83341183-0461a380-a2a6-11ea-88b6-2f635cfd6922.png)

**Comment by Alys** [comment] 2020-05-31 04:03
@Amberlisi  Thank you! Please go ahead, and post here if you have questions.

**Comment by Amberlisi** [comment] 2020-06-01 18:24
@Alys Are these API calls being handled in website/server/libs/user/index.js? That's what it looks like to me, but wanted to verify in case I'm wasting time going down the wrong path.

**Comment by Amberlisi** [comment] 2020-06-03 02:32
Hey! So, something that I noticed while running through a few tests was that running the API command to set the players display name will error out if a '\\' is followed by anything other than a character such as 'n', or 't', or 'r'. I've tried this with one, and two backslashes. Both produced the same error.

I'm not sure how this kind of scenario can be handled and wondering if there are any thoughts about this?

**API Command**
```
curl -X PUT -H "Content-Type: application/json"  -d " {\"profile.name\": \"ac\\dc\"
}" -H "x-api-user: $USERID" -H "x-api-key: $USERKEY" http://localhost:8080/api/v3/user
```

**Error I get**
```
2020-06-03T02:20:40.012Z - warn SyntaxError: Unexpected token d in JSON at position 22
    at JSON.parse (<anonymous>)
    at parse (/Users/amber/Documents/GitHub/habitica/node_modules/body-parser/lib/types/json.js:89:19)
    at /Users/amber/Documents/GitHub/habitica/node_modules/body-parser/lib/read.js:121:18
    at invokeCallback (/Users/amber/Documents/GitHub/habitica/node_modules/raw-body/index.js:224:16)
    at done (/Users/amber/Documents/GitHub/habitica/node_modules/raw-body/index.js:213:7)
    at IncomingMessage.onEnd (/Users/amber/Documents/GitHub/habitica/node_modules/raw-body/index.js:273:7)
    at IncomingMessage.emit (events.js:323:22)
    at IncomingMessage.EventEmitter.emit (domain.js:505:15)
    at endReadableNT (_stream_readable.js:1204:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
{
  method: 'PUT',
  originalUrl: '/api/v3/user',
  headers: {
    'x-forwarded-host': 'localhost:8080',
    'x-forwarded-proto': 'http',
    'x-forwarded-port': '8080',
    'x-forwarded-for': '127.0.0.1',
    'content-length': '27',
    'x-api-user': 'f35e2c02-53a3-4d96-aa9b-024e44f72e14',
    'content-type': 'application/json',
    accept: '*/*',
    'user-agent': 'curl/7.64.1',
    host: 'localhost:3000',
    connection: 'close'
  },
  body: {},
  query: {},
  httpCode: 400,
  isHandledError: true,
  fullError: SyntaxError: Unexpected token d in JSON at position 22
      at JSON.parse (<anonymous>)
      at parse (/Users/amber/Documents/GitHub/habitica/node_modules/body-parser/lib/types/json.js:89:19)
      at /Users/amber/Documents/GitHub/habitica/node_modules/body-parser/lib/read.js:121:18
      at invokeCallback (/Users/amber/Documents/GitHub/habitica/node_modules/raw-body/index.js:224:16)
      at done (/Users/amber/Documents/GitHub/habitica/node_modules/raw-body/index.js:213:7)
      at IncomingMessage.onEnd (/Users/amber/Documents/GitHub/habitica/node_modules/raw-body/index.js:273:7)
      at IncomingMessage.emit (events.js:323:22)
      at IncomingMessage.EventEmitter.emit (domain.js:505:15)
      at endReadableNT (_stream_readable.js:1204:12)
      at processTicksAndRejections (internal/process/task_queues.js:84:21) {
    expose: true,
    statusCode: 400,
    status: 400,
    body: ' {"profile.name": "ac\\dc"\n}',
    type: 'entity.parse.failed'
  },
  level: 'warn',
  message: 'SyntaxError: Unexpected token d in JSON at position 22'
}
```

**Comment by Alys** [comment] 2020-06-03 09:22
> Are these API calls being handled in website/server/libs/user/index.js? That's what it looks like to me, but wanted to verify in case I'm wasting time going down the wrong path.

Sorry about the delay! Yes, I think it's the update() function in that file.

For your other question, I think what's going wrong is that \ has a special meaning in your PC's shell, as well as having a special meaning in the database. When you want to put a \ in a command-line command like that curl command, you need to escape the \ with another \
Also to put a \ into the database as a plain-text backslash, you need to escape the \ in the database with another \

So there's two sets of escaping that you need to do. When the update() function inserts the \ into the database, it actually needs to see `\\`  which means you need to put `\\` on the command-line in your curl command BUT each of those backslashes has to be escaped with its own backslash, so you actually need to use `\\\\` (four backslashes).

I.e., this should work:
```
curl -X PUT -H "Content-Type: application/json" -d "{ \"profile.name\": \"A\\\\n\\\\nYellow Spider\" }" -H "x-api-user: $USERID" -H "x-api-key: $APITOKEN" https://habitica.com/api/v3/user
```

That should change your profile.name to exactly this: `A\n\nYellow Spider` when you view it in the Habitica website. That means it should be stored as exactly this in the database: `A\\n\\nYellow Spider` 

Post again if any of that doesn't make sense or if it doesn't seem to work!

**Comment by Amberlisi** [comment] 2020-06-19 02:29
Okay, so too many hours later and I realize that a thing called JSON.Stringify exists. Which automatically escapes the slashes and new lines that get entered when running the API to change the display name. I can throw a bunch of slashes and new lines into the name and it comes out looking perfect! The file that would be changed is the index.js file, within the update function

`    if (acceptablePUTPaths[key] && key !== 'tags') {
      const escapedName = JSON.stringify(val);
      _.set(user, key, escapedName);
    } else if (key === 'tags') {
      if (!Array.isArray(val)) throw new BadRequest('mustBeArray');`

**Comment by Amberlisi** [comment] 2020-06-19 04:19
> Okay, so too many hours later and I realize that a thing called JSON.Stringify exists. Which automatically escapes the slashes and new lines that get entered when running the API to change the display name. I can throw a bunch of slashes and new lines into the name and it comes out looking perfect! The file that would be changed is the index.js file, within the update function
> 
> ` if (acceptablePUTPaths[key] && key !== 'tags') { const escapedName = JSON.stringify(val); _.set(user, key, escapedName); } else if (key === 'tags') { if (!Array.isArray(val)) throw new BadRequest('mustBeArray');`

I just realized that it puts quotes at the beginning of the string, and the end of the string

**Comment by Amberlisi** [comment] 2020-06-19 05:18
@Alys Alright, many hours later I realize there's a JSON.stringify method that will escape an entire string. Not sure if this is a good practice or not, but it has successfully changed the display name with any number of backslashes and new lines. The JSON string output prepends and appends double quotes " " on the string. So I had to slice the string to remove those from the final displayname value.

`    if (acceptablePUTPaths[key] && key !== 'tags') {
      const escapedName = JSON.stringify(val).slice(1, -1);
      console.log(escapedName);
      _.set(user, key, escapedName);
    } else if (key === 'tags') {
      if (!Array.isArray(val)) throw new BadRequest('mustBeArray');`

**Comment by paglias** [comment] 2020-06-20 16:26
Hi @Amberlisi , I think the best place to fix this would be [here](https://github.com/HabitRPG/habitica/blob/develop/website/server/libs/user/validation.js#L29) since we already have a method used to check for the validity of display names, we could expand it to disallow line breaks. 

I *think* but @Alys can confirm that we don't want to limit display names to latin chars like we do for usernames so a regex might not be necessary, we could simply do a search for the `\n` char in a string using the `.includes` method like this:

<img width="328" alt="Schermata 2020-06-20 alle 18 25 28" src="https://user-images.githubusercontent.com/589911/85206608-95ff8680-b323-11ea-9e7c-a072a8b18359.png">
<img width="414" alt="Schermata 2020-06-20 alle 18 26 32" src="https://user-images.githubusercontent.com/589911/85206609-9730b380-b323-11ea-8759-cdd380499ae7.png">

**Comment by Amberlisi** [comment] 2020-06-20 16:29
@paglias Oh, so we are RESTRICTING the user from using '\\n' in their names? I thought the goal was to check if the user used a new line and then make it so that it would be displayed properly.

**Comment by paglias** [comment] 2020-06-20 16:32
Yeah my understanding is that the aim here is to disallow that since I can't think of any benefit / reason for allowing new lines in display names

**Comment by Amberlisi** [comment] 2020-06-20 16:33
Well, it's not that we would want to allow a new line, but we would want to clean up the text so that it's not seen as a new line, but as a literal '\\n' instead.

If we are going to disallow users from using '\\n' why don't we just disallow any use of backslashes in the name?

**Comment by paglias** [comment] 2020-06-20 16:54
> If we are going to disallow users from using '\n' why don't we just disallow any use of backslashes in the name?

from a previous comment by @Alys 

> We'd want to be cautious that any change that prevented this didn't prevent legitimate uses of backslashes. For example, maybe backslashes are used when entering characters in some languages that don't use the Latin alphabet.

Also I'm not sure we want to ban backslashes in general from display names, usernames are restricted to a-z and 0-9 mostly but display names should have more freedom IMO

anyway let's see what @Alys and @shanaqui think

**Comment by Alys** [comment] 2020-06-26 02:50
So sorry about the delay in my reply!

> I think but @Alys can confirm that we don't want to limit display names to latin chars like we do for usernames so a regex might not be necessary, we could simply do a search for the \n char in a string using the .includes method...

Yes, I agree!

Also as paglias says in the previous comment, it'd be best to not ban backslash altogether. Just converting `\n` to `\\n` (i.e., escaping the backslash in that case) is the safest approach.

**Comment by Amberlisi** [comment] 2020-06-26 03:37
So we aren't checking for validity. We are taking the users input and changing the output to escape the characters. Keep in mind that this also happens for \b, \r, \t etc. \\n is not the only problem. And I don't know if it's because of my settings, but the API won't even let a user input a string that contains a backslash followed by a character that doesn't have a special function, such as \\a or \\4 which throws a JSON error. Perhaps there's a way to also fix that, but I haven't found it yet.

{"success":false,"error":"SyntaxError","message":"Unexpected token A in JSON at position 21"}

**Comment by Amberlisi** [comment] 2020-06-26 04:19
Something else interesting I noticed regarding non-Latin characters... I'm actually having problems getting these to work even without making any changes to the way the code works now. So, if I try to change my name to: "Añ傳Yellow Spider" using the API it returns A�?Yellow Spider. Doing this in the UI works though. But I also don't understand non-Latin characters and how they work

**Comment by paglias** [comment] 2020-06-26 13:39
@Alys regarding this

> Also as paglias says in the previous comment, it'd be best to not ban backslash altogether. Just converting \n to \\n (i.e., escaping the backslash in that case) is the safest approach.

Actually I was proposing of banning `\n` altogether as javascripts always transform it in a return carriage

<img width="201" alt="Schermata 2020-06-26 alle 15 32 56" src="https://user-images.githubusercontent.com/589911/85862671-625caa80-b7c2-11ea-8db7-d66afcd05c0d.png">

So `string.includes("\n")` will return true only if a return carriage exists in the string not if you manually type `\n` in an input field. You can verify that by typing `\n` in a textarea, reading it's value with JS and verifying that `stringWithBacksSlashN.included("\n")` returns `false`

**Comment by Alys** [comment] 2020-06-28 12:02
@paglias Ah, sorry about that! I misunderstood. Thanks for the correction. :)

@Amberlisi I have trouble with non-Latin characters on the command-line and in scripts sometimes too. I think my Linux box doesn't have proper support for them. Something like that may be what's going wrong for you. It's likely not a problem that will affect this issue.

**Comment by Amberlisi** [comment] 2020-07-08 18:29
So I would make changes to 3 files:
1. settings.json - Needed for a new error message when a user tries to set their display name using a backslash followed by the letter n
2. validation.js - To add a check for the occurrence of a backslash followed by the letter n
3. index.js - To get the validator in the UI to check for the presence of a backslash followed by the letter n

I think all of the settings.json files will need to be updated for the different locales, correct? Is there a fast way to do that?

Also, is there a better way to share my code instead of pasting it in here?

settings.json
`"displaynameIssueNewline": "Display Names may not contain backslashes followed by an n.",`

validation.js
```
export function nameContainsNewline (username) {
  if (username.includes('\n') || username.includes('\\n')) {
    return true;
  } else {
    return false;
  }
}
```
```
export function verifyDisplayName (displayName, res) {
  const issues = [];
  if (displayName.length < 1 || displayName.length > 30) issues.push(res.t('displaynameIssueLength'));
  if (nameContainsSlur(displayName)) issues.push(res.t('displaynameIssueSlur'));
  if (nameContainsNewline(displayName)) issues.push(res.t('displaynameIssueNewline'));

  return issues;
}
```

index.js
```
export async function update (req, res, { isV3 = false }) {
  const { user } = res.locals;

  let promisesForTagsRemoval = [];

  if (req.body['profile.name'] !== undefined) {
    const newName = req.body['profile.name'];
    if (newName === null) throw new BadRequest(res.t('invalidReqParams'));
    if (newName.length > 30) throw new BadRequest(res.t('displaynameIssueLength'));
    if (nameContainsSlur(newName)) throw new BadRequest(res.t('displaynameIssueSlur'));
    if (nameContainsNewline(newName)) throw new BadRequest(res.t('displaynameIssueNewline'));
  }
```

**Comment by paglias** [comment] 2020-07-08 18:42
> I think all of the settings.json files will need to be updated for the different locales, correct? Is there a fast way to do that?

Only the english file will have to be changed! the others will be updated automatically

as for the code my suggestion would be to start by opening a PR in draft state, even if the code doesn't work yet it'll make it easier to comment on it

**Closed as completed** 2020-07-18 20:41 UTC
Labels: priority: minor, status: issue: in progress, section: Other
