### ISSUE TITLE
Incorrect profile or partial profile data appears under some circumstances - caching old data

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica#11066] opened 2019-03-15 23:35 UTC
_EDIT by Alys 2019-03-19:_   We've seen other reports in addition to the one below to indicate that sometimes profile data from a previous player who you looked at is cached and displayed when you try to view a different player. This display of cached data is permanent (until you close the profile), not temporary as in https://github.com/HabitRPG/habitica/issues/11051 

Possibly the fix should be to clear the cache of any profile data before you open a new profile. That might also fix https://github.com/HabitRPG/habitica/issues/11051 (that issue is currently expected behaviour but probably not desirable).

_The original bug report follows._

---

Reported in Report a Bug; personally cannot reproduce it anymore, though I know I have seen it happen. 

> "For a while, often when I click on someone to view their profile, it pops up someone else's profile. I don't know if this is a known bug or not, but I wanted to report it."

I asked for further details:

> _Benjamin, the Avid Reader @loverofbooks (fc6bd8d5-94a2-462b-ac7f-9b03bc446d45): "I think I figured it out actually. It seems to happen if I click on a profile while Habitica is syncing. The next time I click a profile, it shows that other person's profile. It seems it also makes the sync take longer, but if it finishes syncing, the bug stops.
> 
> I have absolutely no idea what is causing this."_

Possibly just a duplicate of this one: https://github.com/HabitRPG/habitica/issues/11051 (but not sure since the user describes the wrong profile staying open, and I also have observed that)

**Comment by Alys** [comment] 2019-03-19 03:37
I've added this to the top post:

----
 We've seen other reports in addition to the one below to indicate that sometimes profile data from a previous player who you looked at is cached and displayed when you try to view a different player. This display of cached data is permanent (until you close the profile), not temporary as in https://github.com/HabitRPG/habitica/issues/11051 

Possibly the fix should be to clear the cache of any profile data before you open a new profile. That might also fix https://github.com/HabitRPG/habitica/issues/11051 (that issue is currently expected behaviour but probably not desirable).

---

Here's a report from Remeday (d0a3217a-7b92-48d6-b39a-b1b1be96702e):

_"Here's another report related to the "wrong profile" bug: I've been getting the wrong Stats page specifically when loading a profile (it's always the stats page of a profile I'd loaded earlier), while the rest of the profile is for the correct user._
_For example, if I click on Nixcyd's avatar below, the stats page shows gear that doesn't match the avatar, and while the level at the top says 62, and the XP bar shows 1720 needed for the next level, the level bonus on the Stats page is 1."_

**Comment by Alys** [comment] 2019-04-20 22:28
This also happens when trying to view the profile of a player who has deleted their account. cTheDragons reports:
"Click on an account that is deleted in chat and receive the last profile you looked at. If it is the first profile you logged on you will receive yours."

What should happen is that you see a 404 (Page Not Found) error message as described by Tressley in https://github.com/HabitRPG/habitica/issues/11020

**Comment by Alys** [comment] 2019-06-25 08:32
Just to confirm that this still happens, here's a recent report of it:
"sometimes when I try to load and look at somebody's profile it says it's loading me but it's blank. Sometimes a profile will come up but sometimes it stays blank"

**Comment by paglias** [comment] 2020-07-04 20:38
I think this has been fixed by a PR this week, can anyone confirm if it keeps happening?

**Comment by Alys** [comment] 2020-07-05 07:08
This was always intermittent and hard to reproduce but since there's been recent changes to how profiles are loaded, I think it's reasonable to close this and we can reopen if we see new reports of it.

**Closed as completed by Alys** 2020-07-05 07:08 UTC
Labels: priority: medium, help wanted, section: Avatar/User Modal
