### ISSUE TITLE
Colored level number showing wrong color on popup window

### ISSUE THREAD

**Issue by Mihakuu** [HabitRPG/habitica#1920] opened 2013-11-26 15:45 UTC
I've noticed this before but just thought I was going crazy, finally figured out that it color fixes it the longer I leave the page up, but right after refreshing they're all a bit crazy. I haven't seen this issue here yet
![9 1](https://f.cloud.github.com/assets/3769301/1623249/b09e4498-56b1-11e3-86ca-110c22414b8a.PNG)
![9 3](https://f.cloud.github.com/assets/3769301/1623250/b09ec710-56b1-11e3-830b-e76ca50b2af2.PNG)
![9 4](https://f.cloud.github.com/assets/3769301/1623251/b09f499c-56b1-11e3-9dfc-81c2a15d6349.PNG)
![9](https://f.cloud.github.com/assets/3769301/1623252/b0a11966-56b1-11e3-98cb-e66860c3134b.PNG)

**Comment by snicker** [comment] 2013-11-26 18:36
This appears to be an issue with the modals being displayed before the user data has been fully loaded, so it shows the color of whatever profile was last viewed if it displays before the data has loaded in the browser. You see it properly the second time the modal is opened for the same user because the data has been cached.

**Comment by snicker** [comment] 2013-11-26 18:39
Steps to duplicate on beta.habitrpg.com:
1. Use a freshly loaded page.
2. Open a profile of a contributor. Label should be the default grey if the modal loads before data is recieved.
3. Close profile.
4. Open profile of same contributor. Label color should be correct. 
5. Open profile of a different user of a different contributor level. Label should be color of the previously opened contributor's profile if the modal loads before the data.
6. Close profile.
7. Re open that user's profile. Label should be correct color for that user's contributor/npc level.

**Comment by snicker** [comment] 2013-11-26 18:42
This doesn't make any sense because Angular should be changing the class when the data is received. @lefnire @paglias any clues?

**Comment by paglias** [comment] 2013-11-26 19:29
@snicker I believe it's https://github.com/HabitRPG/habitrpg/blob/develop/views/shared/header/avatar.jade#L30 this part inside `ng-class`:

`"label-contributor-{{profile.contributor.level}}": profile.contributor,`

As you can see from the screenshot below the `label-contributor-` class is applied but without the contributor level:

![selezione_0135](https://f.cloud.github.com/assets/589911/1625340/abce7d1a-56d0-11e3-9346-1cf04c6b4d32.png)

Try using javascript concatenation instead of interpolation:

`"'label-contributor-' + profile.contributor.level": profile.contributor,`

**Comment by snicker** [comment] 2013-11-26 19:43
Does that work? I suppose that ngclass will just evaluate the expression, so it should. That could fix one of our other issues with bindonce and interpolation problems. 

I don't know if that will fix _this_ problem though, as this is a issue of putting the cart (view) before the horse (data), have you tested it?

**Comment by paglias** [comment] 2013-11-26 19:51
Sorry I can't test it right now but I read it's the suggested way to go: http://www.thinkingincrowd.me/blog/2013/01/30/string-interpolation-should-not-be-used-with-class-directive-in-angularjs/

I don't know if it will work, I also think that the problem is of another type but it's worth the try

**Comment by snicker** [comment] 2013-11-26 19:51
seems to have worked.

**Comment by snicker** [comment] 2013-11-26 19:52
fixed in https://github.com/HabitRPG/habitrpg/commit/15f3907f00d9d70445980b15f16b54cccf699d74

**Comment by lefnire** [comment] 2013-11-26 22:26
getting wrong colors in party header now: ![screen](http://gyazo.com/9ede14fa5b9bcb2afddb95c14881b1eb.png) (should be some yellow, red, green, blue, etc in there)

**Comment by snicker** [comment] 2013-11-26 22:43
I'm not sure why I thought this was working... Angular does not evaluate the class name, only the conditional of whether or not to apply it. The article is describing a different situation. We need to address the problem I pointed out before, the data loads after the view is displayed.

**Comment by snicker** [comment] 2013-11-26 22:58
fixed in https://github.com/HabitRPG/habitrpg/commit/86f62ac2b2c24823e8c967dbaecdfcb1c09a7d0c

please see comments on that commit for why this works

**Closed as completed** 2013-11-26 23:02 UTC
