### ISSUE TITLE
Firefox "clear cookies at end of session" setting breaks opening new tabs

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#10910] opened 2018-12-13 20:36 UTC
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)
### General Info
  * UUID: 23d6c69b-b1f6-4f02-940c-c5417ef3e1a1
  * Browser: Firefox
  * OS: (unknown)

### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)

Per user Yayef in Report a Bug:
>if I open a new tab in Habitica (for example I'm in the tasks window and I center-click on Party to open it in a new tab), I have to reconnect to view the content of the new page. In Google Chrome it's working fine. 
>
>The main Habitica tab is not pinned.
>
>I don't use containers nor any extension. Firefox is configured to clear cookies when I close my session (like in Google Chrome).
>
>After clearing the data, the problem remains.
>
>Another information: this happens on the two computers I use daily, at home and at work, that's why I thought it was a global problem with Firefox.

So there's something going on with session handling in Firefox x Habitica specifically, though it's hard to tell from here if the problem is on Firefox's end or ours.

**Comment by paglias** [comment] 2018-12-14 10:58
I can't find that exact setting in Firefox, can you ask Yayef about the precise steps to enable it and reproduce the problem?

**Comment by paglias** [comment] 2018-12-14 11:02
Okay, found it, the setting is the one to set cookie expiration to when firefox is closed instead of the expiration date sent from the server. Looks like that deletes the localStorage data everytime a new tab is opened which then trigger logging in again. Not sure we can do much about it

**Comment by Yayef** [comment] 2018-12-15 10:36
I'm here. :) 

FYI, Habitica is the only website acting like this. Every other one I use allows me to open as many tabs as I want without asking me to log in again.

It's not a very big deal, when I need to open multiple tabs on Habitica, I switch to Google Chrome... or I log in every new tab.

But as I ran into this issue, I wanted to share it. But it sounds like no one wants to clear its session after exiting a browser in this world. ;)

**Comment by paglias** [comment] 2018-12-16 11:24
@Yayef I'm sorry this is happening but it looks like that settings on Firefox prevents local storage (a system to save data on your browser) from being saved correctly and since we rely on it to save your login status when you open a new tab it doesn't have the info needed to log you in. I'm not sure why this is the behavior of that setting but it's possible it's a bug in Firefox

**Closed as completed** 2019-03-21 18:24 UTC
Labels: priority: minor, help wanted, section: Login/Statics
