### ISSUE TITLE
Discussion: darker patterns in game design

### ISSUE THREAD

**Issue by asktree** [HabitRPG/habitica#12610] opened 2020-09-24 21:25 UTC
Hi all.

Basically, there is a super long list of things MMOs and mobile games do to be addictive and/or feel more rewarding. I was particularly shocked at how good Gacha games are at this stuff. Habitica does very little of these things.

To me, the ideal version of Habitica would implement a lot of these patterns, even ones that are kinda dark. I realize there's a need to balance this against making Habitica itself too distracting. One way to address this is by making these features configurable, since there's no reason all players need to be playing with the same set of rules. 

Here are some patterns other games do:

-  **Progression never stops**: your dude can always be stronger or cooler. This is often achieved with randomly generated modifiers for gear, making it where you'll never acquire the theoretically optimal gearset. 
   - Habitica on the other hand gives players endgame headgear game very early on (Nameless Helm). This should probably be changed, it just means I have no incentive to buy hats. This is even more true if you're playing with a big party.
   - Randomly generated gear is also just fun, it means the game can never just be "solved" and you constantly have to evaluate new tradeoffs. May be considered too distracting though.
   - Habitica could also achieve this by giving some incentive to reach level 100 and use an Orb, for example giving you a random piece of special permanent gear when you do so.
- **Vanishingly rare drops / jackpots**. Could be achieved via the enchanted armoire and giving quests randomized loot. related to above but I just want to point out that it can be used for cosmetics not just power-increasing things.
  - Relatedly Hearthstone increases your odds of getting a Legendary card the longer you go without getting one, other gambling games similarly have non-independent odds designed to trigger repeat gambling. 
- **Complicated crafting systems**. A lot of games have a bunch of wacky different resources you can use to combine and craft things. Gacha games are probably best in class at this but even League of Legends has a good example in its crafting system. "Once I got a 3rd Golden Shard I disenchanted them into Dust which I used to empower my dragon egg so that it could fuse with the other empowered dragon egg to give me a Hyper Dragon Egg". Another common theme here is exponential requirements- 3 Foos make a Bar, 3 Bars make a Bar+, and so on.
   - These may be too distracting (players spend time understanding the wacky crafting system and optimizing how they craft) but I definitely think it's no accident that they are commonplace. 

I'm not an expert and I don't play a lot of games with dark patterns. I'm sure there are a lot of other things that could be applied. I anticipate some arguments against dark patterns. People do struggle with gaming addiction and there should definitely always be a way to play Habitica without triggering that. That's why this is a discussion ticket and not a feature req.

**Comment by Alys** [comment] 2020-09-25 04:58
Interesting ideas. We use GitHub primarily for bug reports so you may like to submit this through Help > Request a Feature (if you'd like more details about reporting bugs and suggestions, see the template comments in an empty new issue here). I'm going to close this since it's not a bug but it will remain available in GitHub so if you want to include a link to this in your feature suggestion, the link will keep working.

**Closed as completed by Alys** 2020-09-25 04:58 UTC
