### ISSUE TITLE
The same few to dos reappear - will not complete or delete

### ISSUE THREAD

**Issue by Lael-** [HabitRPG/habitica#3803] opened 2014-07-29 13:29 UTC
I noticed that to dos reappear (normal to dos not challenge) and I read that someone reporting a previous problem like this had the suggestion that it was about not properly connecting to the servers - however for me it is always the same few to dos that are doing this, all the rest delete fine. The 6 to dos in question were created a while ago approx. 3-4 weeks ago, and left to go orange. When I tick them off they appear again as yellow but in the same place next to orange and red to dos, and so they stand out on my list and I've noticed that they don't seem to go away. When I tick them off I seem to receive gold each time even though they reappear.  I'll keep trying to delete them and I'll see if it eventually works. Could this bug be due to my exceptionally long list of not completed to dos…? :worried:

**Comment by Lael-** [comment] 2014-07-29 14:54
I keep receiving gold when I try to click complete on each "stuck" to do and the gold continues increasing the second, third etc. time that I tick them off. My gold has kept increasing and staying that way since I noticed this was happening and I started testing it. (my XP increases too and I even went up a level).

After trying a few things I think a "fix" might be if I click to complete them (sometimes they reappear immediately so I click to complete them again)- and then from the completed list I quickly delete the grey versions of each to do - the deleted ones seem to have disappeared for now, whilst some others still appear to travel from the grey completed list back in to my incomplete to dos. I am not sure if these are the only to dos behaving in this way or why it has happened.

I've actually realised that one of my remaining "stuck" to dos is currently appearing on both the grey completed list and yellow to do list at the same time.

**Comment by Alys** [comment] 2014-07-29 22:54
I recommend going to your list of completed to-dos and clicking the "Delete Complete" button. That MIGHT help. Note the advice about exporting first if you want to keep a record of your data. After you've done that:

I don't think you've described what happens when you try to delete one of these to-dos from your list of UNcompleted to-dos. I.e., click the trashcan icon next to one of the problem to-dos and tell us exactly what happens.

Please also paste your User Id into this issue as plain text (not a screenshot). See [API Options](http://habitrpg.wikia.com/wiki/API_Options) for how to find your User Id.

Do you have any third-party applications that work with your HabitRPG account? For example, have you written or installed any scripts/apps/programs that create to-do items?

**Comment by deilann** [comment] 2014-07-30 00:01
@Lael- That wasn't actually a ticket about To-Dos reappearing -- it was a ticket about how challenge To-Dos aren't cleared when you clear completed. When you commented, I realized that ticket was never closed, and it should have been. There's really no reason to be snarky to me for doing housekeeping and affirming to you that your bug is a different one entirely...

**Comment by Lael-** [comment] 2014-07-30 11:23
Hi sorry @deilann  - I think it was just a misunderstanding, since embarrassingly, as well as not quite understanding these tickets,  I also didn't understand what you meant by the phrase "expected and desired behaviour" referring to the game code and how to dos were behaving… I actually thought you meant I'd done something wrong myself! :/  Oh well eventually I worked it out and deleted my comment replying to you in response to what I'd incorrectly thought you meant, sorry about that. Thanks for the work you're doing fixing issues here.

**Comment by deilann** [comment] 2014-07-30 11:31
Lemme explain: so expected behavior means we would expect that to happen
with the code. But sometimes what we expect isn't what we want. So that
would still be an issue. For example, it's expected that you can't wear cat
ears and an eye patch at the same time.

So that's where desired behavior comes in. The challenge to dos not
clearing is desired.

However what you're describing is neither expected (we wouldn't think the
code works this way and it usually doesn't) or desired (one would hope to
be able to get rid of to dos).

In the past, @lefnire has had to go in and delete tasks like these himself.
To do that, he'll need both your user ID which you can find in settings >
API and enough info about the 6 tasks that he cab figure out which ones
they are. If you're not comfortable sharing their title publicly email
admin@habitrpg.com linking this ticket and sharing the task titles.

**Comment by Lael-** [comment] 2014-07-30 11:59
Thanks for clearing that up @deilann
…….
With the "stuck" to dos I tried to delete by pressing the trashcan on the incomplete list (whilst the to do was orange or yellow) and the to do reappeared on the list a while later. Alternatively if I pressed complete they reappeared (I seem to remember that I tried renaming one a while ago and I can't remember how that affected it). It only seemed to happen with these 6 to dos, other ones deleted or completed fine, I've got no idea why.

As you suggested @Alys - I seem to have fixed it by finding them in the grey completed list and using the "Delete Complete" button and for the "stuck" to dos that I did that on, they have now cleared and haven't reappeared again. I had left one to do still behaving in this way to see if there was any reason for it that I could find - when I clicked complete it appeared to come back pretty quickly, this time I clicked the trash can and today the last one has disappeared as it should have done, deleting without reappearing yet - so maybe it is fixed?

I'm not using any third-party apps etc.
Do I still need to send my user ID or does it count as fixed if I've managed to delete the to dos myself now?

**Comment by deilann** [comment] 2014-07-30 12:03
If they reappear again, then we'll need that info. Sharing your UUID isn't
a big deal by the way -- it's publicly visible in your Habit profile. The
reason we'd need it is not because of any third party stuff but because
that's how we identify your account. Without it, Tyler wouldn't be able to
find your account to delete the tasks from the database.

However you should never publicly share your API Token, as it's like a
password.

**Comment by Lael-** [comment] 2014-07-30 13:10
Okay, I'll keep watching to see if it has stopped now or if any reappear. Thanks.

**Comment by Alys** [comment] 2014-08-02 04:09
@Lael-  I'm closing this to tidy up the list of unresolved issues, but we can always reopen it if it happens again. If it does, paste your UUID and some text from the tasks into this issue.

**Closed as completed by Alys** 2014-08-02 04:09 UTC
