### ISSUE TITLE
Mystic Hourglass Problem

### ISSUE THREAD

**Issue by JustTeaForMe** [HabitRPG/habitica#6133] opened 2015-10-28 19:19 UTC
I have been a member for almost two years now. And a while back I had purchased the 12 month subscription. I cannot recall ever receiving an hourglass for consecutive months except from switching my subscription from monthly to yearly. So I have kept an eye out for hourglasses. 

Maybe I am not understanding the process of how it works, but on the Time Traveler's Page it says, "You'll need a Mystic Hourglass to summon the mysterious Time Travelers! Subscribers earn one Mystic Hourglass for every three months of consecutive subscribing. Come back when you have a Mystic Hourglass, and the Time Travelers will fetch you a rare pet, mount, or Subscriber Item Set from the past... or maybe even the future."

I have a recurring bill of $48 every 12 Months
My account says that I have 19 consecutive months
And that I have 0 Mystic Hourglasses

What do I do now?

Thank you, Emily.

**Comment by Alys** [comment] 2015-10-28 20:35
I'm closing this as a duplicate of https://github.com/HabitRPG/habitrpg/issues/6132

**Closed as completed by Alys** 2015-10-28 20:35 UTC
