### ISSUE TITLE
To-Do values keep changing after completion (Wrong task values and colors for  "To-dos Completed" in the Data Display Tool (v7.2))

### ISSUE THREAD

**Issue by Medusil** [HabitRPG/habitica#6470] opened 2016-01-06 15:26 UTC
Completed to-dos in the data-display tool seem to keep dropping in value after the to-do was completed.  
Old tasks that I know were completed as yellow, now have a lower (red) value.  The most recently completed tasks show more accurate values.

UserID
010ee270-e814-40d0-9a85-ba5fcf5e9bc0
Windows 8, Firefox 43.0.3

**Comment by Alys** [comment] 2016-01-06 23:48
The Data Display Tool reads information about your tasks from Habitica's servers, so any value changes happen on the server, not in the DDT.

From a quick look at Habitica's cron code, the value of a To-Do is adjusted at each cron regardless of whether the To-Do is completed or not.

I personally don't think this matters because the value of a To-Do isn't important after it's been completed. In fact, it's probably good that the value does keep changing after completion because if you mistakenly mark a To-Do as completed and then a day or two later realise this and mark it as uncompleted, you would want the value to have changed over that time as if it had never been completed.

I'm going to leave this open for a day for anyone to post opposing viewpoints, but if there are none, I'll close it.

**Comment by crookedneighbor** [comment] 2016-01-07 01:21
I agree with @alys

**Comment by paglias** [comment] 2016-01-07 08:13
I think this behavior is pretty weird. it basically makes impossible to use go back in time and see how you completed some tasks

**Comment by Medusil** [comment] 2016-01-07 09:48
I was also expecting to be able to see how I completed the tasks.  It just didn't seem like intended behavior to me.  It would be nice to get an idea of how my tendency to do short term (yellow) or long-term (red) to-do's was over time.  Habits and dailies can be tracked with the progress tab, it would be nice to track to-do's as a whole in a similar way.
I was expecting to see just that with the "to-do's completed" page in the data-display tool.
Hope it clarifies where I'm coming from.

I also don't know how often other people restore their completed tasks, but for me that only happens immediately when I misclick somthing.  I'd find it odd that someone would want to restore their to-do after multiple days of completing it (or wrongfully completing it).

**Comment by Medusil** [comment] 2016-01-07 09:59
Another thing: Apparently the value of a finished to-do is modified upon  completion as well.  Immediately after completing a red to-do (with a checklist), the value listed is now green because of the 'damage'/value increase that happens when you complete something.

**Comment by Alys** [comment] 2016-01-07 10:39
@Medusil From your most recent comment: That is definitely working as intended - marking a task as complete (or clicking + for a Habit) has the same behaviour across all task types, and one aspect of that behaviour is that the value changes.

It sounds like you're wanting a permanent record of what the value was just before you completed a To-Do. I think this would be best handled as a feature request, because the current behaviour doesn't really count as a bug. Also, it's not something we could change in the short term because some large-scale refactoring is being done on parts of the code at the moment (including the task scoring section which modifies task values) and so we're avoiding making other changes to that code until the refactoring is finished.

You might like to write up the behaviour you'd like to see, in as much detail as you wish, and then go to Help -> Request a Feature to suggest it. I'd recommend including a link to this issue so that we can keep a record of this conversation. We could then consider your request along with other suggestions for task behaviour, and try to come up with a plan that satisfies multiple requests.

Regarding restoring completed To-Dos: I agree that it's rare that you'd want to untick a To-Do a day or more after you ticked it, but it's not impossible. I've done that occasionally in the past when it took me some time to realise I'd completed the wrong To-Do. In the cases when it was necessary, we would want the value of the unticked To-Do to be correct, as if it had never been ticked off inappropriately. So, if we did modify the current code to freeze the values of To-Dos after they were completed, we'd need extra code to apply the appropriate value change after unticking (which wouldn't be especially difficult, but it is one extra thing to consider).

**Comment by Medusil** [comment] 2016-01-07 10:44
Okay, thanks!

**Closed as completed** 2016-01-09 08:32 UTC

**Comment by paglias** [comment] 2016-01-10 13:56
@Alys when implementing cron in api-v3 I made the decision to not process at all completed todos, given this discussion above, should I have completed todos processed, right?

**Comment by Alys** [comment] 2016-01-10 14:27
@paglias No, that's fine! I saw your issue about changing the To-Do's value after unticking (https://github.com/HabitRPG/habitrpg/issues/6488), which is the important thing.
