### ISSUE TITLE
Quests not starting when all party members accept

### ISSUE THREAD

**Issue by peweisberg-fadv** [HabitRPG/habitica#5240] opened 2015-05-19 16:24 UTC
My party's last two quests have not started automatically when all party members accepted.  The latest one is particularly annoying, as the quest owner hasn't logged in to start it manually and it's been sitting there with everyone having accepted for a couple days.

Group ID: 354a79d3-0550-41b3-a901-d678ab9f88b4

My user ID: 912b1db1-3c48-45a2-9256-b57419e88b24

**Comment by Alys** [comment] 2015-05-19 23:20
Duplicate of https://github.com/HabitRPG/habitrpg/issues/3968

The problem is that you had a person listed in the members list who has deleted their HabitRPG account. I have removed them so that this won't happen again.

I'm sorry this most recent quest was annoying for you, but if you report problems as soon as they occur we can fix them before they get annoying.

**Closed as completed by Alys** 2015-05-19 23:20 UTC

**Comment by peweisberg-fadv** [comment] 2015-05-20 00:04
Thank you
