### ISSUE TITLE
Changing value of rewards deducted the amount from my gold and then killed me.

### ISSUE THREAD

**Issue by cleave29** [HabitRPG/habitica#388] opened 2013-02-13 19:49 UTC
I changed the value of a reward and it deducted the amount from my gold each time I pressed the cost down button.  Then I died.

**Comment by Pandoro** [comment] 2013-02-13 19:54
So you clicked the number specifying the number you put in there?

**Comment by cleave29** [comment] 2013-02-13 21:44
Not the cost button, but the "decrease" button for the cost in the edit
menu.
(I almost killed myself pressing the cost button and then I killed myself
trying to change the cost with the down arrow.)
Matt

**Comment by Pandoro** [comment] 2013-02-13 21:57
Hmmm I must be honest here, I cannot follow you :x I do not have a "decrease button". Could you maybe post a screenshot of the button you mean?

Otherwise ... @SlappyBag ? You know what is meant here :x ?

**Comment by cleave29** [comment] 2013-02-13 22:03
Sorry I'm not making myself clear.  By "decrease button", I mean the down
arrow near "Price" in the edit screen of the reward.
I'll attach a screen shot.  Did it go through?
Thanks for responding,
Matt

**Comment by StanLindsey** [comment] 2013-02-13 22:12
Yeah I didn't know what you meant at first but there is a number increment input box when you edit/create a reward. I couldn't replicate the bug you've been having though.

**Comment by Pandoro** [comment] 2013-02-13 22:14
![Screenshot from 2013-02-13 23:12:15](https://f.cloud.github.com/assets/1872333/154835/afc058ee-762a-11e2-90f7-f05b42f9dcf5.png)

This is all I can see when I edit a reward :o

**Comment by cleave29** [comment] 2013-02-13 22:15
Huh.
OK, well, thanks for looking at it.
If it happens again, I'll let you know.
Matt

**Comment by lefnire** [comment] 2013-02-13 22:18
It's a browser thing. Safari handles `<input type="number">` [like this](http://gyazo.com/86df625faa235d74fe758dc94c407759.png?1360793866), for example. So you're saying you clicked that down-arrow and lost HP? I can't replicate

**Comment by cleave29** [comment] 2013-02-13 22:52
Just out of curiosity, what if you spend more gold than you have thus losing hit points, then press the down arrow?

**Comment by Pandoro** [comment] 2013-02-18 18:18
@cleave29  has this occurred again? Apparently nobody could recreate the bug. Which does not mean it wasn't there, but it will make it hard to find if we don't know what it looks like :x

**Comment by cleave29** [comment] 2013-02-18 20:01
No, luckily, it hasn't.  
I've been really careful about using rewards since then, so I don't really want to go looking for it.  
Have you tried the suggestion above: "Just out of curiosity, what if you spend more gold than you have thus losing hit points, then press the down arrow?"  If so, then I guess it's gone.
Thanks for looking into it.

**Comment by Pandoro** [comment] 2013-02-18 20:05
Well I would try it on the test server, but as I mentioned, I was never
able to find the down button in my browser. But from what I understand from
@lefnire s comment, he wasn't able to reproduce it.

Maybe you can test this on the test server? http://habitrpg.herokuapp.com/
There you can play around a little, you don't even need to log in for that.
You should be able to buy some rewards so that they start eating away at
your habits. In your browser you should see the down button and try to
press it when it comes to this. I guess if you cannot reproduce it there,
it might have been fixed in one of the recent updates. Otherwise we have a
starting point to debug it :)

**Comment by cleave29** [comment] 2013-02-19 03:31
I can't replicate it on the test server, but, er...  There are several of my bugs that do not happen on the test server.  For example, I can - Oh, wait, y'all fixed the drag function.  Sweet...
For example, I tried to replicate the "having-my-health-restored-and-gaining-20g-with-a-Habit-after-using-an-undeserved-reward" on the test server and it didn't work.  But it happened to me on my profile this afternoon.  So, is there a difference between the test server and my profile?

**Comment by Pandoro** [comment] 2013-02-19 10:19
Hmm I must admit I am not a 100% sure which version the test server is
running right now. But knowing that it does not occur on there might help
finding out the cause of this problem.

What do you mean by the other bug you mentioned :x ?

**Comment by lefnire** [comment] 2013-02-19 14:37
Test server is old, I'll take it down. We haven't set up a CI deploy of
develop yet

**Comment by cleave29** [comment] 2013-02-19 15:48
@Pandoro I mean #417

**Comment by Pandoro** [comment] 2013-02-19 16:20
@cleave29  sorry for the ... bad help. I wasn't aware the test server was so old :( But @lefnire this might still be interesting? That both this and #417 did not occur on that version of the code? Do you know which version was running there?

**Comment by cleave29** [comment] 2013-02-19 16:44
@Pandoro No sweat

**Comment by lefnire** [comment] 2013-02-20 02:50
ok, #417 is closed now. how we doing on this ticket?

**Comment by horusofoz** [comment] 2013-02-26 12:39
Closing as no response from user after a week

**Closed as completed by horusofoz** 2013-02-26 12:39 UTC
Labels: priority: important

**Comment by cleave29** [comment] 2013-02-26 16:25
Oh, sorry, the down arrow doesn't seem to damage me anymore, so I think we're good.  Thanks!  :)
