### ISSUE TITLE
Quest Infobox Cut Off

### ISSUE THREAD

**Issue by tricksyfox** [HabitRPG/habitica#7932] opened 2016-08-25 14:58 UTC
General Info
- UUID: 90e5c4f2-d5d9-4472-ab2c-19041ee2218d
- Browser: Chrome
- OS: OS X Yosemite 10.10.5
### Description

[//](#): # When hovering over Part 2 of the dish disaster quest scroll, the infobox forms above the top of the site page and gets cut off. Not major, but worth noting.

![screen shot 2016-08-25 at 9 27 45 am](https://cloud.githubusercontent.com/assets/20846625/17974114/c23ccc0c-6ab2-11e6-8773-9c6460dfb039.png)

**Comment by Alys** [comment] 2016-08-25 15:05
Definitely something for us to consider in the upcoming website improvement project, if not sooner. In the project, we should test all hover features on all items that occur at the top, bottom, far left, and far right of the respective areas.

**Comment by khipkin** [comment] 2016-08-25 15:14
Possible duplicate of #7799.

**Comment by Alys** [comment] 2016-08-25 15:38
Ugh, thanks. Sorry @tricksyfox ! :( My fault.

**Closed as completed by Alys** 2016-08-25 15:38 UTC
