### ISSUE TITLE
New tags request a reload to be used in existing tasks

### ISSUE THREAD

**Issue by Eusebius** [HabitRPG/habitica#907] opened 2013-05-07 10:22 UTC
When a new tag is created, the page must be reloaded before it can be assigned to an existing task: when editing, only the tags already present at the latest page load are displayed. Creating a new task shows all tags properly, including the new ones.

I would not categorize this as a bug, but it would be nice if the task editor could fetch the new tags. Note that if a tag is deleted, it is not showed anymore in the task editor (no need for reload here).

**Comment by lefnire** [comment] 2013-05-07 11:59
This is a bug, and a very very complicated one caused by refLists. @toebu
and I are aware of this, it's actually why there's a √ button to the left
confirm or "save" your tags changes - it simply refreshes the page and
nothing more. Nothing we can do about this in the current incarnation, this
will be fixed when I migrate to arrays instead of refLists (which is almost
done).

**Comment by paglias** [comment] 2013-09-09 16:05
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!

**Closed as completed by paglias** 2013-09-09 16:05 UTC
