### ISSUE TITLE
Wallet toolbar spills onto second line at certain widths

### ISSUE THREAD

**Issue by probaton** [HabitRPG/habitica#8240] opened 2016-11-28 17:36 UTC
[//]: # (Fill out relevant information - UUID is found in Settings -> API)
General Info
  * UUID: 6d7d6651-604d-4e7c-adff-a040770a6768
  * Browser: Chrome, Firefox, IE11
  * OS: Windows 10

### Description
[//]: # (Describe bug in detail here. Include pictures if helpful.)
When opening the Habitica main page at a certain width, the the toolbar at the top of the page becomes too crowded, spilling the wallet toolbar onto a second line. This would be odd but fine as long as the rest of the dom moved down to accommodate it. Unfortunately, it does not, which means that the top quarter of my character/party bar is obscured by mostly empty space. 

![responsivebork](https://cloud.githubusercontent.com/assets/13566991/20677806/b0ce413a-b594-11e6-9d06-6d967095e72a.PNG)

The problem solves itself once you decrease the view port width down to below 768 (when @media min-width: 768 lapses) or increase it beyond 1013 (at which point the toolbar becomes wide enough for the wallet to fit). The only problem I have with that is that I always have Habitica docked to half of my screen (Windows key + left arrow), which defaults to a view port width of 958. 

Unfortunately this is where my knowledge of bootstrap fails. The simplest solution seems to be simply moving the content down when the toolbar expands. Though not exactly elegant, I'm totally fine with that. Scrunching up the toolbar content so that the wallet fits or having tablet view kick in at 1013px is also perfectly acceptable to me. I'm ok with a suboptimal toolbar as long as my avatar isn't constantly obscured. 

#### Console Errors
[//]: # (Include any JavaScript console errors here.)

**Comment by khipkin** [comment] 2016-11-28 22:13
Possible duplicate of #8089.

**Comment by crookedneighbor** [comment] 2016-11-28 23:29
It is a duplicate. Also, it's not high priority as we're part way through a redesign of the frontend.

**Closed as completed by crookedneighbor** 2016-11-28 23:29 UTC

**Comment by probaton** [comment] 2016-11-29 06:50
My apologies, I only used the standard search box to search for duplicates, which I only now realize includes the is:open tag. Thanks for getting back to me. 

Incidentally, I don't suppose you have any kind of ETA on the new front-end? I couldn't find anything about it in Habitica news. Not that I'm trying to pressure you into a deadline or anything, but a ballpark would be much appreciated.

**Comment by Alys** [comment] 2016-11-29 06:59
@probaton No worries. :)

There's no ETA yet for the redesign. Any high priority problems with the current design are still being fixed though.

By the way, we have a guild within Habitica now for faster reporting of problems. You can get to it from Help > Report a Bug from the website's menu or Guilds > Report a Bug from the mobile app. When you find a bug, you can start reporting it by putting a brief message there - just enough to explain the problem, optionally with a link to a screenshot from a file sharing or image sharing site if you think that helps. We can usually give rapid replies within the guild and it's rare that an issue needs to be logged in GitHub. If an issue is needed, a moderator would advise you of that.
