### ISSUE TITLE
Overflow sort stage buffered (challenges list)

### ISSUE THREAD

**Issue by arthurvasconcelos** [HabitRPG/habitica#5695] opened 2015-07-30 00:02 UTC
When i try to load the list of challenges i receive this error. I already reload the page but the error persists.

Screen:
![error](http://i.imgur.com/0EyDUKQ.png)

**Comment by crookedneighbor** [comment] 2015-07-30 01:23
This is a duplicate of #4132. Going to close this, but you can track the progress their by clicking the subscribe button. 

Usually this bug happens when you're part of a guild that has a lot of challenges, but it's usually temporary. Reload your browser and try again and see if that makes a difference.

**Closed as completed by crookedneighbor** 2015-07-30 01:23 UTC

**Comment by arthurvasconcelos** [comment] 2015-07-30 14:00
Thank you, I will follow from there! =D
