### ISSUE TITLE
Clicking "Guilds" in header doesn't actually help you get to Guilds

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#12382] opened 2020-07-10 23:02 UTC
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)
### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)

Some dropdowns in the site header have default routing for if you click the main category of the header, rather than a specific item under it. Clicking "Inventory" takes you to Inventory > Items, for example. Clicking "Guilds", however, takes you to the Tavern--and while the Tavern is the top entry in the sub-list, it's not helpful for trying to reach actual Guilds.

Possibly a more intuitive behavior would be to go to Guilds > Discover Guilds upon clicking the word "Guilds". (Guilds > My Guilds would also make sense, but given that for many users it would be empty, defaulting to the master Guilds list is a safer bet.)

**Comment by Tressley** [comment] 2020-07-11 13:36
I think we may want to be sure this is a pattern. Challenges navigates to "My Challenges" from the top-level link, even if your Challenges are empty.

I'd be more inclined to change both Guilds and Challenges top-level links to navigate to their respective discover pages.

**Comment by Alys** [comment] 2020-07-12 09:52
This probably isn't something to consider now since the issue is suggestion-discussion but I'm writing it now so I don't forget later if it becomes help wanted. :)

If / when the change to the Guilds menu goes live, can we consider mentioning it in a Bailey? I know it's a small change from a technical perspective but a Bailley would help to spread the word that it's intentional, hopefully avoid "bug" reports, and would help newer users realise that the "Guild" they'd previously been visiting can be accessed at Guilds > Tavern Chat.

Also I'm marking this as "notify helpers" so that we remember to notify the Socialites and Wiki editors if there isn't a Bailey, and because we'll want to get wiki edits planned in advance.

If it goes live, I suspect we may see an increase in general chatter in the Help guild because it will be the first one on the list that new users see when they click on the top-level "Guilds" menu item. We keep a firm (but gentle) control over "hi" posts and non-Habitica questions in that Guild so that it stays solidly on topic, and that may become harder. If it does turn out that that becomes a problem, maybe we could put a link to the Tavern at the top of the list of public Guilds? Or add a note to say that a general chat space for any topic can be found at "Guilds > Tavern Chat"?

**Closed as completed** 2024-05-13 15:51 UTC
Labels: status: issue: suggestion-discussion, priority: minor, section: Navigation/Header, section: Guilds
