### ISSUE TITLE
Can't buy Axe

### ISSUE THREAD

**Issue by DiegoGarcia88** [HabitRPG/habitica#1337] opened 2013-08-16 12:55 UTC
I can't buy an axe even though i have 30 gold coins. It shows a "Not enough GP" error message
![capture](https://f.cloud.github.com/assets/5244708/975270/1f0cf77e-0673-11e3-9b94-5266df2819d3.PNG)

**Comment by lefnire** [comment] 2013-08-16 14:14
dupe of #1330

**Closed as completed by lefnire** 2013-08-16 14:14 UTC
