### ISSUE TITLE
Error message when using Burst of Flames and it results in a level

### ISSUE THREAD

**Issue by Atramagus** [HabitRPG/habitica#5096] opened 2015-04-27 12:47 UTC
Hi!

So, I used Burst of Flames this morning, which leveled me up but provided the following error:

Please reload, "Error Cannot set property 'drop' of undefined" If the error persists, please report it at Help > Report a Bug. If you're familiar with your browser's console, please include any error messages.

I reloaded the window, which deleveled me and gave me several mana back. I tried it multiple times, each time gave me the same error.

I checked off a few tasks to level me, then used the spell and did not receive the error, so it appears to only happen when leveling by using Burst of Flames.

I hope this helps!

-Ben

**Comment by crookedneighbor** [comment] 2015-04-27 12:56
What level are you on currently? What's your UUID (found in Settings > API)?

This is probably a duplicate of #4986, where if you use a skill to gain a level when on that level you would receive a quest scroll drop, it prevents syncing. 

I'm going to close this issue, but you can track the progress of the bug by clicking subscribe on the issue page I posted above. If this isn't a duplicate after all, and something else is going on, feel free to comment here and/or re-open the issue.

**Closed as completed by crookedneighbor** 2015-04-27 12:56 UTC

**Comment by Atramagus** [comment] 2015-04-27 14:28
Nope, that's the same issue; I just wasn't searching for the appropriate text when searching for it before posting!

Thanks ^_^
