### ISSUE TITLE
Experience Bug

### ISSUE THREAD

**Issue by LuisCoder** [HabitRPG/habitica#2339] opened 2014-01-10 03:08 UTC
This is a small bug. It Happens by mistake when i check a TODO and then i uncheck from the completed list of TODO's. Take a look at the experience value in the image.
![bug](https://f.cloud.github.com/assets/3952208/1884504/3135a51a-79a3-11e3-8696-133242245955.png)

**Comment by snicker** [comment] 2014-01-10 15:00
duplicate of #964

**Closed as completed by snicker** 2014-01-10 15:00 UTC
Labels: priority: minor
