### ISSUE TITLE
null tag entry causes tag functions to fail and tasks to be hidden

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#10688] opened 2018-09-16 06:11 UTC
EDIT by Alys 2019-11-26: see https://github.com/HabitRPG/habitica/issues/10688#issuecomment-558213190 for the suggested fix.
It's important to state in this issue that you want to work on it before you start because as @paglias noted, he'll fix it if no one takes it up.

---

It's possible for an entry in a player's `tags` array to be `null` (i.e., not a normal object but just the value `null`). This causes the tag selection screen on the website to not open and hides tasks that are tagged.

There's two possible fixes (both could be done):
1. Work out what's causing `null` to appear and make that stop.
2. Allow all of the website's tag functions to work even if one of the tag array elements is `null` (just ignore that element). This would be useful if we can't work out what's causing `null` or if we can fix that but in case a new cause appears in future.

However before working on either of those fixes, look to see if any of the staff have commented here about the desired fix!

Note that this also affects tag features on at least one of the mobile apps, so if fix 1 can't be done, we'd want to adjust the app(s) to prevent a null tag from causing problems, as well as adjusting the website.

This was reported by Tania Liao (4e10ce61-16c2-498d-9895-bfea8eabadf6). Below is the `tags` array with the tag names removed for privacy. I've also copied the conversation about it from the Report a Bug guild to provide examples of what players are likely to report if this happens again. I've deleted the null entry from Tania's tags to fix the immediate problem.

I'm marking this as a minor bug since this is the first report of it that shanaqui and I have seen and so I think it's likely to be very rare, although it's extremely damaging to a player's experience when it does happen!

```
{
    "_id": "4e10ce61-16c2-498d-9895-bfea8eabadf6",
    "tags": [
        {
            "name": "redacted",
            "challenge": "true",
            "id": "bb13b211-977c-488c-b5ff-c5cca00a5f83"
        },
        {
            "name": "redacted",
            "id": "e5d784e0-671e-4b14-b56a-df0844d9c845"
        },
        {
            "name": "redacted",
            "id": "cef8606f-3ec9-49cf-ba3c-64f90d041ac2"
        },
        {
            "name": "redacted",
            "id": "c63e4498-bf20-462e-bcfe-10e6e05d60a5"
        },
        {
            "name": "redacted",
            "id": "c9d46c06-4119-4afd-9251-85ab08527d9a"
        },
        {
            "name": "redacted",
            "id": "849ef2b1-70f9-40e3-a1e0-3ffb6102cea1"
        },
        {
            "name": "redacted",
            "id": "1fb2a66a-f442-44ed-aad6-adf5b08a5861"
        },
        {
            "name": "redacted",
            "id": "4940344a-945b-457d-aeea-a4f9e6eb5804"
        },
        {
            "name": "redacted",
            "id": "e20a4c1b-f6c7-4e3e-bea5-d1b3fc8fc232"
        },
        {
            "name": "redacted",
            "id": "30b5ba43-e8b7-4de8-b200-19de2bf8228d"
        },
        {
            "name": "redacted",
            "id": "f1942346-895b-40c5-b5be-2480da0fa389"
        },
        {
            "id": "08e96037-a9f0-4c6d-b5d2-4fad9f379162",
            "name": "redacted",
        },
        {
            "id": "0e1fa753-0eee-48bb-8bf6-2d5ac3c8cbea",
            "name": "redacted",
        },
        null,
        {
            "name": "redacted",
        }
    ]
}
```

Tania Liao: _My habits and dailies all disappeared!! So did some of my tags!_

shanaqui: _Wow, that's a new one on me. Are you sure you haven't put any search text into the search box or selected a tag? @Sabrecat, maybe you ought to take a look right away?_

Tania Liao: _I couldn't even open the tag option. When I said that the tags disappeared, I was using the mobile app version. I was editing the tags, but after I save the change, I found that some tags remain unedited while some disappeared. When I open the notebook to check by the website, I saw that the habits part and the dailies part was empty. I tried to view my tags, but nothing showed when I click on it. I just checked in on PC today. The website asked me if I had complete the dailies below, but the area my dailies should be shown was empty. I clicked "start my day" directly, but I still caused damage to my party. The habits and dailies were still invisible, and the tags were still unavailable. I also checked out my mobile app, and I found that I could see my habits and dailies there, even after refreshing. But the tags were still wrong. Sorry for not giving the whole information yesterday._

Tania Liao: _By the way, some of my to-dos disappeared on the website, too. Only the tasks without any tags could be seen. The app was doing fine._

SabreCat: _Oh dear, what a muddle. I think what's happened is via some glitch (possibly related to the one that deletes tags? it's very rare, but very annoying), you got a tag selected that no longer existed. Can you try opening the tags list on the Web site, and even if you don't see any checked tags, click "clear all filters"?_

Tania Liao: _Nothing happens when I click on the tags bottom. Nothing happens. Neither a window nor a single thing to klick._

**Comment by Alys** [comment] 2019-05-25 02:35
Another example from User ID f2e09b75-aacd-4723-b61f-ac9ed2934be4, with a null tag array entry and two entries that contained a name but no id. I've replaced all names with ... for privacy.
```
    "tags": [
        null,
        {
            "name": "..."
        },
        {
            "id": "67015535-7343-4de4-946d-036a2d32d5d2",
            "name": "..."
        },
        {
            "name": "..."
        },
        {
            "id": "1d527dfb-9d61-4bdf-93ab-6a19beeee5cb",
            "name": "..."
        },
        {
            "id": "24399f8f-6ca0-4c23-8065-9bbaecd1c90a",
            "name": "..."
        },
        {
            "id": "84327326-fd50-4ecf-b442-634b201cfa67",
            "name": "..."
        },
        {
            "id": "7babd8c6-3ce3-4b4b-ae6f-9cf2313bf31f",
            "name": "..."
        },
        {
            "id": "ac051501-6e1d-4174-b1d0-4736bd830ee5",
            "name": "..."
        },
        {
            "id": "406f3d18-1fd9-43b5-9cfa-deba295a5692",
            "name": "..."
        },
        {
            "id": "a59c5367-4518-47ce-bb93-870df9125807",
            "name": "..."
        },
        {
            "id": "352bf28f-d9f7-4cb0-9f0d-4867f76d631c",
            "name": "..."
        },
        {
            "name": "..."
            "id": "a65fd4f1-2d45-42bd-aeb9-a32fcb079d92"
        }
    ]
```

**Comment by Alys** [comment] 2019-05-29 09:53
Another example reported today:

_"The tags functions seems have some problems._
_apk: When I edit tags(click the filters icon on the main screen),want to delete or add tags, after press the "done" button,it shows the message_
_connection Error: There seems to be a problem with the server.Try again later._
_website: 1.I can't add tags to any task(but I can add tags to task on the mobile phone) 2.When a task has some tags(like "work"),the task is invisble in the website(but is visible in the mobile phone) 3.The tags filter can't work ,no tags can be seen from the filter"_


```
{
    "_id": "8bc38388-348c-46f4-b4ab-11220bf105e8",
    "tags": [
        null,
        {
            "name": "..."
        },
        {
            "id": "565dd145-9e2c-4de5-82fb-986653665207",
            "name": "..."
        },
        {
            "id": "08651571-3c96-4fe7-ad0e-0f1d78ab0f0f",
            "name": "..."
        },
        {
            "id": "e3b63dcf-7940-4e84-99bc-e8bdce745c95",
            "name": "..."
        },
        {
            "id": "5fc44a14-25b0-4b9c-9c3c-ee6590eb3cdf",
            "name": "..."
        },
        {
            "id": "66ad1549-964d-4ebf-a3c0-247b8080d29b",
            "name": "..."
        }
    ]
}
```

**Comment by TomRaaff** [comment] 2019-10-07 18:19
Dear Habitica coders, 
I've stumbled upon exactly the same issue. I think it happened when I was editing Tags on my mobile (android) while on a bad internet connection. At some point, a duplicate tag appeared and I couldn't delete it (maybe triggering the null situation). Right now, I can't see any tagged tasks in the **browser** version. On the mobile version, everything works fine, except for the duplicate tag that I can't remove.
My habitica ID is 644a3312-8c29-46d3-a51a-1fafe6f74597
If you have additional questions, please feel free to ask. I hope you'll be able to fix this soon.

**Comment by paglias** [comment] 2019-10-07 18:36
@TomRaaff sorry about this! It should be fixed now but let me know if it's not. Upping the priority on the issue, we might need to do something similar to what we did with notifications

**Comment by Alys** [comment] 2019-11-25 10:37
Another instance:
```
{
    "_id": "e6969079-e2c9-4e5d-b541-f394063d3aae",
    "tags": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        {
            "name": "[tag name (no id)]"
        },
        {
			[other tags with both name and id]
            ....
        }
    ]
}
```

**Comment by paglias** [comment] 2019-11-25 15:44
This is likely caused by either:

- an error in the update query used for removing/adding/moving tags that uses the wrong index, leaving holes in the array
- a mongoose bug

We had something similar going on with notifications which was fixed with some manual cleanup every time the object is saved and should work here as well. The code can be found here https://github.com/HabitRPG/habitica/blob/develop/website/server/models/userNotification.js#L87 and should be possible to easily apply it in this case as well.

If no one gets to it I'll try to do it after finishing the onboarding guide

**Comment by Alys** [comment] 2019-11-26 05:30
I've removed the needs investigation label and added this to the top post:

EDIT by Alys 2019-11-26: see https://github.com/HabitRPG/habitica/issues/10688#issuecomment-558213190 for the suggested fix.
It's important to state in this issue that you want to work on it before you start because as @paglias noted, he'll fix it if no one takes it up.

**Comment by paglias** [comment] 2020-03-01 21:12
have we seen instances where the `name` was the missing property? So an `id` with no `name`

**Comment by Alys** [comment] 2020-03-01 21:24
I don't recall seeing an id with no name.

**Closed as completed** 2020-03-02 10:03 UTC
Labels: priority: medium, help wanted, section: Task Page
