### ISSUE TITLE
My account is not loading properly... Message: ERROR APLICATION, etc - Not saving/loading properly

### ISSUE THREAD

**Issue by elcacto** [HabitRPG/habitica#5486] opened 2015-06-25 14:41 UTC
Hey, I am playing habitRPG for a month now.

But unusually I can't play it anymore! Whenever I do an action in the menu, or try to post in guild/forum, and the page starts loading or saving my action, it doesn't succed in it and appears "Error"!

I'm loving this "game", so please help me.

I also died because of my party, maybe that's relationed?

Please help me, I can't do any actions, because it doesn't save...

**Comment by hairlessbear** [comment] 2015-06-25 15:01
Sorry you're having this problem; I'm having the same issue. There have been a lot of server issues recently, and they seem to have gotten worse today. I'm not an admin, so I can't give you any more information, but hang in there! The admins usually find a way to fix these issues within a few hours. Hopefully one of them can give you more information soon.

**Comment by acsimmons** [comment] 2015-06-25 16:25
Hate to add a "me too", but I've been noticing the server is a bit iffy over the past few days. Anybody know if the problem is the actual server, of it something went wonky just in HabitRPG?

**Comment by crookedneighbor** [comment] 2015-06-25 16:27
Seems to be something with the way our server (Heroku) is interacting with the app. I'm investigating.

**Comment by crookedneighbor** [comment] 2015-06-26 12:10
We did some work server side. Turns out that there's been a pretty serious memory leak in Node that [manifests itself when using New Relic logging](https://discuss.newrelic.com/t/memory-leaking-only-with-node-js-agent-installed/14448/28). We've disabled New Relic for now and are investigating how to patch Node so we can turn New Relic back on. 

From an end user perspective, you should see no change (except for improved stability \o/ yay!) 

Hopefully all is well now. Going to close this, but if you're still having issues, please re-open.

**Closed as completed by crookedneighbor** 2015-06-26 12:10 UTC
