### ISSUE TITLE
New Party members can't join pending Quests

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#9293] opened 2017-10-27 01:10 UTC
After a new user joins a Party, if there is a pending quest that is still in the invitation state, the new Party member cannot join the pending quest. If they choose Accept, they get an error message: "Your party is already on a quest. Try again when the current quest has ended." If the player joins the party while the quest is still in the invitation stage, they SHOULD get an invitation to the quest. They should not if they join the party after the quest has started.

<img width="521" alt="screen shot 2017-10-26 at 6 06 11 pm" src="https://user-images.githubusercontent.com/3494081/32083564-6ee2586c-ba78-11e7-9bd2-0a1ce626568d.png">

**Comment by qhuynh96** [comment] 2017-10-27 05:10
Hi, has anyone been working on this? If not I am happy to be on it. I am a newbie and would try my best. Btw, can you show me where the Party page and relates located? I tried to find it but could not in the end.

**Comment by lemoness** [comment] 2017-10-27 21:54
@qhuynh96 Thank you so much! Go ahead and work on it. Another dev will be along soon to answer your question.

I've updated the labels on this issue.

**Comment by librarianmage** [comment] 2017-12-13 03:47
Hello @qhuynh96! How are you doing with this? Do you need any assistance?

**Comment by qhuynh96** [comment] 2017-12-14 14:18
Hi @MathWhiz , currently I have not made  progress on this issues as I am still waiting for assistance from the dev. I would like to ask about files related to this issue.

**Comment by TheHollidayInn** [comment] 2017-12-14 15:09
Hey @qhuynh96 !

You can find the quest logic here: https://github.com/HabitRPG/habitica/blob/develop/website/client/components/groups/questSidebarSection.vue

And the party page is part of the group page right now: https://github.com/HabitRPG/habitica/blob/develop/website/client/components/groups/group.vue

**Comment by qhuynh96** [comment] 2017-12-16 03:05
@TheHollidayInn Thank you for your info. I have one more question. The issue states that
> If there is a pending quest that is still in the invitation state, the new Party member cannot join the pending quest.

also
>If the player joins the party while the quest is still in the invitation stage, they SHOULD get an invitation to the quest.

I would assume that a pending quest is a quest that started and is in progress. However, is there any chance that a pending quest is in the invitation stage. Do you have any documents about states of a quest?

**Comment by Alys** [comment] 2017-12-16 05:14
@qhuynh96 A pending quest is a quest that's still in the invitation stage. It stops being pending when all party members have accepted or rejected the quest invitation, or when the quest owner has clicked the quest's "Begin" button.

**Comment by TheHollidayInn** [comment] 2017-12-16 05:49
Documentation of the quest states with respect to the members is something we have been working on in a separate issue :P But here is an overview:
1. User starts quest. Invitations are sent
2. Quest is in invitation/pending staging waiting for all users to response (accept or decline)
    - This is the issue stage when a user is invited to the party after the quest has started
3. Quest can be started or will start automatically when all members respond
4. Quest accumulates progress and completes eventually

So, you might also need to look at https://github.com/HabitRPG/habitica/blob/develop/website/server/controllers/api-v3/quests.js because this might be a server side issue.

**Comment by qhuynh96** [comment] 2017-12-17 04:22
@TheHollidayInn I tried to reproduce the issue and experienced the followings:

1. User A created a party and invites user B to the party
2. User B received the invitation to join the party (need to hit sync button to see the invitation).
3. User A started a quest, user B received the invitation (need to hit sync button)
4. User A invited User C, User C accepted the invitation. The quest details show 1 members accepted and 2 pendings. The invitations came up when I hit the sync button. However, the system throws errors when I hit the accept button. After refreshing the page, user C was able to accept the invitation. 

From what I observed, new users will receive an invitation if there is a pending quest in the party. I also checked the source code and found this 
https://github.com/HabitRPG/habitica/blob/develop/website/server/controllers/api-v3/groups.js#L526

I would like to re-confirm about the issue. Is this what you are looking for?

**Comment by TheHollidayInn** [comment] 2017-12-17 06:00
Sounds correct to me! If user C can accept after a refresh, then it might be a client side  issue.

**Comment by qhuynh96** [comment] 2017-12-18 01:44
@TheHollidayInn 
The issue is probably here
https://github.com/HabitRPG/habitica/blob/develop/website/client/store/actions/quests.js#L11

`store.state.party.members.data` returned null which makes the later chaining invalid. I just wonder what is `store.state.party.members` and what is its usage. It seems that `store.state.party.members.data.length` is the default value for partySize; however, I cannot find statements where `store.state.party.members` initialised or assigned with values.

**Comment by TheHollidayInn** [comment] 2017-12-18 21:52
Hmm, that could cause a problem. I'm not sure it would produce the same message as above. Party members stores the users in your party (which are the users in the header or on the party page). There should be a check there to ensure the members are loaded because you can load the party without the party members.

**Comment by beffymaroo** [comment] 2018-04-12 19:02
@qhuynh96 Are you still working on this issue? Please let us know. Thank you!

**Comment by qhuynh96** [comment] 2018-04-15 11:40
Sorry @beffymaroo! I could not find the fix for this issue

**Comment by beffymaroo** [comment] 2018-04-17 19:58
@qhuynh96 Thank you for responding!

**Comment by Arsnael** [comment] 2018-08-25 11:15
Hi there ! Can I take a look into this one? Seems a lot of investigations has been done. I will try to process all of it first and see if I can find a way to solve your problem, and if I need support I will ask here. Good enough? :)

**Comment by paglias** [comment] 2018-08-25 12:47
Sure @Arsnael !

**Comment by Arsnael** [comment] 2018-08-29 10:31
The all process is explained on the PR :) Feel free to give a feedback if necessary !

**Closed as completed** 2018-09-09 09:56 UTC
Labels: priority: medium, status: issue: in progress, section: Party Page
