### ISSUE TITLE
Store user.tasks as object or independent collection

### ISSUE THREAD

**Issue by lefnire** [HabitRPG/habitica#2301] opened 2014-01-08 05:27 UTC
#### Read about what's [happening here](https://github.com/HabitRPG/habitrpg/issues/2301#issuecomment-34398206)

(VersionError: No matching document found)

[Edit] I'm currently (2/5/15) looking into storing tasks as an independent collection rather than an object under the user

---
#### Tracking possible fix-attempts checklists here
- [x] optimize database (upgrade to replsets, optimize queries)
- [ ] kill workers immediately on crash. Partially complete, but still seems users are getting corrupt workers?
- [x] make batch-update atomic, single-save
- [ ] Change handling of re-sends in `userServices.js` to make sure it doesn't get spammed
- [ ] make sure `user.save()` isn't happening anywhere without a callback (check Challenges, it might be attempting `user.save` in the background 
- [ ] Catch all VersionErrors and retry the operation a few times.
- [ ] Place a lock (in DB) on every array. A process has to acquire and release the lock properly. Failure to acquire the lock results in a HTTP 409 error.
- [ ] Use update instead of save when working on arrays.
- [ ] Remove arrays in favor of objects.
- [ ] Find locations in the code where we are updating positionally but could be smarter about it.
- [ ] Find locations in the code where we know an object is no longer valid and still saving it (or double saving).

---

This one, as we've seen, is caused by non-locking and trying to save or access the same record concurrently. No leads as to which action triggered this though, I'll append leads as they come up

```
VersionError: No matching document found.
    at handleSave (/app/node_modules/mongoose/lib/model.js:126:23)
    at /app/node_modules/mongoose/lib/utils.js:408:16
    at /app/node_modules/mongoose/node_modules/mongodb/lib/mongodb/collection/core.js:637:9
    at Server.Base._callHandler (/app/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/base.js:442:41)
    at /app/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:485:18
    at MongoReply.parseBody (/app/node_modules/mongoose/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
    at null.<anonymous> (/app/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:443:20)
    at EventEmitter.emit (events.js:95:17)
    at null.<anonymous> (/app/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:191:13)
    at EventEmitter.emit (events.js:98:17)
    at Socket.<anonymous> (/app/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js:418:22)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:746:14)
    at Socket.EventEmitter.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:408:10)
    at emitReadable (_stream_readable.js:404:5)
    at readableAddChunk (_stream_readable.js:165:9)
    at Socket.Readable.push (_stream_readable.js:127:10)
    at TCP.onread (net.js:526:21)
 ----------------------------

originalUrl: /api/v2/user/
auth: --- | ---
headers: ---
body: {}
```
##

**Comment by colegleason** [comment] 2014-01-08 05:45
I'm not entirely sure now that locks are the "standard" way of doing this. We should try to remove as many of these errors without them as possible.

However, here is at least one article on how you might implement them: https://blog.codecentric.de/en/2012/10/mongodb-pessimistic-locking/

**Comment by lefnire** [comment] 2014-01-08 05:57
I think there might just be a lot of places where we're accidentally writing / reading concurrently to the same model. A poorly-written async.parallel and such, likely throughout spell-casting, challenges, and quests. Unfortunate that none of the error emails have any clues as to what triggered it, but it might just have to be a "keep our eyes peeled" while working on localhost.

I'm gonna give that article a gander and see if we can use it

**Comment by snicker** [comment] 2014-01-10 00:49
with the way everything is asynchronously written at this time, you might need to add a per-user read/write queue if your hunch is correct. client needs to be async as much as possible, server should really be monitoring r/w on its own per record.

**Comment by colegleason** [comment] 2014-01-10 00:53
Well, the other issue is whether or not we should be writing updates to an
object if the updates were calculated for the wrong version. We may have to
be careful when implementing this.

**Comment by snicker** [comment] 2014-01-10 00:59
Race conditions! weeeeeeeeeee

**Comment by colegleason** [comment] 2014-01-19 22:01
VersionError only has to do with array updates!

http://aaronheckmann.blogspot.com/2012/06/mongoose-v3-part-1-versioning.html?m=1

I'm going to argue we should move away from arrays and just have a position field on subdocuments. Position is generally only used for display anyway, right? May also fix duplication issues with tasks, etc.

**Comment by colegleason** [comment] 2014-01-19 22:10
http://tgriff3.com/post/44230656391/versioning-in-mongoose

**Comment by colegleason** [comment] 2014-01-19 22:11
I wonder if the majority of these errors are people moving habits around in their lists. It would be wonderful if we could narrow down these errors to a specific operation.

**Comment by lefnire** [comment] 2014-01-19 22:38
Tasks used to be an object rather than multiple arrays, we experienced quite a lot of issues with that and migrated _away_ from objects to arrays to solve. I'm wary of moving back unless we're sure we're not going to hit those issues again, I can't remember what they were but there are some tickets floating around with the convos, I'm seeing https://github.com/HabitRPG/habitrpg/issues/634 & https://github.com/HabitRPG/habitrpg/issues/1442 , but there are a few more.

Looking into these articles now

**Comment by colegleason** [comment] 2014-01-20 03:00
Possible fixes:
1. Catch all `VersionErrors` and retry the operation a few times.
2. Place a lock (in DB) on every array. A process has to acquire and release the lock properly. Failure to acquire the lock results in a HTTP 409 error.
3. Use `update` instead of `save` when working on arrays.
4. Remove arrays in favor of objects.
5. Find locations in the code where we are updating positionally but could be smarter about it.
6. Find locations in the code where we know an object is no longer valid and still saving it (or double saving).

**Comment by colegleason** [comment] 2014-01-20 08:21
baed on emails in the past few days:

| URL | Count | Notes |
| --- | --- | --- |
| /api/v2/user/ | 6 | Empty body. |
| /api/v2/user/batch-update | 57 | Many of these have bodies that are arrays of 1-3 empty objects WTF? |
| /api/v1/user/tasks?type=daily | 1 |  |
| /api/v1/user | 4 | one of these had `?garbage={blah}` |

**Comment by lefnire** [comment] 2014-01-22 01:27
> (3) Use update instead of save when working on arrays.

As in run a manual mongo update query (like we're doing with quests) instead of `model.save()`? Might be worth a shot, I'll look into it

> (5) Find locations in the code where we are updating positionally but could be smarter about it.
> (6) Find locations in the code where we know an object is no longer valid and still saving it (or double saving).

these are things we should definitely do. I feel like I learned the double-save lesson half-way through coding this repo, so all code before that lesson is subject to double saves. I mean to audit the repo soon and check for these situations.

Yeah, this ticket seems to be the cause of many other tickets. I notice once I see this email, 5m later I'll get a "duplicate to-do" or "can't delete daily" or "challenge didn't remove item" bug, all which likely point to this. Thanks for all your research on the matter btw @colegleason

**Comment by colegleason** [comment] 2014-01-22 03:13
Yeah , no problem. I'll try to put more time into this later this week. I
just got back at school, so I'm still settling in.

The reason 1. works is that the VersionError is really a Mongoose thing
since it tries to refer to array items by indicies. I believe that using
the Mongo update would mitigate that.

On Tue, Jan 21, 2014 at 7:27 PM, Tyler Renelle notifications@github.comwrote:

> 1. Use update instead of save when working on arrays.
>    
>    As in run a manual mongo update query (like we're doing with quests)
>    instead of model.save()? Might be worth a shot, I'll look into it
> 2. Find locations in the code where we are updating positionally but
>    could be smarter about it.
> 3. Find locations in the code where we know an object is no longer
>    valid and still saving it (or double saving).
>    
>    these are things we should definitely do. I feel like I learned the
>    double-save lesson half-way through coding this repo, so all code before
>    that lesson is subject to double saves. I mean to audit the repo soon and
>    check for these situations.
> 
> Yeah, this ticket seems to be the cause of many other tickets. I notice
> once I see this email, 5m later I'll get a "duplicate to-do" or "can't
> delete daily" or "challenge didn't remove item" bug, all which likely point
> to this. Thanks for all your research on the matter btw @colegleasonhttps://github.com/colegleason
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/HabitRPG/habitrpg/issues/2301#issuecomment-32985118
> .

## 

## Cole Gleason

Student, University of Illinois at Urbana-Champaign
Email: cg@colegleason.com
Website: colegleason.com

**Comment by colegleason** [comment] 2014-01-22 06:34
By the way, if you ever find a good way to reproduce this, let me know. I can't seem to figure it out for the life of me.

It would be awesome if we could get a list of ops performed during the batchUpdate when there is a VersionError/

**Comment by lefnire** [comment] 2014-01-30 22:07
I just added `db.users.ensureIndex({ __v: 1, _id: 1 })`. I don't know if it will make a difference, it definitely _would_ if mongoose does the `db.users.find({_id:...,__v:...})` for handling array update conflicts. A couple reasons I'm not sure it would make a difference: this hasn't been an issue in the past, and we've been on Mongoose 3 for a while (though it could just be our user base is so large now, ~180k); I would presume mongoose ensures that index automatically, since it's pretty arcane knowledge - but who knows!

Anyway, I've got some hunches:
- Ops are definitely being duplicated somehow. Many many issues point to this. I think this VersionError issue is very much related
- I it could actually be that the ops being duplicated, are people just rapid clicking! User errors. I've seen some people say "I clicked something right after backstab & got 503", "I'm rapidly clearing my dailies and get 503", etc. 

Some other thoughts: I think you may be correct on going back to object-based tasks. (habits={}, dailys={}, ...). This will afford us a few things: 
1. unique indexes (since the _id is the key)
2. move away from unique array update-handling (VersionError)
3. especially with challenge-management, we can fetch only the pertinent tasks when and save them back. This will decrease server load.

I'm saying all this, but I'm not sure when (or **if**) we'll be able to do this - it will have major implications, first being mobile will be unusable until people migrate. Let's just keep this in the back of our heads for now

**Comment by lefnire** [comment] 2014-02-05 19:12
@colegleason I'm gonna start tracking "attempted fixes" checklist at the top of this issue

**Comment by lefnire** [comment] 2014-02-07 02:19
Ok, I think we have our answer on this one. [SO post](http://stackoverflow.com/questions/15577848/is-mongoose-not-scalable-with-document-array-editing-and-version-control) asking the same question that's my very fear: I think Mongoose is _not_ scalable for rapid array-based updates. This bug is very likely caused by multiple updates, one after another (think +habit spamming, or even legitimate √ √ √ √ √). This also explains why we started seeing it recently - we've grown a ton in January! You're right cole, I think our solutions here are: 
1. Manual update ops (which I'm wary of, given the exact issue Mongoose is trying to solve with `{_id:1,__v;1}`: changing array indexes). 
2. DB-locking (how do we feel about this? Makes me nervous, maybe naively)
3. Catch-and-retry on VersionError
4. Probably the best bet, **move back to objects**. (cole's primary recommendation, but I'd been resistant to).

---

Now, it turns out, given the above I think this issue is far less dire than we'd thought. Since the error is caught and handled as `function(err,req,res,next)`, it doesn't leave the worker corrupt - it just sends the error to the user, and doesn't perform that op. Additionally, I don't think this impacting anything else - I think all those other tickets in this milestone are completely unrelated. (I need to merge [this stuff](https://github.com/HabitRPG/habitrpg/commit/e7c6674b6ba2863ac31e597670f7941648d76f56) ASAP, otherwise any actions after the error don't go through until user refreshes). The solution on the user's end is to be a bit slower about clicking things. Maybe **wait 1 second between clicks**. 'Course, that's not the end solution - we need to move to objects (or whichever solution we choose), but that's the temp

**Comment by snicker** [comment] 2014-02-07 03:39
What's more scalable: the way things are with DB locking, or using
objects? I know that objects are established as expensive, but if it's
a cost that can be paid with more power whereas the other option is
instability that is approaching a point of failure, the choice seems
pretty clear.

Posted From The Peanut Gallery

**Comment by lefnire** [comment] 2014-02-07 03:46
Right right, objects is the better solution here. The big issues we'll need to peg: 
1. Mobile will be unusable until the update becomes available. We'll need to update 3rd-parties to make the change too
2. We'll have to do some magic for handling positional updates when sorting
3. We no longer benefit from TaskSchema. With arrays, you can say `[Schema]`. But with refList-type objects, you can only use `Schema.Types.Mixed`, sans validation & hooks

**Comment by lefnire** [comment] 2014-02-07 04:28
And I think I know why Cluster exacerbates this issue. You can more rapidly have your requests handled (via rapid interaction), which is a _bad_ thing when they're processed concurrently, due to versioning. (Though I don't know why Dynos don't have the same issue...). Thoughts here: 

We may not need Cluster after all. Turns out, while Node.js is single-threaded for its own process (async doesn't use multiple cores), it's actually "properly" asynchronous when performing IO ops (eg, Mongo calls) - utilizing the system's other cores. Since our app is so IO-heavy, we're very likely using the system to it's fullest even without Cluster. Though NR's not tracking CPU, so there's no telling... 

The downside to not using Cluster is we need to crash corrupt workers, which Cluster + domain-middleware gives us automatically with 0-downtime (theoretically). So we'd need to use nodemon or forever for handling the entire dyno's crashed service. I'm gonna hold off on this and see if we can't get Cluster happy in coming days

**Comment by colegleason** [comment] 2014-02-07 05:13
I never knew it used other cores for IO! I'll have to check that out.

**Comment by colegleason** [comment] 2014-02-07 18:58
@lefnire, what about moving to objects for the task lists but having some
sort of backwards compatibility until people move off mobile? We could use
a _.transform and a _map to switch between the two when going to/from
mobile.

It's obnoxious, but it would let us move the majority of the site over.

On Thu, Feb 6, 2014 at 11:13 PM, Cole colewashere@gmail.com wrote:

> I never knew it used other cores for IO! I'll have to check that out.
> On Feb 6, 2014 10:28 PM, "Tyler Renelle" notifications@github.com wrote:
> 
> > And I think I know why Cluster exacerbates this issue. You can more
> > rapidly have your requests handled (via rapid interaction), which is a
> > _bad_ thing when they're processed concurrently, due to versioning.
> > Thoughts here:
> > 
> > We may not Cluster after all. Turns out, while Node.js is single-threaded
> > for its own process (async doesn't use multiple cores), it's actually
> > "properly" asynchronous when performing IO ops (eg, Mongo calls) -
> > utilizing the system's other cores. Since our app is so IO-heavy, we're
> > very likely using the system to it's fullest even without Cluster. Though
> > NR's not tracking CPU, so there's no telling...
> > 
> > The downside to not using Cluster is we need to crash corrupt workers,
> > which Cluster + domain-middleware gives us automatically with 0-downtime
> > (theoretically). So we'd need to use nodemon or forever for handling the
> > entire dyno's crashed worker. I'm gonna hold off on this and see if we
> > can't get Cluster happy in coming days
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHubhttps://github.com/HabitRPG/habitrpg/issues/2301#issuecomment-34403356
> > .

## 

## Cole Gleason

Student, University of Illinois at Urbana-Champaign
Email: cg@colegleason.com
Website: colegleason.com

**Comment by lefnire** [comment] 2014-02-15 20:01
@colegleason the emails... they've reduced substantially! Immediately after the `tasks of null` challenges bug fix. Maybe `VersionError` is exacerbated by a crashed worker somehow. I'm still seeing some other errors floating around, and then surrounded by versionerrors - I'll start fixing some errors and see where that takes us with this ticket

**Comment by deilann** [comment] 2014-02-15 20:09
I also keep wanting to tell you @lefnire -- the site runs MUCH better for
me. Things load faster and it rarely hangs up on me now, which used to
happen all the time.

**Comment by colegleason** [comment] 2014-02-15 23:51
Hmm, that is odd but great! I wish there was better software for
automatically correlating trends with errors, performance, etc.

On Sat, Feb 15, 2014 at 2:09 PM, deilann notifications@github.com wrote:

> I also keep wanting to tell you @lefnire -- the site runs MUCH better for
> me. Things load faster and it rarely hangs up on me now, which used to
> happen all the time.
> 
> On Sat, Feb 15, 2014 at 12:01 PM, Tyler Renelle <notifications@github.com
> 
> > wrote:
> > 
> > @colegleason https://github.com/colegleason the emails... they've
> > 
> > reduced substantially! Immediately after the tasks of null challenges bug
> > fix. Maybe VersionError is exacerbated by a crashed worker somehow. I'm
> > still seeing some other errors floating around, and then surrounded by
> > versionerrors - I'll start fixing some errors and see where that takes us
> > with this ticket
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHub<
> > https://github.com/HabitRPG/habitrpg/issues/2301#issuecomment-35166169>
> > 
> > .
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/HabitRPG/habitrpg/issues/2301#issuecomment-35166378
> .

## 

## Cole Gleason

Student, University of Illinois at Urbana-Champaign
Email: cg@colegleason.com
Website: colegleason.com

**Comment by BrandonHabitRPG** [comment] 2014-02-28 15:19
Does casting Backstab while clicking the + count as multiple clicks?
I had been very careful to go very slowly when using Backstab, but was still getting the bug.  I switched to casting Backstab in the center of the task and then clicking the + separately and have not had the problem since.

**Comment by lefnire** [comment] 2014-02-28 17:01
Ah! It might indeed be. You shouldn't need to delay interactions longer
than 1s, but that action will likely trigger two httprequests

**Comment by lefnire** [comment] 2014-06-04 18:37
tasks array => object progress: https://github.com/HabitRPG/habitrpg/tree/tasks-obj https://github.com/HabitRPG/habitrpg-shared/tree/tasks-obj

**Comment by lefnire** [comment] 2015-02-04 23:03
Dumping my workflowy, moving to a different approach: 
- challenges
  - update api.mocha tests
- todos => todos, completed, archived
- migration
- return diff / apiv2 (stash)
- later
  - divide task sections in jade 
  - move from shared.wrap to constructor invocation

**Comment by lefnire** [comment] 2015-02-05 20:13
Workflowy Brain-dump regarding "tasks as collection" (I'll cleanup these comments later):
- unique id on parent._id & task._id (task._id doesn't have to be unique)
- performance analyze
  - drop
    "db.setProfilingLevel(0);db.system.profile.drop();db.setProfilingLevel(2)"
  - find
    "db.system.profile.find({ns:{$not:/habitrpg.system..*/}}).sort( { ts : -1 } )"

**Comment by paglias** [comment] 2016-06-01 08:45
Done :)

**Closed as completed by paglias** 2016-06-01 08:45 UTC
