### ISSUE TITLE
Dailies are turning red extremely slow.

### ISSUE THREAD

**Issue by Pandoro** [HabitRPG/habitica#1912] opened 2013-11-25 15:01 UTC
There was a time when I completed a daily pretty much every day (getting up at 8am). It even turned green eventually, however in the past couple of months I haven't completed it a single time, yet it is still blue. I have the weird feeling it is not degrading at all. Is this normal? It is not urgent or anything, but it could break the whole purpose if this is an actual bug. 

Name: Pandoro
UUID: 08056cfd-d6cb-4d4d-91e8-b6a27dc02a79

**Comment by lefnire** [comment] 2013-11-25 16:08
Were you resting in the inn during that time?

**Comment by SabreCat** [comment] 2013-11-29 16:29
I had a Daily I didn't touch for weeks, and was surprised at how long it took to turn red. It does degrade, but it's pretty forgiving about it.

**Comment by deilann** [comment] 2014-02-12 02:49
Sorry, thought this one was intended -- it eventually turns red, just slower than expected.

**Comment by lemoness** [comment] 2015-04-17 22:14
Is this still an issue? I feel like we rarely get complaints, and the original issue was opened a year and a half ago.

**Comment by Alys** [comment] 2015-05-17 21:41
I also have seen hardly any complaints about this so I'm closing it. A long period of being very good at a Daily makes it very blue, and so you're rewarded by a very slow decline back to red (it definitely does decline though).

**Closed as completed by Alys** 2015-05-17 21:41 UTC
