### ISSUE TITLE
Click+drag reorder trigger is too sensitive when trying to complete tasks

### ISSUE THREAD

**Issue by Knifa** [HabitRPG/habitica#1157] opened 2013-06-10 00:29 UTC
I often find that I need to really concentrate on not moving the mouse in order to actually click the plus/minus buttons -- instead I usually end up trigger the drag reordering functionality. My mouse is quite high DPI so it could be adding to this but it seems to trigger on the slightest movement.

My suggestion is maybe to add some sort of deadzone rather than triggering immediately. Only triggering on the task title rather than the buttons would also help.

Using Chrome Beta (28.0.1500.37 beta-m) on Windows 8.

**Comment by traceyourshadows** [comment] 2013-06-10 04:05
I've experienced this sometimes too, although not frequently enough to be that bothered by it. When it happens it always works after a couple more tries. It would be great to have a fix for this, though.

**Comment by octern** [comment] 2013-06-11 16:58
This has happened to me, but usually in situations where the interface is hung up and I'm not able to check off items anyway. I believe I've only seen it happen in Chrome, not Firefox.

**Comment by paglias** [comment] 2013-09-09 17:39
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!

**Comment by gwillen** [comment] 2013-09-18 21:29
I don't think I have permissions to reopen this, but it's still happening on the new site. The problem is that you need to be passing a 'distance' parameter to sortable. (I'm assuming from what I can gather that you're using Angular's sortable, which passes through to JQuery's sortable: here's the option I'm talking about. http://api.jqueryui.com/sortable/#option-distance)

The default is for any mouse movement, even a single pixel, to cause a drag. Turning up distance to more like 5 pixels -- fiddle around until you find a value that feels natural -- will fix this issue.

**Comment by paglias** [comment] 2013-09-19 16:34
@gwillen Reopened. Will give a look to it in some days

**Comment by paglias** [comment] 2013-09-21 14:51
@gwillen I've set it to 5px (https://github.com/lefnire/habitrpg/commit/3fb6f25c42d75e63f9c2b4a28d413cd1ba2ed1c1), let me know what do you think, if it's stil not enough I can tweak it

**Closed as completed by paglias** 2013-09-21 14:51 UTC

**Comment by gwillen** [comment] 2013-09-21 16:40
Thanks @paglias! Is the change pushed to production? It still seems to be dragging at 1px for me in Chrome 29.0.1547.76 on OS X. The javascript file I'm getting is app-1057e01b.js, and it doesn't appear to contain the change. (I searched for 'axis: "y"' in the minified JS and inspected the one match, which looks like the pre-patch source.) I did try shift-refresh and clearing the cache.

**Comment by paglias** [comment] 2013-09-21 16:48
No it's not in production, I don't know when it will be pushed but I think
at last tomorrow.

**Comment by paglias** [comment] 2013-09-22 10:04
@gwillen should be in production but since there are some problems actually (http://blog.habitrpg.com/post/61931364067/woah-whats-with-the-site) you can try beta.habitrpg.com .

**Comment by gwillen** [comment] 2013-09-24 16:25
Verified on beta that it works. Thanks!
