### ISSUE TITLE
Still getting one drop per day on first click?

### ISSUE THREAD

**Issue by baconsaur** [HabitRPG/habitica#1625] opened 2013-10-20 15:34 UTC
I commented on an issue about this a while back, but it was closed after the rewrite because it was supposed to have been fixed. But ever since the drop system was introduced way back when, I've always received exactly one drop per day on my first completed task. This is still the case. I've tried using both Firefox and Chrome, and tried it on multiple computers, and it's completely consistent. And it's just my account, since I tried it on my boyfriend's and he gets his drops randomly. Am I the only one still having this happen?

**Comment by SabreCat** [comment] 2013-10-20 17:03
Does it matter what it is you click? Like, a really blue plus-Habit and a 200-streak Daily act the same?

**Comment by baconsaur** [comment] 2013-10-21 00:23
It makes no difference. I've tried starting off with brand new tasks, 100+ streak dailies, etc.

**Comment by hattieshoe** [comment] 2013-10-21 14:41
I have noticed something similar but only lately (maybe last 2 to 3 weeks) -- only one drop per day and on the first daily or task. I did notice yesterday that it doesn't happen when I click a habit first, just dailies and tasks.

**Comment by hattieshoe** [comment] 2013-10-21 14:43
And there is often another time in the day when I click something and I _think_ I'm going to get a drop -- everything pauses for 5 to 10 seconds just like when I get that first drop -- but then nothing drops. Does that happen for you, baconsaur?

**Comment by Shaners** [comment] 2013-10-21 15:49
This would be a hard one to fix if it's not reproduce-able. Look out for JS errors in console or maybe try remaking the offending task (assuming it is a daily) and restoring the streak to see if there might be something specific to that task. Otherwise you may just have to wait until Tyler has the time to look into your account and see if there is anything strange.

What is your user id?

**Comment by hattieshoe** [comment] 2013-10-21 16:26
User ID is 0b670754-57f5-4704-854f-9a9c92107b9b. It doesn't seem to be linked to one particular task, but I will start tracking it better. I'll also make a new daily right now for "track possible drop bug" and check it off first tomorrow to see if the same thing happens.

**Comment by baconsaur** [comment] 2013-10-21 16:29
hattieshoe I haven't noticed that, but I'll look out for it now that you've mentioned it.

User ID is 3cc82d33-d000-44a7-aac8-9e33c186e625

I'll experiment a bit over the next few days and take notes on what happens so I can give you some more specific information.

**Comment by Shaners** [comment] 2013-10-21 17:03
Thanks, really appreciate the extra effort put in to trying to fix this.

If you are getting a drop every time the first task is checked then there must be something funny happening here: https://github.com/HabitRPG/habitrpg-shared/blob/master/script/algos.coffee#L128 or here https://github.com/HabitRPG/habitrpg-shared/blob/master/script/algos.coffee#L129 or here https://github.com/HabitRPG/habitrpg-shared/blob/master/script/algos.coffee#L35 . So creating a fresh task or playing with the streaks or prioirties <em>should</em> fix it. If that doesn't do anything then it might be related to #1561 i.e. your drops enabled flag is being reset every day and that 1 drop is the drop you are supposed to be getting at level 4. Did you guys noticed any eggs being wiped out?

**Comment by paglias** [comment] 2013-10-21 17:06
@Shaners as a fix for #1561 if they're drops are re-enabled every day previous eggs will not be deleted (https://github.com/HabitRPG/habitrpg/commit/08fd4a865a21be0f8b04078ae11a5c81887ec6be), so they won't notice anything getting deleted.

**Comment by Shaners** [comment] 2013-10-21 17:48
@paglias yep but if they noticed them being deleted before that fix, it could be a good indicator that this one is being caused by a similar resetting issue.

**Comment by baconsaur** [comment] 2013-10-21 18:06
I don't think I've ever had any eggs disappear. But I've had a ton of them for a while now, so if any went missing I'm not entirely sure I'd notice.

**Comment by Shaners** [comment] 2013-10-21 18:15
Well if it happened I think would wipe out all eggs.

-Shane

**Comment by hattieshoe** [comment] 2013-10-21 18:25
I've never had any eggs or potions disappear. Wouldn't have noticed eggs because I've always run an excess of potions and hence hatch any eggs as soon as I get them.

**Comment by hattieshoe** [comment] 2013-10-22 12:13
Tuesday 10/22/13: I clicked first on the new daily I made yesterday for "track possible drop bug" and got a lion cub egg. If the pattern continues, I won't get any more drops today. Other info: I've been using the beta site -- would it make any difference if I tried the main site tomorrow? Also, it occurs to me that I haven't gotten a potion drop for a long time, only eggs. I don't know if that is related to the issue or not. (And I can't be 100 percent sure I haven't gotten any potions while the issue has been happening, but I will be tracking from now on.)

**Comment by djuretic** [comment] 2013-10-22 13:13
I think I have the same problem, I've always felt that I got more drops at the start of the day. So yesterday II started to put attention when I received drops, and I can say that yesterday and today I received eggs on my first daily (blue daily, 40+ days streak), I'm using the main site.
The JS console only shows this:

```
Failed to load resource https://ssl.google-analytics.com/ga.js?_=1382446965353
Failed to load resource https://s7.addthis.com/js/250/addthis_widget.js?_=1382446965354
```

**Comment by baconsaur** [comment] 2013-10-22 14:32
Last night I deleted and remade all of my dailies and restored the streaks, and clicking on one first this morning immediately dropped a potion. I'll try something else tomorrow.

I've also been using the beta site exclusively, if that makes any difference,

**Comment by paglias** [comment] 2013-10-22 18:15
@baconsaur thanks for the help troubleshooting this bug, could you try tomorrow witha new task with the streak at 0 to see if it happens anyway?

Also do you have long streaks? How many days?

**Comment by paglias** [comment] 2013-10-22 18:33
Just made some testing and found out that with a task with priority "Easy" and a 33 days streak I always, and I tried over 30 times, get a drop.

I could replicate this only with dailies and is due to how the chance of getting a drop is calculated:
- We have a `delta` absolute number (don't know exactly how it is calculated but it's not very important)
- This `delta` is moltiplied for the `priority` of the task but also this isn't very important
- The streak is added to the chance and at lest in my tests consisted of most of the change points
- A random number (from 0 to 1) is generated and if it's minor than the `chance` moltiplied by 0.05 an item is dropped.

So considering `delta` to be always more than 0 (always?) with a streak of 20 or more the `chance` will always be >= 1 and so causing a drop.

Also the lastDrop number isn't resetted every day so for example I have a `lastDrop.count` of 72, making it impossible to get a second drop in a single day.

**Comment by Shaners** [comment] 2013-10-22 19:15
Doesn't this area make it so streak modifiers can max out? https://github.com/HabitRPG/habitrpg-shared/blob/master/script/algos.coffee#L103
`else if currentValue > 21.27 then currentValue = 21.27`
`delta = Math.pow(0.9747, currentValue)`

**Comment by paglias** [comment] 2013-10-22 19:17
No, the strek bonus, regarding drops, is calculated here https://github.com/HabitRPG/habitrpg-shared/blob/master/script/algos.coffee#L127-L129, it's different from the delta

**Comment by Shaners** [comment] 2013-10-22 19:30
Is the Delta it is grabbing here https://github.com/HabitRPG/habitrpg-shared/blob/master/script/algos.coffee#L115 undefined then? Then we calculate the abs of undefined... `chanceMultiplier = Math.abs(delta)`

I also don't really get why we zero out streak then do this `chanceMultiplier += streak`

**Comment by paglias** [comment] 2013-10-22 19:35
Why undefined? It's passed to `randomDrop()` from `score()` which calculates it using this function https://github.com/HabitRPG/habitrpg-shared/blob/master/script/algos.coffee#L208-L217

About the algorithm probably a discussion on how much value should be given to streaks will be necessary, for the lastDrop count I'll see to fix it now

**Comment by hattieshoe** [comment] 2013-10-22 19:48
It sounds like a high streak value may guarantee a drop-on-first-click (if I'm understanding correctly) but today I clicked one first with a streak of 0 and still got a drop. baconsaur, I'm curious too whether the same thing will happen to you if tomorrow you first click something with a streak of 0. For me it doesn't seem to matter whether I click on one with a high streak or no streak at all, or a new one vs. one I've had for a while.

For tomorrow I thought I'd try clicking a to-do first instead of a daily and see if I get a drop that way, but is there something more enlightening I should try instead?

**Comment by paglias** [comment] 2013-10-22 19:53
@hattieshoe yes, checking if this happens only with dailies or also with habits would be very useful, I could replicate it only with dailies.

It may have been a fortuity getting the drop with a 0 streak daily....

I sent a pull request to fix the lastDrop's count so you can get two drops in a day https://github.com/HabitRPG/habitrpg-shared/pull/30

**Comment by hattieshoe** [comment] 2013-10-22 20:07
Okay, tomorrow I'll (1) click a yellow to-do; if no drop then (2) click a yellow habit; if no drop then (3) click a 0 streak daily. I'll let you know what happens. Should it make any difference whether I use the beta or main site?

**Comment by paglias** [comment] 2013-10-22 20:24
Fantastic! No difference main or beta

**Comment by Shaners** [comment] 2013-10-22 21:39
Ah I think I get it now. `user.items.lastDrop.date` gets updated on the first drop but `user.items.lastDrop.count` never resets preventing a second drop from ever happening. I wonder if anyone has been getting 2 drops in a day and if so why would .count be reset for some but not others.

**Comment by hattieshoe** [comment] 2013-10-23 12:27
Wednesday 10/23/13
1. Clicked yellow to-do: there was a short pause, but no drop.
2. Clicked yellow habit: No drop, no pause.
3. Clicked zero streak daily (one I made yesterday): No drop this time!
4. Clicked daily with streak of 8: Got an egg.

No drops all day yesterday after the first one.

Today's sequence seems to bear out the theory about streaks forcing the first drop. But this streak-of-8 daily is one I've often checked off first, and until this past week, it was always at 0, 1, or 2, and I think I was still getting drop-on-first-click from it. Though unfortunately I wasn't tracking details exactly, so it's possible I'm remembering wrong.

For baconsaur, though, who's had this happen from the start, it seems like it can't be related to streaks if it's been so consistent. I'm curious now whether baconsaur and I have the same thing happening or not, since mine started more recently and (if I'm not remembering correctly and maybe this wasn't happening every single day) could possibly be related to streaks plus some first-click coincidences on lower or no streaks.

**Comment by baconsaur** [comment] 2013-10-23 15:04
I just did the same experiment as hattieshoe and got the exact same results. I'm fairly sure I've had drops when clicking a zero streak daily first before, but that didn't happen this time. May have just been a coincidence. I generally start off with one of my higher streaks, which are around 170.

I did have this problem long before streaks were introduced, but that was pre-rewrite, so that may have been a separate issue.

**Comment by SabreCat** [comment] 2013-10-23 15:22
Cool investigation, @baconsaur, @hattieshoe! So it's not literally the
first click... but there could still be some issues here.
- Are streaks guaranteeing a drop, at some point? Should they? What should
  that point be? (I'd like to see a steady chance increase until the
  all-important 21-day mark, at which point an infinitesimal miss chance for
  a drop is fine. But that's just one opinion.)
- Are people ever getting a 2nd drop in the day? You're supposed to be able
  to get up to 2.

**Comment by paglias** [comment] 2013-10-23 15:26
@SabreCat considering a delta of about 1 or more (I always found it to be a number from 1 to 2) with 19-20 streak the chances of getting a drop are about 100%

No one is getting the second drop in a day because the count is never resetted, it should be fixed with https://github.com/HabitRPG/habitrpg-shared/pull/30 which I haven't merged myself since I'm not entirely sure it's going to work correctly

**Comment by hattieshoe** [comment] 2013-10-24 13:35
Thursday 10/24/13
1. Yellow daily 0 streak - no drop
2. Yellow daily 0 streak - no drop
3. Yellow daily 1 streak - no drop
4. Yellow daily 2 streak - no drop
5. Green daily 0 streak - no drop
6. Green daily 4 streak - dropped potion
So yeah, it looks like the other drop-on-first-clicks that were for 0 or low streaks may have been coincidences, and the streak amount does seem to strongly influence a drop. With no second drop in a day now, it probably does seem to a lot of us like it's "always" on the first click, especially if our first click is often for something with any kind of streak. (I do remember getting two drops in a day quite frequently before, but not recently. Interesting to hear it's universal and also not related to the streak/drop-on-first-click thing. I had assumed they were part of the same issue.)

**Comment by hattieshoe** [comment] 2013-10-25 13:40
Friday 10/25/13
1. Yellow daily 0 streak - no drop
2. Yellow daily 0 streak - no drop 
3. Yellow daily 1 streak - no drop
4. Yellow daily 1 streak - drop egg
Any reason for me to keep tracking this? It seems the problem has been narrowed down pretty well.

**Comment by hattieshoe** [comment] 2013-10-25 13:41
Whoah, I just clicked something else and got another drop. Did someone fix the second-drop issue?? If so - thanks!

**Comment by paglias** [comment] 2013-10-25 13:42
@hattieshoe ahah no need to continue keeping track of this, thanks a lot :) The 1-drop a day limit has been fixed and now it's 2 drops a day as it should be. We should only decide if we're ok with a 100% probability for 20 and more days streaks

**Comment by paglias** [comment] 2013-10-25 19:42
I think we can close this, if you want to change the probability of getting a drop then open another thread

**Closed as completed by paglias** 2013-10-25 19:42 UTC
