### ISSUE TITLE
Tavern / Guild / Party chat lag / slowness

### ISSUE THREAD

**Issue by MHDante** [HabitRPG/habitica#6462] opened 2016-01-05 08:19 UTC
Platform: Win10, Chrome 47.0.2526.106 m

Take a look at this example of the tavern's chat:
![image](https://cloud.githubusercontent.com/assets/4652122/12110172/5c02a85c-b357-11e5-9f20-3e753b775e8a.png)
The Ss were typed one at a time and the Js were typed 5 at a time.

It seems that there is a listener happening every time that the content of the textbox changes. While this doesn't seem to be a problem in-of-itself, It appears that the digest function it is calling is quite expensive.(I'm not sure if this is an AngularJS problem, or something regarding your backend). For reference, my account has ~20 tasks.

It seems that the lag is present throughout the site, (probably on some task iteration logic), and other Issue threads have tried to address it. #6215 #3486 However, I'd recommend fixing the issue at the chat level.  The entire autocomplete feature could be disabled, or perhaps changing it so that it waits a few seconds from last input before it calls the digest handler. ( I think it already works this way? but the delay is really short?)

I know @lefnire mentioned addressing the chat system in another performance thread, but I'm not sure if it came through. Some good places to start would probably be:
habitrpg/website/public/js/controllers/autoCompleteCtrl.js

I would try to fix it myself, but I'm unfamiliar with the software stack. (As of now)

**Comment by testsubject1987** [comment] 2016-01-14 19:01
Thank you.

**Comment by colwem** [comment] 2016-03-05 07:11
Is any work on this being done?  Is there a reason it can't or shouldn't be done?  If not I'd like to work on this issue.

**Comment by nrbunn** [comment] 2016-04-09 15:14
Ok looking at a different angle into this as debounce seems to help but after a while it seems to generate the same problem. Plus the issue with the crtl-enter not working because of super typers @crookedneighbor. 

i found removing the below from habitrpg\website\views\index.jade sped up the chat overall. Not sure yet why its there as there is a commented line right before it without it.
`, ng-keydown="$broadcast('habit:keydown', $event)", ng-keyup="$broadcast('habit:keyup', $event)"`

**Comment by crookedneighbor** [comment] 2016-04-09 15:58
Yep, I think that's it.

That was added to detect `ctrl` being pressed on the tasks page and escape being pressed on on the inventory page to deselect an item.

**Comment by crookedneighbor** [comment] 2016-06-04 15:01
Just deployed a release that uses some of the changes @Sinble suggested. There's still a _bit_ of lag, but it's much better than it was before and since we're doing a rewrite of the client soon, I think I'm going to say this is good enough.

**Comment by robertpateii** [comment] 2016-06-04 16:28
thanks! this is a lot better. I confirm still a little lag but it's a lot more usable now.

**Comment by testsubject1987** [comment] 2016-06-06 03:18
Agreed... progress. There are still some lag and error messages, for example I click a daily and it jumps around the screen, doesn't check the one I clicked but rather another one. Refreshing the page seems to help relieve the issue.  But overall I am impressed. Please keep up the good work.

**Comment by BeanieB** [comment] 2016-06-07 17:05
This has been an issue for a loonngg time for me, and this is a HUGE step forward. Thank you so much!

**Comment by synrg** [comment] 2016-09-23 11:01
This is still an issue for me (fast typist, ~80 wpm, mostly typing on older/slower systems, e.g. Android tablet: Nexus 7 2013, EeePC model 1001px circa 2010, VNC server running on ~10 year old Athlon X2; but on these systems typing in textboxes on AngularJS applications of my own, I don't have this issue). Should I record any observations here or open a new bug, since this one is closed? I was referred here from the Report a Bug guild by shanaqui and we discussed some of the particulars of my situation a bit more there. "Good enough" may only be good enough if you're on a fast system, and for various reasons, users may not all be on systems that are as fast as the ones developers use daily, so for some percentage of your user base, there's still a lot of room for improvement.

Mobile use case:
- using Chrome instead of the Habitica app because i can put the tablet into landscape orientation
- using a bluetooth keyboard because entering large amounts of text by other mobile text entry methods (google voice, swiping), can be painful, especially once you get more heavily into MarkDown formatting
- slow to the point of unusability; I gave up and switched to the desktop

Desktop use case:
- I have a lightweight desktop workstation running Debian stretch, formerly a mobile unit (EeePC 1001px) repurposed to do office work "docked" with a keyboard and large external monitor; I keep chrome open in my 2nd virtual desktop to run Habitica and some other webapps (mail, calendar, trello)
- performance on this system is generally good, until I start doing Habitica chat; this is true even if I close everything else and only run Habitica
- I tried offloading the processing from the underpowered workstation to a VNC server running on a different system that has both more RAM and CPU (though still quite modest amounts; but this strategy has worked before when webapps took more than the workstation could handle)
- Habitica chat performs better in VNC, but is still aggravating

I could help more with profiling, but looking at the Chrome profiler on the minified code (even when pretty-printed) makes it hard for me to see what's what.

**Comment by Alys** [comment] 2016-09-23 12:25
@synrg We're starting a project to rewrite the website's front-end code, and will not use Angular in the rewrite. I would guess that the new code would perform better, and even if it's not as fast as we'd desire, the causes of slowness would be different than they are now, so my personal feeling is that it would not be worth you spending time on this issue.

We don't yet have a timeframe for when the redesign would be finished.

**Comment by synrg** [comment] 2016-09-23 12:32
@Alys Nice. At work, having become less enamored of Angular the more we used it, we have started the switch to Vue.js. Where is the redesign discussion happening? I'd love to track that.

In the interim, I've started pondering if a simple userscript to s/auto-complete// in the page would work around the issue for me. I have noticed that on chats with few members, performance is excellent, so it seems likely that disabling auto-complete completely would be an acceptable workaround.

**Comment by Alys** [comment] 2016-09-23 12:42
@synrg Oh! A userscript would be popular! If you make one, drop in to the Aspiring Comrades guild and mention it there. That's a guild for people who make third-party tools. I'd also encourage you to join the Aspiring Coders guild which deals with questions and information about coding for Habitica itself. When we have any information about the website redesign, we'll mention it there.

**Comment by crookedneighbor** [comment] 2016-09-23 13:33
Just mentioning that we chose Vue for the redesign :smile:

**Comment by synrg** [comment] 2016-09-29 16:47
I have given up on the idea of a userscript because I found a workaround that works great for me and my wife (we have his-and-hers Eee PC model 1001 PX systems). In Chrome, simply install the Habitica chat extension. My wife reports: "it made my typing show right away as opposed to three minutes after the fact" and I have experienced a similar benefit. It has rescued chat from being completely unusable for us. We'll happily use this until the Vue redesign.

**Comment by applmak** [comment] 2017-02-08 14:28
Hi. This issue here is the use of `ngModel` at this line: https://github.com/HabitRPG/habitica/blob/a2cfeafc02393b167cb3dfef0524d7a89b45cc9f/website/views/options/social/chat-box.jade#L11

After every keystroke, `ngModel` does a full `$rootScope.$digest`, which causes the whole page to reflow. I'd suggest removing that directive, and instead, manually assigning to `message.content` in the `keyDownListener`.

Suggested new code might look something like:
```js
textarea.form-control(rows=4, ng-keydown='keyDownListener($event, "message.content")', updateinterval='250', flag='@', at-user, auto-complete placeholder="{{group._id == TAVERN_ID ? env.t('tavernCommunityGuidelinesPlaceholder') : ''}}", ng-disabled='_sending == true')
```

**Comment by applmak** [comment] 2017-02-08 14:37
Oh, actually you don't even need to pass along `message.content` to the `keydownlistener`! Instead, you can look up the value in the text field via `e.target`, and send it to `postchat` there! If you want, I can draft a PR.

**Comment by SabreCat** [comment] 2017-02-08 15:46
@applmak A PR would be great!

**Comment by applmak** [comment] 2017-02-09 02:42
Okay, so I investigated a bit. Here's what I found:
1. The actual problem is hard to repro on a local dev environment. I'm sure that has to do with the super-fast network and the fact that no one is in my Tavern.
2. I can't just get rid of the `ng-model` and replace it with a custom directive that only updates the scope on form-submission, because the `at.js` autocomplete library is tightly coupled to it, requiring a literal `ng-model` on the same element. Boo.
3. Instead, I can use `ng-model-options` and set the `debounce` option, which limits how often the `$scope` is actually updated.

To show that this works, I set up an quick experiment. On my Chrome 56 (with 5x CPU slowdown emulation), I captured a timeline with a js profile while I typed some text in the chat box. Typing _felt_ sluggish, and the profile reflects that, with nearly every frame > 33ms.

<img width="816" alt="before-profile" src="https://cloud.githubusercontent.com/assets/2245625/22767054/a641669c-ee3e-11e6-9440-98dd1ed4d171.png">

The frame in the picture clocks in at 78ms, of which 31ms is in `$setViewValue` (invoked by the `keypress` event), which is what `at.js` [calls](https://github.com/snicker/Angular-At-Directive/commit/a463dd1453636cfa0473f4f32756aab4861bb31f#diff-0c5b7bfa773fc5c55ef022cf64e7412bR68) after it handles a keypress (Note: this seems like a bug in `at.js`, as it shouldn't need to update the model when it hasn't performed an autocomplete).

In the second half of the experiment, I made the `debounce` change, and took another profile while typing the same text and with the same settings. Typing felt more responsive, and the profile shows that the handling of the `keypress` event has nearly entirely disappeared, with an average reduction per frame of typing of ≈30ms!

<img width="522" alt="after-profile" src="https://cloud.githubusercontent.com/assets/2245625/22767055/a6440a1e-ee3e-11e6-97b7-5e50ebdbcee5.png">

I need to run the PR by my employer first, but I'll attempt to get it in order by tomorrow.

**Closed as completed** 2017-02-27 18:19 UTC
Labels: priority: medium, status: issue: in progress
