### ISSUE TITLE
Pet Page/Market Page slow loading times

### ISSUE THREAD

**Issue by DaniDaniDanica** [HabitRPG/habitica#3578] opened 2014-06-08 15:34 UTC
There is so much lag on these pages for me, my Chrome browser will actually make multiple suggestions to simply kill the tab. My laptop does struggle with running a lot of things at once, but a single page has never caused me so many issues before.

**Comment by SabreCat** [comment] 2014-06-10 01:51
Duplicate of #3558 at least.

**Closed as completed by SabreCat** 2014-06-10 01:51 UTC
