### ISSUE TITLE
Error processing string on feeding pets

### ISSUE THREAD

**Issue by mxrowanthomas** [HabitRPG/habitica#4750] opened 2015-02-25 00:15 UTC
Currently feeding pets allows you to feed them but when it would go to "x really liked y" an error processing string comes up instead, have tried several different pets.

**Comment by crookedneighbor** [comment] 2015-02-25 00:48
Duplicate of #4749 

@numberland I assume you're using a language other than English, correct? Should be fixed very soon. Deploying the fix now.

**Closed as completed by crookedneighbor** 2015-02-25 00:48 UTC
