### ISSUE TITLE
NPCs need banner icon in chat

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#9185] opened 2017-10-14 01:42 UTC
When the real-life people who are in-game NPCs post in chat, they're missing their banner icon. It's visible in the Tavern column next to Bailey's name, but doesn't actually show up when they write a message.

**Comment by lemoness** [comment] 2017-10-14 01:44
Here's an example: https://imgur.com/a/00yTI

**Comment by haydenbetts** [comment] 2017-10-20 20:19
I would like to work on this.

**Comment by lemoness** [comment] 2017-10-20 21:35
@haydenbetts Thank you so much! It's yours. Let us know if you have any questions!

**Comment by haydenbetts** [comment] 2017-10-21 21:17
Hi! In my testing, when I set a user's contributor tier = 10 (npc), there was no problem with the styling in tavern chat. See: https://i.imgur.com/yzHMilO.png

Do you know where the bug appeared in production so that I can try to replicate it?

**Comment by lemoness** [comment] 2017-10-23 23:26
This happened in the Tavern, so if you are unable to replicate it, there's a possibility that it was fixed by a separate deploy. Can anyone else replicate it?

**Comment by librarianmage** [comment] 2017-11-13 23:06
I've seen it working with Bailey.

**Comment by lemoness** [comment] 2017-11-14 01:00
I'm closing this ticket now, but we can reopen it if the issue recurs!

**Comment by Alys** [comment] 2017-11-21 16:07
I'm reopening this because it's broken again.

Here's what it looks like in chat:
![image](https://user-images.githubusercontent.com/1495809/33082894-d14384ec-ced5-11e7-8957-af7108aed85a.png)

And here's what it should look like, taken from the list of mods to the right of the Tavern's chat:
![image](https://user-images.githubusercontent.com/1495809/33082935-ed09652a-ced5-11e7-8bb4-0e11c300a93b.png)

I've marked this as Help Wanted but @haydenbetts post here if you'd like to work on it again.

**Comment by TheHollidayInn** [comment] 2017-12-01 14:10
Do you have Bailey's user Id you can send me?

**Comment by Alys** [comment] 2017-12-01 15:42
9da65443-ed43-4c21-804f-d260c1361596

Relevant data from her account (really just the `backer.npc` part is needed I believe):

    "backer": {
        "npc": "Town Crier",
        "tier": 800,
        "tokensApplied": true
    },

**Comment by TheHollidayInn** [comment] 2017-12-01 16:04
Actually, I think the problem is that the tier is 800 :P The client checks for a tier === 10. So we can just update the client to be >= 10 if you want.

**Comment by Alys** [comment] 2017-12-01 16:28
Ah, no, our code is misleading. :( To help clarify things (I hope), here's Bailey's full contributor and backer data:

```
    "contributor": {
        "text": "Pollen Purveyor",
        "admin": true,
        "level": 8
    },
   "backer": {
       "npc": "Town Crier",
       "tier": 800,
       "tokensApplied": true
   },
```
and here's the data for another NPC, mattboch:
```
    "contributor": {},
    "backer": {
        "tier": 800,
        "npc": "Beast Master"
    },
```

Note how both are NPCs and should have the special formatting, but Bailey is also a moderator (contributor.level = 8). I.e., the `contributor` data is irrelevant to their NPC status.

Part of the confusion comes from the way that we talk about "contributor tiers" (e.g., 1 for a new contributor, 8 for a moderator, 9 for staff), but that data is coded as `contributor.level` in the user documents. 
The `backer.tier` is something different and it describes how much money they paid in the [Kickstarter](http://habitica.wikia.com/wiki/Kickstarter) -  i.e., $800, which is why we love our NPCs. :)

I see in our code that we use a style called `tier10` to apply formatting for NPCs, just like we use `tier9` to provide formatting for staff. However that doesn't mean that NPCs have `contributor.level` being set to 10.

The `tier10` style should be applied to anyone who has any value for `backer.npc`

You _could_ instead apply it to anyone who has `backer.tier` == 800 but I'm not sure that's future-proof. Maybe at some future time we might have more NPCs and then I expect they'd be given a value for `backer.npc`, but their `backer.tier` number might be different or not used at all.

We definitely shouldn't apply the `tier10` style to anyone with `backer.tier` >= 10 because that includes a lot of Kickstarter backers who aren't NPCs. The [Hall of Patrons](https://habitica.com/hall/patrons) lists them all.

I'm wondering if it's worth adjusting all our code to change `tier10` everywhere to `tierNPC`. This current code in particular from `website/client/components/chat/chatMessages.vue` makes it too easy to fall into this misunderstanding:
```
import tier7 from 'assets/svg/tier-7.svg';
import tier8 from 'assets/svg/tier-mod.svg';
import tier9 from 'assets/svg/tier-staff.svg';
import tier10 from 'assets/svg/tier-npc.svg';
```

**Comment by TheHollidayInn** [comment] 2017-12-01 16:33
Ah. I see :P Okay, yes. I'll update this:

1. change tier10 to tierNPC
2. change the npc check to if (Boolean(backer.npc))

Sound good?

**Comment by Alys** [comment] 2017-12-01 16:33
This could be changed too to use 800 instead of 10:
`test/api/v3/integration/user/PUT-user.test.js:62:      backer: {'backer.tier': 10, 'backer.npc': 'Bilbo'},`

Changing that value wouldn't have any effect on the test, but it would make the test data more closely resemble real data, and might help to avoid confusion in future.

**Comment by Alys** [comment] 2017-12-01 16:34
Yes, those two points sound good!

**Closed as completed** 2017-12-13 01:05 UTC
Labels: priority: important, status: issue: in progress, section: Tavern Chat, section: Guilds
