### ISSUE TITLE
Cannot update Guild description

### ISSUE THREAD

**Issue by eiron** [HabitRPG/habitica#5248] opened 2015-05-20 17:38 UTC
Error get:

> Please reload, "Error request entity too large" If the error persists, please report it at Help > Report a Bug. If you're familiar with your browser's console, please include any error messages.

I am not familiar with my browser's console.

**Comment by Alys** [comment] 2015-05-30 06:54
@Eiron Errors like this typically happen with large groups and are often temporary. If it's still happening, tell us:
- the URL for the guild
- the current text(s) that you want removed
- the new text(s) to replace the old text(s).

If it's for a private guild and you don't want to paste the details here, PM me (for this one particular job only, not in general). If there's no need for it to be kept secret, please put all the details here.

**Comment by Alys** [comment] 2015-07-26 11:55
I'm closing this because we can't do anything currently, but if the problem is still happening, tell us the details from my previous comment and we'll be able to help.

**Closed as completed by Alys** 2015-07-26 11:55 UTC
