### ISSUE TITLE
Egg pets do not have growth bar to become mounts

### ISSUE THREAD

**Issue by thaithyme** [HabitRPG/habitica#3399] opened 2014-05-02 12:07 UTC
I've been working on getting all of my pets but found that I cannot feed the eggs to make them grow even though there is a row of unhatched egg mounts. Not sure if this is a user error or not. Screenshots attached for clarity. Thanks!

![screen shot 2014-05-02 at 8 03 20 am](https://cloud.githubusercontent.com/assets/4501106/2862439/2083acce-d1f2-11e3-91a8-61ff686bc35b.png)

![screen shot 2014-05-02 at 8 03 45 am](https://cloud.githubusercontent.com/assets/4501106/2862441/263311dc-d1f2-11e3-96fa-a32880514bc0.png)

**Comment by thepeopleseason** [comment] 2014-05-02 13:29
The mount positions are a bug. Plain eggs are not intended to be fed into mounts. 

Closing--Duplicate of #3240.

**Closed as completed by thepeopleseason** 2014-05-02 13:29 UTC
