### ISSUE TITLE
Gaining experience from completing a quest doesn't appear to trigger a level up

### ISSUE THREAD

**Issue by anwilli5** [HabitRPG/habitica#5399] opened 2015-06-14 04:55 UTC
Upon completing a quest recently, the amount of experience received brought my character's experience amount to 262 out of 260, but did not result in my character leveling up.  Completing a task did fix this issue, though, triggering a level up as expected.  Perhaps the logic to check for and trigger a level up just doesn't get hit in the quest completion case?

To add some additional information:
- My character was level 10 and I had not chosen a class yet
- The quest completed was "Escape the Cave Creature"

Let me know if there is any additional information I can provide.  Thanks for your hard work in making HabitRPG such a great site!

**Comment by crookedneighbor** [comment] 2015-06-14 05:01
Duplicate of https://github.com/HabitRPG/habitrpg/issues/2433. You can follow the progress of the bug their by pressing the subscribe button.

**Closed as completed by crookedneighbor** 2015-06-14 05:01 UTC

**Comment by anwilli5** [comment] 2015-06-14 15:12
Ah, sorry - In my search for existing issues I'm not sure how I missed that one!  Thanks.
