### ISSUE TITLE
dailies only partially reset, and health potions cost more and give less than they should

### ISSUE THREAD

**Issue by kb-code** [HabitRPG/habitica#4779] opened 2015-02-28 17:19 UTC
So, this has happened sporadically over the time I've been playing, but twice in the last week, so let me share it...

I first visit the party page when I check in for day, to see how much damage I've done to boss.  It registers what seems like crazy amount of damage (sometimes I've registered like 20 points damage on a "perfect day" the day before! today, I registered 12.6 on 2 missed dailies, which at my level should only be about 3 damage at most)  Earlier this week, I logged in, it told me I did large damage, I went to the tasks page, half were still checked, so I refreshed, and it killed me.  And half my dailies were STILL checked after refresh.  Which brings me to the other point, half my dailies are still checked after log in sometimes.  I'm attaching a screenshot of the dailies as they looked this morning on log in before I did any checking off tasks.  As you can see, there is what appears to be a random resetting of streaks too as I suddenly have no streaks on well over half of the dailies.

Then, when I went to buy some health potions to make sure I didn't once again lose tons of gold by dying, I bought two, and each time it charged me 25 gold and 8 silver.  Then it only gave me 13.1 HP for each, which covered me, but still, all those numbers are off....

This time it didn't kill me because of health potions, so there's nothing I need in return, and not sure what additional info you might need to look into this, but I'm happy to do whatever you need to diagnose.  

![2015-02-28 08_52_01-habitrpg _ your life the role playing game](https://cloud.githubusercontent.com/assets/3348252/6427090/b093a0d2-bf2a-11e4-9867-68c99d25d63f.jpg)

**Comment by Alys** [comment] 2015-02-28 21:08
The damage you are doing to the boss isn't unusually large. If you happen to get a lucky [critical hits](http://habitrpg.wikia.com/wiki/Critical_hit) when you tick off a task, then you can do much more damage to the boss than normal.

The issue with your Dailies remaining ticked incorrectly or behaving as if you had not ticked them is an example of the bug reported in https://github.com/HabitRPG/habitrpg/issues/4313. I am sorry you were hit by it! If you look in the first post on that page, you will see some information about a workaround for what to do when it happens ("How to fix Dailies that should have become unticked"), and also "What to do if you experience this bug often", which seems to be the case for you unfortunately. :(

The odd prices and results of using health potions would be a side-effect of the caching behaviour caused by that bug. When you see notifications for how much something costs, or how much your stats have changed, it's not necessarily telling you the cost/change caused by your most recent action. Instead, it's telling you how much your gold or stats have changed since the last time you saw a report about them. Usually that's the same thing -- under normal circumstances, if you buy a potion, it will cost you 25 gold, and that's exactly how much your gold decreases by, so that's the amount that you are shown in the notification. However when you've been hit by the "two versions of your data" bug, there are actions cached in your browser that haven't been saved to the server yet and that you haven't yet received notifications for, so that when you take a new action such as buying the health potion, the unsaved actions are then saved and the notifications give you a summary of all the changes to your gold and stats since your last notification. This means that the potion does actually cost you 25 gold exactly, but other changes have resulted in 8 silver being removed as well, so you see a notification for 28 gold and 8 silver at the same time. Similarly, the potion will have given you the full 20 HP but at the same time, something caused you to lose 6.9 HP (e.g., damage from Dailies that were affected by this bug), so you see a total notification of 13.1 HP.

I am not sure how well I have explained this, and I might not have given enough basic information about the bug for it to make sense, so do please ask here if you have questions! In brief, I think all the problems you have reported (except the boss damage amounts, which are normal) are caused by caching of your data, and I am hoping that the nightly reload fix described in that issue will help you. Let us know if that's not the case.

I'm closing this issue, but you can track the progress of the bug by going to that other issue and clicking the subscribe button in the right-hand column. If you do ask questions here, we will still be notified about them even though this is closed.

**Closed as completed by Alys** 2015-02-28 21:08 UTC
