### ISSUE TITLE
Error Processing String

### ISSUE THREAD

**Issue by akwilke** [HabitRPG/habitica#4619] opened 2015-02-03 18:52 UTC
![image](https://cloud.githubusercontent.com/assets/10748453/6026825/6731a262-aba3-11e4-8f5c-d31ed6fefb42.png)

Hello I got this error message in the seasonal shop and it said to report it.  I searched for a similar thread and didn't see it so started a new one.  I refreshed the page as well as closed and reopened the page and the error remained.

**Comment by crookedneighbor** [comment] 2015-02-03 19:00
Duplicate of #4615

You can track the progress by going to that link and clicking the subscribe button.

**Closed as completed by crookedneighbor** 2015-02-03 19:00 UTC
