### ISSUE TITLE
Issue with dailies (not resetting on new day)

### ISSUE THREAD

**Issue by erythrodont** [HabitRPG/habitica#2117] opened 2013-12-26 05:20 UTC
My dailies are showing up exactly as marked yesterday, as if my day hasn't ended yet. They should've reset 8 hours ago. @Alec is facing the opposite issue - his dailies have reset before his custom time of 3am.

**Comment by lefnire** [comment] 2013-12-26 05:21
oh woops, Alec's is a new one then. _This_ one is the dupe of #1057

**Closed as completed by lefnire** 2013-12-26 05:21 UTC

**Comment by erythrodont** [comment] 2013-12-26 05:35
Thanks @lefnire! I'm always amazed by the promptness of your response. Just fyi, setting the custom day start to 0 doesn't seem to be working. I just think I'll wait it out till the server resets the day. Cheers!

**Comment by lefnire** [comment] 2013-12-26 05:41
np! yeah, setting your 0-dayStart won't trigger until next cron, unfortunately. But yeah, custom dayStart != 0 is just a source of many nebulous bugs that I can't peg. Now that most major features are released I'm going into maintenance mode, and I'm gonna tackle that one soon as I can
