### ISSUE TITLE
HUGE unexplained experience (XP) gain, damage to boss, jump in levels

### ISSUE THREAD

**Issue by Gooseus** [HabitRPG/habitica#7625] opened 2016-06-08 16:35 UTC
### General Info
- UUID: 81060e72-f214-4894-aed5-d8849da9372e
- Browser: Chrome (can get version later if relevant)
- OS: Windows 10
### Description

Wish I'd gotten a screenshot, but last night I cast Burst of Flames on a task and got conflicting alerts. One said "Burst of Flames cannot be cast on Challenges" and the other gave me something like 1044xp and I jumped an entire level immediately.  Also the boss damage I did yesterday was 2x my best previous boss damage, which doesn't seem possible to me even with my buffs.

**Comment by librarianmage** [comment] 2016-06-08 21:29
Was the task you cast the spell on from a challenge?

**Comment by Gooseus** [comment] 2016-06-08 21:44
Yep, I was unaware that it wasn't allowed and wasn't even really thinking about it... just trying to rack up some max DPD spamming BoF.

Specifically, it was the the Write 5,000 Words to do from the 15K Words Challenge that I cast on, I believe.  Not sure if that matters.

**Comment by librarianmage** [comment] 2016-06-08 21:49
Were you clicking really quickly? I don't know if that would be of any significance, but sometimes spamming creates desync issues, which could of caused your problem.

**Comment by Gooseus** [comment] 2016-06-08 21:58
I suppose I'd describe it as quickly in human speed.

I scrolled, clicked BoF, then clicked the task... that feels like an eternity in computer speed, though it could be relevant if it was a bug related to round trip communication from previous BoF sent with latency?

**Comment by crookedneighbor** [comment] 2016-06-08 22:24
I see in your party, you just completed the second part of the moonstone quest series, which includes a reward of 1000xp. Most likely, the quest ended, but you hadn't synced yet. When you cast the skill, it failed, but also synced your user, resulting in the large amount of xp.

**Comment by Gooseus** [comment] 2016-06-09 02:24
@crookedneighbor That definitely would make sense, but that's not the last quest we did...  The last quest we did was Vice Part 2 specifically to unlock the current quest, which is Vice Part 3.  Before Vice2 I'm pretty sure we did either Dilatory 3 or Trapper Santa.  Nobody in my group has Moonstone unlocked yet, I'm highest level at 46.

We actually specifically were driving toward Vice3 because we wanted the 1000xp reward and none of the previous quests we've done have more than like ~100xp.

My group ID is `fcf05341-605a-4e6e-ab18-c7d0982e2255`, so I'd say this is either a different bug in our group, a bug with me being in a 2 groups at once (I've had reports that I appear in my current group twice on Android and I got the double boss damage bug once before), or it's something else entirely.

**Comment by librarianmage** [comment] 2016-06-09 02:26
@Gooseus Vice Part 2 is the second quest in the Moonstone Quest chain, if that changes anything

**Comment by Gooseus** [comment] 2016-06-09 02:37
I'm definitely confused... I was under the impression Vice and Moonstone were completely different quest series?

![image](https://cloud.githubusercontent.com/assets/39137/15917262/0c12ad8c-2dc9-11e6-8f49-459ee3b448cb.png)

![image](https://cloud.githubusercontent.com/assets/39137/15917269/1d88d474-2dc9-11e6-8168-23600e20fcbf.png)

Did this change or am I missing something?  That screen also shows Vice 2 being worth only 75xp.

**Comment by librarianmage** [comment] 2016-06-09 02:40
Oh, nvm

**Comment by crookedneighbor** [comment] 2016-06-09 03:08
Sorry, you're right, I wasn't looking closely enough. I saw light crystals and mistakenly thought it was the moon stone quest.

**Comment by crookedneighbor** [comment] 2016-06-09 03:09
You can't be in two parties at once because parties are determined by a single value on the user object.

**Comment by Alys** [comment] 2016-06-25 04:38
I don't think this is directly related to casting the skill. For the huge XP gain and boss damage to have been caused by casting BoF on the challenge task, there'd have to be a bug in both the code that prevents skills being cast on challenge tasks and in the code that controls how much XP and boss damage can be done by BoF, and both those pieces of code are relatively simple and unlikely to be buggy.

We do occasionally see sudden, unexplained increases in levels (https://github.com/HabitRPG/habitrpg/issues/594, https://github.com/HabitRPG/habitrpg/issues/5238, https://github.com/HabitRPG/habitrpg/issues/4955) and I think this is a similar thing. I'm marking this as not being a challenge problem, and adjusting the title.

**Comment by Alys** [comment] 2016-11-20 22:33
For the record, another example similar to this was logged in the Report a Bug guild by La Chapelière (b8824fa6-fa1e-452a-8bc0-34b21ce06ccd) about 10 hours ago:

"Hi, I've just had a weird thing happen to me when I clicked a reward. It was supposed to cost 10 gold. It took from me around 33 gold and 70 mana but gave me 2000xp. It might have costed me some life points too, I'm not sure."

I can't find anything in the AWS logs or Amplitude to indicate what caused it.

**Comment by Alys** [comment] 2017-06-20 22:01
I haven't seen this for a while so I'm closing it. We can reopen if we hear other reports of it.

**Closed as completed by Alys** 2017-06-20 22:01 UTC
Labels: priority: minor, status: issue: needs investigation
