### ISSUE TITLE
Beast Master achieved without doing anything

### ISSUE THREAD

**Issue by nicovaras** [HabitRPG/habitica#1819] opened 2013-11-14 21:52 UTC
I reached level 3 and beast master was automatically achieved. I don't have any pets. 

UUID 1d162bcb-1125-4552-bed5-bc24cd468ff0

Google Chrome 31.0.1650.57

**Comment by lefnire** [comment] 2013-11-14 21:57
dupe of https://github.com/HabitRPG/habitrpg/issues/1818 , please refresh your page and try again

**Closed as completed** 2013-11-14 21:57 UTC
