### ISSUE TITLE
Not loading properly: tasks not loading, all menus expanded

### ISSUE THREAD

**Issue by Shelkesem** [HabitRPG/habitica#5485] opened 2015-06-25 13:57 UTC
![image](https://cloud.githubusercontent.com/assets/13050352/8355892/01449814-1b20-11e5-96ec-c37d31df64d0.png)

Code showing up instead of text; habits, dailies, and to-dos not showing up at all; all menus expanded, with awkward overlap. Off-site links are still functional (i.e., "report a bug," "request a feature") but in-game links are not (i.e., "pets," "equipment"). In-game links being broken means I can't get to Settings --> API to access my user ID, so I'm unable to include it. I'm using Chrome Version 43.0.2357.130 m on Windows 7 Pro.

Not fixed on reload.

**Comment by hairlessbear** [comment] 2015-06-25 15:08
This is caused by the same issue as #5486 (I'm having the same problems). There have been multiple server issues recently, and they appear to have gotten worse today. Unfortunately, there's not much you can do at the moment other than refreshing and hoping for the best. Hopefully it'll get fixed soon.

**Comment by crookedneighbor** [comment] 2015-06-26 12:10
We did some work server side. Turns out that there's been a pretty serious memory leak in Node that [manifests itself when using New Relic logging](https://discuss.newrelic.com/t/memory-leaking-only-with-node-js-agent-installed/14448/28). We've disabled New Relic for now and are investigating how to patch Node so we can turn New Relic back on. 

From an end user perspective, you should see no change (except for improved stability \o/ yay!) 

Hopefully all is well now. Going to close this, but if you're still having issues, please re-open.

**Closed as completed by crookedneighbor** 2015-06-26 12:10 UTC
