### ISSUE TITLE
Reset does not remove attribute points OR lets them go negative

### ISSUE THREAD

**Issue by JadelynnOpal** [HabitRPG/habitica#2496] opened 2014-01-21 00:21 UTC
I was a level 15 rogue and went to reset my account and for some reason it didn't completely reset. I still have the attribute points (and am classed as a Rogue) from when I was level 15 and I still have a Mana bar even though I don't have access to any spells/skills. I didn't find this on any known bugs list, either.
##

**Comment by JadelynnOpal** [comment] 2014-01-21 00:50
I also have all pet and mount-related inventory items, though combat gear has been removed. And still have access to the equipment store as well.

**Comment by JadelynnOpal** [comment] 2014-01-24 20:18
Got to level 10 again and it didn't give me the option to choose class, which is one of the main reasons I wanted to reset. Am I going to have to completely delete my account if I want to start over properly?

**Comment by deilann** [comment] 2014-02-11 10:08
Ach @JadelynnOpal sorry no one ever got to you:

reset doesn't change your class, partially because changing your class costs gems and reset is free. If you want to change your class, you can do this in Stats & Achievements for 3 gems.

**Comment by deilann** [comment] 2014-02-11 10:08
Sorry, reopening because the attribute thing is a problem.

You should have all pet/mount related items because those can be bought with gems, and people don't want reset to take away items they might have spent real money on.

**Comment by digital-carver** [comment] 2014-05-20 09:23
The Mana bar still keeps appearing after a reset, pets and pet food remains (I don't particularly mind this), and most importantly for me, the previous Challenges still show a "Leave" button as if I was still in on them, even though all of the corresponding tasks and habits have been removed by the Reset. 

This is particularly grating because the Challenges page is already difficult to use, with every Leave or Join triggering a reload which also ends up losing my scroll position within the page, necessitating a Ctrl-F every time. With this Reset bug, I have to do this _twice_ for every Challenge I wish to take up again, once on clicking "Leave" (so that I can turn the button to "Join"), and then again on actually Joining back to the challenge. 

I don't know whether the attribute thing still exists though, I hadn't noted down what my attributes were before the Reset, but currently that part of the profile reads: 

```
10 Unallocated Attribute Points 
Automatic Allocation
Distribute attribute points evenly
Distribute points based on Class
Distribute points based on task activity
Points allocated to CON: 0  
Points allocated to INT: 0  
Points allocated to PER: 0  
Points allocated to STR: 6  
```

**Comment by deilann** [comment] 2014-05-20 09:27
Yes, reset is a poorly maintained feature. Patching it up is not super high
prio, but will be looked into at some point.

**Comment by Alys** [comment] 2014-12-06 09:11
Refer to https://github.com/HabitRPG/habitrpg/issues/3947 and https://github.com/HabitRPG/habitrpg/issues/2332 for attribute points becoming negative after Reset.

**Comment by adamhollett** [comment] 2015-02-03 16:40
This happened to me as well.

I kept all of my assigned attribute points after a reset, which doesn't seem to be the intended behaviour. You can do a "clean" reset by buying an attribute point refund for 3 gems and then performing an account reset. This way, you still keep your current class, but your attributes are as a level 1 character's should be.

Maybe a note should be added somewhere to indicate this behaviour, if it's not going to be fixed.

**Comment by crookedneighbor** [comment] 2015-02-03 17:20
Verified that this is still an issue.

I believe that this is the function that needs to be modified: https://github.com/HabitRPG/habitrpg-shared/blob/32ed4dace7b6d713e659e6f0b7ff7cea0160a75b/script/index.coffee#L436-L457

![screen shot 2015-02-03 at 11 18 17 am](https://cloud.githubusercontent.com/assets/2916945/6025220/6237cb40-ab96-11e4-9b76-5988f817127c.png)

**Comment by crookedneighbor** [comment] 2015-02-03 18:29
@deilann 

### Re: not resetting class because of it being a gem purchasable item.

Is the thinking that someone would reset and then use fix character values to restore stats and thus get around the need for gems to change classes?

If that's the case, what's stopping someone from just upping their level to over 100 using fix character values and then using the free orb of rebirth?

I feel like as long as the fix character values option exists, this is not a good argument for not resetting the class as well.

I'm in total agreement about the other gem purchasable things though (pets, backgrounds, etc).

Thoughts?

### Re: the mana bar.

That is [persistent because the code that displays it](https://github.com/HabitRPG/habitrpg/blob/develop/views/shared/header/header.jade#L25) is this:

``` jade
.meter-label(tooltip='Mana', ng-if='user.flags.classSelected && !user.preferences.disableClasses')
```

And since the class is not reset, the mana bar is still present. 

I ran into a problem showing the mp stat for the member modal, since that flag is not present on the member object, I showed the MP stat by doing this: 

``` jade
tr(ng-if='profile.stats.lvl >= 10 && !profile.preferences.disableClasses')`
```

So perhaps we should change the `ng-if` to reflect the same check (using `user` instead of `profile`, of course). That should take care of it.

**Comment by deilann** [comment] 2015-02-03 18:30
Orb of Rebirth was never free when I made that comment.

**Comment by Alys** [comment] 2015-05-18 00:51
Related: https://github.com/HabitRPG/habitrpg/issues/2041 "Changing level with Fix Character Values doesn't adjust Attribute points"

**Comment by Alys** [comment] 2016-01-09 14:05
I'm closing this in favour of [Issue #6482: incorrect attribute / stats points from various causes - need generic function to do allocation / deallocation](https://github.com/HabitRPG/habitrpg/issues/6482)

**Closed as completed by Alys** 2016-01-09 14:05 UTC
