### ISSUE TITLE
Only one egg or potion per day, always on first task completed

### ISSUE THREAD

**Issue by AdrienLemaire** [HabitRPG/habitica#1343] opened 2013-08-18 00:50 UTC
Hello,

Until recently, I think we could have up to 2 potions or eggs per day, and it came randomly during the day.

But since about a week, I noticed that I get one and only one potion or egg (of course always something I already have, haven't hatched in a while), and always on the first task completed on a day.

This doesn't seem right. Someone who completes only one task per day finds as much potion/egg as someone who completes 15 :(

**Comment by octern** [comment] 2013-08-21 03:50
This is definitely not the intended behavior.

**Comment by lefnire** [comment] 2013-08-21 04:06
definitely not. we'll get to this come rewrite, we're saving current site fixes for critical errors

**Comment by AdrienLemaire** [comment] 2013-08-21 04:11
Ok fine, thanks :~)

**Comment by baconsaur** [comment] 2013-08-21 18:11
You used to get your drops randomly? Huh. I've used HabitRPG every single day since before drops were introduced and I've always received just one per day with my first task. I'd assumed it was intentional.

**Comment by octern** [comment] 2013-08-21 19:07
It's never been like that for me. I get 1 or 2 drops a day and not at all
at consistent times.

**Comment by Shaners** [comment] 2013-08-22 21:54
What browser are you using and which version of it?

**Comment by Shaners** [comment] 2013-08-22 22:10
Also could you go to:
http://jsfiddle.net/VN3Bd/
a couple times and let us know what your split is?

**Comment by octern** [comment] 2013-08-22 22:21
Firefox 23.0.1 on Mac OS 10.8, not getting the problem described in the OP:
49.09/50.91
49.2/50.8
49.480000000000004/50.519999999999996
50.44/49.559999999999995
49.64/50.36000000000001
50.06/49.94

Yay floating point math!

**Comment by Shaners** [comment] 2013-08-22 22:30
Interested to see @Fandekasp 's results or anyone else with odd drop rates. Wondering if math.random() is the culprit or contributing (probably not.)

**Comment by baconsaur** [comment] 2013-08-22 22:48
I'm on Firefox 24.0, and I have no idea what all of this is but here we go:
49.82/50.18
49.47/50.529999999999994
50.28/49.72
50.07/49.93

**Comment by AdrienLemaire** [comment] 2013-08-22 23:23
Using [dwb hg](http://portix.bitbucket.org/dwb/) (webkit based):

```
Above 500: 4905
Below 500: 5095
split: 50.949999999999996/49.05
Above 500: 5036
Below 500: 4964
split: 49.64/50.36000000000001
```

Or Chromium 28.0:

```
Above 500: 4947
Below 500: 5053
split: 50.529999999999994/49.47
Above 500: 4922
Below 500: 5078
split: 50.78/49.220000000000006
```

**Comment by SabreCat** [comment] 2013-08-23 03:36
I know my drops have been nicely randomized in the past, but now I'm all paranoid... have I been on a consistent streak of getting one egg on the first click of the day? Gonna keep track of when I get my drops from here out, see if it's a thing.

**Comment by Shaners** [comment] 2013-08-23 20:12
Here's a condensed version of the Habit drop system if anyone else wants to play with it:
http://jsfiddle.net/Shaners/aFd7M/
Open up browser console to see more details. 
Edit currentValue between -47.27 and 21.27 to simulate task score. 
Edit this line for priority multiplier (1, 1.5, or 2): chanceMultiplier *= 1.5; 
Edit this line for streak bonus: chanceMultiplier += :arrow_right:5:arrow_left: / 100 + 1;

**Comment by SabreCat** [comment] 2013-08-25 17:51
Already got a counterexample here. The pattern @Fandekasp and @baconsaur are witnessing definitely isn't universal.

Start: 17 eggs, 8 potions.

8/24: First click (daily at 6 streak) gets a Flying Pig Egg. No further drops.
8/25: First click (daily at 0 streak) gets nothing. Second click (daily at 78 streak) gets a Cactus Egg.

**Comment by paglias** [comment] 2013-09-09 18:11
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!

**Closed as completed by paglias** 2013-09-09 18:11 UTC
