### ISSUE TITLE
Clicking on user always shows the wrong armor set

### ISSUE THREAD

**Issue by casicastiel** [HabitRPG/habitica#2018] opened 2013-12-17 19:35 UTC
This could be because I'm wearing the Golden armor set (though using a disguise).

When I click on other users - one of whom just signed up today, and literally can't have that armor equipped - it shows the golden armor for them under equipment (but the correct armor bonuses under Attributes).

I'm in Chrome, user id cca60406-1b8f-496e-af77-cd19df77c895.

**Comment by lefnire** [comment] 2013-12-17 19:38
dupe of https://github.com/HabitRPG/habitrpg/issues/2010

**Closed as completed by lefnire** 2013-12-17 19:38 UTC
