### ISSUE TITLE
Display Name and Profile blurb editing should include checks for swear words and slurs

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#11865] opened 2020-02-15 09:14 UTC
As you probably know, Habitica's chat feature has code that prevents you posting a message that contains swear words or slurs - when you try to post such a message, you see an error and the message is not posted. Also, If you try to post a slur, your chat privileges are automatically revoked.

We want the same checks to be done when someone edits their profile, which they can do by clicking the Edit button on the [User Icon > Profile](https://habitica.com/user/profile) page.

I.e., when the user clicks Save on the Profile edit screen, the text in the Display Name and About fields should be checked to ensure that they have no swear words or slurs. If they do, the change should not be saved. If a slur is used, the user's public chat permissions should be revoked and moderators should be notified in the same way that they are for chat messages that contain slurs.

You can see at least some of the current code that checks for swears and slurs in chat posts by doing `git grep Banned` (case-sensitive).

As you're looking through the code base, you might come across the files `website/server/libs/bannedWords.js` and `website/server/libs/bannedSlurs.js` - be aware that that's where the bad words are stored, so don't read through them if you don't want to see the words. The top several lines of each file are safe and give you information about how the words are used. There's a large amount of space under that information so you should be able to read the top part of the files without seeing the bad words at the bottom.

For testing on your local install, you can use "TESTPLACEHOLDERSWEARWORDHERE" and "TESTPLACEHOLDERSWEARWORDHERE1" as swear words, and "TESTPLACEHOLDERSLURWORDHERE" and "TESTPLACEHOLDERSLURWORDHERE1" as slurs. They'll give the same behaviour as real swears or slurs would. To restore chat privileges to your test account, set `flags.chatRevoked` to `false`
 
Ideally, the checking of the Display Name and Profile blurb should be done with code in the API, not client-side code (this will later make it easier for the same checks to be added to the mobile apps or to third-party tools). HOWEVER it's important that the checks are done only when the user has changed their Display Name or Profile blurb. I.e., when any other change is saved to the user's account, the name and blurb should not be checked for bad words. If that proves to be difficult or impossible, post here and we'll consider options.

I'm leaving this as suggestion-discussion for about a week in case the staff want to make any comments about it but after that if there's no objections I'll mark it as help wanted.

---

_NB: In case anyone's curious, when a player uses a slur and has their chat permissions automatically revoked, the team of moderators are notified and we always review those repors promptly. In cases where the slur was used accidentally or innocently, we restore the chat permissions as quickly as we can and PM the user to explain what happened (e.g., if the user is posting a literary quote that contains a slur but that is otherwise unobjectionable)._

**Comment by joefessenden** [comment] 2020-02-15 20:36
I'd like to take a crack at this one. I'm not sure I'll be able to handle it, but we've gone this long, so I don't think a couple days of me trying is going to be the end of the world. 

I just realized it's not ready for the oven yet (I'm assuming that's what this status means).

**Comment by Alys** [comment] 2020-02-15 23:32
@joefessenden Thanks for offering! Please check back when it's been given the help wanted label. Note that there might be changes to the requirements based on staff feedback, so you'd want to read the issue again and then if you still decide you want to work on it and no one else has picked it up, post here again and we'll mark it as in progress for you.

**Comment by Alys** [comment] 2020-02-22 08:17
I've labelled this as help wanted. @joefessenden Are you still interested in taking it on?

**Comment by joefessenden** [comment] 2020-02-22 15:33
@Alys yes, Please.

**Comment by Alys** [comment] 2020-02-22 21:04
@joefessenden Great, thanks! Please go ahead.

**Comment by joefessenden** [comment] 2020-03-10 23:26
@Alys I wish I could do this in a timely manner, but I just took a new job, and I won't have time to sit down with this code for a little while, so please make it available again. If no one has grabbed it when I catch up, I'll swing back around.

**Comment by shanaqui** [comment] 2020-03-11 19:34
@joefessenden Alright, I've marked it as help wanted again!

**Comment by inftp** [comment] 2020-03-13 15:06
Can I have a crack at this as my first contribution?

**Comment by Alys** [comment] 2020-03-14 09:28
@inftp Thank you! Please go ahead. Post here if you have questions.

**Comment by inftp** [comment] 2020-03-18 00:33
@Alys just to clarify:
* If the user's new display name or blurb contains a ***swear or slur*** the change will not be accepted.
* If the user's new display name or blurb contains a ***slur*** their chat privileges are to be revoked.

Is this correct?

**Comment by Alys** [comment] 2020-03-18 02:44
@inftp That's correct!

**Comment by inftp** [comment] 2020-04-27 09:24
Hi team,

I will unfortunately no longer have the ability to work on this ticket. Is it possible for someone else to use the state of the current PR (#11991) to work off or should I close it out?

**Comment by shanaqui** [comment] 2020-05-12 14:45
@inftp Thanks for letting us know! I've marked it as help wanted again. I'm not sure if someone else will be able to use your PR -- @Alys?

**Comment by HowlingWolfTable** [comment] 2020-05-15 23:01
I'll take it on. I'll let you know if it's too complex, but I think I'll be able to handle it.

**Comment by Alys** [comment] 2020-05-16 08:52
@HowlingWolfTable Thank you! I've marked this as in progress for you.

Please review @inftp 's pull request and the comments made in it: https://github.com/HabitRPG/habitica/pull/11991
Many of the comments will be relevant to your work (e.g., we list new error messages there), and you might like to consider re-using some or all of the code.

@inftp @shanaqui I'm sorry I didn't reply to your questions before now. Yes, the pull request can be continued by @HowlingWolfTable if they wish to. Thanks for your work @inftp !

**Comment by HowlingWolfTable** [comment] 2020-05-17 06:56
I will have to abandon @Alys. I'm new to this LOL.

**Comment by Alys** [comment] 2020-05-17 12:37
@HowlingWolfTable No worries! Thanks for letting us know!

**Comment by NickHolden** [comment] 2020-06-02 15:23
i'd like to take this one on!

**Comment by Alys** [comment] 2020-06-02 23:45
@NickHolden Thank you! Please go ahead and post here if you have questions or run into trouble.

You've probably seen this already from one of my comments above but just in case:

Please review @inftp 's pull request and the comments made in it: #11991
Many of the comments will be relevant to your work (e.g., we list new error messages there), and you might like to consider re-using some or all of the code.

**Comment by shanaqui** [comment] 2020-07-16 12:51
@NickHolden Hi! Are you still interested in working on this issue? If not, or if we don't hear from you within a week, I'll mark it as help wanted to see if anyone else wants to take it on. :)

**Comment by shanaqui** [comment] 2020-07-28 12:00
@NickHolden I've marked this as help wanted again, but feel free to let us know you want to pick it back up.

**Comment by bigsee** [comment] 2020-08-07 17:27
@shanaqui this one looks a little involved from what I can see of the previous PR. However, I'm willing to have a go if this still needs attention and no-one else is on it. If I get in trouble or find that it's beyond me then I could just bring it back and let you guys know?

**Comment by Alys** [comment] 2020-08-08 11:56
@bigsee Thank you! That would be great. I've marked it as in progress for you. Feel free to tell us if you have any questions or decide not to work on it.

**Comment by bigsee** [comment] 2020-08-09 14:00
PR is here 👆🏽

**Comment by shanaqui** [comment] 2020-10-06 09:59
@bigsee Same here! Are you still working on this? :)

**Comment by shanaqui** [comment] 2020-10-13 11:49
@bigsee I'm going to mark this as help-wanted again, but let us know if you want to pick it back up!

**Comment by bigsee** [comment] 2020-10-13 14:46
@shanaqui hello! I've done this already I believe. There was a merge request submitted but I can't remember the status. I'll be able to check tonight.

**Comment by lsophie** [comment] 2020-11-12 17:08
Is this issue still open to pick up? If so, I'd love to try it!

**Comment by bigsee** [comment] 2020-11-13 08:44
@lsophie @shanaqui I mistakenly thought this issue was fixed by a MR I've already had accepted #12444, but it turns out there is a separate one here #12445 that needs a simple text change. Since the majority of the work is done I can make the text change requested by @Alys here if that's OK?

**Comment by hamboomger** [comment] 2020-11-27 11:30
@shanaqui it looks like the issue is being worked on by @bigsee, could you please remove the `help wanted` label?

**Comment by paglias** [comment] 2020-11-27 17:43
@bigsee sorry for the delay, please go ahead!

**Comment by bigsee** [comment] 2020-11-27 17:47
@paglias no problem at all! Thanks for confirmation. I'll get this finished off.

**Comment by shanaqui** [comment] 2021-02-23 15:05
@bigsee Just checking in on this one and whether you're still working on it/whether there's anything left to do!

**Comment by bigsee** [comment] 2021-03-01 22:25
@shanaqui apologies for the delay. I started a new job in the meantime and looks like this fell off my list. will double-check what needed finishing with this PR and try to tie up over the next few days.

**Comment by bigsee** [comment] 2021-03-16 20:43
Updated PR. Apologies again. 🙏🏽

**Closed as completed** 2021-04-30 20:47 UTC
Labels: priority: medium, status: issue: in progress, section: Other
