### ISSUE TITLE
Web site is not aware of all mobile app state changes

### ISSUE THREAD

**Issue by ioandev** [HabitRPG/habitica#8607] opened 2017-03-28 13:14 UTC
[//]: # (Fill out relevant information - UUID is found in Settings -> API)
General Info
  * UUID: eeaa2757-fb24-49f9-afbf-1104e94bf70a
  * Browser: Chrome
  * OS: Win 10

### Description
[//]: # (Describe bug in detail here. Include pictures if helpful.)
I'm mostly using Habitica from my android phone as I like the design way more and it's everywhere I go. However, I use it in the browser sometimes to up my STR levels and have a grander view of everything.
That said, I don't think the web site is updated with all that I do on the phone. Sometimes I get helpful popups to teach me stuff that I already did on the phone.
10 minutes I checked a few checkboxes in the app for the todos I've made. Then, I got to about 274/280 points and 34HP (got hit by cron last night for 16). Then I get this popup: http://prntscr.com/epgrlx
It said for a second that I got level 12 and I have 30 EXP now. And this popup is weird.. because I had a negative value for checkins till next prize -13. Guess what? The Feral Dust Bunnies is a mission I've completed 3-4 days ago. Why does it even show? Anyway.. I said whatever. I should've gotten the points for this achievement a few days ago, and I guess I get them now.. OK.
However, after pressing "Awesome" there were my abilities STR,CON,etc that I could've upped. And so I did.. I put a point in STR and then it happened: i got a error message that I don't have points for that ability yet, and then it put me back to level 11 and I took 16 dmg back to 34HP ..

Is this a client state bug?
Maybe.

But it didn't give me the EXP back. Before this popup I was at 274/280 EXP and now I am at 30/280 EXP.

To recapitulate: I was LV 11  274/280EXP 8STR 3CON, then I got to LV 12 30EXP 8STR 3CON, putting +1STR got me back to LV 11  30/280EXP 8STR 3CON .

So I am missing 244 EXP.

You can check that I did "The Feral Dust Bunnies" a few days ago and started another mission 1-2 days ago.

Thanks.

#### Console Errors
[//]: # (Include any JavaScript console errors here.)
I've refreshed the page..

**Comment by lemoness** [comment] 2017-12-07 20:30
This is a duplicate of our concurrency issues, so I'm closing this ticket for now!

**Closed as completed by lemoness** 2017-12-07 20:30 UTC
