### ISSUE TITLE
Reset doesn't exactly reset

### ISSUE THREAD

**Issue by mgatten** [HabitRPG/habitica#139] opened 2013-01-20 17:38 UTC
I love the idea of this site, having just discovered it this morning and becoming a Kickstarter contributor. The first thing I did was try to delete a habit by clicking the little red "minus" - which, of course, docked me hitpoints instead of deleting it. Fortunately, since I've not done anything else, a Reset made sense. (Not because a single hit made much of a difference, but because the very first thing in my history data would be wrong forever and that seemed silly.) So I reset. 

I was expecting it to go back to the way it was when I first logged in - with sample habits, tasks, and dailies intact. (A few of those were handy and I'd planned to keep them.)

Instead, all the samples were gone - so it wasn't exactly a reset to first login. Since it's the newest users who are most likely to use the reset feature, it should either reset it to the same thing a brand new user sees, or should be clear that it's not going to do that.

**Comment by horusofoz** [comment] 2013-01-26 11:10
@hookang @lefnire Has anyone considered whether or not we're likely to implement what the user is asking for? 

My thought would be a Reset confirmation dialogue explaining what a Reset does and offering a Re-roll if that is what the user is looking for.

@mgatten Can you advise if a Re-Roll is what you were looking for when you chose Reset? As there is no "activity log" at this stage your desire to avoid having " the very first thing in my history data... wrong forever" is offset.

**Comment by mgatten** [comment] 2013-01-26 16:25
This is really only an issue for rank beginners. But, since we hope there will always be a large cadre of new users flocking to the site every day for at least the next 50 years or so, I'd still like to see it addressed. The impression currently given is that the reset will make your account look like it did the first time you logged in. The first thing a new user is most likely to do is play around with features and learn how the site works, and in doing so they are likely to discover that feature and take it as a green light to experiment as much as they want without having to worry about screwing up their character. Once they are ready to actually "use" the site, they click reset and suddenly everything is blank and all the samples are gone. If they liked some of those samples and planned to build on them, they will just have to remember them. 

A few alternative ways to address the issue:
1. When you press reset a warning should appear mentioning that the result will include wiping out everything and leaving you with completely empty lists; Or,
2. Any time all of somebody's lists are completely empty there could be a button to load a set of sample tasks. Maybe this could even be dynamically generated by finding the top-ten most commonly used strings across the userbase and putting those into the lists. That would ensure that the things the most people find useful to have on lists will be the ones offered to new users; Or,
3. Just have the reset load the original samples (which was, after all, the expected behaviour).

**Comment by horusofoz** [comment] 2013-01-26 16:49
@mgatten Great ideas. We'll have to wait to for the devs to decide.

**Comment by bodhiBit** [comment] 2013-02-20 20:25
The reset doesn't seem to delete all my rewards, which it should since I didn't really earn them when I was playing with the site.. My gold is gone, but I can still see the in-game rewards and pets I had available..

**Comment by lefnire** [comment] 2013-02-20 20:28
reset doesn't disable features. The item store is separate from your
rewards, they're static items unlocked by the item-store feature. I think
we're going to keep that as is

**Comment by bodhiBit** [comment] 2013-02-20 20:43
Well, for me unlocking items is part of the game.. Getting new rewards available is a reward in itself.. And I still have a pet that I didn't truly earn and now can't get rid of..

If I can't truly start over and start playing the game honestly, then it would just be a constant reminder that I "cheated".. That doesn't seem motivating to me..

Bottom line: Reset should do what it says it does: Reset.. fully..!

Other than that, I think it's a great concept that I can't wait to try out, once I figure out how to start fresh.. :)

**Comment by wc8** [comment] 2013-03-13 23:02
Perhaps, for a full reset: [Delete Account](https://trello.com/c/ezd4YkAS) and then recreate it.

**Comment by wc8** [comment] 2013-04-04 12:19
In consideration of #771 and previous comments, for clarity for the user, I suggest:
- Reset returns the account to "factory state," i.e. what they would get if they were a new user: preset items, tour, unlock levels, etc. with full warning. 
- Exception(s) with full warning: Tokens, spent tokens are not restored

Users wanting more nuanced account "reset" can mostly do so manually with some or all of the following:
- delete all or almost all tasks, habits
- die: record bad habit(s) until dead, account now at level 1, HP 50, (levels remain unlocked?)
  - reroll to restore a few saved tasks & habits to yellow
- if/when implemented, [restore sample items](https://trello.com/c/3q5fHAdQ) to their account

> _reset_ Electronics cause (a binary device) to enter the state representing the numeral 0. :wink:

**Comment by StanLindsey** [comment] 2013-05-06 05:38
Closing as if this should now be solvable.

**Comment by lefnire** [comment] 2013-05-06 08:03
Well, the reset button is still busted. We can remove it sine they can delete, recreate their accounts, but then they'd lose api credentials. Let's keep this open till we fix or remove the reset feature

**Comment by lefnire** [comment] 2013-09-11 20:36
broken reset button is fixed now. reseting by removing sample tasks is as intended, I see many more people wanting a blank slate once they've figured out the system, then the starter tasks

**Closed as completed by lefnire** 2013-09-11 20:36 UTC
Labels: status: issue: suggestion-discussion

**Comment by ghost** [comment] 2013-12-27 15:42
I didn't use the site for a couple months and was surprised by the new class system. I was forced to pick a class, even though I didn't have any idea what all the stats and classes and skills did. 
I thought all would be good again, if I reset my account. I'm back to level 1 now, but I am still a Rogue with 19 unspent attribute points. Is this intended?
