### ISSUE TITLE
Died despite Resting in Tavern

### ISSUE THREAD

**Issue by KatjeiDa** [HabitRPG/habitica#1090] opened 2013-05-29 20:41 UTC
I "checked into" the Tavern on Thursday because I was going away for the weekend and early week and was not going to be able to complete Dailies etc but when I went to "check out" on Wed morning I found my "check in" had not registered and thus I had died over the weekend.

I did use Restore and got back more or less to where I was but just wanted to report it for the record.

**Comment by wc8** [comment] 2013-05-29 23:45
Perhaps related to #997

**Comment by lefnire** [comment] 2013-06-04 16:55
yeah, dupe of that. let's follow up there

**Closed as completed by lefnire** 2013-06-04 16:55 UTC
