### ISSUE TITLE
quest pets triggering beast master notification

### ISSUE THREAD

**Issue by rhonnnnie** [HabitRPG/habitica#3320] opened 2014-04-21 01:13 UTC
Haven't seen this issue mentioned anywhere yet so making a new ticket :)
After I got the Beast Master achievement, every time I hatch a new quest pet the notification will pop up again?
Just a little thing, but after the Egg Quest or something with 10 eggs lined up it got a little irritating having to close it every time... 

Thanks :D
(UUID is 76416b9e-307f-43ad-8a1a-cce5225eebe1)

**Comment by thepeopleseason** [comment] 2014-04-21 01:38
Duplicate of #2990

**Closed as completed** 2014-04-21 03:09 UTC
