### ISSUE TITLE
Health being reset to 5

### ISSUE THREAD

**Issue by vewong** [HabitRPG/habitica#16] opened 2012-12-14 08:27 UTC
I can't remember what level I was at, but I leveled up and right after my health was refilled from leveling up, it plummeted down to 5. I tried to buy a potion with my credits but again, it went up then back down to 5. I leveled myself up again to get the health back.

Next time I logged in, my health was at 5 and I immediately died because I guess I lost 5 health for not updating my daily tasks today.

**Comment by lefnire** [comment] 2012-12-14 19:16
Hey @vewong, I think I know exactly what's happening - which is definitely a bug. Where heavy data manipulation in the browser is present, Derby takes a bit (as in like 5s, which is a lot) to sync the data to the server. This happens for example when "cron" is run on the browser (1s after a refresh), leveling up, etc. It takes time for that data to sync up to the server, and if any actions are performed between that phase it causes wonky data screwup. My solution will be to perform complex data manipulation on the server using [racer-server-request](https://github.com/rma4ok/racer-server-request)

In the meantime, the janky solution is to wait a good 5 seconds to make sure big changes get synced to the server (reviving, leveling up, loosing points at the beginning of each day, etc)

**Comment by lefnire** [comment] 2012-12-29 18:30
I think Racer has undergone some major improvements to mitigate this issue, tell me if it's still having issues. Otherwise, my [notes here](https://workflowy.com/shared/a2934319-31af-e1bf-0e51-73c11240b2db/) on the progress.

**Comment by lefnire** [comment] 2013-01-01 23:51
ok, this should be fixed now. if not, reopen

**Comment by demizach** [comment] 2013-02-02 12:24
I'm not sure if this is the same problem, but it seems like it.

When I leveled up to Level 4, my hit points momentarily went to 50/50, but then a few seconds later dropped (I don't remember exactly to what value, as it caught me off guard).  I just leveled up to Level 5.  This time, same thing...hit points momentarily went 50/50, then immediately dropped to 35/50.  What was even weirder though, is that my experience jumped to 70 something/100.

Again, not sure if this is the same problem, or something new.

**Comment by Pandoro** [comment] 2013-02-02 12:27
Do these numbers correspond to the values before leveling up? Or are they
random?

Have you tried refreshing the site? If so what happened then?

**Comment by demizach** [comment] 2013-02-02 12:31
Now that you mention it, those numbers "may" correspond to the previous values before I leveled up.  I've refreshed multiple times, and the numbers remain at the current values (currently 35/50, 78/100...I completed a couple of tasks).

**Comment by Pandoro** [comment] 2013-02-02 13:03
I'll reopen this then, so that @lefnire  can take a look at it.

**Comment by horusofoz** [comment] 2013-02-12 10:11
@demizach Their has been some code pushed so can you advise if this is still an issue at your end?

**Comment by demizach** [comment] 2013-02-12 11:45
It's still being a bit erratic.  I leveled up yesterday, and my HPs stayed at 39/50, which I believe was the level before leveling up.  So, as of yesterday, it would appear that the problem is still occurring.

**Comment by Pandoro** [comment] 2013-02-18 18:54
@demizach I'm really sorry for the continuing frustration on this one :( You haven't been forgotten though! Did it occur again? There have again been major changes, so I am not sure if that might have changed something for you as well?

**Comment by demizach** [comment] 2013-02-19 01:53
Thanks for the follow up.  No worries...fully understand that this is in the "testing" stage, and as such, there will be bugs to be worked out.

Haven't leveled up for a while.  Should level up in a day or two.  Will let you know who it goes.

Cheers!

**Comment by horusofoz** [comment] 2013-02-22 08:57
@demizach How did things go?

**Comment by demizach** [comment] 2013-02-23 03:55
Just leveled up yesterday.  So far, so good.  Nothing wacky going on with hit points.  Only losing points for uncompleted dailies.  Looks like the latest changes did it.  Cheers!

**Comment by unaimed** [comment] 2013-02-23 04:09
I think I am experiencing a related bug. After login, my health drops (as it should, because I have unfinished tasks) by 19 HP.  After you see the animation it "resets" to the value before the substraction; in my case it is 40.
And this phenomenon has now occurred for 2 day in a row .

So I am invincible; but I really don't think it should be this way.

(User ID a404a7b2-e38f-4a57-9735-e6317bf3385e )

edit:
Today everything went back to normal without leveling up. I am happy :+1:

**Comment by PhilipHow** [comment] 2013-03-07 23:45
Closing this for now to clean up the list. Feel free to comment if the bug crops up again!

**Closed as completed by PhilipHow** 2013-03-07 23:45 UTC
