### ISSUE TITLE
To do list - consecutive numbers displayed as "1."

### ISSUE THREAD

**Issue by Naerriel** [HabitRPG/habitica#5656] opened 2015-07-22 16:14 UTC
Every time I create a To Do list and I use numbers to order my actions and number sections, after editing every one of them is displayed as "1".
How does it look like:
![habitrpgbug](https://cloud.githubusercontent.com/assets/13454526/8830554/137860b4-309d-11e5-8bb9-be80573d9977.jpg)
![habitrpgbug2](https://cloud.githubusercontent.com/assets/13454526/8830558/19cc30bc-309d-11e5-8880-c20bbb0ee5f2.jpg)

My browser is Google Chrome, operational system is Windows Vista, and ID is b14c18cc-bd6b-4f09-a0df-04a58e818741.

**Comment by SpenserJ** [comment] 2015-07-22 17:03
This is due to the fact that Markdown is used to format all of the messages. It views `1.` as the start of a list, and turns each of your numbered items into its own list. You can use `1) Task Title` or escape it (`1\. Task Title`) to get the functionality you expect.

There is a wiki article at http://habitrpg.wikia.com/wiki/Markdown_Cheat_Sheet if you want more information on this.

This is a duplicate of #4843.

**Comment by Naerriel** [comment] 2015-07-22 18:21
I see! Sorry for bothering you!
I am very thankful you have told me that.

2015-07-22 19:03 GMT+02:00 Spenser Jones notifications@github.com:

**Comment by SpenserJ** [comment] 2015-07-22 18:30
No problem @Naerriel.

**Closed as completed** 2015-07-22 20:54 UTC
