### ISSUE TITLE
Tooltip is floating

### ISSUE THREAD

**Issue by tjwds** [HabitRPG/habitica#4440] opened 2014-12-29 22:34 UTC
![http://i.imgur.com/xW5szyN.png](http://i.imgur.com/xW5szyN.png)

I have no idea where this CSS is coming from, but it seems to be causing the problem: 

> .popover.top {
> margin-top: -10px;
> }
##

**Comment by crookedneighbor** [comment] 2014-12-29 22:41
Related to #4307 

And I don't think that CSS is the problem. I use the Chrome developer tools to disable it, and it was still floating:

![screen shot 2014-12-29 at 4 39 34 pm](https://cloud.githubusercontent.com/assets/2916945/5573904/77ba9b98-8f79-11e4-9d59-108368428ca4.png)

**Comment by tjwds** [comment] 2014-12-29 22:43
You're right; with that disabled, it looks like the calculated "top" rule is 33 px off.

**Comment by kangabell** [comment] 2015-01-16 23:04
I'm trying to hunt down how the margin is being calculated. It is proving to be somewhat difficult. If anyone has any clues let me know!

**Comment by crookedneighbor** [comment] 2015-01-17 16:08
I believe it's being calculated by the bootstrap plugin that generates the popover.

**Comment by kangabell** [comment] 2015-01-21 22:46
That's what I figured. However, when I tried commenting-out all of the content of popover.js, tooltip.js, jquery.ui.tooltip.js, jquery.ui.tooltip.min.js, along with a ton of other code I thought might potentially be causing the popover, the popovers still mysteriously persist. I don't get it...

**Comment by TheHollidayInn** [comment] 2015-02-21 00:42
Hello,

Do you mind telling me how to recreate the issue? I would like to help debug, but I'm not sure how to get a popover that persists.

**Comment by kangabell** [comment] 2015-02-21 03:54
@keithEz Good question. To replicate, find or create an item (habit, reward, etc.) with "Extra Notes" filled out – something with 200 or so characters – then hover over the item. The tooltip that contains the "Extra Notes" data will float way high up above the item. The excess margin seems to grow with however many lines of text you have. So if the notes are shorter (i.e. only a few words) the placement looks correct, but once you get into longer descriptions it's very out of place.

**Comment by kangabell** [comment] 2015-02-21 04:00
here is an example
![untitled](https://cloud.githubusercontent.com/assets/5122304/6312767/0eef02c0-b954-11e4-9dbc-47cf9a8ae1a0.png)
(note: cursor is over "Earthquake", and the tooltip info is associated with that item, not the one it's directly over)
*sorry this image is huge – dunno what's up with that!

**Comment by TheHollidayInn** [comment] 2015-02-21 22:08
Okay, so I believe I have made some progress.

First of all, when you edit a daily, add notes and then hit save, the tooltip remains a float.

Also, it seems that the tooltip is misplaced for every item in the Rewards section.

Does that sound correct?

**Comment by kangabell** [comment] 2015-02-22 14:57
The tooltip remaining after saving a daily sounds like a separate issue. I believe this issue is specifically for the _placement_ of the tooltip.

As for the Rewards section, the placement depends on the content of the items. Everyone has different content there. But I believe the issue is only for tooltips whose content amounts to more than one line of text. If there is just one line of text it seems fine.

**Comment by TheHollidayInn** [comment] 2015-02-25 03:22
Sounds good. I believe this may have been resolved on the tooltip.js file. Here is a commit: https://github.com/angular-ui/bootstrap/commit/5726e3efae782dc400c39182943b6b33de57bb12 .

I believe this should resolve the issue on a new build. I'm going to rerun on my local server. Is anyone still experiencing this issue?

**Comment by khipkin** [comment] 2016-08-25 15:31
@Alys is this still an issue?

**Comment by Alys** [comment] 2016-08-26 06:45
I'm not sure, but it's low priority and it will be made redundant by the upcoming website improvement project so I'm closing it.

**Closed as completed by Alys** 2016-08-26 06:45 UTC
Labels: priority: minor
