### ISSUE TITLE
Error processing string in notifications

### ISSUE THREAD

**Issue by tartakovsky** [HabitRPG/habitica#4655] opened 2015-02-09 06:30 UTC
Here is the screenshot:
http://take.ms/m4bg1

**Comment by johnball** [comment] 2015-02-09 07:33
I have also experienced this twice today. It has also been reported twice in the Tavern in the past 10 hours. 
Experienced it once with the Fox egg, and once with the Zombie egg. Both times from memory completing Habits.
Was using Firefox 35.0.1 if it helps.

**Comment by negue** [comment] 2015-02-09 07:37
Dont worry it will be fixed soon, you still get your eggs :) - Closing this as duplicate of #4652

**Closed as completed by negue** 2015-02-09 07:37 UTC
