### ISSUE TITLE
Repeat Every X Days Since Last Completed

### ISSUE THREAD

**Issue by anwilli5** [HabitRPG/habitica#6941] opened 2016-03-22 02:05 UTC
In the 'Repeat' section under 'Advanced Options' for a Daily, it'd be great to have an entry called something like 'Every X Days Since Last Completed'.  This should add a Daily that becomes active on the specified 'Start Date' and, upon completion, gets scheduled for X days from the completion date.  It should remain active and count as a missed Daily every day until it is completed.  If it is checked while not active, the Daily should be scheduled for X days from the date of being checked.

Example use cases:
- Cleaning bathrooms once every month
- Replacing your home air filter once every three months
- Getting a free credit check once every four months

There has been a lot of discussion about implementing something like this on the Trello card linked to below, and there isn't a clear consensus about how this and similar features (Ex: repeat every X days, but have the Daily remain active until completed) should be implemented.  The approach described above seems reasonable, though, and is in line with what sites like Todoist do (they have the 'every' keyword tied to repeat every X days and 'every!' which would be the equivalent to this feature.)  Anyway, I wanted to make a ticket for this functionality and post a bounty to encourage someone to implement it unless there are serious reservations about adding this.

https://trello.com/c/q7uM2Ymq/92-dailies-v-3-dailies-minimum-does-not-apply-button-weekly-rolling-over-streak-history

[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=32123883)](https://www.bountysource.com/issues/32123883-repeat-every-x-days-since-last-completed?utm_source=32123883&utm_medium=shield&utm_campaign=ISSUE_BADGE)

**Comment by Alys** [comment] 2016-03-22 09:34
@anwilli5 We actually use github almost exclusively for bugs, rather than feature requests. You can make suggestions through Help > Request a Feature from the Habitica website's menu, which will take you to a Trello card with instructions for where to put your request. In this particular case, you can write it on https://trello.com/c/XuVokK2V/108-repeat-every-days-weekly-monthly but for future requests, the instructions will guide you to the correct card.

**Comment by anwilli5** [comment] 2016-03-22 15:17
@Alys I was trying to mirror was was done with #4173.  Given that the BountySource page seems to tie funding to specific github tickets, is there no way currently to put money behind new feature development (since tickets are only for bugs?)

**Comment by Alys** [comment] 2016-03-22 23:09
I understand now, and thank you for being willing to support our developers! I'm sorry I missed your comment about the bounty when I first read this.

We do use issues for feature requests when a bounty is desired, but in general it's still best to comment in Trello. You can state there that you want to contribute money towards a bounty for your idea and you can ask that an issue be set up for that. If the idea is approved, we'd create an issue or reuse an existing one, if any, and add the Bounty Source plugin to it (an admin needs to do that).

Please note though that our main developers are currently making some wide-ranging changes to the site to improve performance and reliability, and there's a change freeze on any code that would be impacted by those changes. I believe the code required to implement this feature would fall under that freeze, so this probably isn't something that any developer could work on yet.

I've added a note to that trello card (https://trello.com/c/q7uM2Ymq/92-dailies-v-3-dailies-minimum-does-not-apply-button-weekly-rolling-over-streak-history) to state that this issue exists and that a bounty is desired.

I'll check about whether this can be worked on now and if it can be, we'll reopen this and add the plugin. If it can't be done yet, we'll reopen it later (or open a similar issue if it's decided that this isn't quite what's needed - for example, we might open a different issue for this plus some related features).

**Comment by Alys** [comment] 2016-03-22 23:36
It's confirmed that we won't accept work on this issue until version 3 of Habitica's API is released (release date is currently unknown). However we will add the Bounty Source plugin to this issue so that you can put money on it now if you still want to.

**Comment by anwilli5** [comment] 2016-03-23 04:00
@Alys sounds great, thanks!  And from now on I'll be sure to go through Trello for new feature requests

**Comment by Hus274** [comment] 2016-12-13 04:34
Would it be alright if I tried picking this up?

**Comment by TheHollidayInn** [comment] 2016-12-13 14:15
@Hus274 I think that is fine. I'd like to message you about implementation thoughts though. I'll PM you

**Comment by gwenaellarmet** [comment] 2017-04-21 21:15
Is there anyone currently working on this issue ? I'd love to give it a try

**Comment by TheHollidayInn** [comment] 2017-04-22 19:23
@Hus274 Was working on it. Not sure if he is still doing so.

**Comment by Hus274** [comment] 2017-04-22 19:37
Ive has a bunch come up and haven't been able to work in this. Feel free to pick it up

**Comment by librarianmage** [comment] 2017-07-14 21:41
@gwenaellarmet Are you working on this? If not, I'd like to try my hand at it.

**Comment by gwenaellarmet** [comment] 2017-07-16 19:15
@MathWhiz I give it a try but I haven't got a chance to finish this, feel free to give it a try

**Comment by Alys** [comment] 2017-08-26 12:44
@MathWhiz How's your code going for this? Even though another coder has submitted a PR, you can still submit one if you wish. Alternatively if you have any suggestions to make about @asifmallik's PR based on anything you found from working on this issue, you might like to post those.

**Comment by librarianmage** [comment] 2017-08-26 17:05
@Alys While I can't show you any code right now due to being away from a computer and having a broken install, I had some ideas about the implementation that I was working on articulating that I was planning on posting when I get home. Also, I was under the assumption that PRs were closed at the moment, which was why I didn't post a PR yet.

**Comment by librarianmage** [comment] 2017-08-31 05:09
If we are trying to implement use cases like

* Cleaning bathrooms once every month
* Replacing your home air filter once every three months
* Getting a free credit check once every four months

I feel like a better representation would be creating "blocks" of time in which the daily is active until the period passes, after which the damage is dealt. It might not look like a significant change, but it would keep each period the same length and would allow use cases like

* Water plants thrice per week
* Exercise 10 times per month

There could also be a completion display, like how To-Dos with checklists are displayed.

**Comment by SabreCat** [comment] 2017-08-31 18:50
@MathWhiz: Yeah, I think that's a better description of the suggestion here: "X times every Y [intervals]". That said, "X [Intervals] Since Last Completed" could still have its own use cases.

**Comment by librarianmage** [comment] 2017-08-31 18:55
@Sabrecat Would you like me to implement both?

**Comment by SabreCat** [comment] 2017-08-31 20:20
@MathWhiz Sure, if you're feeling like tackling it! There's also "Active Until Completed" as one of my own personal deepest desires :3

**Comment by librarianmage** [comment] 2017-08-31 20:22
@Sabrecat What do you mean?

**Comment by SabreCat** [comment] 2017-08-31 20:28
@MathWhiz Or maybe "Due Until Completed". Suppose I have a bog-standard Daily due every Monday. At present, if I fail to do the Daily, then on Tuesday I will take some damage, but the Daily will no longer be due.

What I'd like to see is an option where if I fail to complete the Daily, it'll do its damage _and then be due again the next day_. It only stops being due once I check it off, at which point it will come due again according to its schedule.

Right now my workaround is to have such Dailies due every day, and if I succeed in checking it off when due, moving the Start Date to the next relevant day.

**Comment by librarianmage** [comment] 2017-09-03 02:30
@SabreCat I spent some time visualizing what each daily version would look like, to make sure I understand what each one would look like. Outlines around the day mean that it is "active", and red scribbles show when damage is applied.

Basic Daily (Repeat 1x a week on Sundays)
===========================
![img_201709022120240](https://user-images.githubusercontent.com/12386291/30000092-4cf59354-9025-11e7-82ea-db107d134131.jpg)

Basic Daily w/ Due Until Completed (Repeat 1x a week on Sundays)
===========================================
![img_201709022120241](https://user-images.githubusercontent.com/12386291/30000094-4cf7f9be-9025-11e7-88d7-cadfb6277484.jpg)

X Intervals since Completion (7 days since completion)
===================================
![img_201709022120242](https://user-images.githubusercontent.com/12386291/30000095-4cf8b07a-9025-11e7-830f-607ea2bcc34d.jpg)

X Intervals since Completion w/ Due Until Completed (7 days since completion)
===================================================
![img_201709022120243](https://user-images.githubusercontent.com/12386291/30000093-4cf7dbb4-9025-11e7-8ded-f2a7e981d696.jpg)

X Times Y Intervals (1 time every week)
=========================
![img_201709022120244](https://user-images.githubusercontent.com/12386291/30000096-4cf94bde-9025-11e7-9f84-4acf84e3d394.jpg)

---

Am I understanding this correctly?

**Comment by SabreCat** [comment] 2017-09-05 16:58
Yes, that is absolutely right, what an awesome visualization XD No doubt someone will come up with a different funky use case that's not covered by the above, but that looks great to me.

**Comment by librarianmage** [comment] 2017-09-05 19:01
@SabreCat Thanks! It's amazing what one can do when they can't sleep XD. Should I hold off on working on this until the redesign comes out?

**Comment by SabreCat** [comment] 2017-09-05 19:49
@MathWhiz Did you build the calendar / take the photo? Or did you paint onto an existing image?

As for timing with the redesign, you can implement the needed server-side logic and tests right away. But building out the UI for selecting the different options should probably wait!

**Comment by librarianmage** [comment] 2017-09-05 22:54
@SabreCat I took a pic of a [LEGO calendar](https://brickset.com/sets/853195-1/Brick-Calendar) set that I use.

Ok! I will start brushing up on how task scheduling is implemented.

**Comment by SabreCat** [comment] 2017-09-06 16:52
Ooh, that might mean we can make use of those on the wiki when this is live... 🤔

**Comment by librarianmage** [comment] 2017-09-06 17:15
@SabreCat Ooh, that's a good idea! If we are able to do that, I can add another image for the "X Times Y intervals" for a larger value of X. I can also clean the images up.

**Comment by librarianmage** [comment] 2017-09-08 17:11
@SabreCat I've been thinking about how to implement these options, and I have a couple thoughts:

### Daily Schema
https://github.com/HabitRPG/habitica/blob/6e70f27bc698d14876fe7e7d0191ddee18e387a2/website/server/models/task.js#L22-L92
https://github.com/HabitRPG/habitica/blob/6e70f27bc698d14876fe7e7d0191ddee18e387a2/website/server/models/task.js#L195-L213
https://github.com/HabitRPG/habitica/blob/6e70f27bc698d14876fe7e7d0191ddee18e387a2/website/server/models/task.js#L224-L250

### Repeat until Completed

* Should it clear checklist every cron, or should that be an option?
* How should `nextDue` work?

### Repeat X Days after Completion

* How should `nextDue` work?

**Comment by SabreCat** [comment] 2017-09-08 19:44
Good questions! 

* Repeat Until Completed checklist: my instinct is to leave checklist items checked until the task is done and rescheduled.
* `nextDue`: I'm not deeply familiar with how that field is used (@vIiRuS can maybe weigh in?), but my immediate expectation is that `nextDue` will be different depending on whether the Daily has been checked off or not. If it's due until completed, and it's not done yet, it'll next be due tomorrow; if it's completed, then it's next due according to its schedule. Days After Completion, we'd return the nextDue according to the schedule regardless, because the schedule will update when I check it off.

**Comment by librarianmage** [comment] 2017-09-08 23:03
@SabreCat `nextDue` is used in the client to help people figure out the next times it will be active, I believe.

**Comment by librarianmage** [comment] 2017-11-07 20:11
@SabreCat How should the bounty be handled on this issue?

**Comment by anwilli5** [comment] 2017-11-21 19:50
The bounty associated with this ticket will automatically be paid out tomorrow - @SabreCat can you confirm that the work has been done and that the bounty should be claimed by @asifmallik?  Thanks!

**Comment by librarianmage** [comment] 2017-11-22 02:37
@anwilli5 It was removed in 3f92317 to allow for more testing.

**Comment by TheHollidayInn** [comment] 2018-01-22 17:03
I believe this is still in progress, just waiting on some cron refactoring from me.

**Comment by beffymaroo** [comment] 2018-05-10 00:06
@TheHollidayInn Is this still in process, or does it need label changes?

**Comment by evantd** [comment] 2018-05-10 01:15
I'm still really excited about it, so I hope it can be included soon.

**Comment by Alys** [comment] 2018-05-10 01:55
I'd still like to remove the special handling for Resting in the Inn from the cron code with the exception of (iirc) just one `if` statement around the normal cron code that we don't want to run when the user is Resting. That would remove the blocker for this change. I definitely agree that the cron code could be refactored to be better, but merging the Resting code back in to the main code won't make it worse overall, and refactoring could be done later when we have more time.
@Staff: Let me know if you're interested in me doing that.

**Comment by TheHollidayInn** [comment] 2018-05-30 21:09
Sounds good. I say that sounds like a good plan.

**Comment by Alys** [comment] 2018-09-09 07:23
I'm working on this now. I'm merging `develop` into @asifmallik's code as I've described at https://github.com/HabitRPG/habitica/pull/8962#issuecomment-419695990

**Comment by evantd** [comment] 2018-09-09 14:58
Awesome, thanks! I'm very excited about this feature.

**Comment by AliNiitsu93** [comment] 2018-12-05 17:43
According to the first requirements. The latest version of Habitica does seem to support repeat by X days, week, month, year. 
So the example cases of:
- Cleaning bathrooms once every month (Implementable)
- Replacing your home air filter once every three months (Implementable)
- Getting a free credit check once every four months  (Implementable)
So this issue should be resolved.

**Comment by librarianmage** [comment] 2018-12-05 17:48
@AliNiitsu93 I would argue that it isn't implemented. As stated directly above the list,

> In the 'Repeat' section under 'Advanced Options' for a Daily, it'd be great to have an entry called something like 'Every X Days Since Last Completed'. This should add a Daily that becomes active on the specified 'Start Date' and, upon completion, gets scheduled for X days from the completion date. It should remain active and count as a missed Daily every day until it is completed. If it is checked while not active, the Daily should be scheduled for X days from the date of being checked.

The examples listed below (the ones you mention) are tasks that would be useful if they only repeated after being completed, instead of appearing on a single day before disappearing.

**Comment by AliNiitsu93** [comment] 2018-12-05 17:53
@MathWhiz thank you. I miss interpreted that.

**Comment by evantd** [comment] 2018-12-05 17:56
The existing support is a fixed schedule. The request is for the next due date to be based on the most recent completion date. This has two main effects. For a task due every 3 days, for example:

* if I was supposed to do it yesterday, it should still be on the list today.
* if I did it early, the due date of the next one should be moved earlier.

This essentially changes the rule from "exactly 3 days between occurrences" (where if you miss it, there's no benefit to doing it the next day) to "at most 3 days between occurrences".

**Comment by Kirska** [comment] 2018-12-09 17:46
I'm actually working on an API tool for this functionality, and started on it before seeing this issue/thread, for my own use.

I've described it as repeating To-Do's (To Do Overs). This seems like the most straightforward way to implement it with the current API/app. Ideally this functionality would be part of the Daily task, as described in detail above, but it is possible with the API, using a To-Do task instead.

I am using this tool for a reminder to clean my pet bird cage, which needs to be done at least once every couple weeks, but it makes no difference what day I do it, and it doesn't need to be done again for another couple weeks from the time I do it.

The basic idea is:
1. Create a To-do with due date 14 days from current date using API tool. 
2. In daily script, tool checks if to-do task was done, and if so create a new to-do with due date 14 days from the current date/the day the task was completed. 
3. Tool also checks if task expired, and if so recreate it.

Anyway it's a work in progress in Django I have here on my profile but may help some of you that would use this functionality.

**Comment by Alys** [comment] 2018-12-11 10:28
Thank you for those details! We're about to start testing [new code](https://github.com/HabitRPG/habitica/pull/10854) for implementing Dailies that repeat based on completion date but if that falls through, the approach you describe might be something we'd look at.

**Comment by citrusella** [comment] 2018-12-11 18:36
For some reason that to-do tool idea mention got me thinking of something I have no ability to implement: Some sort of tool or script that changes the start date of a daily to the next day in the interval you want to complete it after it's done. (Which is really not that different functionally from the planned real "every X days since last completion" thing so there's not much use in trying it right now, but my brain was just like "YOU could try to do it" and I replied "...but I only know CSS"... so enjoy me rambling my incoherent thoughts here XP)

**Comment by kajsa** [comment] 2019-06-07 14:47
This is exactly the feature that got me interested in contributing to Habitica.

**Comment by SunSparc** [comment] 2019-12-02 15:43
It looks like this will probably close when pr #10854 is merged.

**Comment by SabreCat** [comment] 2021-04-30 22:02
As this is a feature request rather than an issue, which we've been trying to avoid tracking in the public GitHub repo for a while, I'm marking this for the staff to review and potentially move to the private repo with its accompanying project board.

**Closed as completed** 2022-05-16 19:25 UTC
Labels: status: issue: suggestion-discussion, priority: medium

**Comment by balboah** [comment] 2024-01-26 09:31
3 years later this seems still not supported, it was the expected behavior for me (repeat X days after **completion**, not fixed days). For example:

## Exercise every 2nd day
- Missed it one day, but now it is **not** listed the next day
- Finished early one day, but now it punishes me the next day if I don't exercise 2 days in a row

For me it makes no sense to have fixed days on any of my dailies :) 

Where can I track this feature request if not github?

**Comment by kendonB** [comment] 2024-12-24 18:44
One workaround for this is to track the item as a positive/negative Habit, mark as negative if you are late completing and positive each time you complete the task. Then, use Ticktick's Repeat -> Custom -> Repeat type: By Completion Date to track the timing. 

This is still not ideal even on the Habitica side as punishing after missing Dailies is the default behavior, whereas the negative habit requires active input from the user.
