### ISSUE TITLE
Habits and Daily tasks dissapearing/going blank

### ISSUE THREAD

**Issue by claudiamp** [HabitRPG/habitica#118] opened 2013-01-18 19:30 UTC
After the page is refresh my habit list and some daily tasks dissapear and a blank slot appears instead.

![habitrpg](https://f.cloud.github.com/assets/3309145/79190/823861e4-61a5-11e2-8baa-00fe4bdf0aec.jpg)

**Comment by BenMilford** [comment] 2013-01-18 22:52
I have the same issue.

**Comment by cehter** [comment] 2013-01-19 13:54
Same issue, but after an server problem and an page refresh. Lost everything  :(

**Comment by timothyCoxon** [comment] 2013-01-19 15:35
Fairly sure I've had a load of habits go missing too.

**Comment by horusofoz** [comment] 2013-01-19 17:17
I had a similar issue resolved under #38. @claudiamp & @GreatAndRandom Can you confirm if after a refresh this issue is still present?

**Comment by BenMilford** [comment] 2013-01-19 17:54
![Capture v5](https://f.cloud.github.com/assets/3310514/80485/2e9fc894-6261-11e2-80b0-d9d9eb0beba9.JPG)
![Capture v4](https://f.cloud.github.com/assets/3310514/80486/2ea085d6-6261-11e2-8db7-81ca8dae6de9.JPG)

Yes.

EDIT: Heh, sorry, they are oddly personal, but whatever.
EDIT: also, I have adblock disabled on the website, but it didn't seem to work.

**Comment by horusofoz** [comment] 2013-01-19 18:07
@GreatAndRandom Ok for the sake of maintaining a persistent instance of your character do not "untick" the takss. For me that wiped out my health on first untick. Killed my chracter on second.

@lefnire Was the fix you implemented under ticket #38 user specific or global as look like you have a recurrence?

**Comment by p1agu3** [comment] 2013-01-19 18:23
This is still occurring.  I don't typically uncheck todos, dailies, or habits, but I had approximately ten habits earlier today, and after browsing away and returning to the page I am now down to two habits.  This has happened once before, about a week ago when the site started to get unstable.

At that time I had made some edits and after a half an hour or so, hit ctrl+F5 (was not showing "offline mode" in top before this) to refresh and about half were gone.

I just want this fixed, so if someone can tell me how to test using some js tools or point me to a tutorial to help, I'd be more than happy to try.  I can't keep recreating habits, I'm going crazy over this.

**Comment by lefnire** [comment] 2013-01-19 18:34
@p1agu3 test using js tools, as in integration-testing? because that would be OH so lovely! see #122. So @GreatAndRandom and @p1agu3 , are you both losing habits now - is that the bug?

@horusofoz I'll start testing untick once I can get some basic #122 in place, I can't replicate it for my own account unfortunately. Ugh... would that I had gotten Reddited/LH'd just a few weeks later. Automated testing was so near on the roadmap.

**Comment by BenMilford** [comment] 2013-01-19 20:23
Yes, I'm losing habits, dailys, to-dos and rewards (ones that I have input myself, such as YouTube.)

**Comment by horusofoz** [comment] 2013-01-20 01:04
@lefnire Note the unticking = death issue was specific to the tasks that didn't disappear or became empty.

**Comment by mfcovington** [comment] 2013-01-20 23:52
@lefnire I also encountered this issue following an `Offline - Reconnect` warning. I had Habits, Dailies, Todos, and Rewards permanently go missing. However, I did not notice any blank placeholders remaining in place of the missing items, nor had I unchecked any Dailies/Todos.

Edit: After messing with adding tasks, refreshing, closing/re-opening browser tabs, etc. I usually have better success retaining items if I close the browser tab and reopen it vs hitting refresh.

Edit2: It's not always the most recent edits that go missing.

**Comment by wc8** [comment] 2013-01-21 14:31
I have this issue (disappeared habits, dailies, and/or todos) also. Today I lost about 5 or 6 cleaning habits after I edited an unrelated habit. 
Edit: I don't have blank placeholders either.

**Comment by lefnire** [comment] 2013-01-21 14:41
see [this comment](https://github.com/lefnire/habitrpg/issues/138#issuecomment-12500268) for what's going on. The (unfortunate) best way to get around this while I tinker is to make sure to refresh before going on an edit spree. So if the site sits idle in your browser for a few hours, once you come back to it and want to play around - do a refresh first, then play

**Comment by BenMilford** [comment] 2013-01-21 22:55
The issue is persisting still. This time the loss was only in the Habit's section. I had a auto refresh extension refreshing the page every two minutes for about an hour, and sometime between that about half the list was cleared. Hopefully I'm just an outlier here. Among the missing Habit's were things from a few days ago and today.

**Comment by wc8** [comment] 2013-01-21 23:01
In the meantime: maybe a reminder at the top of the page to Refresh before Playing (making changes)?
EDIT: This would be helpful with new users, too, who would be likely to be frustrated. 

I haven't had an issue with data loss IF I remember to refresh just before playing and just after (although sometimes it takes a couple of refreshes, as the last couple of times one of two lists was missing after the first refresh and the others appeared to be empty. The second refresh corrected the situation—except when I had forgotten to refresh. 

I, too, have only been losing habits lately.

**Comment by lefnire** [comment] 2013-01-21 23:02
man... i can't believe it's getting this bad, ok - i'm currently writing out the test suite then i'll add the reminder soon as i can

**Comment by Falala** [comment] 2013-01-21 23:07
Just to add to this - as well as entries still disappearing (especially rewards - they all disappeared when I unlocked the store), I now have multiples of two habits that I entered today. They multiplied by 6 each, and I can't delete them without my HP going down, so I'm kinda stuck with them. Just giving you a heads up

**Comment by wc8** [comment] 2013-01-21 23:32
Current backup plan: select all occasionally and save to text file. Thus at least, will be able to re-enter deleted habits. 
I don't appear to be suffering from HP loss on delete or duplication.

There's something amazing about this, because it's working so well for me today even though it's not working. ;-)

**Comment by lefnire** [comment] 2013-01-21 23:35
god i love you guys. any other world and i'd be sewed for this shit :)

**Comment by wc8** [comment] 2013-01-22 00:56
Re: duplicate & blank: I spoke too soon. I just got hit by it in dailies, but I sorted it out, and when all was said and done, I had no duplicates, no HP loss and 2 extra gold. :-)

In case it helps, 
- I added a task "clean B." 
  *\* completed it 
  *\* refreshed 
  *\* I saw "clean B" unchecked, so I checked it off, thinking, _huh, I thought I checked that_. 
  *\* refreshed, "Offline-Reconnect" message appeared briefly during reload.
- Repeat once, only this time thinking, _I *_know*\* I checked that*. 
- Scrolling down, I saw two checked versions of clean B at the bottom of the list in addition to the unchecked one. 
  So I deleted one and refreshed. 
  *\* Two blank, unchecked tasks appeared in place of the unchecked "clean B." and one of the checked "clean B." One of the checked duplicates was successfully deleted. 
  *\* I then deleted the blank tasks and refreshed again. Everything looked okay.
- This time, I refreshed between adding task and checking task complete. Seemed to work ok.

**Comment by horusofoz** [comment] 2013-01-22 04:39
:( Renamed one of my habits then upon refreshing I noticed half of my habits were renamed the same and all history lost :(

**Comment by castor-troy** [comment] 2013-01-22 05:06
Dailies and Todos still missing. I see the same number of entries that I saw yesterday, which I think is not a server disconnection issue. I tried refreshing etc. The same entries which are missing yesterday are still missing now.

**Comment by p1agu3** [comment] 2013-01-22 17:43
After a ctrl+F5 refresh today, I attempted to add a few dailies and some todos back in.  They stuck, at least for a bit.

I just left my desk for about five minutes to drop off some computer parts with a coworker and after hitting F5 to refresh the page again, things reverted to how they looked at approximately 12:00 AM this morning - all entries I made were gone, one of them was "back from the dead" (showing unfinished edits from last night), and some of my dailies were unchecked that I had previously checked earlier today.  I don't believe the gold or experience was removed from their previous award of completion, though.

Very interesting bugs, but I can't even begin to guess at what is happening.  Let me know how else I can continue to help other than further troubleshooting!

**Comment by lefnire** [comment] 2013-01-22 19:09
Hear ye hear ye - everyone, starting today (about an hour ago) I'm _hoping_ this should no longer be a problem. Let's play with this for a day, and I'm crossing my fingers I solved it!

**Comment by wc8** [comment] 2013-01-22 21:21
There's been an improvement, at least. I'll leave my browser open for awhile and see what happens. (Tasks copied to txt file, just in case.)
UPDATE: Seems fine on my end, with the one qualifier that if the "Offline—Reconnect" message is in place changes made before reconnect do not save, but no data loss otherwise. I suppose that is understandable. The chief awkwardness there is that message is not always visible if you have a long list (#100 would address that).

**Comment by p1agu3** [comment] 2013-01-23 18:46
I agree with wc8 - so far, this problem has seemingly been successfully mitigated.  That status message is easy enough to miss, but things are working properly for me otherwise, even if I go somewhat fast.  

_Awesome_ work on this, Tyler!

**Comment by lefnire** [comment] 2013-01-23 18:50
thanks @p1agu3! 
ok everyone, how we doing now? it all comes down to #84

**Comment by wc8** [comment] 2013-01-24 05:04
So far, the same, no loss if online. :+1:

**Comment by mfcovington** [comment] 2013-01-24 06:34
@lefnire Now this is interesting. As of the fix, I haven't lost anything. However, between ~6pm and 10:30pm pacific time, it seems that all(?) my habits/dailies/todos/rewards that had vanished have suddenly returned. I can tell they aren't duplicates, because I didn't name everything the same when I re-entered them. This is much better than losing things and I anticipate that when I delete these zombies, they won't return. Keep up the good work!

Edit: The resurrected items had accrued negative points, so deleting the dailies hurt me a bit.

**Comment by StanLindsey** [comment] 2013-01-24 07:09
I came on to post the exact same thing; All my previously lost items came back - that was a surprise. =D

@lefnire has almost fixed it tooo well. =P

**Comment by lefnire** [comment] 2013-01-24 12:58
woohoo! #198

**Closed as completed by lefnire** 2013-01-24 12:58 UTC
