### ISSUE TITLE
Reward Edits

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#576] opened 2013-03-04 17:18 UTC
I went in to edit some of my rewards today and I can only do one action before it saves and closes. 
Meaning:
Tried to change the name of one of rewards and it will only let me enter one character at a time. 
It really isn't super important- I easily combated this with typing it into something else and copy/pasting it to the reward. It's just a bit annoying.

**Comment by PhilipHow** [comment] 2013-03-04 17:23
Thanks, this is a known problem, we're looking into it. Closing this as it's a duplicate of #553. Feel free to comment if there's anything else, however.

**Closed as completed by PhilipHow** 2013-03-04 17:23 UTC
