### ISSUE TITLE
[API v3] Unchecking Daily with completed checklist only subtracts mana

### ISSUE THREAD

**Issue by quin-jay** [HabitRPG/habitica#7246] opened 2016-05-14 17:11 UTC
General Info
- UUID: 1534a0ee-2f69-4c2e-9659-0d719ac2ea68
- Browser: Chrome 50.0.2661.94 m
- OS: Windows 10
### Description

Steps to replicate:
1. Make a Daily with at least one checklist item
2. Check off all checklist items
3. Check off Daily
4. Uncheck Daily
5. Mana is deducted, but not XP or Gold

Having one but not all checklist items ticked off results in the expected behavior when checking and then unchecking the Daily. Problem only arises after unchecking a complete checklist. I tested it with 1, 2, and 3 checklist items.
#### Console Errors

After refreshing the page and immediately replicating this issue, this is the full console output, including several errors that may or may not be related:

```
app-3552eb76.js:41 Deprecation warning: moment().zone is deprecated, use moment().utcOffset instead. https://github.com/moment/moment/issues/1779
Arguments: 
Error
    at q.zone (https://v3.habitica.com/app-3552eb76.js:41:2721)
    at Object.t.authenticate (https://v3.habitica.com/app-3552eb76.js:44:13223)
    at Object.<anonymous> (https://v3.habitica.com/app-3552eb76.js:44:14350)
    at Object.i [as invoke] (https://v3.habitica.com/app-3552eb76.js:5:16822)
    at Object.c [as $get] (https://v3.habitica.com/app-3552eb76.js:5:15218)
    at Object.i [as invoke] (https://v3.habitica.com/app-3552eb76.js:5:16822)
    at https://v3.habitica.com/app-3552eb76.js:5:14868
    at g (https://v3.habitica.com/app-3552eb76.js:5:16455)
    at Object.i [as invoke] (https://v3.habitica.com/app-3552eb76.js:5:16789)
    at D.instance (https://v3.habitica.com/app-3552eb76.js:6:8436)
app-3552eb76.js:43 GET https://d24n15hnbwhuhn.cloudfront.net/libs/amplitude-2.2.0-min.gz.js net::ERR_BLOCKED_BY_CLIENT(anonymous function) @ app-3552eb76.js:43nrWrapper @ (index):1
www.facebook.com/impression.php/fec85c64e3ee38/?lid=115&payload=%7B%22source%22%3A%22jssdk%22%7D:1 GET https://www.facebook.com/impression.php/fec85c64e3ee38/?lid=115&payload=%7B%22source%22%3A%22jssdk%22%7D net::ERR_BLOCKED_BY_CLIENT
syndication.twitter.com/i/jot?dnt=1&l=%7B%22widget_origin%22%3A%22https%3A%…22%2C%22section%22%3A%22share%22%2C%22action%22%3A%22impression%22%7D%7D:1 GET https://syndication.twitter.com/i/jot?dnt=1&l=%7B%22widget_origin%22%3A%22h…n%22%2C%22section%22%3A%22share%22%2C%22action%22%3A%22impression%22%7D%7D net::ERR_BLOCKED_BY_CLIENT
px.srvcs.tumblr.com/impixu?T=1463245394&J=eyJ0eXBlIjoidXJsIiwidXJsIjoiaHR0c…16e3b29dd547b32ac2a779d73a1f61dfcf7cbcd101e&R=https%3A//v3.habitica.com/:1 GET https://px.srvcs.tumblr.com/impixu?T=1463245394&J=eyJ0eXBlIjoidXJsIiwidXJsI…c216e3b29dd547b32ac2a779d73a1f61dfcf7cbcd101e&R=https%3A//v3.habitica.com/ net::ERR_BLOCKED_BY_CLIENT
rapid-3.36.1.js?_v=403448c…:2 POST https://geo.query.yahoo.com/v1/public/yql?yhlVer=2&yhlClient=rapid&yhlS=119…=1463245439657&yhlClientVer=3.36.1&yhlRnd=9NpzjdCzUY015uJh&yhlCompressed=0 net::ERR_BLOCKED_BY_CLIENTaT @ rapid-3.36.1.js?_v=403448c…:2aV @ rapid-3.36.1.js?_v=403448c…:2aP @ rapid-3.36.1.js?_v=403448c…:2aC @ rapid-3.36.1.js?_v=403448c…:2D.sendRapidNoDelay @ rapid-3.36.1.js?_v=403448c…:2ai @ rapid-3.36.1.js?_v=403448c…:2YAHOO.i13n.Rapid @ rapid-3.36.1.js?_v=403448c…:2(anonymous function) @ button?notes=none&canonicalUrl=https%3A%2F%2Fhabitica.com%2Fstatic%2Ffront&:72(anonymous function) @ button?notes=none&canonicalUrl=https%3A%2F%2Fhabitica.com%2Fstatic%2Ffront&:74
button?notes=none&canonicalUrl=https%3A%2F%2Fhabitica.com%2Fstatic%2Ffront&:93 GET https://secure.assets.tumblr.com/assets/scripts/vendor/cedexis/cedexis.radar.js?_v=7450eec657e34e1e41dac4e1af96a170 net::ERR_BLOCKED_BY_CLIENTa @ button?notes=none&canonicalUrl=https%3A%2F%2Fhabitica.com%2Fstatic%2Ffront&:93
payments.amazon.com/gp/cba/uedata/188-3234745-4687927?ld&v=28&id=VZ73NX6SM8…=0&hob=1&hoe=1&ld=256&t=1463245440588&ctb=1&csmtags=nonredirect|noAmznJQ:1 GET https://payments.amazon.com/gp/cba/uedata/188-3234745-4687927?ld&v=28&id=VZ…rc=0&hob=1&hoe=1&ld=256&t=1463245440588&ctb=1&csmtags=nonredirect|noAmznJQ net::ERR_BLOCKED_BY_CLIENT
fls-na.amazon.com/1/batch/1/OP/AGWSWK15IEJJ7:188-3234745-4687927:VZ73NX6SM8…256%26t%3D1463245440588%26ctb%3D1%26csmtags%3Dnonredirect%7CnoAmznJQ:257:1 GET https://fls-na.amazon.com/1/batch/1/OP/AGWSWK15IEJJ7:188-3234745-4687927:VZ…3D256%26t%3D1463245440588%26ctb%3D1%26csmtags%3Dnonredirect%7CnoAmznJQ:257 net::ERR_BLOCKED_BY_CLIENT
```

**Comment by paglias** [comment] 2016-05-15 19:28
This should be fixed with https://github.com/HabitRPG/habitrpg/commit/52bedc3563f90b089ce5fdb9aad0fe1bb89daf08 that has just been deployed. Reopen if the error persists after reloading the site.

**Comment by paglias** [comment] 2016-05-15 19:29
Ops.. wrong issue!

**Comment by paglias** [comment] 2016-05-15 19:34
Confirmed, no idea where it comes from though

**Comment by Alys** [comment] 2016-05-17 19:55
common/script/ops/scoreTask.js

Mana is handled correctly because it's assigned by _gainMP()

The bug for XP and GP will come from differences between _calculateDelta() and _calculateReverseDelta() and the way they handle checklists. I don't know exactly where but I'm sure I can find it, and I'll look at it later today if no one else gets to it first.

**Comment by crookedneighbor** [comment] 2016-05-17 20:04
I personally don't think this is a blocker. It'll be nice to fix this before release, but I'm fine if this particular behavior doesn't get fixed until after the official release.

**Comment by Alys** [comment] 2016-05-18 14:44
I didn't get time to look at this today but I agree with @crookedneighbor that it's not a blocker. The bug won't be noticed very often, and I'm confident I can fix it when I have a bit of time. Most likely in the next couple of days. Others are still welcome to work on it if they want.

**Comment by Alys** [comment] 2016-05-19 14:54
Ha. Found it. _calculateDelta() was being called with a wrong parameter. It's really, embarrassingly obvious once you know what it is. :) I'll do a PR tomorrow after some testing. Too late at night now.
[EDIT: https://github.com/Alys/habitrpg/commit/9d97738bd9e38f31605285875779e0c00cb29b29 but there'll likely be other edits too]

I've also been doing some refactoring of common/script/ops/scoreTask.js but it doesn't have to go live before API v3 does. When I'm finished, I'll PR it for review off course. I'm mentioning it now in case anyone else was thinking of doing it - don't. :)

**Comment by paglias** [comment] 2016-05-20 09:18
This should be fixed, will go live today

**Closed as completed by paglias** 2016-05-20 09:18 UTC
