### ISSUE TITLE
ServerInternalError when trying to pay with paypal

### ISSUE THREAD

**Issue by CarInAPark** [HabitRPG/habitica#7908] opened 2016-08-17 21:36 UTC
General Info
- UUID: becc59b5-e391-4aab-8947-5170e2e8a6d0
- Browser: Chrome 51.0.2704.103 (64-bit)
- OS: Mac OSX 10.11.4
### Description

I encountered an error when trying to subscribe to Habitica using PayPal. I was prompted to log in (which I did, successfully) and I chose to change the default credit card for payment but when I tried to proceed, all I saw on the screen was the following:
{"success":false,"error":"InternalServerError","message":"An unexpected error occurred."}

I was able to subscribe using the same card in Amazon, but internal server errors are bad, and it's not a great user experience either to print out a json response without a properly formatted error page. Let me know if I need to provide any more details!
#### Console Errors

N/A

**Comment by paglias** [comment] 2016-08-18 20:07
Sorry about this. Unfortunately we cannot find your error in the server logs nor reproduce it. We show an internal server error because Paypal errors are difficult to parse and sometimes we use internal server errors to avoid showing sensitive information. I agree that a nice HTML page would be much better

**Comment by schrodingerskat** [comment] 2016-08-30 17:59
I got the same error yesterday. In my case, the PayPal transaction completed successfully, but returning to Habitica gave me the same Internal Server Error string. I emailed admin@habitica.com with the transaction ID and my user information, and I'm happy to provide more information wherever it's useful.

User ID: cab07e1b-d63b-4b72-bffb-6f6d533de03e
Browser: Google Chrome 52.0.2743.82 (64-bit)
OS: Linux Mint 17.3

**Comment by paglias** [comment] 2016-09-03 09:02
@schrodingerskat thanks for the report. Are you using any ad blocker, incognito window or any other plugin on chrome?

**Comment by schrodingerskat** [comment] 2016-09-05 23:20
@paglias No, none of the above. I have AdBlock Plus installed but disabled on most sites; I just verified that it's not active when I visit either Habitica or PayPal. My only other extensions are LastPass for password management and a Google Scholar bookmarklet, and I wasn't using an incognito window.

**Comment by TheHollidayInn** [comment] 2017-04-19 21:34
I'm pretty sure this is the same error that happened with Stripe account that were cancelled and we were not notified. I'll write a test for this and ensure our webhooks/ipn are working.

**Comment by Alys** [comment] 2017-12-07 05:32
I haven't seen this reported for a while so I'm closing this.

**Closed as completed by Alys** 2017-12-07 05:32 UTC
Labels: priority: important, status: issue: needs investigation
