### ISSUE TITLE
Hide Row of Undiscovered Quest Pets Until One Is Owned

### ISSUE THREAD

**Issue by deilann** [HabitRPG/habitica#3324] opened 2014-04-21 15:34 UTC
So, as we get more and more quest pets, the page is going to start getting _super_ unwieldy. Even worse, if we have limited edition quest pets -- like the eggs -- new players will have a row show up for them, but never get to fill it in. Super huge bummer.

I suggest that for quest pets, if you don't own one of them, you don't get a row stating they exist. This would be pretty simple to do, however, I don't want to do it unless we don't have some consensus. :)

Thoughts?
##

**Comment by k8sullyvan** [comment] 2014-04-22 16:43
I was thinking about this at the beginning of the Egg Hunt. For what it's worth I think that is a great solution to the issue.

Possibly linked to this: The mounts are not organised in the same way that the pets are (which can be annoying sometimes) but that could transfer across easily enough to mounts it they were shuffled around to match

**Comment by thepeopleseason** [comment] 2014-04-22 17:03
+1

**Comment by wildcate** [comment] 2014-09-04 06:48
+1

**Comment by moshner** [comment] 2015-03-06 21:37
I would go even further and recommend that all pets and mounts that have not yet be found be hidden completely. I don't like scrolling on forever to find my few pets that I actually have.

**Comment by nataliechan** [comment] 2015-07-23 02:16
If we do just not show rows if the user doesn't have any of them, does anyone think that'll be confusing for users if they see a Quest Pets heading then nothing underneath? (e.g. no paws at all)

I realize this hasn't been touched in a whileand isn't high priority at all, but I think I"ll take a poke at it at the very least just as a refresher of how git works and how whatever languages are relevant work unless someone else is looking at it.

**Comment by Alys** [comment] 2015-07-23 02:32
@scribblypanda You could well be correct about it being confusing, so perhaps we can include a brief sentence that appears under the Quest Pets heading when no rows are displayed. If that ends up being complicated for a first submission, it could be done in a second stage.

You're welcome to work on this! Comment here if you'd like advice about it, or if you have partially working code, you can submit a pull request and ask for advice in that.

For now, just do this for quest pets and quest mounts. Once we see how that works out, we can consider @moshner's suggestion to do it for non-quest beasts as well.

**Comment by SabreCat** [comment] 2015-07-23 15:23
Perhaps something similar to the Rare Pet golden paw--a single ? pawprint with hover text explaining how to get rolling.

**Comment by scribblypanda** [comment] 2015-07-29 01:54
Does anyone happen to know how to check if a user has a pet or not? I'm currently trying to run an if statement that changes a counter if a pet exists, and I'm not quite sure if `if 'user.items.pets["#{pet}"]'` is doing what I want it to do

**Comment by nataliechan** [comment] 2015-07-29 02:08
Does anyone happen to know how to check if a user has a pet or not? I'm currently trying to run an if statement that changes a counter if a pet exists, and I don't think that
`if 'user.items.pets["#{pet}"]'` 
is doing what I want it to do. 

I'll try to post a PR shortly so my code (not much is changed!) is visible in case it helps. Thanks in advance!

**Comment by SabreCat** [comment] 2015-07-29 17:34
Because we display pets with a status of `false`, you'll want an existence check, not a truthy check. Something more along the lines of `if typeof user.items.pets[pet] !== 'undefined'`

**Comment by crookedneighbor** [comment] 2015-07-29 17:46
@SabreCat see my comment here: https://github.com/HabitRPG/habitrpg/pull/5688#issuecomment-125818873

Chime in if that doesn't make sense to you.

**Comment by lemoness** [comment] 2015-07-29 20:57
A little worried about how this might affect site revenue from
completionists who are buying the quest pet scrolls. What if we showed one
extra row of empty paw prints with a message about Quest Pets to indicate
that there are more?

So if you have no quest pets, it would show the row of empty paw prints; if
you hatch a seahorse, you would have the seahorse row, followed by the row
of empty paw prints; etc. When you have them all, there is no empty row.

**Comment by Alys** [comment] 2015-07-29 21:36
That's a good point about completionists - I should have thought of it myself since I am one.

@scribblypanda If you're not sure how to achieve that, start by getting it working exactly as intended initially (hide all rows for which you don't have any pets), and then we can give advice about adding one empty row.

@lemoness In a future PR, we could perhaps add an illustration of each of the missing pet types (a shadowy base pet or an egg or the quest scroll image).

**Comment by nataliechan** [comment] 2015-07-30 02:32
Thanks @crookedneighbor , @SabreCat for coding input - will try to not forget about MVC type tyings again!

@Alys at this point, I'm trying to just get rows that you don't have any pets for hidden, _then_ figure out how to just do that for quest pets (not normal pets), _then_ I'll come back and see how to go about adding an empty row/whatever ends up being decided on, if that's okay (: There's a reason I picked something that wasn't urgent to work on..

**Comment by Alys** [comment] 2015-07-30 02:49
@scribblypanda That sounds good! You're right that this is a good one to practice on. And you're doing fine; that thing with the lack of access to the user object was far from obvious to a new coder. :)

**Comment by cjprieb** [comment] 2016-07-21 22:30
One suggestion is to have a toggle that allows the user to show/hide the missing pet types. That way users who want to see all the possible spaces can, and others can only view the pets they actually own. And it'd be easy to switch between the two views. 
I only have one pet and it's third from the end of the base pets, so it's a bit annoying to have to scroll to it.

**Comment by wildcate** [comment] 2016-07-21 22:30
Ich bin bis zum 29.07. in der Sommerpause. In dieser Zeit werden keine Bestellungen über den Online-Shop bearbeitet oder versendet, und ich bin nur sehr eingeschränkt über Email oder Telefon zu erreichen. In dringenden Fällen bitte eine SMS an meine Mobilnummer schicken: 0160 9161 4276.

I am on summer break until July 29. Until then, orders via the online shop will not be sent out, and I have limited access to email or phone. If you need me urgently, please send a text message to my mobile phone: +49 160 9161 4276.

**Comment by librarianmage** [comment] 2016-08-25 04:03
Is anyone still working on this?

**Comment by Alys** [comment] 2016-08-25 04:13
This should probably wait for the website redesign, so I'm marking it `wait` but if any other admins disagree, feel free to change it!

**Comment by lemoness** [comment] 2017-10-14 02:01
You can now use the filters on the side of the Stable to hide pets that you don't own (and filter them in many other ways, as well), so I'm closing this issue!

**Closed as completed by lemoness** 2017-10-14 02:01 UTC
Labels: priority: minor, status: issue: on hold
