### ISSUE TITLE
Random Death Problem

### ISSUE THREAD

**Issue by rawbherb** [HabitRPG/habitica#1120] opened 2013-06-02 18:26 UTC
I'm getting so sick of this, to the point where it's making me lose most of my interest in Habit RPG. I've been willing to put up with the numerous bugs because I love the concept of the game so much and I understand it's in beta, but this is getting really hard to deal with. I've been playing for a long time and haven't even reached level 10 once because of how many random "You died!" messages I get whenever I was well above 30 HP the day before. It doesn't make any sense. What's FRUSTRATING about it is that I lose all of the equipment I worked so hard for over the week[s]. If the problem with random, spontaneous deaths can't be fixed then I really urge you to let us keep our equipment after dying. I mean, it makes sense. If you fall in battle then it's likely your equipment might be damaged, but usually not damaged beyond repair. Please consider this, because I really really want to keep playing HabitRPG but it's frustrating to play with this happening.

**Comment by lefnire** [comment] 2013-06-02 18:46
you can set your equipment back via Options > Settings > Restore. We're constantly working on bugs like this, sorry for the frustration and stay tuned, but know we're doing everything we can. Also, dupe of #777 let's follow up there

**Closed as completed by lefnire** 2013-06-02 18:46 UTC
