### ISSUE TITLE
Tasks Get Random Labels Assigned

### ISSUE THREAD

**Issue by vgbandit** [HabitRPG/habitica#7510] opened 2016-05-26 20:27 UTC
General Info
- UUID: df66dbf9-8e2a-45d2-8e26-ce9549a40928
- Browser: Google Chrome
- OS: Mac

Description
When I add new tasks through the website, they've been assigned random labels. Whenever I've tried re-assigning the labels, the labels just stay the same/don't change to what I want them to be.

I've been able to change the labels when I log onto the app on my iPhone.

There was also one task that was not new (it's been on my dailies for a while) that suddenly had all my labels on it.

**Comment by SabreCat** [comment] 2016-05-26 20:47
Duplicate of #7412. Follow our investigations there! There's also a workaround documented there for getting rid of the excess tags.

**Closed as completed by SabreCat** 2016-05-26 20:47 UTC
