### ISSUE TITLE
Multiple CPUs

### ISSUE THREAD

**Issue by OneWhoPondersWhy** [HabitRPG/habitica#1112] opened 2013-05-31 23:01 UTC
When I left my PC at home four hours ago, I was level five and at good health.  When I started up my laptop just now, I was level two at 2 hp.  Nothing rolled over between and I was actually doing rather well habit-ly speaking.

**Comment by lefnire** [comment] 2013-06-04 17:07
duplicate of #635

**Closed as completed by lefnire** 2013-06-04 17:07 UTC
