### ISSUE TITLE
I can't buy a blue sword because I don't have enough gold, but I totally do.

### ISSUE THREAD

**Issue by Corriebird** [HabitRPG/habitica#1341] opened 2013-08-17 15:01 UTC
![habitrpgscreen](https://f.cloud.github.com/assets/5251050/981208/dc5b51f6-074d-11e3-9553-46987ebe3d8a.jpg)

I hope that picture works. If it doesn't, then my screen shows that I have 67 gold. When I click to buy the blue sword, it says I don't have enough GP. 

what the whaat?

**Comment by lefnire** [comment] 2013-08-17 15:11
dupe of https://github.com/lefnire/habitrpg/issues/1330

**Closed as completed by lefnire** 2013-08-17 15:11 UTC
