### ISSUE TITLE
"request entity is too large" when joining a challenge

### ISSUE THREAD

**Issue by Typhlosaurus** [HabitRPG/habitica#5554] opened 2015-07-03 22:24 UTC
On URL https://habitrpg.com/#/options/groups/challenges/b96642a7-8e3b-4587-bfa8-3716b52b29ff I clicked the "Join" button and was given a red alert box telling me that "error request entity is too large" and that if it recurred after a reload I should report the issue.  Tried reloading a few times and re-trying; it happened each time.

Running Chrome 43.0.2357.130  on MacOS Yosemite
In JS console it logs two errors each time:

```

(index):1 POST https://habitrpg.com/api/v2/challenges/b96642a7-8e3b-4587-bfa8-3716b52b29ff/join 500 (Internal Server Error)
nrWrapper @ (index):1
(anonymous function) @ app-fbb62087.js:6
s @ app-fbb62087.js:6
f @ app-fbb62087.js:6
j @ app-fbb62087.js:7
(anonymous function) @ app-fbb62087.js:7
j.$eval @ app-fbb62087.js:7
j.$digest @ app-fbb62087.js:7
j.$apply @ app-fbb62087.js:7
(anonymous function) @ app-fbb62087.js:8
n.event.dispatch @ app-fbb62087.js:2
r.handle @ app-fbb62087.js:2nrWrapper @ (index):1
```

then

```
app-fbb62087.js:29
Object {data: Object, status: 500, config: Object, statusText: "Internal Server Error"}config: Objectcached: falsedata: vheaders: Objectmethod: "POST"transformRequest: Array[1]transformResponse: Array[1]url: "/api/v2/challenges/b96642a7-8e3b-4587-bfa8-3716b52b29ff/join"__proto__: Objectdata: Objecterr: "request entity too large"__proto__: Objectheaders: (c){if(!b)b=sc(a);if(c){var d=b[g(c)];if(d===void 0){d=null}return d}return b}arguments: (...)get arguments: ThrowTypeError() { [native code] }set arguments: ThrowTypeError() { [native code] }caller: (...)get caller: ThrowTypeError() { [native code] }set caller: ThrowTypeError() { [native code] }length: 1name: ""prototype: Object__proto__: Empty() {}<function scope>status: 500statusText: "Internal Server Error"__proto__: ObjectresponseError @ app-fbb62087.js:29j @ app-fbb62087.js:7(anonymous function) @ app-fbb62087.js:7j.$eval @ app-fbb62087.js:7j.$digest @ app-fbb62087.js:7j.$apply @ app-fbb62087.js:7s @ app-fbb62087.js:6w @ app-fbb62087.js:6y @ app-fbb62087.js:6nrWrapper @ (index):1
responseError @ app-fbb62087.js:29
j @ app-fbb62087.js:7
(anonymous function) @ app-fbb62087.js:7
j.$eval @ app-fbb62087.js:7
j.$digest @ app-fbb62087.js:7
j.$apply @ app-fbb62087.js:7
s @ app-fbb62087.js:6
w @ app-fbb62087.js:6
y @ app-fbb62087.js:6
nrWrapper @ (index):1
```

**Comment by Typhlosaurus** [comment] 2015-07-03 22:33
User ID: b6efb4af-937e-4cca-b35e-b673e98aa3b0

**Comment by crookedneighbor** [comment] 2015-07-04 00:05
Usually this error happens when you're part of a group with a large number of challenges. The good news is that it's usually temporary. Try refreshing and let us know if you still get the error.  

We're working on improving this system so this doesn't happen.

**Comment by crookedneighbor** [comment] 2015-07-04 00:06
Closing as a duplicate of #1471. Feel free to follow the progress of the bug by subscribing to that ticket.

**Closed as completed by crookedneighbor** 2015-07-04 00:06 UTC
