### ISSUE TITLE
CastError: Cast to number failed for value "NaN" at path 

### ISSUE THREAD

**Issue by lefnire** [HabitRPG/habitica#2167] opened 2013-12-29 18:59 UTC
Very common error I'm seeing. When I try to replicate on local, it usually only triggers once and then everything's sorted. 

```
CastError: Cast to number failed for value "NaN" at path "quest.progress.hp"
    at SchemaNumber.cast (/app/node_modules/mongoose/lib/schema/number.js:201:9)
    at SchemaNumber.SchemaType.applySetters (/app/node_modules/mongoose/lib/schematype.js:526:17)
    at /app/node_modules/mongoose/lib/document.js:544:18
    at model.Document.$__try (/app/node_modules/mongoose/lib/document.js:757:8)
    at model.Document.set (/app/node_modules/mongoose/lib/document.js:543:24)
    at model.Object.defineProperty.set [as hp] (/app/node_modules/mongoose/lib/document.js:1200:45)
    at Promise.<anonymous> (/app/src/models/group.js:212:29)
    at Promise.<anonymous> (/app/node_modules/mongoose/node_modules/mpromise/lib/promise.js:171:8)
    at Promise.EventEmitter.emit (events.js:95:17)
    at Promise.emit (/app/node_modules/mongoose/node_modules/mpromise/lib/promise.js:88:38)
    at Promise.fulfill (/app/node_modules/mongoose/node_modules/mpromise/lib/promise.js:101:20)
    at /app/node_modules/mongoose/lib/query.js:1386:13
    at model.Document.init (/app/node_modules/mongoose/lib/document.js:250:11)
    at completeOne (/app/node_modules/mongoose/lib/query.js:1384:10)
    at Object.cb (/app/node_modules/mongoose/lib/query.js:1143:11)
    at Object._onImmediate (/app/node_modules/mongoose/node_modules/mquery/lib/utils.js:126:16)
    at processImmediate [as _immediateCallback] (timers.js:330:15)
 ----------------------------
originalUrl: /api/v2/user/batch-update?_v=209&data=1388341282015&siteVersion=1

body: [{}]
```

**Comment by colegleason** [comment] 2014-01-16 21:06
@lefnire How did you reproduce this? I'm having difficulty.

**Comment by paglias** [comment] 2014-01-16 21:46
@lefnire mongoose doesn't show a stack trace for its errors or we're not dealing correctly with them?

It may be https://github.com/HabitRPG/habitrpg/blob/develop/src/controllers/user.js#L422 with body `[{}]` that is not treated as empty?

---

No, it shouldn't be that because we check after for each op not to be empty https://github.com/HabitRPG/habitrpg/blob/develop/src/controllers/user.js#L442, the body in the error report is the body of the request?

**Comment by Alys** [comment] 2015-05-17 22:11
Closing on the assumption this has fixed itself in the past couple of years.

**Closed as completed by Alys** 2015-05-17 22:11 UTC
