### ISSUE TITLE
Grand Gala Seasonal Equipment appears twice after class change if Equipment is pinned to Rewards

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#9352] opened 2017-11-01 02:15 UTC
User report: I was a Warrior and I had pinned all the other-class Grand Gala equipment (Rogue, Healer, Mage) to my rewards column, to remind me to change classes to get it before the end of the month. Today I decided to actually do the change, and I discovered that all of the equipment for my new class (Healer) now appeared in the rewards column twice. Buying one instance of an item from the rewards column seems to make both instances vanish, at least.

**Comment by Alys** [comment] 2018-03-31 07:27
FYI this still happens. The problem is that when Grand Gala gear is available, the gear for your current class is automatically shown in your pinned rewards area (although it is not added to your `pinnedItems` array). Thus if it's been manually added to your `pinnedItems` array, it appears twice.

One possible fix is for the code that automatically shows available Grand Gala gear to look at your pinned items to determine whether it should actually show them. I believe it already looks at your list of owned items, so maybe that code could be used as a basis for this fix. However if a contributor wants to fix it in a different way, feel free. :)

**Comment by Alys** [comment] 2018-12-26 20:59
Just to confirm: This still happens.

**Comment by Alys** [comment] 2020-12-27 07:02
I'm closing this because I accidentally duplicated it at https://github.com/HabitRPG/habitica/issues/12906 but I've put more details into the newer one.

**Closed as completed by Alys** 2020-12-27 07:02 UTC
Labels: priority: medium, help wanted, section: Task Page
