### ISSUE TITLE
hint not updating after buying an item

### ISSUE THREAD

**Issue by martenson** [HabitRPG/habitica#1094] opened 2013-05-30 06:48 UTC
If you buy an item e.g. Buckler it disappears from the Rewards menu and is replaced by another item - Reinforced Shield in this case. But the tooltip "Decreases HP lost by 4%" stays and is replaced with the correct version (5%) after the manual reload.

**Comment by SabreCat** [comment] 2013-06-01 17:46
Duplicate of #1020

**Closed as completed** 2013-06-04 17:06 UTC
