### ISSUE TITLE
Missing sleeping_bed emoji image

### ISSUE THREAD

**Issue by luanmuniz** [HabitRPG/habitica#9128] opened 2017-10-02 23:01 UTC
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found in Settings -> API)
### General Info
  * UUID: 0d8208a5-9485-4a2f-9be9-009d9ed5679f
  * Browser: Google Chrome 61.0.3163.100 (Official Build) (64-bit)
  * OS: macOS 10.12.6 (16G29)

### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)
The sleeping_bed image for the emoji is missing

![screen shot 2017-10-02 at 19 58 06](https://user-images.githubusercontent.com/3428149/31103194-180711f6-a7ac-11e7-8f01-8f1fe222a826.png)

![screen shot 2017-10-02 at 19 59 46](https://user-images.githubusercontent.com/3428149/31103238-4661bad8-a7ac-11e7-96e7-9cb58db59640.png)

![screen shot 2017-10-02 at 19 59 07](https://user-images.githubusercontent.com/3428149/31103220-31255738-a7ac-11e7-8b78-154667c24c16.png)

**Comment by lemoness** [comment] 2017-10-03 05:13
This may be the case for other emojis as well.

**Comment by sheley** [comment] 2017-10-09 07:41
i submitted a "bug report" though the website about this last week, can confirm for other emojis: i have a lot of missing ones on my tasks etc. and then i just got curious and decided to check if there's an issue for it.

**Comment by tim1234ltp** [comment] 2017-10-18 03:42
I have investigated this issue for a bit but I could not know how you get the sleep_bed emoji in the first place. According to [http://habitica.wikia.com/wiki/Emoji](url) , if you use :melior:, emoji could be shown. In the emoji cheatsheet, there is no sleep_bed though.

**Comment by sheley** [comment] 2017-10-18 06:00
the other ones missing for me are:

🗣 `speaking_head`
🥗 `green_salad`
🎙 `studio_microphone`
🍽 `plate_with_cutlery`
 🥄 `spoon`

(edit: hmm I also checked and see that these are all missing from the emoji cheatsheet page..)

interestingly i can see them all fine in the edit screen, but then the emoji disappears in the regular tasks view and the text appears instead

edit view:
<img width="428" alt="screen shot 2017-10-18 at 07 56 14" src="https://user-images.githubusercontent.com/3749305/31702926-49bd2796-b3da-11e7-83a1-3a3e38805807.png">

task view: 
<img width="302" alt="screen shot 2017-10-18 at 07 57 07" src="https://user-images.githubusercontent.com/3749305/31702931-53c4d04a-b3da-11e7-8191-dc3e790064eb.png">

i got to them by using the emoji keyboard (on osx: ctrl + cmd + spacebar)

**Comment by tim1234ltp** [comment] 2017-10-18 06:10
Perhaps this is an issue of Habitica's support for emoji? From I what know, not all emoji icons in the cheatsheet are supported, let alone others outside of the cheatsheet.

**Comment by sheley** [comment] 2017-10-18 06:15
could be.

you can also see that the versions of emojis are different in my two screenshots. In the edit screen it looks like the most recent design of the emojis are being used. but in the task view (the second screenshot), the emoji design is different and i'm guessing an older generation.

Maybe the task view is displaying the older generation of emojis, which don't support the missing emojis i listed above because they're newer than that generation. which is maybe why those emoji are missing from the cheatsheet, which also seems to be outdated.

i'm not really sure how emojis work and how you choose which generation of them to display but maybe that is the fix??

**Comment by sheley** [comment] 2017-10-18 06:17
also to cite my source of where i thought the emojis displayed were the newer versions: https://emojipedia.org/mobile-phone/

<img width="513" alt="screen shot 2017-10-18 at 08 17 06" src="https://user-images.githubusercontent.com/3749305/31703422-c70f8e6c-b3dc-11e7-9976-7b21076d55ca.png">

**Comment by tim1234ltp** [comment] 2017-10-18 06:23
I found a closed issue https://github.com/HabitRPG/habitica/issues/7428 "Unicode emoji not changing to images". It was said to be fixed in the old Habitica. Perhaps it could give you some insights?
This repo is also something worth looking at: https://github.com/HabitRPG/habitica-markdown-emoji

**Comment by Alys** [comment] 2017-10-18 13:20
Here's my understanding of this issue:

There's two types of emoji. One type is specified by using words inside colons, for example `:smile:` - that's the only type that this issue is concerned with. It's supported by Habitica because it can be set up to use the same images on all platforms.

The other type can be specified by using the Apple keyboard, or other keyboards or methods of insertion, and it inserts images directly. Those images tend to vary widely across different platforms. There's no problem with players using that style of emoji in their own tasks but we're not considering them in this issue. We also don't really recommend that they be used in challenges, guild descriptions, etc if you want to be sure of everyone seeing the same image.

Habitica's website code uses the [habitica-markdown](https://github.com/HabitRPG/habitica-markdown) library, which uses the [habitica-markdown-emoji](https://github.com/HabitRPG/habitica-markdown-emoji) library (to specify custom emoji such as `:melior:`), and it in turn uses the third-party [markdown-it-emoji](https://github.com/markdown-it/markdown-it-emoji) library (which implements most standard emoji). So I believe that the lists of supported emoji words can be found at:
- [markdown-it-emoji list](https://github.com/markdown-it/markdown-it-emoji/blob/master/dist/markdown-it-emoji.js) (don't worry that the images there look wrong)
- [habitica-markdown-emoji list](https://github.com/HabitRPG/habitica-markdown-emoji/blob/master/lib/custom-emojis.js)

Within the website's code, when a piece of text needs to support emoji and markdown, that text needs to be parsed by the `habitica-markdown` library. There are places where that isn't being done but that can be handled in different issues than this one (for example, https://github.com/HabitRPG/habitica/issues/9223).

When a piece of text can show some emoji but not all of them, it means that the text is being parsed by the `habitica-markdown` library but one of these problems is happening:
- The missing emoji is not included in either of the above libraries. In this case you'll see that the emoji remains as text like this: `:emoji_word:`. To fix that, someone would need to submit a PR to the [habitica-markdown-emoji](https://github.com/HabitRPG/habitica-markdown-emoji) repository to add the emoji, but you should ask here first to make sure the emoji is suitable for Habitica.
- The emoji is included in one of those libraries but Habitica's image for it doesn't exist in our Amazon AWS bucket. For example, the `:smiley:` emoji works because it has an image in AWS: https://s3.amazonaws.com/habitica-assets/cdn/emoji/smiley.png but the `:sleeping_bed:` emoji doesn't work because the image is unavailable: https://s3.amazonaws.com/habitica-assets/cdn/emoji/sleeping_bed.png -- that's the problem that needs to be fixed.

**Comment by mitten** [comment] 2017-10-24 17:29
I've read through this ticket, and the similar one at [#9223](https://github.com/HabitRPG/habitica/issues/9223), and I think my issue is more like this one.

I am seeing the "missing emoji" problem, but it's a little more complex. When I put certain emojis in on their own, like "unicorn" or "fox face", they do not appear. However, when I put them **directly** next to another emoji, they do appear. If there is a space between the emojis, the problem one does not appear.

So it doesn't seem to be a problem with access to the image in a library - the image is shown properly under certain circumstances, such as in the edit window (but not the task list) and when it's next to another emoji.

Not sure what would cause this now-you-see-it-now-you-don't issue, but I'll add some screenshots to show what I mean.

Screenshot explanations:

In edit screen, with problem emoji at the end of the title:
<img width="190" alt="screen shot 2017-10-24 at 10 04 06" src="https://user-images.githubusercontent.com/153555/31957893-f978cbda-b8a4-11e7-875a-60058ee0aa8d.png">

In task list, with problem emoji at the end of the title:
<img width="262" alt="screen shot 2017-10-24 at 10 04 17" src="https://user-images.githubusercontent.com/153555/31957916-10d092f4-b8a5-11e7-9bf0-d4b393f9b826.png">

In edit screen, with problem emoji directly next to non-problem emoji:
<img width="204" alt="screen shot 2017-10-24 at 10 04 46" src="https://user-images.githubusercontent.com/153555/31957950-248c2ad8-b8a5-11e7-827c-ffc8da0c6221.png">

In task list, with problem emoji directly next to non-problem emoji:
<img width="265" alt="screen shot 2017-10-24 at 10 04 37" src="https://user-images.githubusercontent.com/153555/31957998-448a0c4c-b8a5-11e7-97db-01b224a85e66.png">

In task list, with problem emoji and non-problem emoji separated by a space
<img width="265" alt="screen shot 2017-10-24 at 10 04 57" src="https://user-images.githubusercontent.com/153555/31958115-96930264-b8a5-11e7-8dc7-a9a5fe263ebf.png">

**Comment by kipraske** [comment] 2017-11-14 16:11
To expand on @mitten 's comment. I did some poking around and what seems to be happening is that the markdown-it library only parses chunks of strings at a time. So if you put in an emoji next to some other text, then markdown-it completely ignores the emoji since it thinks it is just part of the word. Thus it is "working" without a space next to it because it never gets transformed into the image tag with the AWS image bucket, you are just seeing the raw unicode character instead. This is also why you can get the two different versions of the emojis in a single app.

If there is a space, the emoji gets transformed into an `<img>` tag which either works because we have the image in AWS or the image fails to load because it doesn't exist so you just see the alt text on the image tag, which also happens to be the same name as the emoji. Similarly using the special emoji escapes like `:bed:` can also result in this broken image tag.

So there are a few ways to fix this, and someone above my pay grade should decide which one they want to implement:

* Fill in the missing images into the AWS store. If slack and trello can have all of the images why not habitica?
* Put the unicode character of the emoji into the alt text. So then when the image fails, you just see the unicode emoji and it looks like it is working. Putting in `token[idx].content` into the alt text inside `index.js` of the habitica-markdown-emoji node_module should do the trick.

Thanks @Alys for pointing me in the right direction. Filling my tasks with a bunch of emoji is important to me for some reason. 👍  🎤 😹  🛌

**Comment by Alys** [comment] 2019-01-01 10:42
Some of the reports here might be caused by this issue: https://github.com/HabitRPG/habitica/issues/10927

**Comment by SabreCat** [comment] 2020-10-30 19:42
Closing this in favor of a holistic emoji ticket, created above.

**Closed as completed by SabreCat** 2020-10-30 19:42 UTC
Labels: priority: minor, help wanted, section: Other

**Comment by evelynhathaway** [comment] 2021-08-23 02:09
I am so thankful for @mitten's comment! If anyone is digging through old Habitica tickets to see if there's an option to just use system emojis and don't want to use two emojis next to each other, just add a zero-width emoji symbol like [`U+E0020`](https://emojipedia.org/tag-space/) next to each one. Though, this would only make sense for dailies and habits since you have to paste it in.
