### ISSUE TITLE
Issues using multiple computers

### ISSUE THREAD

**Issue by Seelge** [HabitRPG/habitica#635] opened 2013-03-11 10:01 UTC
Hello,

I am using multiple computers, but _not_ simultaneously (i.e. work and home) and although I am using the same account, both computers seem to play a character that is only partially connected to the one logged in on the other computer. They have different Levels/HP/XP but they seem to share the same items.

Example: I reached level 6 yesterday on one computer. Today the other computer says I'm in the middle of level 5 and near death although I'm pretty sure I clicked on all dailies on the first computer.

I did delete all cookies and logged back in on both computers multiple times but it didn't help.

**Comment by Seelge** [comment] 2013-03-11 10:05
I just noticed that a daily that I typically tick off on my home computer is deep red on my work computer.

**Comment by Pandoro** [comment] 2013-03-11 13:11
I can confirm that this is happening to me and I think this is the same as  #548 ?

**Comment by Seelge** [comment] 2013-03-11 20:06
It is. I use pinned tabs in Firefox, too. Thanks for the reference.

**Comment by Gr4ssh0pper** [comment] 2013-03-11 20:52
I too run into this issue between my work and home computer. Another thing that can get annoying is I set up my Dailies according to time I wrote in the title. So they are in a specific order according to the time of day it should be completed. It has happened a couple times now that when logging in on a different computer the order of all my habits will get mixed up randomly.

**Comment by jrcoones** [comment] 2013-03-14 14:23
I use this mostly from work. I check in at home very rarely. Last night I checked in at home and went from ~40 HP down to 8 HP. This morning I checked in at work and I'm dead.

**Comment by lefnire** [comment] 2013-04-08 01:02
this is a mystery bugger! I'll keep this on my mind as I go through fixing crits, but I'm not sure yet how to approach this. I'll keep y'all posted

**Comment by rixx** [comment] 2013-04-09 07:34
I think this might also be the same (or related to) #777? I'm experiencing this, too, and I'd be more than happy to help in any way I can.

**Comment by lefnire** [comment] 2013-04-09 21:44
yeah, I'm almost certain #777 & #635 are related. These two are on my forefront.

**Comment by rixx** [comment] 2013-04-10 04:00
Btw, for everyone experiencing this: move your Dailies to normal Habits, and instead of ticking them off, click the + or - in the evening depending on how you did. It isn't nice, but it's a workaround that will not dock HP of its own.

**Comment by NotChrisPlease** [comment] 2013-05-05 06:25
I use two operating systems on one computer and I don't experience this problem,
So it's likely an issue with being connected to two different places not the actual systems themselves.

**Comment by scarmichael** [comment] 2013-05-20 15:26
Just started using Habit on my home iMac with Chrome last night. Logged in using Facebook login.

Got to work (again, OSX on Chrome) and logged in via the same method and while health and XP match up, my Habits/Dailies/To-Dos/Rewards did not sync over. So my disconnect appears to be with tasks and not character.

EDIT: After returning home, looks like what happened is the site just didn't save any of my changes from that first session. So... appears that my issue was different from the one mentioned here.

**Comment by paglias** [comment] 2013-09-09 18:07
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!

**Closed as completed by paglias** 2013-09-09 18:07 UTC

**Comment by Ohaeri** [comment] 2013-12-19 23:31
Hi folks,

I started using the Android app for HabitRPG today, and now all of a sudden my healer is being kicked back repeatedly to level five. :( I'm going to uninstall the app, but it seems like this bug is happening still at least to me.

Running Chrome 31.0.1650.63 m
Was running HabitRPG for Android v. 0.0.13

**Comment by lefnire** [comment] 2014-01-01 00:54
This sounds like https://github.com/HabitRPG/habitrpg/issues/2157 . You need mobile apps versions 0.0.15. iOS is still pending review (they take forever...)

**Comment by ghost** [comment] 2014-05-13 19:49
I set up an account a long time ago from my work computer and forgot about it (the app drove me away before I could get started). I was able to set up a new account with the same name from home yesterday.

I went to sign into my work computer, and it logged me into my older attempt (in which I promptly died). My home pc and iPod is linked fine, but my work PC still shows the old toon and chores. I'll bring my work computer home tonight and see what it does.

**Comment by lefnire** [comment] 2014-05-13 19:52
@shawmutt can you try logging out explicitly on your work computer (gear icon > log out) and logging back in with your new creds?

**Comment by ghost** [comment] 2014-05-13 23:53
I tried that a couple times and it didn't work, but...

now my home computer matches my work computer when I logged in at home.  No biggie, since I just started anyway and just lost my starter sword.  However, my iPhone app is still showing the wrong data.  I tried logging out and back in, restarting, and deleting and reinstalling but it didn't work.

**Comment by deilann** [comment] 2014-05-13 23:56
When you see the wrong account, delete it.

That should fix your problems.

**Comment by ghost** [comment] 2014-05-14 00:27
now I jacked it all up.  I deleted my account and when I try to reregister it's telling me my email address is already used.  The app is still working with the old data.  This obviously isn't the problem talked about in this thread, so I'm going to start a new thread after I search a bit.

Thanks for you help, it's appreciated!

**Comment by deilann** [comment] 2014-05-14 00:30
No you should have deleted the account with the old data, then logged in
again. That should allow you to log into the newer account with the same
credentials. Which account did you delete? You shouldn't need to register
again.

**Comment by ghost** [comment] 2014-05-14 00:46
I started a new thread here:  https://github.com/HabitRPG/habitrpg/issues/3459

I only have one account, the shawmutt one.  For some reason it let me use the same credentials twice.

**Comment by deilann** [comment] 2014-05-14 00:54
You had two accounts with the same.credentials most likely

**Comment by ghost** [comment] 2014-05-14 00:57
yep.  not sure how it happened.  Is there anyone I can email about it?

**Comment by ghost** [comment] 2014-05-14 02:16
oh ffs I'm an idiot.  password AND username is case sensitive...

no bug, all questions answered _facepalm_
