### ISSUE TITLE
Group quests don't working

### ISSUE THREAD

**Issue by fbsr** [HabitRPG/habitica#7574] opened 2016-06-01 11:47 UTC
General Info
- UUID: 95c171f5-ea31-465e-ac41-6e19b17a4786
- Browser: Chrome
- OS: Windows 10
### Description

I join in group boss quest, but not working damage in boss xD.
#### Console Errors

I don't know

**Comment by crookedneighbor** [comment] 2016-06-01 12:02
You were listed in the quest as `null`, which should indicate that the quest was started without you choosing to join in. (`true` would mean you accepted the quest and `false` would mean you rejected it) 

Did you press the accept quest button?

In any case, I've added you to the quest.

**Comment by fbsr** [comment] 2016-06-01 12:14
Really? It's joke? It I accept quest, I'm in quest. The boss appear in quest menu.
This issue not resolved. Wrong closed.

**Comment by Alys** [comment] 2016-06-01 12:20
@fbsr There **was** a problem with your quest but @crookedneighbor has just fixed it for you. You will start doing damage to the boss each morning now.

Tomorrow morning, if you don't see that you've damaged the boss, then comment here again and we'll keep helping you, but based on everything that I and @crookedneighbor can see in your account, the problem is now fixed.

**Comment by crookedneighbor** [comment] 2016-06-01 12:49
@fbsr Sorry, I was rushing when I made my comment. What Alys says is exactly right.

However, in addition, I accidentally removed some properties on your party object. I've restored it from a backup from a few days ago. You may have lost some chat messages in the meantime. If desired, I can download a more backup recent backup and restore the chat messages from there.

I'm sending you 4 gems for the inconvenience.

**Comment by crookedneighbor** [comment] 2016-06-01 17:06
I've restored the chat message that was missing. Everything should be good now. Let me know if you still don't make progress after your next cron.

**Closed as completed by crookedneighbor** 2016-06-01 17:06 UTC

**Comment by fbsr** [comment] 2016-06-02 11:43
Thank you for support, but don't work yet unfortunately. And button of find members and party members show same time now in task page.

**Comment by crookedneighbor** [comment] 2016-06-02 12:39
The memberCount in the group object was set to 1 instead of 2 (likely from restoring the backup I had) which is what caused the button to re-appear. I've corrected it. (note though, that in the future, the button may appear again for parties with less than 4 members. See https://github.com/HabitRPG/habitrpg/pull/6765)

I do see evidence that you caused damage to the boss. Please reload the party page, it should say 

> `Bill attacks The Basi-List for 3.6 damage.` `The Basi-List attacks party for 0.0 damage.`

Not seeing the party chat immediately is an instance of https://github.com/HabitRPG/habitrpg/issues/7407
