### ISSUE TITLE
Day not resetting

### ISSUE THREAD

**Issue by samjam** [HabitRPG/habitica#647] opened 2013-03-13 17:17 UTC
I currently am not getting a reset for my day, despite the fact that it's past my custom day start time. I don't want to unclick the things I did yesterday and not get points, but I don't want to not be able to "redo" things I did yesterday either. Help?

**Comment by lefnire** [comment] 2013-03-13 17:20
can you tell me if there are any javascript errors in chrome console / firebug?

**Comment by horusofoz** [comment] 2013-03-17 14:04
@samjam Following up on the query below, are any javascript errors or is the issue no longer occurring?

**Comment by vizakenjack** [comment] 2013-03-19 21:14
I have same issue, custom day ends in 6 pm, tried to change it to 8, but it didnt help.

No, there are no js errors.

**Comment by wc8** [comment] 2013-06-29 16:53
I just experienced this today. 
I wonder, as a short-term workaround, what if there was an **Emulate Day Start** button in Settings, Danger Zone?

**Comment by wc8** [comment] 2013-06-29 16:57
Follow up: curiously, I changed day start to 1300 and refreshed and the daily tasks seemed to reset (no checkmarks, not grey) but I did not go through the point calculations. It was not yet 1300 hours. (12:53 pm)
I had repeatedly tried refresh before without success.
When I changed back to 300 hours day start, the greys and checkmarks came back. I am puzzled. 
P.S. Reverting to 1300 removed the greys and checkmarks.

**Comment by Sonoris** [comment] 2013-06-29 17:44
wc8 - I tried that as well when I had the issue. I think it doesn't work cuz of how/when the server applies the day start.  I read a better explanation somewhere on here... just, don't sleep in the inn till they reset to unchecked again or you'll have to wait even longer.

**Comment by devarops** [comment] 2013-09-07 22:11
I'm experiencing the same problem. Dailies for today are grayed out (not "active").

**Comment by lefnire** [comment] 2013-09-07 22:25
dupe of #1057, let's followup there

**Closed as completed by lefnire** 2013-09-07 22:25 UTC
Labels: priority: important
