### ISSUE TITLE
Freaking reload when opening the page

### ISSUE THREAD

**Issue by smowden** [HabitRPG/habitica#1306] opened 2013-08-04 16:34 UTC
Hey,
every day I open up habitrpg and start typing a todo which is lost because the page reloads after I manage to type about 20 characters. The text is gone, the field looses focus and if I am extra lucky I hit backspace because I wanted to correct something. Only now it takes me back to the previous item in my browsing history.
I gotta say that is a royal pain in my ass!

**Comment by SabreCat** [comment] 2013-08-04 17:31
I just got an education in this issue when I posted #1304. Root of the problem is discussed toward the end of #840.

The rewrite's coming soon, and thus far performance issues like this appear to be vastly improved. We can revisit this afterward and see if it's an issue anymore.

**Comment by paglias** [comment] 2013-09-09 18:04
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!

**Closed as completed by paglias** 2013-09-09 18:04 UTC
