### ISSUE TITLE
No pet image and unexpected level up

### ISSUE THREAD

**Issue by ooker777** [HabitRPG/habitica#4976] opened 2015-04-04 19:39 UTC
Today I login to my account and all the images of my pets and mounts are disappeared.
![capture1](https://cloud.githubusercontent.com/assets/6695517/6994266/1009854e-db3d-11e4-889d-08f170ded41c.PNG)

And I level up unexpectedly. I hadn't login to check my tasks for two days and didn't rest in the inn. There is one API plugin (AnkiHRPG) but I didn't use it on those days too. In theory I should die, not level up, right?

My user ID: _d0d2b675-2a55-4e18-bc53-410e04a2e437_

**Comment by crookedneighbor** [comment] 2015-04-04 21:42
Re: Invisible pets- That's very strange. As a first step could you refresh the page? If they're still invisible, could you clear your browser's cache? If you're unsure how to do that, try googling for how to do it for your particular browser.

Re: Unexpected level up- We changed the behavior recently, so you'd only get penalized for one days worth of missing dailies, no matter how long you were absent from the site, so unless you have a massive number of dailies, I wouldn't expect it to kill you right off. As for where the extra experience came from, not sure. It's possible that the 3rd party add-on you mentioned prompted sent a call to give your avatar some extra experience, and it just didn't get synced from the server until you logged in. Ultimately, I wouldn't worry about it right now.

**Comment by Alys** [comment] 2015-04-04 21:50
@ooker777 We had another report of invisible pets yesterday. The pets reappeared by themselves after a day or two. I did think at the time that it was just an odd and aggressive caching issue but since it's happened to you too it might be something more. We'll look into it. For your case, it is likely that the pets will reappear. If they haven't in two days, please report here again.

For the level up, did your party finish a quest recently? That can give you enough XP to level up.

**Comment by ooker777** [comment] 2015-04-04 22:50
Thanks everyone for helping me. The pets have come back again, I didn't clear any cache.

I host a solo party, so all the experience I get must come from me. If I don't complete any task, there should be no experience gained. And I can make sure that 3rd party addon can't give me any experience these days,

**Comment by berriganator** [comment] 2015-05-11 09:40
Hello. For the past few days, I have also had issues of disappearing pets. Also disappearing mounts, headless mounts, mounts with only a head and no body, missing equipment, etc. Anything that is inventory-related. Sometimes refreshing brings them back, sometimes it doesn't. Sometimes everything is back—and then something disappears again. It does seem consistent to the inventory item, however. When the pets are gone in the avatar image, they are also gone in the inventory. Thanks!

**Comment by Alys** [comment] 2015-08-15 12:01
The pets disappearing temporarily would have been caused by caching/loading issues stopping certain images being seen. These things are always temporary and we haven't seen any reports recently so I'm closing this issue.

**Closed as completed by Alys** 2015-08-15 12:01 UTC
