### ISSUE TITLE
Habitrpg doesn't work with firefox "remember password"

### ISSUE THREAD

**Issue by jepler** [HabitRPG/habitica#829] opened 2013-04-17 02:13 UTC
This affects at least FF20.0 on Linux.

The first time, the browser prompts to remember the password, but the next time the login dialog is shown the remembered password isn't inserted.

**Comment by pjf** [comment] 2013-04-24 00:49
I can reproduce this.

What's interesting is that password remembering used to work, but doesn't now.

**Comment by paglias** [comment] 2013-09-09 16:00
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!

**Closed as completed by paglias** 2013-09-09 16:00 UTC
Labels: priority: minor

**Comment by hkopp** [comment] 2018-12-31 12:15
I have a similar issue on FF 63.
The browser never prompts me to remember the password.

Best regards and happy new year
