### ISSUE TITLE
Tag list in tasks starts collapsed option setting is inverted

### ISSUE THREAD

**Issue by cTheDragons** [HabitRPG/habitica#7388] opened 2016-05-21 03:59 UTC
### General Info
- bc10ec41-4213-4482-bbb8-558e3c3ea8d5
- Opera 37.0.2178.43
- Windows 8.1 32-bit
### Description

When setting _Open new tasks in edit mode_ is ticked.

Setting _Tag list in tasks starts collapsed_ option to ticked (on) when you go and create a task the tag list in the task is not collapsed but shows all the tags.

Setting _Tag list in tasks starts collapsed_ option to not ticked (off) when you go and create a task the tag list is collapsed.

**Comment by Alys** [comment] 2016-05-21 04:07
Confirmed. Thanks @cTheDragons ! Good catch.

However I'm removing the API v3 label from the title because we won't fix this until after the migration is over, and I want to clear it out of the list of issues and PRs we need to look through today. Feel free to report more bugs though if you want to keep testing! If you do, put the v3 tag on them as you have been doing, and we'll remove it if it's not something we can get to today.

**Comment by librarianmage** [comment] 2016-05-29 19:56
I can work on this!

**Comment by Alys** [comment] 2016-05-29 22:32
@MathWhiz Please do!

**Closed as completed** 2016-05-30 20:09 UTC
Labels: priority: minor, help wanted
