### ISSUE TITLE
New items are duplicated in the dailies or todo list

### ISSUE THREAD

**Issue by Gmk1212** [HabitRPG/habitica#894] opened 2013-05-05 07:20 UTC
If I create a new item in the Todo list, it is also created in the dailies list, or vice versa. If I create them in the todo list, it sometimes puts both items into the todo list, and sometimes not.

If the item was created in the todo list and I delete the duplicate, it deletes both items.

If the item was created in the dailies list, it deletes the duplicate and leaves behind an empty frame in the dailies list with a white background.

![dupes](https://f.cloud.github.com/assets/4319103/463360/2e276e54-b553-11e2-8288-86df4489004c.jpg)

![dupes2](https://f.cloud.github.com/assets/4319103/463363/82157754-b553-11e2-91e1-8611582ab80f.jpg)

![dupes3](https://f.cloud.github.com/assets/4319103/463372/0dae2478-b554-11e2-8e7b-3429c95c2847.jpg)

**Comment by rcoural** [comment] 2013-05-05 07:32
I have the same problem + between Habits and Dailies.

**Comment by heyimzsa** [comment] 2013-05-05 08:10
Same here.

It's also mentioned in #891

**Comment by kirill-fedyanin** [comment] 2013-05-05 08:11
Same + sometimes dupliсation performs as renaming item that was created before

**Comment by lefnire** [comment] 2013-05-05 09:19
dupe of #891, follow there

**Closed as completed by lefnire** 2013-05-05 09:19 UTC
