### ISSUE TITLE
Experience is 201/200, no level up

### ISSUE THREAD

**Issue by Hudelf** [HabitRPG/habitica#6186] opened 2015-11-05 16:19 UTC
![habitica level up bug](https://cloud.githubusercontent.com/assets/15674430/10974190/d94f34ca-83ae-11e5-9a2c-36b1efdb9fa1.JPG)

This fixed itself after getting more experience, but was a bit odd. I had the same experience through the Android app. I may have received the final bit of experience by completing a task through the app, I can't remember for sure, if that makes any difference.

**Comment by SabreCat** [comment] 2015-11-05 16:56
Duplicate of #2433, I believe. Though if the gauge went that high by some other method than mentioned there, let us know!

**Closed as completed by SabreCat** 2015-11-05 16:56 UTC
