### ISSUE TITLE
Max-width on "Additional Notes" in task card

### ISSUE THREAD

**Issue by 105th** [HabitRPG/habitica#6967] opened 2016-03-26 14:45 UTC
General Info
- UUID: a402c4dd-1f0d-44c8-a403-f86ce5046c39
- Browser: Yandex Browser 16.3.0.6920 beta (64-bit)
- OS: OS X El Capitan 10.11.3
### Description

This is normal condition.

![image](https://cloud.githubusercontent.com/assets/11395678/14060568/ef16fe6a-f379-11e5-9301-4fee18101f13.png)

But if i resize this window, it becomes very large.

![image](https://cloud.githubusercontent.com/assets/11395678/14060573/2ab817c4-f37a-11e5-8122-8c85e683663e.png)

I think here it is possible to add a property "max-width" to class ".form-control"

![image](https://cloud.githubusercontent.com/assets/11395678/14060582/68979cea-f37a-11e5-94f0-a95a485f92d1.png)
#### Console Errors

![image](https://cloud.githubusercontent.com/assets/11395678/14060560/9649b624-f379-11e5-8237-a80327e0c8ad.png)

**Comment by crookedneighbor** [comment] 2016-03-26 15:03
Can't reproduce in Chrome. Does the same behavior happen in other browsers?

Adding `max-width: 100%` shouldn't change anything, as the `width` attribute is already set to `100%`.

**Comment by citrusella** [comment] 2016-03-26 20:07
I can reproduce by dragging the corner in Firefox 45.0.1 on Windows 7.

**Comment by crookedneighbor** [comment] 2016-03-26 20:19
Oh, you're saying dragging the corner of the textarea, not the corner of the window. I misunderstood. 

That would be fixed by using the resize property: https://davidwalsh.name/textarea-resize

**Comment by Alys** [comment] 2016-03-26 21:37
I see this very much as a feature not a bug. The purpose of textarea corner dragging is to let the user make the textarea temporarily larger so that they have more space to view the text. It's fully under the control of the user - if they want it wider than the column, they can do that, if they don't, they can avoid dragging it too far sideways.

I think the only thing that needs to be fixed is that if you drag it far enough that the right-hand side of the textarea goes past the edge of the next column, then it actually goes under the column, whereas it should go above.

However this might be something best looked at during an upcoming UI improvement project.

**Comment by 105th** [comment] 2016-03-28 08:04
@crookedneighbor Yep, i mean corner of the textarea.
@Alys I think, nobody wants to drag this area to the right-left, because it's just inconvenient. Or, you can allow them to change the size just inside the card unit (10-15 pixels), but not the entire screen.

**Comment by Alys** [comment] 2016-03-28 08:14
@105th It's certainly inconvenient to drag right-left at the moment because that causes it to go under the next column. If we change the CSS so that the text area remains above the columns, it could be very convenient for some notes to be dragged out to a larger width. 

Some of my tasks have long notes, and a wide view would definitely make them more readable (at the moment, I copy-paste the notes to a temporary text file when I want to edit them in a larger window, which is not ideal). I don't think we can say that nobody will want to drag them right-left. :)

If we fix this before the UI project, I'd like the fix to be to z-index rather than max-width.

**Comment by librarianmage** [comment] 2016-03-29 03:21
If this will be done before the UI project, I can try my hand at this!

**Comment by SabreCat** [comment] 2016-03-29 16:10
I don't think there's any harm in fixing this up now! A UI overhaul is a couple months out at the earliest. Assuming e.g. @MathWhiz isn't sad if the fix does become moot later this year, heh.

**Comment by librarianmage** [comment] 2016-03-29 17:29
I would not mind in the least!

**Closed as completed** 2016-04-05 13:56 UTC

**Comment by librarianmage** [comment] 2016-04-05 23:23
@crookedneighbor This should probably stay open, because I just realized: it might also cause the textarea to cover the username selector

**Comment by crookedneighbor** [comment] 2016-04-06 00:15
I don't know what you're talking about. Can you clarify or post a screenshot?

**Comment by librarianmage** [comment] 2016-04-06 00:42
The "username selector" when you type @… appears underneath the textarea in
the Party and Tavern screens

**Comment by Alys** [comment] 2016-04-06 00:46
@MathWhiz Can you please log that as a new issue?

**Comment by librarianmage** [comment] 2016-04-06 00:58
Sure!

**Comment by crookedneighbor** [comment] 2016-04-06 01:06
I'll scope the change to just the task boxes. Fixing now.

**Comment by crookedneighbor** [comment] 2016-04-06 01:10
Fixed in https://github.com/HabitRPG/habitrpg/commit/ae14d405cb355f7419fa90466e36e518a92506a6
