### ISSUE TITLE
Potential memory leaks

### ISSUE THREAD

**Issue by jsachs** [HabitRPG/habitica#8710] opened 2017-04-29 23:00 UTC
As part of a university project, I ran static memory leak detection on the Habitica app. One area that was flagged for potential memory leaks was the `InAppMessageManager` class, which is part of the `seeds-sdk`. This class uses a large number of anonymous classes to perform background tasks, such as [this `Thread`](https://github.com/therealseeds/seeds-sdk-android/blob/master/sdk/src/main/java/com/playseeds/android/sdk/inappmessaging/InAppMessageManager.java#L152). When a background task is defined this way, it can retain a reference to the parent `Activity` while it continues to execute, using memory. The problem can be corrected as described [here](http://blog.nimbledroid.com/2016/09/06/stop-memory-leaks.html).

I recognize that `seeds` is not your library, but given the relative number of project stars, it seems appropriate to report the issue here.

**Comment by TheHollidayInn** [comment] 2017-04-30 05:30
Good find. I think this should be moved to our Android repo. We do use a leak detection for development as well. I believe it is called LeakCanary.

**Comment by jsachs** [comment] 2017-04-30 13:16
Part of our project was actually comparing static analysis tools to LeakCanary (which is a great tool). The library that we used is called [Infer](http://fbinfer.com/). We developed some additional checkers to find anonymous class leaks and static `View` leaks, which are [here](https://github.com/jsachs/infer).

**Comment by paglias** [comment] 2017-04-30 14:39
@jsachs thanks for the report but I'm closing the issue since the problem is better reported in the Android App repository at https://github.com/HabitRPG/habitica-android

**Closed as completed by paglias** 2017-04-30 14:39 UTC
