### ISSUE TITLE
Grand gala & Seasonal shop items missing after rebirth

### ISSUE THREAD

**Issue by Joerle** [HabitRPG/habitica#7898] opened 2016-08-13 19:45 UTC
I recently rebirthed my character, and read through the warning about equipment being removed and put in the rewards box for re-purchase.
However, I must have missed the part about seasonal items! (if it was there) I have NO seasonal equipment available for repurchase, even though I bought some cross-class items with gems! Please let me know if this is a mistake, or working as intended.

name: Joerle
id:  2d4d5ee9-d798-4a8d-be1c-1121625d2edc

**Comment by Joerle** [comment] 2016-08-13 19:55
May be related to #6724 (if so, sorry for the duplicate)
https://github.com/HabitRPG/habitrpg/issues/6724

**Comment by Alys** [comment] 2016-08-13 20:23
@Joerle It is intentional that all equipment is removed by the Orb of Rebirth, except equipment that has a zero gold cost - that's what's referred to by the Orb's description where it says "You have no Experience, Gold, or Equipment (with the exception of free items like Mystery items)."

The Orb takes you back to a state very similar to that of a new user, which means that equipment from other classes is not available to you. That's what it's getting at when it says "Limited edition equipment you've purchased can be repurchased, even if its event has ended. To repurchase class-specific equipment, you must first change to the correct class." Please tell us if you have suggestions for making that clearer!

Our intention for how the Orb will be changed in future is described in https://github.com/HabitRPG/habitrpg/issues/5750#issuecomment-166851875 so I'm closing this issue now, however you can still comment here and we'll see it. If you tell us which equipment pieces you purchased with gems, we will put them back on your equipment page.

We have a guild now for telling us about bugs, which you might find more convenient, and which often helps us because we can see information about your Habitica account immediately. You can access it from the website's menu at Help > [Report a Bug](https://habitica.com/#/options/groups/guilds/a29da26b-37de-4a71-b0c6-48e72a900dac). It's recommended that bugs be posted there first and if a GitHub issue is needed, we'll let you know.

**Comment by crookedneighbor** [comment] 2016-08-13 20:24
It is currently working as intended. You can repurchase the gear by switching to that class. We may change the behavior in the future (as mentioned in the issue you posted), but for now it is working as it should.

**Closed as completed by Alys** 2016-08-13 20:23 UTC

**Comment by Joerle** [comment] 2016-08-13 21:53
Thanks @Alys 
I was a mage previously, so I won't mention that equipment... The ones I purchased with gems is as follows:
Icicle Drake set (Rogue, Winter Wonderland 2014/2015)
Bloodred Set (Rogue, Fall Festival 2014)

As for suggestions on making it clearer... I'll see if I can find a full transcript and take a look... I think a note about seasonal/class equipment appearing after a class change would be helpful, as well as something about gem-purchased equipment.

EDIT: Oh, I see there is a copy of the text on the link you included :)

**Comment by Alys** [comment] 2016-08-21 04:15
@Joerle Sorry about the delay! I've given you back the Rogue gear. Tell me if any is still  missing (Data > Data Display Tool will tell you definitively). 

FYI, Rebirth will be changed as described here: https://github.com/HabitRPG/habitrpg/issues/7917

**Comment by Joerle** [comment] 2016-09-03 23:53
Thanks @Alys, I have those items again!
I've only just returned from the other coast, so no worries re: the delay.
