### ISSUE TITLE
 Lunar Battle quests and the Feral Dust Bunnies quest have incorrect unlock conditions

### ISSUE THREAD

**Issue by TheHollidayInn** [HabitRPG/habitica#8329] opened 2016-12-28 19:34 UTC
### Description

As reported in the Report a Bug Guild:

> Lunar Battle quests and the Feral Dust Bunnies quest say that they're unlocked by inviting friends, even though they're unlocked through the check-in incentive

Here is the start of the code that needs to be changed. 
https://github.com/HabitRPG/habitica/blob/develop/website/common/script/content/index.js#L2655

#### Console Errors
[//]: # (Include any JavaScript console errors here.)

**Comment by SabreCat** [comment] 2016-12-28 19:40
The Web site has special handling to display the check-in count instead of "invite friends," but the mobile apps still display only "invite friends". The user reporting the issue is probably on mobile.

Two things to do for the fix, in order:

1. Update the mobile apps to handle a new unlock condition, "check-in incentive".
2. Update the content file to have "check-in incentive" instead of "invite friends" for the unlock condition on these quests.

We could also have a "create account" unlock condition for the Feral Dust Bunnies, because it doesn't so much come with a check-in as that it's given to you by default.

**Comment by SabreCat** [comment] 2017-07-24 20:07
This got duplicated in #8863 and a bunch of discussion happened there. Normally I'd close the newer dupe, but since there's more detail in that ticket, I'm closing this one instead. Sorry @TheHollidayInn!

**Closed as completed by SabreCat** 2017-07-24 20:07 UTC
