### ISSUE TITLE
Damage to Boss Not Showing Up/Damage Not Resetting

### ISSUE THREAD

**Issue by PendragnJenna** [HabitRPG/habitica#8097] opened 2016-10-04 13:55 UTC
General Info
- UUID: e77d6c97-8850-4f31-bd46-c412243d6035
- Browser: Safari
- OS: MacOS (Sierra)
### Description

Some members of my party (09d91c4f-c632-4bd4-b39f-d10295a4777f), including myself, are not consistently seeing their damage to the boss show up. Today, for example, I'm showing 62.4 points of damage accrued from yesterday (according to the compass-like icon in the top right corner of the screen), but it's not being "applied" to the party/boss. Others in the party have noted that they checked off a bunch of dailies and to-do's but didn't get credited for them the next morning.

**Comment by khipkin** [comment] 2016-10-04 15:10
@PendragnJenna Did any of you get damage messages in the party chat?

**Comment by khipkin** [comment] 2016-10-04 15:13
Admins: This is either a duplicate of #7727 or #7909, depending on whether or not boss damage messages showed up in the party chat.

**Comment by PendragnJenna** [comment] 2016-10-04 15:16
No, we didn't. That's how we noticed there was a problem. A couple people in the party had been questioning for the past couple weeks why their damage didn't show up occasionally, but we hadn't thought it was a huge deal. It happened to a couple of us today, though, and I thought to look at the compass icon and saw that my damage points seemed to be accruing from yesterday--and is continuing to grow today--but not getting applied to the boss/party.

**Comment by PendragnJenna** [comment] 2016-10-04 15:25
Khipkin: Sorry for the duplication. We've seen behaviors from both https://github.com/HabitRPG/habitica/issues/7727 and https://github.com/HabitRPG/habitica/issues/7909 in our party. Sometimes a member will report that they didn't have anything at all show up in the chat feed and other times it'll show they did 0.0 damage even though they checked off all their dailies and did a bunch of to-do's/habits. We've also noticed there are days when one of us will have checked off a bunch of to-do's but only show minimal damage, as if not all our completions are getting tallied. But we haven't found any consistent pattern, so we'd just been writing it off as a fluke and didn't think to report it until today.

**Comment by khipkin** [comment] 2016-10-04 23:28
@Alys ?

**Comment by Alys** [comment] 2016-10-05 00:29
I was asleep when this was logged and am now getting ready for work. I'll look at it when I have free time but it won't be for several hours.

**Comment by Alys** [comment] 2016-10-05 11:12
@PendragnJenna I'm going to close this since we're tracking it in the two issues @khipkin mentioned, and automatic links have been created from those issues to this one so that we can refer back to this one easily when we need to.

When you or your party mates notice something like this happening, can the person it happens to please post to the Report a Bug guild? You can get to it from Help > Report a Bug on the website or Guilds > Report a Bug on the app. If I can get an individual, specific description of each problem shortly after it happens from the person it happened to, I can help to restore lost damage in some cases and we can track the frequency of the problem. However there's probably not a great deal we can do for now, until we've worked out why it's happening and how to stop it. It might be just problems from the server being overloaded.

**Closed as completed by Alys** 2016-10-05 11:12 UTC
