### ISSUE TITLE
Constant desync

### ISSUE THREAD

**Issue by asktree** [HabitRPG/habitica#10581] opened 2018-08-08 14:33 UTC
I find that I run into desync very often on both the web and mobile app, using the official server (haven't tried a self-hosted). This is especially bad when trying to re-order tasks. Is this a known issue? What accounts for it?

**Comment by TheHollidayInn** [comment] 2018-08-09 13:28
Hey, @asktree. Can you give more details on what is desyncing? Do you have screenshots/video or a way to reproduce?

**Comment by asktree** [comment] 2018-08-09 19:24
I've found a wiki article about them.

http://habitica.wikia.com/wiki/Sync_Errors

Obviously live synchronization with a server is a task that many online applications perform, usually without a hitch. I'm not an expert on the topic but it doesn't seem like Habitica should face any special challenges that other platforms wouldn't.

**Comment by paglias** [comment] 2018-08-09 20:02
@asktree can you post your Habitica UUID? You can find it under Settings -> API

**Comment by asktree** [comment] 2018-08-09 20:51
@paglias 9ed86aed-d1a0-4618-b5eb-d64d1190b915

**Comment by TheHollidayInn** [comment] 2018-08-09 20:57
Sync errors can occur under different circumstances. We've improved much since that article was first written, but there are some common things that other companies also run into as well as the fact that we can always improve.

Now that's generic :P, but to continue with helping you:

Are you seeing this error: `NotAuthorized: Your session is outdated. Please refresh or sync.` and is that what you are referencing?

**Comment by asktree** [comment] 2018-08-09 21:26
No, I'm not getting that error. The phenomenon I'm mainly referring to sometimes* occurs when I try to re-order tasks. When the page syncs, the tasks will not be how I ordered them; they may not have moved at all, or they may have moved to the wrong place, or sometimes even a task somewhere else in my list will have moved. This happens even if I'm only doing one move. 

I tried to reproduce it with some new tasks, but strangely I couldn't. So, as of writing, I've failed to reproduce. 

Slow/wonky syncing seems to pervade interaction with the site so I figured it was well known enough to make a broad issue without much specific detail.  To give another example, sometimes I might click on a task and it will no longer be completed after syncing, and I'll get a notification saying I lost health and HP, and I'll have to click again. Also, if I change my equipment, I have to reload the page in order for it to update. I just assumed that there was some underlying architectural reason that things might not sync as cleanly as in other softwares.

**Comment by TheHollidayInn** [comment] 2018-08-09 21:42
The task reordering sounds like this issue: https://github.com/HabitRPG/habitica/issues/8500. We are having trouble reproducing - as you are now. We would love for any insight in to this. So if it continues to happen and you can help us debug, that would be great.

There isn't a general architectural issue. Those are specific problems we'd like to address.

- for the task click, this is something we've been improving as well. We've improved lag with scoring task which causes this, but sometimes it can still happen. Without getting technical, we are working on speed improvements in this area that should prevent it for certain types of users. But if you can recreate this issue/it happens to you a lot, that would help us debug anything we are missing.

- For the equip not happening on refresh. @negue are you aware of this? I'm not seeing an existing issue, so we should add one/fix this.

**Comment by Alys** [comment] 2018-08-09 22:34
Because there's a few unrelated issues reported here, I'm going to break the conversation out now into separate issues so that we can more easily track each one.

@asktree I've copied your comment about task sorting here: https://github.com/HabitRPG/habitica/issues/8500#issuecomment-411917888
If you have any additional information, as @TheHollidayInn says we'd love to hear it so please comment on that issue.

I've copied your equipment change issue here: https://github.com/HabitRPG/habitica/issues/10586
@negue I've also put @TheHollidayInn's question to you there, so if you could respond there, that will keep it all in one place.

@asktree If you have anything else to report about the task click, probably best for now to post it here in this issue and we'll create a new issue for it if needed. I'm closing this one but we'll still get notifications if you do add more about the task click problem.

For any other bugs, the Report a Bug guild is a great place to post because we can see your Habitica account there (no need to tell us your User ID) and we can give you rapid replies to known issues (e.g., to show you where they are already logged), or can apply fixes to your account directly if needed. It's usually not necessary to log a new issue for a bug that you find, and we'll often do it for you so that we can add extra technical information to help with a fix, if we can. You can reach that guild from the Help menu on the website or the Guilds menu item on the mobile app (you'll find it in the "Public Guilds" section - search for the word "bug" and it will appear straight away). There's also a link to it from the new issue form here in GitHub, if that's ever more convenient for you to find it. Thanks for the reports so far!

@TheHollidayInn Does the wiki's [Sync Errors](http://habitica.wikia.com/wiki/Sync_Errors) page need any updates?

**Closed as completed by Alys** 2018-08-09 22:34 UTC
