### ISSUE TITLE
[API v3] Join and Leave button displayed in guild at the same time

### ISSUE THREAD

**Issue by Memry** [HabitRPG/habitica#7296] opened 2016-05-16 13:34 UTC
General Info
- UUID: e495bd8b-f2f1-48e8-8f5f-9a52710999cf
- Browser: Chrome Version 50.0.2661.102 m
- OS: Windows 7

I joined Lifehackers guild to help someone else test something.  After I joined - this appeared:

![image](https://cloud.githubusercontent.com/assets/7385423/15290913/3c69997e-1b30-11e6-83f1-aab3151a856b.png)

**Comment by quin-jay** [comment] 2016-05-16 14:02
@Memry Does the issue persist after refreshing the page? For me, joining or leaving guilds forces a page reload (it does in the live site, too). I'm unable to replicate, but maybe I would be if it didn't automatically reload.

**Comment by ghost** [comment] 2016-05-16 17:18
For what it's worth, I've seen the same thing on production

**Comment by paglias** [comment] 2016-05-16 20:11
Confirmed, @TheHollidayInn this happens when the page is refreshed after joining a guild (I don't think the refresh is necessary) a second refresh fixes it. I think the problem is because the isMember binding is a one time binding

**Comment by TheHollidayInn** [comment] 2016-05-16 20:26
Yep, same happened in challenges. I can fix this

**Comment by TheHollidayInn** [comment] 2016-05-17 22:21
I'm having trouble replicating this locally, but I am changing the way joining and leaving a guild works, so I am hoping that will solve this problem and some others. Let's just have you all test when the fix is pushed, please.

**Comment by paglias** [comment] 2016-05-18 09:32
This should be fixed now

**Closed as completed by paglias** 2016-05-18 09:32 UTC

**Comment by ghost** [comment] 2016-05-18 09:43
Confirming that it's fixed for me!
