### ISSUE TITLE
To-Do score rises every cron, despite not doing tasks that day

### ISSUE THREAD

**Issue by TheRealQA2** [HabitRPG/habitica#5696] opened 2015-07-30 06:03 UTC
For the last few days, each day my to-do score has been rising by a few hundred points. I've done a few small things some of those days, but definitely not enough to warrant this kind of rise, given that I also have some overdue tasks that should be dragging it down.

I'm kind of wondering if possibly one of my really overdue tasks has actually gone so far negative that it wrapped around, if the daily score adjustment for a task is a short or byte.

User ID: 5dd82d44-993d-44f4-ab31-bbc8a48d766b

Firefox 39.0 OSX 10.8.5 No javascript errors reported in console. 
##

**Comment by Alys** [comment] 2015-07-30 06:41
I'm not sure it's possible for a task value to get that large, but you can see your own task values by doing a [Data Export](http://habitica.wikia.com/wiki/Data_Export) or from HabitRPG's Data menu -> Data Display Tool ("Task Overview" section).

The tasks schema is at https://github.com/HabitRPG/habitrpg/blob/develop/website/src/models/task.js where you can see that the value is a [Number](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number).

[Task Value](http://habitica.wikia.com/wiki/Task_Value) might also have information that's useful for studying this.

**Comment by TheRealQA2** [comment] 2015-07-30 22:53
Ok. I checked out the <value> elements and everything seems more or less in order, so that is not the problem.

My total To Do score jumped another 300 points last night, though, for no To Dos checked off, so there is definitely a bug somewhere.

Date: Wed, 29 Jul 2015 23:41:23 -0700

**Comment by SabreCat** [comment] 2015-07-31 17:39
@TheRealQA2: What do mean by "total To Do score"? Unless you're aggregating the task values via an extension, the site doesn't keep track of the total value across all To-Dos. Are you maybe referring to Experience, the gold bar with the star by it showing your progress to the next level? In that case, it should also be noted that overdue tasks don't drag anything down. Experience doesn't decrease unless you level up or run out of Health.

**Comment by TheRealQA2** [comment] 2015-08-01 00:23
At the top of the ToDo column, there's the small histogram icon, which when clicked shows a line graph between the TODO column header and the tasks underneath. The mouse-over is actually "Progress" and not "score" so apologies for the terminology mistake. If it's still unclear what I mean I'll be happy to attach an image or post one to a hosting site and link. Thanks!

Date: Fri, 31 Jul 2015 10:39:25 -0700

**Comment by TheRealQA2** [comment] 2015-08-01 00:25
Oddly, now that I look at it, the mouse-over is tool-tipped with "progress", the graph is titled "history" and the blue square indicating what the line on the graph stands for is labelled "score". Might actually be worth putting in an intro-coders' issue to bring some consistency to the labels, given that it's creating confusion.

From: qa_2@hotmail.com
To: reply@reply.github.com
Subject: RE: [habitrpg] To-Do score rises every cron, despite not doing tasks that day (#5696)
Date: Fri, 31 Jul 2015 20:22:58 -0400

At the top of the ToDo column, there's the small histogram icon, which when clicked shows a line graph between the TODO column header and the tasks underneath. The mouse-over is actually "Progress" and not "score" so apologies for the terminology mistake. If it's still unclear what I mean I'll be happy to attach an image or post one to a hosting site and link. Thanks!

Date: Fri, 31 Jul 2015 10:39:25 -0700

**Comment by SabreCat** [comment] 2015-08-02 18:00
Aha! OK, that does make a lot more sense. And a good point about the terminology--I'll paste your comment over into a new issue, for that.

Now that I understand the issue better, I agree, something is fishy. If no To-Dos were checked off during a day, I wouldn't expect the progress meter to rise.

**Comment by rachelkachel** [comment] 2015-12-05 22:29
I've noticed something similar on my progress graph too. Doesn't really bother me, since that graph has honestly never been very useful, but I'm pretty sure that's not the intended behavior. If it's a wraparound thing, I suspect that one particular to-do is to blame. It currently has a value of -23687.38, according to the DDT. It's 18 months old and has 63 checklist items, 41 of which are checked off. I also have several others with values in the minus-several-hundreds and one that's -5000ish (I'm bad at to-dos).

I notice that the increase on mine started about the same time as this was first posted, so something in the code might have changed then.

Clearing completed to-dos has no apparent effect (not that I expected it to, just for thoroughness).
The first big jump is from rebirth, everything set back to yellow, it's the sudden change from decreasing to increasing at the end of July that I'm looking at.
![screen shot 2015-12-05 at 2 54 51 pm](https://cloud.githubusercontent.com/assets/12229558/11610497/620aef06-9b61-11e5-8fee-98f35ffb17d8.png)

Edit (12/28): And now it's decreasing again - sudden drop down to where I'd've expected it, around the 6th, and gradual decrease since. Maybe clearing completed did do something.

**Comment by paglias** [comment] 2016-09-03 09:17
I think that the score is rising because the value for every todo that is not done gets increased every day

**Comment by Alys** [comment] 2017-12-07 04:43
To-Do values are currently rising as intended and the progress graphs have been removed (they'll be replaced by a better feature at some future time) so I'm closing this.

**Closed as completed by Alys** 2017-12-07 04:43 UTC
Labels: priority: medium, help wanted
