### ISSUE TITLE
Broken seasonal items appearing purchasable for gems in featured section

### ISSUE THREAD

**Issue by rilygreat** [HabitRPG/habitica#13923] opened 2022-04-10 17:34 UTC
via @citrusella from admin email
> Past-year seasonal gear previously purchased but lost (i.e. to death or old-style rebirth) can show up in the featured area in the seasonal shop as purchasable for gems even though it shouldn't (because if I'm the correct class to buy it then I could buy it for gold). In the case of what I'm seeing right now, it's the rogue 2021 (last year) set. I didn't try to buy it but I imagine if I did I would have encountered an error similar to the one described in this issue from 2016: https://github.com/HabitRPG/habitica/issues/7843 (which is basically the same issue but the items were just showing up in the seasonal shop itself, which is not the case here)

**Comment by CuriousMagpie** [comment] 2022-04-11 15:41
Essentially the same as issue #13798, PR in progress.

**Comment by citrusella** [comment] 2022-04-11 16:31
...Wait, these are caused by the same thing? 0_o

(Confused because to me they look like entirely separate issues that both have the same genesis (gear lost to death). I can buy the gear I'm seeing for gold in the market (unlike the nonstandard slot issue), it's just inappropriately showing up for gems in the seasonal shop's featured item section (it's not supposed to show up at all in the seasonal shop after you first buy it there, AFAIK). If the root cause is the same that is so interesting to me and makes me want to look at the code and see how. XD)

**Comment by citrusella** [comment] 2022-04-11 17:08
I may be off-base because I'm still not SUPER proficient at JS, but I think this issue is caused by the featured items code, specifically, looking for *anything* falsy for the equipment key(s) it's checking, which would include `false` (the way equipment is listed if lost to death, as opposed to nonexistent in your equipment list if you've never bought it before, which would be when it'd make more sense to show as a featured item).

https://github.com/HabitRPG/habitica/blob/5d87c2af1398e07de4bb62ac49e99709a1019535/website/client/src/components/shops/seasonal/index.vue#L439-L444

Though I don't *quite* know what the issue is on the greyed-out nonstandard slot issue, I'm *pretty sure* that PR won't fix this issue? I dunno. Could be possible I'm missing something. Or reading things wrong.

Also, I just tested buying the seasonal featured gear I've previously owned and lost and I found out that you actually *can* buy it for gems completely with no warning or error other than the confirmation you want to spend the gem. ._. (I got the gem back by jumping onto my test account and gifting one from there to myself.)

**Comment by CuriousMagpie** [comment] 2022-04-12 20:38
Okay, I figured out what's going on here. If you lose a piece of gear due to rebirth or death _and_ it is one of the pieces in `featuredSet` in `website/common/script/libs/shops-seasonal.config.js`, _then_ it will appear purchasable with gems in the Seasonal Shop while it is simultaneously unavailable to purchase with gold _if_ your class does not match that of the set's.

Example:
I have a test character who is a Mage. I removed all the Spring and Summer Armor pieces from Test and this is the result:

`armor_specialSpring2021Rogue`from the `spring2021TwinFlowerRogueSet` purchasable with gems, because Test is a Mage, not a Rogue and `spring2021TwinFlowerRogueSet` is the `featuredSet`:
![Screen Shot 2022-04-12 at 4 10 45 PM](https://user-images.githubusercontent.com/78037386/163046020-210cdca0-3e07-4ce4-b019-3e3194606444.png)

`armor_specialSpring2021Rogue`from the `spring2021TwinFlowerRogueSet` unable to be purchased with gold in the Market because Test is a Mage, not a Rogue:
![Screen Shot 2022-04-12 at 4 16 19 PM](https://user-images.githubusercontent.com/78037386/163046720-27861869-1598-4517-9dc2-dedf850a85ff.png)

Changing Test's class to Rogue changes the Market like so:
![Screen Shot 2022-04-12 at 4 20 43 PM](https://user-images.githubusercontent.com/78037386/163046981-c3cc3ff1-76f0-4ac1-8ab6-dda146925c2c.png)

The Seasonal Shop remains the same.

So the issue here, if any, is that there _may_ need to be an `if` statement implemented somewhere to check:

- If users class matches `featuredSet`
  - Then item owned previously
    - Then item available for purchase in the Seasonal Shop for gold
  - Else available for purchase in the Seasonal Shop for gems
- If user's class does not match `featuredSet`
  - Then item owned previously
    - Then item locked for purchase in the Seasonal Shop and item cost is in gold
  - Else item available for purchase in Seasonal Shop for gems

Or something along those lines. 

This seems like an extreme edge case--most people are not likely to run into this issue and it's easy enough for us to restore specific gear items on an ad hoc basis--i.e., single items lost through death, not bulk restoration of items lost through account reset or scripting--if an official bug report is filed. 

I'm re-opening this for @SabreCat's input.

**Comment by adamfitzgibbon** [comment] 2022-10-17 08:06
Hey @CuriousMagpie, I could work on this, but the logic flow you described above seems to be the current functionality.  You're saying we should check their class and if it doesn't match and they owned it previously, then it's locked which based on your example seems to be what is happening. Can you clarify?

**Comment by citrusella** [comment] 2022-10-17 08:39
That logic *is* the current functionality AFAIK. The problem is that the equipment is showing up as purchasable for gems (and not gold) when the user has already bought it for gems before, if it happens to be a featured item. This featured item can be bought whether you're the same class or not, even though the typical "gear lost to death" (or old-style rebirth, technically) situation both removes the items from the seasonal shop otherwise *and* doesn't charge you gems again *and* doesn't let you buy if your class doesn't match.

Also, since I don't think this was realized (or at least not brought up) by anyone present, since I realized it upon doing some searching to figure something else out, this issue is a duplicate of #10719 from 2018 (still open and even tagged for Hacktoberfest 14 days ago like this issue!), when the suggestion from @SabreCat at the time was "make the items gold buy instead if the user previously owned and broke them". I don't know if that'd still be the thinking.

**Comment by CuriousMagpie** [comment] 2022-10-27 18:50
I *think* what should happen is that if the user used to own the item--regardless of their current class--if they lose it to death or disfigurement, it should be re-purchasable with gold, not gems. It seems unfair to make users use gems to re-purchase something they lost through a game mechanic. So if you want to take a look at it, @adamfitzgibbon, with that thinking, go for it! :)

**Comment by adamfitzgibbon** [comment] 2022-11-01 03:25
This should fix it #14326 it still locks the item if it's the wrong class. I can make it also unlock the item if that is what we want @CuriousMagpie

**Closed as completed** 2022-11-18 22:43 UTC
Labels: priority: minor, section: Market, section: Seasonal Shop
