### ISSUE TITLE
Boss health display doesn't update at same time that damage is dealt

### ISSUE THREAD

**Issue by hairlessbear** [HabitRPG/habitica#5535] opened 2015-07-01 16:30 UTC
Here's an example from today:
![selection_015](https://cloud.githubusercontent.com/assets/7059890/8459569/41a22112-1fec-11e5-8764-fe8a7ca488bc.jpg)

Notice that 43 damage has been done, but the boss's health remains full. The health bar updates if I navigate to a different page and then go back to my party's page, or if the page is refreshed.
##

**Comment by joedragons** [comment] 2016-06-19 13:05
I noticed this before as well too, but this seems better with the latest redesign; I haven't noticed in a while.  Wondering if this issue is fixed or at least less prominent.  FYI/2 cents.

**Comment by crookedneighbor** [comment] 2016-06-19 13:18
It's not "fixed", but the party page now reloads every time you go to it, so the only way to reproduce it is to be on the party page, click fetch recent messages, get the notice that damage has been dealt, and see that the boss has not been updated. If you leave the page and come back, then it will update. 

Going to close this now, since we don't plan to fix it before the frontend redesign.

**Closed as completed by crookedneighbor** 2016-06-19 13:18 UTC

**Comment by crookedneighbor** [comment] 2016-06-19 13:42
@paglias pointed out to me that the fetch recent messages button does update the quest data, so this is actually fixed now.
