### ISSUE TITLE
Progress lost every day

### ISSUE THREAD

**Issue by Salarjak** [HabitRPG/habitica#4634] opened 2015-02-05 04:10 UTC
All progress (exp, tasks, gold, etc.) goes back to the way it was before this started happening. This has been happening for the past three or four days and shows no sign of stopping. 

I'm using the app primarily on my iPhone. 

After reading a few similar bug reports, I logged on to the website to try clicking the Tags: Clear button, but nothing happened. 

My UIDD: 5db747f6-6328-4996-ad1a-68b03f16d039

**Comment by Alys** [comment] 2015-02-05 05:21
@Salarjak Is your internet connection on your iPhone intermittent or unreliable? 

You might want to try setting up most of your tasks in the website, which I think will have less chance of causing this problem. I'm sorry about the trouble this is putting you to. I believe we have provided a new version of the app to Apple but they are very slow about releasing it.

@paglias Could this be from iOS problems we're familiar with caused by the app being offline?

I'm not very familiar with iPhone problems so I'm bowing out of this issue now.

**Comment by paglias** [comment] 2015-02-06 16:17
@Alys if he uses the app offline even once it's probably this. unfortunately the iOS update is taking ages to be approved :/

**Comment by crookedneighbor** [comment] 2015-02-10 02:00
@Salarjak the iOS update was released today. (finally) Would you mind updating the app and seeing if you're still having the same problem?

**Comment by Salarjak** [comment] 2015-02-10 02:08
I will, thank you!

**Comment by Alys** [comment] 2015-06-14 03:48
@Salarjak I'm closing this but comment here if it's still a problem.

**Closed as completed by Alys** 2015-06-14 03:48 UTC
