### ISSUE TITLE
Changing level with "Fix Character Values" doesn't adjust Attribute points

### ISSUE THREAD

**Issue by jfriendlys** [HabitRPG/habitica#2041] opened 2013-12-18 06:49 UTC
This is low priority, but I thought I should report:
I used "Fix Character Values" to reset my character back to level 5 (I couldn't wait for the New Game+ feature).  My Attribute points remained at 32, and I don't have a way of lowering them.

I don't mind, and frankly think it's better to not have the option of manually changing attribute points (way too much potential for abuse).  Just something to consider - do we want that feature to affect attribute points? or do we just sidebar the issue until New Game+ is developed?
##

**Comment by lefnire** [comment] 2013-12-18 06:51
Confirmed. Will need to fix this

**Comment by wc8** [comment] 2013-12-18 12:32
I suggest _changing levels adjusts your attribute points to match your level._
Any necessary reallocation happens in the Profile > Stats & Achievements page.  
- User going from Level 32 to Level 5 will have 5 points. 
- User going from Level 32 to Level 34 will get 2 more points. He then allocates them on the Stats page.
  If the system can’t track where to allocate the 5 points, then just leave it to the user to decide.

Yes, they could abuse, but 1) this approach doesn’t make how to abuse it so obvious, 2) for now it’s honor system anyway

**Comment by wc8** [comment] 2014-01-08 03:10
Related… after using reset, I finally reached level 10, but find I have -15 attributes to allocate. …
Perhaps this is because _reset_ did not reset classes and attributes?

**Comment by marcelosizer** [comment] 2014-10-15 17:04
Apart from the known bug, I used "fix character values" and got my 3 gems back after refresh.

**Comment by miketekin** [comment] 2015-04-10 02:10
My character just died and lost 2 levels. I've used "fix character values" but I lost the 2 attribute points I allocated to perception and it shows that I have 0 unallocated points. This is the first problem I'm experiencing with habitrpg and I'm super bummed about it. If anyone can think of a work around until this gets fixed, I would appreciate it.

**Comment by Alys** [comment] 2015-04-10 02:17
@tekinm25 This will definitely fix itself when you next level up (you'll get all the correct attribute points then). However if you'd like to fix it immediately, go back to Fix Character Values, adjust your level down by one, and save that. Then look at the maximum XP on your XP bar. Use Fix Character Values to adjust your own XP to the maximum (or greater than maximum if you wish). Then go to your tasks list and tick off any task (you might like to create a new To-Do for this). You'll level up normally to your correct level and your attribute points should now be correct.

**Comment by miketekin** [comment] 2015-04-10 02:21
Yeah, adjusting it down and completing a task to level up is working. Thanks! For the help and the quick response.

**Comment by Alys** [comment] 2015-05-18 00:51
Related: https://github.com/HabitRPG/habitrpg/issues/2496 "Reset does not remove attribute points OR lets them go negative"

**Comment by Alys** [comment] 2016-01-09 14:05
I'm closing this in favour of [Issue #6482: incorrect attribute / stats points from various causes - need generic function to do allocation / deallocation](https://github.com/HabitRPG/habitrpg/issues/6482)

**Closed as completed by Alys** 2016-01-09 14:05 UTC
Labels: priority: medium
