### ISSUE TITLE
Pinning a Quest or Time Traveler item resets filters

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#9500] opened 2017-11-15 23:08 UTC
Pinning a Quest or item on the Time Travelers' shop resets filters. This has been confirmed happening in Chrome, Firefox, and Opera.

**Comment by Alys** [comment] 2017-12-07 23:00
In the Report a Bug guild, webbie ( 03117605-1b3f-4b42-a0e2-a57b135f6457 ) has confirmed this still occurs:

"i'm looking through the github cases and found #9500 which i could test in my opera: pinning (and un-pinning) a quest in the questshop still resets the filters. i tried with quest of all three sections, with one and two filters unchecked, with locked and unlocked quests ... it's the same all the time.
at the market everything's fine, though, no resetting of filters when pinning something."

**Comment by Tressley** [comment] 2020-04-27 14:48
This issue also occurs on Chrome and Firefox. It's on any filter type, but is only specific to the Quest and Time Travelers' shop.

**Comment by Alys** [comment] 2020-04-28 02:32
I've marked this as "help wanted" instead of "needs investigation" since this seems to be reproducible issue now - thanks @Tressley !

**Closed as completed** 2020-07-13 09:53 UTC
Labels: priority: medium, help wanted, section: Quest Shop, section: Time Travelers
