### ISSUE TITLE
Unchecking a daily costs more gold/silver than it gives?

### ISSUE THREAD

**Issue by scheidm** [HabitRPG/habitica#4497] opened 2015-01-09 14:55 UTC
Today I accidentally checked off a daily I had failed to accomplish. It gave me 62 silver. Then I clicked again to correct it and it debited me 73 silver. I did it again, just to double check, and it did the same.  I can't imagine that's working as intended. Please correct me if I am wrong.
##

**Comment by Alys** [comment] 2015-01-09 19:27
Duplicate of https://github.com/HabitRPG/habitrpg/issues/964 although that's supposed to be fixed. But really, we're talking about 0.1 gold - very small. Minor rounding error?

**Comment by Alys** [comment] 2015-02-14 04:31
Comment from @crookedneighbor in #4678 :  

"Usually the discrepancy is due to the streak bonus. For instance, one of my dailies is worth 2 gold and when I click it, I get 2 gold plus 3 silver as a streak bonus (separate notification). When I uncheck it, I lose 2 gold and 3 silver as a single notification."

**Comment by Alys** [comment] 2016-04-02 07:45
I'm pretty sure this is fixed. I can't replicate it. Closing. Reopen if I'm wrong.

**Closed as completed by Alys** 2016-04-02 07:45 UTC
