### ISSUE TITLE
Overpowered Rogue

### ISSUE THREAD

**Issue by Johangsl** [HabitRPG/habitica#2001] opened 2013-12-17 04:56 UTC
I became a Rogue, allocated my stats and tried out pickpocket on a task I just did, and it gave me 500 gold. This was a blue habit, so no way it could net that amount.

![image](https://f.cloud.github.com/assets/5248861/1761636/84b5dbd0-66d7-11e3-87ec-ae7aea5b8ecf.png)

**Comment by cleave29** [comment] 2013-12-17 06:05
Same here.  I got even more because I clicked a daily and it registered 3 times.  
In fact all of my gold is about 4 times what it is normally.
(P.S.: love the changes!!!  You guys are awesome!)

**Comment by nlivni** [comment] 2013-12-17 07:08
i had the same issue but i got thousands of gold! awesome work guys. love the new features.

**Comment by lefnire** [comment] 2013-12-17 07:19
Is it just PickPocket people are experiencing huge balancing issues one? or is it general interaction with tasks, and/or other spells?

In the meantime, I could use help balancing some of this. I'm not great at math, and I'm running around fixing server error from this release. I threw together a [sloppy fix here](https://github.com/HabitRPG/habitrpg-shared/commit/2ecbb3b3ce2c505fb2b55ad1a518891af55e234f) for pick-pocket. You can see all the spells' [math here](https://github.com/HabitRPG/habitrpg-shared/blob/develop/script/content.coffee#L189L375), and standard [+]/[√] [math here](https://github.com/HabitRPG/habitrpg-shared/blob/develop/script/index.coffee#L670TL689). A task.value ranges roughly between -30 & 20, FWIW. Haallp!

**Comment by octern** [comment] 2013-12-17 07:27
As described in #2005. I'm level 45, got 9.29 GP for a new to-do (repeatably). I didn't use any skills (I haven't even figured out how to use skills yet!) I haven't bought any equipment except for oiled leather.

**Comment by TheOfficePicnic** [comment] 2013-12-17 07:43
As cleave29 said, GP awarded for checking off habits/dailies/to-dos seems to be inflated by 3x to 4x what it was before the update. I am a wizard, level 29, with 7 points allocated to each stat (except 8 in INT). I have not tried using any spells yet, so it is probably not a factor. My wife has her own account, and reported the same inflation as a level 19 warrior.

**Comment by lefnire** [comment] 2013-12-17 07:44
See above hotfix, this might help (pushing now). We'll still need a proper mathist to sweep habitrpg-shared

**Comment by Pandoro** [comment] 2013-12-17 10:27
@lefnire I just glimpsed over some of the values and think that in general the values are a bit generous. Looking at my level 35 with super basic gear, my perception is at 44 already. So saying a "main" stat gets to 44 so easily and then having multipliers in the range of 0.2~0.5 while target values are between -30~20, or e.g. hp which maxes at 50 is a bit too generous. I think you should not be able to double your standard values without doing a LOT of effort on maxing certain stats. I can maybe have a look at this later, although I feel rather unfamiliar with the stat system currently.

**Comment by Johangsl** [comment] 2013-12-17 14:41
I have 10 in PER, I recieve a drop everytime i complete a task.

**Comment by nafoster** [comment] 2013-12-17 16:00
Had the same problem as a high-level Wizard, but it seems to be fixed now.

**Comment by lefnire** [comment] 2013-12-17 16:06
Nay, wizard's aren't fixed yet. There are tons of math issues all over the place, we're gonna need some help getting the math right. I'm gonna write a "call to arms" blog post

**Comment by ghost** [comment] 2013-12-17 18:50
I'm a mathemathician and I think that to get the values right we need to have a comparison with pre-update data in order to get the results in a similar range. I'm not familiar with the script used but the math seems right, so the problem is probably on the order of magnitude of the fixed multipliers.

**Comment by fragmental** [comment] 2013-12-17 19:04
Is there any way to make the charts display only the amount they change, so that people can watch them more easily?

**Comment by ghost** [comment] 2013-12-17 20:22
wait, maybe I got something... (beware of pseudo-code ahead)

for pickpocket we have (content.coffee)
gp <- gp + (mod_task_value + 2) \* PER \* 0.3
where mod_task_value picks 0 if negative, task_value if positive (Chi functions needed in math)

then we have the 'standard' modifier for when a task is completed (index.coffee)
gp <- gp + (gpmod_)
with gpmod_ depending on gpmod and if there's a task streak (takes some Chi functions to write in math notation, but I did it, trust me)

so we have two scripts that are executed at the same time that both want to modify the same value... I have done only a couple of IT exams in my career but this could lead to some consequences I think...

my (horrible) solution: edit the spells/abilities in content.coffee so that they write in a separate variable what they will sum to the gp/xp/etc, then edit the functions index.coffee to consider these other variables. I don't know the language used so I can't say if/how it's doable, but I hope it's helpful :)

EDIT: I'm assuming both the scripts are executed when clicking on a task but I can't find the actual code for this, could you point me to it if I'm wrong?

**Comment by lefnire** [comment] 2013-12-19 21:24
Gonna close this card for centralized conversation, most of the dialog is happening over [on trello](https://trello.com/c/L1H6LiZ3/110-character-stats-attributes-the-class-system). Main issue now is (1) classes being _underpowered_, and (2) casting a spell on checkboxes causes crazy numbers bugs (vs casting on the task body), which we'll follow separately

**Closed as completed by lefnire** 2013-12-19 21:24 UTC
Labels: priority: important
