### ISSUE TITLE
Boss damage doesn't show up until refresh of party page

### ISSUE THREAD

**Issue by octern** [HabitRPG/habitica#2126] opened 2013-12-26 15:46 UTC
My rollover is scheduled to happen at 10:00 AM. This morning I checked off some dailies from yesterday, and after 10 I reloaded the page so rollover would happen. I got my HP loss notification from an item I missed and my dailies all reset. Then I went to my party page to check the new boss's HP, but it was still at max. I then reloaded the page again, and the boss showed a little damage. 

I'm not sure why this would happen. Does rollover occur separately for different pages?

**Comment by lefnire** [comment] 2013-12-26 16:06
I plan to fix this, but it's gonna be an adventure - so will be a ways out. Here's the technical lowdown.

`user` is loaded from the server separately from `group`s (guilds, tavern, party). This is for performance reason - you may only want to do your tasks and never visit the tavern or guilds tab in a session. However, here's the consequences:
1. Load user & party concurrently, but separately
2. In the case of boss attacks, party will return to the client first, because cron+bossAttack is an expensive operation
3. user finally returns updated, but party is now out-of-date

I can either look into adding socket.io notifications of updates to clients (which I'm a bit hesitant towards, due to my experience with Derby); or I can look at returning some "time to update the party" flag on the user object, which I'll have to think on.

@paglias I know you don't really use the social stuff, but do you have any architectural thoughts?

**Comment by paglias** [comment] 2013-12-26 16:17
Maybe I don't get how this is working... if I start a quest, then the rollover is scheduled at 10am and I don't login again until 11am, my party members won't have the bossAttack damage until 11am? 

The quest "cron" could be moved from user's cron to a new party's cron that is run for all party members when the party is requested?

**Comment by lefnire** [comment] 2013-12-26 16:19
Well, each user's cron triggers bossAttack individually, and on that user's own schedule. So 
1. lefnire's cron: did half my dailies. Boss hits party 10hp, lefnire hits boss 10hp.
2. paglias's cron (8h later): all his dailies: Boss hits party 0hp, paglias hits boss 20hp.

So the _timing_ needs to be handled on a per-user basis, which is why I did it in user cron

**Comment by paglias** [comment] 2013-12-26 16:26
Ok... but we could try running user's cron ayway: if user's day start time
is passed and cron has still to run (if user has not logged in today) then
it's run otherwise no.

But, when the user itself open the app for the first time and requests the
party then the cron could be run twice (by api.user and by api.party)....

2013/12/26 Tyler Renelle notifications@github.com

> Well, each user's cron triggers bossAttack individually, and on that
> user's own schedule. So
> 1. lefnire's cron: did half my dailies. Boss hits party 10hp, lefnire
>    hits boss 10hp.
> 2. paglias's cron (8h later): all his dailies: Boss hits party 0hp,
>    paglias hits boss 20hp.
> 
> So the _timing_ needs to be handled on a per-user basis, which is why I
> did it in user cron
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/HabitRPG/habitrpg/issues/2126#issuecomment-31225976
> .

## 

Matteo Pagliazzi - paglias.net

**Comment by paglias** [comment] 2013-12-27 21:42
For that we could add a check and if the user is in a party then doesn't run the cron on the user but only on the party

**Comment by lefnire** [comment] 2013-12-27 22:15
On thing I was bouncing around in my head: add `UserSchema.party.id = {type:String,ref:'group'}`. Have a flag for detecting changes (add `GroupSchema._v` back in, compare with `UserSchema.party._v`). If it's different, do `user.populate('party.id')` instead of fetching party separately. Remove all party-fetching code from initialization, but instead run `party.resolve(user.party.id)`.

That's kinda jumbled, does it make sense what I'm getting at? It's a pretty substantial overhaul, and it means Party would be sent down all over the place (it's not used at all on Mobile, so that's wasteful). But just thinking out loud in case that leads to any other thoughts

**Comment by paglias** [comment] 2013-12-28 19:23
I have a quite radical idea for this and #1057, instead of waiting for the user to login why not run a cron worker every hour that run the cron automatically for users with cron set at that hour? 

For heroku https://devcenter.heroku.com/articles/scheduler

**Comment by lefnire** [comment] 2013-12-28 19:51
Only problem I see with that approach is it will run for all users in the database, and only ~4k of our 110k users are active, meaning we'll spend 116k unneeded processing power. Not a show-stopper, just wanna point it out

**Comment by paglias** [comment] 2013-12-28 20:01
How much do you think it will take? It must be fast... I thought about:

1-) compile a cached list of users divided for cron hour
2-) remove the dead ones

**Comment by lefnire** [comment] 2013-12-28 20:13
Oohhh... remove dead ones will keep inactives out of the processing, and will limit the list substantially! Very good call. Then we can just add a compound index on `{lastCron:1,'stats.hp':1}` for fast lookup. I think I like this idea, definitely worth experimenting with

**Comment by paglias** [comment] 2013-12-28 20:17
And we may also keep out the ones without dailies, right?

For #1057 we may end up with the same problem, though... Maybe calculating
the timezone offset right when the day start is set so it's relative to GMT
or server timezone may help, at that point there shouldn't be difference
between users with custom day start and users without

**Comment by paglias** [comment] 2013-12-28 20:18
For the last comment we may try it also without moving cron calculation to
a server cron job, keeping the same system as we're using now

**Comment by paglias** [comment] 2013-12-28 20:19
Because let's face it, it is probably that it will take a minute or more to
compute everything so users who login in the mean time may have problems...
Il 28/dic/2013 21:18 "Matteo Pagliazzi" matteopagliazzi@gmail.com ha
scritto:

> For the last comment we may try it also without moving cron calculation to
> a server cron job, keeping the same system as we're using now

**Comment by lefnire** [comment] 2013-12-28 22:10
I'm gonna try to parse this when I get a moment, having trouble wrapping my mind. I think CDS & #1057 is gonna factor a lot of complication into this equation, but it'll be doable. We are storing user timezone (it's set immediately upon page-load if one doesn't exist), so we have that to work with. If you decide to tackle this before me and have questions, hit me up

**Comment by flora-bonita** [comment] 2014-02-28 16:46
I also had this issue.  Perhaps just include hitting the refresh under the chat in the instructions.  I thought I did no damage for three days until I tried hitting that.

**Comment by Yuubou** [comment] 2014-03-02 16:14
I also have an issue with Party Page reloading.  I will get a notification of a new message in Party on the top bar; when I go there nothing new displays.  If I sync it nothing new displays.  I have to right click reload for the new message to appear.  Not a big bug, but wanted to report it anyway.

**Comment by Heavyarmorpally** [comment] 2014-03-04 17:07
I also have this issue. The boss damaging part of my cron doesn't register until I refresh my page on the social party Boss fight page AND my damage is consistently terrible and much lower than the rest of my similarly powered and equipped party.

**Comment by deilann** [comment] 2014-03-06 11:18
@Heavyarmorpally Your damage is probably lower because either your dailies are much bluer, you have fewer of them, or are doing less To-Dos, or spells that hurt bosses.

**Comment by Heavyarmorpally** [comment] 2014-03-06 13:57
Fair enough! :-) However, it still doesn't change the fact that my cron isn't automatically attacking the boss unless I hit refresh while directly on the party page.

**Comment by deilann** [comment] 2014-03-06 14:07
It is, it is just not displayed until refresh because your browser has a cached copy of your party page.
Heavyarmorpally notifications@github.com wrote:

> Fair enough! :-) However, it still doesn't change the fact that my cron isn't automatically attacking the boss unless I hit refresh while directly on the party page. 
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/HabitRPG/habitrpg/issues/2126#issuecomment-36889609

Fair enough! :-) However, it still doesn't change the fact that my cron isn't automatically attacking the boss unless I hit refresh while directly on the party page.

**Comment by Gaelan** [comment] 2014-03-09 11:59
The per-user cron system can actually be used to a party's advantage: if the boss is almost dead, and one party member did really badly and the other did well, the one that did well can intentionally open Habit first, and the boss will be dead before the other party member can do any damage.

**Comment by Alys** [comment] 2015-07-04 03:47
I'm removing the "critical" label from this. It seems to me like a nice-to-have but not essential fix. Any admin who disagrees can add it back and then I won't touch it again. :)

**Comment by crookedneighbor** [comment] 2015-07-04 03:50
There goes my chance at earning the hammer

**Comment by hairlessbear** [comment] 2015-07-04 18:02
Is #5535 a duplicate of this?

**Comment by Alys** [comment] 2015-07-04 20:35
Closing in favour of https://github.com/HabitRPG/habitrpg/issues/5535 because it doesn't contain the comments above, some of which are outdated.

**Closed as completed by Alys** 2015-07-04 20:35 UTC
