### ISSUE TITLE
Paying for Gems with Paypal is broken

### ISSUE THREAD

**Issue by Firey40** [HabitRPG/habitica#2542] opened 2014-01-24 03:49 UTC
I've been trying for the past few days to pay for Gems with Paypal, but the button doesn't go anywhere when I click on it... My browser recognizes it as a link, but that's it.

**Comment by SabreCat** [comment] 2014-01-24 03:57
Duplicate of #2535.

**Closed as completed by SabreCat** 2014-01-24 03:57 UTC
