### ISSUE TITLE
Buffs that had no chance to take effect shouldn't reset at cron

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#3071] opened 2014-03-14 00:09 UTC
I frequently have the problem that I toss out a Valorous Presence or similar buff, but it's in between when (at least some of) my party members last check in to the site for the previous day and when they next check in triggering cron. This ends up meaning that a buff meant to last "until the end of your day" lasts exactly... no time at all. Maybe this makes sense for a buff to CON, since it'll absorb damage from missed Dailies during that turnover, but for a buff to STR (my favorite), it's useless.

Could the cron logic note that there are pending but unapplied buffs, and put them into play _after_ clearing extant buffs? You'd need to be careful about how to handle skipped days (don't want people to be able to cheat by stacking up buffs over several days they don't even stop in), but it'd be wonderful for this rather common use case.

**Comment by deilann** [comment] 2014-03-16 11:18
Honestly, I'd like to see party buffs last 24 hours no matter what-- or go away upon the person who cast them's cron. Although then there's the issue of what if they never log in again?

**Comment by SabreCat** [comment] 2014-03-16 12:02
24 hours period seems to be the most-suggested solution. In either case, we'd need to start tracking individual buffs as distinct entities instead of just dumping adds into the user's stats object and forgetting about them.

**Comment by deilann** [comment] 2014-03-16 12:09
And we'd have to figure out how we want to handle recognizing when 24 hours
is up.

**Comment by brightbold** [comment] 2014-03-16 12:58
+1 for 24 hours. 

I wasted a bunch of buffs early in their existence by casting them at the end of the day, believing that then my party would get full use of them for the next day until 24 hours had passed, not realizing they were actually going to expire while we were all sleeping. My logic for casting at the end of the day was realizing that my mana was maxxed out and I was going to miss out on getting my 10MP overnight. I'm guessing I'm not the only person who has made this bad assumption, so it  would be nice if it worked the way you'd guess if you didn't RTFM.

**Comment by wc8** [comment] 2014-03-21 16:04
@brightbold you're not the only person who made this assumption, I found this ticket illuminating. 
+1 for 24 hours, if feasible.

**Comment by wingsandgills** [comment] 2014-06-15 16:28
It might not be ideal, but what if buffs that are meant to last a day didn't take effect UNTIL next cron, and then reset at the cron after that? So if I cast Tools of the Trade now (on the 15th), it wouldn't buff until everyone's cron runs on the 16th, and then wiped when everyone's cron runs on the 17th. It would mean a delayed benefit, but it would also mean everyone definitely got the benefit of the buff for a full day even if they log in at markedly different times.

**Comment by townimbecile** [comment] 2014-11-07 18:19
I've encountered this problem, too. If buff timestamps are too unmanageable, though, is it possible that party members poke cron for everyone else? What I mean is, if I wake up first in my party and sign in, habit checks to see that it is past my day start, so it triggers my cron. Great. But why _doesn't_ it cascade to my party members, checking their day start, and triggering their cron? This would solve the lost morning buffs issue. It would also make the logic of healing someone who is already effectively dead more transparent (that is, if someone went to bed, about to take enough damage to die, but you wake up before they do, the damage they're about to take should be clear to you).

**Comment by Alys** [comment] 2015-05-18 02:46
Duplicate of https://github.com/HabitRPG/habitrpg/issues/2523 so I'm closing this issue.

@townimbecile I think cascading crons would cause problems due to players not being able to control when their own cron occurs. For example, in my party recently, one member who'd been unable to do most of their Dailies stayed off HabitRPG for several hours longer than usual, to give the current quest time to end, so that they didn't damage the party. Now admittedly there are other ways around that particular scenario, but it is an example of a player wanting control over their own cron.

@wingsandgills I think the delayed benefit would be troublesome to many users. If you're casting a buff, it might be because you know your party mates need protection from extra CON now, or because you want to earn more gold today for buying new equipment. Delayed rewards tend to be less effective for motivation.

**Closed as completed by Alys** 2015-05-18 02:46 UTC
Labels: status: issue: suggestion-discussion

**Comment by SabreCat** [comment] 2015-05-19 17:47
I would like to overhaul buffs so they last an actual 24 hours, but that
will be a fairly substantial project.

**Comment by deilann** [comment] 2015-05-21 14:28
@SabreCat I've been thinking on this and I've come to the conclusion that having buffs last an actual 24 hours is a terrible idea and it would make the Habit experience very frustrating.

If buffs lasted an actual 24 hours, throughout your Habit day intelligence and perception buffs would wear off, meaning your max MP and drop cap would suddenly shift. Unless you have a better memory than me, you'd have almost no idea when these changes would occur and they could lead to some very upsetting experiences like not getting MP for the task you just did because your max MP just dropped, or not realizing your drop cap went back down and having no drop chances for a series of tasks when you thought you did.

I think a much better alternative would be if a player is buffed between their last action in a day and when they trigger cron, they get that buff for the next day. This would be more reliable and not create such upsetting circumstances.

**Comment by Alys** [comment] 2015-05-21 14:40
Good points. Stats that (seem to) vary randomly throughout the day would be sure to at least raise questions. I'd find it annoying to suddenly lose MP through my max MP dropping. I'm sure I usually wouldn't notice until after the excess MP was gone.

**Comment by dbarnett** [comment] 2016-10-18 13:56
Closed as a dupe of #2523, right? There's no easy answer for solving that one (optimizing for mixed-CDS parties), but there's an unambiguous improvement available to store party member effects and load/check them on individual party members' first activity of the day.
