### ISSUE TITLE
Quests: No Damage to boss from any Dailies or To-Dos 

### ISSUE THREAD

**Issue by BananasAreGoodForYou** [HabitRPG/habitica#4831] opened 2015-03-10 17:45 UTC
So after many days of barely damaging this boss and reading the wiki many times. I think my party is bugged. Neither party members are causing any damage to the boss with completion of any dailies or to-do tasks. The two of us use a combination of phone and web and the items are checking off properly on our web based task pages. The only damage we are doing is a small amount of damage when boss damage is calculated from missing dailies. This damage is not affected by strength. 

My ID is 5934b535-d361-41a6-908d-eae485fa2dc4
my party member ID is 76633864-c91b-457e-a132-26d44632c4f6
Our party ID is  0ddd4d98-bfb6-4bb8-9847-a9b4d17a6cad

**Comment by Alys** [comment] 2015-03-10 19:17
I've checked the damage log for your party and the two people in the quest are definitely doing damage to the boss (e.g., 9.1 and 4.6 damage most recently). This damage is coming from your completed To-Dos and Dailies.

For quests, all damage to the boss is applied when your cron runs - i.e., once per day, usually when you first use HabitRPG for that day (the previous day's damage is applied then).  For more information, see http://habitrpg.wikia.com/wiki/Cron and http://habitrpg.wikia.com/wiki/Boss (especially the mechanics section) and the information at the bottom of the quest box on your party page.

The damage you do will increase as your strength increases, but a small strength increase will result in only a small damage increase.

I'm going to close this now since everything seems to be normal, but we can reopen it if it turns out that that's not the case, and if you have any questions you can ask them here. We'll see and answer them even when the issue is closed.

**Comment by BananasAreGoodForYou** [comment] 2015-03-10 21:16
Strength seems to have virtually zero effect on damage. The characters are doing the same varrence of damage despite aimless having  44 additional strength than tofu hero and doing more task during the day. Despite a huge stat difference we are doing the same damage that we were doing a month ago.

**Comment by Alys** [comment] 2015-03-10 21:46
Yes, strength does have a small effect on damage. The formula for damage done to a boss is
`x * (1 + STR / 200)`
where x is a value that's determined from the redness of the task and STR is your total strength from all sources (equipment, attribute points, buffs). You can see from that that strength is divided by 200 before being used to calculate damage.

The best way to increase damage done to a boss (and to level up faster) is to do more tasks, or increase the difficulty of tasks (medium or hard, rather than easy, in the task edit screen), or add checklists to To-Dos (each checklist item is effectively the same as one new To-Do, and this can be a good way to break a difficult task into easier steps, while also getting more XP for the task). Also, in an upcoming change, Habits will start damaging bosses so you might find that you are doing more damage then. If either of you are a Mage or a Warrior, you can use Burst of Flames or Brutal Smash to do more damage to the boss.

**Comment by deilann** [comment] 2015-03-10 22:04
Also, if you regularly do your tasks, they're getting bluer... which means
that as your strength increases, the task value also increases, which
lowers the amount of damage they do. So that's probably balancing out your
increase in strength.

**Comment by BananasAreGoodForYou** [comment] 2015-03-11 21:47
Thank you both for your help. We used some warrior skills yesterday and Aimless' damage jumped from 7 to 37!

**Comment by Alys** [comment] 2015-03-12 06:00
Thanks for letting us know!

**Closed as completed by Alys** 2015-03-12 06:00 UTC
