### ISSUE TITLE
Unresponsive script error

### ISSUE THREAD

**Issue by Caspid** [HabitRPG/habitica#3323] opened 2014-04-21 14:10 UTC
Script: https://habitrpg.com/app-99334215.js:5
![program manager 2014-04-21 07 07 29](https://cloud.githubusercontent.com/assets/2336773/2754859/8b658cb6-c95e-11e3-8af7-38434a00714e.png)

Occurs frequently and sporadically with normal tasks; can't come up with a consistent STR.

Latest Firefox Nightly; w7x64.
##

**Comment by deilann** [comment] 2014-04-21 14:12
This happens pretty regularly to me as well -- it happens the most when a
lot is happening (notifs to find, expecially). If I wait, it almost always
eventually sorts itself out. I do not have to stop the script.

**Comment by Caspid** [comment] 2014-04-21 19:52
I get it even when doing relatively little/nothing — entering the site, entering the Tavern, etc.

**Comment by deilann** [comment] 2014-04-21 19:53
@Caspid Those actions would check your notifs, jsyk. Don't know if it's
connected, but notifs.

**Comment by Caspid** [comment] 2014-05-02 03:07
I've unsubscribed to all but ≈5 guilds, and I'm still getting pretty frequent errors.
e.g.  https://habitrpg.com/app-d5639d50.js:5

**Comment by deilann** [comment] 2014-05-02 15:41
This has gotten to the point where I will often get multiple errors on one
load.

To the point where if I have 5 minutes and I need to check off five tasks,
I have not been able to do so within 5 minutes.

**Comment by ghost** [comment] 2015-07-13 19:58
I've had many of these Unresponsive Script errors in the past couple weeks, and Habit has been incredibly sluggish.  The blue bar often takes 30seconds-1minute to get across the page. Browser: Firefox 39.  Most recent error was in app-1d478d23.js:9 which was unreadable in my console window.

My console also had the following error text, which may or may not be related (couldn't find a timestamp):
"Error: [$rootScope:inprog] $digest already in progress
http://errors.angularjs.org/1.3.9/$rootScope/inprog?p0=%24digest
d/<@https://habitrpg.com/app-1d478d23.js:4:23731
o@https://habitrpg.com/app-1d478d23.js:7:19007
wd/this.$get</j.prototype.$apply@https://habitrpg.com/app-1d478d23.js:7:17463
y@https://habitrpg.com/app-1d478d23.js:20:9637
n.event.special[a].handle@https://habitrpg.com/app-1d478d23.js:2:10159
n.event.dispatch@https://habitrpg.com/app-1d478d23.js:2:6414
n.event.add/r.handle@https://habitrpg.com/app-1d478d23.js:2:3224
nrWrapper@https://habitrpg.com/#/tasks:1:11505
b.prototype.token@https://habitrpg.com/app-1d478d23.js:9:10367
b.prototype.lex@https://habitrpg.com/app-1d478d23.js:9:10309
b.lex@https://habitrpg.com/app-1d478d23.js:9:10166
j@https://habitrpg.com/app-1d478d23.js:9:21359
a</a@https://habitrpg.com/app-1d478d23.js:30:2914
.link/j</m@https://habitrpg.com/app-1d478d23.js:30:3952
.link/j<@https://habitrpg.com/app-1d478d23.js:30:4229
wd/this.$get</j.prototype.$digest@https://habitrpg.com/app-1d478d23.js:7:15972
wd/this.$get</j.prototype.$apply@https://habitrpg.com/app-1d478d23.js:7:17526
s@https://habitrpg.com/app-1d478d23.js:6:13455
w@https://habitrpg.com/app-1d478d23.js:6:15073
y@https://habitrpg.com/app-1d478d23.js:6:14735
nrWrapper@https://habitrpg.com/#/tasks:1:11505
"

**Comment by ghost** [comment] 2015-07-14 16:12
Today's unresponsive script error was for: https://habitrpg.com/app-1d478d23.js:5
This was not my very first load of Habit for the day, but I went away for a few minutes, which sent my computer to sleep, and then woke it up and had the error on my Habit tab.  There was nothing in the console.

**Comment by neverasuspect** [comment] 2015-08-16 17:51
Did anyone ever find a way to fix this? my most recent was the one below but I get them constantly if the Habitica tab is even open, it jams up the rest of the browser. 
Script: https://habitica.com/app-2a5fb0af.js line 7 > Function:1

**Comment by Alys** [comment] 2015-08-16 21:34
@neverasuspect It tends to be an intermittent error that's browser-specific, rather than caused by Habitica code. Do you have very many tabs open in your browser? That can worsen browser performance. Also try turning off all extensions and if that improves matter, turn them back on one by one until you've identified a culprit. You can also try using Habitica in a different browser if nothing else works.

**Comment by librarianmage** [comment] 2017-11-15 03:19
Is this still an issue?

**Comment by Alys** [comment] 2017-11-15 12:36
This was logged for the old site and was typically because the site had too much javascript for a browser to handle. The new site is hopefully better so I'm closing this. We can log a new issue if needed.

Thanks MathWhiz! :)

**Closed as completed by Alys** 2017-11-15 12:36 UTC
Labels: priority: important, status: issue: needs investigation
