### ISSUE TITLE
Loss of checked dailies when switching computers on a new day

### ISSUE THREAD

**Issue by mmarkey3** [HabitRPG/habitica#1332] opened 2013-08-14 18:10 UTC
I've had a repeated bug during the past few weeks or so where I would check off dailies at home in the evening, hard refresh to ensure that everything was checked off properly, and then go to my computer at work the following morning to find that some or all of my dailies were marked as undone the previous day.  I took damage for the undone activities, lost my streaks, and even level gain was undone - in other words, expected behavior for if I hadn't checked off those dailies the night before and/or ensured that they were actually in the system.

This may be involved with going from computer to computer, or it may be because of going from Chrome at home to Firefox at work.  I am now loading Habitrpg in Chrome exclusively to experiment as to whether this is a Firefox problem (but it'll be a day or two before I know, but I'll let you know).  I would also get a "script is not responding" error in Firefox before this happened.

I'm running windows 8 on both computers and the latest versions of both Chrome and Firefox.

**Comment by angelicmaiden** [comment] 2013-08-16 07:14
I get the same error, but I use chrome at home _and_ at work, so I think the problem is caused by switching PCs. Very annoying...

**Comment by lefnire** [comment] 2013-08-16 16:25
see  No. 2 of http://habitrpg.tumblr.com/post/55792029689/bug-workarounds , the issue is leaving a browser open on the previous machine when you access habit in the new browser. We're working on a rewrite to get around these issues

**Comment by lefnire** [comment] 2013-08-16 16:26
dupe of #635

**Closed as completed by lefnire** 2013-08-16 16:26 UTC
