### ISSUE TITLE
when editing tag names, textbox loses keyboard focus after one character

### ISSUE THREAD

**Issue by sdpope** [HabitRPG/habitica#1228] opened 2013-07-04 13:15 UTC
This isn't critical but it's pretty annoying. whenever I go to edit my tags, whichever input box I'm typing in immediately loses keyboard focus after one character or backspace (but not navigating with the arrow keys). 

I'm using Firefox 22.0 in Xubuntu 12.04.

**Comment by svemir** [comment] 2013-07-06 09:35
Confirmed in FF and Chrome on OSX. The worst part is that after pressing delete and losing the focus, if you press delete again, browser interprets it as Back...

**Comment by dashbuck** [comment] 2013-07-30 21:57
I'm getting the same exact error as svemir on Firefox in both Windows XP and Ubuntu 12.04.

**Comment by paglias** [comment] 2013-09-09 17:50
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!

**Closed as completed by paglias** 2013-09-09 17:50 UTC
Labels: priority: minor
