### ISSUE TITLE
browser find feature does not work correctly in private messages

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#11949] opened 2020-03-07 07:05 UTC
browser: Firefox 73.0.1 (64-bit)
OS: Ubuntu 18.04.3 LTS

The browser's find feature can't be used to find old PMs that contain certain text because the message panel in the page doesn't move to show you the found text.

To reproduce:
1. Find a PM conversation that contains more than one screenful of text.
2. From an old message in the conversation (a message that's off the screen by default), copy a phrase to the clipboard.
3. Scroll back down to the most recent message so that the phrase is off the screen.
4. Launch the browser's find feature (e.g., Ctrl-F) and paste the phrase into it.
5. Use the browser's find controls to try to search for all instances of the phrase (e.g., Ctrl-G or the up and down arrows next to the Find text box).
6. Observe that the find feature reports that it has found the phrase but that the portion of the screen containing the phrase is never moved to the visible part of the screen.

The expected behaviour is that the find feature should work as for any other webpage: when you use Ctrl-G or the arrow buttons, the page should be automatically scrolled so that you can see the portion containing the found text.

**Comment by paglias** [comment] 2020-03-07 11:08
@negue is the scrolling fixable?

There's also the issue that only the most recent messages are loaded in a conversation so even if it scrolled correctly you would only be able to search some messages.

I think we should consider adding our own search functionality but not sure about the priority of the feature. I'm marking this as `suggestion-discussion` until we get some input from @negue

**Comment by Alys** [comment] 2020-03-07 12:26
> There's also the issue that only the most recent messages are loaded in a conversation so even if it scrolled correctly you would only be able to search some messages.

That wasn't a significant problem for the use case I was using. I knew that a particular phrase was in a message some time in the past several months, so I scrolled back and loaded more messages a few times without trying to read any of them until there was about a year's worth of messages (that took maybe 15 seconds), and then I tried finding the phrase.

**Comment by negue** [comment] 2020-03-07 14:05
> There's also the issue that only the most recent messages are loaded in a conversation 

This (and the `load messages`) is by design to not load ALL messages every time you open private messages => less CPU / DB work


A bit more background to the messages list, it uses https://github.com/mercs600/vue2-perfect-scrollbar to have the same scrollbar on all OS (not adding padding, its hidden until hovered), this hides the normal content / scrollbar (`overflow:hidden`)

And I guess this prevents the searching (and rather to scrolling to the found text)


I also had to create a workaround when you select text and scroll up/down, at first this didn't work because of the `overflow:hidden` but I could disable it while the text-selection was in action.

If there are api's for the browser search this workaround could work too.

Otherwise we would need our own search input - or - redesign the messages list to have always a padding for a scrollbar (windows, unix?) - on mac the scrollbar is already hidden by-design.

**Comment by paglias** [comment] 2020-03-07 18:32
> This (and the load messages) is by design to not load ALL messages every time you open private messages => less CPU / DB work

yeah, we don't want to load everything but we might consider a search endpoint for the API.

> Otherwise we would need our own search input - or - redesign the messages list to have always a padding for a scrollbar (windows, unix?) - on mac the scrollbar is already hidden by-design.

Adding our own search input and hijacking the CTRL+F combination might be an easy way but I fear that the moment we introduce it people will, rightfully, expect it to search among all PMs, making it necessary to implement something at the API level

**Comment by negue** [comment] 2020-03-07 19:06
> but we might consider a search endpoint for the API.

yes! , this is probably needed

> expect it to search among all PMs, making it necessary to implement something at the API level

@Tressley what do you think? should the existing search above the conversations be used for that or should we integrate another search somewhere ?

**Comment by Tressley** [comment] 2020-03-09 16:07
PMs built-in search should be searching all PMs. Similar to how the search on Stable still shows results for Pets & Mounts that may be hidden behind "Show More."

Now, the "Show More" for Stable and "Load More" for PMs may not technically work the same, but the search for both of them should.

**Comment by negue** [comment] 2020-03-09 16:27
Currently the PMs built-in search only goes through the loaded conversations (recent message) , I'll rework this for an api search.

I'd suggest this way:
- User enters a string in the PMs built-in search
- the page will lists all conversations with users that had this string
- selecting a conversation would load the (first?) or (last?) message of this string and a range of 5 messages before / after ?

But with this style we'd have to work with 2 types of `load more`, because we'd have a range of messages (don't want to load all messages here):
- before the loaded messages
- after the loaded messages 

or would there be a better way to do it?

**Comment by Tressley** [comment] 2020-03-09 17:44
> selecting a conversation would load the (first?) or (last?) message of this string and a range of 5 messages before / after ?

If we do use this approach, I would encourage a "Jump to recent" feature to allow the user to navigate back to the current conversation.

**Closed as completed** 2020-04-20 14:32 UTC
Labels: priority: medium, status: issue: in progress, section: Messages
