### ISSUE TITLE
single completion Group Plan To-Do don't get marked complete in task board

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#10787] opened 2018-10-27 12:23 UTC
When a Group Plan To-Do is set to "Single - Completes when any assigned user finishes" (`singleCompletion`) and is assigned to or claimed by a player, when that player completes it in their own task list, it moves to their own completed To-Do list but they see the message "Task not found" and the task in the Group Plan task board doesn't get marked as completed.

It is possible that this also occurs with other task types but I haven't tested.

**Comment by VickyKoblinski** [comment] 2018-11-03 19:54
Can we change the priority of this to high? Right now I'm paying the group membership subscription for this functionality and since it's not working, I might have to go ahead and request a refund. I don't want to - I love Habitica - but my team *needs* this. 

I'm not seeing the message "Task not found", but otherwise this description matches my issue.

**Comment by paglias** [comment] 2018-11-05 13:28
@VickyKoblinski sorry for the delay here, we're looking into this

**Comment by paglias** [comment] 2018-11-05 13:45
So i just tried to replicate and the todo is moved correctly to the Completed tab, but the checkbox is missing the completion mark
<img width="438" alt="schermata 2018-11-05 alle 14 43 51" src="https://user-images.githubusercontent.com/589911/48001625-67f70f80-e109-11e8-8550-0f145ab86ff1.png">

@VickyKoblinski is this the same thing that's happening to you? Or the task never ends in the Completed list?

**Comment by paglias** [comment] 2018-11-05 14:06
The issue of the  completed todos checkmark not being shown has been fixed in https://github.com/HabitRPG/habitica/commit/7195ac15b99b0dd969c4f2545ac097f08fc4a516

**Comment by paglias** [comment] 2018-11-05 14:15
And we're thinking about changing the default Shared Completion to `Single
<img width="501" alt="schermata 2018-11-05 alle 15 15 37" src="https://user-images.githubusercontent.com/589911/48003070-ac84aa00-e10d-11e8-9fa1-d92ca4b0ac5e.png">

https://github.com/HabitRPG/habitica/pull/10815

**Comment by VickyKoblinski** [comment] 2018-11-06 04:29
@paglias Not really. Actually, I'm sorry, maybe my bug is a different one. I was referred here. But my bug is similar. I'll leave it up to you if this should be a separate issue. 

My issue is actually with the shared, assigned Dailies. 

Steps:
1) Have a group task board
2) Create a new daily
3) Assign daily to yourself
4) Go to your normal task list
5) Check off item as complete, get experience and gold and increment streak counter
6) Go back to group task board
7) *BUG* Assigned task is still orange, cannot be checked, and appears incomplete to all group members. Streak is 0 (Important).

**Comment by paglias** [comment] 2018-11-06 11:19
@VickyKoblinski thanks for the details, I'll get back to you as soon as possible regarding your issue. Thanks for your patience

@Alys regarding the original issue, do you think the changes listed at https://github.com/HabitRPG/habitica/issues/10787#issuecomment-435886923 and in the comment about that are enough to handle the problem? I've not been able to reproduce the `Task not found` issue (there's more discussion in Slack)

**Comment by Alys** [comment] 2018-11-06 11:35
I'm not getting the "task not found" error now so something has fixed that, or it was an intermittent error that occurs only under certain (currently unknown) circumstances.  The checkmark change sounds like it will fix the other part of the problem. I'm fine with this being closed. We can open another if needed. I'm not closing it myself now in case you want to keep using this issue for @VickyKoblinski's bug.

**Comment by paglias** [comment] 2018-11-08 09:59
@VickyKoblinski we've discussed your report internally and it's probably due to some confusion on how dailies are meant to work in group plans.

The shared completion setting is only available for To-Dos, so it's normal that the dailies in the group plan tasks page aren't marked as completed. We're considering changing the behavior so that dailies get marked as complete as todos but right now the correct behavior is for them to remain unchecked

**Comment by VickyKoblinski** [comment] 2018-11-10 01:00
@paglias Thank you for looking into this. I think it'd be really helpful in the present time while determining if that functionality is going to be added, is if that's made clear, both during sign up and in the UI (maybe a warning when trying to add a daily, or disabling it, or a message saying "coming soon" - right now, from a UX perspective, it appears broken). 

I'd be really excited to see this added though! Thanks again :)

**Comment by SabreCat** [comment] 2018-11-10 17:04
@VickyKoblinski Thanks for the feedback! Group Plans will get some long-due attention soon after we complete this overhaul of username functionality, so changes are coming.

**Comment by kirsty-tortoise** [comment] 2018-11-14 23:55
See #10690 for @VickyKoblinski's issue, I think.

**Comment by paglias** [comment] 2018-11-18 19:11
I'm going to close this one as the original issue reported at the top has been fixed, #10690 covers the dailies issue and for the switch to Single Completion as the default option there's a PR although it'll need some internal discussion

**Closed as completed by paglias** 2018-11-18 19:11 UTC
Labels: priority: important, help wanted, section: Group Plans
