### ISSUE TITLE
Cannot Join Challenge due to "Entity Too Large" Error

### ISSUE THREAD

**Issue by Luthien22** [HabitRPG/habitica#5772] opened 2015-08-12 15:30 UTC
I tried to join [the happy list challenge](https://habitica.com/#/options/groups/challenges/2def5ee7-291b-4ec0-860e-33c2d3d09551) that is currently live in the tavern, but whenever I try to join it I receive an error message stating "Entity too large".

**Comment by crookedneighbor** [comment] 2015-08-13 12:50
This is a duplicate of #1471 so I'm going to close this. If you'd like to track the progress of the bug, you can do so by clicking the subscribe button on that issue. 

If you'd just like me to add you to the challenge, I can do that if you give me your user id. You can find it in [Settings > API](https://habitrpg.com/#/options/settings/api). Be sure to only copy the User ID and _not_ your API Token.

**Closed as completed by crookedneighbor** 2015-08-13 12:50 UTC
