### ISSUE TITLE
Quests disappear

### ISSUE THREAD

**Issue by CodeFoodPixels** [HabitRPG/habitica#4152] opened 2014-10-16 19:55 UTC
I set a quest for my party, waited 7 hours and then it disappeared.

User ID: ca2b5cc5-4d73-468d-af98-ff810c1eaf3e
Group ID: f238355c-335a-405c-a9c4-d1ffb01631da

This issue has occurred with shorter timeframes. This instance was on Chrome 38 on Linux Mint 15. Previous instances have occurred on Chrome 37 on Linux Mint 17 and the Android App on Android 4.4.4

**Comment by ArlieS** [comment] 2014-10-17 15:13
In my case, the disappearance seems to have been instant. Now I can't load the party screen, so it might be a different problem. Creating an issue of my own, but it might really be a dup.

**Comment by Alys** [comment] 2015-08-15 13:09
@lukeb-uk I'm very sorry that we never responded to this. :(  I'm closing this on the assumption that the problem isn't still happening, but please tell us if it is.

**Closed as completed by Alys** 2015-08-15 13:09 UTC
