### ISSUE TITLE
Setting Dailies Repeat days off by one day

### ISSUE THREAD

**Issue by murfrosoft** [HabitRPG/habitica#6663] opened 2016-02-05 04:03 UTC
I have noticed that all of my repeating dailies are off by one day.  For example, if I flag a daily to repeat on Monday and Wednesday, they are instead showing up as active on Tuesday and Thursday.

This 'might' have happened after I changed my cron job end of day from midnight to 11pm... but I'm not sure.  It's been a bug for awhile, and I hoped that it might go away after time, but it has not.

This is my first bug post... please let me know if I can provide more information.  Thanks.

UUID:  ca3f4642-5fb7-475f-9872-4b9594db7a44
Operating System:  Windows 8.1
Browser: Chrome

**Comment by Alys** [comment] 2016-02-05 04:59
This is expected behaviour when you've set your Custom Day Start time to 11pm, because what that setting is saying is that each "Habitica day" doesn't start until 11pm on the next "real world day". I.e., in Habitica, it's still counted as Tuesday until 11pm on Wednesday. For more information, see "Examples and a Warning about Late Custom Day Start Times" in the wiki's page about the Custom Day Start time : http://habitica.wikia.com/wiki/Custom_Day_Start

If you have questions, you're welcome to comment here! We'll still see them and answer you even though I'm closing this now.

At some time in the future, it's likely that there will be an option to set the Custom Day Start time back one hour instead of forward 23 hours, which is probably what will suit you better.

**Closed as completed by Alys** 2016-02-05 04:59 UTC

**Comment by murfrosoft** [comment] 2016-02-05 05:09
Oh thank you!  I'm sorry I missed that explanation in the wiki, but it makes sense.  Thank you for the feedback.

**Comment by Alys** [comment] 2016-02-05 05:18
No worries! There is a LOT of material on the wiki, it's easy to miss things. :)
