### ISSUE TITLE
Checking Daily post-midnight, pre-later start time counts for both days

### ISSUE THREAD

**Issue by mojganin** [HabitRPG/habitica#1706] opened 2013-11-01 17:55 UTC
I've changed my daily start time to 4AM. Ever since I changed that, I've encountered some odd behavior. It seems that if I check off a daily after midnight, but before 4, I am not penalized, and it counts as having been done for the previous day, as it should. 

However, when I wake up the next morning, the item is still checked off. It's as though whatever function resets the tasks and checks for streaks doesn't look at the day start time.

For instance, on Wednesday, I flossed and worked on my dissertation, so I checked off both those items before going to bed at some point after midnight. But, all day yesterday, they were still checked off, preventing me from checking them for Thursday (which is good, since I dropped the ball on both). Now, today on Friday, neither is checked off (correct), but my streak continues for both (incorrect). The streak count does not include Thursday—Writing is at 2 for Tuesday & Wednesday—but neither did Thursday break the chain. As far as my Dailies are concerned, Thursday didn't exist.

**Comment by mojganin** [comment] 2013-11-01 17:58
Dupe of #1057?

**Comment by lefnire** [comment] 2013-11-04 02:54
yeah, I believe dupe of that one. let's continue convo there

**Closed as completed by lefnire** 2013-11-04 02:54 UTC
