### ISSUE TITLE
When saving guild description, the selected categories briefly appear as 'String " not found'

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica#12970] opened 2021-01-16 15:04 UTC
Steps to reproduce:

- Go to edit a guild 
- Press "Update guild"
- Watch the "Categories" section flicker to 'String " not found'

![image](https://user-images.githubusercontent.com/8144640/104815371-fa2bef80-580b-11eb-8150-8038ca04a8d9.png)

The categories are saved correctly, so there's no issue there, so this *seems* to be a minor cosmetic issue.

**Comment by Alys** [comment] 2021-01-17 06:41
For the benefit of anyone investigating the cause of this, it's been happening for months, possibly many months. I've noticed it several time. It's never occurred to me to log it for a fix though, so sorry! Thanks shanaqui for doing this. 

When I've seen it, it's always been a temporary cosmetic issue, just as shanaqui says.

I'm marking it as help wanted.

**Comment by shantanu96** [comment] 2021-01-19 07:16
Hi, can I take this issue?

**Comment by Alys** [comment] 2021-01-19 10:12
@shantanu96 yes, thank you! Post here if you have questions.

**Comment by shantanu96** [comment] 2021-01-23 06:25
@Alys So while debugging the code I found this line of code to be the issue:
https://github.com/HabitRPG/habitica/blob/c001831e63e1904727f59d7fc8137ae79af05281/website/client/src/components/groups/groupFormModal.vue#L610-L619
The `workingGroup.categories` originally has a string as its array elements, but in the above code, it is converted to an array with objects before sending it to the server. So when you click on Update Guild it shows ` string '' not found`

So should I create a new variable for displaying categories and use `workingGroup.categories` for the server request.

**Comment by benkelaar** [comment] 2021-01-23 20:54
I think the object array is being assigned so that object array is also available when emitting the `updatedGroup` event.  To be certain of this you can look at how listeners for this event treat the array.

However, in line https://github.com/HabitRPG/habitica/blob/c001831e63e1904727f59d7fc8137ae79af05281/website/client/src/components/groups/groupFormModal.vue#L621 a copy of `this.workingGroup` is already being created.

So if you just set the object array on this copy instead of on the original state and emit that copy (`groupData`) instead of `this.workingGroup` you'll get the same behaviour without affecting the layout code and without having to introduce extra bookkeeping.

**Comment by shantanu96** [comment] 2021-01-24 07:06
@benkelaar Thanks for your help

**Closed as completed** 2021-01-25 22:44 UTC
Labels: priority: minor, status: issue: in progress, section: Guilds
