### ISSUE TITLE
Potion/Egg Drops not getting a pop up

### ISSUE THREAD

**Issue by marphod** [HabitRPG/habitica#1535] opened 2013-09-14 13:38 UTC
Since the new site, I've apparently been collecting Eggs and Potions, but I've never gotten prompted about a item drop.

I only know if  have had any drops when I check my inventory and compare it against my previous state.

It is possible that this is a result of using a pop-up or script blocker on my end, but I have whitelisted almost everything to do with HabitRPG.

**Comment by lefnire** [comment] 2013-09-14 14:06
dupe of https://github.com/lefnire/habitrpg/issues/1394

**Closed as completed by lefnire** 2013-09-14 14:06 UTC
