### ISSUE TITLE
When viewing anyone else's profile in lightbox, the Equipment section shows you YOUR gear, not the other person's

### ISSUE THREAD

**Issue by TheOfficePicnic** [HabitRPG/habitica#2055] opened 2013-12-19 04:17 UTC
Title says it all. No matter whose profile you're viewing, the gear listed is the gear that YOU have equipped currently, not the other person's, as intended.

**Comment by SabreCat** [comment] 2013-12-19 04:25
Duplicate of #2010 .

**Closed as completed by SabreCat** 2013-12-19 04:25 UTC
