### ISSUE TITLE
MIsalignment in some pages due to "Shrink Your Habitica Tasks" Stylish theme

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica#11687] opened 2020-01-02 22:23 UTC
![image](https://user-images.githubusercontent.com/8144640/71696958-64632500-2dae-11ea-9846-b03c54f9d802.png)

Reported by @Nakonana (33bb14bd-814d-40cb-98a4-7b76a752761c).

_edit 2020-01-23:_ [this comment](https://github.com/HabitRPG/habitica/issues/11687#issuecomment-577458274) explains the cause.

**Comment by Kevin-DDR** [comment] 2020-01-03 12:56
I wasn't able to reproduce the issue using Chrome, in English, French or  Русский .
I also tried in a smaller window

It might be linked to the web browser used? IE or Edge perhaps?

![Capture d’écran de 2020-01-03 13-40-40](https://user-images.githubusercontent.com/12892650/71724448-a59c1900-2e30-11ea-85ed-91ef92aec8e3.png)
![Capture d’écran de 2020-01-03 13-48-06](https://user-images.githubusercontent.com/12892650/71724469-ac2a9080-2e30-11ea-873d-0d7aa0de2ae1.png)
![Capture d’écran de 2020-01-03 13-51-16](https://user-images.githubusercontent.com/12892650/71724477-b2207180-2e30-11ea-8c31-05069c443c69.png)

**Comment by citrusella** [comment] 2020-01-04 08:11
I've no idea if it happens in Edge (pre-Chromium or post-Chromium) but--after a really rocky time getting a test account set up because IE just couldn't part with the cache I guess and then just refused to run without freezing so I had to pull out an entire second computer--but IE11 (11.914.17763.0) on Windows 10 does not have this issue (though it *does* have an issue where absolutely no actions seem to show up until it gets a full reload, syncs be darned ._.). No idea if it might be an issue on Windows 7 differently somehow (the version there specifically is 11.0.9600.18537IS and is probably behind even if the "up-to-date" Windows 7 version number is normally behind the Windows 10 version--it's had issues updating no matter how I try it for years).

(I didn't think to test in a different language than English, though, and I've already shut the other computer down for the night...)

**Comment by citrusella** [comment] 2020-01-04 19:11
Also doesn't happen on Edge or Edge Beta in English. (I, again, didn't think to test outside English, *gah*, but in this case it also probably would have annoyed the person I was trying to quickly borrow the computer from.) Is there anything special about Russian that would be more likely to make that happen?

**Comment by Kevin-DDR** [comment] 2020-01-04 19:16
I tried it just in case the different Alphabet might have affected the layout. (Just a wild guess frankly)
If Edge isn't the issue, I'm not quite sure where it could come from

**Comment by Alys** [comment] 2020-01-23 01:03
Nakonana helped us with some more troubleshooting and found that the problem is caused by the [Shrink Your Habitica Tasks](https://habitica.fandom.com/wiki/Shrink_Your_Habitica_Tasks) Stylish theme so I'm closing this issue. I'll update the theme's wiki page to indicate that this is a known bug.

For the record, it causes some other pages to also show the same problem (e.g., [Overview for new Users](https://habitica.com/static/overview)), and happens with English not just Russian.

I'm about to change the name of this issue to 'MIsalignment in some pages due to "Shrink Your Habitica Tasks" Stylish theme'

**Closed as completed by Alys** 2020-01-23 01:03 UTC

**Comment by Nakonana** [comment] 2020-10-12 06:43
@Alys I think, I've found out what part of the code is causing the issue:

    ".offset-3 {",
	"margin-left: -26% !important;",
	"}",

At least it fixes the FAQ, Overview for New Users pages and the misalignment in the guild member list header. (have yet to check pop-ups).

**Comment by Alys** [comment] 2020-10-13 10:22
@Nakonana Oh nice! Removing those lines from the extension does fix the problem - well done! I've added that to the bug box at the bottom of the [Shrink Your Habitica Tasks](https://habitica.fandom.com/wiki/Shrink_Your_Habitica_Tasks) wiki page (feel free to edit it further if you wish). Thanks!
