### ISSUE TITLE
keeping track of string typos/missing spaces

### ISSUE THREAD

**Issue by deilann** [HabitRPG/habitica#2582] opened 2014-01-26 19:01 UTC
Okay, so, I don't have time to take care of these, dealing with everything else right now, so I'm opening this ticket to list all of the stuff that got accidentally a little mussed with the switchover.
- [x] missing whitespace between the number of guild gems and "Guild Gems" in guilds
- [x] conText is being used twice, showing the wrong info for the CON Tooltip
- [x] Purchasing quests asks if you want to buy this "quests" (conflict with adding modal?)
- [x] Actually, purchasing in general just has issues
- [x] If you're leading a guild, the edit button is EditGroup
- [x] Settings has "User Id" and "Api Token"
- [x] Guild Invites display no space between guild name and "Invite to"
- [x] double space when feeding pets
- [x] "Accommodate" is misspelled at the features page
- [x] Two-handed gear message says "two-handled"

**Comment by marcelosizer** [comment] 2014-01-26 19:45
Fixed by #2583 and [habitrpg-shared #119](https://github.com/HabitRPG/habitrpg-shared/pull/119).

**Comment by deilann** [comment] 2014-01-26 19:54
Awesome, I'm gonna keep this open, so we don't get 20 million issues about these things, and they can all be listed here.

**Comment by marcelosizer** [comment] 2014-01-26 19:55
Can you make a checklist then?

**Comment by deilann** [comment] 2014-01-26 20:04
Done

**Comment by deilann** [comment] 2014-01-26 20:52
Got another one -- attempting to purchase quests asks if you would like to buy "this quests"

**Comment by SabreCat** [comment] 2014-01-27 02:21
If you're leading a Guild, the edit button is "EditGroup"

**Comment by deilann** [comment] 2014-01-27 02:22
Updated.

**Comment by SabreCat** [comment] 2014-01-27 02:26
On Settings page, "User Id" and "Api Token" should be "User ID" and "API Token"

**Comment by marcelosizer** [comment] 2014-01-27 02:37
@SabreCat's strings shall be fixed with [habitrpg-shared #119](https://github.com/HabitRPG/habitrpg-shared/pull/119).

@deilann the quests issue is happening with everything that you try to buy. It's an issue with the variable `string` on the `purchase` function on `inventoryCtrl.js` that is not working as intended. For instance, if you try to buy the saddle it asks if you want to buy **food**.

**Comment by deilann** [comment] 2014-01-27 02:39
Added. I'm separating other things to purchase because of the possible quest modal.

**Comment by marcelosizer** [comment] 2014-01-27 16:01
Actually it doesn't conflict as after the modal the same confirmation prompt is displayed, so it's the same error and it will still be there if the quest modal is added.

**Comment by deilann** [comment] 2014-01-27 16:19
ah, k, didn't look close enough at that

**Comment by deilann** [comment] 2014-01-28 18:29
Can we keep this open so we don't get 8 million issue threads on typos and can keep it all in one place?

**Comment by paglias** [comment] 2014-01-28 18:30
I tought it was another one, sorry

**Comment by marcelosizer** [comment] 2014-01-29 02:43
As suggested by @deilann I'm going to do a modal for the items on the market similar to #2533.

**Comment by deilann** [comment] 2014-01-29 23:38
Got another one:
Guild invites display
`You're Invited ToGUILDNAME`

**Comment by marcelosizer** [comment] 2014-01-30 00:12
Fixed. =p

Will be up when string interpolation is finished.

**Comment by deilann** [comment] 2014-01-30 00:18
sweet -- you are spot on these

**Comment by marcelosizer** [comment] 2014-01-30 00:21
I have all of those files opened as I'm working on them, so I just grep the folder, see where the error is and edit there.

**Comment by SabreCat** [comment] 2014-01-31 03:44
Rebirth prestige tag tooltip: "Reborn, max level##" (missing space)

**Comment by SabreCat** [comment] 2014-01-31 03:45
Ah wait, maybe it was fixed already. Saw that earlier today and made a note, but after a refresh I'm not seeing it. Never mind!

**Comment by marcelosizer** [comment] 2014-02-07 18:39
I fixed the purchasing things, though a proper fix will come with the purchase modal.

**Comment by deilann** [comment] 2014-02-11 10:18
feeding pets has an error, too

**Comment by hattieshoe** [comment] 2014-02-21 06:03
On the challenges page, the challenge creators are listed as "byXXXXX" (no space between "by" and creator's name).

**Comment by thepeopleseason** [comment] 2014-02-21 11:31
@hattieshoe I've got a pull request out to cover that one, and the lack of a space between "Seewhat prizes" in the contributor awards modal:
HabitRPG/habitrpg#2875

**Comment by denis-sokolov** [comment] 2014-04-20 01:37
The last item on the list, "double space when feeding pets" does not seem to exist anymore:
![1](https://cloud.githubusercontent.com/assets/113721/2749851/4936b33e-c82c-11e3-9162-63a67e02bdd9.png)
![2](https://cloud.githubusercontent.com/assets/113721/2749852/4938a7e8-c82c-11e3-80a3-56ffcbbd65d4.png)
![3](https://cloud.githubusercontent.com/assets/113721/2749853/4946f8c0-c82c-11e3-851c-5ce8ad2a2edb.png)

With that gone the entire issue can be closed.

**Comment by deilann** [comment] 2014-04-20 01:38
I'd actually prefer to keep this open as an ongoing issue, rather than opening a ticket every time a concat error shows up.

**Comment by ghost** [comment] 2014-04-20 09:04
Could you please consider #3224 

> "Accommodate" is misspelled at the features page

the separate ticket was created according to advice by @paglias

**Comment by deilann** [comment] 2014-04-20 09:05
Thanks @GitHubSphinx ! Added to the list -- gonna close #3224 for housekeeping.

**Comment by ghost** [comment] 2014-05-01 16:24
From Transifex, about messageTwoHandled: "<%= gearText %> is two-handled" by bouncyballboy.

> Is this really supposed to say two-handled? Not two-handed? Or am I just missing some context?

You know, I'm not a native English speaker, but I'd rather support the question as "two-handled" seems like something having two handles, not something handed with both hands.

**Comment by deilann** [comment] 2014-05-01 16:35
Native English Speaker says: it's two handed.

**Comment by paglias** [comment] 2014-05-02 10:35
@deilann @GitHubSphinx fixed

**Comment by crookedneighbor** [comment] 2014-12-03 14:24
@deilann and @paglias do you still want to keep this open? Or close this and log new instances in #3593?

**Closed as completed** 2014-12-05 15:10 UTC
Labels: good first issue
