### ISSUE TITLE
Text overflow on task checklists

### ISSUE THREAD

**Issue by fentie** [HabitRPG/habitica#10429] opened 2018-06-05 01:37 UTC
### General Info
  * UUID: 8f4a567a-038c-4c48-9941-fea2dc1d2845
  * Browser: Chrome
  * OS: OSX

### Description
When a long, unbroken word (like a URI) is present in a task checklist, it can overflow the boundaries of the column. Add an appropriate CSS overflow property

https://imgur.com/a/IMd1YIC

#### Console Errors
Zero, zip, zilch, nada, niente

**Comment by vinmegamitensei** [comment] 2018-07-02 18:51
I can fix this, just need an 'Ok' to start. Thanks!

**Comment by paglias** [comment] 2018-07-02 19:05
@vincecampanale go ahead!

**Comment by Alys** [comment] 2018-09-09 02:37
I'm reopening this because it's happening again for at least one person (below) although I'm not able to reproduce it on Firefox 61.0.1 64-bit on Ubuntu. I've asked papierukartka to turn off extensions and styles to see if that fixes it. This issue is on hold until we hear more (basically I just want to record these details somewhere for now so they don't get lost).


_papierukartka (743d556b-6603-47e9-bf68-0e0b395208c3) writes:_
Hey, I've just noticed that checkbox description is not displayed correctly when creating a checklist for todo/habit on Firefox(I'd look into overflow-wrap property). Besides, it looks like checkbox description is using a slightly different font than dailiy/todo as it's first choice (Roboto instead of Roboto-condensed); dunno if that's a bug or a feature.
* As is: Checkbox item description text gets out of the form boundaries.
* To be: Checkbox item description should be wrapped inside the box.
* Screenshot: _[below]_
* I've found this issue on Firefox 62.0 64bit; on Chromium 68.0 text is wrapped correctly, but the font is still big - as I've said, dunno if feature or bug.
* Steps to reproduce:
   1. Create a daily or a todo
   2. Add an checklist item to previously created daily/todo in form of a long link or a string without spaces (ex. Lorem_ipsum_dolor_sit_amet,_consectetur_adipiscing_elit._Donec_est_magna,_elementum_a_turpis_nullam.)
   3. Click "Save"

![image](https://user-images.githubusercontent.com/1495809/45260512-0843f700-b42d-11e8-848f-6440315e7981.png)

----

_Also GoatGeek (7dc77b23-6c90-4bae-888e-83002baa953b) commented:_

It looks like that's more related to word-wrap (and the future overflow-wrap would be a better solution).

**Comment by sliwkr** [comment] 2018-09-11 22:22
Hey @Alys, thanks for taking the time. I've verified it with extensions disabled; the issue still persists. Additional information:
Linux 4.17.0-1-amd64 Debian 4.17.8-1 (2018-07-20) x86_64 GNU/Linux
using screen resolution 1920 x 894
Let me know if you need any more information.

**Comment by sliwkr** [comment] 2018-09-15 10:44
Hey, it looks like something similar occurs on Firefox 32bit on latest Lubuntu. The checkbox description text doesn't get wrapped inside the box (see screenshot)
Details:
Screen resolution: 1024x600
Browser: Firefox 62.0 32bit
Distro: Lubuntu 32bit (Linux 4.15.0-33-generic #36-Ubuntu i686 GNU/Linux)
![zrzut ekranu z 2018-09-15 12-42-38](https://user-images.githubusercontent.com/10583086/45585472-18544e80-b8e5-11e8-9883-a8dac176a636.png)

**Comment by Alys** [comment] 2018-11-02 05:20
@papierukartka Thanks for that information and sorry about the delay in our reply! I've taken this off hold and marked it as help wanted.

**Comment by ianoxley** [comment] 2018-11-12 21:01
Is it OK if I take a look at this?

**Comment by paglias** [comment] 2018-11-13 07:48
@ianoff sure!

**Closed as completed** 2018-11-17 10:01 UTC
Labels: priority: minor, status: issue: in progress, section: Task Page
