### ISSUE TITLE
Hitting enter in the title of a task in edit mode sets a due date

### ISSUE THREAD

**Issue by lorian** [HabitRPG/habitica#2199] opened 2013-12-31 00:17 UTC
Previous behavior (before checklists): hitting enter while cursor was in title of task would close edit mode.
Current behavior: hitting enter in task title now sets due date to today, which is super unexpected.

**Comment by lefnire** [comment] 2013-12-31 00:24
Blah, Firefox! _shakes fist_. Works fine in Chrome & Safari. Not sure what could be causing it, probably angular-bootsrap-ui datepicker within a form. I'll take another peak at where we are for a bootstrap & angular-ui upgrade.

**Comment by lorian** [comment] 2013-12-31 01:07
Firefox: The new IE!

**Comment by patena** [comment] 2014-01-28 18:36
Dammit, Firefox! Yeah, this confused me a lot back when I started.

**Comment by negue** [comment] 2014-10-11 23:13
Can't reproduce. 

I'll close this, if it happens again, we'll reopen it.

**Closed as completed by negue** 2014-10-11 23:13 UTC
