### ISSUE TITLE
New Achievements and Badges: Grew X Mounts

### ISSUE THREAD

**Issue by beffymaroo** [HabitRPG/habitica#8619] opened 2017-03-29 22:14 UTC
These new achievements and badges are ready to be implemented! These should be received when a player grows the number of mounts indicated by each badge. The badge images and the names/mouseover text for the user achievement page can be found here: 

https://trello.com/c/ZP7TlViF/11-grew-x-mounts-badges

_edit by Alys:_  See the [comment below](https://github.com/HabitRPG/habitica/issues/8619#issuecomment-317213127) by @guyguy2001 which contains a lot of useful information for implementing this feature.

**Comment by guyguy2001** [comment] 2017-05-04 20:36
I started working on it. It's my first contribution (specifically to habitica), so it might take a bit for me to understand the system and where to put everything, but there shouldn't really be any problem.

**Comment by Alys** [comment] 2017-05-04 22:09
@guyguy2001 Thank you! Comment here if you have questions or need advice!

**Comment by guyguy2001** [comment] 2017-05-06 12:07
Is it X unique mounts, or X mounts in general (ie grew the same mount twice)?
Also- I have to ignore released mounts that were received before adding this achievement, if they didn't make it to a full set of 90 for the Mount Master achievement, as I can't know if they exist or not afaik.
One question though- Is there a function that I can count on as being the first one to work when I load the page, in which I will calculate the starting number of mounts the player own (as in mounts received before releasing this achievement)?

**Comment by guyguy2001** [comment] 2017-05-08 17:50
How should the badges behave? A single badge with the blue counter that updates the image as you progress (and shows the achievement message on the 1/10/25/50 milestones)? If not, then how?

**Comment by guyguy2001** [comment] 2017-05-12 20:58
Sorry for taking  a lot of time, my computer was in repair. However I know exactly what to do to the end of this, so it really shouoldn't take more than a day or two now.

**Comment by guyguy2001** [comment] 2017-07-22 21:58
After a lot of time fighting with bugs and staying at the same spot for a long time, I think I should give this one up and let someone else come at this with a new perspective. **HOWEVER, PLEASE USE MY FORK OF IT AS A STARTING POINT**. It will make things so much more easier for you, as I also added a new badge type for this. Some notes and todos for whoever takes this on:

- The branch in my repo is mountachieve

- I integrated the pet collector achievement into this, both to see how the error I had behaves there (exactly the same apperently), and to make the formatting of the two identical. The 2 achievements are very similiar in nature, so it shouldn't take additional work doing them together (in fact it will save time in the larger picture)

- **Retrospective count:** The achievement should be able to track mount growths on mobile / before the addition of the achievements. The system I put in place has a major problem: Lets say that you have 0 mounts, but the achievement shows 45 because you released all of your mounts for gems. Now, if you get a mount on mobile, and go back to the browser to grow another one, it says "I got 2 mounts, which is less than the achievement (45). I'll add one to it then", which means that it **doesn't count the mounts that were raised on mobile, because the retrospective count wasn't smart enough**. I think it could be solved by saving how many pets you had the last time you were on the browser.
- **Retrospective count:** I am not sure how to count pets. do we get a beast master achievement when we get a triad bingo? We need to check.
- **Retrospective count:** It could be that some numbers aren't right, that was trynig to find the bug. everything should be either 90 or 180, depending on the rules of triad bingo above.
- **Retrospective count:** READ MY LAST COMMENT
- **The bug:** for some reason, the value of the achievements jumps by 91* for no apperent reason. at first it was whenever I raised a new mount, but now it's only when I reset the server. *It seems to jump to the current number of mounts + 91, but **before it enters the function**. I am not really sure about the details though.
- **UI and strings:** I didn't yet finish the announcment screen in achievement.jade, which needs more strings / removing the placeholders for them. I am pretty sure however that I did finish the achievement itself in the profile though. I split the announments to 1, 10, 25, 50, as I didn't find a way to create one generic message (hope to be proven wrong though!)
- **Tests:** This thing needs a ton of random tests. What I mean is you can think of it as having 3 actions: growing/buying a mount, getting a mount through cheats (or through android / in the past),  and releasing mounts. we need to make sure that everything that happens makes sense, for example, if you raise 1 mount on android and then 1 normally, no matter how does the mount count relate to the retrospective count, it absulutly has to understand that it is 2 mounts.
- **Time traveler / future support:** Support should be added to buying mounts / pets from the time travelers (the ui->code there is pretty much the same as in the inventory afaik, so it shouldn't really be a big problem). ALSO, there should be a note somewhere to make sure all future events trigger this script, OR BETTER: have a section in the retrospective count that looks at gen 2+ pets, which I think is the best option for this.
-Most of the pet stuff was done by @corinnaj, so yeah, get credit :P

While I did quit this, I will still be online and maybe actually contributing on another issue, so please, if you need me to explain something on what I have done, go into a problem that I might have already been through, or even want me to work on something that you can't do on your own, message me on mail or in Habitica (Guy Geva), and I will help as much as I can.

**Comment by Alys** [comment] 2017-07-23 06:56
@guyguy2001 Thank you so much for all those detailed notes! I've marked this as help welcome and put an edit in the top post to direct the attention of other coders to your comment. If the final fix is based on your code, you'll get partial credit towards a contributor tier for it. Please remind us of that if you notice we've forgotten when the issue is closed!

**Comment by LunarGem** [comment] 2017-07-23 10:28
I could maybe try this next? I'm experiencing an odd amount of motivation this week :P

**Comment by Alys** [comment] 2017-07-23 10:45
@LunarGem Please do, thank you! See also https://github.com/HabitRPG/habitica/issues/8620 in particular the final comment from @guyguy2001. If you do a pull request that fixes both this issue and that one, please write "fixes https://github.com/HabitRPG/habitica/issues/8619 and fixes #8620" in the title of your PR. That will cause both issues to be closed automatically if your PR is merged.

**Comment by guyguy2001** [comment] 2017-07-25 20:44
@LunarGem It took me an absurdly long time to realize this, but server side functions, being server side, apply to all platforms. Therefore, you don't need to track achievements gained on android respectively. Only 2 kinds of mounts/pets are left to track in retrospect afaik- past ones, and single time ones (like events). For the event ones, I would assume all of them are gen 2 (We gotta ask that to a dev though), and therefore you can just have seperate retro counts for gen 2 (unreleaseable) and gen 1 (releaseable) pets and mounts.

**Comment by LunarGem** [comment] 2017-08-15 23:06
I'm having some trouble setting up my dev environment for this. I got some errors setting up the Mongo database. I didn't get a response in the aspiring blacksmith's guild, should I try again or can someone help me here?

**Comment by guyguy2001** [comment] 2017-08-16 15:54
Sorry for taking so long to write this.
(I will write it for windows, should be similiar for mac / linux)
Whenever I want to run mongo, I just open cmd (no matter where) and write 
```mongod```. If it gives you an error like
```
C:\data doesnt exist
```
Just create the folder that it wants.
If it gives you other errors just remove all the content __inside of__ c:data\another-folder\

**Comment by LunarGem** [comment] 2017-10-14 20:33
I'm not sure how to use your fork as a starting point, @guyguy2001, especially since the redesign. Is that still applicable? It seems as if a lot of folders disappeared when the codebase was restructured.
EDIT: Nvm, actually using my brain for a change fixed most of the problems I was having. 😛 The controller files are missing after the redesign though...

**Comment by guyguy2001** [comment] 2017-10-15 18:11
@LunarGem you have 2 "html" files to worry about: the achievement screen and the popup message. just copy paste any of those, as there are a lot of examples like them. (Just hit inspect on an achievement in the site, check for something like the element id or name, and look for it in the files. I use the grepWin program for stuff like that). (edit) Tell me if you need help finding it though :P

**Comment by LunarGem** [comment] 2017-10-15 18:51
@guyguy2001 I've actually made a ton of progress thanks to the code you did, I'm about finished making edits and I'm about to start testing to see where any problems are.

**Comment by lemoness** [comment] 2017-12-07 06:10
@LunarGem - Hi there! Just checking in -- what's the status of this?

**Comment by LunarGem** [comment] 2018-01-18 18:34
Haven't moved since October, unfortunately, haven't actually had a dev environment until this week. I'll see what I can do about this over the weekend maybe.

**Comment by beffymaroo** [comment] 2018-04-12 18:39
@LunarGem Are you still working on this issue? Please let us know. Thank you! :)

**Comment by guyguy2001** [comment] 2018-04-14 13:43
@LunarGem I though about it a few days ago, but forgot to send until now:
If you encounter the error which I encountered, where the achievement counter jumps from 2 to about 300, it might be because it is a string and you used it as a number. If you suspect that that is the case, try logging the `typeof` of that counter.

**Comment by LunarGem** [comment] 2018-04-17 14:20
Ok, so my keyboard is still wonky, and I have a *lot* of work to do before graduation. I still really want to finish, though.

**Comment by beffymaroo** [comment] 2018-04-17 19:59
@LunarGem If you think you'll be able to get to it relatively soon, I'm happy to leave it as "in-progress" for now so you can continue working on it.

**Comment by beffymaroo** [comment] 2018-05-16 22:14
@LunarGem Since we haven't heard from you in a while, I've changed this issue to Help Wanted. If you'd like to pick it back up just let me know!

**Comment by TNychka** [comment] 2018-10-01 17:20
Hey! I can take a look at this!

**Comment by saraolson** [comment] 2019-08-15 17:27
Staff are looking at implementing new user achievements, so we're putting this issue on hold for now.

**Comment by veeeeeee** [comment] 2021-04-22 16:25
We are now tracking these somewhere else to ensure proper handling.

**Closed as completed by veeeeeee** 2021-04-22 16:25 UTC
Labels: priority: medium, status: issue: on hold, type: medium level coding, section: Avatar/User Modal
