### ISSUE TITLE
Quest Scrolls acting up: negative number of quest scrolls

### ISSUE THREAD

**Issue by eiron** [HabitRPG/habitica#2592] opened 2014-01-27 10:02 UTC
I had what seemed to be "-1 scrolls" (actually one The Fiery Gryphon scroll), until I spent 4 gems each on Trapper Santa and Find the Cub. Now I have "1 scroll", which is actually one Trapper Santa and The Fiery Gryphon from before. The Find the Cub scroll never materialised. Any idea what is up?

_edit by Alys 2019-03-23:_

For the current status of this bug, see this comment and any comments after it: https://github.com/HabitRPG/habitica/issues/2592#issuecomment-475829848

**Comment by marcelosizer** [comment] 2014-01-30 20:51
I have -1 scrolls too, my party is currently doing a Fiery Gryphon quest that I started.

**Comment by marcelosizer** [comment] 2014-01-31 13:42
![-1scrolls](https://f.cloud.github.com/assets/6205335/2050840/9275fb00-8a7d-11e3-9a6d-d1aeb7bb1a72.png)

**Comment by marcelosizer** [comment] 2014-02-02 14:58
Got the vice scroll and now I have 0 quest scrolls.
![-2scrolls](https://f.cloud.github.com/assets/6205335/2060452/674519c2-8c1a-11e3-8ad4-37627bfcdccb.png)

**Comment by marcelosizer** [comment] 2014-02-11 11:19
After using Vice Awakens scrolls this is what happened.
![-2scroll](https://f.cloud.github.com/assets/6205335/2136272/4bd0934c-930e-11e3-9c45-0ac3f83e817d.png)

**Comment by lefnire** [comment] 2014-02-12 17:36
Yeah, guarantee due to the ops duplication bug (floating around). @Sinza- I'm gonna make you a GM, feel free to Gem yourself enough to buy back.

**Comment by marcelosizer** [comment] 2014-02-12 17:43
@lefnire actually I still have all my gems as I haven't tried to buy any scrolls since that bug kicked in. I just got the Vice one. Right now all the scrolls that I used worked as they should. I'll just buy and see what happens then, see if my count goes back up.

**Comment by marcelosizer** [comment] 2014-02-12 17:45
Reading my previous posts I didn't explain what happened correctly. The only thing that's wrong with me is the count.

And that message saying that I have no scrolls.

**Comment by extrajordanary** [comment] 2014-02-15 01:15
Not sure if this is most related to this issue or the one I previously posted (https://github.com/HabitRPG/habitrpg/issues/2642) or if it might be something else entirely.

I had purchased 2 each of the Winter '13 quest scrolls. After starting the polar bear mount quest with my party both of my quest scrolls were gone. I should have reported it then, but I was sorta in a "meh" mood about it. But then it did the same thing when I ran the cub quest with my party, my 2 scrolls turned into 0. So best I can figure is that when the quest is accepted it's deleting all of the relevant scrolls instead of just one. 

Additionally, I know that I was on the beta site for the 2nd occurrence, but I can't remember if I was or not the first time it happened. 

For now I'm just not stocking up on more than one quest scroll of any one kind.

User ID: 7c389c86-74c3-419b-9cd7-94baafce2d49

**Comment by deilann** [comment] 2014-02-15 01:21
It's definitely not ALWAYS happening; I've used stacked scrolls before and
not lost all of them.

**Comment by chornsby** [comment] 2014-02-15 12:19
Just lost four gems buying the Gryphon quest when my Quest Scrolls counter was at (-1). I didn't think that one through...

Also, can confirm @deilann's response: I've previously used a stacked scroll and they've decremented correctly.

**Comment by deilann** [comment] 2014-02-15 12:27
@chornsby Wassyer UUID, so I can get you some gems back?

**Comment by chornsby** [comment] 2014-02-15 12:36
@deilann My UUID is: db393d59-b0cc-41ee-998d-e1b7888a6eea

You're a gentleman and a scholar!

**Comment by deilann** [comment] 2014-02-15 12:40
No problem! You should have your gems back. :)

**Comment by Kamsly** [comment] 2014-02-15 22:34
I didn't notice whether or not I had (0) scrolls or (-1) scrolls when I went to buy one. I had 16 gems, went to the market, clicked on the Fiery Gryphon scroll, clicked ok when it asked if I wanted to spend 4 gems. Then I had 12 gems, but no scroll. Then my inventory said I have 0 quest scrolls. I've refreshed and I've logged out and back in again and still no scroll. I posted in the Tavern and Ryan 2.0.7 said to post here and refunded my 4 gems, so now I'm back to 16 gems. I have only ever had one scroll that I previously purchased and used with no problems.

**Comment by maybeimelias** [comment] 2014-03-03 23:03
Today, I started a gryphon quest whilst having 5 gryphon scrolls. Upon my party (4 members) accepting the quest, I returned to my inventory to discover I have only 2 gryphon scrolls remaining. Also, my scroll count is incorrect. Quest Scrolls (6), while I have 2 gryphon scrolls and 5 hedgehog scrolls and SHOULD HAVE 4 gryphon scrolls.... My userID: 516d71d4-8c39-4554-aad6-167d3f6f40ec

**Comment by deilann** [comment] 2014-03-03 23:44
maybeimelias, what's your UUID?

**Comment by maybeimelias** [comment] 2014-03-04 19:26
deilann, not sure what you're asking for so here is a ton of data.
UserID: 516d71d4-8c39-4554-aad6-167d3f6f40ec
API token: [REDACTED]
Group ID: fe361b1d-d831-402b-afb3-8ccd91b2b6bd

**Comment by deilann** [comment] 2014-03-04 21:45
@maybeimelias Please do not ever post your API Token publicly, for a heads up! It's like a password-- I can use it with your UUID (The UserID) to log into your account. I've edited it out of your comment, though.

If you refresh, you should have 8 more gems. :)

**Comment by maybeimelias** [comment] 2014-03-04 21:58
haha, thanks and sorry @deilann ! but here is a fun fact, today I am down to 1 gryphon scroll, and my overall scroll count decremented to 5 but I have 6 and should actually have 9...

**Comment by busterroni** [comment] 2014-03-04 22:31
I can still see the API token because I get sent an email with every reply
to issues. I'm obviously not going to log into their account, but is there
a way to change their API token?

**Comment by Kamsly** [comment] 2014-03-05 16:05
Just chiming in to say I have the API token in my emails, too. Not sure how
many people get notified when this thread is updated, but it's definitely
out there. Might be a good idea to change it if possible. :)

**Comment by paglias** [comment] 2014-03-05 16:08
@busterroni @Kamsly definitively, it needs to be changed.

let's ping @lefnire

**Comment by lefnire** [comment] 2014-03-09 03:38
@maybeimelias I changed your API Token as per the emails issue (security). You'll need to log out and back in, same for any 3rd-party extensions/apps (mobile, chrome extension, etc). Sorry about that :(

**Comment by lefnire** [comment] 2014-03-09 03:39
yeah, we'll definitely want a way to change API Token from API tab

**Comment by hametsunosaturn** [comment] 2014-03-09 19:57
I had the same thing happen, I had 5 Gryphon quest scrolls, started the quest with my party and dropped down to 3 scrolls. I've since bought more, but I still lost the one to mysterious circumstances. My UID is 44566434-9db5-4a89-9138-a67f6b92cfc7

Also, how much warning will we have before the pet scrolls stop being available? Or are those going to stick around longer than non-pet quests? Since we have to do the quest 10 times to get all the pets/mounts (for those of us obsessed with completion), I want to buy enough before they're gone, but with the 25 gem limit, that's two months worth of gems and there's already a new pet quest scroll to buy now.

**Comment by lefnire** [comment] 2014-03-09 20:45
- Pet scrolls will never go away. Any limited-edition scrolls will be expressed as such in a Bailey announcement. 
- We're working on making pet quests more manageable, because at the current rate it will cause player burnout (maybe increase egg drops, or something - @lemoness & @SabreCat were working on a solution IIRC). 
- Scrolls don't drop yet. The intent is that they do, I just haven't gotten to coding it. I promise it's not to milk gem purchases, hopefully someone can do me a PR?
- @hametsunosaturn I set you up some gems for repurchase of lost scroll

**Comment by hametsunosaturn** [comment] 2014-03-09 20:52
I am _so pleased_ to hear the pet scrolls won't go away. I do kinda hope you'll wait a bit on introducing any new pets though, for that exact reason of burn out. It's hard when you've only got a small party. Thanks so much for answering and taking the time to help. And thank you, thank you for the replacement gems.

This game is great and has been really useful for getting stuff done. The glitches are frustrating but I want to keep supporting you guys 'cause it's been so fun.

**Comment by lemoness** [comment] 2014-03-10 21:28
We will be introducing new pets at a rate of 1 a month, but we're
implementing the following two measures to reduce burnout (hopefully).
1. Increasing the number of eggs received per battle to 3.
2. After you've defeated the same Pet Quest Boss 4 times, you can buy that
   Quest Pet egg directly from the Market.I was thinking two gems for the
   price?

@SabreCat, want to continue this conversation here, and maybe get started
on the implementation? Unless it would be more helpful for me to make a
separate Github thread.

**Comment by deilann** [comment] 2014-03-10 21:30
@lemoness I would make it less than 4-- we've got folks saying it takes
their party 3+ weeks to do a quest && 4x is more than enough to get all the
pets and then some-- just not the mounts. I'd suggest after 2 times or even
1 and make the eggs cost the same as other eggs.

**Comment by lemoness** [comment] 2014-03-10 21:34
How about 2 times, then?

**Comment by deilann** [comment] 2014-03-10 21:36
2 sounds perfectly reasonable to me!

**Comment by deilann** [comment] 2014-03-10 21:37
If a quest grants you 3 eggs, doing the quest then gives you 9 gems worth
of eggs, not 6 gems, which I find more appropriate considering the amount
of work a quest can take.

**Comment by hametsunosaturn** [comment] 2014-03-10 22:05
Once you complete the quest X number of times (however many you decide), and eggs can be bought -- would they also start dropping as items? Because the other problem is that these eggs would end up being pay-to-play only, which is a little unfair for the people who genuinely can't afford it. I can buy the scrolls for my party so they can participate in this, but I can't buy eggs for them. 

I still think it would be nice if we could have a community chest for eggs/potions/gems/food to share among the party. Especially when we end up with like, 15 every potion but no pink cotton candy potions. I understand that it could be abused (ex: someone level 60 who has all the pets could give a level 4 party member everything), but like other things in this game, it's the honor system method. (Sorry if this belongs in a different thread, I posted it once somewhere on the suggestions page, but I never saw a response, and it kind of applies to the conversation.)

**Comment by deilann** [comment] 2014-03-10 22:11
I don't want to speak for Lemoness, but no, I don't think these eggs will
drop. You have a few options here:

1) You can continue to do the quests. Your party will continue to get eggs
that way, without having to buy them themselves.
2) You can give gems to your party members via challenges, and then they
can buy the eggs themselves.

I personally don't like the gifting idea because base eggs become pretty
much worthless at the moment, once you have Beastmaster. So while yes, it
is honor system, the player who receives the eggs/potions/food hasn't done
anything to earn them! This is heavily discussed on the Trello "Give Gifts"
card. I feel like the RNG keeping what you from getting what you want is a
major motivator in the game-- and giving gifts/trading gets rid of that
motivation.

Finally, the quest pets are premium. It's not necessarily "unfair" that
players who can't afford gems can't have a special pet. The same vein of
logic would state that it's unfair that they can't get the subscriber items
without subscribing. Pets provide some incentive, yes, but they are an
extra-- not a core feature of the game.

**Comment by hametsunosaturn** [comment] 2014-03-10 22:21
I can understand the point of view of motivation, but honestly, at some point it becomes frustration more than motivation. For example, I have 134 eggs and 121 potions. My teammate has roughly the same number of each. However, we both had issues of getting potion after potion after potion and having the particular ones we need never drop. I had all pink potions and she had all blue potions and while we were still doing the work to earn them, we were both getting really ticked off that we actually weren't getting useful rewards. It was actually a demotivator at that point. 

So I don't consider it "gifting" as you put it, but more working together as a team to achieve goals together. What's the point of a reward if it's not actually rewarding? (Which is probably why I never noticed the "give gifts" card because I don't want it as a gift, I want it as a community treasure chest.)

**Comment by deilann** [comment] 2014-03-10 22:24
A community treasure chest is, in essence, gifting to your party. But let's
move this discussion to Trello.

**Comment by hametsunosaturn** [comment] 2014-03-10 22:47
For anyone following along, wishing to chime in, it was a bit tricky to find. So here's a link: https://trello.com/c/BLIOj4Ty/206-send-gifts

**Comment by lemoness** [comment] 2014-03-11 02:40
To clarify - these pet eggs will not start dropping, they will just be
purchasable. They will never give players any stat item or reward badge
that would give them any advantage over players who aren't paying, or way
to "cheat" the system instead of improving themselves through hard work -
they serve as a cosmetic "extra" to thank all of the awesome people who are
helping to support the project :)

If it's the lack of free quests that worries you, don't fret - more
auto-drop Equipment Quests are coming, as well as gold-purchasable Random
Encounter Monster Quests, so soon non-paying users will have even more
opportunities to use quests to motivate themselves as well :)

**Comment by eiron** [comment] 2014-03-11 10:34
I still have the issue of the missing Polar Bear Cub quest scroll. Any way
of getting that back?

**Comment by casicastiel** [comment] 2014-03-13 17:35
I probably should have mentioned this earlier, but ever since I received(from pt.2) and then used my Vice Awakens scroll, a couple weeks ago, my scroll count has displayed -1, despite the fact that I still have a Trapper Santa lounging around in there.

(Related, possibly: for some reason, I and several of my party members seemed to have received multiple T Santa scrolls, back when they were given out for free — I had three [already used two] without ever buying one, so I'm not too concerned about keeping it if it's not actually supposed to be there.)

**Comment by meganstrickland** [comment] 2014-03-30 21:50
I just noticed that I also have negative scrolls:

![negative-scrolls](https://cloud.githubusercontent.com/assets/3529967/2562593/2ba2293e-b855-11e3-9d25-9f8912961b43.png)

As far as I know, I have not actually lost any scrolls or gems, it's just the count that is wrong, but I don't know what to expect the next time I purchase a scroll (which will probably be today). Any hints?

UID: 73e5125c-2c87-4004-8ccd-972aeac4f17a

**Comment by deilann** [comment] 2014-03-30 23:15
You may not get the scroll. If that happens, ping me.

**Comment by meganstrickland** [comment] 2014-03-30 23:17
Actually, I just tried and it seems to be working. I purchased the scroll and sent the invitation to my party and so far nothing is amiss aside from the inventory screen, which now shows 2 scrolls but a scroll count of 0.

**Comment by deilann** [comment] 2014-03-30 23:19
I'm thinking what it is is that trying to purchase a specific scroll
wouldn't show up. So you have -2 of a specific type of scroll.

**Comment by meganstrickland** [comment] 2014-03-30 23:22
Hmm... Well, the ones in my inventory are Vice's Shade and Fiery Gryphon (which I just "used" but is still pending acceptance from party members). I don't know when my scroll count started being wrong, so I'm not sure which scroll(s) triggered the problem.

**Comment by meganstrickland** [comment] 2014-03-30 23:29
Just a quick note that this is now resolved for me, thanks to help from deilann. It was the Hedgebeast scroll that was "negative", so buying more of them fixed the problem. Inventory and scroll count now match. :o)

**Comment by Mihakuu** [comment] 2014-04-22 14:23
I just tried purchasing a gryphon and deer scroll, but they did not show in my inventory after refreshes but my gems where subtracted. Also my scroll count is 7 when I have 8 showing.
![quest](https://cloud.githubusercontent.com/assets/3769301/2765923/afdbadca-ca29-11e3-8af0-bd5fe43cbd5d.PNG)

UUID 9da65443-ed43-4c21-804f-d260c1361596

**Comment by deilann** [comment] 2014-04-22 14:26
@Mihakuu

One of them is negative and one is zero most likely...

I refunded you your 8 gems. Can you purchase moar another gryphon and deer
scroll?

**Comment by Mihakuu** [comment] 2014-04-22 14:34
@deilann I was able to purchase and receive a gryphon on beta (which fixed my scroll count oddly enough) but the deer quest I purchased on the production side wasn't received

**Comment by deilann** [comment] 2014-04-22 14:39
That's actually what I was expecting @Mihakuu -- so, the deer quest had a
value quantity of -1, but the gryphon had a value quantity of 0. Yay!
You're all evened out.

**Comment by Mihakuu** [comment] 2014-04-22 14:40
but I still dont receive a scroll on the production side. Gems transferred, no scroll.

**Comment by deilann** [comment] 2014-04-22 14:41
Yes, you'll need to purchase another deer scroll. You had -1 deer scrolls,
so now you have 0 deer scrolls.

**Comment by Mihakuu** [comment] 2014-04-22 14:42
Thats very odd @deilann but yes that worked thank you

**Comment by deilann** [comment] 2014-04-22 14:43
The issue has something to do with stacked quest scrolls and the system
taking away too many, reducing it to negative numbers. Which then means you
have to buy multiple scrolls to get back up above 0 and... have them.

**Comment by Mihakuu** [comment] 2014-04-22 14:45
But I only had one of both of those scrolls

**Comment by deilann** [comment] 2014-04-22 14:47
That is good to know. So sometimes the reduce scroll number operation gets
duplicated even when there's only one scroll.

**Comment by ghost** [comment] 2014-05-01 07:24
May I just shoot a suggestion about the workaround?
I gave up programming in school when we had delphi 5 as a major framework and not mastered the skill. So I'm more than out-of-date in the question and simply can't analyze the code myself. Please ignore me if I say it wrong, but the users keep facing the issue, and alongside with searching for the cause can a quick fix be introduced?
Something like a check: when a user buys an item with gems, see if "the-current-count-of this-item-possessed" is <0 make it 1, else just increase by one.

**Comment by deilann** [comment] 2014-05-01 07:27
Sphinx, I actually suggested something similar a bit ago (if quantity < 0,
quantity = 0, then as normal), but I wanted to make sure @lefnire's okay
with a quick-fix that doesn't solve the problem.

**Comment by ghost** [comment] 2014-05-01 07:40
deilann, well I see. Quick fixes are meant to be temporary, but when there are lots of them, the code can really become such a mess... I wouldn't even think about something of the kind if only if it wasn't about "real money" and often happening - and at the same time seemingly easy to be patched (meaning a patch is something of one line, localized in the code and easily withdrawn when the SOLUTION is found).

**Comment by deilann** [comment] 2014-05-01 07:43
@GitHubSphinx Actually, it only patches the issue sometimes. There's still the issue of when people have a stack of scrolls and they lose them.

**Comment by deilann** [comment] 2014-05-02 22:07
I think I've figured this one out. I believe it's related to https://github.com/HabitRPG/habitrpg/issues/2657 -- whenever the system restarts the quest, it takes another scroll from the quest leader. Two things should fix it:

1) Remove the scroll from the quest leader upon _invitation_, not upon the quest starting.
2) Put in an error check for purchases -- if scroll quantity < 0, set it to 0
3) A possible fix for #2657 would also alleviate this -- add in error checking past invititation to check to see if a quest is active before starting a quest.

I _believe_ all three of these together would solve this issue.

Any thoughts?

**Comment by deilann** [comment] 2014-05-02 22:12
The only problem is I don't know what's triggering the restart quest bit, so I have no way of testing this. QA Master @SabreCat thoughts on that?

**Comment by secretstaircase** [comment] 2014-05-05 15:42
I just had the spend gems / don't receive quest scroll problem, also on the Gryphon quest. Could I be refunded the gems, please? User ID: 471f47bc-52cc-4cbf-904c-6d4909e43866

**Comment by deilann** [comment] 2014-05-05 19:13
UUID?

**Comment by secretstaircase** [comment] 2014-05-05 19:34
Huh, I thought I edited to add that. User ID: 471f47bc-52cc-4cbf-904c-6d4909e43866

**Comment by deilann** [comment] 2014-05-05 19:34
Editing doesn't hit my inbox, sorry.

**Comment by deilann** [comment] 2014-05-05 19:35
Refunded!

**Comment by Yuubou** [comment] 2014-05-12 16:44
@deilann I have been testing this a bit, and noted the following:
My quest scroll count & displayed scroll icons decreased by one upon party invitation to the quest.
My quest scroll count also decreased by one after defeating the quest.  

This was true for both The Fiery Gryphon and Free Yourself of the Dragon's Influence.  

So, I know I should be -1 The Fiery Gryphon & -1 Free Yourself of the Dragon's Influence.  I tried buying a different scroll with my gems and was able to purchase it.  Then I tried buying a Fiery Gryphon & it again took my gems and upped the scroll count but deposited no scroll. I haven't noticed scroll counts decreasing when other party members start the quest.  

This all leads me to believe it has to do with the mechanisms involved with the fact that if you abandon a quest, you can use the scroll again - my guess is there's a line of code that if you defeat the quest, the scroll is taken (rather than telling it to return a scroll if the quest is abandoned).  But there is probably a line somewhere if you re-start a quest, a scroll is taken.

Any way, my UUID is 7846c2cc-400d-4aff-b1ad-40ee3d68305c if you don't mind refunding 8 gems.

Thanks for looking into this!

**Comment by lefnire** [comment] 2014-05-12 16:45
Note, @deilann's fix isn't live yet. We won't deploy it until we've solved the i18n fixes on beta

**Comment by deilann** [comment] 2014-05-12 16:49
@Yuubou Not only is the fix not live, I am almost positive this is not
what's going on, simply because if that were the case, it would _always_
remove an extra scroll. But it only does sometimes.

The scroll isn't removed upon invitation; it's removed upon quest start.
And aborting a quest refunds a scroll, I am almost positive because players
often have to refresh to have it back in their inventory after losing it.

What probably happened is you had an extra questStart trigger -- we'll find
out if that seems to be the case when my fix goes live.

Anyway, gems refunded.

**Comment by ghost** [comment] 2014-05-13 05:18
I bought a Hedgehog Quest scroll the other night, and it took my gems, but gave me know scroll. I have noticed for a few days that I also had negative numbers of quest scrolls, but I didn't think anything of it. Could someone give me my gems back? And should we not try to buy scrolls until this is fixed? Or just come back here if it happens again? Thanks for all the hard work y'all do.

My UIUD is a92762ce-f8bc-411a-9452-245acccac9b9

**Comment by deilann** [comment] 2014-05-13 05:22
Just come back here if it happens again. :) It's fixable by buying the
scrolls.

Gems refunded!

**Comment by ghost** [comment] 2014-05-13 05:22
Thanks so much. ^_^

On Tue, May 13, 2014 at 1:22 AM, deilann notifications@github.com wrote:

> Just come back here if it happens again. :) It's fixable by buying the
> scrolls.
> 
> Gems refunded!
> 
> On Mon, May 12, 2014 at 10:18 PM, cinnamingirl notifications@github.comwrote:
> 
> > I bought a Hedgehog Quest scroll the other night, and it took my gems,
> > but
> > gave me know scroll. I have noticed for a few days that I also had
> > negative
> > numbers of quest scrolls, but I didn't think anything of it. Could
> > someone
> > give me my gems back? And should we not try to buy scrolls until this is
> > fixed? Or just come back here if it happens again? Thanks for all the
> > hard
> > work y'all do.
> > 
> > My UIUD is a92762ce-f8bc-411a-9452-245acccac9b9
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/HabitRPG/habitrpg/issues/2592#issuecomment-42918036>
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/HabitRPG/habitrpg/issues/2592#issuecomment-42918237
> .

## 

Siobhain

---

Siobhain Rivera
siobhain.rivera@gmail.com
MLS Candidate, Digital Libraries
Indiana University

Website: www.siobhain.rivera.com
Twitter: @SioTheLibrarian https://twitter.com/SioTheLibrarian
Tumblr: www.siothelibrarian.tumblr.com

**Comment by chornsby** [comment] 2014-05-13 09:04
It happened again. >.< Shortly after starting the hedgehog quest one of my party members was sent the quest invitation again and accepted it. This lead to the boss going back to full health and my quest scrolls counter saying 0 despite having the vice scroll in my inventory.

User ID: db393d59-b0cc-41ee-998d-e1b7888a6eea

From reading the thread, this might help locate the problem. If the scroll is removed on quest start but we've had a spurious restart without abandoning the quest then that could explain why there are now -1 hedgehog scrolls in my inventory?

**Comment by deilann** [comment] 2014-05-13 09:10
Yes, I believe that is the issue and there is a fix on the way. It will be
pushed to the site once i18n stuff is cleared up.

Something is causing questStart to run again without the quest leader to
run another invite. I don't know what it is, but I've added a clause into
questStart to check and make sure a quest isn't running before it does
anything. I'm hoping this fixes the problem, even if we're not positive
_why_ questStart is being retriggered -- or in your case, why your party
member was sent another quest invitation and then triggered questStart.

I've refunded you 4 gems. :) Repurchasing the Hedgebeast scroll should
patch you up.

**Comment by chornsby** [comment] 2014-05-13 09:13
Thanks a lot! Sounds like a very sensible fix -- hopefully it'll solve the bug!

**Comment by Memry** [comment] 2014-05-14 04:27
I had the same problem with the purchase. Tried to purchase Spirit of Spring and did not receive it.  Thanks, deilann for steering me here!

My user ID is e495bd8b-f2f1-48e8-8f5f-9a52710999cf

**Comment by deilann** [comment] 2014-05-14 04:37
Np I'll refund you ASAP

**Comment by deilann** [comment] 2014-05-14 06:16
Refunded! Lemme know if repurchasing doesn't patch you up. :)

**Comment by eiron** [comment] 2014-05-14 14:39
I am now missing the Trapper Santa and the Find the Cub quest scrolls (which have disappeared without my using them), and have "(5)" scrolls which are actually 6, as I have two of the Egg Hunt.

**Comment by deilann** [comment] 2014-05-14 15:24
When you say disappeared without using them do you mean you never once
activated a Trapper Santa or Find the Cub scroll? That does not fit the
pattern at all... I don't think anyone has ever reported losing a scroll
they've never used.

**Comment by deilann** [comment] 2014-05-15 03:21
This https://github.com/HabitRPG/habitrpg-shared/pull/204 and this https://github.com/HabitRPG/habitrpg/commit/9a4e8d38b46d02475ca97121b5d77a777f8d1f92 should fix this and patch it over nice self healing for already negative scroll amounts being repurchased.

Please lemme know gaiz, if you continue to have this problem.

**Comment by eiron** [comment] 2014-05-15 13:23
My mistake. Trapper Santa is there. But yes, the Find the Cub scroll remains dead and gone (both were exhausted as one). No option exists to repurchase that one as yet.

**Comment by deilann** [comment] 2014-05-15 13:27
Yeah, I can't fix that. But just to confirm: you are confirming that you
had 2 Find the Cub scrolls, you activated one, and it nommed 2? Because
that's what this bug is thought to be doing.

@lefnire can you refund Eiron? UUID: 4182cdea-64db-4db4-9713-dc587d86c662
needs 1 Find the Cub scroll

**Comment by Bujungo** [comment] 2014-08-14 13:53
I finished the first part of the Vice quest and attempted to start the second and now the scroll is gone and I'm not in the quest.

**Comment by Alys** [comment] 2019-03-23 01:59
I'm reopening this because I suspect the bug happened to another player (NookaBean, 77468ba2-c08a-4c12-9cb8-70c6a7ee437c) based on a recent post in the Report a Bug guild in which they bought a scroll but did not receive it. I've confirmed that the workaround for the bug (https://github.com/HabitRPG/habitica/pull/10953) works if you're buying a quest scroll with Gold but not with Gems. The code change from that PR was put into `website/common/script/ops/buy/buyQuest.js` and it would need to be copied to `website/common/script/ops/buy/buyQuestGem.js`.
https://github.com/HabitRPG/habitica/blob/a2261e35919a0396d2e74ea70f209b68ebc004c6/website/common/script/ops/buy/buyQuest.js#L68-L69

However it might be better to try to apply the workaround to the super class's `purchase()` function (see code snippet below) so that it's run for every kind of purchase, although that would be tricky since each subclass handles the decision about where in the user document the current number of owned items can be found. Perhaps there could be a new inheritable function that could do the checking just before `executeChanges()` is run? Possibly it could be optional so that it wouldn't have to be added to all purchase/item types yet (i.e., the super class would not throw an error if the function wasn't implemented).

https://github.com/HabitRPG/habitica/blob/a2261e35919a0396d2e74ea70f209b68ebc004c6/website/common/script/ops/buy/abstractBuyOperation.js#L91-L98

It might also be worth renaming `website/common/script/ops/buy/buyQuest.js` to `website/common/script/ops/buy/buyQuestGold.js` to help with future additions since it's easy to forget that there's two ways to buy quests.

FYI for anyone curious, here's one example of how the negative quest scrolls bug can occur: https://github.com/HabitRPG/habitica/issues/10974
Ideally all causes would be fixed to remove the bug entirely, but that's a lot more work than adding the workaround described above.

**Comment by Alys** [comment] 2019-08-21 09:53
We've had another report of a failed quest scroll purchase that was probably due to this. 

I've confirmed the bug still exists -- I gave myself -1 of a gem-purchasable scroll, then bought the scroll, and ended up with 0 scrolls, so the fix that was done for gold-purchasable quests definitely still needs to be applied to gem quests. I'm raising this to a high priority since it's taking gems from players.

**Comment by cheng-shiqi** [comment] 2019-09-29 17:43
@Alys Can I take this one? And thanks a lot for the information and suggestions above, giving huge help in looking into such a long issue!

**Comment by Alys** [comment] 2019-09-29 21:35
@cheng-shiqi Yes, please do, thank you! Post here if you have questions. 

Good to hear my comments helped, thanks. :)

**Comment by cheng-shiqi** [comment] 2019-10-02 17:41
@Alys Just submmitted the PR for this issue, sorry for the delay. I copied the resetting code in #10953 to website/common/script/ops/buy/buyQuestGem.js and renamed website/common/script/ops/buy/buyQuest.js, as you suggested. But I didn't extract the workaround in #10953 as a new function and pull it up to the super class, cause I haven't figured out a proper solution yet.

**Closed as completed** 2019-10-06 15:06 UTC
Labels: priority: important, help wanted, type: medium level coding, section: Quest Shop
