### ISSUE TITLE
Errors with batch-buying gold purchasable quests

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#9507] opened 2017-11-16 01:19 UTC
Batch-buying gold purchasable quests seems to result in errors where the number the user attempted to purchase don’t show up in inventory, but gold is sometimes deducted correctly for the amount they attempted to purchase anyway.

**Comment by kipraske** [comment] 2017-11-20 22:23
This looks like a fun bug to fix. Can i help out with this one?

Unfortunately I have not been able to reproduce the bug as it is stated here. However, there is something definitely broken with batch buying quests: The quantity is simply never passed to the server. So the frontend thinks you have bought 10 quests or whatever but the backend thinks you have only bought 1 quest. Once you refresh you get all your money back. I hope that fixing this would fix the much worse bug that is stated in this issue.

So as a start we could either update the call to accept a quantity on the server, or we could remove the ability to batch buy quests altogether. What do you think is better? I personally don't see the need to batch purchase quests ever, but I can see how someone might like this ability here for UI consistency.

**Comment by kipraske** [comment] 2017-11-20 22:33
While I am poking around in here. I also noticed that you can set a quantity for the mystic hourglass items. This quantity is similarly never passed to the server so thankfully you can only buy 1 mystery item. In this case we should definitely remove the "How many would you like to buy?" dialog. The good news is that it only uses 1 on the client as well so we don't have any refunding problems.

**Comment by Alys** [comment] 2017-11-20 22:51
@kipraske Please do work on this issue - thanks!

For the gold-purchasable quests, it's likely that few people would want to buy more than one at a time. However for the gem-purchasable pet quests, it's more likely that you'd want to buy several at once (e.g., enough to get a full set of pets). I think on the whole for consistency, it's best to allow multiple purchases for any kind of quest scroll.

Buying Mystery Items with Hourglasses is being covered by the fix for this issue: [Cards (greetings, thank you, etc) should not have multiple Batch Buying (also gear, Backgrounds, Mystery Item sets, Rebirth, Fortify, Armoire) - Issue #9317 - HabitRPG/habitica](https://github.com/HabitRPG/habitica/issues/9317)
But thanks for mentioning it! If we didn't know about it, we'd definitely be glad we did now. :)

**Closed as completed** 2017-11-28 01:33 UTC
Labels: priority: important, status: issue: in progress, section: Quest Shop
