### ISSUE TITLE
Little green blob appears in mouseover for class selection

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#3327] opened 2014-04-22 01:32 UTC
Alas, I don't have a screenshot of it, but when you use the Class Change feature and mouse over one of the class sample avatars, a little green box appears in the upper left. It appears that the bubble meant to show the profile name when hovering over yourself or a party member doesn't, under the recently revamped UI, know not to appear when there is no name to display.

**Comment by lefnire** [comment] 2014-04-22 17:36
Confirmed. And it doesn't show you which class you have selected before clicking "Select"

**Comment by usernamenumber** [comment] 2014-04-27 18:08
I've created a pull request that attempts to fix both of these problems. 

https://github.com/HabitRPG/habitrpg/pull/3360

**Comment by Alys** [comment] 2014-09-19 19:18
I can't replicate this so it looks like it's being fixed. Closing, but reopen if I'm wrong.

**Closed as completed by Alys** 2014-09-19 19:18 UTC
Labels: priority: minor
