### ISSUE TITLE
My Challenges should include all Owned Challenges

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#9286] opened 2017-10-27 00:27 UTC
The My Challenges sections of the site should include:

-  all of a user's Owned Challenges, even if they aren't currently part of those Challenges. 
- Challenges that they own which are located in a Private Guild.
- Challenges that they have joined which are located in a Private Guild.

**Comment by pcvonz** [comment] 2017-11-09 02:02
I can try and take care of this one.

**Comment by pcvonz** [comment] 2017-11-09 05:49
Did some digging into the ownership issue:

On the My Challenges page the filter will always check if the user is a member of the challenge since the `participating` role is always passed. The easy solution is to not pass the `participating` role when `Owned` is checked in the sidebar. But that'd mean that the user wouldn't be able to see every challenge they own but aren't participating in and all participating challenges at once, which I don't think is what we want. So, I'm thinking of writing a new filter function specifically for the My Challenges page.

Another thing I noticed is that the sidebar doesn't reflect what is actually being passed to the filter. For instance, the participating option should be checked on the My Challenges page.

**Comment by lemoness** [comment] 2017-11-10 01:01
Good point about the filter! Thanks very much for tackling this.

I've updated the labels on this ticket.

**Comment by TheHollidayInn** [comment] 2017-11-17 12:06
Yea, the issue is we first wanted to only included participating challenges. To fix this, you'll probably need to:
1. Remove this: https://github.com/HabitRPG/habitica/blob/develop/website/client/components/challenges/myChallenges.vue#L115
2. Replace this: https://github.com/HabitRPG/habitica/blob/develop/website/client/components/challenges/myChallenges.vue#L130 with an "Owned" filter because our API doesn't return only owned challenges if I remember. 

I don't think there is a need to write a custom filter for my challenges, but I'm open to seeing what you have. Maybe just go with the fix first though.

**Comment by marvinrabe** [comment] 2018-05-07 14:14
I will do this.

**Closed as completed** 2018-05-13 14:31 UTC
Labels: section: Challenges, priority: medium, status: issue: in progress
