### ISSUE TITLE
Kicked back to a previous level when using multiple browsers.

### ISSUE THREAD

**Issue by Krosty** [HabitRPG/habitica#544] opened 2013-03-01 01:51 UTC
I check in on my iPhone 5's standard browser and on iE on a desktop computer. I had leveled up to 3 (unlocked party) and then the next morning when I went to log my habits, I believe on the desktop, it had kicked me back to a previous 'save' it seems - old Todos that I had copleted were on my list. This is what loads now when I log in and out. I also had 30+ coins and then I was abck to 12. I don't know if this includes loss of backer coins.

**Comment by ruddfawcett** [comment] 2013-03-01 02:21
You can restore your level.  Click the down arrow next to your name --> settings --> restore.

**Comment by lefnire** [comment] 2013-03-01 02:34
Hey @Krosty , sorry for the bummer :( See "Lost Progress" of https://github.com/lefnire/habitrpg/wiki/Restoring-Your-Account - definitely something we're fixing.

**Comment by horusofoz** [comment] 2013-04-01 05:18
@Krosty have you had any further instances of this issue?

**Comment by nexttin** [comment] 2013-05-13 16:54
Happened to me last night, got to Level 2 and unlocked items. Back this morning and I'm reverted to level 1 although the new Level 2 items are still available. I keep Habit open in a background tab basically 24/7.

**Comment by lefnire** [comment] 2013-05-19 13:02
looks like a duplicate of #635, let's follow up there

**Closed as completed by lefnire** 2013-05-19 13:02 UTC
Labels: priority: important
