### ISSUE TITLE
Pet hover label is too far up

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#1303] opened 2013-08-03 16:37 UTC
Windows 7, Chrome and Firefox.

The hover "speech bubble" labeling pets in the Stable is unnecessarily far detached from the actual critter:

![screenclip](https://f.cloud.github.com/assets/4501321/905892/770122ca-fc5a-11e2-90e6-d8fbeb203dd0.png)

If it moved south about 20 pixels, it'd better match the positioning of the pet, while still not intruding too far onto the largest sprites (e.g. the missing animal ?).

**Comment by SabreCat** [comment] 2013-08-03 16:38
@onduhray or @nafoster, this seems like it'd be up your alley? I tried to track down where this offset is specified, but I'm too new to CSS to puzzle it out.

**Comment by AndreCaseyScott** [comment] 2013-08-03 23:05
Thanks for pointing this out! It seems it's not a CSS puzzle, as it is caused by the pet sprite sheet used to display the pets. It is 99px tall in order to accommodate flying pets and backer pets. 

I think I've found a way to fix this involving margin-top and overflow: hidden on each pet type, but will give it more testing to be sure.

**Comment by paglias** [comment] 2013-09-09 18:03
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!

**Comment by SabreCat** [comment] 2013-09-10 00:06
This one hasn't changed with the rewrite, from what I can tell. Reopening.

**Comment by Shaners** [comment] 2013-09-10 04:13
We could crop the CSS at a different position and size for this page if we needed to avoid negative margins.

**Comment by Shaners** [comment] 2013-11-06 17:26
Been playing with a fix for these. What do you guys think of this?
![rearranged-stable](https://f.cloud.github.com/assets/2374703/1484529/20458144-4708-11e3-8680-3b40b36232f9.png)
Piggies still broken in this test.

**Comment by paglias** [comment] 2013-11-06 17:49
Great! We could add a different margin/padding or background position only for piggies

**Comment by Shaners** [comment] 2013-11-06 18:21
Here's an alternative that keeps the same spacing but moves the tooltip down, with bonus coloured box!
![rearranged-stable002](https://f.cloud.github.com/assets/2374703/1485058/2342062c-470f-11e3-87db-a7f6fdea929a.png)
![rearranged-stable003](https://f.cloud.github.com/assets/2374703/1485095/e3acb38a-470f-11e3-94a2-ed4e5b6fb06e.png)

**Comment by SabreCat** [comment] 2013-11-07 03:04
I dig the positioning you've got going with the final iteration here! The colored background is a little hard to read on Golden, though, at least with my subpar monitor.

**Comment by nafoster** [comment] 2013-11-08 17:05
For Golden, try making the text black or a dark grey. Other than that, these tooltips look awesome!

**Comment by lefnire** [comment] 2013-11-12 19:00
@paglias did you mean to close-reopen the last few tix? Is it to bump them?

Re: this ticket, mounts rewrite has popovers instead of tooltips - we may need to revisit css to re-reposition

**Comment by paglias** [comment] 2013-11-12 19:03
No sorry, I tried something like Huboard called ZenHub and I mistake the
meaning of a button which meant to be a way to close issues

2013/11/12 Tyler Renelle notifications@github.com

> @paglias https://github.com/paglias did you mean to close-reopen the
> last few tix? Is it to bump them?
> 
> Re: this ticket, mounts rewrite has popovers instead of tooltips - we may
> need to revisit css to re-reposition
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/HabitRPG/habitrpg/issues/1303#issuecomment-28322308
> .

## 

Matteo Pagliazzi - paglias.net

**Comment by lefnire** [comment] 2013-11-12 19:13
Oh this looks awesome! I just signed up for early access

On Tue, Nov 12, 2013 at 11:03 AM, Matteo Pagliazzi <notifications@github.com

**Comment by paglias** [comment] 2013-11-12 19:15
yes it looks quite good :) mostly its data isn't saved as github tags as huboard so multiple devs can use it at the same time, when I tried Huboard it was the same as your :)

**Closed as completed** 2013-11-25 15:44 UTC
Labels: priority: minor
