### ISSUE TITLE
Regularly receiving application errors

### ISSUE THREAD

**Issue by murraybd** [HabitRPG/habitica#6704] opened 2016-02-12 14:52 UTC
When I have been working with tasks, adding or completing, or feeding pets I have been regularly receiving the "Yikes, an error occurred message".  I am using Firefox version 44 on Ubuntu 16.04 and here is information from my java console:

"Error: [$rootScope:inprog] $apply already in progress
http://errors.angularjs.org/1.3.9/$rootScope/inprog?p0=%24apply
d/<@https://habitica.com/app-c14655c7.js:4:22855
o@https://habitica.com/app-c14655c7.js:7:18157
wd/this.$get</j.prototype.$apply@https://habitica.com/app-c14655c7.js:7:16613
y@https://habitica.com/app-c14655c7.js:20:4989
o.event.special[a].handle@https://habitica.com/app-c14655c7.js:2:9671
o.event.dispatch@https://habitica.com/app-c14655c7.js:2:6057
o.event.add/r.handle@https://habitica.com/app-c14655c7.js:2:2867
b.choosePet@https://habitica.com/app-c14655c7.js:34:15203
g@https://habitica.com/app-c14655c7.js:7:3744
h/</e@https://habitica.com/app-c14655c7.js:8:11787
wd/this.$get</j.prototype.$eval@https://habitica.com/app-c14655c7.js:7:16398
wd/this.$get</j.prototype.$apply@https://habitica.com/app-c14655c7.js:7:16632
h/<@https://habitica.com/app-c14655c7.js:8:11846
o.event.dispatch@https://habitica.com/app-c14655c7.js:2:6057
o.event.add/r.handle@https://habitica.com/app-c14655c7.js:2:2867

My user id is: 5b93ce83-2508-4ea4-9647-079899dffa96.

**Comment by Cartogenic** [comment] 2016-02-12 14:54
You're not the only one. I've been having those, quite a lot, as well, since yesterday.
People in the tavern also complain.

**Comment by Cartogenic** [comment] 2016-02-12 14:58
This is seriously annoying
 https://i.imgur.com/jFHgVOv.png

https://i.imgur.com/hUZgEeB.png

**Comment by Endroine** [comment] 2016-02-12 15:02
Same, I'm looking here for solutions but there seem to be none (yet). I Hope this gets fixed soon because its annoying af.

**Comment by Cartogenic** [comment] 2016-02-12 15:03
Duplicate of #6700

**Comment by lemoness** [comment] 2016-02-12 20:13
We're very sorry about this! We've been investigating the cause and are working on some fixes. You can follow https://github.com/HabitRPG/habitrpg/issues/6700 to hear more about the issue and our progress. Thank you so much for your patience!

If you lost any stats due to these errors, you can restore them on the website under Settings > Site > Fix Character Values. I'm going to close this thread now, but feel free to keep responding if you have more questions!

**Closed as completed by lemoness** 2016-02-12 20:13 UTC
