### ISSUE TITLE
Multiplied Party Member

### ISSUE THREAD

**Issue by tamacodechi** [HabitRPG/habitica#1272] opened 2013-07-22 22:11 UTC
The member adding function didn't show any verification of the request being sent so I input the UserID several times. Once the member accepted my request he was added on my party 4 times (the number of times I input the UserID). It can be fixed by going to the group and removing the member several times until only one copy is left. Easily fixed therefore I suppose not a priority, but still a bug, thought you'd like to know.

**Comment by lefnire** [comment] 2013-07-26 22:17
duplicate of #1213, let's follow up there

**Closed as completed by lefnire** 2013-07-26 22:17 UTC
