### ISSUE TITLE
dailies not reseting

### ISSUE THREAD

**Issue by monkeyik** [HabitRPG/habitica#1976] opened 2013-12-10 10:57 UTC
is there a way to manually do this? Ive tried logining in and out. and ive looked all over the settings.

**Comment by ghost** [comment] 2013-12-12 08:09
I had to press "ctrl+shift+r" to clear my cache, for mine to update.

**Comment by lefnire** [comment] 2013-12-12 17:22
duplicate of #1057

**Closed as completed by lefnire** 2013-12-12 17:22 UTC
