### ISSUE TITLE
Error while trying to subscribe with coupon code through Stripe.

### ISSUE THREAD

**Issue by khipkin** [HabitRPG/habitica#8518] opened 2017-02-27 18:52 UTC
_edit by Alys:_

khipkin was affected by two bugs, one caused by unexpected data in her account that caused a subscription to terminate early and the other caused by a bug in our code that processes coupons. **This issue is specifically for fixing the bug that prevents coupons being used.** You can read details of that from this comment and below: https://github.com/HabitRPG/habitica/issues/8518#issuecomment-284889852

I think there's a good chance that the code would be easy to repair because it's could be just something like a missed parameter that's preventing the coupon being passed from the website's form to the backend code, so I'm marking this as a medium level coding fix, however if you're looking into it and can't find a problem relatively quickly, please post here to let us know that it might be more complicated!

### What to do if this bug happens to you:

**Email admin@habitica.com with your User ID and the coupon code that you are trying to use.**

_khipkin's original bug report is below._

-----

[//]: # (Fill out relevant information - UUID is found in Settings -> API)
General Info
  * UUID: f9c89bba-abf8-4f20-a974-cf1550ff603f
  * Browser: Chrome Version 56.0.2924.87 (64-bit)
  * OS: Ubuntu 14.04 trusty (x86-64)

---

### Description
[//]: # (Describe bug in detail here. Include pictures if helpful.)

Before I canceled my original subscription:

![image](https://cloud.githubusercontent.com/assets/5641207/23374315/9c2028c6-fcd8-11e6-90de-37e2014d6eb9.png)

Trying to resubscribe, coupon code applied:

![image](https://cloud.githubusercontent.com/assets/5641207/23374376/e2941b3c-fcd8-11e6-915f-db228d3fab2d.png)
_Note the erroneous "inactive" date, almost a month in the past._

The coupon is only for the 6-month subscription, so I select that option.

![image](https://cloud.githubusercontent.com/assets/5641207/23374465/417d1e28-fcd9-11e6-8e13-b9c797cc9f86.png)

Click "Credit Card (using Stripe)", and enter credit card info. Click confirmation button. Pop up with error message.

![image](https://cloud.githubusercontent.com/assets/5641207/23374800/b40dd594-fcda-11e6-832a-b04201b15fa0.png)

Then there was a little red error button with the same message, but I didn't get a picture in time.

---

#### Console Errors
[//]: # (Include any JavaScript console errors here.)

![image](https://cloud.githubusercontent.com/assets/5641207/23374612/db70f57c-fcd9-11e6-806c-fdeb565520a4.png)

**Comment by Alys** [comment] 2017-03-07 21:22
Oh heck @khipkin I'm so sorry we never replied to this! I kept it in my inbox to do something about your subscription but it got buried. :( I can see your subscription has terminated because of this bug and of course you couldn't create a new one. :( I'm going to leave this issue open for an investigation into the cause and a coding fix but I'm about to PM you with details of how I'll fix the specific problem for your account now.

**Comment by Alys** [comment] 2017-03-07 21:52
In case it helps with us investigating the bug, here is khipkin's subscription data from before the cancellation, taken from a backup made on 2017-01-26 and from today before my manual fix is applied:

```
"purchased.plan" : {
	"planId" : "basic_earned",
	"paymentMethod" : "Amazon Payments",
	"lastBillingDate" : ISODate("2016-12-30T01:33:46.158Z"),
	"dateUpdated" : ISODate("2017-01-01T16:37:47.391Z"),
	"dateTerminated" : null,
	"dateCreated" : ISODate("2016-08-29T23:43:42.880Z"),
	"customerId" : "[I have a private record of this]",
	"consecutive" : {
		"trinkets" : 0,
		"gemCapExtra" : 5,
		"offset" : 0,
		"count" : 5
	},
	"mysteryItems" : [ ],
	"gemsBought" : 30,
	"extraMonths" : 0,
	"quantity" : 1
}
```

```
"purchased.plan": {
	"planId": null,
	"paymentMethod": null,
	"lastBillingDate": "2017-01-30T02:25:43.172Z",
	"dateUpdated": "2017-02-01T15:19:35.531Z",
	"dateTerminated": "2017-02-02T00:00:00.000Z",
	"dateCreated": "2016-08-29T23:43:42.880Z",
	"customerId": null,
	"consecutive": {
		"trinkets": 0,
		"gemCapExtra": 0,
		"offset": 0,
		"count": 0
	},
	"mysteryItems": [],
	"gemsBought": 0,
	"extraMonths": 0,
	"quantity": 1
}
```

**Comment by khipkin** [comment] 2017-03-07 22:00
Thank you, @Alys! I wasn't going to panic or start pinging until we got a bit closer to the end of the month. 😊

**Comment by khipkin** [comment] 2017-03-07 22:03
Although I am now realizing that the end of *my* month (in terms of my original subscription) has already passed. 😢 Darn. Totally miscalculated on that.

**Comment by khipkin** [comment] 2017-03-07 22:29
**I just tried again, and the exact same thing is still happening.**

**Comment by Alys** [comment] 2017-03-07 22:29
All fixed. Here's the current state in case we need to repair it again if future subscription attempts fail. Note the consecutive benefits in particular.

```
"purchased.plan": {
	"quantity": 1,
	"extraMonths": 0,
	"gemsBought": 0,
	"mysteryItems": [],
	"consecutive": {
		"count": 6,
		"offset": 0,
		"gemCapExtra": 10,
		"trinkets": 1
	},
	"paymentMethod": null,
	"customerId": "Gift",
	"dateCreated": "2016-08-29T23:43:42.880Z",
	"dateUpdated": "2017-03-08T00:00:00.000Z",
	"dateTerminated": "2017-04-09T01:00:00.000Z"
}
```

**Comment by Alys** [comment] 2017-03-07 22:34
Oh. I posted that last comment at exactly the same time as @khipkin said a new subscription attempt failed. :-/  "All fixed" refers to her current repaired subscription specifically, NOT to this bug.

It looks like there's a persistent bug with subscribing with a coupon code. It might be related to subscribing over the top of a cancelled subscription.

@khipkin I'm sorry to mess you around, but can you try one more time? I've temporarily removed all traces of the subscription from your account, as if you'd never had one. I'd like to see if the subscription with a coupon code works now. Of course I will put back your consecutive month benefits as soon as you've tested again!

**Comment by khipkin** [comment] 2017-03-07 22:39
@Alys It still fails with the same error message. Based on the message content, I would guess that the coupon parameter isn't being passed as expected.

**Comment by Alys** [comment] 2017-03-07 23:05
Thanks so much for testing!  I've put back the subscription details that are shown in [my post above](https://github.com/HabitRPG/habitica/issues/8518#issuecomment-284881450). Tell me if anything doesn't work.

I think you're right about the couponn parameter not being passed. Here's the error from our logs:
```
2017-03-07T22:39:11.027Z - warn: BadRequest: The coupon code is required.
    at Object._callee$ (/var/app/current/website/transpiled-babel/libs/stripePayments.js:93:19)
    at tryCatch (/var/app/current/node_modules/regenerator-runtime/runtime.js:64:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/var/app/current/node_modules/regenerator-runtime/runtime.js:355:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/var/app/current/node_modules/regenerator-runtime/runtime.js:116:21)
    at GeneratorFunctionPrototype.tryCatcher (/var/app/current/node_modules/bluebird/js/release/util.js:16:23)
    at PromiseSpawn._promiseFulfilled (/var/app/current/node_modules/bluebird/js/release/generators.js:97:49)
    at Object.<anonymous> (/var/app/current/node_modules/bluebird/js/release/generators.js:201:15)
    at Object.checkout (/var/app/current/website/transpiled-babel/libs/stripePayments.js:212:17)
    at _callee$ (/var/app/current/website/transpiled-babel/controllers/top-level/payments/stripe.js:54:47)
    at tryCatch (/var/app/current/node_modules/regenerator-runtime/runtime.js:64:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/var/app/current/node_modules/regenerator-runtime/runtime.js:355:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/var/app/current/node_modules/regenerator-runtime/runtime.js:116:21)
    at GeneratorFunctionPrototype.tryCatcher (/var/app/current/node_modules/bluebird/js/release/util.js:16:23)
    at PromiseSpawn._promiseFulfilled (/var/app/current/node_modules/bluebird/js/release/generators.js:97:49)
    at /var/app/current/node_modules/bluebird/js/release/generators.js:201:15
    at handler (/var/app/current/website/transpiled-babel/controllers/top-level/payments/stripe.js:66:8)
    at /var/app/current/website/transpiled-babel/libs/routes.js:25:15
    at Layer.handle [as handle_request] (/var/app/current/node_modules/express/lib/router/layer.js:95:5)
    at next (/var/app/current/node_modules/express/lib/router/route.js:131:13)
    at /var/app/current/website/transpiled-babel/middlewares/cron.js:301:5
    at bound (domain.js:280:14)
    at runBound (domain.js:293:12)
    at tryCatcher (/var/app/current/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/var/app/current/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/var/app/current/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromiseCtx (/var/app/current/node_modules/bluebird/js/release/promise.js:604:10)
    at Async._drainQueue (/var/app/current/node_modules/bluebird/js/release/async.js:138:12)
    at Async._drainQueues (/var/app/current/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/var/app/current/node_modules/bluebird/js/release/async.js:17:14) method=POST, originalUrl=/stripe/checkout?a=a&sub=xxxxxxxxx_6mo&coupon=xxxxxxxxxxxxxx, host=habitica.com, x-real-ip=xxxxxxxxxxxxx, x-forwarded-for=xxxxxxxxxxxxx, xxxxxxxxxxxxx, content-length=672, accept=application/json, text/plain, */*, accept-encoding=gzip, deflate, br, accept-language=en-US,en;q=0.8,de;q=0.6, content-type=application/json;charset=UTF-8, origin=https://habitica.com, referer=https://habitica.com/, user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36, x-api-user=f9c89bba-abf8-4f20-a974-cf1550ff603f, x-client=habitica-web, x-user-timezoneoffset=xxx, x-forwarded-port=443, x-forwarded-proto=https, xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx, livemode=true, type=card, used=false, httpCode=400, isHandledError=true
```

We must also look into why your original subscription's cancellation date was set to 2017-01-02 -- **before** the date you cancelled it on! There was no negative extraMonths to explain that and there's no failed charges in the payment processor website.

The first step though is to look at our code for collecting and passing on the coupon to see if there's some variable not matching up or something.

**Comment by khipkin** [comment] 2017-03-24 16:32
Ping! <2 weeks until my subscription runs out again.

**Comment by Alys** [comment] 2017-04-13 20:56
For the record, khipkin's subscription was adjusted again a couple of weeks ago.

I've updated the top post with this information:


khipkin was affected by two bugs, one caused by unexpected data in her account that caused a subscription to terminate early and the other caused by a bug in our code that processes coupons. **This issue is specifically for fixing the bug that prevents coupons being used.** You can read details of that from this comment and below: https://github.com/HabitRPG/habitica/issues/8518#issuecomment-284889852

I think there's a good chance that the code would be easy to repair because it's could be just something like a missed parameter that's preventing the coupon being passed from the website's form to the backend code, so I'm marking this as a medium level coding fix, however if you're looking into it and can't find a problem relatively quickly, please post here to let us know that it might be more complicated!

**Comment by khipkin** [comment] 2017-05-04 21:43
Subscription expires today!

**Comment by Alys** [comment] 2017-05-04 22:04
@khipkin Sorry. :(  Can you please create a normal-priced, non-recurring 3-month gift subscription for yourself using the gift box in the corner of your profile and ping me when that's done - a PM will be fine for this particular thing. I'll then extend the termination date to give you enough time for free so that you're effectively getting the discount that the coupon should have given you. This is the workaround I've done for other Google employees who've contacted us about this recently. I've extended your termination date now by two days to give us time for this workaround without you losing benefits.

**Closed as completed** 2018-01-15 19:12 UTC
Labels: priority: medium, status: issue: in progress, type: medium level coding, section: Payments
