### ISSUE TITLE
Sync issues on computer & iOS app

### ISSUE THREAD

**Issue by kchauhanmd** [HabitRPG/habitica#6306] opened 2015-11-26 13:45 UTC
Hi! So here is some technical information that I think might help:
- I use Google Chrome version 46.0.2490.86 m on a Windows 7 PC
- I have an iPhone 5c with an OS of 8.1.2 
- My userID is d2fa6e6f-3b8b-4bf1-83f8-5f9641691d6b

At least for the past week, I have been having issues on my laptop when creating/checking off tasks/dailies. Sometimes, the blue bar at the top does not completely finish and then this red pop-up message appears. It disappeared before I could screenshot it but I'll try to do so next time. The text (from a copy & paste) says: Yikes, an error occurred! Please reload the page, your last action may not have been saved correctly.

"Error 

" 

If the error persists, please report it at Help > Report a Bug. If you're familiar with your browser's console, please include any error messages.

It can be a bit frustrating because sometimes I'll have to re-purchase things, re-make tasks, etc. 

Additionally, I've noticed that when I check off dailies/tasks on my phone or create tasks/dailies on my phone, it doesn't usually sync very well when I access Habitica on my PC. There have been times where I'll have Habitica open on my phone and on my PC and there are essentially 2 different screens up because they're not syncing despite me pressing sync on both devices. 

I hope this is the right place to post this and I would love some guidance on resolving these issues. Habitica is super useful and I really want to continue using it! Thanks! :]

EDIT: Hope you all have a happy thanksgiving!

EDIT: 
![image](https://cloud.githubusercontent.com/assets/16033757/11424605/823dc510-941c-11e5-943d-f130923dc477.png)

**Comment by Alys** [comment] 2015-11-26 21:07
I'm sorry you're getting these errors so often!

The sync issues on your browser might sometimes be related to this issue: https://github.com/HabitRPG/habitrpg/issues/4313
Have a look at the Advice section near the top (that's the only party you need to read). In brief, reloading the website every so often might help with some of the sync problems. 
(Even though that issue focuses on cron, it applies at other times too - cron is mentioned only because that makes it really obvious when your actions to tick off Dailies haven't synced.)

The application errors are a site-wide, all-user problem caused by heavy load on the server. When we notice them, we restart the server which helps for a while. We are improving our code base with refactoring and other changes which in the long term should make the site more robust.

For the mobile sync issues, all I can think of is that perhaps your internet connection drops out sometimes? However it is possible that the mobile app IS syncing correctly to the server all the time, but that bug I linked to is preventing your browser getting updates often enough that it looks like the mobile app isn't syncing.

Unfortunately I'm not sure I can provide much more advice than this. :( Reloading the website every so often might be the only thing you can do. At the least, try it when you notice that you don't have all your recent changes from the mobile app.

**Comment by Alys** [comment] 2016-04-26 03:25
I'm closing this now but if you're still having problems, tell us and let us know if anything in my previous comment was of use.

**Closed as completed by Alys** 2016-04-26 03:25 UTC
