### ISSUE TITLE
Accepted challenge - Tasks are not automatically added.

### ISSUE THREAD

**Issue by TulinKei** [HabitRPG/habitica#4847] opened 2015-03-12 13:26 UTC
Hello,
I have understood when you join a challenge, tasks should be automatically added in the tasks section. This has not happened for me. 

I've joined 365 Less Things and Self Discipline. Would it be possible to assist please?

I also tried to ask a question, as I thought perhaps I was doing something wrong, but the page only says this:

{{Math.ceil(user.stats.hp)}} / 50 (This is in the Red bar)
{{Math.floor(user.stats.exp) | number:0}} / {{Shared.tnl(user.stats.lvl) | number:0}} (This is in the Yellow bar)

Thanks for your help.

5fa2812d-dc27-4ca3-badf-08c10637ca56

**Comment by deilann** [comment] 2015-03-12 13:41
Clear your cache. Reload the page.

This is likely completely unrelated to the challenge, and once you've done
this, everything should be as it should be, including the challenge tasks.

**Comment by TulinKei** [comment] 2015-03-12 14:33
Thank you for the fast response Deilann. I have noticed I am unable to view my tasks now.
I have cleared the cache and have reloaded the page. Unfortunately my task page now has the same error as the 'ask a question' page.
{{Math.ceil(user.stats.hp)}} / 50
{{Math.floor(user.stats.exp) | number:0}} / {{Shared.tnl(user.stats.lvl) | number:0}}

**Comment by deilann** [comment] 2015-03-12 14:35
It's a LocalStorage issue then.

Try what @paglias says to do in this comment:
https://github.com/HabitRPG/habitrpg/issues/4640#issuecomment-73131349

(also, it's deilann, not Deilann)

**Comment by TulinKei** [comment] 2015-03-12 14:44
Hi deilann,

I've followed the instructions, but I'm afraid the console gave me this error:

[Exception... "File error: Corrupted"  nsresult: "0x8052000b (NS_ERROR_FILE_CORRUPTED)"  location: "JS frame :: debugger eval code :: <TOP_LEVEL> :: line 1"  data: no]

I've tried refreshing the page and going to the static front page to log in, but it is to no avail at the moment.

Sorry to be a pain. And the capital D.

**Comment by deilann** [comment] 2015-03-12 14:47
Try doing it this way:
https://github.com/HabitRPG/habitrpg/issues/4379#issuecomment-67117280

**Comment by TulinKei** [comment] 2015-03-12 14:57
Thanks! I've opened the Firefox in a new private window and it seems to work fine now. I don't mind logging in private windows to access the website instead. I appreciate your help, and your swift replies!

**Comment by TulinKei** [comment] 2015-03-12 15:06
Unfortunately I am still having problems. I've been trying to join a guild challenge and I have been getting this error:

Please reload, "Error Runner error: Overflow sort stage buffered data usage of 33991221 bytes exceeds internal limit of 33554432 bytes" (see Chrome console for more details).

**Comment by deilann** [comment] 2015-03-12 15:24
That's this issue: https://github.com/HabitRPG/habitrpg/issues/4800

**Comment by TulinKei** [comment] 2015-03-12 15:40
Thank you

**Comment by Alys** [comment] 2015-03-14 13:33
This seems now to be a duplicate of the issue that deilann linked so, so I'm closing this issue, but it can be reopened if I'm wrong. @TulinKei if you have questions or are still having problems that aren't covered by https://github.com/HabitRPG/habitrpg/issues/4800, ask here. We'll see your message and respond even after the issue is closed.

**Closed as completed by Alys** 2015-03-14 13:33 UTC
