### ISSUE TITLE
Toggled tags are not reset with new Chrome browser sessions but are lost on new Firefox sessions

### ISSUE THREAD

**Issue by crypdick** [HabitRPG/habitica#4505] opened 2015-01-11 19:51 UTC
Today, I logged in and most of my habits and dailies are missing from Chrome. I've tried refreshing and restarting, trying to switch between the "Due" tabs-- no changes.

Edit: I've figured out the issue. One of my tags was toggled in Chrome, hiding most of my habits and dailies. For some reason, the toggle persist between Chrome browser sessions but not with Firefox sessions.

Chrome Version 39.0.2171.95 (64-bit)
Linux Mint 17
User ID: 406f4291-a374-48e7-891f-ce75c272ac39

Screenshots attached, including JS console output (I think the errors are unrelated to the issue
![chrome screenshot, most dailies and habits missing](https://cloud.githubusercontent.com/assets/5415776/5696484/000d018a-9988-11e4-9e43-3ffa18fbfcf1.png)
![JS console output](https://cloud.githubusercontent.com/assets/5415776/5696486/000e41da-9988-11e4-8ca3-dea7d1b4e496.png)
![Firefox, dailies and habits showing up properly](https://cloud.githubusercontent.com/assets/5415776/5696485/000e085a-9988-11e4-99a4-3488e872da71.png)
##

**Comment by bTackt** [comment] 2015-01-11 20:13
Yesterday I also had a glitch in which I logged into Habit on a different machine (no cache yet set there, but on Chrome, Windows 8) and it appeared that all the activity I had done in the span of an hour the night before had not synced (no amount of sync buttoning was fixing it), but upon returning to my own machine hours later, everything was back (as a result, I had self-duplicated the tasks ._. XD). idk, thought I'd mention it, I'm not sure it it directly has to do with this issue.

**Comment by Alys** [comment] 2015-01-11 20:25
@isomerase Click the "clear" button next to your tags, even if it looks like no tags are selected. Does that fix it?

@knittingfrenzy18 Are there still problems with your account? If so, tell us your UUID.

**Comment by crypdick** [comment] 2015-01-11 20:25
I've figured out the issue. One of my tags was toggled in Chrome, hiding most of my habits and dailies. For some reason, the toggle persist between Chrome browser sessions but not with Firefox sessions.

**Comment by bTackt** [comment] 2015-01-11 20:27
@Alys, no, the issue has fixed itself. I'm not sure what it was (I don't
think it was tags, it was all activity for a period of time). Then again, I
had a different machine.

**Comment by Alys** [comment] 2015-01-11 20:27
@knittingfrenzy18 Since @isomerase's issue is fixed, I'm closing this. Log a new issue if you need help with your account.

**Comment by crypdick** [comment] 2015-01-11 20:28
@Alys shouldn't this be fixed?

**Comment by Alys** [comment] 2015-01-11 20:29
Tags are meant to be persistent within one browser session.

**Comment by crypdick** [comment] 2015-01-11 20:30
Right. But when I close down Chrome and reopen it the toggles persist, which it does not do in Firefox. Doesn't seem to me like that's intended.

**Comment by Alys** [comment] 2015-01-11 20:32
Chrome is a more standard browser, so its behaviour is sometimes better than that of Firefox's. Firefox is close though. We do recommend Chrome as the best browser to use for HabitRPG.

**Comment by Alys** [comment] 2015-01-11 20:35
I'll do some testing on both Chrome and Firefox and see if I can replicate the Firefox bug.

**Comment by crypdick** [comment] 2015-01-11 20:36
Am I mistaken?

Intended behavior: opening HabitRPG with a fresh browser session opens a fresh HabitRPG session.
Actual behavior: Opening a fresh browser session (w Chrome) gives me my last HabitRPG session, specifically tag toggles.

edit: nvm, thanks for reopening
edit edit: let me know if you want me to test something

**Comment by Alys** [comment] 2015-01-11 20:44
The actual behaviour is the behaviour that I'd want. If I opened a new session, I'd want it to be the same as my previous session. E.g., if the browser crashed, or I had to close it due to lagginess, I'd want to be able to take up where I left off in HabitRPG.

**Comment by Alys** [comment] 2015-01-11 21:11
Confirmed on Firefox 34.0.5 on MacOS - tag selections are not persisted through a browser crash and restart. To me, that's a bug; to others it might be a feature. Our [trello card for tags](https://trello.com/c/HzlNeTQB/274-tags-v-2-tag-ideas-enhancements) says "Selected tags should be saved between sessions if you close your browser window or refresh the page. Should be local rather than global, so selected tags may be different on different computers/browsers."

**Comment by cgibson-dev** [comment] 2016-06-01 15:37
I never had this issue before, but I am now seeing this bug in Chrome as well. Ever since the last maintenance (or two maintenances ago), the toggled value of the tag does not persist. Occasionally, the tags "clear" (as if the 'clear' button was clicked) just by leaving the task pane, and then returning. Most of the time, it appears as if the selected tags "clear" after a certain amount of elapsed time.

**Comment by cgibson-dev** [comment] 2016-06-01 17:22
Just tested the bug and it appears that syncing the site is what is causing the tags to clear. Clicking the "Sync" button in the top right cleared any selected tags for me.

**Comment by Alys** [comment] 2016-06-02 08:36
@hbennet That's a separate issue and we have it recorded at https://github.com/HabitRPG/habitrpg/issues/7413 . No need to comment there - we know it affects all players.

I'm closing this issue because I believe an upcoming change to how temporary data is stored from the website will make both Chrome and Firefox not persist tags after the browser is closed and reopened.

**Closed as completed by Alys** 2016-06-02 08:36 UTC
