### ISSUE TITLE
Every chat message gets scrollbars

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#1273] opened 2013-07-22 22:53 UTC
Chrome browser, Windows 7 64bit, beta.habitrpg.com, user ID 7f14ed62-5408-4e1b-be83-ada62d504931. No relevant JS errors (just a bunch of warnings about accessing people's avatar pics non-HTTPS).

Starting sometime today--since I posted the top message in the screenshot, less than an hour back--every chat message gets horizontal and vertical scrollbars:

![tavern-scrollbars](https://f.cloud.github.com/assets/4501321/838523/6cb54e1e-f321-11e2-8076-87eb7ce9af96.png)

**Comment by SabreCat** [comment] 2013-07-22 22:54
Not reproducible on habitrpg.com . Possibly a result of the #1224 commit?

**Comment by litenull** [comment] 2013-07-23 07:00
Yep, indeed.

**Comment by AndreCaseyScott** [comment] 2013-07-24 13:56
balls....

**Comment by AndreCaseyScott** [comment] 2013-07-24 14:02
Was there a commit that fixed this? Not able to reproduce on beta.habitrpg.com :/

Using Chrome, Mac OSX, beta.habitrpg.com

**Comment by AndreCaseyScott** [comment] 2013-07-24 14:21
On Firefox I get this:

![screen shot 2013-07-24 at 7 06 34 am](https://f.cloud.github.com/assets/3774345/848920/c4d39b2e-f46a-11e2-89f2-544c3bb2bb03.png)

Seems that "overflow: scroll" is treated differently in each browser/OS. In this case, showing scrollbars even though they aren't required yet (the max height has not be reached). 

Removing the "overflow" properties fixes this on Firefox (Mac OSX), which requires removing the "max-height" property to prevent clipping or other nasties. The "word-wrap: break-word" property should be enough to keep the site from having weird scrolling issues, but a troll could still leave a monster essay, bogarting tavern chat.

**Comment by AndreCaseyScott** [comment] 2013-07-24 14:34
hmm, after a quick search, looks like it might be possible to hide the scrollbars, but still allow it to be scrollable (thus limiting bogartability in tavern/party/guild chat). 

Will take a look at this soon. 

http://hynchrstn.wordpress.com/2012/06/10/hide-scrollbar-but-still-scrollable-using-css/

**Comment by lefnire** [comment] 2013-07-24 18:51
merged

**Closed as completed by lefnire** 2013-07-24 18:51 UTC
