### ISSUE TITLE
modal does not close itself when you remove one deleted challenge task

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#9765] opened 2018-01-04 12:58 UTC
As reported in the Report a Bug guild bu Il Mago Azzurro (c073342f-4a65-4a13-9ffd-9e7fa5410d6b), when a challenge task is deleted by the challenge owner, and the challenge participant wants to remove the task from their own list, the modal for that does not close itself after the participant has confirmed the deletion. Steps to reproduce:

- join a challenge with some tasks
- the owner deletes a task
- click on the red megaphone/broken challenge link
- first there is the modal asking if I want to keep or remove the task
- then there is a browser alert that asks me if I want to delete the task
- click ok on that
- the other modal doesn't close on its own, but stays there
- clicking again on "Remove them" just says "task not found"
- you have to close the modal manually

**Comment by SheepD** [comment] 2018-01-04 19:37
@Alys may i work on this?

**Comment by TheHollidayInn** [comment] 2018-01-04 19:58
Please do :D

**Comment by lemoness** [comment] 2018-02-21 01:46
@SheepD Hi there! What's the current progress on this fix?

**Comment by TheHollidayInn** [comment] 2018-08-20 05:19
Duplicate of https://github.com/HabitRPG/habitica/issues/10224

**Closed as completed by TheHollidayInn** 2018-08-20 05:19 UTC
Labels: priority: minor, section: Challenges, help wanted, type: medium level coding
