### ISSUE TITLE
Being Able to Feed Pets Over and Over again.

### ISSUE THREAD

**Issue by Paot** [HabitRPG/habitica#4596] opened 2015-01-30 14:03 UTC
I found a bug where when I click on food and the pets light up with the green boarder that is you click that food item again the pets lose the green boarder, but you can still feed it of the pet and the food does not disappear. I was able to do this a few times in a row, then stopped with the assumption I could go on indefinably.

**Comment by crookedneighbor** [comment] 2015-01-31 05:31
I was unable to reproduce this. 

When I click the food item again, and then click on a pet, it just selects that pet as my current pet rather than feeding it.

Can you think of anything other details to help me reproduce it? What food item? What pet? (shouldn't matter, but since I can't reproduce it, I'd like as many details as possible)

What browser are you using?

Can you try it in Chrome and open the console (Use the keyboard shortcut Command - Option - J (Mac) or Control -Shift -J (Windows/Linux) and record any errors? If there are no errors, you should still get a message in the console about how much your pet liked the food.

**Comment by Paot** [comment] 2015-01-31 12:58
It is actually not letting me do it anymore. Maybe it was a specific bug to a specific set of coordinates. 
I will Keep testing it to see if it happens again and I'll let you know. And just for paper sake I am using firefox. 

Date: Fri, 30 Jan 2015 21:31:40 -0800

**Comment by crookedneighbor** [comment] 2015-01-31 17:32
@Paot Sounds like it was a momentary issue then. I'm going to close this, if in the future it happens again, feel free to re-open this ticket.

**Closed as completed by crookedneighbor** 2015-01-31 17:32 UTC
