### ISSUE TITLE
Sprites will not compile

### ISSUE THREAD

**Issue by sporeball** [HabitRPG/habitica#7915] opened 2016-08-19 18:02 UTC
- **User ID:** ce3d1e2b-be53-4e5e-8101-273157548178

Sprites are not compiling at all for me. I've tried running both `npm run sprites` and `gulp compile:sprites` in the node.js command line, with no result. Running either of those commands logs no other message, does nothing, and still lets me run any other command immediately after.

**Comment by crookedneighbor** [comment] 2016-08-20 12:16
What operating system are you using?
What node version?

When I run `npm run sprites`, I get:

``` bash
> habitica@3.33.1 sprites /Users/blade/workspace/habitrpg/habitrpg
> gulp sprites:compile

[08:13:16] Using gulpfile ~/workspace/habitrpg/habitrpg/gulpfile.js
[08:13:17] Starting 'sprites:clean'...
[08:13:17] Starting 'sprites:main'...
[08:13:19] Starting 'sprites:largeSprites'...
[08:13:20] Finished 'sprites:clean' after 3.24 s
[08:13:29] gulp-imagemin: Minified 1 image (saved 171.15 kB - 29.6%)
[08:13:29] Finished 'sprites:largeSprites' after 9.42 s
[08:13:33] gulp-imagemin: Minified 1 image (saved 74.94 kB - 40.5%)
[08:13:35] gulp-imagemin: Minified 1 image (saved 81.48 kB - 37.6%)
[08:13:46] gulp-imagemin: Minified 1 image (saved 217.61 kB - 34.7%)
[08:13:54] gulp-imagemin: Minified 1 image (saved 86.8 kB - 35.5%)
[08:13:54] gulp-imagemin: Minified 1 image (saved 86.88 kB - 36%)
[08:13:57] gulp-imagemin: Minified 1 image (saved 181.7 kB - 34.2%)
[08:13:57] gulp-imagemin: Minified 1 image (saved 87.34 kB - 36.8%)
[08:14:00] gulp-imagemin: Minified 1 image (saved 66.76 kB - 66.5%)
[08:14:07] gulp-imagemin: Minified 1 image (saved 23.66 kB - 25.9%)
[08:14:07] gulp-imagemin: Minified 1 image (saved 74.91 kB - 33.5%)
[08:14:13] gulp-imagemin: Minified 1 image (saved 115.49 kB - 39.1%)
[08:14:13] gulp-imagemin: Minified 1 image (saved 43.36 kB - 25.1%)
[08:14:17] gulp-imagemin: Minified 1 image (saved 72.76 kB - 34.6%)
[08:14:20] gulp-imagemin: Minified 1 image (saved 83.95 kB - 35.5%)
[08:14:20] Finished 'sprites:main' after 1.05 min
[08:14:20] Starting 'sprites:checkCompiledDimensions'...
Verifiying that images do not exceed max dimensions
All images are within the correct dimensions
[08:14:20] Finished 'sprites:checkCompiledDimensions' after 39 ms
[08:14:20] Starting 'sprites:compile'...
[08:14:20] Finished 'sprites:compile' after 15 μs
```

When you say it does nothing, you're not even getting:

``` bash
> habitica@3.33.1 sprites /Users/blade/workspace/habitrpg/habitrpg
> gulp sprites:compile
```

Do other gulp commands work? For instance, `npm run test:api-v3:unit`?

**Comment by sporeball** [comment] 2016-08-20 22:59
I'm using node.js 6.2.2 on Windows 10. Other gulp commands don't work either.

**Comment by paglias** [comment] 2016-08-21 04:03
@MrEikono Habitica's using Node 4.x Try using that version

**Comment by sporeball** [comment] 2016-08-23 23:02
Been busy, so haven't had time to try stuff out.

@paglias Would Node 4.5.0 work? Just asking because there are lots of 4.x versions, y'know :/

**Comment by paglias** [comment] 2016-08-24 01:17
Yeah 4.5 should work. You'll have to delete node_modules and reinstall all
the depencies

Il 23 ago 2016 16:02, "MrEikono" notifications@github.com ha scritto:

**Comment by sporeball** [comment] 2016-08-28 21:46
Still nothing. @paglias

**Comment by crookedneighbor** [comment] 2016-08-29 03:47
I doubt it has anything to do with the node version. Seems much more likely that it's not playing nice with Windows 10. 

If I have time, I'll try to reproduce the issue on a Windows 10 vm, but it's not the highest thing on my priority list right now.

**Comment by crookedneighbor** [comment] 2016-09-20 01:56
Was just able to boot up a Windows 10 VM (finally) and when I ran the command, it failed (because I'm missing the OS dependencies for compiling the sprites), but it still presented me error messages as I expected it to. @MrEikono I'm afraid I cannot reproduce your issue of gulp refusing to run on your system. Fairly certain there's something going on with your particular setup, and it has nothing to do with the HabitRPG repo itself, so I'm going to close this.

**Closed as completed by crookedneighbor** 2016-09-20 01:56 UTC
Labels: priority: minor, status: issue: needs investigation
