### ISSUE TITLE
The filters bar interacts weirdly with the menu containing health, experience, etc. whenever the tasks page is loaded

### ISSUE THREAD

**Issue by sporeball** [HabitRPG/habitica#7772] opened 2016-07-11 02:11 UTC
**OS:** Windows 10
**Browser:** Google Chrome
**User ID:** ce3d1e2b-be53-4e5e-8101-273157548178

Whenever the tasks page loads, the filters bar renders partially on top of the menu containing the player's avatar, health, experience, mana, and party members. Because of this, to use the scrollbar in this menu in order to see all party members, you have to click and drag on the top few pixels of the scrollbar. You can't use the arrows on either end.

The filters bar goes back to where it should be when the page is scrolled down by any amount and then scrolled up to the top again. Going to another page and then going back to the tasks page leaves the filters bar in the wrong place if it was already in the wrong place, or leaves the filters bar where it should be if it was already in the right place.

This GIF shows most of the things described above (I figured out about the arrows and the functionality when going to another page and back to the tasks page _after_ recording the GIF) --

![habitica](https://cloud.githubusercontent.com/assets/12767408/16718110/6b36c71e-46d1-11e6-83bd-7baa1f66ead8.gif)

(Sorry about the slight visual artifacts in that GIF. LICEcap isn't the best.)

**Comment by mcooledge** [comment] 2016-07-11 16:41
I just want to chime in that this is consistent for
**OS:** Windows 10
**Browser:** Firefox 47
**User ID:** 225ebf4e-8e61-4b80-93b8-74da957021fc

**Comment by PowerlinxJetfire** [comment] 2016-12-06 02:55
I've figured out the root cause of this. The [jQuery plugin](https://github.com/garand/sticky/) Habitica is using for the sticky header (the thing with health, avatars, etc.) doesn't handle dynamic content well. The plugin works by putting a placeholder element in place to keep the rest of the content (i.e. the filter buttons) below the header. But it doesn't detect when the header's size changes, so it doesn't push the filter buttons down farther when the header gets taller. The problem is fixed when the user scrolls because then the plugin _does_ check the header's height again.

The issue occurs when you load Habitica because the header's content hasn't finished loading when the plugin checks its height. The issue can also occur if the user resizes the browser window.
![habitica crop](https://cloud.githubusercontent.com/assets/4098714/20911283/f9611b7a-bb34-11e6-869d-418c2ab82334.png)

The window resize case is easy to fix because there's a browser event for that. So now I'm looking into how to detect that the header is fully loaded. Once I've got that I'll submit a PR. Any advice to point me toward an event or function that's called when the header is done loading would be appreciated!

**Comment by khipkin** [comment] 2016-12-06 04:03
@PowerlinxJetfire Nice investigation!

**Comment by PowerlinxJetfire** [comment] 2016-12-06 04:47
@khipkin thanks! Just submitted a [PR](https://github.com/HabitRPG/habitica/pull/8258) that fixes the resize case.

**Comment by PowerlinxJetfire** [comment] 2016-12-06 04:50
I still haven't found a way to know when all of the content has loaded in order to fix the page load case. You could fix it for most users with a few `setTimeout()` calls that fire at intervals (say every .2 or .5 seconds) for a few seconds after the page load. But if anyone's internet connection is slower than the last timeout, they'd still experience the issue. And overall it would be a pretty hacky solution (albeit to alleviate a problem in a hacky JavaScript implementation of CSS' `position: sticky`).

Long term, it might be better to actually switch to using CSS. Chrome is shipping `position: sticky` in version 56. At that point, Safari, Firefox, Chrome, and Opera will all support it. Edge will probably get on board at some point, but in the meantime it wouldn't necessarily hurt Edge users too much to just have to scroll to the top. You could also obviously selectively apply the current JavaScript solution to browsers without the CSS support.

**Comment by Alys** [comment] 2016-12-06 09:33
@PowerlinxJetfire Regarding the long-term view: We're part way through a project to improve the website's front-end code and that will probably change how this issue can be fixed, if the issue persists after the project is done.

**Comment by Alys** [comment] 2017-06-24 18:23
I'm closing this because we're most of the way through a project to change the website's front-end code and this is likely to no longer happen afterwards, or if it does, there'll be new code that will need to be modified to fix it.

**Closed as completed by Alys** 2017-06-24 18:23 UTC
Labels: priority: minor, help wanted
