### ISSUE TITLE
Party Disbanded, Quest Lost

### ISSUE THREAD

**Issue by tomtangent** [HabitRPG/habitica#7429] opened 2016-05-22 17:21 UTC
after the maintenance yesterday I was completely disbanded from my party and we were on the 200 gold quest: Dilatory Distress Part 1 before that. This meant that we lost our gold and our process toward completion.

_edit by admin:_
## What to do if this happens to you:

**This is almost certainly just a display glitch in the website, and you are still in your party, and in your quest if you had one running.**

**Reload your party page, possibly a few times. If that doesn't bring your party back, log out of Habitica and log back in.**

**If that still doesn't work, comment here with your User ID from Settings > API on the website. You don't need to comment here if your party does reappear after a reload or logout.**

---
## Technical Notes for Developers

kuurbis (904398f7-a6b4-48bd-82eb-3b0488ddbc82) posted this to the Tavern:

"ah, i have noticed that if i let the party page fully load, it assumes i am not in a party anymore. refreshing it does make the party appear again but only util it fully loads."

**Comment by ZhugeSong** [comment] 2016-05-22 18:24
The party I was in had the same issue. My user id is 47cc162d-84c3-4601-8b41-68f3d44d9091 and we had just started part 2 of the Golden Knight series (no actual progress lost, but I did lose the scroll).

**Comment by citrusella** [comment] 2016-05-22 19:35
Are you absolutely sure there's no way you're in the party? (That is, that there's no display glitch?) A lot of people have had trouble accessing their parties but are still in them. Have you tried clearing your cache and then going to the party page?

**Comment by remelem** [comment] 2016-05-22 21:50
My user ID is 30cb818f-bef5-4c6f-ab6d-029326b37c9f; I think I'm in the same boat. There's not an absolute way to tell at the moment as the leader of my guild is having a display issue where only one other party member's name is displayed above a "3 other members" icon. All I know is that I am no longer in a Party, I tried all the fixes and different browsers, and when my party leader tried to readd me I got the error message "Party Not Found"

**Comment by Alys** [comment] 2016-05-22 22:09
@Level1Pixel @ZhugeSong @remelem If you're still having this problem, reload the party page. You might need to do it a couple of times. If that doesn't work, try logging out of Habitica and logging back in. Comment here if you still can't see your party after doing that. 

As @citrusella says, this is probably just a display glitch, and reloading almost always fixes it. We're sorry about the trouble!

**Comment by LyrrenClock** [comment] 2016-05-22 22:58
This might be the wrong place to put this but it is tied to party display issues since the maint. the party chat will not refresh or show new messages at all until you do a hard refresh of the page and even when you do this it will spazz and do a temp display error of being not in a party which is frankly scaring me every time I have to do this just to chat with my party. but once you do this it does refresh the chat just a scary process to me at least hopefully they get these codes fixed up! Running on google chrome on windows 10 if that helps! I have yet to find any other display glitches but will post if I see them~

**Comment by Alys** [comment] 2016-05-22 23:35
@LyrrenClock I'm sorry about that! Do new messages show up when you click the "fetch recent messages" button above the party chat? They are supposed to, so if you're clicking that button and not seeing message, please do tell us!

You definitely can't be removed from your party by the problems you describe, and if some other bug did remove you, we could put you back in, so you don't need to worry too much about that! However I do know that it must be distressing and we are working to fix this.

**Comment by LyrrenClock** [comment] 2016-05-23 00:00
@Alys this seems to work thanks albeit a bit sluggish but yes guess I just got used to it auto fetching upon tabbing into that menue now it no longer does it automaticaly you have to fetch thanks though!

**Comment by calypsomatic** [comment] 2016-05-23 00:30
This has happened to me - I have logged out, reloaded, cleared cache, repeat, several times, and it still acts like I am not a member of a party.  
My user id is 3e687b68-5ba6-43ef-ad20-d8d587b4e048

**Comment by Alys** [comment] 2016-05-23 01:53
@calypsomatic I've put you back in your party and quest. Please tell me if anything doesn't look right! Tomorrow, after your Dailies have reset, please go to party chat and look for a message saying how much damage you've done to the quest boss. If you're on the website, you might need to click "fetch recent messages" before it appears. If you don't see that message, please tell us!

@LyrrenClock We'll be putting the auto-fetch behaviour back soon!

**Comment by Alys** [comment] 2016-05-23 02:36
Note to devs: kuurbis (904398f7-a6b4-48bd-82eb-3b0488ddbc82) posted this to the Tavern:

"ah, i have noticed that if i let the party page fully load, it assumes i am not in a party anymore. refreshing it does make the party appear again but only util it fully loads."

I'm adding this to the top post for easy finding later.

**Comment by sujunmin** [comment] 2016-05-23 06:12
I have not seen my name on quest participate list.
My User ID: ac6fbe37-b0dc-40d8-ba14-77dde66fbfa8
The Quest is The Birds of Preycrastination.
Thanks.

**Comment by Alys** [comment] 2016-05-23 06:30
@sujunmin You're definitely in the party and in the quest (I've checked in the database). There's 39 people in the quest. Is the quest participant list displaying only 30?

**Comment by sujunmin** [comment] 2016-05-23 06:35
@Alys only 24 :D

Xnora
strangewires
TheMoyWonder
Mikael Sai
RedBullbob
betty94044
Crystal Zou
Daein
Jasmine Redfern
Doc Pepper
Di Immortalis
Em030786
JasonNV
Psi0nyx
Tara
medeforest
pemdora
Angello
GroovyOtter
- Dinoruto

Apollo999
Sciamanna
Sreaf
Swana

I am Brown, and I am not at the list.

**Comment by calypsomatic** [comment] 2016-05-23 12:17
@Alys Thanks!  My party and quest is back!  The only thing is I collected _way_ too many things.  The quest is Dilatory Distress part 1, and I've been getting between about 1-5 things a day, and now it says yesterday I collected 17 blue fins and 11 fire coral.

**Comment by paperskye** [comment] 2016-05-23 13:21
I was having the same issue, but I could still see the party on Android. Logging out and back in on the website and party is showing again. Thanks!

**Comment by greysmurf** [comment] 2016-05-23 16:47
I also got booted from my party, my userID is 1e7e48ca-a088-4d5d-aaf3-9b7fe710dcaa .  The rest of the party members seem to be unaffected, although they report that there's 2 more members showing but they don't show who they are.  Interesting, but would love it if you guys could fix this for us! :)

Refresh and logout/login have not fixed it for me.

**Comment by sallystardust** [comment] 2016-05-23 18:57
I've tried refreshing, new window and logging out/back in. Thanks.

9b467ad9-8bf1-4cb6-84a9-622f5e3b966d

**Comment by Alys** [comment] 2016-05-23 19:56
@greysmurf @sallystardust You're both back in your parties and quests now.

You can ignore the "2 more members" text. Member counts for parties aren't accurate. We'll fix that in a few days. Sorry about that!

**Comment by Sara-lily** [comment] 2016-05-23 20:01
Someone was booted from my party as well.  I was able to add her back and we weren't on any quests, so everything's good, but if you need datapoints to track down the issue, here's her id: 

0541ee84-7a2f-4b46-8d7b-9124be129ddb

Let me know if any more details would be helpful.

**Comment by greysmurf** [comment] 2016-05-23 20:56
@Alys TYVM!  <3 I just confirmed it's all working again

**Comment by Cheesus2112** [comment] 2016-05-24 12:52
22ffea67-ba9c-4116-83be-c9662bde753f

I was the only one in my party and got booted. I was doing the Golden Knight Part 3 and had 93 damage left to deal to the boss.

**Comment by Alys** [comment] 2016-05-24 13:13
@Cheesus2112 I've recreated your party from a database back from a few days ago and set the HP to 93. Please tell me if anything doesn't look right! Tomorrow, after your Dailies have reset, please go to party chat and look for a message saying how much damage you've done to the quest boss. If you're on the website, you might need to click "fetch recent messages" before it appears. If you don't see that message, please tell us!

I actually have a partial database dump from just 48 hours ago that shows you were in the party then, so you were removed some time in the past two days. Can you think of anything that might have caused that? Did you notice any odd behaviour or anything that might be relevant?

Can you tell us if you use the website and/or Android app and/or iOS app?

**Comment by jenniferagsdale** [comment] 2016-05-24 13:32
I think this might be related: my party completed Dilatory Distress Part 1 over the weekend, but none of the rewards came through and the part 2 is not unlocked. 
user id eff066ee-2ce9-4bd0-aed0-5bceb047714e

**Comment by Alys** [comment] 2016-05-24 13:42
@jenniferagsdale 
I've given the achievement and rewards to your party. Reload if you don't see them. Please tell me if they don't appear after that!

**Comment by sujunmin** [comment] 2016-05-25 01:40
Hi @Alys , last quest i posted before had been ended, and new quest wiil be started, my mate said he can not see my name in list and party list, Could you help me to check that?
ac6fbe37-b0dc-40d8-ba14-77dde66fbfa8

**Comment by SabreCat** [comment] 2016-05-25 16:04
@sujunmin: I've restored you to the party and its ongoing quest. Can you reload and see if everything lines up for you?

**Comment by sujunmin** [comment] 2016-05-26 04:39
@SabreCat I've reloaded and still can not see me. But I still can join quest.

**Comment by jhendricks611** [comment] 2016-05-26 21:35
I am using Habitica on Chrome on a MacBook Air. Refreshing the page makes my party return; however, my quest (something about a Golden Knight) froze 5 days ago. I am unable to continue collecting testimonies (although I solve many tasks a day), and I get this message when I attempt to post in group chat:

"invalid uuid"

I'm not certain if this is the same issue as the disappearing party/lost quest one, but it feels related. Let me know if I need to relocate this request, or start a new one. 

Thank you!
3e11b4bf-6306-430c-9a2f-c9e629042606

**Comment by Alys** [comment] 2016-05-28 11:29
@sujunmin Are you still having problems? "I've reloaded and still can not see me."

@jhendricks611  @paglias has fixed one of the bugs you reported -- being unable to make any progress in the quest -- in https://github.com/HabitRPG/habitrpg/issues/7470 and I can see from the quest progress log for your party that an entry did appear for you on 2016-05-27 20:29:05 UTC. However if you don't see a quest progress message on future days, please comment on https://github.com/HabitRPG/habitrpg/issues/7470  (check first that you weren't resting in the inn and that you have clicked "fetch recent messages" to see the latest party updates).
For the "invalid uuid" message when you're posting to party chat, please comment on the other issue that you opened for that (https://github.com/HabitRPG/habitrpg/issues/7522 ) to tell us whether it is or isn't still happening. 
If you're still getting the problem of your party disappearing, reload the website when that happens.

**Comment by sujunmin** [comment] 2016-05-28 11:39
@Alys still the same. But I still can join the quest.

**Comment by Alys** [comment] 2016-05-28 12:08
@sujunmin Can you describe the problem in more detail? Is it your party mate who cannot see you in the party (if so, that person should reload the website and tell us if that doesn't help), or can you not see your own name in the party? Is there anything else that's going wrong?

**Comment by sujunmin** [comment] 2016-05-28 13:28
@alys 
1. I've reloaded, re-logined more times on mobile, web, and app(android) versions.
2. I can attend quest from the notifications email or open web, but can not accept at the android version.
3. Every mate can not see me at the participants list.
4. I can get quest completion notifications mails, also the awards for the quests.
5. These things are happened after the upgrade of habitica this time.

**Comment by sujunmin** [comment] 2016-06-13 02:17
Hi @Alys , the problems happened before at the above post were gone, thank you!

**Comment by Alys** [comment] 2016-06-13 03:23
@sujunmin Thanks for letting us know! Sorry it took so long before it was resolved.

**Closed as completed by Alys** 2016-06-13 03:23 UTC
