### ISSUE TITLE
 It keeps saying Error 400: User with id "[id here]" not found when trying to add to party

### ISSUE THREAD

**Issue by monsterthing** [HabitRPG/habitica#2379] opened 2014-01-12 18:28 UTC
I keep trying to add my friend to my party but every time i paste the code into the box i get the error 400 in the corner

I gave her my code as well and the same thing happened (and when I posted my code into my party it said i was already a member, so i gave her the right numbers_

**Comment by lefnire** [comment] 2014-01-13 05:09
dupe of https://github.com/HabitRPG/habitrpg/issues/2260 , follow progress there

**Closed as completed by lefnire** 2014-01-13 05:09 UTC

**Comment by monsterthing** [comment] 2014-01-13 23:47
It is still not working for me
