### ISSUE TITLE
Guild Notifications and Party Notifications sometimes do not automatically clear.

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#9242] opened 2017-10-21 01:52 UTC
Notifications for Guild and Party messages don’t reliably clear when you click them and go to the guild/party they are from. I’m pretty sure that Party never clears, and Guild notifications don’t clear if you go from one Guild to another, but we should definitely carefully investigate.

**Comment by CharlesStocky** [comment] 2017-10-21 23:27
Hi there, could I take this?

**Comment by Alys** [comment] 2017-10-21 23:33
@CharlesStocky Yes, thank you! Comment here if you have questions or find problems.

**Comment by Alys** [comment] 2017-11-30 07:01
In the Report a Bug guild, Aerilita (3b724a41-48d3-4048-ae27-70b258cf5a72) gave us this information:

"Regarding the bug where visiting a guild via notification doesn't clear the notification, and 'Fetch Recent Messages' doesn't either: the notification does get cleared if I do a hard refresh on the guild chat page. I tried with several ones, but I just don't have too many. This doesn't work for party notification. I tried two or three times, it stays. Not sure if it helps with the bug, but just in case."

@CharlesStocky How are you going with this issue? Do you have any questions for us? Or if real-life has got in the way and you no longer have any free time, just let us know! We understand what that's like. :)

**Comment by CharlesStocky** [comment] 2017-12-02 22:55
@Alys Unfortunately I haven't been able to get Habitica running locally. It's something to do with memory, either through docker or otherwise. I'd like to work on Habitica, but currently can't.

**Comment by Alys** [comment] 2018-02-03 23:29
I'm reopening this because we've had reports that it's still happening sometimes:

Catalin (1d7e2c6a-00ea-478f-85d6-702f70a1e5aa): 
"OBSERVATION: If there is say a notification from the "Party" and you click on Party on the menu, not on the notifications list, the notification won't disappear. The only way to make it disappear is if you click on it, directly, in the notifications list. EXPECTED: The notification should clear if the Guild, Party, etc source page has been accessed, not just by accessing the source of the notification through the notifications menu."

KrotoMax (f4662629-472b-45b1-99dc-3603be97d6ef):
"Adding to what @Catalin said: It doesn't always clear, even if you click through it multiple times"

I'll try to remember to record other reports I see here so we can see how common it is.

**Comment by joedragons** [comment] 2018-02-03 23:37
I have noticed that sometimes my number turns grey and then cleared it manually.  I noticed this morning I was more patient and the grey cleared on its own.
I also noticed once I clicked discard all and got an error.
But I haven't seen this exact behavior again...only one voice/set of eyes tho=)  Hope that helps.

**Comment by paglias** [comment] 2018-02-04 13:51
This should be fixed once https://github.com/HabitRPG/habitica/pull/9679 goes live at the end of the week

**Comment by paglias** [comment] 2018-02-09 12:52
This seems to be fixed now, as long as most messages in the chat have been sent since the last deploy to prod (around 12 hours ago). Reopen if it keeps happening

**Comment by catalincodes** [comment] 2018-02-10 21:00
@paglias  I did notice something interesting. If you are on a Guild page, click on "Sync", and there are new posts on it, a notification appears saying you have new posts on this Guild page (you actually are on it). When you click on "Dismiss All" the following error is triggered: 

&nbsp; 

![error](https://i.imgur.com/FRf5efx.png "error")

&nbsp;

The error makes sense since you guys have made it so that if you are on that Guild page, the notification should be removed, given that you see the new posts, but while it's probably gone from the back-end array of notifications, it's still present in the front-end. 

When moving to another page (or refreshing), the notification does eventually disappear.

**Comment by catalinp86** [comment] 2018-02-10 21:03
@lemoness or @paglias could you please reopen the bug. It seems that there are still some issues with it this. Good job otherwise!

**Comment by paglias** [comment] 2018-02-10 22:40
So what's happening here is that the notification is actually correctly marked as read but for a concurrency issue sometimes the number isn't updated in the UI.

So the number is corrected if you sync the user and the server value is applied and when you click on Dismiss all it tries to mark as read the notification that exists on the client but not on the server and thus it fails.

The concurrency issue was caused by fetching avatar at the same time as the notification was marked as read.

This issue has been solved now because avatars aren't fetched anymore from the server but this change is only affecting new chat messages. When all 200 messages in a guild will have been sent (or a big amount) recently this issue will disappear automatically.

Anyway I'm reopening the issue but not taking action on it right now. In a few days I'll check of it still persists and close it or find another cause but it should be fixed, just waiting for some data to update to the new version

**Comment by joedragons** [comment] 2018-02-12 13:27
FYI, I noticed this morning that I clicked on my party notifications and it stayed a grey "1" after I visited the party page.  I noticed this when I was about to return to tasks.  I hadn't noticed this yesterday so it's intermittant at best unless code changed since reopening this.
When I went to repeat (from tasks clicking to party notifications), it cleared the grey 1.
I didn't take a screen since the only thing I thought it'd prove is I'm not a liar;)

UPDATE: Noticed this again 2/28/18 (clicked party, "1" greyed but remained, clicked back to tasks grey "1" still remained).

**Comment by joedragons** [comment] 2018-02-12 23:16
PS: On another account I noticed the same message in the screen above, after my quest had started.  I had clicked dismiss all (knowing it had started from my first account) then noticed that the number was grey.  Further attempts to dismiss resulted in the message.  I believe this is similar to the error occurance I mentioned above.  I don't start new quests every day, so if that's the behavior, I wouldn't notice it but infreqently (and even then hypothetically only if I dismissed).

I probably would have tracked this seperately but it seems similar to the current convo.

<img width="209" alt="same" src="https://user-images.githubusercontent.com/9559205/36125150-e3c5bd2e-1020-11e8-98b7-676c5d558b6e.png">

Browser refresh clears the grey number.

**Comment by paglias** [comment] 2018-02-15 09:37
Most of my guilds are clearing correctly now

**Comment by Alys** [comment] 2018-02-25 11:35
From Il Mago Discorato (c073342f-4a65-4a13-9ffd-9e7fa5410d6b) in the Report a Bug guild:

"when using a notification to enter a guild often the notifications don't disappear on loading the guild, most times they disappear when I open the next notification, this time also the new notification I clicked disappear... or the notifications disappear on the next sync after I opened the guild."

**Comment by paglias** [comment] 2018-02-25 20:28
The bug is gone for more active guilds which have most avatars cached in the messages, for guilds with less activity you'll have to wait until most messages use cached avatars, then the bug will fix itself

**Comment by Alys** [comment] 2018-02-26 23:18
We've had a report  (below) of this for the Report a Bug guild itself, where messages go back to only 2018-02-21 17:39 UTC, which is after the caching feature was released 17 days ago. I.e., all messages have avatars cached.

Sevastra The Jester (845ef24d-7aa8-4e41-b2e2-2060781ea90d):

"It just happened again right here in this guild -- https://habitica.com/groups/guild/a29da26b-37de-4a71-b0c6-48e72a900dac

"I refreshed my Tasks page, and had 5 new notifications, as shown by a red badge. I followed the notification here, the badge turned grey and showed 5…then 4…and then 5 again, where it stayed. The notification for new messages was still there when I clicked on the menu. I wondered if someone had posted just as I opened the page, so I hit the "sync" button, and now the grey badge shows 4 and the notification is gone. And no-one posted in the last half an hour, so I guess it's just a slow sync thing? (please excuse my ignorance of the correct terminology…) and no more serious than the notification message errors? (The notification errors appear even when I only have one tab open, so it's not a multiple-tabs sync thing… I did notice that the error message has changed, now it just says "Notification not found". I have only the vaguest idea how this works, so I find this sync-y-winkey timey-wimey stuff fascinating…)"

The notification errors they're referring to were seeing `( { "success": False, "error": "Not Found", "message": "Notification not found." } )"`, which they'd reported previously and which I assumed were from notifications being cleared in another tab or device, but it looks like not. Perhaps the notification is being cleared when they first visit the guild but then the website shows it again, and then tries to clear it again (causing the error since the notification no longer exists on the server).


If that's a separate bug, I can log a new issue for it.

**Comment by Alys** [comment] 2018-02-26 23:22
Actually, they also added something else that I didn't include there because I thought it was a separate thing, but it just occurred to me that it could well be related:

".... (please excuse my ignorance of the correct terminology…) and no more serious than the notification message errors? (The notification errors appear even when I only have one tab open, so it's not a multiple-tabs sync thing… I did notice that the error message has changed, now it just says "Notification not found". I have only the vaguest idea how this works, so I find this sync-y-winkey timey-wimey stuff fascinating…)"

The notification errors they're referring to were seeing `( { "success": False, "error": "Not Found", "message": "Notification not found." } )"`, which they'd reported previously and which I assumed were from notifications being cleared in another tab or device, but it looks like not. Perhaps the notification is being cleared when they first visit the guild but then the website shows it again, and then tries to clear it again (causing the error since the notification no longer exists on the server).

I'm about to merge this comment into the previous one for clarity. :)

**Comment by paglias** [comment] 2018-02-27 19:22
The errors come from the fact that the notifications are read correctly on the server but the client remains out of sync due to a race condition, a sync (or any other request) will fix the count

**Comment by TheHollidayInn** [comment] 2018-07-20 15:42
Has this been reported recently?

**Comment by joedragons** [comment] 2018-07-20 16:38
I haven't noticed the error in a while.  I noticed the grey 1 (mentioned by me in 
https://github.com/HabitRPG/habitica/issues/9242#issuecomment-364921853) even after I went to party and out as recently as this week.
UPDATE: Grey occurred 8/7/18.

Image (on dismiss, after party and return to tasks):
![ondismiss](https://user-images.githubusercontent.com/9559205/43155565-bce2c5f4-8f45-11e8-9bd1-d8ce49da1573.png)

**Comment by TheHollidayInn** [comment] 2018-08-17 12:09
Sounds good. This issue is actually happening to me as well still

**Comment by paglias** [comment] 2018-08-17 12:20
It's happening to me as well, the reason is always the same: the request to clear the notification should be sent after the last one from the group page loading, otherwise one will return the notification as if it's still there

**Comment by paglias** [comment] 2018-09-01 08:20
#10628 has been reverted so I'm reopening the issue

**Comment by Alys** [comment] 2018-12-27 00:43
FYI this is still happening. I've removed some of the older comments that are no longer relevant. Here's a recent report from Il Mago, junior chemist (@ieahleen, c073342f-4a65-4a13-9ffd-9e7fa5410d6b):

_'I visit a guild from the notifications, the notification doesn't clear so next time I open the notification bubble I see the "Notification not found" (or maybe when clicking on a notification or using "Dismiss All" - anyway it happens various times per day)'_

**Comment by shanaqui** [comment] 2019-02-12 17:30
And again from Report a Bug: 

"Notifications have still some issues: I don't get anymore a "Notification not found error", but in a situation in which a notification didn't clear and would have resulted in that error, the "Dismiss all" button doesn't work, I need to sync and use again the button for all notifications to clear successfully"

**Comment by Alys** [comment] 2019-04-23 22:42
Another report os this from Arkadiy @arkadiyjs (4401fa80-29a5-4f9e-8a51-94081fb3bffd):

"After clicking on a notification from a party I'm a member of, I'm transferred to the party's page. I click on the now greyed out icon, then I click on "Dismiss All". The notification is not dismissed. I haven't checked whether the same applies to Guild notifications."

**Comment by paglias** [comment] 2020-05-14 17:53
I'm handling this in #12179

**Closed as completed** 2020-05-25 15:02 UTC
Labels: priority: medium, status: issue: in progress, section: Achievements/Popups/Notifications
