### ISSUE TITLE
Cannot change name of party without adding a description

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica#10828] opened 2018-11-09 11:10 UTC
Reported in Report a Bug:

> Birdskull (051409ee-97be-42ae-9916-dd27fb22f113) 
> It's impossible to change the name of a party without also adding a description.

Confirmed by me.

It seems to be desirable that people should be able to change their party name without adding a description; parties aren't public and descriptions aren't that important.

_edit by Alys 2020-01-19:_

This is the desired fix for this issue:

- When you edit a Party, the Description field must be optional - you should not be forced to enter a Description before you can click the "Update Party" button.
- When you edit a Guild, there should be no change to the current behaviour: a Description is mandatory (i.e., it should not be possible to delete the Description then click the "Update Guild" button).
- When you are editing a Party, you should not see an asterisk in the Description label.
- You should still see that asterisk when you are editing a Guild.
- When you are editing either a Party or a Guild, you should not see an asterisk in the "Privacy Settings" label. It's not mandatory to tick the checkbox there so that field shouldn't be marked as mandatory. (This isn't strictly related to this issue but it's a trivial change - just delete the asterisk for all cases.)

**Comment by SemperDisco** [comment] 2018-12-06 13:40
@shanaqui Can I work on this issue?

**Comment by shanaqui** [comment] 2018-12-06 13:54
'fraid I'm not the right person to ask; hopefully someone will be by soon to give you the answer!

**Comment by SabreCat** [comment] 2018-12-11 12:22
@SemperDisco: Go for it!

**Comment by akmaekki** [comment] 2019-10-29 20:31
Can I work on this issue?

**Comment by Alys** [comment] 2019-10-29 23:34
@akmaekki yes, thank you!

**Comment by akmaekki** [comment] 2019-10-31 18:23
(read if you are lazy: Right now the behavior of the code is strange, because I can create a party and afterwards change the name, but then I have to change the description of the party also.)

What should be the expected behavior if I change the name of my party?:

- I can create a party without description (like now) and don't have to specify a description?
- I can change title of party and delete or have to modify the description?

After this fix, people can just modify the name of the party without any conditions. But I think that there was a reason why previously the modification of the name of a party was linked to the modification of the description (test regression).

**Comment by Alys** [comment] 2019-10-31 21:55
In my opinion, the desired behaviour is that a party leader can change the name of the party without adding a description. As shanaqui says, parties aren't public and descriptions aren't that important.

It's possible that the requirement to add a description was coded in in the past to encourage existing party leaders to add descriptions but I'm not sure if that's still desired. No one's commented on this issue to say it's not a bug.

**Comment by Alys** [comment] 2020-01-19 01:40
I've added the text below to the top post for this issue and I've also deleted a couple of old comments that were just related to a previous contributor asking to work on this.

This is the desired fix for this issue:

- When you edit a Party, the Description field must be optional - you should not be forced to enter a Description before you can click the "Update Party" button.
- When you edit a Guild, there should be no change to the current behaviour: a Description is mandatory (i.e., it should not be possible to delete the Description then click the "Update Guild" button).
- When you are editing a Party, you should not see an asterisk in the Description label.
- You should still see that asterisk when you are editing a Guild.
- When you are editing either a Party or a Guild, you should not see an asterisk in the "Privacy Settings" label. It's not mandatory to tick the checkbox there so that field shouldn't be marked as mandatory. (This isn't strictly related to this issue but it's a trivial change - just delete the asterisk for all cases.)

**Comment by Alys** [comment] 2020-01-30 22:54
I've marked this issue as "help wanted" again and deleted a couple more old comments related to a previous contributor asking to work on this.

**Comment by anoopravella** [comment] 2020-04-10 20:31
I'd like to take a look at this.

**Comment by Alys** [comment] 2020-04-11 06:26
@anoopravella Thank you! Please go ahead and post here if you have questions or need any clarifications.

**Comment by anoopravella** [comment] 2020-04-14 16:33
I'm currently trying to test some changes on my local install, but I can't seem to create a guild because I don't have enough gems. Is there a way to get gems locally so I can test the guild behavior?

**Comment by Alys** [comment] 2020-04-15 03:19
@anoopravella You can use the "debug" button in the footer of your local install's website for that. There's a gem option in it. See the "Testing your Change Manually" section in [Using Your Local Install to Modify Habitica%27s Website and API](https://habitica.fandom.com/wiki/Using_Your_Local_Install_to_Modify_Habitica%27s_Website_and_API) if you'd like more details or a screenshot.

**Closed as completed** 2020-04-20 16:34 UTC
Labels: priority: medium, status: issue: in progress, type: medium level coding, section: Party Page
