### ISSUE TITLE
Died for no apparent reason, and then things got weird

### ISSUE THREAD

**Issue by MtnLioness** [HabitRPG/habitica#2882] opened 2014-02-18 06:23 UTC
I just died for no good reason. I'm in a solo quest, but the boss damage shouldn't have been enough to kill me. I'm pretty sure my dailies were almost all checked off before cron, so that shouldn't be it either. The only thing I can think is that the time zone on my computer changed recently (it switched to CST right around midnight EST), so maybe my account went through cron twice?

What clued me in that there might be a bug beyond the simple time-zone shift is the way the "broken" equipment changed. It initially said my hood had stopped working, and the hood became available for purchase again. A few minutes later, that had disappeared and one of my hand weapons had been downgraded instead. When I clicked on the hood in my inventory, it dealt me over 40 points of damage on top of what the other events had done. I have no idea what happened there. 

I also don't really remember what my XP or gold was before all of this happened, or where I was with streaks on various dailies, so I can't reset things accurately. Any help with figuring out where I was before all that happened would be appreciated. My ID is 2205917b-5cd0-484f-a863-b1fcdcc146b6.

**Comment by deilann** [comment] 2014-02-18 09:39
If you export your info, you can get a better idea of your streaks and whatnot. As for XP and GP... there's no real way to tell, but be generous, due to bug.

**Comment by WisTex** [comment] 2014-03-10 21:01
It might be useful if HabitRPG kept a log of such changes.  The log doesn't have to stay around forever, but a few days might be enough to be able to revert stuff like this.

**Comment by deilann** [comment] 2014-03-10 21:02
Scott, we're thinking about doing "Save States," but there are some
logistical questions on the table.

**Comment by putrocca** [comment] 2014-04-04 05:20
I just had a pretty similar problem.

I screencapped this one.  I think it's a time zone issue becuase I recently traveled from Central time to EST then back to Central.  Tonight it seems to have tallied my cron (which should be set for midnight) at 11 PM and then to have tallied it AGAIN at midnight, dealing whopping piles of damage to the party both times.  The second time it definitely registered as if not a single one of my dailies was checked off, because all my streaks were reset to zero.

![chronerrorcapture](https://cloud.githubusercontent.com/assets/6431192/2612111/52de0bd8-bbb8-11e3-8eb6-7eb504a24b4c.JPG)

To make the timing clear: I signed in a little after 11 to check off my evening tasks, and was stunned to see, checking the Party, that my cron had been tallied and had done damage.  I was looking around trying to figure out why this had happened for about 50 minutes and then noticed it had re-tallied again at midnight.  I did go to my "Settings" page in between to make sure my custom day start was still untouched, since I have never changed it, and I made no changes then, but possibly just looking at that page did something?

Interestingly I tried exporting my data but can't figure out from it what my streaks were, so have had to roughly guess to reset.  I think this killed everyone, or nearly everyone, in my party, and it certainly killed me.  :-(

**Comment by nirame** [comment] 2014-10-13 08:41
me, too, just refreshed the page and died for no reason (no boss battle damage, full health bar, nothing, just in the middle of the day for no apparent reason). Guess there's no way to get those 400 gold back, huh? _sighs sadly_

**Comment by Alys** [comment] 2014-10-13 08:42
@nirame, you asked this same question in the Tavern. Please see the answer that I've already put there for you (in brief, it's likely from boss damage that you're not seeing in chat yet, not a bug).

**Comment by nirame** [comment] 2014-10-13 09:52
As I said, I refreshed several times, yet, of course I checked this first. 

could the new chrome update cause such things?

![bildschirmfoto 2014-10-13 um 11 52 20](https://cloud.githubusercontent.com/assets/9193119/4611795/aaf58164-52be-11e4-927c-673fe62ab435.png)

**Comment by Alys** [comment] 2014-10-13 10:02
Refreshing isn't actually sufficient (if by refresh you mean reloading the page using the browser's refresh button). As I said in the Tavern, it is essential to click the sync button that is next to the send chat button - the button that is outlined in blue in your screenshot. Can you please click that again now, even if you have already clicked it, and tell us if there is any more recent damage than two hours ago?

**Comment by nirame** [comment] 2014-10-13 10:05
I did both of course, that's why it's outlined in that shot. I just did it again 2 times, still the same thing. I died about an hour ago, no damage was being done by that time, I was online for 2 hours by then, everything was fine, then I refreshed (browser refresh) my task page and suddenly - boom - you died.

**Comment by Alys** [comment] 2014-10-13 10:11
Thanks for confirming that! Please tell us your unique User ID. If you're not sure what it is, you can learn how to find it from the instructions on the page that you get to after you click "Report a Bug" from the site's Help menu.

**Comment by nirame** [comment] 2014-10-13 10:19
5774bacc-e363-4ac1-a4db-9b135c3a0e15
here's it
thanks for your support so far

**Comment by lefnire** [comment] 2014-10-13 15:57
@nirame i've tested the account locally, all seems fine on this end (refresh, cron happens, tick some stuff, refresh again, all's well). Do you have any simple replicable steps to reproduce this? Is it commonly after a certain thing that you die?

**Comment by nirame** [comment] 2014-10-13 16:02
no, this was the first time. This morning I logged in and everything was alright, I checked some tasks, gave a pet some candy and then got to the task page again and left it like this. An hour after that I open the tab, refresh (browser refresh) the page and that's it. Never happened before, and with no real reason or anything specific I did that could have caused it. O_o

**Comment by Alys** [comment] 2015-05-18 00:20
These were likely caused by [Sync Errors](http://habitrpg.wikia.com/wiki/Sync_Errors). I'm closing this but it can be reopened if needed.

**Closed as completed by Alys** 2015-05-18 00:20 UTC
