### ISSUE TITLE
Difficulties keep on getting reset

### ISSUE THREAD

**Issue by handcuff** [HabitRPG/habitica#2949] opened 2014-02-25 04:16 UTC
Every week, there's always a few tasks or habits that get their difficulties set to Easy.

**Comment by quedecir** [comment] 2014-09-14 23:12
I have a related issue. Every day since creating my account, my habit values reset back to neutral.

Background info: I've been using HabitRPG for months but fell off the wagon for a while, so about a week ago I decided to start fresh with a new tactic. I reset my account, but a few things remained (pets, inventory, attributes, maybe a few other things I can't remember) so I deleted my account and then immediately signed up again with the same email address. Voila, clean slate! So I created some habits, to-dos, and rewards, but no dailies. That was about a week ago. Ever since then, this issue has been happening to my habits. (My to-dos have been acting normally, i.e. the ones I haven't completed yet have turned orange. This morning I added a daily but otherwise I've been daily-free so far, so I can't yet comment on their behavior.)

I mostly use the Android mobile app but occasionally check in online as well. (I'm using Chrome as my browser, but I don't use the Chrome extension, just the regular website.) Since creating this new account, I haven't checked into the Inn or messed with the custom day start (but I did both with the previous account). I'm keeping all the XP/gold I get, so I don't think it's a sync issue, but who knows.

Could this have perhaps been caused by creating a new account with the same email address right after deleting the old one??

If you need it, my user ID is b6302a6d-c012-4807-976c-cda1b7838eb3.

**Comment by Alys** [comment] 2014-09-15 00:44
@quedecir : That's normal behaviour and is not related to this issue (difficulty and tash colour/value are different). I'm going to explain further in the [forum post](http://habitrpg.wikia.com/wiki/Thread:22866) that you made. We'll continue the entire conversation about your issue over there, since it's not a bug.

**Comment by lemoness** [comment] 2014-09-16 18:18
Since this is expected behavior, I'm closing this ticket - let me know if you experience any problems and I will reopen it!

**Closed as completed by lemoness** 2014-09-16 18:18 UTC
