### ISSUE TITLE
New day not starting

### ISSUE THREAD

**Issue by Nostos** [HabitRPG/habitica#2099] opened 2013-12-24 14:02 UTC
Greetings,

I noticed this morning (I'm writing from Italy) that my tasks have not reset at rollover tonight, in spite of the fact that my day start is scheduled at 4 AM. 
I tried to search this repository for the same issue, but could not find any (I can't say I actually knew _what_ to search for...I tried with "Day start" et similia), so I hope I didn't miss any report :/

As of now, most of my Dailies are checked and I cannot check them again. I guess I can give in to laziness today :D

Nostos

**Comment by dzlotnik** [comment] 2013-12-24 16:08
Same here (rollover time set to 11am EST). Fairly sure daily tasks failed to refresh for second day in a row.

**Comment by lefnire** [comment] 2013-12-24 16:23
dupe of #1057

**Closed as completed by lefnire** 2013-12-24 16:23 UTC
