### ISSUE TITLE
quest start process running multiple times incompletely

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#10974] opened 2019-02-03 01:49 UTC
On January 11, 2019 10:46:43 pm UTC, webbie @webbie_at (03117605-1b3f-4b42-a0e2-a57b135f6457) started a Veloci-Rapper quest using one scroll, and three "Your quest has started" messages appeared in party chat (see below).

There's only [one event recorded in Amplitude](https://analytics.amplitude.com/habitica/project/132025/search/03117605-1b3f-4b42-a0e2-a57b135f6457?eventFilter=quest&sessionHandle=Wg%2FFZvN_Wg%2FFxLk_J%2F5ap2_gO5_a0b2acd7-f6e6-4327-863b-137e1ecc9693&eventId=c68817f6-15f2-11e9-a8ce-0666db3e00ac) so clearly the other two attempts to start the quest failed part way through.

I'll be asking them if they recall anything unusual happening at the time but it was probably too long ago for them to remember (quite understandably!). This only came to light now because they reported today that they were affected by the negative quest scrolls bug that caused them to buy a new scroll two times while ending up with zero scrolls. https://github.com/HabitRPG/habitica/pull/10953#issuecomment-460015372

I've marked this minor priority because I suspect it doesn't happen often and the damaging effect of the bug (ending up with negative quest scrolls so that future purchases seem to fail) will be fixed when this PR goes live: https://github.com/HabitRPG/habitica/pull/10953

```
{
    "_id": "26032648-90ba-4d40-95d8-d070886752a9",
    "flagCount": 0,
    "flags": {},
    "id": "26032648-90ba-4d40-95d8-d070886752a9",
    "text": "`Your quest, The Veloci-Rapper, has started.`",
    "timestamp": ":31.645Z",
    "likes": {},
    "client": null,
    "uuid": "system",
    "groupId": "f09124d8-0513-46c3-8ceb-2b7b6d7ae7a1",
    "_meta": {
        "participatingMembers": "03117605-1b3f-4b42-a0e2-a57b135f6457, ..."
    },
    "__v": 0
}
{
    "_id": "6f991a51-1611-4d56-97dc-8f763b7065ae",
    "flagCount": 0,
    "flags": {},
    "id": "6f991a51-1611-4d56-97dc-8f763b7065ae",
    "text": "`Your quest, The Veloci-Rapper, has started.`",
    "timestamp": "2019-01-11T22:49:31.336Z",
    "likes": {},
    "client": null,
    "uuid": "system",
    "groupId": "f09124d8-0513-46c3-8ceb-2b7b6d7ae7a1",
    "_meta": {
        "participatingMembers": "03117605-1b3f-4b42-a0e2-a57b135f6457, ..."
    },
    "__v": 0
}
{
    "_id": "e11bbb15-ef06-44b2-89fa-97def76ff0f6",
    "flagCount": 0,
    "flags": {},
    "id": "e11bbb15-ef06-44b2-89fa-97def76ff0f6",
    "text": "`Your quest, The Veloci-Rapper, has started.`",
    "timestamp": "2019-01-11T22:49:31.143Z",
    "likes": {},
    "client": null,
    "uuid": "system",
    "groupId": "f09124d8-0513-46c3-8ceb-2b7b6d7ae7a1",
    "_meta": {
        "participatingMembers": "03117605-1b3f-4b42-a0e2-a57b135f6457, ..."
    },
    "__v": 0
}
```

**Comment by Alys** [comment] 2019-02-03 01:50
I've marked this minor priority because I suspect it doesn't happen often and the damaging effect of the bug (ending up with negative quest scrolls so that future purchases seem to fail) will be fixed when this PR goes live: https://github.com/HabitRPG/habitica/pull/10953

**Comment by SabreCat** [comment] 2019-11-01 18:31
With no new input since February and no clues on how to reproduce, closing this for now.

**Closed as completed by SabreCat** 2019-11-01 18:31 UTC
Labels: priority: minor, status: issue: needs investigation, section: Party Page
