### ISSUE TITLE
Hover on Health Potion moves spells a few pixels down

### ISSUE THREAD

**Issue by mczuchnowski** [HabitRPG/habitica#2427] opened 2014-01-16 10:14 UTC
Every time I hover my mouse over the Health Potion, the spell list moves a little bit down, gets back when I stop hovering over the potion. Not a biggie, but I suppose not something planned either.

**Comment by TheSisb** [comment] 2014-03-02 18:37
I notice this happening to any container which children who have popovers (the tooltip-like thing).
On the task page almost every column has the effect and the bug.  I don't have a locally editable copy, but I managed to fix it by adding an empty div inside the ULs in which it is being put into.
It may also be fixed by switching the holding container from the calculated UL (being placed between LIs is not too great) to data-container: 'body' 
http://getbootstrap.com/javascript/#popovers

**Comment by lefnire** [comment] 2014-03-03 01:09
@TheSisb exactly that, experiment with `popover-append-to-body`. CTRL+F "popover-append-to-body" at [angular-ui-bootstrap](http://angular-ui.github.io/bootstrap/)

**Comment by negue** [comment] 2014-11-17 20:59
Seems to be fixed? Cant reproduce on Win8.1/Chrome.

@mczuchnowski @TheSisb Does this issue still exist?

**Comment by mczuchnowski** [comment] 2014-11-17 21:06
@negue yup, seems to be fixed now. Tested using Chrome under Win 8.1 and FireFox under Ubuntu 14.04.

**Comment by negue** [comment] 2014-11-17 21:08
Great!, I'll close this issue.

**Closed as completed by negue** 2014-11-17 21:08 UTC
