### ISSUE TITLE
after buying an Avatar customisation set (e.g., Hairstyles) the "unlock set - 5gems" link does not disappear (takes gems again if clicked twice)

### ISSUE THREAD

**Issue by Sethycakes** [HabitRPG/habitica#4312] opened 2014-12-02 01:22 UTC
Hi! I tried to buy Hairstyle Set 1 for 5 gems by clicking the "Unlock Set - 5" button and it took my gems, but it remained locked. I tried again and it took my gems yet another time but the hairstyle set was still locked. I tried refreshing the page, but it didn't help and my gems were still gone.

UID: 8a1db51b-01f8-4794-8f9b-a0da605b9bcb

**Comment by lemoness** [comment] 2014-12-02 01:31
Hi Sethycakes!

We're very sorry about this - our domain registrar has been having trouble
today, and so there are some issues while we've been waiting for them to
fix it. As soon as that has calmed down, I'll refund you your gems, and
then you can try to buy the hair set again. It may not be until tomorrow,
unfortunately - the problem is not on our side.

Thanks for filing the report!

**Comment by deilann** [comment] 2014-12-02 01:35
Actually, Leslie, this is unrelated to the site issues. I can't find the related issue, but there was one recently, where Hairstyle Set 1 showed the ability to repurchase. I also reported this to Alys, but then forgot to make a bug report.

@Sethycakes, I have returned your gems. Do not try and purchase the set again after the site regains stability. Wait until a fix has been deployed for this issue.

**Comment by alexvan85** [comment] 2014-12-04 07:32
I had this same issue. I had purchased this previously, and noticed the other day that it was showing as locked. I spent another 5 gems to unlock it again, and my gems disappeared but the hairstyles stayed locked. 

UID: 359a4ac0-67cb-4426-9eb1-0cde62fc47fc

**Comment by Alys** [comment] 2014-12-04 07:36
@alexvan85 Are you sure they're still locked? Do they still have the dark grey background (locked) or a white background (unlocked)? When you click on one of the ones you tried to unlock, does it appear on your avatar? If you tell me your unique user ID (Settings -> API) I'll refund you gems.

**Comment by alexvan85** [comment] 2014-12-04 07:40
My mistake - because everything on my avatar page has been unlocked for so long, I didn't realise that they have a grey background if they are locked. They are unlocked but the button to "unlock" is still there, and still takes gems when I click it, but you are right, they are unlocked. 

My UID is: 359a4ac0-67cb-4426-9eb1-0cde62fc47fc

Thank you!

**Comment by alexvan85** [comment] 2014-12-04 07:41
Oh wow you are in Brisbane like me :D That is awesome!

**Comment by Alys** [comment] 2014-12-04 07:59
@alexvan85   Oh yay! :)  
As I understand it, you spent a total of 10 gems on the hairstyles, instead of 5 gems, so I have given you back 5 gems. But if that's not correct or if the gems haven't appeared, be sure to tell me!

**Comment by alexvan85** [comment] 2014-12-04 08:05
@Alys That is perfect, thank you so much! :) My OCD tendencies will just have to live with that unlock button staring at me every time I open that screen... at least I know now its just a bug and I can access it all :) Thanks again!

**Comment by Alys** [comment] 2014-12-04 08:39
We'll definitely get this fixed. :)  Just not sure when...

I've marked this as "entry level coding" because I think it should be an easy fix. The Backgrounds page has a similar "unlock set" option which does disappear on purchase, so it should be just a matter of copying that code. I hope. :) If anyone starts work on this and then finds themselves needing help, just ask!

**Comment by AdrienLemaire** [comment] 2014-12-06 01:24
Same problem here:

![img](http://i.imgur.com/5FniaDh.png)

Lost 10 gems trying to buy it :)
84497c76-4028-4dd5-8403-69b4f5b12575

**Comment by Alys** [comment] 2014-12-06 01:27
@Fandekasp Your first click would have bought it (it won't be greyed-out now). I'm about to refund the 5 gems for your second click. Reload in a couple of minutes and they'll be there.

**Closed as completed** 2014-12-14 18:42 UTC
Labels: good first issue
