### ISSUE TITLE
I Continuously Die Without A Reason

### ISSUE THREAD

**Issue by sammylau94** [HabitRPG/habitica#5013] opened 2015-04-11 14:52 UTC
The first time my character died, I thought it was because I neglected an important to-do and that I just lost a lot of health. This time (around Friday April 10th), I woke up to see 40 health points missing, even though I did most of my dailies, habits, and to-dos. I was at level 12, now bumped down to 11.

I'm also in a party and they didn't get effected.

My User ID is: c993d213-5ea1-4e0a-bfd1-0e541da93a8d

**Comment by hairlessbear** [comment] 2015-04-11 15:54
Your health is never affected by to-dos, and it's only affected by habits if you push the `-` button. The only way you should lose health automatically is from quests or missed dailies (assuming the game is working properly, of course). 

If your party is currently on a quest, please check the [party chat](https://habitrpg.com/#/options/groups/party) and hit the "Fetch Recent Messages button to find out how much damage was done to your party. Keep in mind that if you have a low constitution (check your stats [here](https://habitrpg.com/#/options/profile/stats)), you will take more damage. 

Do you have a substantial number of dailies that you didn't check off? The difficulty and color of the dailies affects how much damage they do. The harder and redder a daily is, the more damage it causes. Are some of the dailies you missed set to `medium` or `hard` difficulty, and are any of them red or dark red?

**Comment by sammylau94** [comment] 2015-04-11 21:30
I asked my party members if they were effected when my character died the first time. They said that I was the only one effected.

I don't. I check off at least 75-80% of the dailies every day, regardless of how busy I am. For the hardest difficulties, I only neglected to check off one but that didn't turn red until today. I couldn't have lost 40 health points in one day because of that, could it? As for the other Medium and Hard tasks, I check them off at least 70% of the time. And I never neglect all of the dailies in one day, to my knowledge.

**Comment by crookedneighbor** [comment] 2015-04-11 21:51
Just looked it up and @sammylau94's party is on the egg collection quest, so no chance of boss damage.

@sammylau94 My best guess is that you experienced some kind of sync error. IE, you checked off your dailies and then closed the browser window before they could finish syncing to the server (you'll see a blue progress bar appear at the top of the window when syncing is taking place).

Do you use any API add-ons? Like the chrome extension?

I would recommend taking a look at the data display tool. Clicking on the data link from the HabitRPG menu bar will automatically fill in the user id for you, so all you'll need to do is fill in the [API token](https://habitrpg.com/#/options/settings/api). 

I would check and see if there are any dailies listed there that are not showing up on the site. That happened to a user that was using a 3rd party add-on that mangled her dailies. It prevented the daily from showing up on the site, and was dealing massive damage to her everyday. Discouraging to say the least!

I'm not saying that this is happening to you, just trying to get more information to figure it out with you. :smile:

**Comment by sammylau94** [comment] 2015-04-12 00:53
Ohhh, that could make sense. I most likely wasn't even aware.

Chrome extension as in A Chrome extension or a HabitRPG extension? Because I DO have an extension on both Safari and Chrome, however I mainly use Safari. I forgot what it was called and I'm away until tomorrow morning. I will update on that.

Oh! That definitely is an idea. Thank you so much. :)

**Comment by Alys** [comment] 2015-04-12 00:56
@sammylau94 For the API token, there is a link on the Data Display Tool immediately above the ID/Token form which will take you to the place where you can find the token.

There is a HabitRPG Chrome extension that deducts health when you visit websites that you have configured as bad. It will have HabitRPG in its name, so if that does not appear in your extensions list, then you do not have it installed.

**Comment by sammylau94** [comment] 2015-04-12 00:57
Oh I see. No, I do not have a Chrome extension affiliated with HabitRPG. If this is the case, how do I get my levels back? Or do I just have to continue from the level I'm at right now?

**Comment by sammylau94** [comment] 2015-04-12 01:01
I just checked my dailies history, and there doesn't seem to be any hidden dailies that are attacking me. :/

**Comment by Alys** [comment] 2015-04-12 01:05
@sammylau94 The bug that affected you was probably https://github.com/HabitRPG/habitrpg/issues/4313
Near the top is an Advice section that will tell you how to recover from it.

**Comment by sammylau94** [comment] 2015-04-12 01:08
Thanks!

**Comment by hhirsch** [comment] 2015-05-01 15:38
Looks like this should be closed as duplicate of #4313.

**Comment by Blommelina** [comment] 2015-05-17 10:41
Hello, dear HabitRPG admins!

I have a bag report, concerning my HabitRPG account. Yesterday I finished all my daily tasks and marked them done before the end of the day (which is 2 a.m. in my case), but today somehow my characters died and lose 2 levels at the time. It was ok when I refreshed the page at night but in the morning this unexpected change happened. My hero was also not sitting on her mount and some of my daily tasks for today were marked as done. I can handle that, but I also lost my Fireproof helmet, which is a unique item and I can’t buy it any more. Could you please fix that or at least give me the helmet back?
My id number is: c54dd1e0-7dbb-4ab8-96e0-d0db52799d68
My browser is: whatsmybrowser.org/b/NC1UKPA

With best wishes and love to the whole team,

Blommelina.

**Comment by Alys** [comment] 2015-05-17 11:23
@Blommelina I'm very sorry, you were hit by this bug: https://github.com/HabitRPG/habitrpg/issues/4313. Please see the Advice section near the top for ways to recover from the damage. When you die, you can always buy back the piece of equipment that you lost.

**Comment by Blommelina** [comment] 2015-05-17 12:52
@Alys Thank you for answer!
Did I get it right, I can buy back the equipment even if that was a unique seasonal item? Sorry for asking again, but I really liked that set and that'd be a shame to lose it forever.

**Comment by hairlessbear** [comment] 2015-05-17 13:01
@Blommelina Yes, you can buy back your equipment. From the [wiki](http://habitrpg.wikia.com/wiki/Death#Lost_Equipment) (emphasis added):

> Lost equipment can be re-purchased in the Item Store. **This includes special and limited-time items that are no longer available.**

And don't forget, if you'd like to restore the gold/level/experience you lost, you can always use [Fix Character Values](http://habitrpg.wikia.com/wiki/Fix_Character_Values) to manually change the values :)

**Comment by Blommelina** [comment] 2015-05-17 20:17
Finally I've noticed this helmet in the Store! Sorry for asking all those silly questions. I feel so ashamed! 
Many thanks for your help and patience though!

**Closed as completed** 2015-07-16 08:49 UTC
