### ISSUE TITLE
Item drop, beast master, pets disappear

### ISSUE THREAD

**Issue by Hodizzle** [HabitRPG/habitica#1822] opened 2013-11-14 23:57 UTC
My UserID is d9782b4f-6b0d-404c-a3ed-add1c0259a0d. I got a drop of a candy pink potion, then suddenly was awarded the beast master award (unfairly). When I looked in my inventory, all of my eggs and potions were gone. Then I looked in my stable, currently no pet is equipped, and all pets are missing as well. 

I don't know anything about programming, but I hope this log can help:
Failed to load resource https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?_=1384462461701
Failed to load resource https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?_=1384462461702
Failed to load resource https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?_=1384462461703
Blocked a frame with origin "https://checkout.stripe.com" from accessing a frame with origin "https://habitrpg.com". Protocols, domains, and ports must match.
Blocked a frame with origin "https://ct1.addthis.com" from accessing a frame with origin "https://habitrpg.com". Protocols, domains, and ports must match.
Blocked a frame with origin "https://platform.twitter.com" from accessing a frame with origin "https://habitrpg.com". The frame requesting access set "document.domain" to "twitter.com", but the frame being accessed did not. Both must set "document.domain" to the same value to allow access.
Blocked a frame with origin "https://s-static.ak.facebook.com" from accessing a frame with origin "https://habitrpg.com". The frame requesting access set "document.domain" to "facebook.com", but the frame being accessed did not. Both must set "document.domain" to the same value to allow access.
Blocked a frame with origin "https://apis.google.com" from accessing a frame with origin "https://habitrpg.com". Protocols, domains, and ports must match.
Blocked a frame with origin "https://accounts.google.com" from accessing a frame with origin "https://habitrpg.com". Protocols, domains, and ports must match.
Blocked a frame with origin "https://platform.twitter.com" from accessing a frame with origin "https://habitrpg.com". The frame requesting access set "document.domain" to "twitter.com", but the frame being accessed did not. Both must set "document.domain" to the same value to allow access.
TypeError: Object #<Object> has no method 'indexOf'
    at h.a.ownsPet (https://habitrpg.com/app-7e1fbd67.js:17:6886)
    at h.a.selectableInventory (https://habitrpg.com/app-7e1fbd67.js:17:6949)
    at Object.get (https://habitrpg.com/app-7e1fbd67.js:6:20415)
    at h.$digest (https://habitrpg.com/app-7e1fbd67.js:5:17708)
    at h.$apply (https://habitrpg.com/app-7e1fbd67.js:5:19125)
    at HTMLButtonElement.<anonymous> (https://habitrpg.com/app-7e1fbd67.js:6:27282)
    at HTMLButtonElement.fb.event.dispatch (https://habitrpg.com/app-7e1fbd67.js:2:18085)
    at HTMLButtonElement.r.handle (https://habitrpg.com/app-7e1fbd67.js:2:14847) app-7e1fbd67.js:5
TypeError: Object #<Object> has no method 'indexOf'
    at h.a.ownsPet (https://habitrpg.com/app-7e1fbd67.js:17:6886)
    at h.a.selectableInventory (https://habitrpg.com/app-7e1fbd67.js:17:6949)
    at Object.get (https://habitrpg.com/app-7e1fbd67.js:6:20415)
    at h.$digest (https://habitrpg.com/app-7e1fbd67.js:5:17708)
    at h.$apply (https://habitrpg.com/app-7e1fbd67.js:5:19125)
    at HTMLButtonElement.<anonymous> (https://habitrpg.com/app-7e1fbd67.js:6:27282)
    at HTMLButtonElement.fb.event.dispatch (https://habitrpg.com/app-7e1fbd67.js:2:18085)
    at HTMLButtonElement.r.handle (https://habitrpg.com/app-7e1fbd67.js:2:14847) app-7e1fbd67.js:5
TypeError: Object #<Object> has no method 'indexOf'
    at h.a.ownsPet (https://habitrpg.com/app-7e1fbd67.js:17:6886)
    at h.a.selectableInventory (https://habitrpg.com/app-7e1fbd67.js:17:6949)
    at Object.get (https://habitrpg.com/app-7e1fbd67.js:6:20415)
    at h.$digest (https://habitrpg.com/app-7e1fbd67.js:5:17708)
    at h.$apply (https://habitrpg.com/app-7e1fbd67.js:5:19125)
    at HTMLButtonElement.m (https://habitrpg.com/app-7e1fbd67.js:12:1204)
    at HTMLButtonElement.fb.event.special.(anonymous function).handle (https://habitrpg.com/app-7e1fbd67.js:2:21631)
    at HTMLButtonElement.fb.event.dispatch (https://habitrpg.com/app-7e1fbd67.js:2:18085)
    at HTMLButtonElement.r.handle (https://habitrpg.com/app-7e1fbd67.js:2:14847) app-7e1fbd67.js:5
TypeError: Object #<Object> has no method 'indexOf'
    at h.a.ownsPet (https://habitrpg.com/app-7e1fbd67.js:17:6886)
    at h.a.selectableInventory (https://habitrpg.com/app-7e1fbd67.js:17:6949)
    at Object.get (https://habitrpg.com/app-7e1fbd67.js:6:20415)
    at h.$digest (https://habitrpg.com/app-7e1fbd67.js:5:17708)
    at h.$apply (https://habitrpg.com/app-7e1fbd67.js:5:19125)
    at https://habitrpg.com/app-7e1fbd67.js:5:24606
    at g (https://habitrpg.com/app-7e1fbd67.js:4:16090)
    at https://habitrpg.com/app-7e1fbd67.js:4:17786 

Please fix my account :(

**Comment by lefnire** [comment] 2013-11-15 00:22
dupe of https://github.com/HabitRPG/habitrpg/issues/1818 , please refresh the page

**Closed as completed by lefnire** 2013-11-15 00:22 UTC
