### ISSUE TITLE
Casting spells triggers boss damage

### ISSUE THREAD

**Issue by Mairi012** [HabitRPG/habitica#6156] opened 2015-11-01 14:26 UTC
I finished all of my Dailies yesterday, and my cron ran normally with no damage.  My cron is set to run at 10pm - I changed it to this time months ago, and it has been working fine at that time, until now.  My only suspicion is that it has something to do with my changed cron time and the fact that the seasonal time change happened last night.  But, the numbers are weird.

This morning, at about 7:30am I checked in and cast boost spells (Earthquake x4, and Ethereal Surge x4).  After I had cast all these spells, I got a damage alert, and when I checked the party page, it showed that I had triggered boss damage twice: before the first spell, and after the second.  I took no damage from Dailies.  It did wipe out my buffs (from previous Perfect Day, from spells cast earlier that day by a party member, and from my first two Earthquake spells).  The boss damage did affect all of my party members.

I've included the text of the party chat log for that period below, showing the timing.  Also my user stats, and the User Data Display stats as if this morning.  It is notable that the amount of damage done does not correspond to the amount of boss damage predicted by today's Dailies.

I run Habitica via Firefox on my desktop PC.  I do have the app installed on my iPad, but I have not used it there for some weeks.  My PC and my iPad do have the same timezone setting.

User ID: a69c43cd-63e2-476e-8ef2-ab020e42738a
Group ID: 56c61186-652b-44d3-bbb5-7accbdbbfa20
## Party chat log - 1 Nov 2015 @ 7:41 am

Mairi casts Ethereal Surge for the party. -13 minutes ago+1  
Mairi casts Ethereal Surge for the party. -13 minutes ago+1  
Mairi casts Ethereal Surge for the party. -13 minutes ago+1  
Mairi casts Ethereal Surge for the party. -13 minutes ago+1  
Mairi casts Earthquake for the party. -13 minutes ago+1  
Mairi casts Earthquake for the party. -13 minutes ago+1  
Mairi attacks Crystal Colossus for 0.0 damage, Crystal Colossus attacks party for 22.4 damage. -13 minutes ago+1  
Mairi casts Earthquake for the party. -13 minutes ago+1  
Mairi casts Earthquake for the party. -13 minutes ago+1  
Mairi attacks Crystal Colossus for 0.0 damage, Crystal Colossus attacks party for 22.4 damage. -13 minutes ago+1  
Poolwatcher casts Tools of the Trade for the party. -5 hours ago+1  
Poolwatcher casts Tools of the Trade for the party. -5 hours ago+1  
Poolwatcher casts Tools of the Trade for the party. -5 hours ago+1  
Poolwatcher casts Tools of the Trade for the party. -5 hours ago+1  
Poolwatcher attacks Crystal Colossus for 11.1 damage, Crystal Colossus attacks party for 0.0 damage. -5 hours ago+1  
parallaxia attacks Crystal Colossus for 52.0 damage, Crystal Colossus attacks party for 0.0 damage. -9 hours ago+1  
Mairi attacks Crystal Colossus for 32.1 damage, Crystal Colossus attacks party for 0.0 damage. -10 hours ago+1   
## User Stats - 1 Nov 2015 @ 7:41 am

Stats
Health: 50/50
Mana: 91/508
Gold: 12
Level: 87
Experience: 1684/2900
Equipment
Jean Chalard's Noble Tunic: 25 CON 25 INT 
No Back Accessory
No Body Accessory
No Eyewear
Nameless Helm: 25 STR 25 INT 
No Head Accessory
No Shield-Hand Equipment
Golden Staff: 10 PER 18 INT 
Attributes
Strength: 68  
    Level: 43
    Equipment: 25
Intelligence: 239  
    Level: 43
    Equipment: 68
    Class Bonus: 9
    Allocated: 87
    Buffs: 32                    <<--  NB: this is the buff from 2 Earthquake spells.  All other buffs are gone.
Constitution: 68  
    Level: 43
    Equipment: 25
Perception: 58  
    Level: 43
    Equipment: 10
    Class Bonus: 5
## User Data Display Tool stats - 1 Nov 2015 @ 7:41 am

```
50    Current Health
12    Dailies Incomplete
20.5    Est. Damage to You
10.7    Est. Damage to Party
0    Damage to Boss
3    To-Dos Due Today
0 / 14    Drop Count / Cap
```

**Comment by Alys** [comment] 2015-11-01 23:08
I'm sorry about this! Your cron ran a second time today because of the daylight savings change. It's odd that you took no damage form your Dailies, but unless that keeps happening in future crons, we can consider it to be a once-off glitch.

Your Custom Day Start of 10pm might be causing some unexpected behaviour, because it's making Habitica treat each day as if it were yesterday, until 10pm. This will affect which Dailies are due and that might have been what made the boss damage to be higher than is predicted now. For details, please see the "Examples and a Warning..." section in [Custom Day Start](http://habitica.wikia.com/wiki/Custom_Day_Start) and ask here if you have questions.

**Comment by Mairi012** [comment] 2015-11-01 23:23
Thanks, Alys.

Yeah, I'd figured out that my days were actually starting late, instead of early, and I was OK with that.

I'm not worried about this as a regular thing - it has been fine for months, and it did seem likely to be related to the time change.  On the other hand, the specific behaviour is downright weird.  Among other things, cron clearly ran three times, not just two.  And none of the numbers make sense.  I figured I'd better send you what data I could, in case it is helpful for debugging related issues.  Clearly there's _something_ messed up here.

Anyway, I'm happy if you roll this one in with other related issues.  I just wasn't sure what it might be related to.

**Comment by Alys** [comment] 2015-11-02 08:30
Timezone maths is weird, especially when you bring custom day starts into the equation. :-/ It doesn't completely surprise me that cron ran three times. We are working on a fix, it's just a bit painful to get it right. Thank you for the bug report. I'll close it now since we have the timezone problem reported in a few other issues, but if you do notice anything similar happening when there's no timezone changes, please comment here and we'll keep looking at it.

**Closed as completed by Alys** 2015-11-02 08:30 UTC
