### ISSUE TITLE
Character resetted and dead after page refresh

### ISSUE THREAD

**Issue by sehiralti** [HabitRPG/habitica#818] opened 2013-04-14 15:57 UTC
I just refreshed the page because the page was disconnected (as I usually do with this problem). This time though, I was logged out of the page and sent back to the home page. When I logged back in, all my dailies, to dos, tasks, rewards were gone, and my character was dead. I know that I can get back my levels and golds etc., but is there a way to get back the dailies? That's the most important because I really don't feel like starting from scratch.

**Comment by lefnire** [comment] 2013-04-14 16:02
Is this Oguz from Facebook? (just wanna make sure it's not happening to multiple people right now). What's your [user id](https://github.com/lefnire/habitrpg/wiki/User-ID) ? How long ago (roughly) did you register on the site, and when was the last time you remember having had to re-login (expired cookie, for example). See https://github.com/lefnire/habitrpg/issues/459 for what I'm currently mulling might be happening, but I can explore more with some deets

**Comment by sehiralti** [comment] 2013-04-14 16:06
Yeah, it's me! :) My Id is: 5b28c7d6-bf1b-441f-ac08-9c16b28ef2a9. I registered a long time ago, it should be January. I never had to re-login before. The only problem was, if I tried logging in from another computer, I would die, so I was always using my computer which logged in automatically. But using Safari in my computer never resulted in a log out. Maybe it's a Safari problem?

By the way, now when I log-in, my name appears. It used to be "anonymous".

**Comment by frrmack** [comment] 2013-04-14 16:43
Same thing happened to me. User id: 0b3ac601-1f1d-45ed-9992-3149c4a91653

I login from two computers, one Windows Vista, the other Ubuntu 10.10, using Chrome in both.

Everything, dailies, habits, inventory, profile name, etc., any data associated with the account is gone.

I don't remember when was the last time I logged in with my credentials, but both computers were logged in for a while (one or two weeks, maybe), and refreshing would retrieve my data without any problems.

**Comment by lefnire** [comment] 2013-04-14 16:45
for both of you - do you get full-fledge blank tasks, or is the account back to the "start" form with dummy tasks (1h productivity, cake, etc)

**Comment by frrmack** [comment] 2013-04-14 16:45
Start form with dummy tasks

**Comment by sehiralti** [comment] 2013-04-14 16:46
Yes, dummy tasks. They're all red though. It's as if I've been using those since signing up and failing miserably (around -400 in points).

**Comment by frrmack** [comment] 2013-04-14 16:48
My dummy tasks are not all red. They are exactly the same colors as the regular start form. [I don't know if this is relevant at all, but I started using habitrpg 10-15 days ago]

**Comment by lefnire** [comment] 2013-04-14 16:55
Ok thanks my friends. Hang tight, I'm gonna be diving into database backups with your account IDs over the next hour.

**Comment by sehiralti** [comment] 2013-04-14 17:00
Thanks a lot! This made me realize how much HabitRPG became a part of my life. I feel like I must be checking off things that I do now.

**Comment by lefnire** [comment] 2013-04-14 17:07
On second thought, User Id isn't helpful in this case because it looks like the accounts were reset (including api keys). Could y'all send me your usernames or email address or something ([email me](mailto:tylerrenelle@gmail.com) if privacy concern). Sorry for all this back and forth

**Comment by frrmack** [comment] 2013-04-14 17:08
username: frrmack
email: irmak.sirer@gmail.com

**Comment by lefnire** [comment] 2013-04-14 17:08
awesome thanks, and i found your info @sehiralti so no worries

**Comment by sehiralti** [comment] 2013-04-14 17:09
Ok, thanks!

**Comment by earthbutterfly** [comment] 2013-04-14 17:12
Hey, I had a similar thing where I logged on and it said I died, even though I had full health and not many red dailies.

User ID: bfcea6b1-ed04-47d0-af76-953fa224da4f

I saw what you just posted about needing usernames etc, but I just logged on through my Facebook - did you need those details or some other ones?

My e-mail (if it helps) is: rebecca.eva.lawson@gmail.com

**Comment by lefnire** [comment] 2013-04-14 17:19
@frrmack can you just try logging out and / or clearing cache, cookies for habitrpg.com, then logging back in? I'm looking in the databsae, and the username/email account looks perfectly intact, but it's a different account from the user id you gave me in the beginning - _that_ account has no auth property associated with it, so I'm surprised it's letting you in

**Comment by lefnire** [comment] 2013-04-14 17:21
@earthbutterfly but you didn't lose any data I hope? aka, no deleted tasks? if so, this is the issue you're experiencing: https://github.com/lefnire/habitrpg/issues/777 (separate issue). Use the restore tool to set yourself back (explained in that thread). Quick, i'm gonna edit your post to remove the API token - we wanna keep that secret (user id is safe to publicize)

**Comment by lefnire** [comment] 2013-04-14 17:29
@sehiralti yours on the other hand is a dilema. I have a hunch yours was victim to https://github.com/lefnire/habitrpg/wiki/Restoring-Your-Account#user-not-found (last section), because I'm going through monthly backups -  back to my very oldest database backup from february, and your account is always in demo / starter mode - but with that facebook auth tied to it. I think the browser session got corrupt somehow (very common during the early days of Habit), and it was saving data to a user account not associated with an auth property. What I'll need, if you can think of something, an **exact** task title, or something specific I can look you up by.

**Comment by frrmack** [comment] 2013-04-14 17:29
Emptied the cache, killed the cookie, refreshed, and logged in again. (The tour started again, etc. so I know the whole fresh start thing worked). I did log in, all the data is still missing.

I looked at the settings again, and I don't know why, but now the user id is different:
39590194-a9f4-48ad-bab3-f05f2c1b0b76

**Comment by sehiralti** [comment] 2013-04-14 17:32
Hmm, in the dailies, there should be "1h Satsioppi" "1h Homework" "1h Swedish" "1h Piano Practice", among other things. There might also be "30m Schenker Research". I hope I remember them exactly. Let me know if those don't turn up, so I can think of some other titles.

**Comment by earthbutterfly** [comment] 2013-04-14 17:34
Thanks for pointing me to the right thread (yes, that is what happened).

I'm not sure what all the input values are meant to be - obviously level and HP are easy, but I forgot how many tokens I was on and XP etc - is there any way for you to find a cached copy or something and find out these details for me? Was really doing so well... :/

Also, I don't know what to put in for items. I know I had purchased all that were available and only my own personal rewards and the Potion were left, but I don't know how many this was?

**Comment by sergiobc** [comment] 2013-04-14 17:44
The same with me,
Login: zergio

**Comment by lefnire** [comment] 2013-04-14 17:51
@earthbutterfly can you chime in on the other ticket with those particulars? sorry, my brain's all a-scatter on this thread

**Comment by lefnire** [comment] 2013-04-14 18:03
@sergiobc your account looks to be having the same issue as sehiralti, can you give me an exact task name to find by?

@sehiralti, those tasks were helpful - I found your lost account as a result, so hopefully a refresh should fix you. Can you try logging back in?

I think what's happening here is everyone who was victim to that above-mentioned lost-account issue from january-ish... I think Express has recently invalidated the session table, or maybe just those particular users' sessions, and so it's showing up for everyone all at once. I'm sorry guys :( this is crazy town

**Comment by lefnire** [comment] 2013-04-14 18:04
as for @frrmack, that one is different than other people's issues - that's a really weird bug, it looks like each time you log in, it ignores your actual account (which looks in tact in the database) and creates a new dummy account with no auth property. Can you try from a different browser? Firefox maybe?

**Comment by sehiralti** [comment] 2013-04-14 18:36
Yes! Everything's back to normal. I should add that previously my name was "anonymous" and now it displays my correct name. Maybe this will fix my problem about not being able to log in from other places.

Just thinking out loud, maybe this name being displayed as "anonymous" is a symptom for this problem?

**Comment by lefnire** [comment] 2013-04-14 18:39
well, it's because you were getting the dummy user - which is anonymous. 
- The symptoms: dummy tasks, anonymous name. (in fact, if you have _no_ tasks, it's a different issue)
- The cause: the login's not reaching your actual account, which has lost it's `auth` property - and your browser has been tied to a corrupt Express session, which recently got invalidated.
- The fix: give me a super-unique task name, i'll look you up and do some database surgery.

so @sehiralti is fixed, I need a unique from @sergiobc, @earthbutterfly was a different issue - now @frrmack is the only mystery.. no clue what's going on there, so I'll just wait to hear back on different browsers see if that helps

**Comment by frrmack** [comment] 2013-04-14 18:43
I just logged in from firefox and it's all there!

That's really weird. But at least I got my precious, precious data :)
Thanks.

I've been using chrome on both windows and linux thus far, and this is the only time this happened. Until tonight at around 9-10, I won't know if the chrome in the windows machine also has that same problem.

**Comment by lefnire** [comment] 2013-04-14 18:45
Very weird. Someone else was experiencing Chrome login issues, but with Facebook: https://github.com/lefnire/habitrpg/issues/814 . I'm developing primarily to Chrome, since it's far-and-away the majority browser for Habit. I'll start investigating.

**Comment by lefnire** [comment] 2013-04-15 14:54
https://github.com/lefnire/habitrpg/issues/825 for the Chrome login issue

**Comment by paglias** [comment] 2013-09-09 15:56
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!

**Closed as completed by paglias** 2013-09-09 15:56 UTC
