### ISSUE TITLE
Checklist behavior for To-Dos is still kinda funky

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#2629] opened 2014-01-29 01:23 UTC
There seem to be some inconsistencies in the scoring of To-Dos with checklists, still.
- The user is rewarded with a number of MP equal to the number of checklist items, regardless of how many are actually checked off.
- The main checkbox (the fact that you're knocking off a To-Do in the first place) is counted equivalently with completed checkboxes for experience and gold awards, but not for MP.

My suggestion: a To-Do with an arbitrary number of checklist items, but only one checked off, should act exactly the same as checking off a To-Do without a list. 1 MP, 1x multiplier on gold and experience. Checking off two checklist items then completing the To-Do should be 2 MP, 2x gold, 2x experience, and so on.

**Comment by SabreCat** [comment] 2014-01-29 01:28
I'd also be okay with having checked-off items always add to the multiplier, representing _additional_ effort on top of whatever the main To-Do is, but that'd need to be fixed for MP... yet per [this pull](https://github.com/HabitRPG/habitrpg-shared/pull/87) I guess we decided it's intended behavior? Just want it to be consistent, heh...

**Comment by deilann** [comment] 2014-01-29 04:39
I'd like a prompt when checking off a To-Do with a checklist: "Did you do all items?" If the answer is no, then it acts as if the unchecked ones are unchecked. If you say yes, you get the full everything, as if they were all checked. Or at the very least, a "check all" option.

**Comment by ghost** [comment] 2014-01-29 17:09
If the intended behaviour for Daily checklists is that checking the main box is the same as checking all the list items plus the main box then changing that behaviour for To Dos only is going to create confusion and frustration. The "Did you do them all?" dialogue is a good idea if you are going to change the behaviour.

**Comment by patena** [comment] 2014-01-29 22:01
Wow, I had no idea it gives you points for all of them! I regularly have ToDos with a few of the checklist items being "extra effort", because I assumed I would only get points for them if I checked them, but I still considered the basic task done without them. That seems counterintuitive to the whole idea of checking things - why are the checkboxes even there if checking them doesn't make any difference?

The checklist behavior between dailies and ToDos is already different (dailies don't have a multiplier at all, right? The checklists only matter for damage calculations?), so I don't see an issue with it becoming even more different.

I think having the ToDo count as 1, plus 1 for each checked item, for all purposes, sounds good. 
A "Did you do them all?" question would annoy me, since I would have checked them if I had done them, but I could live with the minor annoyance. Or it could be an option or something.

**Comment by ghost** [comment] 2014-01-29 23:42
To be clearer then: Right now checking the main box gives the same result for both Dailies and To Dos and results in the program assuming all checklist items have been done. The only difference is in the math which the user has no control over anyway. Making them behave differently when it comes to checking off items is not intuitive.

**Comment by patena** [comment] 2014-01-30 00:11
It doesn't give the same result, though. The program doesn't necessarily assume that checking a daily means all checklist items have been done - it just assumes the task has been done. Whether that should be interpreted as "all items have been done" or "enough items have been done to consider it good enough" is entirely up to user interpretation - as I said, for me and apparently other users the intuitive version is different than for you, which probably means this should be an option if possible.

What actually happens is that checking a Daily with a checklist gives you X experience and gold; checking a ToDo with a checklist gives (X+n_total_checklist_items) experience and gold, and some people are arguing for switching the latter to (X+n_checked_checklist_items). Both of the possible ToDo behaviors seem equally different from the Daily behavior to me, and the difference is just math in both cases.

**Comment by deilann** [comment] 2014-01-30 00:18
But if it asked if all items were completed and explained the differences,
it could become intuitive for everyone. ;)

**Comment by colegleason** [comment] 2014-01-30 00:21
You are a modal junkie.

**Comment by deilann** [comment] 2014-01-30 00:22
Sob, it's true.

**Comment by patena** [comment] 2014-01-30 00:26
Making it ask sounds fine, and may be the best way to prevent different people assuming different things. 
Better yet, make it ask to start with, and let the user set one or the other as the assumed behavior in options, to stop it asking every time. 

(btw there have already been two issues about this, which were closed for a reason I cannot determine - here are the links, I don't know if there's a nicer way of linking them. http://github.com/HabitRPG/habitrpg/issues/2405 and http://github.com/HabitRPG/habitrpg/issues/2327 )

**Comment by deilann** [comment] 2014-01-30 00:33
Nah, I disagree. I'd like to have it ask every time. Think about this --

I have a really long to-do. Most of the time, I want it only to register
what I've checked off. But I've completed all of the items on this and
don't feel like checking off the last 6 individually before checking it.

If it asks me, I can just let it know "Yes! I did do all of the items."

Otherwise, I'd have to either check them all off one by one (very annoying
when things are laggy) or I'd have to go change my settings.

(But then again, I'm also a modal junkie, as Cole pointed out. I really, really like modals.)

And I think those were closed because SabreCat referenced them in a PR,
which changed the way things work.

**Comment by patena** [comment] 2014-01-30 00:38
So give "always ask" as another option! ;)
I'm fairly sure I would be more annoyed by having to answer an extra question every time than by having to check extra checkboxes sometimes, but it depends on the user, yes.

Ah, okay, I saw the PR now - and now I'm even more confused. The PR says it was merged, so only checked checkboxes should get points, but apparently it's just not working... Oops.

**Comment by deilann** [comment] 2014-01-30 00:45
I'd say start off with always ask, see how annoying it is, and if it's a
problem, add the layer of complexity of settings as an option. it could
also be part of the "advanced settings" of the To-Do.

**Comment by patena** [comment] 2014-01-30 00:50
Putting it in per-ToDo settings wouldn't help - setting that for each new ToDo would require just as much clicking as answering the question. But yeah, we could stick with always ask to start with. Still much less work than having to delete all the undone checklist items by hand, which is what I currently have to do to get my preferred behavior. 

(I still think just giving points only for checked items would be better, and that seems to have been the decision in the previous issues, but if enough people find that unintuitive, then asking is fine too.)

**Comment by deilann** [comment] 2014-01-30 00:52
Well, partially it's unintuitive, partially with the way the site lags,
checking off 6+ items in a row before checking off the To-Do can be quite a
hassle, even on a computer, never mind on a tablet. I'd also be happy with
a "check all" button, and Justin the Guide explaining how Checklists work
in the walkthrough.

**Comment by patena** [comment] 2014-01-30 01:00
Makes sense. It doesn't lag that badly for me, although I haven't tried it on a tablet. A "check all" button sounds like a good solution too.

**Comment by SabreCat** [comment] 2014-01-30 01:05
One correction on the conversation here: Checking off a To-Do with unchecked boxes _does not_ give you Experience and Gold multipliers for the unchecked ones, anymore. It gives you _Mana_ multipliers for unchecked ones still, which is what prompted me to write up this ticket.

If a To-Do without a checklist gives you 10 XP, 1 Gold, and 1 MP, these are some examples of the current behavior:

To-Do with 5 checklist items, none of them checked off: 10 XP, 1 Gold, 5 MP.
To-Do with 5 checklist items, 2 of them checked off: 30 XP, 3 Gold, 5 MP.
To-Do with 5 checklist items, all 5 of them checked off: 60 XP, 6 Gold, 5 MP.

That seems weird to me in the ways described in the issue ticket above, even though it is partially taking checkmarks into account.

**Comment by patena** [comment] 2014-01-30 01:05
Yes, oops, I mis-read the problem. That definitely seems weird.

**Comment by SabreCat** [comment] 2014-01-30 01:51
Setting aside the discussion of modals for the moment, it sounds like we're agreed that Mana should work the same as Gold and Experience. But should the main To-Do box count as its own thing (i.e., you get credit for 1 + the number of accomplished checklist items), or not (if you add a checklist, you get the value of each accomplished checklist item, no +1)? The first way says "A To-Do always represents accomplishing something, even if it's got a sublist with nothing checked off in it," while the second is more like "the main To-Do is just a container for a checklist of other To-Dos."

**Comment by deilann** [comment] 2014-01-30 01:55
I say the To-Do itself is an accomplishment, along with all the subtasks.

So n+1

If nothing was accomplished, one should not check off the To-Do, and
instead, delete it.

**Comment by patena** [comment] 2014-01-30 01:55
I would tentatively vote for 1+n, since otherwise we could have ToDos that give nothing when checked, which seems silly. But I can see the argument for the other option, too.

I've definitely done my ToDos both ways - either as containers for a list of things, or as a "Do thing" ToDo with the checklist only used to list one or two extra things I could do while doing the main one (so it would make sense to get gold/xp even if none of them were checked). For me the former tends to happen with long lists and the latter with short lists, and the n vs n+1 difference is more pronounced with short lists, thus my vote.

**Comment by colegleason** [comment] 2014-01-30 02:06
@SabreCat What happened was that GP/XP and Mana were out of sync here: https://github.com/HabitRPG/habitrpg/issues/2324#issuecomment-31961807

I changed it to be somewhat in sync here: https://github.com/HabitRPG/habitrpg-shared/pull/87

You changed it again here: https://github.com/HabitRPG/habitrpg-shared/commit/a770d0c72f7ec836dfbc2e0f03d2a51acae3e057

And now it is out of sync again.

**Comment by colegleason** [comment] 2014-01-30 02:18
This sounds like there is enough contention that maybe it should be a poll
or even a user preference.

On Wed, Jan 29, 2014 at 7:55 PM, Weronika Patena
notifications@github.comwrote:

> I would tentatively vote for 1+n, since otherwise we could have ToDos that
> give nothing when checked, which seems silly. But I can see the argument
> for the other option, too.
> 
> I've definitely done my ToDos both ways - either as containers for a list
> of things, or as a "Do thing" ToDo with the checklist only used to list one
> or two extra things I could do while doing the main one (so it would make
> sense to get gold/xp even if none of them were checked). For me the former
> tends to happen with long lists and the latter with short lists, and the n
> vs n+1 difference is more pronounced with short lists, thus my vote.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/HabitRPG/habitrpg/issues/2629#issuecomment-33653396
> .

## 

## Cole Gleason

Student, University of Illinois at Urbana-Champaign
Email: cg@colegleason.com
Website: colegleason.com

**Comment by deilann** [comment] 2014-01-30 02:20
Or a modal asking you which you want. :P

(not serious)

**Comment by lorian** [comment] 2014-01-30 04:28
I would like to suggest that, at the very least, the pop-up box asking whatever should NOT appear if you have already checked off all items!

**Comment by Alys** [comment] 2015-05-17 23:30
I'm going to close this because the initial bug has been fixed. 

The To-Do checklist behaviour discussed in https://github.com/HabitRPG/habitrpg/issues/2629#issuecomment-33556040 and most of the following comments is interesting, but it might be best to add it to Trello with a link back to this issue for the details. I fear that if we try to implement it from this issue, it'll keep on being ignored since the bug has been fixed.

**Closed as completed by Alys** 2015-05-17 23:30 UTC
