### ISSUE TITLE
dragging tasks sometimes results in just selecting text

### ISSUE THREAD

**Issue by mattrozak** [HabitRPG/habitica#324] opened 2013-02-07 04:57 UTC
since the new push today, sometimes when I try to drag a task up or down I just end up selecting the text and surrounding area. sceenshot below...

Chrome 24.0.1312.57 on OSX 10.8
![Screen Shot 2013-02-06 at 11 54 25 PM](https://f.cloud.github.com/assets/1066386/134551/d342a21a-70e2-11e2-93ec-1d90929a98df.png)

**Comment by mattrozak** [comment] 2013-02-07 05:00
I should note that the cursor is _on_ the task (it's a four-way arrow) and is not in between two tasks when i initially click.

**Comment by horusofoz** [comment] 2013-02-07 08:54
@lefnire Confirmed. This has also been annoying me all day. Suspect since the last code push.

Chrome Win7

**Comment by Pandoro** [comment] 2013-02-07 08:55
Confirmed on ubuntue 10.04, FF17 as well

**Comment by StanLindsey** [comment] 2013-02-07 08:56
Confirmed, but i think it seems to happen when the page isn't fully loaded. Try refreshing the page if you have this issue.

**Comment by rikikiangel** [comment] 2013-02-07 13:38
My habits suddenly got rearranged today by itself and I tried to rearrange it which I can't(not sometimes, cannot at all), refreshing doesn't work, forgot to say the page is fully loaded.
Using Opera 12.12, Windows XP

**Comment by DesignLemming** [comment] 2013-02-07 21:24
Had this problem this morning but a refresh seemed to fix it and I was able to reorder things. Checked back in this afternoon and the order was back to the pre-fixed one but again unable to drag and drop. Tried a refresh and was able to move one thing right away but then couldn't drag any more. Refreshed a few time any was able to fix everything but after logging out and back in everything reverted back the the old order.

On win XP, Chrome.

**Comment by killroy42** [comment] 2013-02-08 08:32
Currently cannot move anything, even after refreshing.

**Comment by lefnire** [comment] 2013-02-08 16:04
Sort is broken for everyone, hang tight guys - I'm diagnosing it, but #330 is higher priority to me ATM

**Comment by mfcovington** [comment] 2013-02-10 05:15
May or may not be a coincidence, but when sort broke for me:
1. I was adding a new reward (which was successfully added)
2. I noticed two new armor rewards (Buckler and Chain Coif) for the first time ever

**_Edit (11pm Pacific 2/9):**_ Sort is now almost working for me. I'm able to sort Habits, Dailies, and Rewards; however, sorting Todos results in seemingly random placement.

**Comment by lefnire** [comment] 2013-02-10 17:40
New armor is a recent feature add, a potential fix to dailies is in master#head now and will be pushed soon - I'll check back

**Comment by mfcovington** [comment] 2013-02-11 21:33
Sorting is currently back to normal for me.

**Comment by horusofoz** [comment] 2013-02-11 22:22
Still an issue for myself.
Chrome
WinXP/7

**Comment by kwilson328** [comment] 2013-02-12 10:07
Experiencing this issue on Chrome, OS X 10.7.5
Seems to be triggered when I try to drag just far enough that it would require a small amount of scrolling.
Minor sorts (like swapping two that are adjacent) works fine after a refresh

**Comment by ianjohnsa** [comment] 2013-02-13 21:59
I also am experiencing this issue on Chrome and Win 7. Shows the four-way arrow moving cursor indicator thingy but just selects text when I try to drag.

**Comment by wildcate** [comment] 2013-02-18 14:02
Same for me (Win7, Firefox).

**Comment by MiriamELewis** [comment] 2013-02-22 10:38
Still happening, its getting very frustrating now. Can't move anything at all, it just selects text. Also can't use the +/- buttons.

**Comment by wildcate** [comment] 2013-02-22 11:27
Same here - only selecting text (though the + - buttons work for me). The one time the re-ordering was possible everything was back to the old order after a refresh.

**Comment by Olathe** [comment] 2013-02-26 14:53
Some reports are also in issue #501. It seems to occur more (though not by much) repeatably if I hold down the mouse button and move even a pixel or two even if no text is selected. Refreshing sometimes helps but, again, not always.

**Comment by cmackley** [comment] 2013-03-01 15:14
I can't reorder tasks at all anymore.  I would see this problem now and then but I'd refresh and it'd go away.  In Chrome, it stopped working altogether so I moved to running Habit in firefox.  Now firefox isn't working.  This is definitely going to push me away from the product as reordering is key to organizing my todos. 

The only workaround I can find is that there's a brief (1-2 second) period where I can drag and drop.  If I hit refresh, let the page mostly\* load, DnD works but as soon as one of the last server request comes back it stops working.  I tried getting more specific details on which server request it is but the calls are too similar and not very descriptive.

On Win7 w/ Chrome, Firefox, IE9
and Win8 w/ IE10

EDIT: 
I just bought a shield (lvl 2 shield, buckler I think) and reorder started working (win7, firefox).  I opened it in a new tab and it still doesn't work there.  So I won't be refreshing my browser anytime soon. :)

**Comment by kwilson328** [comment] 2013-03-02 21:19
I've tried the best I can to break it, but this issue seems completely resolved for me. Can anyone else confirm? I've yet to get the "text selection" error, and every refresh I do saves my re-ordering. This is great!

OS X 10.7
Chrome 25.0.1364.99

**Comment by cmackley** [comment] 2013-03-02 23:56
I have a consistent repro!

I'm still **unable** to sort with my lvl 4 character.  Yet if I log out and use the default, playground character that you get by hitting Start on the splash screen, I **can** sort there.  However, as soon as I add a task with (, ), $, or : I can no longer sort.

Here's the repro:
1. Sign out if you're already signed in.
2. Navigate to https://habitrpg.com/splash.html
3. Try to drag tasks around. Note they do drag and drop.
4. Add a new Todo: "characters like $ ( ) : will me!"
5. Try to drag the task to reorder.
   Expected:
   Drag and drop still works.
   Actual:
   Text is selected.

Sounds like there's an issue parsing or scrubbing the user inputs. I'd even guess that it's on the server side as I don't see any errors in the browser's debug console, but JS doesn't always throw errors :).

**Comment by kwilson328** [comment] 2013-03-03 00:03
Now, several hours later, the issue is back in full force. Guess I jumped the gun in celebrating.

**Comment by Pandoro** [comment] 2013-03-03 00:11
@kwilson328 can you confirm or refute that you have any special characters like $ or ( or ) in your tasks?

**Comment by kwilson328** [comment] 2013-03-03 00:21
In a few random todos I have the following  % , ' ? + -
I have a couple habits with ! and /

**Comment by lefnire** [comment] 2013-03-03 00:26
yeah, i can't replicate with special characters either.

**Comment by wildcate** [comment] 2013-03-03 19:23
I cannot sort either; I have ( and ) and : and ! and "  in my tasks as well as ä, ö and ü. Sorting sort of never functioned properly for me; there was a day or two when I could move one thing for a bit and then it fell of the cursor and just sat somewhere.
I also cannot sort the rewards.

**Comment by lefnire** [comment] 2013-03-04 00:54
note to self, going to try to move all public/vendor js files back into `<Scripts:>` as page re-renders don't re-establish the `require()` statements from `loadJavascripts`

**Comment by lefnire** [comment] 2013-03-04 16:55
can y'all try logging into your same accounts on our [staging server](http://habitrpg.herokuapp.com/) and see if this problem exists there? (possible fix above). Remember this site gets wiped periodically, so don't get too cozy there.

**Comment by michalmau** [comment] 2013-03-04 17:12
It works OK on staging!

**Comment by Pandoro** [comment] 2013-03-04 17:30
Works for me as well. See #577 for different problems though :x

**Comment by lefnire** [comment] 2013-03-04 18:35
deployed, re-open if still an issue

**Closed as completed by lefnire** 2013-03-04 18:35 UTC
