### ISSUE TITLE
Navigation bar / Navbar broken on small screens/resized windows

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica#11016] opened 2019-02-22 15:00 UTC
I'm gathering various reports about this into one issue so they're not lost and we can see the breadth of the issue.

> @Remeday (d0a3217a-7b92-48d6-b39a-b1b1be96702e): "I'm having the nav bar bug too now, in a half-size browser window. (Same as I've used for months now; until today I've gotten the small screen nav bar where you open the menu to see gems and gold.) A visual is here: https://1drv.ms/u/s!Aho9LBF7ATTU-EezR9dUEnVZoJOk"

> My browser window (Chrome, half-screen, screen itself is about 20'') used to use the small-screen nav bar. As of yesterday it loads the weird form with the notifications on the wrong side.
> (Sorry for partly repeating myself; not sure if my report was seen and anyway it didn't include the browser and screen info.)

> citrusella, the serving wench   @citrusella (2d6ef231-50b4-4a22-90e7-45eb97147a2c) [web] tier 7: Legendary Socialite, Comrade, Scribe 
> @SabreCat @shanaqui I believe @LadySam's issue is caused by a screen size that would normally possibly load the "small screen" version of the site. At normal zoom, I can get it to happen in Firefox on my computer by making the window size about three quarters of the width of a 1280 width screen. o.o Something's making the header layout go a bit wacky instead of being in that hidden menu or whatever.

**Comment by shanaqui** [comment] 2019-02-22 15:03
I've also confirmed this issue on Windows 10/Chrome if I resize the window to about half the screen's width, at a resolution of 1920 x 1080 on a 24" monitor, if that helps at all.

**Comment by shanaqui** [comment] 2019-02-22 15:08
> Ceran   @Ceran (aabe567b-aa55-42c1-b612-b7699a7ba9b7) [web] tier 3: Elite Challenger, Socialite 
> Came to report probably the same thing as @LadySam. My header bar is all wonky if the browser window isn't maximized. Instead of collapsing into a menu icon, it all stays and tries to arrange into two line. Since the notification button moves to the very left, I can't see what the notifications are. Doesn't seem to be my computer. Using chrome and I think a 13" screen.

**Comment by Alys** [comment] 2019-02-23 12:13
@LadySam (96ff3029-60cb-4e9a-beaf-fcd95d518e81) gave us the information below as requested by SabreCat, but this bug can be replicated in any browser by dragging the browser window narrower until the navigation bar gets corrupted:

_"I'm using Google Chrome (but I have the same problem when I use Samsung Internet). I think my screen size is 5.38 inches by 2.75 inches. Thank you for your help!"_

**Comment by SabreCat** [comment] 2019-02-26 14:41
This appears to be caused by recent updates to the `bootstrap-vue` package. Unfortunately, rolling back causes the Challenge award dropdown to break again...

**Comment by SabreCat** [comment] 2019-02-26 16:10
Fixed in 53555a0f161a88

**Closed as completed by SabreCat** 2019-02-26 16:10 UTC
Labels: priority: important, help wanted, section: Navigation/Header
