### ISSUE TITLE
Bolding text inside a link on a task causes new tab to open with link + task to open for editing

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica#12178] opened 2020-05-07 12:34 UTC
Reported by JohnJSal:

> Either a bug or just weird behavior: I noticed when I make a clickable link in a task note and put it in bold at the top, it will open that link in a new tab, but when I return to the original tab, it also opens up that task for editing, as if I had just clicked on it normally. This was the task:
> 
> `[**New Year's Resolution**](https://habitica.com/groups/guild/6e6a8bd3-9f5f-4351-9188-9f11fcd80a99) Post in the Guild chat about how things are going, or respond to someone else's comment. Share any successes or difficulties and support your fellow Guild members! * *Note that completing this Daily is not a requirement to be eligible to win the Challenge*`
> 
> I added that first line.

I've tested this out in Firefox, and it turns out it only happens with that specific format; the bolding needs to be inside the link. This would be fine:

> `**[New Year's Resolution](https://habitica.com/groups/guild/6e6a8bd3-9f5f-4351-9188-9f11fcd80a99)**`

**Comment by fmaximus** [comment] 2020-05-07 18:12
The edit task ignores the click then the element clicked on is a link.
In the first case @shanaqui mentions, 
there will be a `<strong>` element inside the `<a>`,
thus not ignoring the click.

https://github.com/HabitRPG/habitica/blob/db0009ebad323bf51dbdeaf4a03c883c8a163442/website/client/src/components/tasks/task.vue#L976-L982

One option would be to move up the parent hierarchy up until the task-clickable-area to see if there's a `<a>`

**Comment by paglias** [comment] 2020-05-07 20:32
pinging @Tressley , I'm slightly worried that if we let the click open the link and not the edit modal we might risk people getting confused with tasks that only have links in their name / description since then the only way to edit them would be to use the 3 dots menu

**Comment by shanaqui** [comment] 2020-05-07 20:54
Hmm. You don't need to click on the text of a task to open the editing modal -- e.g. clicking anywhere in the yellow-highlighted bit works for me:

![image](https://user-images.githubusercontent.com/8144640/81343149-56027e00-90ac-11ea-8cc8-1cec6d108df2.png)

The current longstanding behaviour is not to open the modal. I have all my guilds all linked in a reward so I can easily jump to them, and it's never opened the task editing modal when I click on them. If we decide it should, that will be a change which might be quite unwelcome to folks who are used to the current behaviour.

**Comment by Tressley** [comment] 2020-05-11 13:58
@paglias -- Yeah, I understand where you're coming from, but I think @shanaqui makes a good point. Additionally, in this use case, I think the link style on a task title changes the expected behavior when a user clicks. Clicking a link, even if it's the title, is expected to open a link. If the task title is only a link, there will be a difference in clicking to edit, but that's expected when supporting additional click elements in a clickable region.

However, I do think it's a bug in that it opens both a link and the task modal. We should have it only open the link (preferably in a new tab.)

**Comment by paglias** [comment] 2020-05-11 14:38
Sounds good 👍 I'll mark it as help wanted then

**Comment by fmaximus** [comment] 2020-05-11 17:59
I'll tackle it

**Comment by Alys** [comment] 2020-05-12 00:06
@fmaximus Thanks! I've marked this as in progress.

**Closed as completed** 2020-05-19 14:55 UTC
Labels: priority: minor, status: issue: in progress, section: Task Page
