### ISSUE TITLE
Editing tasks not available on mobile version

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica#11002] opened 2019-02-18 15:37 UTC
Reported via email, confirmed in Chrome on Android. 

Tapping a task to edit it doesn't work on mobile version of the website, and the three dots dropdown won't open either.

**Comment by gautamz07** [comment] 2019-06-02 16:19
@shanaqui works fine in chrome android actually , can you provide more details ?

Tapping on the task , does open a edit dialog and the three dots are not visible ofcourse but if clicked on the dot area it shows up and then you can click the "edit" option.

**Comment by shanaqui** [comment] 2019-06-02 16:23
Further testing since the initial report has revealed it isn't a problem on all versions of Chrome, and may also be something to do with the device. I originally confirmed it on a Samsung S8 with the most recent version of Chrome that was available at the time if that helps. It didn't work in the Samsung browser either. 

It's possible this issue may need to be closed now if it's no longer replicable at all; I'll get some juice in that phone and get it updated to the latest version, and see what happens.

**Comment by shanaqui** [comment] 2019-06-05 22:05
This is still a problem on a Samsung S8, latest version of Chrome available. (Chrome 74.0.3729.157, Android 9; SM-G950F Build/PPR1.180610.011.)

Tapping on the task does not open an edit dialogue; tasks are not scoreable (also reported at https://github.com/HabitRPG/habitica/issues/11181); the three dots menu appears when you tap on the task, but is non-responsive. It seems like only the drag and drop function is working.

I wasn't able to get Samsung Internet updated due to the phone not charging properly (Samsung updates won't occur below 20% battery, even when plugged in), so I can't confirm if the behaviour is still the same on that.

**Comment by SabreCat** [comment] 2019-11-01 17:34
Looks like #11181 was a duplicate of this, but has the most documentation--closing this one!

**Closed as completed by SabreCat** 2019-11-01 17:34 UTC
Labels: help wanted
