### ISSUE TITLE
Challenge Tags not Reverting to Ordinary Tags after Challenge Ends

### ISSUE THREAD

**Issue by Altariel3** [HabitRPG/habitica#7569] opened 2016-06-01 03:25 UTC
General Info
- UUID: be317a32-c027-4032-bbd5-25ccb21eb912
- Browser: Google Chrome Version 50.0.2661.102 m
- OS: Windows 10, 64-bit
### Description

When a challenge I'm in ends, the challenge tag is still sorted into the Challenge tags section of the tags dropdown. It should be converted to an regular tag and sorted appropriately.

**Comment by crookedneighbor** [comment] 2016-06-01 03:36
Was it the case that challenge tags were converted to regular tags? That's not what I recall. 

If that's so, I never knew that. @Alys @lemoness ?

**Comment by Altariel3** [comment] 2016-06-01 03:50
That's always the way it was before, for me at least, and I also looked it up in the Wiki which says, "When a challenge is over, the megaphone icon disappears and the tag will look like a regular tag."

**Comment by crookedneighbor** [comment] 2016-06-01 03:50
Today I learned!

**Comment by Melissarie** [comment] 2016-06-13 09:01
I'm having this issue too, no clue how to remove them now that the challenge is done

**Comment by Alys** [comment] 2016-06-13 09:50
@Melissarie if you just want to remove the tags, it doesn't matter that their appearance hasn't changed. You can delete challenge tags at any time, just like deleting normal tags, even while you're an active participant of the challenge if you don't want to use the tag (deleting the tag doesn't affect your participation in the quest).

**Comment by habitrpguser** [comment] 2016-08-11 13:47
Just confirming that challenge tags actually did turn green after a challenge ended, and don't anymore now. (Several people asked in the [Guild Leaders & Challenge Creators](https://habitica.com/#/options/groups/guilds/0393624e-65f0-40c1-8e87-360955fcebca) why they don't anymore.) It was very practical, too (especially when cloning a challenge and deleting the old one - you knew which tag was that of the running challenge).

**Comment by habitrpguser** [comment] 2016-09-03 00:37
Some more odd behavior of challenge tags which, I think, is probably related to the bug of tags not turning green when a challenge ends or when the person leaves the challenge:

I joined a challenge, left it (opting to keep the tasks), then joined again. I had only one tag now, and it tagged both sets of challenge tasks (one without megaphone, one with megaphone). I edited that tag so it had a different text. It still tagged both task sets. Then I left the challenge again (opting to keep the tasks) and joined it a third time. I still had only one tag, which had its original text again now, and referenced all three sets of challenge tasks (two without megaphone, one with).

This isn't intended behavior, is it? (Especially since challenge participants are supposed to edit challenge tags if they like to, and are supposed to tag own related tasks with it, too, if they like to.) I know tag behavior was different before API 3 - you got a new tag each time you rejoined a challenge.

I think this may be related to the described bug of challenge tasks not turning green because that bug may also make the code treat the tags from joining several times as one tag. (You could say not even the code can tell the difference anymore.)

Oh, and I should add that all this happened on the website and that I've never used any of the apps.

Also, I did a bunch of reloading and deleting browser data, too, while testing this, and I always waited for sync to run properly, so that wasn't the cause either.

**Comment by habitrpguser** [comment] 2016-09-06 05:10
Could the priority of this bug please be raised to "medium" (at least)? In combination with [the bug that throws Habiticans out of challenges without any form of notification, even if they haven't left any guild](https://github.com/HabitRPG/habitrpg/issues/7764), this bug means that the only way to be sure that you're still in a challenge is to check the tasks of every challenge for megaphones every day. :( It can really be very frustrating to do the challenge tasks every day for a month, only to be told in the end that you weren't even participating in the challenge. Having the challenge tags turn green when you leave a challenge or the challenge ends (like they used to) would make it immediately visible which challenges you're in or out of, and would prevent this.

**Comment by librarianmage** [comment] 2017-10-20 03:10
Is this still desired?

**Comment by Alys** [comment] 2017-10-20 08:05
We definitely still want this. There's valuable use cases for keeping tasks
from challenges so you need the tag for organisation.

**Comment by lemoness** [comment] 2017-10-20 21:46
I've updated the labels on this issue!

**Comment by shanaqui** [comment] 2018-06-01 11:31
Just posted in Report a Bug by Il Mago:

> this issue: Challenge Tags not Reverting to Ordinary Tags after Challenge Ends #7569 has been closed, but challenge tags don't revert to regular tags in any situation: not when the challenge is closed or deleted nor when the user leave the challenge. (I am thinking that the fix didn't work because last few posts say it was a wanted change, but if this was dismissed than ignore me)

Any thoughts?

**Comment by Tressley** [comment] 2020-06-05 16:40
Closing this issue to move relevant information to a new issue #12276.

**Closed as completed by Tressley** 2020-06-05 16:40 UTC
Labels: section: Challenges
