### ISSUE TITLE
enchanted armoire

### ISSUE THREAD

**Issue by nightstitched** [HabitRPG/habitica#5624] opened 2015-07-15 12:47 UTC
For my character their showed only four piece of equipment in the enchanted armoire. But when I looked back at the equipment I got I had  two independent items and equipment piece two and three of the rancher set, but the armoire still says that there is no more equipment left!

Is this a bug or have they just not released all of the equipment yet?

My id is 8f711a4a-b928-4428-9de4-0c3325d84ed3

Thank you!

**Comment by crookedneighbor** [comment] 2015-07-15 12:56
Pinging @SabreCat

**Comment by Alys** [comment] 2015-07-15 12:56
I've checked your account and it shows that you own all of the Armoire items released so far. If you aren't seeing them all on your Equipment page, please reload it. This is what you will see: http://i.gyazo.com/cbe56f142e4190786da27b31dd78ffa2.png

**Comment by Alys** [comment] 2015-07-15 12:57
@nightstitched I've closed this but you're welcome to ask again here if you still have questions. We'll see your posts even though it's closed.

**Comment by JenniferNeff** [comment] 2015-07-23 08:17
I'm actually seeing a similar effect. I know for a fact that I've only collected four equipment items from the Armoire, and after refreshing my browser, I do see them, and only those:
![armoire gear](https://cloud.githubusercontent.com/assets/8341199/8845802/c318b2ba-30d6-11e5-95ae-cde66e105555.png)

Shortly after I got the last of those (the Rancher Robes) I briefly saw the message that the Armoire would have more items next month (but it was only on screen a moment and I didn't get the chance to click to dismiss it), and now see this in my Rewards list:

![armoire closed](https://cloud.githubusercontent.com/assets/8341199/8845842/22914eaa-30d7-11e5-80eb-d86050d7c807.png)

...but shouldn't there be 10 more things in there until August? Up until this happened, it was counting down from 14.

User ID: c5183dfa-c741-43ce-935e-c6d89b41a030
Using Chrome on Windows 7

**Comment by Alys** [comment] 2015-07-23 08:32
I've confirmed that @JenniferNeff has only these four Armoire items:

```
                "head_armoire_rancherHat" : true,
                "armor_armoire_lunarArmor" : true,
                "weapon_armoire_rancherLasso" : true,
                "armor_armoire_rancherRobes" : true
```

The content.coffee script still specifies 14 Armoire items, so yes, there should be 10 more things.

@JenniferNeff Note that when an item is put in the Armoire, it's there permanently (until you buy it), so even if we don't get this sorted out until August (unlikely!), you'll still be able to get all the items. Armoire items don't expire.

I'm investigating, although not for long because it's approaching my bedtime, but someone else will take this up if I don't resolve it.

**Comment by Alys** [comment] 2015-07-23 08:46
My initial suspicion is that `flags.armoireEmpty` is being set to true too early. I'm about to do tests on my account for that. 

I've set JenniferNeff's armoireEmpty flag to false, which will probably let her get at least one more item.

@JenniferNeff could you please reload HabitRPG and see if the Armoire now has 10 items in it?

**Comment by JenniferNeff** [comment] 2015-07-23 08:49
Thanks! I actually clicked the Armoire again, for science, before I saw your message, and it gave me the Soothing Lunar Crown. So it says 9 items, but that's correct.

**Comment by Alys** [comment] 2015-07-23 09:01
Thanks @JenniferNeff! You'll probably find that if you reload the site, it will go back to appearing empty, but it's likely that we'll fix this properly in a day or two.

On my own account, I deleted all but three armoire items (`$unset` rather than `$set` to `false`) and I set `flags.armoireEmpty` to `false`. I was then able to buy Armoire items as expected. After I bought five with no problems (leaving six in the Armoire), I reloaded the site. As the reload finished, I saw the modal saying that I'd obtained all Armoire items, and then the Armoire told me that it was empty. In my account, `flags.armoireEmpty` had been set to true by something that happened during the reload.

**Comment by Alys** [comment] 2015-07-23 09:13
Sorry, more testing shows that's a bit wrong. 

If you have items left in the Armoire and flags.armoireEmpty is false, you can buy an item from the Armoire. As soon as you do, flags.armoireEmpty becomes set to true, even when you don't have all the items. However you can still keep buying items until you reload the page, because the flag doesn't affect the behaviour of the Armoire until the reload happens.

It has to be this line that's failing because it's the only place that the flag is set to true:
https://github.com/HabitRPG/habitrpg/blob/7b9102c88ced9a935119dbc4b85251e19341d56a/common/script/index.coffee#L883
so there's something wrong related to api.count.remainingGearInSet.

I'm rolling back the last deployment to production which should fix this temporarily.

**Comment by Alys** [comment] 2015-07-23 09:34
Rollback completed. This bug won't hit any players who haven't already been hit by it.

However, for those that have, they'll keep on seeing that the Armoire is empty when it's not, until flags.armoireEmpty is set to false for them (something a database admin can do easily once we have their UUIDs).

So to fix this for all affected players, we're going to have to run a migration over all users to find and fix the ones that don't have all the armoire gear. Or just wait until next month when the flag will be reset when new gear is released... I don't like that option though. I'll probably work on a migration script this weekend, if no one else does it first.

**Comment by crookedneighbor** [comment] 2015-07-23 13:45
Redeploying the refactor code, but am using the old version of the armoire count code (should never have sent that out as part of a refactor deploy anyway).

@JenniferNeff please respond if you encounter the bug again.

**Comment by SabreCat** [comment] 2015-07-23 14:17
Note to anyone else who ran into this: some of what @Alys mentioned above implies that you won't be able to get more Armoire equipment, but thankfully that's not the case. The Armoire will look empty, but if you go ahead and use the Armoire again, you can still find equipment.

**Comment by Alys** [comment] 2015-07-26 11:18
fixed in https://github.com/HabitRPG/habitrpg/commit/bfd56b35e170669e97b3df6ce4712648296f5194

**Closed as completed by Alys** 2015-07-26 11:18 UTC
