### ISSUE TITLE
Habit Graphs not registering activity

### ISSUE THREAD

**Issue by dmccormick** [HabitRPG/habitica#3903] opened 2014-08-21 21:40 UTC
When I click the plus icon after doing a habit, some of the habits do not update on the graph for the current day. Instead it will add to the previous day and it increases. Not all of the habits do that but the ones that do are inaccurate now because I have clicked them more than once if I didn't see the current date updated. My userID is dmccormick and I am using Google Chrome.

The following is what JavaScript shows after I click plus for a Habit that isn't updating accurately:
GET https://habitrpg.com/audio/off/Plus_Habit.ogg 404 (Not Found) app-b4824a60.js:23
GET https://habitrpg.com/audio/off/Plus_Habit.mp3 404 (Not Found) /audio/off/Plus_Habit.mp3:1
GET https://habitrpg.com/audio/off/Item_Drop.ogg 404 (Not Found) 
##

**Comment by lefnire** [comment] 2014-08-21 21:53
confirmed on the missing audio files, cc @Fandekasp @DanielTheBard

**Comment by AdrienLemaire** [comment] 2014-08-21 21:57
@lefnire it's trying to use the "**off**" music theme ^^' I suggest you remove the sound off option from the theme select.

**Comment by lefnire** [comment] 2014-08-21 22:01
Ahh! We'll want to keep the "off" selection - I'll just need to go through and see where it was previously looking for `ng-if="user.preferences.sound"` (or some-such) and switch to `ng-if="user.preferences.sound!='off'"`

**Comment by librarianmage** [comment] 2016-04-15 16:42
@Alys is this fixed?

**Comment by Alys** [comment] 2016-04-16 03:54
I suspect not (at least the Habit click thing probably isn't; the unrelated 404s were fixed). Habit history has always been a bit obscure. The code will probably change for API v3 so we can look into this after that's live.

**Comment by Alys** [comment] 2016-06-25 10:52
I'm closing this because Habit history works differently now (multiple clicks are recorded for each recent day).

**Closed as completed by Alys** 2016-06-25 10:52 UTC
Labels: status: issue: on hold
