### ISSUE TITLE
Newly subscribed accounts receive erroneous notification that they have Mystery Items

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica#10496] opened 2018-07-03 09:39 UTC
If an account is newly subscribed, in at least some cases a notification appears that they have Mystery Items available, even though they do not. 

This one is verified by me. In this specific case the account (which did not have a subscription) was invited to a group plan (thus receiving a 'free' subscription).

**Comment by SabreCat** [comment] 2018-07-10 17:55
From bug guild:

> **Il Mago** (c073342f-4a65-4a13-9ffd-9e7fa5410d6b) tier 7 Legendary Socialite
> this issue happened to me too, so I think it's not only when a non subscriber start being subscribed but also when a gifted subscription period ends and a new one start, maybe this information can help narrow down the cause of the issue

**Comment by Alys** [comment] 2018-07-10 22:17
Technical details: When a player is added to a group plan (i.e., given a free subscription), the bug is that this is added to their `notifications` array:
```
        {
            "type": "NEW_MYSTERY_ITEMS",
            "data": {
                "items": []
            },
            "seen": false,
            "id": "c1f55931-faff-428b-acad-bbc3f5dd01fe"
        }
```

That should only happen if there are Mystery Items waiting for them to collect.

I assume the same thing happens if they get a subscription in another way but I haven't bothered to check.

**Comment by Alys** [comment] 2018-07-10 22:26
https://github.com/HabitRPG/habitica/blob/75e5b20f93a68cc043abd63471a09ab34ce74052/website/server/libs/payments/subscriptions.js#L141

https://github.com/HabitRPG/habitica/blob/75e5b20f93a68cc043abd63471a09ab34ce74052/website/server/libs/payments/subscriptions.js#L24-L41

That function should probably add the notification only if `pushedItems` isn't empty.

**Comment by thomasward1212** [comment] 2018-07-19 09:41
Hi :wave: 

First time here!

Can I pick this one up??

Tom

**Comment by Alys** [comment] 2018-07-19 09:50
That would be great, thanks! Post here if you have questions. :)

**Comment by legitmaxwu** [comment] 2018-08-20 04:30
Hello, I am new to this project!

I was wondering if I could work on this too, or should I search for a project that no one is working on?

Thanks,
Max

**Comment by Alys** [comment] 2018-08-20 11:40
@thomasward1212 How are you going with this? Are you still working on it? If real life has got in the way and you're no longer free to work on it, just let us know. :)

**Comment by Alys** [comment] 2018-08-21 21:44
@legitmaxwu I've marked this as help wanted again but if you're still interested in taking it now, comment here again briefly and I'll mark it as in progress for you.

**Comment by flhat** [comment] 2018-08-22 03:54
@alys - I'll take a stab at it

**Comment by Alys** [comment] 2018-08-22 04:14
@BlkStormy Awesome, thanks! :)

**Comment by flhat** [comment] 2018-08-30 20:33
@alys Are there steps to reproduce the issue?  It seemed like the update was straight forward, but I need a way to verify it.

**Comment by Alys** [comment] 2018-08-30 23:49
@BlkStormy If you have yourself set up to be able to use a test Stripe or Amazon or PayPal account from your local install, you can "buy" a subscription for a test user, however getting that set up isn't trivial. Probably the faster way is to create a private guild, add a group plan to it (there's a database update command for that in the Using your Local Install... wiki page), and then invite a test user to the account (thereby giving them a free subscription).

**Comment by flhat** [comment] 2018-08-31 02:04
@Alys Thanks - I have a test stripe account I can use.  I'll see if I can reproduce that way.

**Comment by derekdkim** [comment] 2018-10-01 16:43
If it already isn't being worked on, can I give this a shot?

**Comment by SabreCat** [comment] 2018-10-12 17:47
@derekdkim Looks like it-- we haven't heard from @BlkStormy in a while! Go ahead and see what you can come up with.

**Comment by derekdkim** [comment] 2018-10-13 02:56
I'm a little ashamed to say that I'm currently troubleshooting the local installation process. I'll be back as soon as I can get it running and find a solution & the appropriate unit tests.

**Comment by SabreCat** [comment] 2018-10-13 18:04
@derekdkim: Local installs for Habitica can be finicky, no shame in that! The Aspiring Blacksmiths Guild is a good resource for help on such things.

**Closed as completed** 2018-10-23 11:47 UTC
Labels: priority: medium, good first issue, status: issue: in progress
