### ISSUE TITLE
Design problem  (z-index, three-dots menu on tasks)

### ISSUE THREAD

**Issue by twim32** [HabitRPG/habitica#11524] opened 2019-11-10 10:59 UTC
Opened reward menu is under inventory items.

**Comment by Alys** [comment] 2019-11-10 21:50
@twim32 Can you please give us a bit more information? For example, the exact name of the menu item that you're referring to and where it should be? If you can take a screenshot, that would help.

Can you also tell us if this happens on the website or iOS app or Android app (or any combination of them)?

By the way, the best place to report bugs is the [Report a Bug](https://habitica.com/groups/guild/a29da26b-37de-4a71-b0c6-48e72a900dac) guild, which you can reach from the Help menu on the website or the Guilds menu item on the mobile app (you'll find it in the "Public Guilds" section - search for the word "bug" and it will appear straight away). That's especially good because we can sort out the full details of the bug before it goes into GitHub (and often a new issue isn't needed, if it's something that can be fixed quickly or if an issue already exists). If a bug occurs only on the mobile app, you can report it through the app's menu at About > Report a Bug, which sends debugging information to the mobile team.

**Comment by twim32** [comment] 2019-11-11 09:26
Yes, of course!
It's happens on website. Here is screenshot:
![as](https://user-images.githubusercontent.com/25387613/68576088-0564ec00-04a0-11ea-8e14-48e485ad009f.png)

When i focus the sub menu of redward item, it goes under shop items. And when i focus out it's ok.

**Comment by paglias** [comment] 2019-11-11 10:09
Thanks for the report but looks like it's a duplicate of https://github.com/HabitRPG/habitica/issues/11457

**Closed as completed** 2019-11-11 10:21 UTC
Labels: status: needs reply
