### ISSUE TITLE
[API v3] Can't start quests (party of one)

### ISSUE THREAD

**Issue by Kryzowsky** [HabitRPG/habitica#7232] opened 2016-05-14 11:17 UTC
General Info
- UUID: 432192fb-66ed-413c-88f6-b1ece628d943
- Browser: Google Chrome 50.0.2661.102 m
- OS: Windows 7
### Description

I've left my party, created a new by myself, but I can't start quests. Even though I am in a party. I am not sure though if I could start a quest or not if I remained in my party, as a quest invitation there was already on its way.

**Comment by paglias** [comment] 2016-05-15 19:28
This should be fixed with https://github.com/HabitRPG/habitrpg/commit/52bedc3563f90b089ce5fdb9aad0fe1bb89daf08 that has just been deployed. Reopen if the error persists after reloading the site.

**Comment by cTheDragons** [comment] 2016-05-15 21:04
Not sure if it is a bug or due to the copy over, however the quest won't start in my party. The following items took place:

+ System copied over with all but one member accepted the quest

+ One member left the party

+ I invited the party member back

+ Kicked the other party member who not accepted out

+ Other party member I invited came back and accepted the quest.

So is it a bug or just one of those circumstance things?

**Comment by cTheDragons** [comment] 2016-05-15 21:44
Not sure if it is a bug or due to the copy over, however the quest won't start in my party. The following items took place:

System copied over with all but one member accepted the quest

One member left the party

I invited the party member back

Kicked the other party member who not accepted out

Other party member I invited came back and accepted the quest.

So is it a bug or just one of those circumstance things?

**Comment by paglias** [comment] 2016-05-16 16:23
I think I closed the wrong issue, this could still be valid.

@cTheDragons in your case it could be caused by the migration

**Comment by paglias** [comment] 2016-05-16 20:03
@Kryzowsky I'm not able to replicate this one, quests start correctly for me

**Comment by paglias** [comment] 2016-05-18 09:59
This should be fixed and will go live in a few hours

**Closed as completed by paglias** 2016-05-18 09:59 UTC
