### ISSUE TITLE
regex queries on registeration too expensive (was: Registration issues/Unable to access website (503 errors))

### ISSUE THREAD

**Issue by kimboslice44** [HabitRPG/habitica#4737] opened 2015-02-23 21:46 UTC
## Edit from Repo Admin: There is no need to add new comments to this issue. If you would like to receive email updates about the progress of the issue, please press the subscribe button on the right.
# What to do if you died due to this outage:

On the [habitrpg.com](https://habitrpg.com) website, go to [Settings -> Site](https://habitrpg.com/#/options/settings/settings) and click on the **Fix Character Values** button. You can then increase your level by 1, increase your Experience and Gold to approximately what they used to be, and also add some extra Gold to buy back the equipment piece that you lost.

If your Dailies have lost streaks, you can edit each Daily and reset the streak in the Advanced Options. If you are not sure what the streaks were, you can go to Data -> Data Display Tool and use the "Dailies History" section to estimate them. Ask in the Newbies guild if you need help with that (Help -> Ask a Question)! 

---

I can't register for this site. I can click on play, and then register and fill in all the boxes, but when I hit submit, it waits for a while and then gives me the 503 error. This also happens when I try to register with Facebook, and on both Chrome and Firefox.

**Comment by crookedneighbor** [comment] 2015-02-23 21:55
@kimboslice44 Thanks for reporting it. We got a recent influx of traffic from imgur, we're trying to track down what the issue that is preventing the site from loading is. We'll report back here when everything is back to normal.

**Comment by LlamaHobbit** [comment] 2015-02-23 22:25
Same issue except I don't need to register. I've had an account I use daily for months, but as of about 3/3:30pm CST it gives me the 503 error when I try logging in on both the main site and on the backup herokuapp site.

**Comment by simkimsia** [comment] 2015-02-23 23:59
Same situation with me on Android and main website

**Comment by Jadziyah** [comment] 2015-02-24 00:05
Same here. Cannot access anything on the website, via browswer or app. We're not trying to register - we are current users. Simply, the site won't load from any platform. Glad it's being looked into

**Comment by kimboslice44** [comment] 2015-02-24 00:06
So I had an interesting development. I received the "Welcome to Habitica" email, even though I never actually successfully registered (that I know of).

**Comment by lapost48** [comment] 2015-02-24 00:35
I was having the same issue earlier but now when I click on the play button the page flashes and the loading bar at the top starts to fill but I never got a register dialog.

**Comment by Dranian** [comment] 2015-02-24 01:15
I'm still experiencing the [503 error](https://www.dropbox.com/s/aq9q40m9oskgoje/Screenshot%202015-02-23%2020.10.34.png?dl=0) as of 20/20:30 EST.

**Comment by bobdownsinfo** [comment] 2015-02-24 01:39
Same issue happening for me while trying to Register on the website using my Win7 Laptop with Chrome. Tried registering with Facebook and by filling in the fields manually.

**Comment by lemoness** [comment] 2015-02-24 01:52
Unfortunately, we're still having a lot of trouble with the site :( It's
probably best not to register today, but to try again tomorrow. We're very
sorry!

**Comment by bobdownsinfo** [comment] 2015-02-24 01:58
No worries. Just wanted to add my two cents to help make sure you know
where it's coming from... if you didn't already. I've subscribed to this
thread, so if you post when it's fixed, I'll see that and register then.
Thanks! And, good luck!

**Comment by ghost** [comment] 2015-02-24 03:50
Unable to access as of 22:50 cst

**Comment by PWoF** [comment] 2015-02-24 03:50
I don't know if this helps or not.  I didn't really experience the 503 error until between 7 and 8 pm Central Time.

**Comment by bobdownsinfo** [comment] 2015-02-24 04:12
Well, something changed at least. At 8:40 PM MST, I received an email from
HabitRPG with a Subject of "Welcome to Habitica!" This suggested to me that
at least one of my earlier Registration attempts succeeded. So, I clicked
on its link and tried clicking on the "Use Facebook to Login" button. It
thought about it for a while, but then gave me a new error message rather
than logging me in:

Application Error

An error occurred in the application and your page could not be served.
Please try again in a few moments.

If you are the application owner, check your logs for details.

This is fine and I imagine it's still being worked on. In case it might
help, I thought I'd share this update here. Good night!

**Comment by crookedneighbor** [comment] 2015-02-24 04:22
Hey y'all, thanks for the updates. We're still sorting out why the site isn't working. There's no need to add additional comments at this time. We'll post here and on Twitter as soon as the site is back up and working normally again. 

If you've commented already, you should be automatically subscribed to the issue. If you're new, press the subscribe button to the right. As soon as we have new info, we'll update this ticket.

**Comment by crookedneighbor** [comment] 2015-02-24 04:39
~~At this point we think it's something to do with how the Node app is interacting with Heroku. If there are any Heroku Doctors in the house, please come forward. For reference, here's the repo for the [Heroku buildpack for Node](https://github.com/heroku/heroku-buildpack-nodejs).~~

edit: see next comment

**Comment by crookedneighbor** [comment] 2015-02-24 05:45
# UPDATE

We don't think it's node vs heroku anymore.

On a hunch, we spun up a new database for beta.habitrpg.com, and the application errors ceased. This confirmed that the issue was with our database connection. If you tried logging into beta recently and it told you your account could not be found, that is why.

We're sorting out the rogue processes in the database, stand by!

**Comment by lemoness** [comment] 2015-02-24 06:58
QUICK UPDATES FROM TYLER:

So a summary of what i'm doing, and i'll do a post-mortem on the ticket when all's stable.

1. regex queries are evidently insanely expensive, even on indexes.

Been going back and forth with Dave from mongolab, he's pushing us to m3 (from m2) to double our CPU (regex pegs CPU most), and I'm doing what I can to REDUCE the regex usage (eg, https://github.com/HabitRPG/habitrpg/commit/02901e52fda93f9529cb1f5469a8994eab76ddb7) but we can't REMOVE it due to our case sensitive crap.

What happened was we got slammed by new users. Everyone REGISTERING at once was the ticket, not USING the site, registering.

2. 4-5 queries weren't indexed, mostly email stuff. Shooting those queries off were congesting our dynos, and causing them to hang. Just had to build those queries (done), and Dave is doing the rest on the db side.

All's underway and being fixed. The final piece is really figuring out a way to handle this regex bit properly. I fear we might not be able to get a bandaid in fast, it might require a more long-term solution to the whole case-sensitive, duplicate-emails, etc stuff.

**Comment by NovemberEcho** [comment] 2015-02-24 07:20
Site seems to working great now other than the fact that I died due to the connection problems. Can that be undone?

**Comment by lemoness** [comment] 2015-02-24 07:26
It can! Go to Settings > Site > Fix Character Values and restore your stats
:) Sorry about that!

**Comment by NovemberEcho** [comment] 2015-02-24 07:33
no problem, thanks for the quick response

On Tue, Feb 24, 2015 at 12:26 AM, lemoness <notifications@github.com> wrote:

> It can! Go to Settings > Site > Fix Character Values and restore your stats
> :) Sorry about that!
>
> On Mon, Feb 23, 2015 at 11:21 PM, NovemberEcho <notifications@github.com>
> wrote:
>
> > Site seems to working great now other than the fact that I died due to
> the
> > connection problems. Can that be undone?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/HabitRPG/habitrpg/issues/4737#issuecomment-75710448
> >.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/HabitRPG/habitrpg/issues/4737#issuecomment-75710887>.
>



-- 

-Nicholas Elliott

**Comment by lefnire** [comment] 2015-02-24 07:55
Post Mortem (@lemoness I'ma splice your comment here and expand). 

### 1. MongoDB `$regex` queries are _very_ expensive

Even on indexed fields. They _use_ indexes, and you can improve perf with a [prefix expression](http://docs.mongodb.org/manual/reference/operator/query/regex/#index-use) - but they still peg CPU much more than a standard query. The culprit was [here](https://github.com/HabitRPG/habitrpg/blob/16c4c420bb6f03bfd1a85a643f429058a02ff16f/website/src/controllers/auth.js#L78tL86) - that's registration code, meaning we were brought down because everyone was _registering_, rather than simply _using_ the site. I'm working on ways to reduce `$regex` use (eg, https://github.com/HabitRPG/habitrpg/commit/02901e52fda93f9529cb1f5469a8994eab76ddb7) but there's no quick-fix*. In order to get by for now, MongoLab has upgraded us from an M2 to M3 cluster, which doubles our CPU.

(TL;DR on the "no `$regex` quickfix")
The reason we're using regex in the first place is that our auth code is custom - I built it before there was a proper [passport local auth](http://passportjs.org/guide/basic-digest/) system available. One _very poor_ original oversight: unames & emails weren't case-sensitive. Because of that, we indeed have a non-trivial amount of duplicates in either username or email addresses. Were that not the case, we could run a migration against all usernames/passwords to downcase them, and use a standard `{'auth.local.username':username}` query going forward. (Or alternatively, to maintain caps use a "shadow" version like `{uname:"Lefnire", downcase:"lefnire"}`) - but [we don't have that luxury](https://github.com/HabitRPG/habitrpg/issues/3986)

### 2. Index those queries

About 4 or 5 of our frequent mongo queries weren't indexed at all, mostly email stuff. A situation like this causes Dynos to wait for the query to resolve, blocking that Dyno from further traffic. We only get 4-13 Dynos at a time (they scale up and down with traffic), so blocking all 13 puts us on our knees. From Heroku:

> Our router will drop a long-running request after 30 seconds, but the dyno behind it will continue processing the request until completion. Our router is unaware of it, though, so it'll dispatch new requests to that busy dyno. This effect tends to compound, and you'll eventually see H12 errors even for unrelated URLs, such as static assets. H13 errors are similar in what causes them, but are primarily related to concurrent web servers.
> 
> You'll need to use a tool like New Relic to gain visibility into queueing in your app.
> 
> If your app is using ExpressJS, you will also want to install something like [timeout](https://github.com/expressjs/timeout), which will ensure that a long running request is dropped at the dyno-level as well. Specifically, timeout raise a Response timeout exception when that happens.
> 
> With that in place, the compound effect is less likely to occur, but long-running actions still need to be addressed. Again, New Relic is a great tool to provide the visibility into your app to identify the long-running actions. You can then optimize them and make sure they're able to finish within a reasonable time, we suggest keeping all requests under 500ms. If they're performing any inherently long tasks, you should try to offload those to a background worker.

The fix was simple: add the indexes. For our devs, be sure to add db indexes for new queries. Or, you can see bottlenecks at mongolab.com > Slow Queries. Eg, here's an index that needs building:

![slow](http://i.gyazo.com/209a356596ed9738eab6d55eab30f633.png)

Simply click the "Build This Index" button and you're gold. Don't get trigger happy, here's an index that _doesn't_ need building because it's a manual query I ran mongo shell:

![dont bother](http://i.gyazo.com/c709deeeb4d37dad73f681e3090e7da5.png)

The difference is the "query count" field.

---

Anyway, we're back online. Note, we still have that one `$regex` so we're not in the clear yet, we're just _much_ smoother than before. I'll keep an eye on the system tomorrow.

**Comment by lefnire** [comment] 2015-02-24 07:59
Oh man... just look at those `$regex` queries' average times:

![time](http://i.gyazo.com/b6d493f04a7ad60574afdd3d70fe6c13.png)

We're gonna need to solve that ASAP

**Comment by StanLindsey** [comment] 2015-02-24 08:13
<3

**Comment by Ulugbeg** [comment] 2015-02-24 08:57
This might not be the right spot for it, for which I then apologize, but: one party member had her cron go of 3 times during this, killing me in the process (do you guys want screenshots or something for that? Our group-id is a7375dd2-8b1c-4f1b-8586-a10fb411bee6). While this is a pity, I can and will restore my stats. BUT I lost my limited edition 2014-2015 ice spike (for my character's left hand). I cannot rebuy that one. My userID is 3ae12e97-6fca-484e-9c92-a308e39afbb8

**Comment by Alys** [comment] 2015-02-24 09:06
@Ulugbeg Have you reloaded your tasks page? The lost equipment should be showing up there under Rewards.

**Comment by Ulugbeg** [comment] 2015-02-24 09:45
Yes, indeed, I apologize for cluttering up this bug, thank you!

**Comment by nivl4** [comment] 2015-10-27 14:41
it seems @paglias fixed this in fc9d0775ab5ec94d7079ee510c3ca1b3f8a84125 , e75d3547c50b4a21b0606ac9be5d5300190c6116, close this issue or more work needed?

**Comment by paglias** [comment] 2015-10-27 15:12
@nivl4 yes, it's fixed!

**Closed as completed by paglias** 2015-10-27 15:12 UTC
Labels: priority: important
