### ISSUE TITLE
Renewal of Dailes

### ISSUE THREAD

**Issue by Pacerparty** [HabitRPG/habitica#950] opened 2013-05-13 22:38 UTC
I have set my Custom Day Start at 5 am. But i have noticed that if i check some Dailies between 0:00 am and 4:59 am they don't get renewed after 5 am, but 24 hours after the first pass of the 5 am!

So some days, although i did my dailies, i can't check them cause they are already checked from the day before and they haven't renewed yet! and i think this will happen again today (it's almost 2 am here as i'm writing this).

Also, i think my dailies kick in at 00:00 am and not in 5 am as i have set them (I logged a few minutes ago and i lost 20 hp and i don't know why!), although i'm not really sure about this.
A log with all the daily info of the negative effects would be nice (date, time, action, effects etc).

Is anyone else facing the same problem?

Update:
Ok, i just logged in (1 am here) and my dailies haven't renewed! :(
That means that still if i make any actions between 00:00 am and 4:59 am there is a problem.
I logged in Thursday around 2 am and did all my actions. I've set my day to change at 5 am. Now i logged in (Friday 1 am ) and my dailies weren't renewed.

**Comment by katofrafters** [comment] 2013-05-14 08:47
I'm having similar issues.  I'm set to renew at midnight Japan-time, but I have come to find them spontaneously renewing in the middle of the day or in the afternoon, usually with some hp loss associated as many of my dailies are done at night.

**Comment by wizonesolutions** [comment] 2013-05-14 10:00
They get updated the first time you log in after the Day Start time, so if you log in in the middle of the day or the afternoon, that's when you'll see them update. I'm assuming though that you mean they shouldn't be updating then anyway.

**Comment by lefnire** [comment] 2013-05-14 17:03
this should be fixed now in https://github.com/lefnire/habitrpg/commit/92b178b4a41eb96e24449f1bef3e379e85590bae - should calculate day-diff properly, color-coding, etc. Please re-open if you experience any more

**Comment by Pacerparty** [comment] 2013-05-14 21:03
I logged in 5 minutes ago (23:53 pm) and my dailies weren't updated. :(

Anyway, i'll see how it goes the next 2 days and i'll report the progress.

**Comment by lefnire** [comment] 2013-05-19 13:48
> Update:
> Ok, i just logged in (1 am here) and my dailies haven't renewed!
> This is so demotivating. And i did so many things today. :(
> 
> That means that still if i make any actions between 00:00 am and 4:59 am there is a problem.
> I logged in Thursday around 2 am and did all my actions. I've set my day to change at 5 am. Now i logged in (Friday 1 am ) and my dailies weren't renewed. And the strange thing is i didn't lose any hp. As if game time has frozen.

**Comment by wc8** [comment] 2013-06-29 17:04
Duplicate of or related to #647 &/or #1057

**Comment by devarops** [comment] 2013-09-07 22:12
I'm experiencing the same problem. Dailies for today are grayed out (not "active").

**Comment by lefnire** [comment] 2013-09-07 22:25
yeah, dupe of #1057, let's follow up there

**Closed as completed by lefnire** 2013-09-07 22:25 UTC
