### ISSUE TITLE
Backstab description misleading

### ISSUE THREAD

**Issue by casicastiel** [HabitRPG/habitica#2829] opened 2014-02-12 17:38 UTC
"You deal higher damage to the task, with a higher chance of a critical hit."

This has been bugging me for a while, and a discussion in the Tavern this morning about the ridiculous rewards given from it prompted me to post it here. I'm not an RPG expert, but in the games I've played, a backstab skill is always one that is specifically meant to deal high damage and high crit chance. While it's described as such here, the actual effect of the skill is an XP/GP gain redundant to — and _significantly_ better than — the Pickpocket skill, and a tiny effect on the task's value. I've tried casting Backstab on yellow/orange tasks a few times, expecting it to help change their color a bit so I'd take less damage that day, before I looked up on the wiki and saw that I was wasting my mana.

For instance, I just cast Pickpocket and then Backstab on the same 113-day-streak task; Pickpocket netted me about 16 gold, and Backstab gave me well over a hundred XP and GP. The 5 extra mana cost is negligible; it's well worth waiting an extra bit for the mana to get a reward that's something on the order of seven to eight times greater.

I'm not familiar with the exact math behind how these skills work (the wiki descriptions don't make much sense to me), but it seems like there's something off between these two skills. If Backstab is to remain as is, I would suggest a different description; the current one says nothing about what the skill actually effectively does for the user, except for the good crit chance.

If it can be changed, I would propose a minimal XP/GP reward and a higher damage dealt, based on PER (not STR, like Brutal Smash, and not a fixed number, like the wiki says it is), and a higher crit chance, maybe 50%, to fall more in line with what I'm used to in other games and with what the current description suggests.

(If this is a discussion more suited for Trello, apologies; I couldn't find a relevant place to put it there.)

**Comment by deilann** [comment] 2014-02-14 13:57
I think part of the problem is that Pickpocket was nerfed, but Backstab not touched...

**Comment by casicastiel** [comment] 2014-02-14 18:09
Even if Backstab was similarly nerfed, though, it's still both redundant and superior to Pickpocket: even with the extra mana cost, it provides XP, GP, crit chance _and_ a small effect on task value, while Pickpocket only produces GP.

**Comment by deilann** [comment] 2014-02-14 18:10
Yeah, but Pickpocket used to give much more GP than Backstab did. But with
PP nerfed, it's clear that Backstab needs a good hard look in general.

**Comment by casicastiel** [comment] 2014-02-15 13:14
Can't stop thinking about this. Here's a proposal, based on 'You deal higher damage to the task, with a higher chance of a critical hit.' (I assume keeping it separate from what Brutal Smash does is preferable.)

Scrap the GP bonus altogether. There's Pickpocket for that. I'm tempted to say scrap the XP bonus, too, but I dunno.

Deal damage to the task based on PER, so that a super high PER stat gives +5 value or something like that. Crit chance should be higher, either fixed at something like 50% or also based on PER (damage calculated by STR). No boss damage, like BS or BoF, made up for by the larger value change.

**Comment by deilann** [comment] 2014-02-15 13:19
I like that.

**Comment by casicastiel** [comment] 2014-02-15 14:09
I'm sure this is wildly impractical, but in my dream world, there's also a tiny (maybe like 2%) chance for an instant kill - that is, neutralize the task to 0, assuming it has a negative value. :p

**Comment by deilann** [comment] 2014-02-15 15:04
I like that, too.

**Comment by sirsavary** [comment] 2014-03-05 05:11
Backstab is incredibly overpowered in my opinion. I've stopped using pickpocket entirely. It definitely needs to be nerfed. I think taking the GP bonus away from it is a good idea. Right now it's skewing all of my rewards because a backstab can grant them instantly but if I don't have the mana I have to rely on doing my dailies and tasks. My rewards end up being somewhere in the middle: too hard to get on the average day but really easy to get all at once.

**Comment by SabreCat** [comment] 2014-03-23 02:37
"Dealing damage to a task" is a nebulously defined thing. For Brutal Smash, it's threat reduction and boss damage. For Burst of Flames, it's Experience and boss damage (and threat reduction too maybe?). And for Backstab, apparently it's everything and a bag of kittens. o.O Oh, except boss damage, because then it'd be too powerful. xD

So what flavor of damage are people suggesting, here? And what would "neutralize the task to 0" mean: reset it to yellow? Or take it all the way down to minimum value (-27 or whatever the number is)?

**Comment by deilann** [comment] 2014-03-23 03:02
Backstab is everything... but boss damage. Still kittens, though.

**Comment by casicastiel** [comment] 2014-03-23 12:00
I've always interpreted damage to task = value change (as opposed to damage to boss, which is- related? unrelated? arbitrarily calculated by a monkey on a typewriter?). And I meant yellow by 0.

**Comment by SabreCat** [comment] 2014-03-23 13:11
OK, here's my thought...
- Spell description becomes "Kill it and take its stuff! Sneak in and stab a task from behind, weakening it and maybe snagging some loot while it reels."
- Threat reduction based on STR.
- Increased critical hit chance.
- Rolls a chance for an item drop according to the normal formula (PER, etc.).
- No Experience or Gold gain.

I'm considering giving it a bit of boss damage as well, then doing the same for the Healer's Searing Brightness. Thoughts?

**Comment by deilann** [comment] 2014-03-23 18:49
I'd give it more boss damage than Searing Brightness. Healers have more
value than rogues in boss battles already-- being that they can heal the
extra damage.

**Comment by Kristyjnh** [comment] 2014-08-04 01:19
I know I'm dredging up an older thread, but I would really like to see something for Rogues that could do increased boss damage. Right now I feel kind of useless fighting Vice with my mage party member. There's not a lot I can contribute. And on the other hand, we have backstab, a beefed up, Exp granting pickpocket. I would like to see backstab just be Exp and boss damage or something along those lines.

**Comment by kiramarch** [comment] 2014-08-16 22:01
How does a decision get made to go ahead with a change like this? I just unlocked Backstab, and agree that it's so powerful that it's unbalancing the game for me. 

I can compensate for the crazy amount of gold and experience by how I use it, but some of the other ideas here are good ones that individual players can't mimic on their own. Thanks!

**Comment by Alys** [comment] 2015-05-01 08:47
Fixed by https://github.com/HabitRPG/habitrpg/issues/3029 which is going live soon.

**Closed as completed by Alys** 2015-05-01 08:47 UTC
