### ISSUE TITLE
Attributes Calculating Wrong

### ISSUE THREAD

**Issue by hametsunosaturn** [HabitRPG/habitica#4898] opened 2015-03-21 14:35 UTC
This is a problem I've had off and on for months. I always assumed other people must be having the same problem and never reported it. But I can't find any other issues like mine. For some reason, my point values for each attribute aren't right. See here:

![attributes](https://cloud.githubusercontent.com/assets/4701023/6765403/1d0ce5c6-cfb5-11e4-94e5-02e076e41c00.PNG)

If you add up any of the points for Level/Equipment/Allocated, it's off by 29 from the total listed on the left (ex intelligence: 79+50+55 = 184. 184-155 = 29). This is true for everything, Strength, Intelligence, Constitution and Perception. It does this, sometimes for a few hours, sometimes for a few days. I always notice when it's happening because my total mana drops from 440 to 340 for the duration of the glitch. There doesn't seem to be any rhyme or reason for when it happens. It just does. I try to unequip my armor/weapons and then reequip it, but that never works. It's the same both on the web and on the mobile app, so it's nothing on my end that's doing it. 

It randomly fixes itself, as well, with no clear reasoning. It's not always at the start of a new day, sometimes it's in the middle of the day. Sometimes it's the next day or sometimes it's two or three days later. The way I deal with it is usually by using 100 MP, then returning the 100 to myself through the stats editor option, because the glitch is shorting me 100 points. But it'd be nice if it just didn't happen. Because I assume my spells and attacks are weaker during these times, too. 

Sorry if this is reported anywhere else or a known issue. I searched every way I could think of for this problem and couldn't find it.

**Comment by deilann** [comment] 2015-03-21 20:31
It's actually a display issue, not a glitch with your stats. Your stats are
correct. The issue is that your level/2 points cap at level 100.

I thought we'd fixed this display issue, though...

**Comment by hametsunosaturn** [comment] 2015-03-21 21:06
I don't think I know what that means, the level/2 point cap. Does it mean that every time I level up, my attribute points don't mean anything? 

And as far as the display issue, my mana is still at 340 and has been all day when just yesterday it was 440. So if that's a display issue, then I guess it isn't fixed?

**Comment by deilann** [comment] 2015-03-21 21:18
Your stats are meant to freeze at level 100. Your attribute points do mean
something, although soon that will be fixed, where you won't gain an
attribute point after level 100. But your stats (where it says level)
actually max out at 50, or level/2.

Also, what you're experiencing with your max mana is that you probably had
a Perfect Day bonus yesterday. That will increase your intelligence by 50
points, and so give you an extra 100 max MP. That is not a display issue.
When you lose a perfect day bonus, your max MP will go down by 100.

The display issue here, is that it says that your points from level are
higher than 50.

**Comment by hametsunosaturn** [comment] 2015-03-21 21:29
Ohhh, I see, I was reading / as "slash" not "divided by." It all makes sense now. Kinda. The extra 29 points are the difference between the 50 it's supposed to stop at and the 79 it actually displays. 

So, I'm at level 159 now, because I've been using Habit for a long time now. Now I'm curious, what's the point of leveling up if you only get to 100 and then everything after that doesn't add anything to your character? And should I assume that 340 (with the exception of a perfect day bonus +100 MP) is the total my mana will ever be? 

At this level in the game, I really want to keep playing and using Habit and supporting it (I'm a subscriber), but literally the only thing I can gain in-game is quest pets and mounts. I've got all the weapons (new weapons quests would rock, though), all 90 of the drop pets and their respective mounts, I've apparently passed the max level 59 levels ago. If attribute points to my stats are going away soon, what will be the point of playing? Just doing quests?

**Comment by deilann** [comment] 2015-03-21 21:37
Have you tried using the Orb of Rebirth?

Originally we had a level cap at 100. Some players wanted to keep leveling
because that on its own was motivating for them. We froze the stats to keep
the game from getting completely unbalanced and to keep from opening the
can of worms where folks wanted more and more content for even higher
levels.

The idea is that if you feel like you're in a point of stasis, you can use
the Orb of Rebirth and start over from level 1. You'll have all of  your
weapons to repurchase and can feel like your levels mean something again.
You can also release your pets and mounts with Key to the Kennels, so you
can start collecting pets again.

**Comment by hametsunosaturn** [comment] 2015-03-22 14:07
The problem with starting over is that there are only two people in my party, so quests take long enough as it is. I'm the warrior, so I do most of the damage to bosses right now. We've tried to recruit others to the game, but haven't been successful. If I start back at level 1, we would never keep up with all the pet quests. There's just no good answer. :/

**Comment by deilann** [comment] 2015-03-22 23:43
If quests are exciting for you, one thing you can do is adapt the way you
use Habit to deal more quest damage. I actually find that when I use the
Orb of Rebirth I initially do more quest damage because my tasks are no
longer blue. :) You could also find ways to better reward yourself with
mana, either by using To-Dos more (although soon, Habits will give you mana
as well) or allowing yourself to purchase mana using Fix Character Values.
Then, you can do more Brutal Smashes and deal more quest damage!

I'm sorry you're feeling a bit stuck in a rut, but I think there is a good
answer. It just may involve trying a few things that don't feel like a good
answer at first, if that makes sense?

**Comment by Alys** [comment] 2015-03-26 07:51
This should be fixed when https://github.com/HabitRPG/habitrpg/issues/4913 is deployed to production (should be in just a couple of days). If not, we can reopen this.

**Closed as completed by Alys** 2015-03-26 07:51 UTC
