### ISSUE TITLE
negative exp. after undoing completing task

### ISSUE THREAD

**Issue by dreaganluna** [HabitRPG/habitica#4217] opened 2014-11-03 10:13 UTC
I had a difficult task that I completed by accident (clicked the checkmark when site hanged during updating data). I headed over to the "completed" tab and checked the task again, since I still needed to finish it.
Now I'm in negative exp. Possibly due to the fact that I leveled.

**Comment by paglias** [comment] 2014-11-03 16:47
duplicate of #663

**Closed as completed by paglias** 2014-11-03 16:47 UTC
