### ISSUE TITLE
Blank, undeletable task on web breaking mobile app access

### ISSUE THREAD

**Issue by morisy** [HabitRPG/habitica#1473] opened 2013-09-08 00:51 UTC
I have a blank, undeletable task in my todo list:

![screen shot 2013-09-07 at 8 40 02 pm](https://f.cloud.github.com/assets/136939/1102444/5680571e-1820-11e3-883a-d85e9787ff3c.png)
Ran the Java console and got this:

``` javascript
Sync: Queue is empty app.js:14
Given URL is not allowed by the Application configuration.: One or more of the given URLs is not allowed by the App's settings.  It must match the Website URL or Canvas URL, or the domain must be a subdomain of one of the App's domains. 
```

My username is morisy (06983658-0cea-4d6d-99ec-2aea88d42947). It's breaking access on the mobile apps, but things appear to work fine on the website, except it can't be deleted, marked as completed, or otherwise edited. Was going to poke at it via the API, but my own server is down :-1:

**Comment by lefnire** [comment] 2013-09-08 00:55
dupe of #1436 . follow instructions at this link: https://github.com/lefnire/habitrpg/issues/1436#issuecomment-23899437 temp workaround till we can kill the old site and run a migration to tidy up people's old.habit corrupts

**Comment by lefnire** [comment] 2013-09-08 00:56
I'm sorry, #1436

**Closed as completed by lefnire** 2013-09-08 00:55 UTC
