### ISSUE TITLE
"Rest in Tavern" did not work

### ISSUE THREAD

**Issue by wildcate** [HabitRPG/habitica#936] opened 2013-05-13 06:23 UTC
I was away for a few days and had clicked "Rest in Tavern" before this, but when I reconnected after coming back, I died.

This non-functioning might, perhaps, be connected to (ahem) my curiousness  - after I clicked the "Rest" button, I clicked it again to see how I would be told about the minimum stay. There was no message or something in my case - the button just turned back to "Rest", so I clicked it a third time to go and rest.

Good thing the restoring possibility is still in there! :+1:

**Comment by kriscrat** [comment] 2013-05-27 16:58
Same issue here, but I only clicked it once.  I also didn't get a confirmation message or anything.

The grim reaper animation was ADORABLE though, and the loss was much better than resetting back to zero (motivating, not discouraging).  I've already used restore to get back to where I was, approximately, so no action needed on my account.

**Comment by lefnire** [comment] 2013-06-17 14:10
dupe of #997, let's follow up there. (this came first, but that one has more comments & info now)

**Closed as completed by lefnire** 2013-06-17 14:10 UTC
