### ISSUE TITLE
Animal skins shifting and disappearing when other skins equipped

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#11685] opened 2020-01-01 10:11 UTC
As @geolojess (da27bf23-48f7-469d-9a32-58521f9c84a9) reports expressively:

_"Now this is a wild one, when I equip a new skin on the website the animal skins (which are 'locked, I haven't bought any of them) move around and swap places with eachother. Sometimes one will even disappear and then come back when I equip another skin. I thought my brain was messing with me at first XD"_

When I set my account to have the same purchased items as geolojess, I see the same behaviour. Below are screenshots showing the changes I observed.

Below the screenshots are the `purchased` objects that I set into my account to be able to replicate this behaviour (although really probably the only thing you'd need to set would be the skins). Before I adjusted my `purchased` objects, I owned all possible avatar items and I wasn't noticing the buggy behaviour.

![Screenshot from 2020-01-01 20-01-25](https://user-images.githubusercontent.com/1495809/71640268-bd5d8b00-2cd2-11ea-8df8-00d63c50aa80.png)
![Screenshot from 2020-01-01 20-01-27](https://user-images.githubusercontent.com/1495809/71640269-bdf62180-2cd2-11ea-8b9b-12fbea252ada.png)
![Screenshot from 2020-01-01 20-01-33](https://user-images.githubusercontent.com/1495809/71640270-bdf62180-2cd2-11ea-9a63-204037a2e4d1.png)
![Screenshot from 2020-01-01 20-01-36](https://user-images.githubusercontent.com/1495809/71640271-be8eb800-2cd2-11ea-9d5d-03f402ff66b3.png)
![Screenshot from 2020-01-01 20-01-45](https://user-images.githubusercontent.com/1495809/71640272-be8eb800-2cd2-11ea-80ba-8576ac29b96d.png)
![Screenshot from 2020-01-01 20-01-48](https://user-images.githubusercontent.com/1495809/71640274-bf274e80-2cd2-11ea-849f-1696d4025e92.png)

```
"purchased.skin": {
	"winterstar": true,
	"snowy": true,
	"sugar": true,
	"polar": true,
	"holly": true,
	"festive": true,
	"dapper": true,
	"aurora": true,
	"zombie2": true,
	"transparent": true,
	"skeleton2": true,
	"shadow2": true,
	"reptile": true,
	"pumpkin2": true,
	"ogre": true,
	"candycorn": true,
	"tropicalwater": true,
	"shark": true,
	"merruby": true,
	"mergreen": true,
	"mergold": true,
	"merblue": true,
	"deepocean": true,
	"clownfish": true,
	"eb052b": true,
	"f5d70f": true,
	"f69922": true,
	"0ff591": true,
	"2b43f6": true,
	"d7a9f7": true,
	"800ed0": true,
	"rainbow": true,
	"pastelPink": true
},
"purchased.hair": {
	"color": {
		"TRUred": true,
		"blue": true,
		"purple": true,
		"green": true,
		"yellow": true,
		"rainbow": true,
		"candycorn": true,
		"ghostwhite": true,
		"halloween": true,
		"midnight": true,
		"pumpkin": true,
		"zombie": true,
		"aurora": true,
		"festive": true,
		"hollygreen": true,
		"peppermint": true,
		"snowy": true,
		"winterstar": true,
		"pblue2": true,
		"pgreen2": true,
		"porange2": true,
		"ppink2": true,
		"ppurple2": true,
		"pyellow2": true
	},
	"base": {
		"6": true,
		"15": true
	}
},
"purchased.shirt": {},
```

**Comment by SabreCat** [comment] 2020-01-01 19:21
Duplicate of #10225 I think?

**Closed as completed** 2020-01-01 19:28 UTC
Labels: priority: medium, help wanted, section: Avatar/User Modal
