### ISSUE TITLE
Master Keys to the Kennel is Broken

### ISSUE THREAD

**Issue by CuriousMagpie** [HabitRPG/habitica#13883] opened 2022-03-10 18:21 UTC
[//]: # (Fill out relevant information - UUID is found from the Habitica website at User Icon > Settings > API)
### General Info
  * UUID: 7debdd0a-23f0-46d9-af75-e364d8e877bf
  * Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:97.0) Gecko/20100101 Firefox/97.0

### Description
The Master Keys to the Kennel no longer work. We tested them on a local `develop` branch and then in production--the item worked in `develop` but not production. 

#### Console Errors
![Screen Shot 2022-03-10 at 1 05 32 PM](https://user-images.githubusercontent.com/78037386/157729322-3d8cf773-b413-4b25-b902-f6a058a7072c.png)

**Comment by Alys** [comment] 2022-03-11 07:10
I've just tested in production three times and each time I saw console messages similar to those but the pets and mounts were released.

**Comment by vanathi-g** [comment] 2022-05-02 04:23
Hey, @CuriousMagpie can I work on this issue? I checked and the pets and mounts are being released as intended. The console messages appear because of a forced reload (in `keysToKennel.vue`) interrupting the request-response flow.

**Comment by CuriousMagpie** [comment] 2022-05-04 21:11
@vanathi-g Sure thing! Thank you!

**Comment by vanathi-g** [comment] 2022-05-07 06:18
Hi, I just realized the issue hasn't been assigned to me yet @CuriousMagpie . Also, I have a couple of questions to clarify certain things:

1. There is no achievement for using Key to the Kennels (pet/mount/both)? 
2. The achievements Beast Master, Mount Master and Triad Bingo unlock the pet, mount and master keys respectively in the shop?

Basically (if I understood correctly), on using a key, there is no necessity to reload the page to reflect changes in achievements.

**Comment by Alys** [comment] 2022-05-07 09:30
@vanathi-g I've given this issue the "in progress" status label to indicate that you're working on it. Thanks for reminding us about that!

There's no direct achievement for using Key to the Kennels but use of it may increase the counter on Beast/Mount Master and Triad Bingo achievements.
Those achievements don't unlock the keys; the keys are unlocked when you've gained the appropriate set of pets/mounts.

There's more information about the unlock conditions and achievements in the wiki's [Key to the Kennels](https://habitica.fandom.com/wiki/Key_to_the_Kennels) page, in case that helps.

The file website/client/src/components/shops/market/keysToKennel.vue has some comments about why the reload was added.

**Comment by vanathi-g** [comment] 2022-05-07 13:41
Alright, thanks for the info @Alys !

**Closed as completed** 2022-05-19 20:37 UTC
Labels: priority: important, status: issue: in progress, section: Market
