### ISSUE TITLE
Cron Resets Early on Quests

### ISSUE THREAD

**Issue by mokaono7** [HabitRPG/habitica#5193] opened 2015-05-13 07:39 UTC
So my day is set to start at 9AM. The setting has been that way for almost three months now, yet the last two times I've done a quest, almost every day HabitRPG resets my cron twice in a day. Once 9-12 hours early, dealing anywhere from 14-25 damage to my party members for dailies I haven't yet completed, and once with the remainder of my damage to the boss at the turn of a new day. My party members and I have died more than once over this issue and it's making it impossible for me to quest anymore.

**Comment by deilann** [comment] 2015-05-13 07:41
We'll need your User ID to investigate. It'd also be appreciated if you
could post screenshots of the damage being dealt in party chat. If you want
to blur out names or personal chats, that's a-okay.

**Comment by mokaono7** [comment] 2015-05-13 07:51
7f090d0c-2569-4a8c-a47e-00467a0587aa

![screenshot 2015-05-13 02 48 33](https://cloud.githubusercontent.com/assets/3751787/7606009/aa31e292-f91a-11e4-85cb-cc1e04c56ab7.png)

My username is Mokano7 by the way.

**Comment by deilann** [comment] 2015-05-13 07:54
I don't see you doing damage twice in a 24 hour period?

**Comment by Alys** [comment] 2015-05-13 08:37
@mokaono7 I've checked in the database for the timestamps of your eight most recent boss damage messages and they are all approximately a day apart:
2015-05-13 08:09:47
2015-05-12 02:31:06
2015-05-11 08:40:44
2015-05-06 15:04:04
2015-05-05 12:55:36
2015-04-25 13:00:59
2015-04-24 18:24:21
2015-04-23 12:35:46

Note that those times are NOT necessarily in your timezone but they show that you're not doing damage twice a day, only once a day. The variation in times will correlate to variation in the time that you start using HabitRPG each day.

The process that resets your Dailies and applies progress to your quest (the "cron" process) does not occur at your custom day start time. It occurs when your account is active on HabitRPG for the first time after your day start time. Thus if your custom day start time was set to the default of midnight, and you  used HabitRPG for the first time at 8am one day, the boss damage from the previous day would occur at 8am.

It's possible that the day start time of 9am is confusing the issue. I recommend setting it to a time that is later than the last possible time you would use HabitRPG each day but not much later. So for example, if you typically go to bed at 10pm, set it for 11pm or midnight. If you work nights and sleep during the day, then a day start time of 9am might be exactly appropriate, but you do need to ensure that your due Dailies are marked as completed before 9am each day.

**Comment by mokaono7** [comment] 2015-05-13 09:11
I keep a tab of HabitRPG running all day, so it's constantly refreshing. And even if it were marking off the previous day's dailies when I refreshed it in the morning, I did all but two yesterday so I'm a little confused as to why it did so much damage.

**Comment by Alys** [comment] 2015-05-13 09:45
The website doesn't constantly refresh itself; it only refreshes when you take an action on the site. There is a process that can cause cron to occur exactly at your day start time, but only if the site is on an active tab of an active browser on an active device. Since you are (I'm assumimg) sleeping at 9am, your PC has probably put itself into hibernation by then. Regardless of the reason, your crons are not occurring exactly at the custom day start time, they're occurring when your account is active on the site after that time, which is the expected behaviour.

If you sometimes have unexpected damage, it might be from this bug: https://github.com/HabitRPG/habitrpg/issues/4313. See the Advice section at the top of the page.

**Comment by Alys** [comment] 2015-06-26 05:56
I don't think there was a bug here, except perhaps the one I linked to in my previous comment, so I'm closing this. It can be reopened if I am wrong.

**Closed as completed by Alys** 2015-06-26 05:56 UTC
