### ISSUE TITLE
hatching a pet gives a second, empty hatching dialog

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#9531] opened 2017-11-18 00:33 UTC
From AbelianGrape ( e723ec48-2de6-4560-8f89-ed505a3efdf3 ) in the Report a Bug guild:

"I hatched some pets today and after clicking the Onward! response to [this dialogue](https://pasteboard.co/GTYF7eC.png), a nearly empty hatching dialogue containing only the response buttons kept popping up again at the top of the page. It looked like [this](https://pasteboard.co/GTYFsxk.png). I tried clicking on the Hatch button when I took these screenshots just now, but it didn't seem to do anything."

It was also  reported by jaolsn ( 04fd7a1a-1964-49c6-a2cb-59d2d231c7f6 ).

**Comment by aalsehly86** [comment] 2017-11-19 00:36
@Alys I'm thinking this is related to issues #9393 and #9536!

**Comment by Alys** [comment] 2017-11-20 09:18
@aalsehly86 Could be! There are definitely problems related to inappropriate modals reappearing, but there might be a few different cases. It's known that modals you've seen before can reappear when they're no longer relevant but that's not easily reproducible as far as I'm aware, whereas this issue is which made me think it had its own specific cause. 

I'd be interested to know if you can reproduce this issue on your local install when you are using the `develop` branch and if  you can then not reproduce it when using your fix in https://github.com/HabitRPG/habitica/pull/9545. If your PR fixes this one as well as #9393, we can close this one when your PR is merged.

**Comment by aalsehly86** [comment] 2017-11-20 23:44
@Alys The method used in PR #9545 fixes this problem, and I was able to reproduce it.
![hatch-modal-error](https://user-images.githubusercontent.com/30061021/33046573-8e723160-ce1f-11e7-9c5c-88bc00b1d6be.gif)

> Clicking `cancel` will exit the empty hatching modal

Now this behavior is stopped once I change what triggers that modal in `website/client/components/inventory/stable/hatchedPetDialog.vue` 

That is changing `this.$root.$emit('bv::show::modal', 'hatchedPet-modal')` to `this.$root.$emit('bv::show::modal', 'hatchedPet-modal', '$event.target')`

Notice that in #9393, passing `'bv::hide::modal'` as a third argument stopped the wrong challenge modal from reappearing, and here `'$event.target'` also does the same job for hatching modals! Apparently passing a third argument, no matter what, will stop emitting the wrong modal!

Now after changing the code, it works fine
![hatch-fix](https://user-images.githubusercontent.com/30061021/33046725-36f412b8-ce20-11e7-9299-b98e964fc92b.gif)

Should I create a new PR or include the changes in #9393 and reference this one? Thanks.

**Comment by Alys** [comment] 2017-11-21 18:06
I think it will be easiest for everyone if you include the changes in #9393. Thanks!!

**Comment by SabreCat** [comment] 2018-02-22 17:37
Would it be acceptable to temporarily turn off the "Onward!" modal until this is fixed? It's sort of superfluous anyway...

**Comment by TheHollidayInn** [comment] 2018-03-02 21:12
Looking at this issue now and the behavior is correct with our "Stack".  Because the hack modal goes to the hatched modal, when you dismiss the hatched modal, all modals are assumed to go backwards, and it does. So, we need to make an exception for this modal in our stack. We've done something similar for purchasing transformations.

**Comment by SabreCat** [comment] 2019-03-21 21:20
I'm not seeing this happen lately. Closing, but feel free to reopen if it's still reproducible.

**Closed as completed by SabreCat** 2019-03-21 21:20 UTC
Labels: priority: medium, help wanted, section: Stable
