### ISSUE TITLE
Rewards, Equipment, Skills need better filtering options and maybe sorting options

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#4981] opened 2015-04-06 08:40 UTC
Currently, in the Rewards column, it's possible to filter for either "All" items or "Equipment & Skills".

Ideally, we would like to be able to filter for each of these things:
- All
- Custom rewards only
- Equipment only
- Skills only

The downside is that this might make the row of tabs too long so that it wraps unattractively. :(  "Gear" could perhaps be used as a synonym for "Equipment", although that's only a fix for the English interface.

It might also be nice if (instead of or as well as filtering) there could be an easy way of selecting the sort order, although we don't want too many preference settings added to Settings -> Site (preference overload is bad for usability). The default sort order must be the one currently in use on the site because that's necessary for the new users' tour to work correctly. EDIT: By sorting, I mean the changing the order of the sections (not sorting items within one section). The user should be able to choose whether they see Rewards at the top, or Skills, or Equipment.

Does anyone have any suggestions for how these ideas could be made to work in a usable fashion?

If anyone would like to submit code before any discussion happens, you're welcome to of course, but please be aware that usability issues might cause it to be rejected or we might need to ask that significant changes be made. :(
##

**Comment by ll2585** [comment] 2015-04-06 16:23
What about having the second button open a dropdown with the 3 options as a radio group?

**Comment by abigsmall** [comment] 2015-04-06 23:28
Piggy-backing onto @ll2585 ’s suggestion, use that dropdown to stash an option (below the radio group) to switch the radio group from filtering options to sort order options.

**Comment by gisikw** [comment] 2015-04-06 23:31
Also possible - use an accordion, rather than filtering?

Is the intended behavior "show one of [custom, gear, skills]", or "show some of [custom, gear, skills]"?

**Comment by Alys** [comment] 2015-04-07 00:11
Interesting ideas, @ll2585 @abigsmall @gisikw !

"show some of" would be nice, if the options to select them were easy to understand.

It would be especially good if the selection(s) were sticky, ideally in the same way that tags are so that we don't have another preference setting. That would make it per-browser sticky, but I think that's okay (it might even be beneficial to have it per-browser - at work you could show only custom rewards and hide the other two game-like sections, while having all of them displayed at home).

**Comment by mikeplis** [comment] 2015-04-12 12:48
I like @gisikw's suggestion of using an accordion. It would allow the user to collapse the sections that they don't want to see.

One possible issue is that the interface for the rewards column would be different than the other task columns. However, I think that's okay because the rewards column is a little bit different in that the items all belong to a fixed category.

@Alys How did you envision the sorting working? What options would be available (alphabetical, cost, etc.)? Would the sorting only occur within each category, or would you want the user to be able to group all rewards together and then sort?

**Comment by Alys** [comment] 2015-04-12 21:34
@mplis For sorting, I was referring to only the order of the sections (not sorting within a section). Sorry - I should have made that clearer. So, I'd like the user to be able to choose whether they have Rewards at the top, or Skills, or Equipment.

**Comment by Alys** [comment] 2015-04-12 22:05
Of course the accordion option would make section sorting irrelevant.

**Comment by AnitaYCheng** [comment] 2015-04-30 23:14
To keep all the columns consistent, why not make the sections draggable? That is, if the concern is the order of the sections and not availability.

**Comment by lemoness** [comment] 2015-10-13 21:57
I like the dragging option best, but would also be fine with an accordion. The nice thing about dragging is that it has a parallel with the other columns, where you can drag tasks. Of course, dragging the sections is a little different, but it's a similar concept.

**Comment by lynxlynxlynx** [comment] 2015-12-06 22:36
Since not much has happened since either report, how about a pragmatic improvement? Switching the order of spells and items is a oneliner (afaict) and would work even if one has many custom rewards — by using the existing tab that filters them.

**Comment by lynxlynxlynx** [comment] 2016-03-01 12:18
So, any objections to the oneliner\* improvement? Or are we doomed to wait for #5750, which suggests that most gear won't be lost on rebirth anymore.

*It's not a oneliner anymore, now that website/views/shared/tasks/index.jade is gone, but still just about shuffling a block of code (lists.jade).

**Comment by Alys** [comment] 2017-06-24 18:16
I'm putting this on hold because we're most of the way through a project to change the website's front-end code and this might no longer be necessary afterwards, or if it does, there'll be new code that will need to be modified to fix it.

**Comment by lemoness** [comment] 2017-10-16 20:35
This has now been resolved by the new redesign!

**Closed as completed by lemoness** 2017-10-16 20:35 UTC
Labels: status: issue: suggestion-discussion, priority: medium, status: issue: on hold
