### ISSUE TITLE
Losing HP

### ISSUE THREAD

**Issue by Zhelana** [HabitRPG/habitica#3238] opened 2014-04-09 21:14 UTC
I lose HP every day even though I finish all my dailies. It always happens the first time I hit a positive habit. Why am I losing points? This is going to make the site unusable, as I strongly dislike being punished repeatedly for doing nothing wrong.

**Comment by Alys** [comment] 2014-08-13 08:10
@Zhelana, I'm sorry we haven't replied to you before now.

It's likely that this problem was caused by sync errors. To learn about them, see  [Sync Errors](http://habitrpg.wikia.com/wiki/Sync_Errors) on the wiki, in particular the sections titled "How to Minimise Sync Errors" and "Completing most/all Dailies but still losing heath". The positive habit wasn't causing the health loss directly; instead it was causing a sync to occur, which caused the browser to reveal the negative effects of unsynced actions.

I'm closing this issue now since it's rather old (I really am sorry we didn't give you this information earlier), but if the problem is still happening and the sync error page doesn't help, comment here and we'll reopen this.

**Closed as completed by Alys** 2014-08-13 08:10 UTC
