### ISSUE TITLE
Gold to Gem Conversion Cap Not resetting

### ISSUE THREAD

**Issue by ZahRey** [HabitRPG/habitica#6618] opened 2016-01-29 22:23 UTC
Just realized my Gem cap did not reset to 20 in the first 3 days of January. I'm assuming this happened because I haven't purchased all 20 Gems that were available at the time until after the 3rd. 

Couldn't find this issue listed already elsewhere, but I hope this isn't a redundant Issue post. Thanks so much!

ID: 42beb3ec-916a-470c-987e-e6517c39fcac
Browser: But the issue persists on the app as well.

**Comment by Alys** [comment] 2016-01-29 22:45
@ZahRey Could you please give us some more details about this part: "I'm assuming this happened because I haven't purchased all 20 Gems that were available at the time until after the 3rd." I'm not sure I understand what happened there.

**Comment by ZahRey** [comment] 2016-01-29 23:59
It's honestly just a guess at what the issue might be. The tooltip says
that the Gem Cap is supposed to reset with the first three days of the new
month. It did not. I was positing that this may have happened because the
system didn't register as needing a reset because gems were still available
for purchase on the 1st, 2nd, and 3rd of the new month. Not all 20 were
available, but however many I haven't purchased by that point.

So lets say I had 3 gems left that I could purchase with gold when the
reset should have happened. It should have gone back up to 20, but it
didn't.

I don't actually know why, it was just a guess that the system might only
register the need to reset the amount of purchasable gems if you've
purchased all 20, not just a portion of those 20. Does that make sense?

**Comment by Alys** [comment] 2016-01-30 00:51
So at the end of last month, you had about 3 gems left from December's allotment. There were still three gems available on the 1st, 2nd, and 3rd of January, and also on the 4th, 5th etc until you bought those last three gems. Is that all correct?

**Comment by ZahRey** [comment] 2016-01-30 01:07
Right, and since I bought them there have been none available to buy.

**Comment by Alys** [comment] 2016-01-30 01:21
I've reset your number of gems bought to zero. If you don't have time to earn enough gold to buy them before the end of the month, you can use Fix Character Values (http://habitica.wikia.com/wiki/Fix_Character_Values ) to give yourself a loan or gift.

The system should definitely reset the gems bought even if there's some remaining from last month, with those remainders disappearing when the reset occurs (FYI, this is a motivation feature: it's designed to encourage you to earn enough gold to buy the gems before they disappear). Unfortunately we don't have database backups from that far back so I can't investigate this, however I'd like to see if it happens again. Could you please leave at least one gem unpurchased all the way through until 4th February (or when the reset happens, whichever is earliest)? To compensate you for not being able to buy that gem, I'll give it to you after the reset has happened.

I'll watch your account in the first three days of next month to see what happens. I'm able to do that without seeing your tasks or login details - I'll just be viewing the gem-related sections of your account.

**Comment by ZahRey** [comment] 2016-01-30 01:33
Absolutely.  And if it's easier, I will email you in this thread on either
the 4th or whenever the reset happens to update you on what happens. Thanks
so much!

**Comment by Alys** [comment] 2016-01-30 03:25
Thank you! It would be interesting to hear what happens from your point of view.

**Comment by ZahRey** [comment] 2016-02-04 18:12
Hi! Update: So as of today (the 4th) I still only have one Gem available to
purchase. The cap did not reset.

**Comment by Alys** [comment] 2016-02-04 21:10
I've just seen what the problem is - I should have noticed it immediately. I'm sorry about that. Somehow, your subscription information was missing a field called `dateUpdated`, which is modified as part of the monthly process to reset your gem cap, however it can't be modified if it doesn't exist and that was preventing the entire reset process from working.

It's fixed now so you shouldn't have this problem in future months, but comment here if it does happen again.

I've reset your gem cap and given you the extra gem that you didn't buy last month.

**Closed as completed by Alys** 2016-02-04 21:10 UTC

**Comment by ZahRey** [comment] 2016-02-04 23:14
Thanks so much!
