### ISSUE TITLE
Small Screen Bug

### ISSUE THREAD

**Issue by k8sullyvan** [HabitRPG/habitica#4012] opened 2014-09-10 10:52 UTC
When you make the page narrower (I was doing so to fit two chrome windows side by side) Bailey pokes through the notification bubble. It's probably just a layering thing, so possibly an easier bug to fix for a newer volunteer?
![screenshot 2014-09-10 11 48 40](https://cloud.githubusercontent.com/assets/7197274/4216314/513d9be8-38d8-11e4-8616-d2514a6ab73e.png)
##

**Comment by negue** [comment] 2014-09-10 14:59
Yes this is an easy bug to fix for newer volunteers.

**Comment by sbreiler** [comment] 2014-09-17 21:57
_Can you please give more info about your specs (which os, which browser version, desktop/mobile, ...)?_

_I couldn't reproduce the problem._

**Nevermind, did find the problem now.**

**Comment by k8sullyvan** [comment] 2014-09-17 22:25
erm... Using Mac OSX (10.9.4) 13 inch screen, on Chrome. Make the Chrome window about half the size of the screen, small enough so that the Gold Silver Gems and Bailey drop down on to a second grey level.

**Comment by casicastiel** [comment] 2014-09-17 22:39
This is either the same or very closely related to my problem in https://github.com/HabitRPG/habitrpg/issues/4015.

**Comment by Alys** [comment] 2014-09-17 22:45
Yes, probably at least closely related. I think #4015 should be fixed before anyone tries to work on this issue. See the comment I've just added to #4015.

**Comment by sbreiler** [comment] 2014-09-17 22:50
If the menu is collapsed everything should be allright - however i would change the notification z-index regardless, cause you can never be shure if it collapses the right way.

**Comment by Alys** [comment] 2014-09-17 22:57
Be cautious about adding CSS definitions "just in case". The more definitions there are, the harder it becomes to troubleshoot when something goes wrong.

**Comment by sbreiler** [comment] 2014-09-17 23:50
FYI: if the window is small enough the notification popup will change style to fill the hole window. In this mode it has z-index enabled.

My suggestion still is to add a seperate class to the notification popup using z-index - i don't see a better solution to solve this.

The whole collapse thing seems unpredictable, not future nor bullet proof. At the end you never know how browser render your stuff.

**Comment by SabreCat** [comment] 2017-07-26 00:07
Client display issue. Pending until after frontend redesign.

**Comment by lemoness** [comment] 2017-10-14 02:06
Is this still happening? If so, should we open a new ticket to account for the coding changes, or keep this one?

**Comment by SabreCat** [comment] 2017-10-14 02:10
I don't think we even have a Bailey head on the new site (sadly). Closing!

**Closed as completed by SabreCat** 2017-10-14 02:10 UTC
Labels: priority: minor, status: issue: on hold
