### ISSUE TITLE
Custom day change did not work. 

### ISSUE THREAD

**Issue by Pandoro** [HabitRPG/habitica#565] opened 2013-03-03 23:24 UTC
I set the value to 2, assuming it would be 2:00 AM, but the stuff reset at 12:00 PM just as normal. 

I just checked, the two is still there. So it wasn't an issue like "data wasn't sent to the server".

**Comment by lefnire** [comment] 2013-03-03 23:25
ok, critical. thanks alex

**Comment by lefnire** [comment] 2013-03-03 23:57
@Pandoro can you open up chrome console and run `+new Date`, paste the result as well as tell me what the actual time is where you are?

**Comment by Pandoro** [comment] 2013-03-04 00:05
I had to install chrome, but sudo apt-get would only let me get chromium,
but I guess that is fine ?

Failed to load resource: the server responded with a status of 403
(Forbidden) https://habitrpg.com/img/sprites/
- new Date
  1362355501035

actual time is 1:05 am

**Comment by lefnire** [comment] 2013-03-04 00:16
Ok! think i'm on to something, paste into chrome console, and hit Enter

``` javascript
$.getScript('https://raw.github.com/timrwood/moment/2.0.0/min/moment.min.js',function(){
var now = +new Date,
  momentNow = moment(now).format('MMMM Do YYYY, h:mm:ss a')
  lastCron = moment(window.DERBY.app.model.get('_user.lastCron')).format('MMMM Do YYYY, h:mm:ss a');
console.log({now:now, momentNow:momentNow, lastCron:lastCron})
})
```

**Comment by Pandoro** [comment] 2013-03-04 00:17
Object
1. Resource interpreted as Script but transferred with MIME type
   text/plain: "
   https://raw.github.com/timrwood/moment/2.0.0/min/moment.min.js?_=1362355417998
   ". 1YlHcfS-TmX8PpLh_AaPww.js:15https://habitrpg.com/gen/1YlHcfS-TmX8PpLh_AaPww.js

Object {now: 1362356229217, momentNow: "March 4th 2013, 1:17:09 am",
lastCron: "March 3rd 2013, 1:13:45 am"}

**Comment by lefnire** [comment] 2013-03-04 00:28
Well it's definitely taking timezone into consideration, it's getting the dates & times correct. Strange it looks like it didn't actually save lastCron to your user document.. 

_processing_

**Comment by Pandoro** [comment] 2013-03-04 10:13
Today I noticed I only had 45 hp, where I had 46 yesterday night. (Prior to my custom 2am reset.) However, if it would have reset everything based on Mondays tasks, I should have lost by far more than 1hp, as I have 12 open dailies on Monday. 

So:
Option 1. This is an unrelated bug.
Option 2. It reset again at 2am, but it only subtracted hp based on my 1 unchecked daily from Sunday.
Option 3. It reset again, based on 12 tasks, but the amount of hp I lost was by far too low.

**Comment by lefnire** [comment] 2013-03-04 14:30
ran some unit tests, and tested against my main & dummy accounts - worked for me. I actually think it was Option 2, because from your results above user.lastCron never stuck for some reason. Something is amiss with the lastCron save, but I think not with the custom startTime

**Comment by lefnire** [comment] 2013-03-04 16:15
bringing down to important until reproduced

**Comment by lefnire** [comment] 2013-05-14 16:57
this should be fixed in https://github.com/lefnire/habitrpg/commit/92b178b4a41eb96e24449f1bef3e379e85590bae , if anyone re-experiences please re-open

**Closed as completed by lefnire** 2013-05-14 16:57 UTC
Labels: priority: important

**Comment by wc8** [comment] 2013-06-29 16:59
Possibly related to #647.
