### ISSUE TITLE
Testing Can't +1 Own Chats, Interesting Results

### ISSUE THREAD

**Issue by deilann** [HabitRPG/habitica#2441] opened 2014-01-17 04:17 UTC
Attempting to +1 your own chats now gives you the lovely message. However, it freezes up my browser then redirects me back to tasks, rather than leaving me in the Tavern.

**Comment by colegleason** [comment] 2014-01-18 05:29
@deilann: Do you still experience this? I can't seem to reproduce it.

**Comment by deilann** [comment] 2014-01-18 05:44
Yes. I attempt to +1, get a hang up, and then it redirects me to the tasks
page. Happens in Chrome on my laptop, Chrome on my Android tablet, and
Puffin on my Android tablet.

**Comment by deilann** [comment] 2014-01-18 05:45
(For the record, I just tested it in Chrome on my laptop.)

**Comment by colegleason** [comment] 2014-01-18 05:53
When you get a chance, could you please do the following to help me debug?
1. Right click on the page and click "Inspect Element" to open the developer tools.
2. Click the tab called "Console".
3. Right click the console and check "Preserve Log upon Navigation"
4. Try to +1 your chat message.
5. Copy any text that appears in the console window here.

**Comment by deilann** [comment] 2014-01-18 06:09
Strangely, not getting anything there. Further notes: If I let the
notification expire and do not attempt to close it, I do not get a redirect.

Consider using 'dppx' units instead of 'dpi', as in CSS 'dpi' means
dots-per-CSS-inch, not dots-per-physical-inch, so does not correspond to
the actual 'dpi' of a screen. In media query expression:
(-webkit-min-device-pixel-ratio: 1.5), (min-resolution: 144dpi)
tweet_button.1389999802.html:1https://platform.twitter.com/widgets/tweet_button.1389999802.html
Given URL is not allowed by the Application configuration.: One or more of
the given URLs is not allowed by the App's settings. It must match the
Website URL or Canvas URL, or the domain must be a subdomain of one of the
App's domains.
body.scrollLeft is deprecated in strict mode. Please use
'documentElement.scrollLeft' if in strict mode and 'body.scrollLeft' only
if in quirks mode.
body.scrollTop is deprecated in strict mode. Please use
'documentElement.scrollTop' if in strict mode and 'body.scrollTop' only if
in quirks mode.

**Comment by colegleason** [comment] 2014-01-18 09:05
Ah, I wasn't trying to close it. I am now getting that problem.

On Sat, Jan 18, 2014 at 12:09 AM, deilann notifications@github.com wrote:

> Strangely, not getting anything there. Further notes: If I let the
> notification expire and do not attempt to close it, I do not get a
> redirect.
> 
> Consider using 'dppx' units instead of 'dpi', as in CSS 'dpi' means
> dots-per-CSS-inch, not dots-per-physical-inch, so does not correspond to
> the actual 'dpi' of a screen. In media query expression:
> (-webkit-min-device-pixel-ratio: 1.5), (min-resolution: 144dpi)
> tweet_button.1389999802.html:1<
> https://platform.twitter.com/widgets/tweet_button.1389999802.html>
> Given URL is not allowed by the Application configuration.: One or more of
> the given URLs is not allowed by the App's settings. It must match the
> Website URL or Canvas URL, or the domain must be a subdomain of one of the
> App's domains.
> body.scrollLeft is deprecated in strict mode. Please use
> 'documentElement.scrollLeft' if in strict mode and 'body.scrollLeft' only
> if in quirks mode.
> body.scrollTop is deprecated in strict mode. Please use
> 'documentElement.scrollTop' if in strict mode and 'body.scrollTop' only if
> in quirks mode.
> 
> On Fri, Jan 17, 2014 at 9:53 PM, Cole Gleason notifications@github.comwrote:
> 
> > When you get a chance, could you please do the following to help me
> > debug?
> > 1. Right click on the page and click "Inspect Element" to open the
> >    developer tools.
> > 2. Click the tab called "Console".
> > 3. Right click the console and check "Preserve Log upon Navigation"
> > 4. Try to +1 your chat message.
> > 5. Copy any text that appears in the console window here.
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/HabitRPG/habitrpg/issues/2441#issuecomment-32675445>
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/HabitRPG/habitrpg/issues/2441#issuecomment-32675644
> .

## 

## Cole Gleason

Student, University of Illinois at Urbana-Champaign
Email: cg@colegleason.com
Website: colegleason.com

**Comment by deilann** [comment] 2014-01-18 09:09
Further testing: other notification popups act similarly.

Fed pets to test it, despite not having the right food, oh well, and
closing that popup took me to /tasks as well.

**Comment by colegleason** [comment] 2014-01-18 09:10
Here is the issue (in bootstrap-growl): https://github.com/ifightcrime/bootstrap-growl/blob/master/jquery.bootstrap-growl.js#L16

We will want to modify that package to use window.location or something instead of `#`.

**Comment by deilann** [comment] 2014-01-18 09:17
A quick fix would be to set allow_dismiss: false

**Comment by colegleason** [comment] 2014-01-18 09:18
Sure, but let's see if we can't fix it real fast. Issue submitted here: ifightcrime/bootstrap-growl#40

I can also fork if we need to, but I would rather not.

**Comment by deilann** [comment] 2014-02-11 10:00
@colegleason This is driving me crazy. :c My default response when I see and read a notif is to close it.

**Comment by negue** [comment] 2014-12-05 23:08
Can't reproduce, @deilann does this issue still exist?

**Comment by crookedneighbor** [comment] 2015-01-31 17:34
@deilann I can't reproduce it either. Going to close it now. Re-open it if you're still experiencing it.

**Closed as completed by crookedneighbor** 2015-01-31 17:34 UTC
Labels: priority: minor

**Comment by deilann** [comment] 2015-01-31 17:39
I think we use a different notification system now
