### ISSUE TITLE
Negitive Experience Points

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#843] opened 2013-04-21 06:18 UTC
![wert](https://f.cloud.github.com/assets/3363224/406039/d316b276-aa4a-11e2-9f16-15b382b42f52.png)
My profile has been like this for a couple of days. I thought it would go away, but it hasn't.

User ID: 988a955d-7500-45ab-940d-c040401a0fb0

API Token: [redacted by @switz]

**Comment by lefnire** [comment] 2013-04-22 18:59
dupe of https://github.com/lefnire/habitrpg/issues/838, let's follow up there

**Closed as completed by lefnire** 2013-04-22 18:59 UTC
