### ISSUE TITLE
Changing Display Name

### ISSUE THREAD

**Issue by lapost48** [HabitRPG/habitica#4758] opened 2015-02-25 23:10 UTC
When a player changes their display name the change is not retroactive. For example, if Mrs. Lady says hello to a new group she is in and then changes her name to Ms. Woman, her original post is still labeled as being posted by Mrs. Lady. Clicking on Mrs. Lady does bring you to Ms. Woman's info page but the lack of retroactivity can lead to a lot of confusion
##

**Comment by Alys** [comment] 2015-02-26 07:38
Technical details to explain the current behaviour:
When a person makes a post, their comment and their unique User ID (UUID) are stored in the database document for the appropriate guild. Also stored are their current display name [EDIT 2019: and their current @Username] (and their current contributor tier if any, and a little other information). This means that their comment and name can be displayed together without needing any further database lookups. If only their UUID was stored, and not their name, then every time any player loaded the messages, or fetched new ones, a database lookup would have to be performed for every person who had made comments in that guild. This would be very expensive in terms of database load, and also message fetching time.

Because of this optimisation, you are correct: when a person changes their name, their previous posts do not change.

One solution for this would be to never store the name in the guild document and always do database lookups, but that would be too expensive. I don't think we should consider it. 

Another solution would be to go through all existing messages in all guilds and parties and change the name for all messages that user posted, at the time that the user changed their name. This would also be expensive and error-prone.

I'd like to suggest that even apart from these optimisation reasons, the current behaviour isn't too bad. Yes, there can be confusion when a person changes their name - I've seen one example of that recently, but it was rapidly resolved and not troublesome, and in fact mildly amusing. But of course there could be more serious confusion. However, if the names were changed retroactively, I suspect there would also be confusion - probably even more than now. Players typically answer each other in conversations by name, and that means that any prior conversations would be much harder to track because the names used in responses wouldn't match up with the names used in the posts being responded to. 

It could also be considered that the older name more accurately reflects the person at the time that the messages were posted under that name. For example, to use an amusing name-change feature from one of the guilds, "Bob Wearer of the Cone of Shame" was wearing the Cone at a certain point in the guilds history, and his posts at the time reflected the shameful situation that caused him to have that name (he had failed to action tasks he had committed himself to). At a different point in the history, he had redeemed himself and was no longer wearing the Cone, and his posts then reflected his improved status. Changing his name retroactively in those posts would destroy the history associated with the name changes. It's a bit of a frivolous example, but still a valid one I think.

Because of all these reasons, I personally wouldn't recommend that name changes be retroactive. Disagreements are welcome. :)

Possibly some middle ground would be suitable. A notification that X has changed their name to Y? But how would we tell which guilds to put it in? Any other ideas?

Note also that it's likely in time that the current chat system will be replaced by something different. How to handle name changes gracefully could be considered as part of that. I think that I personally would still like to see them not be retroactive.

**Comment by chimericdream** [comment] 2015-03-12 13:34
I think that short of an overhaul of the chat system as mentioned in the last couple lines of @Alys's response, I also believe that the current method of displaying names in chat is a good way to go. In my case, I haven't changed my name (and don't foresee doing so), but I have enjoyed watching the background color of my username change as I give back to the HabitRPG community.

I believe that some middle ground could be suitable, especially the suggestion of a notification of changes to a username. I could see it working like this:
1. There's a user called `chimericdream`
2. `chimericdream` changes his display name to `chimericdream, destroyer of worlds`
3. A chat message is posted in all guilds that the user is currently in\* with the text "_chimericdream_ changed their username to _chimericdream, destroyer of worlds_"
   - _Note:_ I don't think it would be worthwhile to find all guilds the user previously belonged to or posted in and put the message there. If they aren't in the guild anymore, their name change probably isn't really relevant.
4. ???
5. PROFIT! (ok... kidding on this one)

One side benefit to this could be that when users' contributor tier changes, a similar message could show up in their guilds. It's a little bit of extra public thanks for people who contribute. Something like this: "_chimericdream_ is helping HabitRPG grow! They are now a **Champion Blacksmith**!"

**Comment by deilann** [comment] 2015-03-12 13:43
I think the easiest solution is to do what Steam does -- keep a record in
the profile of the names the user has used called "Aliases". I think we'd
be fine keeping the last five or so.

I think the posting in guilds solution would be really annoying, especially
in the larger guilds and with users who are in a lot of guilds.

**Comment by chimericdream** [comment] 2015-03-12 13:53
@deilann I can understand that. I think it's definitely one of those features that can be done "right" in a lot of different ways, and it's hard to figure out which one the most people agree on. :-)

**Comment by deilann** [comment] 2015-03-12 13:56
Remember that in a good week, I might change my name twice.

**Comment by librarianmage** [comment] 2016-08-25 03:46
What is the status of this?

**Comment by Alys** [comment] 2016-08-25 03:58
I still think that we shouldn't change the behaviour for the reasons I listed above (copied below for convenience).

_I'd like to suggest that even apart from these optimisation reasons, the current behaviour isn't too bad. Yes, there can be confusion when a person changes their name - I've seen one example of that recently, but it was rapidly resolved and not troublesome, and in fact mildly amusing. But of course there could be more serious confusion. However, if the names were changed retroactively, I suspect there would also be confusion - probably even more than now. Players typically answer each other in conversations by name, and that means that any prior conversations would be much harder to track because the names used in responses wouldn't match up with the names used in the posts being responded to._

_It could also be considered that the older name more accurately reflects the person at the time that the messages were posted under that name. For example, to use an amusing name-change feature from one of the guilds, "Bob Wearer of the Cone of Shame" was wearing the Cone at a certain point in the guilds history, and his posts at the time reflected the shameful situation that caused him to have that name (he had failed to action tasks he had committed himself to). At a different point in the history, he had redeemed himself and was no longer wearing the Cone, and his posts then reflected his improved status. Changing his name retroactively in those posts would destroy the history associated with the name changes. It's a bit of a frivolous example, but still a valid one I think._

**Comment by librarianmage** [comment] 2016-08-25 04:07
@Alys I agree that it shouldn't be retroactively updated, but what do you think of the "Alias history" @deilann suggested?

**Comment by Alys** [comment] 2016-08-25 04:12
I like the "Alias history" idea! I think the users would like it too, especially if it recorded the UTC date-time stamp of when the change was made. For those who change names due to upgrades/downgrades in their personal progress, it would be a nice history archive feature.

**Comment by librarianmage** [comment] 2016-09-06 12:48
How would I store it?

**Comment by paglias** [comment] 2016-09-06 16:22
I think we should wait before implementing this until we've taken a definitive stance on the username vs display name issue and about what to use in chat mentions

**Comment by sreecharansankaranarayanan** [comment] 2016-10-24 00:35
Came here to report this as a new issue but the obviously active community has been working on this for some time :). I like the idea of keeping a record of aliases. I also like the idea of posting a greyed out message in the guild chat that was suggested by @chimericdream. The concern of too many posts in large guilds is valid and and this can be handled similar to how notifications are currently handled (no notifications from large groups).

The issue of transitioning from the name used currently to the new name also comes up. As of now, it takes some time but the handle changes from the previous name to the new name. Doesn't this cause confusion if the new name is entirely different?

**Comment by Alys** [comment] 2016-10-24 01:00
@sreecharan93 When you change your profile name, the change takes effect immediately. The name on your avatar changes and any new messages you post have your new name. Old messages from before your name change never have the name changed (that's deliberate since the name reflects the person at the time the message was posted). I've seen a few cases of mild confusion from name changes, but nothing serious.

I'm not really in favour of name change messages in guilds because of the potential spamminess of it and because of the server load from working out which guilds needed to be notified. However if we did implement that, we'd have to consider the case where a player was changing their name because their original one violated the Community Guidelines (happens fairly often). At the very least, automatic name change notifications would have to be flabgable. I suggest that we don't discuss that further now since there's no decision yet about notifications; I'm just noting it here so we don't forget it if it becomes relevant.

**Comment by sreecharansankaranarayanan** [comment] 2016-10-24 01:02
@Alys Thank you for your quick response.

**Comment by Alys** [comment] 2017-11-29 21:00
I'm closing this because it's more of a feature request than a bug report, and the current situation is working as intended, and we want to overhaul that name situation in general at some point.

However I have no objections if other admins disagree and reopen this. :)

**Closed as completed by Alys** 2017-11-29 21:00 UTC
Labels: status: issue: suggestion-discussion, priority: minor, type: memorable
