### ISSUE TITLE
[Bug] Cannot buy leather helm

### ISSUE THREAD

**Issue by nonckiewicz** [HabitRPG/habitica#514] opened 2013-02-25 18:04 UTC
When i'm clicking on 15 gold coins to buy leather helmet, nothing happens.

**Comment by lefnire** [comment] 2013-02-25 18:44
Anyone else experiencing this? Any [chrome console](https://developers.google.com/chrome-developer-tools/docs/console) javascript errors?

**Comment by nonckiewicz** [comment] 2013-02-25 18:54
I'm using FF

**Comment by nonckiewicz** [comment] 2013-02-25 20:23
but on chrome I have the same problem

**Comment by lefnire** [comment] 2013-02-25 20:25
while you're on chrome are you able to see if there's a console error? (firebug if you use firefox). Sorry, don't mean to put you to work - just can't replicate myself

**Comment by nonckiewicz** [comment] 2013-02-25 20:34
Ok, I know where the problem lies. I had 15 gold coins and 30 silver, and I cannot bought leather helmet, but when I reached 16 gold, I bought it. So there is something wrong with this prize for this helmet.

Kind Regards,
Adam

**Comment by toebu** [comment] 2013-03-09 19:29
Cannot reproduce this. Tried Firefox and Chrome, both works to buy the shield when having 15 gold plus some silver coins. On Firefox it took a few seconds to actually get me the helmet, but it worked out on the first click.
@nonckiewicz did anything like this happen again?

**Comment by nonckiewicz** [comment] 2013-03-11 09:31
Hi

No, it didn't happen again. Just in this case.

Kind Regards,
Adam

2013/3/9 Tobias Leugger - Vibes notifications@github.com

**Comment by paglias** [comment] 2013-09-09 15:14
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!

**Closed as completed by paglias** 2013-09-09 15:14 UTC
Labels: priority: important
