### ISSUE TITLE
Beast Master Achievement counts Rare Pets

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#1789] opened 2013-11-11 07:16 UTC
I am still two pets away from the beast master achievement, but because I have two rare pets, it just gave it to me and says I have 90/90!

The rare pets shouldn't count towards the achievement.

**Comment by SabreCat** [comment] 2013-11-12 13:16
I agree with this one, but I wrote something very similar up a while ago and was denied, heh...

**Comment by bobbyroberts99** [comment] 2013-11-12 16:59
I got Beast Master at 89 because of rare pet and then again at 90 when I actually got them all. 

On a related note (can't find an existing issue), eggs and potions that I purchased with gems aren't removed from inventory even after multiple reloads (and waiting 5 minutes)

**Comment by lemoness** [comment] 2013-11-13 01:32
Bob - I think we did have an issue with that, but it was closed - should we
reopen it again? @paglias @lefnire

**Comment by paglias** [comment] 2013-11-13 06:30
Yes there's an issue with eggs/potions not disappearing but doesn't seem to
be specific with bought items, I tried but couldn't reproduce.

**Comment by lefnire** [comment] 2013-11-13 06:33
This will likely be fixed when mounts is merged

On Tue, Nov 12, 2013 at 10:30 PM, Matteo Pagliazzi <notifications@github.com

**Comment by SabreCat** [comment] 2013-11-14 21:58
Interestingly, after today's inventory rollout my pets count seems to be off by one even counting my two Rare pets.

**Comment by lefnire** [comment] 2013-11-14 22:02
minus one, or plus one?

**Comment by SabreCat** [comment] 2013-11-14 22:04
Plus one. My count is currently (pets + rare pets + 1) out of 90. Could have happened when I hatched a pet, wasn't watching the total before/after. I'll keep an eye out if you can't spot the problem.

**Comment by SabreCat** [comment] 2013-11-16 13:02
Hatched another pet today, and the counter increased by 1 without problem. So I'm not sure! We already cleaned up those "undefined" pets from a while ago, right?

I guess unless it happens again, all I need is to have the counter reset to its proper value. But by the sound of it, deploying Mounts may clean up the pet counts along the way, so I'll hang out and see what happens then.

**Comment by paglias** [comment] 2013-11-16 17:14
@SabreCat undefined pets are still there I believe, I have one pet more than I should in pets' count. About beast master achievement I don't know if rare pets are still counted now

**Comment by lefnire** [comment] 2013-11-18 04:20
@SabreCat @paglias should be fixed, once and for all (see above commit). Do a double-check on your accounts

**Comment by SabreCat** [comment] 2013-11-18 12:50
Ah, great. Back to (pets + rare pets) / 90. Thanks @lefnire!

**Comment by paglias** [comment] 2013-11-18 15:29
I can confirm it's working, plus now rare pets shouldn't be counted in both pets found and for the beast master achievement.

See https://github.com/HabitRPG/habitrpg/commit/557d65a6263b4368c63f580d1c716cf0d304d06a and https://github.com/HabitRPG/habitrpg-shared/commit/ec1681fce460a332285e84b17932ef3d68fb05d5

Rare pets are currently hard coded in the habitrpg-shared helper (second commit above) so we should update it if we add more pets.

**Closed as completed** 2013-11-18 15:29 UTC
