### ISSUE TITLE
Viewing other's equipment

### ISSUE THREAD

**Issue by ParisiT** [HabitRPG/habitica#2415] opened 2014-01-15 13:51 UTC
When I go to see a party member's stats using the top bar, I end up seeing at least the equipment (maybe all of the stats, I am not sure) of the last person I clicked, rather than the person I am currently looking at. Not sure what's causing this bug and it's low priority, but I figured I would mention it.

**Comment by Aiseant** [comment] 2014-01-15 14:44
Indeed. Stats and Attribute seem ok, but Equipment is wrong if I don't hit F5 between members I'm looking at.

edit : after snooping around, it's a FIXME in views/shared/profiles/stats.jade

**Comment by lefnire** [comment] 2014-01-15 17:40
dupe of https://github.com/HabitRPG/habitrpg/issues/2323 , follow there

**Closed as completed by lefnire** 2014-01-15 17:40 UTC
