### ISSUE TITLE
Negative stats

### ISSUE THREAD

**Issue by nikrage** [HabitRPG/habitica#1060] opened 2013-05-27 17:36 UTC
I just opened habitrpg and my character had -3 exp and -6 gold..

**Comment by lefnire** [comment] 2013-05-27 18:36
dupe of #838. it's when you have habit open in two browsers at the time "cron" (next day rollover) happens. will likely be fixed in the 0.5 upgrade

**Closed as completed by lefnire** 2013-05-27 18:36 UTC
