### ISSUE TITLE
Enchanted Armoire dropped same piece of equipment three times

### ISSUE THREAD

**Issue by InconstantReader** [HabitRPG/habitica#7035] opened 2016-04-07 15:53 UTC
General Info
- UUID: 0e02a9dd-5807-4d34-b14e-af82a74074c4
- Browser: Firefox 45.0.1
- OS: Mac OS X 10.11.3
### Description

After selecting the Enchanted Armoire, I have "received" the Dragon Tamer Helm on three separate occasions. Checking my equipment afterward reveals no new drops.

**Comment by crookedneighbor** [comment] 2016-04-09 20:35
Closing this as a duplicate of https://github.com/HabitRPG/habitrpg/issues/5376

**Closed as completed by crookedneighbor** 2016-04-09 20:35 UTC
