### ISSUE TITLE
Bought limited edition "gumdrop sword", but it got automatically "unbought". Instead, have "winter-lit staff" in the inventory.

### ISSUE THREAD

**Issue by SebastianGG** [HabitRPG/habitica#4635] opened 2015-02-05 04:11 UTC
I bought the limited edition "gumdrop sword" on the last day it was available, but after a couple seconds the buy got undone automatically for no apparent reason, I lost the gumdrop sword and the gold was returned to me. Tried buying it several times, always with the same result.

Now (February 5) I check my inventory, and I have the "winter-lit staff", which I'm sure I haven't bought.

My user ID is 4a2ebb7d-3bf7-4e1c-9448-dcae23d296cf

Thanks in advance.

**Comment by Alys** [comment] 2015-02-05 05:13
Buying limited edition items on the final day can result in the behaviour you describe. It's because the server and your browser have different ideas of what time it is and/or whether the appropriate time period has actually finished. I can reassign it to you; you'll have it in a few minutes.  Comment again here if it hasn't shown up in half an hour (you might need to reload to see it).

That winter-lit staff.... We don't talk about that winter-lit staff.... :) Last weekend, I had to do a minor fix related to the party robes and limited edition item availability, which highlighted a problem with some code, and also a problem with some database data, which required other fixes, which highlighted more problems, and which then turned into [a whole hideous weekend of doom](https://github.com/HabitRPG/habitrpg/issues/4601). :) As part of my testing for limited edition availability, I was adding and removing the winter-lit staff from my own account, and then I forgot to comment out that piece of code and accidentally ran it over some other accounts (it was late; I was sleepy), resulting in some people being given the staff even if they hadn't bought it. It would have required significantly more work to discover just who had and hadn't bought it, and then to remove it from those who hadn't, and since I still had a bunch more work to do, I put that particular problem in the too-hard basket, where it remains to this day. If you don't like the staff, I can certainly remove it now, but I reckon you could also consider it a bonus for having to put up with the trouble caused by the gumdrop sword.

**Closed as completed** 2015-02-05 05:16 UTC

**Comment by SebastianGG** [comment] 2015-02-05 07:14
The gumdrop sword is already on my inventory.

I'll keep the winter-lit staff if you don't mind.

Thanks a lot, not just for fixing this, but for your continued hard work on this great tool HabitRPG is!
