### ISSUE TITLE
Adding member to group gives no indication of success

### ISSUE THREAD

**Issue by gms8994** [HabitRPG/habitica#1197] opened 2013-06-20 18:45 UTC
Adding a member to a group causes the page to spin for a second, then redirects back to the Habit-list page. No indication is given that it's working, or that it was successful.

**Comment by lefnire** [comment] 2013-06-21 02:16
dupe of https://github.com/lefnire/habitrpg/issues/1137, let's follow up there

**Closed as completed by lefnire** 2013-06-21 02:16 UTC
