### ISSUE TITLE
Exp reset every day

### ISSUE THREAD

**Issue by nicuveo** [HabitRPG/habitica#548] opened 2013-03-01 11:22 UTC
Hi!

I created my account on monday and got my first EXP point that day; on Tuesday I reached 4 EXP points. However, every day from then my EXP has been reset to 1.

The game seems to remember awarding me those points, though, as completing my daily tasks now reward me with 1.something amount of exp / gold instead of the 1 I had the first days.

Also, worth noticing: the progress graph was empty until today and now shows values starting from yesterday.

Health, however, seems unaffected: I lost a few health points on Tuesday / Wednesday, and it hasn't been reset to its Monday value, unlike exp.

As far as technical details go: I've been using Firefox only (on both Windows 7 and Linux Mint).

**Comment by lefnire** [comment] 2013-03-01 14:22
Oof, that's a solid one! For now use the [restore dialog](https://github.com/lefnire/habitrpg/wiki/Restoring-Your-Account) to put your Exp back each day, and I'll start looking into this. 

Do this for me - as you interact with the app periodically throughout the day, do a refresh each time before using it (see "Lost Progress" of the [same link](https://github.com/lefnire/habitrpg/wiki/Restoring-Your-Account) for an explanation). After that, is Exp also reset throughout the day, or is it just at the beginning of each new day?

**Comment by nicuveo** [comment] 2013-03-01 14:30
I usually do a refresh each time I check it, as I usually have the "could not reconnect" message. As I don't check more than once or twice a day, I can't tell for sure if it resets every day or during the day. For now it seems to remember my 3 exp points; I'll stay away from the restore dialog for now and will update this page tomorrow to report whether it happened again, and when.

(Btw, on each reload, the final popup of the tour shows up, although I click on "end tour" each time. Probably totally unrelated, though.)

Do you need my userId in order to investigate?

Thanks for the fast answer! :)

**Comment by nicuveo** [comment] 2013-03-01 14:31
Oh, well, more info right now; I just checked, and I now have a few less gold coins and 20 more silver coins than this morning. ^^"

**Comment by lefnire** [comment] 2013-03-01 14:32
I'll wait to hear the results, and if the same have you shoot me your uuid. Cookie not settings, hmm..

**Comment by Pandoro** [comment] 2013-03-03 16:21
@nicuveo Anything new regarding this?

**Comment by nicuveo** [comment] 2013-03-04 09:38
With the exception of the update (which explicitly states "hey I had more exp before!"), it hasn't happened again. It seems to me it stopped happening the day the progress graph started working, just as if my account wasn't really activated before that.

**Comment by nicuveo** [comment] 2013-03-04 20:03
It just happened again... :(
It might come from the fact I usually check-in from two different computers; one at home, one at work. This morning, at work, when I wrote my previous message, it was exactly as I left it on Friday, being offline the whole week-end. Now that I log in at home again, everything has been reset to what it was a few days ago; I've even lost the "daily" tasks that I did today and that I cheked at work.

**Comment by Pandoro** [comment] 2013-03-04 20:11
@nicuveo  please send lefnire your user ID if you haven't done so yet. I'm really sorry that this is happening. I can imagine that it is really annoying! Hopefully this will be fixed soon!

**Comment by nicuveo** [comment] 2013-03-04 20:51
Done. Hope that helps!

**Comment by lefnire** [comment] 2013-03-06 18:37
@nicuveo I'm checking out your user in the DB, everything seems fine. There are a bunch of fixes that went in recently, the one I think may have been causing issues for you is #562 (different bug, but I think same source). Can you try again for the next day or two and check back in?

**Comment by nicuveo** [comment] 2013-03-08 11:28
It still happens. :(

But I might have a clue; it might be linked to Firefox's session restoring, somehow. Here are the detailed steps of how I reached that conclusion.

The situation:
- computer A, at work, windows 7, up-to-date Firefox; I keep habitrpg in one of the _pinned tabs_, and the tab is _restored_ every day when I launch Firefox;
- computer B, at home, windows 7, up-to-date Firefox; I keep habitrpg in one of the _pinned tabs_, and the tab is _restored_ whenever I launch Firefox;
- computer C, personal laptop, Linux Mint, up-to-date Firefox, _no habitrpg tab_.

The steps:
1. Yesterday, at work, on computer A, I reached 75 EXP points. I double checked to see if it was correctly stored by ctrl-F5-ing the tab a few times; everything seemed okay.
2. At home, on computer B, I launched Firefox, and it restored the habitrpg tab to what it was the last time I opened it on B => somewhere around 40 EXP points.
3. I checked on computer C by opening a new tab and logging in: my EXP was indeed around 40, exactly the same stats than on B.
4. Today at work on computer A I launched Firefox; the restored habitrpg tab showed 75 exp points, just like yesterday, even after a few F5 keystrokes. I checked a daily task, jumping to 96 EXP points.
5. I logged in on my phone, which is not on the building's wifi; it shows me my 96 exp points.

To me it therefore seems like when Firefox restores a habitrpg pinned tab, it _overwrites_ the real stats by the ones of the previous session. Hope that helps!

EDIT: if it is indeed caused by Firefox restoring the pinned tab, I'll update the issue's name.

**Comment by nicuveo** [comment] 2013-03-13 13:44
@Pandoro it seems to be the same issue indeed.

**Comment by lefnire** [comment] 2013-03-13 14:31
Oh, this is caused by accessing from different computers after all? Ok, time to bust out me ol' PC

**Comment by paglias** [comment] 2013-09-09 15:14
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!

**Closed as completed by paglias** 2013-09-09 15:14 UTC
