### ISSUE TITLE
All of a sudden duplicates found in habits, dailies, and to-do list.

### ISSUE THREAD

**Issue by syntapy** [HabitRPG/habitica#5078] opened 2015-04-24 15:38 UTC
When I woke up this morning, the consecutive entries at the top that have the same color were found duplicated 4 times as shown in the image.

I'm using firefox in Lubuntu 14.04 along with NoScript (all scripts except google-analytics are enabled), vimperator, and lastpass.

![2015-04-24-083457_1680x1050_scrot](https://cloud.githubusercontent.com/assets/7295000/7322463/f819b7a4-ea5c-11e4-894f-c41d4efac8e6.png)

**Comment by syntapy** [comment] 2015-04-24 15:48
I've deleted the duplicates, but after clicking delete a middle one, one of the bottom duplicates was deleted instead. But, otherwise worked fine.

**Comment by hairlessbear** [comment] 2015-04-24 16:02
Thanks for the screenshot! This looks like an instance of #4470/#4773. Additionally, as it says in #4773:

> you'll be able to delete the duplicates if you start from those at the bottom of the list, rather than at the top.

That's likely why the middle deletion caused the bottom duplicate to disappear.

**Comment by Alys** [comment] 2015-04-24 22:11
@syntapy I am closing this issue since it is a duplicate of #4773 and if you want to follow the progress of the bug you can subscribe to email notifications from that issue.

Thanks @hairlessbear!

**Closed as completed by Alys** 2015-04-24 22:11 UTC
