### ISSUE TITLE
Tag reorder doesn't persist on sync or refresh

### ISSUE THREAD

**Issue by quin-jay** [HabitRPG/habitica#7572] opened 2016-06-01 04:10 UTC
General Info
- UUID: 1534a0ee-2f69-4c2e-9659-0d719ac2ea68
- Browser: Chrome 50.0.2661.102 m
- OS: Windows 7

Somehow my tag order got messed up, but every time I try to reorder them, either they revert to their previous order or the relevant tags end up in a different order unlike either the original or the intended. A non-ideal workaround is to delete the affected tags and create new ones in the order I'd like, but this a) disassociates them from tasks and b) puts my user-created tasks on the other end of challenge tasks, which is still not an order I want.

No console errors

**Comment by paglias** [comment] 2016-06-01 09:46
Duplicate of #7541

**Closed as completed by paglias** 2016-06-01 09:46 UTC

**Comment by quin-jay** [comment] 2016-06-01 19:36
Oops, I searched all issues for "tag reorder," and it didn't show me that one. Should've tried a second search phrase!
