### ISSUE TITLE
Rewards with gold value higher than 99 display the gold icon in a new line in Chrome.

### ISSUE THREAD

**Issue by vibitect** [HabitRPG/habitica#3976] opened 2014-09-03 13:52 UTC
Example:
![cool](https://cloud.githubusercontent.com/assets/1253248/4134945/6b16a634-3371-11e4-995b-0e75788854ba.png)

Note that this issue only appears in Chrome. (Not in Firefox).

**Comment by negue** [comment] 2014-09-03 16:42
Duplicate of #1993

**Closed as completed** 2014-09-03 19:00 UTC
