### ISSUE TITLE
Significant Incorrect Number of Pets Found

### ISSUE THREAD

**Issue by nextmike** [HabitRPG/habitica#1100] opened 2013-05-30 18:10 UTC
Says I found 24/90 pets when, in fact, I have only found 6/90.

User ID: f11e21b9-337a-41cb-b504-62aa7283a7ad

**Comment by lefnire** [comment] 2013-05-30 18:47
dupe of #1086, let's follow up there

**Closed as completed by lefnire** 2013-05-30 18:47 UTC
