### ISSUE TITLE
Cron ran halfway.

### ISSUE THREAD

**Issue by bTackt** [HabitRPG/habitica#4489] opened 2015-01-07 21:28 UTC
I logged into Habit today, 1/7, at approximately 1:30 PM to find that my dailies hadn't been unchecked from their state yesterday. Correspondingly, I hadn't lost any health. It was somewhat as if I had been in the Inn for a night, while I haven't.

However, cron has run; @paglias confirmed that the db showed that I had run it, and my collection for the party's quest for today has worked.

I've been out of the Inn for half a week, and I've never had custom day start on. Other than streaks not resetting (something, iirc, that has already been reported and, as I guess, probably a separate issue), I've never had problems with cron.

My username on Habit is the same as on GH; knittingfrenzy18.

I've been told that this may have to do with the experimental cron fix that was recently implemented.

**Comment by Alys** [comment] 2015-01-07 21:31
UUID is 6cb43b60-641d-4e30-a529-9f4733508958 (from Tavern post).

This sounds like a duplicate of https://github.com/HabitRPG/habitrpg/issues/4313 which was happening before the experimental cron fix.

**Comment by Alys** [comment] 2015-01-22 18:19
@knittingfrenzy18 We've been tracking this problem in https://github.com/HabitRPG/habitrpg/issues/4313  and are still working on it there, so I'm going to close your issue. If you want to follow the progress of the bug fix, you can subscribe to notifications from that issue (button in the right-hand column). If this happens to you again, we'd love it if you could post in that issue so we can track how common it is. If it's happening often and is really annoying for you, there's a workaround that might help: https://github.com/HabitRPG/habitrpg/issues/4313#issuecomment-70820170

**Closed as completed by Alys** 2015-01-22 18:19 UTC
