### ISSUE TITLE
Party members list can get out of sync in some flows with invitations

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#13107] opened 2021-03-10 22:24 UTC
Reported by @citrusella in the Report a Bug Guild:

> Strange behavior I encountered on my test account when doing some party shenanigans (in order to easily access a new, second test account's profile to send it some gems to test a thing):
>
> Here are the steps that happened that seem relevant in order, though I'm not sure every piece would be required to replicate it:
>
>    I invited a user (the second test account) to my test account's party
>    I opened the member list modal in the party and switched to the invited users tab
>    (Here I did some probably irrelevant things, like sending the new test account gems and having it try to buy a quest)
>    Invited user joined the party (because I suddenly wanted to try to start the quest using it, which I did and then aborted)
>    Invited user deleted their account
>    Member list modal (which was last open in the invited state) wouldn't display anything below the sort/search header, even though it should have listed @citrustest as the only member at that point
>    This persisted between pages (i.e. if I left the party page and came back) and didn't clear up until I had reloaded the website completely (though I didn't try to use the sync button)
>
>I suspect this has to do with it having been on the invite tab and either happened when the account joined the party or when it got deleted.

After some further investigation, @citrusella found a simpler flow to reproduce the situation:

>  Invite someone
>  Open the member modal before they accept, switch to the invite tab, close the modal and don't open it again
>  User accepts invite and now there are zero invites

**Comment by AlanGCruz** [comment] 2021-04-17 01:27
Hello @SabreCat i've been debugging this issue and this is what i found.

After following the steps to reproduce the situation above, i noticed that the problem happens when the user switches to the `invites` tab, closes the modal and before he opened the members modal again the invited user accepts the invitation. 

This happens because of three things:

1. Every time you open the modal, a request to get  all the invitees is made and once the data is fetched, it is assigned to the `invites` data.
2. The `invites` tab is only rendered if `invites.length > 0`
3. The modal has another data that stores the state of the last tab selected by the user inside the members modal called `selectedPage`. This means that if you close and open again the members modal the last selected tab will be active and its content will be rendered.

So for the next case:

1. The user invites someone
2. The user opens the members modal, switch to the invites tab and then closes the modal(`selectedPage` will be assigned to `invites` at this point)
3. The invited user accepts the invitation.
4. The user opens again the members modal.

The member modal component will try to render the `invites` tab content (because it was the last tab selected by the user so it's the current active tab) but because by this point the `invites.length` is zero then the content will not be rendered and that is why wouldn't see anything below the sort/search header.

One solution could be that each time we fetch the invites records(each time we open the modal) we can validate if it does have invitations(`invites.length === 0`) if it doesn't, then we should assign the `selectedPage` data value to its default. 
The only thing with this is that it will try to assign the value even if the last selected tab was not the `invites`, but this can be changed to this: `selectedPage === 'invites' && invites.length === 0`.

I also have a question. when the invited user accepts the invitation it is expected that the members modal shows the new member in the list without having to refresh the page or use the sync button?

i would like to continue working with this issue if is possible.

**Comment by AlanGCruz** [comment] 2021-04-26 17:23
Hey @SabreCat just to ask again if i can work on this issue? :)

**Comment by AlanGCruz** [comment] 2021-06-03 17:40
@SabreCat just to ask again if i can work on this issue.

**Comment by Alys** [comment] 2021-06-04 10:31
@AlanGCruz Thank you for asking! Please go ahead, and post here if you have any questions.

**Closed as completed** 2021-08-27 00:36 UTC
Labels: priority: minor, status: issue: in progress, section: Party Page
