### ISSUE TITLE
Challenges - Checking off To-Do unchecks Daily

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#1672] opened 2013-10-30 22:05 UTC
Joined the festivities challenge. Clicked off the Daily. Then tried to click off my first To-Do... but instead of eliminating the To-Do, it unchecked the Daily!!! Then when I tried to check off the second To-Do, it REchecked my Daily. Again, the To-Do was unaffected.

Clicking "buy reward" did nothing. No indication of gold dropping or anything. And I do have enough gold to buy it; I raised the number.

**Comment by wc8** [comment] 2013-10-30 23:49
I wonder if it’s because I deleted the test daily—and it didn’t delete. I was trying to see if I could get the daily to show up on my list. #1674

**Comment by lefnire** [comment] 2013-10-30 23:53
If in doubt, it's a challenges bug. Challenges overhauled a _crap ton_ of backend & database code - it was almost as heavy as the Angular migration! It's stuff that we've been hurting for for a long time, so it needed to happen - but challenges was the first feature to _require_ these changes; other features were able to workaround them. 

So this sounds like a legit bug, I'll dive in deep. But yeah, keep an eye out for anything that may go awry, not just related to challenges, while browsing around

**Comment by lemoness** [comment] 2013-10-31 01:12
Just tried it again in the new Challenge I just made... sure enough, same
problem!!! Also, clicking the Daily plus/minus for my Challenge did nothing.

**Comment by lefnire** [comment] 2013-11-01 07:50
can't replicate. try again with the new push?

**Comment by wc8** [comment] 2013-11-01 11:23
Still there… clicking Learn Spanish checked off Duolingo…

**Comment by wc8** [comment] 2013-11-01 11:26
Update… it happens on the Challenges page. It works correctly on my tasks list.

**Comment by paglias** [comment] 2013-11-01 11:26
I can confirm this only in the challenge page not in your lists, and it's
not only todo -> first daily but also second daily --> first daily.
Everything check off the first daily (probably the first item of the
challenge)
Il 01/nov/2013 12:23 "wc8" notifications@github.com ha scritto:

**Comment by paglias** [comment] 2013-11-01 16:45
Ok, this happens _only_ with todos & dailies which instead of checking off themselves check off the first daily of the list. Habits don't work -they can't be clicked- (why todos & dailies yes?) on the challenge page so i don't know about them.

**Comment by paglias** [comment] 2013-11-01 16:45
Also dailies and todos are supposed to be clickable from the challenge page?

**Comment by lefnire** [comment] 2013-11-01 16:49
ohhhh, on the challenge - not on my tasks. OK, fixed in 37027ac. Yeah, shouldn't be able to interact with tasks on challenge page - working on now. I realized that before I started with ui-router, I had chal tasks & user tasks as separate templates, and forgot that I had discarded that approach

**Comment by lefnire** [comment] 2013-11-01 17:20
fixed

**Closed as completed by lefnire** 2013-11-01 17:20 UTC
Labels: section: Challenges
