### ISSUE TITLE
Challenge Dailies Still Appearing After Challenge Ends

### ISSUE THREAD

**Issue by lordmatt** [HabitRPG/habitica#4318] opened 2014-12-03 11:39 UTC
I am seeing dailies from the challenge that I created (and won) even though it is finished. There is a little red box which says broken challenge link where the challenge link should be.

**Comment by deilann** [comment] 2014-12-03 11:50
Click on that. You'll be asked if you want to keep or remove the tasks.

**Comment by SabreCat** [comment] 2014-12-04 01:25
This is intended behavior; closing!

**Closed as completed by SabreCat** 2014-12-04 01:25 UTC
