### ISSUE TITLE
Inviting party to quest should hard-refresh party page

### ISSUE THREAD

**Issue by khipkin** [HabitRPG/habitica#7697] opened 2016-06-20 01:17 UTC
I invited my party to quest, but the only visual feedback I got was the quest modal going away.  Fetching recent messages and pressing the "sync" button didn't make any difference.  The quest invitations panel only appeared after I manually refreshed the whole page.

This is super weird to me and doesn't seem like desirable behavior.

Thoughts?

_edit by Alys, 16 October 2016:_

See [this comment](https://github.com/HabitRPG/habitica/issues/7697#issuecomment-254025148) and below it for the most recent status of this issue.

**Comment by crookedneighbor** [comment] 2016-06-20 01:49
Did you have any console errors when you started the quest? It does update automatically for me.

**Comment by khipkin** [comment] 2016-06-20 02:04
Yeah, but they seem to be the usual suspects:

> **Deprecation warning**: moment().zone is deprecated, use moment().utcOffset instead. https://github.com/moment/moment/issues/1779
> Arguments: 
> Error
>     at q.zone (https://habitica.com/app-1b0ee312.js:40:27860)
>     at Object.authenticate (https://habitica.com/app-1b0ee312.js:44:10815)
>     at Object.<anonymous> (https://habitica.com/app-1b0ee312.js:44:12036)
>     at Object.i [as invoke](https://habitica.com/app-1b0ee312.js:5:16822)
>     at Object.c [as $get](https://habitica.com/app-1b0ee312.js:5:15218)
>     at Object.i [as invoke](https://habitica.com/app-1b0ee312.js:5:16822)
>     at https://habitica.com/app-1b0ee312.js:5:14868
>     at g (https://habitica.com/app-1b0ee312.js:5:16455)
>     at Object.i [as invoke](https://habitica.com/app-1b0ee312.js:5:16789)
>     at D.instance (https://habitica.com/app-1b0ee312.js:6:8436)
> 
> **Failed to load resource**: net::ERR_BLOCKED_BY_CLIENT
> `https://www.google.com/ads/ga-audiences?v=1&aip=1&t=sr&_r=4&tid=UA-33510635-1&cid=293781116.1447859458&jid=360880557&_v=j44&z=2068794766`
> 
> **Mixed Content**: The page at 'https://habitica.com/#/tasks' was loaded over HTTPS, but requested an insecure image 'http://i.imgur.com/vmFiJQL.jpg?1'. This content should also be served over HTTPS. `/#/tasks:1`
> 
> **Mixed Content**: The page at 'https://habitica.com/#/options/groups/guilds/68d4a01e-db97-4786-8ee3-05d612c5af6f' was loaded over HTTPS, but requested an insecure image 'http://vignette3.wikia.nocookie.net/habitrpg/images/c/ca/Coding_3_by_phoneix_faerie-d7idtti.png/revision/latest?cb=20140518002315'. This content should also be served over HTTPS. `/#/options/groups/guilds/68d4a01e-db97-4786-8ee3-05d612c5af6f:1`
> 
> **Failed to load resource**: net::ERR_BLOCKED_BY_CLIENT `https://www.google.com/ads/ga-audiences?v=1&aip=1&t=sr&_r=4&tid=UA-33510635-1&cid=293781116.1447859458&jid=744401792&_v=j44&z=1409670486`
> 
> **Failed to load resource**: net::ERR_BLOCKED_BY_CLIENT `https://www.google.com/ads/ga-audiences?v=1&aip=1&t=sr&_r=4&tid=UA-33510635-1&cid=293781116.1447859458&jid=1534842060&_v=j44&z=1762331190`

**Comment by crookedneighbor** [comment] 2016-06-20 02:14
Can you go over exactly how to reproduce this? I was able to start a quest from the part page by pressing the start quest button without issue.

**Comment by khipkin** [comment] 2016-06-20 02:34
My party had finished our last quest, so I clicked the "Start a Quest" button, picked a quest scroll, and clicked "Invite Party to Quest".  Then the modal went away, the little blue load bar at the top of the page wooshed from left to right with no problem, and nothing else happened.

The "Start a Quest" button was still in the little panel on the left, just chilling.  No indication that anything had changed behind the scenes.  "Fetch recent messages" and "sync" didn't change anything.

I manually refreshed the page, and then the quest invites panel showed up as expected, the "Start a Quest" button was gone, and there was the list of pending and accepted invites, etc., as expected.

That's it.  That's the whole thing. :confused:

I've done this 3 times now, and the same thing keeps happening.  Except now the "Mixed Content" error messages don't show up on the console any more.  Ugh.

**Comment by crookedneighbor** [comment] 2016-06-20 02:38
Could be something specific to just finishing a quest and then starting a new one.

**Comment by khipkin** [comment] 2016-06-20 02:41
Maybe? That was the case the first time, but the other times were from canceling a quest invite and then immediately starting a new quest.

**Comment by khipkin** [comment] 2016-07-03 00:08
This is still happening for me.

There are tons of console errors like this:

> **`Failed to load resource: net::ERR_BLOCKED_BY_CLIENT`** from `https://www.google.com/ads/ga-audiences`

But there are also some different ones this time:

> **`Failed to load resource: the server responded with a status of 400 (Bad Request)`** from `https://api.amplitude.com` (10 of these errors)

![image](https://cloud.githubusercontent.com/assets/5641207/16543045/4fcb19cc-40c2-11e6-9fc5-c9df8d3fef32.png)

**Comment by Alys** [comment] 2016-07-03 00:10
@khipkin Can you try again with all browser extensions disabled? Might not make a difference but worth trying.

**Comment by khipkin** [comment] 2016-07-03 01:37
@Alys wow good call! That did it.  I wonder which extension caused it.  Adblock maybe?

The only errors on the console this time were 4x the `api.amplitude.com` error mentioned above.

**Comment by Alys** [comment] 2016-07-03 07:08
It could have been adblock or a similar blocking/privacy extension, although they really shouldn't have any effect on the quest behaviour and so this is something we should look at in more detail. Would you mind narrowing down which extension it was that caused the problem? As a first step, I'd recommend turning **on** all extensions **except** those that:
- block ads
- enhance security/privacy (e.g., extensions related to tracking software)
- are custom-built for Habitica (e.g., to modify how features in Habitica behave or how the website looks).

Then see if the original bug still occurs. If it doesn't occur, turn on more extensions one by one until the bug does come back.

**Comment by khipkin** [comment] 2016-07-03 12:59
I turned off all extensions again and checked that it still worked.  (It did.)

Then I turned them all back on, one at a time, and checked that it still worked each time.

The confusing part is that, even after I had re-enabled all of them, IT STILL WORKED. ???????  I mean, I guess that's a good thing, but now I have no idea why it ever didn't work to begin with?

**Comment by khipkin** [comment] 2016-10-16 03:29
This has started consistently happening to me recently.

**Comment by Alys** [comment] 2016-10-16 03:51
Confirmed. When I used the "START A QUEST" button that's on the party page itself, a brief sync occurred but the quest didn't appear on the page. I had to reload the page manually to make it appear. I tested twice and it happened both times.

I tested starting a quest from the Inventory > Quests page, and once the problem did not occur (the quest appeared as soon as the party page appeared) but the second time the problem did happen.

This could be fixed by forcing an automatic reload, or possibly by more advanced client-side code that inserted the quest details into the party page without needing to reload. However since we'll be rewriting the client side code soon, I don't recommend the latter approach. Simply forcing a reload should be simple enough to be worth doing now.

**Comment by Alys** [comment] 2016-10-17 21:56
This problem just occurred for me when starting from the Inventory > Quests page. I'm updating my previous comment to state that.

**Comment by khipkin** [comment] 2016-11-17 22:33
Another example of weird partial-party-sync behavior, this time when a quest ends:
![image](https://cloud.githubusercontent.com/assets/5641207/20397372/7854d9b2-acb7-11e6-9b38-8fa4077d3330.png)

**Comment by marceloyuela** [comment] 2016-11-25 00:13
Is this still open? If so, I can try to get a force-refresh of the page working in the next week and a half.

**Comment by Alys** [comment] 2016-11-26 04:10
@marceloyuela It is still open, thank you!

**Comment by TheHollidayInn** [comment] 2016-11-26 15:49
@marceloyuela Instead of a refresh, you can also use this strategy:

https://github.com/HabitRPG/habitica/blob/develop/website/client-old/js/services/groupServices.js#L110

https://github.com/HabitRPG/habitica/blob/ac732b2c85853570b31d596d0a5054cd46bed2ec/website/client-old/js/controllers/notificationCtrl.js#L17

You can use this to force a full refresh of the part in the Group services by calling `sync(true)` or you can try an update only what is needed like the example above.

**Comment by marceloyuela** [comment] 2016-11-26 21:15
Hey, thanks!

**Closed as completed** 2016-12-10 20:34 UTC
Labels: priority: medium, status: issue: in progress
