### ISSUE TITLE
Habit consuming >2GB of memory over extended periods

### ISSUE THREAD

**Issue by keysmashes** [HabitRPG/habitica#4605] opened 2015-02-01 04:46 UTC
Left Habit open in Chrome for about 12 hours(?); laptop froze & started swapping, at this point about 5.1GB of RAM were being used (of 6GB). I managed to close the Habit tab, and memory usage instantly dropped to 2.6GB, a difference of 2.5GB. Ubuntu 14.04, Chrome 40 (stable channel).
![habitmem](https://cloud.githubusercontent.com/assets/9433472/5991085/452cbc06-a9cd-11e4-9a48-a699c00c3137.png)

I've seen #1499, but this seems to be happening over time (as I'd noticed RAM usage climbing throughout the day, but assumed it was just YouTube/Chrome memleaks), as opposed to being connected to excessive to-dos, as I only have 15 cards (habits, dailys, to-dos) total.

ba265326-25a9-48e1-9112-33aeeac957a9
##

**Comment by keysmashes** [comment] 2015-02-01 19:48
I've left the site open for about 6 hours (very approximately), and Chrome says the tab is consuming 961MB of memory, an increase of at least 700MB from a newly-opened tab using about 200MB.
![habit-chrome](https://cloud.githubusercontent.com/assets/9433472/5993503/1f0f6d24-aa4b-11e4-862e-a8fa05d5f0bd.png)

**Comment by lefnire** [comment] 2015-02-01 19:54
Woa mama... that's not good. It's probably due to #4079 (since the script is local too via browserify). In the meantime, open chrome console and delete the localStorage props for habitrpg: https://www.evernote.com/shard/s17/sh/b49b4853-c2b2-4183-8350-cce2ea6d534f/405d4b8a9d4ae72903e44ad159512999

**Comment by keysmashes** [comment] 2015-02-01 21:03
Done. Delete them each time page is reopened/reloaded (given they've reappeared post-reload) or just delete once now & see how it goes? I probably won't have a chance to try reproducing again till next weekend (school...).

**Comment by lefnire** [comment] 2015-02-01 21:12
Once asked see how it goes. It might log you out

**Comment by keysmashes** [comment] 2015-02-04 17:29
Deleted them. I'll leave the page open for a few hours, see if memory usage increases (currently at 290 – 305MB).

**Comment by keysmashes** [comment] 2015-02-04 18:29
~~After an hour, mem use is up to 320MB~~ Feels like it's trolling me now, I looked on Chrome's task manager and it was at 320MB, go to the page, see that a) localStorage bits I deleted are back and b) memory use is up to 365MB when the page is being viewed and down to 303MB when not...

**Comment by keysmashes** [comment] 2015-02-04 20:01
Up to 750MB now (~2 hours later); the local storage keys reappeared at some point.
![screenshot from 2015-02-04 19 36 50](https://cloud.githubusercontent.com/assets/9433472/6048315/3c8e6e32-aca7-11e4-8853-9860cd7693b1.png)

**Comment by paglias** [comment] 2015-02-04 20:02
Are you using some custom script? The look is different
Il 04/feb/2015 21:01 "Josh Holland" notifications@github.com ha scritto:

**Comment by keysmashes** [comment] 2015-02-04 20:11
@paglias I'm using (a slightly modified for site updates) HabitRPG – The Adventure Begins, from Stylish; I can test without it at the weekend if you think it could be causing the issue.

**Comment by crookedneighbor** [comment] 2015-02-04 20:30
@joho506 Please do. I don't necessarily think it's related, but I like eliminating as many variable as possible.

**Comment by noidexe** [comment] 2015-02-04 20:33
I'm using HabitRPG without any modifications and I have the same issue. Windows 8.1 and Chrome 40 x64.
Deleting the localStorage keys didn't fix it for long.

**Comment by keysmashes** [comment] 2015-02-04 21:42
After about 4 hours, the HabitRPG tab is consuming 1.3GB of RAM. Viewing it or not maybe makes a difference of 100MB, but not much more. A reload has dropped it to 600 – 900MB, depending whether it is the open tab or not. I'll test disabling custom styles when I can, and at the weekend I'll try just having the HabitRPG tab open and leaving it for several hours.

**Comment by boo2060** [comment] 2015-02-06 02:00
Have the same issue. On Ubuntu 14.04, using Firefox.
Memory usage goes up to 3.3 GiB, paralyzing my whole computer. It doesn't happen always but frequently (several times a day). Often I have to kill the Firefox. I deleted all done to-dos recently but didn't help much. Will clear them again and report on issues in a while.

![screenshot habitrpg memoryusage 6feb15](https://cloud.githubusercontent.com/assets/10874246/6073426/6afde24a-adae-11e4-8fdf-83cfa9477709.png)

Well, my issue seems to be a bit different in that memory use peaks when I actively view the tab, not when it is open in the background (in that case Firefox uses about 400 MiB).

**Comment by lefnire** [comment] 2015-02-06 03:49
that's insane. Ok let's try to come up with a common denominator.
Do you y'all frequent guilds out challenges? How many tasks do you track
(ballpark like 10s, 1000s)

**Comment by noidexe** [comment] 2015-02-06 04:18
27 tasks. I've joined 4 guilds but never done any challenges. Only party quests.

**Comment by boo2060** [comment] 2015-02-06 13:55
The same here, joined 2 guilds, subscribed to some challenges way back then and never participated (and cancelled). In a party of 8, doing a lot of quests. Tasks: 15 active (some of them very old - like half a year), 12 archived (done to-dos).

Today Habit is not useable at all, upon opening the tab it sucks up all the RAM within seconds. Usually I was able to use it for a while after booting (or killing and reopening firefox) before issues occured.

Update: I switched to use Habit on Chrome. So far it is working. Chrome memory use in the background (only using Habit): up to 200 MiB; memory use while actively browsing Habit : ~ 400 MiB.

**Comment by keysmashes** [comment] 2015-02-06 21:24
Order of 20 tasks; IIRC I joined a couple of guilds (but can't actually remember how to find them), never been in a party or initiated a quest. Doing 1 or 2 challenges.

**Comment by NobbZ** [comment] 2015-03-14 08:20
I do also have the same problem. Memory consumption rises with a rate of about 100 to 200 MB/h. Using the delete-localStorage-trick does not help (that much), consumption goes a little bit down, but rises again after a short time.

Problem does occur on Win7 Chrome (autoupdated) and also Ubuntu Chrome (even kept up to date on daily basis).

Also I made the following observations:
1. When mem consumption is high, I need to **close** the tab, hitting `F5` or even `CTRL-F5` does not help
2. Closing the memory consuming tab and reopen habitrpg in a complete new tab results in an initial consumption of about 200 MB, climbing up to about 350 in a couple of seconds, staying there for about a minute, falling back to about 150, before starting to rise in above mentioned rate.
3. Maximum consumption I have seen so far was about 6 GiB (of 8 GiB system memory + 8 GiB swap), this was the point when my whole system went into a nearly unusable state because of constant swapping.

**Comment by Zelah-Meyer** [comment] 2015-06-16 14:36
I also have a problem with very high memory usage in Internet Explorer (I know, I know, but the Favourites menu is much more user friendly than Chrome's!)  Often my task page will freeze up and I'll have to delete it and re-open it in order to get back in.  Or, kill the process as described below.  

I have four home page tabs in I.E. and when HabitRPG freezes up on me, if I open Task Manager and check over processes, I'll have an I.E. process listed at around 1,500,000k.  If I click on 'end process' it refreshes all four of my home page tabs & then HabitRPG starts working again.

I have a reasonable amount of tasks.  Too many for me to feel particularly enthusiastic about the thought of counting them! - but it's probably between 100 and 200 in total, mostly habits & to-dos.  It's my task page that tends to freeze up on me rather than my social page (which I usually have open in a separate tab.)  

I have a LOT of tabs/windows open in I.E. in general, but each website seems to show as a separate process, and though the memory spike seems to be coming from HabitRPG, it does refresh all four homepage tabs (Pinterest, Hotmail, Yahoo Mail, and HabitRPG) when I kill that process (and none of the other websites sharing that window.)

Obviously, because I use I.E. for HabitRPG in general, I can't give you any Chrome Console info, but thought I'd pass on the info I do have to hand in case it helps.

**Comment by LordVladneutral** [comment] 2017-06-25 09:57
I'm on Arch, latest version, and Firefox, also latest version (stable ones, though)

I think I got a pretty unique feedback about this matter :  the freezing also frequently happened to me, so I was looking for a solution on my own. First I looked at reducing my task list to the minimum, same with guilds and challenges, that helped, but really just a bit.

Then I looked at the browser side of things. And I had a lot of add-ons, so I disabled them, one or two at a time, and looked if the problem was still there. It was, until I disabled one called "Load tabs on select" which does nothing but prevent tabs from loading until you go to them. It seems really weird to me that this add-on could cause this.

Now it's not really gone either, but it's really minimised, so the site is a lot more usable. If you want me to do some tests, just ask.

**Comment by paglias** [comment] 2017-06-25 10:12
@LordVladneutral thanks for the report, I just want to say that we're working on a complete redesign and rewrite of the client side of the site that should be released in a few months from now and we hope it'll give a boost to performances and greatly reduce the memory usage of the app

**Comment by lemoness** [comment] 2017-10-14 02:09
Is this still happening?

**Comment by SabreCat** [comment] 2017-10-14 02:17
There was some dev discussion of largish memory usage, but nothing like 2GB--more in the hundreds of MB.

**Comment by lemoness** [comment] 2017-10-19 02:25
In that case, I'm going to close it for now. If we need to, we can always reopen this.

**Comment by VisionaryLion** [comment] 2018-01-11 22:01
Found this place since I've been experiencing computer slow down. Habitica seems to be the cause. Seems to get worse the longer I have the tab open. Saw the memory usage spike at about 1gb.

**Comment by TheHollidayInn** [comment] 2018-02-04 23:02
@visionarylion we've fixed some memory leaks recently. Are you still noticing these issues?

**Comment by VisionaryLion** [comment] 2018-02-07 10:05
@TheHollidayInn So far it seems to be running a lot smoother. I'll let you know if I experience anymore slowdown.

**Comment by paglias** [comment] 2018-02-11 17:39
Going to close this ( once again :) ) but comment if you still experience any problem!

**Closed as completed by paglias** 2018-02-11 17:39 UTC
Labels: priority: important, status: issue: needs investigation

**Comment by youve** [comment] 2019-01-21 12:56
Hi!

I'm experiencing memory leaks on habitica over the past few weeks. I normally leave habitica open in a browser tab all day long so that I can check off my tasks and always have a quick view of what's next to do, but by the end of the day I'm using all 3GB of ram and all 2GB of swap space and my computer has slowed to halt. When I keep the habitica tabbed closed all day, I don't experience this memory problem, but I also get a lot less done. I have manually deleted my completed todos recently, after I figured out the problem was my habitica tab.

I have 31 dailies, 10 habits, 86 todos, and 1 custom reward. I'm a member of 15 guilds and am in 17 challenges. My userid is 52d07da8-722d-499e-896e-837b5a47309f and I'm using qutebrowser on archlinux. I'm going to try leaving some guilds but is there anything else I can do?

**Comment by paglias** [comment] 2019-01-22 08:46
@youve sorry about that, can you try with Firefox / Chromium to see if the problems occurs with them as well?

**Comment by youve** [comment] 2019-01-22 13:58
Hi! I experminented a little with Chromium today. Stats for just the Habitica tab.

10:00 150 k - started it. 
12:00 220 k
13:06 340 k
14:00 I don't know what the memory usage was by this time because the computer froze  completely and I had to switch to a different tty to kill chromium. This was a lot earlier in the day than I usually start having memory problems probably because chromium is slower than qutebrowser (they both use qt5).

During these four hours I was getting a lot of messages from Chromium that the habitica tab wasn't responding. I chose to wait rather than to kill it because I wanted to see how high the memory usage would get. I'm going to try again with Firefox.
