### ISSUE TITLE
Challenges not loading

### ISSUE THREAD

**Issue by michaelmatias96** [HabitRPG/habitica#5929] opened 2015-09-15 12:59 UTC
Please reload, "Error Runner error: Overflow sort stage buffered data usage of 33699821 bytes exceeds internal limit of 33554432 bytes" If the error persists, please report it at Help > Report a Bug. If you're familiar with your browser's console, please include any error messages.
##

**Comment by michaelmatias96** [comment] 2015-09-15 13:23
<img width="1440" alt="screen shot 2015-09-15 at 3 59 02 pm" src="https://cloud.githubusercontent.com/assets/10121177/9877517/05bd6628-5bc6-11e5-85d6-c26786c62042.png">

**Comment by Nairolf21** [comment] 2015-09-20 21:56
I have the same error. It's happens when I want to join a challenge. Because of that, I can't join the challenge... 
![screenshot - 09202015 - 02 56 13 pm](https://cloud.githubusercontent.com/assets/8713428/9983160/caa0888c-5fa7-11e5-965f-91011a146e15.png)

**Comment by Nairolf21** [comment] 2015-09-20 22:04
This is the Request Headers I obtain : 

x-api-user: 2fe09154-cc20-4fa4-a21e-da786f089ece
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:40.0) Gecko/20100101 Firefox/40.0
Referer:    https://habitica.com/
Pragma: no-cache
Host:   habitica.com
DNT:    1
Content-Type:   application/json;charset=utf-8
Content-Length: 1121975
Connection: keep-alive
Cache-Control:  no-cache
Accept-Language:    fr,en-US;q=0.7,en;q=0.3
Accept-Encoding:    gzip, deflate
Accept: application/json, text/plain, _/_

**Comment by crookedneighbor** [comment] 2015-09-21 01:42
@Nairolf21 You accidentally posted your api token in that last message. We've edited your message so it's no longer displayed, but since it's a password, I've also issued you a new token.

This will result in Habitica.com no longer working until you log out and log back in. Also, any third party programs you use that require your user id and api token (such as a mobile app or the chrome chat extension) will need you to log out and log back in with  your new credentials.

I've also put you in the inn, just in case you don't see this message before your next cron, you won't accidentally receive damage.

**Comment by Nairolf21** [comment] 2015-09-21 02:35
@crookedneighbor : Oh, thank you for what you've done. My api token was the attribute "x-api-user" ? Is it that you've changed ? 

Thank you.

**Comment by crookedneighbor** [comment] 2015-09-21 02:42
@Nairolf21 `x-api-key` (we deleted it from your previous post).

**Comment by Nairolf21** [comment] 2015-09-21 02:54
Okay, thank you for that.

**Comment by MaleCoconut** [comment] 2015-09-26 16:02
I have exactly the same problem as @Nairolf21 does with the same challenge.
My user id is 9abd79c0-b5c6-4876-8783-520c2596ea84

**Comment by crookedneighbor** [comment] 2015-09-26 17:09
@Nairolf21 Are you still having the issue? I see you're not part of the challenge yet. If so, I can add you to the challenge.

@MaleCoconut I've added you to the challenge.

@michaelmatias96 are you still having issues? Usually this problem only lasts for a few hours.

**Comment by Nairolf21** [comment] 2015-09-26 18:27
@crookedneighbor : Yes, I still have the issue. I would appreciate if you could add me, please.

**Comment by crookedneighbor** [comment] 2015-09-26 20:39
@Nairolf21 I've added you.

**Comment by MaleCoconut** [comment] 2015-09-27 03:54
@Nairolf21 thanks :)

**Comment by MaleCoconut** [comment] 2015-09-27 03:55
@crookedneighbor thanks :)

**Comment by michaelmatias96** [comment] 2015-09-27 10:27
Now working for me as well!

On Sun, Sep 27, 2015 at 4:55 AM, MaleCoconut notifications@github.com
wrote:

> @crookedneighbor https://github.com/crookedneighbor thanks :)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/HabitRPG/habitrpg/issues/5929#issuecomment-143515789.

## 

Watch my recent TEDx talk https://goo.gl/s5gDDi in Palo Alto, California!

Read about my project Hacking Generation Y http://hackgeny.com/israel:
Times of Israel
http://www.timesofisrael.com/google-scion-whiz-kid-hacks-his-way-to-idf-service/
Globes http://www.globes.co.il/news/article.aspx?did=1001029469
Voice of Israel
http://www.voiceofisrael.com/michael-matias-a-young-israeli-entrepreneur-with-a-vision-and-a-new-uniform/
Israel21C
http://www.israel21c.org/headlines/every-teen-should-run-a-startup/

**Comment by Ladeia** [comment] 2015-10-02 09:57
I have a similar problem. 
When I reload the app, habitica dont effective my last steps in game.
I use the "backstab" and I get one new level, before I user the "enchanting armoire" and I get one item ou xp (I lost my beautiful crosbow and one mission scrol) but when I make a reload app, the mods are discarded, and i lost the item e the scroll.

Data of my console
Object { data: Object, status: 500, headers: tc/<(), config: Object, statusText: "Internal Server Error" }
.responseError() app-502a14e5.js:36
j() app-502a14e5.js:7
k/<() app-502a14e5.js:7
wd/this.$get</j.prototype.$eval() app-502a14e5.js:7
wd/this.$get</j.prototype.$digest() app-502a14e5.js:7
wd/this.$get</j.prototype.$apply() app-502a14e5.js:7
s() app-502a14e5.js:6
w() app-502a14e5.js:6
y() app-502a14e5.js:6

**Comment by crookedneighbor** [comment] 2015-10-02 13:51
@Ladeia It sounds like you're actually experiencing this bug: https://github.com/HabitRPG/habitrpg/issues/4986

There is advice on how to fix it.

**Comment by RandomSue** [comment] 2015-11-27 12:33
I have the same issue, challenges page isn't loading. What can I do to fix it?

"Error Runner error: Overflow sort stage buffered data usage of 34085387 bytes exceeds internal limit of 33554432 bytes"

**Comment by Alys** [comment] 2015-11-27 13:18
@RandomSue It's possible that one of the challenges you're in is too large and is causing the error. If so, there's not really anything you can do to fix it since to leave the challenge you need to use the challenges page. If you'd like us to investigate to see if this is the cause, please tell us your User ID (see step 6 of Help -> Report a Bug for how to find your User ID).

**Comment by Alys** [comment] 2016-02-22 05:56
I'm closing this issue because we have it reported in https://github.com/HabitRPG/habitrpg/issues/4132

**Closed as completed by Alys** 2016-02-22 05:56 UTC
