### ISSUE TITLE
Nerfing Burst of Flames Boss Damage

### ISSUE THREAD

**Issue by deilann** [HabitRPG/habitica#3542] opened 2014-05-28 21:36 UTC
I've found that Brutal Smash does not have many of the problems that Burst of Flames has.

I suggest making Burst of Flames work much like Brutal Smash, which does 20% of your STR as damage. However, due to mages having higher MP, I think it would be more appropriate to make Burst of Flames do 10 or 15% of the users INT as damage.

Thoughts?

**Comment by thepeopleseason** [comment] 2014-05-28 21:46
:+1:

**Comment by SabreCat** [comment] 2014-05-29 01:30
Agreed!

**Comment by rcichy** [comment] 2014-05-29 06:35
:+1: Bosses are too easy for mages.

**Comment by thepeopleseason** [comment] 2014-05-29 12:46
This might be opening a bigger can of worms than we'd want to deal with with this ticket, but I think it would be more flavorful in RPGs if: 
- Brutal Smash were stronger for Warriors.
- Burst of Flames were weaker (as suggested) for Mages. 
- Any Critical Hit were to grant some degree of Boss damage.

Since Healers don't offer much beyond the normal daily/to-do checks to boss damage, perhaps casting blessing during a boss quest should grant some measure of XP.

Any thoughts?

**Comment by SabreCat** [comment] 2014-05-30 00:01
I've been thinking of adding a bit of boss damage to the underused Searing Brightness.

**Comment by deilann** [comment] 2014-05-30 00:18
I thought Searing Brightness already did damage... Whoops!

**Comment by wc8** [comment] 2014-06-06 13:47
:+1: reduced Boss Damage from  Burst of Flames
:+1: Brutal Smash were stronger for Warriors.
:+1: Any Critical Hit granting some degree of Boss damage. 
:+1: healers getting a way to do boss damage (searing brightness?)

I've been using Burst of Flames to keep my tasks colored more by their urgency, so I'll cast it on any red task that I don't expect to do soon. The downside is that I get whopping XP for nothing but recoloring my task list and I whomp any boss I'm battling. It's a bit too easy. I have a workaround for the XP, but no way to undo the boss damage.

**Comment by rcichy** [comment] 2014-06-07 07:56
> :+1: healers getting a way to do boss damage (searing brightness?)

If healers have a way to do boss damage, rogues should do some boss dmg. too, right?

**Comment by deilann** [comment] 2014-06-07 08:01
idk -- rogues have STR as their secondary stat and they are built for
collection quests. Do they need a 1 up on boss quests too? Otherwise, we
should do something to even out collection quests for everyone.

**Comment by robeden** [comment] 2014-07-08 14:56
I assume this is the right place to post this:

![damage](https://cloud.githubusercontent.com/assets/1891321/3511454/d1477904-06af-11e4-9b10-2291b7102901.png)

I saw from https://github.com/HabitRPG/habitrpg/issues/2150 that a temporary fix was made, but it doesn't seem to help for our ridiculous mage. (Came darn close to one-shotting Vice.)

**Comment by deilann** [comment] 2014-07-08 15:22
If the amount of damage your mage is doing upsets you, I'd suggest talking
to them. Unless they are extraordinarily high level and have extremely blue
tasks, that much damage would have to be from many, many casts of BoF.

**Comment by gauauu** [comment] 2014-07-08 17:43
Yes, it was many many casts of BoF.  27 I believe.

It sounds like you're saying "yes, it's overpowered, so just ask your mage not to try very hard."  That's a reasonable short-term solution, but wouldn't a balance fix be better? 

Something as simple as having the spell do decreasing damage each time it is cast per day would do a good job of making it worthwhile for a mage to save mana for a boss fight, but prevent the spell from being overwhelming.

**Comment by thepeopleseason** [comment] 2014-07-08 17:51
The existence of this ticket is testament that the balance fix is in the cards. That this card has existed since May 28 suggests that the solution is not "as simple as" things we've previously considered, especially in code.

**Comment by deilann** [comment] 2014-07-08 20:00
Actually, even if it is balanced, casting a skill 27 times is still likely
to cause buku damage. I'm a warrior, and we consider Brutal Smash to be
pretty well balanced. If I cast it 27 times, though, I would one-shot Vice
from the Brutal Smash damage alone.

I'm not saying that your mage should not try very hard. But I am saying
that spending 270 MP in one day is not a normal event. Spending that much
MP should deal ridiculous amounts of damage -- after all, it's more than
most players' max MP! At some point, casting a skill enough times is going
to one-shot Vice, no matter how well balanced the skill is. I mean, we
could add in penalties for multiple casts, but that takes the fun out of it
for players who enjoy that if they get a whole bunch of To-Dos done, they
can deal high amounts of skill damage.

Also, casting Burst of Flames is a voluntary action. They could have spent
that MP on say, Earthquake, buffing the entire party. There's nothing
inherently "try hard" about casting Burst of Flames. The effort put into
the tasks that got them the MP can be spent in productive ways that better
suits your party. If I told you that your mage should have fewer tasks or
reward themselves less, that would be saying not to try so hard. But
self-limiting the number of boss damaging skills they use? Not the same
thing.

**Comment by robeden** [comment] 2014-07-08 20:02
A typical RPG solution to that problem is cooldowns. Have you thought about limiting how often those types of spells can be cast?

**Comment by deilann** [comment] 2014-07-08 20:05
That would damage the enjoyability of the game for many players and parties.

People do have self-control and empathy. They have the ability not to cast
a spell 27 times, if they know their party will be sad. It is not necessary
to cast a spell 27 times. If a party member is repeatedly ruining the
enjoyment of Habit, that party has the ability to remove said member.

Habit very specifically does not change the game in ways that break it for
players who are using it in a legitimate way. People who enjoy one-shotting
bosses are using the game in a legitimate way. People who do not want to
one-shot bosses have the ability to not do so.\

A cool down would be very uncool.

**Comment by robeden** [comment] 2014-07-08 20:06
Ok. "Working as intended."

**Comment by deilann** [comment] 2014-07-08 20:12
Kind of. The amount of damage Burst of Flames does is likely to be reduced
as per my suggestions in this thread. The issue revolves around Task Value
not being capped and Burst of Flames dealing damage based on Task Value.

But Habit is very unlikely to ever limit the way people can use spells
because there is no One True Way of Habit that Habit is going to enforce on
people. That's why you can click a Habit until you turn blue in the face
and you can grant yourself 16 billion gold and infinite XP with Fix
Character Values.

There are people who really enjoy being able to take out a boss in one day
and there are people who refuse to use skills at all when fighting a boss
because they feel it devalues the experience. Most people are somewhere in
between. The secret is to find a party that shares your values. Otherwise,
you're going to all feel unhappy.

**Comment by lemoness** [comment] 2014-09-09 19:10
I've been playing as a warrior after Rebirth, and I really like the way that Brutal Smash is handling boss damage. I feel strong without decimating every boss in two seconds. I'd also really like to see Burst of Flames function like Brutal Smash - maybe you damage the boss by an amount equal to 20% of your intelligence (the exact parallel)? Or we could raise both Burst of Flames and Brutal Smash to 30%?

**Comment by deilann** [comment] 2014-09-10 01:44
Actually the idea would be to do less than brutal smash for burst of flames
because mages have more mana

**Comment by lemoness** [comment] 2014-09-10 03:13
Good call! So maybe 20% of intelligence for mages, and 35% of strength for
warriors?

**Comment by deilann** [comment] 2014-09-10 03:33
35% of StR would end up being way too heavy handed for high level warriors.
I say keep the.boss damage of.brutal smash the same.

**Comment by lemoness** [comment] 2014-09-10 05:43
Then how low to go for Mages in comparison? 15%? 10%?

**Comment by deilann** [comment] 2014-09-10 17:24
I was thinking 10%. Mages tend to have more than twice as much mana and
gain it.back faster.

**Comment by lemoness** [comment] 2014-09-10 19:27
That'll be a shock to the system for mages when it first goes through, but
I agree. I could frequently cast Burst of Flames over ten times a day at my
peak.

**Comment by deilann** [comment] 2014-09-10 19:33
Agreed... it will be quite a shock indeed.

**Comment by lemoness** [comment] 2014-09-10 19:47
Better start preparing my gentle announcement now ;p

**Comment by Alys** [comment] 2015-05-01 08:47
Fixed by https://github.com/HabitRPG/habitrpg/issues/3029 which is going live soon.

**Closed as completed by Alys** 2015-05-01 08:47 UTC
Labels: status: issue: suggestion-discussion, priority: minor
