### ISSUE TITLE
Leaving group button bug : pressing leave multiple times causes multiple confirm/cancel popups

### ISSUE THREAD

**Issue by lalx** [HabitRPG/habitica#6758] opened 2016-02-23 11:18 UTC
i miss-click on "leave group" button, so i clicked to cancel it, but the message dont dessapeared, and appaear another message ahead (sorry for bad english)

Group ID: 50f8c890-5959-41e2-a35d-6111474a72a2
Lalx ID: a0ade8da-16dc-41a1-8521-742d5b6098c8
TheLalx ID: 6be384fc-f6af-4f07-ab7e-eb572c16d565

browser: google chrome
operating system: windows 8

![bug habitica](https://cloud.githubusercontent.com/assets/17428451/13249813/3b9f3236-da05-11e5-93b4-538c4b955abe.png)

**Comment by Alys** [comment] 2016-02-24 06:30
I haven't been able to replicate this, although I'm using Chrome on Mac OS, not Windows.

@lalx Does the problem still happen if you try to do it again? If so, does reloading the page make the problem stop?

**Comment by crookedneighbor** [comment] 2016-02-24 13:43
I was able to reproduce this bug by pressing the "leave" button multiple times without choosing confirm or cancel.

**Comment by Alys** [comment] 2016-02-24 23:12
It must be browser-specific. That still doesn't happen in Chrome on Mac - I can see the popup flicker briefly as the old one is closed and the new one open to replace it.

I would guess that this happens in other buttons around the site, so it would be great to have a fix for this that was applied site-wide.

@lalx When you tried to click cancel, is it possible that you misclicked again on the leave button? Maybe there's a problem with your mouse that causes misclicks like that?

**Comment by lalx** [comment] 2016-02-29 13:42
yes, it happens again and again, every time i reload the page 

when i click Sair(Leave), appaears the correct popup with the message "Deixar Equipe"("leave team") and its ok there
but sometimes appaears the popup without the message, and the bug occurs when that happens

![bug habitica2](https://cloud.githubusercontent.com/assets/17428451/13396015/fd16e1e6-ded0-11e5-9234-765924504d00.png)

**Comment by lalx** [comment] 2016-02-29 13:55
![bug habitica3](https://cloud.githubusercontent.com/assets/17428451/13396360/e31748c4-ded2-11e5-9b5b-37b9bb64c67f.png)

**Comment by lalx** [comment] 2016-02-29 14:05
![bug habitica4](https://cloud.githubusercontent.com/assets/17428451/13396602/4fd39246-ded4-11e5-8d47-b19fbdeaddc9.png)

**Comment by lalx** [comment] 2016-02-29 14:08
i think there is 2 button with 2 different popups with the same function, and when i click on both, occurs a bug.
It's not my mouse cause i try it in 5 different computers and mouses of my college and the bug still happens;

![bug habitica5](https://cloud.githubusercontent.com/assets/17428451/13396691/c8d3f3f2-ded4-11e5-83e1-40a8e2dd9115.png)

starting with ICON CLICK
![bug habitica resumo1](https://cloud.githubusercontent.com/assets/17428451/13397560/46ecc454-ded9-11e5-92f0-950811314dc8.png)

starting with SAIR(LEAVE) CLICK
![bug habitica resumo2](https://cloud.githubusercontent.com/assets/17428451/13397579/5cb33af2-ded9-11e5-911a-9584acdc8c68.png)

**Comment by lalx** [comment] 2016-02-29 16:13
after click on the button icon and appaears the wrong popup,
every time i click on Sair(Leave), cancel it and click in the cancel of the wrong popup, appaears another wrong popup

![bug habitica 6](https://cloud.githubusercontent.com/assets/17428451/13400256/b21a76a2-dee5-11e5-8af0-19ea893e7b40.png)

**Comment by Alys** [comment] 2016-03-01 05:06
@lalx Thank you very much for all the details! I've been able to reproduce this by doing what you've described, so it's not browser-specific (also backed up by you testing on so many machines - thank you!). It doesn't happen all the time for me though. 

I don't think there's two buttons with two popups, instead I think the code that creates the button and popup misbehaves under some circumstances. It might take us a while to work out why and how to stop it.

If you ever find that you can't leave a party or guild because of this, just tell us and we'll adjust the group's membership records to remove you.

**Comment by lalx** [comment] 2016-03-01 14:46
no problem, its good to help you guys to fix some problem, thank you for your attention!

**Comment by ltorroba** [comment] 2016-03-02 17:03
I did some digging on the root cause of the issue and I believe it was caused by a problem with the _clickLeave_ function. To be specific, seems like when the user clicked on the _a_ element, the event behaves normally and the leave popup appears, but when the user clicks on the glyphicon _span_ element, the event _clickLeave_ that triggers the popup, sets the target to the _span_ element. This in turn causes the popup to spawn within the button, instead of outside it.

I've tested this on both Safari and Chrome, running under Mac OS X.

Safari @ Mac OS - DOM tree when clicking glyphicon:
![](http://i.imgur.com/FGU0PTH.png)

Safari @ Mac OS - DOM tree when clicking button text:
![](http://i.imgur.com/FR2RzLi.png)

Chrome @ Mac OS - DOM tree when clicking glyphicon:
![](http://i.imgur.com/KqNqNLh.png)

Chrome @ Mac OS - DOM tree when clicking button text:
![](http://i.imgur.com/lE8Ehwq.png)

Coincidentally this incorrect insertion of the popup in the DOM tree causes the two popups to have differing appearance, as the one inside the a element inherits _color_ and _font-size_.

**THE FIX:** I found the fix to be quite simple and I'll be submitting it as a PR quite soon. Not sure if it's the nicest though, to be frank.

```
if ($scope.popoverEl[0].localName == "span") {
  $scope.popoverEl = $($scope.popoverEl[0].parentNode);
}
```

Would this be suitable? This is my first time contributing to HabitRPG and I haven't got much experience with JS development, so please let me know if there's a better way around it!

**Comment by Alys** [comment] 2016-03-06 10:31
Fixed in https://github.com/HabitRPG/habitrpg/issues/6819

**Closed as completed by Alys** 2016-03-06 10:31 UTC
Labels: priority: minor, help wanted

**Comment by lalx** [comment] 2016-03-07 12:37
![image](https://cloud.githubusercontent.com/assets/17428451/13569676/2f3ac058-e448-11e5-9a86-4ad7aef4af50.png)

**Comment by crookedneighbor** [comment] 2016-03-07 13:31
It's been fixed in the repository, but it hasn't been deployed to the production site yet.
