### ISSUE TITLE
All habits & dailies & tasks that weren't created today disappeared.

### ISSUE THREAD

**Issue by deertheory** [HabitRPG/habitica#3047] opened 2014-03-10 19:46 UTC
I was off of habitrpg for a few days or a week or so, I can't be sure, and just hopped back on. All of my stuff was there. I started going through my dailies today & one of my dailies is to go through my e-mails. I started making new tasks based on my e-mails by clicking tags and typing new tasks. After I finished checking my e-mail, I unclicked all tags so I could check off going through my e-mail in my daily.
None of my habits or dailies popped back up. Any tasks from before going through my e-mails are also gone. I have no tags clicked, or at least none appear to be clicked. I've toggled through them in the event maybe tags were clicked but they weren't blue. No bueno.
My username is hiver and my userID is 166219e2-7f70-46cf-869a-cd4990093482
Help! :( I don't remember all of my habits/dailies, that's why I rely on habitrpg! It took a long time to build up what I had in acknowledgement of what I need to do.

**Comment by deertheory** [comment] 2014-03-10 20:27
As a follow-up, all of the habits/dailies/old tasks show up when I use beta.habitrpg.com

**Comment by deilann** [comment] 2014-03-10 20:29
That sounds like you do have a tag selected. What happens if you hit the x
at the end of your tag list?

**Comment by deertheory** [comment] 2014-03-10 20:32
That worked! I feel embarrassed! I guess the actual bug was that none of my tags were visibly highlighted but at least one of them had to have been on.

**Comment by Placewn** [comment] 2014-03-29 18:02
I had the same problem, thank you @deilann for responding, I had no clue that I should have clicked the x at the end of the tag list! Much appreciated!

**Comment by deilann** [comment] 2014-03-29 21:57
Yeah, I think this is a serious UX issue. Gotta do something about it hmm.

**Comment by paglias** [comment] 2014-03-29 22:24
@deilann what about changing the `x` to `Clear tags` and showing it only when a tag is selected?

**Comment by deilann** [comment] 2014-03-29 22:24
I like that.

**Comment by wc8** [comment] 2014-03-30 01:12
This came up in a guild and there was a similar suggestion, but the suggestion was to place the text in each column. 
Possible alternate phrases, _Show All Items_, _Clear Tags_, or even a count of hidden items, e.g. 6 Hidden Dailies, 2 Hidden Todos. 
Clicking that text would have the same effect as the current :x: tag button now.

**Comment by paglias** [comment] 2014-03-30 09:55
@wc8 tags are global, I would find it a bit confusing if there was a clear tags button over each list

**Comment by deilann** [comment] 2014-03-30 10:02
Agreed... having them over each list would be very odd to me. It would imply that the tags only were filtering that list. However, a list of the filtered items being hidden seems fab.

**Comment by lefnire** [comment] 2014-03-30 16:15
See more convo at https://github.com/HabitRPG/habitrpg/issues/3083

@snicker:

> would you be more apt to leave it in if we added a demonstration for clearing tags in the tour? Personally, I think that that tiny update to make tags persistent improves my personal user experience a TON and I have heard similar sentiments from others as well. It seems that a few outliers that don't seem to pay attention are the ones that have problems.
> 
> Tag filters should probably be cleared on log in/out though, as I'm sure that is the first things most users will try in order to fix the problem (not clicking the clear filters button)
> 
> (a more obvious clear filters button might also, perhaps one that changes color when filters are active)

So it sounds like people are ok with this staying in, as long as it's very clear what's going on? Until we get some in-app clarity, I'm probably going to revert https://github.com/HabitRPG/habitrpg-shared/commit/aa0c69e to cut back on all the support requests. Feel free to un-revert with a UX update

**Comment by deilann** [comment] 2014-03-30 18:11
tut+bailey imo when reimplemented

**Comment by deertheory** [comment] 2014-03-31 03:26
i think that having a tag button over each list might be nice, i often want
all of my dailies to be showing but only some of my tasks when i hit a
filter.

**Comment by deilann** [comment] 2014-03-31 03:27
That would only be nice, deertheory... if that's what it did. ;)

**Comment by deertheory** [comment] 2014-03-31 03:31
haha you're right, i'm projecting one kind of feature onto another.

**Comment by snicker** [comment] 2014-03-31 20:05
Fine by me, I think that some other suggestions were a small footer at the bottom "(...and X other hidden tasks)" to draw attention to it

I hadn't thought of the mobile implications though.

**Comment by Alys** [comment] 2014-09-02 20:37
Original problem is a duplicate of https://github.com/HabitRPG/habitrpg/issues/2370 and fix is proposed: https://github.com/HabitRPG/habitrpg/pull/3970

The UI issues seem to be either resolved or discussed elsewhere as well, so I'm closing this.

**Closed as completed by Alys** 2014-09-02 20:37 UTC
