### ISSUE TITLE
Usernames with underscores on each side aren't displayed correctly

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#12033] opened 2020-03-31 10:16 UTC
If a player has a Username that starts and ends with an underscore (e.g., `@_spider_`), when their Username is mentioned in a chat post, there are three formatting problems:

- the name is in italics (that's kind of expected because underscores indicate italics in markdown but markdown parsing within a Username is not desired) 
- the underscores are not visible (a side-effect of the previous point but this is undesirable because you're not seeing the player's proper Username)
- the text colour of Username is wrong (screenshot below)

The screenshot below was taken from a post that contained this raw text:
`@_spider_ and @blackgoblingo`
Both of those Usernames were in use at the time I made the post (the `_spider_` user has a different name now).
The formatting for the `blackgoblingo` user is correct.
The formatting for the `_spider_` user is wrong.

Both usernames do correctly point to the right profile screens, so that's something. :)

The expected behaviour is that you see `@_spider_` and that it's formatted in the same way as the `blackgoblingo` username.

![image](https://user-images.githubusercontent.com/1495809/78014862-df2ae480-738b-11ea-9875-65fb7593210f.png)

_Thanks to @EliotThe (0d77107e-9128-4656-8c02-6e06331fa396) for reporting this!_

**Comment by kareenf** [comment] 2020-03-31 17:10
I might be interested in doing this! Is that alright?

**Comment by Alys** [comment] 2020-04-01 00:24
@kareenf That would be great, thank you! Post here if you have questions.

**Comment by kareenf** [comment] 2020-04-06 22:10
Hey! So I have been digging through the code and I think I've figured out where the issue is. It seems as though the parseMarkdown/habiticaMarkdown.render function used in chatCard.vue is where the issue of italicizing is occurring. However I can not figure out how to access (/I'm not even sure if I have access to) that render function to possibly add in some checks. 

My understanding is that parseMarkdown is called which turns a username such as `@_spider_` into `@_spider_`which is then sent to the highlightUsers function which is where the proper text formatting should be but the `<em></em>` throws it off somehow because instead of looking for `@_spider_,` it looks for `@spider` (in mentionString/fullMatched) during the RegEx string matching. 

If it's not possible to access the Markdown parser, I could perhaps add in some checks into the highlightUsers function. If I can somehow intercept the username coming in (via mentionString?) and check if there are emphasis tags, I could replace them with underscores however I am having a bit of troubles understanding how the code in highlightUsers is working. Or perhaps intercept the text before it goes into the parser? I'm not sure which would be better/easier/doable.

If anyone has any thoughts or guidance, I would be very happy to hear it! 

Thanks :)

**Comment by benkelaar** [comment] 2020-04-07 23:48
Wouldn't it be enough to simply change the order of atHighlight and parseMarkdown? 

Probably not, the user highlighting will then work, but markdown will probably still turn the underscores into em tags.

I think perhaps for now the easiest solution is to escape the underscores before the text gets send to markdown (chatCard.vue#37 and messageCard.vue#24). However this should not be done if the @mention is in a code block, otherwise you'll end up with the escape characters in your code block. I'm actually working on detecting code blocks in this issue so perhaps we can do something similar here: https://github.com/HabitRPG/habitica/issues/11504

**Comment by kareenf** [comment] 2020-04-08 22:04
So I was trying to work on a possible solution by matching em tags in the mentionStr and replacing them with underscores. However, I have run into an ESLint problem that says no-param-reassign when trying to reassign mentionStr. I see that there is a disable eslint comment for that exact thing in the text = text.replace() line however it seems like it is causing me troubles regardless. Are there any solutions?

P.S. I think I will definitely fix the issue with this solution but this ESLint error is getting in the way :(

**Comment by kareenf** [comment] 2020-04-08 23:13
Also, I just found this out but, apparently Markdown recognizes `__something__` as bolding (strong tag) the word. Should I take care of that as well (granted, I can figure out this darn ESLint issue)? Would it be a possibility that someone would make a username that has a double underscore sandwich?

**Comment by benkelaar** [comment] 2020-04-09 05:09
> So I was trying to work on a possible solution by matching em tags in the mentionStr and replacing them with underscores. However, I have run into an ESLint problem that says no-param-reassign when trying to reassign mentionStr. I see that there is a disable eslint comment for that exact thing in the text = text.replace() line however it seems like it is causing me troubles regardless. Are there any solutions?

So we're talking about this piece of code right? https://github.com/HabitRPG/habitica/blob/9d16ab7dba6650bd40e82dc134a00fbc2b685a8d/website/client/src/libs/highlightUsers.js#L12-L20

**Where does mentionStr come from?**
What is happening here is that the version of string.prototype.replace that passes a regex and a function is being used (As documented here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace#Specifying_a_function_as_a_parameter ). The arguments to the passed in function are the full regular expression match, followed by each individual capturing group from the regular expression in order (You can read more about capturing groups in regular expressions here: https://www.regular-expressions.info/brackets.html -> in a nutshell, capturing groups are the parts in regular expressions between brackets).

So the value that ends up in mentionStr (The third parameter of the arrow function expression passed in as second parameter to text.replace call on line 12) comes from the second capturing group of the regular expression passed in as first parameter to that same text.replace call.

This regular expression is `finalMentionRegEx`, which is dynamically built up in line 7. If you put it all together that regular expression boils down to `(<\\w[^>]*)?(@[\\w-]+)(\\.\\w+)?`. To illustrate the behaviour of this regular expression I've put it in regex101 here: https://regex101.com/r/cLDqbQ/3

As you can see `mentionStr` is the `@user` reference, with `preMention` and `postMention` only filled in scenarios that indicate the mentionStr is actually not a user reference but either part of a link or likely part of an e-mail address.

**What's up with the no-param-reassign linting issue?**
This is a common linting setting in languages because your function parameters are the "input" part of your function. If you reassign the values of your parameters in the function body you make it harder to reason about your function as a whole since you can no longer assume that what came in was actually what the consumer expected.

You can disable this warning as is done in line 12, but a better solution would be to introduce a new variable instead. So instead of 
```jacascript
mentionStr = mentionStr.replace(regex, replacement); // eslint-disable-line no-param-reassign
``` 
you do 
```jacascript
const fixedStr = mentionStr.replace(regex, replacement);
``` 
and then in the following lines you use fixedStr instead of mentionStr. That keeps your local state neatly separated from your external state and also makes your code more descriptive. Double win!

**However, it won't work**
As shown in regex101, the mentionStr capturing group only matches @ characters followed by word characters or dashes. Since <> are not in that selection `@<em>spider</em>` will never be in the mentionStr. I recommend writing some unit tests to figure this out.

OK, lots of information, hope it helps.

**Comment by Alys** [comment] 2020-04-09 08:42
> Also, I just found this out but, apparently Markdown recognizes __something__ as bolding (strong tag) the word. Should I take care of that as well (granted, I can figure out this darn ESLint issue)? Would it be a possibility that someone would make a username that has a double underscore sandwich?

@kareenf Good catch! Yes, that's worth also taking care of.

@kareenf @benkelaar Thanks so much to both of you for all the investigation you're doing!

**Comment by paglias** [comment] 2020-04-09 08:52
Regarding the ESLint error you should be able to disable the rule for one line with a comment links this ```
// eslint-disable-line no-param-reassign
```

But if it doesn't work don't worry, push the PR and we'll fix it later

**Comment by kareenf** [comment] 2020-04-09 17:37
@benkelaar Thank you so much for all of information! I had gotten the gist of what mentionStr was but I wanted to confirm so that was very helpful! 

@Alys I'll give the em tag issue a fix first and then take care of the strong tag once I'm confident the other works!

@paglias Awesome! Just to expand my understanding, does the disable line only work for the line it's on and not for the whole function? I was doing some research that led me to believe that that disable would have carried through in that replace function however I must be mistaken.

Edit: OMG! I think I've fixed the issue! I'll run it through the test suite and probably add some new tests in and hopefully submit a PR very soon :)

**Comment by benkelaar** [comment] 2020-04-09 18:01
@kareenf I did some more research just now and I think the best way to resolve this is to create a markdown-it plugin and embed that into the https://github.com/HabitRPG/habitica-markdown library. 

The documentation to do this properly can be found here: https://github.com/markdown-it/markdown-it/tree/master/docs

Do you want to do this? Or perhaps we can do it together? Perhaps we could discuss it in a (video)? call today or tomorrow?

**Comment by kareenf** [comment] 2020-04-09 22:07
@benkelaar Yeah I'd love to work on that together! I'll still submit a PR for this just as a band-aid for now and for the experience (I'm doing this for one of my classes so I need proof of a PR :) ).

**Comment by kareenf** [comment] 2020-04-09 22:10
I'm trying to add a test to POST-chat.test.js now and I was wondering if anyone had any pointers for understanding the test structure and adding a test? I'm a bit lost as to how to set up the test in a similar way as the others in the file while making sure that the mentions being tested is a username sandwiched with underscores (since it seems as though most of the tests aren't using hard-coded usernames). Is there a way to create another member object outside or inside of the createAndPopulateGroup mocker?

**Comment by benkelaar** [comment] 2020-04-10 06:11
> I'm trying to add a test to POST-chat.test.js now and I was wondering if anyone had any pointers for understanding the test structure and adding a test?

`POST-chat.test.js` are tests of the HTTP backend (server) endpoints which the frontend (or third-party applications) POSTs chat messages to (So basically the storing of chat messages). `highlightUsers` is called in two VueJS components (`messageCard.vue` and `chatCard.vue`) when they are being rendered (So purely when displaying the messages, no interaction with the backend). 

If you want to test `highlightUsers` on a higher level than just the unit test (Which is in `highlightUsers.spec.js`) the best place would be to introduce component tests for those using something like https://vue-test-utils.vuejs.org/api/#shallowmount . 

How this can be done can be seen for example in `notifications.spec.js`. However if this is a band-aid fix it might be enough to just stick to unit test level (There aren't that many component tests in the code base yet, so it would improve the codebase if you did introduce this, but you'll have to judge for yourself how much work you want to spend on this).

**Comment by benkelaar** [comment] 2020-04-10 07:24
> @benkelaar Yeah I'd love to work on that together! I'll still submit a PR for this just as a band-aid for now and for the experience (I'm doing this for one of my classes so I need proof of a PR :) ).

Awesome, what timezone are you in? Perhaps we can do a quick hangout somewhere over the weekend? You can contact me on [twitter](https://twitter.com/BartEnkelaar) or shoot me an e-mail to discuss details.

**Comment by benkelaar** [comment] 2020-04-10 09:19
@kareenf I've invited you as collaborator to my [fork of habitica-markdown](https://github.com/benkelaar/habitica-markdown), where I've also created a [branch](https://github.com/benkelaar/habitica-markdown/tree/habitica-markdown-mention-plugin) and [draft pull-request](https://github.com/HabitRPG/habitica-markdown/pull/87) in which we can discuss work in progress.

**Comment by paglias** [comment] 2020-04-10 11:11
@kareenf regarding how do disable ESLint rules there are a few ways to do it, that go from disabling the rule just for one line, multiple lines or the entire file https://eslint.org/docs/2.13.1/user-guide/configuring#disabling-rules-with-inline-comments 

Usually we prefer to disable lines one by one unless several are affected in which case it's okay to disable multiple ones

----

I was a bit busy these days but I'll give a look at all the other comments / PRs hopefully by monday

**Comment by kareenf** [comment] 2020-04-10 16:37
@benkelaar I'm in EST! I'll send you a quick email as well. I also took a look at the highlightUsers.spec.js file and added a test in there however I'm not sure how to run and see if it passes as it seems to me only files in the test folder get tested using the npm test commands from the wiki. I did run the full test suite and it seems like nothing broke!

**Comment by benkelaar** [comment] 2020-04-10 18:06
The `highlightUsers` function is actually part of the client code, so you'll have to run `npm run test:unit` from the `website/client` folder in order to run the client unit tests. If you then replace `describe` by `describe.only` in `highlightUsers.spec.js` the runner should only run that test.

I haven't looked at the code long enough to see if the client unit tests are also run if you run `npm run test` on the root level.

Edit: Wait, you'll also have to suffix the line by `  // eslint-disable-line mocha/no-exclusive-tests` then otherwise the linter will prevent you from running the test.

**Closed as completed** 2020-04-17 19:45 UTC
Labels: priority: medium, status: issue: in progress, section: Tavern Chat, section: Guilds, section: Messages
