### ISSUE TITLE
Clicking on a challenge from a guild opens the challenges page with all my guilds' challenges displayed at once

### ISSUE THREAD

**Issue by Salstar24** [HabitRPG/habitica#4602] opened 2015-01-31 14:20 UTC
Hi, never reported bugs before so I hope I'm doing this right!

When I click on a challenge from any guild page, it opens the Social -> Challenges page with all my guilds ticked and all their challenges displaying. I can work round this by manually clicking Filter -> Groups to 'None' and then re-clicking just the guild I was interested in to view their challenges. Still, I gather this isn't what's supposed to happen?

I use the Google Chrome browser, version 40.0.2214.93 m.
##

**Comment by gkjt** [comment] 2015-01-31 19:20
I do not think this is browser specific, I am getting it on Firefox 35.0.1 too.

**Comment by crookedneighbor** [comment] 2015-01-31 19:34
The intended behavior is for the screen to scroll down to the open challenge on the challenges page (it doesn't, obviously), but I love the idea of setting the filter to only show challenges for that particular group.

Any devs opposed to that? If so, why?

**Comment by lemoness** [comment] 2015-02-01 20:17
Not opposed - I think that would be a nice touch. Still, would like the
intended scroll to occur as well.

**Comment by Salstar24** [comment] 2015-02-03 12:10
Just wanted to report that the scroll thing did work once for me, the very first time I had tried it that day, but then it stopped working. Maybe it's particular guilds that don't trigger the scrolling? :/

(PS Just wanted to say that I'm super-impressed by the quick response and in general the commitment to responding across the website to newbies like me. :+1: )

**Comment by TheHollidayInn** [comment] 2015-03-12 04:49
Is this ticket a duplicate of https://github.com/HabitRPG/habitrpg/issues/1797 ?

**Comment by deilann** [comment] 2015-03-12 09:41
No. #1797 is about making sure when you click on a link to a challenge you
don't have to scroll to see it. This ticket is about when you click on a
link to a group challenge from a group, the filters should show only
challenges from that group.

**Comment by TheHollidayInn** [comment] 2015-03-12 17:59
Ah, well it seemed similar because of what @crookedneighbor said the intended behavior is.

**Comment by Alys** [comment] 2015-04-05 13:13
Fixed by @TheHollidayInn in https://github.com/HabitRPG/habitrpg/pull/4861 which should appear on the HabitRPG website in a couple of days.

Thanks for suggesting this @Salstar24! I've tested the fix and it really is quite lovely to see the filtered view of challenges.

**Comment by Alys** [comment] 2015-04-06 07:50
We actually had to revert #4861 because it was causing an automated test to fail for reasons still unknown. However I think it has now been superseded by https://github.com/HabitRPG/habitrpg/pull/3319 / https://github.com/HabitRPG/habitrpg/pull/4934 which shows only the challenge you've clicked on. That's not exactly what this issue was asking for (seeing all challenges for one guild at once), but you'll still be able to see them all from the list in the guild's page.

https://github.com/HabitRPG/habitrpg/pull/3319 / https://github.com/HabitRPG/habitrpg/pull/4934 will probably go live in a couple of days, along with a lot of other challenge changes, so after that we'll see if this issue needs more work.

**Comment by Alys** [comment] 2015-04-12 01:10
#3319 / #4934 has gone live. The current state is that when you click on a challenge, you see only that challenge. You can then click on the name of the guild in the challenge header to go back to the guild to see the other challenges. 

But we should probably have an 'all challenges' link on the guild page that takes you to the challenges page with the guild already pre-selected so that you see only the guild's challenges.

**Closed as completed** 2015-11-26 18:35 UTC
Labels: priority: minor, section: Challenges, status: issue: on hold
