### ISSUE TITLE
Random level and gold increase

### ISSUE THREAD

**Issue by knifey-spooney** [HabitRPG/habitica#5323] opened 2015-06-01 02:58 UTC
My level went from 92 or 93 to 110 seemingly overnight with no input from me, and my gold increased from about 1500 to over 9000 even though I did no tasks. Also, some of my habits are marked as completed for the day even though I didn't do them yet today.
I'm using Firefox and Windows 7, and my id is 1568645d-fce8-41ca-874c-009acfc796ed
##

**Comment by Alys** [comment] 2015-06-01 03:13
Can you confirm that you use only the habitrpg.com website and never any mobile apps?

Do you use any third-party tools at all? Any extensions or scripts or anything that might use the API? Have you ever installed anything related to HabitRPG?

I've noticed that in your quest that just finished, you did 1695.2 damage at once. Was there anything you did to cause that deliberately (it's fine if there was! We just need to know), or would it have been caused by the same thing that caused you to level up multiple times?

Were you a Rogue yesterday as you are today, or did you change classes very recently?

Did you notice anything at all either yesterday or today that seemed out of the ordinary, apart from the multiple levels and gold? Even if it doesn't seem related?

When you say your Habits are marked as completed, are you referring to Habits that had changed colour away from yellow, or do you mean Dailies or To-Dos? 

How many Dailies were marked completed inappropriately? Where ALL of those ones marked as completed YESTERDAY by you? 

How many Dailies were NOT marked completed inappropriately?

**Comment by hairlessbear** [comment] 2015-06-01 03:16
To add on the the questions @Alys asked: is there any chance you left your account logged in on a device that others access (e.g., a public computer)?

**Comment by Alys** [comment] 2015-06-01 03:24
And also did you have the website open in multiple tabs overnight?

**Comment by knifey-spooney** [comment] 2015-06-01 05:04
I've used the mobile app once or twice but mainly use only the regular computer version of habitrpg. I didn't do anything specific with the quest, but I did notice last night that I had trouble reaching the server so I just assumed something was down and didn't use the site last night.
I don't use any thirdparty tools and I've always been rogue class, and didn't have the site open last night at all or anything logged on. 
I accidentally said habits, sorry, I meant dailies. 5 were marked as completed and I hadn't marked them myself, and they stayed marked as completed even after refreshing the page.

**Comment by Alys** [comment] 2015-06-01 05:38
Sorry, I need to be certain of one thing: For those five Dailies that were marked as completed today, I understand that you didn't mark them as completed today (and so they should not have been appearing as completed). 

However had you yourself marked all or some of those fives Dailies as completed **yesterday**?

**Comment by knifey-spooney** [comment] 2015-06-01 08:28
Yes I'd marked them completed yesterday, sorry if I'm not being clear enough on stuff.

**Comment by Alys** [comment] 2015-06-01 10:40
No, that's okay! It's a complex situation. To be honest, I'm not at all sure what was going on. We'll have to keep this open and think about it.

If you'd like to set your values back to what they were, you can go to Settings -> Site and click on the Fix Character Values button.

**Comment by knifey-spooney** [comment] 2015-06-01 11:52
Thanks for helping, I hope this is just a weird one-off thing that doesn't happen again!

**Comment by charlesvtiu** [comment] 2015-06-05 11:54
Is there a database table that records every post someone does when they check off a daily? Would be good to see if there are multiple records that just keep firing for this person to isolate the issue.

**Comment by hairlessbear** [comment] 2015-06-17 21:53
A user in the Tavern (UID: a4023a49-60f9-43e0-8d6b-e95fb14fd76b) posted something that sounds very similar to this bug.

_How do I edit my stats and whatnot again? Something seems to have happened overnight, and some of my dailies are already checked, and I'm 5 levels up from where I should be, and I've lost all but 19 of my gold. How do I fix it again? I seem to be lost... :-P_

In response to some questions from the socialites, the user added:

_No one else uses my computer, so I don't think that's it...also, the quest I'm currently on seems to be working fine, as I'm only about halfway through it. I had 900 some GP last night I remember, though I do remember some of my spells not seeming to work yesterday either (ex. casting one worth 25 MP would use the MP but display "Not enough Mana"), so I'm not completely sure what happened. But I know for a fact no one else is using my account._

**Comment by paglias** [comment] 2016-06-01 09:29
Should be fixed, reopen if it happens again

**Closed as completed by paglias** 2016-06-01 09:29 UTC
