### ISSUE TITLE
Using multiple clients causes HabitRPG to glitch

### ISSUE THREAD

**Issue by serendependy** [HabitRPG/habitica#966] opened 2013-05-14 20:27 UTC
I use HabitRPG on multiple computers and a tablet (unofficial andriod app). Whenever I close my browser but forget to log off on one session, all progress I make with other clients is wiped whenever I load the webpage again. It appears to be sending the old data again and overriding the existing data, undoing checked dailies and then causing damage from them. It does not effect pets, gems, eggs, potions, etc, just habits, health, gold, xp.

**Comment by motoyugota** [comment] 2013-05-14 20:47
I've seen this issue many times as well. It will sometimes completely freak out when you reload one of the instances.

**Comment by nrstarr** [comment] 2013-05-15 19:11
Ran into something like this today. Been using my iPhone for a few days because I've been without my laptop, and changes have persisted across multiple days, new sessions, etc. When I opened it up on my laptop today, none of that progress showed up. Health/XP changes not represented, dailies unchecked, todos I'd added not there, all sorts of stuff missing.

EDIT: went to beta.habitrpg.com on my computer and it was fine, then vanilla habitrpg worked again.

**Comment by lefnire** [comment] 2013-05-19 13:01
ongoing issue, duplicate of #635 - let's follow up there. I wonder if Racer's Operational Transformation between the two clients is not working correctly...

**Closed as completed by lefnire** 2013-05-19 13:01 UTC

**Comment by switz** [comment] 2013-05-19 17:54
We don't use racer's OT...

**Comment by lefnire** [comment] 2013-05-19 18:37
why wouldn't we be? Every `model.*()` is a versioned transaction, which Racer uses to perform sequential data operations. I mean, it's not doing complex conflict resolution, which the rewrite handles, but I don't see how we're not using OT?

**Comment by switz** [comment] 2013-05-19 18:57
Racer doesn't use OT by default. Go to derbyjs.com and search "OT methods"

**Comment by switz** [comment] 2013-05-19 18:57
I should note that Racer 0.5 will use OT by default (once sharejs is integrated), but we're not there yet.

**Comment by lefnire** [comment] 2013-05-19 19:13
Ow wow, I had no clue! In that case maybe the last-writer-wins implementation is what's causing this issue? Looks like it's a setting one can toggle? (at least the Pad example is using it) - I may play with this when I get home, load it in 2 computers & futz around.

Racer 0.5 can't come soon enough
