### ISSUE TITLE
Custom Day Start causes newly added Dailies to show up gray

### ISSUE THREAD

**Issue by mayajosyula** [HabitRPG/habitica#6649] opened 2016-02-03 09:53 UTC
_A quick note: it's late in my time zone and I'm tired, so I might have not checked carefully enough - if there's already an issue describing this or if this is intended behavior, I apologize in advance!_

When I created a new Daily just now, it was created gray by default. Looking at the advanced options, all the days of the week were selected as usual, it's just that the Daily itself was gray. I deleted it and created it again, and the same thing happened. The start date of the Daily was set to 02/03/2016, which is today's date according to my computer. Setting the start date to 02/02/2016 made the Daily turn back to yellow.

I'm almost 100% sure this has to do with my Custom Day Start time. I've set my CDS time to 4am and it's 2am right now - it's technically February 3 but cron hasn't triggered yet, so Habitica still thinks it's February 2. But since the Daily start date uses the date according to my computer, not according to Habitica, the start date was set to the following day, which would make the Daily gray. 

(I hope that made sense...)

**Comment by Alys** [comment] 2016-02-04 10:18
@agentx999 Your assessment of the problem is correct! We have this issue recorded at https://github.com/HabitRPG/habitrpg/issues/5525 with some suggestions for fixes, so I'm going to close this issue now, however if you have further questions you can comment here. If you'd like to follow the progress of the fix, you can click the subscribe button in the right-hand column of that other issue.

**Closed as completed by Alys** 2016-02-04 10:18 UTC
