### ISSUE TITLE
Question mark icon being rendered in navbar in place of ☰

### ISSUE THREAD

**Issue by ltorroba** [HabitRPG/habitica#7201] opened 2016-05-13 14:34 UTC
General Info
- **UUID**: 8ac1be04-4201-4eed-a2a4-436eada5c0e9
- **Browser**: Google Chrome
- **OS**: OS X
### Description

Yesterday I noticed that the ☰ icons to open up the dropdowns in the navbar were replaced with question mark icons. Much like in Mario. The screenshot below illustrates what I see:

![](http://i.imgur.com/Ww71nwU.png)

Clearing the cache or using Incognito mode on OS X triggers the same behaviour. Using Firefox, the correct icon is shown. Using Chrome on Android also renders the icon properly.

Interestingly, seems like other icons on the page are being rendered as 'GLYPHICONS Halflings' (as seen at the bottom of the _computed styles_ panel of the developer console); however this icon is being rendered as '.LastResort' instead.
#### Console Errors

None.

**Comment by librarianmage** [comment] 2016-05-13 16:06
It may be that the font isn't loading correctly.

**Comment by paglias** [comment] 2016-09-03 13:21
I cannot reproduce, if it happens again I'll reopen

**Comment by ltorroba** [comment] 2016-09-03 13:41
I've actually grown used to it, but it's still there on Chrome. Other browsers work just fine.

A few weeks back the problem briefly went away, but a few days later returned.

**Comment by paglias** [comment] 2016-09-03 14:08
@zesme strange... I'll reopen the issue. That icon isn't actually an image but a unicode character and I cannot see any .LastResort class in my source code. Can you try using an incognito window (or disabling all extensions) and clearing your cache?

**Comment by paglias** [comment] 2016-09-27 14:03
I'm going to close this, comment if you have more info

**Closed as completed by paglias** 2016-09-27 14:03 UTC
Labels: priority: minor, status: issue: needs investigation
