### ISSUE TITLE
No Avatar in Mobile App

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#3030] opened 2014-03-08 04:25 UTC
My avatar is gone in the mobile app - there's just a blank space. This happened after the second-to-last update, but the most recent update didn't fix it.

**Comment by lemoness** [comment] 2014-03-08 04:26
This is on iOS.

**Comment by hametsunosaturn** [comment] 2014-03-08 18:21
I have an avatar but it's covered in pets and looks real crazy. (Also on iOS)

**Comment by deilann** [comment] 2014-03-09 10:51
@hametsunosaturn That's https://github.com/HabitRPG/habitrpg/issues/2510

**Comment by lemoness** [comment] 2014-03-09 20:25
Poking around - its not just the avatar. When I check things off, the gold
and silver images don't show up.

**Comment by Paratron** [comment] 2014-03-10 16:21
Same here - I have not a single image visible in the mobile app, except of the sync arrows on the top right, and the menu dots on the top left corner of the app.

All other images are not shown. I am on an iPhone 4s on IOS 6

**Comment by lemoness** [comment] 2014-03-10 21:31
Hmmmm, I am also IOS 6. Could be related?

**Comment by negue** [comment] 2014-08-25 08:59
It is maybe a dupe of #2543.

@lemoness @Paratron Please Check again if this is working now.

**Comment by lefnire** [comment] 2014-08-25 17:24
Should be fixed as of https://github.com/HabitRPG/habitrpg-shared/commit/ec396344587c6cc8fcbcc8f7ecdf939c53d0d35b. The problem was no support of CSS `background-size` in older Androids & certain iOS. We'll wait to hear back though

**Comment by lemoness** [comment] 2014-08-25 18:38
Yes, this was fixed with a past update for me!

**Closed as completed** 2014-08-25 22:37 UTC
