### ISSUE TITLE
In Social->Challenges on Chrome, Don't see Habits, Dailies, To-Dos, Rewards for Any Selected Challenge

### ISSUE THREAD

**Issue by DwangoMan** [HabitRPG/habitica#4154] opened 2014-10-16 20:14 UTC
User Id: 79030e0e-ba1f-4fce-8857-993bb49ee9a5

System Specs:
Browser: Chrome Version 38.0.2125.101 m
OS: Windows 7 Enterprise Service Pack 1
Memory: 16.0 GB
System Type: 64-bit OS

Summary
When I open a challenge, a series of action boxes (Habits, Dailies, To-Dos, Rewards) appear, similar to my own lists.  They used to populate with the information for that particular challenge, but now they are just empty lists.

Steps to Reproduce:
1. Sign in.
2. Select Challenges from the Social button drop down.
3. Select any challenge.
Expected Result:
The action lists are populated with the expected To-Dos, Habits, and Dailies and the Rewards shows what you will earn from completing these challenges.
Actual Result:
The lists headers and boxes appear, but they are all empty.

**Comment by negue** [comment] 2014-10-16 20:19
First of all, great issue report! :smile: 

Duplicate of #4150 #4151

This will be fixed very soon. :)

**Closed as completed by negue** 2014-10-16 20:19 UTC
