### ISSUE TITLE
Easy Coin Farming?

### ISSUE THREAD

**Issue by samjross** [HabitRPG/habitica#1775] opened 2013-11-09 19:04 UTC
In my Dailies, if I click 'Completed' and then click it again to make it 'uncomplete', and then 'Completed' again, it gives me one silver coin more every time I hit completed than I lose every time I hit uncompleted.

**Comment by Shaners** [comment] 2013-11-10 03:14
Duplicate of #964

**Closed as completed** 2013-11-10 15:58 UTC
