### ISSUE TITLE
Didn't get Find the Cub reward

### ISSUE THREAD

**Issue by Aemilia** [HabitRPG/habitica#4552] opened 2015-01-21 23:00 UTC
Hi,

My party (e5c9f3da-364b-456e-b3ae-fc3ebfd294b3) has just completed the Find the Cub quest, but we haven't received the polar bear pet. I'm afraid I'm not sure if I received the gold and xp - I don't pay that close attention to my levels.

My ID is 12349e1a-219a-4d9b-ae81-23f0ce0c4b73

Thanks,
Emily

**Comment by crookedneighbor** [comment] 2015-01-22 01:35
Here's your party object on your user. Looks like you're still in progress on that quest. 

``` json
"party": {
    "order": "random",
    "quest": {
      "completed": null,
      "key": "evilsanta2",
      "progress": {
        "collect": {
          "branches": 0,
          "tracks": 2
        },
        "down": 0,
        "up": 41.87201032386694
      }
    }
```

Other devs, am I reading that wrong?

@Aemilia would you try [using the data display tool](https://oldgods.net/habitrpg/habitrpg_user_data_display.html?uuid=12349e1a-219a-4d9b-ae81-23f0ce0c4b73) and click the Quest Progress link. I'm curious what it says.

Can you show me a screenshot of the quest completion text on your party page?

**Comment by Alys** [comment] 2015-01-22 01:39
@crookedneighbor You're reading that correctly, although iirc, I've seen cases in the past where a party's quest has finished, but one or more of the participants have not had that recorded correctly in their own user object - so the quest completion screenshot is important to see, as you've said. The DDT will display the same thing as that json data; that's all it reads. :)

**Comment by Aemilia** [comment] 2015-01-22 02:07
Hi, thanks for the swift response.

I've attached a screenshot.

On Thu, Jan 22, 2015 at 12:39 PM, Alice Harris notifications@github.com
wrote:

> @crookedneighbor https://github.com/crookedneighbor You're reading that
> correctly, although iirc, I've seen cases in the past where a party's quest
> has finished, but one or more of the participants have not had that
> recorded correctly in their own user object - so the quest completion
> screenshot is important to see, as you've said. The DDT will display the
> same thing as that json data; that's all it reads. :)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/HabitRPG/habitrpg/issues/4552#issuecomment-70957403.

## 

0415 175 296
emilyderango@gmail.com

**Comment by deilann** [comment] 2015-01-22 02:09
Jsyk you cant attach the screen shot via email or we cant see it... you
have to go to the issue on github and upload the image there.

**Comment by Aemilia** [comment] 2015-01-22 02:10
Ah right! Here tis.

![habitrpg](https://cloud.githubusercontent.com/assets/8978258/5849303/ebaf8b5a-a237-11e4-82e2-387c35104623.png)

**Comment by Alys** [comment] 2015-01-22 02:26
@Aemilia We can get all this fixed up for you within the next six or seven hours, maybe sooner.

Thanks very much for the screenshot. It's confirmed which bug this is, which definitely helps us.

**Comment by Alys** [comment] 2015-01-22 02:27
@Aemilia Also, thanks very much for the screenshot. It's confirmed which bug this is, which definitely helps us.

**Comment by Aemilia** [comment] 2015-01-22 02:30
No worries at all, thanks for your help. :)

I really appreciate how swift and friendly you've been.

On Thu, Jan 22, 2015 at 1:27 PM, Alice Harris notifications@github.com
wrote:

> @Aemilia https://github.com/Aemilia Also, thanks very much for the
> screenshot. It's confirmed which bug this is, which definitely helps us.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/HabitRPG/habitrpg/issues/4552#issuecomment-70961718.

## 

0415 175 296
emilyderango@gmail.com

**Comment by Alys** [comment] 2015-01-22 09:19
@Aemilia Thank you. :)

You should now have the Polar Bear Cub pet and the Achievement for the quest ("Find the Cub"). Could you please check both of those and tell me if they're not right?

I've also removed the outdated quest information from your user object, so you won't have any troubles starting a new quest with your party.

The quest should have given you 100 XP and 20 GP. I have not assigned them to you because if I happened to do that while you were completing tasks or buying rewards, the conflict would produce unreliable results. However you can go to [Settings -> Site](https://habitrpg.com/#/options/settings/settings) -> Fix Character Values to give yourself the XP and GP, if you would like to.

I'm going to close this now because I think everything should be okay, but we can reopen it if there's any more problems - just comment here, even after it's closed. For tracking progress of the bug that caused this problem, we're using https://github.com/HabitRPG/habitrpg/issues/4252

**Closed as completed by Alys** 2015-01-22 09:19 UTC

**Comment by Aemilia** [comment] 2015-01-22 09:25
Hi Alice,

Cub and achievement are both there.

Thanks again for sorting this so quickly, you Habit folks are ace.

Cheers,
Emily

**Comment by hespa** [comment] 2015-01-24 22:08
Hello all,

I'm not sure if people will see this comment given it's a closed thread, but I thought I would try rather than just start a new one. I'm another member of Emily's party and I did not receive the polar bear pet quest rewards either. Help?

Cheers,

Hespa

**Comment by Alys** [comment] 2015-01-24 22:10
We see all comments. We are all-knowing and all-powerful.  :) Let us know your "User ID" from [Settings -> API](https://habitrpg.com/#/options/settings/api) and we'll get you fixed up within a couple of days.

**Comment by hespa** [comment] 2015-01-24 22:11
Oops, sorry! It's 4338c3b0-48b4-44ab-b6fb-62cf07dad9fb

**Comment by deilann** [comment] 2015-01-24 22:13
Apparently we are NOT all-knowing and all-powerful enough to see UUIDs
yet...

**Comment by Alys** [comment] 2015-01-24 22:24
I could have worked it out from database mining. I'm just also all-lazy.

@hespa That's fixed for you now. You should have the pet and the quest achievement (reload if you don't see either).

**Comment by hespa** [comment] 2015-01-24 23:24
Brilliant, all is fixed - thank you!
