### ISSUE TITLE
streak bonus not removed when daily is unchecked

### ISSUE THREAD

**Issue by octern** [HabitRPG/habitica#1079] opened 2013-05-28 16:23 UTC
If I check and then uncheck a daily with a streak, the streak counter goes up and down properly, and I lose the gold/silver reward. However, the streak bonus is not removed. If I repeatedly check and uncheck a daily, my net gold goes up and up as I skim off the streak bonus each time.

I'm also getting the presumed rounding error where I sometimes lose 1 more silver than I gained, or vice versa, but this is a separate phenomenon (note that the rounding error is always consistent for a given daily -- the gain isn't always the same as the loss, but it's the same gain every time I check it).

**Comment by StanLindsey** [comment] 2013-05-28 18:22
Thanks for the report but tis a duplicate of - #1012 

Closing for house-keeping!

**Closed as completed by StanLindsey** 2013-05-28 18:22 UTC
