### ISSUE TITLE
Died for no reason!

### ISSUE THREAD

**Issue by ohtree** [HabitRPG/habitica#2749] opened 2014-02-05 03:15 UTC
YESTERDAY, I was left with 2 HP, but I was able to gain enough experience to gain a level before midnight. This morning, everything was reset like usual and I was able to do some dailies--but just now, when I went to Habit, it took me to the sign-in page, and when I clicked the start/play/whatever button, I saw that my dailies had reset to what they were yesterday, and it said that I died! I lost a Wizard Robe too. What's weird is that the streak count on all of the dailies didn't go to zero after I died, so it's like Habit knew I didn't actually die. Can I fix this?

**Comment by lefnire** [comment] 2014-02-05 03:19
Dupe of https://github.com/HabitRPG/habitrpg/issues/2601, follow there. You can restore your values at Options > Settings > Restore Character Values

**Closed as completed by lefnire** 2014-02-05 03:19 UTC
