### ISSUE TITLE
Changing equipment gives weird blank notifications

### ISSUE THREAD

**Issue by casicastiel** [HabitRPG/habitica#2235] opened 2014-01-02 16:38 UTC
user cca60406-1b8f-496e-af77-cd19df77c895, mac chrome
![screen shot 2014-01-01 at 4 58 58 pm](https://f.cloud.github.com/assets/6208739/1833561/426cf5cc-73cc-11e3-8613-e2d947584407.png)

**Comment by djuretic** [comment] 2014-01-02 16:56
Happens to me too! Chrome on Ubuntu

**Comment by SabreCat** [comment] 2014-01-03 01:26
Duplicate of #2073.

**Closed as completed by SabreCat** 2014-01-03 01:26 UTC
Labels: priority: minor
