### ISSUE TITLE
Issue when run locally on a debian 6.0 server

### ISSUE THREAD

**Issue by Altor31** [HabitRPG/habitica#631] opened 2013-03-10 12:36 UTC
I fellow the [wiki](https://github.com/lefnire/habitrpg/wiki/Running-Locally), but when I push on play, I obtain _the server is experiencing issues. Try again in a few, the developer has been notified. The most likely culprit is this issue which Tyler is working frantically to fix. (Any memory leak experts?)_ 

_top_ doesn't show any issue with the memory. 

The shell shows : _node server.js 
   info  - socket.io started
Expressions in require() statements:
    require('./lang/' + key)
User not found - this shouldn't be happening!
_

I didn't modify the config.json file.

**Comment by lefnire** [comment] 2013-03-10 13:55
Aha, it's picking up a `req.session.userId` that doesn't exist in the database. Try clearing cookies and refreshing

**Comment by Altor31** [comment] 2013-03-10 15:31
Thank you for your quick answer. 
Unfortunately, I clear cookies, try in private browsing and ask friends to try and I have still this error. 

I don't have a user in "_my_ " habitrpg. Maybe the error comes from this.

**Comment by lefnire** [comment] 2013-03-10 17:51
I won't be able to jump into this soon, but jus ta lead - it's finding session.userId in your browser session, a userId which doesn't exist int he database. [This](https://github.com/lefnire/habitrpg/blob/master/src/app/party.coffee#L38) is where it's triggered. I'm not sure why that's happening if your cookies are cleared, start poking around and I'll see if I can jump in later

**Comment by koentav** [comment] 2013-05-18 11:54
I have the same problem after a fresh install using the wiki instructions

I've tried several browsers, with all history and sessions deleted, but always get kicked back to http://localhost:3003/static/front (I use port 3003, ntop runs on 3000) whenever I hit the play button. I never get to the page where I can register or log in.
Mongodb tells me there is a habitrpg db, so that bit looks fine

The server says:

server:~/git/habitrpg# node server.js 
   info  - socket.io started
Expressions in require() statements:
    require('./lang/' + key)
User not found - this shouldn't be happening!
User not found - this shouldn't be happening!
User not found - this shouldn't be happening!

I don't think the issue is in the party.coffee file, but rather in [here](https://github.com/lefnire/habitrpg/blob/master/src/app/index.coffee#L81). However, I can't figure out what is causing it.

**Comment by lefnire** [comment] 2013-05-18 13:53
Strange.. fresh mongo database too? That error happens when the browser
session has a user id that's not in the database

**Comment by koentav** [comment] 2013-05-18 14:00
Yes, same setup as original poster. Debian squeeze (6.0) . I installed mongodb on it just before installing habitrpg. I had to compile node.js because there is no package for it, but didn't get any complaints during the build process and it seems to behave correctly.

I will probably go to wheezy (7.0) soon, as that is stable now, and see if that solves the problem.

**Comment by lefnire** [comment] 2013-05-18 14:36
which node version? 0.10 breaks things, I find 0.8.x has the best results. Though I believe you'd have been experiencing different issues than this if you're on 0.10.x

**Comment by koentav** [comment] 2013-05-18 18:20
It was 0.10.x. I uninstalled that and got 0.8.23 instead, but still the same issue unfortunately.

I'm in the process of upgrading to wheezy, will report back after that is done.

Thanks for your help so far!

**Comment by koentav** [comment] 2013-05-18 21:01
Good news!

Updating to wheezy seems to have solved the problem. I stuck with my compiled node 0.8.23 because wheezy doesn't have a node.js package either. Mongodb got updated, and a bunch of other stuff, so not really sure what made it work. 

It still gave me the 'User not found - this shouldn't be happening!' warning, but this time the web frontend moved to the page where I could login or register, and from there on everything has been working fine.

I've never seen my two boys brush their teeth with so much pleasure just to obtain XP and gold coins. I think we're onto a winner for chores and homework! 

Many thanks. 

Koen.

**Comment by lefnire** [comment] 2013-05-19 14:36
:) :)

**Comment by fabricepayet** [comment] 2013-07-31 05:17
Same problem and i solved it by upgrading mongodb 1.4.4 to 2.4.5. Thanx you ! 

http://docs.mongodb.org/manual/tutorial/install-mongodb-on-debian/

**Comment by lefnire** [comment] 2013-07-31 15:31
updated the wiki with [these changes](https://github.com/lefnire/habitrpg/wiki/Running-Locally/_compare/da80f981b37daad16b5c4baf11f3742ccd2b6e3d%5E...da80f981b37daad16b5c4baf11f3742ccd2b6e3d), let me know if there's anything else I should add

**Comment by paglias** [comment] 2013-09-09 17:50
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!

**Closed as completed by paglias** 2013-09-09 17:50 UTC
