### ISSUE TITLE
Daily Bug

### ISSUE THREAD

**Issue by Gragriel** [HabitRPG/habitica#240] opened 2013-01-27 20:58 UTC
My dailies are failing to update with server, so I lose the gold/XP I gained from them, but the dailies remain checked after refreshing. This started today (Jan 27 2013)

**Comment by horusofoz** [comment] 2013-01-28 01:56
Hey @Gragriel. Can you test if this is still happening? We experienced some intermittent service issues over the last few hours which may have resulted in the behaviour you describe.

**Comment by Gragriel** [comment] 2013-01-28 04:51
It's not happening now. I should clarify, the bug stopped happening around the time I reported it.  More of an "artifact" than a bug, I suppose. There were some other artifacts around the same time as well, like a moved Habit item moving back and a nearby item moving instead, if I'm remembering correctly. That occurence would imply the first item was listed as moved, the move order repeated itself for the 2nd item now in the 1st item's original spot, then the 1st item was never actually moved. I'm guessing the intermittent service was causing changes to occur partially?

**Comment by horusofoz** [comment] 2013-01-28 04:54
@Gagriel I think you're on the money. If you assent we can close this ticket but a record will be kept to compare against if a new outage happens. Are you cool closing the ticket?

**Comment by Gragriel** [comment] 2013-01-28 04:57
Yeah, that's fine. We should probably remove the "bug" label though, unless there's no better way to describe what happened.

**Closed as completed** 2013-01-28 04:57 UTC

**Comment by horusofoz** [comment] 2013-01-28 04:59
With the current label system, bug is the most relevant. Though the issue itself was not a bug it was a symptom experienced due to a bug/outage. Hope that makes sense.
