### ISSUE TITLE
Received Wrong Monthly Subscriber Item/Didn't Get One At All

### ISSUE THREAD

**Issue by confusedmuse** [HabitRPG/habitica#5492] opened 2015-06-25 22:49 UTC
Hi, I've been a subscriber for several months now, and when I saw that the new item was released today, I went to the Inventory to claim it. When I clicked on the present box (which had a '4' next to it), I received the two items from May instead of the new items. I received two blue pop-ups on the side informing me that I had received the 'Green Knight Lance' and 'Green Knight Helm' (which confused me, since the site update said we were getting snorkel gear and I already had those items) and after clicking on the box twice, the number dropped to zero and now I can't receive anything. I didn't receive any error codes when this occurred either. It doesn't look like I have duplicate items in my inventory, but I haven't received the new items at all. I tried clearing my cache to see if that would help, but the problem is still the same. My user ID is 587e52c6-6e81-4d8c-bcab-b881cf4d6ac1. Thanks for your help!
##

**Comment by hairlessbear** [comment] 2015-06-25 22:59
See #5491. Just hit refresh, and the issue should fix itself :)

**Comment by confusedmuse** [comment] 2015-06-25 23:04
Thanks! Sorry that I didn't see that thread, or I wouldn't have posted this at all! :D

**Comment by hairlessbear** [comment] 2015-06-25 23:07
No worries! Would you mind closing the ticket, since the issue is fixed?

**Closed as completed** 2015-06-25 23:27 UTC
