### ISSUE TITLE
Possible Inn/day resetting Glitch.

### ISSUE THREAD

**Issue by ebugle** [HabitRPG/habitica#1196] opened 2013-06-20 04:21 UTC
I am using a mac (OSX.7.5) and Chrome for the purposes of HRPG. My name on there is Bugle.

I checked into the inn late yesterday, due to physical exhaustion not allowing me to finish my tasks. And this morning, I checked back out. I noticed some of my tasks were still marked as checked off, though, despite it being after 4 in the morning (when I have my day rollover). But this had happened the last time I used the inn, so I ignored it and went to work. When I came home, I checked Habit RPG and it seems my day had somehow rolled over and I took 12 damage from 7 different dailies that hadn't been marked off.

I understand that this is still beta and glitches happen, so despite being a little annoyed that this happen, I certainly do understand it's likely just a glitch and, well, things happen. It's not the end of the world or my account or anything. I'm more concerned that this be fixed so it won't happen again, so hopefully this bug report is helpful to you. If not, sorry for the waste of time.

**Comment by lefnire** [comment] 2013-06-21 01:39
dupe of #997, let's follow up there. firstly, dailys don't reset the day after you check out of inn. but yours sounds more like the bug discussed in #997, in which you weren't properly checked into the inn in the first place due to #165, which is being working on right now in the 0.5 upgrade

**Closed as completed by lefnire** 2013-06-21 01:39 UTC
