### ISSUE TITLE
clone challenge: tasks were not cloned

### ISSUE THREAD

**Issue by kawunngg** [HabitRPG/habitica#8116] opened 2016-10-10 12:28 UTC
hey all!

i run a daily challenge in the Pomodoro Playground and today a member pointed out that there were no tasks in the challenge. i clone it everyday and therefore don't pay too much attention while doing so, i only change the name and the tag, therefore I'm not sure _when_ the tasks disappeared, whether it was while cloning or even after that? but deleting 4 to dos and 2 habits by accident within 10 seconds does not really seem possible to me. 

i cloned the challenge again and this time the tasks are all there. 

original challenge: https://habitica.com/#/options/groups/challenges/2efe79bf-17a9-44ec-af49-8941c9a917f7

cloned, missing tasks: https://habitica.com/#/options/groups/challenges/2817172c-8896-4276-be0a-40689fdc34b1

EDIT: firefox 49.0.1 / Win 7

**Comment by Alys** [comment] 2016-10-10 12:59
@kawunngg Can you please tell us your User ID?

**Comment by kawunngg** [comment] 2016-10-10 13:02
sorry, it's ce935e7f-00e6-44bc-a44a-5280553810f0

**Comment by Alys** [comment] 2016-10-10 13:12
@kawunngg thanks! 

For admin reference, below are the challenge's details from the database, including the creation date, which we can use to find appropriate log files to see if there's any concerning errors in them.

And of course the data has kawunngg's UID in it, so I didn't need to ask for it - sorry kawunngg!

```
{
    "_id": "2817172c-8896-4276-be0a-40689fdc34b1",
    "name": ":tomato: Pom Party 2016-10-10",
    "shortName": ":tomato: Oct 10",
    "description": ":tomato: It's Pom Party Time! :tomato: \n\nSet your personal goal and be productive. this is all about you, so it doesn't matter if you plan to finish 3 or 10 pomodoros or if your pomodoros are really 25 minutes long. set yourself a realistic goal and work towards it.\n\nA winner will be drawn randomly from all those who met their goals. see the notes of the tasks for additional infos. \n\nUse the habit for additional XP and drop chances. \n\n---\n\nNote: I try to post this challenge on a regular basis, usually from Monday till Saturday, sometimes also on sundays. if i'm not here feel free to set up the challenge yourself. i usually post the next challenge around midnight the day before (UTC+2:00). \n\nMondays with gem prize.",
    "leader": "ce935e7f-00e6-44bc-a44a-5280553810f0",
    "group": "36d46844-c04c-4c5b-8a00-7fafb09d2697",
    "updatedAt": "2016-10-10T12:51:20.314Z",
    "createdAt": "2016-10-09T19:40:46.551Z",
    "prize": 1,
    "memberCount": 2,
    "tasksOrder": {
        "rewards": [],
        "todos": [],
        "dailys": [],
        "habits": []
    },
    "official": false,
    "__v": 0
}
```

**Comment by kawunngg** [comment] 2016-10-10 13:14
haha, no problem ;)

**Comment by Alys** [comment] 2016-10-22 10:35
@kawunngg I wasn't able to find log file records for this. We haven't seen any other instances of it, so I'm tentatively assuming it was a once-off glitch, possibly caused by the server being under high load. I'm closing this but we can reopen it if it happens again.

**Comment by UnexpectedMushroom** [comment] 2016-11-12 04:16
It happened again. :P

[Original](https://habitica.com/#/options/groups/challenges/bed856de-d1e6-4f2b-beb7-e7a5d7434367)

[Clone 1](https://habitica.com/#/options/groups/challenges/3ea1f60b-2d7a-49e9-81b9-6b98ce0f2cc4)
[Clone 2](https://habitica.com/#/options/groups/challenges/7de0511e-9d43-481c-927a-34929a14bc1d)
[Clone 3](https://habitica.com/#/options/groups/challenges/fc573ce1-cdb0-4ddb-8d09-486e3cb59b43)

**Comment by Alys** [comment] 2016-11-12 04:56
Confirmed. Reopened. Thanks @UnexpectedMushroom !

**Comment by TheHollidayInn** [comment] 2016-11-16 01:18
@UnexpectedMushroom Do you have any ideas on the steps you take to recreate this issue or does it happen randomly?

**Comment by UnexpectedMushroom** [comment] 2016-11-16 01:56
I have no idea. I don't think I did anything out of the ordinary.

**Comment by TheHollidayInn** [comment] 2016-11-17 04:32
@UnexpectedMushroom Do you know how to view the console? If this happens again, can you right click, select Inspect Element, select Console tab, then paste the output here?

**Comment by Alys** [comment] 2017-01-04 05:46
Another report of this has been made in the Report a Bug guild.

**Comment by kawunngg** [comment] 2017-02-17 13:20
and again ... 

UID: ce935e7f-00e6-44bc-a44a-5280553810f0

challenge: https://habitica.com/#/options/groups/challenges/2b7a3732-5c78-457a-94e2-9c913d14984c

**Comment by kawunngg** [comment] 2017-04-11 20:38
... and again ...

UID: ce935e7f-00e6-44bc-a44a-5280553810f0

challenge: https://habitica.com/#/options/groups/challenges/d4e5405d-e38f-4cd1-9a66-1caf7866f441
edit: i created this challenge about a week ago, unfortunately i noticed only now.

is it still usefull to report broken challenges?

**Comment by Alys** [comment] 2017-04-11 20:56
@kawunngg Yes, still useful, so we know how often it happens. :(  Does the original challenge still exist? If so, can you try cloning it again?

If it does not still exist, did it have many tasks or complex tasks that would take significant time to rewrite? I might be able to find the taaks in a backup, although that's a slow process so for short simple challenges, creating the tasks manually might be faster. Tell me when the original challenge was closed if you want help from a backup.

**Comment by kawunngg** [comment] 2017-04-11 21:17
@Alys i already closed the origial challenge. but cloning it again worked like it should the last 2 times (Feb 17 & Oct 10). 
i keep a "blue print" in my own private guild, i already lost a challenge because i closed it before cloning x-D but it's very nice of you to ask. :)

**Comment by kawunngg** [comment] 2017-04-13 23:12
so today @MintyOtterine stated that the bug seems to like me...

https://habitica.com/#/options/groups/challenges/9044eba5-da20-4105-a4e4-6042a2a5de0e

**Comment by kawunngg** [comment] 2017-04-13 23:15
so today @MintyOtterine stated that the bug seems to like me....

https://habitica.com/#/options/groups/challenges/9044eba5-da20-4105-a4e4-6042a2a5de0e

**Comment by kawunngg** [comment] 2017-07-06 15:46
i just tried to clone a challenge, and noticed the tasks disappear right after clicking on the "clone" button. it was around 3:35 pm (UTC).

User ID: ce935e7f-00e6-44bc-a44a-5280553810f0
original challenge: https://habitica.com/#/options/groups/challenges/5836115a-0654-4078-b278-96d2b3c823bd

i discarded it right away, so there's no clone. i hope the info helps.

**Comment by Alys** [comment] 2017-08-28 11:46
This bug is still happening. A report from LaMama Fox (8f9110b4-50d7-446b-a142-0c6ca0cb5029): 

"I've had trouble cloning challenges. Two weeks ago cloned a challenge but the to do's and habits didn't copy. When I realized this, I cloned it again, and it worked. Today I just tried to clone two challenges: https://habitica.com/#/options/groups/challenges/9d228793-a88f-4294-94fd-82f0125c055e and https://habitica.com/#/options/groups/challenges/c0f65abb-5ce3-4de4-985a-91d4cf3cf5e3. In both case I had to Discard the challenge because the habit and to dos weren't copied. However, I just tried again, and it looked like it worked."

**Comment by kawunngg** [comment] 2017-08-28 11:57
i still notice it too, but i started to notice it instantly before saving the challanges :-P
one moment later and it usually works again. it happend on several times of the day and I'm not sure if it's connected to high user traffic. but i can only set it in relation to the amount of chatter the guilds I'm in, so i might be wrong.

**Comment by Alys** [comment] 2017-08-31 10:01
A few instances have happened to AnneLine (16a107de-d519-43ce-8c30-8da5cbcbb237):
"about half of the private challenges I'm trying to set up are not getting any to dos in them.... I am watching and just re-cloning, but reporting for your reference...."

@kawunngg Thanks for your details!

**Comment by kawunngg** [comment] 2017-10-13 10:23
i think it happens more often now since the update :(

**Comment by TheHollidayInn** [comment] 2017-11-17 12:31
@kawunngg are you seeing any error messages? And can you post here next time it happens with the challenge id? or URL?

**Comment by Alys** [comment] 2017-12-05 16:20
In the [Guild Leaders & Challenge Creators](https://habitica.com/groups/guild/0393624e-65f0-40c1-8e87-360955fcebca) guild, Azuran ( 242241ad-cbf2-4f1d-8549-ed1f24a3476b ) writes:

**I think I may have found the problem... I think that the tasks don't clone onto the new Challenge when I don't let the page load entirely before clicking the "clone" button.**

@TheHollidayInn does that sound plausible to you? I think the relevant code is this:
https://github.com/HabitRPG/habitica/blob/f3c2c0f9013f3a4d498d241f77e2bda376d81c6b/website/client/components/challenges/challengeDetail.vue#L401-L406

If this is the cause, can we prevent the problem by greying-out the clone button until the whole challenge has loaded? Another option would be to move cloning to the API, which would make it more testable and possibly reliable, and allow the apps to use it in future.

**Comment by Alys** [comment] 2017-12-06 17:00
For the record, we've decided we're going to move the cloning feature to the API, which will fix this issue.

**Closed as completed** 2018-01-30 15:23 UTC
Labels: priority: important, section: Challenges, status: issue: in progress
