### ISSUE TITLE
Speed and Memory

### ISSUE THREAD

**Issue by krzychukula** [HabitRPG/habitica#2386] opened 2014-01-13 08:47 UTC
Unfortunately new features makes app slower and take more memory. I can easily see a couple of issues with current app.
1. Takes really long time to load.
2. Takes really long time switching between tasks and settings
3. 'Done' sometimes takes really long time to finish. Most of the time freezing entire UI. This is really bad. XHR status animation at the top is really nice but I want to interact with the app without waiting for 5-10 seconds to unblock UI.
4. Memory: Chrome started recently to kill entire tab (happened twice in last couple of days) after that I notice my ram usage in system dropped about 1/4 (I have 8GB of ram , unfortunately I don't have exact numbers but it's probably easy to inspect).

I interact with the app from Europe, Poland. 
Using newest Chrome on both Ubuntu and Mac and it works pretty much the same.

I know that this is not strictly a bug but in my opinion it should be treated as such.

**Comment by wc8** [comment] 2014-01-13 14:00
I’ve had a similar impression overall. In my case, I’ve had to restart Fluid browser every once in a while after switching between tasks and options or reloading the browser because the page blanks completely. It’s fairly recent, though.

**Comment by lefnire** [comment] 2014-01-13 15:36
dupe of #1499, follow there

**Closed as completed by lefnire** 2014-01-13 15:36 UTC
Labels: priority: important
