### ISSUE TITLE
Repeated errors on Chrome/Mac, slow to register input

### ISSUE THREAD

**Issue by gusandrews** [HabitRPG/habitica#6497] opened 2016-01-11 18:44 UTC
Using Chrome on Mac 10.10.5, I've lately had a lot of times when I complete habits and dailies, it takes forever to register them (Chrome runs a very slow loading bar while it happens), and then it gives me an error message telling me to reload. Reloading is not always helping. Once I reload, it has forgotten that I completed those habits and dailies (and even forgot that I leveled up doing them).

This is the latest message I pulled out of the console, but I think I got this one after reloading and/or closing my Habitica tab and re-opening it:
"Failed to load resource: the server responded with a status of 503 (Service Unavailable)
app-8bc22262.js:32 ObjectresponseError @ app-8bc22262.js:32"

Wondering if it has anything to do with other tabs I have open -- I tend to have a handful open at any given time, and I feel like maybe there's more problems when I have a presentation-type file open in Google Docs, but that's just a hunch.

**Comment by pigpuddle** [comment] 2016-01-11 20:20
I'm having the same problem with Chrome, though I'm on OS 10.11.3. I'm also having the problem while leveling up; I wonder if that's related. Having the same issue on Safari as well.

**Comment by AnnaFromPoland** [comment] 2016-01-12 11:03
in my case it either says something like "document empty" or gives me a huge popup saying "application error" and telling me to reload the page and report the bug blah blah blah.
it happens on chrome only - not in firefox, but firefox has had its own issues lately and pissed me of so i came back to using chrome, but i forgot it had this persistent utterly annoying error.
this error happens "only" when: clicking a task, clicking a spell, doing anything with tasks or spells.
it takes long time to load a challenge's description, user profile or a guild page (basically it takes forever, and with no guarantee of success, to load a page).

screenshot attached.

<img width="1440" alt="0028-01-12 11 54 08" src="https://cloud.githubusercontent.com/assets/16665256/12261906/664f62aa-b924-11e5-866c-0b79611003c5.png">

**Comment by joshers** [comment] 2016-01-15 14:59
What extensions are you running? It seems like it may be a local issue with an adblocker or tracking blocker getting overzealous and messing everything up.

**Comment by AnnaFromPoland** [comment] 2016-01-15 16:30
alright, i'll turn off the adblocker. tracking blocker could be disconnect, i'll set up the exception so it wouldnt activate on habitica. i'm not sure this is the case though, because this happens super randomly, and the only stable (repeating) thing i've noticed is, this happens when i click or type at normal speed. habitica seems very heavy on my system? the computer starts "panting" so to say, warms up a lot and the chilling thingy needs to operate faster, and i have to be suuupeeer sloooow when using it, waiting till the popup after performing an action completely fades away or it will freeze or produce an error. when typing a checklist it's particularly visible, or performing consecutive clicks, like when i want to use tools of trade 7 times in a row. i thought that it may be connected with merfy's skin or the fact i've super many tasks, but i hear some people have even more. first i'll disable the addons that you've mentioned and see how it works.

**Comment by Alys** [comment] 2016-01-16 03:02
@bakatenko How many tasks do you have? The easiest way to count is to go to Data -> Data Display Tool and use the Task Statistics section.

**Comment by AnnaFromPoland** [comment] 2016-01-16 09:44
52 dailies and 134 to do tasks. for the bigger ones i like to add checklists too as it helps me organise things, and every time i do this there's at last one freeze when i'm typing that closes the edit mid way erasing the typing in the checklist item i were doing. have to type very slow, typing at the normal speed guarantees the freeze. what's weirder, quite a few times the typing would suddenly change while i'm typing, mid word - would throw the cursor to the beginning of the line O-o and i have some words typed in correctly and then one cut and finished at the beginning of the line. never seen such a bug, it's funny and odd, i've no idea as per what the cause could be. only had this with checklists here.

**Comment by Alys** [comment] 2016-01-17 10:49
@bakatenko That is quite a lot of tasks. I have about that many and the site is often slow for me and occasionally freezes temporarily. It would be interesting to know if a test account with only a few tasks displayed the same lag on the same browser that you use your real account on.

**Comment by AnnaFromPoland** [comment] 2016-01-17 11:07
i'll be watching the browser work with this load of tasks and continue to compare chrome with firefox (unfo i won't be comparing safari cause it does not support merfy's theme so well - on safari the height of each task box does not get lessened, and with as many tasks as i have, it takes too much space. merfy's skin allows for a "bird view" comparatively), and then will try the same with half the amount (i do have a bit too many tasks indeed. should clear some by the end of the month). i'm alway son the newest build of mac osx, and the browsers update regularly too, it's mostly a question of which is better, chrome or ff.

**Comment by elocin910** [comment] 2016-01-23 02:47
I'm having the same problem! Using Chrome on Mac 10.11.2, I get the 503 Service Unavailable message  on every page no matter the situation. I tried turning off adblocker and it didn't make a difference.

**Comment by AnnaFromPoland** [comment] 2016-01-25 12:26
did you try to turn off any possible -other- disconnecting plugins? if any? that _did_ help a bit in my case, now i see these errors uber rarely (and now only on chrome, ff behaves well with adblock and disconnect turned off on habitica).

it is also _quite_ possible that it’s because chrome and macs don’t mix so well - http://blog.getbatterybox.com/which-browser-is-the-most-energy-efficient-chrome-vs-safari-vs-firefox/ http://blog.getbatterybox.com/which-browser-is-the-most-energy-efficient-chrome-vs-safari-vs-firefox/ - and you might be just better off with something else, safari and opera seem the best options, although i’ve never used the latter so i’m between safari and ff.

**Comment by elocin910** [comment] 2016-01-25 16:31
I've tried it with out any plugins and it still doesn't help. I'm going to be so disappointed if this doesn't get fixed.. I'm definitely not going to switch from using Chrome..

**Comment by berriganator** [comment] 2016-01-28 17:00
I am also having trouble with very very slow registering of any type of activity, and also reload errors. But I am using Firefox on Mac, not Chrome.

**Comment by paglias** [comment] 2016-06-01 09:35
Should be fixed, reopen if it happens again

**Closed as completed by paglias** 2016-06-01 09:35 UTC
