### ISSUE TITLE
Error: [ngRepeat:dupes] Duplicates in repeater not allowed. Use 'track by'... Repeater: member in group.members track by member._id

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#4000] opened 2014-09-08 10:21 UTC
I've noticed non-fatal errors occurring on my local install while doing actions related to quests, for example, accepting a quest invitation, beginning a quest, aborting a quest. These occur even when my source code is identical to upstream/develop. They don't seem to have noticable side-effects and everything seems to keep working as it should. 

```
Error: [ngRepeat:dupes] Duplicates in a repeater are not allowed. Use 'track by' expression to specify unique keys. Repeater: member in group.members track by member._id, Duplicate key: undefined
http://errors.angularjs.org/1.3.0-beta.11/ngRepeat/dupes?p0=member%20in%20group.members%20track%20by%20member._id&p1=undefined
    at http://localhost:3000/bower_components/angular/angular.js:78:12
    at ngRepeatAction (http://localhost:3000/bower_components/angular/angular.js:21229:20)
    at Object.$watchCollectionAction [as fn] (http://localhost:3000/bower_components/angular/angular.js:12323:13)
    at Scope.$digest (http://localhost:3000/bower_components/angular/angular.js:12451:29)
    at Scope.$apply (http://localhost:3000/bower_components/angular/angular.js:12724:24)
    at done (http://localhost:3000/bower_components/angular/angular.js:8328:45)
    at completeRequest (http://localhost:3000/bower_components/angular/angular.js:8533:7)
    at XMLHttpRequest.xhr.onreadystatechange (http://localhost:3000/bower_components/angular/angular.js:8472:11) angular.js:10111
```

My main reason for reporting this is that I'll soon by PRing some quest changes and if anyone then notices these errors, I want to be able to say "it was like that when I got here". :)

**Comment by paglias** [comment] 2014-09-08 10:24
I think it's due to #3993 , but I'm wondering why member._id is undefined..

@Alys it's the 4000th issue :)

**Comment by negue** [comment] 2014-09-08 10:27
Should I've used member.id instead _id?

**Comment by paglias** [comment] 2014-09-08 10:28
_id is correct the problem is why it's undefined, I would suggest reverting
the changes for now
Il 08/set/2014 12:27 "negue" notifications@github.com ha scritto:

**Comment by Alys** [comment] 2014-09-08 10:29
4000th!!! I want a special prize! Set the Artisans to work! :)

**Comment by paglias** [comment] 2014-09-08 10:31
@negue in the meantime I've reverted it
https://github.com/HabitRPG/habitrpg/commit/c90c8f9a5f8584c7ee7c5fc14a5ec3bcac2e5eed

2014-09-08 12:29 GMT+02:00 Alice Harris notifications@github.com:

> 4000th!!! I want a special prize! Set the Artisans to work! :)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/HabitRPG/habitrpg/issues/4000#issuecomment-54800505.

## 

Matteo Pagliazzi - paglias.net

**Comment by negue** [comment] 2014-09-08 10:34
NOOOOOOO, now everything is slow again XD

Should I create seperate changes / pullrequests? without member ?

**Comment by paglias** [comment] 2014-09-08 10:36
Since Tyler said there could be also tasks with the same UJID if you could
make some testing especially on the undefined _id then we can merge
everything once again
Il 08/set/2014 12:34 "negue" notifications@github.com ha scritto:

**Comment by negue** [comment] 2014-09-08 11:23
So create many tasks / members / groups / users and so on? 

Is there any way to connect to http://habitrpg.com/api/ but using local server / frontend?

**Comment by paglias** [comment] 2014-09-08 11:29
@negue if you edit https://github.com/HabitRPG/habitrpg/blob/f981223153532035d72c35d42412628145c40385/public/js/app.js#L12 to "https://habitrpg.com" you should be able to connect to habitrpg official api

**Comment by paglias** [comment] 2014-09-08 11:30
we should really create a lot of fake data to use on local

**Comment by Alys** [comment] 2014-09-08 11:46
I have a set of about a dozen users with matching usernames, UUIDs, and tokens for ease of use, and with a variety of settings (levels, tiers, gear, etc). I'll upload the json file in about 10 hours, after nap time.

**Comment by negue** [comment] 2014-09-08 12:04
@paglias I already many times to change API_URL , but after login it redirects me to "/static/front/#tasks" can't get to show /#tasks 

@Alys demo data would be great

I think there's just some data which doesn't have any _id anymore.

**Comment by Alys** [comment] 2014-09-08 12:15
Do you want to use the production API specifically, or just the API in general? If you're happy to use the API on your local install, edit config.json to do this: `"BASE_URL":"http://localhost:3000",` and then the API is available at http://localhost:3000/static/api
Apologies if that's not what you meant. And there might be a better way of achieving the same thing.

Demo data first thing in the morning, I promise. :)

**Comment by paglias** [comment] 2014-09-08 12:17
I think in order to run it with production data you should find a way to
run only the client side, otherwise the local server won't get api calls
and redirect back to static pages
Il 08/set/2014 14:15 "Alice Harris" notifications@github.com ha scritto:

**Comment by negue** [comment] 2014-09-08 13:57
I'll test it after work, but I still think the API shouldn't return any members ( or items which are used by "track by" ) which doesn't have a _id set.

Just curious the id / _id is only set on the API , in browser, If you add a new task (or other object) the id is undefined?

Need as much information I can get :D

**Comment by paglias** [comment] 2014-09-08 14:19
Tasks get the id set by the browser, about members its possibile that the
api returns only the usernames as part of the group and then load the ids
later. But I'm not sure, it's a lot that I don't touch that code
Il 08/set/2014 15:57 "negue" notifications@github.com ha scritto:

**Comment by negue** [comment] 2014-09-08 15:04
I could connect to https://habitrpg.com

I'm in 4 Guilds and I don't get any undefined errors.

Altought 2 other which are not related to my changes and currenty also there on the live server (https://habitrpg.com) , for those errors I'll create an issue.

Edit: The other bugs:
- #2239
- #4001

**Comment by negue** [comment] 2014-09-08 17:31
I'll wait and test again with @Alys demo data, I hope the new version won't get published without trackBy ^^

**Comment by Alys** [comment] 2014-09-08 18:28
Demo data:
http://oldgods.net/habitrpg/users.json
http://oldgods.net/habitrpg/groups.json
- Usernames are tier-1, tier-2... tier-7, admin-8, etc, where the digits represent the contributor tiers that have been given to the accounts (using the new scheme for contrib tiers which will go live soon).
- All accounts have the password `test`.
- The admin-9 account has contributor.sudo:true.
- For all accounts, profile names and usernames are identical.
- All accounts are in the same party so you can see all usernames easily after you've logged in with one.
- The UUIDs and API Tokens are mostly single digits for ease of use, based on the digits in the usernames. For example, admin-9 has a UUID of 9 and a Token of 9. This non-standardness doesn't seem to cause any problems and is a boon for making party invites and using the API.

I use this shell command for importing user and group data:

```
mongoimport --db habitrpg --drop --jsonArray --collection groups < /vagrant/build/mongo-dumps/groups.json; mongoimport --db habitrpg --drop --jsonArray --collection users < /vagrant/build/mongo-dumps/users.json
```

I use this shell command for exporting data into files called, e.g., groups-20140908181202.json:

```
rm /vagrant/build/mongo-dumps/*201*; dt=`date +"%Y%m%d%H%M%S"`; for c in counters coupons groups users; do echo; echo $c; mongoexport --db habitrpg --jsonArray --collection $c --out /tmp/out; node -e "console.log(JSON.stringify(JSON.parse(require('fs').readFileSync(process.argv[1])), null, 4));" /tmp/out > /vagrant/build/mongo-dumps/$c-$dt.json; done
```

The `date` command works differently on different *nixes so you might need to adjust it.
The `rm` command deletes previous exports but nothing else (unless you put 201 in a file name!).

I store my data dumps in a subdirectory under `build/` because that prevents nodemon from causing an npm restart whenever the dumps are changed (nodemon doesn't watch build/).

**Comment by negue** [comment] 2014-09-08 18:54
@Alys  THANKS!!!

I can only login with admin-8 , all other "tier-X" account won't let me login with `test`

**Comment by Alys** [comment] 2014-09-08 19:01
That's truly weird. I'm afraid I have no idea what's happening there. They all have identical salts and hashed passwords, and I can log in to all of them using `test`. All I can suggest is reimporting the user.json file again, in case something odd happened, but I doubt it will make any difference since admin-8 was working. Is there anything useful in the Console?

**Comment by Alys** [comment] 2014-09-08 19:05
Reload http://oldgods.net/habitrpg/users.json and download it again. I've changed the email addresses to make them unique and standardise them with the usernames. Probably won't help with your login problem, but maybe it will, and I should have done that before anyway.

**Comment by lefnire** [comment] 2014-09-08 19:19
I too don't know why under certain circumanstances _id/id are undefined on certain objects, I've seen it from time to time but can't pin-point anything. Some thoughts:
- A few Group operations (join party, begin quest.. maybe.. I can't remember which ones) have a bug where the Group $resource performs a PUT/POST and gets nothing back, but then loads that nothing as the Group model ($resource expects a result for every op). This is when we see empty lists of members. Could this be the main issue? If so, the simple solution would be to have those cases return a proper response, or somehow tell $resource to not expect a response?
- BTW: reason `task.id` is that way, btw, instead of `task._id` (`_id` is always the correct form, since that's what mongo expects) is legacy Derby stuff that's too hard to migrate from.

BTW, @negue I'm gonna set you as a repo admin. Feel free to commit fixes and such. Continue to send major changes or controversial changes as PRs to get conversation. Thanks for all the help!

**Comment by negue** [comment] 2014-09-08 20:31
@Alys with the first users.json I could login using email addresses, gonna test the new json too (maybe tomorrow)

On my local server I've send me an invitation to a party, and there was no error.

Next try is starting a quest (first time, since I don't have any party online xD). 

@lefnire Gonna check the PUT/POSTS too. ... Wow thank you. I really appreciate it. Got it. Major Changes as PR. Small changes like adding a css class / a style property & stuff are good to push without PR?

**Comment by Alys** [comment] 2014-09-08 20:40
@negue : _"with the first users.json I could login using email addresses"_ That's interesting. It means the accounts and passwords are valid, which is a relief. Were you using all lower-case when you were entering the usernames?

**Comment by negue** [comment] 2014-09-08 20:59
yep all in lower case

**Comment by negue** [comment] 2014-09-08 21:24
Current State:
- POST questAccept?force=true
- POST questAbbort 

... returning the Group Object with a members array BUT here the memberArray is just an array of IDs, instead of member objects, this is why "member._id" is undefined

**Comment by negue** [comment] 2014-09-08 21:36
Sorry for spam :D

I think I found the "solution" , we have to add a `populateQuery(gid, group);` on questAccept / questAbbort (maybe some others ) to get the real member objects, will test this tomorrow

I think if we just add it in api.attachGroup will create more bugs / changes than needed

**Comment by negue** [comment] 2014-09-18 09:40
Now that #4010 is merged, we could "re-revert"  the "ngRepeat with Track By" Checkin.

@paglias Could you do that?, I'm not that experienced with Git yet

**Comment by paglias** [comment] 2014-09-18 16:44
@negue re-reverted https://github.com/HabitRPG/habitrpg/commit/7e53eaf1aee25984142832e753ddb3b0aaf1b46f check if all is ok

**Comment by negue** [comment] 2014-09-18 17:01
Thanks!

Yes works as expected and without this issue here. So I'll close it.

@Alys Now we can celebrate the 4000th Issue :D

**Closed as completed by negue** 2014-09-18 17:01 UTC
