### ISSUE TITLE
Restore password. Bug, no documentation?

### ISSUE THREAD

**Issue by sergey-prosvirnin** [HabitRPG/habitica#12307] opened 2020-06-15 17:34 UTC
Hi, I use habitica and habitrpg-email-server + Mandrill API. I want to do a password recovery via a link and have created a corresponding template for that. 

![image](https://user-images.githubusercontent.com/24830345/84687615-b2c44480-af46-11ea-8634-9b96fb879aa1.png)

But when I try to click the link I get a 404 although this URL is sent in the habitrpg-email-server request. What could be the error?

![image](https://user-images.githubusercontent.com/24830345/84687696-cec7e600-af46-11ea-891c-9fbd94e60357.png)
![image](https://user-images.githubusercontent.com/24830345/84687738-df785c00-af46-11ea-98ae-bae8b1c8f8bb.png).
![image](https://user-images.githubusercontent.com/24830345/84688135-80671700-af47-11ea-897e-6941a5d479eb.png)

Also, it should be noted that the request to send an email is sent through the habitrpg-email-server, is only made when in the file \website\server\libs\email.js check for Boolean value IS_PROD, because the token "IS_PROD": "true" in the file config.json is not read and by default is always false. How do I fix this unusual behavior?

![image](https://user-images.githubusercontent.com/24830345/84687973-34b46d80-af47-11ea-9261-e4e8a0010b17.png)

**Comment by paglias** [comment] 2020-06-15 21:31
I'm going to close this issue as it's a duplicate of https://github.com/HabitRPG/habitrpg-email-server/issues/17

**Closed as completed by paglias** 2020-06-15 21:31 UTC
