### ISSUE TITLE
Dying after logging in later in the day

### ISSUE THREAD

**Issue by Ocny** [HabitRPG/habitica#3115] opened 2014-03-20 20:19 UTC
This is sorta a mobile issue too, but I figured I should put it here since it concerns the actual website as well. (If I need to move it, let me know). I have also looked around to see if this has already been posted, but I couldn't find anything. I'm sorry if this has already been addressed!

I have Habit bookmarked on my iPhone's home screen, so I can go to it like an app, but it is the mobile website it takes me to (not the actual app). However, when I use it on my phone after midnight to log a completed to-do, and then log on from my computer later in the day, it tells me I have died because it thinks I didn't do any of my dailies. I haven't changed the time settings, at least not that I know of. Is there any way to avoid this problem?

Browser: Chrome
ID: 6ff972d2-1aee-4895-b750-31d5cf32dce8

**Comment by deilann** [comment] 2014-03-20 20:22
If you haven't changed the time settings, you cannot log dailies after
midnight for that day, and you will take damage regardless. If you need to
log dailies after midnight, either turn them into "yesterdailies" (did x
task yesterday) or set your custom day start past midnight.

**Comment by Ocny** [comment] 2014-03-20 20:28
The issue isn't logging dailies for the previous day, it's starting a new day and logging a to-do, and then dying because (I think) the system thinks I didn't do those dailies (because it's after midnight, and they've reset).

**Comment by deilann** [comment] 2014-03-20 20:31
Okay, not entirely sure I'm understanding your issue.

Let's talk about two hypothetical days: April 1st and April 2nd.

You log onto your phone to check off a daily after midnight. Are you trying
to check off that daily for April 2nd or for April 1st?

If the issue is that you're trying to check it off for April 1st, see my
previous comment.

If the issue is that you're trying to check it off for April 2nd, make sure
that you refresh your browser (on both your phone and your computer). One
of two things is happening:

Either your phone pulled from the cache and still thinks it's April 1st
because it hasn't updated

or

It's not saving to the server due to the sever issues we've been having.

By refreshing after midnight, you can defeat the former and by refreshing
after checking off (and near the end of the day) you can defeat the latter,
making sure everything saved to the server.

**Comment by Ocny** [comment] 2014-03-20 20:36
It is after midnight on April 2, and everything has reset. I then check off a to-do, because I completed a homework assignment. I then log in on my phone again when I wake up and log a daily or two, with no issues. When I log in that evening (April 2) on my computer, I am notified that I have died.

**Comment by deilann** [comment] 2014-03-20 20:40
Are you questing?

**Comment by Ocny** [comment] 2014-03-20 20:42
Yes, I am, but this has happened previously when I wasn't questing.

**Comment by deilann** [comment] 2014-03-20 20:43
Can you still do me a favor and see if the damage you're taking from questing would be enough to kill you?

**Comment by Ocny** [comment] 2014-03-20 20:46
The last damage I was dealt from the boss was 13.7.

(Also, thanks for helping out! I really appreciate it)

**Comment by deilann** [comment] 2014-03-20 20:48
It's not a problem. I get XP for it. ;)

Are you questing solo or are there others in your party?

**Comment by Ocny** [comment] 2014-03-20 20:49
Very nice!

It's just me doing this quest.

**Comment by deilann** [comment] 2014-03-20 20:51
Okay, my guess here then is that the server is not actually syncing on
mobile. What you're seeing is just your side. If you can, press the sync
button after midnight and regularly sync if you're using multiple devices.
Let me know if that helps.

**Comment by Ocny** [comment] 2014-03-20 20:55
Thanks, I'll do that tonight and see how it works out. If I'm still having the issue, I'll let you know! Thanks a bunch.

**Comment by deilann** [comment] 2014-03-20 20:57
No problem! If it works out tonight, please go ahead and close the ticket.
If it crops up again, the ticket can always be reopened.

**Comment by Ocny** [comment] 2014-03-21 14:10
Everything looks like it's working. Thanks!

**Comment by Ocny** [comment] 2014-03-21 14:11
Actually, just now when I clicked on one of my habits (the first thing I marked today), I died.

**Comment by deilann** [comment] 2014-03-21 16:26
And you synced your desktop computer before clicking that habit?

**Comment by Alys** [comment] 2014-12-12 08:39
@Ocny I'm closing this because it's been a while since there's a report of the problem happening, but if it's still happening, definitely comment here and we'll reopen this!

**Closed as completed by Alys** 2014-12-12 08:39 UTC
