### ISSUE TITLE
Can't add more than one anything

### ISSUE THREAD

**Issue by Lukking** [HabitRPG/habitica#896] opened 2013-05-05 09:37 UTC
Hey im using Windows 7 and the latest version of Chrome. I can not add more than one Habit, daily or todo. If i Create a new Daily for example, it replaces the habit with all its characteristics (checkbox).
Refreshing does not help.

**Comment by lefnire** [comment] 2013-05-05 09:43
dupe of #891 follow up there

**Closed as completed by lefnire** 2013-05-05 09:43 UTC
