### ISSUE TITLE
proxy / cache the static pages

### ISSUE THREAD

**Issue by lefnire** [HabitRPG/habitica#4746] opened 2015-02-24 19:48 UTC
Every hour, on the hour, we get a major surge of traffic which causes HireFire to scale us up and NR to wig out - but it only lasts for 3mins or so (so it's not too critical). Smoking gun: getting indexed / crawled by various search engines, site rankers, etc. Solution: use a proxy or caching setup to host our static pages, particularly the home page. There's an AWS S3 ticket floating around, may want to merge these two?
##

**Comment by davidmanheim** [comment] 2015-02-25 03:46
The site seems not to have a robots.txt file; that seems like step 1; block the parts of the site that create heavy load. If the issue is that Node.js on the servers is causing the slowdown, (ie the Heroku dynos,) that can be blocked in this way as well; you probably can figure out what specifically to block on the site to stop robots from hitting things that need Node instances. (I suspect simply blocking the /nodal/ subdirectory in the robots.txt will fix most of this, but I'm not yet familiar with the site structure.)

**Comment by lefnire** [comment] 2015-03-10 20:31
@davidmanheim thanks! I'm a bit n00b on robots.txt, would this do it? https://github.com/HabitRPG/habitrpg/commit/c5240da81f3d4bbb190150cd62a730800e5ec02e (/static/\* should be allowed for now)

**Comment by davidmanheim** [comment] 2015-03-13 05:28
I'm not sure; there are probably utilities for testing what it would do.

**Comment by davidmanheim** [comment] 2015-03-13 13:50
According to http://tools.seobook.com/robots-txt/analyzer/, this blocks all robots from the site completely; you can also check https://support.google.com/webmasters/answer/6062598?hl=en

**Comment by davidmanheim** [comment] 2015-03-13 15:18
I submitted a new pull request with one tested as working - I'm not sure if it fixes the problem, but it shouldn't break everything. The current (updated) version still seems to block all robots from the main site.

https://github.com/HabitRPG/habitrpg/pull/4854

**Comment by Alys** [comment] 2016-06-04 06:41
Is this still needed? Something to consider for the website rewrite?

**Comment by paglias** [comment] 2016-06-04 08:57
@Alys absolutely something we still want

**Comment by lemoness** [comment] 2017-10-16 20:36
@paglias Should I remove the "on hold" label or has this already been handled?

**Comment by paglias** [comment] 2017-10-16 20:37
Let's close this as it'll be handled by another issue

**Closed as completed by paglias** 2017-10-16 20:37 UTC
Labels: priority: medium, status: issue: on hold
