### ISSUE TITLE
Paypal button redirects to an empty page

### ISSUE THREAD

**Issue by richardschembri** [HabitRPG/habitica#2535] opened 2014-01-23 18:52 UTC
When clicking on the "buy now" button of the paypal option it simply redirects into an empty page "about:blank"

**Comment by zoebeagle** [comment] 2014-01-23 21:12
I can confirm this is happening in Chrome - Windows 7.
Looks like something wrong with [object Object] not getting resolved:

`<form method="post" action="https://www.[object Object].paypal.com/cgi-bin/webscr" class="paypal-button ng-pristine ng-valid" target="_top">`
and
`<input type="hidden" name="env" value="www.[object Object]"><input type="hidden" name="custom" value="?uid=e09e3b3c-a2ac-4a01-ab6e-739e83c79115&amp;apiToken=2486d660-f562-420a-bedc-cf3e0289fa33">`

**Comment by colegleason** [comment] 2014-01-23 21:15
There is an issue where the `env` for Paypal button is being concatenated
incorrectly. I have not figured it out yet.

On Thu, Jan 23, 2014 at 3:12 PM, zoebeagle notifications@github.com wrote:

> I can confirm this is happening in Chrome - Windows 7.
> Looks like something wrong with:
> 
> <form method="post" action="https://www.[object Object].
> paypal.com/cgi-bin/webscr" class="paypal-button ng-pristine ng-valid"
> target="_top">
> and
> <input type="hidden" name="env" value="www.[object Object]"><input
> type="hidden" name="custom"
> value="?uid=e09e3b3c-a2ac-4a01-ab6e-739e83c79115&amp;apiToken=2486d660-f562-420a-bedc-cf3e0289fa33">
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/HabitRPG/habitrpg/issues/2535#issuecomment-33169061
> .

## 

Cole Gleason
Student, University of Illinois at Urbana-Champaign
Computer Science, Class of 2015
cg@colegleason.com | colegleason.com

**Comment by colegleason** [comment] 2014-01-24 02:50
Gah. I can't seem to replicate this on my local instance. @lefnire are the bower components live up to date with whatever my local install would have?

**Comment by SabreCat** [comment] 2014-01-24 03:58
Ah, and this is in turn a duplicate of #2492. I think. If I'm mistaken, @colegleason, feel free to reopen.

**Closed as completed by SabreCat** 2014-01-24 03:58 UTC

**Comment by colegleason** [comment] 2014-01-24 04:26
Ah yes, sorry.
