### ISSUE TITLE
Very large Guild member counts overflow the badge

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#10753] opened 2018-10-11 19:44 UTC
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)

### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)

When a Guild reaches something like 100,000 members, it stops displaying nicely in its member count badge:

https://i.snag.gy/8ncewM.jpg

and in the Guild info itself:

https://i.snag.gy/cm7TCb.jpg

We should probably round these off to remove the decimals, or expand the badge area to fit the count.

**Comment by Dimini** [comment] 2018-10-14 21:45
Hello, I'd like to work on this issue :)

**Comment by SabreCat** [comment] 2018-10-15 05:11
@Dimini OK, go for it, with our thanks! Let us know here or in the Aspiring Blacksmiths Guild if you need a hand with anything.

**Comment by Dimini** [comment] 2018-11-04 21:22
Issue reproduced.

**Count display in the member count badge overflows** -  reproduced after I changed the Guild Member count to 100 010 and more.
**Count display in the Guild info overflows**- reproduced after I changed desktop resolution to value below 1024x768 or after I reduced the size of the window + I changed the Guild Member count to 1010 and more.

The necessary ingredient is to have more than 1k members and the **second to last digit** is not 0.

Thus, 1100 is displayed as 1.1k which is ok, 1101 as 1.1k as well which is ok, but 1010 as 1.01k which is not ok.

I'm going to reduce the number of decimal digits to 1 first and test the results.

**Comment by Dimini** [comment] 2018-11-04 23:43
**Reducing the amount of decimal numbers to 1** resolved the first issue - **Count display in the member count badge overflows**.

With the same solution **the second issue - **Count display in the Guild info overflows** - is resolved for resolution 1024x768**.

For 800x600 however, the issue still persists. Removing the decimals completely would result in slight overflow for 800x600 resolution.

**Moreover, I used `floor` function instead of the `round` function to avoid rounding up.
Eg. If the guild has 4567 members, it shouldn't show 4.6k. It will show 4.5k.**


Regarding the second solution proposed by @SabreCat , the badge would have to be increased in size by at least 15px for the text appear inside the text area. The badge however shouldn't change size, a new badge image with wider text area could be created for Guilds with more than 100k members.

The main root cause of the second issue - **Count display in the Guild info overflows** - is that while the graphical components are browser responsive, the text is not. This way the text area is shrinking with the decrease of resolution and the text overflows.

**Comment by Dimini** [comment] 2018-11-04 23:45
I propose decreasing the amount of decimal places from 2 to 1 for Guild Member Count and using the `floor` function instead of `round` in groupsUtilities.js.

Creating merge request.

**Comment by paglias** [comment] 2018-11-17 10:06
Fixed in #10812

**Closed as completed by paglias** 2018-11-17 10:06 UTC
Labels: priority: minor, status: issue: in progress, section: Guilds
