### ISSUE TITLE
Party chat broken on beta

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#1900] opened 2013-11-23 23:10 UTC
Party chat on beta is broken :( I can't post any comments. I have to switch to non-beta to do so. Tavern works fine.

**Comment by DanielTheBard** [comment] 2013-11-23 23:48
You can post. You just have to hit enter to post. Was just going to make a ticket for this. Party and Guild chat won't let you hit the post comment button. Pressing enter to send works fine though.

**Comment by snicker** [comment] 2013-11-24 00:38
Issue confirmed, has to do with some of the styling changes made for markdown. The element for chat is actually "covering" the buttons. You don't experience this in Tavern because of the message below the chat box. Will push a fix

**Comment by snicker** [comment] 2013-11-24 00:46
fixed in https://github.com/HabitRPG/habitrpg/commit/b793d2b753535a5cd51a06f6a5bd40c3a8250abd

**Closed as completed by snicker** 2013-11-24 00:46 UTC
