### ISSUE TITLE
Tags completely disappeared after I refreshed the page

### ISSUE THREAD

**Issue by rezby** [HabitRPG/habitica#2370] opened 2014-01-11 22:56 UTC
There's not much other detail that I think will be relevant here. I'm level 5, started a week ago or so, maybe a little less.

I made half a dozen tags or so, for the various related games I do and the tasks I wish to complete in them, made some school and personal related tags, and went through all my habits and dailies and tagged each one with a single tag - one had two tags, but that's it. I have about 20 habits and 7 dailies, and they were all tagged. 

Today I opened my laptop, awakened it from its slumber, refreshed the page so the dailies and everything would update, then checked off the dailies I did today and the habits I did today so far. Then some hours later, I remembered something else I want to be a habit so I added some more and tagged them. When I went to go see my tags though, I found out that even though all my habits and dailies still show their "I am tagged" icon right next to the "edit" icon, their tags have been cleared. 

I don't know if its something I did, or if it is in fact that they just spontaneously cleared themselves after a set interval like issue 1528 says.

**Comment by scheidm** [comment] 2014-01-24 14:26
This may be related to this issue, which is listed as closed. I don't think it was successfully resolved:

https://github.com/HabitRPG/habitrpg/issues/2172

My experience: Yesterday I created half a dozen tags, and applied them in different combinations across habits, tasks and dailies. I was able to filter across all of them as usual. Today, when I load the page, the tags are listed as viable filters, but they pull up no results, and opening tasks I'd edited confirmed they did not still have the tag. 

Of possible note, one tag included the unicode character ™, I added about 6 tags all at once and saved them together, and as the above user the issue didn't present itself until I went back to the website the following day.

**Comment by lorian** [comment] 2014-01-25 22:46
Just to add to the data, for me, the items became untagged just an hour or so after I tagged them.

**Comment by jelena121** [comment] 2014-02-05 16:23
I've been having the same issue. Some of my tags get saved, but some of them disappear shortly after creating them.

**Comment by the-dubya** [comment] 2014-02-27 16:24
I'm having this same problem.
My tags don't have any special characters in them. Some of them have a space, but even the ones that are a single word disappear. 
The posts are all marked as tagged, but they can't be filtered by the tag. When I go to edit them, it shows no tag selected.

I hope this gets fixed soon because I added many to-do's on my list and it's overwhelming looking at them without it being sorted out.

**Comment by elprohabro** [comment] 2014-04-12 19:43
When you create tags, you have to refresh page after creating. Only then add new items. This way all tag connections will remain.
Otherwise they all will lose connection after refreshing.

**Comment by jojoyuji** [comment] 2014-05-07 03:37
Same issue here. This is bad since tags are critical for my workflow.. :(

**Comment by deilann** [comment] 2014-05-07 03:43
@jojoyuji See what @TheManniest said. If you refresh after creating the tag, it should stick proper.

**Comment by jojoyuji** [comment] 2014-05-07 03:50
Really @deilann? 
I dont think it's a solution at all. Cmon, this can be better, huh? 

I can't accept such solution, if this is for real then I shall fix it in a push request then. 

Bad ux: frustrating experience with this tag implementation.

**Comment by deilann** [comment] 2014-05-07 03:54
It's a workaround, not a solution. :) I'm not saying that it's desired, but
this isn't top priority right now, and I wanted to help you get your
workflow working.

But if you want to fix it, that would be fab! In fact, that would be more
than fab!

**Comment by jojoyuji** [comment] 2014-05-07 12:21
I love AngularJS, so, wait for my push request!

But again, It's impossible to create another board. As result, ToDo's board becomes all cluttered and messy. 
The workaround is tags implementation. So I dunno which priorities are ahead but it seems to me very critical for organization and since organization is the business of this app, I wonder why it's not that important. 

:)

**Comment by deilann** [comment] 2014-05-07 12:39
Because we all work full time on top of volunteering our time for Habit and
there are critical bugs and needed features that need attending to that
don't have workarounds.

Tags work perfectly fine as long as after you create the tag, you refresh
the page. It is only immediately after creating the tag that they cause
this issue.

**Comment by van-dell** [comment] 2014-07-09 20:02
The problem's still present - just for the record. Glad there is a workaround, though.
I consider noteworthy that all tasks retain the little black icon for "has a tag" correctly, even though when you open them no tag is checked.

**Comment by Alys** [comment] 2014-07-09 20:25
van-dell: _"all tasks retain the little black icon for "has a tag" correctly"_  That's expected. What happens is that when you first create a tag, the tag is assigned a unique ID number. If you then immediately assign the tag to a task without reloading the page first, that ID number is put into the task's "tags" data (which causes the black tag icon to appear). However on reload, the new tag is actually given a different (permanent) ID number and this means that the original ID number no longer points to that tag, so the task is no longer recognised as being tagged with that tag. However the original ID number IS still in the task's "tags" data, so the black tag icon still appears. When you open the task for editing, no tag is checked because HabitRPG then recognises that the original ID number does not apply to any current tag.

It's annoying and will be fixed one day, probably when one of the volunteer programmers has free time to do so, or when the staff programmers run out of more serious bugs. :)

**Comment by lorian** [comment] 2014-07-09 20:27
Wow, THAT's what's going on? Good to know!

**Comment by van-dell** [comment] 2014-07-09 20:32
So to clean that up I'll have to recreate all the habits that are broken. Not today :) Thanks for the clarification.

**Comment by Alys** [comment] 2014-07-09 20:34
If you're going to re-assign a tag to those habits, there's not much point cleaning up the broken tag. Once a tag is correctly assigned with it's permanent ID, the old, unused tag ID won't have any effect. I have several tasks where there's an old incorrect ID as well as a correct one, and it doesn't cause any problems.

**Comment by Alys** [comment] 2014-09-02 20:26
See also https://github.com/HabitRPG/habitrpg/issues/2856

I've proposed a fix here: https://github.com/HabitRPG/habitrpg/pull/3970

**Closed as completed** 2014-09-02 21:50 UTC
Labels: priority: important, status: issue: needs investigation
