### ISSUE TITLE
Custom Day Start Reset

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica#1929] opened 2013-11-27 07:42 UTC
Just checked, and my custom day start was reset to zero. Lots of complaints in the tavern, too - this is going to cause a lot of deaths if it isn't fixed soon.

**Comment by ghost** [comment] 2013-11-27 07:47
Yes, mine was as well. I was changing my end of day from 2 to 3 (it was just after midnight when I was doing this) and the page reset to zero. Not sure if my fussing with the time contributed.

**Comment by Esstheruth** [comment] 2013-11-27 08:02
My custom day start had been 3 a.m. for two weeks already, and my day reverted back to midnight after I clicked on one of my dailies around 12:45 a.m. Lost HP and had to reset several daily streaks.

**Comment by JesperDramsch** [comment] 2013-11-27 08:22
Mine was at 7 am and reset in the middle of the night. When I set it back to 7 this night, the dailies did not reset at said time.

**Comment by veeeeeee** [comment] 2013-11-27 08:22
Clicked a couple things after midnight; page reloaded with clean dailies and a daily start time reset to midnight. Also nearly died as a result, which was, erm, interesting.

**Comment by FireNRice** [comment] 2013-11-27 08:37
Logged in to check off some dailies and was already dead.  My custom day start was set at 4AM, and it got reverted to midnight.  Lost armor, over 1300 gold and experience points.

**Comment by etryn** [comment] 2013-11-27 08:56
Happened to me too. Fortunately I didn't die-- sorry to those of you who did! Hopefully you can restore!

**Comment by Mousekiro** [comment] 2013-11-27 10:05
Hit me last night, too. I didn't die, but I went to check off one of my kitchen-cleaning dailies before bed only to find all my dailies unchecked and some of them had lost their streak. When I figured out what had happened, I changed the day start back to 6:00, but I was still quite wary, so I stuck myself in the Inn. Which is a good thing, because when I logged on this morning, it was back to 0:00 again. Seems every time I reload the site, it has decided anew that I want to reset at midnight.

**Comment by Blauelf** [comment] 2013-11-27 12:02
As mousekiro said, custom day start seems to reset on every reload/sync. Language preference, which also got reset from English back to my browser's default, does not.

**Comment by eiron** [comment] 2013-11-27 13:18
This has also affected me. But with my other issues due to heavy load restoring the streaks is a bit of an arduous task, as I get frequent browser locks. I am often busy until after midnight, so I need those extra hours for last-minute checking before I do finally get to bed.

**Comment by paglias** [comment] 2013-11-27 14:42
@lefnire I think that https://github.com/HabitRPG/habitrpg/commit/2b128f71f45b2b3cb873eacbe36f8212f28a1dad is preventing any value other than 0 from being used.

You can set values client-side as long as you don't try to delete the old value, because it will set it to 0, you can only replace it with a number by selecting the old value. And server-side is always resetted to 0.

**Comment by wisteriacs** [comment] 2013-11-27 15:02
- 1 here -- On the mobile app it suddenly said I was Dead. Luckily it gave me a chance to screen-shot my stats before "reviving"!

**Comment by paglias** [comment] 2013-11-27 15:11
Sorry about this guys, it's now fixed (**not live on the site yet!**) but for every one who logged in in the last hours the custom day start has been resetted to 0, we may restore old values from a backup but let's wait for @lefnire

**Comment by lefnire** [comment] 2013-11-27 18:14
@paglias fixed this, I've deployed fix to both production & beta. I've also ran a migration to restore 0'd dayStarts for users who haven't manually updated after the bug. Everything should be good now, thanks @paglias, and sorry everyone.

Some background on what happened. There were a lot of users whose dayStarts wasn't a whole number (eg `2`), but they were entering `2:00`, which caused Mongoose cast errors, and their accounts couldn't load. I added some validation yesterday to change the dayStart to 0 if it wasn't a proper number, but there was a bug in the validation (which @paglias fixed)

**Closed as completed by lefnire** 2013-11-27 18:14 UTC

**Comment by paglias** [comment] 2013-11-27 18:16
@lefnire could be that a cause for all that mess with custom day start not working? The fact that validation prevents deleting the hour (in order to change it) and that it's saved at every change (for example when using the increase/decrease button) is quite annoying

**Comment by lefnire** [comment] 2013-11-27 18:21
You mean could the other dayStart issues be connected to invalid dayStart (ie, before this push)? I don't think so, to be honest.. I think their accounts wouldn't even load at all when they had invalid dayStarts. I got some emails, people saying "I get red errors and no tasks", and this was the cause

**Comment by paglias** [comment] 2013-11-27 18:23
it would have been too easy :(

**Comment by lefnire** [comment] 2013-11-27 18:24
I know :( I thought about it too, a brief glimmer of hope and then "oh... no..."
