### ISSUE TITLE
Tags not removed when saving

### ISSUE THREAD

**Issue by sqhendr** [HabitRPG/habitica#7565] opened 2016-05-31 18:22 UTC
When I create a new task and remove a tag, after saving it, the tag is reapplied. For example, if I create a new task with no tags filtering my tasks, it automatically applies "personal" and "work." If I then go back and try to remove "work," and save the task, the "work" tag is still applied. 

UUID: 15ff046a-e882-49eb-b5b9-910c56b0a2be
Browser: Tried on Chrome and on Vivaldi
OS: Windows 7

**Comment by SabreCat** [comment] 2016-05-31 18:22
Duplicate of #7412. Will be fixed later today!

**Closed as completed by SabreCat** 2016-05-31 18:22 UTC
