### ISSUE TITLE
Duplicate hatching potions or eggs dropped

### ISSUE THREAD

**Issue by fuzzytrees** [HabitRPG/habitica#901] opened 2013-05-06 14:52 UTC
A few minutes ago, I got a notification that a shade potion dropped. I now have two shade potions in my inventory. A day or two ago the same thing happened with a base potion, but I sort of thought I had just missed the first base potion somehow. The single pet egg and CottonCandyPink potion I had drop somewhere between several days and a week ago were unaffected.

(I'm on playing on Chrome and using Windows, in case that's relevant.)

**Comment by cleave29** [comment] 2013-05-07 05:29
I had this happen twice to me a couple days ago, but after that I went back to getting a single drop.  (2 dragon eggs and then two skeleton potions).

**Comment by fuzzytrees** [comment] 2013-05-08 14:56
Ok, I got a single skeleton potion this morning, so maybe this has been resolved?

**Comment by cleave29** [comment] 2013-05-08 18:26
I got another double after getting the aforementioned single.

**Comment by lefnire** [comment] 2013-05-08 19:01
Naw, this bug hasn't been addressed yet. It's definitely there (seen it
myself), but not too urgent since it's hooking people up - will hit it soon

**Comment by switz** [comment] 2013-05-08 19:24
I've been looking into this. Still haven't found the cause.

**Comment by cleave29** [comment] 2013-05-08 20:31
lol.  Yeah, I wasn't too anxious to report it.  :)

**Comment by Shaners** [comment] 2013-05-08 20:37
Hmmm bug... or feature??? Just call it a crit drop!

**Comment by lefnire** [comment] 2013-05-10 21:32
Starting to look like the duplicate chat messages bug, which I fixed with a super-hack: https://github.com/lefnire/habitrpg/commit/fb29e35ffcd63b2aec0d3e914aa3308d863755d3. I'm pretty sure what happens is `model.push` / `model.unshift` - if it detects the `txn` didn't sync right away (slow connection or what have you) - will queue to attempt again. However, all attempts will go through successfully. By this theory eggs should have the same problem; however, potions are more common, so... I'll dig in soon to see if it's a Racer bug I wouldn't be in over my head to address.@switz - noteworthy.

**Comment by lefnire** [comment] 2013-05-10 21:34
Actually a kink that's caused me to hesitate continuing down the refLists -> arrays migration (since refLists uses `model.id`s which establishes uniqueness & mitigates duplicates)

**Comment by switz** [comment] 2013-05-10 21:35
> I'm pretty sure what happens is model.push / model.unshift - if it detects the txn didn't sync right away (slow connection or what have you) - it will queue the attempt again. However, all attempts will go through successfully. By this theory eggs should have the same problem; however, potions are more common, so... I'll dig in soon to see if it's a Racer bug I wouldn't be in over my head to address.

@slaks Sorry to be a bother, but have you seen this faulty behavior at all?

**Comment by SLaks** [comment] 2013-05-10 21:44
Not offhand.

It might be related to codeparty/racer#115

**Comment by lefnire** [comment] 2013-05-10 21:49
Don't know why, but I got a kick out of that technical jargon -filled ticket [when suddenly](https://www.evernote.com/shard/s17/sh/8517ca34-e024-4209-a876-946d835d2e9b/258e696336702cbb12cfa2642dc408aa). Cool, that will give me a lead to look into - thanks Schabse!

**Comment by zoebeagle** [comment] 2013-05-10 22:39
I just had this happen (with a cactus pet)... but it wasn't until a few minutes later when I was closing my tabs that I realized I had Habit open in two different tabs.  Could this be the cause?

**Comment by lefnire** [comment] 2013-05-10 22:59
Hmm, that's some useful info - but I don't think it's necessarily the case.
I'll spam duplicate chat messages in party / tavern with only one browser &
tab open, and they're using the same constructs so definitely related

**Comment by switz** [comment] 2013-05-12 04:44
Tyler, let's just add a timestamp for the last drop and if it's a 5 min or less difference, nix it. A crappy hack, but it'll at least fix the issue for now. If you think it sounds good, I can try to implement it.

**Comment by lefnire** [comment] 2013-05-12 07:19
Well - i don't think that's the problem, actually. I think the problem is
in model.push / model.unshift. The issue I was experiencing in chat, I
noticed all the chat objects had the same id. Which means that the calling
function wasn't being called multiple times (since it's set as {id:model.id(),
text:...} - but something within model.shift/push was sending to the
database multiple times.

IE, even if we did the timestamp trick (which actually is a fantastic idea
if it worked, and would prevent spamming for your egg) - I still don't
think it would work.

Does that explanation make sense?

**Comment by switz** [comment] 2013-05-12 07:23
Yeah.. that makes sense. I'll do some tests and see if it would work. Have you been able to reliably recreate it? I assume it happens under a bad connection which is tougher to replicate locally.

**Comment by lefnire** [comment] 2013-05-12 07:32
Exactly that. Yeah, I'm trying to think of how to test it locally myself
for that reason

**Comment by switz** [comment] 2013-05-12 07:35
How about http://slowyapp.com/?

edit: there's also a fully free one from apple that you can download on top of xcode.

**Comment by lefnire** [comment] 2013-05-12 07:39
That looks cool! Hopefully works for localhost too. Have at it, will play
with m'self soon

**Comment by lefnire** [comment] 2013-05-12 07:40
Also, I'm curious about SLaks private/public path setting comment. Mayhap
we have surrounded our model.unshift/push within that scenario?

**Comment by SLaks** [comment] 2013-05-12 12:48
You can also run `DERBY.app.model.socket.disconnect()` in the client console to close the socket connection, or you can use your OS tools to forcefully close the actual WebSocket.

**Comment by zoebeagle** [comment] 2013-05-14 12:51
I just got double potions again (they were Desert potions if that makes any difference)... but, I have received two pet eggs and did not get doubles of those.

**Comment by fuzzytrees** [comment] 2013-05-15 16:25
I continue to have some double-drops and some regular.

Also, since @lefnire thinks these are related and I can't find an existing ticket for it:
I had a party chat message post _eight_ times. This also happened to be right before the server crashed.

Uh. I just went to check the timestamp on the message, and all the party chat message history is gone? That's not good.

**Comment by fuzzytrees** [comment] 2013-05-15 17:31
Is the Delete action queued in the same way the Post action and Drop action is? Because all the party messages disappeared right after I deleted the extra seven of my messages.

**Comment by lefnire** [comment] 2013-05-23 17:20
likely a result of https://github.com/codeparty/racer/issues/109 . A bit out of my jurisdiction at present, but I'm hoping migrating to Racer 0.5 will fix this: https://groups.google.com/forum/?fromgroups#!topic/derbyjs/6g7vMJ4FraI

**Comment by cleave29** [comment] 2013-05-25 17:07
OK, I had 4 dragon eggs drop all at once.  And it also unchecked a daily I had just checked (and gave me another one in the streak than I earned.)

**Comment by lefnire** [comment] 2013-05-25 18:50
This should be fixed now. The fix is somewhat a side effect of https://github.com/lefnire/habitrpg/issues/1039, and doesn't really address the real problem.

habitrpg-shared calculates all changes on the user object (not model), and then saves back all those changes via `model.set()`. This means drops are pushed onto the plain JS user object arrays, and then those whole arrays are saved as-is to the database. The underlying problem with this ticket is that `model.push` and `model.unshift` are tres buggy, causing duplicates - which means this fix won't solve the chat issue, or other things like that.

Since this isn't really in my realm to fix (it's a Racer issue), I think our best bet will be the migration to Racer v0.5, which we will be doing very soon. It should solve very many other issues too, such as multiple computer connections and data loss.

If anyone experiences this bug again going forward, please ping me

**Comment by cleave29** [comment] 2013-05-25 19:23
OK, thanks!

**Comment by paglias** [comment] 2013-09-09 17:51
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!

**Closed as completed by paglias** 2013-09-09 17:51 UTC
Labels: priority: important
