### ISSUE TITLE
[API v3] Deleting a challenge will not return gems back to owner

### ISSUE THREAD

**Issue by cTheDragons** [HabitRPG/habitica#7376] opened 2016-05-20 04:56 UTC
General Info
- bc10ec41-4213-4482-bbb8-558e3c3ea8d5
- Opera   37.0.2178.43
- Windows 8.1 32-bit
- Create a challenge with X number of gems. (Examples used 16 & 2)
- Remove yourself as the participant of the challenge.
- Save.
- Open the challenge by itself through the guild link.
- End challenge.
- Gems are not return.
  This was for challenges created prior to migration and new challenges.

**Comment by Alys** [comment] 2016-05-20 05:22
If that was in the Tavern, it's expected behaviour and occurs in the current live site as well. It's possible (likely?) that we'll be changing it in future, but for now we're keeping the same behaviour. Refs: https://github.com/HabitRPG/habitrpg/issues/7272#issuecomment-219680193 and https://github.com/HabitRPG/habitrpg/pull/5137

If it was in a guild or party, please tell us!

**Comment by cTheDragons** [comment] 2016-05-20 07:58
It was in the [⚔ The Duelling Grounds ⚔](https://v3.habitica.com/#/options/groups/guilds/2f6085fe-5382-46d6-a0ac-c1b16f4f7780).

I believe it has worked for me in the actual site.

**Comment by Alys** [comment] 2016-05-20 08:24
Darn. I don't suppose the gems reappeared later after a sync or reload?

**Comment by cTheDragons** [comment] 2016-05-20 08:29
The first 16 gems no. The other 2 did.

Just testing again in Tavern, Dueling ground and party now.

**Comment by cTheDragons** [comment] 2016-05-20 08:42
Ok 
Created 2 gems in my party
Created 3 gems in Duelling Grounds
Created 5 gems in Tavern

Results
Ended 3 gems in Duelling grounds and after refresh gems returned
Ended 5 gems in Tavern gems did not return
unable to find 2 gem challenge in Party Page.
![partychallengenotshowing](https://cloud.githubusercontent.com/assets/14116069/15422170/67f02922-1eba-11e6-9be6-feaf7b01bf51.png)

But can see in Challenge Page 
![partychallengeshowinginchallengescreen](https://cloud.githubusercontent.com/assets/14116069/15422171/67f3639e-1eba-11e6-9d3c-d598c682ce3c.png)

(I think I may need to raise a separate issue for this)
Deleting challenge from Challenge screen does return gems after refresh.

**Comment by Alys** [comment] 2016-05-20 08:56
@cTheDragons Great tests, thank you!

> Ended 3 gems in Duelling grounds and after refresh gems returned

Not ideal but we can live with that for a few days. A quick-and-dirty fix would be to call the reload function after a challenge is deleted.

> Ended 5 gems in Tavern gems did not return

Expected behaviour and same as current site, so that's okay (we'll probably change it later).

> unable to find 2 gem challenge in Party Page.

Confirmed (new bug) - after creating a challenge in my party and then going to my party page and reloading it, there's no challenge listed there. However if I go to the party by pretending it's a guild and creating this URL: https://v3.habitica.com/#/options/groups/guilds/bb0b928d-08ea-457b-a6b2-8e1033825b3e
then I can see my challenge in that page. I.e., the code for displaying challenges on a group page does not work for when a party is considered as a party, but does work when the party is treated like a guild. @cTheDragons If you could create a new issue for this, that would be lovely!

**Comment by cTheDragons** [comment] 2016-05-20 09:05
New Issue Done[[API v3] Unable to see challenges in Parties. #7378](https://github.com/HabitRPG/habitrpg/issues/7378)

However I think there is still an issue with "deleting migrated challenges across" as my first challenge of 16 gems was not returned.

**Comment by paglias** [comment] 2016-05-20 09:16
@Alys I'm closing this in favor of #7378. I'll open a new issue about refunding gems for Tavern challenges

**Comment by cTheDragons** [comment] 2016-05-20 09:19
@paglias  This wasn't a Tavern Challenge. It was a migrated challenge in a guild that I deleted. Shouldn't this issue stay open?

**Comment by paglias** [comment] 2016-05-20 09:23
@cTheDragons sorry I missed that part, reopening

**Comment by paglias** [comment] 2016-05-20 10:28
@cTheDragons The issue with old challenges is due to a bug with the migration that has been fixed but will still appear on the testing site because we cannot re-run the migration

**Closed as completed by paglias** 2016-05-20 10:28 UTC
