### ISSUE TITLE
Easy fix bug -- color of 'repeat days' buttons

### ISSUE THREAD

**Issue by catstavi** [HabitRPG/habitica#2951] opened 2014-02-25 05:58 UTC
Under dailies when selecting which days to repeat. You click to select and it changes color. Then you click again to unselect and it changes to a third color instead of back to the original.

**Comment by negue** [comment] 2014-10-11 18:14
Can't reproduce.

Closing this issue for now.

**Closed as completed by negue** 2014-10-11 18:14 UTC
