### ISSUE TITLE
Add "Dequip All" Button

### ISSUE THREAD

**Issue by deilann** [HabitRPG/habitica#3730] opened 2014-07-13 18:41 UTC
We've got a slew of issues that have to do with not being able to dequip items, pets, or mounts if you don't own something in the right category.

I propose an easy fix:

Add a "Dequip all items" button in Settings. It would reset the avatar to not have anything equipped at all -- no armor, no pets, no mounts.
#### EDIT April 2016:

This is mostly fixed by https://github.com/HabitRPG/habitrpg/pull/4799 which dequips:
- user.items.currentPet even if you don't own that pet
- user.items.currentMount even if you don't own that mount
- the background if any is in use
- all Costume pieces but only if you own those pieces
- all Battle Gear pieces but only if you own those pieces

**We still need a fix for dequipping Costume pieces and Battle Gear pieces that you are wearing but don't own (which can happen occasionally due to unusual circumstances).**
##

**Comment by abustamam** [comment] 2014-07-27 02:35
That seems like a reasonable fix.

**Comment by Alys** [comment] 2014-07-27 07:51
I suggest that it also dequips the background.

It would be lovely if there was an option to either dequip all gear (costume and battle) or only the costume. This button would then make it really easy to start with a clean slate when you want to change your avatar's appearance, which is a daily activity for some of us. :) When doing that, you generally do not want to change your battle gear.

**Comment by deilann** [comment] 2014-07-27 07:51
It could be an at the top equipment button, so it would be mirrored in
costume.

**Comment by Alys** [comment] 2014-07-27 07:54
That would certainly be more convenient to use than going to Settings! I
like that idea.

**Comment by Alys** [comment] 2015-03-14 11:42
I've added this comment to the top post:

This is mostly fixed by https://github.com/HabitRPG/habitrpg/pull/4799 which dequips:
- user.items.currentPet even if you don't own that pet
- user.items.currentMount even if you don't own that mount
- the background if any is in use
- all Costume pieces but only if you own those pieces
- all Battle Gear pieces but only if you own those pieces

We still need a fix for dequipping Costume pieces and Battle Gear pieces that you are wearing but don't own (which can happen occasionally due to unusual circumstances). This is low priority.

**Comment by jihyq9** [comment] 2015-10-03 17:27
I'm going to see if I can make it so Unequip Battle Gear and Unequip Costume removes unowned items.

**Comment by Alys** [comment] 2015-10-03 19:36
@jihyq9 Thank you! Post here if you have any questions, or if you have incomplete code you'd like us to look at, you can submit a pull request, even before it's ready to be merged.

**Comment by youbrokesomething** [comment] 2016-07-26 13:18
@Alys I'm interested in working on this, are there reproducible steps to get myself into the state where I have costume or gear on that I don't own?

**Comment by crookedneighbor** [comment] 2016-07-26 13:55
There's an inventory button in the footer when running a local instance.

**Comment by librarianmage** [comment] 2017-06-06 17:30
Is this still of interest?

**Comment by Alys** [comment] 2017-06-06 19:01
@MathWhiz This part is still needed but still low priority:

"We still need a fix for dequipping Costume pieces and Battle Gear pieces that you are wearing but don't own (which can happen occasionally due to unusual circumstances)."

I.e., the current dequip features would need to be changed to work even when the items you are wearing are not ones you own (pets that have been released; equipment that has been lost and is now appearing in your account with the `false` value). I'm not sure what the current state of the code is so it's _possible_ that change has already been made but I don't recall seeing a change to do that.

**Comment by librarianmage** [comment] 2017-06-06 19:02
Ah, ok

**Comment by SabreCat** [comment] 2017-07-26 00:08
UI feature. Pending until after frontend redesign.

**Comment by librarianmage** [comment] 2017-10-20 22:23
Should this no longer be on hold?

**Comment by Alys** [comment] 2017-10-21 10:51
I'd certainly like to see the dequip buttons come back. They were so convenient. I'm marking this as suggestion-discussion, although it might end up being closed in favour of a new issue that better describes the current situation.

**Comment by lemoness** [comment] 2017-10-23 21:20
De-equip buttons will be coming back, but we need to finalize their designs before making a new ticket, so I'm closing this for now.

**Closed as completed by lemoness** 2017-10-23 21:20 UTC
Labels: status: issue: suggestion-discussion, priority: minor, section: Avatar/User Modal

**Comment by librarianmage** [comment] 2017-10-23 21:23
@lemoness Maybe instead the issue should be labeled on hold: needs designs?

**Comment by lemoness** [comment] 2017-10-23 21:43
No, since most of this is out-of-date, I'd rather make a new ticket when we have the specifics!
