### ISSUE TITLE
Multi eggs

### ISSUE THREAD

**Issue by PazZaitGivon** [HabitRPG/habitica#1007] opened 2013-05-20 22:33 UTC
So, today when the site was going on and offline a lot. I was destined to get an egg, actually I got a potion first but then the site went down and forgot about it. instead of getting one egg... I got eight.... so unless it was a reward for sticking with the site through the online- ofline it is strange. Im happy to keep the eggs though

Edit: after refreshing to make sure that the eggs wouldnt go away I discovered a new egg sitting and waiting for me. I now have enough flying pig eggs to have one of each type, is this possibly caused by refreshing? I did refresh alot due to the disconect issue, refreshing more now to try and duplicate the results and return with more feedback

Edit 2: possibly related to https://github.com/lefnire/habitrpg/issues/874
No hatching potion invovled

**Comment by kyokutei** [comment] 2013-05-21 16:11
I have this exact same "problem." Except that I have 35 extra Wolf Eggs...

**Comment by awkwardsoul** [comment] 2013-05-21 16:16
I just had this happen to me.

I had a tiger egg drop. I clicked to my inventory to see. I went to hatch it, but clicking on the egg didn't bring up the screen. 

So, I clicked on my avatar to switch screens, and it didn't do anything either, but I could click through my profile/stable/etc. 

After a like 30 seconds, I was able to go back to my "tasks" and I went back to my inventory to see 6 tiger eggs instead of 1. 

I reloaded and the eggs are still there. I wish it was the cactus.
I'm using Chrome, Version 26.0.1410.64 m

![habittigers](https://f.cloud.github.com/assets/4040478/543104/95acdb3c-c231-11e2-8ac3-eb2efd7f97be.png)

**Comment by awkwardsoul** [comment] 2013-05-22 16:19
And it happened again. The egg dropped, I went to hatch. The screen that lets you choose your potion did not show up. I clicked a couple times. It eventually reset to my "profile". I then had 3 Panda eggs.

**Comment by sgtorange** [comment] 2013-05-22 20:02
yes, i just got a dragon egg drop except that there's 8 of them in my inventory all of a sudden. my wife's been having the same problem on her account too she's been getting extra eggs AND potions!!

**Comment by nafoster** [comment] 2013-05-23 02:56
I'm also receiving extra potions. Not eggs yet.

I have about 10+ white hatching potions when I know I should have only received one or two in the last couple weeks.

**Comment by Everyst** [comment] 2013-05-23 08:23
So I have not 1, not 10, but 50 or 51 extra base potions now. Probably the same bug. I don't think refreshing has been giving me more though.

**Comment by AvalonAwoken** [comment] 2013-05-23 15:17
I'm guessing my issue is similar, I had potions multiply in my inventory.  It makes the issue of displaying multiples of the same item (instead of say, Base Potion x 7) really stand out.  I haven't tried to use one of the duplicated potions yet, mostly because I keep receiving potions but not eggs (15 pots, no eggs, statistically pretty unlikely if the drops are balanced, and I can't see why they shouldn't be)

**Comment by lefnire** [comment] 2013-05-23 17:19
duplicate of #901, let's close this and follow up there

**Closed as completed by lefnire** 2013-05-23 17:19 UTC
