### ISSUE TITLE
Rogue Leather Hood text missing in Danish

### ISSUE THREAD

**Issue by SoranDK** [HabitRPG/habitica#5282] opened 2015-05-25 20:33 UTC
It just says: "Error processing string. Please report to..."

User ID: 8202449a-82fd-4d63-827a-05fdedef016b

Firefox 38.0.1 on Windows 8

**Comment by ghost** [comment] 2015-05-26 06:40
Thank you for reporting it @SoranDK! 

Confirmation screenshot: http://i.snag.gy/rMAoF.jpg

The issue is about translation having a small error in variable. I've left a [comment on Transifex](https://www.transifex.com/projects/p/habitrpg/translate/#da/gearjson/22883763?key=headrogue1notes) for the Danish reviewer SyntaxTerror ( @lacrimae ) and this one should be easy to fix!

**Comment by gitte-k** [comment] 2015-05-26 13:12
Durr. Thanks, fixed ;)

**Comment by ghost** [comment] 2015-05-31 18:18
Fix is merged with develop, soon live. I guess this can be closed.

**Closed as completed** 2015-05-31 19:08 UTC
