### ISSUE TITLE
Constantly getting "Yikes, an error occurred!" and losing checked items.

### ISSUE THREAD

**Issue by Calamitous** [HabitRPG/habitica#6659] opened 2016-02-04 17:52 UTC
This happens several times a day, usually in the morning when I'm trying to knock out my Dailies.

I'll receive the error, refresh my browser, and sometimes, some of the dailies I've checked are now unchecked.

After the most recent incident, I copied a dump of my browser console (Chrome 48.0.2564.103 (64-bit) on OSX):

```
Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.5 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
https://www.google-analytics.com/analytics.js Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
chrome-extension://pkehgijcmpdhfbdbbnkijodmdjhbjlgp/src/socialwidgets.js:299 Replacing social widget for AddThis
```

I'll update with any further console errors if I find them.

My User ID, if it helps, is 02a50108-c028-490a-9f12-02d1000e8fab

**Comment by Alys** [comment] 2016-02-04 21:02
Could you please log out of Habitica and clear your browser's cookies before logging in again? Does that help? If the errors prevent you getting to the logout menu option (under Settings), you can go to https://habitica.com/static/clear-browser-data and click the button there to log out.

Those errors you've reported are just from your browser rejecting some facebook and analytics code, probably due to privacy extensions, and they're not likely to be related to this problem. However if the problem continues, any other console errors that you find might be useful.

**Comment by Calamitous** [comment] 2016-02-08 19:58
I cleared all cookies and logged out and back in.  That fixed the issue for a couple days, but it's just started happening again (twice today so far).

After the latest, I grabbed the following from the console.

```
Failed to load resource: the server responded with a status of 500 (Internal Server Error)        https://habitica.com/api/v2/user/batch-update?_v=4737&data=1454961263926

Objectconfig: Objectdata: "Internal Server Error↵"headers: (c)status: 500statusText: "Internal Server Error"__proto__: ObjectresponseError @ app-52821948.js:32
```

Please let me know if I can provide any further information or assistance.  Thanks!

**Comment by kasmiman** [comment] 2016-02-09 19:42
I'm getting this error too. My console grab below:

```
<source> element has no "src" attribute. Media resource load failed. habitica.com
All candidate resources failed to load. Media load paused. habitica.com
This site makes use of a SHA-1 Certificate; it's recommended you use certificates with signature algorithms that use hash functions stronger than SHA-1.[Learn More] platform.twitter.com
TypeError: t.getComputedStyle(...) is null
 index.js:4:14449
Object { data: "<!DOCTYPE html>     <html>     <hea…", status: 503, headers: tc/<(), config: Object, statusText: "Service Unavailable" }
```

**Comment by kellarules** [comment] 2016-02-09 19:45
Also getting this error this morning. I reloaded the page several times, the blue line would take a REALLY long time to get all the way across. Once I got to click a few things and then the application error came back. This was all on firefox. I switched to Safari. I couldn't even get the page to load at all, it just brought me to an Application Error page.

**Comment by kellarules** [comment] 2016-02-09 20:11
Seems to be working now, but thought it was still worth posting about since usually I don't get that error that many times in a row or across multiple applications.

**Comment by Denice54** [comment] 2016-02-10 13:51
Started seeing this error message yesterday for first time. Refreshed screen. Logged out, logged in. No help. So it started up again this morning and I found this thread. I have tried the "clear cookies" suggestion above. No help. I'm going to shut my laptop down now and try that. I am working on a Windows 2007 platform using Chrome. I don't know how to do a console grab... yet. But as soon as I find out how I will get one next time I get the error.

**Comment by Denice54** [comment] 2016-02-10 14:10
Totall shut down laptop, started again. Logged into Habitica. Boom. Went over and updated Chrome. No help. But is THIS the kind of console shot y'all are talking about?
![habitica error console 20160210 0906](https://cloud.githubusercontent.com/assets/17161142/12949468/faeed130-cfd5-11e5-9a24-0bdb2e06bec9.JPG)

**Comment by Denice54** [comment] 2016-02-10 14:11
The first couple of check-offs this morning were no problem. Since then, EVERY TIME I have checkmarked anything, I get that Yikes! message.

**Comment by bjack-codes** [comment] 2016-02-10 14:16
I use Habitica on an iPad as the website and I reload it like it says and it's fixed for a few minutes and then it pops up saying, "application error."

**Comment by Alys** [comment] 2016-02-10 22:30
Sorry about this, @Calamitous! We've been having server load issues recently which increases the frequency of these errors. The "Internal Server Error" messages are a typical sign of that.

When errors happen, try logging out again. I'm sorry - I know that's annoying! I think you can probably get away with not clearing cookies each time. A logout will clear Habitica's local storage in your browser which we know does often help. You might also have better luck using a different browser, although I'm not sure about that.

For a proper fix, we are working on improving the site's code to make it more efficient and enhance performance. It will be a while before that's finished, but it should help with issues like this.

**Comment by Alys** [comment] 2016-02-10 22:32
@kasmiman @kellarules @Denice54 @bjack-codes When you get those errors and a reload doesn't fix it for more than a minute or two, try logging out of Habitica. If you're not able to log out, go to https://habitica.com/static/clear-browser-data and click the button there, which will log you out.

**Comment by ashmenon** [comment] 2016-02-11 03:36
To add on, I was encountering similar Application Error issues rather frequently over the past 2 days. Refreshing my browser didn't do anything, but using the clear-browser-data link appears to have helped. I did it about an hour ago and so far no more Errors.

Also, chin up, @Alys! Having more traffic than your server can handle is a good problem to have :)

![screen shot 2016-02-11 at 11 14 31 am](https://cloud.githubusercontent.com/assets/2948776/12968894/82c872b8-d0b3-11e5-8e3d-e7eff51d05ad.png)

**Comment by Alys** [comment] 2016-02-11 08:45
Thanks @ashmenon. :) <3  

For what it's worth, we're trying to find ways of improving performance more rapidly. 

The past day or so has been worse than usual because we had an influx of users from a social media post.

**Comment by scheidm** [comment] 2016-02-11 15:34
I'm having similar issues. I started having issues when I was manipulating checklists for planned actions, getting yikes errors frequently. Now I'm not even able to open the program in a private browser window without failures and console vomit

**Comment by scheidm** [comment] 2016-02-11 15:35
ErrorEvent {isTrusted: true}
jquery.min.js:2 Uncaught SecurityError: Failed to read the 'contentDocument' property from 'HTMLIFrameElement': Blocked a frame with origin "https://habitica.com" from accessing a frame with origin "https://s7.addthis.com". Protocols, domains, and ports must match.ot.each.contents @ jquery.min.js:2ot.extend.map @ jquery.min.js:1ot.fn.(anonymous function) @ jquery.min.js:2(anonymous function) @ ActivityMonitorOverlayView.js:1ot.extend.each @ jquery.min.js:1ot.fn.ot.each @ jquery.min.js:1n.Class.create.bindActivityDetectors @ ActivityMonitorOverlayView.js:1i.Class.create.init @ ActivityMonitorController.js:1API.Component.load.onLoaded @ content.js:1(anonymous function) @ ComponentFactory.js:1q.execCb @ cajon.js:1b.check @ cajon.js:1(anonymous function) @ cajon.js:1(anonymous function) @ cajon.js:1(anonymous function) @ cajon.js:1each @ cajon.js:1b.emit @ cajon.js:1b.check @ cajon.js:1(anonymous function) @ cajon.js:1(anonymous function) @ cajon.js:1(anonymous function) @ cajon.js:1each @ cajon.js:1b.emit @ cajon.js:1b.check @ cajon.js:1b.enable @ cajon.js:1b.init @ cajon.js:1(anonymous function) @ cajon.js:1(anonymous function) @ cajon.js:1(anonymous function) @ cajon.js:1each @ cajon.js:1b.emit @ cajon.js:1b.check @ cajon.js:1b.enable @ cajon.js:1b.init @ cajon.js:1(anonymous function) @ cajon.js:1(anonymous function) @ cajon.js:1n.finishLoad @ text.js:1(anonymous function) @ text.js:1a.onreadystatechange @ text.js:1
app-c14655c7.js:6 GET https://habitica.com/api/v2/groups/party 503 (Service Unavailable)(anonymous function) @ app-c14655c7.js:6s @ app-c14655c7.js:6f @ app-c14655c7.js:6j @ app-c14655c7.js:7(anonymous function) @ app-c14655c7.js:7j.$eval @ app-c14655c7.js:7j.$digest @ app-c14655c7.js:7j.$apply @ app-c14655c7.js:7g @ app-c14655c7.js:4i @ app-c14655c7.js:5g @ app-c14655c7.js:4xa @ app-c14655c7.js:4wa @ app-c14655c7.js:4(anonymous function) @ app-c14655c7.js:9j @ app-c14655c7.js:1k.fireWith @ app-c14655c7.js:1o.extend.ready @ app-c14655c7.js:1I @ app-c14655c7.js:1
app-c14655c7.js:6 SyntaxError: Unexpected token <
    at Object.parse (native)
    at Object.na [as fromJson](https://habitica.com/app-c14655c7.js:4:28377)
    at b.get.transformResponse (https://habitica.com/app-c14655c7.js:32:27856)
    at uc (https://habitica.com/app-c14655c7.js:6:9564)
    at n (https://habitica.com/app-c14655c7.js:6:11232)
    at j (https://habitica.com/app-c14655c7.js:7:9455)
    at https://habitica.com/app-c14655c7.js:7:9652
    at j.$eval (https://habitica.com/app-c14655c7.js:7:16402)
    at j.$digest (https://habitica.com/app-c14655c7.js:7:14865)
    at j.$apply (https://habitica.com/app-c14655c7.js:7:16678)(anonymous function) @ app-c14655c7.js:6(anonymous function) @ app-c14655c7.js:6j @ app-c14655c7.js:7(anonymous function) @ app-c14655c7.js:7j.$eval @ app-c14655c7.js:7j.$digest @ app-c14655c7.js:7j.$apply @ app-c14655c7.js:7s @ app-c14655c7.js:6w @ app-c14655c7.js:6y @ app-c14655c7.js:6
app-c14655c7.js:6 TypeError: Cannot read property 'code' of undefined
    at responseError (app-c14655c7.js:32)
    at j (app-c14655c7.js:7)
    at app-c14655c7.js:7
    at j.$eval (app-c14655c7.js:7)
    at j.$digest (app-c14655c7.js:7)
    at j.$apply (app-c14655c7.js:7)
    at s (app-c14655c7.js:6)
    at w (app-c14655c7.js:6)
    at XMLHttpRequest.y (app-c14655c7.js:6)(anonymous function) @ app-c14655c7.js:6(anonymous function) @ app-c14655c7.js:6j @ app-c14655c7.js:7(anonymous function) @ app-c14655c7.js:7j.$eval @ app-c14655c7.js:7j.$digest @ app-c14655c7.js:7j.$apply @ app-c14655c7.js:7s @ app-c14655c7.js:6w @ app-c14655c7.js:6y @ app-c14655c7.js:6
app-c14655c7.js:6 TypeError: Cannot read property 'ignoreLoadingBar' of undefined
    at responseError (app-c14655c7.js:11)
    at j (app-c14655c7.js:7)
    at app-c14655c7.js:7
    at j.$eval (app-c14655c7.js:7)
    at j.$digest (app-c14655c7.js:7)
    at j.$apply (app-c14655c7.js:7)
    at s (app-c14655c7.js:6)
    at w (app-c14655c7.js:6)
    at XMLHttpRequest.y (app-c14655c7.js:6)(anonymous function) @ app-c14655c7.js:6(anonymous function) @ app-c14655c7.js:6j @ app-c14655c7.js:7(anonymous function) @ app-c14655c7.js:7j.$eval @ app-c14655c7.js:7j.$digest @ app-c14655c7.js:7j.$apply @ app-c14655c7.js:7s @ app-c14655c7.js:6w @ app-c14655c7.js:6y @ app-c14655c7.js:6

**Comment by catlady27** [comment] 2016-02-11 16:00
Just started getting this error myself. Don't seem to be able to check anything off. User ID is 4de4a8f6-962f-4f59-9eb5-036a86013620. Running Chrome Version 48.0.2564.103 m, on Windows 7.

And now it's progressed to this;

Application Error
An error occurred in the application and your page could not be served. Please try again in a few moments.

when I attempt to load the page.

**Comment by Denice54** [comment] 2016-02-11 16:06
Glad to see others have discovered Habitica! Sorry it's causing issues, but I'm sure it will all be well as soon as possible. Yesterday after I tried EVERYTHING suggested it ran beautifully the rest of the day, so I have NO idea what may have actually "worked"! Started off great this morning. Then YIKES! It started again. One post above clicked with me. I seem to start having the issues when I am checking off CHECKLIST items. I will pay more attention to that and report back! (Once I am up and running again today, that is!) <smile>

**Comment by Stendarpaval** [comment] 2016-02-12 01:42
Hello. Github looks neat. Anyway, I had the same issue as @Denice54 had, very similar error messages even. Everything worked fine an hour ago, I could check off dailies and habits and just wandered over to the party page when the error messages appeared. Here's a screenshot of what my console looked like at the time: http://imgur.com/7UlxCYu

So, I tried doing what @Alys suggested, logging out and back in. While trying to log back in, pop up messages appeared with a very brief error message, I think it was Service unavailable: 503 or something similar. I forgot to make a screenshot, but it was a brief message like that with just an OK button near the bottom. 

Eventually it would let me log in, however. Everything seemed fine at first, though the page took rather long to load. Error messages still popped up, so I decided to remove all cookies (wiped them all using ccleaner). 

I made another attempt to log in. No error messages, but loading took very long. In fact, it never loaded completely: the blue bar stopped right in front of the edge of the screen and in the upper left a loading icon is swirling clockwise. This is how it looks like right now. My 7 party members don't show up beside my avatar and while I can navigate to other pages, refreshing the page...

Oh. I just refreshed again and everything works now, party members show up and everything. I was also going to say that I couldn't access my API settings because there was an application error, but upon refreshing it loaded. 

However, the "Yikes, an error occured" message appeared and the console is yet again full of failed to load resource messages: http://i.imgur.com/wt5KK9s.png

I'm at a loss. Here's my information:
User ID: 6e3d49cf-9ef0-4cdc-8876-f2b5251b1ed0
Username (if it helps): CrimsonColossos
I'm running Chrome on Windows 7.

Small update: just tried casting Burst of Flames on a daily and it produced delayed "Yikes" messages. The console shows multiple lines of: 

```
https://habitica.com/api/v2/user/class/cast/fireball?targetType=task&targetId=97ede817-c951-480a-bfc3-d04e7b6b138e Failed to load resource: the server responded with a status of 503 (Service Unavailable)
app-c14655c7.js:32 ObjectresponseError @ app-c14655c7.js:32

```

Another update: It's 12/2 now and I haven't had "Yikes" pop up messages since yesterday. Everything works fine and loads quickly.

**Comment by ccornetet** [comment] 2016-02-12 14:26
I've been having this issue intermittently for the past week or two. I just signed out of Habitica, cleared my browser cookies, and signed back on. Like @stendarpaval, error message popped up when I tried to sign in (with the correct username and password). Finally it let me log in, and the blue bar took ages to load. Once it did, the "Yikes, and error occurred!" message popped up.

I've been getting this message when I check off tasks (the checks are then lost and the task reappears), when I visit my party, when I go to my guild page, when I got to my inventory, and just randomly when I try to do something.

I'm using Chrome on Windows 8 if that's helpful.

**Comment by Denice54** [comment] 2016-02-14 15:27
I am still getting this error randomly. Cannot connect it with any particular function. Forgot to mention particulars in earlier posts. I run Windows 7 on Google Chrome. Version 48.0.2564.109m. I'm on an ASUS laptop. Let me know if anything other info needed!

**Comment by Denice54** [comment] 2016-02-14 15:30
Oops. That's Chrome on Windows, obviously. <grin>

**Comment by Alys** [comment] 2016-02-15 23:58
Everyone, I'm so sorry about the trouble these errors are causing you! They are all examples of the frequent server errors we are having, and we're documenting our progress on preventing them in this issue: https://github.com/HabitRPG/habitrpg/issues/6700

This comment in that issue has our latest update: https://github.com/HabitRPG/habitrpg/issues/6700#issuecomment-184375608

I'm closing this issue now since we have the other one open, but thank you for reporting them - your reports have helped us track the error and work out when we should restart the server (a temporary fix that we've been doing often).

@Calamitous The ERR_BLOCKED_BY_CLIENT message is unrelated to the server errors, and isn't anything to worry about. You can ignore it. It's caused by privacy/security extensions or other software on your browser/PC blocking access to optional third-party websites.

**Closed as completed by Alys** 2016-02-15 23:58 UTC
