### ISSUE TITLE
All tasks disappeared

### ISSUE THREAD

**Issue by vermouthmjl** [HabitRPG/habitica#5060] opened 2015-04-22 14:53 UTC
This happened probably minutes ago. All tasks (habits, todo, dailies) are missing on the page. Both chrome in Windows and chrome in iOS have the same problem. They are still on iOS application.
I have many tasks added using both navigator and the application, at different moments, and all are gone. So I don't think it's a syncing issue.
User id : 70f24872-cb49-463b-9ac1-6ad7cf8015c2

**Comment by chaoticawesome** [comment] 2015-04-22 15:07
Same here, everything's missing. All tasks and all custom rewards as well, no matter when they were added. Nothing else is amiss. I'm using Firefox on Windows.
User ID: 79167200-f69d-4af3-bcac-6d166c21fd31

**Comment by paglias** [comment] 2015-04-22 15:09
@vermouthmjl @chaoticawesome sorry about this! all your data is safe and if you refresh the page you should see it again

**Comment by vermouthmjl** [comment] 2015-04-22 15:12
Wow. They all came back. Thanks.

**Comment by damiananero** [comment] 2015-05-16 21:15
I've got such a problem! 
A problem appeared when I tried to deal with a habit of ended challenge (tried to keep it).
After page refresh disappeared everything custom (not from challenges) - habits, dailies, to-do, rewards. And added two 'third party' habits with names cb9ea102-fae7-493b-af6c-27b9c3ef194f and 1a687d54-d4a7-4b0a-9485-b443607b7fd6.
The same picture is on backup site and in android app. I don't have any browser plugins/apps/smth else, connected to habit.

my ID: 362a1835-b723-4db7-9cc5-389a803c3b82
browser: http://whatsmybrowser.org/b/P3TWXLX

**Comment by deilann** [comment] 2015-05-16 22:13
Press Clear by the tags even though it doesn't look like any are selected.
You can delete the two New habits.

**Comment by damiananero** [comment] 2015-05-16 22:27
(tag) Yes, I did it, but it didn't help
(new tasks) Ok

**Comment by deilann** [comment] 2015-05-16 22:29
@Alys, can you look into the db side?

**Comment by Alys** [comment] 2015-05-17 03:41
@damiananero your account in the HabitRPG database shows that you have 9 Habits (including the two 'third party' habits that can be deleted as @deilann said), 11 Dailies, 17 To-Dos, and 5 Rewards however they are all from challenges (except those two deletable ones). 

I can download a database backup to retrieve your missing tasks. Can you please tell me how many hours ago did you last see all of your tasks in HabitRPG? It's important that you tell me how many hours (or days) in the past, rather than a specific date and time, because timezones make dates+times hard to work with. It's also important that you try to estimate how many hours/days ago fairly accurately because it takes at least two hours to download a database backup (they are huge!) and another one to two hours to extract information from it. If you're not sure how many hours ago you last saw all your tasks, it's much better to overestimate the number rather than underestimate it.

**Comment by damiananero** [comment] 2015-05-17 07:45
@Alys The last time I saw all my tasks was ~ an hour before my post here (in my timezone it was 16th may 23:30 or something like that). I didn't add any new tasks nearly a week, so it won't do any harm if you just take a backup from 16th morning

And sorry for double commenting, it was my inadvertence

**Comment by Alys** [comment] 2015-05-17 08:04
@damiananero Thank you! That's very helpful. I've started downloading a backup. If we're lucky, it will be faster than average and I'll be able to restore your tasks before I go to bed in three hours, but I think it's more likely that I won't have all the data until I wake up about 12 hours from now. 

I recommend that you start [Resting in the Inn](http://habitrpg.wikia.com/wiki/Rest_in_the_Inn) now, in case I restore your Dailies at a time that is after you are able to marked them completed for today.

**Comment by damiananero** [comment] 2015-05-17 08:13
@Alys Thank you) I'll wait in the inn till everything is alright. Have a good sleep)

**Comment by Alys** [comment] 2015-05-17 19:18
@damiananero I've restored your tasks. Please let me know if there's still any problems!

**Comment by damiananero** [comment] 2015-05-17 20:26
@Alys Thank you! Everything is on its' place)))

**Comment by Alys** [comment] 2015-06-14 04:00
I'm closing this because the specific problems listed here have been fixed and the issue in general is a duplicate of https://github.com/HabitRPG/habitrpg/issues/4957

**Closed as completed by Alys** 2015-06-14 04:00 UTC
