### ISSUE TITLE
loading tips can't be read when loading is too quick 

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#11834] opened 2020-02-09 22:48 UTC
This isn't exactly a bug but...

As reported by @Acorn_Sprout (2a5618da-d8c4-4530-a943-3fa871ef4859):

_"This may already be known and it's not precisely a bug, but when using a browser the introductory tip lasts no more than about a second. FWIW the platform I'm currently using is Chrome version 79.0.3945.130 (Official Build) (64-bit) on Windows 10. With Internet Explorer on the same machine, version 11.1387.15063.0, the tip lasts perhaps two seconds - better, but still hard to read quite everything._

_"I believe Chrome on Android 5.1.1 on a Motorola G3 has similarly brief results, but it's a little hard to quantify because my phone is extremely laggy at present."_

The loading tips were introduced to give people something to read while the website slowly loaded, and it's good that the website now loads for some people too quickly for that to be necessary, but it does make the loading tips look like a bit of a tease. :)

~I don't know if there's anything we could or would want to do to "help" with this (we certainly wouldn't want to make loading deliberately slower) but I'm putting this here so that we have it on record. I'm marking it suggestion-discussion. If it's decided to close it as a won't-fix, we can at least direct people to it for an explanation of why the tips don't show up for long.~

EDIT: See the comments below for the desired fix (in brief, remove the loading tips).

**For anyone who wants to see all the loading tips, they're on the wiki at [Loading Page Tips](https://habitica.fandom.com/wiki/Loading_Page_Tips)**

**Comment by artur-borys** [comment] 2020-02-14 12:58
Maybe make the tip collapse into a small window attached to border of the screen after loading finishes? The window could stay for a few seconds or be closed by the user.

**Comment by citrusella** [comment] 2020-02-15 07:09
I had an idea like the other one when I read this, except modal or notification bubble instead but just hadn't mentioned it. (But I think such a thing should be opt-in/out via the settings if it were to become an official thing. I'm fine seeing tips during the loading, whether I can read them or not, but I wouldn't want a window I couldn't opt out of for that kind of thing, even if it disappeared on its own after a bit.)

**Comment by saraolson** [comment] 2020-03-05 19:08
After discussion, we felt that the best way to handle this moving forward would be to delay the appearance of the tip so that under normal loading conditions, the tip will not show. Normal loading times are much too fast to read the tips, which is a good thing! We don’t want to tease people with text they won’t usually have a chance to process. When people do experience longer load times (2+seconds), we can give them a tip to read while they wait.

We will continue to look for opportunities to deliver these helpful messages to improve user experience, but loading messages don’t seem to be the best place anymore.

**Comment by paglias** [comment] 2020-03-06 12:24
@saraolson the problem is that we don't really know when the loading will end, I mean we can have them appear after 2s for example but won't know how much longer they'll be visible for

**Comment by whmountains** [comment] 2020-03-09 23:34
@paglias Good point.

It looks to me that the tips will need to be removed, or we'll need to build out a more persistent UI for displaying them.  I lean towards the former option, since users are already likely to be seeing a modal popup on checkin.  We don't want to two popups competing for their attention.

**Comment by Tressley** [comment] 2020-03-12 16:16
Spoke to the rest of the team and we agree that removing the loading tips for now is the best solution. 👍

**Comment by anoopravella** [comment] 2020-04-01 15:59
Is this issue still open? If so, I'd like to take a look.

**Comment by paglias** [comment] 2020-04-01 17:11
@anoopravella it's! I'll mark it as in progress for you

**Closed as completed** 2020-04-14 20:03 UTC
Labels: priority: minor, status: issue: in progress, type: medium level coding, section: Other
