### ISSUE TITLE
Losing gold for no apparent reason

### ISSUE THREAD

**Issue by 87Yuki** [HabitRPG/habitica#3594] opened 2014-06-12 02:02 UTC
I check up on my tasks via bookmark, and as soon as the page loads I get a little notification just like you would for gaining gold or gaining or losing HP, but it shows me losing 5gold 8 silver, or 6gold 2silver, a random small amount like that, and when I check my gold, yup, its about 5 or 6 less than it was last time I was here.  I was on my tasks only an hour or two ago and I checked the page just now and lost gold - and no, it hadn't rolled over to midnight or anything yet either.  Not that that should have me losing gold anyway(?)  I'm using Google Chrome and my ID is 87Yuki.  I haven't been receiving any error messages as far as I can tell.

**Comment by Alys** [comment] 2014-08-13 08:08
@87Yuki, I'm sorry we haven't replied to you before now.

It's likely that these problems were caused by sync errors. To learn about them, see  [Sync Errors](http://habitrpg.wikia.com/wiki/Sync_Errors) on the wiki, in particular the sections titled "How to Minimise Sync Errors" and "Losing gold or experience or mana for no apparent reason". I'm closing this issue now since it's rather old, but if the problems are still happening and the sync error page doesn't help, comment here and we'll reopen this!

**Closed as completed by Alys** 2014-08-13 08:08 UTC
