### ISSUE TITLE
Todo task created via user/tasks/{id}/up is not marked as completed

### ISSUE THREAD

**Issue by fnurl** [HabitRPG/habitica#4891] opened 2015-03-20 07:44 UTC
At the moment, when creating a new todo task via the `user/tasks/{id}/up` route, the user gets xp and gold, but the todo task remains incomplete. Should the default not be that the todo task also gets marked as complete?

**Comment by Alys** [comment] 2015-03-20 11:12
Are you sure a To-Do is being created? It's meant to create or update a Habit and that's what it's doing when I test it.

The [API documentation](https://habitrpg.com/static/api) also says it's for Habits: "HabitRPG has a simple API for up-scoring and down-scoring third party Habits: POST /api/v2/user/tasks/{id}/{direction} (headers x-api-user and x-api-key required)."

If you're certain that To-Dos are being affected, please let us know! Please include the user ID and the task ID.

**Comment by Alys** [comment] 2015-03-20 11:15
The [API documentation](https://habitrpg.com/static/api) also says it's for Habits: "HabitRPG has a simple API for up-scoring and down-scoring third party Habits: POST /api/v2/user/tasks/{id}/{direction} (headers x-api-user and x-api-key required)."

If you're certain that To-Dos are being affected, please let us know! Please include the user ID and the task ID.

**Comment by fnurl** [comment] 2015-03-23 10:35
Thanks @Alys for the comment. I now found the quote you are referring to, I previously only read the documentation under `user/tasks{id}/{direction}` which refers to a task rather than a habit. The description of the route reads _"Simple scoring of a task."_ and for id the description is _"ID of the task to score. If this **task** doesn't exist, a task will be created automatically"_ (my emphasis). With the description of the object field as _"If you're creating a 3rd-party **task**, pass up any task attributes in the body (see TaskSchema)"_ (my emphasis).

I assumed that I could create todos as well since I understood that task is the parent of habits, dailies and todos according to [task.js](https://github.com/HabitRPG/habitrpg/blob/develop/website/src/models/task.js). Was my assumption correct?

I send something like this when I try to complete my task (same is sent both for new and old tasks (todos))

```
{
  "text": "my todo",
  "id": "{a trello card id}-zapier",
  "type": "todo",
  "completed": "true",
  "dateCompleted": "{date from last trello activity}",
  "notes": "{trello card description}"
}
```

Am I using `/up` in the wrong way? Using `PUT /user/tasks/{id}` and changing complete to true did not seem to score anything for the user?

**Comment by Alys** [comment] 2015-03-23 10:50
"task" does normally mean Habit and Daily and To-Do (and often even Reward). However where it says task in that one piece of documentation, it might just be referring to Habits. 

What happens when you use `/user/tasks/{id}/up` with the ID of a To-Do? Does the To-Do's value change? If so, then you **can** use `up` with To-Dos.
Or is a new Habit created with the same ID as the To-Do that you were trying to modify? If so, then I would say that `/user/tasks/{id}/up` can be used with only Habits.

I believe you are correct that using `PUT /user/tasks/{id}` to set `completed` to true will not give XP, GP, and MP to the user. I think it's meant to be for modifying the task rather than "scoring" the task. If `up` does work with To-Dos, then you can use `up` for the scoring (XP, etc) followed by `PUT ...` to set it to completed.

**Comment by fnurl** [comment] 2015-03-23 13:14
If I use `/user/tasks/{id}/up` with an _existing_ To-Do, the user scores and the To-Do is marked as completed. When using `/user/tasks/{id}/up` with the intent of both _creating and scoring_ a To-Do, the To-Do is created, scored, but _not marked as competed_.

In this particular case, I am using the API via Zapier where only single API calls are supported which unfortunately means I am not able to use the `PUT` followed by a call to the `/up` route.

Is it reasonable to hope for a change in the API behaviour?

**Comment by Alys** [comment] 2015-03-23 13:30
I can confirm the behaviour that when you use `/user/tasks/{id}/up` with an existing To-Do, the user scores and the To-Do is marked as completed.

However I cannot replicate using `/user/tasks/{id}/up` to **create** and score a To-Do. Every time I try it, it creates a Habit and scores it. It doesn't mark the Habit as completed of course, because that doesn't happen with Habits. This seems to be correct behaviour.

Are you sure a To-Do is being created? Are you doing anything specific to make it create a To-Do instead of a Habit?

**Comment by SyntaxPickax** [comment] 2015-03-23 16:44
@Alys Did you include `"type": "todo"` in your POST request? When I test with the [static API page](https://habitrpg.com/static/api#!/user/user_tasks_id_direction), this creates a new green uncompleted To-Do:
![screen shot 2015-03-23 at 9 38 36 am](https://cloud.githubusercontent.com/assets/1245093/6785088/d7a91378-d140-11e4-99d9-1ea372d7370b.png)
and this creates a new green Habit:
![screen shot 2015-03-23 at 9 40 11 am](https://cloud.githubusercontent.com/assets/1245093/6785095/e18f0898-d140-11e4-97ad-01afd829af47.png)

**Comment by Alys** [comment] 2015-03-23 21:05
Ah, thanks @SyntaxPickax, I see those options now. I stupidly hadn't expanded the POST section, assuming that that route was identical to the simple option described in the documentation at the top of the page. Sorry about that! I'll adjust the docs to point out that more details can be provided as described lower down that page.

Okay, so the problem is that when using `/user/tasks/{id}/up` **with the extra option to create the task as a To-Do or Daily**, then the task is not marked as completed. @fnurl I think it is reasonable for us to change the API behaviour for this.

**Comment by fnurl** [comment] 2015-03-24 08:05
@Alys Sounds great! do you think you could comment in this issue when the API has been changed so that I can update my Zapier App descriptions?

**Comment by Alys** [comment] 2015-03-24 08:11
I might not, but issues are always updated when fixes are proposed and are closed when the fixes are accepted, so if you keep following this issue you'll see when it's been worked on.

**Comment by SyntaxPickax** [comment] 2015-03-24 15:39
Thanks @Alys

**Closed as completed** 2015-06-20 04:52 UTC
