### ISSUE TITLE
Missing Gems after creating challenges -- gems being subtracted twice?

### ISSUE THREAD

**Issue by LindaAnneLine** [HabitRPG/habitica#4633] opened 2015-02-05 03:59 UTC
I am fairly sure I was charged an extra 5 gems when I created two challenges I created yesterday in the Short Term Guild for Accountability.  Each of challenge was for 5 gems, and both were set up in late afternoon (I believe).  I know there was a little 'hiccup' in the system right after I created one of them... and I had to go in and make some tiny adjustments ... and perhaps the system charged me again?   I'm not sure which one it was, because both were done together.     To give you some additional background, on Feb 1, I had 1 gem, and created a 1 gem challenge in the Stag Guild (for Feb. Dishes).   That left me with no gems.  Next I purchased the maximum of 35 gems.  I purchased one background (7 gems) (35-7=28) and then created two 'reward' challenges of 5 each in the STAG Guild, one for NightOwl and one for GoldDust.  (28-10=18)  GoldDust's is still in there in case you want to look at it.   I am now at 13 gems... and I think I really should be at 18?    So yes, I do think the system nibbled an extra 5 gems....  Thanks for any help you can provide!  :)
##

**Comment by Alys** [comment] 2015-02-05 05:25
I've given you back 5 gems. Let us know if they haven't shown up (you might need to reload). 

Devs:
This might be related to https://github.com/HabitRPG/habitrpg/issues/4624 in which justicar347 seemed to be charged twice for a 15-gem purchase and a 3-gem purchase.

**Comment by LindaAnneLine** [comment] 2015-02-05 06:24
Thank you, yes they HAVE been credited.
And thank you for being SO PROMPT on working on the problem!
:)
AnneLine (on habitRPG )  akaLindaAnneLine (on github) aka 

Linda A. Harwood

Date: Wed, 4 Feb 2015 21:26:06 -0800

**Comment by tyoungjr** [comment] 2015-02-07 18:24
Unfortunately this also happened to me. I created a challenge and set the reward to 5 gems. Only when I hit save all 20 of my gems were added as a reward . :(

**Comment by Alys** [comment] 2015-02-07 19:59
@tyoungjr We can't fix this without specific information. Please tell us your user ID (there's instructions for finding that under Help -> Report a Bug). Also tell us which challenge it was: view the challenge in your browser, copy the URL, and paste it in here, and also tell us the name of the challenge.

**Comment by tyoungjr** [comment] 2015-02-07 23:05
Hey Alys, my user_id is 36cf1a28-8331-482f-9adc-58d282aec98f , the challenge is [Deploy a MeanJS project to production! The path to contribution!](https://habitrpg.com/#/options/groups/challenges/b568696d-6a10-45c1-b356-4dd8b386475f)

**Comment by Alys** [comment] 2015-02-07 23:45
@tyoungjr The gems should now be correct for the challenge (5) and for your account (15). Let us know if they are not! You might need to reload to see them.

It's possible that your problem was actually caused by a usability issue with the field that lets you specify the gems. You might like to read this comment in case it's relevant for future challenges: https://github.com/HabitRPG/habitrpg/issues/3862#issuecomment-51696097

**Comment by Alys** [comment] 2015-02-07 23:50
@tyoungjr It's possible that your problem was actually caused by a usability issue with the field that lets you specify the gems. You might like to read this comment in case it's relevant for future challenges: https://github.com/HabitRPG/habitrpg/issues/3862#issuecomment-51696097

**Comment by tyoungjr** [comment] 2015-02-07 23:55
Cool thanks Alice. It looks correct.

On Sat, Feb 7, 2015 at 5:50 PM, Alice Harris notifications@github.com
wrote:

> @tyoungjr https://github.com/tyoungjr It's possible that your problem
> was actually caused by a usability issue with the field that lets you
> specify the gems. You might like to read this comment in case it's relevant
> for future challenges: #3862 (comment)
> https://github.com/HabitRPG/habitrpg/issues/3862#issuecomment-51696097
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/HabitRPG/habitrpg/issues/4633#issuecomment-73389369.

## 

Cheers,
T

**Comment by paglias** [comment] 2016-06-01 09:26
Should be fixed, reopen if it happens again

**Closed as completed by paglias** 2016-06-01 09:26 UTC
