### ISSUE TITLE
Damaged from checked daylies

### ISSUE THREAD

**Issue by Asmodan** [HabitRPG/habitica#7545] opened 2016-05-30 18:41 UTC
Did check all daylies yesterday (pre midnight) my habitica day end at 4 or 5 a.m i believe.
(Some i did finish on my mobile device, latest AppVersion, OS Android-4.4.2)
Though no daylie unticked, the boss hit with i suppose like nothing would habe been checked.
No Timechange or something like that sync and refreshed my app and brower after ticking the quests.

user ID:6cea3d6d-936a-4834-8e28-ec4918f1b6f1
Bosslog:
 The Necromancer attacks party for 38.3 damage. 

(right after i logged in today and died though the damage)

It was a single Bosshit, all daylied done nothing open except one trivial daylie for which im not sure if finished or not.

Greeting.

**Comment by superbrewers** [comment] 2016-05-30 20:39
This also happened to my son today. Each time, logging in through Chrome, multiple "null" error messages were displayed, his health was depleted, and he had the option to "Restore health and start again". There were no boss battles, but he had checked off all his dailies yesterday, so he was upset when his character died.

He showed me what happened, and that dropped him to level 72.

I closed out of Chrome and reconnected to Habitica.com and he the same behavior happened, dropping him to level 71. We are looking for his password to try logging in on a different computer.

**Comment by crookedneighbor** [comment] 2016-05-30 20:45
The `null` error messages were probably this: https://github.com/HabitRPG/habitrpg/issues/7546, which has been fixed now.

**Comment by crookedneighbor** [comment] 2016-05-30 20:46
@superbrewers on the settings page, there is a fix character values button where your son can correct their unfairly lost levels and gold.

**Comment by Alys** [comment] 2016-05-30 20:58
@superbrewers If your son is under 13, could you please read the first section in the wiki's Children Using Habitica" page at http://habitica.wikia.com/wiki/Children_Using_Habitica ? In brief, there's a legal requirement for Habitica to collect parental permission for young children to use Habitica, but you can do that easily by sending us an email.

**Comment by Alys** [comment] 2016-05-30 21:07
For @Asmodan's report, I've confirmed that cron treated all Dailies as if they were not completed:

```
        {
            "id": "f7c3f8a8-4875-478d-9e75-637a6e9465d0",
            "text": "`asmodan42 attacks The Necromancer for 0.0 damage.` `The Necromancer attacks party for 38.3 damage.`",
            "timestamp": 1464624347054,
            "flagCount": 0
        },
```

As @Asmodan says, there was no duplicate cron - i.e., the previous progress message was a day earlier.

It's possible for completed Dailies to be ignored if #4313 happens, but @Asmodan was using the app as well as the website and refreshed the website which usually clears #4313, so I think this bug is something different.

@Asmodan You can recover from the unfair damage at Settings > Site > Fix Character Values ("Settings" is the gear-shaped icon on the top right of the website).

**Comment by crookedneighbor** [comment] 2016-05-31 02:59
@superbrewers I figured out what happened, the bug I linked to caused your son's account to cron multiple times. He probably noticed that many of his task's colors turned very red. I can restore them to the state they were before it happened, I just need your son's user id.

You can find it in [Settings > API](https://habitica.com/#/options/settings/api). Be sure to only copy the User ID and _not_ the API Token.

**Comment by superbrewers** [comment] 2016-05-31 15:15
Hi Alys,
My wife and I set his account up for him, so we do give him permission. Didn’t realize you needed it on record.

Thanks.

**Comment by superbrewers** [comment] 2016-05-31 15:16
Thanks for your help. We restored his levels, but he isn’t too worried about the colors on the tasks. Now that he knows the reason, he’s OK.

**Comment by Aerten** [comment] 2016-06-01 04:29
This happened to me as well.  I can go back and fix my streaks and what not (PITB), but I finished all my tasks and am in a challenge.  The party quest page says I did NO damage (LIES!) and I took damage.  Can y'all fix that part?

![habitica](https://cloud.githubusercontent.com/assets/16511223/15698183/cb92a09e-278f-11e6-8bf2-3fb0b040bf82.png)

**Comment by paglias** [comment] 2016-09-03 13:27
I think this has been fixed, please leave a comment if it happens again

**Closed as completed by paglias** 2016-09-03 13:27 UTC
