### ISSUE TITLE
Incorrect item wrapping on Market pages

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#10758] opened 2018-10-14 09:26 UTC
Il Mago (c073342f-4a65-4a13-9ffd-9e7fa5410d6b):
"In the Market sometimes there is a strange positioning of the items, for example in this case when there should be a single item on a new line it is instead positioned as last item of the previous line, and to the right of everything else:"
![scr](https://snag.gy/6HhEyr.jpg)

shanaqui:
"Before I add that to Github, do you have any idea how to get that to happen? Resizing windows, maybe?"

Il Mago:
"I have no idea, it is the first time I noticed it, but it is also the first time in which I could have had a row with only one item inside. I will try to buy some things to see if in an other category i can have that one-row-item to display correctly or if it happens again (it may be connected to the one-row-item that doesn't want to display)"
 
Il Mago:
"I have more details on the issue with the positioning of items in the Market
 I hope this is explanatory enough: [screenshot below]
If not I will try to maybe find a screen recorder or something"
![scr](https://snag.gy/ZQaCPE.jpg)

**Comment by majestic-owl448** [comment] 2018-10-15 07:26
I have been asked to post here about any style that may affect the Market page: the only styles I have affect only the task page

The only thing that is different from before is that I recently set my screen resolution to 125%

If I have the chance to try with different computers, I will see if it can be reproduced

**Comment by Phelilix** [comment] 2018-10-22 19:38
I have identified the problem.
It's a css rule.
The last div in an element with class `items` has less max width, which makes it possible to fit into a smaller gap such as the one depicted by Alys.
Because of these rules:
```css
.items > div:last-of-type {
    margin-right: 0px;
}
```
And:
```css
.items > div {
    display: inline-block;
    margin-right: 24px;
}
```
By the way, these two css rules become ugly in more than just this situation. They also become ugly in the seasonal shop section of the market. (no margin-top, no space between two armor pieces). 

Now the options are:
 * Choose a different class, more suited to this situation. With the time cost actually finding that class. 
 * Modify the class items. With the risk that it doesn't work out somewhere else (in the skills bar)
 * Create a different class, that keeps possibly multiple rows of elements in mind. (contributing to the over 9000 lines in the css file)

**Comment by Alys** [comment] 2018-11-02 05:05
@Phelilix Thank you for finding that! Are you interested in fixing it if the staff comment on their preferred option from your list?

**Comment by Phelilix** [comment] 2018-11-02 08:14
@Alys Sure, i could fix it. 
It looks like an hour of work or so, since I need to reinstall Habitica again.

**Comment by Alys** [comment] 2018-11-04 02:15
@Phelilix Fantastic, thanks! Comment here if you run into trouble!

**Comment by Phelilix** [comment] 2018-11-04 10:30
@Alys I will cook something up. You can say if it follows the sensibilities of Habitica when I'm done.
Since the specifications are still absent.

**Comment by Alys** [comment] 2018-12-23 00:56
@thebat137 (dea8a9e8-c084-438a-9a14-7fe96a73fd0a) reports that this also happens with quest scrolls:

"In the quest shop, when I expand the pet quest section and the browser window is at a certain width, the last line of pet quest scrolls is one scroll longer than all of the other lines (i.e., a "dangling" scroll), instead of the last scroll on that line being wrapped to the next row. Narrowing the browser window slightly causes the dangling scroll to wrap down to the next line, while widening the window slightly allows the lines above to lengthen by one scroll. I can reproduce the problem in both Firefox and Chrome."

**Comment by Alys** [comment] 2020-01-01 00:12
Just confirming that this is still happening:

Alex, Lunar Mage   @lunarwitch (b9464d2c-7bd0-45c9-962e-f09799b9c7d2):
"Hi! Whenever I go to my equipment page and expand the armor tab, the last piece of equipment is displayed as a seventh spot on the grid instead of creating a new row. Image: https://imgur.com/a/KIe1pBb I have already tried refreshing, clearing my cache, and restarting the browser. Browser: Opera Device: Microsoft Surface Pro 6 (I don't know if it happens on my desktop PC too as I currently don't have access to it) OS: Windows 10 Home (64bit)"

**Comment by Tressley** [comment] 2024-07-24 13:12
Closing as this looks to have been fixed in the Customization Shop release.

**Closed as completed by Tressley** 2024-07-24 13:12 UTC
Labels: priority: minor, section: Market
