### ISSUE TITLE
Dailies not reset, but streaks are reset

### ISSUE THREAD

**Issue by LlamaHobbit** [HabitRPG/habitica#3608] opened 2014-06-15 02:38 UTC
Just to preface, I check dailies off on both my PC and on my iPad throughout the day. I only use Habit in the browser (Chrome, usually) for both and never use the mobile app. I've also never messed with Custom Day. I had a "Perfect Day" yesterday, but this did not trigger in my Perfect Day count today. Instead, roughly 1/3 of dailies reset appropriately (the ones I had checked off earliest in the day), while the other 2/3rds showed as already checked, including all checklists that I had checked off, but reset the streak counts. Most of the streak counts were reset to 1, none were reset to 0, and  I think a couple were reset to higher streak counts (or else, I'm doing way better than I thought). I finished checking off the last of my dailies around 10pm on my iPad, hit the Sync button several times but did not do a hard refresh, and then browsed to chat in the Tavern and guilds. This morning, I noticed the still checked dailies on some things and the streaks being reset. But I know the server picked up the checks, because I didn't die or lose any health, and my gold counts are the same. I did notice after a couple hard refreshes and signing out and back in that I had more food than I remembered since I thought I fed all the pets before going to bed. I've manually changed most of  the streaks back since I could look at the ones that were similar but hadn't lost their streaks. Hope something in all this info helps.

**Comment by wc8** [comment] 2014-06-16 17:35
I _might_ have experienced this a week ago. I checked some things off on mobile the night before and had streaks of 1 where I had thought they were higher, but I wasn't sure. I cannot remember at this point if the dailies had reset or not. I just put it down to a sync fluke.

**Comment by deilann** [comment] 2014-06-16 17:36
mobile app or on mobile browser @wc8?

**Comment by wc8** [comment] 2014-06-16 20:15
Hard to remember at this point. I use both. Sorry, mine is not a proper bug report at all. Haven't used mobile last at night since. I'll try to report better if I run into this again.

**Comment by deilann** [comment] 2014-06-16 20:16
The reason I ask is because one person reported this bug first with the
mobile app, then Llama Habit experienced it without the mobile app -- which
could be two different bugs.

**Comment by ninjasophia** [comment] 2014-06-18 17:17
I'm experiencing a similar issue: I joined HabitRPG a while a go and stopped using it. I tried restarting yesterday and today my dailies (completed yesterday) are still gray (both on Chrome and Android). Also, I still have "ZZZ" above my avatar.

**Comment by deilann** [comment] 2014-06-18 17:21
Sophia, that's not this bug. That's expected behavior. If you have ZZZ
above your avatar, that means you checked into the inn. Whilst in the inn,
your dailies won't reset. Check out of the inn, then once you go past your
day start time again, they will reset. Until then, you can record your gold
and XP, uncheck all of your dailies, then go to Settings > Site > Fix
Character values, and put your stats back where they should be.

On Wed, Jun 18, 2014 at 10:17 AM, Sophia Montalvan <notifications@github.com

**Comment by ninjasophia** [comment] 2014-06-18 17:23
@deilann awesome, thanks.

**Comment by Alys** [comment] 2015-07-04 21:42
I'm closing this because it's an old report and we're tracking a similar bug at https://github.com/HabitRPG/habitrpg/issues/4313

**Closed as completed by Alys** 2015-07-04 21:42 UTC
