### ISSUE TITLE
Private Messages (PMs) modal scrolls to top of conversations when closed and reopened

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica#11220] opened 2019-06-13 13:05 UTC
> Kiyoshi @kiyosh1 (5ffee717-5618-4429-b161-981d79842f8a): "Click on messages -> is scrolled to the most recent message. Send a message, close the modal. Click on messages again -> now it is scrolled all the way to the oldest message in the chat. It should still be scrolled to the most recent message."

Confirmed in Chrome.

**Comment by Alys** [comment] 2019-06-25 10:11
I'm putting this on hold until https://github.com/HabitRPG/habitica/pull/11113 is completed, because it will make significant changes to the PM screen and might fix this issue.

**Comment by Alys** [comment] 2019-06-25 10:17
https://github.com/HabitRPG/habitica/issues/11182

**Comment by Alys** [comment] 2019-06-25 10:17
https://github.com/HabitRPG/habitica/issues/11182 might be related to this.

**Comment by SabreCat** [comment] 2019-11-01 17:27
This does seem to be a duplicate of #11182 from what I can tell. If I'm mistaken, feel free to reopen, but if so it'd help to have a clearer main issue description to explain what differentiates it from the other ticket!

**Closed as completed by SabreCat** 2019-11-01 17:27 UTC
Labels: status: issue: on hold
