### ISSUE TITLE
Not recieving awards of a pet quest

### ISSUE THREAD

**Issue by luhm** [HabitRPG/habitica#7034] opened 2016-04-07 15:04 UTC
General Info
- UUID:  551e07b9-9c6b-4d59-835a-bba077de6911
- Browser: Chrome
- OS: Windows 7
### Description

 I completed a pet quest with a group and I haven't recieved the rewards, despite another quest started. The Pet Quest I finished was the "Monstrous Mandrill and the Mischief Monkeys". It started around 4th april.

**Comment by DeweyReadmore** [comment] 2016-04-07 21:06
I am party leader for the party in question and wanted to note that at least a few of our other members are experiencing this same issue. Users @Alan and @SarahDsp were also enrolled for the quest but failed to receive any of the rewards. From what I understand, this includes XP and gold benefits (if any) as well as eggs. Personally, I DID receive all rewards, but I am not sure whether this was influenced by my being the quest owner, as I haven't heard from all involved party members yet, and so far everyone who has responded about the issue on our party page has also been affected. Thanks in advance for any help anyone can give in resolving this matter!

**Comment by DeweyReadmore** [comment] 2016-04-07 21:08
I will continue to update here on behalf of any additional users in our party who report having been impacted in this manner, since many are non-native English speakers and may not feel comfortable attempting to explain the issue in detail in English. I hope that this won't be too confusing! Sorry for the trouble. :)

**Comment by ghost** [comment] 2016-04-07 21:27
Username: petrajaga
User ID: 94924696-eb5d-4124-a436-ee6f1c71d04f
Browser: Firefox
OS: Windows 7

I'm a member of this party and have also not received the rewards at the end of this quest.

**Comment by Alys** [comment] 2016-04-10 11:02
I've given the quest rewards to @luhm, @petrajaga, and to SarahDsp (6b77ed3d-8a8e-4ac5-820d-b5188e16e074).

@DeweyReadmore Could you please tell me the User ID for Alan? There's a few too many players with that name for me to be able to track down the right one. :) You can see his User ID by clicking on his name from your party page or his avatar in the Habitica website's header.

Alternatively, since you're in a large party and many members might have been affected, I can just give the quest rewards to all party members, excluding yourself and the three I've already awarded. It won't bother us if some players happen to get double rewards from this.

Sorry about the trouble. :( This does tend to happen in larger parties. We're trying to improve the site's code to reduce problems like this.

**Comment by DeweyReadmore** [comment] 2016-04-10 16:18
Thanks so much, Alys! Alan's User ID is 5dac9a81-e0b8-4190-88b3-69bce26aa9f0
Nobody else has reported being impacted at this time, so I think that will clear it up. Appreciate your help!

**Comment by Alys** [comment] 2016-04-11 01:42
@DeweyReadmore I've given the achievement and eggs to Alan. He should reload if he doesn't see them. Please tell me if they don't appear after that!

I'm closing this now but if you find other players who didn't get the rewards, comment again here. We'll still see your reply even though this is closed.

**Closed as completed by Alys** 2016-04-11 01:42 UTC

**Comment by ghost** [comment] 2016-05-12 20:59
Hello,

For the party, again with my username (petrajaga), I participated in but didn't receive the awards for the following quests:
- The Moonstone Chain, Part 1: The Moonstone Chain Quest (I've completed this quest once before, but wouldn't mind getting the rewards for this new round - especially the XP)
- The Icy Arachnid

Some more members have mentioned not receiving the Moonstone Chain #1 quest rewards, but I haven't seen a new threat get opened, so I'm commenting here.

Many thanks!

**Comment by Alys** [comment] 2016-05-13 12:06
@petrajaga 
Could you please tell me your User ID? To find out how to get it from either the website or app, see step 6 of the [Report a Bug](https://github.com/HabitRPG/habitrpg/issues/2760) instructions (also available from Help > Report a Bug in the Habitica website's menu).

**Comment by DeweyReadmore** [comment] 2016-05-14 00:31
@Alys The UUID for @petrajaga is     94924696-eb5d-4124-a436-ee6f1c71d04f. I just realized that I didn't receive the rewards for Moonstone Chain Part 1 this go around either, interestingly. I've completed that scroll before, though, and I don't need the rewards, but I'll keep asking around in our party to make sure nobody else was affected. Thanks again for all of your help, @Alys ! Sorry for the trouble!

**Comment by Alys** [comment] 2016-05-14 00:43
@DeweyReadmore what's your User ID? I'll do both of you at once.

**Comment by DeweyReadmore** [comment] 2016-05-14 00:50
Oh, I don't need the rewards, thanks though! I just mentioned it in case that helps you identify the source of the error or something (not sure whether you keep statistics on this sort of thing?). And I haven't heard back from any other party members about this issue yet, either, so it looks like it's just @petrajaga for now. :) Thanks!

**Comment by Alys** [comment] 2016-05-14 01:33
Sorry @DeweyReadmore I missed that in your earlier post. We know that this problem isn't caused by a bug as such, it's because when the quest ends, if there's a lot of people who need the rewards or if Habitica is overloaded for other reasons, then the reward process times out before everyone's accounts are modified. We're coming to the end of a project to improve Habitica's code to make it more efficient, so timeouts like this will become less likely. 

@petrajaga I've given you the quest rewards and achievements.
