### ISSUE TITLE
Tag icon displays for unlabeled tasks (browser)

### ISSUE THREAD

**Issue by samicpeterson** [HabitRPG/habitica#6871] opened 2016-03-12 22:12 UTC
user: de71eec1-3b74-48eb-9da2-28424ab6817b
browser: chrome
OS X 10.9.5 

Newly created habit, dailies, and to-do items show the "tag" icon, despite no tag assigned. Tag icon persists even after editing the task, and after a hard refresh. I did not create any new tags today (only have about 7 total). There don't seem to be javascript errors, but I'm new to using the console for that function.

Thanks for such a great application! Hope reporting this bug helps. No reply needed.

**Comment by samicpeterson** [comment] 2016-03-12 22:13
(actually, upon taking a second look, the tag icon displays for _all_ tasks, even old ones)

**Comment by Alys** [comment] 2016-03-13 02:31
Confirmed, thank you!

**Comment by keysmashes** [comment] 2016-03-13 22:29
I'm investigating this – it started after 2a5011b and before(/by) ~~a9c9d6d~~ 05676d8, but I'm slowly narrowing that gap.

**Comment by keysmashes** [comment] 2016-03-13 23:02
Caused by c399677 (although 05676d8 should be checked out for investigation, as it removes a conflict marker in `common/script/index.js`). I'm stumped as to why this breaks things.

**Comment by paglias** [comment] 2016-03-13 23:04
My fault here, it should've been fixed with https://github.com/HabitRPG/habitrpg/commit/b948fc031f8b5979c47d016715b8b7774af86973

**Comment by paglias** [comment] 2016-03-13 23:16
The fix will go live with the next deploy of the site

**Comment by paglias** [comment] 2016-03-13 23:16
The fix will go live with the next deploy of the site

**Closed as completed by paglias** 2016-03-13 23:16 UTC
Labels: help wanted

**Comment by Alys** [comment] 2016-03-14 09:48
@anowlcalledjosh Thank you for investigating this!
