### ISSUE TITLE
Daily: Data column(s) for axis #0 cannot be of type string

### ISSUE THREAD

**Issue by NotChrisPlease** [HabitRPG/habitica#527] opened 2013-02-27 01:24 UTC
When I click progress on a couple of my dailies I get this.
![dailyerror](https://f.cloud.github.com/assets/3453299/199326/51dfd69e-807c-11e2-82ad-d0db23fe755e.PNG)

**Comment by busterroni** [comment] 2013-02-27 04:16
Duplicate of #315

**Closed as completed** 2013-02-28 00:52 UTC
