### ISSUE TITLE
Dailies not reseting

### ISSUE THREAD

**Issue by Catmagnet** [HabitRPG/habitica#983] opened 2013-05-17 11:06 UTC
My husband has recently created a character in Habit RPG, and now he cannot access it at all.  When he tries to log in it tells him "User Not Found With That Username."  Here are his stats:
Umikuma Tanuki  (aac18778-9d2e-4c51-ab61-e6b0cf601f6c) 
He's rather upset about this, because he actually bought some jewels (because he was impatient to get a pet).  He would very much appreciate any help he can get.

**Comment by lefnire** [comment] 2013-05-17 11:10
[edit: removed api token from post for security]. Looking into

**Comment by lefnire** [comment] 2013-05-17 11:12
username is "Tanuki", make sure to use proper capitalization - character shows dandy in the database

**Comment by Umikuma** [comment] 2013-05-17 11:36
Thanks. I was able to log in but my dailies won't reset. If I try to log in with Facebook it sends me to a different account with nothing - brand new. Can that be fixed so it points to the right account?

**Comment by lefnire** [comment] 2013-05-17 11:39
You registered with username / password, so that's one account. When you
log out and click to register with Facebook, it creates a new account. We
have "consolidate multiple accounts" in the feature queue of derby-auth
https://github.com/lefnire/derby-auth/issues/16 , but might not tackle that
for some time. Regarding dailies, do you have any JavaScript errors in
chrome console? Do you have a custom day start that's after the current
time of day?

**Comment by Umikuma** [comment] 2013-05-17 11:45
I have it set to start each day at 08:00, but it didn't reset at all on Thursday morning and is still that way. No Javascript errors, and It's like that on my phone, too.

**Comment by lefnire** [comment] 2013-05-17 11:51
Hmm, strange! Well, I'm testing your account locally and everything reset
for me just fine. Which browser you using? I find Chrome latest works best
for most people

**Comment by Umikuma** [comment] 2013-05-17 11:53
I'm using Chrome on my laptop and Opera on my phone.

**Comment by Umikuma** [comment] 2013-05-17 11:56
All the dailies are still grey after resetting, even though I've been unable to enter any for today.

**Comment by lefnire** [comment] 2013-05-17 12:01
ok, will check out soon as i can. Limited internet currently, will have better internet in the evening so i can download a database snapshot and investigate more. what timezone are you?

**Comment by Umikuma** [comment] 2013-05-17 12:03
We're om Mountain Daylight Time - Utah. Thanks.

**Comment by lefnire** [comment] 2013-05-17 12:04
Used to live in Payson :) Kk, will ping you when I can dig further

**Comment by Umikuma** [comment] 2013-05-17 12:06
Cool! Thanks.

**Comment by Catmagnet** [comment] 2013-05-22 09:09
Hmmm.  Is this catching?  Because today, all day, my dailies have not reset.  Also, even though I've got my daily reset at 8 a.m., one of Wednesday's dailies has already ungrayed.  It's a daily that's ONLY a Wednesday daily, so I know it shouldn't be on Tuesday (which is what it should still be for me).  Luckily the health hasn't gone down either.  But I'd like to be able to do my dailies!

**Comment by Catmagnet** [comment] 2013-05-22 09:10
Oh, and BTW, I've tried this in both Firefox (my normal browser) and Chrome (which is glacially slow on my computer, so I don't usually use it).  Same for both.

**Comment by gatorshoes** [comment] 2013-05-24 16:39
I'm also having this problem now. I checked my account into the inn last night because I was feeling ill and couldn't finish the rest of my dailies, and when I checked out this morning, all of my dailies from last night were still checked/greyed out and I can't uncheck them without affecting my streaks or deducting exp from myself. My account name is gatorshoes, and I have it set to reset every day at 6am. It was 10am when I checked it, and the day still hasn't rolled over on my account at 12:37pm as I write this. I'm going to try setting my roll-over time to 1pm and see if it rolls over properly in a half hour, because I'm a bit annoyed.

UPDATE: Changing the roll-over time didn't work, issue still unresolved.

**Comment by wc8** [comment] 2013-05-24 18:04
@gatorshoes inn functionality was changed in an attempt to avert lengthy, unnecessary stays. I think this might actually be the expected functionality, where it just sort of freezes your account for the nights you stay there.

**Comment by gatorshoes** [comment] 2013-05-24 19:33
@wc8 Ah, I see. I have a need to keep all things "even", so that particularly aggravates that need. I'm sure it's just me, but I feel like I can't check any of the day's tasks if my ability to properly check the others is impeded. When I check out of the inn when I no longer require it, how am I supposed to do that day's tasks without penalizing myself by removing the ones I did before I checked into the inn and losing exp in the process? That's useless.

**Comment by wizonesolutions** [comment] 2013-05-25 21:29
@gatorshoes What I do is just check the ones that I did the previous day despite the stay in the inn. They won't reset, but that's the price I pay for using the inn. Rather than losing HP, I simply have to wait longer to gain more XP. That makes sense to me. I have to "pay" for the inn in some way, after all :)

**Comment by impr** [comment] 2013-05-27 18:13
My dailies are also not resetting. I've never been in the inn but when I logged in this morning my dailies from yesterday were all still checked and grey. The two "dailies" I have to do today but did not have to do yesterday (MWF only dailies) are now colored and not checked so my account clearly knows it is Monday. I have my end-of-day time set for 0400 so it should have all reset last night... I'm trying changing my reset time to 1200 to see if it resets in 45 minutes but I am not optimistic given this didn't work for the other user upthread. Any other possible patches to work around this?

I'm afraid I made a new report for this issue before finding this thread: https://github.com/lefnire/habitrpg/issues/1057

**Comment by gatorshoes** [comment] 2013-05-28 01:55
@impr I checked my account out of the inn and reset my roll-over time to a later hour so I could see whether or not it would properly roll over and it did not. I had to wait a full 24 hours before it fixed itself.

**Comment by Catmagnet** [comment] 2013-05-28 23:34
I've never been in the inn.  Two days ago, my dailies didn't reset.  Today my dailies didn't reset.  Also, everything I checked off last night (so that I leveled up) was gone this morning, so I hadn't leveled up.  This is quite annoying, since I can't check off what I've done today because my dailies didn't reset!

**Comment by gatorshoes** [comment] 2013-05-30 16:33
It happened to me again. My account was in the inn again when it happened this morning, but I'm going to assume that isn't the issue because the last time I had my account in the inn, my dailies rolled over fine - I just didn't have any penalties and it didn't break my streaks, which is how I had always assumed the system was supposed to work. There goes another day of productivity, I guess.

I did a bit of Googling, and this isn't an uncommon bug at all. I've found multiple threads ranging from /months/ ago that reference this issue, long before the Inn was reprogrammed.

**Comment by Elementara** [comment] 2013-06-19 14:37
My dailies are now not resetting. I was in the tavern off and on for a bit but since I exited the tavern things just aren't working right. I have one M-F daily that has been greyed out and checked since I left the tavern. 

I'm using Chrome on Windows 7. My user id is 0cf3f370-a3ee-48f3-9ca7-04cb600cccc2

I have one error in my java console but it appears to be related to a google ad, so I don't think it's related.

**Comment by lefnire** [comment] 2013-06-19 15:07
@Elementara your account is showing you're still resting in the inn. Can you check that you don't have zzz's above your head, and that the rest-in-tavern button says "Check Out" instead of "Check In"?

**Comment by Elementara** [comment] 2013-06-19 15:11
Okay, that's really weird. I checked out of the inn yesterday or the day before and did some of my dailies yesterday. I didn't check back in. My name plate obscures the top part of my head so I've got no idea if there were zzzs or not. 

I'll have to watch that and see if I return to the inn again.  Thank you.

**Comment by Elementara** [comment] 2013-06-19 15:11
I also shortened my name so my name plate isn't so big.

**Comment by lefnire** [comment] 2013-06-19 15:18
You probably checked out during server downtime caused by #165, which will be fixed in the framework upgrade (in progress)

**Comment by Elementara** [comment] 2013-06-19 15:20
Oooh. And the zzzs would have been a clue.

Thank you!

**Closed as completed** 2013-06-23 19:32 UTC
