### ISSUE TITLE
None of my checked dailies were counted yesterday, except for in the party quest

### ISSUE THREAD

**Issue by intirb** [HabitRPG/habitica#7499] opened 2016-05-25 19:06 UTC
General Info
- UUID: fcbeedbb-d4f9-4eca-bfc9-6e32a6f172a1
- Browser: Firefox
- OS: Linux and Windows
### Description

This one is sort of weird.  I checked off all but two of my dailies yesterday, and I also cast stealth.  The party quest recognizes that I checked off my dailies (the party chat says I did damage to the boss), but all of my dailies streaks were reset (except the ones protected by stealth).  Looking at the data display tool shows that none of my dailies were checked, which isn't what actually happened.  It does recognize my habits from yesterday though.

I manually fixed my streaks but I thought I should report this bug in case anyone else encountered it.  I use both linux and windows machines throughout the day, and this has never been an issue for me before.

**Comment by citrusella** [comment] 2016-05-25 21:25
It's not this bug, is it? #4313 (Though the party recognizing the doing of the dailies sounds out of character of that bug, so maybe not?)

**Comment by intirb** [comment] 2016-05-26 01:06
I don't think so?  My dailies weren't checked off this morning - they were unchecked and streaks had been lost as if they had not been checked yesterday.  But as I read that bug description, I'm pretty sure I also did receive drops yesterday as I was checking off my dailies, which means I must have synced with the server, no?

Hard to say exactly how the party treated my dailies - I did do damage, but the boss's counter-attack is masked right now, so no clue if the party would have received damage or not.

**Comment by citrusella** [comment] 2016-05-26 02:16
Yeah, apparently my reading comprehension was... not the best earlier? I've heard of your bug (like I could have sworn someone mentioned it in the Tavern), but that's probably not it and I don't remember seeing it reported on Github, so... :confused:

**Comment by Alys** [comment] 2016-05-26 02:39
@intirb This will have been caused by cron running twice at the same time for your account - I'm sorry about that! It's from the same cause as this bug: https://github.com/HabitRPG/habitrpg/issues/2805 which we've been seeing much more often this week. paglias has already created a fix for it and it will be deployed within the next few hours. I'll close this issue now, since even if it persists, we'll be tracking it in the other issue. However if you notice this happening again tomorrow or afterwards, feel free to comment again!

**Closed as completed by Alys** 2016-05-26 02:39 UTC
