### ISSUE TITLE
Some dailies didn't reset

### ISSUE THREAD

**Issue by brightbold** [HabitRPG/habitica#1601] opened 2013-10-07 12:02 UTC
All the dailies I checked off after 8pm (EDT) yesterday are still checked this morning. My turnover time is 2am. One of them had a 93 streak which stayed intact, one had a streak of 3 or 4 that has reset to 1, and I don't think the other two had streaks and are both at 1. (I'm mystified as to why one streak reset and one didn't!)

I solved this fairly easily by unchecking all the tasks and then resetting the streaks and the XP, so the only thing I lost was that a daily that had gone to green yesterday when t back to yellow. No big deal for me but obviously something you want to fix if you can reproduce it.

**Comment by lefnire** [comment] 2013-10-17 01:01
dupe of https://github.com/HabitRPG/habitrpg/issues/1057, let's follow up there

**Closed as completed by lefnire** 2013-10-17 01:01 UTC
