### ISSUE TITLE
Invited friend to join party and she accepted, but now shows up in both the party member and invited lists

### ISSUE THREAD

**Issue by crystalraebryant** [HabitRPG/habitica#6259] opened 2015-11-17 17:49 UTC
**My User ID:** 11a45a75-0310-4d75-9f88-fec2691db78f
**Friend's User ID:** bf8806ad-1319-49a5-a480-90df4aa348e5
**Group ID:** 7cc472f1-1e15-4d1f-8199-675e36a4a26e

**Browser:** Chrome 46.0.2490.86 m
**OS:** Windows 10
**Javascript errors:** none

![capture](https://cloud.githubusercontent.com/assets/14956396/11219581/c60bae90-8d20-11e5-86c2-f6c889d1ead0.PNG)

Possibly related:
My friend joined via an invite that was sent when I created the party. My friend had issues signing up, and ended up signing up twice. She deleted the other account, but it didn't make any difference. I think that if I delete this group and start a new one and invite her to the new one, the issue will go away, but I'm leaving it as is so I don't destroy the evidence. It's not keeping us from starting a question, but it does keep telling her she has an invite to the group she's already a part of.

**Comment by SabreCat** [comment] 2015-11-17 20:20
Duplicate of #5649 .

**Closed as completed by SabreCat** 2015-11-17 20:20 UTC

**Comment by Alys** [comment] 2015-11-17 20:31
@crystalraebryant I've removed the invitation from your party and from your friend's account. However these tend to come back, so if it reappears, you or your friend or anyone else in your party can comment here and I'll remove it again. We'll still see your comments even though this issue is closed.
