### ISSUE TITLE
Critical Hit Bug

### ISSUE THREAD

**Issue by SpyPoet** [HabitRPG/habitica#3072] opened 2014-03-14 01:04 UTC
This happened just now while I was doing my stuff: It looks like the box for a critical hit (same type of coloring, etc). I couldn't read through the whole thing to see what it said before it disappeared, though. Google Chrome is my browser of use.

![habitcritissue](https://f.cloud.github.com/assets/6946770/2417056/6f667bdc-ab14-11e3-8f44-2148074b44b6.png)

**Comment by SabreCat** [comment] 2014-03-14 02:08
This is the error box that pops up when the server goes down and your browser tries to process a task action. Thus I believe this is a duplicate of #3065.

**Closed as completed by SabreCat** 2014-03-14 02:08 UTC
