### ISSUE TITLE
Dailies Error: Data Columns

### ISSUE THREAD

**Issue by tessa159** [HabitRPG/habitica#3808] opened 2014-07-30 06:16 UTC
Upon creating a new daily, when I click the progress button, instead of the usual graph it shows, it tells me that data column(s) for axis #0 can not be of type string.
![image](https://cloud.githubusercontent.com/assets/6089151/3745699/08513f0e-17b1-11e4-917a-d014d59a6bdb.png)

**Comment by Alys** [comment] 2014-07-30 07:40
Confirmed in Chromium on Linux. Will confirm in Chrome on MacOS later today.

**Comment by Alys** [comment] 2014-07-30 07:42
Oops, no I won't. This is a duplicate.

@tessa159 : You can follow the progress of this in https://github.com/HabitRPG/habitrpg/issues/3691

Note that it's unlikely this will be fixed as a high priority since the graph wouldn't show any data anyway for a new daily. It's a minor cosmetic issue more than anything.

**Closed as completed** 2014-07-30 19:33 UTC
