### ISSUE TITLE
Aborting a quest with an inactive quest owner

### ISSUE THREAD

**Issue by NephFirefly** [HabitRPG/habitica#4904] opened 2015-03-23 05:18 UTC
User ID: da6c6f7c-2dc5-436e-8f73-55e0153d104f
Group ID: 9c878693-9186-427c-bec7-02288a71513a

Several months ago (very early fall 2014) a member of my group started a quest and left it up barely long enough for anyone else to join. There were only three of us who were able to join, out of over 10 active group members. Unfortunately, shortly after starting the quest the quest owner stopped using HabitRPG altogether. Due to no one else being able to participate, a bunch of members either went inactive or left the group. When I was clearing out inactive members the other day, I accidentally kicked the quest owner, not thinking much of it at the time, though I'm sure since they haven't been on in 4-5 months messaging them wouldn't help, either. In late December the only other person in the quest changed their status to resting in the tavern, and since then it has just been me doing the Vice Awakens quest, for three months. It's incredibly frustrating, and I am hoping that there is a way to abort the quest so that I can start up a new one that will include everyone in the group and bring the fun back into the experience. Any help is appreciated.

Thank you very much!

**Comment by Alys** [comment] 2015-03-23 05:22
We can definitely get this sorted out for you. I'll do it when I get home in a few hours if no one else gets to it first.

**Comment by Alys** [comment] 2015-03-23 05:28
Note that first I'll have to check to ensure that all of the quest participants except you are inactive (and if they are not inactive, I'll need to ask their permission too), but given what you've said, that's probably just a formality. :)

**Comment by Alys** [comment] 2015-03-23 10:25
I've confirmed that the only other person on the quest has been resting in the inn since mid-December, as @NephFirefly says, so I feel justified in ending this quest. I'm just waiting to get one piece of information from NephFirefly in a private message before I do that (any GitHub admins can ask me about this privately if they want details).

**Comment by NephFirefly** [comment] 2015-03-24 02:55
I responded to your message.

**Comment by Alys** [comment] 2015-03-24 04:57
Fixed. Let us know tomorrow if you're not able to start a new quest. I'll close this now, but if you comment here we'll still see your message and will help you.

**Closed as completed by Alys** 2015-03-24 04:57 UTC
