### ISSUE TITLE
Request: option to toggle character bar and rewards column

### ISSUE THREAD

**Issue by Gitanj** [HabitRPG/habitica#654] opened 2013-03-14 22:01 UTC
I'd love to see an option to toggle the visibility of the character bar (toon, health bar, experience bar) and the rewards column. That way, there's a "todo" look (habits, daily, todo) to habitrpg.

(Not sure if this has been requested)

Thanks.

**Comment by wc8** [comment] 2013-03-14 22:19
Vote for [Toggle Header](https://trello.com/c/GHYcVQfD)

**Comment by lefnire** [comment] 2013-03-15 21:26
added the toggle header. do we really want toggle rewards?

**Comment by wc8** [comment] 2013-03-15 23:29
Perhaps just filter them via tags? Allow user could hide any items not relevant to his environment?

**Comment by lefnire** [comment] 2013-03-15 23:49
good call @wc8, I forgot we were originally planning on having system tags too. So once we get tags in, I'll add columns in there, and move in the header toggle.

**Comment by wc8** [comment] 2013-03-19 17:06
Duplicate of/Related to #657

**Closed as completed** 2013-03-19 17:07 UTC
Labels: status: issue: suggestion-discussion
