### ISSUE TITLE
Unchecking daily sometimes removes incorrect amount of XP/Gold

### ISSUE THREAD

**Issue by nmohoric** [HabitRPG/habitica#2331] opened 2014-01-09 20:53 UTC
Sometimes when you uncheck a daily it will remove more or less xp/gold than rechecking it gives you. I haven't been able to track down the specific instances that this occurs but you can definitely see it if you create a new user and check/unckeck the second or third daily.

![capture](https://f.cloud.github.com/assets/156065/1882033/096ca5ac-7970-11e3-88ed-01cd4cd3be21.JPG)

**Comment by colegleason** [comment] 2014-01-09 21:09
I believe this is because we don't actually record the amount given to you.
Therefore, unchecking it just goes through the scoring again and multiplies
it by negative one.

Should maybe fix by keeping track of Gold, XP, MP given for a daily/todo
and then using those when unchecking.

On Thu, Jan 9, 2014 at 2:53 PM, Nick Mohoric notifications@github.comwrote:

> Sometimes when you uncheck a daily it will remove more or less xp/gold
> than rechecking it gives you. I haven't been able to track down the
> specific instances that this occurs but you can definitely see it if you
> create a new user and check/unckeck the second or third daily.
> 
> [image: capture]https://f.cloud.github.com/assets/156065/1882033/096ca5ac-7970-11e3-88ed-01cd4cd3be21.JPG
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/HabitRPG/habitrpg/issues/2331
> .

## 

Cole Gleason
Student, University of Illinois at Urbana-Champaign
Computer Science, Class of 2015
cg@colegleason.com | colegleason.com

**Comment by snicker** [comment] 2014-01-09 23:50
@colegleason I'm sure that @lefnire will have to tackle that exact task when implementing proper "Undo" functionality ;P

**Comment by snicker** [comment] 2014-01-09 23:51
duplicate of #964

**Closed as completed by snicker** 2014-01-09 23:51 UTC
