### ISSUE TITLE
PMs appearing out of order

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica#10730] opened 2018-10-02 11:12 UTC
New PMs are appearing at the top older ones, although older ones remain in the correct order. I'm experiencing this (Google Chrome on Windows 10), and citrusella as well per this report:

> My PMs are being pretty weird. New ones are appearing before the oldest ones (that is, before the "origin" of the conversation, so they're all the way before ones that are from three years ago, which initially led me to believe I had a notification for a PM that wasn't showing up). In addition, my chat avatar on all PMs turns into @Alys but only after viewing my conversation with her (before that, all my chat avatars in other conversations are fine and no one else's avatar does this); Alys's conversation is also the only one with messages recent enough to be swept into this bug I'm experiencing. These issues persist through reloads and complete browser restarts. New PMs I send initially are at the bottom of the messages where they should be but move to the top with the others after a reload. This was not an issue at 14:20:46 UTC 2018-10-01 (when I sent a PM to Alys earlier this morning, the most recent PM I sent to anyone before this started happening) but has been an issue since at least 21:58:39 UTC 2018-10-01 (when Alys replied to me). I don't know if this is just a me problem, just an Alys-and-my-convo problem (I haven't PMed anyone else recently to know if it's more than just her), or an everyone problem. (As an extra note, the messages are in the "proper" order oldest to newest in their erroneous place in line, like "1 hour ago, 10 minutes ago, 5 minutes ago, 3 years ago, 3 years ago, 2 years ago, 1 year ago" etc. but all new ones are up there instead of at the bottom like usual.) I feel like this is a little rambly so please ask for clarification if this doesn't make sense.

And additionally she says:

> (Extra note: This is only happening on the website. The Android app displays them all in their proper place in order. 0_o Would have deleted and recreated the post I just made but it's a little bit of a complicated explanation and I don't want to somehow inadvertently lose any part of the message.)

**Comment by citrusella** [comment] 2018-10-02 14:24
VıccTнσя, the brazilian fox is also experiencing this and has provided a screenshot of the avatar issue [here](https://snag.gy/es0dQY.jpg). I don't know if VıccTнσя's issue is limited to that person like mine is limited to Alys right now, or the exact things that could cause the avatar to change (i.e. if it's limited to the most recent conversation in the list, if it happens to any conversation with messages new enough to be caught in this bug, etc.)

**Comment by citrusella** [comment] 2018-10-02 19:49
There have been reports in the Report a Bug guild today of people who might be having the same issue, except they say they don't see the messages anywhere in their conversations. :-/ Figured I'd post them here in case they're related, so they don't get lost if not:

Charlei (d60a7a50-7482-46b8-8b40-88c6b5bf1863):
> Hello there! I just joined, but I keep having issues with messages and they get more weird every day! Since a day or two I have 1 uread message note but there is noone in the display. And now I got a note on phone (from like 24h earlier) that I got a message and that person explaining the same issue. now I tried to reply, I dn't even see that message, plus my avatar looks exactly like hers when I posted something. I now have at least 3 mysterious messages, they are not at the bottom nor at the top of any of the conversations I had. I find the messaging system very confusing, I rather ask people to message on another site or conversate through guilds (which they are not meant for..). :/

Wildling (9352b9cd-d3e2-439b-af9e-b277598f46f8) mentioned having the "same exact issue".

Arnavi Weiwei, a warrior of soul** (c6815c12-7caf-4d40-89cf-36ea8ac2435b), in the Tavern:
>Are messages not working? I tried few times, its not showing up!

(I told them they might be at the top of the convo if they're on the website)

>@citrusella, the serving wench yes I am on website..Old msgs are there but I am not able to send new! So bug may be there !!

(I suggested they go to the bug guild but they didn't (yet?))

AShore (24eb3e91-08af-4fa1-b91d-c08331afbf32) at first glance seemed like they might be experiencing something similar but I think they're either having something else go on or basic sync issues (messages in their party are also disappearing/never appearing and their skill casts don't seem to be going through). Felt weird not mentioning their report, though, so here it is.

**Comment by paglias** [comment] 2018-10-02 19:52
This is probably due to a change we deployed a couple of days ago, sorry for the issue. If someone experiencing issues can look into their console for possible errors that would be great, thanks

**Comment by shanaqui** [comment] 2018-10-02 19:58
@paglias I just had a go and couldn't see anything coming up that seemed specific to the inbox. Definitely nothing comes up if I clear the console and then try loading my inbox. If there's a particular order to do things that might yield helpful results, let me know.

**Comment by citrusella** [comment] 2018-10-02 19:59
I'm not getting any abnormal console output either on loading Habitica, on loading the messages window, or on loading conversations with or without affected messages.

I wonder if someone not seeing newer messages at all would have a different experience, but...

**Comment by kirsty-tortoise** [comment] 2018-10-02 20:20
I've been doing some investigation because this seemed interesting:
 * On older messages, the timestamp is a number while newer ones have a proper string timestamp. I wonder if they are not being compared properly somewhere? I haven't been able to test locally though due to lack of older messages locally. Possibly this code needs investigating:
https://github.com/HabitRPG/habitica/blob/362ca73c94ec010d05e7a888c7de8a82e7e23e5a/website/client/components/userMenu/inbox.vue#L289-L291
as it should be probably using moment or something?
 * At least one of the issues with avatars seem to be being caused by this code:
https://github.com/HabitRPG/habitica/blob/362ca73c94ec010d05e7a888c7de8a82e7e23e5a/website/server/models/user/methods.js#L156-L157
I suspect we should be setting the sender message styles to the sender, and not the receiver.
This is server side, so I don't think fixing it will make the messages affected so far, but would stop future messages having this error.

**Comment by paglias** [comment] 2018-10-02 20:35
@kirsty-tortoise you reached my same conclusions :) It's fixed here https://github.com/HabitRPG/habitica/commit/5a8366468b9686d8541b18a6f58fa7d64c1522ed and we're testing it right now

**Comment by paglias** [comment] 2018-10-02 20:52
Sorry again for the issue, it's been fixed in https://github.com/HabitRPG/habitica/commit/5a8366468b9686d8541b18a6f58fa7d64c1522ed and will go live later today. 

Some, hopefully all,  messages that didn't appear at all were simply mis-ordered so they should appear correctly after the deploy

If they do not it's possible they have placed in the user's conversation with itself. 

If they're not there either by tomorrow it would be great if I could have your UUID and some info about the message that disappeared.

I'll leave the issue open until the fix is deployed

**Comment by citrusella** [comment] 2018-10-03 05:24
Just a note: I checked just now and my PMs to/from Alys (the only reference for the bug I had) are in the right order but I've still got her avatar. (I feel like a rebel, stealing the Kickstarter set like that. XD)

I don't know if the fix has been deployed but wanted to make that note before I went to bed since I noticed it.

**Comment by kirsty-tortoise** [comment] 2018-10-03 06:04
@citrusella If you send a new message, does that new message still have her avatar? I think that's all the fix would do.

**Comment by Alys** [comment] 2018-10-03 07:21
@kirsty-tortoise should be thought about that. The details that display the avatar are stored within the message and so they won't change in an existing message after a bug has been fixed. @citrusella enjoy the avatar ;)

**Comment by paglias** [comment] 2018-10-03 07:57
Yes, old messages will keep the wrong avatar

**Closed as completed by paglias** 2018-10-03 07:57 UTC
