### ISSUE TITLE
I don't have the Veteran Wolf

### ISSUE THREAD

**Issue by 101Leafy** [HabitRPG/habitica#2527] opened 2014-01-23 02:05 UTC
I'm an Original User, so I have the Veteran Badge. However, I don't have the Veteran Wolf. Why?

**Comment by deilann** [comment] 2014-01-23 08:26
Mentioned here: https://github.com/HabitRPG/habitrpg/issues/2329 Not sure if the push ever happened, though, as I still don't have mine.

**Comment by SeanStiny** [comment] 2014-01-23 15:13
I also still don't have mine.

User ID: 776d604e-b3d4-4b61-8c7a-6928ef24e40a

**Comment by lefnire** [comment] 2014-01-29 21:46
dupe of #2329 follow there. I'll push the migration sometime this week

**Closed as completed by lefnire** 2014-01-29 21:46 UTC
