### ISSUE TITLE
Skills drawer jumps rightward, partially offscreen, in some browsers

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#10618] opened 2018-08-22 19:22 UTC
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)
### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)

Two users have reported the following strange behavior of the skills drawer on the Tasks page:

![image](https://user-images.githubusercontent.com/4501321/44485554-955a1400-a616-11e8-9fb0-a5673f44b594.png)

**Dragonfyre** (f803a498-5771-4d39-8e6b-bd181b026858)

>@Aerilita Yeah pretty much just like that. I'm using Firefox on my Win8.1 desktop not a smart phone. It used to be fine but one day it just appeared on one side one day out of nowhere.
>Also, there was no error message. The Skills tab is just moved over for some reason.

**Comment by TheHollidayInn** [comment] 2018-08-23 20:08
Hmm. I can't recreate this. Maybe the chat plugin they are using is causing it?

**Comment by SabreCat** [comment] 2018-08-24 20:24
Ooh, good call, that Groups tab is a giveaway. I'll contact these users about it and have them test with and without the plugin.

**Comment by Alys** [comment] 2018-09-01 07:02
We have a couple of reports in the Bug guild that this doesn't happen because of the chat plugin:

From about 6 days ago: Poirot (699974bb-7b8f-435b-8152-06a502ebe37e): "Hi @Alys, nope, I don't use any chat plug-in at all, that is , not that I am aware of. Just normal use of the website (and the 4 styles which I disabled yesterday for the testing and reloaded the site, bug still there)."
They followed up with this screenshot:
![scn](https://i.imgur.com/as3ZEZw.png)

---

From about 2 days ago: PurplePanda9 (08089e04-6a42-490d-afad-543764614883): "I am experiencing the same "skills drawer shifted to the right" issue/bug/effect last discussed here ~3 days ago, but only in Safari (Version 10.1.2 (10603.3.8)), not in Chrome (Version 68.0.3440.106 (Official Build) (64-bit)). I don't have any extensions, plugins, or anything else that I know of. Its not a problem for me, just thought that I would report the information."

---

From 5 to 8 days ago:
The Druid (68ce1251-d4a8-4ed6-ada4-f9ebea261d1e): "@citrusella, the serving wench Just to confirm, I deactivated the chat extension and it didn't fix the problem."



"Here's my browser version if that's helpful: 49.0.2623.112 m (Chrome)"

"I also tried opening it in Firefox, and it only gets more confusing. When I'm in Chrome the bottom of the columns look as they appear in the screen shot, which is unmarked as far as habits/dailies, etc. (I think that's what caused the earlier confusion. In Firefox they're labeled as they should be, but the drawer is still in the wrong place. So whatever is causing the end of the columns to be unlabeled (which I didn't even notice) is separate from the drawer issue."

"I'm not using either style currently, though I may have used one of them in the past. I'm not sure on that. Mostly I used a few styles immediately after the redesign to restore some of the functionality that I was used to, but I stopped using them as site changes were made. The only one I used until recently was one to hide task notes, but I even stopped using that one a month or two ago. It was well before this issue occurred. In another attempt to make sure no styles were applied I completely disabled Stylish and all similar apps. No change."

citrusella, the serving wench (2d6ef231-50b4-4a22-90e7-45eb97147a2c): "@The Druid I just thought of a question: You said you see it fine on your boyfriend's computer. Are there any differences between his setup (i.e. browser, extensions, etc.) and yours that could explain it, even if they don't seem related?"

The Druid (68ce1251-d4a8-4ed6-ada4-f9ebea261d1e): "@Alys I can confirm...it's not the chat plug in. I tested this a few days ago and posted to say there was no change. @SabreCat already asked me about it via PM and I've let them know as well. @citrusella_the_serving_wench I saw your post, and will answer in more detail when I'm not on mobile, but the only thing I think could be an issue is that I don't have my Firefix browser updated (and can't, because of a to old OS) while my boyfriend's computer is updated. There are a few other differences that probably aren't a factor, but I can still detail them later."

The Druid (68ce1251-d4a8-4ed6-ada4-f9ebea261d1e): "@citrusella, the serving wench I'm a bit slow, but here are the rest of the difference between my boyfriend's computer and mine, in addition to the more current OS/browser. He has a much larger screen, and what I guess are slightly different screen settings, as I can see a little bit more of my party member header (not a lot...maybe an extra 1/2 of a member or so). He also doesn't have any extensions on his browser. I don't think the screen size/setting is the issue though, because on my computer, only the drawer on the task page is to the right. All other pages display the drawers correctly. Some with the extensions, really. Again, I don't have any that directly interact with Habitica except the chat/groups extension, which I already tried disabling without effect. Which is why I think that the only important difference might be that his browser is updated and mine isn't."

**Comment by Aerilita** [comment] 2018-09-01 12:33
If I can offer an observation: in both of the screenshots the left side of the skills drawer splits the grey Habitica symbol exactly in the middle. As I understand, the symbol is centered. So it seems as if the left side of the drawer is centered, instead of the drawer's whole container.

**Comment by Alys** [comment] 2020-10-28 09:38
_@CathB (36976c15-5bcd-4197-965c-750d865abcd2) has reported this bug:_

"In Mozilla Firefox, my skills bar isn't centered but rather right alligned. So the 4th skill is halfway hidden. [screenshot below]

I don't use any browser extentions which are directly related to Habitica. And I don't use any Stylish/Stylus/Greasemonkey/Tampermonkey themes or styles or scripts that are directly related to Habitica either...

I ckecked in an incognito window in Firefox now. The skills bar is still not centered"

![image](https://user-images.githubusercontent.com/1495809/97418646-c8199880-1954-11eb-9cf8-52dc13b88ec2.png)

**Comment by Tressley** [comment] 2024-07-01 21:14
This was fixed in #12776.

**Closed as completed by Tressley** 2024-07-01 21:14 UTC
Labels: priority: minor, section: Task Page
