### ISSUE TITLE
Incorrect tags being assigned to tasks

### ISSUE THREAD

**Issue by peytonreyton** [HabitRPG/habitica#7520] opened 2016-05-27 14:55 UTC
General Info
- UUID: d5ccbc11-0f06-4ebd-8b1c-a2133ebf65fa
- Browser: Google Chrome 50.0.2661.102 (64-bit)
- OS: OS X El Capitan 10.11
### Description

Whenever I create a new task, it is incorrectly automatically tagged with tags I don't have selected. When I "uncheck" incorrect tags, save, and close the task, the incorrect tags are not removed. This has been happening since yesterday and, since I rely on the tagging system, it's seriously impeding my ability to use Habitica.

**Comment by kamni** [comment] 2016-05-27 15:47
This is a duplicate of #7412.

**Closed as completed** 2016-05-27 17:21 UTC
