### ISSUE TITLE
Daily or To-Do or Reward moved to Habits and cannot be deleted

### ISSUE THREAD

**Issue by supersweet** [HabitRPG/habitica#2334] opened 2014-01-09 22:52 UTC
my dailies task 'morning dog water' somehow got put into the habits section, i have created a new dailies task for it but no matter how many times i try to delete the original it wont disappear from the habits section.
##

**Comment by wc8** [comment] 2014-01-10 04:41
Hi, sorry about that. I think an admin might need to look at your account to fix the item on the technical side. Meantime, I'd try to ignore it. (If you're super desperate and don't care about what else is on your task list you could wipe your task board with a special button but I **don't** recommend it, because you'd have to rebuild your lists.)

Oh, and your UUID will probably be needed, you can copy and paste it from https://beta.habitrpg.com/#/options/settings/api

**Comment by wc8** [comment] 2014-01-16 19:12
@lefnire so you’re aware…
@supersweet I’m assuming this is still a problem for you. If so, please provide your User ID.

**Comment by lefnire** [comment] 2014-01-16 19:50
I'm aware, harder to fix than it sounds so will do when I get a moment (and when we get a UUID)

**Comment by patena** [comment] 2014-01-28 18:33
I had this happen too, this morning - it was a daily that I created yesterday after midnight, I have a custom 6am day start, and I had other improper day start bugs, so I suspect it's related to that. 
Can't delete it either.
UUID is 28493c5d-00bb-4bc0-a471-9c4b40c9e642; the messed up "habit" is called "Evening:", if you need help finding it.

**Comment by Ahlberger** [comment] 2014-01-31 14:25
This happened to me in the past few days as well. My daily 'Meditation' is stuck in my Habit list and won't delete.
User ID is 765c6ac2-981f-4167-91cb-810417e8607b
Hope you can help!

**Comment by AndASM** [comment] 2014-02-03 18:17
Same thing, my 'Do Laundry' task is now a habit and cannot be edited or deleted.

User ID 53da07b9-2d2a-4add-812d-decb1926dd6a

**Comment by pippitree** [comment] 2014-02-19 14:34
Hello, this has happened to me too, but possibly a different way - I was creating a daily task in the iPhone app, and it ended up in the Habit section straight away. It auto synced and is now viewable on the web, and undeletable. 

My user ID: e3e3e55a-c3dd-4e71-ae6e-75062992a230

Hope this makes sense....

**Comment by wooohoooo** [comment] 2014-08-11 21:08
Hey Guys, sorry to bother you, but I think I had the same problem. Created a weekly to write my nephew a letter and it got stuck in habits. My User ID is 46d5b03d-91f3-489f-b630-c7ac41e5a71b

Would be cool if you could help! 
Thanks

**Comment by Alys** [comment] 2014-08-11 21:13
@wooohoooo : Can you tell us the exact text of the task? If there's anything personal in it, then you could leave out some words, but we need to be able to identify the task uniquely.

**Comment by wooohoooo** [comment] 2014-08-11 21:16
@Alys  Yes, of course. It says 'Vincent Laurin Johanna schreiben'. 

Thanks!

**Comment by patena** [comment] 2014-08-11 21:16
@Alys if you're fixing those, could you do mine too? As reported above, the text is "Evening:" and my UUID is 28493c5d-00bb-4bc0-a471-9c4b40c9e642.

**Comment by Alys** [comment] 2014-08-11 21:22
@lefnire : Could you please delete the habits for wooohooo and patena (the two most recent posters above)?
I'm not sure if the earlier reports have been done or not.

@pippitree : If this issue is still happening for you, can you tell us the exact text of the task? If there's anything personal in it, then you could leave out some words, but we need to be able to identify the task uniquely.

Everyone: Unfortunately it's not a quick and easy fix so it might be a little while before it's done. If you create a new daily, that daily should work correctly.

**Comment by wooohoooo** [comment] 2014-08-11 21:27
Thanks for your quick answer  This is my first post and I'm not 100% sure if saying "thank you" is seen as spam in this Forum (I could not find a 'up' button or similar for posts) and its really late here so I'll just add some maybe useful information that I forgot earlier: 
I created the new task on my android device via the app and I also unchecked all the weekdays in the same session, maybe that triggered some problems.

**Comment by Alys** [comment] 2014-09-08 19:41
See https://github.com/HabitRPG/habitrpg/issues/3441 for a screenshot of a Reward in the Habit column.

**Comment by grantbowering** [comment] 2014-12-08 19:09
I've somehow ended up with a Daily in the Habits column now and it won't delete... 

I don't recall specifically how or when this happened, but my theory is that it started as a Daily and I tried to re-order it (not sure if web site or android app) and that caused it to re-order onto the wrong table maybe? 

I'd be happy to ignore it for now, except that it breaks the User Data Display unfortunately. (attributesHTML ln 1222, because obj.type is 'daily' but obj.repeat is undefined; not sure if I should add an issue on @Alys's tools-for-habitrpg repo for this as well because it's obviously an upstream issue... eh, she has lots of activity on this ticket so I'm sure she'll see it and reference it from the other repo if she wants)

![2014-12-08 11_50_16-habitrpg _ your life the role playing game](https://cloud.githubusercontent.com/assets/2152220/5345158/b2631c46-7ed2-11e4-8a1c-4de01dceea3d.png)

![2014-12-08 11_33_59-habitrpg user data display](https://cloud.githubusercontent.com/assets/2152220/5345166/be95de4a-7ed2-11e4-8166-4f2b54b6599e.png)

(My user ID is 8964dbe8-3259-4d20-bff7-2528c9f07172)

**Comment by Alys** [comment] 2014-12-08 20:44
@grantbowering Could you please reload the DDT until you see it at version 3.5.4 and tell me if it works now? Thanks very much for letting me know about this! We'll get the bad task deleted too, but I'm hoping you won't mind testing the DDT first. ;)

**Comment by grantbowering** [comment] 2014-12-08 20:48
Sure thing!  I can confirm DDT fixed wrt this issue in v3.5.4.  Thanks :)

(P.S.  What does the "T" of DDT stand for?)

**Comment by Alys** [comment] 2014-12-08 21:23
Thank you for testing! T = Tool. Data Display tool.
I saw your conversation in the Tavern about this (Blade, thanks for helping!). The most common bugs with the DDT are from odd little quirks in people's data, like this one, and they almost always present themselves by preventing the whole page from working. I keep meaning to wrap all the code in some kind of try-catch thing, but... time.... You're always welcome to contact me if you find anything else wrong. Email is probably easiest (details at the bottom of the error/documentation message).

**Comment by crookedneighbor** [comment] 2014-12-08 21:45
Oh weird, now I got one, but it's only showing up in the mobile app and the api.

I had a todo populated through Todoist for checking on the air filter on my Nest thermostat. It's showing up in my habits and my todos (I assume because of a sync error). I was able to rename it NEST, but I was unable to delete it from the mobile app.

![nest](https://cloud.githubusercontent.com/assets/2916945/5347837/cec28908-7ef0-11e4-966c-07a4b6287077.png)

It's listed as `type: "todo"` instead of `"habit"`, but it has an id of `undefined`, which is why I assume it landed in the habits section. I tried using the `/static/api` page to delete a task with the value `undefined`, but it was unable to be deleted that way.

```
{
    "text": "NEST",
    "challenge": {},
    "attribute": "str",
    "priority": 1,
    "value": 1.9747,
    "tags": {},
    "notes": "This task was created by a third-party service. Feel free to edit, it won't harm the connection to that service. Additionally, multiple services may piggy-back off this task.",
    "dateCreated": "2014-11-20T05:35:28.000Z",
    "id": "undefined",
    "down": true,
    "up": true,
    "history": [
      {
        "date": 1417710644046,
        "value": 1.9747
      }
    ],
    "type": "todo"
  },
```

**Comment by Alys** [comment] 2014-12-09 21:27
@grantbowering and @crookedneighbor The tasks incorrectly placed into Habits should be gone now.

Did everyone else who has posted into this thread get fixed up? If not, post a brief comment now and I'll fix yours too. If you unique user ID is not already in this thread, I will need to be told it. You can copy and paste it from https://beta.habitrpg.com/#/options/settings/api (be careful to paste just the user id, not the API Token).

**Comment by crookedneighbor** [comment] 2014-12-09 21:35
Confirmed. Thanks!

**Comment by ArcOvella** [comment] 2015-09-15 17:03
Hi, I'm not completely sure if this goes here or deserves a new issue but I guess it's pretty similar.
I'm unable to delete a daily task which was part of a Challenge no longer running (it doesn't appear in the challenges list so I can't abandon it). Can you fix that, please?

The exact name of the task is: "Eat an entirely plant based diet today"
And my UUID is: ee22c797-5c21-4029-947b-7c29067ea847

**Comment by Alys** [comment] 2015-09-15 20:06
@ArcOvella Please see "Deleting a Challenge Task" in the wiki's [Challenges](http://habitica.wikia.com/wiki/Challenges#Deleting_a_Challenge_Task) page.

**Comment by Merave1** [comment] 2016-03-03 21:47
I've joined a challenge and one of the to-do's has became a habit while still looking and acting like a to-do. 
It says it's part of a challenge but leaving the challenge & removing the tasks doesn't remove it (I left hoping it will be removed because it doesn't suppose to be a habit). Right now I can't delete it and joining and leaving the challenge again didn't help in removing this habit-to-do.
It has a proper name but the note's says: "This task was created by a third-party service. Feel free to edit, it won't harm the connection to that service. Additionally, multiple services may piggy-back off this task.".
My User ID: 7583232e-3233-4ce6-81de-8ac8b67f9a4b

**Comment by Alys** [comment] 2016-03-04 09:19
@Merave1 Sorry about that! I've deleted the task. Reload the site if you don't see it gone. This was caused by a rare glitch that can happen when the site and database are under heavy load. It should be safe for you to rejoin the challenge - the glitch is extremely unlikely to happen again.

Technical details for our reference:

The task from the challenge:

```
    "todos": [
        {
            "text": "Visit [Week 9: Addresses and contact info ](http://www.home-storage-solutions-101.com/simple-address-book.html)",
            "attribute": "str",
            "priority": 1,
            "value": 7.557387187685171,
            "notes": "",
            "dateCreated": "2016-02-29T01:49:51.528Z",
            "id": "bbc710f6-75cb-457d-9909-b3e64293b1f0",
            "checklist": [],
            "collapseChecklist": false,
            "completed": false,
            "type": "todo"
        },
        {
```

The task from Merave1's account:

```
    "habits": [
        {
            "text": "Visit [Week 9: Addresses and contact info ](http://www.home-storage-solutions-101.com/simple-address-book.html)",
            "challenge": {
                "id": "b03522c6-2ad7-48e3-84a5-9d3f484b94d9"
            },
            "attribute": "str",
            "priority": 1,
            "value": 2.925356518578296,
            "tags": {
                "cd805f02-23d2-4d14-be67-54a91466235c": false
            },
            "notes": "This task was created by a third-party service. Feel free to edit, it won't harm the connection to that service. Additionally, multiple services may piggy-back off this task.",
            "dateCreated": "2016-02-29T01:49:51.528Z",
            "id": "bbc710f6-75cb-457d-9909-b3e64293b1f0",
            "down": true,
            "up": true,
            "history": [
                {
                    "value": 1,
                    "date": 1457038296545
                }
            ],
            "type": "todo"
        },
        {
```

**Comment by Merave1** [comment] 2016-03-04 12:57
@Alys Thank you for the fast fix! :thumbsup:

**Comment by paglias** [comment] 2016-06-01 08:45
This should be fixed

**Closed as completed by paglias** 2016-06-01 08:45 UTC
