### ISSUE TITLE
Every pet hatched after Beastmaster awards Beastmaster again

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#2990] opened 2014-03-03 01:32 UTC
I got the Beastmaster achievement about a week ago. Now every time I hatch a pet (including gryphons, hedgehogs, and hatching a replacement for a pet evolved into a mount) I get the overlay notification that I've achieved Beastmaster. Again. And again. And again. Something's not computing right.

**Comment by deilann** [comment] 2014-03-03 02:36
Ahhh no, I know what that is. Every time you hatch a pet, it checks your
pet count to see if you have hit Beastmaster. Tomorrow I'm going to work
exclusively on Habit stuff, and I'll look at the code to confirm my
suspicions

**Comment by casicastiel** [comment] 2014-03-03 14:31
Hmm, I can't reproduce this - I just finished feeding and re-hatched a white fox, and didn't get the popup.

**Comment by ghost** [comment] 2014-03-03 17:06
I have a pet (blue dragon) that I didn't rehatch after evolving it (I still have all the others). I wonder if that has anything to do with it. I haven't hatched anything today so I don't know if the issue is still there.

**Comment by zoebeagle** [comment] 2014-03-07 19:39
This has been happening with me also.   I just hatched a new hedgehog (my first) and received the Beastmaster modal.

**Comment by deilann** [comment] 2014-03-07 23:42
Here be a question: do all of you actually have Beastmaster (all 90 gen 1
pets) or did you get the modal early for some reason? (I for some reason
only actually got Beastmaster at 91/90 pets.)

**Comment by ghost** [comment] 2014-03-07 23:56
Yes, I legitimately have Beastmaster. I think it's stopped happening (for now) so I'm not sure what triggers it. I haven't re-hatched any pets in the past few days.

**Comment by zoebeagle** [comment] 2014-03-08 03:17
I also legitimately have Beastmaster, and it did pop earlier today when I hatched my first hedgehog, but I noticed that it is also popping everytime I switch PC's (from work to home) or switch to web view on my phone.  At least I won't forget anytime soon that I'm a Beastmaster :smiling_imp:

**Comment by ghost** [comment] 2014-03-16 18:00
Just hatched two gryphon eggs and got the Beastmaster notification each time. Not sure if it's a Pets 2.0 thing or something else.

**Comment by deilann** [comment] 2014-03-16 19:35
Still happening to me as well.

**Comment by Mihakuu** [comment] 2014-03-20 16:50
Darn it I even used the search bar! 
Okay. So dilann does the beast master achievement work by making a question how many pets you have and popping up when you have all 90? So when we hatch gen 2 pets it comes back with a true?

**Comment by deilann** [comment] 2014-03-20 16:52
I haven't had a chance to look at why this happens too closely, sadly. But
I believe that you are correct.

**Comment by disreputabledog** [comment] 2014-04-22 00:19
This happens to me too.

**Comment by lefnire** [comment] 2014-04-22 18:28
fixed in https://github.com/HabitRPG/habitrpg/commit/70af0869c61a713fecba6f874554c940232c549e , will push soon

**Closed as completed by lefnire** 2014-04-22 18:28 UTC
