### ISSUE TITLE
The hero didn't level even the experiences are over the limit.

### ISSUE THREAD

**Issue by PJ007** [HabitRPG/habitica#4642] opened 2015-02-06 15:58 UTC
I grabbed enough experiences to level up. In spite of theht I have 573 of 460 Exp.
How can I level then?
PJ007, ID
a3aa9d1e-7826-42ed-9f72-6a787869f252
Win 7, Chrome Version 40.0.2214.111 m

**Comment by crookedneighbor** [comment] 2015-02-06 16:00
The next time you check off a task, you'll level up. 

Duplicate of #2143

**Closed as completed by crookedneighbor** 2015-02-06 16:00 UTC

**Comment by PJ007** [comment] 2015-02-06 16:08
Thank you. It works.
I got myself over by casting the "Burst of Flames" spell two times.
