### ISSUE TITLE
Doubled habits, to-do's and dailies

### ISSUE THREAD

**Issue by agata0808** [HabitRPG/habitica#7472] opened 2016-05-24 10:18 UTC
General Info
- UUID: f36079b5-ed56-460d-88bd-b7da6c9badaa
- Browser: Google Chrome
- OS: Windows 7
### Description

All of the dailies, to-do's and habits connected with the challenges are now double. I can't delete them. In addition there is an information, that the link to the challenge is wrong. It must have happened during the last week.
#### Console Errors

[//]: app-9e4d2a8b.js:6 Error: [$parse:lexerr] Lexer Error: Unterminated quote at columns 64-89 ["CHALLENGE_TASK_NOT_FOUND] in expression [task.challenge.broken=="TASK_DELETED" || task.challenge.broken=="CHALLENGE_TASK_NOT_FOUND].
http://errors.angularjs.org/1.3.9/$parse/lexerr?p0=Unterminated%20quote&p1=…LETED%22%20%7C%7C%20task.challenge.broken%3D%3D%22CHALLENGE_TASK_NOT_FOUND
    at https://habitica.com/app-9e4d2a8b.js:4:22855
    at fd.throwError (https://habitica.com/app-9e4d2a8b.js:6:28646)
    at fd.readString (https://habitica.com/app-9e4d2a8b.js:6:30028)
    at fd.lex (https://habitica.com/app-9e4d2a8b.js:6:27521)
    at hd.parse (https://habitica.com/app-9e4d2a8b.js:6:30313)
    at o (https://habitica.com/app-9e4d2a8b.js:7:6668)
    at j.$watch (https://habitica.com/app-9e4d2a8b.js:7:13059)
    at link (https://habitica.com/app-9e4d2a8b.js:8:12033)
    at ma (https://habitica.com/app-9e4d2a8b.js:6:7459)
    at pa (https://habitica.com/app-9e4d2a8b.js:6:3005)

**Comment by lynxlynxlynx** [comment] 2016-05-24 12:52
Looks like a dupe of #7436 , but the extra log helps.

**Comment by agata0808** [comment] 2016-05-24 13:08
Thank you. I couldn't find connected issues, maybe because github is completly new to me and I have no idea how to use it. But the other problem still isn't solved, so maybe my informations will help as you've just said. :)

**Comment by Alys** [comment] 2016-05-24 13:49
@agata0808 No worries about not finding the issue. We appreciate you reporting this!

I think for that console error, there might have been an incomplete download of the javascript. That code must be referring to this line, which doesn't have the syntax error described:
https://github.com/HabitRPG/habitrpg/blob/develop/website/server/models/task.js#L44

We're trying to work out what sort of fixes we can do for the challenge task problems. I'm sorry they're so annoying. :(

I'm closing this since we're recording it elsewhere, but there's a link from it to here.

**Closed as completed by Alys** 2016-05-24 13:49 UTC
