### ISSUE TITLE
Website is presenting wrong SSL certificate some of the time

### ISSUE THREAD

**Issue by bond-alexander** [HabitRPG/habitica#4179] opened 2014-10-22 05:05 UTC
When I visit https://habitrpg.com (Firefox on Windows 7), habitrpg loads correctly. However, when my wife loads habitrpg (OSX), it acts strangely. In Chrome, it presents a certificate error, saying that the SSL certificate is for zinzane.com.br. In Firefox, it redirects her to primordia.br.

**Comment by Alys** [comment] 2014-10-22 21:41
Your wife should check that she is typing "habitrpg.com" into the URL bar exactly correctly. If she is and she is still has problems, she should show us a screenshot of Chrome's certificate error, with as much detail showing as possible (e.g., if there are any "more info" links, click on them).

It would also be a good idea for her to run a reputable malware scanner to check her entire computer for malware.

**Comment by bond-alexander** [comment] 2014-10-24 03:12
The issue appeared to go away yesterday, but returned today. I've attached screenshots of the certificate error, the certificate information, and the DNS lookup. The three IP addresses returned for habitrpg.com all point to EC2, so I can't confirm which (or all) of them belong to you.
![Uploading Screen Shot 2014-10-23 at 7.59.12 PM.png . . .]()
![Uploading Screen Shot 2014-10-23 at 7.56.08 PM.png . . .]()
![Uploading Screen Shot 2014-10-23 at 7.55.35 PM.png . . .]()

**Comment by bond-alexander** [comment] 2014-10-24 03:13
![screen shot 2014-10-23 at 7 59 12 pm](https://cloud.githubusercontent.com/assets/8104100/4764730/a78a02b4-5b2b-11e4-8ca3-8cf4a55c53fa.png)
![screen shot 2014-10-23 at 7 56 08 pm](https://cloud.githubusercontent.com/assets/8104100/4764728/a78268c4-5b2b-11e4-8acd-e07fcafb4dca.png)
![screen shot 2014-10-23 at 7 55 35 pm](https://cloud.githubusercontent.com/assets/8104100/4764729/a786c7e8-5b2b-11e4-8b8b-f84659dbfe1a.png)
I don't know why the images didn't upload the last time.

**Comment by deilann** [comment] 2014-10-24 03:15
Did she scan for malware, like @Alys suggested?

**Comment by bond-alexander** [comment] 2014-10-24 03:41
We have antivirus, but AV on Mac is even less effective than AV on Windows. It didn't catch anything.

It appears to be a DNS caching issue. The last IP address, 54.225.118.188, apparently [used to point to HabitRPG](https://www.virustotal.com/en/ip-address/54.225.118.188/information/), but now goes to primordia.com.br. I changed to a different DNS server (previously used my ISP default) and now that IP address no longer appears in the DNS lookup for habitrpg.com. Since that IP no longer appears in my DNS lookup, habitrpg resolves and loads properly.

**Comment by Alys** [comment] 2014-10-24 03:41
DEFINITELY scan for malware if you haven't already.

It's your DNS that's causing the problem. I've reproduced the relevant screenshot below (thank you for including it!!). The 54.225.118.188 address is the odd one out. It points to the www.primordia.com.br website and does NOT belong to HabitRPG. The other two addresses do (as does 23.21.86.178 which you might see in future in those DNS lookups). That's why you're getting inconsistent results - when either of the correct IP addresses are used by your browser, you are directed to the correct site; when the incorrect address is used, you get the primordia site.

Unfortunately I think this is probably not something that we can help you with directly. Your own computer's DNS cache or your ISP's DNS cache (or a cache that your ISP uses) have been poisoned, possibly by malware or by a targetted attack. If you can't fix this locally, explain the problem to your ISP.

Assuming both of your computers use the same ISP for your internet connection, you can probably do a test to see where the poisoning might be occuring. Run several DNS lookups on both computers. If both computers sometimes  include the 54.225.118.188 IP address, then either both computers have the same malware or your ISP's DNS cache is causing the problem. If only one computer ever shows the 54.225.118.188 IP address, then only that computer has malware (and your ISP is not at fault).

![screen shot 2014-10-23 at 7 59 12 pm](https://cloud.githubusercontent.com/assets/8104100/4764730/a78a02b4-5b2b-11e4-8ca3-8cf4a55c53fa.png)

**Comment by Alys** [comment] 2014-10-24 03:43
Ha, yes, you're right. It looks like that 54.\* address did used to belong to HabitRPG. That makes it less likely that malware is involved, which is good. :)

I'm closing this now since it's not an issue we can directly help with, but it can be reopened if you need more assistance.

**Closed as completed by Alys** 2014-10-24 03:43 UTC
