### ISSUE TITLE
UI freezing in certain conditions.

### ISSUE THREAD

**Issue by yangit** [HabitRPG/habitica#769] opened 2013-04-04 01:49 UTC
After you start new session (w.o. cookies) at locally running development branch at url localhost:3000/?play=1 UI will be frozen for some time until "activate" it somehow by dragging, scrolling or opening dev console.
See videos below.
It appears in Chrome and Firefox on MacOS
It can also be somewhat reproduced on iphone4s in chrome browser, UI stays unresponsive for 5-10 sec after you can see the buttons rendered.

This might be something to do with computer speed as this bug is more noticeable when I'm recording screencast (=>my comp slows down).

Sometimes I get following scenario: 
It is important to follow steps exactly and do nothing else (i.e. scroll, click elsewhere, resize window, open dev console)
1) Open localhost:3000/?play=1 (you have to clear cookies or use incognito window of chrome)
2) Start clicking one of the habits "+" button, say "1h productive work" at a rate 2 clicks per sec.
3) Observe EXP\GP changing and notifications with popovers appearing
4) Continue clicking
5) Observe UI stuck. You still get CSS changing color of the button once you hover over it. But no more EXP\GP changing.
6) Continue hover on\off and click same button.
7) Suddenly it starts accepting clicks. Even at a much higher click rate. And those clicks you made before are never recovered.

This bug prevents me from writing test coverage as casperjs\phantomjs seems to suffer from the same issue.

**Comment by yangit** [comment] 2013-04-04 01:50
Here are video links:
http://www.youtube.com/watch?v=fV5Me6ARfEI
http://www.youtube.com/watch?v=AV-IOEIka0c
http://www.youtube.com/watch?v=VbMIEdWelwM

**Comment by lefnire** [comment] 2013-04-04 03:23
Notes for further research (could be unrelated, I'm just thinking out loud):

We're using SLaks' racer & derby forks (Unroll-me/Derby, SLaks/racer) instead of codeparty/*. A long while back I added character.coffee:bulkUpdate() which coincides with a Racer modification I made for bulk updates at https://github.com/codeparty/racer/issues/93 . This could be incompatible with the racer/derby forks we're using, which have since been updated quite extensively. I'll look into this.

Two other weird things I'm seeing.
- "Updating _1 due to ..." happens _many_ times in your browsing session. TMK, this should only happen every so often after many writes, triggering a `model.emit('bulkUpdate')` (see https://github.com/SLaks/racer/commit/a0290483bfcd413fdb25635ffb0fbd866de1714b). I could be misunderstanding `bulkUpdate`, but if I'm understanding it correctly something is awry in Habit code causing too many writes / addData() / something)
- "Updating _1 due to..." is triggering in the **browser** for stuff that should only be happening on the **server**. These are things that are being written in `app.get('/', function(){})` on the server, before `app.render()` is called. Why are these being shown in the browser console? And it looks like the app is hanging **until** these ops have finished being called in the browser - like they're queued up, page rendered, and then operations performed. I will investigate.

**Comment by litenull** [comment] 2013-04-04 06:11
I confirm this on production. I cant click anything until about 20 sec.

On Thu, Apr 4, 2013 at 5:23 AM, Tyler Renelle notifications@github.comwrote:

> Notes for further research (could be unrelated, I'm just thinking out
> loud):
> 
> We're using SLaks' racer & derby forks (Unroll-me/Derby, SLaks/racer)
> instead of codeparty/*. A long while back I added
> character.coffee:bulkUpdate() which coincides with a Racer modification I
> made for bulk updates at codeparty/racer#93https://github.com/codeparty/racer/issues/93. This could be incompatible with the racer/derby forks we're using, which
> have since been updated quite extensively. I'll look into this.
> 
> Two other weird things I'm seeing.
> - "Updating _1 due to ..." happens _many_ times in your browsing
>   session. TMK, this should only happen every so often after many writes,
>   triggering a model.emit('bulkUpdate') (see SLaks/racer@a029048https://github.com/SLaks/racer/commit/a0290483bfcd413fdb25635ffb0fbd866de1714b).
>   I could be misunderstanding bulkUpdate, but if I'm understanding it
>   correctly something is awry in Habit code causing too many writes /
>   addData() / something)
> - "Updating _1 due to..." is triggering in the _browser_ for stuff
>   that should only be happening on the _server_. These are things that
>   are being written in app.get('/', function(){}) on the server, before
>   app.render() is called. Why are these being shown in the browser
>   console? And it looks like the app is hanging _until_ these ops have
>   finished being called. I will investigate.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lefnire/habitrpg/issues/769#issuecomment-15878100
> .

## 

LP, Tomaž :)

**Comment by wizonesolutions** [comment] 2013-04-04 10:56
Thirded. I have 120 tasks, and this happens after every action too. Check
off a task? OK, gotta wait like 10 seconds for the app to come back before
I can do another one. I mostly use @pjf's hrpg client these days for this
reason.

**Comment by lefnire** [comment] 2013-04-04 15:38
oh god... ok, i'm marking as current and will make top prio. @litenull @wizonesolutions how long has it been this way for you two?

**Comment by wizonesolutions** [comment] 2013-04-04 16:02
It's worth noting that my own computer's performance seems to have some
impact on this. But I don't even dare to open Habit on my phone at the
moment, heh.

**Comment by lefnire** [comment] 2013-04-04 19:41
@yangit can you try the [remote-list-cleanup](https://github.com/lefnire/habitrpg/tree/remote-list-cleanup) branch? (be sure to `npm update`)

@wizonesolutions @litenull can you try your accounts on http://habitrpg.herokuapp.com to see if the problem is still there? (it's a database snapshot, not production - so you can safely mess up your accounts)

**Comment by litenull** [comment] 2013-04-04 20:17
No, the problem is solved.

On Thu, Apr 4, 2013 at 9:42 PM, Tyler Renelle notifications@github.comwrote:

> @yangit https://github.com/yangit can you try the remote-list-cleanuphttps://github.com/lefnire/habitrpg/tree/remote-list-cleanupbranch? (be sure to npm
> update)
> 
> @wizonesolutions https://github.com/wizonesolutions @litenullhttps://github.com/litenullcan you try your accounts on
> http://habitrpg.herokuapp.com to see if the problem is still there? (it's
> a database snapshot, not production - so you can safely mess up your
> accounts)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lefnire/habitrpg/issues/769#issuecomment-15919138
> .

## 

LP, Tomaž :)

**Comment by lefnire** [comment] 2013-04-04 20:47
ok, i'm pushing to beta.habitrpg.com - if y'all could, use that one for a while? I'm gonna use it too. some potential mem leak fixes, potential fix for this ticket - my main concern is the task id lists emptying issue mentioned in the commit message above. As long as nobody gets any empty task lists, we'll push to prod. (if you do get wiped, visiting production will restore you - it's super janky, see the commit for more details)

**Comment by litenull** [comment] 2013-04-04 21:35
Basically, there is a socket.io reconnect after about 20s. It takes about 10s to reconnect. There is a message that says: Client timed out; asking for snapshot!

**Comment by lefnire** [comment] 2013-04-04 21:39
but it work just fine on heroku? i wonder if it's an environment issue...

**Comment by litenull** [comment] 2013-04-04 21:41
Yeah, it works fine.

**Comment by wizonesolutions** [comment] 2013-04-05 12:44
I'll run off beta for a bit and let you know. Good thing I have BETA_MODE
in habitsync :D

**Comment by lefnire** [comment] 2013-04-05 19:13
so is it :+1: or :-1: on production now? I pushed 1c2cc06 . here's what I realized is happening. `.set()` operations are async, meaning `page.render()` is called before all the character-cleanup stuff is finished. Seems like the client waits for these transactions to finish, though it's already been rendered, before making some other scripts available. I removed that character-cleanup (which re-consolidates id-lists & their refLists) because it's an expensive operation, so that should mostly solve this problem. However, i'm gonna keep this open until I know nobody is loosing tasks from their lists (a la #85 #86).

**Comment by litenull** [comment] 2013-04-05 19:30
alas, still there. are you sure its habitrpg? it seems to me that the synchronization logic is kinda messy when it comes to 1k+ connections. The XHR long pooling sockets are firing 20 secs after page render.

**Comment by litenull** [comment] 2013-04-05 19:34
pardon me, there seems to be a pause. the DOM is responding the first 10 seconds, then there is a pause of 20 secs. happens every time.

**Comment by lefnire** [comment] 2013-04-05 19:36
I'm going to look into moving beta to websockets, see if that helps

**Comment by litenull** [comment] 2013-04-05 22:07
Yeah, try this. Do you know how are users (sessions) persisting in the XHR fallback ? MongoDB or memory ? Just out of curiosity.

**Comment by lefnire** [comment] 2013-04-05 22:40
Mongo

**Comment by lefnire** [comment] 2013-04-07 19:25
I found a repro-able account to test locally. It's fixed when `NODE_ENV=development` (no clue why) or when using Websockets:

``` SHELL
diff --git a/src/server/index.coffee b/src/server/index.coffee
index f09668d..558775b 100644
--- a/src/server/index.coffee
+++ b/src/server/index.coffee
@@ -14,7 +14,7 @@ middleware = require './middleware'

 ## RACER CONFIGURATION ##

-racer.io.set('transports', ['xhr-polling'])
+#racer.io.set('transports', ['xhr-polling'])
 racer.ioClient.set('reconnection limit', 300000) # max reconect timeout to 5 minutes
 racer.set('bundleTimeout', 40000)
 #unless process.env.NODE_ENV == 'production'
```

It seems simply to be an availability performance issue. I'm going to see if I can get Websockets enabled on beta.habit (still wrapping my head around Chef, needing to override the Nginx cookbook version attribute). This should stop-gap the problem, but I still need to dig deeper.

**Comment by litenull** [comment] 2013-04-07 19:33
Ok, i knew it. :P

**Comment by lefnire** [comment] 2013-04-09 18:06
There's a chance that https://github.com/lefnire/habitrpg/commit/72ee444608c97a5395275d94c504fd3ec9d43ea1 fixed this issue, could someone test on https://beta.habitrpg.com?

**Comment by TheRise88** [comment] 2013-04-09 18:16
nothing changes :(

**Comment by TheRise88** [comment] 2013-04-09 18:17
Actually it's even less responsive: before I could open the window clicking on my avatar at least

**Comment by lefnire** [comment] 2013-04-10 03:29
what whaaaat! we're live on prod with websockets, is anyone here experiencing this issue any more?

**Comment by lefnire** [comment] 2013-04-10 13:54
should be fixed now, knocking down to `important` unless it comes up again

**Comment by yangit** [comment] 2013-04-16 05:37
In c9b3c32 it still persists.

**Comment by lefnire** [comment] 2013-04-18 21:18
possibly fixed, see discussion at https://github.com/lefnire/habitrpg/commit/251890f7b6ecee740b2dd220def312b94705913d

**Comment by paglias** [comment] 2013-09-09 15:58
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!

**Closed as completed by paglias** 2013-09-09 15:58 UTC
