### ISSUE TITLE
Hover bubble for comments does not parse newlines

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#1021] opened 2013-05-22 16:49 UTC
If you enter comments in a task item of any kind, and include newlines in it, the popup bubble that appears when you hover over the word balloon icon doesn't show the line breaks, it shows spaces instead. That makes things like shopping lists contained in a Todo hard to read!

**Comment by paglias** [comment] 2013-09-09 16:16
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!

**Comment by SabreCat** [comment] 2013-09-10 00:05
This is still the case. Reopening.

**Comment by notionparallax** [comment] 2013-12-05 08:23
I've had similar problems in the past. It might be [bootstrap not displaying the content as html](http://stackoverflow.com/questions/18861957/html-bootstrap-popover-function), but I don't think that's the problem as it seems to be being stored in the html with new lines, not `<br>`  or `<p>` tags. It's probably how the text is stored when it is first entered, rather than how it is displayed.

**Comment by deilann** [comment] 2014-02-05 22:11
Now that Markdown is enabled, is this a problem?

**Comment by lefnire** [comment] 2014-02-05 22:55
markdown hasn't been added for comments yet, as bs2 + angular-ui-bs doesn't support html. Now that @paglias has finished bs3 migration (I have yet to merge to develop, expect it on beta in coming days) we can revisit this in the near future - but it's not done yet

**Comment by deilann** [comment] 2014-02-05 22:56
kk thnx for the update -- sorry for all the emails

**Comment by jklein** [comment] 2014-10-17 01:29
Is this still an issue? I can take a look if so, and if it is reproducible.

**Comment by SabreCat** [comment] 2014-10-17 02:56
Still happening for me.

**Comment by negue** [comment] 2014-10-17 04:28
Now that the Extra Notes uses a markdown filter, you could write your inner-todo list with:
1. Text
2. Text

```
1. Text
2. Text
```

or 
- Text
- Text

```
- Text
- Text
```

This doesn't work? @SabreCat

**Comment by SabreCat** [comment] 2014-10-22 13:44
Markdown works. It's the basic newlines that don't. "Priority - minor" indeed, hah.

**Comment by crookedneighbor** [comment] 2014-12-06 02:23
![screen shot 2014-12-05 at 8 23 11 pm](https://cloud.githubusercontent.com/assets/2916945/5325781/918e0ad4-7cbc-11e4-8037-552dd60036cb.png)

Looks good now. Closing this.

**Closed as completed by crookedneighbor** 2014-12-06 02:23 UTC
Labels: priority: minor
