### ISSUE TITLE
Mount Growing modal should use mount name, not pet name

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#8671] opened 2017-04-13 19:33 UTC
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitrpg/issues/2760)

[//]: # (Fill out relevant information - UUID is found in Settings -> API)
### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)
When you raise a pet into a mount, you get (assuming you haven't disabled it) a modal that says "You grew a [COLOR] [PETNAME]!" However, some mounts use a different term for the grown-up version than the pet version: Tiger vs. Tiger Cub, for instance. Given it's displaying the new form, it might make more sense for the modal to use the mount name than the pet name.

**Comment by TigzAU** [comment] 2017-04-14 13:58
I can look into this one,  I'm happy to look at the code alter it and complete testing on my local version, sounds like a simple switch in the code without looking at it.

**Comment by librarianmage** [comment] 2017-04-14 17:12
@TigzAU You may want to check out https://github.com/HabitRPG/habitica/blob/develop/website/views/shared/modals/raise-pet.jade

**Comment by TigzAU** [comment] 2017-04-15 14:59
Thanks @MathWhiz , line 7 is the problem advised, "h3(style='margin-bottom: 0')=env.t('raisedPet',{pet:'{{::raisedPet.displayName}}'})" the "displayName" is calling the right naming convention but the issue is that the naming convention for mounts is based off the pets in all its calls from sprites to information.
so a mount is "tigercub-color/type" for all of its calls except one.
The only place that the proper mount name is displayed that i have found is the mount page on the mouse over function. <\website\views\options\inventory\mounts.jade>
The lines that control that function is the following:
- var mountKey = egg.key+"-"+potion.key
- var mount = env.Content.mountInfo[mountKey]
"popover=mount.text(env.language.code)" - in the below section of code.
div(popover-trigger='mouseenter', popover=mount.text(env.language.code), popover-placement='bottom')
I have injected some code with varying results and are still locating all locations of the funtions and variables being used but this is my initial validation.
Hope to be closer to a resolution on my next update.

**Comment by alanpallath** [comment] 2017-04-21 07:51
Is the issue fixed/need work? I'm new here, but would like to contribute on something. Can anyone help me  in setting up?

**Comment by TigzAU** [comment] 2017-04-21 07:58
I'm still working on the change at the moment

**Comment by Alys** [comment] 2017-06-25 07:13
@TigzAU I'm putting this on hold because we're most of the way through a project to change the website's front-end code and this might no longer happen afterwards, or if it does, there'll be new code that will need to be modified to fix it. We'll assess the status after the new code is live and if it's still needed, we'll open this back up for you to work on if you wish.

**Comment by librarianmage** [comment] 2017-10-20 22:19
Should this still be on hold?

**Comment by TigzAU** [comment] 2017-10-21 02:30
If it does, reassign someone else, the variable that is causing the issue in the old code was being transcoded to its variable at the webpage itself not the coding behind it, I could not see the code to alter this, if it's still happening that is most likely where the issue will be, sorry to advance for me, I know where the issue is  but I can not change it

**Comment by SabreCat** [comment] 2017-10-26 15:49
This probably depends on first getting a fix to https://github.com/HabitRPG/habitica/issues/9214 ; I'd say we keep this on hold until that.

**Closed as completed** 2018-04-01 19:43 UTC
Labels: priority: minor, good first issue, status: issue: on hold, section: Stable, section: Achievements/Popups/Notifications
