### ISSUE TITLE
flag/report button stops working after some time

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#10637] opened 2018-08-25 23:27 UTC
_From citrusella, the serving wench (2d6ef231-50b4-4a22-90e7-45eb97147a2c):_

"I reported this awhile back but: Report buttons on posts stop working after some vague probably-inconsistent period of time from first loading Habitica. I don't know if this is just changes being pushed to the site breaking the button or something (though sometimes this doesn't seem likely, since it can happen frequently sometimes) or if it's some other weird/undiscovered problem?"

"Reloading works to fix it until the next time it breaks, but sometimes (particularly if my browser has been open awhile) refreshing Habitica can make my browser (or even my system if it's really angry) slow down or stop responding. I've been noticing it more (even though it's probably been happening the same amount) lately."

_I've asked her to post here with details of her browser and PC._

**Comment by citrusella** [comment] 2018-08-26 00:34
Currently on Firefox 52.9.0 ESR (latest ESR update right now), on a 32-bit Windows 7 Service Pack 1 (on mid-2011 Macbook Pro hardware, FWIW).

My adblocker is disabled on Habitica, [this CSS style](https://userstyles.org/styles/148842/end-habitica-task-columns-at-last-item) that *should* only be affecting the task columns is all I consistently have running when I encounter this (though at this *exact* moment, I do have [this style](https://userstyles.org/styles/162990/no-p-padding-on-habitica-task-list) and an unreleased/updated version of [Habitica Old Colors](https://userstyles.org/styles/149439/habitica-old-colors) running too) , and I don't have any other extensions that I think could be interacting with Habitica. (To be complete, I do have Greasemonkey, Rikaichan, and Leechblock which can all theoretically interact with Habitica, but I pretty much never have the former two running/enabled on Habitica, and Leechblock has never been blocking Habitica when I've been having a problem.)

I feel like I have a vague memory of playing around in another browser to see if this happened and having it happen (it would have been a current-at-the-time version of Vivaldi or Opera on the same computer as I mentioned earlier, or it would have been a non-ESR up-to-date-at-the-time version of Firefox on a 64-bit Windows 10 machine). But I might be misremembering and ascribing testing something else to this. XP

(The part about reloading slowing my browser/system sometimes is probably more the fault of how I treat my browser/system sometimes than anything else, for what it's worth. Sort of a "well, darn, I was gonna report that but Firefox is misbehaving so now I'm going to have to fully close it first, sigh" addendum than anything implying that being the fault of Habitica.)

I think I've been noticing the button issue more because I feel like I'm reporting more lately, which is why I noted it's probably been actually happening the same amount and I've just been taking note of it more.

**Comment by negue** [comment] 2018-08-30 16:29
I could reproduce this, I've reported some messages in a party, then kinda wanted to report a message a second time - got an error as expected, switching to tavern, clicking on report nothing happens

**Closed as completed** 2018-09-01 17:27 UTC
Labels: status: issue: needs investigation, section: Other
