### ISSUE TITLE
Quest completed but rewards do not show up

### ISSUE THREAD

**Issue by maki-chan** [HabitRPG/habitica#3217] opened 2014-04-06 23:10 UTC
I just completed a quest with my two-player group and the group messages also say that the boss was successfully defeated and that the players receive their rewards.

The quest was the Gryphon quest and I did not receive any egg, gold or experience points whatsoever.

My UUID is 94b21a6e-4b94-443d-a524-98920eb4bc31

Could you please take a look into this?

Cheers,
Maki

**Comment by maki-chan** [comment] 2014-04-07 06:51
OK, I received 3 Gryphon eggs in the meantime, but I'm still missing the experience points and the money. Sure, I could just fix this via the settings, but at all, it should be playable like intended

**Comment by deilann** [comment] 2014-04-07 06:51
Can you refresh just to make sure?

**Comment by maki-chan** [comment] 2014-04-07 06:52
I refreshed about 20 times since my cron has run yesterday (I always refresh after my cron just to make sure, everything is fine, especially the messages in the group chat)

**Comment by deilann** [comment] 2014-04-07 06:54
kk

Are you _positive_ you didn't receive the XP and GP? Like, do you track your values?

(I trust you, I just need to check to be sure. I know I wouldn't notice the difference.)

**Comment by maki-chan** [comment] 2014-04-07 06:57
About the gold, I cannot be 100% sure (I only thought that since the eggs have shown up about one hour in the past, so they were "7 hours late"), but I am very sure about the experience points since I already had more than 300 and the quest should give 125, but I have 380 by now. I cannot remember the exact number, but I can definitely remember it was past 300, because I already calculated with the exp points of the quest for the next level up :D

**Comment by deilann** [comment] 2014-04-07 07:01
I'm thinking the eggs weren't late, just not displaying.

I'm gonna close this, simply because there's really no trouble shooting that can be done at this point and I'm pretty sure that I know what the problem is and it's not related to quests at all, but failed requests to the server. And you got the most important part-- the eggs. :)

Go ahead and fix your values, and revel in your victory!

**Closed as completed by deilann** 2014-04-07 07:01 UTC
