### ISSUE TITLE
"Not enough GP"- Can't buy items even though I have enough GP

### ISSUE THREAD

**Issue by ohtree** [HabitRPG/habitica#1335] opened 2013-08-15 18:02 UTC
Every time I go to upgrade an item (to buy a morning star, chain mail, etc.), I get a pop up that says "Not enough GP!" even though I have enough GP to buy the items. So essentially I cannot upgrade or buy anything. I've tried signing out and signing in again, refreshing my browser, everything. My user ID is f03bd81c-b1d5-4377-9656-5bea30cc9ea3. What should I do?

**Comment by lefnire** [comment] 2013-08-15 18:40
duplicate of https://github.com/lefnire/habitrpg/issues/1330

**Closed as completed by lefnire** 2013-08-15 18:40 UTC
