### ISSUE TITLE
Multiple joining in a Guild

### ISSUE THREAD

**Issue by MllePandaRoux** [HabitRPG/habitica#1294] opened 2013-07-31 10:11 UTC
I have a guild named "Guilde des UTTiens" and if I look to the members list, some members appear  many times : 
![buggy bug](https://f.cloud.github.com/assets/4671953/885173/c663f908-f9c8-11e2-8fab-93ffb3be2759.PNG)

Maybe it's because they attempt to join many times, but I don't think so ("Darla" appears 32 times !) 

In the Public Guild list, it's written as if we have 52 members, but in fact we have only 14 different members.

**Comment by MllePandaRoux** [comment] 2013-07-31 10:12
What should I do ? Suppress the duplicates ?

**Comment by lefnire** [comment] 2013-07-31 15:32
type something in chat, then refresh. it's a crappy hack that removes duplicates while we work on the rewrite

**Comment by MllePandaRoux** [comment] 2013-07-31 17:14
Crappy but it worked :)

**Comment by lefnire** [comment] 2013-07-31 17:29
dupe of #1213, let's follow up there

**Closed as completed by lefnire** 2013-07-31 17:29 UTC
