### ISSUE TITLE
on-hover panel does not appear for purchasable items in Shop and Rewards column

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#12638] opened 2020-10-03 09:20 UTC
When you mouse-over an item in the Shops or pinned to your Rewards column (e.g., a piece of equipment or a Quest scroll), the on-hover information does not appear.

If you click on the item to open its own modal, then you see the on-hover panel, and you still see it when you close the modal. However, when you move your mouse away to make the on-hover panel vanish, moving your mouse back over the item doesn't make the on-hover panel reappear.

Firefox on Ubuntu. Also the browsers in this message from @joedragons (66902097-c79b-496f-acd9-b78cc5867b28):

_"Noticed last night, I did not have any hover over the items in my rewards column. Firefox Windows 10. I saw the same on Safari for Mac and with another account on Mac on Firefox."_

**Comment by paglias** [comment] 2020-10-03 14:45
Do we have an idea on when this started?

**Comment by paglias** [comment] 2020-10-03 14:54
Looks like this was caused by a typo here https://github.com/HabitRPG/habitica/pull/12363/files#diff-a2d98063fa672e3d7a249c7d00a55e5bR68 ( the comma is not necessary )

**Comment by paglias** [comment] 2020-10-03 14:56
I've pushed a fix to `release`, it'll go live with the next deployment

**Closed as completed** 2020-10-03 14:56 UTC
