### ISSUE TITLE
Blank task appears, possibly as result of moving a task

### ISSUE THREAD

**Issue by Laserpiano** [HabitRPG/habitica#3943] opened 2014-08-28 13:32 UTC
I remember moving a task manually upwards and then when I scrolled down it appeared. Before that I had joined some challenges as shown is the screenshot.
![untitled](https://cloud.githubusercontent.com/assets/8580071/4076144/75313454-2eb7-11e4-931b-ed115c929aee.png)

**Comment by Alys** [comment] 2014-08-28 19:37
Possible related to https://github.com/HabitRPG/habitrpg/issues/3946 ?

@Laser-guy are you able to delete the task?

**Comment by ghost** [comment] 2014-08-28 21:00
Sorting seems really messed up in general right now, especially in the development branch. Might want to wait to work on this until #3946 is finished

**Comment by ebiagogo** [comment] 2014-08-29 00:03
I had a couple of empty tasks show up in my Dailies section after trying to reorder them today as well. Moving the tasks around is messed up for sure. After trying to move a couple of times (without success) some of the tasks became unmovable. I can confirm that I was able to delete these new tasks without a problem.

**Comment by ebiagogo** [comment] 2014-08-29 00:08
OK, I just retested this and sorting looks like it's working again and no blank tasks being created. I looked back at #3946 and it looks like the recent changes were reverted.

**Comment by lefnire** [comment] 2014-08-29 00:16
Indeed, sorting is back to the way it was now on prod

**Comment by Laserpiano** [comment] 2014-08-29 14:47
I have just successfully deleted it. I also noticed that it also appeared on HabitRPG app on my iPad. Anyway it now disappears as well.

**Comment by Alys** [comment] 2014-08-29 19:57
Closing because we think this has been fixed with the change to put sorting back the way it was. We can reopen this if it happens again.

**Closed as completed by Alys** 2014-08-29 19:57 UTC
