### ISSUE TITLE
Pickpocket WAAAAAY too effective.

### ISSUE THREAD

**Issue by Decals** [HabitRPG/habitica#2506] opened 2014-01-21 21:55 UTC
I have a daily that I've managed to keep up for 58 straight days.  When I pickpocket this daily, I get 73 gold and 73 silver.  For paying just 10 mana.  With 60 mana points, do the math and think about how much gold I can rake in.  Personally, I'm avoiding using it because with potions costing gold it means that there's basically no worries about dying... pretty much ever.  There should probably be caps on how much you can earn by pickpocketing (maybe 10 gold?)  and how often you can pickpocket (once a day?)

**Comment by lefnire** [comment] 2014-01-21 21:59
dupe of #2093

**Closed as completed by lefnire** 2014-01-21 21:59 UTC
