### ISSUE TITLE
Change links in translation strings to variables

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica#10213] opened 2018-04-01 17:42 UTC
**See [this comment](https://github.com/HabitRPG/habitica/issues/10213#issuecomment-403245134) for current status of this issue**

Report from a user: 

"Windows/Desktop browser + language Spanish, When opening an egg with the potion, appears the window:
¡Has eclosionado una nueva mascota! Cachorro de panda Base ¡Visita el Establo para alimentar y equipar a tu nueva mascota!
The "stable" link points to "inventario/establo", not "inventory/stable", producing a 404 error page."

Confirmed in Spanish language, doesn't occur in French (as one example).

**Comment by citrusella** [comment] 2018-04-01 17:58
It appears the problem exists in [this file](https://github.com/HabitRPG/habitica/blob/0e74d25eded6100d62eb3f1c9fb99f2efeb4c8a4/website/common/locales/es/pets.json#L80)?

But it seems like it might be translatable in every language but just has (luckily) not been translated? ([Here](https://github.com/HabitRPG/habitica/blob/0e74d25eded6100d62eb3f1c9fb99f2efeb4c8a4/website/common/locales/fr/pets.json#L80) is the French file, for example, which includes the link but keeps it English.)

Truthfully that's just a wild guess since I don't know how to actually tell if something is translatable or not...

**Comment by Alys** [comment] 2018-04-01 21:18
@citrusella You are correct! It's a problem caused by a translator not realising that `(/inventory/stable)` should not be translated.

In pets.json, the English version is:
`"hatchedPetHowToUse": "Visit the [Stable](/inventory/stable) to feed and equip your newest pet!",`

Four languages have it translated incorrectly:
```
es/pets.json:80:    "hatchedPetHowToUse": "¡Visita el [Establo](/inventario/establo) para alimentar y equipar a tu nueva mascota!",
id/pets.json:80:    "hatchedPetHowToUse": "Kunjungi [Istal](/inventori/istal) untuk memberi makan dan menggunakan peliharaan terbarumu!",
ja/pets.json:80:    "hatchedPetHowToUse": "[動物小屋]（/所持品/動物小屋）へ行って新しいペットを装備し、えさをやりましょう！",
zh/pets.json:80:    "hatchedPetHowToUse": "到马厩去喂饲和装备你最新的宠物吧!",
```

I'll fix the ones I can in Transifex and tell the translators about any others.

However that's just a temporary fix; I'm sure the problem will reoccur with either this string or others. The proper fix should be something like having the path inserted into the string as a variable. I'm marking this as suggestion-discussion for a few days to give the staff time to comment if they wish to and then I'll make it help wanted.

**Comment by negue** [comment] 2018-07-07 21:51
My Idea to fix this would be replace all `in-page` links by a variable inside all locale-strings, this way those can't / won't able to be translated.

But for a good example `accountSuspended` change the `in-page` urls there would also mean to add the urls on many files

**Closed as completed** 2018-12-23 18:56 UTC
Labels: priority: medium, type: translations, help wanted, type: medium level coding
