### ISSUE TITLE
Support of unauthenticated SMTP 

### ISSUE THREAD

**Issue by arthurlutz** [HabitRPG/habitica#5753] opened 2015-08-07 20:27 UTC
Maybe it's because I'm not very familiar with npm and the ecosystem around it but when configuring my STMP server I kept on getting Auth errors. I ended up setting up a localhost SMTP server for testing. This local SMTP server does not require authentication. Setting SMTP_USER to an empty string did not help, removing SMTP_USER did not help. I had to go and comment website/src/utils.js and remove the auth section lines 15 to 18. 

Is there a better way ? Is there a way through configuration ? If not it would be a nice feature to have. Thanks.

**Comment by crookedneighbor** [comment] 2015-08-08 00:22
@arthurlutz Just curious, are you deploying your own instance of the app in production mode on your own server, or just deving on it locally to contribute to the code base. 

If you're just working on it locally, you shouldn't need to set up an smtp server at all unless you're working on code which specifically sends an email. (such as the forgot password link)

**Comment by arthurlutz** [comment] 2015-08-08 08:21
@crookedneighbor I'm more in the "own instance" scenario, but I think this can also be useful for a dev instance.

**Comment by crookedneighbor** [comment] 2015-08-08 15:49
@paglias Do you have concerns about this?

**Comment by paglias** [comment] 2015-08-08 18:15
Hmm, I'm not very familiar with this, it's only used for password recovery emails. But I suppose that since we're using it in production without any problem there should be something wrong in your configuration as it's working for us

**Comment by crookedneighbor** [comment] 2015-08-08 19:19
If you want to submit a pr, we'll review it.

**Comment by Alys** [comment] 2015-10-05 10:44
I'm closing this since there's been no action for a while, but @arthurlutz you're still most welcome to submit a PR if you find that the problem isn't with your configuration.

**Closed as completed by Alys** 2015-10-05 10:44 UTC
