### ISSUE TITLE
Not getting drops

### ISSUE THREAD

**Issue by theLastStar** [HabitRPG/habitica#6444] opened 2016-01-02 00:00 UTC
I have been getting very little to none drops during the past few levels, pretty sure since I chose to become a rogue - not sure if there is a causality or not. For the past three levels, I have received one food item and perhaps one egg, despite the level progression taking longer than during the first ten levels when I received drops with normal frequency. 

How much I check off typically during one day: I have 8-10 dailies ranging from blue to yellow, one blue habit and a couple of yellows, a couple to-dos not every day but almost. Yet I have only received a drop twice, which, though I can't bring myself to do the math now, seems impossibly low. (Especially being a rogue with 34 Perception.) In comparison, my two friends around the same level as me have got enough drops to grow at least one mount, which I haven't been able to do. It's making the experience quite discouraging for me (because, yes, I am motivated by cute pixel animals).

My user ID is c2a3ec13-69c3-411f-961c-0f5a9f3ab3e1. Using Chrome on Windows 7. Money, XP and mana all drop normally.

**Comment by Alys** [comment] 2016-01-02 01:01
Drops are random (both the item you receive and the chance of receiving an item), so it's not impossible for a player to go through a period of getting few drops from nothing but bad luck rather than a bug.

Over the next couple of days, maybe longer, I'll dump your items owned to a text file each day and compare them to the previous day to see what's changed. If I can confirm that you are getting at least a drop or two each day, then there's probably no bug happening. 

Until I say otherwise, please don't buy any droppable items with gems (but quests are okay to buy), and don't sell any items that have dropped. If you could also avoid hatching pets or feeding pets, that would help, but it's not essential if you're really wanting a new pet.

I have a local copy of items owned data from 2015-12-28, and in that time you've been given only one Fish and one Fox egg (or, you've been given more but have sold them). This does seem low, but still not impossible due to chance.

Please change the password on your account now to something difficult to guess. I would like to completely eliminate the possibility that someone is logging into your account and selling your drops. It's unlikely I know, but changing your password will make it even less likely.

**Comment by Alys** [comment] 2016-01-02 01:06
I'll keep watch on this too:

```
    "items": {
        "lastDrop": {
            "count": 0,
            "date": "2015-12-30T01:54:08.695Z"
        },
```

**Comment by Alys** [comment] 2016-01-02 01:07
@theLastStar Don't worry about changing the password. I'd forgotten about the drop count variable that's in your account. I can watch that to get precise numbers of drops.

**Comment by Alys** [comment] 2016-01-05 12:05
You have been receiving drops over the past couple of days, just not very many of them. To increase your chance of receiving a drop, increase your Perception (e.g., you have one unallocated stat point at the moment - consider assigning it to Perception instead of Intelligence). As you level up and become more powerful and gain more equipment, you'll find that it is easier to increase your Perception.

The best Perception equipment are the pieces you gain from the Vice quest line ( http://habitica.wikia.com/wiki/Free_Yourself_of_the_Dragon%27s_Influence ) and the Golden Knight quest line ( http://habitica.wikia.com/wiki/A_Stern_Talking-To ) so perhaps talk to your party about doing those quests.

You might also consider creating more Dailies and Habits, but keep in mind that overloading yourself with tasks is likely to be counterproductive in the long run if it leads to burnout.

**Closed as completed** 2016-04-26 03:30 UTC
