### ISSUE TITLE
Rounding errors for EXP and GP

### ISSUE THREAD

**Issue by fl0at** [HabitRPG/habitica#56] opened 2013-01-11 23:10 UTC
There appears to be round-off error when "reverting" goals that were checked off by mistake, and then unchecked.
The higher value the goal, the higher the error.
This applies to both money and experience.

For all I know this is a design decision, but I didn't see anything in the FAQ or issue tracker, and my OCD-tendencies drove me right to here.

![Screen Shot 2013-01-11 at 2 53 35 PM](https://f.cloud.github.com/assets/2099677/61335/ceafa17c-5c41-11e2-82be-66267b52df5d.png)

![Screen Shot 2013-01-11 at 3 02 30 PM](https://f.cloud.github.com/assets/2099677/61347/0b988b34-5c43-11e2-871d-5874b6afde64.png)

![Screen Shot 2013-01-11 at 3 03 45 PM](https://f.cloud.github.com/assets/2099677/61348/3cb53488-5c43-11e2-9f7d-100609f95b57.png)

---

As you can see, I currently have a Level 2 character with substantial gold and silver, all from clicking and unclicking goals. Not a single goal has ever been completed.
(The character briefly had -1 XP, but I failed to screenshot it)

This is definitely an extreme example, but even a single mistaken click and unclick of a Red goal can cause a net gain of silver and experience.
# Platforms

On my Mac OS X 10.7.5:
- Chrome 24.0.1312.52
- Safari 6.0.2 (7536.26.17) on 

On my Windows 7 SP1:
- Chrome 23.0.1271.97 m

**Comment by horusofoz** [comment] 2013-02-03 09:11
@lefnire Do we need to consider this a bug?

In my experience it is better to offer a bigger carrot than stick for long term propositions. By design or accident, this "bug" does the same. Leave as is?

**Comment by Pandoro** [comment] 2013-02-03 09:18
@horusofoz I would say we  need to check if this also affects the general rounding. I'm a bit worried that if there is a running error this will also mean that the second and third weapon have the same effect? Or maybe this is caused because the weapons are ignore when undoing a to-do.  So I would suggest that we're investigate a little. 

Edit: sorry about that... wrong button. 

Story

**Comment by Pandoro** [comment] 2013-03-03 19:19
YAY FINALLY fixed as of today :)

**Closed as completed by Pandoro** 2013-03-03 19:19 UTC
Labels: priority: minor
