### ISSUE TITLE
Multiple Lion Cub Eggs Appeared

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#1225] opened 2013-07-02 13:47 UTC
So for some reason I opened up Habit to find I magically had 8 lion cub eggs appear overnight... they weren't there before, and I know that I hadn't been "earning" them because I died the day they all appeared. Might be the only one with this issue. 

Browser: Chrome
User ID: 510ad136-3838-467b-b716-28f2167b67cb
No Javascript Errors

**Comment by mgpc3** [comment] 2013-07-26 14:07
I am only level 2 and have 18 fox eggs somehow...

Browser: Chrome
User ID: 8f21e403-8e3a-4d75-8824-74fe4712b2ce
Also not detecting any errors

**Comment by lefnire** [comment] 2013-07-30 15:17
Dupe of #901, let's follow up there

**Comment by lefnire** [comment] 2013-07-30 15:19
i'm sorry, wrong ticket. Can't find it now, but basically someone was talking with me looking at the code at https://github.com/HabitRPG/habitrpg-shared/blob/master/script/algos.coffee#L108 . Multiple people have experienced getting too many of one thing, but there's nothing in the code there that flags that issue. We may have to just wait till our rewrite and see if it gets fixed

**Comment by paglias** [comment] 2013-09-09 17:51
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!

**Closed as completed by paglias** 2013-09-09 17:51 UTC
Labels: priority: minor
