### ISSUE TITLE
HabitRPG is slow, and occasionally freezes, and prevents chrome from closing the tab for 30+ seconds

### ISSUE THREAD

**Issue by JasonGross** [HabitRPG/habitica#2608] opened 2014-01-28 06:55 UTC
HabitRPG is very, very slow, for not doing much in real time.  Furthermore, every few days, the HabitRPG tab will freeze, eating up ~700 MB of RAM and 25% of my CPU, and Chrome will not close the tab for at least 30 seconds to a minute unless I kill the process with Chrome's task manager.

**Comment by lefnire** [comment] 2014-01-28 06:57
dupe of https://github.com/HabitRPG/habitrpg/issues/1499 , follow there. Hint: keep your task lists fairly slim for the time being, and often clear your completed To-Dos

**Closed as completed by lefnire** 2014-01-28 06:57 UTC
