### ISSUE TITLE
With UI Update, a habit turned into a daily?

### ISSUE THREAD

**Issue by Popitop** [HabitRPG/habitica#2833] opened 2014-02-13 10:13 UTC
After the UI update, one of my habits, which I get high scores on repeatedly, changed from a positive-only habit to a checkbox. It's still in the Habit column.

**Comment by wc8** [comment] 2014-03-29 21:08
@Popitop is this still an issue for you?

**Comment by negue** [comment] 2014-08-25 09:30
Dupe of #2443 ?

(And I think this can be closed, since there is also no reply)

**Comment by Alys** [comment] 2014-08-25 09:48
Yup, yup. It can always be reopened if Popitop replies.

**Closed as completed by Alys** 2014-08-25 09:48 UTC
