### ISSUE TITLE
Sprite sheet issues back on mobile Safari (but not on Chrome).

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#4943] opened 2015-03-30 10:32 UTC
**It's baaaaaack (https://github.com/HabitRPG/habitrpg/issues/2510). At least on iPad running ios 7.1.2. Ever since the last update the sprites are garbled again. This time it's only some of the sprites. The gold/silver coins, the boss images for active quests (Iron Knight in particular), some avatar components, foods, saddles, eggs, and some mounts.**

**Comment by gisikw** [comment] 2015-03-30 10:45
@Anysia It's been suggested in some other issues that the issue is browser caching. If you quit mobile safari, and _force quit_ (i.e. double-tap and remove Safari from your background processes), that should clear your cache - please advise if you still see the issue after that?

**Comment by ghost** [comment] 2015-03-30 15:37
Your force quit instructions don't make any sense for iOS but I cleared all website data if that's what you're asking and it doesn't help. 

**This is exactly the same behaviour as the last time the sprite sheet got too big.**

**Comment by gisikw** [comment] 2015-03-30 15:40
Blargh, sorry, it's been a bit since I was on iOS.

**Comment by ghost** [comment] 2015-03-30 15:48
No problem. :)

**Comment by Alys** [comment] 2015-03-30 16:02
attention: @SabreCat @paglias @negue @lefnire . See the two bolded comments above.

@Anysia I hope you don't mind that i edited your comments to bold the most important parts. I changed nothing else.

**Comment by ghost** [comment] 2015-03-30 16:10
No problem. I should clarify that by "some avatar components" it looks like it's actually some mounts and not the avatars themselves.

**Comment by negue** [comment] 2015-03-30 16:17
So we need to split up the spritesheets into more files? maybe in a context way (so for example, that the avatar wont need to load the spritesheets of NPCs or shop image files)

**Comment by crookedneighbor** [comment] 2015-03-30 17:10
Quick and dirty fix- Change count form 6 to 7 here: https://github.com/HabitRPG/habitrpg/blob/develop/Gruntfile.js#L16

**Comment by ghost** [comment] 2015-03-31 00:39
The beta site still displays properly, which makes sense since the pastel skin colours and hair aren't on it.

**Comment by Alys** [comment] 2015-03-31 01:03
@Anysia Note that the beta site has some rather different code than production at the moment. It's not recommended for use unless the production site is unusable.

**Comment by Alys** [comment] 2015-07-26 12:48
Looks like we fixed this by increasing the number of spritesheets so I'm closing this. It can be reopened if I'm wrong.

**Closed as completed by Alys** 2015-07-26 12:48 UTC
