### ISSUE TITLE
LIVE SITE: Select button (classes) does not allow user to select a class or dismiss the overlaying block

### ISSUE THREAD

**Issue by roseaboveit** [HabitRPG/habitica#1999] opened 2013-12-17 04:44 UTC
While claiming tasks the class system unlocked pop up displayed. The classes appear selectable (green background on clicking) the "select" submit button does not cause a change in the interface. There is no way to dismiss this window.

**Comment by lefnire** [comment] 2013-12-17 04:52
dupe of #2000

**Closed as completed by lefnire** 2013-12-17 04:52 UTC
