### ISSUE TITLE
Todos List wigs out a bit

### ISSUE THREAD

**Issue by psonghi** [HabitRPG/habitica#73] opened 2013-01-15 03:44 UTC
Non fatal bug, but kind of strange to run into.

Say, I added 'Cake' to my Todos
Then, I complete 'Cake'
Then I add 'Cake' back to Todos, as well as 'Eat Cake'
Sometimes when I try to complete these 'Cake', it wigs out and can't fully complete them.
Then, 'Cake' somehow multiplies resulting in many more 'Cake' in my Todos, forcing me to delete 'Cake' ;0.
Where did 'Eat Cake' run off to?

![habituary](https://f.cloud.github.com/assets/2614930/66773/19957c40-5ec5-11e2-8547-a73cd54389cf.png)

**Comment by lefnire** [comment] 2013-01-15 03:46
oh dear. thanks for pointing that out

**Comment by psonghi** [comment] 2013-01-15 03:53
I'm just trying to break it ;)

**Comment by JesperDramsch** [comment] 2013-01-22 16:36
Yeah so I just broke it...

![habitrpg](https://f.cloud.github.com/assets/2620316/87001/e11496ce-64b1-11e2-94ca-100d60c1d8e4.png)

**Comment by lefnire** [comment] 2013-01-22 19:11
@Jesper1337 - can you refresh and check now?

**Comment by wc8** [comment] 2013-01-22 19:49
Nope, it's still there with some variations. I haven't figured out exact steps to replicate any of the variations yet.
Sometimes adding Task X after eat cake had been successfully completed created a duplicate eat cake.
Deleting also sometimes creates a blank task. 

EDIT: In other words, the task names don't have to match to cause the issue.

**Comment by ghost** [comment] 2013-01-24 21:03
I am having the same issue

**Comment by JesperDramsch** [comment] 2013-01-25 10:06
It was good "the next day" and I even got some of the lost habits and dailys back.

**Comment by horusofoz** [comment] 2013-01-25 21:16
@lefnire Close as appears database instability issues are now resolved?

**Comment by lefnire** [comment] 2013-01-25 21:17
let's hang on to this a bit, @Neohuman and @Jesper1337 experienced this yesterday - I'm still writing the tests for this one.

**Comment by toebu** [comment] 2013-01-26 01:16
I found a way to reproduce this problem (the one with the todo's, no idea what happened to the dailys of @Jesper1337):
- Delete all your todos, refresh the page to make sure they are all gone
- Add 3 todos (e.g. 'one', 'two', 'three')
- Tick them off one by one: the last one is checked, but stays in the 'remaining' view
- Unticking it again makes it disappear and some other one duplicate, refreshing the page doesn't help.

The problem is that in app/index.coffee the callback for changes on tasks.*.completed (around line 137) is not called and the todo is not moved to the completedIds.

I thought the easiest way to fix that is to completely get rid of the completedIds and use the completed property of the task to decide whether to display it in the remaining or completed list. I implemented and tested this. I'm totally new to github (and generally not very experienced with git) and haven't got the nerve now to find out how I can get you to see my changes. I'll do that tomorrow (European time).

**Comment by lefnire** [comment] 2013-01-26 04:55
Looking forward to your patch! Also check out Racer filters (instead of
refLists, which is the current implementation)

**Comment by toebu** [comment] 2013-01-26 11:10
You're right, it might be better to get completely rid of the refLists. I'll check out the filters. But for now my fix should do it.

**Comment by lefnire** [comment] 2013-01-26 20:28
Awesome. PS, filters will only be applicable in todos + completed: we need
refLists for the four general lists in order to maintain sort order in the
database.

**Comment by horusofoz** [comment] 2013-02-05 08:42
@lefnire @toebu Is this still an active issue?

**Comment by lefnire** [comment] 2013-02-05 15:18
I've yet to merg @toebu's #277 PR, gonna require some testing on my part. His #226 was merged, doing away with completed ids. Not sure if this ticket is still problematic though

**Comment by toebu** [comment] 2013-02-05 17:34
I think this ticket can be closed, #226 should have fixed it. At least I never had this problem again.

**Comment by wc8** [comment] 2013-02-05 17:56
Thank you for following up.

**Closed as completed by wc8** 2013-02-05 17:56 UTC
