### ISSUE TITLE
Took damage and lost ALL money while in the inn

### ISSUE THREAD

**Issue by conoronor** [HabitRPG/habitica#3889] opened 2014-08-18 22:32 UTC
Title pretty much says it, but I was resting in the inn for a couple days and come back to a lost sword and, most importantly, hundreds of gold gone. Is this intentional? Either way, it is a bummer.

**Comment by Alys** [comment] 2014-08-18 22:39
We can't investigate this specifically without your User ID (see [API Options](http://habitrpg.wikia.com/wiki/API_Options) for how to find your User Id) but it's likely that you are on a boss quest with your party mates and that their incomplete dailies did damage to you. You can see some information about that here: https://github.com/HabitRPG/habitrpg/issues/3885

It's also possible that a sync error prevented you being checked in to the inn, even if it initially looked as if you were - see [Sync Errors](http://habitrpg.wikia.com/wiki/Sync_Errors).

If you think that neither of these are the case, please paste your User ID as plain text (not  screenshot) into this issue.

**Comment by conoronor** [comment] 2014-08-19 18:21
I wasn't in a quest with my party, so it must have been the other issue.  My User ID is 4de5aef3-372b-4489-bf15-384c90e4b047.

**Comment by Alys** [comment] 2014-08-19 20:30
When you came back after your couple of days away did you notice if your avatar was sleeping? I.e., was there "Zzzzzz" next to your avatar in the header bar?

**Comment by conoronor** [comment] 2014-08-19 20:31
Yes, he was sleeping.

**Comment by dpkenna** [comment] 2014-08-31 22:18
Same thing happened to me. I was not on a boss quest. I confirmed from more than one browser (including mobile) that my character was resting in the inn because I have had sync errors before. A couple days later I logged in and got a notice that my character had died. I was able to fix it with Fix Character Values so no real damage done, just something to look into since it seems this has happened more than once.

User ID eb0c01a3-9102-4918-9032-65c58822c909

**Comment by Alys** [comment] 2014-08-31 22:27
@dgitphubk : Did this happen to you today? Or in the past?

Note to devs investigating this: dgitphubk's publicly-available API data shows that at this moment, they are resting in the inn (sleep:true) and not on a quest (quest.key:null).

**Comment by dpkenna** [comment] 2014-09-02 14:56
I discovered it just a few minutes before I posted it here.

On Sun, Aug 31, 2014 at 3:27 PM, Alice Harris notifications@github.com
wrote:

> @dgitphubk https://github.com/dgitphubk : Did this happen to you today?
> Or in the past?
> 
> Note to devs investigating this: dgitphubk's publicly-available API data
> shows that at this moment, they are resting in the inn (sleep:true) and not
> on a quest (quest.key:null).
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/HabitRPG/habitrpg/issues/3889#issuecomment-54003390.

## 

Daniel P. Kenna
dpkenna@gmail.com

**Comment by ktastical** [comment] 2014-10-24 01:37
User ID: 8b75d6d3-d58d-45f4-84da-a4a21c8d04f5
Chrome  39.0.2171.27 beta (64-bit)
OS 10.9.5

I checked into the Inn via the web on Tuesday and quit the mobile application on my iPhone (iOS 8). Heard from a party member today that I caused everyone damage. When I checked in online, my avatar was no longer sleeping and I wasn't in the Inn. ?? I just put myself back in the Inn in hopes of not causing any more damage.

**Comment by Alys** [comment] 2014-10-24 01:56
@ktastical It sounds like you experienced a [Sync Error](http://habitrpg.wikia.com/wiki/Sync_Errors) when you checked into the Inn. Sometimes your browser does not send your actions to HabitRPG's server, and so the server never finds out that you took that action. After checking into the inn, you can reload the page and make sure that you are still reported as being in the inn - if you see that you are after a reload, you can be certain that you really are resting. There's more information at that page I linked to, especially in the "How to Minimise Sync Errors" section.

You and your party members can recover from the damage you inadvertently caused them by going to Settings -> Site -> Fix Character Values (it lets you add health, and also if necessary levels, XP, GP). You can also edit your Dailies to put back in the streaks that you lost (in the Advanced Options section). If you aren't sure what your streaks were, you can count them in the "Dailies History" section of the [User Data Display](http://oldgods.net/habitrpg/habitrpg_user_data_display.html) tool.

**Comment by scheidm** [comment] 2015-01-26 13:19
user id: cd74cac2-86f3-4aa4-956e-9362e1bb628e 
chrome version: 39.0.2171.99 (64-bit)

I hit "rest in the inn" at the beginning of the day on Thursday. I am all but certain I saw the resultant zzz expression on my character. I used it for other things during the day, but did not pay attention to my avatar. This morning I logged in after returning to work, and I am mysteriously dead. it did not seem to still show ZZZ when I clicked the refresh page button

**Comment by Alys** [comment] 2015-01-27 08:39
@scheidm I think this is likely to be a [Sync Error](http://habitrpg.wikia.com/wiki/Sync_Errors) which is where it appears that an action has been taken but the action was not sent to the server for permanent storage. If you look at that wiki page, the section called "How to Minimize Sync Errors" is probably most relevant. Unfortunately there is nothing we can do after the fact, but you can use [Settings -> Site](https://habitrpg.com/#/options/settings/settings) -> Fix Character Values to restore your lost gold, experience, and level. You can also edit each of your Dailies to restore their streaks (in the "Advanced" section). If you aren't sure what your streaks were, you can use Data -> Data Display Tool to estimate them (the "Dailies History" section).

**Comment by Alys** [comment] 2015-01-27 08:40
@scheidm I think this is likely to be a [Sync Error](http://habitrpg.wikia.com/wiki/Sync_Errors) which is where it appears that an action has been taken but the action was not sent to the server for permanent storage. If you look at that wiki page, the section called "How to Minimize Sync Errors" is probably most relevant. Unfortunately there is nothing we can do after the fact, but you can use [Settings -> Site](https://habitrpg.com/#/options/settings/settings) -> Fix Character Values to restore your lost gold, experience, and level. You can also edit each of your Dailies to restore their streaks (in the "Advanced" section). If you aren't sure what your streaks were, you can use Data -> Data Display Tool to estimate them (the "Dailies History" section).

**Closed as completed** 2015-07-19 01:35 UTC
