### ISSUE TITLE
Can't buy items even if I can afford it

### ISSUE THREAD

**Issue by gvilarino** [HabitRPG/habitica#1342] opened 2013-08-17 15:07 UTC
I'm unable to spend my gold for an item I can afford, specifically:

I have 32G 81S and I want to buy the Chain Coif (costs 25g). I click on the buy icon and I get a pop-up with the text "Not enough GP". Repro every time.

I can still buy my custom rewards (2G each), but not the built-in equipment.

User ID: 2762348a-4362-4703-a48b-ed4e39f9730d
Browser: Chrome (latest)
OS: tried it on Windows 7 and OS/X 10.8

**Comment by lefnire** [comment] 2013-08-17 15:11
dupe of https://github.com/lefnire/habitrpg/issues/1330

**Closed as completed by lefnire** 2013-08-17 15:11 UTC
