### ISSUE TITLE
TODO items checked on menu click in Android App

### ISSUE THREAD

**Issue by textoo** [HabitRPG/habitica#1348] opened 2013-08-19 09:16 UTC
hi, 

i've just downloaded the android app and have found that when i was clicking on an item in the left menu, it was checking some items in my todo list.
it looks like ghost clicks.

best regards

**Comment by lefnire** [comment] 2013-08-19 16:28
Ghost clicks indeed. Dupe of https://github.com/HabitRPG/habitrpg-mobile/issues/75, let's follow up on that thread

**Closed as completed by lefnire** 2013-08-19 16:28 UTC
