### ISSUE TITLE
Daily tasks require to be clicked twice a day. Certain progress plot is gibberish.

### ISSUE THREAD

**Issue by btseytlin** [HabitRPG/habitica#6099] opened 2015-10-24 20:47 UTC
Windows 7, Chrome. No JS errors.
5995e5d3-2ad3-4e00-a385-267f50042726

https://gyazo.com/b5da3ab1e38148ec6dccada78ac9c864
You can see on the graph that I had to click the daily task twice on one day:24.10.2015. This happens to all of my daily tasks. I click them and when I return a bit later they are uncompleted.
My day start time is default, 00:00. It appears as if the daily task reset timer is not timezone aware (I am in GMT+3) even though the settings page states it is.

One of daily tasks appears grey no matter what state it is in.

This tasks's progress graph is gibberish:
https://gyazo.com/e6f2fcc5a626be753ffd78eb1cc6513b
The score of around a million, or minus a million, I have no idea.

**Comment by Alys** [comment] 2015-10-24 23:16
Do **all** your tasks become unticked at once and you take damage for any you haven't completed yet, or is it only one or two tasks that become unticked after you've ticked them and you don't lose health because of it? I'm assuming for now that it's the latter because that's the most likely case.

When tasks become unticked a little while after you've ticked them, it's typically because of [Sync Errors](http://habitica.wikia.com/wiki/Sync_Errors) or [this bug](https://github.com/HabitRPG/habitrpg/issues/4313) (which is a lack of syncing caused by your browser holding on to updates instead of sending them to the server). It's probably the latter bug, so I recommend reading the "Advice" section near the top.

When a Daily is always grey even when unticked, it means the Daily isn't due that day. If you edit the Daily and go into the Advanced Options section, you can see all of its settings, such as start date and the repeat options.

When resetting tasks at the beginning of each day (cron), Habitica always uses the timezone configured on the PC or mobile device that you are using Habitica on.

If you'd like to reset the progress graph on any Daily, delete and recreate the Daily.

If you have questions about any of this or if I haven't covered everything you've reported in a way that seems relevant, please comment here.

**Comment by AmyConnelly** [comment] 2015-10-26 06:18
Check if they are set under a specific time slot, they may appear twice if they are.
also it could be a glitch. try entering a new one and see if that one does it too?

**Comment by Alys** [comment] 2015-10-26 08:04
There aren't really timeslots for Dailies. You can assign one or more tags to Dailies, such as morning, afternoon, or night (or any other tag that you create for yourself), but that won't cause a single Daily to appear more than once, or to become uncompleted after you've marked it as completed.

@Euphe If you still need help with this, or if you have any questions about what's here, comment on this issue. I'm going to close it now because if the behaviour you experienced was caused by a bug, then it will be that one that I linked to, but we'll still see any posts you make and will keep helping you if you need it.

**Closed as completed by Alys** 2015-10-26 08:04 UTC
