### ISSUE TITLE
"Your private messages have been marked as read"

### ISSUE THREAD

**Issue by onlyforhabitica** [HabitRPG/habitica#7556] opened 2016-05-31 00:29 UTC
General Info
- UUID: 553bd048-0d10-4a47-835a-21eff8f35c55
- Browser: Most recent version of Firefox
- OS: Windows 8.1 64-bit
### Description

When I check my inbox, like eight or so of these popup messages show up, and they sometimes continue to show up if I go to other tabs like Party.
http://i.imgur.com/EO4aLkV.png
http://i.imgur.com/Zk3LLwC.png

**Comment by Alys** [comment] 2016-05-31 00:37
Confirmed. I saw it once when accessing my inbox this morning (which is expected and currently the intended behaviour), then twice when I was leaving the inbox.

I think we should get rid of that message altogether on the website; it's good to return it from the API. In the website, it's not helpful and typically too many messages make people blind to all messages.

**Comment by quin-jay** [comment] 2016-06-01 20:05
Is there a different way to implement the feature that would be more similar to other chat platforms? Example: If a message has been read, you see a checkbox somewhere

**Comment by librarianmage** [comment] 2016-06-02 15:26
@lynnyliz From past experience, it seems to turn the messages that are read grey

**Comment by LlamaHobbit** [comment] 2016-06-06 14:16
This is still happening for me. Everytime I access my inbox I get 6-8 messages on the side that my "private messages have been marked as read". Even when there was only one message to read. Even when there were no unread messages and I merely navigated there to reply to someone or re-read a message for info. And they all pop-up again when I navigate away to a guild, to my tasks, or to my party. If I then hit refresh, they all pop-up one more time, but then seem to be finished notifying me ... until the next time I visit my inbox.

**Comment by lynxlynxlynx** [comment] 2016-06-19 09:36
@Alys Why you do you consider it useful for the api to return the message? In case the third party wants to display it?

Currently the api docs don't specify this return value and ignoring it in normal operation would require hardcoding in either callOpsFunctionAndRequest or the op itself. Or extra parameters. Nothing as nice as removal.

Is the API frozen?

**Comment by Alys** [comment] 2016-06-19 09:40
It's not necessary on the website because you can see that your messages have been read. However if you're marking them as read using an API call, you might not have the same visual feedback and so it's beneficial to pass back a clear message. Bu if it's not possible to hide the message on the website while still returning it for all other API calls, then we should show it on the website too (but only once).

The API isn't frozen, but we need to be cautious about making changes that adjust its current behaviour.

**Comment by lynxlynxlynx** [comment] 2016-06-19 09:59
But in this case the call is only setting a var and returning it. Even if that can somehow silently fail, one could still check the return value [0]. Another option is to pass an empty string if the op was a noop. That would also skip all the duplicates.

[0] https://github.com/HabitRPG/habitrpg/blob/28f2e9c356d7053884107d90d04e28dde75fa81b/common/script/ops/markPMSRead.js

**Comment by lynxlynxlynx** [comment] 2016-06-19 11:38
That's the cleanest option, so I'm pretty happy with it. RFC

**Comment by crookedneighbor** [comment] 2016-06-19 13:46
This is fixed with https://github.com/HabitRPG/habitrpg/commit/941ff10cdceb59313d575aa6362844fc4ff2e93f, will go out with the next deploy.

**Closed as completed by crookedneighbor** 2016-06-19 13:46 UTC
