### ISSUE TITLE
XP IS -92/380

### ISSUE THREAD

**Issue by nohissyfits** [HabitRPG/habitica#1097] opened 2013-05-30 11:52 UTC
I am currently on level 17, and my xp bar is completely colored in but it is showing -92/380 and I get xp when I click off my habits and dailys but the number just drops lower. My coin count is also slightly off by about 20. I just found a cactus egg too and hatched it so I hope it doesnt disappear.

**Comment by lefnire** [comment] 2013-05-30 18:24
dupe of #838, follow up there

**Closed as completed by lefnire** 2013-05-30 18:24 UTC
