### ISSUE TITLE
Random habits created with UUID text

### ISSUE THREAD

**Issue by TheCarpinator** [HabitRPG/habitica#2654] opened 2014-01-30 09:10 UTC
I refreshed the page directly after my daily reset at 1am, and a new habit appeared, titled "f546ac9c-b054-4145-a520-b7c2c40a21b0" and the extra note says "This task was created by a third-party service. Feel free to edit, it won't harm the connection to that service. Additionally, multiple services may piggy-back off this task." It also took one gold coin, and a few silver ones (I didn't catch the number) when it appeared. Should I be concerned? Why is it there?

**Comment by wc8** [comment] 2014-01-30 15:23
Do you use the chrome extension?

**Comment by colegleason** [comment] 2014-01-30 17:26
We have a theory to what is going on here: https://github.com/HabitRPG/habitrpg/issues/2642#issuecomment-33658836

**Comment by patena** [comment] 2014-02-01 16:42
I just had this happen too - five new habits that were named long gibberish alphanumeric strings and claimed to be "created by a third party service" although I've never used one.
(I also had a bunch of non-resetting dailies, duplicated ToDos, and lost a level, but I'm not sure those things are related.)

**Comment by meganstrickland** [comment] 2014-02-02 07:13
This just happened to me as well. 

Task name: 1702a007-28e4-420c-9092-e3562b41f9e1
My UID: 73e5125c-2c87-4004-8ccd-972aeac4f17a

**Comment by AlexiDavis** [comment] 2014-02-07 17:39
I experienced this today as well; however yesterday I noticed a lag in sync of my mobile (Android) HabitRPG app and the site, and as well I created a to-do on mobile and checked it off before opening the website again. I'm thinking these might be related.

**Comment by negue** [comment] 2014-08-29 11:22
Duplicate of #1402 ?

**Comment by lefnire** [comment] 2014-08-29 19:11
yep, thx!

**Closed as completed by lefnire** 2014-08-29 19:11 UTC
