### ISSUE TITLE
Seasonal shop is not available (Error Processing String)

### ISSUE THREAD

**Issue by tartakovsky** [HabitRPG/habitica#4615] opened 2015-02-03 06:40 UTC
There is a message from Siena Lesley:
"Error processing string. Please report to http://github.com/HabitRPG/habitrpg."

And the screenshot:
http://take.ms/uKq2I

So, i'm reporting here :)

**Comment by Alys** [comment] 2015-02-03 07:29
Thanks @Flar49! That is most helpful!

@SabreCat, @lemoness :

I think the issue is that `locales/en/limited.json` has this:

```
"seasonalShopClosedText": "The Seasonal Shop is currently closed!! I don't know where the Seasonal Sorceress is now, but I bet she'll be back during the next <%= linkStart %>Grand Gala<%= linkEnd %>!",
```

but `views/options/inventory/inventory.jade` doesn't specify values for the link variables:

```
p!=env.t('seasonalShopClosedText')
```

Lemoness, did you want the Shop to link to this wiki page? Or elsewhere? http://habitrpg.wikia.com/wiki/Grand_Galas

**Comment by lemoness** [comment] 2015-02-03 07:53
Wiki page is fine!

**Comment by Alys** [comment] 2015-02-03 08:10
Fixed in https://github.com/HabitRPG/habitrpg/commit/1a8a688c618897ea028ec173bf0dedbc5995a48c

It will go live the next time the site is deployed to production.

![screen shot 2015-02-03 at 6 08 01 pm](https://cloud.githubusercontent.com/assets/1495809/6016576/bbbbd498-abcf-11e4-9bb6-9b4ad6aec092.png)

I'm leaving this open until deployment so that others who might want to report the bug can see it, and so that other devs can check my code if they wish.

**Comment by crookedneighbor** [comment] 2015-02-03 20:01
The fix has been deployed, so I'm closing this ticket.

**Closed as completed by crookedneighbor** 2015-02-03 20:01 UTC
