### ISSUE TITLE
Enchanted Armoire equipment must be purchasable after losing from Death, etc 

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#10849] opened 2018-11-17 21:47 UTC
When your avatar dies or you use the upcoming Empty the Armory feature, if you lose a piece of gear from the Enchanted Armoire, currently you are not able to buy it back. It appears in your Rewards area and the Equipment shop but when you open its modal to try to buy it, the "Buy" button is greyed out.

The correct behaviour is that the equipment is purchasable directly with gold at any time that the player wants to buy it back. (It should also be available randomly in the Armoire but I've seen nothing to indicate that that's not working.)

This would need to be fixed before the Empty the Armory feature goes live.

**Comment by Alys** [comment] 2018-11-18 02:31
ruby1110 has reported (below) that Habitica tells them an Armoire item can't be bought because they're the wrong class. I don't see that on the website since I can't click the button, so I'm guessing that's from the app. Regardless, that gives a pointer at the code to look at for fixing this. Any gear that's doesn't have a `class` or a `specialClass` set to `rogue`, `wizard`, `warrior`, or `healer` should be purchasable regardless of the player's class.

_"I recently lost a Blue Hairbow due to death, but now I can't repurchase it because it says I'm of the wrong class. (It's a classless item and I'm a mage.)"_

**Comment by citrusella** [comment] 2018-11-18 23:14
Out of curiosity, would this have cropped up because of #10818 being merged?

(I'm not sure if that's a helpful hint to anything or not, I just wanted to ask because it seemed relevant.)

**Comment by citrusella** [comment] 2018-11-18 23:31
Also, if [this](https://github.com/HabitRPG/habitica/blob/eca73825457317164a6c828cbc0afd2135397123/website/common/script/ops/buy/buyMarketGear.js#L30) is the code (particularly, `(item.klass !== 'special' && item.klass !== user.stats.class)`)... does that also mean mystery items wouldn't be capable of being bought for similar reasons if they somehow ended up in the rewards/shop? Maybe other things too, if I'm not confused?

~~I almost think I understand how to fix it (or one way, anyway, i.e. adding more `&& item.klass !==` for all the possible classes) but I'm not confident enough for that. XD~~

**Comment by brightbold** [comment] 2018-11-19 02:10
I may have some potentially helpful data: I recently successfully repurchased an Enchanted Armoire item — unfortunately I don't remember which day, but I would have guessed within the last week. (It was the Bat Wand if that's something you're able to check on your end.) But today I get the messages  "You bought Ogre Armor!" and subsequently, "You can't buy this item." So this is definitely a recent regression.

**Comment by Arsnael** [comment] 2018-11-19 03:50
I second people above, this is very recent. On my Empty the Armory feature branch, I can still buy back those armoire items after resetting the equipment (was last rebased with `develop` 6th of november). While I get this issue on the latest update of `develop` branch. 

And as @citrusella mentionned, likely to come from #10818 => well when I revert it locally I can buy again :)

**Comment by paglias** [comment] 2018-11-19 20:39
@negue could you give a look? thanks!

**Comment by brightbold** [comment] 2018-11-20 02:39
Looks like this applies to subscriber items too? I just attempted to repurchase the Helm of Sporting and was told "You can't buy this item."

**Comment by negue** [comment] 2018-11-20 16:27
On it

**Closed as completed** 2018-11-22 13:35 UTC
Labels: priority: medium, status: issue: in progress, section: Equipment
