### ISSUE TITLE
Scrolling on windows 8 internet explorer leaves page blank

### ISSUE THREAD

**Issue by mtrenchluva** [HabitRPG/habitica#2271] opened 2014-01-06 18:53 UTC
I cannot view half of the page but scrolling at all turns the entire page blank until i scroll back to the very top. I've tried zooming but the text is simply too small is i try to fit it all on one page. Very frustrating

**Comment by lefnire** [comment] 2014-01-06 18:59
dupe of #https://github.com/HabitRPG/habitrpg/issues/2262

**Closed as completed by lefnire** 2014-01-06 18:59 UTC
