### ISSUE TITLE
"Save & Close" changes color on Rewards, too

### ISSUE THREAD

**Issue by casicastiel** [HabitRPG/habitica#3863] opened 2014-08-10 01:09 UTC
I assume this is intended for tasks -- an orange Habit has an orange Save button, a blue Daily a blue button, etc, but I found an interesting (and amusing!) side effect: when defining a Reward, the Save button will adopt a color as if the GP price were its task value.

Compare:
![screen shot 2014-08-09 at 9 08 04 pm](https://cloud.githubusercontent.com/assets/6208739/3868201/e06b2ab8-202a-11e4-83ed-f3b771744c6b.png)
![screen shot 2014-08-09 at 9 08 17 pm](https://cloud.githubusercontent.com/assets/6208739/3868202/e06cb5c2-202a-11e4-89d8-55294f6a3f22.png)

**Comment by Alys** [comment] 2014-08-10 01:14
From a programming point of view, this makes sense. Rewards and the three kinds of tasks are stored in very similar data structures, and so each of the four types has a "value" field. For rewards, the value field is used to store the gold/silver amount of the reward. The value field is used to choose the colour (as you noticed), and again the code for that is the same for all of the four kinds of items. So, this is working as intended, even though it seems odd at first glance. I'd suggest that it's probably best to keep it like this to keep the code base as simple as possible.

**Comment by deilann** [comment] 2014-08-10 01:16
I think it's cute

**Comment by casicastiel** [comment] 2014-08-10 01:23
It is pretty cute. I wasn't raising it as an issue, per se, just a curiosity. :)

**Comment by negue** [comment] 2014-08-29 11:31
So button color need to stay the same? Is this how it should work?

If not, this can be closed?

**Comment by lefnire** [comment] 2014-08-29 19:10
it's just picking up taskColor classes as value changes. so minor worth closing IMO

**Closed as completed by lefnire** 2014-08-29 19:10 UTC
