### ISSUE TITLE
Negative reward crashes the website

### ISSUE THREAD

**Issue by townimbecile** [HabitRPG/habitica#4018] opened 2014-09-11 05:34 UTC
Create new reward
Adjust price to -10
Save
(Reward displays with blank price)
"Purchase" reward
Lose all gold
(Reward now displays with NaN)

_edit by Alys 2016-12-26:_

There's new behaviour for this bug - it now crashes the website. Steps to reproduce the error:

- Create a new reward
- Change the reward to -10 and save
- First Bug: the reward value does not display, it is blank
- Click the reward
- Second Bug: Web page appears to go into a loop till you run out of memory. No Console errors

The desired fix is:
- Adjust the API so that the only possible values for the reward field are 0 (numerical zero) or a positive integer or positive floating point number. Infinity and NaN are not permissible.
- Adjust or create tests to match. In particular, the tests should ensure that you cannot enter letters or negative numbers.
- Minor adjustments to the website's front-end could be done to prevent inappropriate values being entered, but the front-end is being rewritten so don't spend too much time on that. Automatic tests of the front-end behaviour probably aren't necessary (but of course you should test the behaviour in a local install before doing a pull request).

_Thanks to SsangWoo for reporting it in the Report a Bug guild and cTheDragons for investigating and writing up the steps!_

**Comment by ShenZhouHong** [comment] 2014-09-23 16:00
I'll take a look this weekend, but no guarantees. However, I do agree with you, it seems straight forward enough to add some sort of check that prevents negative awards.

**Comment by gjoyner** [comment] 2014-10-13 04:43
I'll check this out today or tomorrow if it's still an issue.

**Comment by crookedneighbor** [comment] 2014-10-17 15:43
Looks like this has been fixed now:
![screen shot 2014-10-17 at 10 41 27 am](https://cloud.githubusercontent.com/assets/2916945/4681541/16800898-5614-11e4-8f9f-8e1945908f33.png)

A reward can be 0 gold, which seems odd to me, but not a bug.

Does one of the devs want to close this issue?

**Comment by deilann** [comment] 2014-10-17 18:26
It depends on which button you use to save and close... one doesn't allow
it. The other does, IIRC

**Comment by crookedneighbor** [comment] 2014-10-17 18:37
Ahh, I see now. I can fix it too, I think.

**Comment by gjoyner** [comment] 2014-10-17 19:10
Could either be cleared on a save attempt or check each key up for validity. Not sure which would be preferred.

**Comment by crookedneighbor** [comment] 2014-10-17 19:21
@gjoyner Angular has an ng-change attribute where you can run a function when that particular model changes, so I think that'd be preferable.

**Comment by paglias** [comment] 2014-10-17 19:31
@gjoyner @crookedneighbor angular has some very nice properties to check if a form is validated or not, we should prevent it from being saved unless it's valid like `formName.$valid`, give a look here for more info about that https://docs.angularjs.org/api/ng/directive/form

also @gjoyner we try to avoid using too many ng-change expressions and $watch functions because they slow down the app and use memory and when you're building an app as big as Habit it starts to feel it

**Comment by crookedneighbor** [comment] 2014-10-17 19:34
@paglias The problem is, the checkmark is situated outside of the form. We could hide the checkmark if the value is negative. IE:

```
a(ng-hide='!task._editing || task.value < 0', ng-click='editTask(task);saveTask(task)', tooltip=env.t('save'))
```

I tried using ng-disabled, but I think since it's not an input, it didn't work as expected.

EDIT: Nope, we'd have to include an extra conditional to make sure we're on a reward task.

**Comment by deilann** [comment] 2014-10-17 19:36
Kind of ... but do we NEED the checkmark?

**Comment by crookedneighbor** [comment] 2014-10-17 19:37
@deilann Good UX question.

**Comment by Alys** [comment] 2014-10-17 19:37
What about taking the approach that if the reward cost is negative, the back-end code adjusts it to zero? That would cover a negative reward added through either the form or the API (which I assume is also possible but I haven't checked).

BTW, I'm in favour of allowing zero-cost rewards. They can be useful placeholders, reminders, etc. Basically harmless.

**Comment by crookedneighbor** [comment] 2014-10-17 19:38
Yeah, that's true. Having a zero cost reward doesn't hurt anything.

**Comment by paglias** [comment] 2014-10-17 19:38
I cannot test it right now but it looks like the form is accessible from the $scope http://stackoverflow.com/a/18795264/969528

**Comment by crookedneighbor** [comment] 2014-10-17 19:42
@Alys 
Like this?

```
$scope.saveTask = function(task, stayOpen) {
      if (task.checklist)
        task.checklist = _.filter(task.checklist,function(i){return !!i.text});
      if (task.type == "reward")
        if(task.value < 0)
          task.value = 0;
      User.user.ops.updateTask({params:{id:task.id},body:task});
      if (!stayOpen) task._editing = false;
    };
```

**Comment by gjoyner** [comment] 2014-10-17 19:44
I'm good with a zero cost. Maybe just in the save function check for type and if reward check cost.

**Comment by crookedneighbor** [comment] 2014-10-17 19:47
For my code to work, you also have to remove the min attribute on the number input.

**Comment by paglias** [comment] 2014-10-17 19:49
I would prefer to check for the form being valid, it will cover all the validations used in the html and will be less a nightmare to maintain in case we want to add a new validation or modify an existing one. Also Angualr validations give users a better feedback if they entered an invalid value

**Comment by crookedneighbor** [comment] 2014-10-17 19:51
True. I'll look into the link you posted and start a new branch exploring that method.

**Comment by Alys** [comment] 2014-10-17 19:58
Do we actually want to fix this? The problem of a negative reward removing all your money no longer happens -- at least not for me - does it happen for anyone else? Instead, it behaves exactly as you'd expect: it adds the correct amount of gold.

A negative reward to add gold could be very convenient in some circumstances (e.g., shortcut to using Fix Character Values, which has legitimate purposes for gold loans and gold banks). I am often pleasantly surprised by the interesting ways that people use HabitRPG to motivate themselves and I like the idea of negative rewards being available.

At the very least, I withdraw my comment about fixing it through the API as well. You can enter a negative value there, but since it does not remove all your gold, I see it as harmless, and is at least a power-user method of working around any fix we do put into the form.

**Comment by crookedneighbor** [comment] 2014-10-17 20:00
I tried it on Firefox earlier and it saved as NaN and caused the script to become unresponsive, so something should definitely be done, since that's not expected behavior, right?

**Comment by Alys** [comment] 2014-10-17 20:09
Ok, good catch, that definitely shouldn't happen. Can we consider fixing that exact problem though (i.e. make negative rewards work correctly) rather than make negative rewards not possible? It's okay if I'm overridden on this, but I'd at least like it considered briefly. :) Now that I've realised negative rewards do work (at least on Chrome), I can definitely see a use for them.

**Comment by deilann** [comment] 2014-10-17 20:12
I'm still wondering if this should be fixed by getting rid of the check
mark

**Comment by gjoyner** [comment] 2014-10-17 20:16
The checkmate is good for long tasks. If you scroll up and check and want to save you'd have to scroll down the length of the task, in my opinion.

**Comment by crookedneighbor** [comment] 2014-10-17 20:17
@Alys If you take out the min="0" attribute from the input, you can save it as a negative number, but it still subtracts instead of adds to your gold.

**Comment by crookedneighbor** [comment] 2014-10-17 20:19
Also, @alys, I'd find it counter intuitive to have a thing that says -30 that should add 30 gold instead of subtract it. I get it logically, in context, but it still would seem weird to me.

**Comment by Alys** [comment] 2014-10-17 20:20
"but it still subtracts instead of adds to your gold." - That's weird. Is that just in Firefox? Negative rewards behave as you'd expect in Chrome. If we're getting really inconsistent behaviour in some browsers, then it's unlikely to be worth the effort of persisting with my idea.

**Comment by crookedneighbor** [comment] 2014-10-17 20:27
I just tried it in Chrome (on a Mac), on the site as it is currently, and it didn't save my negative reward correctly. Just showed up blank, then froze the page. When I refreshed, it was the positive version of the value.

**Comment by Alys** [comment] 2014-10-17 20:35
Okay. Too inconsistent. Kill it with much killing. :)

I do like the checkmark for saving tasks when I make changes to checklists. It saves scrolling all the way down (which takes time because I have many tags and leave the tags open by default since I change them often). It's not essential though. A workaround is tabbing into the text field and hitting enter on the keyboard.

**Comment by gjoyner** [comment] 2014-10-17 21:19
So this just with the checkmark right? Is it part of the form? I won't be able to look for awhile?

**Comment by crookedneighbor** [comment] 2014-10-17 21:21
@gjoyner Correct, jus the checkmark. It is situated outside of the form tag.

**Comment by lemoness** [comment] 2014-10-17 22:12
Just popping in with a quick confirmation that I use the checkmark very
frequently, since the amount of tags I have make my To-Dos very long.

**Comment by gjoyner** [comment] 2014-10-17 22:33
Does the checkmark use the save function directly while using the scope task? If so could we use the form submit function and have it trigger validations (I think JavaScript has a form.submit that Angular may use)?

**Comment by crookedneighbor** [comment] 2014-10-20 03:47
@paglias I could be wrong about this, but after some testing, I couldn't get the form to be recognized by `$scope`. 

Since each form is within an `ng-repeat`, I gave them a unique name like this `name="form-{{task.id}}"` so I could easily identify the correct form on save(`$scope["form-" + task.id].$valid]`). But, Angular won't incorporate it into the scope if `{{task.id}}` is part of the name. Just shows up as undefined.

Examining forms on `$scope` does work with static names.

For this use case, if you really want to validate it, it's probably easier to move the form element to encompass the whole box and use `ng-form` for the inner forms, and convert the save checkmark to a button with a `btn-link` class and some minor css editing to make it match the other symbols. 

Does that make sense?

**Comment by crookedneighbor** [comment] 2014-10-20 04:28
Follow up on this. The single inner-form would be the checklist form, and the addToChecklist function will no longer fire on the press of the enter key if the form encapsulates it.

**Comment by crookedneighbor** [comment] 2014-10-20 05:11
@paglias and @gjoyner, I ended up replacing the checkmark's save function with a new function called submitTask that simulates clicking the "save and close" button. If the form is invalid, it shows the error.

Out of all the ways I've tried to deal with this problem, this seems to be the easiest I've come across.

I'm sure there's a more Angular way of doing it, but I haven't figured it out yet. 

Thoughts?

**Comment by gjoyner** [comment] 2014-10-21 09:21
Just got home from travelling, so will try to give it a look within the
next few days.

On Sun, Oct 19, 2014 at 11:11 PM, Blade Barringer notifications@github.com
wrote:

> @paglias https://github.com/paglias and @gjoyner
> https://github.com/gjoyner, I ended up replacing the checkmark's save
> function with a new function called submitTask that simulates clicking the
> "save and close" button. If the form is invalid, it shows the error.
> 
> Out of all the ways I've tried to deal with this problem, this seems to be
> the easiest I've come across.
> 
> I'm sure there's a more Angular way of doing it, but I haven't figured it
> out yet.
> 
> Thoughts?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/HabitRPG/habitrpg/issues/4018#issuecomment-59684387.

## 

Glen E. Joyner Jr.
B.S Computer Science, Clemson University
Gaming Enthusiast, Developer

**Comment by paglias** [comment] 2016-06-01 09:07
I fear this is still an issue in v3 on the API side, there are no check for reward.value to be > 0

**Comment by Alys** [comment] 2016-12-26 11:53
There's new behaviour for this bug - it now crashes the website. Steps to reproduce the error:

- Create a new reward
- Change the reward to -10 and save
- First Bug: the reward value does not display, it is blank
- Click the reward
- Second Bug: Web page appears to go into a loop till you run out of memory. No Console errors

The desired fix is:
- Adjust the API so that the only possible values for the reward field are 0 (numerical zero) or a positive integer or positive floating point number. Infinity and NaN are not permissible.
- Adjust or create tests to match. In particular, the tests should ensure that you cannot enter letters or negative numbers.
- Minor adjustments to the website's front-end could be done to prevent inappropriate values being entered, but the front-end is being rewritten so don't spend too much time on that. Automatic tests of the front-end behaviour probably aren't necessary (but of course you should test the behaviour in a local install before doing a pull request).

I'm copying this information to the top post for ease of reference. Other admins are welcome to adjust it if they don't like what I've written. :)

Thanks to SsangWoo for reporting it in the Report a Bug guild and cTheDragons for investigating and writing up the steps!

**Comment by madpink** [comment] 2017-01-13 17:43
I created a negative reward with the tasks API, as long as I had gold, it deducted the appropriate amount of gold. As soon as I was out of gold, pressing the negative reward caused me damage.

No crash though

**Comment by librarianmage** [comment] 2017-10-20 03:31
Is this still an issue?

**Comment by Alys** [comment] 2017-10-20 08:00
Closing. We can reopen if this still happens.

**Closed as completed by Alys** 2017-10-20 08:00 UTC
Labels: priority: minor, help wanted
