### ISSUE TITLE
Item description popup is hard to see

### ISSUE THREAD

**Issue by Zian** [HabitRPG/habitica#1630] opened 2013-10-22 07:41 UTC
Given the following setup, then when I try to hover my mouse cursor over the description popup icon, it is very hard to get the description popup to stay visible. The popup shows up for a second and then goes away.
- Internet Explorer 10
- Windows 7 x64
- Maximized window on a Dell 1905FP monitor (1280x1024)

**Comment by paglias** [comment] 2013-11-12 17:43
I've noticed that this happens, sometimes (ie the re-roll button and the sync chat button), when the tooltip should appear where the mouse is and so it makes the element lose the hover status and thus the tooltip is hidden

**Comment by negue** [comment] 2014-08-29 13:23
I can't reproduce this. May already have been fixed.

@Zian could you re-check?

**Comment by negue** [comment] 2014-10-11 23:03
I'll close this, if this error "comes back" we'll re open this.

**Closed as completed by negue** 2014-10-11 23:03 UTC
Labels: priority: medium

**Comment by Zian** [comment] 2014-10-28 06:01
It's been resolved. Thank you.
