### ISSUE TITLE
New toolbar buttons are too small, pose accessibility problem

### ISSUE THREAD

**Issue by ashaindlin** [HabitRPG/habitica#3300] opened 2014-04-18 01:16 UTC
I really like the new toolbar design, but the buttons are so small that it often takes me several tries to properly position the cursor over them. I have some mobility issues in my fingers, so accurate trackpad control isn't the easiest thing for me, and an extra bit of space would go a long way towards making Habit more accessible for me and presumably plenty of other users with disabilities/injuries.

I don't think the change needs to be big (literally); the toolbar buttons before this update were large enough that I never had a problem. I hope someone more CSS-savvy than I can fix this.

**Comment by deilann** [comment] 2014-04-18 01:19
So, the other side of the problem is that bigger buttons were gotten away with because they took up too much screen space, making the site virtually unusable for some users.

My solution, at least for the time being, would be to zoom  your screen a bit. The toolbar does scale, along with the rest of the site.

**Comment by deilann** [comment] 2014-04-18 01:21
(I just wanted to remark that this is not me saying this should not be changed or fixed. This is me saying we'll have to think about how to go forward, and in the meantime, the zoom should help you use the site.)

**Comment by ashaindlin** [comment] 2014-04-18 01:31
Ok, thanks. My suggestion would be to have a vertical toolbar on the side of the page, but that's probably a huge amount of work to implement, and obviously low priority compared to the cron bug and all that.

**Comment by deilann** [comment] 2014-04-18 03:18
I would actually suggest a "large buttons" setting. It's a common
accessibility feature, even if I'd prefer fewer settings.

**Comment by crookedneighbor** [comment] 2015-07-19 00:57
Closing this, as I think the site's interface has changed since this was originally posted.

@deilann If you have time, I'd be interested in having you post an issue with a checklist for possible accessibility settings to add.

**Closed as completed by crookedneighbor** 2015-07-19 00:57 UTC
