### ISSUE TITLE
Code error: Scroll bar overflow cross browser bug (overlapped by the tags bar)

### ISSUE THREAD

**Issue by ricardobiundo** [HabitRPG/habitica#3011] opened 2014-03-05 16:05 UTC
Issue: Scrollbar that appears in crowded parties is overlapped by the tags bar.

Browser: Chromium browser (version 33 build in Freebsd mate interface) and possibly in all Linux based operated systems and old versions of Internet Explorer.

How to duplicate the bug: join a party with +8 members and the bottom scrollbar should be displayed with this issue in the commented browsers.

![bug_1](https://f.cloud.github.com/assets/5224572/2334609/a198dec4-a47a-11e3-98de-b18459d41a5a.png)

As displayed in the picture above, the tags (1) are shown above the scrollbar therefore it's nearly impossible to clic on the overflow party bar, scroll and see all the party members.

![bug_2](https://f.cloud.github.com/assets/5224572/2334743/f7d6ab80-a47b-11e3-8f84-e7318032f7b8.png)

In the second picture it can be appreciated the problem in hand. After a quick search, i figured out, as div container is build in the code, that scroll bar in some browsers are displayed outside the box, not inside it as most modern browsers do (http://css-tricks.com/the-css-overflow-property/).

The Solution: a simple solution that i came up with is to modify the div with the id "undefined-sticky-wrapper" that contains all the player stats and avatars changing:
        height: 148px
to
        min-height: 148px

That way the bug is fixed and it works as it should with and without party members:

![bug_3](https://f.cloud.github.com/assets/5224572/2334901/3c112a6c-a47e-11e3-8a3a-c721b18eba55.png)

![bug_4](https://f.cloud.github.com/assets/5224572/2334904/418cf4da-a47e-11e3-9b10-082a4f760b4b.png)

If no one reads this ticket i assume i should request a pull with the modification in the following days.

At last but not least i thank the community and creators of Habitica.

Sincerely Ricardo Marques.

ricardobiundo
ID: 2f34c6d9-90fa-4abd-b47d-3105bbc1f440

**Comment by snicker** [comment] 2014-03-05 17:39
confirmed fix, this bugs me too. unfortunately this seems to be a problem with 
https://github.com/garand/sticky

I thought that the fix described here https://github.com/garand/sticky/pull/83 would work, but it does not solve the problem.

To get jquerySticky to use min-height, we need to modify the code. It hasn't been updated in 10 months, I'm not against forking it into our repository and making the change. @lefnire ... opinions? I don't have authorization to fork to HabitRPG, you'd have to do it

**Comment by paglias** [comment] 2014-03-05 17:43
@snicker are we sure we need jquerySticky? I think this can be accomplished with some css and absolute positioning

**Comment by snicker** [comment] 2014-03-05 17:52
Not sure if we do or not for certain, but I’m fairly sure we do. the purpose is to keep the header bar at the top of the screen while the bottom part of the page continues to scroll.

There need to be some javascript hooks in scrolling to make this happen, which is why jquerySticky is used

**Comment by paglias** [comment] 2014-03-05 17:55
See for example Bootstrap's own navbar. It is sticked to the top and uses only css.

What jquery sticky does is to apply `position: fixed` to an element when it is going to be scrolled

**Comment by snicker** [comment] 2014-03-05 18:29
If you want to work some wizardry to make that happen, it's one less dependency we can have in bower

**Comment by ricardobiundo** [comment] 2014-03-05 19:58
Hello. Thank you for responding.

I search for sticky jquery plugin. @snicker as far as i understand the sticky menu works perfectly and could be made easily with ccs and java script. I don't think the issue is related at all with the hovering menu. Is actually the fact that the scroll bar is created outside the container and with a fixed height size that the div doesn't grow with it. I think the fix should also be accomplished with html if we create another div containing the actual div and give it the scroll attribute.

"min-height" works great for me and it's CSS2 so it works in +IE7 (windows vista and higher i think) and most mobile browsers. Am i missing something?

**Comment by snicker** [comment] 2014-03-05 20:27
@ricardobiundo I believe what you are missing is the fact that the jquerySticky plugin is what dynamically sets `height: 148px` on the DOM element. You could override that in the CSS to be `min-height: 148px` but then it is no longer set dynamically, and if the height of the Party header changes in the future, that has to be changed explicitly as well.

@paglias it appears that it can be done with just CSS, but why was JQuery sticky ever used in the first place then?

**Comment by snicker** [comment] 2014-03-05 20:29
per https://github.com/HabitRPG/habitrpg/blob/c41097b6eccc831b01487de187e182cc61645046/public/js/controllers/rootCtrl.js#L12 it would appear that if we do something different, we need to retain functionality for users to select whether or not they want the header to be sticky.

Or we could just fork jquerySticky, change the single line, and close this ticket

**Comment by snicker** [comment] 2014-03-05 20:30
Re-evaluate whether or not it's needed in another ticket perhaps, we have a fix that can work with minimal effort that will alleviate a fairly annoying UX bug.

**Comment by ricardobiundo** [comment] 2014-03-05 21:29
@snicker are you telling me that the plugin is dynamically making the height equal to 148px based on the size of the content information. Is that right? If so, why that plugin is doing that. As far as i understand JquerySticky is used to maintain the status bar hovering if the user check that option on the preferences tab.
I don't get why it's used to establish the size of the object. I understand your concern that we need to retain the functionality but the problem is present even when the status bar is not hovering. I really don't get why we are using JQuery sticky to change the height either as you told @paglias. Think we should make the modification over the JQuery sticky or better yet make it on CSS.

Sorry for being so annoying but my knowledge of jquerry are almost nil.

**Comment by snicker** [comment] 2014-03-05 22:05
@ricardobiundo that's correct. I assume that it is explicitly setting the height of the object based on its content to deal with some edge case scenarios that we don't experience, but the fact remains that we would need to either:
1. stop using jquerySticky and use a pure CSS model
2. fork jquerySticky and make the modification of the one line

option 1 requires a fair amount more effort than two, so I'm suggesting option 2 with further investigation into option 1 in the future.

**Comment by ricardobiundo** [comment] 2014-03-11 01:25
Problem not present anymore in chromium 33. Not sure if still persists in other browsers like old version of IE.

**Closed as completed** 2014-09-09 18:12 UTC

**Comment by negue** [comment] 2014-09-09 18:17
I had this problem in current Firefox too.

My checkin 62361b6 should fix it.

I've set the sticky header height to auto, now the scrollbar can be used without problem AND all content won't overlap the header.

Once this goes live, pls write here If you still have the same problem.
