### ISSUE TITLE
Blue loading bar

### ISSUE THREAD

**Issue by suitcase76** [HabitRPG/habitica#1794] opened 2013-11-11 22:42 UTC
The blue loading bar at the top left of the browser window (Have only tested on Chrome) is constantly updating and re-setting even when there is no interaction with the page. 

Is anyone else finding this issue? It's not a huge problem, just very distracting.

**Comment by lefnire** [comment] 2013-11-12 02:16
dupe of #1735, follow there

**Closed as completed by lefnire** 2013-11-12 02:17 UTC
