### ISSUE TITLE
Pet not added to stable after hatching

### ISSUE THREAD

**Issue by antiharmonic** [HabitRPG/habitica#1138] opened 2013-06-05 18:08 UTC
Today I hatched two pets in a row, and when I went to my stable the first pet I hatched was not there. It was a Golden Panda. I'm not sure if it had anything to do with hatching two in a row.

**Comment by Shaners** [comment] 2013-06-05 19:07
What is your user ID?

**Comment by antiharmonic** [comment] 2013-06-05 19:32
1a76a453-85d2-4f5b-b254-c9f9f474cebd

**Comment by lefnire** [comment] 2013-06-08 16:26
added some tokens so you can buy back. the issue is in multiple tickets, so i'm gonna close this for organization

**Closed as completed by lefnire** 2013-06-08 16:26 UTC
