### ISSUE TITLE
Ability to Change Challenge Tasks Names/Descriptions

### ISSUE THREAD

**Issue by DanielTheBard** [HabitRPG/habitica#1753] opened 2013-11-05 15:15 UTC
Is it impossible to change it so that we can change the Challenge names/descriptions? I assumed it was done this way on purpose, where we can't change them. However, most of my dailies and habits, I try to keep in an RPG-style. Such as "Sift Through Tomes" instead of "15min of Reading" or "Master the Language of My People" instead of "15min of Duolingo". By not being able to change Challenge titles, the challenges stick out a lot from the theme I have. It's actually preventing me from joining many challenges. I know some other people in my guilds and my party share this same issue. 
##

**Comment by elprohabro** [comment] 2013-11-06 00:08
Tyler fixed it, but still it works only if you add new task to your challenge. Then your edited tasks change to new ones.

**Comment by elprohabro** [comment] 2013-11-06 00:11
Sorry I misled you. I was talking about task names. They don't update unless you add new task. But challenge name changes that way too.

**Comment by deilann** [comment] 2014-02-07 22:17
Okay, so, I'd like to bring this back up. I think that it would be nice to have an "editable" setting on Challenges. Setting a task in a challenge to "editable" would allow people to edit:

**Habits**
The difficulty and the name.

Would allow people to "gamify" the habit and make sure that it's not giving them too much/too little EXP gold, depending on their use.

**Dailies**
The name, the days of the week, and the difficulty.

Same reasons as above, but also allows them to remove days in which they cannot (or should not) do the challenge, such as respecting the Sabbath. Making the days editable would also make it possible for people to choose the day for weeklies.

**To-Dos**
Changing of the name and difficulty.

**Rewards**
Changing of the name and the price.

20GP to me is very different than 20GP to someone else, depending on their setup and PER. This would allow people to set a custom price that is most appropriate to them.

There are instances in which a challenge would NOT want people to edit it, such as rewards that are specifically set low (a one GP mental health day or the .5 GP "Oral Fix" reward I have for my smoking challenge), things that need to be EVERY DAY for the challenge to work, so on and so forth.

**Comment by wc8** [comment] 2014-03-14 12:50
I'd be in favor of supporting editable/not-editable as a switch only the challenge creator controls. It'd be good for #2205 as well. 
Some of the technical difficulties mentioned [here](https://trello.com/c/XFXRoelM/308-challenges-participant-customizations-e-g-aliases-tags) might apply, though.

**Comment by wc8** [comment] 2014-03-14 12:53
@DanielTheBard do you mean the titles of tasks or the challenge tag? 
I don't think the Challenge Title shows up on the user's task board?

**Comment by lemoness** [comment] 2016-06-04 01:58
Are we still interested in this?

**Comment by crookedneighbor** [comment] 2016-06-04 02:18
I don't think so. It's by design that you can't change the task text.

**Comment by Alys** [comment] 2016-06-04 02:18
People ask about it every so often. With the recent challenge API and database changes, we could make it so that participants could change the task names but the challenge owner would still see the original name when assessing the challenge.

However there'd probably be cases where the participants forgot what the original task was and actioned it in a way that wasn't suitable for fulfilling the challenge requirements.

We could make it so that they could add their own title while still seeing the original one, but that would require more effort (front-end changes on both website and apps).

I tend to be on the side of not allowing changes - when you join a challenge, it's to get the same tasks as everyone else

-- and just as I was finishing typing all that, @crookedneighbor closed this. ;)

**Closed as completed** 2016-06-04 02:17 UTC
Labels: status: issue: suggestion-discussion, section: Challenges

**Comment by crookedneighbor** [comment] 2016-06-04 02:19
^ Much more articulate than me, but exactly what I was thinking.

**Comment by aurlxo** [comment] 2017-01-28 11:09
I'd like to have the option to edit challenge task titles on my own task board.

In my opinion, the possibility of forgetting the original task is a small downside in this. Being able to edit the tasks to fit your own task style feels almost like it should have always been possible since people have different ways of playing Habitica! It could be even done so that you could check the original description by clicking "edit" on your own task, and it would display the original title and maybe even have a link to the original challenge.

Different styles of writing the tasks down can end up looking really confusing when browsing through your task list. Being able to edit the challenges to fit your own style would help with this a lot.

**Comment by Alys** [comment] 2017-01-28 11:30
@Vamii The possibility of a challenge participant forgetting the original task is actually a fairly serious one because all participants are meant to have identical tasks when they take part in a challenge, and are meant to action them in the way the challenge owner deemed correct. Challenges are the one place in Habitica where differences in play style sometimes need to be minimised so that all participants are on a level playing field, as much as possible. Allowing participants to change tasks would inevitably lead to them forgetting the original details and many wouldn't click through to remind themselves of those details. This means they'd potentially complete the tasks in a way that was not intended by the challenge owner, which might not be fair to the other participants who had kept the original task titles.

However if you like the topic of a challenge but want to reword the tasks and aren't interested in competing for the winning position, you can join the challenge then immediately leave it, choosing the option to keep the challenge tasks. The tasks will then become your personal copies and you can edit them in any way you wish.

**Comment by aurlxo** [comment] 2017-01-28 12:06
@Alys Thank you for the fast answer! I do understand your concern with this issue.

Still, I believe that as completing a task is also up to the conscience of the players (it would be possible to participate in challenges and just click through them regardless), I don't think it's that likely, or a major issue, if someone ends up "completing" challenge tasks in a slightly modified way that fits them better. Challenge participants are, after all, interested in working on towards the same goal together with the chosen tasks provided by the maker of the challenge. Participating in a challenge but doing something completely different doesn't sound like a likely nor a purposeful action for anyone.

Humans are prone to forgetting things, though, and it is definitely possible that this might end up being a bigger issue than I'd imagine it could be, or they could interpret the possibility to "edit" the challenges in different ways.

But sadly, the option to join a challenge to get the tasks and to then leave the challenge kind of defeats the purpose for me. Everyone has their own personal challenges anyway, but being a part of a challenge group would be a bit different.

Thank you for the consideration, though! Maybe there will be some kind of a solution for this in the future. :)
