### ISSUE TITLE
Dailies not re-setting

### ISSUE THREAD

**Issue by Catmagnet** [HabitRPG/habitica#1618] opened 2013-10-14 20:36 UTC
I had this problem before the port, and it's still occurring.  At least once a week--and twice this past week (today being the second time) my dailies have not updated.  I've tried rebooting my computer, turning the browser off and then on again, and refreshing the page.  None of that helps.  I don't use the mobile app often, but this hasn't happened on the days when I _do_ use the mobile app, so checking the site on multiple devices probably isn't the problem.  If it only happened once in a great while, I wouldn't complain, but it's happening quite often lately, and it's annoying (I have a lot of dailies).

I did notice that it seems to happen after days when I've been too busy to get on and check off my HabitRPG until later in the day (like near midnight HabitRPG time, which I've set at 5 a.m. my time since I'm a night person).  Could reset be messed up by me checking off a fairly large number of tasks just before the turn-over?

Also, do we no longer get notifications of every 21 days of a streak?

**Comment by lefnire** [comment] 2013-10-17 01:01
dupe of https://github.com/HabitRPG/habitrpg/issues/1057, let's follow up there

**Closed as completed by lefnire** 2013-10-17 01:01 UTC
