### ISSUE TITLE
Posts disappearing from Tavern chat

### ISSUE THREAD

**Issue by LordGrowl** [HabitRPG/habitica#1427] opened 2013-09-04 20:33 UTC
I had very recently expressed my appreciation for the fine work lefnire has done by allowing him the privilege of bearing my seed but this post - along with lefnire's gratitude  and a few other posts - appears to have disappeared.

It is a sad day in Habitica (Habitia? Habiticia?).

**Comment by lefnire** [comment] 2013-09-04 21:04
I'll double check on this re: beta, but there's a known bug on the derby branch that clobbers chat. We had to chose between (a) allowing enormous amounts of duplicates due to a Racer bug, or (b) setting the chat object wholesale due to another Racer bug. We chose b, which unfortunately can clobber new posts.

I'd be surprised if this only recently started cropping up, and on the beta branch. What I imagine is happening is we beta-users are chatting, then someone from production pops in and clobbers the messages. Get out of our chat room, production users! :)

We'll be launching to prod soon. If this happens again after that time, then let's revisit

**Comment by lefnire** [comment] 2013-09-06 14:51
as long as nobody chats from old.habit, this should be fixed :) @LordGrowl you have a good eye for this one, can you keep an eye out in case it crops up again?

**Comment by LordGrowl** [comment] 2013-09-06 22:11
No problemo, chief.  =]

**Comment by lefnire** [comment] 2013-09-06 22:26
It's back. Fack. Code looks simple and bugless too :/ Will tackle this one soon

**Comment by paglias** [comment] 2013-09-06 22:29
Disable chat on old site?

**Comment by lefnire** [comment] 2013-09-06 22:31
That's a good idea. Not sure if the issue is people chatting on the old
site (not sure how many people using it), but that would be a good way to
test

**Comment by lefnire** [comment] 2013-09-10 20:35
Well, haven't seen this since! good riddance Grey

**Comment by LordGrowl** [comment] 2013-09-10 21:09
Haha! You only just closed this 34 minutes ago at time of writing and it's just happened again.  =P

**Comment by lefnire** [comment] 2013-09-10 21:12
really? aw man, I hadn't seen it since killing old.habit.  alright _sigh_ re-opening

**Comment by LordGrowl** [comment] 2013-09-10 21:19
Sorry, chief.  =[

**Comment by paglias** [comment] 2013-10-24 19:10
@LordGrowl , this is quite difficult if not impossible to replicate, can you reopen in case you see it once again?

**Closed as completed by paglias** 2013-10-24 19:10 UTC
