### ISSUE TITLE
Group Plan tasks need second completion after approval

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#10985] opened 2019-02-11 21:00 UTC
As reported by @KShadowyn (0d38be36-726c-41bf-9c60-2b19d9c54d48): 

"I have a group that has my family members in it. I created a daily for the kids' chores and set it so it requires approval. When they complete their chores and check it off, it requests my approval. Once I approve that daily, why do they have to go in and check the daily off again? Shouldn't it automatically complete it?"

I asked: "When you approved the Daily, was that on the same day that the child had marked it complete?"

They said: "They were all requested and approved the same day as I tried it many, many times to see if it was just me. So I know that it is doing the same thing on Habits, Dailies and To-do's. It is the same no matter who is requesting approval. It is even the same on the Android app as well as Chrome on my laptop or my phone."

Guild ID: 59e1e27c-6156-48c5-aba8-a85a3851c357 (group plan is active)

**Comment by CBillings92** [comment] 2019-02-12 17:50
I'm not sure if you're looking for a more seasoned contributor for this/what the expected turn around time on this is since it's a high priority level, but I'd be willing to give it a go if that's alright! 

Regardless of whether I'm actually the one who works on this, I figured I'd take a look into it just as a means to learn the code/API a little more (and who doesn't like a challenge). Trying to recreate this locally, and I need to create a group. I'm wondering how one would go about doing that (avoiding/getting around the paywall). Do I just need to manually create the group in the database or figure out how to hit an API endpoint, or is there a built in debugging work around I'm missing?

Thanks!

**Comment by zmontgo** [comment] 2019-02-13 01:22
And if you need me, I can try it, too. I'll defer to CBillings92, though!

**Comment by Alys** [comment] 2019-02-13 10:25
@CBillings92 Thanks! Have a look at [Using Your Local Install to Modify Habitica%27s Website and API](http://habitica.wikia.com/wiki/Using_Your_Local_Install_to_Modify_Habitica%27s_Website_and_API) and search for "group plan" - one of the hits will be in a section that tells you how to add a group plan to a guild. Post here if you have questions about those details or anything else that comes up.
I'll mark this as in progress for you.

@zmontgo Thanks for also being willing to help! We'll let you know if it opens up again.

**Comment by CBillings92** [comment] 2019-02-13 15:57
@Alys Thanks for that suggestion! I found what you were referencing and was able to create a group and recreate the bug. I'll make sure to post here with any questions or updates.

**Comment by CBillings92** [comment] 2019-02-13 16:17
I suppose my first question is actually around how the UI should function ideally. Currently a user checks off a task and they're notified that it's been submitted for task approval, and the task to the assignee appears as if they have not checked it off (and no identification that it's awaiting approval). When the assigner of the task approves the task, the task still remains unchecked. 

Is the ideal design:
1) User (assignee) checks task than needs approval
2) User (assignee) sees new task approval banner that states "Awaiting Approval" (and the task remains unchecked 
3) User (Assigner) approves the task 
4) User (assignee) no longer sees "Awaiting Approval" header above task, and task appears checked (completed) 

Or should the task, while waiting for approval, just appear as though it's been completed?

Thanks for the help!

**Comment by zmontgo** [comment] 2019-02-13 22:27
Perhaps there should be three states for a task, in terms of how the code handles it...
1. Not Done
2. Pending approval
3. Done

**Comment by CBillings92** [comment] 2019-02-16 19:45
Just an update on this (figure I'd share my updates since I'm still new to this code base, hoping I'm on the right path with the correct assumptions)

Seems like the issue is multi-faceted. Currently when I'm on my Tasks screen as a user that's been assigned a task that needs to be approved, and I check off that task...

1) The daily does not get marked with a check mark (stays as it was) (is this the expected behavior)
2) A notification appears, stating that the task has been sent for approval (this seems fine)
3) *No* approvalHeader is shown stating that the request is waiting approval (first issue)
4) When I approve the request, the task for the assigned user that completed the task does not appear completed (second issue)

**For the first issue, I see a couple of causes...** 
1) I see the approvalHeader template being heavily reliant on a `task.approvals` key, which is calculated on the `taskInformation` component. 
    * This `taskInformation` component, however, is only loaded on the *group task board* and *not* your *Personal* Tasks Board, meaning you'll never get the required `task.approvals` key with data to display the `approvalHeader` on your *Personal Task Board*. 
    * The `taskinformation` component code currently doesn't seem to have a way to set an empty array for `task.approvals` if it is indeed empty (it just never creates an `approvals` key on the `task` object). This is problematic because the `approvalHeader` code relies on there being an `approvals` key on each `task` object

***My questions and suggestions for the first issue***
1) Do we want the approval header code for asignees showing up on the *Group's Task Board* AND the person's *Personal Task Board* (the `you are requesting approval header`)?

If we want that `you are requesting approval` messaging on both the *Group* and the *Personal* Task Board then my suggestion would be to maintain the `userIsRequesting` code (dependent on `task.approvals` array only found on the *Group* Task Board), and add the following code to check on the *Personal* task board...
```
      let userIsRequesting =
        this.task.group.approval.requested &&
        !this.task.group.approval.accepted;
```   
So the code might look like 
```
      let userIsRequesting =
        (this.task.group.approval.requested &&
        !this.task.group.approval.accepted) ||
        (this.task.approvals &&
        this.task.approvals.indexOf(this.user._id) !== -1)
```

**For the second issue...**
I've looked a little bit into this, but still exploring. I was trying to figure out the logic of the approvalHeaders and the differences between `task.approvals` and `task.group.approval`

***Questions for the second issue***
How should dailies, to do's, and habits be displayed when they're awaiting approval? Should they appear just as they did before they were checked off, just with the approvalHeader displayed with the appropriate message?

Thanks! Let me know if these thoughts weren't clear! I'm going to continue on this.

**Comment by SabreCat** [comment] 2019-04-24 17:51
This isn't a bug, as such; it's the current expected behavior that the first click on an approval-needed task requests approval, then after receiving approval the user clicks the task to collect their rewards. That said, there is probably a better way to do this, but it'll need some hashing out at the workflow/UX design level. I'm going to set this to needs-discussion.

ETA: The above just refers to the OP, not to subsequent discussion.

**Comment by paglias** [comment] 2020-08-01 13:50
@SabreCat this has been fixed by the recent group tasks PR?

**Comment by SabreCat** [comment] 2020-08-01 14:45
Yes, indeed!

**Closed as completed by SabreCat** 2020-08-01 14:45 UTC
Labels: status: issue: in progress, section: Group Plans
