### ISSUE TITLE
Application error with my chrome browser

### ISSUE THREAD

**Issue by staerawilson** [HabitRPG/habitica#6767] opened 2016-02-25 02:54 UTC
As in the following image: 
![apperror](https://cloud.githubusercontent.com/assets/13644416/13308389/c6b725be-dbad-11e5-9212-c80af73e6ba3.png)
Which persists after several times of reloading.

**Comment by bingaota** [comment] 2016-02-25 19:23
I likewise have the same error using google chorme.  When I go to sync or complete a task or to-do the browser attempts to sync only to produce this error.  I have cleared my cache and cookies, but the issue continues to happen.

**Comment by staerawilson** [comment] 2016-02-26 07:07
@bingaota I re-installed and now it's going well. Just don't know what was wrong with it.

**Comment by alexiabowers** [comment] 2016-03-01 03:03
I'm also seeing this error periodically on Chrome - I usually see it with I'm clicking several things quickly, usually with tasks with checklist items. It will go away when I reload the page. Looking in the headers, it seems like it is an issue with batch-update. I've got a screenshot of the headers in Chrome developer tools (or text version), just let me know. My user id is: 002b1022-bceb-4b9c-ba0f-41915fb3e018.

**Comment by lynxlynxlynx** [comment] 2016-03-01 11:13
Sounds like a duplicate of #6700 and its linked bugs.

**Comment by Alys** [comment] 2016-03-06 22:40
We're tracking this error now at https://github.com/HabitRPG/habitrpg/issues/6700 so I'm closing this one. There's some advice at the top of that issue for anyone who experiences this problem.

**Closed as completed by Alys** 2016-03-06 22:40 UTC
