### ISSUE TITLE
Gold Coin Display Glitch

### ISSUE THREAD

**Issue by EdgeNinja** [HabitRPG/habitica#3908] opened 2014-08-23 17:51 UTC
So I've noticed that whenever you create a custom reward with a price that's three digits or more, the gold piece image doesn't display correctly. The gold piece image will appear UNDERNEATH the price of the custom reward instead of to the right of it. And between rows. Think this glitch might extend to regular rewards priced at three digits or more as well. I'm not the only person who's noticed it.
![habitrpg your life the role playing game](https://cloud.githubusercontent.com/assets/8532482/4021324/14fbb964-2aee-11e4-993c-265c9812f878.png)

**Comment by negue** [comment] 2014-08-23 18:00
Duplicate of #1993 

Possible fix: #3615

**Closed as completed** 2014-08-23 19:36 UTC
