### ISSUE TITLE
Changes made to Dailies and Todos disappear

### ISSUE THREAD

**Issue by pixelpax** [HabitRPG/habitica#1278] opened 2013-07-24 01:31 UTC
I'm using google-chrome (version 27.0.1453.110) in Linux Mint 15. Sometimes when I make changes to ToDos and Dailies (checking them off, modifying them or adding new ones) the changes appear to be made, but when I refresh the page, the changes I made are not present. This happens intermittently, and when it does, all the changes that I made that session disappear. I cannot definitively say whether it affects Habbits (although I would think it would) simply because it hasn't come up yet. I have also used Magic Mickey's Android App, Chrome for Windows 7 and Firefox on Linux Mint 15 without having this problem. 

My UID is 730d2d0f-daf1-4b2c-b2ea-d1df45f2679b and I did not have any js errors. 

I had some other strange behavior the other day with Habit using the same browser and OS. I have no idea if they could be related. Issue is logged here: https://github.com/lefnire/habitrpg/issues/1275

**Comment by lefnire** [comment] 2013-07-24 19:11
Caused by #165, impossible to fix in the interim until we migrate to Angular. See http://habitrpg.tumblr.com/post/55792029689/bug-workarounds for the details & workaroudns

**Comment by lefnire** [comment] 2013-07-24 20:58
don't mind my closing this, lotsa duplicate bugs by different descriptions & doing some house-keeping. still google-able if others hit it

**Closed as completed by lefnire** 2013-07-24 20:58 UTC
