### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by lefnire** [HabitRPG/habitica#4079] opened 2014-09-25 04:45 UTC
After investigating recent server craziness, I've come to a couple points:
1. Memory leak. Per [StrongLoop](http://strongloop.com/strongblog/node-js-performance-tip-of-the-week-memory-leak-diagnosis/), a steady incline in mem usage (vs the "comb" pattern) indicates a memleak. Viewing our [mem usage](https://dashboard-next.heroku.com/apps/habitrpg/metrics/web) (anyone who has heroku access, [screenshot for others](http://gyazo.com/315fac5dc9d33325018bbf94ea2ca619)) shows inclines before each crash/restart, a _very_ likely candidate. Compare that with [NewRelic](https://rpm.newrelic.com/accounts/565514/applications/3386694) will give us deets about which txns / errors might be correlated. My eye is on spell-casting and all things Challenges. However, I haven't been able to find any concrete memleak evidence on local experiments. [Here are tools / resources for getting started](https://workflowy.com/s/14RdBB75p5). No leads yet - though I can almost guarantee we have a leak (per Heroku) - and those are the tools for anyone so inclined.
2. We need to cut back on application code resource usage. NewRelic shows most (like 95%) of our perf bottlenecks on the application side, and Mongo seriously underutilized. To show what I mean, check out https://github.com/HabitRPG/habitrpg/commit/632726fe0273ad507138ae9c30a8a890659e8a0f which pushes all the filtering from the server to MongoDB (saving the server resources). The comments give details on why/what, but this is tip-of-the-iceberg regarding what we can fix-up in Habit's code by moving everything mongo-side. The biggest pain-point here is Challenges, where way too much is handled on the server instead of MongoDB; but there are other locations.

Anyway, this is simply a brain-dump, I'll be in it deep in coming days, just posting here in case someone has insights

**Comment by lefnire** [comment] 2014-09-27 00:27
Updated the thread with a [Workflowy with more deets](https://workflowy.com/s/14RdBB75p5). See in particular `Modules > node-webkit-agent > Steps`, which includes instructions + [this screenshot](https://www.evernote.com/shard/s17/sh/2388d8a3-aea7-4f28-9de4-d67d7166d0e2/55016c828bbe7b2844826a146c987cf9), getting us closer to the goal. Looks like User model is hanging around after just about any action, latest lead is the [wrapper function](https://github.com/HabitRPG/habitrpg-shared/blob/develop/script/index.coffee#L362). Weird thing is, why now (so suddenly, within last week)? Was a module (#.#.x, or \* in package.json) updated, or a module's submodule - which contributed to this issue? Theoretically this leak should have been around for a long time...

**Comment by lefnire** [comment] 2014-09-28 00:31
Not certain yet, but that wrapper function looks _very_ much to be the culprit! I'm showing `ops`, `fns`, and `user` to be objects not garbage collected. After some reading around, looks like closures using object refs from above, esp. within callbacks, are a candidate for holding onto refs (I'm still wrapping my mind around it, so pardon my vagueness). I _think_ the solution here is to change that wrapper function into some proper JavaScript inheritance model w/ prototypes. The difficulty will be handling User Model in one case (server), and POJOs in the other (client). Then when the mongoose model goes out of scope, the only refs that object are `this` within the functions, so should be GC'd. 

https://github.com/mattbornski/node-leak-patterns for more info

**Comment by Feriority** [comment] 2014-10-01 07:44
If I'm understanding the problem correctly, the high memory use comes from reconstructing the closures every time we wrap a user, such that each user contains its own set of all the closures (combined with not releasing the users properly when we're done, but the scope of user is clearly outside `wrap`).

Rather than using prototypes, could this be solved by defining the functions outside `wrap` but having them use `this` instead of `user`?  Then, in wrap, you attach the existing functions to `user`, so it only needs a reference to the already-defined function rather than a new copy of the function?  I don't know the coffeescript equivalent of "use strict", but you could use that to prevent calling the functions without attaching them to an object first (as `this` would be `undefined` and not a global object).

None of this fixes the issue of the users not being GCed in the first place, but it could mitigate the cost of each lingering user.  Then the remaining task would be figuring out what's creating and wrapping these users but not releasing them.

EDIT: I think this solution might be complicated by the functions living in ops and fns rather than directly on user, but could work if ops/fns have a reference back to user?  Apologies for just suggesting an approach and not submitting a patch, but my coffeescript mojo isn't quite up to this and I'm not totally confident in my suggestion.

**Comment by paglias** [comment] 2014-10-01 14:10
@lefnire but it's not possible that user is not being gc and therefore user.ops and user.fns? Everything should be thrown away after the req is closed.

But if it's as you said we can easily move to a 'Class':

```
var User = function(user){
    this.user = user;
}

User.prototype.fns = .....
User.prototype.ops = ....
```

This way `ops` and `fns` will be inherited and we can access user as `this.user`

**Comment by paglias** [comment] 2014-10-01 14:12
@Feriority your approch looks good to me, but I'm not sure `this` in functions inside `ops` and `fns` will be the user... will test and report back

**Comment by paglias** [comment] 2014-10-01 14:13
@Feriority also I'm not sure in this case `ops` and `fns` will be shared among all users but instead could be re-created every time.

**Comment by paglias** [comment] 2014-10-01 14:16
@Feriority I've test it and wouldn't work http://jsbin.com/befobexupiye/1/, this does not reference user

**Comment by lefnire** [comment] 2014-10-01 20:45
@Feriority is on track with the closure stuff. I've tried moving ops/fns to a User constructor, but `this` points to the object `ops:{}` or `fns:{}`. Reworking it so the prototype + `this` is all structured properly will require some major major overhaul of Habit code. Instead, per [this article](https://www.meteor.com/blog/2013/08/13/an-interesting-kind-of-javascript-memory-leak), it's very likely the fact we keep objects around in closures, and they're never released even after Express sends `res.send`. Proposed solutions are `user=null` at the end of the closure that needed the user object, but I've tried going through all locations where this would be likely (particularly at the end of `api.batchUpdate` - but it's still not kicking the leak. Google "memory leaks closure" to see more examples / proposed fixes, I'll keep at it

**Comment by Feriority** [comment] 2014-10-01 20:45
@paglias I think I addressed that in my edit above - see http://jsbin.com/befobexupiye/2/edit

That said, I think my solution is hackier than properly using classes, so if you can do that easily please ignore me :)

**Comment by lefnire** [comment] 2014-10-01 20:57
FWIW, [this is my proposed fix](https://gist.github.com/lefnire/7c02f81d49bbe036f601/cc768a5016316f1175721ee3eeeec46073c39447) (which doesn't work)

[Edit] I may have spoken too soon, `user` at that location was a closure var, not a local var. [Updated gist](https://gist.github.com/lefnire/7c02f81d49bbe036f601/5fff013ed5d9c73c520102cf237347ddb1cf26b0#file-website-diff-L30). The leak is certainly still present, but this _may_ have reduced the severity. Still testing to be sure. If in fact this reduced the severity, we'll just need to keep an eye out for any closures [hanging on to vars in it's lexical context](http://mrale.ph/blog/2012/09/23/grokking-v8-closures-for-fun.html)

**Comment by lefnire** [comment] 2014-10-02 18:37
Oh baby oh baby! @lemoness @paglias @Feriority 

![img](http://i.gyazo.com/6c236e74c1e0b4bb6fbe3df97629da91.png)

Don't want to jinx us now, but I believe my updated gist above fixed it! If not **it**, fixed at least a _major_ portion being on the `api.batchUpdate` side. Now that I know what the issue was (closures holding onto variables due to [lexical context nuances](http://mrale.ph/blog/2012/09/23/grokking-v8-closures-for-fun.html)), I'll be on the hunt for wherever else memleaks may be occurring - but it appears (knock on wood) that I pegged the biggest one

**Comment by lefnire** [comment] 2014-10-02 18:55
@paglias @Feriority incidentally, changing `api.wrap` to be a proper `User()` constructor, following prototypal JS paradigms _wouldn't_ have fixed anything in this case, it's definitely closures. `User` constructor is better practice, and my `api.wrap` code is ugly and weird - but doesn't make a diff here.

**Comment by lefnire** [comment] 2014-10-02 22:48
Pushed the corresponding commits. I've verified: this changeset _helps_ substantially, but it hasn't completely fixed the problem. There's still a leak (or many) that causes [memory to very slowly hike](http://gyazo.com/b1cf3525dd0e6360230d2c629c1a8be2), so let's all keep an eye out for bad closure setups as we go along. I'm cleaning up this thread's comments so others can read this post, as I hope to get more hands in here. Re-opening until we can peg all the leaks

**Comment by lefnire** [comment] 2014-10-04 23:35
Progress on https://github.com/HabitRPG/habitrpg/commit/5c69c3a42b566d736e37f9dbdf56b4deda9112cb . From the articles above, you can see that leaks occur when closures hang on to parent closure variables. The solution is to nullify those variables where necessary. Note, you don't set `user = null` everywhere - _only_ when a child closure uses `user`. So you'll see I don't set all hoisted variables to null, only the ones used in child closures within a function. Best way to tell is use an IDE like Webstorm, click on the var declaration, and all uses within context will be highlighted. Haven't tested yet, just FYI coming code

**Comment by lefnire** [comment] 2014-10-07 00:41
https://github.com/HabitRPG/habitrpg/commit/57a5a62d7c3266808bc72e8ca2de7888ff4bdf75 there's another big one (don't mind all the force-push commit refs before the last one above). Unfortunately, it's a bit hard to test the effectiveness of these changes - kinda "in theory" fixes, with some `node-webkit-agent` fuzzy-tests to see if mem-usage (and diffs) **seem** to have gone down, while still making sure the tests pass. Anyway, keep an eye out for any issues all, this setting variables to null everywhere kinda makes me scratch my chin

**Comment by angelwedge** [comment] 2014-10-15 08:28
(Oops, commented on the wrong issue. This was supposed to be about the "Application error" issue, though I believe someone said that's caused by this)

I've been having this intermittently too.
Really annoyed this morning, though, because I got the error while saving a new challenge. Not only did it lose the details of 16 tasks that had taken me 20 minutes to type up (shouldn't they stay on screen until the server accepts them, so you don't lose data?), but it looks like I still lost the 2 gems I was offering as a prize.

Can I at least get the gems back, please? Username mrangel; userID c54131a9-0a08-4d26-8969-cb6f96bc95bd

**Comment by Alys** [comment] 2014-10-15 09:48
@angelwedge : In case you didn't see my reply to you in the Tavern, can you please reload HabitRPG (any page on the site) and tell me if the gems are still missing?

EDIT: mrangel has said in the Tavern that the challenge WAS created.

**Comment by angelwedge** [comment] 2014-10-15 10:20
Reloading didn't make any difference; nor did looking on a different browser or a different computer. Clicking a tag to filter my tasks seemed to make it appear about an hour later; and re-sync made it appear on other computers. So the challenge now seems to be working, but the only device I can't see it on is now the one that originally created it. I'm going to try a logout, flush cache, and login again, to see if that helps.
This seems like a pretty weird state; I wish I had more JS experience so I could try to figure out how this happened.

**Comment by Alys** [comment] 2014-10-15 10:22
@angelwedge Can you please confirm specifically whether the two gems have been added to the challenge as expected or whether you still require them to be refunded?

**Comment by angelwedge** [comment] 2014-10-15 11:23
Seems to have worked OK, the challenge shows up with a prize. I'm satisfied that it was just a remporary gglitch.
I still can't see the tasks from that challenge on my mobile browser, though they appear OK in the android app. And on my laptop/desktop, I can no longer see the tasks in any challenge I'm not participating in, or see the progress of other challenge participants. I assume that's a separate issue?

**Comment by crookedneighbor** [comment] 2015-07-19 02:21
I believe @gisikw fixed this. New Relic interacting with node was causing the memory leak

**Closed as completed by crookedneighbor** 2015-07-19 02:21 UTC
