### ISSUE TITLE
Text overlapping in Seasonal Shop

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica#10281] opened 2018-04-25 20:27 UTC
> "Hey Habitica! I found a minor front-end issue relating to text overlapping. I don't think this was an issue prior. Perhaps there was a CSS change recently?
> 
> Summary: The "Available until..." text overlaps with the equipment stats for limited-time items.
> 
> Steps to Reproduce:
> 
> Navigate to Shops
> Navigate to Seasonal Shop
> Hover over an item with stats (ie. Buoyant Ballbrush)
> Expected Behavior: The "Available until..." text should be below the stats.
> 
> Observed Behavior: The text overlaps as seen here: "

![img](https://image.ibb.co/hJd0Gx/Screen_Shot_2018_04_24_at_21_41_23.png)

**Comment by shadimoustafa** [comment] 2018-04-29 20:56
@Alys  @shanaqui 

I would assume changing the height of the font for .limitedstring in buyModal.vue would fix this bug.
 
   .limitedString {
        height: 16px;
        margin-left: 8px;
      }

Please let me know if I am mistaken. I would like to work on this but it's hard to test the changes.

**Comment by Alys** [comment] 2018-04-29 21:07
@shadimoustafa Thank you for wanting to work on this! The fix isn't really something we can judge until we've seen it in place so if you'd like to experiment with it on a local install and then submit a pull request, please go ahead! I'll mark this issue as in progress for you, but if you decide to not work on it, just let us know! :)

**Comment by beffymaroo** [comment] 2018-05-30 21:48
@shadimoustafa Are you still working on this issue? Let us know when you have a moment. Thank you!

**Comment by shadimoustafa** [comment] 2018-05-31 05:48
@beffymaroo Unfortunately, I got busy with school and stopped working on it.

**Comment by beffymaroo** [comment] 2018-06-15 21:49
@shadimoustafa Thanks for letting us know! I'm going to change the status to "Help Wanted," but you're welcome to reclaim it if you find time and no one else has grabbed it yet.

**Comment by dspitz716** [comment] 2018-06-28 04:57
hey @beffymaroo  I would love to take a crack at this if no one else is taking a look right now.

**Comment by negue** [comment] 2018-07-07 20:52
@dspitz716 sure go for it! :)

**Comment by beffymaroo** [comment] 2018-07-30 21:02
@dspitz716 Sorry I missed your earlier comment! I'm happy to see you were assigned it after that. Are you still working on this issue? Please update us when you have a moment. Thank you!

**Comment by dspitz716** [comment] 2018-07-30 21:12
Yup I am still working on it thanks!

**Comment by beffymaroo** [comment] 2018-08-08 19:30
@dspitz716 Great! Thanks for checking in.

**Comment by beffymaroo** [comment] 2018-08-31 01:16
@dspitz716 Checking again to see if you're still working on this issue. Please let us know when you have a moment. Thank you!

**Comment by negue** [comment] 2018-10-15 16:30
I guess this seems to be fixed? Can't reproduce on Mac Chrome/FIrefox/Safari

**Comment by dspitz716** [comment] 2018-10-15 17:00
Yes I could not reproduce this anymore either.

**Comment by paglias** [comment] 2018-10-15 17:59
Closing this, if it happens again I'll reopen it

**Closed as completed by paglias** 2018-10-15 17:59 UTC
Labels: priority: medium, help wanted, section: Equipment
