### ISSUE TITLE
Custom day end and dailies not working properly

### ISSUE THREAD

**Issue by motoyugota** [HabitRPG/habitica#1215] opened 2013-06-27 18:22 UTC
If I have a custom day end set to some time the next day (for example, 3am) and I check off a daily at 1am (or any time after midnight), it correctly counts it for that day, but the checkbox is still checked when the next day starts. This means that completing it that next day doesn't count for anything, but the streak doesn't reset and it doesn't count negative either.

This was working as recently as last week, I believe. I've just noticed it over the past few days as an issue.

**Comment by wc8** [comment] 2013-06-29 16:50
I believe this is a Duplicate of #647
Please follow up there.

**Closed as completed by wc8** 2013-06-29 16:50 UTC
