### ISSUE TITLE
checklist items can't be completed in (Record Yesterday's Dailies (RYA) screen

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#11340] opened 2019-09-02 03:58 UTC
Lorem Ipsum / @loremi (64d5d2fa-4ab1-4ff2-bc93-e46a18d44b25) writes:

"I'd like to report a "end of day popup checklist bug": When checking off checklists of dailies at the cron popup prompt, the items don't get checked off IN the popup – but I can see it gets checked off in the background. (By background I mean the popup darkens the rest of the screen; the actual darkened daily behind the popup is the one that gets the checkmark.)"

@paglias is this likely to be a similar issue to https://github.com/HabitRPG/habitica/issues/11336 / https://github.com/HabitRPG/habitica/commit/923bc9b28422584ea2064c5a6dd267b91cab2554 ?

**Comment by paglias** [comment] 2019-09-02 12:30
yeah it's the same thing, the issue is that checkboxes must have different ids or they won't work, not sure why it worked until now

**Comment by paglias** [comment] 2019-09-02 12:36
fixed in release

**Closed as completed** 2019-09-02 12:38 UTC
Labels: priority: important, help wanted, section: Task Page
