### ISSUE TITLE
Console errors in develop (Cannot read property 'maxMP') -- profile._statsComputed is undefined

### ISSUE THREAD

**Issue by khipkin** [HabitRPG/habitica#6969] opened 2016-03-27 17:02 UTC
I was working on another branch, and I noticed that there are console errors that didn't seem to be related to what I was doing.  So I checked out `develop`, got the most up-to-date changes, and restarted the server, and the console errors are still there!

```
angular.js:11594 TypeError: Cannot read property 'maxMP' of undefined
    at Object.mpDisplay (statServices.js:98)
    at $parseFunctionCall (angular.js:12332)
    at Object.expressionInputWatch (angular.js:12736)
    at Scope.$digest (angular.js:14218)
    at Scope.$apply (angular.js:14489)
    at bootstrapApply (angular.js:1449)
    at Object.invoke (angular.js:4182)
    at doBootstrap (angular.js:1447)
    at bootstrap (angular.js:1467)
    at angularInit (angular.js:1361)
```

It looks like [`+basicRow('mana', '{{statCalc.mpDisplay(profile)}}')` in basic-stats.jade](https://github.com/HabitRPG/habitrpg/blob/develop/website/views/shared/profiles/stats/basic-stats.jade#L4) is passing in `profile`, which is undefined.

**Comment by khipkin** [comment] 2016-03-27 17:09
Correction: `profile._statsComputed` is undefined.

**Comment by khipkin** [comment] 2016-03-27 17:38
It looks like the jade file is processed multiple times before [this line](https://github.com/HabitRPG/habitrpg/blob/b948fc031f8b5979c47d016715b8b7774af86973/common/script/index.js#L197) is executed, so `statCalc.mpDisplay(profile)` fails a few times before eventually succeeding.

**Comment by Alys** [comment] 2016-03-28 02:29
@khipkin Thank you for the investigation!

@paglias @crookedneighbor I don't know if this falls under something that will be / should be fixed by the API v3 rewrite, or fixed after it's finished?

**Comment by paglias** [comment] 2016-03-28 08:52
This can be fixed now

**Comment by Alys** [comment] 2016-03-28 08:55
@khipkin Would you like to work on this? If not, I'll mark it as "help welcome now" and advertise it in the Aspiring Coders guild.

**Comment by khipkin** [comment] 2016-03-28 15:40
@Alys this seems like an issue with the order of execution of different processes.  I wouldn't know where to even begin.

**Comment by Alys** [comment] 2016-03-29 03:39
@khipkin No worries. :) Thanks for letting us know!

**Comment by nnashwin** [comment] 2016-04-27 08:15
Hello!
I'd like to work on this issue if you guys are alright with it.

**Comment by Alys** [comment] 2016-04-28 08:19
@ttymed Please do! Thanks!

**Comment by khipkin** [comment] 2016-09-06 17:03
This might have been fixed by #7870 ?

**Comment by paglias** [comment] 2016-09-06 17:11
@khipkin I have to say I never reproduced these errors so I can't say if they're fixed or not. But if you can't see them anymore, we'll close this

**Comment by crookedneighbor** [comment] 2016-09-06 17:12
This code has also changed since it was reported. Reopen if you reproduce it again.

**Closed as completed by crookedneighbor** 2016-09-06 17:12 UTC
Labels: priority: minor, help wanted
