### ISSUE TITLE
Stealth Not Acting As Planned

### ISSUE THREAD

**Issue by deilann** [HabitRPG/habitica#5279] opened 2015-05-25 08:09 UTC
According to the DDT's Task Statistics, I have 98 Dailies. 36 of them are inactive today.

My Perception is 358. However, Stealth will allow me to avoid **55** Dailies.

**Reasons why this is not as planned:**

At max, one cast of Stealth should only allow me to skip half of my Dailies, or 49.

Furthermore, as Stealth now no longer counts inactive tasks, it really should only be allowing me to skip 50% of my _active_ tasks.
##

**Comment by TNychka** [comment] 2017-04-11 23:54
Looks like what's happening is the stealth attribute is calculated based on static stats. 
in 
```
user.stats.buffs.stealth +=  Math.ceil(diminishingReturns(user._statsComputed.per, user.tasksOrder.dailys.length * 0.64, 55));
```
 none of 
+ user._statsComputed.per
+ user.tasksOrder.dailys.length * 0.64
+ 55

will change between casts, thus each cast will avoid the same number of dailies increasing stealth stat linearly. 
Depending on intended behavior (Correct me if I'm wrong) stealth should avoid _up to half_ of the users' _active_ dailies with diminishing returns on each cast.
A suggested solution to this is to do 

```
Math.ceil(diminishingReturns(user._statsComputed.per, (user.tasksOrder.dailys.length * 0.5) - user.stats.buffs.stealth));
```
which will increase stealth up to (not sure if including, can tweak to fix) half with diminishing returns per cast. 

diminishingReturns for reference
```
function diminishingReturns (bonus, max, halfway) {
  if (!halfway) halfway = max / 2;
  return max * (bonus / (bonus + halfway));
}
```

**Comment by Alys** [comment] 2017-04-12 10:50
@TNychka I like that idea!

Although it would still count inactive Dailies in its calculations (user.tasksOrder.dailys.length gives the total number of all Dailies). We're part way through adding an `isDue` property to Dailies (https://github.com/HabitRPG/habitica/pull/8509), which, when completed, would make it easier for Stealth to count only due Dailies.

**Comment by guyguy2001** [comment] 2017-07-23 09:40
@Alys Can I work on it, now that isDue exists?

**Comment by Alys** [comment] 2017-07-23 10:41
@lemoness  Seeking your approval for the proposed fix:

Currently, when you cast Stealth, it protects you from a certain number of Dailies that can be up to about half the number of TOTAL Dailies you have. For a high-Per Rogue, two casts can hide all Dailies.

The proposed fix is to make Stealth less powerful by counting only the active Dailies and by making each cast have a smaller effect than the previous cast (on the same day).

Is that okay with you?

----

@TNychka Assuming this is approved, did you want to do the coding for it? If not, we can let guyguy2001 work on it.
@guyguy2001 Thanks for asking!

**Comment by TNychka** [comment] 2017-07-23 12:23
@Alys if @guyguy2001 would like to do this, thats fine by me!

**Comment by guyguy2001** [comment] 2017-07-23 18:39
So do I start working on it now, or do I need to wait for approval?

**Comment by TNychka** [comment] 2017-07-23 19:09
@guyguy2001 You're probably okay to start looking at it, but just wait for Alys or lemoness to confirm before committing or going too in depth. 
The code I referenced above is located in spells.js (habitica/website/common/script/content) around line 197, see what you can do with that.

**Comment by lemoness** [comment] 2017-07-24 23:15
I think that these fixes have promise! However, I would like us to test
them to make sure that they don't have a negative impact on retention -- I
could see there possibly being a case where users are casting Stealth to
make Habitica easier and less discouraging for themselves.

**Comment by Alys** [comment] 2017-07-24 23:56
@guyguy2001 Go ahead with this, thank you!

Unless another admin says otherwise, keep the old behaviour in the code as well. Use an if-else block for switching between the old and new behaviour. For now, the `if` condition could be just `true` (i.e., `if true do new behaviour else do old behaviour`). Later we can adjust that for A-B testing or just to be able to easily switch between the new and old behaviour for everyone while we're testing retention. Once we're sure which option is best, we'd delete the code for the other option. Note that as long as your PR is merged, you'll get contributor credit for it, even if we later delete the new behaviour.

**Comment by librarianmage** [comment] 2017-12-13 04:07
Note for future me: this is on hold until #9136 has been fixed.

**Comment by lemoness** [comment] 2017-12-13 21:40
I've added the "on hold" label.

**Comment by guyguy2001** [comment] 2018-03-16 20:26
I still need to add tests to this.
I will probably have time for it after next week (as I'll be entering the passover school-break), however until them I doubt I'll get to it. If anyone else wants to do tests, I'll give it to them. If not, I'll finish it then.

See #9751 for details if you are interested in doing the tests.

**Comment by veeeeeee** [comment] 2019-01-08 18:35
Removed help wanted tag bc on hold

**Comment by veeeeeee** [comment] 2020-10-27 17:01
Current behavior has not garnered further complaints, so we are closing this issue in favor of focusing on more immediate fixes.

**Closed as completed by veeeeeee** 2020-10-27 17:01 UTC
Labels: priority: minor, status: issue: on hold, section: Task Page
