### ISSUE TITLE
Editing Problems with Rewards

### ISSUE THREAD

**Issue by Ronwea** [HabitRPG/habitica#553] opened 2013-03-02 00:01 UTC
When I'm trying to edit my rewards I'll type into it and it will automatically exit out of it before I can make any changes. Sometimes if I'm quick enough I can change a digit or a letter but it's acting like a slippery pad of butter.

Help or fix?

Thanks!

**Comment by Pandoro** [comment] 2013-03-02 12:40
First of all sorry for the inconvenience! Maybe this could be related to #539  The description seems to fit this problem. I'm not sure about that though.

In fact I just tested this and I can confirm it. A fix would thus be, according to #539, that you first type the text somewhere and then copy/paste it into the field. I know this is not very nice, but as the other thread is listed as critical already, I am fairly sure that this will be taken care of sooner than later.  

Who assigned this as minor :x ? @lefnire what do you think about this case?

**Comment by lefnire** [comment] 2013-03-04 22:48
more i think of it, this nor #539 should be happening simply due to auto-persisting functionality. The editing text in input fields had never previously been an issue, and i think was fixed recently as a non-rewards tasks issue. So I think something else is causing this.

This is still a bug, just saying I don't think it's due to auto-persist / {dynamic binding}, just not to self & @MrConcept

**Comment by lefnire** [comment] 2013-03-05 20:33
something funky [here](https://github.com/lefnire/habitrpg/blob/master/views/app/tasks.html#L64), if I remove the that whole `{#if}` clause (and just include the section inside `{else}`, fixes. I'm currently hunting a stray missing `{/}` or something similar

**Comment by lefnire** [comment] 2013-03-05 22:09
fixed

**Closed as completed by lefnire** 2013-03-05 22:09 UTC
