### ISSUE TITLE
Reset/Update Password issue

### ISSUE THREAD

**Issue by jtanmay** [HabitRPG/habitica#7483] opened 2016-05-24 19:27 UTC
General Info
- UUID: d98d6428-a033-4d96-ab32-60679ad2d431
- Browser: Chrome / Firefox
- OS: Mac
### Description

Not able to change the password. 
I had forgot my password, so did the forgot password functionality. The reset was successful. Now as the password was system generated, I went ahead and tried updating to a password i remember. But getting errors. 'Yikes! An error occurred... "
#### Console Errors

Deprecation warning: moment().zone is deprecated, use moment().utcOffset instead. https://github.com/moment/moment/issues/1779
Arguments: 
Error
    at q.zone (https://habitica.com/app-9e4d2a8b.js:40:26438)
    at Object.u.authenticate (https://habitica.com/app-9e4d2a8b.js:44:7870)
    at Object.<anonymous> (https://habitica.com/app-9e4d2a8b.js:44:9020)
    at Object.i [as invoke](https://habitica.com/app-9e4d2a8b.js:5:16822)
    at Object.c [as $get](https://habitica.com/app-9e4d2a8b.js:5:15218)
    at Object.i [as invoke](https://habitica.com/app-9e4d2a8b.js:5:16822)
    at https://habitica.com/app-9e4d2a8b.js:5:14868
    at g (https://habitica.com/app-9e4d2a8b.js:5:16455)
    at Object.i [as invoke](https://habitica.com/app-9e4d2a8b.js:5:16789)
    at D.instance (https://habitica.com/app-9e4d2a8b.js:6:8436)
https://pixel.advertising.com/ups/50/sync?uid=5744a8253c6557ab&redir=true Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
https://e.nexac.com/e/googlegdn_sync.xgi?na_exid=CAESECnvNqQKX3NJuTgmKBVpfQw Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
7contentscript.js:36 CTFM highlighted text sent: 
https://habitica.com/api/v3/user/auth/update-password?userV=3 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
app-9e4d2a8b.js:43 ObjectresponseError @ app-9e4d2a8b.js:43
sh.908b832….html:1 Uncaught TypeError: (t.data || "").search is not a functionp.pmh @ sh.908b832….html:1
(index):1 Uncaught TypeError: C.indexOf is not a functionh.Widgets.Utilities.parseMessage @ Widgets.js?_=1464117605688:45h.Widgets.Utilities.handleMessage @ Widgets.js?_=1464117605688:45nrWrapper @ (index):1

**Comment by crookedneighbor** [comment] 2016-05-24 20:06
This is a duplicate of https://github.com/HabitRPG/habitrpg/issues/7423

We've fixed the issue in the code base and are doing a deploy soon.

**Closed as completed by crookedneighbor** 2016-05-24 20:06 UTC

**Comment by crookedneighbor** [comment] 2016-05-24 21:14
The fix is deployed now.
