### ISSUE TITLE
Negative XP points

### ISSUE THREAD

**Issue by ra100** [HabitRPG/habitica#720] opened 2013-03-25 07:24 UTC
This morning I refreshed HabitRPG and got tons of messages with negative XP and Coins (as if I've undone many quests) and I got with XP to -60 or so. But when I complete daily, habit... I counts new XP and adds it's value. But this way I've lost about 200 XP or so.
![Screenshot - 03252013 - 08:20:42 AM](https://f.cloud.github.com/assets/3185410/296905/f24f17ac-951c-11e2-943c-d622d5a5ce0c.png)

**Comment by lefnire** [comment] 2013-03-25 14:43
woa mama. upgraded to crit

**Comment by lefnire** [comment] 2013-03-25 23:15
i noticed your Opera issue, and looking at that screenshot - looks like you hit this particular issue with Opera as well? Can you access the error logs at all? (Chrome console, Firebug - not sure with Opera)

**Comment by ra100** [comment] 2013-03-25 23:57
exactly, on Opera 12.15 (linux x64), and in JS console is something like this: 
Updating, _1, due to, set, of, users.3f6b885f-c6fe-46ff-b800-14fd182b7111.habitIds
Updating, _2, due to, set, of, parties.b5e9a2ab-8fa4-4462-8b66-aac07bb0e822
IMfKVa-4X5K-hQB95t92hg.js:4840
Updating, _1, due to, set, of, users.3f6b885f-c6fe-46ff-b800-14fd182b7111
Updating, _4, due to, set, of, users.3f6b885f-c6fe-46ff-b800-14fd182b7111.dailyIds

you can open in with CTRL+SHIFT+I
and Error Console ins CTRL+SHIFT+O (there are too many errors, mostly CSS, I don't know what to look for)

**Comment by lefnire** [comment] 2013-03-26 00:08
all of what you listed is legit. But yowser, just downloaded opera to see - over 1000 errors, 90% caused by 3rd party libraries we're using (and extremely established ones too, like bootstrap). I know this sucks, but I _think_ for the time being you should probably stick to chrome or firefox until we get more stable. Try that for a few days and if this error still happens in one of those browsers, I'll revisit

**Comment by ra100** [comment] 2013-03-26 00:28
I get it, there are mor important thing s to do :) but  if I have some time, I'll try to understand those errors, and maybe find the solution, but probably not. And maybe Opera wll have WebKit core then :)

**Comment by ra100** [comment] 2013-03-26 07:23
I maybe found CSS solution, comment in https://github.com/lefnire/habitrpg/issues/721

**Comment by kriscrat** [comment] 2013-03-29 16:53
I have the same problem.  I used chrome, firefox, and internet explorer.  Logged out and back in.  ideas?

**Comment by kriscrat** [comment] 2013-03-29 17:17
![image](https://f.cloud.github.com/assets/4007169/318339/82dd0872-9894-11e2-9bba-fd6b24f0cc89.png)

**Comment by bernerbits** [comment] 2013-04-27 12:46
I get the same issue in Chrome. It's happened to me a few times; it seems to occur when switching computers.

**Comment by lefnire** [comment] 2013-05-19 14:14
let's follow this one up on #838 . That one's actually a dupe of this, but it has more info in the comments so we'll follow that thread

**Closed as completed by lefnire** 2013-05-19 14:14 UTC
