### ISSUE TITLE
If user has redundant party invite, can get kicked out of party attempting to clear it

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#12291] opened 2020-06-11 21:08 UTC
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)
### General Info
  * UUID: 9bc9d551-61d1-4820-ae3d-9bca2ce2e470

### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)

It may be possible in some circumstances for a user to accept a party invite and end up _leaving_ the party instead of joining it. It's not clear exactly how @beffymaroo tripped it, but one of her test accounts was a member of a party; still appeared to have an outstanding invite to that party; accepted it, and ended up with no party at all.

Looking at this code in the group join route 

https://github.com/HabitRPG/habitica/blob/develop/website/server/controllers/api-v3/groups.js#L549-L559

there's no guard rail for the situation where the invite might be spurious. We go ahead and have the user leave their current party, even if it and the one they're ostensibly trying to join are the same. Could it be that this part of the process went through, but the later database updates meant to add the user _to_ the party failed, leaving them with none at all?

**Comment by Alys** [comment] 2020-06-12 10:35
Confirmed with these steps:
1. Invite an account to your party.
2. Using that account, log in to the Habitica website and confirm that the invitation is there. Do NOT accept or reject the invitation.
3. Add the account to the party with a database update command that sets the account's `party._id` attribute to the party's group ID.
4. Reload the website while you're logged in to that account. Confirm that you're in the party and still have the invitation.
5. **Accept** the invitation (i.e., this is accepting an invitation to the party you are currently in).
6. **Observe that you are no longer in the party.**
7. You may see the error message "Group not found or you don't have access." You don't always see this. If you were looking at the party page when you accepted the invitation, then you won't see this error message. If you were looking at your tasks page, you will see it. (Regardless, it's not an important feature of the bug - the bug is that you're dumped out of the party.)

I followed those steps three times with the same result each time, so it's reproduceable.

The expected behaviour is that if the invitation is for the party you are currently in, you should NOT be removed from the party when you accept the invitation. 

This bug isn't something that can normally happen because when you join a party the invitation to it should be cleared, but other errors could result in this situation arising. I'd expect this to happen less often after database transactions are in place, so I don't know if we want to do a fix for it?

BTW if you follow those steps above but **reject** the invitation, you are **not** removed from the party. However if this bug condition happened to a regular player, I'd expect them to accept the invitation rather than reject it, if they recognised it as being for the party they wanted to be in.

In case it helps someone develop a fix (if a fix is desired), below is the invitation data and party data taken from the account of the user who was invited to the party.

```
"invitations": {
	"guilds": [],
	"party": {
		"id": "12345678-8050-4253-85ba-14eab6b19e72", // this is the group ID of the party
		"name": "Party Name",
		"inviter": "d904bd62-da08-416b-a816-ba797c9ee265" // User ID of the person who invited you
	},
	"parties": [
		{
			"_id": "5ee35360bba1a567405d1efe",
			"id": "12345678-8050-4253-85ba-14eab6b19e72", // this is the group ID of the party
			"name": "Party Name",
			"inviter": "d904bd62-da08-416b-a816-ba797c9ee265" // User ID of the person who invited you
		}
	]
},
"party": {
	"quest": {
		"progress": {
			"up": 0,
			"down": 0,
			"collectedItems": 0,
			"collect": {}
		},
		"RSVPNeeded": false
	},
	"order": "level",
	"orderAscending": "ascending",
	"_id": "12345678-8050-4253-85ba-14eab6b19e72" // this is the group ID of the party
},
```

**Comment by SabreCat** [comment] 2020-06-12 17:13
Thanks for the STR, @Alys! That should be enough to go on--changing from needs-investigation to help-wanted.

**Comment by JalanshMunshi** [comment] 2020-06-22 11:16
@Alys: Will it be okay if I start working on this issue? 
A fix that I could think of is that could we introduce a check before inviting a user to the party? The check will verify if the user is already a member of the party or not.

Another fix that I could think of is that we can see what happens when a user accepts the part and how can we change the code to avoid this bug.

**Comment by Alys** [comment] 2020-06-22 12:48
@JalanshMunshi You're welcome to start on it - thank you!

>  A fix that I could think of is that could we introduce a check before inviting a user to the party? The check will verify if the user is already a member of the party or not.

I think we already have that check, and I _think_ it works correctly. I'm pretty sure this bug creeps in after that point, and only happens in unusual circumstances.

> Another fix that I could think of is that we can see what happens when a user accepts the part and how can we change the code to avoid this bug.

That's probably the better approach to take. For example, when the user is trying to accept a party invitation, you could check if they're already in that same party, and if they are, just remove the invitation without doing anything else. But that's just one idea. :)

**Comment by JalanshMunshi** [comment] 2020-06-23 17:31
Thanks for the reply, @Alys !

As per my understanding, the API call, `url: '/groups/:groupId/join'`, gets executed when a user accepts the party invitation. Please point it out if I am committing a mistake here.

We can write some new code which will check if the current party of the user is the same as the party that the user is invited to. This code will be executed only if the user has been invited to a party. 

https://github.com/HabitRPG/habitica/blob/b2bb25152271c3b2c69835a7682328a532f449e4/website/server/controllers/api-v3/groups.js#L541-L548

We will get the user details for accessing the party that the user is currently a part of. If the current party and the invited party is same, then we will send a `BadRequest` stating that the user is already in the party! (Not entirely sure about the `BadRequest`. Can something else be done instead?)

We will insert the new logic inside the `if (inviterParty)` block. Please let me know if this approach looks good or not.

**Comment by JalanshMunshi** [comment] 2020-06-25 08:17
@Alys 

I implemented the above logic and checked it locally. The logic seems fine but the `BadRequest(res.t('alreadyAMemberOfTheParty'));` does not work. The alert says that `String 'alreadyAMemberOfTheParty' not found.`

I guess we will have to pre-include this error message somewhere. Where can we implement this? What do you suggest? 

Also, as an addendum to my previous comment, we will also have to remove the party invitation notification from the users's notification box.

**Comment by Alys** [comment] 2020-06-26 09:39
@JalanshMunshi Sorry we didn't reply earlier! This is sounding good so far, except that throwing a BadRequest error may not be the best way to handle it because I _think_ (I could be wrong) that the user would see that error message. Since this error condition wasn't caused by anything the user did wrong, and since the user can't fix it themself, it may be best to not show them an error message at all. Instead, when you've identified that the invitation is for the same party that they're currently in, you could remove the invitation from the user's account without notifying them (and also without notifying the person who sent the invitation).

How does that sound? Do you think it may be possible?

**Comment by JalanshMunshi** [comment] 2020-06-30 18:05
Thanks for the input, @Alys ! That approach is better than throwing a BadRequest. Yes, the user will see that error and the user did not do anything wrong in this case; hence it would be inappropriate to throw a BadRequest.

As suggested, I checked if the user is already a member of the party or not, and the line `if (userPreviousParty) await userPreviousParty.leave(user)` will only be executed when the user was previously in a different party. This works on my local environment and the repro steps that you mentioned in this thread are avoided. The user still remains a member of the party. Please have a look at it and let me know if we need to modify the approach.

A test case that I could identify was to send multiple invites to the user and see if the same result is achieved or not. We can do it by creating a duplicate of the below-mentioned test case and sending another invite after the first invite.

https://github.com/HabitRPG/habitica/blob/b9d42bf0bc2e12ca971eedf21e3e9f3e6ed90c67/test/api/v3/integration/groups/POST-groups_groupId_join.test.js#L200-L204

What do you think?

**Closed as completed** 2020-07-13 14:00 UTC
Labels: priority: minor, status: issue: in progress, section: Party Page
