### ISSUE TITLE
Inventory / Quick Inventory should show new items immediately

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica#11174] opened 2019-05-16 13:38 UTC
> Bug: Received a food item from completing a task, but it does not show up in the quick inventory on /inventory/stable until refreshing the page.

From Report a Bug. Not confirmed. I would expect the quick inventory to update, though. Will check in whether a sync updates it.

_Edit by Alys 2019-07-27:_

This also affects the Inventory > Items page, and applies to Food, Eggs, and Hatching Potions.

**When you gain an item from a drop, if you look on the Inventory page or in either of the Quick Inventory windows, you don't see that item. You need to click the sync button before it appears.**

**The desired behaviour is that as soon as you've earned an item from a drop, it should appear in your Inventory. A sync should not be needed.**

This bug causes people to think that they weren't actually given the item(s) advertised in the drop notifications so they feel cheated.

**Comment by Alys** [comment] 2019-07-27 04:15
Verified. A sync will fix it; reloading/refreshing isn't needed. It also affects the Inventory page. This causes people to think that they weren't actually given the item(s) advertised in the drop notifications so they report it as a bug and feel cheated.

To make the desired fix clear to contributors, I'm about to rename this issue to "Inventory / Quick Inventory should show new items immediately" and I'll move my comments to the top post.

**Comment by paglias** [comment] 2019-07-28 17:39
Is this only affecting drops or any new item (for example if you bought it?) i thought I knew what was going on (new items not being set correctly in vue) but this doesn't seem the case and will need more investigation

**Comment by Alys** [comment] 2019-07-30 09:40
This issue doesn't occur when buying equipment. We have https://github.com/HabitRPG/habitica/issues/10920 ("when buying new equipment, item does not disappear from Market or Seasonal Shop") and I've just tested to confirm that issue is still happening. I.e., when you buy an equipment piece, it **does** appear immediately in your inventory (but doesn't disappear from the shop).

This issue also doesn't occur when buying eggs. I bought an Axolotl egg (I previously owned none of them) and when I switched to my Inventory the egg was there. 

No sync needed for either of those tests.

**Comment by paglias** [comment] 2019-07-30 17:16
Thanks for the investigation @Alys! I'm going to be away for the first 10 days of August but if no one has fixed it by then I'll prioritize this one

**Comment by Xaz16** [comment] 2019-09-14 08:04
@Alys can I take this one?

**Comment by paglias** [comment] 2019-09-14 08:07
@Xaz16 sure!

**Comment by SabreCat** [comment] 2019-11-01 17:34
@Xaz16 Are you still at work on this?

EDIT: Looks like Xaz16 grabbed a bunch of issues but hasn't been around in the last month--I'll open this one up for further help as well.

**Comment by Xaz16** [comment] 2019-11-01 21:54
@SabreCat yes, i'm still on this. Sorry, for delay guys, I'm focused on other issues and couple of my pull requests...

**Comment by Xaz16** [comment] 2019-12-11 19:52
I finally on this issue... and I can't reproduce it

My steps for reproduce:

1. remove all foods, potions, eggs from user (through mongo)
2. buy enchanted armoire until drop is food/potion/egg

And after such steps I saw it in quick inventory. Can we move it on qa?
@paglias  @Alys

**Comment by Alys** [comment] 2019-12-12 12:02
@Xaz16 I don't recall any recent reports of items obtained from the Armoire not appearing immediately. I don't think this issue relates to the Armoire.
If you'd like to keep looking into it, try using a task to reproduce it. You can speed up testing by increasing your Perception with buffs or direct database updates.

**Comment by paglias** [comment] 2019-12-12 14:19
I think this should happen wirh Gear Irena that you don't own and have
never owned before

Il Gio 12 Dic 2019, 13:02 Alys <notifications@github.com> ha scritto:

**Comment by shanaqui** [comment] 2019-12-12 14:29
@paglias I think gear is irrelevant here since it doesn't show in the quick inventory anyway (only foods, potions and eggs do, because they're the only ones you can sell)? I think they were just using the Armoire to test because it drops food as well.

**Comment by paglias** [comment] 2019-12-12 15:57
@shanaqui you're right, I got confused with another issue :)

**Comment by merwok** [comment] 2019-12-12 21:43
The issue that I’ve seen is not with armoire, but rather food or potions obtained with task combos or daily streaks that don’t appear when going to stable screen (android or ios).

**Comment by Xaz16** [comment] 2019-12-13 11:22
> @Xaz16 I don't recall any recent reports of items obtained from the Armoire not appearing immediately. I don't think this issue relates to the Armoire.
> If you'd like to keep looking into it, try using a task to reproduce it. You can speed up testing by increasing your Perception with buffs or direct database updates.

Ok, I will try to reproduce it in this way

**Comment by Xaz16** [comment] 2019-12-29 16:29
Hi guys
What about this one: I noticed that we have some issues with vue state updates, due to splitting common and client codebase we miss that some of complex object like user.items.gear.owned have assigned without updates from vue reactivity.

I created PR to resolve such issues: https://github.com/HabitRPG/habitica/pull/11637
And I suggest to retest such issues after merging it

**Comment by Alys** [comment] 2019-12-30 05:12
@Xaz16 Thanks! I've put this on hold until https://github.com/HabitRPG/habitica/pull/11637 is closed and then we can test to see if it's fixed.

I've also marked this as "status: needs reply" since that label is used for periodic reviews. Anyone reviewing it can ping me for a reply if needed. :)

**Comment by paglias** [comment] 2020-01-14 12:00
Fixed in #11637

**Closed as completed by paglias** 2020-01-14 12:00 UTC
Labels: priority: medium, status: issue: on hold, section: Items, status: needs reply
