### ISSUE TITLE
"Pets Found" of Party members are the same as mine

### ISSUE THREAD

**Issue by filkaris** [HabitRPG/habitica#1943] opened 2013-11-28 16:20 UTC
All the party members display that they have 15 pets, same as me, even the guys that are lvl 1 and lvl 2. 

So I know for a fact it's inaccurate.

It also did the same yesterday, when I had 13 pets.

**Comment by SabreCat** [comment] 2013-11-28 17:00
Duplicate of #1936. Been fixed in the code, but might not have deployed to the site yet.

**Closed as completed by SabreCat** 2013-11-28 17:00 UTC

**Comment by filkaris** [comment] 2013-11-28 17:06
You're right! Sorry for not searching :innocent:
