### ISSUE TITLE
Rewards Column Occasionally Vanishes

### ISSUE THREAD

**Issue by bauerbach** [HabitRPG/habitica#11011] opened 2019-02-19 15:29 UTC
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)
### General Info
  * UUID: 
  * Browser: Firefox (it happens on Chrome as well).
  * OS: Windows 10.

### Description
[//]: # @Alys asked me to post this issue in GitHub.
 On very rare occasions, my entire Rewards column vanishes and I have to refresh the page to get it back.  

Screenshot: 

![Screenshot](https://i.postimg.cc/GmVF3Z1H/Untitled.png) 

#### Console Errors
[//]: TypeError: "a" is undefined.

**Comment by paglias** [comment] 2019-02-19 17:25
Thanks for the console log @bauerbach ! I think this is a duplicate of https://github.com/HabitRPG/habitica/issues/10134. If it happens again coudl you click on `inAppRewards.js` and post a screenshot of what appears (it might take a few seconds for it to load correctly)

**Comment by bauerbach** [comment] 2019-02-27 17:56
This is what appears in inAppRewards.js (the bug happened again today):

[![screenshot.png](https://i.postimg.cc/ydPQLVzF/screenshot.png)](https://postimg.cc/k62v4PG4)

**Comment by bauerbach** [comment] 2019-02-27 17:57
Sorry, I was just curious about the permissions needed for closing an issue! I won't do it again unless an issue REALLY needs to be closed, I promise!

**Comment by beffymaroo** [comment] 2019-02-28 19:50
@bauerbach Please do not close any issues. Habitica staff will make that decision. Thank you.

**Comment by paglias** [comment] 2019-04-01 12:48
This should be fixed now with https://github.com/HabitRPG/habitica/pull/11031. @bauerbach if it happens again after Friday let us know!

**Closed as completed by paglias** 2019-04-01 12:48 UTC
