### ISSUE TITLE
Constancy

### ISSUE THREAD

**Issue by Mihakuu** [HabitRPG/habitica#1434] opened 2013-09-05 16:03 UTC
Low priority but there is constancy errors with number formats.  
![constancy](https://f.cloud.github.com/assets/3769301/1089480/9781601a-1644-11e3-9e57-21c5033fb93f.PNG)

**Comment by paglias** [comment] 2013-09-18 17:50
Duplicate of #1358

**Closed as completed by paglias** 2013-09-18 17:50 UTC
