### ISSUE TITLE
[API v3]: Party page displays the button "Start a Quest" although the party is already on a quest

### ISSUE THREAD

**Issue by Wariannem** [HabitRPG/habitica#7328] opened 2016-05-17 14:45 UTC
General Info
- UUID: a1f425bb-1fa4-4fcc-93d7-56737a8edfe2
- Browser: Chrome (Version 50.0.2661.94 (64-bit))
- OS: Mac El Capitan
### Description

The green button "Start a Quest" is displayed on the party page while the party is on a quest. Clicking on it opens the quest inventory and after picking a quest and clicking to send the invite, the notification "Your party already on a quest [...] Try again when the quest has ended.“ appears.
#### Console Errors

None

**Comment by paglias** [comment] 2016-05-17 14:57
Duplicate of #7266

**Closed as completed by paglias** 2016-05-17 14:57 UTC
