### ISSUE TITLE
Challenge out of sync remove button deleted almost all tasks unrelated to challenge / manually added

### ISSUE THREAD

**Issue by Nayelianne** [HabitRPG/habitica#4466] opened 2015-01-02 03:44 UTC
I got a little notice on a daily task from a challenge saying it was out of sync, and that the **challenge had ended**. When I clicked to edit that task, it was asking whether I wanted to keep it or delete it. **I went with delete, and then... pretty much all my tasks that I had manually added (and had nothing to do with the challenge) disappeared at once**. A ctrl+f5 didn't fix the problem. Did I seriously misread something here or is it a big bad bug? ): I had SO many tasks and it's very disheartening to lose my streaks and have to add everything again.

This was more or less how my tasks looked like (though it's an outdated screenshot): 
![image](https://cloud.githubusercontent.com/assets/9331429/5594053/a4dabcce-921d-11e4-81e3-4032099195ba.png)

This is how it looks now ;-; 
![image](https://cloud.githubusercontent.com/assets/9331429/5594067/f780d372-921e-11e4-944a-04d2942fdec4.png)

**Apparently everything (dailies, to-dos, habits) was deleted in one go except for a few tasks that were from a different challenge.**

User ID: 1448f1e9-7b17-45cd-940c-741f84a3d78d
Ended challenge that caused it all was from the Kotoba Miners Guild ( b9424e99-ee46-4c96-8633-dbdf375160e7 )
Operational System: Windows 7 64 bits.
Browser + Version: Chrome 39.0.2171.95 m
**Console Errors displayed on the page (after refresh, hadn't looked before :disappointed: ):**
![image](https://cloud.githubusercontent.com/assets/9331429/5594070/17868dce-921f-11e4-80da-94b53bfd3942.png)
Other details: 
- Tried pressing "clear" on the tags to see if I had any tags selected and tasks would came back, nothing changed.
- Apparently I can still create tasks normally, if that's at all relevant.

Is there any way to restore the tasks?

**Comment by Alys** [comment] 2015-01-02 03:58
@Nayelianne : I believe we can probably restore your tasks from a recent backup but I still need to look into that.

FYI @lefnire @paglias - this is extremely worrying!

@Nayelianne: I've checked your account in the database and, yes, almost all your tasks have been deleted. There are two Habits and one Daily remaining, as shown in your screenshot, plus a few completed To-Dos (no uncompleted). I am VERY sorry this has happened to you. I am going to look into the backup situation now, but working with database backups is slow because they are very large, so it could be a few hours before I can get back to you. The good news is that I have a month-old copy of the database on my local machine, and it's showing several tasks for you, for each kind of task, so I'm pretty confident that I can get more recent data for you from a more recent backup (hopefully just 12 or 24 hours old). I'm not sure yet about being able to import your data back into your account (I think it should be possible) but at worst I can tell you what your tasks and streaks etc were.

We will also look into working out why this happened, but for now I'm focusing on retrieving your data.

This would be a bug. You did not misunderstand the message about the challenge tasks.

**Comment by Alys** [comment] 2015-01-02 03:59
@Nayelianne : I forgot to say: this would be a bug. You did not misunderstand the message about the challenge tasks.

**Comment by Alys** [comment] 2015-01-02 04:07
@Nayelianne : The most recent database backup was four hours ago. Did your problem start more recently than that?

**Comment by Alys** [comment] 2015-01-02 06:33
@Nayelianne : I've downloaded the backup I mentioned in my previous comment and it seems to have much the same tasks as in your screenshot, so it looks like your problem did occur after that backup was made.

I'm going to do some test runs of importing the data into some test accounts and if that goes well, I'll import it into yours. I won't overwrite any tasks that are still there, so you might end up with a couple of duplicates.

**Comment by Alys** [comment] 2015-01-02 07:18
@Nayelianne : You should now be able to see all the tasks that were in your account at the time that our most recent database backup was made (about 7 hours ago). Please check your tasks and let me know if they look okay.

The challenge tasks will still be there. Please go through the same process as before to remove them. I would be very interested to see if the same problem happens again. If it does happen - do not worry! Restoring your tasks again will be MUCH faster because I have a restoration script all ready to go. :)

**Comment by Nayelianne** [comment] 2015-01-02 22:42
@Alys Thank you SO much for the speedy support and for restoring the tasks. ;_; **It seems to have restored some pretty old ones I had completed or deleted in december, but I'm super happy to not have to re-add everything.**

Regarding reproducing the bug,  **I did have one "Broken challgenge link" that had been removed from the same challenge (and I had deleted it from my tasks in december), and I managed to remove that one again without problems at least.**

The rest of the challenge tasks, however, are no longer giving the "broken challenge link" message, nor seem to be editable/deletable. When I went to my Challenge page, it shows as if I'm not participating in any challenges either.

![image](https://cloud.githubusercontent.com/assets/9331429/5600280/f52465e0-92bd-11e4-8597-ab2ff03f908d.png)

![image](https://cloud.githubusercontent.com/assets/9331429/5600292/608a6a82-92be-11e4-9ebb-c3368be0c009.png)

xD So I guess they're stuck now?

**Comment by Alys** [comment] 2015-01-02 22:46
_"restored some pretty old ones I had completed or deleted in december"_ - That's extremely odd because the tasks I restored were definitely taken from a backup made just four hours before you reported the error. FYI @lefnire, @paglias - maybe this is something else weird happening with this account?

For the challenge tasks that you want to delete, tick one of them off as if you had accomplished it, and the megaphone should become broken. This is common for completed challenges. For more information about that, see "Deleting a Challenge Task" in the wiki's [Challenges](http://habitrpg.wikia.com/wiki/Challenges#Deleting_a_Challenge_Task) page.

**Comment by Nayelianne** [comment] 2015-01-02 23:05
It did seem a bit odd considering you said it a recent backup :confused:
Ticking each challenge and refreshing the page as you said seems to have made the notice show.

![image](https://cloud.githubusercontent.com/assets/9331429/5600428/e6a8f7d0-92c0-11e4-9097-3408c22b06c5.png)
**I wonder if it's counted "orphan tasks" as everything that doesn't fall into a challenge rather than just the ones from that specific challenge? It'd explain why just the tasks from another challenge were kept and all the manual ones disappeared?**

For the sake of bug reproduction, **I risked pressing the "Remove them" button again, and nothing broke this time :relieved:**

**The tasks from challenges that haven't ended were still stuck so I tried entering the challenges again but it simply duplicated the challenges, and when leaving the challenge it only removed the duplicates. Stubborn as I am I did it again and this time it actually removed them properly though :heart:**

Thank you for all the help. :)

**Comment by Alys** [comment] 2015-01-02 23:11
It certainly should not be counting non-challenge tasks as "orphan tasks" but it does look like it did originally. This is one of the things we will have to look into. That duplication of challenge tasks and then the extra step you had to take to remove them also should definitely not have happened.

Thank you very much for providing these extra details! They might help us work out what went wrong.

i'm going to leave this issue open so that we can investigate the cause of it. I'm also about to edit your comments to add bold highlighting to the ones that I think are most important, so that they stand out for us when we're investigating. I won't be changing your comments in any other way!

**Comment by Nayelianne** [comment] 2015-01-02 23:18
No worries.
c: Let me know if I can do anything else to help.  I really appreciate the thoughtful replies and the speedy help. :heart: Just made my love for habitRPG grow.

**Comment by jdrapic** [comment] 2015-06-24 01:23
Hello, I've had the exact same thing happen to me this afternoon. Would it be possible to roll back my account a few hours? Thanks in advance for any help you can give. (If it helps, the task I was deleting at the time was something like "Defeat all the monsters of the day".) 2524a616-4a06-433f-81c2-4cd0a8f2df20

**Comment by Alys** [comment] 2015-06-24 01:38
@jdrapic yes, we will definitely do that for you. Can you tell me how many hours ago your tasks disappeared? That will help me get the best database backup. Note that it's helpful if you tell me how many hours ago, rather than a specific time, because timezones make specific times difficult to deal with.

Also, can you please click the "clear" button next to your tags even if it looks like no tags are selected, and ensure that there's no text in the new search form (just above the Rewards column), in case the problem is that your tasks are merely hidden.

**Comment by Alys** [comment] 2015-06-24 01:40
Also, @jdrapic can you please click the "clear" button next to your tags even if it looks like no tags are selected, and ensure that there's no text in the new search form (just above the Rewards column), in case the problem is that your tasks are merely hidden.

**Comment by jdrapic** [comment] 2015-06-24 01:46
I believe the tasks have been gone about 2 hours, give or take.

Ah sorry, I should have mentioned I did the trouble-shooting before posting haha. Clearing the tasks and search, hard refreshing, and logging out and back in had no effect. =)

**Comment by Alys** [comment] 2015-06-24 01:54
@jdrapic There was a backup made two hours and fifty minutes ago. Is that likely to have your tasks? If not, I can use a backup made fifteen hours ago. The reason I'm asking is that it takes at least two hours to download the backup (it's huge!) and then up to three hours to import it into my local database server, and then some additional time to extract and restore your data - none of which I mind doing since you should not have been hit by this bug, but if the first backup I choose doesn't have your tasks, I probably won't be able to get them restored for many more hours. Let me know which backup you'd like me to try first, and I'll start downloading it as soon as I hear from you.

**Comment by Alys** [comment] 2015-06-24 01:57
@jdrapic Argh, sorry, ignore that. The backup was actually made two hours ago (did I mention timezones are annoying?). I'll go for the one made fourteen hours ago. I hope you won't have lost too much progress. :( 

I recommend that you make yourself [Rest in the Inn](http://habitrpg.wikia.com/wiki/Rest_in_the_Inn) now so that when your Dailies return, you won't take damage from them if you happen to be asleep at the time.

**Comment by jdrapic** [comment] 2015-06-24 01:58
Thanks so much. =) I'll go ahead and take your advice and check in then. You've been amazing!

**Comment by Alys** [comment] 2015-06-24 09:06
@jdrapic I've restored your Habits, Dailies, To-Dos, and Rewards from that backup. Please tell me if anything isn't right with them or any other part of your account!

**Comment by jdrapic** [comment] 2015-06-24 21:40
Everything looks right to me. You've been absolutely fantastic, thank you
so much!

**Comment by Alys** [comment] 2015-07-26 11:30
I'm closing this in the hope that #5504 has fixed it - I'm quite confident but it can be reopened if I'm proved wrong. :)

**Closed as completed by Alys** 2015-07-26 11:30 UTC
Labels: section: Challenges, status: issue: needs investigation
