### ISSUE TITLE
"Incorrect Password" message when trying to log in after site upgrade

### ISSUE THREAD

**Issue by poopstick** [HabitRPG/habitica#1461] opened 2013-09-07 08:38 UTC
When the upgrade happened, I was on my laptop. I was logged out and had to sign back in. I did that, and I remain logged in on my laptop's browser.

When I got back home to my desktop, I refreshed my open habitrpg tab and it prompted me to log in. I got "incorrect password". The laptop was still working, so I reset my password from inside my account and tried again with the new password. "Incorrect Password"

I have cleared the browser cache, and tried Firefox (am using Chrome), but can still not log into the site on my desktop PC.

I'm really worried that the next time I have to log in on the laptop, that I'll be locked out forever.

Username is SgtScient

**Comment by paglias** [comment] 2013-09-07 08:39
Are you using 1pass?

**Comment by poopstick** [comment] 2013-09-07 08:42
No, I am not.

**Comment by lefnire** [comment] 2013-09-07 18:22
dupe of #1460, let's follow up there. This is our most crit bug at present

**Closed as completed by lefnire** 2013-09-07 18:22 UTC
