### ISSUE TITLE
Stuck on modal on mobile browser: User Profile / Stats / Achievements has no close button

### ISSUE THREAD

**Issue by cvuorinen** [HabitRPG/habitica#12182] opened 2020-05-09 16:26 UTC
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)
### General Info
  * Browser: Chrome
  * OS: Android

### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)
On mobile browser opening a user profile modal leaves user stuck there with no way to close it. The modal is so big that there's no room for tapping outside, there's no close button, there's no esc key on mobile, and using native back button just navigates the page behind the modal without closing it. 

For example the Guild invite modal has a X button in top right corner for closing the modal. Same thing could be used in the profile modal too? IMO it's good UX even on desktop to have a dedicated close button.

**Comment by cvuorinen** [comment] 2020-05-09 16:29
And the layout of top part of the profile modal is also quite broken on mobile, but I guess that's a separate issue. Anyway, I can make a PR for this if you think it's a good idea.

**Comment by paglias** [comment] 2020-05-09 17:38
Thanks for the report, pinging @Tressley in case we have something planned for the mobile website

**Comment by Alys** [comment] 2020-05-10 02:21
Confirmed on Firefox on Android.

There's also no close button on the website on a PC - you have to hit "ESC" which is good for people who prefer keyboard navigation, less convenient for those who prefer mouse.

The User Profile > Stats / Achievements screen has the same issue. I'll add that to the issue title so we don't forget it.

Perhaps adding a "x" icon in the top right corner would be a suitable workaround for now? That's what's done for User Profile > Backgrounds.

**Comment by Tressley** [comment] 2020-05-11 13:53
Unfortunately, we don't have a much time to focus to the mobile web experience at the moment, but we do have plans to make improvements in the future.

As for web in general, the default modal component should have a close icon as well as ESC to close. We'll probably need to refactor modals and then properly apply it where necessary. There are exceptions though -- task modals use a "cancel" button as the close option, Record Yesterday's Activity requires the user to click "Start my new day!", choosing a class has an opt out option instead of closing out of the modal.

**Comment by Alys** [comment] 2020-05-12 00:12
If there's no objections in a couple of days, I'll mark this as help wanted for adding the same close icon that User Profile > Backgrounds has (the x in the top right corner). That seems to be a decent way of achieving the desired behaviour below I think, keeping consistency with similar modals, and it would be an easy workaround until the refactoring is done.

> As for web in general, the default modal component should have a close icon as well as ESC to close.

**Comment by cvuorinen** [comment] 2020-05-12 11:00
@Alys as I said already in previous comment "I can make a PR for this if you think it's a good idea."

**Comment by Alys** [comment] 2020-05-12 11:17
@cvuorinen Ha yes, good point, you did say that! Thanks for the reminder! If there's no objections in a couple of days I'll mark it as in progress for you and post here when I've done that. Thank you!

**Comment by veeeeeee** [comment] 2020-05-12 17:00
Ok to move forward on this, @cvuorinen! Thanks :)

**Closed as completed** 2020-05-22 15:48 UTC
Labels: priority: medium, status: issue: in progress, type: medium level coding, section: Achievements/Popups/Notifications
