### ISSUE TITLE
"not participating" search/filter checkbox doesn't work in Discover Challenges page

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#13025] opened 2021-02-07 06:48 UTC
On the [Discover Challenges](https://habitica.com/challenges/findChallenges) page, if you tick the "Not Participating" checkbox (in the Role section of the filters), you see Challenges that you are participating in.

The expected behaviour is that you see only Challenges that aren't currently joined by you.

The same occurs if you tick both "Not Participating" and "Not Owned" so anyone fixing this bug should check that the fix works for that use case too.

_Thanks to @LindyBlues for reporting this!_

**Comment by ceckleder** [comment] 2021-02-08 05:59
Hi 👋 ,

I would like to work on this issue. I checked and I could reproduce the erroneous behaviour. 

Christina

**Comment by Alys** [comment] 2021-02-09 06:27
@ceckleder Thank you! Please go ahead and post here if you have questions!

**Comment by ceckleder** [comment] 2021-02-09 14:00
Hi @Alys,

thanks for letting me help out. I analyzed the problem enough to be quite confused.
1.) The filters for myChallenges do behave weirdly too. The sidebar has Role, Membership, and Ownership. The checkboxes for Role and Membership are not independent if one is clicked the other correspondent one is marked as well.
2.) The API does have a member and owner parameter for the /challenges/user call but it does not have a role parameter.
3.) The sidebar for finding challenges has filters for role and ownership but lacks membership.
![Screen Shot 2021-02-09 at 14 30 19](https://user-images.githubusercontent.com/9212216/107374103-87025a00-6ae7-11eb-94fb-95fc8eb79010.png)


Could you please explain the difference between role and membership? One other thought that crossed my mind was if the options should be displayed as checkboxes because it feels wrong and leads to weird code.

**Comment by Alys** [comment] 2021-02-10 08:42
@ceckleder I'm not actually sure about this myself. Excellent questions! I'll leave this for Habitica's staff to answer. :)

**Comment by saraolson** [comment] 2021-02-18 17:25
Following up after team review: we don't know where role came from. It can be taken out, and the 'Membership' section should be present on both My Challenges and Discover Challenges views

**Comment by ceckleder** [comment] 2021-02-22 09:23
@saraolson thank you for the update. I reworked the ui yesterday to match it to the new requirements. I found something that I would like to improve.
Currently the member parameter in the API is a string and setting it true will return challenges where the user is a member. On not sending anything or sending false the server will return all challenges that belong to the same group as the user including the ones that the user is a member. To compensate this the frontend does additional filtering.
I would like to move the filtering to the backend and like to adapt the API. I suggest to change the parameter to have to possible values 'member' and 'not_member'. 
The response would be the following:
* member=member all challenges the user is a member
* member=not_member all challenges where the user is not a member but are listed in the member's group
* no member parameter all challenges that are listed in the member's group independent if the user is a member or not

I was also wondering about the filters for the myChallenges tab. I am worried that selecting challenges that the user is not a member will lead to a strange user experience. In that case the tab's name is still my challenges but the content would be the same as on the Discover Challenges tab. My suggestion is to not have the membership filter in the my challenges tab. I personally do not use the challenges that much so I might be missing something here.

I have one other question that is about the local setup. Is there a way to seed the database with test data? I created a small set manually but It would be nice to have a larger set.

**Comment by Alys** [comment] 2021-02-23 04:17
@ceckleder The myChallenges tab is designed to show both challenges that the player is participating in and the ones that they created (i.e., where they are the `leader`), with the optional filters being used to limit them further. That's behaviour we want to keep because there's good use cases for running challenges but not participating in them.

For your suggestions about changing the parameters in the API, it sounds like it may be a "breaking change". That's where a change to an API route causes any existing third-party tools to no longer work the same way they did before. In rare cases a breaking change is essential enough to be worth this but in general it's best to avoid it whenever possible so that the Comrades don't have to do urgent fixes to repair their tools. 

Speaking for myself (not an official staff/moderator opinion), I wouldn't see a problem with the API having extra parameters for filtering but I think it would need to be done as a non-breaking change. You're welcome to ask here if you'd like clarification about this!

Something else to keep in mind for the website may be responsiveness. If a single API route is used to load all appropriate challenges (e.g., both owned and participating) and then client-side filtering is used, the filter results are likely to be displayed immediately. If filtering was solely done with the API, then every time you adjusted the filter settings, you'd need to wait for new data to be loaded from the database. I'm not necessarily saying that would be bad, just that it's one consideration! :)

For your local install, there's currently no way to set up a lot of data without doing it yourself with manual website actions or with local API commands. We did have a dataset in the far past, but it became outdated as changes were made to the API.

**Comment by ceckleder** [comment] 2021-02-23 11:54
@Alys thanks a lot for the update. In that case I think it is better to keep the api stable and the additional filtering in the frontend. 
Regarding the responsiveness, my impression was that every filter change does indeed result in an api call. That's why I thought that it would be cleaner to handle the case in the backend. Maybe it's also easier to see if what can be improved in the PR.

**Comment by lizapritchard** [comment] 2021-04-18 20:36
Hi @saraolson, I was looking into this issue and I was wondering if "Role" was intended to have similar behavior to the Guilds screen, where the options are "Guild Leader" or "Member". I think the mistake may have been in making the options identical to the membership options, not in the presence of a role filter. The following screenshots show the filters on the guilds and challenges screens respectively. 
<img width="221" alt="Screen Shot 2021-04-18 at 4 35 37 PM" src="https://user-images.githubusercontent.com/49509154/115160061-361d5d80-a064-11eb-8357-28974bcea324.png">
<img width="203" alt="Screen Shot 2021-04-18 at 4 36 10 PM" src="https://user-images.githubusercontent.com/49509154/115160063-39184e00-a064-11eb-869e-3909e00ff600.png">

**Comment by saraolson** [comment] 2021-04-19 12:48
@lizapritchard if that's the case I still think it is the right move to take it out from Challenges, as that filter's rough equivalent in My Challenges screen is already represented in the 'Ownership: Owned/Not Owned'

This wording seems much clearer in the context of Challenges, so I think it's beneficial to have the different filters that are customized to the features themselves than simply duplicating wording for consistency sake.

**Closed as completed** 2021-05-28 21:57 UTC
Labels: section: Challenges, priority: medium, status: issue: in progress, type: medium level coding
