### ISSUE TITLE
Challenge Tags are not automatically associated with Challenge Tasks when creating new challenges

### ISSUE THREAD

**Issue by cTheDragons** [HabitRPG/habitica#7449] opened 2016-05-23 18:20 UTC
### Description

When you create new challenge the tasks that appear in the your own, that is the challenge owner's, task list due to the challenge are not automatically associated with the challenge tag.

The tasks themselves are still connected to the challenge are marked as challenge tasks. They are still removed automatically if you choose to remove the tasks when leaving or if the challenge is finished.
## What to do if this happens to you:

This occurs only for the challenge creator when they first create a challenge - their own copies of the challenge tasks are not associated with the challenge tag. The creator can be certain that when other players join the challenge, those players will find that the tag works correctly.

The challenge creator can work around this problem by leaving their own challenge (they'll still remain as the owner!), choosing to delete the challenge tasks. They can then re-join the challenge and they'll find that the tag will then work for them.

**Comment by makkoi** [comment] 2016-05-23 18:34
I am also experiencing this error. 

user ID: b3e66733-ab6f-432f-a052-6fa64585da5a
Browser: Google Chrome Version 50.0.2661.102 (64-bit)
OS: Mac OS X Version 10.9.5

**Comment by cTheDragons** [comment] 2016-05-24 05:25
Should note if you are joining a challenge the tags appear to work correctly.

**Comment by Altariel3** [comment] 2016-06-01 03:20
I am also experiencing this error for challenges that I joined, that I don't own.  If a task is added after I joined the challenge than the challenge tag isn't associated with the task.

user ID: be317a32-c027-4032-bbd5-25ccb21eb912
Browser: Google Chrome Version 50.0.2661.102 m
OS: Windows 10, 64-bit

**Comment by kawunngg** [comment] 2016-06-01 20:08
same thing for me: in all challenges i create, the tags aren't connected to the tasks. this only happens in my own challenges. if i leave the challenge and join again, they are connected again. (tried once). challenges by other people seem to behave normal.

ce935e7f-00e6-44bc-a44a-5280553810f0
Win7 / Firefox 46.0.1

Habitica user aust said they have the same problem, don't know what system they use.
90ad1ff2-b48b-406a-b8a9-2b2415a6a3af

**Comment by kawunngg** [comment] 2016-06-02 12:30
oh, another thing i noticed, don't know if this is connected: when i create challenges the tasks appear on top of my to do list, if i join other people's challenges, they are added on the bottom of the list as usual.

**Comment by Alys** [comment] 2016-06-25 05:34
related: https://github.com/HabitRPG/habitrpg/issues/7469 "Challenge Extra Notes Missing in creator's copies of tasks after creating a challenge"

**Comment by habitrpguser** [comment] 2016-09-12 09:41
Looks to me like these are two different bugs:
- Bug 1: When someone creates or clones a challenge, and then just stays in it, nearly everything is buggy for the creator's challenge tasks and tag at the moment. (See #7469 which @Alys already referenced, and #7599 . #7599 is actually also 2 bugs, one of them only happening when the creator stays in the challenge.) The solution for this is always that the creator leaves the challenge (opting to remove the tasks, and then probably deleting the tag just to make sure) and rejoins. (And because joining challenges in general also has bugs at the moment, best sync/reload/[clear your browser data](https://habitica.com/static/clear-browser-data) after that, or a combination of these. That fixes at least one of the current general challenge joining bugs.)
- Bug 2: When the challenge creator adds new tasks after the challenge has already started and participants have already joined, those tasks appear in the participants' tasks lists and have the megaphone symbol, but aren't tagged with the challenge tag. (This is what @Altariel3 described, and I can confirm this, it just happened to me, too. That was on the website in Chrome on Windows.) Until this bug gets fixed, the workaround, of course, is for the creator to make sure that the participants know that new tasks were added, and to tell them they should look into the challenge and see which tasks are new, and then find those tasks in their own task lists and tag them with the challenge tag themselves.

Should we create a separate issue for the second bug? That one is really the nastier one. Once a challenge creator knows they should leave and rejoin, that's easy - but having to message every challenge participant and explain the bug and the workaround to them whenever you add a new task is a lot of work. Many challenge owners write in the challenge description _"New tasks will be added later!"_ or similar, and then the participants click the tag occasionally and look for those new tasks - but because of the bug, they don't find them now because they aren't tagged correctly.

**Comment by Alys** [comment] 2016-09-12 10:55
@habitrpguser Yes, could you please create a separate issue for Bug 2?

**Comment by Alys** [comment] 2017-10-21 11:33
I'm closing this because we've decided to do this instead: https://github.com/HabitRPG/habitica/issues/9248 "challenge creator should not automatically join their own challenge"

**Closed as completed by Alys** 2017-10-21 11:33 UTC
Labels: priority: minor, section: Challenges, help wanted
