### ISSUE TITLE
Unable to use the gems in the guild's bank (as a guild leader)

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#7696] opened 2016-06-19 18:26 UTC
### General Info
- UUID: 60e9e6cd-efdb-4e9d-8035-3277c3276d52
- Guild ID: 17d57080-1bb2-407a-8276-63282e44c3ce
- Browser: Google Chrome Version 51.0.2704.103 m (also happens with Internet Explorer Version 11.420.10586.0)
- OS: Windows 10 Home
### Description

I subscribed to Habitica today and made my first guild. From what I understand, the 4 gems used to create the guild can be returned by making a challenge and declaring myself as winner, which is what I am trying to do. But when creating a challenge and placing 4 gems as the prize, I'm getting an error saying "Value must be less than or equal to 0." ([screenshot](http://i.imgur.com/Zva74uJ.png)). I currently have 0 gems in my account, and I'm guessing that when creating the challenge, it tries to take them from my balance instead of the guild's bank.

I have reported this in the Report a Bug Guild, and was told by Alys to report it here on GitHub.

**Comment by ghost** [comment] 2016-06-20 13:59
For the sake of linking: https://github.com/HabitRPG/habitrpg/issues/7361 (please ignore offtopic messages about errors in the middle)

**Comment by paglias** [comment] 2016-06-20 16:45
Duplicate of #7631 (cleaning it up now)

**Closed as completed by paglias** 2016-06-20 16:45 UTC

**Comment by ghost** [comment] 2016-06-20 17:01
@paglias looks like you got the wrong link

**Comment by paglias** [comment] 2016-06-20 17:04
@Racobot yep sorry! #7361
