### ISSUE TITLE
Automatically getting back mana after casting a spell

### ISSUE THREAD

**Issue by fsaxen** [HabitRPG/habitica#5341] opened 2015-06-04 00:04 UTC
When I cast "Valorous Presence" and any Habit immediately afterwards, I sometimes get back all 20 mana points from the spell.
I'm not totally sure that it's a bug because I'm a Warrior with 210 strength but it does not say that i landed a critical hit.

FYI: User ID: 5772e41c-5690-460b-92f6-a79a3eb5b0d3
Using windows 8, Firefox 38.0.5
##

**Comment by crookedneighbor** [comment] 2015-06-04 00:13
@nuke160 Are you casting multiple spells in quick succession? In that case, likely the server was unable to catch up with the browser and didn't register that the spell was cast, giving you back the 20 mp and not actually applying it.

**Comment by fsaxen** [comment] 2015-06-04 08:38
No. I cast Valorous Presence once and hit a habit quickly after it.
I also thought that maybe it has not been registered but it shows up on the party page.

**Comment by crookedneighbor** [comment] 2015-06-07 13:28
Not sure what's going on. Has this been a recurring issue? Or is it back to normal now?

**Comment by fsaxen** [comment] 2015-06-07 19:43
No. I can still recreate this problem. But it's not happening every time.
If I cast "Valorous Presence" twice quickly, it also happens. It seems that it's related to the data synchronisation, since it only appears if I cast them quickly...

**Comment by crookedneighbor** [comment] 2015-06-07 20:25
Is there a series of steps you can do that reproduces it? Having trouble reproducing it on my end.

**Comment by deilann** [comment] 2015-06-07 21:56
I've known about this for some time.

If you interrupt a skill while it's processing, many times it will still
count and cast the spell, but give you your mana back. This is most notable
when you click spells very quickly, but can happen when you interrupt the
process with any other request. It's just harder to do because it involves
moving your mouse.

@Alys and I talked about it at one point, and it's not really something
that can be fixed without managing to fix all sync errors. If users feel
upset about it, they can reduce the MP manually via FCV. Or they can just
celebrate an extra boon of mana. Or they can wait for the blue bar to
finish before clicking something else, which is advised for all parts of
the site, whenever you click on anything.

**Comment by Alys** [comment] 2015-06-07 22:51
Ugh, yes, sorry, I have a To-Do to log an issue about that explaining the problem and outlining (probably undesirable) solutions. I should have logged it weeks ago. Sorry. :(

**Comment by paglias** [comment] 2016-06-01 09:29
Should be fixed, reopen if it happens again

**Closed as completed by paglias** 2016-06-01 09:29 UTC
