### ISSUE TITLE
Experience and money changed sign?

### ISSUE THREAD

**Issue by pixelpax** [HabitRPG/habitica#1293] opened 2013-07-30 15:28 UTC
I started a party and suddenly my experience and money have turned negative. Whenever I gain experience or money now, my totals just get less negative. It's pretty wild. Hard to tell exactly when it happened, as I just + and - habits through magic mickey's android client. My uuid: 730d2d0f-daf1-4b2c-b2ea-d1df45f2679b

**Comment by lefnire** [comment] 2013-07-30 20:34
Check out No 2 of http://habitrpg.tumblr.com/post/55792029689/bug-workarounds. Dupe of #838, let's follow up there

**Closed as completed by lefnire** 2013-07-30 20:34 UTC
