### ISSUE TITLE
Disappearing items: eggs, hatching potions, food

### ISSUE THREAD

**Issue by PrincesseGrenadine** [HabitRPG/habitica#4946] opened 2015-03-30 18:51 UTC
Hello there!

So, here’s my weird bug from yesterday: I’ve lost all my eggs, except 5 pig eggs. I have no idea how it happened.

I had all kinds of basic pet eggs (except foxes, no quest pets), between 4 and 14 depending on the species; same for potions. I sold between 2 and 3 Lion/Bear/Wolf eggs, and a couple of Base and Desert potions. With my new gold, I bought my last 4 or 5 gems for this month.

I didn’t notice anything weird at this point. The transactions were normal, no bug of any kind. 

I went on my business, checked a few other tasks later and received a drop. I went back to my inventory and surprise: all my eggs are gone, except 5 pig ones. Desert and Base potions have disappeared too. I do not remember how many pig eggs or other potions I had, but I don’t have the impression I’m missing any of those.

Other weird detail: I can buy 1 other gem even though I’m sure I reached my monthly quota (that’s why I was selling stuff).

I’ve hard refreshed the pages, clicked the Sync button, logged out and in, used another device: it didn’t change anything. Nothing else to say, I didn’t die or level up or finish a quest during that time.

It happened on PC running with Windows 7, with the latest version of Firefox. My ID is 23c9e7d5-5f62-41fa-9b0c-80d0e759ff80. No 'before' screencap, alas.

Thanks for taking the time to read!

**Comment by Alys** [comment] 2015-03-31 03:46
I checked this account yesterday when this was reported in the Tavern and I can confirm that the eggs and potions were not in the account then.

I have no idea at all how this happened. Database glitch caused by overload??? Weird code bug? Aliens? We'll keep this open but without other reports, it could be very hard to track down what caused it.

@PrincesseGrenadine I can give you whichever eggs and potions (and food?) you think you might have lost. Make whatever guess you think is best. Feel free to overestimate a bit if you're not sure, because you shouldn't have to suffer from this bug.

**Comment by PrincesseGrenadine** [comment] 2015-04-01 19:59
@Alys That is terribly nice of you. Thanks again for your help with this after helping with my shifty attribute points! 💟 

I had 10 Base/Desert potions after I had sold some.
Eggs, I have no idea, I think they were all between 4 and 9 after my sales but couldn’t tell you the species... let’s round that up to 6 for everything? Sounds fair? Except foxes, because I never get any foxes, and pigs because they stayed. 
I’m starting to think they’re guilty, actually. Jealousy, because I like the other pets better. They wanted me to be stuck with only them 🐷

So 6 Panda, Bear, Wolf, Cactus, Lion, Dragon and Tiger eggs?

(Great April Fool’s day by the way! 🌸)

**Comment by Alys** [comment] 2015-04-01 22:04
LOL! Those darned pigs!  

That all sounds perfectly reasonable. I'll get that sorted out for you in the next 24 hours (I'm rushing off to work now, and then at a party tonight).

**Comment by Alys** [comment] 2015-04-03 01:46
@PrincesseGrenadine I've assigned you 10 each of Base and Desert potions, and 6 each of eggs for PandaCub, BearCub, Wolf, Cactus, LionCub, Dragon, and TigerCub. Let me know if they aren't showing up correctly!

I'm going to leave this open so that we can track any other reports of this.

**Comment by Alys** [comment] 2015-07-26 12:46
I don't recall any other reports of this so I'm closing it.

**Closed as completed by Alys** 2015-07-26 12:46 UTC
