### ISSUE TITLE
"The quest owner has left" when they have not

### ISSUE THREAD

**Issue by SteveMcLogic** [HabitRPG/habitica#4074] opened 2014-09-24 10:18 UTC
User ID: 938a0539-9036-4f23-bd53-928d6992a97d
Group ID: 7fce4962-464f-4741-9d42-8d9d8b3915c2
Google Chrome Version 37.0.2062.120 m
Windows 7 Professional SP1

Twice now at least some of my party has been wrongly shown the following message:

"The quest owner has left the party and can no longer begin the quest. It is recommended that you cancel it now. The quest scroll will be returned to the quest owner."

This is not the case, the quest owner did not leave the party at any point after creating the quest. 

This is a larger issue because when people read that message, they are prone to canceling the quest. We have not yet got everyone to accept the quest after receiving this error message to know if the quest will successfully start or not.

I will post a link to this thread in my parties chat, please let me know if you would like any more information.

Thanks,

Steve

**Comment by Alys** [comment] 2014-09-24 10:34
This should have been fixed in a very recent update so I'm wondering if the latest code wasn't being used when that happened. Can you tell me approximately when was the most recent time that this happened?

**Comment by SteveMcLogic** [comment] 2014-09-24 10:57
It happened multiple times today (around 40 mins ago), however as I check it this second the message no longer appears. Refreshing it doesn't make the message appear. I did refresh the page previously when the message appeared, and this didn't stop it from appearing.

**Comment by Alys** [comment] 2014-09-25 09:13
@SteveMcLogic : I've tested this on the production site and the bug did not occur for me, however with the server problems we've been having over the past couple of days, there might well have been unexpected behaviour for your party. If you don't mind, I'd like to put this on hold until the admins are certain that the server is behaving normally (shouldn't be too long now), and then we'll definitely investigate this properly. I'm concerned that if we do try to investigate now, anything we do might be affected weirdness that has nothing to do with the actual bug. :)

**Comment by SteveMcLogic** [comment] 2014-09-25 10:39
@Alys : That's fine with me, the bug seems to have magically disappeared for me since I posted about it, which I think gives me +1 credibility. By all means fix the server issues first, it's currently not occurring, and thus currently it's not an issue.

Thanks for helping to make such an awesome game :-D

**Comment by Alys** [comment] 2014-09-26 04:52
Another player in the Tavern has reported this happening just now:

TetoIsGreat (ddb68b6c-296a-4dd2-abaf-dd1f562ac140) 
I'm new and have just been accepted into a party. Both times they have tried to start a quest everything seems fine until I click accept and then the message turn to "The quest owner has left the party and can no longer begin the quest. It is recommended that you cancel it now. The quest scroll will be returned to the quest owner." Am I doing something wrong ? The quest owner has not left the party. It has happened yesterday and just now. Reloading the page didn't seem to fix it.

I'm still hoping it's related to the server issues, but I'll do some testing on my local install this weekend to see if I can replicate it with the latest code.

**Comment by Yuubou** [comment] 2014-09-27 01:37
Hi, I am the party leader of TetoIsGreat.
Group ID: 67298e51-99d7-4530-871e-9c26fa1940cb

I've started a Hedgehog quest 3 times now; each time, it shows me as Accepting the quest, I've seen some other party members accept the quest, and then (possibly at RollOver?) my party members get the above error and when I check it is as if the quest was never started in the Party view.

Also of note, we recently added a few members - we had never gotten this error before that.  Thanks for any help you can give.

**Comment by Yuubou** [comment] 2014-09-27 17:45
Update: We had someone else start a quest.  When I logged in I was able to accept it, but immediately got the error on the quest side bar suggesting I cancel it.  Instead, I logged out and logged back in and then error message was not there any more.  Will update if anything else happens.

**Comment by Alys** [comment] 2014-09-28 19:02
@Yuubou and @SteveMcLogic : Could you please tell me how many people are in your party? On the party page, there'll be a list of members which you can count and then possibly text saying "n more members", so add up the two numbers.

**Comment by Yuubou** [comment] 2014-09-28 22:30
10 members, which is accurate.  I didn't check this when the error was displaying.

**Comment by SteveMcLogic** [comment] 2014-09-28 23:46
My party has now successfully started the quest called "Attack of the Mundane Questline, Pt. 2: The SnackLess Monster". The error message is not currently displaying.

We have nine party members avatars showing up the top of the screen, and nine under the "members" section of the party. I also didn't check this when the error was displaying.

**Comment by SteveMcLogic** [comment] 2014-09-29 19:21
@Alys HIGH PRIORITY! We seem to have encountered a much more important bug in the same quest. I just completed one of my dailies, and directly took damage for this. My party was probably also damaged (95% chance based on my memory of their previous HP). The damage came up as an effect, along with the XP and gold income for the task. 

It seems reasonable to assume that this has occurred for the whole parties tasks, since most of the party has already lost over half their health. 

I would be happy to do further tests to confirm this, except without admin intervention this seems likely to kill me and my party members. Please advise ASAP.

**Comment by Alys** [comment] 2014-09-29 19:34
@SteveMcLogic  Completing a Daily cannot cause damage. It's more likely that a party member did not do all their Dailies and that caused the quest boss to damage the whole party, and that damage was coincidentally applied at the same time that you ticked off your own Daily. Go to the party page and (important!!) click the sync button that is next to the "send chat" button. The damaged caused by the boss will be displayed in the party messages. Even if that was not the cause of the damage, it is not possible that the glitch in displaying quest members could cause damage, so if there is a bug, it is different than this issue. If you don't see appropriate damage messages in party chat, please log this as a new incident.

**Comment by SteveMcLogic** [comment] 2014-09-29 21:44
@Alys It seems I was mistaken. The damage was caused by a party member not completing his to-dos. The way it appeared at the same time as the XP and gold made me jump to conclusions. Sorry for the newbie mistake (in my defense, I'm still L5).

**Comment by Yuubou** [comment] 2014-10-05 17:36
Update: We started another quest after this with no reports of the issue reoccuring.  Then we just started another quest and it came up again.  After accepting the quest for Rat King, I got the same error.  On the error page, in the the Quest Invitation section there were 10 instances of the word "Pending", one for each of our members, however our names were not populated in neither the Quest Invitation section nor the Member(s) section.

Refreshing the webpage page resolved the error.

**Comment by scarlet-lettered** [comment] 2014-10-13 06:55
I got this error today (10/12/2014) after sending out invites to my party for the hedgebeast quest.  I was told the quest owner had left the party--when I am, in fact, the quest owner.  I was using the android app when it appeared.  Another party member mentioned seeing the bug when they accepted the invite and the quest has been aborted twice today, so it seems other party members have seen it as well.

My API: 92e55b5f-769b-4f68-a8a2-912f11ee4663
Our Group ID: 8c090988-e644-45f6-b1e3-799b6c877138

**Comment by Alys** [comment] 2014-10-13 07:05
I still haven't been able to replicate this on the live site or my test install but it's clearly causing chaos for some people so I'll remove the code that allows quests to be aborted when the quest owner really has left. I'll try to do that in the next day or two.

**Comment by Yuubou** [comment] 2014-10-13 07:38
I'm pretty sure the only time the quest is actually cancelled is when one of the party members clicks cancel instead of refresh.  The quest never aborts itself.  So maybe changing the warning to "Click cancel to abort the quest for the entire party" will get people to not click it.,

**Comment by scarlet-lettered** [comment] 2014-10-14 01:23
Hi, our quest disappeared again, despite everyone trying not to abort the quest.  Just wondering--are only some parties seeing this error when they start quests?  Forgive me, I'm completely ignorant of how code works.  I'm both the party leader and the quest owner--is that causing a conflict? We're a new party and this is our first quest--could that trigger the bug somehow?  Thanks!

My API: 92e55b5f-769b-4f68-a8a2-912f11ee4663
Our Group ID: 8c090988-e644-45f6-b1e3-799b6c877138

**Closed as completed** 2014-10-19 19:17 UTC
