### ISSUE TITLE
Clicking does nothing

### ISSUE THREAD

**Issue by Chichirinoda** [HabitRPG/habitica#840] opened 2013-04-19 04:28 UTC
All evening, I can't get the website to respond. It looks like it's working just fine, but if I click on any of my items, nothing happens. A daily will remain checked, but doesn't go grey, and no experience or hit points are recorded. Habits don't respond at all. I haven't tried to dos. When I go to my profile, it says I'm "anonymous" and I don't have access to my stable or anything.

I've tried logging out and in, and I've refreshed the website a dozen times, but no luck. Help!

**Comment by ghost** [comment] 2013-04-19 07:58
Possibly related to #769

**Comment by keshirkey** [comment] 2013-04-19 14:46
I'm having the same issue with clicking doing nothing. I'm not having the anonymous issue though. I've tried logging in and out and using Firefox instead of Chrome, but nothing works.

**Comment by svemir** [comment] 2013-04-19 16:55
This happens to me once every day. The first time I open the page, clicks do not trigger appropriate actions. Once I reload the page in the browser (Chrome on OSX) everything starts working correctly.

**Comment by keshirkey** [comment] 2013-04-19 18:10
The reloading of the page hasn't been working for me. I even tried closing and reopening Chrome, but still no luck.

**Comment by ghost** [comment] 2013-04-19 18:19
Have you tried if https://beta.habitrpg.com works, it runs (As far as I am
aware) a newer version of HabitRPG which may work better.

**Comment by keshirkey** [comment] 2013-04-19 18:48
Yes, that's exactly what I've been using and having a problem with. It was fine for a few weeks, but yesterday I started having the unresponsive issue.

**Comment by Chichirinoda** [comment] 2013-04-20 02:30
The problem has continued today. I'm using Firefox and on the beta site. It's done this for a few minutes at a time before but refreshing always fixed it. Today I refreshed and took a big HP hit becasue I couldn't record any of my activity yesterday, but still I can't click on anything and get a response. 

@xeross I'd say it's definitely not the issue you suggested because it's not related to clicking many times. The very first time I try to click it doesn't work.

**Comment by bobbyroberts99** [comment] 2013-04-20 04:25
Although better than yesterday, I'm still having trouble successfully clicking habits and dailies. Seems like once I've left the beta.habitrpg.com tab (Safari, OS X 10.8), when I return I have to refresh a few times before it works. Seemed like it got better after all the commits were restored and now it's struggling again. I'm in the habit of checking after everytime I click and verifying that I received XP and GP.

**Comment by AngeloAdam** [comment] 2013-04-20 14:19
same issue

**Comment by Chichirinoda** [comment] 2013-04-21 23:39
Okay, I think I've figured out the problem. The latest Java update appears to be incompatible with habitrpg. I disabled Java in my Firefox and now it seems to be working.

**Comment by bobbyroberts99** [comment] 2013-04-21 23:50
I've had java disabled the whole time. It does seem better today though. Still have to refresh on first visit but not every click.

**Comment by Chichirinoda** [comment] 2013-04-21 23:53
@bobbyroberts99 Yeah, that's what was happening before it stopped working completely, so it's back to that as the status quo.

**Comment by lefnire** [comment] 2013-04-24 12:28
Hey guys, this is the same issue as https://github.com/lefnire/habitrpg/issues/769 (and many others). This is very difficult to diagnose, I've tried quite a few fixes which only made things worse (see discussions on that thread). We'll be moving to AngularJS (https://github.com/lefnire/habitrpg/issues/841) due to many inexplicable and highly complex issues like this. In the mean time, know that this issue is top priority for me and I'm trying to solve it.

For those experiencing the issue, please post your user ids (**not** your API key!) so I can take a gander. And if you know how, open chrome console and paste here any errors that are showing.

**Comment by Chichirinoda** [comment] 2013-04-24 14:59
@lefnire Thanks for your hard work. The error seems to be coming and going now, though I had thought disabling the latest java update had fixed it. My username is chichirinoda though the name displayed over my avatar is Jessica Steiner. I'm not quite sure which one is my user ID.

**Comment by ghost** [comment] 2013-04-26 22:22
Well, since you asked me to follow up here:
I can report my progress on my habits and dailies just fine, I didn't have any problems there. Now I can also rearrange them again. 
After some time I noticed a pattern: for every item, I can only open one thing; the edit menu or the progress graph. I can open and close them just fine. If I try opening the other menu of the same item though, both get bugged and won't open anymore. After a refresh, everything is unblocked and I can start over.

Here is my log of errors in Chrome Console on refresh, there don't appear any more errors when using the site:
GET https://www.assoc-amazon.com/e/ir?t=ha0d2-20&l=as2&o=1&a=1400069289  beta.habitrpg.com:21
GET https://wms.assoc-amazon.com/20070822/US/js/link-enhancer-common.js?tag=ha0d2-20  beta.habitrpg.com:21
GET https://www.assoc-amazon.com/e/ir?t=ha0d2-20&l=as2&o=1&a=0142000280  beta.habitrpg.com:21
GET https://www.assoc-amazon.com/e/ir?t=ha0d2-20&l=as2&o=1&a=0312430000  beta.habitrpg.com:21
GET https://www.assoc-amazon.com/e/ir?t=ha0d2-20&l=as2&o=1&a=1594484805  beta.habitrpg.com:21
GET https://www.assoc-amazon.com/e/ir?t=ha0d2-20&l=as2&o=1&a=1400069289  vj_kb7FLPDeQFSOsRCgThg.js:5
GET https://www.assoc-amazon.com/e/ir?t=ha0d2-20&l=as2&o=1&a=0142000280  vj_kb7FLPDeQFSOsRCgThg.js:5
GET https://www.assoc-amazon.com/e/ir?t=ha0d2-20&l=as2&o=1&a=0312430000  vj_kb7FLPDeQFSOsRCgThg.js:5
GET https://www.assoc-amazon.com/e/ir?t=ha0d2-20&l=as2&o=1&a=1594484805  vj_kb7FLPDeQFSOsRCgThg.js:5

**Comment by lefnire** [comment] 2013-04-27 11:39
@Blacer what's your user id? I'll disable ads and see if that does anything

**Comment by ghost** [comment] 2013-04-28 19:55
My user ID is: 2e7e5cd9-54f7-4381-b301-ab78d1305620

**Comment by lefnire** [comment] 2013-05-01 12:25
can we all give it another gander? I tried moving blocking script loads to ajax load https://github.com/lefnire/habitrpg/commit/584eb3e9362bddb83e238d73a13ee9eb74661e0c , that might solve it

**Comment by ghost** [comment] 2013-05-01 15:01
Nope, I still have the same issues and errors.

**Comment by lefnire** [comment] 2013-05-01 15:37
Alas. Thanks for testing

**Comment by tijlk** [comment] 2013-05-06 06:29
I have the same problem very often (on the non-beta site). Clicking tasks doesn't do anything until I refresh (which usually fixes the problem).

**Comment by ghost** [comment] 2013-05-06 06:49
I don't know if they fixed it fully on the beta site, but haven't had it
occur there for a while so.

**Comment by lefnire** [comment] 2013-05-06 07:37
It's likely an issue of model bundling performance, and since so few people
use beta it doesn't have performance issues.

**Comment by ghost** [comment] 2013-05-06 07:40
Well I had it also happen on Beta until recently, so either it randomly started working again as less people use beta, or you guys at least somewhat alleviated the problem

**Comment by JellyBean22** [comment] 2013-05-09 08:37
I have just started experiencing this on beta & prod.
Win 7
Chrome 28.0.1496.0 dev-m

**Comment by fawques** [comment] 2013-05-09 08:48
Started happening right now (not in beta)
I'm in Ubuntu with firefox
the console shows this error:
SyntaxError: missing } after function body
https://habitrpg.com/gen/mb2OKot1tjlH3nxKiWMKcQ.js
Line 4

**Comment by lefnire** [comment] 2013-05-09 08:49
yep, there's a minification compilation error in production mode i'm trying
to figure out right now. sorry guys, hang tight

**Comment by lefnire** [comment] 2013-05-09 13:14
#840 fixed

**Comment by switz** [comment] 2013-05-09 17:32
it was that uglify error?

**Comment by lefnire** [comment] 2013-05-09 22:58
The most recent bug #840 was an uglify error. This one i don't believe is, and don't know why it's closed actually

**Comment by lefnire** [comment] 2013-05-09 22:59
oh, it was closed from the commit message "fix _____" automatically. That's a good and bad feature, i'm finding

**Comment by ghost** [comment] 2013-05-10 20:21
I see this issue has been closed. I still have exactly the same issue as I reported earlier though; I can only open the settings or progress of a goal, if I try to open the other, both get bugged and can't be opened again. 
I still have the same kind of errors in the console, and I'm still seeing those ads.

**Comment by lefnire** [comment] 2013-05-10 20:26
gawd damnit github! hahah, note to everyone who makes commits, don't put the word "fix" in your commit message

**Comment by lefnire** [comment] 2013-05-10 20:38
so strange, @Blacer I tried testing your account locally. All clicks work, no errors. It's definitely an environment issue. Could you bring up your chrome / FF console, and click some items a few times to see if you get any errors? One of these days I'll get to setting up some VMs, but in the mean time I'm going to continue to try to bring down the number of query subscription requirements. What's weird is you're not in a party or anything, I don't know what it could be... I'll keep chugging.

In the mean time, I disabled ads for you on the off chance that's the issue, but I doubt it.

**Comment by lefnire** [comment] 2013-05-10 20:40
although I did get a 403 unauthorized server-side the first time I tried your account locally. Can you try clearing your cookies / cache "for all time", or try from a different browser?

**Comment by ghost** [comment] 2013-05-10 20:57
When I refresh, all the errors in the console of the amazon ads are gone. I still have the same problem though. I just tried in Firefox, there it's the same.
When I click around, there don't appear any errors. Once I saw:
Exception when calling callback "open" with exception "Error: o". cb=gapi.loaded_0:96

And sometimes, after refreshing, I have the following error in the console:
Unknown RPC service: widget-interactive-I0_1368219107928 cb=gapi.loaded_0:117

**Comment by nbering** [comment] 2013-05-28 13:29
I had this issue this morning.  I clicked on a daily, and it checked but didn't go grey.  I already knew before I checked that something was up, because I had the console open and it had an error displayed.  Shortly after I checked off the daily the screen refreshed and it was unchecked again, so I clicked again and it worked properly.

Here's the error that came up when the page loaded:

> Uncaught TypeError: Cannot call method 'split' of undefined EmZeoPsijKn3nHCYrHbLvw.js:18

**Comment by ghost** [comment] 2013-06-03 19:47
Just wanted to let you know that this bug has disappeared. I can click on progress and settings on the goals just fine, and there aren't any errors in the console any more.

**Comment by lefnire** [comment] 2013-06-03 19:51
Woo @Blacer! how about everyone else? There was a recent big stability push
(about 4-5 days ago) that I think could have solved this ticket, crossing
my fingers!

**Comment by Chichirinoda** [comment] 2013-06-03 20:02
I haven't had a problem with it in quite a while! Definitely not within the last 4-5 days.

**Comment by aurakami** [comment] 2013-06-06 00:41
Not to potentially burst the happy bubble but I've experienced a bit of this yesterday and today. Refreshing and waiting for the page to load completely fixes it though.

**Comment by AndreCaseyScott** [comment] 2013-07-07 04:10
Like @aurakami said, waiting for the page to completely load works. Key word is _completely_. At my last test just now, it took 2 mins to stop loading initially. It then takes another 30 secs or so before you can actually click on anything and have it register. It's quite annoying, to put it mildly.

These are the readings from the Network panel in Chrome. [I wish there was an export function for this, but screenshots will have to work]. These were done on the main habitrpg.com, not beta.

![screen shot 2013-07-06 at 8 52 29 pm](https://f.cloud.github.com/assets/3774345/757551/4aaaa766-e6b9-11e2-9e79-03c4bd130059.png)

There is one item that fails altogether, that image file, whatever it is. The other seems to be some initialization service (guessing since it's linked to socket.io which is the node.js web server service).

![screen shot 2013-07-06 at 8 52 17 pm](https://f.cloud.github.com/assets/3774345/757552/4abe4cee-e6b9-11e2-85b2-b8ad489f1907.png)

![screen shot 2013-07-06 at 8 52 08 pm](https://f.cloud.github.com/assets/3774345/757553/4ad69bdc-e6b9-11e2-9f53-054d28a4b440.png)

sidenote- does doing a command-R (mac) to refresh cause the server to ignore the cache? if not, then my guess is there is no caching of assets currently, as every reload downloads about 1.2MB of data...

![screen shot 2013-07-06 at 9 04 53 pm](https://f.cloud.github.com/assets/3774345/757555/7ab12f4c-e6ba-11e2-818f-5385b284c937.png)

During one this it took 2.6 mins to fully load. I prematurely cropped the screenshot, but during the next two reloads I got one at 1.8 min (with a bunch of 502 timeouts), and the one pictured at around 3 mins...

I dunno about you, but that is a reeeeeally long time. Especially since [at this point] we have to reload so often to make sure things stick.

**Comment by lefnire** [comment] 2013-07-12 01:34
@onduhray can you give http://upgrade.habitrpg.com a gander with your chrome tooling and see if it's gotten any better?

**Comment by lefnire** [comment] 2013-07-12 01:41
actually, if I look at my account on upgrade.habit:

![timeline](http://gyazo.com/59946e3a09d7aac4406cf69f9193d50b.png)

The actual app code (4th down) is ~250k. All the other files are profile images of other users and guilds, constituting 3.5m for my own account. I wonder how we can prevent those from being downloaded until accessed..

**Comment by AndreCaseyScott** [comment] 2013-07-12 02:17
Haven't done a thorough search but this looks promising.
https://github.com/mozilla/connect-cachify

From what I've found, Node.js is not designed to do any caching, which is
what browser's do by default. This cachify module supposedly allows node to
do this. There might be done workflow to manually clear updated resources,
since the expiration is supposedly very large.

Either way, we're looking for a way to cache assets so they are downloaded
once, and not again until changed. If that's on the first load, fine. Makes
the rest if the app run smoother then.

Hope this helps move in the right direction. I am no node ninja...

**Comment by AndreCaseyScott** [comment] 2013-07-12 03:14
This too. https://hacks.mozilla.org/2012/12/fantastic-front-end-performance-part-1-concatenate-compress-cache-a-node-js-holiday-season-part-4/

**Comment by AndreCaseyScott** [comment] 2013-07-12 08:39
@lefnire What kind of template system does Habit use? This cachify thing mentions EJS and Jade, both of which looks different than the views in Habit. Wondering what I need to look up to see how to use cachify with Habit...

Also, this might be useful for API things. https://github.com/imrefazekas/connect-rest. It claims to be a middleware helper for building REST apis's with node.js. Since you said API was broken in #1247, figured I'd throw it out there.

**Comment by litenull** [comment] 2013-07-12 13:59
@onduhray HabitRPG uses DerbyJS, which has a templating engine. And yeah, its not the page itself that causes the non-responsive thing. The dom is loaded perfectly when you cant click stuff. The problem is the connection between client and server. Socket.IO fails to connect to the server because of the traffic, so it basically hangs until the connection is established.

**Comment by lefnire** [comment] 2013-07-12 17:31
Derby actually has a lot of caching mechanisms in this place. It uses express and a bunch of contrib modules, plus sane production configurations, to provide optimal server setup. For example, all scripts are min/cat and served from memory rather than disk, public files are gzipped and set with cache headers, css and html all served inlined as one file, etc. The real problem is all these images, which are user and guild profile images, and are hosted elsewhere (habit doesn't yet have image upload). I'm showing 3mb of off-site profile images being downloaded.

**Comment by lefnire** [comment] 2013-07-12 17:48
The  is all based on what I've understood about how derby runs when NODE_ENV = production. I could be wrong and I'd better double check the source code and ping the Google group before I sound too sure. But my hunch is that our big need here is to add image uploads so they can be controlled by express caching of the public folder

**Comment by lefnire** [comment] 2013-07-12 22:53
so what's going on here is every user in any guild or party that you are subscribed to loads into the HTML ( the reason being so that you can click on the users and see their profile information) . One thing I'm going to try doing is to create the modals with Javascript on user click (using bootstraps api) , which would insert the image elements dynamically, rather than preparing the modal templates on page load

**Comment by AndreCaseyScott** [comment] 2013-07-18 08:51
If the caching is working for everything except offsite stuff, than loading dynamically seems the way to go. We might want to consider some way of caching the images on the Habit server versus just loading from offsite. Would create a better user experience in case the original host blocks hotlinking, (and it's the nice thing to do :P)

**Comment by paglias** [comment] 2013-09-09 18:01
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!

**Closed as completed by paglias** 2013-09-09 18:01 UTC
