### ISSUE TITLE
Suddenly killed, damage from quest x2?

### ISSUE THREAD

**Issue by skreebat** [HabitRPG/habitica#4189] opened 2014-10-27 01:01 UTC
User ID: 29685531-3021-4fb8-8614-cb909a0007de
Group ID: af61e28c-2a32-4b73-89cf-049b20a35404

Did most of my Dailies, as well as a bunch of To-Dos, including red ones. 2 hours ago, my list reset, and it was all good; still had a lot of health, got my mana, and did the quest damage.

Suddenly, just 9 minutes ago, I get a notif saying that I died, and I go and check the Party Log and it says that I did no damage (in the last 10 minutes) and that Irecieved 20.3 damage.

Copy7+paste:

"Skreebat attacks The Laundromancer for 0.0 damage, The Laundromancer attacks party for 20.3 damage. -10 minutes ago+1 
Skreebat casts Spooky Sparkles on thepinkuma. -2 hours ago+1 
Skreebat attacks The Laundromancer for 29.2 damage, The Laundromancer attacks party for 4.0 damage. -2 hours ago+1 "

I'm not sure why it reseted twice in the same day, and 2 hours apart...

**Comment by Alys** [comment] 2014-10-27 19:39
Did you change to or from daylight savings time on that day or did the time or timezone on your PC or mobile devices change for any other reason? If so, that would have caused cron to run twice.

**Comment by mcv123** [comment] 2014-10-29 21:14
This isn't quite the same issue, because it's not a multiple hits in short amount of time, but:

"stineo attacks Ghost Stag for 0.0 damage, Ghost Stag attacks party for 138.3 damage. -12 minutes ago+1 "

How? That seems like an insane amount. This party member has missed dailies before and hasn't lost that many points. Although I don't know what the point tracking mechanism is really so, maybe it is reasonable?

**Comment by Alys** [comment] 2014-10-29 22:03
@mcv123 When it's not the same bug, it's best to log a new issue so that the two different problems don't get mixed up together. However for a brief reply: It's possible to do that much damage if very many Dailies are missed, which can happen either by just not doing them, or by cron running early (e.g. by changing the time of CDS or the time the PC is set to). If the party member would like this investigated, please ask them to [go here and log a new issue](https://github.com/HabitRPG/habitrpg/issues/2760).

@skreebat :
Did you change to or from daylight savings time on that day or did the time or timezone on your PC or mobile devices change for any other reason? If so, that would have caused cron to run twice.

**Comment by skreebat** [comment] 2014-10-30 00:35
@Alys 
We hit daylights savings time over here, so the time changed on my devices. But it doesn't make sense (to me, anyway) that it would change two hours after and not just one...
But that might've been it

**Comment by Piskvor** [comment] 2015-01-29 11:55
I have been affected by the same symptoms today. No TZ changes, no time change on any device, no custom cron offset. Levelled up shortly before midnight, yet seem to have received two crons since - one when logging in via Android app in the morning ("okay, I am at thirty-something"), other when logging in via browser ("how did I lose 28 HP since midnight?!").

Devices: Android 4.0.4 with HRPG app
2x Chrome 40 64bit Linux

**Comment by Alys** [comment] 2015-01-29 12:02
@Piskvor Did you notice any other signs of cron apart from health loss? For example, did any Dailies you'd recently ticked become unticked? Are you in a party doing a boss quest? If so, please go to the party page and click "Fetch Recent Messages" then look for red messages that show damage caused by the boss - are there any that add up to 28 HP? Please also tell us your User ID from Settings -> API.

**Comment by Piskvor** [comment] 2015-01-29 12:17
- Did not tick any dailies today yet, so I don't have any indication there
  - (but I did tick dailies shortly before midnight yesterday, in the Android app - which is very laggy on my device; perhaps that might be related?).
- Boss quest: yes - _Attack of the Mundane Questline, Pt. 2: The SnackLess Monster_

>  Piškvor attacks The SnackLess Monster for 1.9 damage, The SnackLess Monster attacks party for 10.0 damage. -2 hours ago+1  
>   Piškvor attacks The SnackLess Monster for 7.2 damage, The SnackLess Monster attacks party for 5.6 damage. -20 hours ago+1       
- I see 15.6 HP in total
  - (of which 5.6 was erased by the level up @ about 11:30 PM local time yesterday).
- UID: aee569da-c23e-428f-b4ee-e5983b5d7738

The weird thing here is - I have logged in in the morning, via the app; shouldn't past midnight's cron have happened then?

**Comment by Alys** [comment] 2015-02-07 08:47
@Piskvor There was an earlier report of cron running twice in the same day for no known reason at https://github.com/HabitRPG/habitrpg/issues/4216. I've made a record of your report in that issue, so I'm going to close this one now.

@skreebat Your problem was probably caused by the time change, although I can't be sure. If not, it's the same bug as the one I've just linked to.

Please let us know in https://github.com/HabitRPG/habitrpg/issues/4216 if it happens again so that we can track the bug.

**Closed as completed by Alys** 2015-02-07 08:47 UTC

**Comment by tuki24** [comment] 2015-04-07 21:50
Didn't see anything on this page that would help so I will just ask; Two days ago I logged in and my health was full and I got a level up. I didn't log on yesterday. Today I went to sign in and my password was changed and when I was able to reset it I logged on and I was dead. Not sure if this was a bug or a hacker but I need answers and/or explanations that I have not yet considered. Thanks.

**Comment by Alys** [comment] 2015-04-07 22:07
@tuki24 We never change passwords (unless a player sends a forgotten-password request) and there are no automatic processes that would change your password. Are you sure you didn't just mistype it? Or were you entering your username with typos? The username must be in exactly the same case as it was when you signed up (e.g., if you chose Tuki24 as your username, then you'd have to enter it just like that, rather than, for example, tuki24).

When you don't log in for a day, you aren't able to complete your Dailies for that day, so you take damage from them. You can learn about how and why Dailies give you damage at [Dailies](http://habitrpg.wikia.com/wiki/Dailies). In brief, it's HabitRPG's main motivational feature - once you yourself have committed yourself to doing certain tasks every (or nearly every) day, then HabitRPG helps you enforce that commitment by removing health from uncompleted Dailies.

**Comment by Skendar** [comment] 2015-07-01 17:27
ID: 4a7b7898-c255-41fa-a47f-b14d662d1530
Group ID: ce42c4e5-a058-40ec-a331-2c01f67623b8

I got an weird issue since an few day. im doing perfect day, yet receive large amount of damages. this happen with the iron knight boss, however i already did this one, with the same party, and i remember back then, perfect day = 0 damages.

Skendar attacks The Iron Knight for 387.4 damage, The Iron Knight attacks party for 70.9 damage.
Skendar attacks The Iron Knight for 796.9 damage, The Iron Knight attacks party for 14.5 damage.
Skendar attacks The Iron Knight for 32.8 damage, The Iron Knight attacks party for 25.6 damage.
Skendar attacks The Iron Knight for 32.8 damage, The Iron Knight attacks party for 48.6 damage.

**Comment by mokaono7** [comment] 2015-08-26 03:37
Well this bug just hit my party and killed everyone. Only instead of it logging boss damage once and then party damage later, it just logged party damage even though I had checked off all of my dailies the day before. Not only that, but it kicked all of my streak data and knocked my buffs as well. And no, I didn't forget to log my dailies. I do it every night before I go to bed, without fail. Yes I drag myself out of bed to finish the task. So this is not an operator error.

**Comment by mokaono7** [comment] 2015-08-26 03:39
Oh and with that, I was alive and well earlier today when I checked to make certain I had logged everything. When I reloaded the tab to check everything off about a half-hour ago, it killed me.

**Comment by Alys** [comment] 2015-08-26 05:34
@mokaono7

Can you give us more details about "instead of it logging boss damage once and then party damage later"? Both are meant to be logged at the same time, so I'm not sure what you mean by that.

Note that if you were using Habitica earlier today without dying from your Dailies, and then died later in the day, it's almost certainly from someone else's Dailies causing boss damage. Have you clicked on "Fetch Recent Messages" in party chat to see the latest quest messages?

If you'd like us to investigate, please tell us your User ID and your party's Group ID. If you're not sure how to find them, go to Help -> Report a Bug and see step 6.

**Comment by mokaono7** [comment] 2015-08-26 23:37
Okay, what I've figured out is that Habitica erased every record of my activity from the 48 hours previous when I logged in last night. I know I cast 3 valorous presences before attacking my dailies the night before and then two during and those are no longer listed on the chat along with the damage that was there previously. 
As for the phrase above, what I meant was, it didn't log damage at any point and it killed everyone to -109.2 damage (or at least that's where I was at). What I hadn't realised at the time of that post was that everything from the previous 48 hours had been erased from the site. 

User ID: 7f090d0c-2569-4a8c-a47e-00467a0587aa
Group ID: fc2ac851-37d0-4f10-991c-1458952e453c
