### ISSUE TITLE
Quest ownership transferred to party leader while owner was still in party

### ISSUE THREAD

**Issue by zoli90** [HabitRPG/habitica#4683] opened 2015-02-14 10:18 UTC
Six days ago a party member invited us to a quest and after a day or so, the quest ownership was transferred to me(I'm the party owner/leader). I have no idea how and why this could've happened.
On Thursday I was in the inn and spent a lot of mana on burst of flames(BOF).
On Friday I checked out of the inn and started the quest(because I'm the owner).
When I logged in on Saturday morning I OHKO'd the Laundromancer with the burst of flames damages from Thursday. So the damages I did while in the inn was stored for later use.

I've seen this once before, but then the quest was already going and when I used BOF while in the inn and didn't do any damage(not even for tasks or dailies done while I was in the inn). Days later when I checked out from the inn this damage was done for Necro-vice.

I'm using lubuntu 14.04 and Firefox 34.0 (the about page also says 'Mozilla Firefox for ubuntu canonical - 1.0'). My UUID is 02026ad7-00c7-4b95-ae91-b060cd8a49ad the party ID is 7ae975e5-6614-498a-8364-e4668e1e4679
##

**Comment by Alys** [comment] 2015-02-14 10:34
_"the quest ownership was transferred to me(I'm the party owner/leader)"_  -- That happens if the person who started the quest chooses to leave the party. If the person later comes back to the party, the quest ownership is not transferred back to them.

_"So the damages I did while in the inn was stored for later use."_  -- Yes, a code change was made earlier this year to allow attack skills cast before the quest started to be applied to the quest, as long as the skills were cast on the same day. The effect of being in the inn is to effectively turn your entire time in the inn into one "day".

_"when I used BOF while in the inn and didn't do any damage(not even for tasks or dailies done while I was in the inn). Days later when I checked out from the inn this damage was done for Necro-vice."_  -- That also is expected behaviour. While you are in the inn, because your "day" does not end, the [cron](http://habitrpg.wikia.com/wiki/Cron) process never runs, so the damage you built up is not applied to the quest at that time. It is applied after you have checked out, when you "day" finally ends.

I'm not actually sure which of these things you're reporting here, but I hope I have answered your questions. Everything you describe sounds like the intended behaviour. Please ask if you have more questions.

**Comment by zoli90** [comment] 2015-02-14 10:47
Sorry for the false alarm. I didn't know this is normal now.
That party member who invited us to the quest the quest never left the party(as far as I know).

**Comment by Alys** [comment] 2015-02-14 11:00
That's cool. :) If it had been a bug we would definitely have wanted to know about it!

It is odd that the quest was transferred to you if the original owner had not left at all. I'm not sure how much investigation we can do now since the quest has finished, but I'm going to keep this open so we can think about it. If you notice that happening again, or anything else that seems relevant, please do add a new comment here! I'm about to change the title of this issue so that it reflects the quest ownership problem specifically.

**Comment by zoli90** [comment] 2015-02-16 18:46
We weren't able to reproduce the bug.
I forgot to mention last time, that I originally chose to decide later whether to join the quest and not accepted first. I accepted the quest immediately the second time.

**Comment by zoli90** [comment] 2015-02-17 17:37
I've noticed something different. When I'm at the party page and refresh the chat, one user from the quest invitation list disappears(his or her user id is: db768703-c136-4b39-8900-5bf80fc6c64b). When I reload the page this user is back on the list. I can easily reproduce this.

**Comment by Alys** [comment] 2016-06-25 09:51
We've made significant changes to the code since this bug occurred so I'm closing this. If it happens again, we can reopen.

**Closed as completed by Alys** 2016-06-25 09:51 UTC
Labels: status: issue: needs investigation
