### ISSUE TITLE
Rapidly casting buff skills results in sync issues

### ISSUE THREAD

**Issue by fentie** [HabitRPG/habitica#10685] opened 2018-09-15 15:45 UTC
### General Info
  * UUID: 8f4a567a-038c-4c48-9941-fea2dc1d2845
  * Browser: https://mybrowser.fyi/report/5b9d28885ae2040014c96e76 (I just think this is a neat tool)

### Description
If you rapidly cast a skill (ex. Tools of the Trade) from the web UI, such that the new API calls are made before the old ones finish, you end up gaining the mana back for your earlier casts. Ex. 

Cast 1, 75 mana -> 50
Cast 2, 50 mana -> 25
API call 1 returns, saying you have 50 mana left
Cast 3, 50 -> 25

It's not harmful, but people can get free skill castings from it.

#### Console Errors
I didn't have the console open, will try to check tomorrow when I have more mana again

**Comment by Alys** [comment] 2018-09-16 04:51
It's a known problem although I'm not sure we've created an issue for it. We don't care too much about people getting free skill castings (they can do that deliberately using [Fix Character Values](http://habitica.wikia.com/wiki/Fix_Character_Values) if they want to), but it is a little annoying. There is a plan to introduce bulk skill casting which might help with this, although I think the current plan is to have the player specify the number of casts and then have the API perform those casts one at a time, so maybe the same problem would occur there sometimes. If the plans change to have a true bulk cast (all the benefits of the full number of skills applied at the same time), that would certainly fix this. Adding support for database transactions might help too ([ref 1](https://github.com/HabitRPG/habitica/issues/9871#issuecomment-406590231), [ref 2](https://github.com/HabitRPG/habitica/issues/10275#issuecomment-383397271)).

Our usual response when people report things like this is to advise them to click more slowly (e.g., [How to Minimize Sync Errors](https://habitica.wikia.com/wiki/Sync_Errors#How_to_Minimize_Sync_Errors)), although I understand the desire to rapid-click! Third-party tools that cast skills on your behalf will take away the pain of that - for example, "Schedule Casting Party Buffs Skills"  by cTheDragons from the wiki's [Google Apps Script](https://habitica.wikia.com/wiki/Google_Apps_Script) page, which cleverly introduces a delay to prevent the issue you describe.

https://mybrowser.fyi/ IS a nice tool! Thanks for mentioning it!

**Comment by Alys** [comment] 2018-09-16 04:53
Staff: I've labelled this as suggestion-discussion because I'm not sure we want a specific fix for it since it's a part of a wider problem, but feel free to change that of course.

**Comment by SirLouen** [comment] 2018-11-05 10:32
@Alys I'm going to continue here the discussion instead of the Bug guild. 

You are not seeing this as a big bug, because maybe you don't understand the problem. 
The buffing issues are not related with the buffing itself, but with how they are prompted + managed. 
It unfolds into two problems:

**Issue 1:**

 As I mentioned you can simply control the sync problem just by removing the possibility of mass clicking. The button will just de-activate until it receives the callback of the successful buff

**Issue 2:** 

Worse problem as I said, is that everytime you click it auto-logs the buff in the party chat. This is a huge bug. I don't understand why the party chat is not populated as the result of the successful buff instead of just everytime the user clicks.

Today I've tested the thing again
I started with 959 MP and I mass launched a lot of Trade of the Tool buffs, more concretely 38 (959/25 ~ 38,36). I ended with 784 MP

My starting PER was 762 and the ending was 1105

I have 48 Unbuffed PER, therefore 4800/98 = 48,97 per buff (according to the TOTT formula)

This means that 1105-762 = 343 PER buffed/48,97 = 7 real buffs

If I started with 959 and ended with 784 = 175 MP spent / 7 buffs = 25 MP per buff

This means that this utterance:
> It's not harmful, but people can get free skill castings from it.

It's incorrect: The system is not "free buffing". As I said it just records the buffs in the Party Chat but the buffs do not actually work. They are completely fake due to huge sync issues.

As I mentioned above, I think both issues can be easily solved (I'm not sure how this is programmed, but essentially it's needed that everytime one user launchs a buff, there is a callback function waiting for answer for the server and this sync'd with the UI). I see this as a little pain but not a huge issue. I think this can wait a little bit.

But I'm going to start looking in the second issue first because I found that it is more critical: Since the buffs are wrongly logged in the party chat, my party (for example), thinks that some people are actually buffing way more that they are actually buffing (i.e. in my example above, people may think that I launched 38 buffs but I did only launch 7 that is a huge difference). For my party it's important to know exactly who is buffing and who isn't because its a little indicator of who is commited and who isn't.

Also there is a bigger problem with this. The party chat only logs 200 lines. So if some people is fake casting (it's not in purpose but they just click 50 times and go away and just casting 7-8 real times). We are 30 on the guild. If only 4 of the 30 do this, the party chat is completely obfuscated meaning that I don't have a way to track ideally real buffs (because older buffs go under the 200 lines). Noone really cast too many buffs per day. But for those who cast like 50 on a row due to this bug means that they are breaking our party dynamics 👎

**Comment by Alys** [comment] 2018-11-05 12:29
@SirLouen As I mentioned in the Report a Bug guild, it's not recommended rapidly click in Habitica. If you wait for a sync to finish after each click, problems like this won't happen. You can use the third-party tools I mentioned to more conveniently cast multiple buffs - that's likely to be easier for you than multi-clicking and will produce reliable results.

The effects you describe are buggy but they're avoidable by waiting for the sync bar to disappear after each skill cast.

I think the best fix for this is not to try to stop the sync issues at all. Instead we could implement a bulk cast option for skills (specify a skill and how many times you want to cast it and then all the effects of all those casts are applied in one step). That would be significantly easier for the players, would condense all the system messages in party chat to a single message ("Bobob casts Protective Aura 20 times"), and would completely avoid problems from multi-click sync errors since no one would be multi-clicking any more.

**Comment by SirLouen** [comment] 2018-11-05 12:49
@Alys yes that could be another good solution

But you have to agree with me that it's a bug that it's not currently managed the sync issue related to the party log. This means, that as long as any user can spam the party chat by mass clicking any button, this is still under the bug section (not just a suggestion/discussion), because you cannot leave 100% of the responsability in the users specially when this converges in a group point (the party chat).

From your idea I see two solutions

1. For the party chat, only print the text when the buff has fully synced. This means when you know that the database has written the register (I'm not sure if with mongodb this can be confirmed somehow, because I've been only working with SQL-like DB up to now)

2. For the UI, there can be like a modal similar to when you bulk buy things like gems, potions, etc. with a number selector, the result will be more adequate because you can calculate extracting from the intent: example: if the user has 1000 MP and wants to launch 25 TOTT then you only send 1 command to the DB (1000-1000=0 and 25*TOTT buff for the whole party), all at once. Less stress for the server overall. If the user inputs 30 TOTT then the system just calculates the max (25, 30>25) and do the same execution but with the max possible. And in the party chat, as mentioned in the first point, you just print the real execution: "User cast TOTT 25 times"

**Comment by veeeeeee** [comment] 2020-04-03 16:37
Bulk casting is not a desired behavior.

**Closed as completed by veeeeeee** 2020-04-03 16:37 UTC
Labels: status: issue: suggestion-discussion
