### ISSUE TITLE
To-Dos do not maintain order after being changed

### ISSUE THREAD

**Issue by kriscrat** [HabitRPG/habitica#5889] opened 2015-09-05 18:13 UTC
When the list order is manually changed, a refresh sorts everything again.  This occurs both when drag & drop and push-to-top. Order changes upon refresh or any type of page reload due to navigation. 

This has been going on for at least 3 weeks, exact date is not known.  This behavior was not experienced prior to that.

**Comment by zedutch** [comment] 2015-09-05 19:12
~~Does it also change back when you wait a little before refreshing so it can sync with the server? (you can force this by clicking the spinning arrows in the top-right corner)~~

This seems to be a duplicate of #2606. That issue also contains a temporary workaround.

**Comment by crookedneighbor** [comment] 2015-09-05 19:43
Just in case you didn't see @zedutchgandalf's response (edits don't send emails), this is a duplicate of https://github.com/HabitRPG/habitrpg/issues/2606

**Closed as completed by crookedneighbor** 2015-09-05 19:43 UTC

**Comment by kriscrat** [comment] 2015-09-06 18:05
Thank you!
