### ISSUE TITLE
Sorting stable by name,causes to list all animals

### ISSUE THREAD

**Issue by negue** [HabitRPG/habitica#9477] opened 2017-11-14 22:24 UTC
Using the `A-Z` sort just lets all animals to be listed, which breaks the `show more / less` workflow

**Comment by lemoness** [comment] 2018-03-05 21:47
@Tressley How would you like to handle this?

**Comment by beffymaroo** [comment] 2018-04-17 20:07
@Tressley Can you update about what might be needed here? Thanks!

**Comment by Tressley** [comment] 2019-02-12 18:03
If A-Z is selected, we can hide the Show More/Less button since it's listing all options. If that is not the intended behavior, then the bug is the rows not collapsing as they should.

**Comment by HerrMoriden** [comment] 2020-11-15 15:41
is this still an issue ? would like to work on this

**Comment by Tressley** [comment] 2020-11-16 16:54
@HerrMoriden -- Yes, this is still an issue. I've marked it as in progress for you. Feel free to comment here if you have any questions.

**Comment by shanaqui** [comment] 2020-12-10 11:32
@HerrMoriden Hi! Same on this issue -- can you let us know you're still working on it? If not/if we don't hear back, I'll mark it as Help Wanted again!

**Comment by shanaqui** [comment] 2020-12-22 11:47
Marked as Help Wanted again since we received no reply.

**Comment by adamfitzgibbon** [comment] 2022-10-20 06:36
This looks like it was already fixed, at least on web. Can anyone confirm?

**Comment by Tressley** [comment] 2022-10-20 13:26
@adamfitzgibbon -- This does not look to have been fixed. The behavior of the A-Z sort should mirror the experience of the other options, i.e. It should also use the expand and collapse functionality.

If you're interested in taking this on, just drop a comment and I'll assign it your way. 👍🏻

**Comment by adamfitzgibbon** [comment] 2022-10-21 05:32
@Tressley Oh ok, from the above I thought the ideal functionality was to hide the "See more" without it being collapsed. If we want it to work with the "See more" I can take that on!

**Comment by adamfitzgibbon** [comment] 2022-10-24 03:17
Fixed in #14304

**Closed as completed** 2022-11-18 22:45 UTC
Labels: priority: minor, help wanted, section: Stable
