### ISSUE TITLE
Email link to join quest unsuccesful

### ISSUE THREAD

**Issue by altsalt** [HabitRPG/habitica#5793] opened 2015-08-15 16:32 UTC
One of our party members created a quest two days ago. I immediately clicked the email link which brought up the quest page. However, it did not add me to the quest and currently the party member is participating alone.

The Mandrill email link still goes through habitrpg.com so that could be one source of problems.

UserID: 08b7ea3d-3210-46df-a7ca-dd7234ac9ae0
GroupID: 61c52c57-ef8f-4154-8d5a-2e59cfc6a85b

Console Log:

```
window.controllers is deprecated. Do not use it for UA detection. https-everywhere.js:342
Use of getUserData() or setUserData() is deprecated.  Use WeakMap or element.dataset instead. requestNotifier.js:64
<source> element has no "src" attribute. Media resource load failed. habitica.com
All candidate resources failed to load. Media load paused. habitica.com
Use of getUserData() or setUserData() is deprecated.  Use WeakMap or element.dataset instead.
```

**Comment by crookedneighbor** [comment] 2015-08-15 17:27
My best guess here is that your party member invited you to the quest and then started the quest before you had a chance to click on the link. It's not that the link didn't work, but that the period where you would have been able to join the quest ended before you were able to click on it. 

Does that make sense?

**Comment by crookedneighbor** [comment] 2015-08-15 17:28
If you think this was a mistake, you can ask your party member to cancel the quest they are on, which will put the quest scroll back in their inventory, and ask them to start it again.

**Comment by altsalt** [comment] 2015-08-15 17:32
The party member who initiated the quest is using the new iPhone Habitica app.

Their display shows that all of our party members have accepted and are participants.

Perhaps there is a bug with the app?

**Comment by Alys** [comment] 2015-08-15 18:01
The database shows that only the quest owner is participating in the quest. If the quest owner is seeing that all party members are participants of the quest, they should log a bug report through Menu > About > Report a Bug. That will send some automatically-generated information to the mobile developers, as well as their bug report description, so it's the best way to report mobile app bugs.

I agree with @crookedneighbor's description of what probably occurred (and his suggested fix). Note that the link in the email isn't meant to add you to the quest, it's just meant to take you to the Habitica website where you can then accept or reject the quest, so it sounds like the link was working as intended and the quest had already started.

I'm going to close this because if there's any bug it's with the app's display, and the mobile report option needs to be used by the person seeing the bug, however if you have any questions, you can comment here and we'll see them and keep helping you.

**Closed as completed by Alys** 2015-08-15 18:01 UTC
