### ISSUE TITLE
mobile app not synching

### ISSUE THREAD

**Issue by isailey** [HabitRPG/habitica#4844] opened 2015-03-12 07:52 UTC
I couldn't use my computer prior to midnight to close out my dailies. I tried to close them out on my android phone.  To do list items were very old on the phone this morning. I tried syncing but it didn't seem to sync.  I tried syncing again prior to closing out all the dailies that were showing on the mobile around 11:30 or 11:45pm, though I'm not sure they were synced.  When I logged into habit on my computer after midnight, I got the "you died" message, and zero credits on my quest, so it appears that  the dailies checked off on the mobile didn't go through, unless there is a delay on this sync as well.

Could I get the "you died" fixed so I don't lose all equipment, gold and streaks?

I just checked my phone now and to do list looks more accurate.

**Comment by Alys** [comment] 2015-03-12 08:29
I'm very sorry that happened to you! You were hit by this bug: https://github.com/HabitRPG/habitrpg/issues/4313

If you look in the first comment, you'll see an "Advice" section. That has information about resetting everything back the way it should be. Ask here if you have any questions about that!

**Comment by SynapticWanderer** [comment] 2015-03-24 20:51
I had that happen too, where the app didn't sync anything at all, so I just stopped using it.

**Comment by SpenserJ** [comment] 2015-07-21 02:55
Duplicate of #4313 and safe to close out.

**Closed as completed** 2015-07-21 12:59 UTC
