### ISSUE TITLE
Beast master achievement granted without all pets

### ISSUE THREAD

**Issue by jbenzimra** [HabitRPG/habitica#1894] opened 2013-11-23 09:12 UTC
I currently have 55 pets, but I got the Beast Master achievement.
I've closed Habit, refreshed, and even complete some habits / dailies, but I still get the achievement.

user ID: 0f90ed3c-33fb-4137-85aa-926b1388759d

![image](https://f.cloud.github.com/assets/5383317/1606206/476b532e-541f-11e3-8dd5-a417d039aa31.png)

**Comment by SabreCat** [comment] 2013-11-23 12:49
Duplicate of #1889 , should be fixed once that rollback is live.

**Closed as completed by SabreCat** 2013-11-23 12:49 UTC
