### ISSUE TITLE
[API v3] Checking one checklist item removes checklist entirely until a sync; after sync, the item checked is now unchecked

### ISSUE THREAD

**Issue by citrusella** [HabitRPG/habitica#7219] opened 2016-05-14 04:43 UTC
General Info
- UUID: 2d6ef231-50b4-4a22-90e7-45eb97147a2c
- Browser: Mozilla Firefox 46.0.1
- OS: Windows 7 Professional Service Pack 1 (via Bootcamp on a late-2011 Macbook Pro)
### Description

[//](#): # I'd take a screenshot, but my screenshot program isn't cooperating right now... Checking an item on a checklist makes the checklist disappear entirely. It's as if the daily doesn't even have one. The disappearance even persists in the edit form. Syncing will bring the list back, with the checklist item unchecked.
#### Console Errors

I don't think there were any?

**Comment by shanaqui** [comment] 2016-05-14 05:21
On a to-do, the to do just disappeared entirely, returned with the checklist in the same condition after a reload.

**Comment by crookedneighbor** [comment] 2016-05-14 14:08
Looking at this now.

**Comment by crookedneighbor** [comment] 2016-05-14 14:15
@shanaqui @citrusella I can't reproduce this now. I did some work on the checklists last night so I think I fixed the bug then. Is it working for you now?

Going to close this now, but definitely re-open it if there's still a problem.

**Closed as completed by crookedneighbor** 2016-05-14 14:15 UTC

**Comment by shanaqui** [comment] 2016-05-14 14:30
Yeah, looks like whatever you did fixed it. I've tested both dailies check lists and to dos.
