### ISSUE TITLE
Challenge owner changing habit +/- ,  buttons not working

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#4581] opened 2015-01-27 04:57 UTC
User ID: 18fa2201-c6b4-4430-bc24-861e8cb43f51

I can't remove the [-] button on a habit in a challenge that I created. I have tried in Safari and Chrome, but the same thing happens when I click to remove. When I click, both [+] and [-] buttons shift positions and then go back when I release.

Actually, I just tried again and was able to remove both the [+] and [-] buttons, but it depends on where I click. The area is not actually on the buttons, and seems to be different when adding and removing.

**Comment by Alys** [comment] 2015-02-06 08:30
"When creating Challenges, I can no longer make a +-only Habit because clicking on the - button does nothing. - only and +/- are fine, though - only can take a few clicks." -- Lemoness in https://github.com/HabitRPG/habitrpg/issues/4641

**Comment by lemoness** [comment] 2015-02-06 17:19
_facepalm_ Whooops, sorry for the dupe ticket!

**Comment by melissamcewen** [comment] 2015-03-14 18:22
This is happening for me too

**Comment by melissamcewen** [comment] 2015-03-16 00:12
So for me it does not work at all on Chrome- clicking + or - on the habit when creating and editing a challenge makes it flicker and doesn't save. On Firefox it works fine.

**Comment by deilann** [comment] 2015-03-16 00:30
If it makes it flicker and doesn't save, that means it thinks you're trying
to drag the task. So you're likely moving the mouse a bit when you do it.

**Comment by melissamcewen** [comment] 2015-03-16 00:49
I've tried it with a few mouses and it doesn't seem to be dragging, it's the same thing I'm doing in FF which works
![mar 15 2015 19 48](https://cloud.githubusercontent.com/assets/1251094/6659140/6c6cc78e-cb4c-11e4-98e5-b81ccf6cde55.gif)

**Comment by deilann** [comment] 2015-03-16 01:09
It appears to be dragging to me... dragging under the +. I've been having
trouble lately with Chrome taking single clicks as drags or double
clicks... which is really annoying when I'm checking off my Dailies and I
click and it ticks off two instead of one. That's probably related to this.

**Comment by melissamcewen** [comment] 2015-03-16 01:50
Here's a better gif though sadly doesn't show the flickering, I've disabled drag and it's still doing it, here's a better gif, but of course if someone else could see if it's happening to them that would be great 
![untitled](https://cloud.githubusercontent.com/assets/1251094/6659500/e5d0e8be-cb54-11e4-8268-12b84c7d4cfd.gif)

I'd also note the other buttons like easy/medium/hard work fine

**Comment by deilann** [comment] 2015-03-16 02:20
Yes, and now it's not flickering. I'm not saying it's going to suddenly
start working if you can not drag. :) I'm saying that flickering means it
thinks it can drag. Does that make sense?

**Comment by melissamcewen** [comment] 2015-03-16 02:39
Yeah the screen capture software I've been trying hasn't been capturing the "flickering." Here is an exact capture (mov to gif) 

![out](https://cloud.githubusercontent.com/assets/1251094/6659833/c17e1016-cb5b-11e4-9423-3ff038f10787.gif)

**Comment by deilann** [comment] 2015-03-16 02:50
Yes, again, it's trying to move the - button below the + button. That's why
it's flickering. It's then jumping back up because it can't actually go
anywhere else. It is misinterpreting the action, just like it is
misinterpreting other actions.

**Comment by melissamcewen** [comment] 2015-03-16 02:58
Any ideas on how to fix/debug it? It is strange it works for normal habits but not challenge habits.

**Comment by deilann** [comment] 2015-03-16 03:02
No, especially considering it's not 100% reproducible. Frex, I have no
issues with it using Chrome.

**Comment by Alys** [comment] 2015-03-16 03:03
@melissamcewen Have you tried clicking on different parts of the buttons, as @hazel-nutty did?

**Comment by melissamcewen** [comment] 2015-03-16 03:44
OK by clicking around I was able to get + to go but not -
![test](https://cloud.githubusercontent.com/assets/1251094/6660338/c7508614-cb64-11e4-8496-45298373bc31.gif)

**Comment by lemoness** [comment] 2015-03-16 03:47
For what it is worth, clicking on different parts of the buttons does not
tend to work for me for minus, because it moves away from my mouse
too quickly - so that isn't a very good workaround.

**Comment by deilann** [comment] 2015-03-16 03:49
I don't think we're looking for a workaround here as much as we're trying
to understand the behavior. The best workaround is to use Firefox when
editing/creating challenges, for those who are affected.

**Comment by TheHollidayInn** [comment] 2015-03-16 15:30
I'm testing this behavior out on my local server now. I have noticed two things:
  --When click the plus or minus button on a habit (either in a challenge or on the main page) the buttons bounce.
 -- If you change the width of the challenge habit (using CSS), you can edit the plus or minus button.

So, I believe this has something to two the the bounce behavior that is forcing the button to expand in width when clicked, thus pushing the button down. Maybe there is some CSS added on click. I will continue to investigate.

**Comment by TheHollidayInn** [comment] 2015-03-16 15:41
Sorry, to double comment, but I found the issue. In app.css lines 5672-5680 (when inspecting the browser)

```
.visuallyhidden.focusable:active,
.visuallyhidden.focusable:focus {
  clip: auto;
  height: auto;
  margin: 0;
  overflow: visible;
  position: static;
  width: auto;
}
```

If you remove either position: static or width: auto, the issue is resolved. I can fix the quickly, but I'm not sure what else would be affected.

**Comment by melissamcewen** [comment] 2015-03-16 18:00
If we want to keep that class it seems like the position: static is the source of the issue

**Comment by TheHollidayInn** [comment] 2015-03-16 18:06
Removing width:auto seems to fix the issue as well.

**Comment by Alys** [comment] 2015-03-16 20:40
The style is used in a few places in `website/views/shared/tasks/task.jade` so we would need to ensure that any changes worked in all places. 

Also note this comment from where the style is defined:
_// Extends the .visuallyhidden class to allow the element to be focusable when navigated to via the keyboard: h5bp.com/p_
That function must keep working too.

@TheHollidayInn Is your fix still okay, bearing those things in mind?

**Comment by TheHollidayInn** [comment] 2015-03-16 21:49
From searching the file, it seems that only the Dailies/To-do checkbox has the class as well. That checkbox still works with my change.

From h5bp.com/p, "The :active is required for IE6 and IE7..." So, removing the :active psuedo-class should maintain functionality. When I set the elements to visible, I am able to navigate to them using tabs.

Also,I am seeing the elements in Fangs, a screen reader emulator for Firefox.

However, I don't have a screen reader, so I can't do any real testing.

**Comment by Alys** [comment] 2015-04-05 12:50
We believe this has been fixed in https://github.com/HabitRPG/habitrpg/pull/4866 by @TheHollidayInn as he describes in his post above. It will go live in a day or two probably. Once it's live, I'll post here again, and then after that we will definitely want to know if anyone still experiences this bug.

**Comment by Alys** [comment] 2015-04-08 10:50
The fix for this is now live. Can those who were experiencing this problem please try again and let us know if it's still happening or not?

It never happened to all users, so the testing we have done so far is not sufficient to tell if it's fixed.

**Comment by ghost** [comment] 2015-04-08 16:30
Fixed for me!

**Comment by lemoness** [comment] 2015-04-08 21:33
Fixed for me as well!

**Comment by Alys** [comment] 2015-04-11 11:50
I'm closing this but if anyone still has problems, comment here and we'll investigate.

**Closed as completed by Alys** 2015-04-11 11:50 UTC
