### ISSUE TITLE
Negative experience and no money

### ISSUE THREAD

**Issue by scroll** [HabitRPG/habitica#863] opened 2013-04-26 04:09 UTC
I just logged to see my experience shows -308/240 , but the bar is full. 
On top of that I had 50 gold and I am left with 9.

**Comment by fawques** [comment] 2013-04-27 08:27
Related with this: Yesterday I had 45 gold and today I had 3, when I went to Settings->Restore and restored my gold, my exp went from 100 to -53

**Comment by lefnire** [comment] 2013-04-27 11:01
dupe of https://github.com/lefnire/habitrpg/issues/838, let's follow up there

**Closed as completed by lefnire** 2013-04-27 11:01 UTC
