### ISSUE TITLE
"Error" Application Error When Loading Page on WWW (Chrome) - Page Stuck on Yesterday's Tasks

### ISSUE THREAD

**Issue by aksteele** [HabitRPG/habitica#6478] opened 2016-01-07 16:25 UTC
I've been getting the following error (on RHS of page) for the last two days - it appears every time the home tasks page re-loads, and as a result completed or added content doesn't seem to save.

Today I'm still looking at yesterday's dailies list.

<img width="262" alt="screen shot 2016-01-07 at 8 23 19 am" src="https://cloud.githubusercontent.com/assets/3885681/12175615/2c007ee6-b518-11e5-9e2a-969d256aedfc.png">

**Comment by aksteele** [comment] 2016-01-07 16:36
Update: I tried logging out and logging back in, but now I can't get the log in module to load from this page: https://habitica.com/static/front

**Comment by paglias** [comment] 2016-01-07 16:37
@aksteele thanks for the report. Could you try doing the following:
1. If you have Chrome installed navigate to habitica.com, open the Console Ctrl(Cmd on Mac)+Alt+J and switch to the Network tab
2. Try completing an action on the site that should trigger the error, report here anything that appears in the Network tab, you should see a new red item which you can click

**Comment by aksteele** [comment] 2016-01-07 16:39
@paglias - can't even log in at this point. here's the error I'm when I press the 'join for free' button:

<img width="1321" alt="screen shot 2016-01-07 at 8 39 10 am" src="https://cloud.githubusercontent.com/assets/3885681/12176012/2dbe3f5a-b51a-11e5-9d19-b92a6b713cd2.png">

**Comment by aksteele** [comment] 2016-01-07 16:41
And here's the one I get when I press "Play Habitica":

<img width="1316" alt="screen shot 2016-01-07 at 8 40 40 am" src="https://cloud.githubusercontent.com/assets/3885681/12176063/72f69ebe-b51a-11e5-98fd-2f100d3d7ed1.png">

**Comment by paglias** [comment] 2016-01-07 16:43
@aksteele that's very useful if you keep the console open while you refresh and switch to the network page there should be a list of requests with one that points to https://habitica.com/api/v2/user/batch-update... it should be marked in red. Click on that one and post anything you see there. Also if you remember your UUID you should post it here

**Comment by aksteele** [comment] 2016-01-07 16:55
Sorry - what's the network page? Oh I think I figured it out. One sec.

UUID is: d1cf75df-132c-404d-a431-4ba7b7fa00b9

**Comment by aksteele** [comment] 2016-01-07 16:58
<img width="1311" alt="screen shot 2016-01-07 at 8 57 44 am" src="https://cloud.githubusercontent.com/assets/3885681/12176591/fb7672e4-b51c-11e5-87a0-f5f1a2059a4d.png">

**Comment by paglias** [comment] 2016-01-07 17:00
@aksteele sorry,

**Comment by paglias** [comment] 2016-01-07 17:03
@aksteele when you open the console there are several tabs on the top:

<img width="1440" alt="schermata 2016-01-07 alle 18 00 44" src="https://cloud.githubusercontent.com/assets/589911/12176658/c00a7470-b568-11e5-8773-d12b367e54dd.png">

You should click on Network and then do the action that triggers the error like clicking on the logic button. If the error happens before you do anything just reload the page with the console still open and report any item with the url (on the left) similar to batch-update?date=...

**Comment by aksteele** [comment] 2016-01-07 17:06
I already figured it out, see above (or here it is again):

<img width="1311" alt="screen shot 2016-01-07 at 8 57 44 am" src="https://cloud.githubusercontent.com/assets/3885681/12176792/f11c2de2-b51d-11e5-9c40-67d469a5f66b.png">

**Comment by AdrianTP** [comment] 2016-01-07 17:23
I have a similar issue, with that error message popping up intermittently and the loading bar not finishing.

Chrome `Version 47.0.2526.106 (64-bit)` on OS X `Version 10.9.5`

Habitica User ID is `dbd1f6f3-cb5e-4bb2-b4f5-cc759e7540e2`

I can check off tasks and receive the little EXP notifications but they do not persist.

...and then while I was writing this I refreshed the page again to collect more information and it worked just fine and finally persisted my checked-off tasks, so nevermind I guess. Still posting the log for reference.

Here's the relevant contents of my JS Console:

```
XHR finished loading: GET "https://rpt.cedexis.com/f1/yHikaMO0ebqyasifcaeqIg0OX6kUTGuW1lQ6Tau41lQ6Tava…aayacaakabGawOtyNv0Dg9Ums5HBxmUAhyUChjVzaaa/0/0/17652/14/0/10666/2044141/0".o.makeAjaxGetRequest @ cedexis.radar.js?_v=7450eec657e34e1e41dac4e1af96a170:2o.sendReport @ cedexis.radar.js?_v=7450eec657e34e1e41dac4e1af96a170:2o.onMeasurementReady @ cedexis.radar.js?_v=7450eec657e34e1e41dac4e1af96a170:2v.onProbeComplete @ cedexis.radar.js?_v=7450eec657e34e1e41dac4e1af96a170:2w.onImageLoad @ cedexis.radar.js?_v=7450eec657e34e1e41dac4e1af96a170:2(anonymous function) @ cedexis.radar.js?_v=7450eec657e34e1e41dac4e1af96a170:2
app-1c790aff.js:6 GET https://habitica.com/api/v2/groups/party 503 (Service Unavailable)(anonymous function) @ app-1c790aff.js:6s @ app-1c790aff.js:6f @ app-1c790aff.js:6j @ app-1c790aff.js:7(anonymous function) @ app-1c790aff.js:7j.$eval @ app-1c790aff.js:7j.$digest @ app-1c790aff.js:7j.$apply @ app-1c790aff.js:7g @ app-1c790aff.js:4i @ app-1c790aff.js:5g @ app-1c790aff.js:4xa @ app-1c790aff.js:4wa @ app-1c790aff.js:4(anonymous function) @ app-1c790aff.js:9j @ app-1c790aff.js:1k.fireWith @ app-1c790aff.js:1o.extend.ready @ app-1c790aff.js:1I @ app-1c790aff.js:1
app-1c790aff.js:6 XHR finished loading: GET "https://habitica.com/api/v2/groups/party".(anonymous function) @ app-1c790aff.js:6s @ app-1c790aff.js:6f @ app-1c790aff.js:6j @ app-1c790aff.js:7(anonymous function) @ app-1c790aff.js:7j.$eval @ app-1c790aff.js:7j.$digest @ app-1c790aff.js:7j.$apply @ app-1c790aff.js:7g @ app-1c790aff.js:4i @ app-1c790aff.js:5g @ app-1c790aff.js:4xa @ app-1c790aff.js:4wa @ app-1c790aff.js:4(anonymous function) @ app-1c790aff.js:9j @ app-1c790aff.js:1k.fireWith @ app-1c790aff.js:1o.extend.ready @ app-1c790aff.js:1I @ app-1c790aff.js:1
app-1c790aff.js:6 SyntaxError: Unexpected token <
    at Object.parse (native)
    at Object.na [as fromJson] (https://habitica.com/app-1c790aff.js:4:28377)
    at b.get.transformResponse (https://habitica.com/app-1c790aff.js:32:13149)
    at uc (https://habitica.com/app-1c790aff.js:6:9564)
    at n (https://habitica.com/app-1c790aff.js:6:11232)
    at j (https://habitica.com/app-1c790aff.js:7:9455)
    at https://habitica.com/app-1c790aff.js:7:9652
    at j.$eval (https://habitica.com/app-1c790aff.js:7:16402)
    at j.$digest (https://habitica.com/app-1c790aff.js:7:14865)
    at j.$apply (https://habitica.com/app-1c790aff.js:7:16678)(anonymous function) @ app-1c790aff.js:6(anonymous function) @ app-1c790aff.js:6j @ app-1c790aff.js:7(anonymous function) @ app-1c790aff.js:7j.$eval @ app-1c790aff.js:7j.$digest @ app-1c790aff.js:7j.$apply @ app-1c790aff.js:7s @ app-1c790aff.js:6w @ app-1c790aff.js:6y @ app-1c790aff.js:6XMLHttpRequest.send (async)(anonymous function) @ app-1c790aff.js:6s @ app-1c790aff.js:6f @ app-1c790aff.js:6j @ app-1c790aff.js:7(anonymous function) @ app-1c790aff.js:7j.$eval @ app-1c790aff.js:7j.$digest @ app-1c790aff.js:7j.$apply @ app-1c790aff.js:7g @ app-1c790aff.js:4i @ app-1c790aff.js:5g @ app-1c790aff.js:4xa @ app-1c790aff.js:4wa @ app-1c790aff.js:4(anonymous function) @ app-1c790aff.js:9j @ app-1c790aff.js:1k.fireWith @ app-1c790aff.js:1o.extend.ready @ app-1c790aff.js:1I @ app-1c790aff.js:1
app-1c790aff.js:6 TypeError: Cannot read property 'code' of undefined
    at responseError (app-1c790aff.js:32)
    at j (app-1c790aff.js:7)
    at app-1c790aff.js:7
    at j.$eval (app-1c790aff.js:7)
    at j.$digest (app-1c790aff.js:7)
    at j.$apply (app-1c790aff.js:7)
    at s (app-1c790aff.js:6)
    at w (app-1c790aff.js:6)
    at XMLHttpRequest.y (app-1c790aff.js:6)(anonymous function) @ app-1c790aff.js:6(anonymous function) @ app-1c790aff.js:6j @ app-1c790aff.js:7(anonymous function) @ app-1c790aff.js:7j.$eval @ app-1c790aff.js:7j.$digest @ app-1c790aff.js:7j.$apply @ app-1c790aff.js:7s @ app-1c790aff.js:6w @ app-1c790aff.js:6y @ app-1c790aff.js:6XMLHttpRequest.send (async)(anonymous function) @ app-1c790aff.js:6s @ app-1c790aff.js:6f @ app-1c790aff.js:6j @ app-1c790aff.js:7(anonymous function) @ app-1c790aff.js:7j.$eval @ app-1c790aff.js:7j.$digest @ app-1c790aff.js:7j.$apply @ app-1c790aff.js:7g @ app-1c790aff.js:4i @ app-1c790aff.js:5g @ app-1c790aff.js:4xa @ app-1c790aff.js:4wa @ app-1c790aff.js:4(anonymous function) @ app-1c790aff.js:9j @ app-1c790aff.js:1k.fireWith @ app-1c790aff.js:1o.extend.ready @ app-1c790aff.js:1I @ app-1c790aff.js:1
app-1c790aff.js:6 TypeError: Cannot read property 'ignoreLoadingBar' of undefined
    at responseError (app-1c790aff.js:11)
    at j (app-1c790aff.js:7)
    at app-1c790aff.js:7
    at j.$eval (app-1c790aff.js:7)
    at j.$digest (app-1c790aff.js:7)
    at j.$apply (app-1c790aff.js:7)
    at s (app-1c790aff.js:6)
    at w (app-1c790aff.js:6)
    at XMLHttpRequest.y (app-1c790aff.js:6)(anonymous function) @ app-1c790aff.js:6(anonymous function) @ app-1c790aff.js:6j @ app-1c790aff.js:7(anonymous function) @ app-1c790aff.js:7j.$eval @ app-1c790aff.js:7j.$digest @ app-1c790aff.js:7j.$apply @ app-1c790aff.js:7s @ app-1c790aff.js:6w @ app-1c790aff.js:6y @ app-1c790aff.js:6XMLHttpRequest.send (async)(anonymous function) @ app-1c790aff.js:6s @ app-1c790aff.js:6f @ app-1c790aff.js:6j @ app-1c790aff.js:7(anonymous function) @ app-1c790aff.js:7j.$eval @ app-1c790aff.js:7j.$digest @ app-1c790aff.js:7j.$apply @ app-1c790aff.js:7g @ app-1c790aff.js:4i @ app-1c790aff.js:5g @ app-1c790aff.js:4xa @ app-1c790aff.js:4wa @ app-1c790aff.js:4(anonymous function) @ app-1c790aff.js:9j @ app-1c790aff.js:1k.fireWith @ app-1c790aff.js:1o.extend.ready @ app-1c790aff.js:1I @ app-1c790aff.js:1
cedexis.radar.js?_v=7450eec657e34e1e41dac4e1af96a170:2 XHR finished loading: GET "https://rpt.cedexis.com/f1/yHikaMO0ebqyasifcaeqIg0OX6kUTGuW1lQ6Tau41lQ6Tava…uabAcGGaeaayacaakabGawOtyNv0Dg9Ums5HBxmUAhyUChjVzaaa/0/0/29582/0/0/119/0/0".
```

**Comment by paglias** [comment] 2016-01-07 17:28
@AdrianTP thanks, that's very useful.

Both you and @aksteele should try navigating to https://habitica.com/static/clear-browser-data and clicking the "Clear Local Storage" button, wait until the operation finishes then try to open the site again. Let us know if it helps

Thanks for the patience

**Comment by WolfChick2216** [comment] 2016-01-07 17:31
I'm in chrome and I am getting an application error message that suggests that I reload the page so I do and the message comes back so I end up in an endless loop of refreshing.
UPDATE: I have just refreshed the page again and it's gone. false alarm sorry :)

**Comment by aksteele** [comment] 2016-01-07 17:44
Cleared local storage. Pressed "Play Habitica." Was able to see the log in module. Pressed "log in/register using facebook". Pop up appears but nothing loads in the pop up, pop-up disappears. Tried a second time. Closed the module, turned off ad blocker (noticed that was throwing an error in Console). Pressed "Play Habitica" again. No longer see the log in module at all, get the same 503 error in Console.

Cleared local storage again. Now ad block is already off. Pressed "Play Habitica." Saw log in module. Pressed "log in/register using facebook". Pop up appears but nothing loads in the pop up, pop-up disappears. Tried a second time. Closed the module. Pressed "Play Habitica" again. No longer see the log in module at all, get the same 503 error in Console.

Hope this is helpful :/

**Comment by aksteele** [comment] 2016-01-07 18:10
More context on what I'm seeing when I load: 

<img width="1310" alt="screen shot 2016-01-07 at 10 10 11 am" src="https://cloud.githubusercontent.com/assets/3885681/12178543/df44bcde-b526-11e5-82c5-1f11f85819bb.png">

**Comment by aksteele** [comment] 2016-01-07 19:51
Also a little bummed that when I finally signed in on my android app I saw that I lost a level & gold from yesterday because I wasn't able to update :sob:

**Comment by Alys** [comment] 2016-01-07 20:14
@aksteele We're sorry about the lost level and gold! When you have access to the site again, you can go to Settings -> Site and use the Fix Character Values button to get them back. "Settings" is the gear-shaped icon on the top right of the website.

**Comment by aksteele** [comment] 2016-01-07 23:54
Updated - signed in on Firefox. Problem is only on Chrome.

**Comment by Alys** [comment] 2016-01-08 00:53
@aksteele Thanks for the update! This means that it's likely to be a local storage problem. On Chrome, please go to https://habitica.com/static/clear-browser-data and click the button there, then see if you can use Habitica again.

Others experiencing this problem can try this too.

**Comment by aksteele** [comment] 2016-01-08 00:57
@Alys as mentioned above I've done that multiple times to no effect. Clearing local history doesn't seem to solve the problem. I still can't log in on Chrome.

**Comment by Alys** [comment] 2016-01-08 01:02
Sorry, my mistake. I should have been reading more carefully.

**Comment by aksteele** [comment] 2016-01-08 01:15
Np! It's a long thread :)

**Comment by Alys** [comment] 2016-01-08 03:24
@aksteele I'm sorry to ask you to do another test, but can you please try logging in on Chrome in an incognito window? That would let us be more certain about whether the problem lies with Chrome itself or with data saved in Chrome for your account.

**Comment by lightlines** [comment] 2016-01-11 14:31
Hi, I'm also getting this error. It's fluctuating wildly across chrome - have cleared data within habitica and in Chrome itself. Getting the pink boxes in multiple numbers; sometimes I can log in and sometimes I can't; sometimes I'm seeing source code. 
Any help would be appreciated! This all happened when I joined a quest - everything went wonky. User ID: 4faa74d6-061e-bb9b-a9c139ef08e2 - it's showing as 'network error' notifications on the iOS app. Thanks.

**Comment by aksteele** [comment] 2016-01-11 21:40
@Alys - no problem! Yes, signing in on an incognito chrome window does work, so the problem must be on my chrome account.

**Comment by Alys** [comment] 2016-01-14 10:19
@aksteele Is this still happening on Chrome without using incognito mode? I'm hoping that whatever corruption was causing it has disappeared now.

If it is still happening, did you clear cookies at any time? That plus https://habitica.com/static/clear-browser-data again might fix it.

**Comment by aksteele** [comment] 2016-01-18 20:08
Problem is back:

(1) Page not updating - seeing yesterday's dailies still checked off
(2) But still lost all my levels & gold (even though I accomplished a ton yesterday, so that's weird :/)

**Comment by aksteele** [comment] 2016-01-18 22:31
Didn't fix when I cleared browser data :(

**Comment by Alys** [comment] 2016-01-18 23:49
@aksteele The problem is that local storage was holding on to your actions yesterday to mark your Dailies as completed. It didn't send them to the server yesterday, so the server thought you hadn't done them and damaged you for them on cron. After cron, local storage then did send the completion actions to the server, making the Dailies appear to be completed today. Clearing local storage after that happens unfortunately can't help because the actions have already been saved on the server. If you look at the "Advice" section at the top of https://github.com/HabitRPG/habitrpg/issues/4313 you'll see tips about how to recover from the unfair damage and how to untick your Dailies for use today without losing XP etc.

**Comment by Alys** [comment] 2016-03-06 22:39
We're tracking this error now at https://github.com/HabitRPG/habitrpg/issues/6700 so I'm closing this one. There's some advice at the top of that issue for anyone who experiences this problem.

**Closed as completed by Alys** 2016-03-06 22:39 UTC
