### ISSUE TITLE
I can't click settings!!! I hover over it and it tries to select it as text instead of a link. Using a URL does seem to work though.

### ISSUE THREAD

**Issue by Viscerim** [HabitRPG/habitica#8192] opened 2016-11-05 14:59 UTC
[//]: # (Before logging this issue, look through common problems at https://github.com/HabitRPG/habitrpg/issues If you find your issue there, read at least the first post to see if there is a workaround for you)

[//]: # (Github is primarily used for reporting bugs. If you have a feature request, use "Help > Request a Feature" so that the feature request can be vetted by the larger Habitica community)

[//]: # (To report a bug in one of the mobile apps, please report it in the correct repository. Android: https://github.com/HabitRPG/habitrpg-android, iOS: https://github.com/HabitRPG/habitrpg-ios)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitrpg/issues/2760)

[//]: # (Fill out relevant information - UUID is found in Settings -> API)
General Info
  * UUID: 
  * Browser: 
  * OS: 

### Description
[//]: # (Describe bug in detail here. Include pictures if helpful.)

#### Console Errors
[//]: # (Include any JavaScript console errors here.)

**Comment by Alys** [comment] 2016-11-05 19:21
This is just a problem with your browser or your mouse not behaving correctly. Please reboot your PC and try again. If you still have trouble after that, you can comment again here but you'll need to tell us your browser and OS details. There's probably not much we can do to help though since this isn't caused by Habitica. I'm going to close this but if you make another comment we'll still see it and try to give you some advice.

If you notice any other problems, you're welcome to ask about them at Help > Report a Bug from the website. You'll usually get faster answers there, especially for simple problems that many of the helpers there know about.

**Closed as completed by Alys** 2016-11-05 19:21 UTC
