### ISSUE TITLE
weird behavour from the enchanted armoire...?

### ISSUE THREAD

**Issue by selena-ariel** [HabitRPG/habitica#5784] opened 2015-08-14 02:45 UTC
OK, don't ask me why I was doing this but... I was randomly playing around with my test account for no good reason at all when I realized that the Enchanted Armoire was haunted by a Something that is making it act really weird. I don't know if it's acting this way for everyone, or even anyone else, because I'm not going to mess up my real account to check and there's only so many test accounts that one person can manage. All of these screenshots/food drops are from the Enchanted Thingy, and I don't think it's supposed to be giving out so many strawberries? Especially when the aforementioned strawberries mysteriously turn into chocolate on their way into the inventory...

![too much chocolate gives people stummyaches](https://cloud.githubusercontent.com/assets/9969311/9266222/2010e47e-420c-11e5-9fe6-7c5a1d5a6b95.png)

![strawberries](https://cloud.githubusercontent.com/assets/9969311/9266223/25cbdd74-420c-11e5-8a17-1bd1f416b618.png)

![more strawberries](https://cloud.githubusercontent.com/assets/9969311/9266224/295d71c8-420c-11e5-8f95-fcee0d75f478.png)

User ID: f88b1aa3-9eca-4399-bc93-d19a257d5d7a (keep it mind this is a test account, I don't use it for anything other than wikia-related-screenshots and...um...testing things...)

On Chrome. Linux/ubuntu operating system.

**Comment by crookedneighbor** [comment] 2015-08-14 03:18
Closing this as a duplicate of https://github.com/HabitRPG/habitrpg/issues/5376

**Closed as completed by crookedneighbor** 2015-08-14 03:18 UTC

**Comment by Alys** [comment] 2015-08-14 06:47
@selena-ariel In addition to the information from the issue that @crookedneighbor linked to, I suspect you're getting unusual behaviour because you are (I am guessing), clicking on the Armoire very rapidly, which doesn't give your stats time to update, and possibly also because your GP is so high. The randomess from the Armoire is seeded by your current GP, so if your GP doesn't change (e.g., due to rapid clicks), you'll always get the same result. The seed might also behave oddly at very high integers. If you repeat this test with a few thousand GP and slower clicks, I think you'll get more normal behaviour.

This is just FYI. You don't have to repeat the test if you don't want to. :)

**Comment by selena-ariel** [comment] 2015-08-14 22:25
Repeated. With normal stats it does work fine...I didn't realize stats were linked at all, so I didn't bother testing that. Oops.

**Comment by Alys** [comment] 2015-08-14 23:21
No worries! This is how you learn. ;)

**Comment by lemoness** [comment] 2015-08-18 21:53
Seed definitely breaks when gold is too high - I've had the same thing on
my own test account :)

**Comment by crookedneighbor** [comment] 2015-08-18 22:05
Yeah, we need to revisit how we're doing the armoire.

**Comment by selena-ariel** [comment] 2015-08-18 22:35
Just for the record - in case this information is helpful for anybody (I really wouldn't know, but it's fun to test these things):

95,808,862,808,033,540,000 GP breaks the Armoire. All I'm getting is potatoes and the occasional burst of (300+) XP.

9,580,886,280,803,354,000 GP: getting only small bits of XP. No food.

958,088,628,080,335,500 GP: The Enchanted Armoire is acting perfectly normally, at least so far as I can tell.

I don't know how many years it would take to collect more than 958,088,628,080,335,500 GP without messing around with character values or otherwise cheating, but I would guess that any Habitican who legitimately has this much gold isn't worrying about whether their Armoire is broken in terms of strawberries or potatoes.
