### ISSUE TITLE
Rogue spell without effect

### ISSUE THREAD

**Issue by Roberic** [HabitRPG/habitica#6118] opened 2015-10-27 08:07 UTC
Hello,

today, I cast Tools of the Trade on my party various times. (Yes, I had an awful long To-Do-List, but did it, yeah!). The problem is, it seems to have affected my Perception, but not the party's. Just the last spell raised their Perception somewhat, but not the ones before that.
Is there anything we can do about this?

I'm using Firefox on Win 8.1. My API is bf1ff7b3-7ff9-4a97-b067-57ccbd37185d, the group's 5cddebd2-f33a-4f24-a0b7-7c8a7c1e7da0.

Thank you in advance!
##

**Comment by Alys** [comment] 2015-10-27 10:04
Can you tell us what you or your party members noticed that makes it seem that the skill wasn't applied to them?

Note that if their cron ran after you cast the skill before they had a chance to look at their perception, they wouldn't have noticed the buff. Could that explain it?

**Comment by Roberic** [comment] 2015-10-27 11:23
My perception increased but not that of the party. The difference was quite easily noticeable as their perception was still their basic perception after I cast the spell nine times. Only after the tenth time it finally went up. Our mage was online while trying it and had notified me about it actually, as, of couse, I thought everything was alright when looking at my skill rate.

**Comment by Roberic** [comment] 2015-10-27 11:47
Strangely, our warrioress just looked at her perception and hers has gone up now, too. But the mage had even relogged. Could there be some delay somehow?

**Comment by Roberic** [comment] 2015-10-30 04:58
So no idea?

**Comment by Alys** [comment] 2015-10-30 05:05
It's most likely this bug: #4313
Your browser was seeming to cast the skill, making your own stats seem larger, but it wasn't sending your actions to the server, so they had no effect on your party.

However we'll leave this open for a while to see if anyone reports anything similar, in which case it might be a separate bug.

**Comment by Roberic** [comment] 2015-11-01 01:27
It seems to have sent the effect to some of the group, yet not all.

**Comment by Roberic** [comment] 2015-11-01 01:28
So.. My apologies, I'm somewhat confused. Is there any solution or consequence to this or is this support forum just for collecting bugs?

**Comment by Alys** [comment] 2015-11-01 02:03
It depends on the issue. For issues where we need to explain a bug or feature to the person reporting the issue, then we provide support, and a solution if there is one. For issues where we don't yet have enough information to work out what's happening, the issue is just for collecting information until we can do something with it.

When you say that some of the group was affected but not all, how are you determining that? Are you yourself looking at all the party members' stats before and after casting the skill, and making note of which ones increase and which don't (which would be useful information if you have it!), or are you asking your party members to report on whether they noticed buffs? If the latter, are they all responding as soon as you ask them, or do some not respond for perhaps a few hours? Buffs are wiped out when a player crons, so if some of your party members are asleep when you cast the buffs, then by the time they get back onto Habitica and look at their stats, the buffs will have disappeared. Does it sound like that might be what happened?

**Comment by Roberic** [comment] 2015-11-01 02:27
Thank you for your explanation.
Please find the answers to your questions above, as in us indeed communicating our procedures.

But do I take it right that the buffs do not have a duration of 24 hours, i.e. from midnight to midnight, but just the periods in which the individual player logs in and then logs in the next day?

**Comment by Alys** [comment] 2015-11-01 02:37
I'm very sorry but I can't tell for sure from what you've written whether you examined your party members' buffs yourself, or waited for them to tell you. You said that difference was quite easily noticeable but I'm not certain that you meant noticeable by you or by them. You said your mage and warrior had notified you about it, which implies that you waited for your party members to report their stats.

Did you yourself examine the stats of **all** your party members before and after you cast the buffs? If so, what did you yourself notice for all of them?

Buffs do not necessarily last 24 hours. They start as soon as you cast them. They end for each player individually when that player's cron runs.

**Comment by Roberic** [comment] 2015-11-01 13:22
My apologies if I did not chose clear words. Thank you for your attempt to find out and explain the spellcasting, and thank you for your time.

I admit I had expected a somewhat less technical approach but that might be my personal position.

Since this becomes too time and energy consuming for me, I hereby declare this case, as far as it concerns me, closed.

**Comment by crookedneighbor** [comment] 2015-11-01 13:50
If you feel differently later and would like to explore this some more, please feel free to re-open the ticket.

**Comment by joekatzman** [comment] 2016-01-07 20:27
Can we re-open this ticket? Because I'm having the same problem. 

I can click on other party members' avatars to see that my Valorous Presence is buffing their strength. But Tools of the trade has been cast 3 times in the last <48 hours, and NONE of them have buffed my Perception. I've been checking my stats, generally within a couple hours of each casting. We're all in North American timezones, too, so it isn't a cron problem.

The only thing I can think of that may be affecting this is that I declined the party's original invite, then accepted a subsequent one. So the Party page lists me as both invited and a party member.

**Comment by Alys** [comment] 2016-01-07 20:40
@joekatzman We'd need your User ID and party ID to help with this (go to Help -> Report a Bug and see step 6 for how to find them).

**Comment by joekatzman** [comment] 2016-01-07 21:57
Oops. Read the page, but missed that.

User ID: 6bddb2c7-a12b-4ed9-b890-5632534956a2
Party ID: aeb00bf5-3e9d-4e09-958a-a40ca1d518d0

**Comment by Alys** [comment] 2016-01-07 22:14
@joekatzman I've removed the excess party invitation for you. They do have a tendency to come back by themselves, so I'll check and remove it a couple of times each day for the next few days, and after that it should be gone for good.

The most recent Tools of the Trade was at timestamp 1452177737614 and your most recent cron was at 1452185064186 (after the skill was cast), which means that even if it had been applied to your account, you would not have noticed that because cron would have removed it. When you're in a quest, your can tell when you cron because that's when the quest progress message appears in party chat.

If you notice Tools of the Trade being cast after you've cronned, please comment here and tell us whether or not your Perception was buffed. If possible, please do that as soon as you notice so that we can look at the data before your next cron.

**Comment by joekatzman** [comment] 2016-01-08 00:10
Roger that. I have been checking for the past couple of days during the day, and seeing nothing. But I'll bring the next one to your attention ASAP; I get that you need to look at it live.

**Comment by joekatzman** [comment] 2016-01-08 00:36
OK, just had a party member log in for the day, which triggered her cron and monster attack. Then she cast Tools of the Trade, and this time it worked for me. Our party will try moving to a new timing protocol for Buffs, and see if the problem goes away completely.

**Comment by firedraco** [comment] 2016-02-29 19:55
I think I've had this issue crop up for me.

I logged on earlier today (about 8am PST), and a couple hours later a couple of rogues cast Tools of the Trade which didn't seem to give me any perception, but it did update for other members of my party. I tried syncing and ctrl+f5ing to see if it would update but it didn't.

A little later a warrior in our group cast both of his buffs and then after ctrl+f5ing again everything seemed to show up.

Not sure how useful that is since they popped up now but:
User: 0cab852e-20dd-48c8-a59e-d4005f2aab7a
Party: 35e1a5cf-2c26-466e-885c-865f908ab175

**Comment by Alys** [comment] 2016-03-01 07:05
@firedraco So the Perception buff DID show up later in the day? If so, the problem was just that your browser had been unable to sync with the server for a while. If you notice problems like that and a reload doesn't fix them, then logging out of Habitica usually does.

**Comment by Alys** [comment] 2016-03-03 06:36
I'm closing this again because it's sounding like all the issues have been from cron removing buffs (which is intentional, although undesirable in some cases, and we have https://github.com/HabitRPG/habitrpg/issues/2523 for discussing improvements) or from sync errors (http://habitica.wikia.com/wiki/Sync_Errors and https://github.com/HabitRPG/habitrpg/issues/4313).

**Closed as completed by Alys** 2016-03-03 06:36 UTC
