### ISSUE TITLE
Health

### ISSUE THREAD

**Issue by Nelmalih0** [HabitRPG/habitica#248] opened 2013-01-29 02:28 UTC
It would be really cool if you get more HP with every level

**Comment by lefnire** [comment] 2013-01-29 02:31
Agreed. Will tackle that problem once we start implementing stats
https://trello.com/card/character-stats-attributes/50e5d3684fe3a7266b0036d6/110

**Comment by wc8** [comment] 2013-01-29 02:33
I felt like something was wrong when I didn't increase Health, but, then I thought it was by design: i.e. so that the game is more challenging. Wondering: If you have more health points on every level, will it get easier to stay alive? Is that a good thing?

**Comment by lefnire** [comment] 2013-01-29 02:36
Good question. Currently leveling up increases your str & def, so do
weapons & armor - i wondered if that's a good or bad thing, since the game
actually gets easier as you play. IMO, challenge yourself by adding more
habits. Also, i think it's ok because the danger (at least for me) is when
i'm really bombing at habits / todos, in which case stats can't save me.
Something we should chat about

**Comment by ghost** [comment] 2013-01-29 03:46
all the rpgs I have ever played either directly gave you a health increase as you leveled up or an option to increase health from a variety of stats

**Comment by wc8** [comment] 2013-01-29 03:46
Gaining a stronger constitution on leveling up does help emphasize progress. #204 (Diseased Todos) might be challenging enough! 

Challenging yourself by adding more habits sounds good: in fact I've been challenging myself by adding moving certain habits to dailies. I may have gotten in a little over my head, come to think of it, so more life could be useful!

In the light of user comments about dying being discouraging after gaining levels #223, maybe it's a good thing to give the user a stronger constitution, so they don't die too soon. (Or would that be worse? Now I've lost my constitution, too!)

**Comment by ghost** [comment] 2013-01-29 04:00
Stronger constitution is generally a good thing

**Comment by StanLindsey** [comment] 2013-01-29 10:11
Take into account lefnire that as people level up more features will be unlocked, so a high level character will potential have more to deal with. 

Personally I think keeping HP static is better, otherwise the game will become too easy over time.

**Comment by wc8** [comment] 2013-01-29 15:22
Perhaps a **small** boost: 1 HP point per level, or so, for the sense of progress without making it too easy.
Larger boosts (5?) could come with the introduction of a greater challenge: eg. diseased todos.

**Comment by wc8** [comment] 2013-01-30 16:07
After considering #223, I think there should be a significant HP boost on leveling up. 
Increase difficulty via algorithms, user's self-challenge, implementation of disease, and maybe a reward cost inflation.

**Comment by Nelmalih0** [comment] 2013-01-30 16:33
Since anyway, you usually add more habits the more you use HabitRPG, and like he said more features will be implemented while you level up, i think it would be a good idea

**Comment by wc8** [comment] 2013-01-31 16:23
Another, perhaps better way of addressing difficulty: XP to HP ratio. If the number of points to level up is at the right ratio of HP points, it will still be difficult to level up, and the extra constitution will be helpful.

**Comment by wc8** [comment] 2013-01-31 16:28
In the light of this being implemented when stats are updated, I added a checklist item for this request on [Character Stats/Attributes](https://trello.com/c/L1H6LiZ3). It can be converted to a card later if need be.

**Comment by killroy42** [comment] 2013-02-02 19:36
Perhaps "earn" constitution with fitness or healthy eating habits?

**Comment by horusofoz** [comment] 2013-02-04 12:01
@Nelmalih0 Your requested functionality is likely to be integrated into [Character Stats/Attributes](https://trello.com/c/L1H6LiZ3) calculated through Health Skill/Character Level. A current proposal for skill/task mapping is as below. Note this is only a _Proposal_. The skill types are still to be decided and user's will be able to associate their tasks with attributes/

![Image 1](https://f.cloud.github.com/assets/3202339/123430/1721ea14-6ec1-11e2-9705-0fd32e95ecc8.png)

With the above in mind are you cool for us to close this ticket?

**Comment by Yughurt** [comment] 2013-02-07 00:07
Well what you could do is do the maths so you die just as quickly. Ie, while you gain more life, things kill you faster , you need more exp to gain a level(just like in most games) There's the element of progression but game doesn't get easier. This the main reason I don't like the idea of avatar based stats. It's a gamification element that doesn't increase the users goal which should be the complete goals. I guess some people might want to make it more game like but I think it should be an option that you should warn people about. Personally, cool avatar progression is good enough. For equips I just posted a new method of incentivising equips. https://github.com/lefnire/habitrpg/issues/207.

**Comment by wc8** [comment] 2013-02-07 02:28
@Yughurt What do you have in mind by cool avatar progression versus avatar based stats?

**Comment by Yughurt** [comment] 2013-02-07 11:12
As in having your avatar gain equipment and other things than strength, dexterity and health. The stats don't do anything that makes the act of doing tasks better. The assumtion with getting stats is that they help make the game easier which mean you don't have to do as many tasks. Working so you can get named equips doesn't have the assumptions that your equips do more things. In #207 I talk about random blessings for armor for completing tasks. I'm not sure if it's still an app but there was a game called godville which was a textbased random generated journey for your hero which you must protect. Its approach to lots of the elements are very light-hearted and is a good way of approaching elements in habitrpg.

**Comment by wc8** [comment] 2013-02-07 17:47
As I understand it, the stats feature is not about making the game easier but to acknowledge the work you are doing. 

For example, if you are doing well in categories (tags) which relate to health, your health will be going up and you will be gaining titles (levels) related to it. If you are doing well in study-type tasks, you gain intelligence. 

Stats are about showing you your strengths and weaknesses in different kinds of tasks and giving you something to aim for. 

In fact, except for #207's element of equipment rewards, the stats/character attributes feature, as I understand it, seems similar to the #207 feature's goal. Make progress in particular areas of your tasks and game recognizes you for it.

**Comment by Hermione333** [comment] 2013-02-10 19:08
I would like NOT to gain health points with each level, because it is too arbitrary and there is no "right" number of health points to gain. INSTEAD I would like a health elixir that gives a fixed amount of health points, and I would like that elixir to decrease in cost as you go up each level. For example: at level 1 an health elixir that gives you 5 health points will cost 50 gold coins, at level 2 you get a 5% discount and so on.

**Comment by Yughurt** [comment] 2013-02-10 23:57
Yeah I guess stats are fine as well? Except I don't know what dexterity, and other stats would be. But sure if you can make it work.

Hermione, if you've read what's been going on, getting more HP shouldn't make the game easier as you progress, removing pressure for you to get things done. HP gain, would be a sign of progression except that you would have to make failing tasks deal more damage.

**Comment by horusofoz** [comment] 2013-02-12 09:59
@wc8 has outlined it perfectly. Stats are to show your progress in specific areas while probably tying into classes which will be another RPG'esque indicator of your progress.

**Comment by horusofoz** [comment] 2013-03-03 08:15
For further discussion please refer to [Trello 110](https://trello.com/c/L1H6LiZ3).

**Closed as completed by horusofoz** 2013-03-03 08:15 UTC
Labels: status: issue: suggestion-discussion, priority: important
