### ISSUE TITLE
iOS Client issue (bugs and questions)

### ISSUE THREAD

**Issue by HKmania** [HabitRPG/habitica#1425] opened 2013-09-04 17:17 UTC
Hi! I'm from Russia, and my English isn't good (I'm just learning), but I'll try to write correctly.
You make a great project, and I was waiting app for iPhone a very long time, because I don't use PC often :) When your app was published, I downloaded and tried it at first day, and found some bugs (maybe it doesn't bugs, but feature).
All of this points relate to iPhone version, not iPad.
iPhone 4, iOS 6.1.3.
1. Letters in "Note" window (for Habits, Daily and To-Do "Edit") is too large.
![img_1856](https://f.cloud.github.com/assets/5293007/1082215/d5f876dc-1584-11e3-82e9-73711bdc7166.png)
2. When I try to edit smth (keyboard is open) and open main menu synchrounous, keyboard is keeping in an open state.
![img_1857](https://f.cloud.github.com/assets/5293007/1082210/d5c4c378-1584-11e3-9eee-09844c36198c.png)
3. Main window is moving with black stripe, when I come to the end of list.
![img_1858](https://f.cloud.github.com/assets/5293007/1082211/d5c7ab56-1584-11e3-9ec1-23b8869f5ce0.png)
4. I can edit "API token" and "User ID" - is it bug or feature?
5. Legend's parts in the list of Habits or Daily or To-Do is hidden from view. (If you'll  make a legend "Looooooooooooooooooong legend" - after making you can see only "Looooooooooo..."). At the 'Rewards" list full legends is hidden too (I don't know what equip give to my character).
![img_1859](https://f.cloud.github.com/assets/5293007/1082212/d5ca49e2-1584-11e3-8afa-b5bd0618386b.png)
6. Menu "Customize" doesn't move to the end. In the app I can see only parts of last two squares (Clothing).
![img_1860](https://f.cloud.github.com/assets/5293007/1082213/d5cf3d12-1584-11e3-801a-6d27a891698a.png)
7. Main Menu is too large for iPhone.
8. When I go from "Help" to GitHub's link, I cannot come back to app (there is no button "Back to App" or cross at the upper corner or smth like this). Only app's reset can help.
![img_1861](https://f.cloud.github.com/assets/5293007/1082214/d5db5520-1584-11e3-9124-cbaeabbea300.png)
9. There are no numbers of HP and XP at the stripes in main menu.
10. If main menu is open, and I try to move a visible part of list at the right, then main menu doesn't move right. (It move together) - sometimes.
![img_1858](https://f.cloud.github.com/assets/5293007/1082211/d5c7ab56-1584-11e3-9ec1-23b8869f5ce0.png)
11. Switching between "Customize" and "View" isn't clear (there is no sign, where am I: in the "Customize" menu or in the "View" menu)
12. It's bug only for Russian alphabet: type, using in the HabitRPG's app in Russian doesn't equal type, using in English.
![img_1862](https://f.cloud.github.com/assets/5293007/1082282/ded1631c-1585-11e3-97b6-9537e876c8d5.png)
That's all.
Best regards and thank you for HabitRPG :)

**Comment by HKmania** [comment] 2013-09-04 17:28
Sorry for a big pictures, I'll try to reduce it :(

**Comment by paglias** [comment] 2013-09-04 17:29
Thanks for the report! 
Next time file this in https://github.com/HabitRPG/habitrpg-mobile which is the mobile app repository, anyway I''ll try to answer on some of these:

5-) If you click on the todo/daily/habit you'll get to a detail page where you can see the whole text. For rewards click doesn't work, the code has been updated to fix this so you'll be able to click also on them.
9-) It is so by design.
11-) Yes, you're right, I'l try to fix it in the next days

**Comment by paglias** [comment] 2013-09-04 17:33
About n **7**, too large how? the text or the space it occupies?

**Comment by lefnire** [comment] 2013-09-04 17:35
I think several of these were already fixed by you and @meaganoff yes? FWIW we haven't yet cut a new release of the iOS app, we'll do that this weekend

**Comment by paglias** [comment] 2013-09-04 17:37
I fixed only 5, I think. Don't know about @meaganoff 

Before release we should fix 11, it's quite unintuitive.

**Comment by HKmania** [comment] 2013-09-04 17:51
"About n 7, too large how? the text or the space it occupies?"
I think, it is the space (in a vertical direction) and the text too. This is the best size for iPad. But I'm getting used to this size of menu. 
And I forgot p.13: at "Settings" menu legends "Save" and "Logout" is hidden at half.

**Comment by HKmania** [comment] 2013-09-04 18:49
About the main menu: if you delete "Profile", and give this function to hero's avatar, like it have done at full version, you will get free space, and you will can align height of menu with height of iPhone. It's just a suggestion.

**Comment by paglias** [comment] 2013-09-05 10:45
@HKmania About 11 I created a pull request with some changes. It is here HabitRPG/habitrpg-mobile#124, what do you think?

**Comment by HKmania** [comment] 2013-09-05 17:42
@paglias I think, this change will do interface more friendly/intuitive. As a suggestion: for more intuitive interface you can make active button's background darker than other button, like it was pressed. 
And other suggestion: completed tasks move to bottom of list automatically; actually things left at top of list.

**Comment by paglias** [comment] 2013-09-05 17:54
I agree about the background but I'm not very good at design so maybe we should wait for someone who can choose the right color :)

Abbout completed task, do not they move to the `completed` list?

**Comment by HKmania** [comment] 2013-09-06 02:35
Completed list exists only for "To-Do". For "Daily" active, completed and inactive tasks are mixed by time of making.

**Comment by HKmania** [comment] 2013-09-06 11:45
I find one more trouble: list of rewards don't move completely and I cannot buy healing potion from app. I can buy it only from site :(

**Comment by paglias** [comment] 2013-09-06 12:05
Yes I noticed that too, I think a new release with several fixes is going
to be published tomorrow. Let's see if it will fix them and then if they
are still there was please repost here. It may takes some time to land on
the iPhone due to the apple review process.

**Comment by HKmania** [comment] 2013-09-09 18:04
@paglias, I update app, and it work better (lists move correctly, legends isn't hide, I can change difficult of tasks), but I have the trouble: today isn't Sunday, but mobile app don't think so... I have to shut off all daily shedule, because it's wrong :( App is being late of 24h. My timezone is GMT+5. How can I fix it?
And little bug: there is smth mystery in "Rewards" menu, it costs 30 coin and have no legend. I think, it's weapon.

**Comment by paglias** [comment] 2013-09-09 18:18
I also have the little bug you mentioned at the end, sincerely I don't know where it comes from and emulating the app in the browser doesn't give that problem. In my case it's the sword, what about you?

For the timezone issue, someone else reported it on HabitRPG/habitrpg-mobile#127, I got it some days ago on the site and then everything is running correctly now, let me know if it's still going on the next days. If it isn't try reinstalling the app/loggin out and back in. I'm sorry :(

**Comment by paglias** [comment] 2013-09-09 19:29
@HKmania i'm going to move this bug to http://github.com/HabitRPG/habitrpg-mobile, but before doing that: of all the bugs you reported which one are still there after the update? thanks for you're time!

**Comment by paglias** [comment] 2013-09-09 19:55
I just pushed some fixes, **n1** is fixed, added padding to notifications, details page can scroll to the bottom

**Comment by HKmania** [comment] 2013-09-10 04:28
@paglias, n 5, 6, 11 are fixed. Other bugs are still there.
About days of week: in app Sunday is site's Monday, app's Monday is site's Tuesday etc. It's late for a 24h. May this function check date and time by iPhone date&time? I fix this problem temporary by choosing other day in shedule, but now I cannot use the site correctly. I have already read issue about timezone trouble, and I'll be waiting for fix.
About mystery rewards: this is all type of weapons (for me it's axe).
And one more trouble: I'm 4th lvl now, and profile says, that I have one pet, but there are no pets in "Customize".

**Comment by paglias** [comment] 2013-09-10 08:25
About the rewards it should be fixed now, when the new update is published.

About days of week, we're working on it.

About the pets, actually the mobile apps shows only the pet you have selected but you can do that only from the website from the stable (click on the avatar, wait a few seconds for the options page to load, click on stable)

**Comment by HKmania** [comment] 2013-09-10 10:47
Thank you for answers, I'll be waiting for update in Appstore.
Shall I open new issue, if I find new bugs? Or I can write comments here?

**Comment by paglias** [comment] 2013-09-10 12:41
About the update we still have to fix the bug before releasing it so iit may takes some days

The  next time it would be better to open a new issue on https://github.com/HabitRPG/habitrpg-mobile

Thanks for the time spent reporting these!

**Closed as completed** 2013-09-10 18:11 UTC
