### ISSUE TITLE
Setting due date for a todo: window falls behind, instead of in front of, spell list

### ISSUE THREAD

**Issue by casicastiel** [HabitRPG/habitica#2234] opened 2014-01-02 16:37 UTC
User cca60406-1b8f-496e-af77-cd19df77c895, Chrome on Mac
![screen shot 2014-01-02 at 11 35 39 am](https://f.cloud.github.com/assets/6208739/1833557/2e0fcff0-73cc-11e3-8067-bdc75440fd9d.png)

**Comment by SabreCat** [comment] 2014-01-03 01:27
Duplicate of (or very very closely related to) #2187.

**Closed as completed by SabreCat** 2014-01-03 01:27 UTC
Labels: priority: medium
