### ISSUE TITLE
Pets keep on resetting after hatching them (8 times since first issue)

### ISSUE THREAD

**Issue by Awakebutstilldreaming3** [HabitRPG/habitica#3279] opened 2014-04-14 14:25 UTC
I have had a consistent issue with trying to hatch pets. at the moment i have 33 eggs and 16 hatching potions. of which many can create pets i do not have yet. But every time i try and hatch the pets and feed them with the 12 food items i have, it works for the moment. but when i refresh the page for the next day or open HabitRPG for the next day it refreshes, and i have the eggs and food and potions put back into my market and the pet count goes down again. Please help :3

**Comment by Alys** [comment] 2014-04-15 09:38
Can you please add your [User ID](https://habitrpg.com/#/options/settings/api) (not API Token) here?

I'm wondering if you experience more server sync errors than the rest of us (that could cause what you describe). Have you noticed an unusually high number of other problems with the site, such as a LOT of "Application Error" messages or other error messages?

Or do you frequently taking much more damage overnight from uncompleted dailies than you might expect? If you're not sure what's an expected amount of damage, I would be interested to know these things:
 1) Approximately how many dailies do you have?
 2) Roughly how many, on average, are left uncompleted at the end of the day? (Just one or two, or almost all of them, or somewhere in between?)
 3) Are most of your dailies blue/green or orange/red?
 4) Roughly how much does your Health drop overnight, on average? E.g., about 1 point / 5 points / 10 points / ...?
 5) Do you have problems with your internet connection in general, such as websites often not loading properly, or loading very slowly, or your internet connection just dropping out (disappearing / failing) often?

If you can't answer all these questions, that's okay! It might turn out that they aren't relevant. Just answer what you can, but definitely give us your User ID.

**Comment by Awakebutstilldreaming3** [comment] 2014-04-16 15:35
yeah of course. sorry i just kinda signed up, trying to figure it out 
this is the User ID 12349cbc-dd67-4159-bd4d-714f724eda46
ive noticed a lot of time I'll try and go to my party and suddenly it will say I don't have a party or it's taking too long to load. and sometimes when i try and refresh the page it takes a while, but when i do im back to having 72/100 pets and a enlarging amount of food, potions, and eggs
1. i have 14 dailies 
2. they all get completed usually. , there was only one i sometimes cant do 
3. they're all deep blue right now 
4. uhm lately it hasn't any, but when i was doing the quest of freeing yourself from the dragons influence it would drop about five points a day
5. my internet is a little slow because it's at school, but I can easily get internet connection and all at home.

**Comment by Alys** [comment] 2014-04-16 20:18
Thanks for the detailed answers! It looks like you do not have significantly more problems with server sync errors than the rest of us, so that can't explain your pets unhatching themselves back into their eggs. Unfortunately, I can't think of any other explanations at the moment. :(

It _might_ help if you could take some before-and-after screenshots and upload them to a site such as imgur (or, if you don't have/want to create a login to any such site, you can [email them to me](mailto:lady_alys@oldgods.net) and I'll upload them. Take one of your Market tab immediately after hatching a pet, so that it shows the notification box that says the pet was hatched, then take one of the pets screen showing the new pet (tell us which pet it is), and then the next day when the pet has vanished, take another screenshot of the pets page showing the blank spot. There might be something in all this that gives the developers a clue about what's going on. To simplify the situation, just try to hatch ONE pet on the day that you do this, and don't feed any pets at all.

_"I'll try and go to my party and suddenly it will say I don't have a party or it's taking too long to load"_  That's very common and many of us experience it. It doesn't indicate a problem. What happens is that the browser first loads a basic template for the party page, and then fills in the correct information. This can often take more than an eyeblink of time, so you see it happening.

**Comment by deilann** [comment] 2014-04-16 20:51
It _could_ still explain it if you're hatching them super fast one after
another. But I'm still not sure that's it... But like Alys said, try to
hatch just one pet, and see how that rolls.

**Comment by Awakebutstilldreaming3** [comment] 2014-04-16 20:53
@deilann I tried to only hatch one a day and the same thing happens the second i refreshed my page. One time i had hatched my pet and just went back to the tasks page and refreshed it and my new pet was gone. Ill take those screen shots though

**Comment by deilann** [comment] 2014-04-16 21:04
That _is_ a server issue then. Hmm.

**Comment by Awakebutstilldreaming3** [comment] 2014-04-16 21:07
Ive been trying to take those pictures... and i just noticed something, i thought it was happening becuase of my add blocker, but i turned that off too. The green little blurb that says "this thing has hatched" or "you found this thing" or "pet likes this food" isnt showing up

**Comment by deilann** [comment] 2014-04-16 21:09
What browser are you using?

**Comment by Awakebutstilldreaming3** [comment] 2014-04-16 21:12
google chrome?

**Comment by deilann** [comment] 2014-04-16 21:13
And you're getting notifs on everything else?

**Comment by Awakebutstilldreaming3** [comment] 2014-04-16 21:26
nope :/ not any more no notifications on additions of mana or gold

**Comment by deilann** [comment] 2014-04-16 21:26
Can you open up the console and tell me if you're getting any errors?

**Comment by Awakebutstilldreaming3** [comment] 2014-04-16 21:28
i have it opened right now. It seems fine to me. just no notifications. No server errors \

**Comment by deilann** [comment] 2014-04-16 21:30
I'm looking specifically for Javascript and CSS errors. You're not
necessarily going to see server errors in the console. We're looking at
your side. You need to take an action and try something to get notifs.

**Comment by Awakebutstilldreaming3** [comment] 2014-04-16 21:49
i tried resetting my computer settings and then went to the site and then refreshed and hatched three more pets and fed food. no notifications came up. 
sorry, i was in class when you sent this

**Comment by deilann** [comment] 2014-04-16 21:51
Did you try hatching them whilst the console was open? You have to take an
action for anything to show up in the console.

**Comment by Awakebutstilldreaming3** [comment] 2014-04-16 21:51
wait. I'm sorry, which console are you referring to?

**Comment by deilann** [comment] 2014-04-16 21:52
The Javascript console.

**Comment by deilann** [comment] 2014-04-16 21:53
Press ctrl-shift-j

**Comment by Awakebutstilldreaming3** [comment] 2014-04-16 21:55
yeah.. alright with my new computer settings i reopened it and tried to find the javascript console. found three errors. 
![habitrpg1](https://cloud.githubusercontent.com/assets/7291013/2725862/d4442b0a-c5b1-11e3-97b7-31a122277499.png)

**Comment by Awakebutstilldreaming3** [comment] 2014-04-16 21:57
this is what happens when i tried to hatch an egg
![habit2](https://cloud.githubusercontent.com/assets/7291013/2725881/089cb066-c5b2-11e3-9c12-fe23bf711433.png)

**Comment by Alys** [comment] 2014-04-16 22:41
Images from Awakebutstilldreaming3: https://docs.google.com/file/d/0B_spCtVdyjgeQ0FfeDlHdkJMNlk5eW1laTA1dXo1X2hXdVU0/edit?pli=1
(Although it's now obvious to me that you can upload images to github, which I previously had no idea about. Duh. :)

**Comment by Awakebutstilldreaming3** [comment] 2014-04-16 22:42
haha i just figured it out :3 im kinda slow too

**Comment by deilann** [comment] 2014-04-19 05:33
Can you try using another browser/computer and see if it sticks? I am
wondering if this is an issue with your account or if it's a local issue
(something on your end). (Local doesn't mean it's your fault, but it does
mean that fixing it is a different beast.)

**Comment by Awakebutstilldreaming3** [comment] 2014-04-21 20:57
i got a new computer im using and tried it on that.. instead of using chrome i used mozilla. and now the updates are happening. i dont have another browser set up on the computer i was using. so i guess its just with the computer i have then?

**Comment by Alys** [comment] 2014-04-21 21:57
It did sound like a specific browser problem; not even a general Chrome problem, because I use Chrome without incident, but a problem with your specific instance of Chrome. You will probably find Chrome works on your new computer (we would be interested to know if it does not!) 

Are your pets no longer resetting after you hatched them?

**Comment by Awakebutstilldreaming3** [comment] 2014-04-22 02:08
ill check it out once i get the new computer back (i just borrowed it from my dad). It seems odd though because i reset my computer many times and still the same problems occurred. But the pets are staying now. so long as i make the action on another computer it will read on this one. i just cant do so on this computer. 
that was the weirdest part Alys. ive been using chrome the entire time and the problems only just started occuring.

**Comment by radicallyradish** [comment] 2014-04-25 03:54
Hey, I'm also having the same problem, and was able to get everything to work when switching to firefox. So, I'm assuming it's something to do with our specific chrome servers...

**Comment by Alys** [comment] 2015-01-14 17:00
@Awakebutstilldreaming3 and @radicallyradish : I'm sorry we didn't get back to you about this. Are you still having this problem on the Chrome browser?

**Comment by JaeBeyBey** [comment] 2015-06-05 22:46
User ID: d56109ad-3b4c-4188-bcb6-0eb21a95e9c6
Browser: Chrome

Related Issue: Pet that has leveled to Mount is still showing in the Pet section but is not grayed out.

I have a Red Dragon that I fed a bunch of strawberries and it leveled to a Red Dragon Mount.  The Red Dragon shows up in both the Pets and the Mounts tab but it's not grayed out in the Pets tab.  It's not a crucial issue but I thought I'd report it just in case it causes other users try to feed it even though it's already been leveled.  I did not hatch another Red Dragon (I'm not sure if you can hatch duplicates).  I did not try to feed it with more Food items.

Let me know if I can provide more info! <3

**Comment by hairlessbear** [comment] 2015-06-05 22:51
@AwesomeJae Have you tried refreshing the page? And if so, have you tried closing the page completely, and opening HabitRPG in a new tab/window?

**Comment by JaeBeyBey** [comment] 2015-06-05 22:58
@hairlessbear Thanks for the suggestions!  Here's what I tried:
- Refreshing Page
- Closing tab and reloading HabitRPG on a new tab
- Closing browser and reopening
- Restarting laptop
- Cleared browser cache

**Comment by hairlessbear** [comment] 2015-06-05 23:05
That's very thorough! Since you didn't say otherwise, I'm assuming none of those worked. 

Does the red dragon pet function as expected (i.e. when you click it, it shows up in your avatar, and it doesn't have a feed bar under it)? And does the red dragon mount work properly?

**Comment by JaeBeyBey** [comment] 2015-06-05 23:07
@hairlessbear It does.  Not sure if it's supposed to show up at the same time as a mount though...
![screen shot 2015-06-05 at 4 06 16 pm](https://cloud.githubusercontent.com/assets/11524609/8016774/f6581436-0b9c-11e5-89c0-dc47201662ab.png)

**Comment by hairlessbear** [comment] 2015-06-05 23:15
@AwesomeJae Don't worry, that's working properly ([here's my profile for another example](https://habitrpg.com/static/front/#?memberId=8ac7242d-8f18-4d6f-b4f4-8f6302f7fa0b)). 

Welp, I'm out of ideas. I'm guessing that this was caused by some sort of sync error, but you'll have to wait for an admin to come by to investigate further. Out of curiosity though, would you like to keep the pet, or not?

**Comment by Alys** [comment] 2015-06-05 23:19
@AwesomeJae your pets data in the database has become corrupted with multiple entries for the same pet. I'll fix it for you soon. If it's still not right in an hour after a reload, comment here again.

**Comment by Alys** [comment] 2015-06-05 23:23
Actually, no, that's completely untrue. I was looking at your data too quickly. It's fine. Possibly a sync error caused you to keep the pet after you mounted it, if you're certain you didn't rehatch it. Everything looks fine apart from that.

**Comment by Alys** [comment] 2015-07-18 23:55
@AwesomeJae Sorry for the delay. Is this still happening for you?

**Comment by Alys** [comment] 2015-08-12 10:25
I'm closing this, but @AwesomeJae if you're still having problems, let us know.

**Closed as completed by Alys** 2015-08-12 10:25 UTC
