### ISSUE TITLE
challenge tasks don’t retain sort order when creating or editing a challenge

### ISSUE THREAD

**Issue by wc8** [HabitRPG/habitica#1703] opened 2013-11-01 12:38 UTC
One can reorder items on the Challenges tab but the sort reverts. 

EDIT by Alys 2020-05-13: Before working on this, please read the comments below and also the comments in this pull request: https://github.com/HabitRPG/habitica/pull/12021 . If you think the code in that PR is suitable for re-use in your solution, you're welcome to use it - please mention in your PR that you've done so.

EDIT by Alys 2017: This issue will be easier to fix now because  there is code for sorting tasks in Group Plans (#8358) and it can be reused for challenges. Copying from @TheHollidayInn's [comment below](https://github.com/HabitRPG/habitica/issues/1703#issuecomment-274308541):
"the code allows to order challenge tasks (and can be shared between all three). Although, there needs to be a taskOrder object on the challenge - not sure if that exists."

EDIT by Alys 2020-02-28: What's supposed to happen is that the order of the tasks you see on the challenge's screen should be the same as the order of the task IDs in the challenge's `tasksOrder` object. Below is an example of that object in a challenge's document.

An additional problem is that the challenge's page has lost the ability for the challenge owner to reorder the tasks. The owner should be able to drag and drop in the same way that a user can drag and drop their own tasks. Admins (moderators and staff) should also be able to drag and drop the challenge's tasks (there's already code for challenges that gives admins the same rights at the challenge owner). Other players should not be able to drag a challenge's tasks in the challenge's own page (of course they can drag their own copies of the tasks after they join the challenge).

```
{
    "_id": "b7fbd6a2-6d5e-4f28-a81f-12f42f9cf447",
    "tasksOrder": {
        "habits": [
            "990933b0-4853-4f38-92b0-3864ce576f9e",
            "3d131996-768b-46e9-937d-993452a78df2",
            "5ca7fbf1-b7b5-498e-9c6d-85d328a50099"
        ],
        "dailys": [
            "30ef773b-292e-46e7-beb1-ecf2df66cbb3",
            "62782db7-8bbd-48e4-b0b0-2ab86a5d1031"
        ],
        "todos": [
            "85a5e240-8c64-446d-baab-db6debbabdd0",
            "71a67058-e022-497a-8319-d52584383b66"
        ],
        "rewards": [
            "2c0f8ed9-a61f-4ba4-9ad4-5f36a25db02a"
        ]
    },
    "official": false,
    "memberCount": 0,
    "prize": 0,
    "name": "My Challenge",
    .... etc ....
}
```

**Comment by habitrpguser** [comment] 2016-02-03 09:22
I think this issue and the closed issue #5647 ("Cannot rearrange tasks when creating or editing a challenge.") are different issues (though related). One is about tasks changing order in one's personal tasks page after joining the challenge. The other is about not being able to reorder tasks in a challenge while editing. Those are/should be two different orders. (One of the tasks inside the challenge as you see them before you join, the other of your personal tasks after you've rearranged them into your own preferred order.)

I'd very much like to have the feature to reorder challenge tasks during challenge creation. It would save much work since now the only way to do it is to delete tasks and recreate them in the right order.

**Comment by lemoness** [comment] 2016-06-04 01:34
Still an issue post API-rewrite, or can this be closed?

**Comment by Alys** [comment] 2016-06-04 02:24
Still an issue.

**Comment by habitrpguser** [comment] 2016-08-31 22:46
I just cloned a challenge, and the task order changed. So now you can't sort them when you create them, you can't sort them when you edit the challenge, and you can't rely on them staying sorted when you clone the challenge. :(

The challenge I cloned was created before the change to API v3. (I'm not sure if that makes a difference but I thought I'd mention it. I haven't tested it with newer challenges.)

**Comment by habitrpguser** [comment] 2016-09-06 13:05
I did some testing about this in the Challenge Sandbox guild. Please read the (looong) description of the challenge [:bug: Bug Test Challenge 1: Testing Various Task Order Bugs](https://habitica.com/#/options/groups/challenges/28791b0a-72a4-4f2f-b4dd-77e687e7877c) for details!

To sum things up:
- When someone creates a challenge, the tasks are saved in a different order than they are shown in when editing. The order is random (or at least unpredictable). If you try to create the same challenge twice, entering the same tasks in the same order, you will get two challenges with two different orders.
- The same happens if you clone a challenge. The tasks of the new challenge won't be in the same order as in the original challenge. If you clone the same challenge twice (both times from the same original), you will end up with two different clones with two different task orders. (I'm not sure if they still deserve the name "clone"...) The order is random (or at least unpredictable).
- The same happens if you create new tasks and delete old ones during editing. They won't be saved in the order they appear in during editing.
- There is no way to "sort" challenge tasks when creating or editing (by dragging them around or by clicking on the "push to top/bottom" arrows). There never was.

Those are definitely bugs. (Ok, the last one is rather a missing feature.) So, is there no workaround? Yes, there is! (At least it has worked so far...)
- Create a challenge with as many tasks as you need. Fill the tasks with short meaningless placeholder text. ("sdg", "bla", "."). Save.
- Edit the challenge. Don't add or delete any tasks. Instead, edit the existing tasks. They will save in the same order.

(Of course, you could always just simply number the tasks and leave it to each participant to sort them in their own Tasks page...)

Also, please don't confuse this bug with other bugs! (For example, [issue 7599 (challenge tasks are in wrong order in one's own Tasks page directly after joining, creating, or cloning)](https://github.com/HabitRPG/habitrpg/issues/7599), or [issue 7645 (when sorting tasks in one's own Tasks page, the order isn't saved properly, or changes unexpectedly)](https://github.com/HabitRPG/habitrpg/issues/7645).)

**Comment by Alys** [comment] 2017-01-21 11:31
This issue might be easier to fix now because there is code for sorting tasks in Group Plans: https://github.com/HabitRPG/habitica/pull/8358

It's possible that the code could be reused or copied for challenges. Or I might be completely wrong. :) It's probably worth a look though.

**Comment by TheHollidayInn** [comment] 2017-01-22 04:52
Yep, the code allows to order challenge tasks (and can be shared between all three). Although, there needs to be a taskOrder object on the challenge - not sure if that exists.

**Comment by lemoness** [comment] 2017-10-05 06:13
Is this still an issue?

**Comment by wildcate** [comment] 2017-10-05 08:52
I haven't done any challenge item sorting for a long while, so I can't 
actually say - sorry!

lemoness wrote:

**Comment by lemoness** [comment] 2017-10-07 01:46
I'm going to close this issue for now, but we can always open a new ticket if it happens again.

**Comment by Alys** [comment] 2018-06-28 09:46
This is definitely still an issue so I'm reopening it. Note the comments above from me and TheHollidayInn  from January 2017 about sorting. tasksOrder does exist in challenges, for example:
```
{
    "_id": "21aacfa4-3eea-4d64-9cfe-efc3c60a034d",
    ...
    "tasksOrder": {
        "rewards": [],
        "todos": [
            "d5cb42b1-e7d2-4977-b2e1-5dbfde9d6a67",
            "ce4e18cc-7c76-4342-bfd2-d08cff01325b",
            "17cb44ff-5839-4f5e-a1f2-33159fe25a8a",
            "5111b729-4eba-42f9-b74a-c6a6c0656efb"
        ],
        "dailys": [],
        "habits": []
    },
    ...
}
```

**Comment by paglias** [comment] 2018-06-28 09:50
This is about challenge tasks not keeping the same order when added to the user's list? So it's different from the issue @SabreCat reported?

**Comment by Alys** [comment] 2018-06-28 10:50
This one is about the challenge owner editing the challenge to sort the tasks on the challenges page (basically the same as #10464). https://github.com/HabitRPG/habitica/issues/7599 is for tasks keeping the same order when first added to the user's list.

**Comment by alecbrick** [comment] 2020-02-28 07:07
It looks like this isn't an issue anymore. Should it be closed?

**Comment by Alys** [comment] 2020-02-28 09:54
It is still an issue. What's supposed to happen is that the order of the tasks you see on the challenge's screen should be the same as the order of the task IDs in the challenge's `tasksOrder` object. Below is an example of that object in a challenge's document. (What seems to happen currently is that the tasks stay in a fixed order, but it's not the order they're meant to be in.)

However I've realised that the challenge's page has lost the ability for the challenge owner to reorder the tasks. They should be able to drag and drop in the same way that a user can drag and drop their own tasks. Admins (moderators and staff) should also be able to drag and drop the challenge's tasks (there's already code for challenges that gives admins the same rights at the challenge owner). Other players should not be able to drag a challenge's tasks.

I'll update the top post with this information since dragging-and-dropping should be implemented at the same time as obeying the tasksOrder object.


```
{
    "_id": "b7fbd6a2-6d5e-4f28-a81f-12f42f9cf447",
    "tasksOrder": {
        "habits": [
            "990933b0-4853-4f38-92b0-3864ce576f9e",
            "3d131996-768b-46e9-937d-993452a78df2",
            "5ca7fbf1-b7b5-498e-9c6d-85d328a50099"
        ],
        "dailys": [
            "30ef773b-292e-46e7-beb1-ecf2df66cbb3",
            "62782db7-8bbd-48e4-b0b0-2ab86a5d1031"
        ],
        "todos": [
            "85a5e240-8c64-446d-baab-db6debbabdd0",
            "71a67058-e022-497a-8319-d52584383b66"
        ],
        "rewards": [
            "2c0f8ed9-a61f-4ba4-9ad4-5f36a25db02a"
        ]
    },
    "official": false,
    "memberCount": 0,
    "prize": 0,
    "name": "My Challenge",
    .... etc ....
}
```

**Comment by Alys** [comment] 2020-02-28 09:56
Ooops, here's the example I meant to paste in, although I've noticed there's already one in an earlier comment.

```
{
    "_id": "b7fbd6a2-6d5e-4f28-a81f-12f42f9cf447",
    "tasksOrder": {
        "habits": [
            "990933b0-4853-4f38-92b0-3864ce576f9e",
            "3d131996-768b-46e9-937d-993452a78df2",
            "5ca7fbf1-b7b5-498e-9c6d-85d328a50099"
        ],
        "dailys": [
            "30ef773b-292e-46e7-beb1-ecf2df66cbb3",
            "62782db7-8bbd-48e4-b0b0-2ab86a5d1031"
        ],
        "todos": [
            "85a5e240-8c64-446d-baab-db6debbabdd0",
            "71a67058-e022-497a-8319-d52584383b66"
        ],
        "rewards": [
            "2c0f8ed9-a61f-4ba4-9ad4-5f36a25db02a"
        ]
    },
    "official": false,
    "memberCount": 0,
    "prize": 0,
    "name": "My Challenge",
    .... etc ....
}
```

**Comment by alecbrick** [comment] 2020-03-30 00:05
I've created a PR! https://github.com/HabitRPG/habitica/pull/12021

**Comment by shanaqui** [comment] 2020-05-05 19:55
Hi @alecbrick, are you still working on this one? :) If I don't hear back, I'll set this back to "help wanted" in about a week.

**Comment by shanaqui** [comment] 2020-05-12 14:42
@alecbrick I'm setting this issue back to help wanted, but if you want to pick it back up, let us know!

**Comment by Alys** [comment] 2020-05-13 00:06
I've removed some old comments that are no longer relevant and updated the top post to mention that a contributor should review the other comments here and in https://github.com/HabitRPG/habitica/pull/12021

Ideally we should collate all the comments from both sources and purge anything irrelevant to make this easier to pick up. :-/ If I can find time I might do that.

**Comment by paglias** [comment] 2020-05-13 09:00
I'm going to take over that PR, it was almost done and contains a lot of good refactoring, I'll try to finish it this or next week

**Comment by habitrpguser** [comment] 2020-11-07 22:16
I checked again today - and when cloning a challenge, the cloned challenge still has a different (apparently randomly mixed up) task order than the original challenge.
(Today I also deleted my "Bug Test Challenge 1" from 2016 that I linked to in a previous comment. Most of the detailed test description in that challenge was obsolete and useless by now.)

**Comment by shanaqui** [comment] 2020-11-24 15:11
Thanks for the update! I don't think a fix has actually been completed for this anyway, so it would be expected that things are still not working that way... is that right, @paglias?

**Comment by paglias** [comment] 2020-11-24 18:22
@habitrpguser this is still open indeed! We have a quite complete PR at https://github.com/HabitRPG/habitica/pull/12204 and if you could finish the remaining issues it would be great!

**Closed as completed** 2021-04-30 21:23 UTC
Labels: section: Challenges, priority: medium, status: issue: in progress, type: medium level coding

**Comment by habitrpguser** [comment] 2021-06-08 17:23
This bug still happens! I don't know if challenge tasks change order if a challenge is cloned once (I couldn't reproduce that), but they definitely do if a challenge is cloned and then that clone is cloned again. Please see examples:

https://habitica.com/challenges/79fabb8c-f99a-459f-bdb7-ed810f25661b

https://habitica.com/challenges/7f96108c-c086-4ae1-9fa4-7b2006bbb965

https://habitica.com/challenges/6cec332e-8ddc-46f7-afe6-f2a9cb212311

**Comment by Alys** [comment] 2021-06-09 08:54
@habitrpguser Thanks! I've logged it as a new issue here: https://github.com/HabitRPG/habitica/issues/13328
