### ISSUE TITLE
Habits, Dailies and to-dos I created are all gone

### ISSUE THREAD

**Issue by ceruleanesk** [HabitRPG/habitica#4617] opened 2015-02-03 10:57 UTC
I created several habits, dailies and to-dos along with accepting various challenges.
Yesterday I found some of the ones I created myself are gone, on habitrpg on my PC. On my iPad I could still see them at that time.
Now I also don't see them on my iPad anymore.

Other than that there are 5 habits added with UUID-like names (hex names). The program also keeps on adding "todos" and "productivity" habits since I started, but that's not a major thing.

**Comment by deilann** [comment] 2015-02-03 11:06
Have you tried clicking "Clear" by the tags? Please try this, even if you
have no tags enabled.

**Comment by ceruleanesk** [comment] 2015-02-03 12:23
Yes, pressing clear doesn't change anything.

**Comment by deilann** [comment] 2015-02-03 12:28
Can you post your UUID?

**Comment by ceruleanesk** [comment] 2015-02-03 14:08
It's d6e25f45-7100-4e99-85a3-326deb34e059

**Comment by Alys** [comment] 2015-02-03 19:40
@ceruleanesk I'm looking at your data now in the database. I can see the Habits with hex names, and I'll delete them for you as soon as I can. The "productivity" Habit will be added by an extension or other third-party tool that you have installed, so I won't delete it; the tool will just keep putting it back, because it needs it to do whatever actions it's meant to do.

It's possible that your missing tasks were never sent to the server, and so were never saved properly. It's also possible they aren't being displayed for some reason. I can see several tasks in the database, but I don't know if they're the ones you are seeing. Can you show us a screenshot of your current tasks? Or tell us the approximate descriptions of the ones that you lost? If you want to keep this information private, you can email it to alys@habitrpg.com.

**Comment by lefnire** [comment] 2015-02-03 19:45
Check for chrome console errors too, if there's a JS error on the page Angular will stop repeating the tasks on that error (say, duplicate task.id or such)

**Comment by Alys** [comment] 2015-02-03 20:00
@lefnire Interesting, thanks! 

@ceruleanesk I've deleted the Habits with hex names and also two Habits that had no names. Please let me know about all problems that still exist for you. If there are such problems, if at all possible, please use the Chrome browser and show us any errors that exist in the JavaScript Console. If you don't know how to do that, we can walk you through it (it's not hard, basically cmd-shift J or ctrl-shift J but we can give you as much information as you need!).

**Comment by Tephraa** [comment] 2015-02-04 04:05
This has happened to be as well, I just signed up so spent ages entering everything in, now some seem to be gone and some are still there (FYI I was entering them using the iPad app). Since I am not going to keep two to-do lists just in case one loses half my data, I am just wondering, is this common? Is there a way to get them back?

**Comment by Alys** [comment] 2015-02-04 10:14
@Tephram I'm not sure it's common. We have many thousands of users and we don't hear many reports of this by comparison. It can help to ensure that the app has synced with the server by dragging downwards from near the top of the screen, while you are viewing one of the task screens. When you're dragging in the right place, a spinning sync indicator appears at the very top of the screen.

**Comment by paglias** [comment] 2015-02-04 10:18
If it's on iOS then offline syncing breaks everything, apple has still to
approve pur update. So you should force close the app and the use it only
with a strong connection
Il 04/feb/2015 11:14 "Alice Harris" notifications@github.com ha scritto:

**Comment by Tephraa** [comment] 2015-02-04 10:23
K, so if I don't use on iPad I should be ok? Because I was continually syncing the whole time as suggested by Alys...however nothing ever told me that the sync hadn't worked...perhaps it should warn you then?

**Comment by phinmak** [comment] 2015-02-25 14:54
User ID: ff1039e0-ede4-49c9-9213-b83f6ea83946
Wondering if my issue is similar enough to this thread to be included here vs a new one.  Hoping that the solution isn't to just not be able to use my iPhone.

I'm one of the people that crashed the servers after finding out about you from Imgur.  I set up a new account via PC (Chrome) and set up a handful of habits, dailies, and to-dos.  I realized that I would be more involved if there was an App on my phone, so I went looking in the iPhone appstore.  I noticed that some of the reviews were quite negative including a comment that getting the app caused them to lose all of their habits/dailies, etc. ("So sad, so much potential" dated 2/14/15)  I crossed my fingers and told myself that I hadn't done much so couldn't lose much.  After logging in via my iPhone everything transferred to my phone fine (though there have been a few instances where the list of habits/dailies has needed to be refreshed regularly as there are duplicates or missing items).  But immediately after logging in on my phone I checked my PC and saw that every habit/daily/to-do was missing.  They're still there on my phone but not the PC.  I can add new tasks on the PC and they get pushed to the phone.  Sometimes these new tasks stay visible on my PC for awhile and then randomly drop out too.  Only had 24+ hours of experience so far, so can't give a great history here.  Tried to attach a screenshot of my PC here to show that my available tasks list is missing most everything.
![image](https://cloud.githubusercontent.com/assets/11194763/6372766/6eed04b4-bcd4-11e4-9258-35c59ee31cd0.png)

**Comment by crookedneighbor** [comment] 2015-02-25 15:56
@phinmak In the screenshot you provided, all the tasks that are displayed have the tag icon, so I'm guessing you just have a tag enabled. Click the clear button in the tag section above the task boxes (even if it doesn't look like a tag is enabled), and that should reveal your other tasks.

![screen shot 2015-02-25 at 9 56 15 am](https://cloud.githubusercontent.com/assets/2916945/6374130/92d3167a-bcd4-11e4-800c-93fb4099677d.png)

**Comment by phinmak** [comment] 2015-02-25 16:19
I think that did it.  Everything is popping back up.  Wonder why/how signing up my phone enabled the tag filter... Thank you very much!

**Comment by crookedneighbor** [comment] 2015-02-25 16:22
@phinmak Not sure, might have been a coincidence. Definitely going to start a new issue for making the fact that tags are enabled more visible, because this is not the first time this has happened.

**Comment by Alys** [comment] 2015-02-28 06:59
I just did a test of signing up on the Android app, creating nine tasks (three of each), and then logging in to the website on my laptop. Tag filters were not enabled. It's not a consistent bug (which unfortunately makes it harder to track down).

**Comment by LittleELK26** [comment] 2015-03-24 23:03
A similar issue:
Yesterday evening I noticed that 2 of my habits were not showing up on my HabitRPG app, when I got a chance to check this morning I found that they're also not displaying on my PC. (And continue not to on the app) I've had these two habits (a laundry and a dishes one) running successfully for at least a week so I don't know how or why they would have disappeared at some point yesterday.

My user ID is: d288ea32-3b06-41a8-988a-fe96af9dcbde

**Comment by Alys** [comment] 2015-03-25 07:58
@LittleELK26  In your account, there's definitely no laundry and dishes Habits (excluding the very new one), so the problem is not that something is hiding them. They have been deleted. I can't find out when or how, but I'm wondering if they were deleted when you were cleaning up duplicate tasks (https://github.com/HabitRPG/habitrpg/issues/4470#issuecomment-85724164). Glitches related to the duplication might have caused them to be removed.

**Comment by LittleELK26** [comment] 2015-03-25 22:07
No, @Alys they definitely hung around longer than I was cleaning up duplicates. But if there's definitely no way to get them back then I'll add them back in and format them the way I need (rather than that new one that's hanging out) Thanks!

**Comment by Alys** [comment] 2015-06-14 04:11
This issue looks like a combination of [sync errors](http://habitrpg.wikia.com/wiki/Sync_Errors), https://github.com/HabitRPG/habitrpg/issues/4466, and https://github.com/HabitRPG/habitrpg/issues/4957 so I'm closing it as a duplicate.

**Closed as completed by Alys** 2015-06-14 04:11 UTC
Labels: status: issue: needs investigation
