### ISSUE TITLE
Inappropriate class bonuses in profile modal

### ISSUE THREAD

**Issue by deilann** [HabitRPG/habitica#5135] opened 2015-05-03 19:35 UTC
Users with an even level are showing a 0.5 class bonus, when they have no equipment equipped in that stat and when they do, all the equipment is going in class bonus, instead of equipment:

![image](https://cloud.githubusercontent.com/assets/6274734/7446515/ffd95758-f18f-11e4-8ada-fd2a00c45183.png)

![image](https://cloud.githubusercontent.com/assets/6274734/7446517/20d7fd7e-f190-11e4-92c0-c86f6b104ed9.png)

Users with an odd level do not show the extra 0.5 but do get their equipment in class bonus:

![image](https://cloud.githubusercontent.com/assets/6274734/7446525/4588e840-f190-11e4-8b84-71e2ed85f8b8.png)

![image](https://cloud.githubusercontent.com/assets/6274734/7446535/5f01026c-f190-11e4-9034-eade969e5734.png)

Equipment shows up properly on the stats page:

![image](https://cloud.githubusercontent.com/assets/6274734/7446539/81a01b46-f190-11e4-9a6e-613d54d93fea.png)

But the 0.5 class bonus appears for even leveled users:

![image](https://cloud.githubusercontent.com/assets/6274734/7446542/9af84226-f190-11e4-9cfe-2952ce96bcb2.png)

This includes level 100 users:

![image](https://cloud.githubusercontent.com/assets/6274734/7446547/c1023346-f190-11e4-8cfd-eded2d1adb57.png)

But not level 102 users:

![image](https://cloud.githubusercontent.com/assets/6274734/7446552/dcc38c1a-f190-11e4-9065-3afcb4fca77f.png)

**Comment by deilann** [comment] 2015-05-03 19:37
A comment of mine from the Tavern:

I'm wondering if the skill changes included something about making stats integers, not floats, so it's rounding up the level/2 bonus to be an integer. The stats display isn't actually a proper breakdown... it's done via maths subtracting the points from what your stats are... so I'm imagining the class bonus is generated from the leftovers, and showing as .5 because of that.

This especially makes sense as after level 100, it's no longer (lvl-1)/2 level bonus, but a flat 50 bonus.

**Comment by mayajosyula** [comment] 2015-05-03 19:45
I was going to put this in the Tavern, but this is probably a better place - I think you're right, since all the stat totals show up as integers now but they weren't before the changes (you'd see 37.5, 90.5, etc. as the total).

Also, the thing you first said about equipment bonuses going into the "Class Bonus" section was true even before the skill changes (I remember thinking it was really odd, but I figured it was intended). The "Equipment" section only ever shows up on the user stats page.

**Comment by deilann** [comment] 2015-05-03 19:50
This should be relatively easy to fix. I'll post it to Aspiring Coders.

**Comment by git-afsantos** [comment] 2015-05-07 21:23
The 0.5 class bonus in the stats page, when no equipment is benefiting the stat, seems to add up alright. In your screenshot, 99 CON = 44 + 37 +17.5 + 0.5.
Should it be kept, or is the level bonus supposed to round up (in this case, 44 + 37 + 18)?

**Comment by deilann** [comment] 2015-05-07 23:33
@git-afsantos Previously, we didn't round at all.

**Comment by crookedneighbor** [comment] 2015-05-08 12:46
Closed via https://github.com/HabitRPG/habitrpg/pull/5165

**Comment by deilann** [comment] 2015-05-08 17:21
Equipment still needs to be removed from Class Bonus section.

**Comment by git-afsantos** [comment] 2015-05-08 17:29
The problem here is that, when viewing other users' profiles, the sum of equipment stats (`weapon[str]` and so on) is always amounting to zero. Since class bonuses are the leftovers of all stat contributions, the leftovers include what should be attributed to equipment.

**Comment by deilann** [comment] 2015-05-08 17:31
Yeah, I figured it'd be something like that, from what I looked at last
time I looked at that code.

**Closed as completed** 2015-07-22 22:46 UTC
Labels: good first issue
