### ISSUE TITLE
Unable to reorganize To Do's

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#2180] opened 2013-12-30 12:15 UTC
Today I noticed I'm not able to reorganize my To Do list any more. If I drag a To Do to another place in the list, all tasks scramble to seemingly random places. The other lists can be rearranged just fine.

I'm using Chrome, on Windows 7.
Errors in console:
![image](https://f.cloud.github.com/assets/3669861/1821987/1a2cc326-714c-11e3-93cc-b63fcb9ae70f.png)

**Comment by brightbold** [comment] 2013-12-30 15:36
Yeah this seems crazier than usual today. Much worse than the bug in #1616. Not sure if this bug should be closed as a dupe of that one and the older issue reopened, or if this is totally new. It behaved differently, certainly. Previously it looked like you had successfully rearranged the list until the page refreshed. Now as soon as you drop the dragged task, the list reorders into something crazy, and the previous workaround of refreshing the page immediately does not seem to work.

**Comment by lefnire** [comment] 2013-12-30 16:19
Honestly, I'm surprised To-Do ordering ever worked for anyone. This ticket should have been the case since the very first day, even Derby days. And it _is_ different from #1616, this is _just_ To-Dos.

What happens is that `user.dailys`, `user.habits`, `user.rewards` sort orders are all managed independently. However, from the beginning `user.todos` was never separated into `user.todos, user.completed`; it's all stored in `user.todos` and the completion-status filtering is handled on the client (aka, `display:none;` when listing "remaining" and this item is complete). What this means is: if you have completed To-Dos, and you re-order your Remaining To-Dos, it's going to move things around with other-task invisible sort positionings at play. ie, sort will work just fine without any completed To-Dos, it will act very weird _with_ completed To-Dos.

The solution is to break `user.todos` into `user.todos, user.completed`. However, this is going to require server downtime & a migration, new mobile app releases, and notifying our 3rd-party devs -- which is why we've put this task off.

**Closed as completed** 2013-12-30 17:20 UTC

**Comment by lefnire** [comment] 2013-12-30 17:21
I pushed a temporary fix. Will cause performance issues, we need to separate out `user.todos` to `user.todos,user.completed` as soon as we can as the real fix

**Comment by lorian** [comment] 2014-01-19 20:22
This was fixed until a couple days ago, but it's back to the seemingly-random reordering now (as seen in #1616 ) :( I try to keep my completed to-dos clear, but I have a bunch that are from challenges and thus can't be cleared. This is really unfortunate, as had gotten used to the working ordering, and was relying on it for my daily task planning. (Note that, unlike 1616, it's definitely not reordering to order of creation; it's something else).

**Comment by theglus** [comment] 2014-01-26 03:17
I had become really accustomed to, at night before going to bed, putting my To-Dos in order for what I want to complete first for the next day. This bug is really messing with my flow. I also had really gotten used to looking at the "Completed" section of To-Dos as reference before doing Daily SCRUM. Since "everything just bounces around willy-nilly," it's a real pain. I've experienced the issue in both Chrome (32.0.1700.77) and Firefox (26). I'm running OSX 10.9.1. I think there is a real need to open up this issue again. Feel free to reach out to me if you want me to further elaborate on the issue.
