### ISSUE TITLE
Challenge tasks not removed when deleting a challenge

### ISSUE THREAD

**Issue by mczuchnowski** [HabitRPG/habitica#5401] opened 2015-06-14 11:52 UTC
I deleted a challenge that I once created (I was participating in it) and now I'm left with undeletable daily task form that challenge. Can't leave the challenge, since it no longer exists.

**Comment by crookedneighbor** [comment] 2015-06-14 13:29
Duplicate of #2763. You can track the progress of the bug there as well as see a workaround for deleting the tasks.

**Closed as completed by crookedneighbor** 2015-06-14 13:29 UTC
