### ISSUE TITLE
I've been added to many guilds, can't leave any of them

### ISSUE THREAD

**Issue by CortJstr** [HabitRPG/habitica#1255] opened 2013-07-15 23:17 UTC
I've been added to about 10 guilds that I never actually joined. When I click to leave one it asks if I'm sure, takes me back to my main page, but doesn't actually remove me from the guild.

Additionally, when I try to check off a daily it will often bring up the "are the sure you want to leave this guild" pop up twice. The daily gets checked no matter which option I select.

**Comment by cgardner** [comment] 2013-07-20 04:16
I have been added to a few guilds that I didn't sign up for as well.  However, I am able to leave them.

My User ID is 111e44b5-b429-4d0c-87ed-a26422e6738e and the guild is Fanfiction Connoisseurs (5be5335e-2183-49dc-a197-1f989ddc6e88)

**Comment by CortJstr** [comment] 2013-07-21 15:38
Over the past couple days I've been able to leave the guilds. I'm not sure what changed.

**Comment by lefnire** [comment] 2013-07-23 20:06
Nothing's changed. Very strange, I'll look into this asap post angular migration

**Comment by lefnire** [comment] 2013-07-26 22:27
I think this is caused by https://github.com/lefnire/habitrpg/issues/1213 . I think what's happening is your user id is being duplicated in the members list, when you leave it removes one of those ids, but not all. So basically you'd have to leave as many times as your user id is duplicated. Don't do that for now, I'm going to fix this soon (see #1286)

**Comment by paglias** [comment] 2013-09-09 18:21
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!

**Closed as completed by paglias** 2013-09-09 18:21 UTC
