### ISSUE TITLE
Can only type 1 letter at a time in party description and leader message

### ISSUE THREAD

**Issue by startmyquest** [HabitRPG/habitica#1180] opened 2013-06-14 07:42 UTC
Same problem that was occurring with the editing of tags?

**Comment by lefnire** [comment] 2013-06-14 14:58
same problem indeed. see commit message of
https://github.com/lefnire/habitrpg/commit/268157ca246280aace22dff949367691d7db96d6
if
you're interested, I roughly know what's going on here but having trouble
working around the private path restrictions

**Comment by lefnire** [comment] 2013-06-14 15:01
dupe of #1179 , let's follow up there

**Closed as completed by lefnire** 2013-06-14 15:01 UTC
