### ISSUE TITLE
Application Error – Firefox Console

### ISSUE THREAD

**Issue by wc8** [HabitRPG/habitica#3285] opened 2014-04-15 15:07 UTC
I've been getting a lot of Application Errors lately, so I thought I'd open up the console and copy the report:

> "Given URL is not allowed by the Application configuration.: One or more of the given URLs is not allowed by the App's settings.  It must match the Website URL or Canvas URL, or the domain must be a subdomain of one of the App's domains." ping:1
> "Error: a.group is undefined
> a.chatChanged@https://beta.habitrpg.com/app-1d9e3f1e.js:23
> Qd/this.$get</i.prototype.$digest@https://beta.habitrpg.com/app-1d9e3f1e.js:7
> Qd/this.$get</i.prototype.$apply@https://beta.habitrpg.com/app-1d9e3f1e.js:7
> mf[b]</<.compile/</<@https://beta.habitrpg.com/app-1d9e3f1e.js:7
> n.event.dispatch@https://beta.habitrpg.com/app-1d9e3f1e.js:2
> n.event.add/r.handle@https://beta.habitrpg.com/app-1d9e3f1e.js:2
> " app-1d9e3f1e.js:6
> [object Object] app-1d9e3f1e.js:22
> [object Object] app-1d9e3f1e.js:22
> [object Object] app-1d9e3f1e.js:22
> [object Object] app-1d9e3f1e.js:22
> [object Object] app-1d9e3f1e.js:22
> [object Object] app-1d9e3f1e.js:22
> [object Object] app-1d9e3f1e.js:22
> [object Object] app-1d9e3f1e.js:22
> [object Object] app-1d9e3f1e.js:22
> [object Object] app-1d9e3f1e.js:22

**Comment by ghost** [comment] 2014-05-07 20:52
I have a similar error getting up everytime I check a task. It gives me gold and xp, then a red bubble pops up saying:
Please reload, "Error Internal Server Error" (see Chrome console for more details).

Console details:
"Given URL is not allowed by the Application configuration.: One or more of the given URLs is not allowed by the App's settings. It must match the Website URL or Canvas URL, or the domain must be a subdomain of one of the App's domains." ping:1

When clicking habit:
POST https://beta.habitrpg.com/api/v2/user/batch-update [HTTP/1.1 500 Internal Server Error 298ms]
[object Object] app-ebfc3b19.js:22

**Comment by deilann** [comment] 2014-05-07 20:53
@noakei That's basically a request failing to make it through to the server and save. Is it every time you check a task? Usually this can be avoided by clicking a single task and waiting for the blue bar at the top to finish before clicking the next. Clicking too fast will almost certainly cause application errors.

**Comment by lefnire** [comment] 2014-05-07 21:02
@noakei beta's having some troubles currently due to a big i18n overhaul, use prod for a bit

**Comment by ghost** [comment] 2014-05-07 21:06
@deilann that was only 1 task at a time
@lefnire thanks for the heads-up :)

**Comment by deilann** [comment] 2014-05-07 21:08
Yeah, I think it's def beta issues then @noakei. Hopefully prod works out
better for you.

**Comment by lemoness** [comment] 2014-06-04 17:31
Been getting so many application errors this morning (in Safari) that I cannot even use the Tavern :/ Reloading does not help; it just results in the Tavern screen with no messages. I've been trying to send messages for a while. It isn't working on my app either.

**Comment by lemoness** [comment] 2014-06-04 17:32
![screen shot 2014-06-04 at 10 28 40 am](https://cloud.githubusercontent.com/assets/3494081/3177277/3aa191b2-ec0e-11e3-8d31-f61ca5b1affc.png)
![screen shot 2014-06-04 at 10 29 08 am](https://cloud.githubusercontent.com/assets/3494081/3177278/3b040914-ec0e-11e3-92a8-aab6ac1e2a58.png)

**Comment by lemoness** [comment] 2014-06-04 17:35
Not just me - social media is full of complaints. What should I tell them? @lefnire @paglias

**Comment by paglias** [comment] 2014-06-04 17:37
error rate seems normal but response time is awful

2014-06-04 19:35 GMT+02:00, lemoness notifications@github.com:

> Not just me - social media is full of complaints. What should I tell them?
> @lefnire @paglias
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/HabitRPG/habitrpg/issues/3285#issuecomment-45123806

## 

Matteo Pagliazzi - paglias.net

**Comment by lemoness** [comment] 2014-06-04 17:51
Where should I direct the users who are having a lot of trouble? This ticket? A different one?

**Comment by kribbit** [comment] 2014-06-04 18:09
I'm having this error a ton, too, almost every time I sync my stuff! I also keep getting a message when I try to view my party chat: "You are either not in a party or your party is taking a while to load. You can either create one and invite friends, or if you want to join an existing party..." Even though I can clearly see my party members at the top of my screen O.o I also have to keep loading and reselecting things, like trying to add stat points or change equipment (I just switched classes). Glad I'm not the only one having this problem.

**Comment by lefnire** [comment] 2014-06-04 18:37
This should be fixed now, just restarted the server. This is usually caused by server overload by closing a very large challenge, which can only be fixed once tasks are moved from array to object (https://github.com/HabitRPG/habitrpg/issues/2301 , [progress](https://github.com/HabitRPG/habitrpg/issues/2301#issuecomment-45132401))

**Closed as completed** 2014-06-04 18:37 UTC

**Comment by wc8** [comment] 2014-06-04 21:30
I left an update in the Tavern (which will most likely be seen by people who aren't affected).
...and here I was thinking the other mods weren't active because they were busy cranking out their to-dos and dailies. ;-)
