### ISSUE TITLE
Image links in the Blurb field does not work using markdown format.

### ISSUE THREAD

**Issue by vibitect** [HabitRPG/habitica#3975] opened 2014-09-03 13:41 UTC
Example:

```
[![Link description](https://assets-cdn.github.com/images/spinners/octocat-spinner-32.gif)](https://github.com/HabitRPG/habitrpg/issues)
```

This displays an image link to the HabitRPG issues webpage.

In the blurb it displays a link to the image itself.
## Edit from admin: Just wrapped the image in a code block so you could see the syntax @adam-arold is using.

Want to back this issue? **[Place a bounty on it!](https://www.bountysource.com/issues/4189677-image-links-in-the-blurb-field-does-not-work-using-markdown-format?utm_campaign=plugin&utm_content=tracker%2F68393&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F68393&utm_medium=issues&utm_source=github).
</bountysource-plugin>

**Comment by Pfeil** [comment] 2014-12-08 09:36
Not sure if I understand you correctly (blurb?), are you talking about this?

![habit_mdissue](https://cloud.githubusercontent.com/assets/4805153/5337158/b7559cf4-7ec5-11e4-96f7-5ea338760b8f.png)

I experience this bug since the downtime last week or so.

**Comment by crookedneighbor** [comment] 2014-12-08 13:55
Possible duplicate of #1963

**Comment by SpenserJ** [comment] 2015-07-21 16:47
@adam-arold If you're still having this issue, and it _isn't_ a duplicate on #1963, please let us know. Otherwise I think this is safe to close.

**Comment by Pfeil** [comment] 2015-07-21 20:41
Well, the issue on my screenshot seems to be fixed. Works fine for me.

**Closed as completed** 2015-07-22 13:04 UTC
