### ISSUE TITLE
"undefined NaN, NaN" To-Do error on iPhone and Android apps (and website?), possibly from lack of due date

### ISSUE THREAD

**Issue by Cramertech** [HabitRPG/habitica#4250] opened 2014-11-18 01:08 UTC
When I make new sub-tasks (or a checklist) on an item, the sub-items I add seem to either go away, or when I come back to see them I find "NaN, undefined" or something somewhere.

Let's walk through this process right now:

I tap an item in my to-do list... I tap on the pencil icon to edit it.  I tap on the button to add a checklist.  I start adding items.  Then I presume you need to tap the checkmark button at the top (which btw is overlaid on top of the work "Details"....ugly if you ask me), however doing so doesn't seem to do anything.  So then I tap on the "< To-Dos" button in the top left to go back.  I'm shown my list with that item and the item shows its name and then the next line shows "undefined NaN, NaN".

Tapping on that item will now show me my checklist, but of course the "undefined NaN, NaN" is present below the title.  Also ugly, but better than other times when I go and find that my sub-items or checklists are not there.

Also I've added an item to my to-do list and it didn't show up when I loaded the website.  This brings me to my next bug or set of bugs, which is this: Yesterday I added several things, and completed some regular items.  This morning when I opened the app I see that I lost a ton of health (far more so than normal) and other stuff.  This leads me to believe that none of that was registered on the server and I basically got docked points for doing nothing at all.

My user ID is: c6d5deb2-7566-4f04-b821-f89e08a4ac75
My OS version is Apple iOS 8.1.
The browser is the latest version of Chrome: 38.0.2125.67
My HabitRPG version is the latest: 0.0.38 released Nov 13

**Comment by JenniferNeff** [comment] 2014-12-08 08:00
Got a similar thing happening with the Android app.

![app_screenshot](https://cloud.githubusercontent.com/assets/8341199/5336151/864e8bec-7e6c-11e4-9a81-0503247e9994.JPG)

To get to the screenshot attached, I created the "New To-Do" task, then opened it to edit it, and then tapped "To-Dos" on the upper left to go back to the list screen.

I might have seen a similar thing happen on the website itself, when viewed from my laptop...perhaps ONCE, but I forget what I did to trigger it.

User ID: c5183dfa-c741-43ce-935e-c6d89b41a030
Phone is a Nexus 5 running Android 5.0 (but it's been happening since long before the 5.0 update)
My browser is Chrome and was just updated today, so it would have been a little behind when I saw the one time on the website
HabitRPG app is version 0.0.40

**Comment by Alys** [comment] 2014-12-08 08:34
In the Tavern today, Vanyalosswen commented about the "undefined NaN, NaN" bug: _"That happens to me when I add To-Dos on the Android app without specifying a due date; it's referring to the nonexistent date."_

**Comment by Alys** [comment] 2014-12-08 08:38
@woohoowebs : The problems you reported with items being added on the app but not showing up on the website would be because the app changes weren't synced with the server. The app doesn't always automatically sync. Just before you move from the app to the website, it's best to force a sync on the app by dragging downwards while looking at a task screen. Then, on the website, force a sync by clicking on the sync button on the right hand corner of the website.

Loosing a lot more health than expected is probably also related to sync errors - your actions to tick off Dailies might not have been recorded. For more information about this, see [Sync Errors](http://habitrpg.wikia.com/wiki/Sync_Errors), especially the sections "How to Minimise Sync Errors" and "Completing most/all Dailies but still losing health and streaks".

**Comment by Cramertech** [comment] 2014-12-08 20:02
Okay, so no, the problems with sync'ing aren't due to my not manually
sync'ing things... I do that ALL THE TIME.  I do it because I'm attempting
to make up for a lack of intuitive auto-syncing that seems to plague the
app.  In spite of my best efforts, and even clicking the sync button on the
website, I still get that happening.  It's not how I'm doing it, it's the
app.

I agree, that perhaps the losing more health than expected problem might be
due to the sync issues, but the sync issues are not user error.  Trust me.

**Comment by Cramertech** [comment] 2014-12-08 20:04
Okay, but it then shows up on the website as well.  Why can't this be
fixed?  A non-existent date is possible without the errors if you enter it
via the website....  You make it sound like it's user error - like I'm
supposed to put in a date or something...

**Comment by Alys** [comment] 2014-12-08 20:33
@woohoowebs : For your second comment above _"Why can't this be
fixed?  A non-existent date is possible without the errors if you enter it
via the website....  You make it sound like it's user error - like I'm
supposed to put in a date or something..."_, no that wasn't what I was meaning to say. It certainly can be fixed, it's just that your report of it was the first that we saw, and I added the suggestion about it potentially being caused by a lack of date because that's useful information for any of the developers who might be working on this issue. I'm not saying that the "fix" is that you have to add dates to all your To-Dos.

For your first comment above _"problems with sync'ing aren't due to my not manually
sync'ing things... I do that ALL THE TIME."_  Thanks for explaining that! It's good to know, because that does indicate that there could be a significant problem. What I'd like to do is split this issue into two parts, one for the NaN problem (this issue since it has the screenshot), and a second one for your syncing problem. That will let both issues be worked on separately, without confusion from two sets of progress reports in the same place. Would you like me to create the second issue on your behalf, or would you prefer to? There are advantages to you doing it (you'll be automatically subscribed to updates, it will be very obvious who the issue belongs to), but I can understand that you must be very frustrated by these problems and might not want to go to the extra trouble of opening another issue - if so, I'm happy to do it for you.

**Comment by Cramertech** [comment] 2014-12-08 21:41
I'm just happy to help by reporting the issue for now.  I don't need to be
kept updated on it.  I'm sure the devs will eventually get it fixed.  If
you could open up that other issue that would be very nice.  Thanks.

**Comment by Alys** [comment] 2015-07-26 12:14
Earlier this month, we released a new, native iOS app called Habitica. It can be installed at https://itunes.apple.com/us/app/habitica/id994882113?ls=1&mt=8 . It has several improvements over the old app.

We are also working on a new, native app for Android which will also be an improvement. It's not finished yet but is close.

I'm closing this issue but if anyone has any problems with the new iOs app, there's an in-app bug report form under Menu > About > Report a Bug/Request a Feature or you can email us at mobile@habitrpg.com. There'll be similar reporting features for the new Android app.

**Closed as completed by Alys** 2015-07-26 12:14 UTC
