### ISSUE TITLE
Broken Challenge Link After Update

### ISSUE THREAD

**Issue by nelle013** [HabitRPG/habitica#7420] opened 2016-05-22 11:53 UTC
Hi, 

You may already know about this, but my challenge seems to have broke during the update. It hasn't started yet but is luanched: https://habitica.com/#/options/groups/challenges/89ce610b-6758-4aa0-b69d-310fc906014d 

I've been using the Habit and that has a broken challenge link... obviously I don't want to remove the tasks or end my challenge early. 

Thanks!

**Comment by nelle013** [comment] 2016-05-22 11:57
Also this one: https://habitica.com/#/options/groups/challenges/db6a5a3e-9743-45f9-a2cf-ba9382956e61

**Comment by Memry** [comment] 2016-05-22 14:03
I am having a similar issue with pre-update challenges.  I joined the 15K challenge after seeing it in this issue an it appears normal, but a number of challenges I am in (both my own challenges and ones created by others) have the broken challenge link.  My UUID is 2dc2722b-fdc1-4a36-894f-c22418b67a30

**Comment by lemoness** [comment] 2016-05-22 21:41
Thanks very much for letting us know about that! We're sorry about all the Challenge issues. The good news is that we are investigating the cause now. We are working on developing a fix that should solve most of these issues, but it may take some time. Meanwhile, we recommend signing up to the challenges again, which will provide a new set of tasks for you. If you'd like, you can also delete the broken Challenge tasks. 

Unfortunately, this means that your progress on the Challenge so far might not be saved, although we will do our best to restore it. We're very sorry about this! We know that it's very disappointing to possibly lose your progress, especially when you've been working hard.

We will keep you updated when we know more! Thank you for your patience.

**Comment by Memry** [comment] 2016-05-23 03:46
Unfortunately, no delete option is given for the challenges.  The broken challenge link appears, but none of the usual verbage to keep or delete tasks appears when you click on it and the delete button is not visible if you don't click on it.  For me, none of the challenges exhibiting this behavior are vital, so I am not alarmed at the error.  If after the fix the tasks are still not deletable I will let you know.

**Comment by meganstrickland** [comment] 2016-05-23 10:15
Just wanted to chime in that I'm seeing the same behavior. I have one set of challenge tasks with the "broken" challenge icons, but I cannot delete them; I have another set of the same challenge tasks with regular challenge icons, though I did not manually re-join the challenge. I am the owner of this particular challenge, and it is a party challenge. They seem to share the same challenge tag. All of the tasks are Habits.

I'm in another party challenge (which I do not own), which consists of a single Daily which is not due today (or yesterday---I believe it has not been due since the refactoring). It seems unaffected by the glitch.

If there is any other information that would be helpful, please let me know. Thank you to all the blacksmiths for your incredible work!

**Comment by khipkin** [comment] 2016-05-23 11:23
I am also having this issue.  The challenge I'm having a problem with (https://habitica.com/#/options/groups/challenges/30ddbfd8-b648-4af3-8924-0430f159ceb6) consists of a habit and a daily.  Here they are, side by side, with the habit showing what happens when you click the broken megaphone:
![image](https://cloud.githubusercontent.com/assets/5641207/15469200/f6f2409e-20e8-11e6-95c7-db1dd90c2dda.png)

If I go to the challenges page and display only challenges that I'm participating in, the challenge is still there:
![image](https://cloud.githubusercontent.com/assets/5641207/15469265/79cb03d4-20e9-11e6-8bb2-69e4aed06bcd.png)

**Comment by nelle013** [comment] 2016-05-23 12:09
In the experience I had it appears to be with challenges that are launched
but not started yet. The one I was participating in was easy enough to fix
(leave and rejoin), but the Lessen Screen/TV Time is one I created and I'm
not sure how to deal with that.

**Comment by Alys** [comment] 2016-05-23 13:48
Another report from the Tavern from Kait (939bb164-2e00-4dac-810d-05268b03657d):

I know people have posted about challenge tasks incorrectly appearing with the "broken challenge link," but either I missed something or this is different than what other people have experienced! In addition to the regular tasks with the broken challenge link, I have all the challenge tasks appearing in yellow--as though I had just rejoined the challenge. (The dailies are even at the bottom of my list rather than where I placed them.) Which tasks should I check off?
The really odd thing is that I checked off the challenge tasks yesterday and didn't notice a problem... Oh, and this is the Daily Reading Goal Tavern Challenge.

**Comment by kaitmiller** [comment] 2016-05-27 00:51
Hello! This is Kait!

Since this bug hasn't been squished yet, and I still had duplicate challenge tasks, I decided to leave and re-join the challenge. I found that I had to click "Leave -> Remove tasks" twice, as though I really was in the challenge twice.

After that I was able to re-join normally (and then I left immediately because I'd already checked off the tasks for the day--I'll re-join and stay in the morning).

I thought that might be useful information--hope it helps!

**Comment by crookedneighbor** [comment] 2016-05-29 03:47
Finally made some headway on this. See https://github.com/HabitRPG/habitrpg/pull/7532

**Comment by nelle013** [comment] 2016-05-29 22:28
Good luck Blade Barringer!

**Comment by crookedneighbor** [comment] 2016-05-30 19:08
Okay, this _should_ be fixed now so I'm closing this. If you are still having issues, please comment back here with your user id and the link to the challenges that are not working for you.

**Closed as completed by crookedneighbor** 2016-05-30 19:08 UTC

**Comment by Memry** [comment] 2016-05-31 13:34
I don't know if this is part of the same issue, but I closed a challenge yesterday or the day before and today I received the typical broken challenge link info.  I asked it to "keep tasks" and got this:

![image](https://cloud.githubusercontent.com/assets/7385423/15675648/c08a87ea-26f7-11e6-91c6-649362d44f60.png)

I tried twice and it gave me the same message the second time.  

When I asked it to remove tasks it was fine. (But now the challenge task is gone, so I cannot test it any further.)

UUID: e495bd8b-f2f1-48e8-8f5f-9a52710999cf

**Comment by crookedneighbor** [comment] 2016-05-31 13:50
@Memry this was caused by the migration and was this issue: https://github.com/HabitRPG/habitrpg/issues/7546#issuecomment-222662772

If you're still having problems, please chime in on this or that issue.

**Comment by paglias** [comment] 2016-05-31 13:54
@crookedneighbor what @Memry is reporting is being unable to keep tasks when unlinking them. Unfortunately it's still an issue because https://github.com/HabitRPG/habitrpg/blob/develop/website/server/controllers/api-v3/tasks.js#L875 causes validation to fail. I've opened an issue in the Mongoose repo but haven't received a response yet https://github.com/Automattic/mongoose/issues/4182

**Comment by crookedneighbor** [comment] 2016-05-31 13:56
:+1:

**Comment by writeblankspace** [comment] 2023-02-02 12:22
no idea where i could get the challenge link, but @writeblankspace and I can't delete a challenge 
![image](https://user-images.githubusercontent.com/75297066/216323648-c6bd2d47-09ff-4d5b-83a5-005a0e55dd9e.png)
