### ISSUE TITLE
No challenges yet?

### ISSUE THREAD

**Issue by lawlietbeyond13** [HabitRPG/habitica#5658] opened 2015-07-23 01:12 UTC
I put in a couple challenges for my guild and nothing pops up on the guild screen.

**Comment by SpenserJ** [comment] 2015-07-23 02:25
@lawlietbeyond13 Can you post both your user ID (First box on https://habitrpg.com/#/options/settings/api) and Guild ID (top left of your guild page) so that the developers can look this up?

**Comment by lawlietbeyond13** [comment] 2015-07-23 19:03
User id 9bfeb5bd-5024-41b2-87f7-932319a63f41 guild Id ac98df68-90fe-4f47-b00b-42a0b136d1c8

**Comment by Alys** [comment] 2015-07-24 13:18
I can confirm there's no challenges in that guild.

@lawlietbeyond13 Did you create the challenges in another guild? Please go to Social -> Challenges and use the buttons in the left-hand column to filter the view to show only challenges that you created (that's the "Owned" option). Do you see your challenges now? 

If you do, you can look at each one to see what guild or party it's in. If it's in the wrong place, you can click on the "clone" button to make a new copy of it, and change the guild to the correct one. You can then go back to the original challenge and click "end challenge". If you set a gem prize for the challenge, choose yourself as the winner - that will give the gem(s) back to you. If there's no gem prize, you can just delete it.

Let us know if this doesn't help.

**Comment by lawlietbeyond13** [comment] 2015-07-24 19:49
It says it's under my guild I'm pretty sure but I probably did something wrong I'll double check everything and remake the challenge just in case
I'll get back to you when I get the time to get on.

**Comment by lawlietbeyond13** [comment] 2015-07-25 02:10
Yes, I believe they should be there. As you can see in the picture its there.:(
![untitled](https://cloud.githubusercontent.com/assets/13460023/8887460/4b977a50-3248-11e5-9232-0068d77bd4f1.png)

**Comment by Alys** [comment] 2015-07-25 02:26
@lawlietbeyond13 Please click on each challenge in turn and then copy the URL and paste it here. You don't need to specify which challenge belongs to which URL - I just need the three URLs. They should have a string of random characters in them, like this:
https://habitrpg.com/#/options/groups/challenges/8b63cb69-8962-4a17-a506-9c3e4855616f

**Comment by lawlietbeyond13** [comment] 2015-07-25 03:58
I didn't think they'd be three separate strings like that, thought it'd
only be one.
https://habitrpg.com/#/options/groups/challenges/d18d049b-fe70-4933-9e30-27c2e74aed8a
https://habitrpg.com/#/options/groups/challenges/ea9fef1d-bbae-44c3-8e2f-fb709559a326

https://habitrpg.com/#/options/groups/challenges/97da2ec1-dc77-41e3-8de6-ea7df0ada533

**Comment by Alys** [comment] 2015-07-25 04:11
Those challenges all belong to your party, not to the guild with the ID ac98df68-90fe-4f47-b00b-42a0b136d1c8. That guild and your party both have the same name, so it will be difficult to tell the difference between them when you are creating or viewing challenges. You're the leader of both the guild and the party, so you can, if you wish, edit one of the to give it a slightly different name.

If you want to move the challenges from the party to the guild, see the advice in my earlier comment.

I'm going to close this now since there isn't a bug, but you're welcome to comment here if you have questions. You might also like to use the HabitRPG Help menu's Ask a Question option if you'd like advice about editing the guild/party or cloning the challenge. It's visited by many experienced users who can give you answers to almost any question about the site.

**Closed as completed by Alys** 2015-07-25 04:11 UTC

**Comment by lawlietbeyond13** [comment] 2015-07-25 13:42
Thank you to didn't even know I could do one for my party
