### ISSUE TITLE
Drop down lists for header bar don't disappear when clicking off side or moving into a different section

### ISSUE THREAD

**Issue by Rbrinkley** [HabitRPG/habitica#5090] opened 2015-04-26 02:47 UTC
Hello! I noticed this while I was browsing the header bar. Whenever you open up one of the tab lists and the list drops down, the only way to get the list put away is to either click on one of the items in the list or click on the lined portion that you had to click in the beginning to open the list.

If you click outside of the list, the list stays open and even if you say click on the button that opens up the tavern or party chat the list will still be open.

I have a video documenting the process. Sorry for the absoulutely horrible quality, I need a better screen capturing software. Sorry about having to download the file. I don't know where I could be able to share the video without having to download it. (If anyone has one please feel free to tell me so I can make showing the video less of a hassle for others. I would greatly appreciate it.) The file is only 4 seconds long and 62.5 mbs and you can delete it afterwards. Sorry about that.

http://www.filedropper.com/video2_4

(Notice I start out on the tavern tab and then I move onto the challenges tab and the drop down list is still present. I also click enough that the highlighted portion appears.)

I am not sure if this is intentional or not but I just wanted to point it out.

User ID:6f14571c-f2e9-4446-8e4e-591a7a3a42eb

**Comment by Alys** [comment] 2015-04-26 02:51
This is a duplicate of this issue: https://github.com/HabitRPG/habitrpg/issues/3783 so I'm going to close this one now but if you want to follow the progress of the fix, you can subscribe to notifications using the button in the right-hand column of that issue.

**Closed as completed by Alys** 2015-04-26 02:51 UTC

**Comment by Rbrinkley** [comment] 2015-04-26 02:59
Will do. Thanks for the info.
