### ISSUE TITLE
singleCompletion Group Plan Dailies will have sudden behaviour change when PR 11390 goes live

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#11236] opened 2019-06-18 07:56 UTC
I'm putting this here for discussion, and so that (if necessary) we can link players to it if they have questions/bug reports about this in future.

Any Group Plan Dailies created since commit 1135ab946e went live (some time after 2019-04-29) probably have their `sharedCompletion` attribute set to `singleCompletion`. Single completion isn't yet implemented for Dailies so the Dailies will currently be behaving (I think) as if they were set to `recurringCompletion`.

However when https://github.com/HabitRPG/habitica/pull/11390 goes live, if I understand correctly, the behaviour of those Dailies will suddenly change to single completion.
I.e., all assigned members who have been used to completing a Group Plan Daily every time it's due will find that only one of the members can complete it each day.

If that is what will happen, then I think it's likely to cause confusion so it might be worth describing this change in a Bailey when the change goes live.

However instead of that, maybe it's worth considering doing a migration at the time that the PR goes live to adjust all existing Group Plan Dailies to switch them to `recurringCompletion` so that they keep having the same behaviour that the group members are used to.
There's definitely a solid use case for `singleCompletion` Dailies and it's great that they'll exist, but it might not the best option to set automatically on Dailies that were created before the feature was released.
There would certainly be cases in the past where a group leader has created Dailies hoping that they would use a single completion mechanism, but I think it's pretty likely that the leader would have deleted those Dailies when they realised that they didn't work that way. I think there's a good chance that most/all current Group Plan Dailies are meant to use `recurringCompletion`, and so any of those Dailies that automatically change to use `singleCompletion` might appear to be buggy from the group members' point of view.

FYI @SabreCat 
FYI @MeanderingCode although this shouldn't affect anything you're doing in your PR. You might be able to comment though if I'm wrong about any of the technical details. :)

**Comment by MeanderingCode** [comment] 2019-06-21 15:43
Yes, I imagine that `singleCompletion` was default for all tasks simply for the convenience of the fact that only Todos had any kind of `sharedCompletion` behaviour (and UI, as the Todos edit modal is the only one which showed the shared completion UI).

I think you are right in that the expected default behaviour for Dailies would be that they are "not shared", that they should be treated as individual daily tasks for all assigned users. I will add code that sets this default when creating a new Daily (though I think `singleCompletion` makes sense as default for Todos, as it is now).

Regarding the change to existing tasks, I believe the best course of action would be a database query to update existing tasks. Once testing on #11179 is satisfied, before it is merged and deployed live, it would be simple to run a mongo query like the following:

```
db.users.update(
  {
    "group.id": {$exists: true},
    type: "daily"
  },
  {
    $set: {"group.sharedCompletion": "recurrningCompletion"}
  },
  {
    multi: true
  }
)
```

Running this migration would change all group "master tasks" of `type: daily` and their linked tasks to `sharedCompletion: recurringCompletion`, which preserves the existing and expected behaviour.

**Comment by MeanderingCode** [comment] 2019-07-09 19:04
On looking at this code and thinking about it, I do not feel it is necessary or helpful to change this.

Since Group Dailies have not had Shared Completion features, the modal did not show these options and the created task defaulted to `singleCompletion`, as you are pointing out. When #11179 goes live, the options will be shown and it will be available as a choice when creating Shared Dailies. Adding code to change the default is unnecessary, though time will tell if there is a UX issue (the "tyranny of the default", and all that).

This will still required the migration I outline above in order to preserve behaviour of existing Group Dailies.

**Comment by Alys** [comment] 2019-07-10 11:21
@MeanderingCode I agree! I might not have been clear in my original post here. I'm not concerned about the default for new Dailies created in the future; my only concern is that the behaviour of the existing Dailies shouldn't change.

**Comment by SabreCat** [comment] 2022-02-04 16:42
A ton of Group Plan (to be renamed "Team") features won't work the same way after the coming rewrite--in fact, "shared completion" as currently implemented isn't really going to be a thing, in this iteration. Closing this ticket

**Closed as completed by SabreCat** 2022-02-04 16:42 UTC
Labels: status: issue: needs investigation, section: Group Plans, status: issue: on hold - needs design
