### ISSUE TITLE
Unable to allocate attribute point (negative attribute points)

### ISSUE THREAD

**Issue by Tessarabella** [HabitRPG/habitica#4385] opened 2014-12-17 00:24 UTC
I just leveled up and 1)was given three attribute points, and 2)am unable to allocate any of them.  I press the + and nothing happens.  I've tried refreshing (multiple times) as well as logging off and logging back on.  The problem remains.
##

**Comment by Alys** [comment] 2014-12-17 00:27
Please tell us your User ID. You can see instructions for finding it a HabitRPG's [Help -> Report a Bug](https://github.com/HabitRPG/habitrpg/issues/2760) menu item (point 5 on that page). Please also report the OS etc from point 6.

**Comment by Tessarabella** [comment] 2014-12-17 00:36
Right.  Sorry about that.  I was looking at those instructions earlier, but then forgot about them.  My userid is 
82e1c22b-c151-45bb-af3c-c9945ba52da8

I'm using safari and the latest version of Apple's OS (I think it's Maverick)

**Comment by Alys** [comment] 2014-12-17 00:54
Do you have Chrome available? It would be interesting to see if the same problem happens there (Chrome is a more standard browser than Safari and has better error reporting). If you are able to try Chrome and still can't allocate attribute points, could you tell us if the Chrome JavaScript console has any error messages? We can talk you through how to check that if you haven't used it before.

**Comment by crookedneighbor** [comment] 2014-12-17 01:04
[Here's a download link for Google Chrome.](https://www.google.com/intl/en/chrome/browser/desktop/index.html)

When on the HabitRPG site while using Chrome, press `cmd + option + j`, that should bring up the console. Take a screenshot by pressing `cmd + shift + 3`, it'll save a screenshot to your desktop. Just drag that screenshot onto the message box in Github on a computer (won't work to try and upload a screenshot on the mobile site).

**Comment by Tessarabella** [comment] 2014-12-17 01:43
I already have chrome, so it was easy to try, however it didn't resolve the problem.

![screen shot 2014-12-16 at 6 40 54 pm](https://cloud.githubusercontent.com/assets/10214752/5465358/4d20c338-8553-11e4-998b-f825f0cc4452.png)

**Comment by Alys** [comment] 2014-12-17 01:48
Please go to User -> Stats. There you'll see options in the middle column for assigning the points to one (or more) of the four attributes. Does that help?

The + button in the navigation bar is meant to drop down a menu of notifications, one of which should take you to the same place as User -> Stats.

**Comment by Tessarabella** [comment] 2014-12-17 01:51
Unfortunately, that doesn't help.  The + button I was pressing was the one next to the attribute I wanted to increase (intelligence).  No matter how many  times I clicked it, nothing happened.  I even tried other attributes; same result.

**Comment by Alys** [comment] 2014-12-17 01:53
Please go back to the User -> Stats page, open the Console again if it's not still open, reload the page (wait until fully loaded), take a screenshot of the console contents, then click the Intelligence plus button once only, and take another screenshot.

**Comment by Tessarabella** [comment] 2014-12-17 01:58
I hope this is right (I'm not sure how to take a screenshot of the console only).

![screen shot 2014-12-16 at 6 55 45 pm](https://cloud.githubusercontent.com/assets/10214752/5465456/5467e958-8555-11e4-81d5-74153a2dae21.png)

![screen shot 2014-12-16 at 6 56 33 pm](https://cloud.githubusercontent.com/assets/10214752/5465465/6723c60c-8555-11e4-9ca3-9de2f0e590e5.png)

**Comment by Alys** [comment] 2014-12-17 02:06
No, that's good. The whole screen is actually what I wanted, I just wrote that badly. :)

The problem is that you actually have negative 3 attribute points (-3), not three new points to allocate. This can happen if you go down three levels, for example by using Fix Character Values (FCV) to reduce your level, or possibly due to death (although death usually handles this correctly). Can you remember if you've used FCV recently to reduce your level?

The problem should fix itself after you have gained another three levels or four. At the moment you have more points assigned than you "should" have but it will balance out when your level catches up to your number of points.

**Comment by crookedneighbor** [comment] 2014-12-17 02:07
@Alys Do you think we should set it to hide plus buttons and the number of attribute points to allocate if the number is negative?

**Comment by Alys** [comment] 2014-12-17 02:20
Probably better to stop it going negative (handle level reduction in FCV better; make sure death isn't buggy). If we hide the symptoms of negative points, we won't notice bugs that cause it. Disagreements welcome though.

**Comment by Tessarabella** [comment] 2014-12-17 02:42
Hmmm, I haven't used fix character values recently, or died since using the most recent orb or rebirth.  However, it's possible that upon reaching level 10, I was given more attribute points than I should have.  At least the mystery is solved.

**Comment by okuden** [comment] 2015-01-09 05:05
User ID f1932044-339a-409c-ab05-77e0dc4ddfb7
OS X Yosemite (Version 10.10.1)
Using site on Chrome and Firefox

After switching my character back to rogue, all but 2 points allocated to Perception vanished, and I have 0 points to distribute. I should have 37 total points in Perception. Here's a screenshot:

![screen shot 2015-01-09 at 6 04 16 am](https://cloud.githubusercontent.com/assets/10459249/5675699/52004520-97c5-11e4-8ee0-867bb36307a7.png)

**Comment by Alys** [comment] 2015-01-09 05:14
@okuden  Can you tell us the exact sequence of events? For example, you selected Rogue, then did your attributes appear immediately as they do now, or were you able to assign some points and then the others disappeared? Did you use Fix Character Values to make any changes at all, at any point shortly before, during, or after you changed to Rogue?

The problem is confirmed from the database:

```
{
    "_id" : "f1932044-339a-409c-ab05-77e0dc4ddfb7",
    "stats" : {
        "buffs" : {
            "str" : 0,
            "int" : 0,
            "per" : 0,
            "con" : 0,
            "stealth" : 0,
            "streaks" : false
        },
        "class" : "rogue",
        "con" : 0,
        "exp" : 884.2665288865334,
        "gp" : 918.0144177189849,
        "hp" : 50,
        "int" : 0,
        "lvl" : 90,
        "mp" : 11.596700000000013,
        "per" : 2,
        "points" : 0,
        "str" : 53,
        "training" : {
            "con" : 0,
            "str" : 0,
            "per" : 0,
            "int" : 0
        }
    }
}
```

**Comment by okuden** [comment] 2015-01-09 05:27
I changed from Mage to Rogue, and was immediately able to distribute all of my points. After about 24 hours, I visited the website again and the point amount on Perception had shifted to 0. At that time, I had 2 points free to distribute, and Strength was unaffected. I put the two points in Perception and waited another 48 hours before reporting the bug here.

I didn't use Fix Character Values.

**Comment by Alys** [comment] 2015-01-09 05:40
@okuden Well that's just **weird**. In that 24 hour period, were you using the mobile app? Android or iOS? Did you notice any odd behaviour in the app even if it might not seem related?

Do any devs reading this have any idea what could cause that?

@okuden I've fixed your account so you should have the correct attributes now. Resync the stats page to see them. Let me know if it's not right.

**Comment by okuden** [comment] 2015-01-09 05:48
I don't have the app, so this was on Chrome.

Thanks for fixing it! I resynced the page, and it looks like everything is fine now.

**Comment by Alys** [comment] 2015-04-04 23:18
I've made a partial fix at https://github.com/HabitRPG/habitrpg/commit/e134c36ca2a358f83f56ba53540d7582bf976155

When you level up, it now checks to see if your unallocated attribute points are negative and if so, sets them to zero. This means that you won't get a persistent notification stating that you have negative points to allocate. 

**There's a TODO comment in the code to remind us to also de-allocate assigned points until the number of assigned points are equal to the current level.**

Ideally, we'd fix this problem at the point at which it occurs but I think there might be a few such points (Fix Character Values when you reduce a level; Death if something goes wrong with the points reduction code there; sync errors or similar when allocating points resulting in more than you have being allocated; random weirdness). Fixing it at the time that you next level up catches all cases and allows the problem to persist for only a short time.

I'm leaving this open until we have code that  de-allocates assigned points until the number of assigned points are equal to the current level.

**Comment by Alys** [comment] 2016-01-09 14:05
I'm closing this in favour of [Issue #6482: incorrect attribute / stats points from various causes - need generic function to do allocation / deallocation](https://github.com/HabitRPG/habitrpg/issues/6482)

**Closed as completed by Alys** 2016-01-09 14:05 UTC
