### ISSUE TITLE
Dying

### ISSUE THREAD

**Issue by Nikki13S** [HabitRPG/habitica#3482] opened 2014-05-18 01:17 UTC
Hi! I know that dying is a part of the game if Dailies are not completed and life is drained to zero but there have been multiple times where I have died for no reason. The most recent occurrence was today, when I turned on my computer this morning I had full health, so I crossed off a couple of my Dailies and continued with my day, now well into the afternoon I come back to check off a few more of my Dailies and it says that I died. Yes the Party I'm currently in is in a quest but checking through the chat area where it also shows how much damage is given / received, the received damage is always 0.0. Dying has also occurred even if I completed all/ most of my Dailies ( I have 13 and the most I have not completed since this has begun is 2).

**Comment by deilann** [comment] 2014-05-18 03:23
Are you making sure to refresh the party page? Usually, you have to fetch
the new messagse for the party area to see  what happened.

**Comment by Nikki13S** [comment] 2014-05-18 03:46
I restart my computer every morning and refresh often to make sure that I do not miss any conversations or notifications so that is not the issue.

**Comment by deilann** [comment] 2014-05-18 03:49
No, I mean specifically when you check the party page. Are you refreshing
then?

Restarting in the morning and refreshing often doesn't mean you'll
necessarily see the latest info on the party page. You need to refresh the
party page immediately after getting the mystery damage. Refreshing any
other page is not going to do you any good.

**Comment by Nikki13S** [comment] 2014-05-18 04:44
I press the sync button or refresh button yes. Even to make sure that it was not the quest that killed me I refreshed multiple times at looked at the damage receive and again it was 0.0. Something is wrong because even if there was some damage it would not kill me with full health.

**Comment by deilann** [comment] 2014-05-18 04:48
I just want to make absolutely sure that you are not pressing the general
sync button on the toolbar but the "fetch new messages" button on the party
page or refreshing the actual party page.

This is a problem with the party page itself.

So you are refreshing the party page?

It's not that I disbelieve you; it's that there's a problem with fetching
messages in parties and I want to rule that out absolutely.

**Comment by Nikki13S** [comment] 2014-05-18 04:57
I understand that you want to be thorough. I have used the normal browser refresh, the HabitRpg "sync", and even closed the tab and reopened it from a new one and each time I look at the damage received it still hasn't changed. It also seems that some other members in the party I am a part of are also dying even though they have full health (this is just an assumption from some of their posts and I can take a picture if you would like to see them).

**Comment by deilann** [comment] 2014-05-18 05:02
Interesting. So, just want to make sure this is all correct:

You are doing a boss quest. But party members are not dealing damage any
time around when the damage is reported.

You're receiving the damage in the middle of the day, after you've already
clicked things off during your day, so it's clearly not triggering cron.

Your party members are reporting the same.

This shouldn't cause it, but are any of your party members not
participating in the quest? It almost sounds as if for some reason, quest
damage is going through, but not being reported.

**Comment by Nikki13S** [comment] 2014-05-18 05:21
Yes we are doing the Spirit of Spring quest but around the time I died people were dealing damage but the White Stag was not "hitting" back (he was not dealing any damage but the Party was).

I never got any messages (those little bubbles that will tell you if you lost health or gained XP etc.). I am not sure what cron is so I am not sure.

That is the way it sounds,

As far as I know I believe some of the lower level players did not accept the Quest invitation and therefore not participating. Is that what you meant?

**Comment by deilann** [comment] 2014-05-18 05:27
That is what I mean. I'm wondering if they're not "participating" but still
dealing damage for some reason. So the damage isn't displaying in the chat.

(In case you didn't know, you can go to Settings > Site > Fix Character
Values to set your stats the way they should be, in case of glitch death,
like this. Do let your party members know as well!)

How close are you to defeating the Ghost Stag? It'd be good to know if this
continues after this quest finishes.

(Also, cron is your day turnover. So when your dailies get unchecked, you
deal damage, and you take damage the first time you sign in after your
custom day start.)

**Comment by Nikki13S** [comment] 2014-05-18 05:58
So far those not participating have not mentioned dying, but they may also be inactive players (not a 100% sure but they never talk or level up).

Oh thanks for telling me, I was not aware Habit had this (it is a good back up plan in case stuff like this happens) and I will tell my fellow party members.

So far we are 462/1200 as of a second ago .

**Comment by deilann** [comment] 2014-05-18 06:07
They might not even be taking damage, just dealing damage, if something is
firing wrong. But that's just me guessing. I'm really not sure what's going
on here.

It sounds like it should be related to the quest because it's happening
midday and your party members are reporting the same.

If you post your UUID (You can find this in Settings > API) NOT your API
Token, which you should never share, and your party's GroupID, someone with
database access (if they have time) can peer in and try to figure something
out.

**Comment by Nikki13S** [comment] 2014-05-18 06:24
I think  it might be related to the quest as well because none of this has happened before we started it (we have completed the Quest once before). How do I send the UUID and GroupID to someoe with database access? Just through Contact Us?

**Comment by Alys** [comment] 2014-05-18 08:25
Nikki13S, you can post your UUID and GroupID here. It's safe to do that. Just don't include your API Token, as deilann said.

**Comment by Alys** [comment] 2014-08-12 01:43
I'm closing this because we can't do anything without the UUID and GroupID. It can be reopened if the issue is still happening but we'll need that information before we can help.

**Closed as completed by Alys** 2014-08-12 01:43 UTC
