### ISSUE TITLE
Level suddenly dropped by 38

### ISSUE THREAD

**Issue by thespooniest** [HabitRPG/habitica#6185] opened 2015-11-05 04:09 UTC
At about 11:00PM EST on November 4, 2015, my wide noticed that my level had suddenly dropped from 81 to 43. This probably occurred between 12:00PM and that time. I still have my gold, levels, and experience, so I don't think I died (and I'm sure I didn't die 38 times). But my stats, not cou ting allocated points, are what I would expect for a Level 43 character. Despite that, though, all 81 of my stat points are still allocated, this shows up on both my wife's machine (IE/Windows) and my tablet (Chrome/Android).

My user ID is d0d52894-f35b-4a05-9472-07ff8f327032

**Comment by Alys** [comment] 2015-11-05 08:42
I've confirmed from a recent database backup that your level was definitely 81 (sorry about that - I wasn't doubting you, we just need to confirm things like that when really odd errors happen).

You can use Settings -> Site -> [Fix Character Values](http://habitica.wikia.com/wiki/Fix_Character_Values) (FCV) to restore your level.

I don't suppose you were using FCV over the past day for any kind of change, were you? If so, it might be possible that your level was changed inadvertently. The numerical fields in that form allow the number to be changed if a mouse or trackpad is scrolled while focus is on the field, so if you were changing something else in the form, and then focus was dropped into that field, and then you scrolled down the page, the level would have changed and you might not have noticed.

If that's not possible, then I'm afraid I'm out of ideas for the moment.  We do sometimes see sudden changes in stats, possibly due to local storage pushing a lot of actions at once to the server, but I haven't seen a report of only the level changing before, so I can't yet explain this.

I'm very sorry about the inconvenience!

**Comment by paglias** [comment] 2016-06-01 09:34
Should be fixed, reopen if it happens again

**Closed as completed by paglias** 2016-06-01 09:34 UTC
